### ISSUE TITLE
Setup Sugardough base

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#1]
https://github.com/mozilla/sugardough/

Also we should think about generating/serving the client through node or something, Just to keep the client as simple/decoupled as possible.

**Comment by lmorchard** [comment]
Resolved in #10 and #40

**Comment by lmorchard** [comment]
# GitHub Pages Deployment
Pull Request: https://lmorchard.github.io/photon-components-web/pull/1/index.html
Branch: https://lmorchard.github.io/photon-components-web/branches/lmorchard-patch-1
Commit: https://lmorchard.github.io/photon-components-web/848974745892dd58b07cc268af6ec642bd0f26ed/
https://lmorchard.github.io/photon-components-web/848974745892dd58b07cc268af6ec642bd0f26ed//dist.zip
