### ISSUE TITLE
Extract Docker advice from README into a separate file

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#100]
README.md is starting to look kinda neckbeardy.

Maybe we should extract our collective Docker wisdom into a separate file.

**Comment by pdehaan** [comment]
How about adding a CONTRIBUTING.md file?

It has the added benefit of being linked in a big yellow box when a user goes to submit a new issue:

![new_issue_ _mozilla_fxa-content-server](https://cloud.githubusercontent.com/assets/557895/10152478/56a7580a-6607-11e5-9b66-75c0b108b305.png)
&mdash; via https://github.com/mozilla/fxa-content-server/issues/new

We could move all the ["Development Setup"](https://github.com/mozilla/idea-town#development-setup) stuff there, as well as any Git commit conventions, etc.

That'd pretty much reduce the README.md file to:
- a logo + brief intro
- Repositories
- More Information

**Comment by pdehaan** [comment]
Counter proposal is to use the GitHub wiki for random "Docker Tips". Still easily accessible for those that need additional help, but doesn't put a bunch of files in the main repo.

**Comment by jaredhirsch** [comment]
@pdehaan I find the github wiki oddly hard to use: I never remember files are in there until I click the wiki button. There's no way to see, without clicking that button, if there even are files in the wiki.

So I'm all about that CONTRIBUTING.md file. Are you up for adding it?

Ideally that file would also contain the git-related contributor decisions we documented in this metabug: https://github.com/mozilla/idea-town-meta/issues/5

Finally, we merged the `/bin/docker-build.sh` file recently, which should probably get mentioned in the README (and maybe the CONTRIBUTING file too) as the nuclear option: blows away all caches, takes f-o-r-e-v-e-r to run, but fixes mysterious caching errors with the client-build image. Kind of a last resort thing, or a first resort if you're just trying a first build.

It would be super duper awesome if you could take a swing at this, I'd merge basically anything that makes our docs better :-)
