### ISSUE TITLE
Correct grammatical errors in survey questions

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1000]
e.g., should be “neither”/”nor”

**Comment by johngruen** [comment]
@robhudson sharonbautista

**Comment by johngruen** [comment]
@sharonbautista

**Comment by sharonbautista** [comment]
Turns out I don't have access to the TxP surveys. I reached out to Rob Rayborn last week and just followed up again. As soon as I get admin access, I can make the changes.

**Comment by ghost** [comment]
Fixed, sorry for the late movement was out of town then sick, but still way too slow here.

Working with Sharon RE: access (SG shows her account, but might need to regenerate email)
