### ISSUE TITLE
Highlight bold portions of the TOU

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1010]
This is a follow on from #1005 and https://bugzilla.mozilla.org/show_bug.cgi?id=1281242

We should eventually restyle the bold text in the ToU to match the following: 

<img width="1077" alt="highlight-copy" src="https://cloud.githubusercontent.com/assets/3323249/16263718/1db2b700-3876-11e6-8ab3-38e2358a486c.png">

**Comment by pdehaan** [comment]
@johngruen what color/padding is that? I can probably sneak this into my current PR.

**Comment by pdehaan** [comment]
#1005 was merged, but should be easy enough to tweak the two paragraphs with a nested `<div class="legal">` tag and tweak the CSS.

``` diff
 const Remarkable = require('remarkable');
-const md = new Remarkable();
+const md = new Remarkable({
+  html: true,
+  linkify: true,
+  breaks: true
+});
```

Probably easier than trying to auto-assign an id to the heading or `<li>` tag and then style the nested `<p>` tags.
