### ISSUE TITLE
Can disable testpilot and continue using other add-ons

### ISSUE THREAD

**Issue by ericawright** [mozilla/testpilot#1011]
Clicking `disable` on about:addons will only disable Testpilot, other add-ons continue to work

On `uninstall` other add-ons are removed.

**Comment by meandavejustice** [comment]
@johngruen guessing here the move would be to just disable all experiments as well. At this point if the user visits the site they will be prompted to install the addon again, do we want any special handling in this case?

**Comment by johngruen** [comment]
@meandavejustice yeah, this is kind of a bad edge case where upstream behavior leaks into Test Pilot....will think about it. I might ping you later today to figure out what's possible here.

**Comment by johngruen** [comment]
I sort of feel like this isn't a thing anymore. will confirm in a bit

**Comment by SoftVision-PaulOiegas** [comment]
Just an opinion. I think this is the right flow. Some users maybe just want to disable Test Pilot so they won't get any push notifications or something, but keep using the other experiments. I feel like we would be forcing the user in a way if we consider this. 
Indeed, the uninstall flow was implemented like this, but there has more sense...

**Comment by chuckharmston** [comment]
@SoftVision-PaulOiegas The experiments have some technical dependencies on Test Pilot for metrics and other things.

**Comment by johngruen** [comment]
Lets just uninstall all the experiments if a user disables Test Pilot

**Comment by ghost** [comment]
jgruen says disabling is ok too, whatever is easiest

There is some question about whether an add-on gets its own disable event.  If it doesn't, this might be a wontfix.

**Comment by johngruen** [comment]
we should file a different issue to kill code that detects experiments installed in the add-on. For surveys we should – since we're moving to bootstrap – pull state from the server
