### ISSUE TITLE
Add Discourse Link to each experiment details page

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1019]
You know, in the details section

**Comment by meandavejustice** [comment]
@kaganjd This feature will cover a couple different things.
1. adding a field to the [experiment model](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/models.py)
2. Updating the experiment [serializer](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/serializers.py) to send down the data properly.
3. updating the [experiment model tests](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/tests.py) to ensure that they match your updates and pass*
4. updating the [experiment view](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/experiment-page.js)
5. updating the [experiment view test](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/test/views/experiment-page.js)
6. Update [demo data](https://github.com/mozilla/testpilot/blob/master/fixtures/demo_data.json) so we don't have to add the urls manually in the admin when running locally.

Ping me if you have any questions

\* to run the tests take a look at [README-DOCKER.md](https://github.com/mozilla/testpilot/blob/master/docs/README-DOCKER.md)

**Comment by johngruen** [comment]
@kaganjd thanks for picking this up

**Comment by kaganjd** [comment]
@meandavejustice this commit was v helpful! https://github.com/mozilla/testpilot/commit/071d113743ad2ed5bd91f48409eb9d8a771b3920

**Comment by meandavejustice** [comment]
@kaganjd Oh nice, good thinking looking that up. We'll have to remember pointing people to previous commits like that for guidelines
