### ISSUE TITLE
Basket subscribe inconsistent with `+` character in email address (bug 1281889)

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1026]
Carry-over from https://bugzilla.mozilla.org/show_bug.cgi?id=1281889

> Original implementation: Bug 1263675 
> 
> To replicate:
> 1) Go to https://testpilot.firefox.com
> 
> 2) Signup a brand-new/uniuqe-to-our-system email address for an Account/Test Pilot ie LDAP+uniquename@mozilla.com
> 
> 3) Confirm your FxAccount
> 
> Error found:
> Email address is not passed through to Basket with Test Pilot subscription.
> 
> Thought:
> Test Pilot form/integration is not accepting "+" in the email address. I just tried this with my reg & existing email address and it worked.

**Comment by jaredhirsch** [comment]
It [looks like](https://github.com/mozilla/testpilot/blob/53ebacd/testpilot/frontend/static-src/app/main.js#L105) the email address isn't entity encoded when it's passed to the form body:

``` js
      body: 'newsletters=test-pilot&email=' + email
```

I bet `encodeURIComponent(email)` would fix it.
