### ISSUE TITLE
Simplify local development for experiment builders

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1029]
Currently, various functions of the main Test Pilot add-on rely on data from the Test Pilot server API. 

That means an in-development experiment which talks to the Test Pilot add-on also requires a locally running instance of the Test Pilot server - because the developer needs to enable their experiment and have the main Test Pilot add-on recognize it through the server API.

We should find a way to stub this out, so that there's just enough of a dev server - or even just static JSON files - that the Test Pilot add-on can fetch and so recognize the in-development experiment without a full-blown Docker installation.

**Comment by ghost** [comment]
I think flat files (#988) would solve this.

**Comment by lmorchard** [comment]
Another idea: What if there was a local dev mode which used the list of all locally installed add-ons as valid experiments, along with the server API list? Then we could at least set up things like BroadcastChannels for WebExtensions to receive Telemetry ping requests

**Comment by chuckharmston** [comment]
Closing since we've shipped flatfiles.
