### ISSUE TITLE
Remove Test Pilot user database.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1034]
Drop email addresses from the database.  This data is in exact target now and we don't need a copy of it.

**Comment by lmorchard** [comment]
Something that occurred to me: We probably want to keep the actual DB tables, but delete _most_ of the records. That is, all users _without_ the `is_staff` and/or `is_superuser` flags. Until we get to using flat files (#988), we still need admin logins to access the admin pages.

**Comment by lmorchard** [comment]
See also: #1056

**Comment by lmorchard** [comment]
Collapsing #1056 & #1046 into this issue as things to keep in mind when we delete data:
- [ ] Retain contributor accounts & profiles (i.e. make sure `is_staff=True`)
- [ ] Retain admin accounts (i.e. `is_superuser=True`)
- [ ] Ensure admin accounts can be logged into at `/admin/` by setting passwords

We need to keep the actual user database around, but we can delete all records where `is_superuser=false AND is_staff=false` and clean up all data not related to core staff

**Comment by ghost** [comment]
Marking as blocked just to keep us from landing this yet.  Next sprint please.

**Comment by ckprice** [comment]
I'm going to take this off this milestone as it doesn't block TXP-7.

**Comment by lmorchard** [comment]
So, I think this can be unblocked now, and taken care of with some SQL run on stage / prod with the next deployment. That, or I can write a Django DB migration that takes care of it. I'm going to poke around a bit on my local machine and see if I can't come up with something solid before tomorrow EoD.

Basically, I think we want to wipe out all accounts & profiles & email address records - _except_ for users with /admin/ access and users included as contributors on experiments.
