### ISSUE TITLE
Use Badge API to update toolbar badge with `new` experiment UI.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1036]
Badge added when a new experiment is added to Test Pilot. Icon is unbadged when the user interacts with the icon.

UX: See the New Experiment Notification card here: https://invis.io/Q77S1H6ZC

**Comment by lmorchard** [comment]
> including separate logging name to compare badged vs unbadged performance

I don't think we log clicks on the toolbar icon at all right now. At least, [I don't see any kind of measurement happen here](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L289). How / where should we do that? (eg. telemetry? google analytics?)

**Comment by lmorchard** [comment]
Filed issue #1108, because I'm hitting a similar thing in different issues.

**Comment by lmorchard** [comment]
Moved the metrics part into a separate issue: https://github.com/mozilla/testpilot/issues/1109
