### ISSUE TITLE
Update UI in doorhanger with new experiment UI.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1037]
UI added when a new experiment is added to Test Pilot. Removed once a user has interacted the doorhanger UI or enabled the experiment.

UX: See the New Experiment Notification card here: https://invis.io/Q77S1H6ZC

**Comment by lmorchard** [comment]
Screen looks like it's specifically here https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/168767160
