### ISSUE TITLE
Update UI on website with new experiment UI.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1038]
UI added when a new experiment is added to Test Pilot. Removed once a user has enabled the experiment or clicked through to the details page.

UX: See the New Experiment Notification card here: https://invis.io/Q77S1H6ZC

**Comment by lmorchard** [comment]
The "New Experiment Notification" card on the invision deck doesn't show website UI - just add-on & notification pop-up UI. Looks like maybe this is what we need?

https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/169825427

**Comment by meandavejustice** [comment]
A good commit to checkout for implementing this would be https://github.com/mozilla/testpilot/commit/5ea7dc1c0ca74a1a9ecf0cd23ff189a0a8dfc195 since @kaganjd just did such similar work

**Comment by lmorchard** [comment]
@meandavejustice @kaganjd Thanks for that commit, I completely stole from it 😀

**Comment by SoftVision-PaulOiegas** [comment]
Three things that I have observed here. 
1. The cards for new experiments are clearly larger than the ones for existing ones. 
2. If you hover the existing ones, a border is added around the card, while on the new cards, the border cuts from the card.
3. Even if border is displayed for existing experiments, the new ones still seem a bit larger.

Shouldn't we have some consistency here ? 
![cards size and borders](https://cloud.githubusercontent.com/assets/17258026/17251167/41758d82-55b0-11e6-936d-c5f272bec840.png)

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas hey, that's height difference is by design, but the hover is fixed by https://github.com/mozilla/testpilot/pull/1151
