### ISSUE TITLE
Replace source for "### people trying experiment" with count derived from metrics

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1039]
Currently, we expose experiment usage via keeping a record of installations and counting them by distinct user. Once we get rid of the user DB (#1034), that a) removes the uniqueness index and b) means we have to rework that installations table to track client IDs.

It might be better if we also remove that installations table & API altogether, and instead find a way to get a per-experiment usage count from the Telemetry metrics sent from the client. This would also help us along the way to flat files (#988) by removing probably the last thing for which we need our own server & database.

**Comment by lmorchard** [comment]
FWIW, I have no idea how to do this yet, but I'm hoping there's some way we can get a report out of Telemetry just counting daily/monthly/overall active users. 

My blue sky wish would be to have a JSON resource somewhere that just offers those counts - it could be a static file periodically updated from metrics data, or a live dynamic query that we heavily cache. Tomayto, tomahto.

**Comment by lmorchard** [comment]
Actually, I'll take it out of the milestone for now, because we _can_ actually still get the counts from the installation table after getting rid of accounts. They don't necessarily have to be tied together and this issue will take some time to figure out

**Comment by johngruen** [comment]
@johngruen to talk to @clouserw about this stuff

**Comment by dannycoates** [comment]
It seems like you could do this with a Spark job that writes json to an S3 bucket... [This one](https://gist.github.com/mreid-moz/dac9c5b67f01ea3734a207821b120668) that creates some data for Presto might have some clues.

**Comment by ghost** [comment]
Sunah is working on this right now, but it won't be done in time for this sprint

**Comment by lmorchard** [comment]
FWIW, I filed #1312 with a proposed usage count JSON format that we can move to right now using the existing Django API. Hopefully whatever we come up with here can match that format, and switching over is just a matter of changing a configured URL

**Comment by lmorchard** [comment]
Following up here, it looks like we have data from Telemetry - and that's well more than half the battle!

https://analysis-output.telemetry.mozilla.org/testpilot/data/installation-counts/latest.json

Other parts to wrap up this issue:
- [x]  After PR #1321, [the `usageCountsUrl` needs to be switched to the Telemetry URL](https://github.com/mozilla/testpilot/pull/1321/files#diff-687e0a1f096950bef2c3d1bedbbc020eR10).
- [x] Remove the add-on code [that sends PUT / DELETE requests on experiment enable / disable](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L206), because Telemetry tracks that now.

**Comment by lmorchard** [comment]
Marking this as blocked to signal that we're still kind of waiting on final consensus about whether we're good to switch over to the Telemetry data. The two steps in my last comment - switching to that URL & removing the Django code - are the wrap up.

**Comment by lmorchard** [comment]
Actually, sounds _un_blocked and we should be clear to switch over to the Telemetry based numbers in a few weeks - probably next sprint end?

**Comment by ghost** [comment]
👍 flip over any time
