### ISSUE TITLE
Update landing page to accomodate removal of FxA auth

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1041]
- [x] Update landing page to link directly to Install.
- [ ] Updated Landing page UI to reflect new onboarding steps (at the bottom of the landing page).

Mockup: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/168769316

(Do we need assets for this?)

**Comment by lmorchard** [comment]
The first TODO up there will be covered by #1065

**Comment by lmorchard** [comment]
Looks like the only asset we might need are the chat bubbles image for step number 3

**Comment by lmorchard** [comment]
@johngruen Do we have that chat bubbles image somewhere already? Or does that still need slicing from a mockup?

**Comment by johngruen** [comment]
@lmorchard ah, yeah: https://www.dropbox.com/s/8zsjpvhf9jsz6xe/chat-icon.svg?dl=0

Thanks, i didn't realize this was covering both issues.
