### ISSUE TITLE
Implement email address collection dialog

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1043]
Blocked by https://github.com/mozilla/testpilot/issues/1074
- [ ] Create email signup modal for optional sign up after installation.
- [ ] Move basket integration to email signup modal.

**Comment by jaredhirsch** [comment]
I'm taking this _but_ if anyone wants to steal it before Friday, go right ahead

**Comment by johngruen** [comment]
@6a68 (or whoever picks this up), here's the email graphic for you.
![graphic_mail](https://cloud.githubusercontent.com/assets/3323249/16875104/8e2891e2-4a6b-11e6-84c4-d039880fdc77.png)
![graphic_mail 2x](https://cloud.githubusercontent.com/assets/3323249/16875105/8e2969c8-4a6b-11e6-90bc-2b98136e829b.png)

 hint...I stole it from FXA :)

**Comment by johngruen** [comment]
@6a68 updated the string in the mockup above the email input...should now be `Find out about new experiments and see test results for experiments you've tried.`

**Comment by jaredhirsch** [comment]
Updated mocks: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/171956981

> hint...I stole it from FXA :)

I recognized it instantly :-)
