### ISSUE TITLE
Ensure content for "Contributors" list on experiment details page is retained after user account deletion

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1046]
The "contributors" list for each experiment is made up of a list of user accounts.

This should probably be reworked to be a simple list of name, title, and avatar totally separate from user accounts.

**Comment by ckprice** [comment]
I wonder if it makes sense to remove this from TXP-7, and add it to our flat files milestone when it's created.

There may be a more interesting way to manage this list once we figure out the files architecture, and I think we can continue to edit the contributors list in the DB after we remove Firefox Accounts.

**Comment by lmorchard** [comment]
Problem is that the data behind this column possibly goes away when TXP-7 is finished. The contributors list is made of users. That said, we could possibly retain those specific users - since those are all Mozillians and possibly all admins.

**Comment by pdehaan** [comment]
If we move to flat files (backed by Markdown+JSON/Yaml) we could probably just use front matter.
For example:
- https://gohugo.io/content/front-matter/
- https://jekyllrb.com/docs/frontmatter/

So in the case of an experiment, the front-matter could just specify a sorted array of contributors and have no dependencies on a database or anything else.

---

```
---
title: Tab Center
version: "1.21"
slug: tab-center
changelog_url: https://github.com/bwinton/VerticalTabs/releases/latest
contribute_url: https://github.com/bwinton/VerticalTabs#readme
bug_report_url: https://github.com/bwinton/VerticalTabs/issues
discourse_url: https://discourse.mozilla-community.org/c/test-pilot/tab-center
description: "What would it be like to move tabs from the top of the browser to the side? We wanted to find out!"
tags: [ "Just Updated" ]
lastmod: 2016-07-05
date: "2012-04-06"
contributors:
  - {name: "John G", bio: "Firefox UX"}
  - {name: "Philipp S", bio: "Firefox UX"}
  - {name: "Blake W", bio: "Firefox UX"}

---

<p class="lead">Take your tabs from in the way to tucked away. Tab Center moves your tabs to the side of your browser window so they're out of sight when you don't need them, and easy to expand and grab when you do.</p>

![Some image]()
Tuck away those tabs until you need them.

![Second image]()
Pin Tab Center to see everything you've got open.

![Third image]()
Redecorate and move the furniture! Tab Center works with your favorite Firefox themes.

```

**Comment by lmorchard** [comment]
Flat files issue over here: https://github.com/mozilla/testpilot/issues/988 (also a meeting this Weds)

But, we're not moving to flat files right now. Right now, we're removing FxA accounts. So, either way we need to do something about the Contributors content by the end of TXP-7. User accounts are getting deleted, but we need to retain the content for contributors (currently expressed as user accounts). If we delete everything, it doesn't matter how we structure / express the content because it will be deleted :)

**Comment by lmorchard** [comment]
This issue should probably just be something to keep in mind as part of #1034. I'll close this and add a todo over on that issue
