### ISSUE TITLE
Installation of Test Pilot extension unsuccessful

### ISSUE THREAD

**Issue by sydbarrett74** [mozilla/testpilot#1049]
I am trying to join the Test Pilot project and attempted installation of the extension. When I click on 'Install Test Pilot', the button text switches to 'Installing Test Pilot' and sits there indefinitely. The browser status bar reads, 'Stopped'. Refreshing the page doesn't help: the same thing happens.
- [ ] Operating system - Windows 10 x64 Insider Fast Ring build 14379
- [ ] Firefox build - Release 47.0.1

**Comment by ckprice** [comment]
Thanks for filing!

A few quick questions
- Does this also happen with a release version of Windows 10? Looks like you're on a pre-release version of Windows 10.
- Are you in private browsing mode?
- Do you have any ad/tracking protection add-ons or extensions installed?

Thanks again.

**Comment by sydbarrett74** [comment]
I'm a moron. I disabled uBlock Origin and uMatrix for the site and the addon installed successfully. Sorry to have wasted everyone's time. This should've been the very first thing I checked. Grrrr...
