### ISSUE TITLE
Frontend always redirects to /home on initial load

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#105]
Whenever I visit or reload `http://ideatown.dev:8000/experiments/foobar`, I get redirected to `http://ideatown.dev:8000/home/`. We should probably navigate to the requested view on load rather than always redirect to `/home/`

**Comment by meandavejustice** [comment]
This is happening because we call `app.router.reload` when we get data back from the server after authorizing. Since we fetch from `api/me` on a fresh request we should have some sort of loading page we can show before directing to the requested page
