### ISSUE TITLE
Add support for 'just modified' / 'just launched' in experiment views

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1052]
The [new specs](https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/169825427) show experiment cards with 'Just Launched' and 'Just Updated' labels in the experiment page view.

To support this, we'll need to propagate the experiment's last modified time from the DB, through the API, to a field on the experiment model. We'll then need to add the label UI to the DOM, and add hooks to toggle visibility of those tabs when appropriate.

(Split out from #968)

**Comment by johngruen** [comment]
This has been fixed
