### ISSUE TITLE
Update `Leave Test Pilot` flow to message users to manually unsubscribe from email list.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1059]
We're backing out FxA which means we can no longer automatically unsubscribe users from the Test Pilot mailing list.
- [ ] Remove [`/news/unsubscribe/`](https://github.com/mozilla/testpilot/blob/f9b13478d3b978ddd221e4adde974c48029933b6/testpilot/users/models.py#L43) call.
- [x] Add messaging to inform users that they will have to manually unsubscribe to be taken off list.

**Comment by ckprice** [comment]
@johngruen to provide specs for messaging.

**Comment by lmorchard** [comment]
<strike>Hmm, this could be a terrible idea, but... is there any kind of token or receipt we get from the subscribe API request that we can use with the unsubscribe? Could send that up to the add-on & store it in the client to use on uninstall. If that's missing, we could fall back to messaging about manual unsubscribe.</strike>

Yeah, no, [the unsubscribe resource doesn't work this way.](http://basket.readthedocs.io/newsletter_api.html#news-unsubscribe)

**Comment by johngruen** [comment]
@lmorchard why don't i do a WIP PR of the front end of this

**Comment by johngruen** [comment]
@lmorchard #1064 is the UI changes, does not remove the actual unsubscribe code.
