### ISSUE TITLE
check for docker-machine in docker-build.sh

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#106]
`docker-machine` is not a hard dependency of the project. We should check to ensure the user has it installed before running it's commands

**Comment by lmorchard** [comment]
Hmm... I thought docker-machine _was_ a hard dependency of the project, at least for dev.

Oh, wait, I see. That's just for OS X. Linux can run Docker stuff natively, and Windows still apparently uses boot2docker.
