### ISSUE TITLE
Remove button-related code from experiment-row-view.js

### ISSUE THREAD

**Issue by kaganjd** [mozilla/testpilot#1067]
#1051 replaces "Manage" and "Get Started" buttons with a participant count. But there's still lingering button-related code [here](https://github.com/mozilla/testpilot/blob/67ad38a84bd36be94de501e9d6b6af2d5ea70cb2/testpilot/frontend/static-src/app/views/experiment-row-view.js#L72) that needs to be updated or deleted.

**Comment by meandavejustice** [comment]
@kaganjd we should just remove this in #1051

**Comment by ghost** [comment]
IRC says this is done.  Hooray, thanks!  Please close issues when they get finished. 🎅
