### ISSUE TITLE
Test Pilot & Web Extensions messages: prefValueRequest and addonListRequest

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot#1068]
Now that https://github.com/mozilla/testpilot/pull/1022 is merged, and for https://github.com/mozilla/blok/issues/12#issuecomment-232443161, I'd like to request some new message types between Test Pilot and other (Web Extension) add-ons:

When Test Pilot receives a message like `{type: 'prefValueRequest', pref: '?'}`, it should return a response message like `{type: 'prefValueResponse', pref: '?', value: '<value>'}`, so Web Extensions can query for Firefox pref values.

When Test Pilot receives a message like `{type: 'addonListRequest'}`, it should return a response message like `{type: 'addonListResponse', addons: [<addonID1>, <addonID2>, ...] }`, so Web Extensions can query Firefox for other installed add-ons.

**Comment by johngruen** [comment]
We're not going to do this, but we do have in product UI warning users about incompatible add-ons
