### ISSUE TITLE
Addon: Replace post-install doorhanger with new tab

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1074]
This issue should have been filed with the rest of TXP-7, but there accounts-backout UX does away with the installed-panel UI. Instead it opens a second tab in the background on install with the following:

![add-on notice 2x](https://cloud.githubusercontent.com/assets/3323249/16885925/1efe46d4-4a9f-11e6-9939-52d1161d13b4.png)

Flow should be: 
1. user installs add-on
2. browser redirects to the experiments home page
3. the above page opens in a background tab.

There is no panel UI in the updated flow

**Comment by johngruen** [comment]
![icon-highlight](https://cloud.githubusercontent.com/assets/3323249/16886001/921da4b6-4a9f-11e6-8104-a67977c969c2.png)
![icon-highlight 2x](https://cloud.githubusercontent.com/assets/3323249/16886002/9220ef86-4a9f-11e6-877b-ceab91373342.png)

**Comment by johngruen** [comment]
![icon-highlight](https://cloud.githubusercontent.com/assets/3323249/16886038/cd992696-4a9f-11e6-9e25-05d5f4b9fb9d.png)
![icon-highlight 2x](https://cloud.githubusercontent.com/assets/3323249/16886039/cd9ca366-4a9f-11e6-8832-7aac43158f37.png)

**Comment by ghost** [comment]
Also close #1119 and #1098
