### ISSUE TITLE
"Installing..." keeps spinning after add-on installation attempt

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1075]
Occasionally on a fresh Firefox profile, I try to install the add-on but the "Installing..." barberpole never stops spinning. 

There will be an error in the Web Console like "Uncaught promise rejection: waitForMessage timed out". Having trouble reproducing this to capture the exact error message. 

[waitForMessage is here](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/main.js#L68) and it has a timeout for when the add-on takes too long to respond. It [gets called here in the frontend](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L41) after the install button [detects that the add-on has been installed](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/landing-page.js#L55).

My guess is that between installation and when the add-on finally starts responding to messages, there's a gap of sometimes more than 5 seconds and that's why the error happens. Still investigating, though.

Every time this has happened to me, a page refresh seems to fix everything and the add-on is actually working.

**Comment by jaredhirsch** [comment]
> Every time this has happened to me, a page refresh seems to fix everything and the add-on is actually working.

@lmorchard What if we just refresh the page after 5 seconds?

**Comment by lmorchard** [comment]
Looks like @johngruen captured the same error message I saw over in #1076:

> Noticed this error in the console:
> Unhandled promise rejection waitForMessage timeout: sync-installed from within the vendor 
> bundle

**Comment by jaredhirsch** [comment]
I can consistently reproduce this bug by doing the following:
1. start FF (I'm using release channel 47.0.1 on OS X 10.11.5) with a fresh profile
2. go to the dev site: http://testpilot.dev.mozaws.net/
3. click 'Install the Test Pilot Add-on'
4. Download the add-on: <img src="https://www.dropbox.com/s/geo0ln8t1a28ylp/Screen%20Shot%202016-07-15%20at%201.25.15%20PM.png?dl=0&raw=true" width=300>
5. Turn off wifi / disconnect network
6. Install the add-on: <img src="https://www.dropbox.com/s/73m3czr3zsqt9oz/Screen%20Shot%202016-07-15%20at%201.25.21%20PM.png?dl=0&raw=true" width=300>
7. Note that the barberpole never stops spinning & the browser console contains the error message `Unhandled promise rejection waitForMessage timeout: sync-installed`
8. Turn on wifi / reconnect network
9. Barberpole still never stops spinning
10. Page updates correctly on refresh

**Comment by johngruen** [comment]
Possibly related. If i uninstall the add-on on my local build (near master in every possibly significant way) the first time i click to reinstall it hangs but the second time i click to reinstall it works (even w/o page refresh)

Error msg: 

```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Jul 15 2016 16:37:27 GMT-0400 (EDT)
Full Message: TypeError: this._addon is null
Full Stack: BrowserAddonActor.prototype.id@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/addon.js:50:5
DSC_setAddonOptions/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1556:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
```

**Comment by jaredhirsch** [comment]
@johngruen The bug you've found looks like a devtools bug

**Comment by johngruen** [comment]
BUGS FOR EVERYBODY

**Comment by pdehaan** [comment]
I'm seeing this as well after switching from prod to dev:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/16925813/d008f4fa-4cda-11e6-91e8-48e01b9f8871.png)

``` js
{
  version: "",
  source: "https://github.com/mozilla/testpilot",
  build: "https://circleci.com/gh/mozilla/testpilot/619",
  commit: "8e617b1298ab4827a566e0099bcc284a3713594b"
}
```

**Comment by lmorchard** [comment]
Hmm, I can't reproduce on dev after a dozen or so tries... I just tried from a fresh profile, and then on my dev edition after removing an old add-on and re-installing from dev. 

Were you installing from dev? Just visiting with an existing add-on install after switching to dev in prefs? What version of the add-on do you have installed?

**Comment by pdehaan** [comment]
I probably have an existing add-on that I installed a while ago (and auto-updates) and this morning switched from prod to dev. I can't seem to see any of the pages on Test Pilot using this profile/config (either browsing directly or via the Test Pilot add-on drop-down menu).

So far I've tried:
- http://testpilot.dev.mozaws.net/
- http://testpilot.dev.mozaws.net/experiments
- http://testpilot.dev.mozaws.net/experiments/tab-center

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/16928449/9780e4f0-4ce7-11e6-86ea-4878875d1166.png)

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/16928463/ae29be20-4ce7-11e6-9888-f8f6e7e87999.png)

---

**UPDATE:** Of course NOW I cannot reproduce reliably (trying to access via the add-on to an experiment directly failed, but I can manually go to /experiments/). Wondering if this is partially related to the dev server's deploying on a whim and possible slight downtime during the deploy process.

**Comment by lmorchard** [comment]
@pdehaan Looks like this might be issue #1101
