### ISSUE TITLE
Build the legacy user migration page

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1079]
As part of our migration from the legacy Test Pilot we need to build a simple landing page which we show before we remove the old add-on.

You can see the spec at https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/169034030
- The "Check out Test Pilot" button should just link to the home page
- The "Check out Test Pilot" button should be instrumented to determine how many people hit the download funnel.  I think this can be done simply by making the download button a new referral name in our stats (similar to a snippet, or whatever).  /cc @mattgrimes to say if that will work, and if so, to give the name of it

**Comment by MattGrimes** [comment]
Works for me. I like legacy_testpilot or testpilot_classic for a referral. Anything is fine though so long as we know before the migration.

**Comment by ghost** [comment]
Thanks, I'm going with `utm_source=testpilot_legacy` .  This is set to launch on Aug 16th.
