### ISSUE TITLE
Scrolling behavior is a bit jumpy on testpilot.dev

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1087]
Found in http://testpilot.dev.mozaws.net/__version__ (1e0aa89297ab8d4ba481ed186d8b7f934a1c4065):

``` js
{ "build": "https://circleci.com/gh/mozilla/testpilot/624",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "commit": "1e0aa89297ab8d4ba481ed186d8b7f934a1c4065" }
```

---
### Steps to reproduce:
1. Go to an experiment details page (ie: http://testpilot.dev.mozaws.net/experiments/tab-center).
2. Make sure the experiment is enabled.
3. Slowly start scrolling.
### Actual results:

The green "Tab Center is enabled." bar slowly scrolls off screen, then reappears after you scroll down too far.

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/16930322/8783dad6-4cf0-11e6-8a1a-05e253f3de10.png)

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/16930343/a257793a-4cf0-11e6-8e99-071e4f6aa636.png)

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/16930359/b4a42d5e-4cf0-11e6-9e74-580e2179f81e.png)
### Expected results:

We may need to tweak the smart scrolling bits and detect the header sooner so we make the header "fixed" as soon as we scroll to the green bar.
Or not, whatever, minor nit.

**Comment by pdehaan** [comment]
FWIW, scrolling works really well when the experiment is not enabled and the "{Experiment.name} is enabled." banner is not displayed.

**Comment by johngruen** [comment]
@pdehaan yeah, i think we have a hard-coded height in the view. with the new UX, we could add the height of the notification div when experiment is enabled.

**Comment by SoftVision-PaulOiegas** [comment]
Managed to reproduce the jumpy scrolling also when the experiment is not enabled (Windows 10 x64). So you should take in consideration both cases.
Screen recording https://goo.gl/gwZhqo .

**Comment by meandavejustice** [comment]
I'm seeing some jumping when scrolling on experiment pages as well

![vokoscreen-2016-09-28_16-22-55 2](https://cloud.githubusercontent.com/assets/1844554/18931242/54fb4c66-8599-11e6-9238-2c6b4eef41fd.gif)

**Comment by lmorchard** [comment]
Yeah, I think this is because of [the hardcoded pixel height cutoff we have for the scrolling transition](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/ExperimentPage.js#L19). We probably have it tuned for one platform (i.e. OS X) but not others (i.e. Linux) - would be better if we could find a way to more naturally derive that number, or use a different approach for causing the transition

**Comment by ghost** [comment]
Dupe of 🔨 #1240
