### ISSUE TITLE
If user cancels add-on install, stop the 'installing...' barberpole

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1089]
STR:
- go to test pilot site
- click big green install button
- close the addon install doorhanger without installing anything
- the 'installing...' button state persists, clicking the button will actually retrigger the install, but the text is never updated back to 'Install' and the barberpole style isn't removed

**Comment by jaredhirsch** [comment]
going to try to get to this as part of the [TXP-7](https://github.com/mozilla/testpilot/milestone/11) task milestone

**Comment by johngruen** [comment]
@6a68 thanks for filing this one. Can we make it so the UI just reverts back to the original install button?

**Comment by lmorchard** [comment]
Yeah, this one is a little hard, and probably needs a long time-out. We can't actually detect whether they cancelled the install. 

The chicken-and-egg thing is we need the add-on to get any messaging to the frontend from the browser, but if there's no add-on we don't get any privileged info about things like cancelled add-on installs.

**Comment by johngruen** [comment]
Talked to @andymckay about this one and the TL;DR is that there's not much to be done in this case until https://bugzilla.mozilla.org/show_bug.cgi?id=1288178 makes it into release

**Comment by johngruen** [comment]
@clouserw @6a68 I think we should consider not doing this and resolving via #1223

**Comment by ghost** [comment]
That seems reasonable.  That API has already shipped (in 48, I want to say?).  Anything we do to the "old way" of installing add-ons is already stale.

**Comment by johngruen** [comment]
@6a68 backing out of TXP-0 for now since doing anything clever about add-on install stuff depends on #1223.

**Comment by johngruen** [comment]
No doorhanger = no problem
