### ISSUE TITLE
String typo displayed under the "Test Pilot" toolbar button after installing the add-on

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1091]
![an button](https://cloud.githubusercontent.com/assets/18304511/16943937/fdd008b6-4da6-11e6-800c-2a61c75fc589.png)
[Affected versions]:
- Nightly 50.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net
2. Install Test Pilot.
3. After the installation is completed, observe the message displayed under the Test Pilot button.

[Expected result]:
"FYI: We put a button in your toolbar so you can always find Test Pilot" tooltip is displayed.

[Actual result]:
"FYI: We put an button in your toolbar so you can always find Test Pilot" tooltip is displayed.

[Notes]:
- Attached a screenshot of the issue.

**Comment by SoftVision-PaulOiegas** [comment]
The typo was corrected on dev environment.
