### ISSUE TITLE
Experiment icons are not centered in their wrapper

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1092]
![experiment icon](https://cloud.githubusercontent.com/assets/18304511/16945184/c348f882-4dac-11e6-8f87-7941e006ea41.png)

[Affected versions]:
- Nightly 50.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net
2. Open the "Inspector" (Ctrl+Shift+C).
3. Hover one of the add-on cards icon.
4. Observe the icon position.

[Expected result]:
div.experiment-icon height is 80px.

[Actual result]:
div.experiment-icon height is 100px.

[Notes]:
- Attached a screenshot of the issue.
- On https://testpilot.firefox.com/ the icons are 80x80.

**Comment by SoftVision-PaulOiegas** [comment]
Wrapper was enlarged an now icons are correctly displayed in the center of the designed area.
