### ISSUE TITLE
The last 4 lines from the "Terms of Use" page are misaligned with the rest of the text

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1093]
![misaligned lines](https://cloud.githubusercontent.com/assets/18304511/16945840/7c873fdc-4daf-11e6-8f74-a5f8e3d1c3b6.png)

[Affected versions]:
- Nightly 50.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net/terms
2. Scroll down to the bottom of the page.
3. Observe the last 4 lines from the "Contact" section.

[Expected result]:
All the lines from the "Contact" section are aligned with each other. 

[Actual result]:
The last 4 lines are misaligned.

[Notes]:
- Attached a screenshot of the issue.

**Comment by SoftVision-PaulOiegas** [comment]
The text was indeed aligned on production, but now the "Mail" section has nothing displayed. 
Also, shouldn't "Attn:" be in bold too like the others got after the fix ?
