### ISSUE TITLE
Universal Search can no longer be enabled if it was previously disabled, unless the browser is restarted

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1094]
[Affected versions]:
- Nightly 50.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Test Pilot is installed from https://testpilot.stage.mozaws.net/

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net/experiments
2. Enable the "Universal Search" experiment.
3. Disable the experiment.
4. Re-enable the experiment.

[Expected result]:
The experiment is successfully enabled.

[Actual result]:
The page is updated and it shows that the experiment is enabled, but it is not in fact enabled.

[Notes]:
- As a side effect, if the browser "Menu" is not expanded while doing the above steps it is no longer working. Same for Pocket.
- The experiment is correctly enabled after restarting the browser
- Attached a screen recording of the issue.

[Universal Search can no longer be enabled if it was previously disabled.zip](https://github.com/mozilla/testpilot/files/371468/Universal.Search.can.no.longer.be.enabled.if.it.was.previously.disabled.zip)

**Comment by johngruen** [comment]
@chuckharmston @6a68 can you guys dig around on this one? might be an upstream issue with the universal search add-on.

**Comment by chuckharmston** [comment]
Moved to https://github.com/mozilla/universal-search/issues/270
