### ISSUE TITLE
Enabling Tab Center or Universal Search experiments removes the URL of the page from address bar

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1095]
[Affected versions]:
- Nightly 50.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Test Pilot is installed from https://testpilot.stage.mozaws.net/

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net/experiments
2. Navigate to Enable the "Tab Center" or "Universal Search" experiment page and observe the address bar.
3. Chose to enable one of the above mentioned experiments and observe the address bar URL. 

[Expected result]:
The experiment is successfully enabled and the URL in the address bar remains unchanged.

[Actual result]:
The experiment is successfully enabled but the URL in the address bar is removed.

[Notes]:
- This issue does not occur when enabling "Activity Stream" experiment.

**Comment by ghost** [comment]
we're going to ignore this for now. thanks
