### ISSUE TITLE
After installing "Test Pilot", the toolbar button is actionable only after the "FYI:" message disappears

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1098]
[Affected versions]:
- Nightly 50.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net
2. Install Test Pilot.
3. Click the Test Pilot button when the "FYI: We put a button in your toolbar so you can always find Test Pilot" tooltip is displayed.

[Expected result]:
The "Test Pilot" dropdown is displayed.

[Actual result]:
The "FYI:" message is dismissed and the dropdown is not displayed.

[Notes]:
- The dropdown can be opened only after the tooltip dismisses itself, or after a second click.
- Attached a screen recording of the issue.

[the toolbar button is actionable only after the FYI message disappears.zip](https://github.com/mozilla/testpilot/files/371615/the.toolbar.button.is.actionable.only.after.the.FYI.message.disappears.zip)

**Comment by johngruen** [comment]
This should be closed when we land #1074

**Comment by johngruen** [comment]
Note: this will go away when TXP-7 lands. remeber to close @6a68

**Comment by johngruen** [comment]
Fixed by #1074
