### ISSUE TITLE
Measure conversion of social media shares to new installs

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1099]
The share URLs from #1096 should ship with `utm_` parameters indicating the link's origin. These will be used to create a dashboard to track the conversion rate from these links to Test Pilot installs.

**Comment by chuckharmston** [comment]
@johngruen two points of clarification:
1. Would you like each service's link to be for the same campaign and source, but a different medium? Would you like each medium tracked separately?
2. The [solicitation flow](https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/169753822) shows the copiable [testpilot.firefox.com](https://testpilot.firefox.com) link without params. Is that intentional or oversight?

**Comment by johngruen** [comment]
@chuckharmston 
1. i think we should track media separately.
2. yeah, oversight. we should have params here. Thanks for looking out!

**Comment by chuckharmston** [comment]
@ckprice Can we get these params please? Thanks!

This would be a great place for any additional instrumentation you'd want in this flow as well.

**Comment by chuckharmston** [comment]
Note to self: to keep the shared URLs cleaner, let's use the [mzl.la](https://mzl.la) URL shortener.

**Comment by ckprice** [comment]
## Measurements for the /share page

### Create `pageview` event on the /share page

We'll want to add a `pageview` event to this page sending along `dimension1`, `dimension2` and `dimension3`.

```
app.sendToGA('pageview', {
  'dimension1': this.hasAddon,
  'dimension2': anyInstalled,
  'dimension3': installedCount
});
```

These dimensions will give us information on the types of users that are sharing.

Referencing our [GA Custom Dimensions documentation](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#custom-dimensions), we'll want to add `Share Page` to the 3 mentioned dimension rows and update the docs.

### utm parameters of the auto tab opening after x days (#1292)

Referencing our [GA Table of Tagged Links](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#table-of-tags), here is what this link should have (please also update this document)

| Description | utm_source | utm_medium | utm_campaign | utm_content |
| --- | --- | --- | --- | --- |
| Tab opens after user has tried an experiment for n days (#1292) | testpilot-addon | firefox-browser | share-page |  |

`Nice to have`: My understanding is that this tab will open automatically; is it possible to determine if someone actually clicked into this tab?

### Capturing the clicks on the share buttons - category will be `ShareView Interactions`

Referencing our [GA Table of Events documentation](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#table-of-events), here is what the new events will look like (please also update this document)

| Description | eventCategory | eventAction | eventLabel |
| --- | --- | --- | --- |
| Click on a button in the Share section | ShareView Interactions | button click | {facebook,twitter,email,copy} |

### utm parameters on the links which get shared out

ehull@ shared [this document](https://docs.google.com/presentation/d/1xB2VYLOW52xT_Hpyw-l9lBQI-ZlwlgeQz_rOeNc7XiA/edit#slide=id.p) that the marketing team uses for tracking social links, which I based these on.

Referencing our [GA Table of Tagged Links](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#table-of-tags), here is what this link should have (please also update this document)

| Description | utm_source | utm_medium | utm_campaign | utm_content |
| --- | --- | --- | --- | --- |
| Links that get shared from /share | {facebook,twitter,email} | social | share-page |  |

@chuckharmston I think that's it.

**Comment by chuckharmston** [comment]
> My understanding is that this tab will open automatically; is it possible to determine if someone actually clicked into this tab?

@ckprice What do you mean by "clicked into this tab"?

**Comment by chuckharmston** [comment]
> utm parameters on the links which get shared out
> ...
> {facebook,twitter,email}

@ckprice I'm going to add `copy` to this set unless there's an objection.
