### ISSUE TITLE
Style import: add third header layout + change header mgmt

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#110]
This is for the 101-style-home-and-experiment-pages branch.

The experiments page header should have a third, thinner header state.

I'm not sure if the cleanest approach is to have the header view expose an API to allow pages to tell it to update itself, or if the header should be managed by the PageManager (i.e., its node inside the page-container node, and the header treated as a subview of pages). The latter seems cleaner, but I'm not sure.

**Comment by jaredhirsch** [comment]
@meandavejustice Are you working on this one?

**Comment by meandavejustice** [comment]
@6a68 Haven't written any code against it yet.
