### ISSUE TITLE
The "Settings" dropdown can only be dismissed by clicking on the button

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1100]
[Affected versions]:
- Nightly 50.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Test Pilot is installed from https://testpilot.stage.mozaws.net/

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net/experiments
2. Click the "Settings" button.
3. Click anywhere else on the page.

[Expected result]:
The "Settings" dropdown is dismissed.

[Actual result]:
The "Settings" dropdown is not dismissed.

[Notes]:
- The "Settings" dropdown can only be dismissed by click the "Settings" button again.
- On https://testpilot.firefox.com/, the [...] dropdown can be dismissed this way.
- Attached a screen recording of the issue.

[Settings dropdown can't be dismissed.zip](https://github.com/mozilla/testpilot/files/371724/Settings.dropdown.can.t.be.dismissed.zip)

**Comment by lmorchard** [comment]
[I think this change was intentional.](https://github.com/mozilla/testpilot/pull/1063/files#diff-9122a431ad71d321669d254c7c602d82L47)

@johngruen - do you know why we removed the click-anywhere-to-close code? Or was that not intentional?

**Comment by johngruen** [comment]
@lmorchard i took it out on purpose, but now that i think about it that might be premature. A quick cafe test of the random person sitting next to me at the airport suggests clicking out is the preferred pattern.

**Comment by ghost** [comment]
I also noticed I couldn't click anywhere and thought it was an oversight.

**Comment by johngruen** [comment]
@lmorchard @clouserw, yeah just to confirm, we should re-add this functionality

**Comment by johngruen** [comment]
I break it = i bought it

**Comment by SoftVision-PaulOiegas** [comment]
Settings menu is now correctly closed when clicking everywhere outside of it. Verified on main page and on all the experiments pages.
