### ISSUE TITLE
Need a documented process for developing new metrics

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1108]
When we (or experiments) have a new feature, we'll want to measure something about its performance. It seems we have a number of parts lying around to make this happen. (e.g. Telemetry, Google Analytics, etc) 

But, personally, I don't have a grasp on how we put the pieces together to measure a new feature. It would be great to have a documented process that goes something like:
1. Formulate the question (e.g. "What is the comparative performance of badged vs non-badged toolbar button clicks for the add-on?" from #1036)
2. Define & publicly document the data collection schema that would answer the question
3. Set up the analysis pipeline to process the collected data (e.g. telemetry? GA? other?)
4. Set up the dashboard to show the results (e.g. GA? re:dash?)
5. Implement code to collect interaction data (e.g. send telemetry pings? send Google Analytics pings? other?)

Some of these metrics tools are more or less appropriate for the add-on or the web frontend. Some of these steps (e.g. 3 & 4) may require requests of / meetings with other teams to get things implemented / configured, etc. Maybe it ends up being simple & self-service with something like Google Analytics. 

In any case, it would be good to have this stuff sketched out.

**Comment by chuckharmston** [comment]
Piggybacking on this: it'd be great to have some sort of documented process of this for experiments as well as Test Pilot itself. The Venn diagrams should overlap quite a bit, as I understand it.

**Comment by lmorchard** [comment]
Oh yeah, that too!

**Comment by lmorchard** [comment]
We should also roll some doco about how we use Google Analytics into this (#696), because it's a great big black box to me too.

**Comment by lmorchard** [comment]
@clouserw @ckprice @johngruen - tagging you folks into this, because I think you all have more insight than I do about this stuff.

**Comment by ckprice** [comment]
Taking the next steps on this one. I put a regroup on the public cal for Tuesday, I'll have a proposal for next steps then.

**Comment by ckprice** [comment]
Leaving the [draft document](https://docs.google.com/document/d/1AbgkEYxKOlrIzZjLoElvwJBDXFK8NlLigHCJSzdzldw/edit) (anyone with link can comment) open for the weekend for comments. Will open a PR next week.
