### ISSUE TITLE
Sidebar is persisting in full screen

### ISSUE THREAD

**Issue by errxr** [mozilla/testpilot#1112]
The sidebar is persisting when whatever video is in full screen with the "Keep sidebar open" feature.
Mac 10.11.6 and Firefox dev 49.0a2
<img width="1280" alt="sans titre" src="https://cloud.githubusercontent.com/assets/19875803/17029419/d5b33cc6-4f73-11e6-8201-cd4b9e7a69f2.png">

**Comment by meandavejustice** [comment]
@errxr are you referring to a tab center feature "keep sidebar open"?

**Comment by errxr** [comment]
@meandavejustice Yes.

**Comment by SoftVision-CiprianMuresan** [comment]
Thank you for reporting the issue errxr, we also found this too and logged it on Tab Center repository. https://github.com/bwinton/VerticalTabs/issues/441 so I will close this in favour of the other one.
