### ISSUE TITLE
The "Blok" experiment icon has a wrong aspect ratio on Homepage

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1118]
[Affected versions]:
- Nightly 50.0a1
- Test Pilot 0.8.1 -dev-53fe977

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to http://testpilot.dev.mozaws.net/
2. Observe the "Blok" experiment card icon on the Homepage.

[Expected result]:
The "Blok" icon has the right aspect ratio as the other experiments icons.

[Actual result]:
The "Blok" icon has a wrong aspect ratio.

[Notes]:
- The issue is also visible after installing Test Pilot on Main Page.
- The issue is not reproducible on experiment detailed page.

![blok icon aspect ratio](https://cloud.githubusercontent.com/assets/17258026/17061830/119a8b34-5039-11e6-8476-c4ec1935912e.png)

**Comment by johngruen** [comment]
Fixed
