### ISSUE TITLE
Media Request 

### ISSUE THREAD

**Issue by j1my3p1x** [mozilla/testpilot#1125]
I recently fell in love with this image ( https://raw.githubusercontent.com/mozilla/testpilot/master/testpilot/frontend/static-src/images/copter%402x.png ) seen on the [testpilot webpage](http://testpilot.firefox.com/). I've tried asking around (on Reddit) and searching (Reverse Google Images searches) but I haven't seen any HD or vector versions of the Firefox Test Pilot UFO. I was wondering if anyone had them, and if they do, if they could share them. 

Thank you, and I'm sorry if this is the wrong place to be asking.

**Comment by johngruen** [comment]
hey @j1my3p1x the image was made in photoshop. Here's a big PNG, lemmie know if you want it bigger. I didn't make the image, so I'm not sure if it's cool for me to share the source file

![test-pilot-logo](https://cloud.githubusercontent.com/assets/3323249/17252580/3dd7398a-557b-11e6-8fc6-0666c3f39162.png)

**Comment by johngruen** [comment]
We're triaging bugs so i'm gonna close this for now.

**Comment by j1my3p1x** [comment]
That's perfect, huge thanks! I really appreciate it.
