### ISSUE TITLE
Weird layout gap with even number of experiments in a row

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1131]
Found in http://testpilot.dev.mozaws.net/__version__ (e9e40d0052b61faa8017abf8f4716dd947d24039):

``` json
{ "commit": "e9e40d0052b61faa8017abf8f4716dd947d24039",
  "source": "https://github.com/mozilla/testpilot",
  "version": "",
  "build": "https://circleci.com/gh/mozilla/testpilot/647" }
```

---
### Actual results:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/17120953/c54bee5a-5284-11e6-840b-b09b077226d6.png)

**Comment by ckprice** [comment]
Fixed in #1226.
