### ISSUE TITLE
Remove SRI enforcement from the site

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1134]
SRI turns out to be trouble for 3rd party services that update their JS-include-based API hooks often - e.g. Pontoon, Google Analytics, Optimizely. The hashes change without notice, and SRI's rejection of resources has the potential for major site breakage.

Thought we needed SRI for security requirements, but can't find an email or bug mentioning it. So, since it seems more trouble than it's worth without better tooling (e.g. Issue #1121), let's remove it for now.

**Comment by jaredhirsch** [comment]
SRI still seems nice in general. What if we, instead, wire up an SRI error listener, and fire a special metrics ping if SRI fails for something? If we have stuff that just cannot break, like GA, we can fall back to self-serving the current snippet, which will likely work long enough to verify the changes and update the SRI hash using the /admin/ console.

**Comment by jaredhirsch** [comment]
Expanding a bit: the 'special metrics ping' could fire a 'bad but not critical' alert, notifying the team to take a look at the third-party script. I guess we would only want to fire this alert once per 24 hours per individual resource URL.

**Comment by fmarier** [comment]
> SRI turns out to be trouble for 3rd party services that update their JS-include-based API hooks often - e.g. Pontoon, Google Analytics, Optimizely.

Yes, SRI is not designed for that use case at all. It's for static files that don't change. For scripts that may change at any time, the best you can do right now is whitelist their origins via CSP.

> If we have stuff that just cannot break, like GA.

I hope you don't rely on GA to fire though because lots of people block it (e.g. everybody who goes into Private Browsing). See https://hacks.mozilla.org/2016/01/google-analytics-privacy-and-event-tracking/

**Comment by lmorchard** [comment]
> I hope you don't rely on GA to fire

Luckily, we have GA event calls wrapped in handlers to swallow errors if GA is blocked. (We figured that out the hard way.)

**Comment by jaredhirsch** [comment]
After some discussion in IRC, looks like the recommended approach is ye olde `onerror` attribute with inline function call:

```
<script src="..." onerror="onScriptLoadError()">
```

**Comment by lmorchard** [comment]
Submitted #1167 to cover possibly re-enabling SRI, since I think we're just going with disabling this for now. Would be nice to have it back, but probably good to get rid of the errors for now
