### ISSUE TITLE
variant error: this.experimentFeaturesChanged is not a function

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1135]
I'm unable to send variant data from universal search to test pilot.

[Here](https://github.com/mozilla/universal-search/pull/261/commits/89f536f346a24dd7f1d17143c7714f89a3ee858e) is a universal search commit that mostly contains variant-related code.

Each time I send the data over, I see this error in the browser toolbox console:

```
TypeError: this.experimentFeaturesChanged is not a function
Stack trace:
module.exports.onReceiveVariantDefs@resource://gre/modules/commonjs/toolkit/loader.js -> resource://testpilot-addon/lib/metrics.js:163:5
Observer<.observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/events.js:81:7
Search.prototype.fetchVariantData/sendPing@chrome://universalsearch-lib/content/universal-search.js:109:7
setTimeout_timer@resource://gre/modules/Timer.jsm:30:5
```

Looks like the value of `this` isn't properly bound at line 163 of lib/metrics.js.

**Comment by lmorchard** [comment]
😞
