### ISSUE TITLE
"Take the Tour" in Test Pilot always show a blank box

### ISSUE THREAD

**Issue by netoeuler** [mozilla/testpilot#1141]
- Operating system: Debian 8, 64 bits, all packages up to date
- Firefox build: Firefox ESR 47.0.1

![etst_pilot_bug](https://cloud.githubusercontent.com/assets/3870633/17182119/d4b08b6a-53f8-11e6-8906-b1e288b365e4.png)

**Comment by lmorchard** [comment]
On what site / URL did you see this? I don't think "Blok" is an existing experiment, and the tour will show up blank if there are no tour steps created.

**Comment by netoeuler** [comment]
No? It's showed in http://testpilot.dev.mozaws.net/experiments. Is it a fake URL?

**Comment by lmorchard** [comment]
Yeah, dev is definitely fake data. We've given more attention to the data on testpilot.stage.mozaws.net for QA purposes, but dev isn't guaranteed to have good content

**Comment by meandavejustice** [comment]
can we close this @lmorchard ?

**Comment by netoeuler** [comment]
But I was redirect to this link by the add-on that I get in https://testpilot.firefox.com/

**Comment by lmorchard** [comment]
> But I was redirect to this link by the add-on that I get in https://testpilot.firefox.com/

The add-on can be installed from testpilot.firefox.com, but it can be configured to use the dev environment - which seems to be the case here.

If you didn't intentionally configure the environment yourself, this could be a bigger issue

**Comment by netoeuler** [comment]
It was me that configured to use dev environment beacuse the default enviroment always sends to me to a blank page.

**Comment by lmorchard** [comment]
Okay, then that's why the add-on from testpilot.firefox.com is sending you to the dev environment. And the dev environment does not have real content. So, this is working as expected. You should switch your add-on back to production unless you are actually developing code for Test Pilot.

The blank page issue sounds like #1101, which should be resolved next Monday or so when we deploy the fixes
