### ISSUE TITLE
Add border to Just Launched cards when user does not have add-on installed

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1145]
# E Current:

![screen shot 2016-07-28 at 2 07 46 pm](https://cloud.githubusercontent.com/assets/3323249/17223938/cab87e54-54cc-11e6-8365-9cc4cc43aacb.png)
## Expected:

Just Launched cards should have the same blue border whether or not users have the Test Pilot add-on installed

**Comment by lmorchard** [comment]
<strike>I _think_ this was already covered in #1038 and https://github.com/mozilla/testpilot/commit/a9bc5085d3527cd23a0cdd69fedb23b0c2038b55 - we use the same card view, whether you have the add-on or not</strike>

Oh wait, you mean the border - then yeah that's a bug. Probably something in the CSS :/

**Comment by johngruen** [comment]
@lmorchard i this should also apply to 'just updated' experiments. I think it's a matter of flattening out the sass, but i can take this one if it's too annoying :)
