### ISSUE TITLE
Admin toggle for status of experiment

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1153]
Currently I have to enter in all of the correct content into the django admin and then hit save to display stuff on the Test Pilot site. I would like a checkbox  for each experiment that controls whether or not an experiment is displayed so that we can populate the various panels and check for typos without fear of accidentally posting the wrong content to the site.

**Comment by johngruen** [comment]
This was formerly titled `Toggle to display experiments in django admin`, but i changed to flesh out the ask a bit.

We should be able to update where an experiment is in its lifecycle in order to set it's position in UI.

Proposal for states: 
- draft (doesn't display)
- active (Displays)
- graduated (displays in graduated UI)

**Comment by ghost** [comment]
let's just use the launch date
