### ISSUE TITLE
HTTP 500 when installing Activity Stream experiment in a new profile

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1156]
Found in https://testpilot.firefox.com/__version__ (8e617b1298ab4827a566e0099bcc284a3713594b):

``` js
{ "version": "2016-07-15-1",
  "build": "https://circleci.com/gh/mozilla/testpilot/620",
  "source": "https://github.com/mozilla/testpilot",
  "commit": "8e617b1298ab4827a566e0099bcc284a3713594b" }
```

---
### Steps to reproduce:
1. Create a new profile.
2. Go to https://testpilot.firefox.com/ and install Test Pilot add-on.
3. Go to https://testpilot.firefox.com/experiments/activity-stream and enable experiment.
4. Open the dev tools console.
### Actual results:

> PUT **XHR** https://testpilot.firefox.com/api/experiments/2/installations/1a054c15-12bf-6143-ad3e-2631d257bbc6 [HTTP/1.1 500 INTERNAL SERVER ERROR 136ms]

![browser_console_and_firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/17262532/ca8bebc2-5590-11e6-8bf4-c7b68f84def1.png)

Seems like the add-on installed correctly, so not sure what the PUT was doing.

**Comment by lmorchard** [comment]
I _think_ we just fixed this with some manual SQL applied in production.
