### ISSUE TITLE
Onboarding new tab page should use correct env URL

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1159]
This is a [TODO](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L157) from [PR 1155](https://github.com/mozilla/testpilot/pull/1155#discussion_r72857565):

Rather than hard-code the production test pilot URL in the `openOnboardingTab` method, we should wait until the settings data is ready, then open the onboarding tab using the correct server environment base URL.

**Comment by lmorchard** [comment]
Fixed by https://github.com/mozilla/testpilot/commit/06f2605126949f942384fca5d6f8765441cc2cb4
