### ISSUE TITLE
Universal Search is not correctly uninstalled if Tab Center experiment is instaled before it 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1164]
[Affected versions]:
- Nightly 50.0a1
- Test Pilot 0.8.3 -tag-2016-07-29

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net page.
2. Click on the big green "Install the Test Pilot Add-on" button.
3. After the installation chose the "Tab Center" experiment and "Enable" it.
4. Return to "Experiments" page and choose the "Universal Search" experiment.
5. Enable it and after click on "Settings" button from top part of the page.
6. Choose to "Uninstall Test Pilot" and confirm the choice from "Proceed" button.
7. Observe the browser address bar after uninstall is finalized.

[Expected result]:
The browser address bar is split again in two different bars as default.

[Actual result]:
The browser address bar remains unchanged as if "Universal Search" experiment is still installed.

[Notes]:
- This only reproduces when "Tab Center" experiment is installed before Universal Search one.
- The "about:addons" page no longer displays any of the experiments as installed.
- Reproducible 5/5 tries. 
- Added a screen recording with the issue https://goo.gl/6DDrTi.

**Comment by chuckharmston** [comment]
Moved here: https://github.com/bwinton/TabCenter/issues/479
