### ISSUE TITLE
Tooltip color change on "Test Pilot" button after enabling "Tab Center" experiment

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1165]
[Affected versions]:
- Nightly 50.0a1
- Test Pilot 0.8.3 -tag-2016-07-29

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net page.
2. Click on the big green "Install the Test Pilot Add-on" button.
3. Observe the "Test Pilot" button from browser toolbar.
4. Chose the "Tab Center" experiment and "Enable" it.
5. Observe again the "Test Pilot" button from browser toolbar.

[Expected result]:
In both cases the "Test Pilot" button is displayed with a blue "New" tooltip over it.

[Actual result]:
Step 3 - the "Test Pilot" button is displayed with a blue "New" tooltip over it.
Step 5 - after "Tab Center" installation, the tooltip changes its color into red. 

[Notes]:
- Added a screen recording with the issue https://goo.gl/uCdqbH.

**Comment by ghost** [comment]
filing under tab center:  https://github.com/bwinton/TabCenter/issues/489

**Comment by bwinton** [comment]
As commented in the TabCenter issue, you can also replicate this by entering Customize mode, so I'm afraid this is actually a TestPilot bug, not a TabCenter bug.  (Uh, but I can't re-open it, so I'll leave that for someone else. 😉)

**Comment by dannycoates** [comment]
Seems related to https://bugzilla.mozilla.org/show_bug.cgi?id=1292981

There's no code in testpilot that changes the `badgeColor` to anything but a constant value.
