### ISSUE TITLE
Berberpole animation along with "Installing" text are not displayed for bottom page installation button

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1169]
[Affected versions]:
- Nightly 50.0a1
- Test Pilot 0.8.3 -tag-2016-07-29

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net page.
2. From the bottom of the page click on the big green "Install the Test Pilot Add-on" button.
3. Observe the button behavior.

[Expected result]:
- The button changes into "Installing..." and a "berberpole" animation is displayed under the text.

[Actual result]:
- "Berberpole" animation along with "Installing" text are not displayed for bottom page installation button.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/UKYA0J

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and is no longer reproducible.

**Comment by SoftVision-PaulOiegas** [comment]
Seems we have a regression here. Probably because of #1225.
Reopening issue.

**Comment by johngruen** [comment]
Can't repro on prod
