### ISSUE TITLE
Don't use `default` for name of docker-machine VM

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1172]
Docs currently have users create the Test Pilot VM with the name `default`, which is used by docker-machine whenever the machine_name argument is omitted in commands. That's a bit of an anti-pattern, and could cause problems with users not familiar with Docker who are  copy/pasting our instructions.

[As we do in Universal Search](https://github.com/mozilla/universal-search-recommendation/blob/master/docs/local.md), we should use give it an explicit name to avoid conflicts with other software projects.

**Comment by lmorchard** [comment]
In troubleshooting some things today, I uninstalled all things Docker from my machine and looked up the current version... [Looks like the latest Docker for Mac doesn't even use docker-machine anymore!](https://docs.docker.com/docker-for-mac/docker-toolbox/) So, I wonder if we should revise everything to favor that instead?

**Comment by ghost** [comment]
I have a patch changing the docs to that (mostly deleting steps) but I didn't get the SQL to run yet so I didn't submit the PR.  Gotta sort that out and then I'll have it

**Comment by ghost** [comment]
That PR is at https://github.com/mozilla/testpilot/pull/1177  .  Note that Docker for Mac _only_ has a `default` machine, so, that doesn't really solve this issue as filed, but I think it does address it.

**Comment by chuckharmston** [comment]
>  Note that Docker for Mac only has a default machine

Does that mean that it runs all containers inside of a single host VM as a design? If that's the case, we should probably make sure to namespace our containers.

**Comment by ghost** [comment]
I'm not a Docker pro, but that was my understanding from [the docs](https://docs.docker.com/docker-for-mac/docker-toolbox/):

> With Docker for Mac, you get only one VM, and you don’t manage it. It is managed by the Docker for Mac application, which includes autoupdate to update the client and server versions of Docker.

kinda seems like a step backwards, but I guess it is way simpler

**Comment by lmorchard** [comment]
> If that's the case, we should probably make sure to namespace our containers.

FWIW, `docker-compose` already does that, prefixing all the container names and the locally-built image names with `testpilot_`:

```
➜  testpilot git:(master) ✗ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                              NAMES
bc93ee623664        testpilot_server             "./bin/run-dev.sh"       3 hours ago         Up 3 hours          0.0.0.0:8000->8000/tcp                             testpilot_server_1
86db95fda4ba        postgres:9.3                 "/docker-entrypoint.s"   3 hours ago         Up 3 hours          5432/tcp                                           testpilot_db_1
f9be82590bbb        testpilot_frontend_watcher   "./bin/run-frontend-w"   3 hours ago         Up 3 hours          0.0.0.0:9966->9966/tcp, 0.0.0.0:35729->35729/tcp   testpilot_frontend_watcher_1
```

By default, it uses the name of the current directory as the project name for that prefix. You can also supply the project name with [the `-p` option](https://docs.docker.com/compose/reference/overview/), if you wanted to spin up a different independent set of services.

**Comment by ghost** [comment]
I don't think this is an issue with Docker for Mac anymore.  If it is, please reopen and let us know. :)
