### ISSUE TITLE
Webextension Telemetry pings aren't showing up in Telemetry

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1175]
Ilana looked for pings today from a "No More 404s" test[1] and didn't see any.  We've had the add-on installed and goofed around with it for the past week, so we should have seen a few pings at least.

I had the add-on installed last week and didn't see any pings in my about:telemetry.

Blok is also using the same code.  There weren't pings from Blok on the server either.  Luke is checking his about:telemetry.

[1] https://github.com/internetarchive/FirefoxNoMore404s/blob/master/src/scripts/background.js#L75

**Comment by lmorchard** [comment]
Was the experiment enabled from a local copy of Test Pilot? The main Test Pilot add-on won't listen for messages from anything but addon IDs in the list it gets from the server-side API. (see also #1029)

**Comment by ghost** [comment]
I pointed my Test Pilot add-on at stage, where No More 404s is configured and saw the pings in about:telemetry from it.  So, I think we're good here.  Thanks @lmorchard
