### ISSUE TITLE
The link for docker installation in linux part of README.MD (screenshot attached) leads to a 404 error page .

### ISSUE THREAD

**Issue by Akshay-Anand** [mozilla/testpilot#1176]
![screenshot from 2016-08-02 19 10 16](https://cloud.githubusercontent.com/assets/12967243/17351661/7b4a43b2-58e5-11e6-98ca-0349534539b9.png)

**Comment by meandavejustice** [comment]
Thanks for reporting @Akshay-Anand

**Comment by carolineh101** [comment]
Hello, I think I've found the link you may be looking for: https://docs.docker.com/engine/installation/linux/ubuntulinux/
May I go ahead and submit a pull request?

**Comment by Akshay-Anand** [comment]
carolineh101 Yes ,The link you have given is correct .Please submit the pull request  so that I  can close the issue.
