### ISSUE TITLE
Use Discourse input form templates

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1178]
Discourse supports new topic templates, similar to the Github new bug report templates:

https://meta.discourse.org/t/what-are-topic-templates/38295

The community IT manager mentioned this on IRC. We could use it to shape feedback and make it a bit less freeform on a per-experiment (that is, per-category) basis.
- [ ] create a topic template for Test Pilot discussions (could be a replacement for the idea submission form?)
- [ ] create a sensible experiment template that individual teams can customize to focus feedback
- [ ] update experiment author wiki docs to mention creating a template along with other stuff

**Comment by johngruen** [comment]
Yeah, this sounds like a nice idea. Let's do it!

**Comment by johngruen** [comment]
Soul: Crushed
