### ISSUE TITLE
Need better Discourse link for No More 404s experiment page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1183]
Re: https://testpilot.firefox.com/experiments/no-more-404s

Currently it looks like we're linking to the generic "Test Pilot" Discourse forum for No More 404s, but we should probably link to the specific No More 404s forum: https://discourse.mozilla-community.org/c/test-pilot/nomore404s

![firefox_test_pilot_-_no_more_404s](https://cloud.githubusercontent.com/assets/557895/17386274/f05ec732-599d-11e6-836b-8bd387a13bcf.png)

**Comment by johngruen** [comment]
Resolved
