### ISSUE TITLE
Fix Mark's bio picture on No More 404s

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1184]
![fullscreen_8_3_16__5_26_pm](https://cloud.githubusercontent.com/assets/557895/17386441/afab98d0-599f-11e6-8159-3cb0adc7c828.png)

``` html
<img class="avatar" data-hook="avatar" src="https://testpilot-prod.s3.amazonaws.com/users_userprofile/e/a/ea82410c7a9991816b5eeeebe195e20a_avatar_1470244527_0592.jpg" width="56" height="56">
```

![](https://testpilot-prod.s3.amazonaws.com/users_userprofile/e/a/ea82410c7a9991816b5eeeebe195e20a_avatar_1470244527_0592.jpg)
**Figure 1:** 187px by 213px. We probably want to resize to 213x213 so it's square and then fill w/ black background. Probably look "good enough" due to rounded radius, but still better than the skewed pic we have currently.

**Comment by pdehaan** [comment]
#### FEAR MY PHOTOSHOP SKILLS!

![mark-graham](https://cloud.githubusercontent.com/assets/557895/17386635/6b39da02-59a1-11e6-96e0-ac710f07db66.png)

| &nbsp; | PIC |
| --: | :-: |
| Before: | <img width="85" alt="firefox_test_pilot_-_no_more_404s" src="https://cloud.githubusercontent.com/assets/557895/17386565/da38e778-59a0-11e6-9fcb-dcb72637d173.png"> |
| After: | <img width="98" alt="untitled" src="https://cloud.githubusercontent.com/assets/557895/17386599/15013162-59a1-11e6-9b4f-0a67bace8cf5.png"> |

**Comment by johngruen** [comment]
Fixed
