### ISSUE TITLE
I have never been able to download the tab add-on.  I first tried about 8 months ago, and gave up.  I tried again today, and the "enabling" button starts flashing but never stops.  Thanks.

### ISSUE THREAD

**Issue by legalgal** [mozilla/testpilot#1191]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

If you're experiencing a bug in Test Pilot, please include the following information:
- [ ] Operating system
- [ ] Firefox build (Nightly, Developer Edition, Beta, Release)

---

If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by ghost** [comment]
This sounds like the same as #1189 so I'm going to close this in favor of that issue.  Feel free to follow along there.  Thanks!
