### ISSUE TITLE
Don’t ask to take a survey if that’s already done

### ISSUE THREAD

**Issue by SimonSapin** [mozilla/testpilot#1193]
- [x] Operating system: Arch Linux x86_64
- [x] Firefox build: Release 47, then 48 (distribution package)

---

In the last few days I was asked to rate Tab Center and complete a survey about it three times, even though I did it the first time.

**Comment by johngruen** [comment]
@meandavejustice 

@SimonSapin can you check the add-on version for Test Pilot? You can find this in about:addons. 

Thanks for the report!

**Comment by ghost** [comment]
I've also been prompted to rate Tab Center a few times in the past few days.  Jared is going to look at this.

**Comment by SimonSapin** [comment]
Test Pilot 0.8.3-tag-2016-07-29

**Comment by meandavejustice** [comment]
This is currently built to survey three separate times at the intervals, `twoDays`, `oneWeek`, `threeWeeks`, and `monthAndAhalf`.

@SimonSapin were you prompted at those intervals, or three times sooner than that?

**Comment by SimonSapin** [comment]
If I remember correctly I had been using Tab Center and Test Pilot for more than a month and a half before I was first prompted. There were a few days between the first and second prompt, but I believe less than five. The second and third prompts were on the same day. There hasn’t been a fourth so far.

Regardless of the timing, something should remember that I’ve already done what was asked, and so there is no need to ask again.

**Comment by jaredhirsch** [comment]
> something should remember that I’ve already done what was asked, and so there is no need to ask again.

IIRC the concept in showing the survey repeatedly was to see how users liked it over time. However, it seems like we may just be _annoying_ the users.

@johngruen do you want this bug to change the survey to just run once? Currently it runs every 2, 7, 21, 46 days--but we use client-side storage to keep track of when we've asked, so if the user uninstalls, then reinstalls, they'll get another survey 2 days later.

**Comment by SimonSapin** [comment]
> IIRC the concept in showing the survey repeatedly was to see how users liked it over time. However, it seems like we may just be annoying the users.

Yes. My opinion hasn’t changed within a couple days, and asking again really seems like the system has forgot that I already answered these questions. (I did not uninstall.)

Kinda like some websites:

[![](http://imgs.xkcd.com/comics/server_attention_span.png)](https://xkcd.com/869/)

**Comment by ghost** [comment]
Has anyone seen the too-many-surveys problem recently or is this fixed?

**Comment by ghost** [comment]
No replies from anyone seeing this so I think it's fixed.  Please holler if not.  Cheers!
