### ISSUE TITLE
Simplify experiment onboading tour

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1197]
This was feedback from @ckarlof:

He installed an experiment and saw this page:
![tour](https://cloud.githubusercontent.com/assets/16946141/17446777/bcd5f544-5aff-11e6-9d4c-1638249e6e3d.png)

And thought we could eliminate a click if we just dropped right into the tour.  If a person wants to skip it, they can skip it from step 1 instead of step 0.

**Comment by ckarlof** [comment]
Yeah, this provides some feedback for enabling the experiment, but it doesn't feel very inviting to take the tour. I'm assuming this is the same UX for all experiments. What's our success rate in getting people to take experiment tours?

**Comment by ckprice** [comment]
> What's our success rate in getting people to take experiment tours?

GA is saying we range from 65-68% of users who enable an experiment take the onboarding tour. Not terrible, but there's probably some room for improvement.

**Comment by sevaan** [comment]
Additionally, once a user is in the tour there is no way to exit it without completing the tour.

Working on this one.

**Comment by sevaan** [comment]
Revised Tour UX (5 Pages): https://mozilla.invisionapp.com/share/Q77S1H6ZC#/185342725_Current_UX_Issues

**Comment by johngruen** [comment]
@ckarlof we'll be happy to know we're going to work on this now.

**Comment by johngruen** [comment]
I'll do this on the plane tomorrow
