### ISSUE TITLE
Use "protected-branches" for master?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#120]
https://github.com/blog/2051-protected-branches-and-required-status-checks

If this sounds kosher, I can do this for this repo and our related addon repos (and universal-search).

Ref: https://github.com/mozilla/fxa/issues/61

**Comment by meandavejustice** [comment]
:+1:

**Comment by lmorchard** [comment]
One caveat - we don't have all checks passing yet. Coveralls still fails for reasons I haven't figured out. Need to make sure that doesn't stop us from merging PRs to master, or just disable Coveralls for now.

**Comment by ghost** [comment]
FWIW, we switched to [Codecov](https://codecov.io/) for the Push server. Happy to whip up a quick PR if you're interested.

_/me returns to lurking_

**Comment by pdehaan** [comment]
FWIW, it looks like _"Protect this branch"_ and _"Require status checks to pass before merging"_ are different settings, so we can enable them separately for the time being ([source](https://github.com/mozilla/idea-town/settings/branches/master)).

**Comment by lmorchard** [comment]
:+1: to protecting branches, but defer status check enforcement for now.

**Comment by pdehaan** [comment]
[**master** branch](https://github.com/mozilla/idea-town/branches) is now protected, but doesn't enforce any status checks [yet].

Closing.
