### ISSUE TITLE
Cannot install Universal Search or Activity Stream from their respective Test Pilot pages

### ISSUE THREAD

**Issue by BoffinBrain** [mozilla/testpilot#1202]
OS: Windows 7 Ultimate 64-bit
Firefox version 48.0

I'm not sure if this is a specific issue with the 2 tests, or the Test Pilot website/addon itself. When I try to install Universal Search or Activity Stream, the button gets stuck on 'Enabling' forever. When installing Tab Center and No More 404s, it works correctly.

I have tested this on a blank Firefox profile with no other addons installed and got the same results for all four tests. Two worked and the other two did not.

I had a peek at the network and console tabs in dev tools, but didn't see anything obviously wrong there. I assume it's something internal to the addon.

**Comment by BoffinBrain** [comment]
May be related to https://github.com/mozilla/testpilot/issues/1192 but note that No More 404s works fine for me.

**Comment by ghost** [comment]
Can you be specific about what order you are trying to install the add-ons in?  We're trying to debug something with Tab Center breaking other add-ons, but we haven't seen this anywhere else.  Thanks.

**Comment by BoffinBrain** [comment]
There is no specific order. I tried installing both of them in different orders, with and without the other experiments installed. I have even refreshed the test profile and tried again today, with the same results. I can install Tab Center but not Universal Search.

I have attached the profile I used for testing. It's a blank profile with Test Pilot installed and history turned off. If you load this profile and it works for you, then I'm baffled!

[test-pilot-profile-win7.zip](https://github.com/mozilla/testpilot/files/416728/test-pilot-profile-win7.zip)

I'm using Kaspersky Total Security 16 and it isn't alerting to anything.

**Comment by SoftVision-PaulOiegas** [comment]
This is related to https://github.com/bwinton/TabCenter/issues/479 that is reproducible.
Before you had to uninstall Tab Center in order to break the Universal Search install. But now it breaks even if you install Tab Center first and after you try to install Universal Search.

**Comment by ghost** [comment]
Is this still reproducible?

**Comment by BoffinBrain** [comment]
Yes, still reproducible on my blank profile here, using the latest Test Pilot and Firefox 49.0.

When I try now, instead of waiting forever, I get an 'uh-oh' error message pop up, but other than that, the same experiments fail to load. In the screenshot, you can see Tab Center and No More 404s are enabled (they were successfully installed during this session) while Universal Search has failed.

![stillbroken](https://cloud.githubusercontent.com/assets/13255058/18400545/4f4a8aa4-76ce-11e6-8ec7-65c4bec70ac4.png)

**Comment by SoftVision-PaulOiegas** [comment]
Hey, as mentioned in #1269, we have a bunch of issues that seem related to environment setup or 3rd party software. Maybe your issue is related to firewall or antivirus settings too. 
Can you test this from a different machine and let me know of the results ? Or, if you have some spare time, even poke a bit the firewall or antivirus settings to see if this changes after.

**Comment by BoffinBrain** [comment]
Wasn't able to repro on my Windows 7 Professional box using Firefox 49.0. This machine is on a domain with a corporate proxy and McAfee AV and all experiments installed fine. I will test my laptop later.

**Comment by BoffinBrain** [comment]
OK, I wasn't able to repro on my Windows 10 laptop either, using two different versions of FF. I guess my main install is just garbled somehow! Still won't install Universal Search or Activity Stream on 50.0b3.

**Comment by ghost** [comment]
Ok.  Maybe try making a new profile?  Thanks for following up.
