### ISSUE TITLE
Cannot download addon due to a connection failure

### ISSUE THREAD

**Issue by gaby2300** [mozilla/testpilot#1204]
Using Windows 7 64 bit and  Nightly in a new profile. 
Trying to install the TestPilot addon I get the following: The addon cannot download because of a connection failure. My Internet connection work fine, that's why I don't understand the motive of this issue. 

 I am adding the screencast for you to see

---

Update: edited to remove the binary screencast file. Please embed a Dropbox or other link rather than attaching binary files, thanks - Jared (@6a68)

**Comment by meandavejustice** [comment]
Thanks for the report @gaby2300, would you mind posting a screencast which can be viewed in browser?

**Comment by gaby2300** [comment]
Hi @Dave, I tried to upload a non zipped file but it wasn't supported. If
you could please tell me how can I obtain a screencast as you request, I
will be happy  to do it!

Many thanks!
Best regards,
Gabriela
QA Mozilla Hispano Team Responsible

**Comment by SoftVision-PaulOiegas** [comment]
Hi Gaby, maybe upload a supported video format on Google Drive or Dropbox and post the share link here ? I'm doing the same with my screencasts for issues and I'm using screncast-o-matic for recording my desktop.

**Comment by gaby2300** [comment]
Hi Paul, will do as soon as I can, thanks!

**Comment by gaby2300** [comment]
Hi Paul, here you are!  Very sorry for my delay!

https://drive.google.com/open?id=0Bz7G9PmM_MT7S1lrZ2VBbjBfWmM

I think you'll have to download it first though.

**Comment by SoftVision-PaulOiegas** [comment]
Sorry Gaby but I totally forgot about this issue. I've finally made to open your video and tried the same steps at the job and also at home, but sadly, I cannot reproduce this on my end. 

What version of Firefox are you using ? If it's an older one, can you please update to the latest 48.0.2 release and retest this on a clean new profile (https://goo.gl/PNe90E) ? Maybe something that you have installed in the browser can affect this, or any custom preferences set.

Also, another guy had a similar problem with one of the experiments inside Test Pilot. He had a firewall setup on his company that didn't allowed him to install one of the experiments. 
Is it possible by any chance that you could have something like that setup or any antivirus that could block you in downloading the Test Pilot add-on ?

**Comment by gaby2300** [comment]
Hi Paul, you were right! It was an antivirus related issue. I changed it's configuration and the problem was fixed. Many thanks for your help!

**Comment by SoftVision-PaulOiegas** [comment]
You welcome ! Glad we sort it out. :smiley:

**Comment by SoftVision-PaulOiegas** [comment]
One more thing Gaby. What antivirus client are you using and what was the setting that caused this ?  This could help us in debugging other issues that may appear related to this one.

**Comment by gaby2300** [comment]
Hello Paul,

My antivirus is ESET, Nod 32. The setting I changes was the one about the
SSL's protocol scan, I disabled it according to the following steps:
http://support.eset.com/kb3126/

I hope this will useful to you and other users facing similar problems, I
am always happy to help!

**Comment by delixyr** [comment]
[Adguard](https://github.com/AdguardTeam/AdguardForWindows) https filtering also cause the same issue.

**Comment by SoftVision-PaulOiegas** [comment]
@delixyr Are you still encountering this issue with Adguard ? 
We recently deployed a fix for the antivirus clients issue. If you still encounter this using the latest add-on version, we might need to test with this too in order to expand the fix.
