### ISSUE TITLE
Move list archives to google groups

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1207]
This is not the most user-friendly archive website:

https://mail.mozilla.org/pipermail/testpilot-dev/2016-May/thread.html

It would be really nice to have a google groups-compatible list, regardless of the underlying implementation.

**Comment by jaredhirsch** [comment]
Looks like google groups still supports NNTP: https://support.google.com/groups/answer/6003482?hl=en

This was used to provide a nice web interface to old skool usenet lists like dev-webdev: https://groups.google.com/forum/#!forum/mozilla.dev.webdev

**Comment by jaredhirsch** [comment]
Seems relevant (need to find followup link w/final IT decision): https://blog.mozilla.org/it/2012/12/02/discussion-forums-redux-paths-forward/

**Comment by ghost** [comment]
Closing due to discourse move
