### ISSUE TITLE
Hidden close button when disabling an experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1209]
I uninstalled the Blok experiment (on dev), and it prompted me to take a survey, with seemingly no way to opt-out. Turns out the "Close" button was just white-on-white and impossible to read.

<img width="769" alt="firefox_test_pilot_-_blok" src="https://cloud.githubusercontent.com/assets/557895/17488883/3d606fa8-5d50-11e6-9aeb-1bd29961b4a5.png">

**Comment by SoftVision-PaulOiegas** [comment]
Cannot reproduce, the issue seems to be fixed.
