### ISSUE TITLE
After fresh install, the "Test Pilot" add-on toolbar icon is grayed out if browser window is not focused

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1215]
[Affected versions]:
- Nightly 51.0a1
- Test Pilot 0.8.3 -tag-2016-07-29

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Use a clean profile without Test Pilot add-on installed.

[Steps to reproduce]:
1. Go to http://testpilot.dev.mozaws.net and install Test Pilot add-on.
2. Observe the Test Pilot icon from the main toolbar.
3. Click outside the browser window to remove the focus from it.
4. Observe again the Test Pilot icon from the main toolbar.

[Expected result]:
- The Test Pilot icon is displayed in black color even if browser window is focused or not.

[Actual result]:
- The Test Pilot icon is displayed in black color but becomes grayed out when browser window is not in focus.

[Notes]:
- This issue is visible only for a few minutes after installation. 
- I have observed a similar behaviour on Windows 7 x64. After installation, hovering the Test Pilot icon changes its color to gray instead of displaying the hover selection overlay.
- Added a screen recording with the issue https://goo.gl/7aFvHz.

**Comment by dannycoates** [comment]
The dimming comes from:

``` css
#toggle-button--testpilot-addon-testpilot-link.toolbarbutton-1:-moz-window-inactive:not(:hover) {
  opacity: 0.5;
}
```

which I adapted from [browser.css](https://github.com/mozilla/gecko-dev/blob/master/browser/themes/osx/browser.css#L1091) that I now realize is platform specific 😭 

I could use some help here. This seems to be above my UI skill level.

**Comment by SoftVision-CosminMuntean** [comment]
This issue was verified on the latest Test Pilot dev add-on, and is no longer reproducible. Tested with the latest Nightly (51.0a1) build and the latest Firefox (48.0) release.
