### ISSUE TITLE
Firefox displays the loading spinner in poor quality

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1217]
[Affected versions]:
- Nightly 51.0a1
- Test Pilot 0.8.3 -tag-2016-07-29

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Go to http://testpilot.dev.mozaws.net on Firefox browser.
2. Refresh the page and observe the loading spinner displayed until page content is loaded.

[Expected result]:
 The loading spinner appears and animates with no display issue each time content is loaded. 

[Actual result]:
The loading spinner appears when content is loaded but has poor quality.

[Notes]:
- The issue is present on every page that requires loading time.
- This issue is not reproducible on Chrome browser.
- Added a screen recording with the issue https://goo.gl/WcdOrL .

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas can this be reproduced in other FF versions...my guess is this is an upstream rendering issue in nightly.

**Comment by SoftVision-PaulOiegas** [comment]
Not really, yesterday I verified this on release (48.0) and it has the same poor quality. 
Right now I did a double check on latest Beta (49.0b2), dev edition (50.0a2) and also on latest nightly with e10s disabled and got the same result.

On Mac OS and Ubuntu 14.04, latest Nightly correctly displays the loading spinner. So it's platform dependent on Windows.

**Comment by SoftVision-PaulOiegas** [comment]
While testing on an even older version of Nightly (44.0) observed that the animation runs smooth. Did a regression window for this and managed to narrow the bad revision. Here is the pushlog https://goo.gl/7KA0L0 . I'm betting on issue https://goo.gl/s4B5mo to be the one that broke this. 
If you guys think the same, let me know and I'll contact the developer from that issue to see what can be done.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas yeah, that looks like the issue. I'm gonna back out the spinner for now and replace it with something a bit less complex

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas I changed the layout of the loader...can you still see the degradation on dev or stage?

**Comment by SoftVision-PaulOiegas** [comment]
No, the new loader looks crispy clear. :smiley:

**Comment by SoftVision-PaulOiegas** [comment]
Talked with the dev on https://goo.gl/s4B5mo and he told me that he already fixed a regression of that fix in https://bugzilla.mozilla.org/show_bug.cgi?id=1292856 on . 
If you guys still want that loading spinner back, maybe we can re-add it on production to check if something changed after his fix ?
