### ISSUE TITLE
Use the amazing new mozAddonManager API

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1223]
Ok, using something newer than Firefox 48 (I think) go to about:addons, click "Get Add-ons" in the menu on the left and then enable/disable some add-ons that you see there.  See how amazing and easy it is to enable add-ons?  We want that!

Good news!  [Bug 1288178](https://bugzilla.mozilla.org/show_bug.cgi?id=1288178) gave testpilot.firefox.com access to that API.  We're going to try to get it uplifted -- if we get it into beta, it will go live on **Sep 13** for general release users.  That means we'll need to do some detection to support the old method of installing as well as the new method.  That can be done with `if (navigator.mozAddonManager)`.

Before this will work on our site, we'll need to ensure that the add-on .xpi URLs live on testpilot.firefox.com/files/.  [Bug 1291357](https://bugzilla.mozilla.org/show_bug.cgi?id=1291357) is taking care of proxying that to our CDN, but we'll still have to get the other files up there.

I'm filing this bug a bit early to get it on the radar and mark it as needs:ux in case we want to adjust our install buttons at all to be more similar to the disco pane sliders.

/cc @johngruen @sevaan

**Comment by lmorchard** [comment]
Going to call #990 a retroactive dupe of this one, since there's way more info here.

**Comment by ckprice** [comment]
This is ready in Nightly. Confirmed that we're not changing UX.

**Comment by ghost** [comment]
Also uplifted to aurora and beta
