### ISSUE TITLE
Only detect desktop Firefox

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1233]
Noted by Jared [on a pull request](https://github.com/mozilla/testpilot/pull/1225/files/aa9a687b557711cbcf48ff2fb06d5f745babb154#r74461827):

We currently use [Firefox detection](https://github.com/mozilla/testpilot/blob/35802081bee163996b6766d8d119de769284e321/testpilot/frontend/static-src/app/views/landing-page.js#L21) that will false-negative on Fennec. We should improve that to only offer the add-on on desktop Firefox.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

**Comment by johngruen** [comment]
Is this a dupe of #672

**Comment by chuckharmston** [comment]
Yep.
