### ISSUE TITLE
Measurements for TXP-17 Allow Users to explore experiments before installing Test Pilot

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1237]
Based on our [new feature metrics documentation](https://github.com/mozilla/testpilot/blob/master/docs/README-FEATURE-METRICS.md).

**Formulate the question**
- it should measure the Rate of install from details page
- it should measure rate at which non-firefox users download firefox from the details page
- It should measure the rate of experiment activation from the details page

Tasks
- [x] Add public experiment detail page (#1225)
- [x] Add social links in footer? (#294)

**Comment by ckprice** [comment]
# Add public experiment detail page (#1225)

### Capturing the "Install Add-on" click on the experiment detail page

![experiment detail page install](https://d3vv6lp55qjaqc.cloudfront.net/items/2u3k1i2X1r0V2k0d0v0F/Image%202016-08-15%20at%2011.39.34%20AM.png?v=8c3c6a69)

This will require a `sendToGA` event.

For reference this is [the install add-on event call on the home page](https://github.com/mozilla/testpilot/blob/3bdaa14c648f6fe3a01a1ba995450c76ac91a5ed/testpilot/frontend/static-src/app/views/landing-page.js#L56)

```
app.sendToGA('event', {
      eventCategory: 'HomePage Interactions',
      eventAction: 'button click',
      eventLabel: 'Install the Add-on',
      outboundURL: downloadUrl
});
```

Referencing our [GA Table of Events documentation](https://github.com/mozilla/testpilot/blob/master/docs/README-GOOGLE-ANALYTICS.md#table-of-events), here is what the new event will look like (please also update this document)

| Description | eventCategory | eventAction | eventLabel |
| --- | --- | --- | --- |
| Click on Install from experiment details page | ExperimentDetailsPage Interactions | button click | Install the Add-on |

### Updating `pageview` event on the experiment details page

We'll want to update this pageview call to include whether or not the user has the add-on installed. This is via the custom dimension (`dimension1`).

Referencing our [GA Custom Dimensions documentation](https://github.com/mozilla/testpilot/blob/master/docs/README-GOOGLE-ANALYTICS.md#custom-dimensions), here is what the updated pageview row will look like with the Experiment Detail Page added (please also update this document)

| Page | Description | Dimension | Value |
| --- | --- | --- | --- |
| Home Page, Experiment Detail Page | Does the user have the add-on installed | 1 | {0,1} |

Reference on [how the home page is capturing this](https://github.com/mozilla/testpilot/blob/c7b26ca714a4bb9633cc5b724fca907f3fa665a2/testpilot/frontend/static-src/app/views/experiment-list-page.js#L26).

### Capturing the clicks on the "Try out these experiments as well" section (`ExperimentDetailsPage`)

![experiment list](https://d3vv6lp55qjaqc.cloudfront.net/items/3F0M0J1l1A0l2r1z171P/Image%202016-08-15%20at%2011.59.02%20AM.png?v=ba87abb8)

Referencing our [GA Table of Events documentation](https://github.com/mozilla/testpilot/blob/master/docs/README-GOOGLE-ANALYTICS.md#table-of-events), here is what the new event will look like (please also update this document)

| Description | eventCategory | eventAction | eventLabel |
| --- | --- | --- | --- |
| Click on the "Try out these experiments as well" section | ExperimentDetailsPage Interactions | button click | try out {experiment_title} |

### Capturing the clicks on the "Try out these experiments as well" section (`HomePage`)

Referencing our [GA Table of Events documentation](https://github.com/mozilla/testpilot/blob/master/docs/README-GOOGLE-ANALYTICS.md#table-of-events), here is what the new event will look like (please also update this document)

| Description | eventCategory | eventAction | eventLabel |
| --- | --- | --- | --- |
| Click on experiment from landing page | HomePage Interactions | Open details page | {experiment_title} |

/cc @garethcull

**Comment by chuckharmston** [comment]
@ckprice One thing I see that could be missing: clicks on this section (on the homepage) also need logged ~~may benefit from an indicator of whether or not the user has the add-on installed~~, since it's now possible to navigate from there.

![screen shot 2016-08-17 at 8 26 08 am](https://cloud.githubusercontent.com/assets/23885/17740006/433ce73e-6454-11e6-9850-b21d5213fd35.png)

**Comment by ckprice** [comment]
@chuck this is happening already [here](https://github.com/mozilla/testpilot/blob/9ffb36833d373ab68c09934f1d090d7b21659de0/testpilot/frontend/static-src/app/views/experiment-row-view.js#L147), but could use some refinement. I added another section to my comment at the bottom 'Capturing the clicks on the "Try out these experiments as well" section (`HomePage`)'.

**Comment by chuckharmston** [comment]
@ckprice yep, I tried to refine it in #1225, where I pinged you for review. There are three different places where we show a clickable experiment list now:
- On the homepage to users without the add-on
- On the experiments page to users with the add-on
- On the experiment detail page to users without the add-on

I instrumented those separately in [this commit](https://github.com/mozilla/testpilot/pull/1225/commits/8bea6f47d4bde218007fa081798e2c0b92416c09), though it deviates from what you put here, so I wanted to get your eyes on it.

**Comment by ckprice** [comment]
That's fine. I updated my comment to match your code - the analysis side is the same.

Verifying the sends now.

**Comment by ckprice** [comment]
# Add social links in footer? (#294)

We'll need `sendToGA` calls with `outboundURL` configured to the social property URL ([reference](https://github.com/mozilla/testpilot/blob/master/docs/README-GOOGLE-ANALYTICS.md#samples-of-event-structures)).

Referencing our [GA Table of Events documentation](https://github.com/mozilla/testpilot/blob/master/docs/README-GOOGLE-ANALYTICS.md#table-of-events), here is what the new events will look like (please also update this document)

| Description | eventCategory | eventAction | eventLabel |
| --- | --- | --- | --- |
| Click on the Test Pilot GitHub button | Footer Interactions | button click | goto GitHub |
| Click on the Test Pilot Twitter button | Footer Interactions | button click | goto Twitter |
