### ISSUE TITLE
The "View all experiments" button is not entirely visible if a new experiment is enabled

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1239]
[Affected versions]:
- Nightly 51.0a1
- Test Pilot 0.8.5 -tag-2016-08-11

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Test Pilot add-on is installed on a clean profile.
- No new experiments are enabled on the used profile.

[Steps to reproduce]:
1. Click the "Test Pilot" button from browser toolbar.
2. Click on a new experiment (eg: NoMore404s).
3. Click on the "Enable" button for the experiment.
4. After the experiment is enabled click the "Test Pilot" button from browser toolbar and observe the bottom part of the displayed door-hanger.

[Expected result]:
- The list with the available experiments is correctly displayed. 

[Actual result]:
- The "View all experiments" button is not entirely visible.  placed a few pixels downward  

[Notes]:
- This issue occurs because enabled new experiments have three lines of text instead of two which forces the button to move lower then the designed container space.
- Added a screenshot with the issue: 
  ![view all experiments button](https://cloud.githubusercontent.com/assets/19226534/17620925/876f22b0-6098-11e6-8243-a47d83448c49.png)

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean nice grab...we should  not show the `New Experiment` string if the experiment is enabled
