### ISSUE TITLE
Scroll becomes jumpy and footer links are not accessible when zooming out or in on specific pages from Test Pilot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1240]
[Affected versions]:
- Nightly 51.0a1
- Test Pilot 0.8.5 -dev-9ffb368

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Test Pilot add-on is installed on a clean profile.

[Steps to reproduce]:
1. Click the "Test Pilot" button from browser toolbar.
2. Click on Blok experiment.
3. Change the page zoom at 110%.
4. Scroll the page.

[Expected result]:
- Scrolling is correctly performed untill the bottom of the page and footer links can be accessed.

[Actual result]:
- Scroll becomes jumpy at the bottom of the page and footer links cannot be accessed.  

[Notes]:
- Added a screen recording with the issue: https://goo.gl/FelVl4

**Comment by SoftVision-CosminMuntean** [comment]
The issue is also reproducible on the Firefox release.
I have also tested on Mac OS and I have managed to reproduce it with the latest Nightly build, and latest release.

**Comment by meandavejustice** [comment]
I don't know if we want to support different zoom levels

**Comment by ghost** [comment]
I can't reproduce this on Nightly + Linux.  But the video does look pretty bad

**Comment by meandavejustice** [comment]
~~Still seeing this is dev edition, will test in nightly and post gif in the AM~~

Seeing this on version 51.0a2 Dev Edition
zoom level: 100% (and others)

same as gif in https://github.com/mozilla/testpilot/issues/1087#issuecomment-250291236

**Comment by johngruen** [comment]
Fixed by #1588

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on dev server. I have retested this using the latest Firefox (49.0.1) and latest Nightly (52.0a1) build.
