### ISSUE TITLE
The "New experiment" string is wrongly redisplayed after disabling a new experiment

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1242]
[Affected versions]:
- Nightly 51.0a1
- Test Pilot 0.8.5 -tag-2016-08-11

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Test Pilot add-on is installed on a clean profile.
- A new experiment is enabled on the used profile.

[Steps to reproduce]:
1  Click the "Test Pilot" button and observe the new experiment status.
2. Restart the browser.
3. Open again the experiments doorhanger and observe the experiment status.
4. Open the new experiment and choose to disable it.
5. Open again the experiments doorhanger and observe the disabled experiment status.

[Expected result]:
Step 1. The experiment has enabled string displayed.
Step 3. The experiment remains unchanged.
Step 5. The experiment has no string displayed.

[Actual result]:
Step 1. The experiment has both New experiment and enabled strings displayed.
Step 3. The experiment has only enabled string displayed and changes its position in the list.
Step 5. The experiment has again the New experiment string displayed and moves back to the top of the list.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/x22yVg

**Comment by dannycoates** [comment]
@johngruen #1241 won't fix this. In order to stop showing an experiment as new again once you've removed it we'll have to keep track of experiments that you've uninstalled.

**Comment by ghost** [comment]
the New badge is tied to a date.  This is expected behavior.
