### ISSUE TITLE
error on java script

### ISSUE THREAD

**Issue by MassivesoundZ** [mozilla/testpilot#1245]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

If you're experiencing a bug in Test Pilot, please include the following information:
- [ ] Operating system
- [ ] Firefox build (Nightly, Developer Edition, Beta, Release)

---

If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by pdehaan** [comment]
@MassivesoundZ Do you remember what the specific error message was?
