### ISSUE TITLE
UI Leading Up to Experiment Graduation

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1247]
### String Tracking Doc

https://docs.google.com/document/d/1VL7UoumVNV_8vzUoXQEYo7fyprSOFwzjqXIL8BhzDnc/edit?ts=57b1c452#

Strings in mock ups aren't final
### One Week Out

https://mozilla.invisionapp.com/share/Q77S1H6ZC#/181298063_One_Week_Out
### One Day Out

https://mozilla.invisionapp.com/share/Q77S1H6ZC#/181298064_One_Day_Out
### Closing Day

https://mozilla.invisionapp.com/share/Q77S1H6ZC#/181298065_Day_Of_Closing

Happy to break this down further if we want

**Comment by dannycoates** [comment]
Closing in favor of #1301 #1302 and #1303
