### ISSUE TITLE
experiment-detail page: experiment not rendering?

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#125]
This is what I see when I click an experiment on the /home page:

<img width="1387" alt="screenshot 2015-10-05 17 49 57" src="https://cloud.githubusercontent.com/assets/96396/10297546/823f2d76-6b89-11e5-927c-bd3c9b8951a3.png">

Might be just me, but if I revert the 2nd scratchpad PR, the experiment loads ok.

Need to investigate + fix.

**Comment by jaredhirsch** [comment]
Looks (on my machine) like the page is, indeed, not rendering. The `page-container` element seems to be empty:

<img width="1247" alt="screenshot 2015-10-05 18 00 09" src="https://cloud.githubusercontent.com/assets/96396/10297670/f2fa844c-6b8a-11e5-8ef0-664efb70315d.png">

**Comment by lmorchard** [comment]
fixed with https://github.com/mozilla/idea-town/commit/4c5e24075fdcfd50a18c649d2b3811330f56d04d (I presume)
