### ISSUE TITLE
Make Experiment Details Pages Fully Responsive

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1251]
Now that we've made these things visible without logging it, we're going to need them to be responsive.

**Comment by sevaan** [comment]
Need authenticated and unauthenticated versions for details page.

**Comment by chuckharmston** [comment]
@johngruen @sevaan Cutting it close on this one, any chance we could get UX for this on Wednesday? I should be able to fit it in then.

**Comment by sevaan** [comment]
John, the UX on Invision good to go? You mentioned some text wasn’t right, but I don’t think that needs to be reflected in the UX…it’s more about the layout.
https://mozilla.invisionapp.com/d/main#/console/7882387/182507370/preview
https://mozilla.invisionapp.com/d/main#/console/7882387/182507371/preview

**Comment by johngruen** [comment]
@chuck the first link is how pages should look w/the add-on and the second link is without.

@sevaan The logged out page is higher priority here, but the logged in case is a bit more complex...here are questions about both pages. Also note that the 'details' section for logged in experiments is missing in the logged in mockups, but presumably would go at the bottom with all the other experiment details.
- [ ] what does it look like if the browser is not firefox?
- [ ] how do we handle status bars on the logged in page, my guess is let's get rid of the sticky header on responsive widths

@chuck, the reflowing sevaan is proposing is a little complex. possible to do

**Comment by johngruen** [comment]
also @chuck and @sevaan 'logged in' === 'add-on installed' in my comments above

**Comment by johngruen** [comment]
@sevaan pro tip, you have to paste in the share links from invision, otherwise ppl can't see them unless they have an account!

https://mozilla.invisionapp.com/share/Q77S1H6ZC#/182507371_Mobile_Responsive_-_Not_Authenticated

https://mozilla.invisionapp.com/share/Q77S1H6ZC#/182507370_Mobile_Responsive_-_Authenticated

**Comment by sevaan** [comment]
Updated!

_Mobile:_

Mobile Responsive - Authenticated:
https://mozilla.invisionapp.com/share/6S8DTJMRB

Mobile Responsive - Not Authenticated:
https://mozilla.invisionapp.com/share/CA8DTYIRW

Mobile Responsive - Active Experiment:
https://mozilla.invisionapp.com/share/HD8DU82CQ

Mobile Responsive - Non-FX: https://mozilla.invisionapp.com/share/6B8DTYFPN

_Tablet:_

Tablet Responsive - Authenticated:
https://mozilla.invisionapp.com/share/JE8DTYURX

Tablet Responsive - Not Authenticated:
https://mozilla.invisionapp.com/share/K88DTZ44Z

Tablet Responsive - Non-FX: https://mozilla.invisionapp.com/share/EB8DTZ2RC

Tablet Responsive - Active Experiment:
https://mozilla.invisionapp.com/share/DX8DU8BPR

**Comment by johngruen** [comment]
@sevaan I asked Chuck to hide the details content on the small pages b/c it's not really actionable and saves a ton of work. Looks good to me, you should be able to review on dev once this gets merged.

**Comment by chuckharmston** [comment]
This should be reviewable on dev now: http://testpilot.dev.mozaws.net/experiments/universal-search
