### ISSUE TITLE
Switch to a single, central notification queue

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1252]
Straw plan for moving push notifications away from django while maintaining some flexibility: 
- Instead of having per experiment push notifications, we should simply have single central push notification scheduler that accepts the following:
- message
- time to send
- click thru URL
- some kind of selector to determine if the push should be sent only to (a) people using a particular experiment, (b) people not using a particular experiment experiment, (c) all users

The same rules would still apply WRT not pushing to users based on scheduled pushes before their install date.

How does this sound?

**Comment by lmorchard** [comment]
We could do this pretty much like we do in the experiments, just with a single "feed". That is, a JSON resource with an array of candidate notifications. Then we can filter in the add-on to decide which to show - i.e. based on date to detect new & unseen items, flags for experiment enabled / disabled, etc. That keeps the server rather dumb (good since we're moving away from Django) and puts the smarts in the add-on.

**Comment by johngruen** [comment]
@dannycoates would it be possible to filter notifications depending on if a user does or does not have a particular experiment installed... I could also open this in a new issue @ckprice

**Comment by dannycoates** [comment]
> would it be possible to filter notifications depending on if a user does or does not have a particular experiment installed

sure

**Comment by dannycoates** [comment]
I think until we're fully django / db-free it doesn't make sense to break out notifications into its own thing as most of the work to do it will get thrown away. Here's what I propose:
1. keep notifications with experiments in the db as is
2. switch to experiments.json, keep notifications attached to experiments
3. then break out notifications

**Comment by ghost** [comment]
We're going to delay this until we're on flat files.

**Comment by johngruen** [comment]
Leaving this alone for now, pending figuring out what's going on with SDK notification text issues

**Comment by johngruen** [comment]
Ref #1309
