### ISSUE TITLE
No more 404s + e10s breaks expensify.com Web site

### ISSUE THREAD

**Issue by karlcow** [mozilla/testpilot#1256]
- [x] Mac OS X 10.11.6 (15G31)
- [x] Firefox Nightly 51.0a1 (2016-08-16)

The issue template doesn't have any specific repository for "No More 404s" add-on, therefore filing here. It took time for us to isolate the issue on webcompat.com but we finally nailed it down to the "No More 404s" add-on.
1. Install "No More 404s" add-on
2. Go to the site https://expensify.com/

The site is broken and doesn't display the CSS and JS which are compressed assets. The add-on seems to tamper with network data in e10s window.

You can see the details of the issue at:
https://github.com/webcompat/web-bugs/issues/3026

The "No more 404" add-on + non-e10s window is working.

**Comment by chuckharmston** [comment]
Closing in favor of the bug you filed on the NoMore404s repo: https://github.com/internetarchive/FirefoxNoMore404s/issues/46

Thanks for the report!
