### ISSUE TITLE
Add integration test for add-on install flow via public experiment pages

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1257]
In PR #1225, we're adding another add-on installation button. We should create an integration test to assert that this works.

**Comment by b4handjr** [comment]
Public experiment page means what exactly?

**Comment by lmorchard** [comment]
Hmm, this issue is old enough that I think it dates back to when we had Firefox Accounts login - so public/logged-out versus logged-in. 

I think the ask in this issue now is to ensure that the main add-on gets successfully installed from individual experiment pages (i.e. versus the home page)
