### ISSUE TITLE
Present email opt-in after installing from an experiment detail page

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1259]
STR:
- Have Test Pilot uninstalled.
- (currently this is only on dev) Configure your add-on environment to dev.
- Visit an experiment detail page e.g. http://testpilot.dev.mozaws.net/experiments/activity-stream
- Install Test Pilot.
- Detail page refreshes except you now have Test Pilot installed.

Expected Result:
- Email opt-in modal is presented to the user.

Actual Result:
- No email opt-in modal is presented to the user.
- If a user browses away from Test Pilot, then hits the homepage later, the modal appears.

I _think_ this is the "Expected Result" we want. @chuckharmston @johngruen thoughts?

**Comment by chuckharmston** [comment]
This would be a pretty simple fix.

However, when the user installs Test Pilot from a detail page, it seems like a pretty strong signal of intent that they want to install the experiment presented on that page. I'm not sure we should get in their way.

**Comment by johngruen** [comment]
@chuckharmston yeah, we would be...but only very temporarily and it's skippable. I think it's a fair tradeoff
