### ISSUE TITLE
Header should contain clickable 'home' link

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#126]
We've got a FF logo and the heading 'Idea Town' at the top of the small header and the expanded header. Seems like those should be clickable, and should take the user back to `/home`.

<img width="434" alt="screenshot 2015-10-05 18 01 05" src="https://cloud.githubusercontent.com/assets/96396/10297686/310055be-6b8b-11e5-9dab-67f3f65792ea.png">

<img width="301" alt="screenshot 2015-10-05 18 02 16" src="https://cloud.githubusercontent.com/assets/96396/10297689/3a5b69e6-6b8b-11e5-8400-2d63c32194c0.png">

**Comment by pdehaan** [comment]
This looks broken again. Looks like it changed in https://github.com/mozilla/idea-town/pull/225

![idea_town_and_feat_landing-page___let_users_know_idea_town_is_still_wip_by_johngruen_ _pull_request__225_ _mozilla_idea-town_and_mozilla_idea-town_ _github](https://cloud.githubusercontent.com/assets/557895/11351291/b327a030-91ea-11e5-8b7e-3991bf8896d3.png)
