### ISSUE TITLE
Newsletter sign up pop up is wrongly displayed without installing Test Pilot add-on

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1265]
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Go to https://testpilot.dev.mozaws.net page.
2. Click on the big green "Install the Test Pilot Add-on" button.
3. Close the doorhanger request for installation.
4. Scroll down on the page and click on one of the experiments cards.
5. Observe the page behavior.

[Expected result]:
- User is redirected to the selected experiment details page.

[Actual result]:
- User is redirected to the selected experiment page but the pop up for newsletter signup is also displayed.

[Notes]:
- The newsletter pop up should be displayed only after add-on installation.
- The issue also occurs when trying to install the add-on from an experiment details page and after another experiment page is opened.
- Added a screen recording with the issue https://goo.gl/U1GHBm .

**Comment by chuckharmston** [comment]
I can't reproduce this locally (dev seems to be down, so I can't check there).

@SoftVision-PaulOiegas when you were testing this, did you set the value of the `testpilot.env` config to `dev` before installing the addon? You'll get unexpected behavior if that isn't congruent with the environment in which you're testing.

I'm going to close for now, as I'm reasonably certain that was the problem here. Feel free to reopen if it's still reproducible.)

**Comment by SoftVision-PaulOiegas** [comment]
I can still reproduce this on testpilot.dev and it has nothing to do with the environment pref because you don't need to install it to reproduce this. To be sure I have set the pref before trying to reproduce this and got the same result.
I was testing it on dev server since it's the only one who has the experiments details page available without installing the Test Pilot add-on.

All you need to do is click on install button, close the install doorhanger and after just click on one of the experiments cards from homepage. The newsletter pop up will magically appear as in my screen recording

**Comment by chuckharmston** [comment]
Ah, I misunderstood; when you said "Close the doorhanger request for installation" I thought you meant "hit allow". Fix incoming.

**Comment by SoftVision-PaulOiegas** [comment]
Seems fixed. Cannot reproduce it even if I hammered the functionality from all sides on both Nightly and Release builds :smiley: .
