### ISSUE TITLE
Test Pilot Legacy users update page is not displayed when updating from 1.2.3.4 to 1.2.3.7 old add-on versions

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1270]
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Firefox browser with a new clean profile.
2. Install Test Pilot 1.2.3.4 old build from attached archive with drag and drop on the browser.
3. Restart the browser when prompted and observe its behavior.
4. Install the second old build 1.2.3.7 from the archive and restart when requested.
5. Observe the browser behavior after restart.
6. Go to "about:addons" page and search for Test Pilot add-on.

[Expected result]:
- Step 3: the browser is restarted re-displaying the tabs that were opened before restart.
- Step 5: the browser is restarted, previously opened tabs re-displayd and Test Pilot legacy page is displayed.
- Step 6: both add-ons were uninstalled and no longer displayed in "about:addons" page. 

[Actual result]:
- Step 3: the browser is restarted re-displaying the existing tabs before restart.
- Step 5: the browser is restarted, previously existing tabs re-displayd but Test Pilot Legacy page is not displayed.
- Step 6: both add-ons were uninstalled and no longer displayed in "about:addons" page. 

[Notes]:
- Installing just the 1.2.3.7 add-on version correctly displays the Legacy update page after restart and also uninstalls the old add-on version.
- Attached a screen recording with the issue https://goo.gl/Nx922e . 
- Attached old builds archive https://goo.gl/jbqqkP .

**Comment by ghost** [comment]
I can reproduce this on Linux.  If I put a `return` in before the add-on uninstalls itself, the add-on works fine for me every time, so I think it's some kind of a race condition.

**Comment by SoftVision-PaulOiegas** [comment]
Way better with the new provided add-on v1.2.3.8. 
Here's a screen recording of the update process http://goo.gl/WI38JD

**Comment by ghost** [comment]
Cool, thanks.  Calling this fixed.

For the record: was fixed by adding a couple timeouts.  Unclear on where the race condition existed in Firefox, and easier not to deal with it. :)
