### ISSUE TITLE
Graduation "Ending Soon" UI

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#1271]
Implement the first part of #1247 

https://mozilla.invisionapp.com/share/Q77S1H6ZC#/181298063_One_Week_Out

**Comment by dannycoates** [comment]
@johngruen where should the "Ending Soon" text go when there's a subtitle? There's not much space left.
<img width="368" alt="screen shot 2016-08-22 at 6 01 01 pm" src="https://cloud.githubusercontent.com/assets/87619/17876832/8c12114a-6892-11e6-8bf5-450a2d672b4a.png">

Updated:
<img width="353" alt="screen shot 2016-08-22 at 7 57 00 pm" src="https://cloud.githubusercontent.com/assets/87619/17878851/c00ba56e-68a2-11e6-848d-c2aecd9aa301.png">
Maybe it's not _so_ bad.

**Comment by dannycoates** [comment]
OMG, special case text for 'tomorrow'...

![why](http://i.giphy.com/kyrd72DC2Iwfu.gif)

**Comment by dannycoates** [comment]
@johngruen where's the "Learn more" link supposed to go?

**Comment by johngruen** [comment]
@dannycoates I was thinking that field could just be hand written in the admin/yaml that replaces it, but the link would go to whatever we do in #1249. Might be fine to just point it to /about

**Comment by dannycoates** [comment]
wip here: https://github.com/dannycoates/gemini/tree/graduation

expect a PR this afternoon
