### ISSUE TITLE
Allow public users to sign up to be notified

### ISSUE THREAD

**Issue by nchapman** [mozilla/testpilot#128]

**Comment by meandavejustice** [comment]
Does this need anything separate from the splash site?

**Comment by lmorchard** [comment]
So, we'd discussed a kind of invite system for the site on initial launch. Goes something like this:
- Anyone can sign up/in via Firefox Accounts. 
  - This creates an account that can be active or inactive. We might want to use the Django `is_active` User flag, if possible.
- Users with a mozilla.com email address get auto-activated and allowed into the general site. (#27)
- Users with non-mozilla.com email addresses
  - See a "coming soon" page inspired/based on the splash site, but cannot access the general site.
  - Can have their accounts later activated by us from the Django admin pages.
  - On activation, users should get an email notifying that they're in (#129)

We should probably also explore what to do when we go to general launch, and presumably activate all the signed up accounts.
