### ISSUE TITLE
Add integration tests for experiment enable / disable

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1281]
We should implement an integration test that:
- [ ] Ensures the main add-on is installed
- [ ] Navigates to an experiment page
- [ ] Enables the experiment
- [ ] Asserts that the experiment add-on was installed
- [ ] Asserts that the frontend indicates the experiment is enabled
- [ ] Disables the experiment
- [ ] Asserts that the experiment add-on was uninstalled
- [ ] Asserts that the frontend indicates the experiment is disabled

Probably easiest to create a minimal "hello world" add-on as a mock "experiment" and see how that works. This should also help mitigate some e10s concerns raised in #1277, because eventually we can run the integration test suite against many versions of Firefox

**Comment by b4handjr** [comment]
Is it still advised to create a mock addon?

**Comment by lmorchard** [comment]
> Is it still advised to create a mock addon?

Maybe? Or if it's easier to just grab one of whatever experiments are currently live and use that, that seems fine. I think the notion here was to untangle the site's experiment installation from whatever issues might arise from the experiment itself. But, that might be too much hassle for what shouldn't often be an issue

**Comment by b4handjr** [comment]
I am working on this as it is one of my goals this quarter. I will be using https://github.com/mozilla/FoxPuppet to interact with the browser chrome. I will probably write a pytest-plugin to help with this as well. 

I currently have the 2 tests working, just need to get Foxpuppet updated and the plugin created.

**Comment by chuckharmston** [comment]
We have a nice suite of integration tests, closing this.
