### ISSUE TITLE
Subscribe new users to testpilot mailing list

### ISSUE THREAD

**Issue by nchapman** [mozilla/testpilot#129]

**Comment by meandavejustice** [comment]
We may have another issue for tracking this, but I'm not seeing it. @nchapman Where can I look for updates to idea-town mailing list status? I imagine this will come after any tweaks on the name. But would be nice to have this for internal launch for other users that stumble in.

**Comment by meandavejustice** [comment]
reassigning this to @clouserw to continue the discussion.

**Comment by clouserw** [comment]
I think this is talking about a mailing list that doesn't exist right now?  What would be the purpose of the mailing list?

**Comment by lmorchard** [comment]
Currently, we have an auth system that lets you sign up / log into Test Pilot with FxA. If you don't have an *@mozilla.com email address, your account is set to inactive and you're shown a "coming soon" kind of message.

So, in effect, the "mailing list" is the set of email addresses of inactive accounts. Presumably, we'd notify them when they can come back and actually use Test Pilot. 

We don't have a tool to actually email those people yet, though. But, that was the notion for doing an internal launch followed by opening up incrementally to a larger audience. We could set progressively bigger sets of inactive accounts as active and notify them as we go.

(Oh, and there's also code to auto-activate vouched mozillians.org users as active, but I think there was some discussion to keep that turned off for now.)

**Comment by lmorchard** [comment]
We'd also had some discussion about having an actual google-groups-style mailing list for announcements and such, but I think we drifted away from that a bit

**Comment by clouserw** [comment]
Got it, thanks.  Based off of that comment I'm going to close this issue -- it sounds like it has expired.  The addresses with an inactive account aren't a mailing list.  When we want to email them we could write a tool, or we could just run a query and export the addresses to a text file.  Once we figure out how we want to handle the accepting-new-users flow we can sort that out.  Thanks!
