### ISSUE TITLE
Privacy information not shown on non-Firefox browsers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1290]
In Firefox, this is what I see when I scroll:

<img width="959" alt="firefox_test_pilot_-_activity_stream" src="https://cloud.githubusercontent.com/assets/557895/17988036/6649d57c-6ad8-11e6-8cef-a1990d5960ab.png">

But if I try and view the same [Activity Stream]() page in Chrome, I don't see the experiment Privacy content:

<img width="959" alt="firefox_test_pilot_-_activity_stream" src="https://cloud.githubusercontent.com/assets/557895/17988044/729477c4-6ad8-11e6-9d7b-ec717cbeff70.png">

---

Even though I'm currently using Chrome, I may still be interested in the experiment and the privacy notice.

**Comment by chuckharmston** [comment]
That's [by design](https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/169082794). We only show that info to users with the Test Pilot add-on installed.

**Comment by pdehaan** [comment]
Fair enough. I'll agree to disagree.

As a user, even before I install the main add-on or experiment it's likely that I'd want to know about my data privacy and probably want to see the repo/code and discourse info.

<details>
<summary>

**Disclaimer:** I'm creepy and weird.</summary>


![](https://media.giphy.com/media/hmDutUmwiZgcw/giphy-facebook_s.jpg)
</details>

**Comment by chuckharmston** [comment]
> Disclaimer: I'm creepy and weird.

Can't argue that.

CC @johngruen to make sure he sees this feedback.
