### ISSUE TITLE
Cannot install experiments on Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1291]
... but the twist is that PageShot (in theory) will support Chrome, per the repo: https://github.com/mozilla-services/pageshot/

> `./bin/run-chrome-builder` will build the Chrome version of the add-on in `build/chrome-extension/`, and watch for changes and rebuild as necessary.

Possibly (probably?) not worth the effort of building all the logic of some experiments being Firefox+Chrome compatible, but thought I'd throw this out there.

**Comment by ghost** [comment]
Test Pilot is focused on testing new features in Firefox currently.  I'm going to wontfix this.  Thanks.
