### ISSUE TITLE
Installation doorhanger is dismissed at second installation attempt when previously closed from "(x)" button

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1293]
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Go to https://testpilot.stage.mozaws.net page and choose to "Install the Test Pilot Add-on".
2. When prompted by the browser, choose to "Allow" the installation. 
3. After download is complete click the close "(x)" button from doorhanger top right corner.
4. Choose again to "Install the Test Pilot Add-on" and allow the installation.
5. Observe doorhanger behavior.

[Expected result]:
- After the download is complete, the doorhanger presents the options to "Cancel" the installation or to "Install" the downloaded add-on.

[Actual result]:
- After download is complete, the doorhanger is dismissed. The user has to manually open it again by clicking the extension icon in the left side of the address bar to proceed with installation.

[Notes]:
- If the user closes several times the installation from "(x)" button, afterwards he we'll be able to cancel the installation only if he clicks on "Cancel" button as many times as the doorhanger was closed from "(x)" button.
- This issue also occurs if the user tries to install the add-on from different pages.
- Added a screen recording with the issue http://goo.gl/hFxVto .

**Comment by ghost** [comment]
I think #1223 will fix this also

**Comment by SoftVision-PaulOiegas** [comment]
Nope, it seams that this is a Firefox issue after all. The same behavior occurs with AddBlock. Closing this.
