### ISSUE TITLE
The Github and Twitter icons from Test Pilot Privacy and Terms pages don't have the same colour as the bottom links

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1298]
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open the browser and navigate to "https://testpilot.stage.mozaws.net" page.
2. Scroll to the bottom of the page and observe the color of the footer pages links and social media share buttons.
3. Click on "Privacy" or "Terms" page links.
4. Scroll to the bottom of the page and observe the color of the footer pages links and social media share buttons.

[Expected result]:
- Both the footer pages links and social media share icons are displayed in white color over blue background. 

[Actual result]:
- The footer pages links are displayed in blue color over white background, while the social media sharing icons are displayed in gray color over white background.

[Notes]:
- Added a screen shot with the issue.

![bottom iscons](https://cloud.githubusercontent.com/assets/19226534/18055169/77335fc2-6e0f-11e6-9cbf-97ac1cdb5059.png)

**Comment by atiqueahmedziad** [comment]
@SoftVision-CosminMuntean I am getting nothing on Privacy or terms page. Would you kindly check?
![capture](https://cloud.githubusercontent.com/assets/8364578/18411318/b540738c-7796-11e6-841d-ac244629a208.JPG)

**Comment by sevaan** [comment]
This bug doesn't need UX. Those assets are SVGs and so can be coloured with CSS. Can we please have the logos on those pages coloured #0996f8?

Also, the Mozilla logo on that page is not the correct share of blue. It should also be #0996f8, but is instead #1587bf. It is a png however, so ideally should be replaced with an SVG which I'm sure we have somewhere and coloured via CSS as well.

In case that's not possible, I've created a new blue Mozilla logo asset, attached.

![mozilla-blue](https://cloud.githubusercontent.com/assets/473531/18526085/24f933c8-7a8d-11e6-83ec-af13809924c4.png)
