### ISSUE TITLE
Closing day addon elements

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#1303]
On the closing day of an experiment active users will be prompted for feedback and the panel will treat the completed experiment differently as shown here: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/screens/181298065

**Comment by dannycoates** [comment]
I hate the "Hey" badge. As a Firefox user and busy person (as we all are) having a toolbar button yell "Hey" at me is first going to make me wonder what the hell that means then next make me confused and angry that it bothered me for something so trivial: "Hey! Not that it's urgent or anything, but this experiment is over. How does it affect you? It doesn't really. I just thought I'd distract you long enough for you to forget what you were doing."

I think the best way to inform folks and ask for feedback is via email. They'll be in email-mode and maybe even have a minute to take the survey. If they miss it they can discover it on their own without the badge. I'm less hostile toward the one time new tab notification, although I think it'd be nice to have a "remind me later" option or something attached to it.

**Comment by chuckharmston** [comment]
> having a toolbar button yell "Hey" at me is first going to make me wonder what the hell that means

https://youtu.be/f6Zq9OJr0xM
