### ISSUE TITLE
Implement Github webhook driven deployment for static content

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1305]
For our static content, we'd like on-demand build & deployment from a branch-per-environment on Github. So, if we have branches named `production`, `staging`, and `development`, those should get built & deployed to the appropriate server when new commits are pushed to each. (FWIW, `development` could also just be `master`)

Static content includes all our experiment pages & images, as well as frontend JS & CSS. We'll still need a Django API server & database around until #1039 has a solution for deriving usage counts from metrics. 

We should work out a way to separate the static content deployment from API server deployment. API changes should be rare compared to content updates.

Not sure what options for deployment have been discussed. Currently we bundle everything up into a Docker server image. But, pure static content could be just uploaded to an S3 bucket. Kind of an open question, here.

**Comment by lmorchard** [comment]
Also for the sake of not blocking here - I think we can safely assume that something like this will work for a build script when we're done with everything else in this milestone:

```
npm install
npm run build
```

As long as we have node, we'll be able to kick off Gulp (or whatever) and have a directory of ready-to-deploy content (e.g. `dist`). So, hopefully we can talk about deployment as how to trigger builds and where it needs to go after.

**Comment by pdehaan** [comment]
At what point do we just deploy to GitHub pages? (which I think now you can do from a /docs/ subfolder instead of needing to be a weird specific branch)
https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

**Comment by lmorchard** [comment]
> At what point do we just deploy to GitHub pages?

There are a number of reasons we probably never want to do literally that, the security of Firefox being one of them - though there's a whole discussion to be had there :) But we do have a pile of things that need building which GitHub Pages won't support.

**Comment by dannycoates** [comment]
Also

> HTTPS is not supported for GitHub Pages using custom domains

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by lmorchard** [comment]
https://github.com/mozilla/testpilot/commit/847e4a60d7111adb838db5eadf78062e6a6f8cba
