### ISSUE TITLE
Implement static page rendering with progressive enhancement

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1306]
Probably way too big an issue to file as such, but here goes:

We should build a static HTML rendering of all pages - experiment pages, legal pages, everything - in a way that works for most browsers.

Then, when the JS kicks in and we detect Firefox, we can flip on/off relevant bits. Same goes for whether we do or don't detect the Test Pilot add-on as installed.

Ideally, it would be great if we could statically render React templates and dynamically render the JS-dependent bits also within React. Not-as-ideally, we could render the base cases with something like Jekyll and then sprinkle in React magic after load.

**Comment by lmorchard** [comment]
Also, possibly blocked by #1307 (React conversion) unless we want to jump straight at Jekyll / Liquid Template rendering.

Prior art: https://github.com/chuckharmston/testpilot-flatfiles

**Comment by fzzzy** [comment]
I'm actually most of the way done with this at https://github.com/fzzzy/testpilot/tree/remove-react-router , so I'll close this as a dup of https://github.com/mozilla/testpilot/issues/2260
