### ISSUE TITLE
Convert to React views & Redux state management from Ampersand views & models

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1307]
This work in progress has been merged into the [development-static](https://github.com/mozilla/testpilot/tree/development-static) branch and [is auto-deploying](https://circleci.com/gh/mozilla/testpilot/tree/development-static) to https://testpilot-static.dev.mozaws.net

if you set `testpilot.env` to `static-dev` in about:config, [this environment](https://testpilot-static.dev.mozaws.net) should fully work. Anything not listed as a known issue in the TODOs below is something new and needs to be fixed - so feel free to edit this & add to the list!

To run the [development-static](https://github.com/mozilla/testpilot/tree/development-static) branch locally, just check it out and then run this:

```
cd addon
npm install && npm run package
cd ..
npm install
while [ 1 ]; do NODE_ENV=development gulp; sleep 1; done
```

Docker is no longer needed. Just build the add-on and start up gulp. The while loop is to re-start gulp when it exits, which it will do if it sees edits to gulpfile.js or build tasks.

**Note**: If you get an ["Unexpected token" error](https://pastebin.mozilla.org/8909837) when trying to run gulp, make sure you're running at least Node v6.2.0.

Remaining TODOs:
- [x] Auto-deployment does not invalidate CloudFront distribution, so things stay stale after deployment
- [x] Links in Settings menu do the wrong things, retire flow is broken.
- [x] Port over [the new mozAddonManager code](https://github.com/mozilla/testpilot/commit/2c570b23840c1afbf06a298c39f3cdd8375c99f6) for add-on installation
- #1349 <strike>[ ] Try building with React in production mode, to be sure everything still works</strike>
- #1350 <strike>[ ] Update docs to describe new static generation & React architecture. No more Docker.</strike>
- #1351 <strike>[ ] Frontend tests - port over existing? start fresh with [Mocha](https://mochajs.org/) + [Enzyme](http://airbnb.io/enzyme/)?</strike>

**Comment by johngruen** [comment]
@lmorchard: settings menu should only appear if the user has the add-on installed

**Comment by lmorchard** [comment]
> settings menu should only appear if the user has the add-on installed

That's what I'm seeing... are you seeing something different?

**Comment by dannycoates** [comment]
I also see settings without the addon

**Comment by ckprice** [comment]
Can't see a couple GA events/pageviews firing
- Viewing the home page without the add-on installed ([ref](https://github.com/mozilla/testpilot/blob/6bd599eb1c3396883a7a98acaf6671dd49e03132/frontend/src/app/views/landing-page.js#L39)).
- Clicking `Proceed` on retiring modal and going to the retire page ([ref](https://github.com/mozilla/testpilot/blob/6bd599eb1c3396883a7a98acaf6671dd49e03132/frontend/src/app/views/retire-page.js#L45)).
- Viewing the experiment detail pages ([ref](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/views/experiment-page.js#L266)).

Eh, looks like there are no `pageviews` sends in the branch.

Think that's it.

/edit I'm putting together a commit for this.

**Comment by johngruen** [comment]
@dannycoates @lmorchard I wonder if this could be some kind of issue with the groundcontrol add-on. I can't repro on a clean profile

**Comment by johngruen** [comment]
@lmorchard having a bit of trouble seeing the 'add-on installed' state on this branch

STR:
- Create a new profile in dev edition
- Turn xpi signatures off 
- go to localhost:8000
- install the add-on
- I see the secondary onboarding tab fire, but no redirect to /experiments
- go to about:config
- set the testpilot.env to `local`
- refresh
- still see the add-onless landing page when i refresh localhost:8000

**Comment by lmorchard** [comment]
@johngruen So, localhost:8000 won't work - you still have to use testpilot.dev:8000, because there's no recognized environment for localhost in the add-on. 

Also, you have to set testpilot.env to local before you try installing the add-on. None of the events involved in telling the web frontend about add-on installation will work if that env is not set ahead of time.

All of this applies to both this React branch and the current Django master.

**Comment by johngruen** [comment]
@lmorchard yeah that's what i figured, but when i go to testpilot.dev:8000 (w/ or w/o add-on) i get a timeout.

<img width="869" alt="screen shot 2016-09-13 at 11 21 56 pm" src="https://cloud.githubusercontent.com/assets/3323249/18491955/30acc61e-7a09-11e6-9442-a8f2cb9663a7.png">

**Comment by lmorchard** [comment]
Are you running Docker at the same time? (shouldn't be) What does Gulp say when it starts up? At some point it should say "Server started http://0.0.0.0:8000". And also you should still have testpilot.dev in your /etc/hosts from Docker setup

**Comment by johngruen** [comment]
@lmorchard yes to all:
docker not running, terminal reporting gulp server correctly...
in /etc/hosts i have
`192.168.99.100 testpilot.dev`

**Comment by lmorchard** [comment]
> yes to all, in /etc/hosts i have 192.168.99.100 testpilot.dev

Okay, that needs to be changed to:

```
127.0.0.1 testpilot.dev
```

[We recently changed that when we moved the project to use Docker for Mac](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md#os-x-hosts)

**Comment by johngruen** [comment]
@lmorchard that did it. thank you!

**Comment by dannycoates** [comment]
When a download fails the button remains in the enabling state.

<img width="440" alt="screen shot 2016-09-13 at 2 54 14 pm" src="https://cloud.githubusercontent.com/assets/87619/18492859/57a0f714-79c2-11e6-9186-625854f1963f.png">

**Comment by dannycoates** [comment]
> When a download fails the button remains in the enabling state.

I get the feeling some of the things in `this.state` of ExperimentPage.js like `isEnabling` would be better as props managed by redux so that actions from outside can easily change them... @lmorchard @chuckharmston ?

**Comment by chuckharmston** [comment]
@dannycoates What do you mean? Still haven't dug into this PR, but whether state or props (99% of the time if there's a question you should be using state*), you'd want to set up an event handler in this app that fires the action when told to by the add-on.

\* That is to say, the connected components should be passing state down to children as props.

**Comment by dannycoates** [comment]
> What do you mean?

Sorry, my inexperience with React (jargon) is making it more difficult to communicate. 

In this particular case take a look at the usage of `isEnabling` in [ExperimentPage.js](https://github.com/mozilla/testpilot/blob/development-static/frontend/src/app/components/ExperimentPage.js). Since its "local" to the Component when a [download-failed](https://github.com/mozilla/testpilot/blob/development-static/frontend/src/app/lib/addon.js#L133) message arrives from the addon it can't automatically update the ui. If `isEnabling` were somewhere in the redux store it seems to me that it'd be easier for the change to propagate. 

I hope that made _some_ sense

**Comment by lmorchard** [comment]
Hmm, there _is_ an [`inProgress`](https://github.com/mozilla/testpilot/blob/development-static/frontend/src/app/lib/addon.js#L136) on experiments in the redux store. But, it looks like I didn't end up using it on the experiment page - [I just use it as an index for finding the last experiment being installed, if I can't find it another way](https://github.com/mozilla/testpilot/blob/development-static/frontend/src/app/lib/addon.js#L113)

But yeah, `inProgress` could be used to turn off local `isEnabling` / `isDisabling` state here. Or, it could make sense to actually move those two flags into the redux store

**Comment by johngruen** [comment]
Here's one: experiments are sorted alphabetically, they should be sorted by `experiment.id`

**Comment by lmorchard** [comment]
> Here's one: experiments are sorted alphabetically, they should be sorted by experiment.id

Cool, that should be a one-liner to fix. The ID is a manual thing in YAML now, so we can use that for manual sorting.

**Comment by lmorchard** [comment]
This is merged to master, now. 🎉 

Let's file additional issues / submit PRs against master from here.
