### ISSUE TITLE
Notification without a title.

### ISSUE THREAD

**Issue by mhoye** [mozilla/testpilot#1309]
I get this notification: /edit by ckprice http://i.imgur.com/N6p3C3W.png

in Nightly on OSX (Both current latest) and that seems like it's not the right thing.

Clicking that directs me to the No More 404s test pilot page - No More 404s is the only Test Pilot add-on I have installed.

**Comment by digitarald** [comment]
I have the same issue (empty notification) but don't have No More 404 installed

**Comment by ckprice** [comment]
I've deleted the current notification until this is investigated.

**Comment by lmorchard** [comment]
@ckprice - Did you happen to get a screenshot of the notification in admin before it was deleted? I never saw it, would help to diagnose things

**Comment by lmorchard** [comment]
Seems like [our code](https://github.com/mozilla/testpilot/blob/master/addon/lib/experiment-notifications.js#L109) called the SDK notification library correctly: A notification was displayed with our hardcoded "via testpilot.firefox.com" and clicking it went to the right experiment URL. But, it seems like [the notification we randomly picked](https://github.com/mozilla/testpilot/blob/master/addon/lib/experiment-notifications.js#L102) had an empty or undefined title & text. Not sure how that would happen. Could the random array index come up with something empty if there's just one notification?

[I've got a PR open to add unit tests for notifications](https://github.com/mozilla/testpilot/pull/1297), but nothing like this came up in there. Would be very handy to reproduce this issue in a test (after someone reviews & merges that PR pretty please!) and see about fixing it

**Comment by lmorchard** [comment]
For good measure, [I just added a unit test to my PR that works with just one notification](https://github.com/mozilla/testpilot/pull/1297/files#diff-2b3639e8f7a812b3bddbfc4edcb2e0fdR87). That's as close as I can come to what happened in this issue off the top of my head. Bad news is, the test didn't reproduce this issue. So, I still don't know what happened.

**Comment by ckprice** [comment]
> Did you happen to get a screenshot of the notification in admin before it was deleted? I never saw it, would help to diagnose things

No, sorry 😞 It was a dup of the last one - copied the two fields from the existing notification.

**Comment by dannycoates** [comment]
@lmorchard I saw the json from https://testpilot.firefox.com/api/experiments before it was deleted. It looked fine to me:

``` json
{
          "id": 2,
          "title": "Tired of 404s?",
          "text": "Check out our latest experiment!",
          "notify_after": "2016-08-29T20:15:45Z"
}
```

**Comment by lmorchard** [comment]
Poked at this over the last couple of hours, and can't reproduce the issue locally - neither in a unit test nor in adding a notification to my local server. Can anyone else reproduce it in a controlled environment? If not, then we don't have an explanation or a fix so far

**Comment by dannycoates** [comment]
I've also tested this locally and can't reproduce. I think @johngruen had a theory yesterday that it's css/theme related... It'd be really helpful to get the `utm_content` from the querystring of one of these.

**Comment by lmorchard** [comment]
> I think @johngruen had a theory yesterday that it's css/theme related...

Well, the weird thing with that is our "via testpilot.firefox.com" shows up, which is just a hardcoded string [we tack on before `notification.text`](https://github.com/mozilla/testpilot/blob/master/addon/lib/experiment-notifications.js#L112) to give some context and fake the look of a web push notification. It should get blanked out too if it's a CSS thing, I'd think

**Comment by dannycoates** [comment]
Maybe the `utm_content` is still in @mhoye or @digitarald history? Mine looks like this:

<img width="1102" alt="screen shot 2016-08-30 at 10 41 09 am" src="https://cloud.githubusercontent.com/assets/87619/18106610/7184af18-6eb9-11e6-913e-281526926cc6.png">

**Comment by digitarald** [comment]
Same URL in my history: `https://testpilot.firefox.com/experiments/no-more-404s?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=push+notification&utm_content=2`

**Comment by ckprice** [comment]
Opened #2303 to test this on Stage. The notifications target users who have the experiment installed, and it pops after a browser restart.

**Comment by ghost** [comment]
We're going to remove the notifications feature.
