### ISSUE TITLE
Receiving incompatible browser version disclaimer despite using correct version.

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#1314]
I just loaded up Test Pilot in the latest Firefox release, 48.0.2, and noticed I'm still receiving an incompatible version warning on the experiment details pages.

![screen shot 2016-08-31 at 9 34 58 am](https://cloud.githubusercontent.com/assets/473531/18130802/785f7926-6f5e-11e6-98a3-e0534940ff7c.png)

**Comment by SoftVision-PaulOiegas** [comment]
Duplicate of #1208 ...
