### ISSUE TITLE
/legacy page needs `pageview` event

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1315]
### Create `pageview` event on the /legacy page

We'll want to add a `pageview` event to this page sending along `dimension1`, `dimension2` and `dimension3`.

```
app.sendToGA('pageview', {
  'dimension1': this.hasAddon,
  'dimension2': anyInstalled,
  'dimension3': installedCount
});
```

These dimensions will give us information on the types of users that are sharing.

Referencing our [GA Custom Dimensions documentation](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#custom-dimensions), we'll want to add `Legacy Page` to the 3 mentioned dimension rows and update the docs.

@clouserw not sure if this page will be relevant next sprint (or if you have a different way to track views), but we can capture views through GA with this. Feel free to close this out if we don't need it.

**Comment by ghost** [comment]
Thanks for filing, but I don't think we need this.  We're on the downhill side of the campaign at this point so this wouldn't do much for us.
