### ISSUE TITLE
Share page seems almost comically tall

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1316]
Found in http://testpilot.dev.mozaws.net/__version__ (a81d93b4a83dab398adec033e44386c598d82d37):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/903",
  "version": "",
  "commit": "a81d93b4a83dab398adec033e44386c598d82d37",
  "source": "https://github.com/mozilla/testpilot" }
```

---
### Steps to reproduce:
1. Go to http://testpilot.dev.mozaws.net/share
2. Scroll
3. Realize you had to scroll to see the entire page.
4. Question why we need to scroll vertically when you're on a 3yr old fancy rMBP.
### Actual results:

Scrolling in Mountain View.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18151383/b2ce7ee6-6fa3-11e6-9863-c44bab867220.png)
**Figure 1:** This is actually maximized in Chrome (~~see how the "copy" label seems slightly misaligned compared to Firefox too~~ Field separately as #1317), but the results are similar in FF Nightly. My screenshot/screen resolution is 1440px by 877px.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18151423/e97f0424-6fa3-11e6-89f6-946fea83e8fa.png)
**Figure 2:** Rest of the page scrolled (again in Chrome).

<img width="1440" alt="screenshot_8_31_16__5_54_pm" src="https://cloud.githubusercontent.com/assets/557895/18151447/18a99462-6fa4-11e6-8800-bf72349e3ae0.png">
**Figure 3:** Same same in Firefox Nightly (although with better aligned "copy" link). Ignore the oddly floating min-vid of Mel Brooks.
### Expected results:

Less padding/margins/scrolling.

**Comment by johngruen** [comment]
![p-3209- clown-horn](https://cloud.githubusercontent.com/assets/3323249/18271241/6b80d178-7431-11e6-9eab-f673d2d82d38.jpg)

**Comment by pdehaan** [comment]
![](http://i.imgur.com/IT6Yh.gif)

**Comment by SoftVision-PaulOiegas** [comment]
I still think that maybe the UI is a bit too large. On a 13 inch MacBook Pro Retina you still have to scroll the page to reach the footer links. But maybe it's only me. :smiley:
