### ISSUE TITLE
Copy button is misaligned on /share page in Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1317]
Ref: #1316

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18151492/66e096ee-6fa4-11e6-9618-d7af4d0e08af.png)
**Figure 1:** Google Chrome shifts the "copy" button onto a new line.

---

<img width="1440" alt="screenshot_8_31_16__5_58_pm" src="https://cloud.githubusercontent.com/assets/557895/18151503/81fb6206-6fa4-11e6-8057-c39f57d6d4ac.png">
**Figure 2:** Firefox aligns beautifully.

**Comment by johngruen** [comment]
what is @pdehaan watching

**Comment by pdehaan** [comment]
@johngruen Sorry, it was https://www.youtube.com/watch?v=CB-tFLCShyU

Apologies for not making it more explicit in the STR. /cc @chuckharmston
