### ISSUE TITLE
Deploy to staging

### ISSUE THREAD

**Issue by nchapman** [mozilla/testpilot#132]

**Comment by meandavejustice** [comment]
Can we close this? @lmorchard

**Comment by lmorchard** [comment]
Still working through this. We have a dev server, but staging & prod are in progress

**Comment by lmorchard** [comment]
Notes on [Docker and Cloud Services](https://mana.mozilla.org/wiki/display/SVCOPS/Docker+and+Cloud+Services) (needs an LDAP login)

**Comment by lmorchard** [comment]
We are deployed to staging! https://ideatown.stage.mozaws.net/
A wrinkle left to iron out with FxA credentials, but things seem to be working so far.
