### ISSUE TITLE
Firefox Release w/"No more 404s" extension hangs whole browser on loading treeherder links (Force Close)

### ISSUE THREAD

**Issue by ovidiuboca** [mozilla/testpilot#1322]
This issue is a clone after https://bugzilla.mozilla.org/show_bug.cgi?id=1299586.

STR:
1. On OSX, launch Firefox 48.0.1 with a clean profile.
2. Install "Test Pilot" and the "No more 404s" extensions.
3. Launch URL.
4. (If necessary) quit and restart browser, then launch URL.

Expected result:
- I can see both left and right side of treeherder page, and continue working.

Actual result:
- I see only left side of treeherder page, a spinning beachball of death, and totally frozen Firefox.

No UX or tabs work (I'm in the non-e10s population) and I'm forced to "Force Close", at which point I don't even get Mozilla's crash reporter, instead I get the "Send to Apple" one (do we even get those?)

Workaround:
- Disable the "No More 404s" extension (and possibly restart).

**Comment by jaredhirsch** [comment]
@wresuolc says this works in today's nightly. I'll investigate.

**Comment by ghost** [comment]
Is this still reproducible?

**Comment by ovidiuboca** [comment]
Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1299586. I have just created a clone for this bug.

**Comment by ghost** [comment]
That bug is fixed, so closing this one as well.  Thanks.
