### ISSUE TITLE
Make it easier to add allowed environments to the main add-on

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1325]
In PR #1320, I added 2 more environments for static dev & static staging. But, it would be nice to make it way easier to add environments - especially if that means we don't have to deploy new versions of the add-on. This would make it easier to do things like #525 and support many alternate branches deployed to servers for UX testing and such. 

See also: an 'any' environment over in @dannycoates' experimental addon https://github.com/dannycoates/x16/commit/e3e9a97df05cf1113294b7d3b89d4023a8f57117

**Comment by johngruen** [comment]
WONTFIX by reason of meh
