### ISSUE TITLE
Add new experiments to testpilot.dev.mozaws.net

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1326]
We should probably add the upcoming Page Shot and Min Vid experiments to the development http://testpilot.dev.mozaws.net/ site (Blok is already added).

Makes it easier for QA to get started testing, and will let us see how everything will look if we launch w/ 7 active experiments (on the homepage, and in add-on dropdowns, and in related experiments at bottom of details pages.

**Comment by johngruen** [comment]
@pdehaan planning on getting something up ~ mid next week

**Comment by lmorchard** [comment]
FWIW, this will probably be solved permanently when we finally switch over to flat-files, because we'll be staging the content in the project repo and it will follow the rest of the site code from dev to stage to prod
