### ISSUE TITLE
Add interstitial message for Tracking Protection experiment when user attempts feedback

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1328]
With the upcoming tracking protection experiment, we will mostly want people to give feedback via the tracking protection add on. We can cut down on bad interactions by adding an interstitial modal between the feedback button on the experiment details page and the redirect to survey gizmo.

**Comment by sevaan** [comment]
UX: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/187233763_Tracking_Protection_Feedback

Image asset attached.
![asset 2x](https://cloud.githubusercontent.com/assets/473531/18359374/a7d42598-75c7-11e6-8f0c-7dbc87f18d07.png)

**Comment by sevaan** [comment]
So to clarify, user clicked the Give Feedback button on the experiment details page, and then the new tour UI ([Issue #944](https://github.com/mozilla/testpilot/issues/944)) is revised to show a message clarifying where to give feedback.

**Comment by johngruen** [comment]
@sevaan thanks for making this. We're going to need to tweak this asset b/c we've changed the name of the add on to Tracking Protection

**Comment by johngruen** [comment]
I'll get you a new XPI ASAP

**Comment by johngruen** [comment]
@lmorchard I already put together an PR for #1208 that assumes YAML, but I suppose this + that one will require some kind of django migration until we deploy statically. Would it make sense for me to get a YAML only PR together for this one to accompany my other PR then open a follow on issue for you or @dannycoates add the appropriate stuff to django?

**Comment by lmorchard** [comment]
It probably doesn't make sense to duplicate new features like this in Django if we're just going to throw it away in a few weeks (hopefully). 

Here's another option I mentioned in IRC last night: We _can_ actually use the flat files content on Django. There's a waffle switch in admin to swap from using the DB to using content from YAML.

The catch, though, is that we can't update content on the site without doing a full-on tag-and-deployment with ops.

**Comment by johngruen** [comment]
@lmorchard @clouserw straw plan: 

We get everything in place with the YAML for our deployment. We delay tagging until Friday this sprint to acommodate last minute changes to various XPIs and copy. We add the new experiments in the yaml and add a `show_after` flag with our intended launch date (we could even add a `butimspecial`) query sring so soft vision could see the upcoming experiments.

Thoughts?
