### ISSUE TITLE
Use SSL for local development.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1329]
In #1223 I am introducing some functionality that only works over HTTPS. I'm working around it with a proxy for now, but it'd be nice if we shipped with some dummy certs or LE configuration that let us use HTTPS for local work without configuration.

**Comment by lmorchard** [comment]
See also, for dev on elastic beanstalk (not a dupe, but also important): https://github.com/mozilla/testpilot/issues/548

**Comment by lmorchard** [comment]
I remember we did this with MDN, but via a full Apache instance in Vagrant. Let's not do that here. Maybe we can use something like [django-sslserver](https://github.com/teddziuba/django-sslserver)?

**Comment by lmorchard** [comment]
Going to say this is closed since #1394 was merged. Could use some docs though
