### ISSUE TITLE
Allow users to delete their Idea Town account

### ISSUE THREAD

**Issue by nchapman** [mozilla/testpilot#133]

**Comment by lmorchard** [comment]
Should we assume that "delete" means a user and all associated data is deleted?

For example, should we delete feedback collected as part of #154 insofar as may be tied to a user profile?

**Comment by pdehaan** [comment]
Could we keep the feedback but make it anonymous if the user deletes their account?
It'd be sad to have a user fill out a big feedback form saying "these are the reasons I'm deleting my account" and then we immediately delete that feedback after the user deletes their account.

I think Reddit just sets the username to "[Deleted]" in posts if the user removes their account.

**Comment by nchapman** [comment]
Yeah good point @pdehaan. It'd be great to keep their feedback. I'll check with legal about this today.

**Comment by meandavejustice** [comment]
@nchapman Any word from legal on this?

**Comment by nchapman** [comment]
This is the angle that I forgot to cover. I'll talk to Brian and Marshall about it.

**Comment by johngruen** [comment]
@nchapman @lmorchard I'll talk to Ryan about this today. Marketplace and Hello don't offer a 'delete' button so I'm not sure if we need to, but maybe we should since there's more at stake? 
FWIW, I don't think we should use the term "Idea Town Account" should ever be user facing.

**Comment by clouserw** [comment]
I'm always in favor of being able to un-signup for anything I've signed up for, but in this case it doesn't feel very important.  Having people uninstall the add-on essentially "cancels" their account until they re-install it.  All the data was so opt-in to start with, deleting it just doesn't seem critical to me.  If y'all feel strongly though, anonymizing it would work too.

**Comment by ckprice** [comment]
Bumping this, adding it to our April milestone and /cc @javaun.

Some questions:
1. This is an add-on: do we need any additional mechanism to point users to disable?
2. We do keep a segment of user data in our TxP DB for feedback reasons, does this need to be deleted/anonymized?

**Comment by ckprice** [comment]
Closing in favor of #499.
