### ISSUE TITLE
Add-on installation never completes on dev.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1332]
The add-on is installed, but never updates the navigator properties of the top window, so the spinner never finishes.

**Comment by johngruen** [comment]
@chuckharmston is this dev edition or from the dev server?

**Comment by chuckharmston** [comment]
Dev server using Nightly, sorry. I'll do a little more prodding and update the title and description to be more clear.

**Comment by chuckharmston** [comment]
I think this was due to `testpilot.env` not being set correctly. I'll close until I can reproduce again.
