### ISSUE TITLE
Toggle Native Tracking Protection Pref off if user installs Test Pilot Tracking Protection

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1333]
Related to #944, and we may not need a separate issue here, but we can cover this in triage today.

**Comment by johngruen** [comment]
https://github.com/mozilla/blok/issues/12

**Comment by johngruen** [comment]
@ckprice could we implement this toggle without UI and just call it out in the short privacy notice?

**Comment by sevaan** [comment]
This does not seem like highly important information users need to be made explicitly aware of via some sort of UI. It makes sense to alert users to pref switch somewhere in the fine print.

**Comment by ckprice** [comment]
This was given a thumbs up in theory by Marshall/Elvin pending the addition of a bullet to the already approved Privacy Notice. I'll come back to this bug once the PN has been approved, but I would recommend we start implementation here.

**Comment by marco-c** [comment]
This is a bit counterintuitive to me.

**Comment by johngruen** [comment]
@marco-c yeah, it's a bit of a workaround since there's a collision btwn native tracking protection and the experimental add-on.

**Comment by marco-c** [comment]
Would it be possible to use native tracking protection, when it is enabled, and only make the addon allow users to report broken sites?

**Comment by groovecoder** [comment]
Whoa, okay this needs some immediate attention.

Based on https://github.com/mozilla/blok/issues/116 I [disable the add-on powered tracking protection in Private Browsing windows](https://github.com/mozilla/blok/commit/729c15a036da7d4878539495fd5ca234fa21029e).

So right now, users with the Blok experiment **are being tracked** in Private Browsing windows unless they explicitly re-enable tracking protection in that window.

**Comment by dholbert** [comment]
> So right now, users with the Blok experiment are being tracked in Private Browsing windows unless they explicitly re-enable tracking protection in that window.

Yikes!  This is _extremely_ unexpected & counterintuitive.  @groovecoder, is there a plan to address that (or an issue open)? I just independently discovered this, when opening a private browsing window -- it shows "Tracking Protection: {o--}" (slider in "off" position).

**Comment by groovecoder** [comment]
https://github.com/mozilla/testpilot/pull/1566 was merged 6 days ago. I think that means it will deploy ... tomorrow? (@clouserw)

**Comment by SoftVision-PaulOiegas** [comment]
@groovecoder Probably it is already on dev server. On stage server will end up Thursday EOD if I'm not mistaking and if there are no unfinished tasks and issues appeared. And will land on production on Tuesday morning if the staging testing looks ok on Friday and Monday.
