### ISSUE TITLE
Do a better job monitoring for error states in extension installation

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1335]
We don't do a great job of monitoring for error states in add-on installations. I see at least three places for improvement:
- Listen for exceptions in the Test Pilot add-on when `mozAddonManager` is used (#1223)
- [Listen for exceptions](https://developer.mozilla.org/en-US/Add-ons/Add-on_Manager/InstallListener#onInstallFailed%28%29) in experiment installations via the Test Pilot add-on
- Set a timeout on the traditional link-to-XPI install.

**Comment by sevaan** [comment]
@chuckharmston I'm not sure I fully understand the UX ask here. Could you clarify further (screenshots could be helpful if applicable)?

**Comment by chuckharmston** [comment]
@sevaan 

Right now, while installing either the Test Pilot add-on or experiments, we don't do the best job of surfacing that there are errors. Sometimes that's because we haven't implemented it yet, but sometimes we also can't know that there's an error (for security/other reasons). That means that in some error states, our install button spins infinitely. I'm proposing that:

1) We do a better job of listening for errors and telling the user when they happen.
2) We assume that if the Test Pilot add-on or experiment hasn't been successfully installed after `n` seconds (not sure what that should be...20?) we assume something went wrong and that we tell the user as much.

**Comment by johngruen** [comment]
Whelp, @sevaan went and had a baby. I'll do UX for this issue by EOW

**Comment by chuckharmston** [comment]
@johngruen putting this back on your radar

**Comment by johngruen** [comment]
@chuckharmston, noted. Let's see if this doesn't sneak into 14 tomorrow...

**Comment by Caspy7** [comment]
I've just helped a user who was receiving "Installing..." forever.
After _much_ troubleshooting, it was determined that the user already had Test Pilot installed but disabled.

We should do better about failing gracefully and/or informing the user of the situation.

**Comment by sevaan** [comment]
I have a proposal here: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/203288154_Landing_Page_-_Error_Installing

If the install process hangs for say, 30 seconds, we could refresh the page and display this error message at the top. The "Still not working?" link could take the user to the Github issues, or maybe even just a readme somewhere. Thoughts?

**Comment by Caspy7** [comment]
> maybe even just a readme somewhere

Perhaps a sumo page.

**Comment by johngruen** [comment]
I'll need to add an FAQ, to link to, but this is ready to go

**Comment by vpomerleau** [comment]
> I've just helped a user who was receiving "Installing..." forever.
After much troubleshooting, it was determined that the user already had Test Pilot installed but disabled.

I've noticed the same issue. It would be great to detect if the plug-in is already installed (ex. replace the "install" button with an "enable" button).

**Comment by fzzzy** [comment]
This was fixed by 'use mozAddonManager more' https://github.com/mozilla/testpilot/pull/2360 and ' fix download failed 'https://github.com/mozilla/testpilot/pull/2373

However, 'installing test pilot addon when it is already installed but disabled is poorly handled' https://github.com/mozilla/testpilot/issues/2331 is still open. I'll close this issue and use 2331 for the remaining issue, since it is short and to the point in describing the only known bug that remains.
