### ISSUE TITLE
Add GA to the addon

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1337]
Benefits include a secondary resource to check general usage information, and interaction with the addon UI (clicks on icons, heartbeat prompts, notification views, etc).

This needs a legal review and a review by @garethcull. Would like to target this landing in the next sprint.

Assigning myself for pushing the next steps, but comments are welcome. I started playing around with how this could be structured in [a branch](https://github.com/ckprice/testpilot/tree/ga-addon).

**Comment by lmorchard** [comment]
I think this is interesting for prototyping but I think we really, really do not want to [pull in third-party JS from an external URL](https://github.com/ckprice/testpilot/commit/c40332a8fcf10c9fedaaf0076185f078382ead5c#diff-1aa7bfd12c0f1875cbcc72990dcfbef4R18) into our signed & super-powered add-on. That sets off some pretty loud security alarms. I might be misreading what that line's doing, though.

If we definitely want to send pings to Google Analytics, we should do it with our own code calling [the Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/).

**Comment by ckprice** [comment]
> If we definitely want to send pings to Google Analytics, we should do it with our own code calling the Measurement Protocol.

Thanks for the link, yeah just wanted to start blocking out some things and hadn't seen these docs. I'll tweak my branch.
