### ISSUE TITLE
Use SSL on dev site

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1343]
Similar to #1329, we should be using SSL on our development site.

I believe the flatfiles move will close this issue, but I'm still filing it as a discrete requirement for our stack in the event that it does not.

**Comment by pdehaan** [comment]
Dupe of #548?

**Comment by lmorchard** [comment]
Yeah, dupe of #548, but also we have HTTPS via CloudFront here now:

https://testpilot-static.dev.mozaws.net/

**Comment by lmorchard** [comment]
Going to close this, since it's done except for changing host names around
