### ISSUE TITLE
There is no domain validation for email address on the displayed newsletter pop up after installation

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1345]
[Affected versions]:
- Nightly 51.0a1

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Firefox and navigate to testpilot.firefox.com.
2. Click on "install the Test Pilot add-on" button and follow the steps to install it.
3. After installation, click on the text box for newsletter sign up from the displayed pop up.
4. Enter an email address without a domain (eg: "test@") and click on "Sing me up" button.

[Expected result]:
- "Please use a valid email address!" error message in red is displayed above the box.

[Actual result]:
- The pop up confirms that the email is sent even if an email with no domain is entered.

[Notes]:
- This issues is also reproducible on dev and stage servers.
- Added a screen recording with the issue: https://goo.gl/Xoub5l.

**Comment by ghost** [comment]
We'll do new email UI in the next sprint

**Comment by SoftVision-PaulOiegas** [comment]
Yey, new newsletter sign up functionality finally arrived. Oh wait, this still reproduces on new one. 😢

**Comment by johngruen** [comment]
FIXED
