### ISSUE TITLE
Missing GA events (and all pageviews)

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1346]
Copying from https://github.com/mozilla/testpilot/issues/1307#issuecomment-246800267

Can't see a couple GA events/pageviews firing
- Viewing the home page without the add-on installed ([ref](https://github.com/mozilla/testpilot/blob/6bd599eb1c3396883a7a98acaf6671dd49e03132/frontend/src/app/views/landing-page.js#L39)).
- Clicking `Proceed` on retiring modal and going to the retire page ([ref](https://github.com/mozilla/testpilot/blob/6bd599eb1c3396883a7a98acaf6671dd49e03132/frontend/src/app/views/retire-page.js#L45)).
- Viewing the experiment detail pages ([ref](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/views/experiment-page.js#L266)).

Eh, looks like there are no `pageviews` sends in the branch.

**Comment by ckprice** [comment]
The router is a good spot for this!

**Comment by ghost** [comment]
@ckprice please confirm with people when you assign them issues.  thanks!

**Comment by ckprice** [comment]
Eh, this was a dupe of https://github.com/mozilla/testpilot/issues/1362#issuecomment-247641915 which Les took. It was discussed in the meeting, but I can try to be pingier.

**Comment by ckprice** [comment]
Closed in #1406
