### ISSUE TITLE
Optimize React build in gulp, switch to production mode

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1349]
React is building in default development mode right now. Switch it to production in CircleCI.

I think this is done with [envify](https://github.com/hughsk/envify), but I've not gotten that working myself yet.

**Comment by pdehaan** [comment]
Re: minification,

**Warning:** It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

> ### npm
> 
> We recommend using React from npm with a bundler like browserify or webpack. You can use the `react` and `react-dom` packages. After installing it using `npm install --save react react-dom`, you can use:
> 
> ``` js
> var React = require('react');
> var ReactDOM = require('react-dom');
> ReactDOM.render(<App />, ...);
> ```
> 
> Each of the add-ons lives in its own package.
> 
> **Note:** by default, React will be in development mode. To use React in production mode, set the environment variable `NODE_ENV` to `production` (using envify or webpack's DefinePlugin). A minifier that performs dead-code elimination such as UglifyJS is recommended to completely remove the extra code present in development mode.

&mdash; via https://facebook.github.io/react/downloads.html

**Comment by ckprice** [comment]
Moving on deck just to verify that it is happening then we can close.

**Comment by johngruen** [comment]
FIXED
