### ISSUE TITLE
When a download fails the button remains in the enabling state.

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1352]
[As reported](https://github.com/mozilla/testpilot/issues/1307#issuecomment-246845942) by @dannycoates in #1307:

> When a download fails the button remains in the enabling state.
> 
> <img width="440" alt="screen shot 2016-09-13 at 2 54 14 pm" src="https://cloud.githubusercontent.com/assets/87619/18492859/57a0f714-79c2-11e6-9186-625854f1963f.png">

**Comment by SoftVision-PaulOiegas** [comment]
Shouldn't the "Enabling..." animation stop also when trying to enable an experiment with no internet connection ? I get the error bar above but the animation is still spinning after 5 minutes of waiting... Not sure this was fixed entirely.
Tested on dev using WIndows 10 and Mac OS 10.12 (preview).
