### ISSUE TITLE
Use localhost:8000 instead of testpilot.dev:8000 for local environment?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1358]
Currently, even with gulp & react, we still need to use a testpilot.dev entry in /etc/hosts.

We only really needed to do that for Docker - and even then, only when it was running in a VM on a private network IP before Docker for Mac. We don't need that now for the new gulp + flat files + static pages + react world.

So, we could:
- [ ] Change the add-on 'local' env to use local host
- [ ] Update all the docs

**Comment by chuckharmston** [comment]
In order to develop against `mozAddonManager` (#1223, #1344) locally without needing to MITM yourself, it'd be great if we used a predictable hostname that we could get on the `mozAddonManager` whitelists (or we could use example.com, which is on the whitelist already.

Also #1329

**Comment by lmorchard** [comment]
Ah, okay, I forgot about that caveat. So maybe that is one remaining reason to keep the custom hostname

**Comment by ghost** [comment]
I'm a fan of this!
