### ISSUE TITLE
Implement in product restart Prompt for e10s users in 49

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1360]
Per: https://bugzilla.mozilla.org/show_bug.cgi?id=1302846

The issue is that we need to get all Test Pilot experiments on the e10s whitelist for FF49 if we want e10s users to avoid browser restart. If we are unable to make this list, we need a graceful fallback. Fortunately, mozAddonManager allows for [in-content restart UI](https://github.com/mozilla/addons-frontend/pull/568).

@chuckharmston here's a provisional mock up. I'm not 100% wedded to the design, but the idea here is to rive users inexorably toward that restart button.

@andymckay has offered to provide support in implementation here. 

![e10s restart](https://cloud.githubusercontent.com/assets/3323249/18564740/3965abe2-7b8d-11e6-95fe-1e62d07c0930.png)

**Comment by chuckharmston** [comment]
Best I can tell, we cannot trigger a restart from `mozAddonManager`; just find out if one is necessary. @andymckay can you confirm that?

**Comment by johngruen** [comment]
@chuckharmston yeah, we can't do anything actionable here. Leaving this open for now to track decisions.

**Comment by andymckay** [comment]
Confirmed

**Comment by johngruen** [comment]
it should
[ ] ask users to restart
[ ] on browser restart open test pilot tab(s)

**Comment by johngruen** [comment]
@chuckharmston it's on

**Comment by chuckharmston** [comment]
Clarification on that last point: on Test Pilot add-on initialization, if Test Pilot has never been started before and there are no open tabs with the domain for the current add-on environment, open a tab to that environment’s homepage.

**Comment by chuckharmston** [comment]
We should probably be instrumenting this somehow, so we can understand just how this all affects conversions. @ckprice @johngruen

**Comment by johngruen** [comment]
@chuckharmston agree. let's figure out how on monday maybe we add a special GA event for users who see the 'please restart' page, and a follow on event when users see the test pilot page on restart.

**Comment by chuckharmston** [comment]
I'd suggest something a little larger in scope than that:
- Event: user sees CTA
  - Dimension: is user on homepage or experiment detail page?
  - Dimension: can user use `mozAddonManager`?
- Event: user clicks install button
  - Dimension: is restart required?
- Event: user shown "must restart" modal.
- Event: add-on opens homepage after restart
  - We'd want `utm_`s for this.

This should let us segment different pathways as they're fed into existing funnels to measure the effect on conversion rates. Plus, we would have absolute numbers to pair with the conversion rates to serve as a basis for speculation of how many users we lost in each step.
