### ISSUE TITLE
React not logging pageviews

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1362]
Per our [GA documentation](https://github.com/mozilla/testpilot/blob/9340be7168e663f0fc5efef1867d8129b86440e8/docs/metrics/ga.md#pageviews), we should be logging GA pageviews.

This seems not to have survived the Reactpocalypse.

**Comment by ghost** [comment]
Les & Chuck suggest putting this in the router!

**Comment by ckprice** [comment]
Closing for #1346 (also assigning Les to #1346).
