### ISSUE TITLE
Consider using CSS modules

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1363]
We should consider using [CSS modules](https://github.com/css-modules/css-modules). It feels strange at first, but does a great job of tightly coupling styles to components, avoiding deep nesting, and preventing brittle reliance on cascading.

For React: https://github.com/gajus/react-css-modules

**Comment by johngruen** [comment]
@chuckharmston gonna kick this out of the 37 Milestone. Let's discuss this some time this weel though.

**Comment by ckprice** [comment]
Let's close (our app isn't that complex, so not as helpful).
