### ISSUE TITLE
Move component state to Redux store

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1367]
In most cases, things you'd consider storing as component-level state may be helpful for other components to know. For example:

https://github.com/mozilla/testpilot/blob/622e5285dae57a3952817aa29ea2854f884db5ec/frontend/src/app/components/MainInstallButton.js#L11

We currently store `isInstalling` on the install button's component. If this is stored in the Redux store, the email modal component would be able to monitor its value and pop up whenever it changes from `false` to `true`, rather than needing to be manually-triggered.

There's a lot of good discussion about this out there:

https://github.com/reactjs/redux/issues/1287
http://redux.js.org/docs/FAQ.html#do-i-have-to-put-all-my-state-into-redux-should-i-ever-use-reacts-setstate

There is one important benefit to everything going into the Redux store: it turns your app into a finite state machine. The Redux store becomes the input, and the output is the rendered DOM. This makes some good things easy: testing complex interactions between components, time travel, bug reproduction, and testing. 

For the sake of being consistent and explicit, I'd suggest implementing a guideline to not use component state, instead putting everything into the Redux store and passing values down as props.

**Comment by johngruen** [comment]
we should do this at some point.

**Comment by chuckharmston** [comment]
For a less contrived example of how this might be useful, see the `addon.restart` store bits in https://github.com/mozilla/testpilot/pull/1369.

**Comment by fzzzy** [comment]
I think this is mostly done now: as you can see here https://github.com/mozilla/testpilot/blob/master/frontend/src/app/reducers/addon.js RestartState.isRequired is part of the AddonState in redux now, and here https://github.com/mozilla/testpilot/blob/master/frontend/src/app/reducers/experiments.js you can see that inProgress is now a part of the Experiment redux state.

However, an anti-example is https://github.com/mozilla/testpilot/blob/master/frontend/src/app/reducers/newsletter-form.js where I think possibly all that state should be local to the component with setState.
