### ISSUE TITLE
Benchmark add-on startup speed

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1370]
While writing #1369, I noticed that the vast majority of our (relatively slow) installation process happens in the add-on initialization, rather than in the installation. Check out the differences between this videos showing [installation only](https://vid.me/rrPw) vs [installation + initialization](https://vid.me/LLC8).

Let's benchmark the init process, find out where the issues are, and see what we can do to improve that speed. It may be that the majority of our initialization can be done asynchronously.

**Comment by ckprice** [comment]
This was filed before moz add-on manager, performance has improved since then. Closing.
