### ISSUE TITLE
Move BaseAppRedirector redirection logic into components

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1372]
The [BaseAppRedirector](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/lib/router.js#L32-L52) logic is sort of gnarly and is probably not the right place for the logic.

A more idiomatic way to do this would be to write wrapping components to encapsulate the logic, acting sort of like Python decorators. In that world, the `ExperimentsListPage` render method might return something like this:

```
<RequireAddon redirect='/'>
    <EverythingElse>
</RequireAddon>
```

The `RequireAddon` component would render `this.props.children`, and its `componentWillMount` method would replace the logic currently encapsulated by `BaseAppRedirector`.

**Comment by lmorchard** [comment]
Yeah, BaseAppRedirector is a sore spot. It works, but it didn't feel like I was doing the right thing. Improvements definitely welcome here.

**Comment by chuckharmston** [comment]
Since this bug was filed, additional logic has been added to `BaseAppRedirector`. Renamed the issue to reflect its original purpose, and filed #1583 to handle the removal of the rest of the logic.
