### ISSUE TITLE
Restructure experiments store

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1373]
The experiments bit of the store currently looks like this:

``` json
{
  "routing": "...",
  "experiments": {
    "experiments": [
      {"slug": "activity-stream"},
      {"slug": "no-more-404s"},
      {"slug": "tab-center"},
      {"slug": "universal-search"},
    ],
    "lastFetched":  1474222448673
  },
  "browser": "...",
  "addon": "..."
}
```

I'd suggest two restructures:
1. Removing the awkward `experiments.experiments` naming.
2. Store experiments in an object, with `slug:  {}`, to make references easy.

It might look like this:

``` json
{
  "routing": "...",
  "experiments": {
    "data": {
      "activity-stream": {},
      "no-more-404s": {},
      "tab-center": {},
      "universal-search": {}
    },
    "lastFetched":  1474222448673
  },
  "browser": "...",
  "addon": "..."
}
```

We lose any sorts, but that is controller logic, not data logic.

**Comment by lmorchard** [comment]
Yeah, we're [sorting explicitly by `id` in the card lists now](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/ExperimentCardList.js) anyway. So, this is a fine idea.
