### ISSUE TITLE
Use .jsx extension for files that use JSX.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1376]
Mostly just to give GitHub a hint, e.g.

``` js
render() {
  return <p>This ' is an apostrophe.</p>;
}
```

``` jsx
render() {
  return <p>This ' is an apostrophe.</p>;
}
```

**Comment by pdehaan** [comment]
When doing this, we also need to confirm that ESLint still lints all the new .jsx files.

**Comment by fzzzy** [comment]
I think we should do this sometime soonish.

**Comment by fzzzy** [comment]
We don't actually have to do this any more since the new lint rules require using &amp;apos; instead of ' inside of jsx blocks. Woo!
