### ISSUE TITLE
Disable coveralls until / unless we can get it working?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#138]
So, I've been idly poking at #85 in between other tasks, but I've yet to be able to get Coveralls working. Odd thing is that it works fine on my laptop, so that hasn't helped me diagnose things.

In the meantime, the failing Coveralls step prevents all our PRs and such from having a "green" check status even though all tests & linting steps have passed. Can we turn off Coveralls until / unless it's an urgent need? Seems like just noise right now

**Comment by meandavejustice** [comment]
:+1:

**Comment by lmorchard** [comment]
Should be disabled now, I hope
