### ISSUE TITLE
CSP Error on GA pings

### ISSUE THREAD

**Issue by adamopenweb** [mozilla/testpilot#1380]
Reported originally on webcompat.com https://github.com/webcompat/web-bugs/issues/3219
The user was unable to enable Activity Stream due to CSP error. I was able to reproduce the issue once, but not again. 

URL: https://testpilot.firefox.com/experiments/activity-stream?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=not+badged
Browser / Version: Firefox 50.0
Operating System: Windows XP

STR:
1) Navigate to https://testpilot.firefox.com/experiments/activity-stream?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=not+badged
2) Enable Activity Stream

Expected Behavior: Button should change to "Enabled"

Actual Behavior: Button doesn't change from "Enable Activity stream"

![68747470733a2f2f776562636f6d7061742e636f6d2f75706c6f6164732f323031362f392f62343565633062342d366138612d343763622d393462632d3239663130356161663437302e626d70-1](https://cloud.githubusercontent.com/assets/6587558/18645136/0a25c3fe-7e7a-11e6-8044-22431ee671f8.jpg)

**Comment by ghost** [comment]
Do you have other add-ons or malware installed?  We don't do anything with doubleclick.net which is what is being pinged here.

**Comment by adamopenweb** [comment]
I can't speak for the original reporter, @Prranesh?
When I reproduced it was on a clean profile in Firefox Dev Edition for OSX. As for malware, I'd be surprised on my system.

**Comment by dannycoates** [comment]
I can reliably reproduce the CSP error by clearing the `_gat` cookie

<img width="1316" alt="screen shot 2016-09-26 at 12 51 29 pm" src="https://cloud.githubusercontent.com/assets/87619/18849609/8f8ff5fa-83e8-11e6-972b-313ec6713e3b.png">

**Comment by dannycoates** [comment]
However, I don't see any correlation with the CSP error and the download of activity stream failing.

**Comment by ckprice** [comment]
The `doubleclick.net` URL in the second line of Danny's screencap references the GA code that Test Pilot uses. So I agree that this isn't an Activity Stream thing (changing title).

I caught up with Peter on the analytics team, and he said he's had reports of this happening on other properties so it appears to be something newish. They have emails in to Google with questions.

This is his status on the ping and how it affects our numbers

> The key take away is, we can choose*\* to block the double-click ping and it won't affect our GA numbers but will not allow us to have advertising features enabled, or get demographic data.

/edit *\* looks like they are confirming on if it's possible to disable this in our GA admin.

**Comment by ghost** [comment]
Thanks guys

**Comment by ckprice** [comment]
I think this is skewing our GA numbers pretty drastically at the moment. On prod, I don't see any pageviews or events in the Network tab. However I do see them being sent on stage.

**Comment by alexgibson** [comment]
If it's any correlation here, we hit this too unexpectedly on mozorg when we turned on CSP. After some discussion, It has since been turned off in GA.

**Comment by ghost** [comment]
We chatted about this in our last meeting and actually decided to leave it blocked as it shouldn't affect our numbers at all.  You can turn it off in GA though?  That sounds like it would be good to do.

This is WONTFIX, but leaving open for discussion.

**Comment by Prranesh** [comment]
Thank you for reply..!! I've found that error while installing that ADD-ON in my college computer LAB. But when I did the same to my PC. I didn't encountered such Issues .
