### ISSUE TITLE
Add notification of mismatch between testpilot.env pref and site being viewed.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1382]
We should add to the add-on a content script that injects a small notice to the top of any of our environments if the URL mismatches with the `testpilot.env` setting.

Lots of issues caused by a mismatch, this should do a lot of work toward remediation.

**Comment by ghost** [comment]
How about a button that's like "Yo, you're on the other site. want me to switch it for you?"

**Comment by ckprice** [comment]
This annoys us a lot, let's move to on deck.

**Comment by lmorchard** [comment]
Will try taking a crack at this too

**Comment by lmorchard** [comment]
Didn't get around to this in the last sprint, may return to it but removing myself from assignment for now so as not to leave the cookie licked

**Comment by johngruen** [comment]
Fixed
