### ISSUE TITLE
Clicking  the "View all experiments" button from "Test Pilot" doorhanger, wrongly redirects to a "Four Oh Four!" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1384]
[Affected versions]:
- Firefox 48.0.2 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Click on the "Test Pilot" spaceship icon from the main toolbar.
3. Click the "View all experiments" button and observe the browser behavior. 

[Expected result]:
- A new tab is opened and you are redirected to the Test Pilot "Experiments" page.

[Actual result]:
- A new tab page is opened but you are redirected to a "Four Oh Four!" page.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/jne8l8.

**Comment by dannycoates** [comment]
fixed by #1408
