### ISSUE TITLE
The new onboarding UI has no content for most experiments on dev server

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1385]
[Affected versions]:
- Firefox 48.0.2 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to testpilot.dev.mozaws.net/experiments/.
2. Choose a experiment card and click on the "Enable [experiment_name]" blue button.
3. Observe the new onboarding UI.

[Expected result]:
- The new onboarding UI is correctly displayed and contains details about the experiment.

[Actual result]:
- The new onboarding UI has no content other that the title of the experiment and the navigation buttons.

[Notes]:
- The lack of content is present on all experiments except for NoMore404s.
- Added a screen recording with the issue: https://goo.gl/JQJ44D.

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean I think this is resolved now

**Comment by johngruen** [comment]
Confirmed fixed
