### ISSUE TITLE
Only send installed add-ons to website once.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1403]
#1402 introduces a second call of `AddonManager.getInstalledAddons`, sending the full, unfiltered list of installed add-ons to the website, rather than just a list of the installed experiments.

We should only send one list of installed add-ons, segmented:

``` json
{
  "experiments": [],
  "other": []
}
```

**Comment by lmorchard** [comment]
A gotcha: Any changes to the messages between add-on & site will need to account for version differences between the two. Not sure if we have any metrics on how far behind users might be with the main add-on, but there will for sure be at least a 24 hour period where folks haven't yet picked up the latest add-on after we deploy.
