### ISSUE TITLE
Serve static files from S3?

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#141]
PR #137 allows S3 to be used for user-uploaded media, which means experiment thumbnails, in our case.

If we push static files (scripts, styles, fonts) to S3 as well, then we'd have a really nice first version of a build chain: put stuff on S3, use a CDN in prod.

Worth doing?

**Comment by lmorchard** [comment]
Some thinking out loud ahead... TL;DR: Seems like a good idea, will introduce moving parts & gotchas.

In one sense, this could make the Django docker image simpler. I'm playing with [a build script](https://github.com/mozilla/idea-town/compare/docker-tweaks...lmorchard:docker-tweaks#diff-1e5c4882847e3eefa76de60a300139b8R1) that builds a throwaway container with gulp & node that prepares the frontend assets before building the server container image around them.

Instead, we could build the Django server image without frontend assets and change the [STATIC_URL setting](https://docs.djangoproject.com/en/1.8/howto/static-files/) to point at a CDN. 

But, then, we have two sources of static files: We need frontend assets built by node + gulp. But then we also need a few static assets from Django using the `collectstatic` command (e.g. `/admin/` stuff, etc). Not infeasible, just another detail to automate.

We'd also no longer have a single atomic container holding everything that represents the current version of the site. Deployment would be multi-part: Update both the CDN and the server container. 

We'd have to version static assets, maybe stick the SHA hash of the git commit used to build the server container in front of the URL path - e.g. `/2ac76d8b2f49e2eedf842a2bf7e1c536ceeee358/app/app.js`. That way, if we have to roll back the server, the old assets are still there and at the same presumably expires-never cached URLs. I _think_ we can do this via env vars and the `STATIC_URL` setting in Django - deployment would just have to include that SHA hash in the var.

Wastes a little space on S3, but we could eventually have scripts that clean up old versions once we're sure we'll never roll back to them. And the more I think about it, the more versioning assets like this sounds like something we should be doing anyway, CDN or not

So, overall, I think it's worth putting together. Just want to be sure to cover all the gotchas

**Comment by meandavejustice** [comment]
ping @lmorchard is this issue still relevant?

**Comment by lmorchard** [comment]
Going to say no, since we're serving up static assets from the Docker container and that's a happy path for ops so far
