### ISSUE TITLE
Restart tab always being opened

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1420]
Reported by @SoftVision-PaulOiegas in email.

When restarting the browser to disable e10s, a new Test Pilot tab should only be opened if no Test Pilot tabs are already opened (i.e. if the session wasn't restored.) We currently are opening one no matter what. I can't reproduce this locally, and suspect that this indicates a timing issue with `sdk/tabs` (i.e. addon init code is running before the list of tabs is available.

@johngruen What would your preferred behavior be if we can't get the detection working? 
- Always open the tab
- Never open the tab
- Do the check for a tab on a timeout (no idea how long would be appropriate; maybe `1000ms`?)

**Comment by chuckharmston** [comment]
On IRC, John indicated a preference to always open the tab.

**Comment by chuckharmston** [comment]
In #1421 I am always opening the tab. I don't like that we're taking some users from 1 tab to 3, but I'm not terribly inclined to spend time trying to fix the timing issues, since it doesn't prevent any user behavior and will only apply once to a smallish cohort of users.

@johngruen Feel free to disagree, otherwise I'll close this when #1421 merges.

**Comment by johngruen** [comment]
@chuckharmston i do not disagree
