### ISSUE TITLE
Experiment pages should use the metadata configured in YAML for social shares

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1434]
Looks like the experiment pages are using the Test Pilot logo on experiment pages for `og:image` and `twitter:image`. It should use [the values configured in the experiment YAML](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/min-vid.yaml#L8).

**Comment by lmorchard** [comment]
Ugh. Looks like our switch over to static YAML isn't fully easy with Django - it's still using the database for those page templates. We don't have any code in Django to read YAML right now, just to switch the JS frontend over to the JSON built from YAML. That doesn't affect server-generated HTML results.

**Comment by lmorchard** [comment]
So, easiest fix (engineering-wise and deployment-wise): Add records for these new experiments in Django admin, use dummy content for all fields except the social thumbnails.

Harder fix, we get Django reading the YAML files to fill in the index.html frontend template when the static switch is turned on.

**Comment by lmorchard** [comment]
Tweaked title, because it's more than images that are the problem

**Comment by lmorchard** [comment]
Looks like we went with the manual solution for this - need to keep title, description, image_facebook, and image_twitter for experiments up to date in Django admin until we finish switching away from Django.
