### ISSUE TITLE
Install the Test Pilot Add-on button on experiments page 404s

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1439]
Found in http://testpilot.dev.mozaws.net/__version__ (aad58349d65f04e75cb05371530a0bc4354f7198):

``` json
{ "commit": "aad58349d65f04e75cb05371530a0bc4354f7198",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/1129",
  "version": "" }
```

---
### Steps to reproduce:
1. Go to http://testpilot.dev.mozaws.net/experiments/min-vid
2. Click the "Install the Test Pilot Add-on" button in the oversized header.
### Actual results:

Page is redirected to http://testpilot.dev.mozaws.net/static/addon/addon.xpi, which is a Four Oh Four! page, which is basically a dead end.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18799784/6b3886ba-818e-11e6-8f98-c1efe44a97d2.png)
### Expected results:

Gimme an XPI.

---

Also 404s from the Homepage:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18799832/b955ca60-818e-11e6-9e33-a3ccb062090d.png)

**Comment by ghost** [comment]
add-on is in place now
