### ISSUE TITLE
Install counts not displayed for new experiments

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1440]
Found in http://testpilot.dev.mozaws.net/__version__ (6c3f245b36600947c686141fdd01b0c6915ea221):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/1130",
  "commit": "6c3f245b36600947c686141fdd01b0c6915ea221",
  "version": "",
  "source": "https://github.com/mozilla/testpilot" }
```

---
### Steps to reproduce:
1. Go to http://testpilot.dev.mozaws.net/
2. Install the Test Pilot add-on. (Set `testpilot.env` to 'dev' in about:config)
3. Go to http://testpilot.dev.mozaws.net/experiments/
### Actual results:

I see install counts for the older experiments, but not for any of the newer experiments. Probably on purpose, but inconsistency makes me sad.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18800141/4416bbae-8190-11e6-907b-d52ed619825a.png)

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18800176/6eee0f6c-8190-11e6-9bdd-7e1f608fc2be.png)

Versus

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/18800183/7bbe655c-8190-11e6-9147-b980de818388.png)

**Comment by lmorchard** [comment]
This is by design: https://github.com/mozilla/testpilot/commit/4817c11539b74657be79ff4bc6ca5defbefbb175
