### ISSUE TITLE
Wrong pointer type displayed while hovering the "Upgrade Firefox" button on versions older than 45.0

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1451]
[Affected versions]:
- Firefox release 44.0.2 and under

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open an older release of Firefox (44.0.2 or under) and navigate to testpilot.stage.mozaws.net page.
2. After the page is loaded and the "Update Firefox" green button is displayed, hover over it.
3. Observe the Pointer behavior.

[Expected result]:
- Arrow pointer changes into a hand pointer while hovering the "Upgrade Firefox" button. 

[Actual result]:
- Arrow pointer is kept while hovering around the text and changes into a text selection pointer while hovering the text on the button. 

[Additional Notes]:
- Added a screen recording with the issue https://goo.gl/CnTr53.

**Comment by ghost** [comment]
This is weird, but Test pilot supports release and the previous version of Firefox so we won't be making modifications for 44. Thanks for filing though
