### ISSUE TITLE
Redirected to Test Pilot home page unprompted

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1453]
We've received reports of users being taken to the Test Pilot home page unprompted.

https://testpilot.firefox.com/experiments/?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=restart-required

**Comment by ckprice** [comment]
Fixed in #1454.

**Comment by pdehaan** [comment]
Funny, I think I was just hitting this in https://github.com/meandavejustice/min-vid/pull/317#discussion_r80746553

And more specifically, this comment:

> Actually, mildly interesting and now slightly more related to this repo:
> - https://testpilot.firefox.com/experiments works.
> - https://testpilot.firefox.com/experiments/ redirects to https://testpilot.firefox.com/.

**Comment by pdehaan** [comment]
I'll file a new bug, since I don't think that `/experiments` and `/experiments/` (with trailing slash) should have _significantly_ different behaviour... and now it's look like it's caused at least 2 problems.
