### ISSUE TITLE
Visiting /experiments/ instead of /experiments shouldn't auto redirect to homepage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1455]
I'd think/hope that the trailing "/" would be optional and purely cosmetic, but so far it's caused possibly 2 issues:
- https://github.com/meandavejustice/min-vid/pull/317#discussion_r80746553
- https://github.com/mozilla/testpilot/issues/1453

**Comment by chuckharmston** [comment]
#1453 is unrelated.

**Comment by pdehaan** [comment]
> #1453 is unrelated.

Is it? The URL is https://testpilot.firefox.com/experiments/ with a trailing slash.
If it didn't have that trailing slash, would it have redirected to the home page unprompted?

**Comment by chuckharmston** [comment]
It is.  That was due to some botched code for forced-restart flows.

**Comment by ghost** [comment]
Will be fixed with #1467
