### ISSUE TITLE
Track first-time add-on runs.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1457]
Despite #1456 being likely WONTFIX, we should still continue to store something in `simple-storage` the first time our add-on is initialized. Then, in the future, we can do a better job of detecting actual first runs vs upgrades.

**Comment by dannycoates** [comment]
Pretty sure this code path only hits on first run already https://github.com/mozilla/testpilot/blob/956a1501e6d71618be3f4ed23bd6ffea4ff3d757/addon/index.js#L342-L344
