### ISSUE TITLE
Give Feedback button doesn't register data collection

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1458]
From email:

> Hey Guys,
> 
> I was looking at the production site today, and noticed that the 'Give Feedback' button doesn't register any data collection.
> 
> Can you ensure the following values are passed on an event when a user clicks the 'Give Feedback' button? (We'll use the url to distinguish which experiment has folks giving feedback)
> 
> event category: ExperimentDetailsPage Interactinos
> event action: button click
> event label: Give Feedback
> 
> Thanks guys, please let me know if you have any questions.
> 
> Peter

**Comment by peterGerman** [comment]
Typo fixed in event category.
event category: ExperimentDetailsPage Interactions
event action: button click
event label: Give Feedback

**Comment by johngruen** [comment]
Looking at GA, this got fixed awhile ago. i think maybe when we did the pre-feedback warning stuff:

https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/ExperimentPage.js#L619

**Comment by johngruen** [comment]
Actually, reopening b/c there are some issues with the PreFeedback event logging that are relevant here
