### ISSUE TITLE
Correct min-vid copy and product tour on TxP site

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1465]
The experiment page copy says that the min vid player can be dragged anywhere in the browser window. It can actually be dragged anywhere on the desktop.

The product tour shown after installing doesn't mention right-clicking links to launch min-vid. It only mentions the overlay icon.

**Comment by johngruen** [comment]
@6a68 wontfix-ing the right click thing in the tour. It's in the details images already.
