### ISSUE TITLE
Persist query string through redirect to /experiments or /

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1467]
STR:
- Have Test Pilot installed.
- Go to https://testpilot.firefox.com/?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=not+badged

Expected Result:
- Redirected to https://testpilot.firefox.com/experiments?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=not+badged

Actual Result:
- Redirected to https://testpilot.firefox.com/experiments/

This affects our GA attribution.

**Comment by lmorchard** [comment]
As a caveat, that redirect is client-side. Does GA register hits at all for fully client-side window.history changes? If not, then retaining the URL params won't actually solve the issue if recording the page change is what we're after.

**Comment by ghost** [comment]
1) Make the content of /experiments live at /
2) Stop linking to /experiments
3) Redirect /experiments to / for everyone

(stuff will still live at /experiments/______, we're just skipping the middle step)

**Comment by johngruen** [comment]
note @clouserw's comment is now outdated

**Comment by dannycoates** [comment]
no longer an issue as of current master fc53730c390a84c32c6eb7c1287bef2bd102e77c
