### ISSUE TITLE
new experiments fail to install on old installs of test pilot

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/testpilot#1468]
1. install old version of test pilot (i also tried to update in about:addons)
2. try to install new experiments: minVid, pageShot

actual: they fail to install
peter and I both repro'd this, i uninstalled testPilot addon and installed and it fixed the problem.  I don't think i had installed anything special.

expected: they should.

**Comment by NodokaMurmevent** [comment]
same problem for me, same way for resolve this 
firefox 50.0b2 on Win10 pro

**Comment by ckprice** [comment]
Ref: #1474

**Comment by ghost** [comment]
closing as dupe
