### ISSUE TITLE
Should we require users to be on the latest version of the add-on?

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1469]
We could detect the installed version of the add-on, compare to the latest version, and prompt the user to update.

**Comment by pdehaan** [comment]
Don't the add-ons all auto-update, unless the user specifically turns that off in about:addons?

**Comment by chuckharmston** [comment]
Correct. This would be to handle that latter case.

**Comment by ghost** [comment]
This sounds good.  I don't think we need any prompting to the user - just detect an out of date version and update ourselves.

**Comment by johngruen** [comment]
@clouserw @fzzzy let's discuss this in our monday planning meeting WRT migration to webextensions

**Comment by johngruen** [comment]
WONTFIX
