### ISSUE TITLE
Set up frontend unit tests

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#147]
We have no frontend unit tests, yet. That could be handy to have!

The last time I played with frontend testing, I used Karma + mocha + chai on Travis CI [on a side project](https://github.com/lmorchard/parsec-patrol). That seemed to work well. Could be a starting point.

There are other options. Anyone have suggestions?

**Comment by meandavejustice** [comment]
It's been a while since I've setup a testing framework for something of a larger scale than the module level. For that I usually stick to [tape](https://github.com/substack/tape) I'm :+1: to mocha/chai though.

**Comment by meandavejustice** [comment]
# Meaningful things to test

## Models

### Me
- has addon install event
- has addon uninstall event
- cookie csrftoken
- fetch success
- fetch fail
- fetch success and sync
- `updateEnabledExperiments`

### Experiment
- enabled is false by default
- enabled install event
- enabled uninstall event

## Collections

### Experiments
- addon-available experiment mapping event
- addon-uninstalled experiment mapping event
- fetch success
- fetch fail

## Views

### account-inactive
- renders and el is present

### base-view
- renders and el is present (will need to pass template into this one)
- `beforeRender` is called
- `afterRender` is called
- `remove` is called on each of `this._subviews` when `removeSubviews` is called.

### contributor
- renders and el is present

### detail
- renders and el is present

### error
- renders and el is present

### row
- renders and el is present

### feedback
- renders and el is present

### footer
- renders and el is present

### header
- renders and el is present
- settings menu subview renders
- render called on 'change:hasAddon'

### home
- renders and el is present
- `experimentList` view is present on page

### landing
- renders and el is present
- properly checks loggedIn state
- properly checks if addon installed

### notfound
- renders and el is present

### page
- renders and el is present
- header is present
- footer is present

### settings
- renders and el is present

### experiment
- renders and el is present
- `afterRender` attaches `detailView` and `contributorView`
- `updateAddon` calls install correctly
- `updateAddon` calls uninstall correctly
- `updateAddon` forwards event correctly
- `updateAddon` formats event correctly
- `renderUninstallSurvey` shows form
- `feedback` shows form

## Lib

### Router
- landing redirects correctly if not logged in with addon
- home "                                                 "
- experiment "                                           "
- experiment only navigates to experiment detail if slug exists in collection.

### WebChannel
- `sendMessage` is event is structured correctly.
- `_messageReceived` parses and forwards event correctly.

## General
- test that each image in images folder has an `@2x` equivalent

**Comment by meandavejustice** [comment]
All of the above tests are written to fail above(some of them are fully written and pass).\ There will be a pull request open for tracking very soon.
