### ISSUE TITLE
We should do some preloading for tour images

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1477]
Right now the images only get loaded when the modal gets rendered in the page view. Might be nice to preload in the background them when we load the page so users don't get the load jank on the modal

**Comment by johngruen** [comment]
I will look at who clicks on these things

**Comment by johngruen** [comment]
Nice!

**Comment by dannycoates** [comment]
:sad_trombone: https://bugzilla.mozilla.org/show_bug.cgi?id=1222633#c129

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates Let me get this right. This was fixed but it doens't work because of upstream? I have just tested dev and it doen't seems to be working. The images display has a delay on first attempt, and only after it works as it should.
