### ISSUE TITLE
Not an add-on problem but Test Pilot/Firefox itself

### ISSUE THREAD

**Issue by ghpicard** [mozilla/testpilot#1479]
I am trying to enable Min Vid and Tracking Protection, and both of the screen stay showing the "enabling" message indefinitely.

O.S.: Windows 7
Firefox Version: 49.0.1

**Comment by johngruen** [comment]
@ghpicard can you try restarting your browser?

**Comment by ghpicard** [comment]
Hi John, I did it, several times, to no avail. Even rebooting the machine did not change the behavior.
However, and in spite of keeping the "Enabling" message on forever, the install was successful. So this seems to be a visualization/report error instead of a software deployment one.

**Comment by ghpicard** [comment]
To clarify a little more, Firefox does not recognize that it has the add-ons installed and enabled, and offers to enable them as it did the first time. Procedure that fails in the way I described in the prior comments.

**Comment by ckprice** [comment]
@ghpicard thanks for the report. I'm going to close this out for #1474. If you have any further context to add, please feel free to add there. Thanks again!
