### ISSUE TITLE
Make optional external assets non-breaking

### ISSUE THREAD

**Issue by karlcow** [mozilla/testpilot#1480]
Hello.
(this was initially filed at https://github.com/meandavejustice/min-vid/issues/352 )

If you go to the current page 
https://testpilot.firefox.com/experiments/min-vid

with this settings in uMatrix (aka blocking the telemetry), the page content never ever initializes.

![capture d ecran 2016-09-29 a 12 08 34](https://cloud.githubusercontent.com/assets/505230/18939755/95ea0df8-863d-11e6-9264-88977b78517b.png)

It stays in this state:

![capture d ecran 2016-09-29 a 12 10 07](https://cloud.githubusercontent.com/assets/505230/18939764/b1e8aec4-863d-11e6-8a87-dd24dc39ef6a.png)

**Comment by ghost** [comment]
The page fails to render when the analysis-output.telemetry.mozilla.org ping fails

**Comment by johngruen** [comment]
Fira loaded in the `index.moustache` file is also offending

**Comment by ghost** [comment]
PR in #2184

**Comment by fzzzy** [comment]
https://github.com/mozilla/testpilot/pull/2184 has landed, is this fixed?

**Comment by dannycoates** [comment]
I don't know about the font issue that @johngruen mentioned. I've been too <strike>lazy</strike> busy to actually test this

**Comment by fzzzy** [comment]
I just tested this on master, and the original issue is fixed. I don't see any issues with the font thing. If there is an issue with loading the font, let's file a new issue for it and provide STR.
