### ISSUE TITLE
Incorrect message is displayed on the "Restart" page when installing Test Pilot from an experiment page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1485]
[Affected versions]:
- Firefox 49.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser with a new profile and navigate to https://testpilot.firefox.com.
2. Click on any experiment card.
3. Install Test Pilot from the experiment page.

[Expected result]:
- "Please restart Firefox to enable <experiment name>" message is displayed.

[Actual result]:
- "Please restart Firefox to enable experimentTitle." message is shown.

[Notes]:
- Added a screen recording with the issue https://goo.gl/MTofbU.

**Comment by johngruen** [comment]
Resolved by the new messaging in #1572. This should close when that merges
