### ISSUE TITLE
Combine frontend & addon build processes?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1486]
[Building the frontend first requires a separate add-on build run](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md#for-linux--os-x-hosts). That can be (and has been) confusing. Maybe we should find a way to combine all of this into one single set of `npm install && npm {build,test,start}` commands from the project root?

**Comment by lmorchard** [comment]
Alternatively, we could also have the `/static/addon` path in the dev server proxy to the production server. But, I don't think the add-on build is all that onerous if you've already got all the prereqs to build the web frontend

**Comment by johngruen** [comment]
Wontfix: separating concerns seems easier
