### ISSUE TITLE
Create some canned experiments data for dev & demos

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#149]
Starting from a fresh dev machine, there are no experiments. I start from a fresh dev machine often, since I frequently blow away my whole setup while tinkering with Docker concerns. It would be nice to have some placeholders out of the box.

We have a mechanism for this: [`fixtures/initial_data_dev.json`](https://github.com/mozilla/idea-town/blob/master/fixtures/initial_data_dev.json) gets loaded on every startup by [`bin/run-dev.sh`](https://github.com/mozilla/idea-town/blob/master/bin/run-dev.sh). 

We could add some canned experiment and experiment detail records there. One tricky bit is adding some sample images (e.g. maybe under `idea_town/frontend/static-src` or `idea_town/base/static`) and ensuring the proper paths in the records to point to them.

**Comment by lmorchard** [comment]
This may actually end up being an on-going dev concern past the initial additions. That is, along with generating a schema migration for changes to data models, we should also update `initial_data_dev.json` with new bootstrap example data.

**Comment by johngruen** [comment]
Would be nice to do 3 ideas, maybe only go into detail on one, but enough so there's a full grid on the main page.

**Comment by lmorchard** [comment]
Mentioned [the Django `dumpdata` command](https://docs.djangoproject.com/en/1.8/ref/django-admin/#dumpdata-app-label-app-label-app-label-model) this morning in the status meeting for helping generate some importable JSON from a dev setup.

Basically, while running your Docker machine, you can do this from OS X:

``` bash
docker exec ideatown_server_1 ./manage.py dumpdata --indent 2 --output snapshot.json
```

And that should result in `snapshot.json` with a big pile of JSON representing the contents of your environment's database. The `--indent` option should a least make it slightly readable

The [`loaddata` command](https://docs.djangoproject.com/en/1.8/ref/django-admin/#loaddata-fixture-fixture) will do the reverse, and populate your database from that big pile of JSON.

To capture any file uploads you've done (images, etc), you also need the `media` directory in the root of your project. That should go along with the JSON export, which has pointers to filenames under `media`.

We'll probably want to get a capture of a sample running dev environment (like @johngruen 's) and then maybe manually pare down the JSON so we have a clean version to use as an upgrade to [`initial_data_dev.json`](https://github.com/mozilla/idea-town/blob/master/fixtures/initial_data_dev.json)

**Comment by lmorchard** [comment]
Sir Gruen has is updating the dev site with some nice looking content. I'll see about extracting it with dumpdata when it's in a good state

**Comment by lmorchard** [comment]
Working on this today. Slightly more complicated than the previous comment, since it looks like I need to manually tweak the data a bit to leave out some models & mildly sensitive data. Also had to download images from S3 and need to prune through the relevant ones.

**Comment by chuckharmston** [comment]
> lso had to download images from S3 and need to prune through the relevant ones.

Maybe it's good enough to put [placekitten](http://placekitten.com/) URLs in the fixtures?

**Comment by lmorchard** [comment]
Included some real images, because I think making it presentable for demos with sorta-real thumbnails might be important. But, we can always back those out
