### ISSUE TITLE
Issue with Page Scroll

### ISSUE THREAD

**Issue by kaving** [mozilla/testpilot#1491]
Whenever I opne a new tab, with Mouse scroll button, the page is opened in New tab, but page will be scrolled to the end.

**Comment by SoftVision-PaulOiegas** [comment]
Can you please be more specific and tell me what pages are you opening with scroll click ? The only page I knew before it does that it's the "Cookies" one from the footer links. Right now I am opening randomly pages from experiments and I cannot reproduce this elsewhere.
