### ISSUE TITLE
Enable Tracking Protection fault

### ISSUE THREAD

**Issue by JulianPaulRoberts** [mozilla/testpilot#1492]
Uh oh. ⁨Tracking Protection⁩ could not be enabled. Try again later

Message received when trying to enable Mozilla Test Pilot

**Comment by ghost** [comment]
Do you have any anti-virus or firewalls installed?

**Comment by JulianPaulRoberts** [comment]
Avast Internet Security 2016

**Comment by SoftVision-PaulOiegas** [comment]
@JulianPaulRoberts Hey Julian, sorry for late reply. Avast Antivirus client is also installing an extension into Firefox if you do the default installation flow. Can you please switch the Google Analytics option to "ON" on that extension, and after try to install the experiment again ? 

Here is an image that explains better where you need to make the change.
![avast online security](https://cloud.githubusercontent.com/assets/17258026/19145608/5fbe59fc-8bb8-11e6-8b33-58641208c87f.png)

**Comment by ghost** [comment]
We're tracking this at #1474

**Comment by JulianPaulRoberts** [comment]
Google Analytics switched ON, as requested.  Same result, as per screen shot:
