### ISSUE TITLE
Avatars are confusing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1496]
Ref: https://github.com/mozilla/activity-stream/issues/1425

I'm not sure where to put an avatar for new experiment contributors. So far I've narrowed it down to one of:
- [/frontend/src/images/experiments/avatars](https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/avatars)
- [/frontend/src/images/experiments/activity-stream/avatar](https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/activity-stream/avatar)
- [/frontend/src/images/experiments/activity-stream/users_userprofile/2/8](https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/activity-stream/users_userprofile/2/8) &mdash; Olivier (125px &times; 125px)
- [/frontend/src/images/experiments/activity-stream/users_userprofile/5/6](https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/activity-stream/users_userprofile/5/6) &mdash; Ursula (500px &times; 500px)
- [/frontend/src/images/experiments/activity-stream/users_userprofile/9/f](https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/activity-stream/users_userprofile/9/f) &mdash; Marina (371px &times; 341px &mdash; not quite square)
- [/frontend/src/images/experiments/activity-stream/users_userprofile/c/e](https://github.com/mozilla/testpilot/blob/master/frontend/src/images/experiments/activity-stream/users_userprofile/c/e) &mdash; Nan (400px &times; 400px)
- [/frontend/src/images/experiments/activity-stream/users_userprofile/e/d](https://github.com/mozilla/testpilot/blob/master/frontend/src/images/experiments/activity-stream/users_userprofile/e/d) &mdash; Tim (460px &times; 460px)

I'd probably be nice to either normalize errything into one global [/frontend/src/images/experiments/avatars](https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/avatars) avatar directory, or into experiment-specific avatar directories, like [/frontend/src/images/experiments/activity-stream/avatar](https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/activity-stream/avatar).

I'd also be nice to probably resize all these into some consistent dimensions, since I think

---

I'm guessing this is just fallout from Django because I also see cryptic directories for experiment details: https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/activity-stream/experiments_experimentdetail and the tour steps: https://github.com/mozilla/testpilot/tree/master/frontend/src/images/experiments/activity-stream/experiments_experimenttourstep

**Comment by pdehaan** [comment]
> or into experiment-specific avatar directories, like /frontend/src/images/experiments/activity-stream/avatar.

Actually, I think I'd favor using experiment-specific avatars directories instead of one big shared directory. We'd have a few places where we duplicate avatars, but the up side is that if we delete an experiment directory, we don't have to worry about orphaned images in a shared folder.

**Comment by lmorchard** [comment]
Yeah, all these paths are an artifact of the automated Django export. We can manually reorganize this to make more sense going forward
