### ISSUE TITLE
Visiting testpilot.firefox.com breaks the back button (if already using the add-on)

### ISSUE THREAD

**Issue by alexgibson** [mozilla/testpilot#1500]
Hi,

We're linking to `https://testpilot.firefox.com/` from the new Firefox channel pages over on mozilla.org (WIP preview can be [seen here](https://www-demo1.allizom.org/en-US/firefox/channel/desktop/)). We noticed that if users click the `Learn more about Test Pilot` link in the bottom section of the page, then they cannot return to mozorg by clicking the browser back button if they already have Test Pilot installed. It looks like https://testpilot.firefox.com/ forwards to https://testpilot.firefox.com/experiments/ if you're already using the add-on, so hitting back does nothing as the redirect just kicks in again.

**Comment by pdehaan** [comment]
Possibly fixed when we do https://github.com/mozilla/testpilot/issues/1467#issuecomment-250788273

**Comment by johngruen** [comment]
This is fixed
