### ISSUE TITLE
No Icon displayed for Test Pilot after installing the add on on Firefox Private Window

### ISSUE THREAD

**Issue by pilots48** [mozilla/testpilot#1504]
I installed Test Pilot in Firefox but there is no Icon in the tool bar.

**Comment by pdehaan** [comment]
We had another report of a user, @Ajith20, not seeing a Test Pilot or Page Shot toolbar icon after installing in Page Shot: 

https://github.com/mozilla-services/pageshot/issues/1696 &mdash; No Icon displayed after installing the add on

> _"I am using 64 bit Windows 10 OS (10.0.14393 Build 14393). Firefox version 49.0.1. I don't see the icon in hamburger menu or the customize one. True, I installed Test Pilot
> add on but it isn't showing up either."_

&mdash; via https://github.com/mozilla-services/pageshot/issues/1696#issuecomment-251544641

**Comment by pdehaan** [comment]
User also reported that the Test Pilot and Page Shot toolbar icons did _not_ reappear after a restart (see https://github.com/mozilla-services/pageshot/issues/1696#issuecomment-251569195).

> > @pdehaan: "If you quit and relaunch Firefox, do the Page Shot and Test Pilot icons appear? Or are they still missing after a restart?"
> 
> @Ajith20: "No change after quitting and restarting."

**Comment by johngruen** [comment]
@pdehaan I think we should track all of these reports here

**Comment by chrwang** [comment]
This issue is also present in Firefox Developer Edition 51.0a2(2016-10-12) on OS X 10.11.6. Test Pilot and associated addons are seen in the about:addons tab but their icons are not displayed.
Here's a screenshot for reference.  It's also neither in the hamburger nor the customise hamburger menus. I will try on Linux and a fresh profile of Firefox tomorrow. 
EDIT: Persists after fully quitting and restarting Firefox. Also persists after fully uninstalling and reinstalling the addon after a restart of Firefox.
![screen shot 2016-10-12 at 22 00 28](https://cloud.githubusercontent.com/assets/12618247/19334065/628a11e4-90c7-11e6-8514-986a2d93b8ed.png)

**Comment by chrwang** [comment]
Ok, tried it on Firefox 50.0b4 on Arch Linux, and the icon and plug-in appear after installation. I have the same set of extensions as I do on my OS X install.

**Comment by SoftVision-PaulOiegas** [comment]
Is there a chance that you tried to install it from a private window ? I've seen this behavior while installing it from that kind of window.

**Comment by Ajith20** [comment]
Yes, I don't save my history at all.

**Comment by chrwang** [comment]
It was indeed installed in a private window. Disabling private browsing and reinstalling works(on macOS). However, the icon does not show when a private browsing session is opened. The extension still works when using normal browsing mode with history and downloads off. Is this the intended behaviour?

**Comment by SoftVision-PaulOiegas** [comment]
I think for the moment it is, but I'm not 100% sure. Almost all of the experiments from Test Pilot are not working on private mode as far as I know.

@johngruen @wresuolc Is this the intended behavior for Test Pilot icon not to be displayed in Private Window ?

**Comment by chuckharmston** [comment]
You need to [opt-in](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing#Opting_into_private_browsing) to private browsing in SDK add-ons.
- Test Pilot itself [has not asked for that permission](https://github.com/mozilla/testpilot/blob/master/addon/package.json#L47-L49).
- Page Shot [has not](https://github.com/mozilla-services/pageshot/blob/master/addon/package.json#L86-L88).
- Min Vid [has not](https://github.com/meandavejustice/min-vid/blob/master/package.json#L16-L18).
- Tab Center [has](https://github.com/bwinton/TabCenter/blob/master/package.json#L29).
- Activity Stream [has](https://github.com/mozilla/activity-stream/blob/master/package.json#L276).
- Universal Search is not an SDK add-on, but [explicitly does nothing](https://github.com/mozilla/universal-search/blob/be20956e69eddf720c512434ebdf843aa0b4af03/lib/ui/urlbar.js#L48-L52) in private mode.
- No More 404s and Tracking Protection are WebExtensions, which currently [only supports](https://blog.mozilla.org/addons/2016/09/13/webextensions-and-parity-with-chrome/) [`spanning` mode](https://developer.chrome.com/extensions/manifest/incognito#spanning).

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston Well, Tab Center is crashing like hell on Private Window. And when it comes to Activity Stream, you can use only the share functionality implemented in it, but not the enhanced page content that it provides... So not sure about that.

**Comment by chuckharmston** [comment]
For another way this manifests, see #1687. We should probably either:

1) Opt-in to private browsing mode and require all experiments to do the same.
2) Add some UI flagging that we don't support private browsing mode.

**Comment by chuckharmston** [comment]
A proposal, in three parts:
1. Test Pilot opts-in to private browsing. We don't require anything of experiments.
2. We annotate windows with an indicator that it is a private browsing window. This should also cover #1687.
3. On experiment pages, we add warning UI if the user has the Test Pilot add-on and is using in a private browsing window.

@johngruen?

**Comment by johngruen** [comment]
@chuckharmston meeting with @sevaan in the morning, we will toss this around

**Comment by ghost** [comment]
@sevaan is cooking up some UX

**Comment by jaredhirsch** [comment]
Some technical background:

Addons can test for private browsing mode [using `PrivateBrowsingUtils`](https://developer.mozilla.org/en-US/docs/Supporting_per-window_private_browsing#Detecting_private_browsing_mode). If the test pilot addon is installed, we could signal to the site that the user's in PBM.

Without the addon installed, it looks like the best ordinary web content can do is try to set, then get, an IndexedDB value. This doesn't tell us for sure that we're in private browsing mode, but gives us a good guess.

**Comment by johngruen** [comment]
Wontfix, we're going to do some messaging instead.

**Comment by johngruen** [comment]
also apparently this fixed itself

**Comment by fzzzy** [comment]
I just tested installing from a private browsing window, it seems to work now.
