### ISSUE TITLE
/contribute.json served as application/octet-stream

### ISSUE THREAD

**Issue by peterbe** [mozilla/testpilot#1507]
This is not with any specific app, but the general Test Pilot site. 

The `Content-Type` of https://testpilot.firefox.com/contribute.json is `application/octet-stream` making it hard to read. You have to download it because selecting "Open" might open it in some annoying editor like XCode if you're not careful.

**Comment by ghost** [comment]
should be application/json

**Comment by ghost** [comment]
This is fixed now. https://testpilot.firefox.com/contribute.json
