### ISSUE TITLE
Update /__version__ on static deploys

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#1509]
Our Docker-based deployments have a `/__version__` JSON resource we can use to check the current deployed version of the site. The new static deployment system does not do this. It probably should.

**Comment by lmorchard** [comment]
Going to have to ping @relud or someone else in ops to fully resolve this. We _were_ doing this in CircleCI with a [build-version-json.sh](https://github.com/mozilla/testpilot/blob/master/bin/circleci/build-version-json.sh) script that generated JSON from CircleCI vars. That, in turn, got embedded in the Docker container that we shipped to stage & prod eventually.

[I got this working for a dev S3 bucket](https://github.com/lmorchard/testpilot/commit/c34c407aeb1131bdc121928727d69ed9d5b52f73) - but I realized that's only because I'm using CircleCI to build & deploy to dev. 

For stage & prod, we're using an internal Mozilla service to build & deploy. We'll need that to do the equivalent of [build-version-json.sh](https://github.com/mozilla/testpilot/blob/master/bin/circleci/build-version-json.sh) with whatever env vars are available there.

**Comment by relud** [comment]
i can add a script to the build step when i get back next week. Preferrably it would create `dist/__version__` and be labelled with the correct content-type by `bin/deploy.sh`. lmk when there's a script to do that.

**Comment by relud** [comment]
also: you don't get access to the circle env vars, but you do get access to the git repo, which should tell you the branch and commit, and with `git describe --abbrev=0` you can get the most recent tag in the branch

**Comment by relud** [comment]
or if you want tag exactly matching the current commit: `git describe --exact-match --abbrev=0`

**Comment by relud** [comment]
this is fixed
