### ISSUE TITLE
Page to restart your browser after installing Test Pilot feels like a dead end.

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#1510]
After restarting the browser the user is shown a page with a message asking them to restart the browser in order to choose their features.

<img width="1392" alt="screen shot 2016-10-03 at 3 11 24 pm" src="https://cloud.githubusercontent.com/assets/473531/19050345/2a7800ce-897c-11e6-942b-ada14ec2082d.png">

Once the browser restarts the icon is added to the toolbar, but there is no indication that anything is new.

<img width="1392" alt="screen shot 2016-10-03 at 3 18 04 pm" src="https://cloud.githubusercontent.com/assets/473531/19050474/bb05f7e0-897c-11e6-949e-0581a80dab6a.png">

Some ideas to improve the UX here (not all my be possible):
- Have some imagery/text on the Restart Your Browser page to educate the use to the fact that the icon will be added after they restart.
- Maybe a button on the page to initiate the restart would be helpful
- Pop a Test Pilot tab after the browser has restarted and the Add-on has been installed. Can this be the active tab?

**Comment by ckprice** [comment]
> Pop a Test Pilot tab after the browser has restarted and the Add-on has been installed. Can this be the active tab?

FWIW this used to happen, but caused a few issues right around launch, so it was disabled in #1454. When it came time to discuss adding it back, [it was determined](https://github.com/mozilla/testpilot/issues/1456) that the first run redirect would not be worth putting back in.

**Comment by sevaan** [comment]
Also, the new email footer I'm working on could go on this page.

**Comment by sevaan** [comment]
> FWIW this used to happen, but caused a few issues right around launch, so it was disabled in #1454. When it came time to discuss adding it back, it was determined that the first run redirect would not be worth putting back in.

Okay. I think the quick-fix here would be just to have an image of the toolbar with the Test Pilot icon in it and a circle around it.

**Comment by sevaan** [comment]
Updated UX: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/194697495_Restart_Browser

Basically take the speech bubble from the [onboarding tab](https://testpilot.firefox.com/onboarding) and put it on this page, minus the triangle.

**Comment by lmorchard** [comment]
The issue is that opening a page at all right after restart (and only the restart after first install) was really problematic, and we decided not to do it until we find a good solution for #1457

**Comment by johngruen** [comment]
@lmorchard i think @sevaan is just proposing adding an image to that e10s restart page that shows up before the add-on initializes. Feels like a solid remediation to me. @sevaan we might want to change the string to indicate that the icon will be there after restart.

**Comment by sevaan** [comment]
Updated UX: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/194697495_Restart_Browser
Assets: http://i.sevaan.com/2E3M0G2k3s03
