### ISSUE TITLE
Lack of Android support?

### ISSUE THREAD

**Issue by rmenessec** [mozilla/testpilot#1512]
Test Pilot appears to be marked compatible for Firefox for Android, and I can install the extension. However, after the extension is installed, there's no initial user UX, and it's not possible to install experiments.

Bug #791 is poorly worded, and doesn't really shed any light on whether Test Pilot is intended to work on Firefox for Android.

If it's not, I for one would really like to be able to use Test Pilot on Firefox for Android.

(Nexus 6, Android 6.0.1, latest Firefox for Android Aurora build)

**Comment by ghost** [comment]
Thanks for filing.  We'll track this in https://github.com/mozilla/testpilot/issues/672
