### ISSUE TITLE
None of them will install or open properly they just hang 

### ISSUE THREAD

**Issue by Cybertoad** [mozilla/testpilot#1513]
Thank you for contributing to Test Pilot!

Cant even test failed to install and failed to load.  None of them will install or open properly they just hang LOL gees did you guys even test these only apps I have had do this 100% failure.

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by johngruen** [comment]
Hey @Cybertoad we've seen some reports of antivirus software causing install breakage. Can you tell us what add-ons you currently have installed?

**Comment by Cybertoad** [comment]
I do know Avast is integrated into the browser to check pages and No script
are about the only virus related I can think of.

**Comment by SoftVision-PaulOiegas** [comment]
This issue is mainly generated by the Avast option to disable any Google Analytics from its browser extension.  Please try to enable it and the retry the experiments installation.

Here is a screenshot with what you need to enable.
![avast online security](https://cloud.githubusercontent.com/assets/17258026/19152636/99757662-8bdb-11e6-8b97-f72533d3a301.png)

**Comment by ghost** [comment]
we're tracking this at #1474
