### ISSUE TITLE
Replace eslint-config-airbnb with eslint-config-airbnb-base

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1514]
Currently it looks like we're [extending](https://github.com/mozilla/testpilot/blob/123fa362f66bd92c9db284b7348f08cf8f79cdf8/.eslintrc#L4) the deprecated [**eslint-config-airbnb/base**](https://www.npmjs.com/package/eslint-config-airbnb#eslint-config-airbnbbase) config in our [package.json](https://github.com/mozilla/testpilot/blob/123fa362f66bd92c9db284b7348f08cf8f79cdf8/package.json#L52) file.

We should probably switch to **eslint-config-airbnb-base**:

> #### eslint-config-airbnb/base
> 
> This entry point is deprecated. See [**eslint-config-airbnb-base**](https://npmjs.com/eslint-config-airbnb-base).

&mdash; via https://www.npmjs.com/package/eslint-config-airbnb#eslint-config-airbnbbase

**Comment by pdehaan** [comment]
Unrelated but related:
- ESLint now recommends file extensions on your .eslintrc files (the vanilla .eslintrc is deprecated, but still works for legacy reasons). See [ESLint "Configuration File Formats"](http://eslint.org/docs/user-guide/configuring#configuration-file-formats). We probably want to rename all our .eslintrc files to .eslintrc.yml.
- We shouldn't need [**eslint**](https://github.com/mozilla/testpilot/blob/123fa362f66bd92c9db284b7348f08cf8f79cdf8/package.json#L51) and [**gulp-eslint**](https://github.com/mozilla/testpilot/blob/123fa362f66bd92c9db284b7348f08cf8f79cdf8/package.json#L62) in the package.json file.
- [/frontend/src/scripts/legal.js](https://github.com/mozilla/testpilot/blob/123fa362f66bd92c9db284b7348f08cf8f79cdf8/frontend/src/scripts/legal.js) doesn't seem to get linted. Not sure how to handle that as I think it may be a special file and runs in browser context and not Node, so it may need special rules or env overrides.

**Comment by fzzzy** [comment]
Should we switch to prettier?

**Comment by johngruen** [comment]
okay closing...we're gonna use prettier
