### ISSUE TITLE
make this an app

### ISSUE THREAD

**Issue by MrBlueBass** [mozilla/testpilot#1515]
I would like to make test pilot an app on my Windows 10 computer so that I can easily choose to use it when I am websurfing. How do I do this? I can't seem to find Test Pilot anywhere on my computer. It's not in the Program Files and it isn't listed in the Apps.

If someone could help, that would be great.

**Comment by lmorchard** [comment]
Test Pilot is a feature you enable within Firefox itself - you won't find it as a separate app on Windows 10. So, you can launch Firefox and find it there as an add-on.
