### ISSUE TITLE
Browser tab name is not updated when navigating to Test Pilot experiments pages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1518]
[Affected versions]:
- All Firefox versions 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://testpilot.firefox.com/ .
2. Observe the browser tab name and after click on one of the available experiments.
3. Observe again the browser tab name.

[Expected result]:
- Step 2: "Firefox Test Pilot" is displayed as tab name.
- Step 3: The tab name updates with the name of the visited experiment page "Firefox Test Pilot - experiment_name".

[Actual result]:
- Step 2: "Firefox Test Pilot" is displayed as tab name.
- Step 3: The tab name remains as "Firefox Test Pilot" no matter what experiment you visit. 

[Notes]:
- The tab name only updates if the page is refreshed.

![no tab name update](https://cloud.githubusercontent.com/assets/17258026/19082069/491aabd2-8a65-11e6-88e5-6f3a1cc6dce1.png)

**Comment by ghost** [comment]
I just tried to reproduce this and the tab name updates for me.  Is this still an issue?

**Comment by SoftVision-PaulOiegas** [comment]
The original issue is indeed no longer happening. But now if you are on an experiment page and you click the "Firefox" logo at the top, the tab displays the experiment name for the homepage. 
So it's quite the opposite now . 😆 

![home tab name](https://cloud.githubusercontent.com/assets/17258026/22987280/e38fcade-f3b6-11e6-99c3-1af836183904.png)

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas will confirm that this is fixed

**Comment by SoftVision-PaulOiegas** [comment]
Both the scenarios from initial bug report and from https://github.com/mozilla/testpilot/issues/1518#issuecomment-280082882 are no longer reproducible. Marking this as verified.
