### ISSUE TITLE
Change copy on email list confirmation message

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1520]
We don't require a user to verify his or her email address, nor do we send them a confirmation email. Let's change [this language](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/EmailDialog.js#L45):

> When you get a chance, head over to your inbox to verify your email address. Thank you!

Maybe just a "Thank you!"? @johngruen (or maybe @sevaan?)

**Comment by johngruen** [comment]
Yes, just 'Thank you' is fine.

**Comment by lmorchard** [comment]
https://github.com/mozilla/testpilot/commit/34fe36e4c2691c432857195858f8ab203d261462
