### ISSUE TITLE
Collect email addresses with persistent form at bottom of page

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#1521]
Our metrics show that email is a powerful tool for converting users for new experiment installations. We should explore options to collect email addresses at a greater number of touch points. One good touch-point would be to have an email collection form at the bottom of each Test Pilot page.

UX: https://mozilla.invisionapp.com/share/SW8TRWTMA
Example of footer on landing page: https://mozilla.invisionapp.com/share/E28TRXP46
Example of footer on details page: https://mozilla.invisionapp.com/share/UN8TRXWVS

This footer exists on a number of different Mozilla pages so it may be possible to use that existing code. You can see an example of it in action here at the bottom of the page: https://www.mozilla.org/en-US/firefox/products/

The asset for the mail icon can be found here: 
![mail](https://cloud.githubusercontent.com/assets/473531/19084157/5fece88e-8a33-11e6-9bcf-380defe37bca.png)

**Comment by chuckharmston** [comment]
Few questions for @sevaan:
- Are these strings final?
- Can we get an SVG of the email icon?
- Is it okay if we block submission of the form if it's not complete, rather than having a distinct error state?
- How does it look if there's a white-background footer, e.g. the [privacy page](https://testpilot.firefox.com/privacy)?

**Comment by sevaan** [comment]
> Are these strings final?

Yes, I am using the same strings that were used to collect email addresses before. The strings in the footer (e.g. the fine print in the form) are on all the other Mozilla web properties so do not need to be altered as they are already vetted with Legal. We removed one string, and Jess Osorio approved it.

> Is it okay if we block submission of the form if it's not complete, rather than having a distinct error state?

All this code exists and is in use on an assortment of Mozilla properties, so the error states, animations, and everything and are already coded. Is it not possible to use that code as it exists?

> How does it look if there's a white-background footer, e.g. the privacy page?

I don't think we should or need to capture emails on the white-background footer pages.

**Comment by sevaan** [comment]
[Asset in SVG!](https://github.com/mozilla/testpilot/files/520076/Email.svg.zip)

**Comment by chuckharmston** [comment]
Thanks!

> All this code exists and is in use on an assortment of Mozilla properties, so the error states, animations, and everything and are already coded. Is it not possible to use that code as it exists?

That's not really how it works. For example, mozilla.org uses jQuery, and many of their interactions (including their form validation) are built around that. Even if we'd be okay adding jQuery (we probably wouldn't be), we use an entirely different paradigm in which form validation done that way doesn't make a lot of sense.

**Comment by sevaan** [comment]
Okay thanks, that's helpful. In that case I bet I can simplify this whole thing more.

On Mon, Oct 10, 2016 at 1:39 PM Chuck Harmston

<
mailto:Chuck Harmston notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Thanks!

All this code exists and is in use on an assortment of Mozilla properties, so the error states, animations, and everything and are already coded. Is it not possible to use that code as it exists?

That's not really how it works. For example, mozilla.org uses jQuery, and many of their interactions (including their form validation) are built around that. Even if we'd be okay adding jQuery (we probably wouldn't be), we use an entirely different paradigm in which form validation done that way doesn't make a lot of sense.

—

You are receiving this because you were assigned.

Reply to this email directly,
https://github.com/mozilla/testpilot/issues/1521#issuecomment-252688746
, or
