### ISSUE TITLE
Solicit Users with Test Pilot, but no experiments installed to install and experiment

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1524]
@sevaan we're seeing many of our new test pilot installers not complete the circuit of installing experiments. if users install test pilot but don't install an experiment, we should lead them an experiment install page after a day or so.

**Comment by sevaan** [comment]
Proposed UX: https://mozilla.invisionapp.com/share/2F8UVXWCV

**Comment by johngruen** [comment]
Closing, we actually might want to rip this code oiut
