### ISSUE TITLE
Disabled (in Firefox) experiments marked as enabled (in Test Pilot)

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1529]
![screen shot 2016-10-05 at 10 00 21 am](https://cloud.githubusercontent.com/assets/23885/19121131/915a5ed8-8ae2-11e6-82cb-ca0f20e94864.png)

**Comment by SoftVision-PaulOiegas** [comment]
Probably a dupe of #1300 and it also applies to removed experiments.

**Comment by ghost** [comment]
closing as dupe
