### ISSUE TITLE
Experiment Add-ons not getting installed

### ISSUE THREAD

**Issue by omesh10** [mozilla/testpilot#1530]
Except the Tab Center, no other add on is getting installed. It shows similar kind of message for all the other add ons. Please look into this issue. I have attached a screenshot of the issue. This same problem is occurring  with all other add ons.
![test pilot](https://cloud.githubusercontent.com/assets/22645252/19127836/557e3e76-8b5e-11e6-83c4-fce533d064d7.jpg)

**Comment by ghost** [comment]
being tracked at #1474
