### ISSUE TITLE
Issue with testpilot icon

### ISSUE THREAD

**Issue by itsbanq** [mozilla/testpilot#1535]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

Unable to find testpilot icon in my toolbar.

**Comment by johngruen** [comment]
Hey @itsbanq can you confirm that the add-on is installed? you can type about:addons into the URL bar and go to the 'extensions' tab. If you don't see test pilot, you'll need to install again

**Comment by pdehaan** [comment]
I think this may be a dupe of #1504 _"No Icon displayed after installing the add on"_

**Comment by andrewycraft** [comment]
i also have no icon after installation

**Comment by itsbanq** [comment]
John,

Yes I am able to see that it is installed.

**Comment by johngruen** [comment]
@itsbanq thanks, for the update. as @pdehaan mentioned, this is a dupe of an issue we're going to track in #1504. For background, could you tell us a bit more about your version of Firefox? Helpful information would include:
- OS
- Firefox Version
- Installed Add-ons

**Comment by ghost** [comment]
dupe of #1504
