### ISSUE TITLE
Add `X-Target-Digest` header to XPIs

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1537]
When serving either the Test Pilot add-on or any of the experiments, we should include the following HTTP Header:

```
X-Target-Digest: sha256:<sha256_hash_of_xpi_file>
```

This should fix #1474.

**Comment by chuckharmston** [comment]
I think the best place for this to happen is at nginx, which proxies requests to an S3 bucket.

Note: we need to do this for all experiments, including ones that aren't currently hosted by us. It's unclear to me if we should:
1. Make it a requirement for experiments to add the header, wherever it's being served, or;
2. Make it a requirement that we host all experiments.

**Comment by chuckharmston** [comment]
CC @aswan @kmaglione

**Comment by ghost** [comment]
it's already a requirement that we host all experiments.  The two we don't are just grandfathered in at this point.  We're fixing this for our experiments right now, but it's not fixed for the test pilot xpi itself since that's not on the /files/ bucket

**Comment by ghost** [comment]
For those following along:  It turns out the X-Target-Digest header shouldn't go on the .xpi itself, it needs to go on a 302 redirect to the .xpi file, which makes this more complicated in our flat file world.  Progress ongoing...

**Comment by ghost** [comment]
Alright, I think we have a solution.  The install button on stage is currently pointing to https://testpilot.firefox.com/files/min-vid/min-vid-latest.xpi which is a 302 to the actual .xpi file.

@chuckharmston If you can verify that works as expected, I can do the same to the other files on s3

For the record, it turns out that when you use amazon's redirect thing on S3, it strips out custom headers, so we ended up not being able to use that at all.  This is simply setting an x-amz-meta-location header (which gets the prefix stripped automatically) and then relud is rewriting the 200 to a 302.

**Comment by chuckharmston** [comment]
Confirmed that this works as expected.

On macOS Sierra with Avast Free installed `testpilot.env` set to `stage`, and `extensions.install.requireBuiltInCerts` set to `true`, I was able to install min-vid from our staging site, but not other extensions.

Response headers:

<img width="472" alt="screen shot 2016-10-08 at 12 55 29 pm" src="https://cloud.githubusercontent.com/assets/23885/19214970/99ab2240-8d56-11e6-8e20-22114e15732f.png">

<img width="471" alt="screen shot 2016-10-08 at 12 55 35 pm" src="https://cloud.githubusercontent.com/assets/23885/19214978/aaa75c30-8d56-11e6-9a63-c72e4e0f0013.png">

**Comment by chuckharmston** [comment]
Confirmed that this works as expected.

On macOS Sierra, with:
- Release Firefox
- Avast Free installed
- `testpilot.env` set to `stage`
- `extensions.install.requireBuiltInCerts` set to `true`

I was able to install min-vid from staging, but not other experiments. Response headers:

<img width="472" alt="screen shot 2016-10-08 at 12 55 29 pm" src="https://cloud.githubusercontent.com/assets/23885/19214970/99ab2240-8d56-11e6-8e20-22114e15732f.png">

<img width="471" alt="screen shot 2016-10-08 at 12 55 35 pm" src="https://cloud.githubusercontent.com/assets/23885/19214978/aaa75c30-8d56-11e6-9a63-c72e4e0f0013.png">

**Comment by chuckharmston** [comment]
We should make sure to document this (and the process of doing it from the AWS console) before closing this issue; it'd be nice if @clouserw isn't a single point of failure for updates here.

**Comment by ghost** [comment]
Thanks for checking.  I wrote a sync script for s3 which I was going to commit, but am going to have to update now that hashes and redirects are involved.  I'm considering making one of my Q4 deliverables getting automated experiment uploads hooked up which should take me out of the loop completely.

**Comment by ghost** [comment]
These are all fixed on S3 and https://github.com/mozilla/testpilot/pull/1568 fixes this in the code

**Comment by clouserw** [comment]
Now being tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1315033
