### ISSUE TITLE
cant load scrabble with test pilot activated

### ISSUE THREAD

**Issue by ronngail** [mozilla/testpilot#1554]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by johngruen** [comment]
Hey @ronngail, have you enabled the Tracking Protection experiment? This experiment may definitely cause issues on certain sites, but you can disable Tracking Protection on any site by clicking the purple shield icon while on the broken site. This will help us understand how Tracking Protection affects your experience of the web.

**Comment by johngruen** [comment]
@ronngail here's the icon you're looking for: https://github.com/mozilla/testpilot/blob/master/frontend/src/images/experiments/tracking-protection/experiments_experimenttourstep/tour1.jpg
