### ISSUE TITLE
Pass add-on hash to mozAddonManager.createInstall

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1555]
Refs:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1308261
- https://hg.mozilla.org/integration/autoland/rev/0c6ac0ce7b39

**Comment by fzzzy** [comment]
This seems like something we should do. What benefits does it provide? Added security?

**Comment by lmorchard** [comment]
Going to take a crack at this

**Comment by lmorchard** [comment]
Thinking this through... Should be easy enough for the main Test Pilot add-on - calculate the hash at site deploy time and embed it in the static JS bundle.

However, getting a hash for each experiment XPI seems trickier: Experiment updates are decoupled from static Test Pilot site updates, so we'd need to fetch them from somewhere fresh on load in the browser.

There's the `x-target-digest` header on `https://testpilot.firefox.com/files/**/latest` redirects. I think a `fetch(url, {redirect: 'manual'})` could get that for us. <strike>But, we'd need to add CORS headers to those redirects to support `fetch`.</strike> Also, my thinking is fuzzy on this, but I feel like using the header weakens the security story here - trusting the XPI URL itself for its own hash, though practically speaking we host them ourselves anyway.

Alternatively, would it make sense to maybe host a `.json` resource with hashes for all the XPIs under `/files/`? That would require tweaks to the XPI deployment system to keep that resource updated. (That system is a black box to me right now, so I'm not *quite* sure what that would entail.)

**Comment by lmorchard** [comment]
@clouserw What do you think about having the experiment XPI deployment system update a JSON resource with a hash on deploy? Could be a single resource like this:
```
{
  "addon0@example.com": "sha256:cfeda508085d8798c552b0081a4ab655779c855e2ecd6ea420f878965a0c54cc",
  "addon1@example.com": "sha256:cfeda508085d8798c552b0081a4ab655779c855e2ecd6ea420f878965a0c54cc",
  "addon2@example.com": "sha256:d4bab17ff9ba5f635e97c84021f4c527c502250d62ab7f6e6c9e8ee28822f772"
}
```

**Comment by ghost** [comment]
I'd rather not have a single file listing multiple hashes.  Right now updating an XPI only changes files under its directory, which I think is good.

The hashes already exist in the updates.json files.  eg. https://testpilot.firefox.com/files/activitystream/updates.json .  Could those be used?

I'm also curious what benefit this is providing.  Is this a replacement for putting the x-target-digest headers on the redirect?

**Comment by lmorchard** [comment]
> The hashes already exist in the updates.json files.

Ah, I forgot those update.json resources exist. Looks like I can grab those with `fetch()` - had a brainfart & thought we needed CORS headers because I was trying the fetch from a web console on an MDN page rather than from, you know, the same origin.

> I'm also curious what benefit this is providing. Is this a replacement for putting the x-target-digest headers on the redirect?

Yeah, I'm actually not sure. The original bug doesn't discuss it. @chuckharmston do you have any more details on this? I think you dealt with the x-target-digest headers too.

**Comment by chuckharmston** [comment]
It's definitely related to X-Target-Digest—it possibly supplants it—but I filed this issue at the request of the add-ons team and don't remember details. Maybe @aswan?

**Comment by aswan** [comment]
Passing the hash is meant to ensure that the thing that gets installed is actually the thing you meant to install.  There are multiple ways to provide a hash including the two being discussed here (passing it to `createInstall()` and including it in a special header if the load of the actual addon is redirected).  The former offers slightly more protection (ie against somebody who manages to hijack or MITM the redirect) but if you're already sending hashes on redirects and including the hash with `createInstall()` is impractical, its probably fine to leave it as-is (though having a more qualified security person review that conclusion would be good...)

**Comment by lmorchard** [comment]
> The former offers slightly more protection (ie against somebody who manages to hijack or MITM the redirect) but if you're already sending hashes on redirects and including the hash with createInstall() is impractical, its probably fine to leave it as-is

Yeah, that's my basic conundrum here: I don't get how moving the hash check might protect better. Maybe it's better where the XPI is on a different origin than the JS installing it?

Otherwise, if you can MITM our redirect with a hash, I'd guess you can MITM a JSON resource containing the hash. Worse, you could MITM our JS resource containing the `createInstall()` call that uses the hash.

> (though having a more qualified security person review that conclusion would be good...)

Do we know who that might be? We do already have the X-Target-Digest header, so changing nothing would be convenient. :grin: But, it would be good to have a solid thumbs up on whether doing nothing is the correct route.

**Comment by aswan** [comment]
> Yeah, that's my basic conundrum here: I don't get how moving the hash check might protect better. Maybe it's better where the XPI is on a different origin than the JS installing it?

To be pedantic, the actual location of the XPI doesn't really matter, this is certainly more meaningful if the redirect comes from a different place than the page that is starting the install.  If the page and the redirect come from the same place, I would agree that if you can subvert one, you are likely to be able to subvert the other too.

> > (though having a more qualified security person review that conclusion would be good...)
> Do we know who that might be?

Not sure, I would start with @dveditz

**Comment by lmorchard** [comment]
> To be pedantic, the actual location of the XPI doesn't really matter, this is certainly more meaningful if the redirect comes from a different place than the page that is starting the install.

Sure, and that's also the same here: Redirects, XPIs, and JS are all located at https://testpilot.firefox.com/

**Comment by lmorchard** [comment]
Alright, how about this: Seems like maybe we don't really need to do this, so I'll close. Re-open / comment if there's a strong case to do this in addition to X-Target-Digest header on redirects.
