### ISSUE TITLE
Double issue. Do with it whatever you desire

### ISSUE THREAD

**Issue by exec228** [mozilla/testpilot#1557]
Issue 1)
https://qsurvey.mozilla.com/s3/min-vid have bugs:
when I fill my answers, and press "Next", the page resets score question and demands me to fill it again as "Required answer". Eternally.

Issue 2)
The report I'd send to MinVid is:

----------8<-----------cut and dump----------8<-----------
Conflict with Stylish directive:
audio, video { min-width: 380px; max-width: 100% !important; }
Some sites have media player with progress bar, so user can rewind the record forward/backward.
Some stupid sites have media player 3cm wide for 60 minutes record. E.g. radio stream record.
Therefore I really need that Stylish directive to make players' width a bit more reasonable.
So... Youtube player starts to shift video to the right, leaving black band at the left of the player. If I try to specify 800px of minimal width, almost entire video disappears below right edge. 380px is a minimal width Youtube can tolerate.
As a result I have:
mini-video of MinVid extension shifted right by black space.
My priority is Stylish, therefore I must renounce using MinVid.
Thank you!
----------8<-----------cut and dump----------8<-----------

Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream: https://github.com/mozilla/activity-stream/issues/new
- Tab Center: https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search: https://github.com/mozilla/universal-search/issues/new
- No More 404s: https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot: https://github.com/mozilla-services/pageshot/issues/new
- Min Vid: https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection: https://github.com/mozilla/blok/issues/new

**Comment by ghost** [comment]
@rayborn -- any ideas for the first issue?

I filed your issue 2 at https://github.com/meandavejustice/min-vid/issues/426

**Comment by ghost** [comment]
I tried to reproduce #1 today and didn't so I assume this is fixed.
