### ISSUE TITLE
The "puzzle", "spaceship", and "chat bubbles" icons are no longer displayed on page bottom (staging)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1558]
Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to testpilot.stage.mozaws.net.
2. Scroll to the bottom part of the page and observe the icons above the install button.

[Expected results]:
- The "puzzle", "spaceship" and "chat bubbles" icons are correctly displayed above their messages. 

[Actual results]:
- All 3 icons icons are no longer displayed on the bottom of the page. 

[Notes]:
- Added a screenshot with the issue:

![test pilot bottom icons](https://cloud.githubusercontent.com/assets/19226534/19234760/71734cf2-8ef6-11e6-9e85-343fb27c4d18.png)

**Comment by lmorchard** [comment]
Looks like we need to set `Content-Type` headers for `*.svg` images in static deployment:

``` bash
➜  testpilot git:(master) ✗ curl -sD - -X HEAD https://testpilot.stage.mozaws.net/static/images/add-on.a0600b1d.svg
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
```
