### ISSUE TITLE
The "Privacy" and "Terms" pages from Test Pilot are no longer available (staging)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1559]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on the "Privacy" or "Terms of Use" text links under the page green buttons.

[Expected result]:
- The pages are successfully loaded and correctly rendered.

[Actual result]:
- "Four Oh Four!" page is displayed.

**Comment by lmorchard** [comment]
Hmm, [`/privacy`](https://testpilot.stage.mozaws.net/privacy) and [`/privacy/`](https://testpilot.stage.mozaws.net/privacy/) don't work - but [`/privacy/index.html`](https://testpilot.stage.mozaws.net/privacy/index.html) works. 

Do we not / can we not have web hosting turned on for the S3 bucket in staging to handle default pages? [`/privacy`](https://testpilot-static.dev.mozaws.net/privacy) & [`/privacy/`](https://testpilot-static.dev.mozaws.net/privacy/) both work on static dev where web hosting is on. But, I know things have changed on staging as we've had to figure out how to set additional headers that aren't set for dev

**Comment by relud** [comment]
stage is using index.html as the default index page, so i don't know why /privacy/ wouldn't work v_v, i'll investigate this today

**Comment by relud** [comment]
if i can't figure it out without s3 website, i can enable that.

**Comment by relud** [comment]
this is resolved

**Comment by ghost** [comment]
closing for last comment. thanks
