### ISSUE TITLE
The "GitHub" and "Twitter" social buttons are no longer visible on page bottom (staging)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1560]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Scroll to the button of the page and observe the elements on the right side.

[Expected result]:
- The "GitHub" and "Twitter" social buttons are displayed on the bottom right of the page.

[Actual result]:
- The "GitHub" and "Twitter" social buttons are no longer displayed on the bottom right of the page.

**Comment by lmorchard** [comment]
Looks like we need to set `Content-Type` headers for `*.svg` images in static deployment (same as #1558):

``` bash
➜  testpilot git:(master) ✗ curl -sD - -X HEAD https://testpilot.stage.mozaws.net/static/images/github-icon.21d4d530.svg
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
```
