### ISSUE TITLE
The closing  "X" button from "Take the Tour" pop-up is not visible but still working

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1562]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net/experiments/" page.
2. Click on one of the available experiments and choose to "Enable" it.
3. Observe the closing "X" button from the "Take the Tour" displayed pop-up.

[Expected result]:
- The "X" button is visible on the top right of the displayed pop-up.

[Actual result]:
-  The "X" button is not visible on the display pop-up.

[Notes]:
- The button works if you click in the designed area but it's not visible.

**Comment by johngruen** [comment]
Likely has the same fix as #1558

**Comment by lmorchard** [comment]
Hmm, `/privacy` and `/privacy/` don't work - but [`/privacy/index.html`](https://testpilot.stage.mozaws.net/privacy/index.html) works. 

Do we not have web hosting turned on for the S3 bucket in staging to handle default pages? [This works on static dev](https://testpilot-static.dev.mozaws.net/privacy)

**Comment by lmorchard** [comment]
Looks like we need to set `Content-Type` headers for `*.svg` images in static deployment (same as #1558):

``` bash
➜  testpilot git:(master) ✗ curl -sD - -X HEAD https://testpilot.stage.mozaws.net/static/images/close-icon.a2bcaf72.svg
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
```

**Comment by johngruen** [comment]
@clouserw @lmorchard I realize that #1562, #1560, #1559 and #1558 are all small fixes, but i've added the critical label since they'll need to be fixed before a production push
