### ISSUE TITLE
Activity Stream Forum Editor

### ISSUE THREAD

**Issue by bitshifter52** [mozilla/testpilot#1563]
I was trying to enter a suggestion in the "testpilot" forum and tried to had a web link using ctrl-k. The link dialog box appeared but I couldn't make it close and then I lost my entire post. I'm running Ubuntu 16.04 and Firefox 49.0.

**Comment by johngruen** [comment]
Hey @bitshifter52, I just tested this out, and it looks like an upstream issue (meaning it's a problem in Firefox, rather than with Activity Stream or Test Pilot in particular). I've filed a bug on Bugzilla to track the problem for you:

https://bugzilla.mozilla.org/show_bug.cgi?id=1308931
