### ISSUE TITLE
Enable Tracking Protection in Private Mode for Tracking Experiment Users

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1565]
Blok does some stuff to Tracking Protection, we should make sure `privacy.trackingprotection.pbmode.enabled` is set to `true` for experiment users.

**Comment by johngruen** [comment]
@dannycoates can you pick this one up this sprint

**Comment by johngruen** [comment]
@groovecoder could probably grab it too if necessary

**Comment by groovecoder** [comment]
Looks trivial to fix this for future TxP experimenters. (We can just remove the `experiment-hacks.js` that changed the pref values.

But is there an `updated` hook where we can reset all existing TxP experimenters' prefs back to the values they had before they installed/enabled the experiment?

**Comment by dannycoates** [comment]
> But is there an updated hook where we can reset all existing TxP experimenters' prefs back to the values they had before they installed/enabled the experiment?

#1566 should cover all the bases
