### ISSUE TITLE
NoMore404s cannot be enable on staging 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1573]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net/experiments/" page.
2. Click on NoMore404s experiment and choose to "Enable" it.
3. Observe the browser behavior.

[Expected result]:
- The experiment is successfully enabled.

[Actual result]:
- The experiment could not be enabled. "Uh oh. No More 404s could not be enabled ..." error is displayed.

[Notes]:
- Here are the console errors when trying to enabling the experiment:

![nomore404s browser console](https://cloud.githubusercontent.com/assets/19226534/19272227/74efc3bc-8fd0-11e6-9b04-b1f5d229fcde.png)

**Comment by ghost** [comment]
This was due to mishandled encoding of the '+' in the URL.  Fixed now.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible on production.

**Comment by ghost** [comment]
This will be fixed by https://github.com/mozilla/testpilot/pull/1579

This was due to NoMore404s being around before our nginx proxy so it links directly to the CDN.  That also means it doesn't get the proper headers from the proxy.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on stage and production servers. I have tested this on the latest Firefox (49.0.1) release and latest Nightly (52.0a1) build on Windows and Mac.
