### ISSUE TITLE
You are wrongly redirected to Test Pilot homepage while you visit "Privacy" and "Terms" pages and after you click on the Firefox logo

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1574]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net/experiments/" page.
2. Scroll the page and from the bottom click the "Privacy" link.
3. Scroll the page and from the bottom click the "Terms" link.
4. Click the Test Pilot Firefox icon from the top of the page.
5. Observe the browser behavior.

[Expected result]:
- You are redirected to the "https://testpilot.stage.mozaws.net/experiments/" page.

[Actual result]:
- You are wrongly redirected to "https://testpilot.stage.mozaws.net/" page. 

[Notes]:
- Added a screen recording with the issue: https://goo.gl/lCYVuk.

**Comment by chuckharmston** [comment]
I'm going to work on #1372, which will fix this.

**Comment by chuckharmston** [comment]
Apparently #1372 did not fix this; I'll keep investigating.

**Comment by SoftVision-CosminMuntean** [comment]
Verified this after the fix for #1615 was deployed and it's no longer reproducible with the original steps. 
Tested on dev server with the latest Firefox (49.0.1) release and latest Nightly (52.0a1) build.

Base on this, I will close this issue as resolved fixed.
