### ISSUE TITLE
Get our Google Analytics on SSL

### ISSUE THREAD

**Issue by clouserw** [mozilla/testpilot#1578]
In our CSP we allowlist www.google-analytics.com.  I noticed AMO is allowing https://ssl.google-analytics.com.  I like that https restriction.  Let's do that for us too -- why are they using ssl.\* instead of www.* and how do we do that?

**Comment by chuckharmston** [comment]
Once this lands, we'll want to verify that telemetry—both from the website and the add-on—is working as expected and doesn't regress.
