### ISSUE TITLE
Implement transitions between page views?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#159]
We're building this shiny single-page-app. Maybe it should have some tasteful transitions between page views?

**Comment by jaredhirsch** [comment]
The ampersand-page-switcher has hooks built in to handle cross-page transitions

Edited: sorry, I mean the [ampersand-view-switcher](https://github.com/AmpersandJS/ampersand-view-switcher). See the readme for animation examples.

**Comment by johngruen** [comment]
@lmorchard yeah, probably should. Preferably we could get away with using CSS to fade into views a bit.

Only issue I see is that RN the `#main-footer` is in that outer index file and isn't injected with the views.

**Comment by johngruen** [comment]
Oh, yeah so PR #210 should make this a lot easier to implement.

**Comment by lmorchard** [comment]
https://github.com/mozilla/idea-town/commit/5c2f837ee8a47680f32bef493c5e77ba2b1eacd6
