### ISSUE TITLE
Move settings menu into its own component

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1590]
We currently have the settings menu fully contained inside of the [`Header`](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/Header.js) component. We should break it out into its own component.

**Comment by aayushsanghavi** [comment]
I'd like to take this issue. Could you tell me how to proceed?

**Comment by yjkimjunior** [comment]
@aayushsanghavi If you check out the Header component, in renderSettingsMenu(), you can see the JSX for the settings menu directly coded into the function. You can copy that code exactly and make it its own component, i.e. Settings.js

Then in renderSettingsMenu() you can just return the <Settings > component.

**Comment by aayushsanghavi** [comment]
Thanks @yjkimjunior but I guess that wouldn't work because the code under renderSettingsMenu uses a lot of the methods of the Header component. So simply copy pasting the code won't help.

**Comment by aayushsanghavi** [comment]
@chuckharmston @johngruen could you tell me how to proceed with the issue?

**Comment by yjkimjunior** [comment]
@aayushsanghavi My bad, I commented after only a cursory glance. You'll want to use props in order to pass information from the Header component to the Settings component, which would be its child. If I'm not mistaken, you will also want to write a separate Settings-test.js file to stay consistent with the Shallow rendering in the rest of the test files.

**Comment by pmespresso** [comment]
@aayushsanghavi sorry I went ahead and made a PR on this. My initial advice was wrong, but if you look at the change I made, you'll see that we can use methods in the Header component from the new Settings component by using props. 

This is a good source:
https://www.tutorialspoint.com/reactjs/reactjs_props_overview.htm

**Comment by aayushsanghavi** [comment]
@yjkimjunior great! I was going to tell you to take it up if you wanted to. I was working on other issues.
