### ISSUE TITLE
Move retire dialog into its own component

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1592]
We currently have the retirement dialog fully contained inside of the [`Header`](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/Header.js) component. We should break it out into its own component. Additionally, we should also try to divorce it from `#main-header` in the DOM, instead making it a child of the (to-be-committed) `.view` element.

**Comment by lmorchard** [comment]
We have a [RetireConfirmationDialog](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/RetireConfirmationDialog.js) component which is _used_ by Header. Do you mean it should be used somewhere else?

**Comment by ckprice** [comment]
Think it is now, closing.
