### ISSUE TITLE
Inconsistent comma use on experiments vs details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1594]
Found in http://testpilot.dev.mozaws.net/__version__ (5641deddb006f95b8969b2fbac45ae2dd1fdc061):

``` js
{ "commit": "5641deddb006f95b8969b2fbac45ae2dd1fdc061",
  "source": "https://github.com/mozilla/testpilot",
  "version": "",
  "build": "https://circleci.com/gh/mozilla/testpilot/1300"}
```

---
### Steps to reproduce:
1. Go to homepage and look at the installation count formatting (with comma).
2. Go to experiment details page and look at the installation count formatting (sans comma).
### Actual results:

<img width="719" alt="firefox_test_pilot" src="https://cloud.githubusercontent.com/assets/557895/19322574/79189042-906e-11e6-8c2e-182aff01d36c.png">
**Figure 1:** Homepage, with comma.

---

<img width="719" alt="firefox_test_pilot" src="https://cloud.githubusercontent.com/assets/557895/19322615/9f1fb838-906e-11e6-8b1f-360ec09d8a68.png">
**Figure 2:** Details page, without comma.
### Expected results:

Let's add a comma to the details page, since it looks prettier (although I suppose adds some locale consideration at some point -- since not all locales use commas as a separator).

**Comment by SoftVision-CosminMuntean** [comment]
Since we are talking about this kind of issues, I have a similar one. The Page Shot experiment description from "about:addons" page has no "dot" at the end. All the others have.

![page shot description](https://cloud.githubusercontent.com/assets/19226534/19393968/b7fcae88-923f-11e6-8503-70a012eaeb1a.png)

**Comment by johngruen** [comment]
Can no longer repro, closing. will file issue to add period on to end of Page Shot Desc.
