### ISSUE TITLE
Related experiments not displayed if you have Test Pilot add-on installed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1596]
Found in http://testpilot.dev.mozaws.net/__version__ (5641deddb006f95b8969b2fbac45ae2dd1fdc061):

``` js
{ "commit": "5641deddb006f95b8969b2fbac45ae2dd1fdc061",
  "source": "https://github.com/mozilla/testpilot",
  "version": "",
  "build": "https://circleci.com/gh/mozilla/testpilot/1300"}
```

---
### Steps to reproduce:
1. Go to http://testpilot.dev.mozaws.net and install the Test Pilot add-on.
2. Go to experiment details page (ie: http://testpilot.dev.mozaws.net/experiments/tracking-protection)
3. Scroll to bottom of the page. (Should look like **Figure 1** below).
4. Open same page in Chrome (or disable the Test Pilot add-on in about:addons).
### Actual results:

Oddly, when I have the Test Pilot add-on installed, I don't see related experiments (which is arguably when I'd want it most).

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/19323329/5222c8a6-9071-11e6-9a2e-6e8c2668278f.png)
**Figure 1:** Tracking Protection experiment page w/ Test Pilot add-on installed.

---

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/19323383/8b0e3c04-9071-11e6-87be-0616195f2e60.png)
**Figure 2:** Tracking Protection experiment page w/ Test Pilot add-on disabled.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19323423/afc193c0-9071-11e6-8290-fc0790d70152.png)

**Comment by chuckharmston** [comment]
That's actually by design.

@johngruen might have more to say about it.

**Comment by pdehaan** [comment]
> @johngruen might have more to say about it.

Why we do dis, @johngruen?
I've gone to the effort of installing Test Pilot add-on and am interested in an experiment. Why would we hide the other experiments from this view?

**Comment by SoftVision-PaulOiegas** [comment]
+1 to Peeter's idea. We were asking the same thing a while ago...
