### ISSUE TITLE
Audit the libraries we are using in package.json

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1597]
Let's make sure we're up to date!

**Comment by pdehaan** [comment]
Plus don't forget we have a nested package.json file for the add-on:
https://github.com/mozilla/testpilot/blob/master/addon/package.json

**Comment by ghost** [comment]
I enabled greenkeeper.io on our repository which will take care of the top level one.  It doesn't have support for deeper files, but is marked as "will be completed" at https://github.com/greenkeeperio/greenkeeper/issues/139
