### ISSUE TITLE
Absorb idea-town-addon into idea-town repo?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#160]
So, I know we went through a whole pile of repo creation / renaming / merging at the start of this project. But, I'm wondering if maybe we want to do one more and pull [idea-town-addon](https://github.com/mozilla/idea-town-addon/) into a subdirectory of this repo. 

Benefits could include sharing issues list, having atomic commits that cover all of the server / frontend / add-on changes needed for a feature. We can also tweak Travis CI to run all the relevant tests together.

Downsides? (that is, besides the yak shaving churn such a merge will stir up)

**Comment by meandavejustice** [comment]
@lmorchard I don't see any downsides to this. I'm :+1:

**Comment by lmorchard** [comment]
Cool! FWIW, in case you haven't seen it before, [`git filter-branch`](https://www.google.com/search?q=git+filter+branch+merge+repos&ie=utf-8&oe=utf-8) is a nifty tool that helps in merging repos while preserving history. Could be interesting to pull idea-town-addon into an addon/ subdirectory with all its commits intact.

**Comment by chuckharmston** [comment]
Make sure you use [`filter-branch`](https://git-scm.com/docs/git-filter-branch) to preserve history while merging.

Ninja: doh, Les beat me to it.

**Comment by meandavejustice** [comment]
woah, I hadn't seen that. thanks!

**Comment by lmorchard** [comment]
And of course, this isn't a priority at all unless it makes some things easier. We can get around to it in between other tasks as polish later, if it's a distraction

**Comment by meandavejustice** [comment]
Gunna go ahead and tackle this now, as it will make some of my upcoming tasks easier
