### ISSUE TITLE
Provide a method of letting users know if experiments are not localized to their language

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1600]
When we ship our German experiments, we generally don't want to prevent German speakers from using non-localized experiments. We should provide UI letting German speaking experimenters know if an experiment is EN only.

**Comment by chuckharmston** [comment]
Are we just doing this for German, or for all localizations? Do we care about region codes? What about users who speak multiple languages, but have a preference?

**Comment by johngruen** [comment]
Probably for all languages, although we'll pilot with German. I don't really care about region codes, but we don't have full requirements yet.

**Comment by chuckharmston** [comment]
#1695
