### ISSUE TITLE
After Tracking Protection is actively blocking a page content, the GA events are no longer working on TP pages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1601]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to testpilot.dev.mozaws.net page.
2. CLick on "tracking Protection" experiment from the page and choose to "Enable" it. 
3. On the same tab or on a new one, navigate to http://mashable.com.
4 After the page is completely loaded, navigate to http://testpilot.dev.mozaws.net/ and open the browser console (Ctrl+Shift+J).
5. From Test Pilot page click one of the experiments cards and observe the browser console NET section. 

[Expected result]:
- You can observe a "GET https://www.google-analytics.com/collect" request for the visited page.

[Actual result]:
- The GA events are no longer displayed in browser console NET section for the visited page.

[Notes]:
- Even if the browser is restarted, the GA events are still not displayed in browser console.
- This issue is also reproducible on stage and production servers.
- The issue is no longer reproducible if you disable Tracking Protection experiment.
- Added a screen recording with the issue: https://goo.gl/KZu4xZ.

**Comment by chuckharmston** [comment]
Pretty sure that is Tracking Protection working as intended.

@groovecoder, want to confirm that?

**Comment by SoftVision-PaulOiegas** [comment]
But wouldn't this affect our GA metrics since the pageview events don't show up anymore for any Test Pilot page we visit ?

**Comment by chuckharmston** [comment]
It would. There isn't much we can do about that, though; we're not going to whitelist Test Pilot in Tracking Protection.

**Comment by lmorchard** [comment]
It would affect every site's metrics (including ours), because the user is blocking metrics tracking. I don't think we want to make an exception for ourselves

**Comment by groovecoder** [comment]
👍 @chuckharmston @lmorchard.
