### ISSUE TITLE
Allow experiments to be hidden from users with specific locales.

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1602]
Basically, there's a collision between our upcoming German search experiment and Universal Search. We should decouple the timelines here by adding an optional flag to the YAML that lets us disable certain experiments for certain locales.

**Comment by chuckharmston** [comment]
- What does `hide` mean here? Do we just exclude them from experiment lists, or go a step further and 404 pages?
-  What does `locale` mean here? `navigator.language` generally returns the language the user has localized the browser in, while `navigator.languages` has a list of the user's language preferences from `Accept-Language`.
- Do we care about region codes? i.e. since we're language as a proxy for "region", do we only restrict the experiment to `de-DE`, or `de*`? Is this different when blacklisting languages rather than whitelisting them?

**Comment by johngruen** [comment]
- We should 404 them
- locale probably means first choice language header, but it's negotiable
- AFAIK we do not care about region codes

**Comment by chuckharmston** [comment]
> We should 404 them

This prospectively has search engine and social consequences. (Which is probably fine, just making sure we understand all the consequences of this.)

> AFAIK we do not care about region codes

There are places where this may or may not matter. There's not a huge difference between `en-US` and `en-GB`, but there is a bigger difference between `zh-CN` or `zh-SG`, for example. (And `Accept-Language` does use region codes, fwiw.)

**Comment by johngruen** [comment]
`This prospectively has search engine and social consequences. (Which is probably fine, just making sure we understand all the consequences of this.)`

yeah, maybe we could do slightly better than 404-ing, but i'd call that a stretch. This issue is basically just a helper so we don't have to sunset U-Search and launch German search experiment on the same schedule.

> There are places where this may or may not matter. There's not a huge difference between en-US and en-GB, but there is a bigger difference between zh-CN or zh-SG, for example. (And Accept-Language does use region codes, fwiw.)

Good point, I think we can localize as needed. For our time frame de-\* will do, but in future, i could see us calving off regions. Swiss German is pretty seriously different than de-DE.

**Comment by chuckharmston** [comment]
To contrast with #1670:

Only show Bar Experiment to users who do not speak Azerbaijani (`do not speak` defined above).

**Comment by lmorchard** [comment]
> What are the locale values meant to be, here? For example, it looks like this collapses en-US, en-GB, & en-NZ into just en and es-MX, es-ES, & es-CO into just es. Is that what we want? They're definitely different locales, despite shared languages.

Left that comment over on #1686 - ignoring locales and just using language seems strange.
