### ISSUE TITLE
Use mzl.la links on sharing page.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1604]
https://testpilot.firefox.com/share has a few links to Test Pilot with various GA `utm_` params. We should consider swapping them out with mzl.la-shortened versions of the link, if only for aesthetic reasons.

All mozilla.org links shortened on bit.ly are automatically made with the mzl.la domain, but since we're on firefox.com, it's not automatic. I believe that a logged-in user of the account that controls mzl.la can handle the creation of these links for us. Might take some digging to figure out who that is.

CC @ckprice

**Comment by ckprice** [comment]
I have the keys

http://mzl.la/2dMREdP

also

http://mzl.la/this-is-hot

**Comment by chuckharmston** [comment]
Sweet! We'll have four links we want shortened:

https://testpilot.firefox.com/?utm_source=twitter&utm_medium=social&utm_campaign=share-page
https://testpilot.firefox.com/?utm_source=facebook&utm_medium=social&utm_campaign=share-page
https://testpilot.firefox.com/?utm_source=email&utm_medium=social&utm_campaign=share-page
https://testpilot.firefox.com/?utm_source=copy&utm_medium=social&utm_campaign=share-page

**Comment by ckprice** [comment]
Here are the links. I'm going to keep myself assigned here, but may not be this sprint.

> https://testpilot.firefox.com/?utm_source=twitter&utm_medium=social&utm_campaign=share-page

https://mzl.la/2e7huGS

> https://testpilot.firefox.com/?utm_source=facebook&utm_medium=social&utm_campaign=share-page

https://mzl.la/2dheNkx

> https://testpilot.firefox.com/?utm_source=email&utm_medium=social&utm_campaign=share-page

https://mzl.la/2dZByMS

> https://testpilot.firefox.com/?utm_source=copy&utm_medium=social&utm_campaign=share-page

https://mzl.la/2dps7H1

**Comment by ghost** [comment]
Marking this as a good first bug since the links are already made.  I think the only stuff left here is to replace the links mentioned above in the code with the short links in the previous comment.

**Comment by epq** [comment]
I'd like to work on this issue.
