### ISSUE TITLE
addon installed state races on home page

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#1606]
I managed to trigger two unfortunate races setting the installed state of the addon that caused the experiment list page to show the no-addon version instead of the (correct) with-addon version. Once the page was in the no-addon state it stayed there.

I added a few `console.warn` lines before each dispatch of `setHasAddon`. Here's the log from a time when the page goes from the loading view to no-addon view.

<img width="798" alt="screen shot 2016-10-13 at 10 42 58 am" src="https://cloud.githubusercontent.com/assets/87619/19361889/464dca62-9139-11e6-90bc-c61a07e93bef.png">

And here's a particularly weird one where the page goes from loading flashing to with-addon but then quickly to no-addon.

<img width="883" alt="screen shot 2016-10-13 at 11 06 43 am" src="https://cloud.githubusercontent.com/assets/87619/19361896/5020a802-9139-11e6-828c-1d4f641ade82.png">

**Comment by dannycoates** [comment]
Happens in prod too, so it wasn't added this week

**Comment by dannycoates** [comment]
This is PageMod being a jerk. The short of it is that the `detach` [event](https://github.com/mozilla/testpilot/blob/master/addon/data/set-installed-flag.js#L14) from a previous page load can trigger on the current page and _trick_ the frontend into thinking the addon is gone.

It doesn't look like a "normal" page refresh is problematic so far, but when you navigate by changing the url (or not) in the address bar and hitting enter there's a chance you'll get this behavior.

**Comment by SoftVision-PaulOiegas** [comment]
Isn't this the same issue from #1574 ?

**Comment by dannycoates** [comment]
> Isn't this the same issue from #1574 ?

Indeed it is!
