### ISSUE TITLE
Add Sentry to Test Pilot

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1609]
We never got this fully integrated with Django, so we closed the bug, but Sentry provides client side error reporting as well.  Let's hook that up so we can see what our users are seeing.

@relud -- is there a server we can send Sentry reports to already?

**Comment by relud** [comment]
yes, cloudops has a sentry you can send reports to

**Comment by relud** [comment]
for prod: https://5e095c0c62ff4f118675ca98e1e2a1df:dd848e4f87474449a3b664d51eaa3411@sentry.prod.mozaws.net/168

**Comment by relud** [comment]
I'm silly and pasted the private one before. I revoked that. here's the public dsn for testpilot-prod https://51e23d7263e348a7a3b90a5357c61cb2@sentry.prod.mozaws.net/168
