### ISSUE TITLE
Do something with our CSP Reports

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1610]
We have CSP error reports coming in, but I don't think they go anywhere.  We should collect them and see if there are any problems with our rules.  

Random ideas:  maybe we could transform them somehow and send them through to Sentry? (#1609).  Otherwise, something in datadog?

**Comment by jvehent** [comment]
We have standard integration in cloudops to capture those in nginx and route them to elasticsearch. That's how AMO does it.

**Comment by ghost** [comment]
Sweet. /cc @relud for when he's back

**Comment by relud** [comment]
@jvehent can you link me to that configuration, and will that work with testpilot being fronted by a cdn? (i don't know how this works at all)

**Comment by jvehent** [comment]
@relud: I believe it will work fine with the CDN as long as POST requests make it to Nginx.

AMO has a sample conf here: https://github.com/mozilla-services/puppet-config/blob/master/amo/modules/amo_proxy/templates/nginx.csp.conf.erb
Which uses this log format: https://github.com/mozilla-services/puppet-config/blob/master/amo/modules/amo_proxy/templates/nginx.service.conf#L29
Then all you have to do is capture the content of CSP.log into the logging pipeline.

**Comment by ghost** [comment]
Reassigning to me.  I can't assign relud to this, apparently, but I've confirmed it's in his wheelhouse and he's just looking for time to do it.

**Comment by jvehent** [comment]
Allow me to share (privately) the good stuff: https://github.com/mozilla-services/cloudsec/blob/master/docs/cspreport.md

**Comment by jaredhirsch** [comment]
@wresuolc I added @relud to the TxP github team, assigning to him 👍

**Comment by jvehent** [comment]
cc @g-k for help

**Comment by relud** [comment]
actually I've got it, i just need to find a moment to /do/ it.

**Comment by relud** [comment]
this is implemented by mozilla-services/cloudops-deployment#311

**Comment by ghost** [comment]
@relud how can we see these logs? (and/or get alerts?)

**Comment by relud** [comment]
@wresuolc you can access csp reports for stage here: https://testpilot-kibana.stage.mozaws.net/_plugin/kibana/#/discover

the list of people with access is currently being managed in puppet, so for others to get access I would need a list of people to allow.

**Comment by ghost** [comment]
I can log in there and can see reports, thanks.  Is this something we can enable on production?

**Comment by relud** [comment]
yes, but it requires re-deploying the nginx servers in prod.

**Comment by ghost** [comment]
@relud Can we schedule that? :)

**Comment by relud** [comment]
tomorrow, Tuesday march 7th, at 11am Pacific

**Comment by relud** [comment]
https://testpilot-kibana.prod.mozaws.net/_plugin/kibana/#/discover

**Comment by ghost** [comment]
Thanks @relud.  CSP reports from production are now available at https://testpilot-kibana.prod.mozaws.net/_plugin/kibana/ .  I didn't see anything scary in there, fwiw.
