### ISSUE TITLE
Page parameters are stripped from URL when sharing with Test Pilot add-on installed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1618]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Test Pilot add-on was previously installed on a lean new Firefox profile.
- A Facebook or Twitter profile is already logged in.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.firefox.com/share/" page.
2. Click on any of the 3 sharing options (eg: Facebook).
3. After redirected on the social network sharing page/new email, choose to post/tweet/send the message. 
4. Open the social network profile page / email client.
5. While watching the address bar URL, click on the previously posted message / sent url. 

[Expected result]:
- The Test Pilot experiments page is correctly loaded and the URL displays also the shared page parameters.

[Actual result]:
- The Test Pilot experiments page is correctly loaded but the page parameters from the URL are striped after less than a second of display.

[Notes]:
- This only happens if the Test Pilot add-on is installed.
- This also happens for the Twitter and email share.
- Here is a screen recording of the issue: https://goo.gl/CnOFmu.

**Comment by ghost** [comment]
ref #1603

**Comment by ghost** [comment]
I can no longer reproduce this (some discussion in #1575 ).  Tentatively closing...
