### ISSUE TITLE
Too frequent requests for surveys

### ISSUE THREAD

**Issue by AngelEzquerra** [mozilla/testpilot#1621]
I just disabled one of the TestPilot addons, tab center. TestPilot asked me to complete a survey. I do not mind that. In fact I like to give feedback to improve the products I use when I can. However about 1 minute earlier I had submitted a suggestion for tab center after which I had voluntarily participated in the optional survey that comes after submitting the issue. I assume both surveys would be the same. I think that TestPilot should take that into account when suggesting you to take yet another survey (i.e. do not ask to take the same survey so soon).

**Comment by johngruen** [comment]
What if we:
- [ ] delay heartbeat for 48 hours if a user has just taken a survey
- [ ] make the disable confirmation modal's primary control a simple confirmation if a user has given feedback in the last 48 hours

**Comment by sevaan** [comment]
Sounds good. To reiterate:

- [ ] Delay Heartbeat for 48 hours if a user has just taken a survey
- [ ] If a user has taken a survey in last 48 hours and disables an experiment, change the "Take a quick survey" button in the Thank You modal to "Got it" and make the action close the modal on click.

![thank you no survey](https://cloud.githubusercontent.com/assets/473531/21865157/ea7292ec-d812-11e6-89b8-83ac156fcb27.png)

**Comment by johngruen** [comment]
This is per-experiment. So if a user has given feedback for Tab Center then disabled Min Vid they should still be prompted for feedback for Min Vid

**Comment by sevaan** [comment]
Thanks for clarifying.

**Comment by johngruen** [comment]
@johngruen will figure out a _holistic_ strategy here

**Comment by johngruen** [comment]
we dropped the Heartbeat style random surveys. Closing!
