### ISSUE TITLE
Install count numbers down drastically

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1622]
https://analysis-output.telemetry.mozilla.org/testpilot/data/installation-counts/latest.json

As of Friday:
- Page Shot, Min Vid, and Tracking Protection had ~70k
- Activity Stream had 80k
- Universal Search had 100k

**Comment by chuckharmston** [comment]
CC @sunahsuh, @ilanasegall

**Comment by sunahsuh** [comment]
Thanks for the alert -- this was fixed a few hours ago and we're talking about ways to increase resilience to failure in the future (conversation in #datapipeline if interested.)
