### ISSUE TITLE
Tour step events are coming in as undefined in GA

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1628]
Some housekeeping 
<img width="241" alt="screen shot 2016-10-18 at 8 17 32 pm" src="https://cloud.githubusercontent.com/assets/3323249/19490582/0003f000-9570-11e6-9b8a-bec04258e2ee.png">
<img width="272" alt="screen shot 2016-10-18 at 8 17 27 pm" src="https://cloud.githubusercontent.com/assets/3323249/19490584/00146f2a-9570-11e6-85c6-586c8a5c2562.png">
<img width="289" alt="screen shot 2016-10-18 at 8 17 15 pm" src="https://cloud.githubusercontent.com/assets/3323249/19490583/000a3f1e-9570-11e6-91b6-3983cc20fe0c.png">

**Comment by johngruen** [comment]
Hard to repro this on dev, i console logged out the event actions and they look alright...

let's see if we can see these events correctly in GA after today's push to stage.

**Comment by lmorchard** [comment]
I think this might actually be fixed with this deploy. I made some bugfixes along with writing tests for the tour dialog here: https://github.com/mozilla/testpilot/commit/4fcb83e32d944229c4b87ef998b5df249802d0ed

**Comment by lmorchard** [comment]
Yeah, I think that fixed it, going to close this issue - reopen if they come back undefined again

**Comment by johngruen** [comment]
@lmorchard confirmed stats coming through in latest prod
