### ISSUE TITLE
Set up some kind of offline work queue

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#163]
We've tossed around ideas of needing to send notifications, emails, & etc. We should use an offline work queue for that. Celery & RabbitMQ has been popular, but maybe not the best way going forward. Celery backed by Redis in dev and [Amazon ElastiCache Redis](https://aws.amazon.com/elasticache/) in production could be interesting.

**Comment by lmorchard** [comment]
It occurs to me that we might want to hold off actually implementing something here until we also have a defined feature that wants to use it.

**Comment by meandavejustice** [comment]
closing since we don't have use for a queue yet
