### ISSUE TITLE
Add back toggle to legal pages

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1641]
This is a follow up to #1638.

> So, 👍 for the changes to generated pages, and the about page gets built fine.
> 
> One question though: All these generated pages have lost their white backgrounds and the "Learn More" links are no longer there to fold up & reveal content. Is that intentional?
> 
> Old: https://www.dropbox.com/s/erfjuwspcj2sher/Screenshot%202016-10-20%2016.35.42.png?dl=0
> 
> New: https://www.dropbox.com/s/jd5kmamrgq8cre4/Screenshot%202016-10-20%2016.36.13.png?dl=0
> 
> If that's all copacetic, good to self-merge

We should land this before we go to production.

**Comment by johngruen** [comment]
@ckprice these toggles work in dev

**Comment by johngruen** [comment]
This will be fixed by whatever we do in #1636 

Here's the offending line: https://github.com/mozilla/testpilot/blob/master/frontend/src/scripts/legal.js#L24

@ckprice @lmorchard We could add if `|| 'location.pathname === '/privacy/index.html'` on that line if we like, or just close this.

**Comment by lmorchard** [comment]
Eh, maybe let's close this... we don't link to `privacy/index.html` and the only reason index.html actually exists is for website hosting mode on S3
