### ISSUE TITLE
[release] 2016-10-24 on stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1643]
_Part of our old process was having a deployment Bugzilla bug for QA to report issues. We no longer need that, so maybe we can use a GH issue. Comments welcomed_

Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.
- Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
- Release notes: https://github.com/mozilla/testpilot/releases

http://testpilot.stage.mozaws.net/

**Comment by ckprice** [comment]
We'll want to get https://github.com/mozilla/testpilot/issues/1645 and ~~https://github.com/mozilla/testpilot/issues/1641~~ merged in before we go to production.

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys, 

The tests were finalized on staging, here are the results:
**New issues:**
1. The footer links from "Privacy" page are wrongly displayed on the middle of the page  (#1648) - minor
2. Mozilla Privacy Policy text hyperlink is missing on Test Pilot "Privacy" page (#1649) - normal
3. The confirmation newsletter email is not sent after Sign Up from Test Pilot (#1650) - major
4. Two unneeded "Show More" text buttons were implemented on Test Pilot "Privacy" page (#1651 - closed) - normal 
5. The gray separating line is no longer displayed on "Settings" menu between "File an Issue" and "Uninstall Test Pilot" options (#1653) - minor
6. Test Pilot image is no longer displayed in Facebook or Twitter shared posts (#1654) - normal
7. The Newsletter text box wrongly displays letters like "g, q and f" (#1655) - minor

**Known issues:**
1. There is no domain validation for email address on the displayed newsletter pop up after installation (#1345) - still reproduces on new newsletter functionality.
2. If Test Pilot is installed from an experiment page, the "Welcome" pop-up is only displayed after navigating to "Experiments" page (#1447) - old pop up still displayed on dev and stage even with the new functionality present.

**Comment by ckprice** [comment]
We're going to do one more push to stage today, then SV will verify overnight and approve for a push tomorrow morning.

**Comment by ckprice** [comment]
Let's make sure https://github.com/mozilla/testpilot/issues/1645 is working well once we push to production.

**Comment by ckprice** [comment]
[2016-10-24](https://github.com/mozilla/testpilot/releases/tag/2016-10-24) has been merged to `stage-static`.

**Comment by ckprice** [comment]
This was verified by @SoftVision-PaulOiegas on production.
