### ISSUE TITLE
Mozilla Privacy Policy text hyperlink is missing on Test Pilot "Privacy" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1649]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Firefox and navigate to testpilot.stage.mozaws.net page.
2. Click on the "Privacy Notice" text link under the "Install the Test Pilot Add-on" green button.
3. Click the first "Learn More" text link to expand it's section.
4.  Click on the "Mozilla Privacy Policy" text link from the expanded section second sentence.

[Expected result]:
- You are redirected to Mozilla Privacy Policy page.

[Actual result]:
- The "Mozilla Privacy Policy" text does not have a hyperlink under it.

[Notes]:
- Based on the preview functionality and the new designs there should be a hyperlink under the mentioned words.

![missing hyperlink](https://cloud.githubusercontent.com/assets/17258026/19593178/f0952138-9787-11e6-9df9-2a34db92f074.png)

**Comment by ghost** [comment]
John says he couldn't reproduce this locally, although I definitely saw it on stage as well.  Once the two PR's touching the privacy page land, let's test this again.

**Comment by ghost** [comment]
I'm seeing this fixed on https://testpilot.dev.mozaws.net/privacy after John's patches landed earlier so I'll assume it's good now.  Thanks for filing.

**Comment by SoftVision-PaulOiegas** [comment]
Indeed, the hyperlink is now present under the text and you are correctly redirected to "Mozilla Privacy" page when clicked.
