### ISSUE TITLE
The confirmation newsletter email is not sent after Sign Up from Test Pilot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1650]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Firefox and navigate to testpilot.stage.mozaws.net.
2. From the bottom of the page click on the text box for newsletter sign up.
3. Enter a valid mail, check the "I'm ok with..." checkbox and click the "Sign Up Now" button.
4. Open the email client and check for an email from Test Pilot.

[Expected result]:
- A confirmation email from Test Pilot was received on the email client.

[Actual result]:
- No confirmation email is received from Test Pilot.

**Comment by chuckharmston** [comment]
@SoftVision-CosminMuntean Can you try to reproduce with the network tab open? Two possible problems here:
1. You're getting an error in the request to `https://basket.mozilla.org/news/subscribe/` (i.e. `4xx` or `5xx` status codes and we are not correctly reporting it, or;
2. You're getting a `200`  and Basket isn't sending the confirmation emails.

**Comment by chuckharmston** [comment]
Note: our newsletter service throttles subscription requests, so receiving `429`s after multiple submissions is expected, though we should be appropriately handling the error.

**Comment by chuckharmston** [comment]
If it's the first problem, https://github.com/mozilla/testpilot/pull/1652 will close this.

**Comment by SoftVision-CosminMuntean** [comment]
Here are the net console logs:

![sign up now test pilot](https://cloud.githubusercontent.com/assets/19226534/19596294/929f1e08-9796-11e6-8b0c-b9dad9502e1f.png)

**Comment by chuckharmston** [comment]
@SoftVision-CiprianMuresan Sorry for ambiguity; not in the browser console, but in the network tab of the developer tools. I'm looking for a request like this:

<img width="1187" alt="screen shot 2016-10-21 at 5 02 24 am" src="https://cloud.githubusercontent.com/assets/23885/19596392/a217592c-974b-11e6-93b3-2ee95723d7e9.png">

**Comment by SoftVision-CosminMuntean** [comment]
Yeah, my bad, I was thinking at something else.

![error console](https://cloud.githubusercontent.com/assets/19226534/19596481/8169ccc2-9797-11e6-80ec-f1736d8e1827.png)

**Comment by chuckharmston** [comment]
Great, #1652 should solve this. Thank you!

**Comment by SoftVision-CosminMuntean** [comment]
The thing is that I never received an newsletter email. Even for the first request I did today. But we'll see after your fix lands if this is still reproducible.

**Comment by chuckharmston** [comment]
@johngruen Should we be doing more specific error messaging based on error codes? Basket throttles after just one request, so at worst this will help make testcases a bit clearer.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible. The confirmation email from Test pilot is received and an error is displayed if another submission is performed with the same email. Tested on latest Firefox (49.0.2) release and latest Nightly (52.0a1) build.

However, we logged a possible enhancement for the error message displayed: #1669.
