### ISSUE TITLE
The gray separating line is no longer displayed on "Settings" menu between "File an Issue" and "Unistall Test Pilot" options

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1653]
[Affected versions]:
- Firefox 49.0.1 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to testpilot.stage.mozaws.net page.
2. Click the "Settings" button from the top right of the page and observe the menu elements.

[Expected result]:
- A gray separating line is displayed between "File an Issue" and "Unistall Test Pilot" options. 

[Actual result]:
- There is no gray separating line between "File an Issue" and "Unistall Test Pilot" options. 

[Notes]:
- Added a screenshot with the issue:

![gray seprating line](https://cloud.githubusercontent.com/assets/19226534/19598136/d9574f5e-97a1-11e6-9962-93ca65439f95.png)

**Comment by johngruen** [comment]
Oh yeah, i did that...

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible. Verified on the latest Firefox (49.0.2) release and latest Nightly (52.0a1) build.
