### ISSUE TITLE
I tried to enable and the message said I did, but there's no icon in my tool bar.  So now what?

### ISSUE THREAD

**Issue by gmbriggs** [mozilla/testpilot#1663]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by SoftVision-PaulOiegas** [comment]
Hi @gmbriggs and thanks for reporting this. Are you trying to install /enable this on a Private Window ?
Test Pilot and most of the experiments are not compatible with Firefox Private Window. In order to properly test the experiments you will need to work on a normal window.

**Comment by gmbriggs** [comment]
Yes, I always use Private Window.  So Page Save won’t be usable on Private Window then?  Maybe you could put a proviso or warning on the beta announcement so that those of us who use private windows all the time know not to bother testing the beta.

**Comment by chuckharmston** [comment]
We're tracking this issue in #1504. Thanks for the report!
