### ISSUE TITLE
Unable to take screenshot of Facebook

### ISSUE THREAD

**Issue by vze2mp9g** [mozilla/testpilot#1665]
Hello,
Great idea, but taking a screenshot on **Facebook** is impossible. I guess I have to go back to PRINT SCREEN in Windows 10. Please fix this issue ASAP.
Thanks
Dave
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by SoftVision-PaulOiegas** [comment]
Hello @vze2mp9g thanks for reporting this. Can you be a bit more specific about the steps you are performing and are failing ?
If I understand right you are trying the "Page Shot" experiment from Test Pilot and you wish to make a screenshot of a Facebook page. 

I am using Page Shot on Windows 10 with the latest Firefox 49.0.2 release and I can easily create a screenshot of a Facebook wall for example.
If you click on a specific picture or area of the page, it selects only that area. If you want to take a screenshot of the whole page, for the moment you need to click, hold and drag over the desired area to make a larger selection. We are already testing a new option for full page screenshot but it will only be available in a future version.
