### ISSUE TITLE
[Enhancement] The newsletter submission error could be a bit more explicit when it comes to multiple requests

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1669]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac

[Steps to reproduce]:
1. Open Firefox and navigate to testpilot.stage.mozaws.net.
2. From the bottom of the page click on the text box for newsletter sign up.
3. Enter a valid mail, check the "I'm ok with..." checkbox and click the "Sign Up Now" button.
4. Refresh the page and repeat step #3 using the same valid mail.
5. Observe the submitting error.

[Expected result]:
- A more complete error could be displayed for the user to understand that there is another possible cause. Maybe something like "There was an error submitting your email address or you already sent a request. Try again?".

[Actual result]:
- "There was an error submitting your email address. Try again?" error is displayed.

[Notes]:
- This comes after we logged an issue that no email was sent due to the multiple requests sent on the same email address.
- If the user won't know that this is a possibility he might think that the functionality is broken instead.

**Comment by chuckharmston** [comment]
https://github.com/mozilla/testpilot/issues/1650#issuecomment-255354933
