### ISSUE TITLE
Allow experiments to be hidden from users without specific locales.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1670]
e.g. Only show Foo Experiment to users who speak Azerbaijani

**Comment by johngruen** [comment]
@chuckharmston clarification on the needs:product label? This seems legit

**Comment by chuckharmston** [comment]
I honestly couldn't say; must have intended to put it on a different issue. Removing.

**Comment by chuckharmston** [comment]
I honestly couldn't say...must have hit the wrong bug on a list. Removing.
