### ISSUE TITLE
Use pseudolocales to ensure localization works

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1672]
In the past, I've used the 'accented English' [pseudolocale](http://informationisart.com/27/) to test if Firefox OS apps were properly localized.

Need to figure out what tooling exists for implementing pseudolocales with `.ftl` files and l20n.js.

Note: @wresuolc helped with the pseudolocale script implementation in the past and could help.

**Comment by ghost** [comment]
The way the translate-toolkit would do this is to run a script that converts the file to .po (in memory), do whatever conversions were needed, and then convert it back to your file format.  The psuedolocale you are talking about is using the `podebug` command.  You can see it at work here:  https://github.com/mozilla/addons-server/blob/master/locale/omg_new_l10n.sh#L90

It looks like the toolkit already has an ftl2po converter: https://github.com/translate/translate/blob/master/translate/convert/l20n2po.py but the issue to support L20n (https://github.com/translate/translate/issues/3389) is still open, so I don't know how well it works.

**Comment by jaredhirsch** [comment]
I asked stas about this in #l20n on IRC, sounds like l20n doesn't have a solution yet:

> I haven't really had much time to think about that, sadly
> 10:03 AM the latest code is at https://github.com/l20n/l20n.js/blob/v3.x/src/lib/pseudo.js
> 10:03 AM this is from the 3.x branch which was used in fxos
> 10:04 AM the current 4.x is very different and doesn't support pseudo yet

**Comment by ghost** [comment]
@stasm does L20n have something for this yet?

**Comment by stasm** [comment]
Not yet, sorry, we've focused on something different. I'm on PTO for the next two weeks but I filed https://github.com/projectfluent/fluent.js/issues/17 and I'll dive into it when I'm back!

**Comment by ghost** [comment]
Great, thanks.  I'm going to close this then until it's usable. Thanks!
