### ISSUE TITLE
Need toolbar icon assets

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#168]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [6a68](https://github.com/6a68)**
_Thursday Aug 13, 2015 at 16:56 GMT_
_Originally opened as https://github.com/mozilla/idea-town-addon/issues/4_

---

**Comment by bryanbell** [comment]
Icon:  http://cl.ly/1A0V3P0q3Q14
