### ISSUE TITLE
Closing the "about:addons" page after manually disabling an experiment changes the "Disable experiment" button into "Enabling..." animation

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1683]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was already added in "about:config" page with "dev" value set. 
- Test Pilot was already installed on a new clean Firefox profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to testpilot.dev.mozaws.net page.
2. Click on one of the available experiments cards and choose to "Enable" the experiment.
3. After enabled, in a new tab navigate to "about:addons" page at "Extensions" section.
4. Choose to manually remove the enabled experiment.
5. Switch back to the experiment tab leaving the "about:addons" still open.
6. While watching the "Disable" button close the "about:addons" tab.

[Expected result]:
- The disable button remains unchanged (for now). In the future we'll update it to "Enable".

[Actual result]:
- The "Disable" button changes into "Enabling..." animation for indefinite time.

[Notes]:
- Added a screen recording of the issue https://goo.gl/v6Chnr.

**Comment by jaredhirsch** [comment]
When an addon is removed inside about:addons, the addon is only disabled, not uninstalled, until the user navigates away from the page. (This is how the undo feature is implemented on about:addons: if you disable/remove, then click undo, the addon is re-enabled.)

If about:addons is then refreshed or the tab is closed (as in the STR here), the addon is then fully removed.

So, the test pilot addon must be sending a signal to the TxP site on addon removal that is interpreted incorrectly by the site.

**Comment by fzzzy** [comment]
This is just how the addon manager works because of the undo ui, there's nothing we can do about it.

**Comment by SoftVision-PaulOiegas** [comment]
Well, it seems there was something we could do since this no longer occurs after mozAddonManager merge. 😄 
Anyway, it was for "Disable", not for "Remove". Where indeed, we don't have what to do, but that was reported in a different bug.

**Comment by fzzzy** [comment]
🎉
