### ISSUE TITLE
Newsletter form checkbox, has a different outline on all OSs

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot#1684]
**[Affected versions]:**
-Firefox 49.0.2 and up

**[Affected Platforms]:**
-All Windows
-All Mac OS
-All Linux

**[Steps to reproduce]:**
1. Open Firefox and go to https://testpilot.firefox.com/ .
2. Scroll the page down and enter one letter in email field from newsletter form.
3. Observe the checkbox outline.

**[Expected result]:**
-The outline of the checkbox is red and has a shadow.

**[Actual result]:**
-The outline form the left side of the checkbox is truncated.

**[Notes]:**
-On Chrome browser the outline and shadow effects are missing from the checkbox.
-The checkbox has a different outline on Windows than on Mac OS X and than on Ubuntu.
-Added a screenshot of the issue:

![checkbox outline](https://cloud.githubusercontent.com/assets/9248513/19726464/b324057a-9b93-11e6-8ebb-267df6f33c42.png)

**Comment by chuckharmston** [comment]
This is unfortunately an oddity in how browsers handle OS chrome. Firefox on OS X, for example, adds the red outline to `:-moz-ui-invalid:not(output)`.

@johngruen or maybe @sevaan: thoughts on how you want to handle this? Few different possible approaches:
- Try to normalize the best we can. This will be unreliable and have accessibility costs.
- Use image replacement on checkboxes. This will also have accessibility costs.
- Ignore it and let browsers do what they think is appropriate.

Worth nothing: these same issues exist on the same type of UI on mozilla.org.

**Comment by johngruen** [comment]
@chuckharmston my vote is nothing
