### ISSUE TITLE
"Please fill out this field." tooltip from newsletter form is still displayed when scrolling the webpage if e10s is enabled

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot#1685]
**[Affected versions]:**
-Firefox Nightly 52.0a1 e10s enabled

**[Affected Platforms]:**
-All Windows
-All Mac OS
-All Linux

**[Steps to reproduce]:**
1. Open Firefox and go to https://testpilot.firefox.com/ .
2. Scroll the page down.
3. Click on "Sign Up Now" button from newsletter form.
4. Scroll up the webpage.

**[Expected result]:**
-"Please fill out this field." tooltip is dismissed on scroll event.

**[Actual result]:**
-"Please fill out this field." tooltip is still displayed when scrolling the webpage.

**[Notes]:**
-[Here ](https://drive.google.com/open?id=0B6QogV2AJFKiZWN3VzY3dVdHZWM)is a screen recording of the issue.

**Comment by chuckharmston** [comment]
We're using [HTML5 form validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms_in_HTML) here, so it's actually browser chrome that's not behaving appropriately here. I'm going to close this, but filed [a bug against platform](https://bugzilla.mozilla.org/show_bug.cgi?id=1313079) for the issue.
