### ISSUE TITLE
post-install onboarding

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#169]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [6a68](https://github.com/6a68)**
_Thursday Aug 13, 2015 at 20:53 GMT_
_Originally opened as https://github.com/mozilla/idea-town-addon/issues/5_

---
- [x] open a new tab pointed at `ideatown.firefox.com/home`
- [x] create toolbar button that takes the user to the same `/home` page

**Comment by meandavejustice** [comment]
<a href="https://github.com/meandavejustice"><img src="https://avatars.githubusercontent.com/u/1844554?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [meandavejustice](https://github.com/meandavejustice)**
_Tuesday Aug 18, 2015 at 19:19 GMT_

---

https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/self#loadReason

**Comment by meandavejustice** [comment]
<a href="https://github.com/meandavejustice"><img src="https://avatars.githubusercontent.com/u/1844554?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [meandavejustice](https://github.com/meandavejustice)**
_Tuesday Sep 01, 2015 at 18:34 GMT_

---

@6a68 Does this refer to explaining the user how to use the addon, and what it will be doing for the user? cc/ @johngruen

**Comment by meandavejustice** [comment]
@johngruen Can I close this issue?

**Comment by johngruen** [comment]
@meandavejustice...Sorry I've been working on some other Q4 deliverables. Leave open for now. I'll circle back to it ASAP

**Comment by johngruen** [comment]
Closing in favor of
#438
#439 
#440
