### ISSUE TITLE
[addon] Make the `npm run package` script more generic

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#170]
<a href="https://github.com/pdehaan"><img src="https://avatars.githubusercontent.com/u/557895?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pdehaan](https://github.com/pdehaan)**
_Friday Aug 28, 2015 at 22:47 GMT_
_Originally opened as https://github.com/mozilla/idea-town-addon/issues/15_

---

Currently the [package.json `package` script](https://github.com/mozilla/idea-town-addon/blob/2d00d202c5c742fba5995faefe8e53c18d9f2f13/package.json#L16) hardcodes a specific version XPI.

``` js
"package": "jpm xpi && mv @idea-town-addon-0.0.1.xpi dist/idea-town-addon-0.0.1.xpi"
```

We probably want to make that more generic so we don't need to update the package.json every time we bump versions or do releases.

We could do something a bit less fancy, like this:

```
"package": "jpm xpi && mv *.xpi dist/"
```

But that won't rename the file to remove the leading `@` (if we care).

**Comment by meandavejustice** [comment]
<a href="https://github.com/meandavejustice"><img src="https://avatars.githubusercontent.com/u/1844554?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [meandavejustice](https://github.com/meandavejustice)**
_Friday Aug 28, 2015 at 22:47 GMT_

---

@pdehaan good thinking

**Comment by meandavejustice** [comment]
<a href="https://github.com/pdehaan"><img src="https://avatars.githubusercontent.com/u/557895?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [pdehaan](https://github.com/pdehaan)**
_Saturday Aug 29, 2015 at 00:08 GMT_

---

Ref: https://github.com/mozilla-jetpack/jpm/issues/329

From the looks of the code, it seems like there should be a way to specify `options` and pass in an `xpiPath`, but I can't figure out how/if it works.

---

**UPDATE:** I can't get it working from the CLI, but here's an example of creating an XPI using the **jpm** module; https://github.com/mozilla-jetpack/jpm/issues/330#issuecomment-135920347

**Comment by pdehaan** [comment]
@meandavejustice Do we still need this, or do you think it was adequately solved via https://github.com/mozilla/idea-town/pull/231?

**Comment by meandavejustice** [comment]
@pdehaan I think #231 solved it wonderfully.

**Comment by pdehaan** [comment]
Or at least until https://github.com/mozilla-jetpack/jpm/pull/344 gets addressed.
