### ISSUE TITLE
Newsletter section from "Legacy" page is shorter than on other pages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1701]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open Firefox and navigate to testpilot.dev.mozaws.net/legacy page.
2. Scroll to the bottom of the page and observe the Newsletter signup section.
3. Navigate to testpilot.dev.mozaws.net page and observe the Newsletter section.

[Expected result]:
- Newsletter section is displayed in the same way on both pages.

[Actual result]:
- Newsletter section is displayed shorter on "Legacy" page.

![newsletter on legacy](https://cloud.githubusercontent.com/assets/17258026/19774147/beddc0f4-9c74-11e6-9af3-6ba9d6535884.png)

**Comment by chuckharmston** [comment]
It actually shouldn't be on the legacy page; that was an oversight.

**Comment by SoftVision-PaulOiegas** [comment]
Newsletter section correctly removed on dev server without affecting other page elements.
