### ISSUE TITLE
Privacy page content is wrongly positioned on the middle of the page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1702]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Steps to reproduce]:
1. Open Firefox and navigate to testpilot.dev.mozaws.net/privacy page.
2. Observe how the page content is displayed.

[Expected result]:
- The page content is positioned on the top and starts from under the Firefox logo.

[Actual result]:
- The page content is positioned on the middle of the page.

[Notes]:
- All the Test Pilot related pages (About Test Pilot and Terms) have the content starting from the top of the page. I think there should be consistency on these pages.
- Content is moved to the top of the page when "Learn More" sections are expanded.

![privacy content center](https://cloud.githubusercontent.com/assets/17258026/19774572/3d48f73c-9c76-11e6-9cf5-08c096f8412c.png)

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen This issue reappeared on the http://testpilot.dev.mozaws.net/privacy page. Probably due to the latest changes merged on the UI (#2132).

**Comment by ghost** [comment]
I just tried this in Nightly and it looks fine (no space at the top).  Marking fixed.

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc I reopened this because the footer links are now displayed under the content and not at the bottom. We have fixed in the past the same behavior but it reappeared, and it's still reproducible on dev server.

**Comment by SoftVision-PaulOiegas** [comment]
As a matter of fact, this was only partially fixed. The content was in the middle of the page when I reopened this, but now the top space was indeed removed. However, we still have the above mentioned issue with the footer links. 
In my opinion the footer should be at the bottom of the page no matter how much content we have above it.
