### ISSUE TITLE
Cannot Enable in Private Window

### ISSUE THREAD

**Issue by animally** [mozilla/testpilot#1703]
I often use a private window for testing purposes and would like to take advantage of the Page Shot. However, the Test Pilot is not available or enableable in a private browser window.

**Comment by animally** [comment]
It looks like the Tab Center works fine in private windows, but the Page Shot icon is not showing.

**Comment by chuckharmston** [comment]
Thanks for the report, @animally! We're tracking this in #1504 and have some solutions currently under consideration.
