### ISSUE TITLE
[IE11] Experiment cards rendering

### ISSUE THREAD

**Issue by jvhoven** [mozilla/testpilot#1705]
On Windows 10 using IE 11.0 the experimental cards do not render as they should. It would be great if someone could confirm this as I've tested this using BrowserStack and I do not know how reliable that is.

![selection_005](https://cloud.githubusercontent.com/assets/5366355/19783440/43fd9f12-9c92-11e6-9a81-b0995f9df4ce.png)

**Comment by dumptyd** [comment]
Yep, can confirm. But, it's working fine on edge.

![image](https://cloud.githubusercontent.com/assets/16368429/19800210/5d305a7a-9d18-11e6-93a0-d787dd7786cc.png)

**Comment by jvhoven** [comment]
Woops I edited the comment but not the title itself, I ment IE 11 ofcourse. Thank you @dumptyd!

**Comment by ckprice** [comment]
< 0.50% of our sessions were from IE11 in the last 30 days.

**Comment by johngruen** [comment]
ACTUALLY, the whole site don't load so good. I'll look at usage

**Comment by SoftVision-PaulOiegas** [comment]
Production https://testpilot.firefox.com doesn't even load on IE 11 now.
