### ISSUE TITLE
Add docs for adding new locales

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1716]
It'd probably be pretty useful to write some basic docs on getting started w/ localization in Test Pilot.

I was trying to test the new [Slovenian (sl) localization](https://github.com/mozilla/testpilot/tree/master/locales/sl) and had to do a bit of digging and hacking to wire up some pieces.

For example, I had to add `sl` to the [`<meta name="availableLanguages"/>`](https://github.com/mozilla/testpilot/blob/81b20c7d7b382dbe2deb0f1230e88bca56fb24ec/frontend/src/index.html#L9) tag (and [here too](https://github.com/mozilla/testpilot/blob/81b20c7d7b382dbe2deb0f1230e88bca56fb24ec/frontend/src/templates/index.mustache#L10)). And doing a [search for "availableLanguages"](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=availableLanguages) shows me that I should probably have added "sl" [here as well](https://github.com/mozilla/testpilot/blob/72f7d5c814ea03bebfe2d4445de5b73a447ccde4/compiled-templates/compiled-templates.js).

---

Probably not useful, but I also hackily whipped up this file which copies the ./locales/en-US/*.ftl files into the specified locale folders, and then comments out all the strings so they revert to the default values in the templates:

``` js
#!/usr/bin/env node

const { readFileSync, writeFileSync } = require('fs');
const { join } = require('path');
const { cp, ls, test } = require('shelljs');

const LOCALE_ROOT = 'locales';
const DEFAULT_LOCALE = 'en-US';

const newLocales = process.argv.slice(2);

newLocales.forEach((locale) => {
  if (localeExists(locale)) {
    return console.info(`Locale '${locale}' already exists, skipping.`);
  }

  console.log(`Locale '${locale}' doesn't exist, copying.`);
  copyLocale(locale);
});

/**
 * Checks to see if a specific locale folder already exists.
 * @param  {String} locale  [description]
 * @return {Boolean}        [description]
 */
function localeExists(locale) {
  return test('-e', join(LOCALE_ROOT, locale));
}

/**
 * Copies the default locale's files into the specified target locale folder.
 * @param  {String} locale [description]
 * @return {null}
 */
function copyLocale(locale) {
  const src = join(LOCALE_ROOT, DEFAULT_LOCALE);
  const dest = join(LOCALE_ROOT, locale);
  // Copy the default locale into new directory.
  cp('-rn', src, dest);

  // Comment out the translated strings in the new .ftl files.
  getLocaleFiles(locale)
    .forEach((ftl) => {
      const contents = readFileSync(ftl).toString()
        .split('\n')
        .map((line) => {
          const trimmed = line.trim();
          // Pass through blank and commented lines.
          if (trimmed.length === 0 || trimmed.startsWith('#')) {
            return line;
          }
          return `# ${line}`;
        })
        .join('\n');

      writeFileSync(ftl, contents.trim() + '\n');
    });
}

/**
 * Returns an array of all *.ftl files in the specified locale directory.
 * @param  {String} locale  [description]
 * @return {Array}          [description]
 */
function getLocaleFiles(locale) {
  return ls(join(LOCALE_ROOT, locale, '*.ftl'));
}
```

Then you can create new locales by doing something like this:

``` sh
$ ./bin/create-locale.js es-ES ru de fr en-US

Locale 'es-ES' doesn't exist, copying.
Locale 'ru' doesn't exist, copying.
Locale 'de' doesn't exist, copying.
Locale 'fr' doesn't exist, copying.
Locale 'en-US' already exists, skipping.
```

And the script will create the locales like ./locales/de/app.ftl which look like:

``` ini
# siteName = Firefox Test Pilot

# pageTitleDefault = Firefox Test Pilot
# pageTitleLandingPage = Firefox Test Pilot
# pageTitleExperimentListPage = Firefox Test Pilot - Experiments
# pageTitleExperiment = Firefox Test Pilot - {$title}
```

Hacky, but worked for me locally. Although I don't know how we'll it'd play w/ Pontoon.

**Comment by lmorchard** [comment]
Thinking we need to close the loop on Pontoon before we know ourselves what it takes to add a new locale to the project. Does Pontoon need stub files in the repo? Or will Pontoon let localizers create new locales themselves and just add them to the repo?

**Comment by lmorchard** [comment]
Looks like Pontoon adds files to the repo for locales: https://github.com/mozilla/testpilot/commit/2d93c4e6a0a7860995c4c4a0d78bac340432c09b

So, then I guess the question is, do we have to file a bug with Pontoon folks to add a locale? Or, is that self-service from Pontoon itself?

**Comment by lmorchard** [comment]
If/when PR #1797 is merged, we'll have two lists of available locales to manage - one for local & dev listing _all_ in-progress locales and one for stage & prod listing just completed locales.

https://github.com/mozilla/testpilot/pull/1797/files#diff-f576cf165b9df501fd5cb5400c3f1761R6

**Comment by meandavejustice** [comment]
I actually do this for min vid, https://github.com/meandavejustice/min-vid/blob/master/bin/locales

here is the url which should be used for fetching the testpilot locales https://l10n.mozilla-community.org/webstatus/api/?product=testpilot&json&type=complete

This isn't quite `good-first-issue` but it's close, maybe a good second or third issue :)

**Comment by chuckharmston** [comment]
@flodolo This is an ancient bug. Do you think there's any value in this in 2018?

**Comment by flodolo** [comment]
I've skimmed through the discussion.

As said, locales are requested via Pontoon's UI, and it will take care of adding the files to the repo. 

I don't think there's anything to keep this discussion open.
