### ISSUE TITLE
Update mobile page copy, promote newsletter more, and add mobile badges

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1721]
Ty (a designer in marketing) made the following observation and suggestion

> The copy caters to desktop users and is accompanied by a download button which then redirects to the download page. I think we should consider changing the copy and content that would prompt a mobile user to first sign up for the Test Pilot newsletter and secondly offer the store specific download badge for Firefox, with the caveat that Test Pilot is only available on desktop. 

Ref

![mobile](https://cloud.githubusercontent.com/assets/8632184/19901605/de7a4dca-a024-11e6-938a-49f1928c2b33.jpg)

@johngruen to think about.

**Comment by johngruen** [comment]
@ckprice this is what #672 is about

**Comment by ghost** [comment]
Suggestion: Replace the [desktop browser] Download button with a newsletter signup button.

**Comment by johngruen** [comment]
We're gonna do a whole mobile "thing". Closing
