### ISSUE TITLE
Remove short_title

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1723]
Does `short_title` need to exist? It doesn't seem like it's currently used [to do anything](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=short_title).

**Comment by johngruen** [comment]
KILL IT WITH FIRE

**Comment by lmorchard** [comment]
> KILL IT WITH FIRE 

I think you asked for it, though, so we could have shorter titles in some UX elements like buttons & such :) But, if it's not handy, into the fire it goes!

**Comment by lmorchard** [comment]
Getting this off my plate since there's a PR already

**Comment by chuckharmston** [comment]
Hah, sorry Les, looks like I tried to assign myself but instead assigned it to you.
