### ISSUE TITLE
Audit experiment YAML files, template, and documentation

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1724]
Now that we're localizing YAML content (#1340), we should audit and reconsider the experiment YAML files, template, and documentation with localization in mind. Some tasks:

- Ensure that all fields are currently being used (e.g. #1723)
- Do a better job delineating optional and required fields in the template and docs.
- Minimize the use of HTML in strings; this makes localization much more challenging.
- Try to standardize the structure of fields that are currently semi-freeform (e.g. [`measurements`](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/tab-center.yaml#L21-L33))
- Remove blank keys and null values where appropriate.
- Make l10n arguments available to strings where appropriate, e.g. [the experiment name in the measurements paragraph](https://github.com/mozilla/testpilot/blob/master/docs/experiments/experiment-content/template.yaml#L24)
- Make sure templates correctly handle missing optional fields.
- Move all the inline comments in [`template.yaml`](https://github.com/mozilla/testpilot/blob/master/docs/experiments/experiment-content/template.yaml) to [`getting_started.md`](https://github.com/mozilla/testpilot/blob/master/docs/experiments/experiment-content/getting_started.md)
- Move the docs in `docs/experiments/experiment-content` (intended to be docs for experiment authors) to `docs/content`

**Comment by ghost** [comment]
Related: https://github.com/mozilla/testpilot/issues/1308

**Comment by chuckharmston** [comment]
I'm moving this from sprint 14 to 15, since it's sort of a meta-bug that I've been addressing with small PRs as I have time.

**Comment by ghost** [comment]
Are enough of these done to turn this into separate bugs?  and/or can we turn this into checkboxes so we can see how much is left?

**Comment by chuckharmston** [comment]
This is good to be closed, actually.
