### ISSUE TITLE
[integration tests] Use get-firefox to fetch Firefox on CI server

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1743]
We currently download an unbranded Firefox build from a [hard-coded path](https://github.com/mozilla/testpilot/blob/5dc4872a/bin/circleci/setup-test-dependencies.sh#L6) as part of integration test setup.

Looks like the npm `get-firefox` package can do this via `get-firefox -p unbranded-beta` or `unbranded-release`, and we won't have to hard-code any paths.

**Comment by lmorchard** [comment]
One caveat I'd toss in here is whether we _do_ actually want to specify the version of the build we use? We've also talked about running the integration tests repeatedly against a range of versions to be sure we're compatible with the latest and maybe 2-3 releases back

**Comment by lmorchard** [comment]
The good-first-bug label is misleading here, since I think we're in the midst of overhauling the integration tests altogether.

**Comment by fzzzy** [comment]
This was fixed by https://github.com/mozilla/testpilot/pull/2380/files
