### ISSUE TITLE
Add Graduation Survey

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1744]
When an experiment ends, we should trigger a graduation survey. 

In the simplest iteration we could simply pop a survey page the add-on detects the experiment has hit graduation time. In addition to any UX, we'll need a new query param for the new survey type.

**Comment by MattGrimes** [comment]
In Shield Studies we pass "study-ended" but you can use whatever you like. @rayborn and I can discuss the question line later today and get something ready for review.

**Comment by johngruen** [comment]
@dannycoates we should discuss this one today...I think some of this is covered in #1303, but let's review the required work together

**Comment by dannycoates** [comment]
This 
<img width="438" alt="screen shot 2016-11-07 at 10 11 55 am" src="https://cloud.githubusercontent.com/assets/87619/20069742/aa9dd3e8-a4d2-11e6-8aed-131c026f13a2.png">
is already implemented. It passes an interval of 'eol' to the survey page. What else do we need to add?

**Comment by johngruen** [comment]
@dannycoates nuthin!
