### ISSUE TITLE
Changes to Add-on UI for near-graduating experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1747]
Current:
- While there's a 1 week EOL notice on the experiment page, this isn't reflected in the add-on.

Proposed
- Elevate the near EOL experiment to the top of the list in the Add-on UI
- Add 'Ending soon' or 'Ending Tomorrow' as a subheader to this experiment. This should supersede and replace the 'Enabled' subheader should the experiment be enabled. 
- The color for this string should be: #ff9300, font size, weight, and position should be the same as the 'Enabled' string

**Comment by dannycoates** [comment]
The only part of this that isn't done (and deployed) is the sort order

**Comment by johngruen** [comment]
cool!

**Comment by johngruen** [comment]
@dannycoates it occured to me that we should probably add 'ends today' as well as 'ends tommorrow.'

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen I think the remaining changes are somehow blocked by #1864. The issue is present in all Test Pilot servers.

**Comment by dannycoates** [comment]
no doorhanger, no problem
