### ISSUE TITLE
[addon] Cleanly switch between dev and prod prefs

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#175]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [6a68](https://github.com/6a68)**
_Wednesday Sep 30, 2015 at 00:20 GMT_
_Originally opened as https://github.com/mozilla/idea-town-addon/issues/29_

---

The `jpm` package seems to assume that prefs live in package.json. What, then, is a clean way to toggle between dev and prod URLs?

Do we want to build package.json from several other files?

Or, maybe we want to have `package.json.dev` and `package.json.prod`, and some build process copies one or the other to `package.json`, so that jpm can see it?

Or maybe we just always build the addon using the prod settings, then go into FF and manually set prefs in about:config?

¯\_(ツ)_/¯

This bug covers figuring out the most add-on idiomatic way of toggling prefs, and then implementing it.

**Comment by meandavejustice** [comment]
<a href="https://github.com/lmorchard"><img src="https://avatars.githubusercontent.com/u/21687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lmorchard](https://github.com/lmorchard)**
_Wednesday Sep 30, 2015 at 00:33 GMT_

---

> Or maybe we just always build the add-on using the prod settings, then go into FF and manually set prefs in about:config?

I think that's it. The prefs in package.json are just initial defaults - and it seems like prod settings would be the best defaults for shipping. Then, you can overlay dev-specific things in local profile via about:config. (Maybe even with a second add-on that configures everything for you. (yo dawg))

**Comment by meandavejustice** [comment]
<a href="https://github.com/lmorchard"><img src="https://avatars.githubusercontent.com/u/21687?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [lmorchard](https://github.com/lmorchard)**
_Monday Oct 19, 2015 at 17:51 GMT_

---

Here's what might be a crazy idea: What if the idea town addon listens for client messages from the known hosts for prod, dev, staging, local dev, etc? One of the messages on login could supply the addon with config details for that server - API endpoint, etc. Then, when you login, the addon can auto-configure itself for that particular server. 

I think the big caveat for this is that devs should really use a different Firefox profile for working on each server environment. Could also have the addon present a quick confirmation dialog on environment change, something like "You just logged into Idea Town {Dev,Staging,Local} - do you want to configure Firefox for this instance? [yes] [no]"

**Comment by pdehaan** [comment]
IIUC, **jpm** allows you to set the prefs location via the `--prefs` flag: https://github.com/mozilla-jetpack/jpm#usage

> `--prefs [path]` Uses a JSON file or common js file which exports a JSON object. The keys of this object will be the pref names, the values will be the pref values.

**Comment by lmorchard** [comment]
Probably related to / can be done at the same time as #174

**Comment by lmorchard** [comment]
For Orlando, let's make sure everything in the repo points at prod (ideatown.firefox.com) and maybe document what needs changing in about:config for devs,

Ideally we should have a smooth way of switching, but not necessary before Orlando

**Comment by lmorchard** [comment]
Going to say #256 handles this well enough for now - [we can use the `jpm run --prefs` option to launch Firefox with canned dev-specific prefs](https://github.com/mozilla/idea-town/commit/4b60baf1f25c9f6e6fb0b462faa977f77248bdaa#diff-18ea69015717516d88dedc84076c033eR16)
