### ISSUE TITLE
Add a graduationReport field to experiment YAML

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1753]
I will add screenshots to show how this should work ASAP

**Comment by johngruen** [comment]
If the user does not have Test Pilot:
<img width="321" alt="screen shot 2016-11-08 at 11 54 59 am" src="https://cloud.githubusercontent.com/assets/3323249/20096633/13216bb8-a5ab-11e6-9f61-82b3c3206598.png">

If the user has Test Pilot:
<img width="301" alt="screen shot 2016-11-08 at 11 55 54 am" src="https://cloud.githubusercontent.com/assets/3323249/20096632/13216708-a5ab-11e6-86fe-a0c54ac28a43.png">

**Comment by ckprice** [comment]
Closed in #1830.
