### ISSUE TITLE
Audit GA events and reporting

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1754]
Few things here

- [x] Audit that all of our features are firing a GA event (e.g. #1711).
- [ ] Implement items from the audit.

John and I will own this.

Ref:
https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md
https://github.com/mozilla/testpilot/blob/master/docs/metrics/new_features.md

**Comment by ckprice** [comment]
@clouserw this issue backfills some missing GA events using our current ping system. I know you and @6a68 are working on changing this, so do you think we should wait? I saw in another doc that  jared was planning on implementing the missing pings into his branch.

**Comment by johngruen** [comment]
Closing this in favor of new metrics bugs
