### ISSUE TITLE
Use NewsletterForm component in EmailDialog

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1758]
In the spirit of easier localization, would it make sense to use the same strings for the two email signup forms?

![window_and_firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/19989237/60c66020-a1e2-11e6-9ba1-443f6a087389.png)

### Popup:

- `email goes here :)`
- `Sign me up`

### Footer:

- `YOUR EMAIL HERE`
- `Sign Up Now`

**Comment by chuckharmston** [comment]
Then plan is actually to move the modal to use the [`<NewsletterForm>` component](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/NewsletterForm.js); just haven't gotten around to it yet. Actually, I'm not sure there's a bug for it yet. I'll hijack this one, thanks.

**Comment by chuckharmston** [comment]
Make sure to delete all the unnecessary strings when doing this; there are quite a few only used by this component.

**Comment by johngruen** [comment]
Not going to get to this today...I'll save it for when i want to hide in a corner for awhile in hawaii.
