### ISSUE TITLE
Add ability to dismiss "Thanks!" section after signing up for newsletter

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1759]
https://testpilot.stage.mozaws.net/__version__ (2ac545add55c628db1c12ea7273dcc0f0ca795dc):

```json
{ "commit": "2ac545add55c628db1c12ea7273dcc0f0ca795dc",
  "version": "2016-11-03-1",
  "source": "https://github.com/mozilla/testpilot" }
```

---

It'd be kind of nice if you could dismiss the Newsletter block after signing up. It takes up like 210px of vertical space.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/19989686/79e33fee-a1e5-11e6-9e2e-a763211de233.png)

I thought that it was persisting across page loads, but that may not be 100% true as at least at one point it reverted back to a signup form so I re-signed up and got an error:

![firefox_test_pilot_-_no_more_404s](https://cloud.githubusercontent.com/assets/557895/19989710/b1a4297a-a1e5-11e6-9a16-fd09555272f3.png)

**Comment by pdehaan** [comment]
OK, so I think if I just browse from page to page, it persists that "Thanks!" newsletter signup UI. As soon as I hit the refresh button, it forgets its previous state and presents me with the form again. So that's why I was seeing it toggle between the two behaviors above.

**Comment by chuckharmston** [comment]
I think the right thing here might be to [persist](https://github.com/rt2zz/redux-persist) a bit of state that indicates that the form has been completed, and never render it in those cases.

Thoughts @lmorchard, @dannycoates?

Edit: we'd actually want two pieces of state: one that indicates that it has been completed this session (unpersisted), and one that indicates if it was ever completed (persisted).

Edit 2: this would also keep us from pestering users with newsletter form modals if they've already signed up.

**Comment by ghost** [comment]
Let's do it, @chuckharmston!

**Comment by johngruen** [comment]
MEH
