### ISSUE TITLE
Activity Stream XPI hash out-of-date.

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1760]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on Activity Stream experiment and choose to "Enable" it.
3. Observe the browser behavior.

[Expected result]:
- The experiment is successfully enabled.

[Actual result]:
- The experiment could not be enabled. "Uh oh. Activity Stream could not be enabled ..." error is displayed.

[Notes]:
- Here are the console errors when trying to enable the experiment:

![as browser console](https://cloud.githubusercontent.com/assets/19226534/20008049/a8f41f8e-a2a7-11e6-9041-78a0c7ce7566.png)

**Comment by chuckharmston** [comment]
@clouserw looks like the hash is out of sync with the XPI

**Comment by ghost** [comment]
fixed, thanks
