### ISSUE TITLE
make a fake experiment on -dev

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1762]
Let's add a fake experiment on -dev which we can graduate early

**Comment by pdehaan** [comment]
Semi-related, but it'd also be nice if we could add some real/dummy translations for testing on dev.
Not sure if we want to use something like [**convict**](http://npm.im/convict) to create special configs for dev/stage/prod so we can sandbox the dev locales to "en-US,de,yi", and only have "en-US" on prod.

**Comment by chuckharmston** [comment]
@pdehaan #1672 covers that.
