### ISSUE TITLE
Document our pull request review process

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1763]
We're changing our pull request process as follows (discussed in 11/4 bug triage):

- if you are going to review a PR, assign yourself to it
- assigned person is responsible for helping get the PR over the finish line
- if a PR doesn't have an assigned person, it's up for grabs

Where should we put this information?

**Comment by ghost** [comment]
https://github.com/mozilla/testpilot/blob/master/docs/process.md or https://github.com/mozilla/testpilot/blob/master/CONTRIBUTING.md ?
