### ISSUE TITLE
make -dev match stage/prod

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1764]
Please turn on website hosting mode and query parameter pass through

**Comment by lmorchard** [comment]
Okay, I think I've got this covered.

On S3 bucket properties:

![screenshot 2016-11-08 14 58 55](https://cloud.githubusercontent.com/assets/21687/20114843/f5ef0c62-a5c3-11e6-88a5-e07e2e9dacb6.png)

And on CloudFront behaviors:

![screenshot 2016-11-08 14 59 54](https://cloud.githubusercontent.com/assets/21687/20114859/07da0418-a5c4-11e6-8f86-aa7c7440eba7.png)

**Comment by lmorchard** [comment]
Not quite done yet - just realized I need to switch the URL for S3 used by the nginx proxy in the middle

**Comment by lmorchard** [comment]
Okay. _Now_ it's done.
