### ISSUE TITLE
Unable to install tab center

### ISSUE THREAD

**Issue by tarunsinghaldotme** [mozilla/testpilot#1765]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by johngruen** [comment]
Hey @iamtarunsinghal were you able to install any other experiments?

**Comment by tarunsinghaldotme** [comment]
Hii @John

Yes I am able to install all other experiments.
and I must tell you they are superb and very helpful.
only  one issue i am getting other than above one that after installing all
the experiments, firefox taking 99% cpu utilization.
but still great efforts guys.

thanks and regards
Tarun Singhal | Linux System Administrator.

**Comment by ghost** [comment]
Generally we find this is a conflict between other installed add-ons (particularly with Tab Center).  If you want to enable it, we suggest disabling all your other add-ons and enabling them one at a time to find the conflict.
