### ISSUE TITLE
Can we remove the TOS agreement checkbox from the new email panel?

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1766]
This just occurred to me, but I think we are covered already once the user has opted into the TOS/PN of Test Pilot itself which covers email-based communication. I'll confirm with legal and either change the title of this bug or close it.

**Comment by johngruen** [comment]
Caveat: we'll have to leave the check box on the landing page itself but IIRC we should be able to remove it if the user has Test Pilot installed (aka opted into the ToS/PN)

**Comment by ghost** [comment]
@eleemoz HELP!

**Comment by johngruen** [comment]
@eleemoz (╯°□°）╯︵ ┻━┻
