### ISSUE TITLE
experiment.complete logic should take UTC offset into account

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1767]
### Currently

the experiment.completed field uses UTC for retiring an experiment, but the logic for displaying/modifying relies on time generated by `Date.now()`. This means that depending on where you are in the world, the retire flow will show up at different times.

### Expected

Experiment completion logic should happen at the same universal time no matter where people are in the world. 

I used the moment.js `utc` method to normalize `experiment.launch_date` across time zones. We should do something similar here. It looks like this is an issue in the add-on reducer as well as in a few of the components.

**Comment by johngruen** [comment]
Some examples of how we're using this now: 
https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=utc&type=Code

**Comment by dannycoates** [comment]
`Date.now()` is always UTC regardless of the local machine's timezone setting, so I don't understand the problem... i.e. this: 

> This means that depending on where you are in the world, the retire flow will show up at different times.

is not true

**Comment by johngruen** [comment]
﻿@dannycoates yeah i think maybe i said that backwards. So I want the experiments to end at the same exact moment everywhere in the world. I don't think this would happen the way the experiment complete check is currently implemented. Here's a video where i change my system timezone and get two different results using the same comparison as in the addons reducer:

https://www.dropbox.com/s/gpeyjse8svtpkwy/Different%20Time%20Results.mov?dl=0

**Comment by dannycoates** [comment]
@johngruen dude, just make sure the completed date in the yaml has a timezone

**Comment by johngruen** [comment]
@dannycoates 
![oh](https://cloud.githubusercontent.com/assets/3323249/20107979/cec89f6a-a5da-11e6-8f9b-28d0f46b8c45.gif)
