### ISSUE TITLE
Implement updates for experiments in main Idea Town addon

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#177]
<a href="https://github.com/6a68"><img src="https://avatars.githubusercontent.com/u/96396?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [6a68](https://github.com/6a68)**
_Thursday Oct 15, 2015 at 18:23 GMT_
_Originally opened as https://github.com/mozilla/idea-town-addon/issues/32_

---

The universal search addon might want to check for updates more frequently than the default "once a day, if online" Addon Manager behavior.

Since Idea Town is already dealing with the Addon Manager, it would be awesome for the Idea Town addon to hide the details behind an API that's exposed to the experiments.

**Comment by lmorchard** [comment]
Or, to flip things, maybe experiment addons shouldn't worry about update checks. Instead, the Idea Town addon should regularly ping the Idea Town site and perform updates as needed. Once an hour? Every 4 hours?

**Comment by meandavejustice** [comment]
I think @lmorchard 's approach sounds much easier for addon devs. Thoughts @6a68 ?

**Comment by jaredhirsch** [comment]
I think universal search is going to be privately published on AMO, so we can ignore this till after Mozlando.

My thought, though, was that a bad update would probably lead to uncaught exceptions being thrown while running the bootstrap.js install() or startup() method, so it would be cool to detect that and check for updates. Definitely makes more sense for Idea Town to handle this, since it's the manager/container for the experiments, and the Idea Town addon already has an AddonListener attached to the AddonManager: I suspect the AddonManager publishes observable events when an upgrade fails.

**Comment by lmorchard** [comment]
Tweaking the title to assert that we're going to control updates via the main Idea Town addon. Probably via pings to a server-side API that will support A/B variants, incremental release, etc based on clientUUID or userID

**Comment by meandavejustice** [comment]
Thinking this issue is going to need a bit more discussion, so I'm pushing this off until:
1. i finish other low hanging fruit
or
2. les is back after the break

**Comment by clouserw** [comment]
We could adjust the default update interval to 4 hours (or whatever) and use the existing infrastructure (ops might have an objection to that if we end up at giant scale)

**Comment by lmorchard** [comment]
> We could adjust the default update interval to 4 hours (or whatever) and use the existing infrastructure (ops might have an objection to that if we end up at giant scale)

Probably a better idea than building up our own custom update process. I've been starting to think that maybe what we want more is user-specific feature flipping (#366) rather than pushing out variant addons to different user segments.

**Comment by lmorchard** [comment]
Meant to actually close this, since I think we made a decision to go with more conventional addon update machinery.
