### ISSUE TITLE
Add flow to entice zero-experiment-users to enable an experiment

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1770]
@sevaan will provide UX here ASAP.

**Comment by sevaan** [comment]
UX: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/203225298_No_Experiments_Enabled_After_N

**Comment by chuckharmston** [comment]
Few questions about the UX:
1. The link in the heartbeat banner appears to be a version of our experiment listing page with slightly different copy. Is that the only way you can see that copy? Or is it what we show all users with no experiments?
2. Minor nit, but there isn't enough contrast in the "Let us know why." link color; it'd fail every accessibility test.
3. Where does that link go? Discourse?
4. How would you like this instrumented @ckprice?

**Comment by sevaan** [comment]
1) Yes, the only way you would see the copy is by going through the heartbeat info bar.

@johngruen What do you think of making this what all users without experiments see when they go to the Test Pilot landing page after, say, a week?

2) Agreed. I’ve updated it.

3) Not sure, I think a SurveyGizmo survey was what @johngruen mentioned. Could you clarify, John?

**Comment by sevaan** [comment]
Orange for link: #FF9D16

**Comment by johngruen** [comment]
@chuckharmston
- I think we should do it for all new users who haven't installed an experiment after one day.
- Obviously, when we ship there will be a sizable cohort who are already in Test  Pilot, but have no experiment installed. We should trigger this for those folks also.
- We should only trigger this thing once to see how it works, so there should be a flag set to ensure that it doesn't happen again until we do something to change that.
- looks like @ckprice filed the metrics issue

**Comment by johngruen** [comment]
@rayborn In this issue we'd like to add a survey to test pilot to ask users not involved in any Test Pilot experiments why they aren't interested. In order to complete this work @chuckharmston will need to point users to a Survey Gizmo URL. Can you provide this?

**Comment by ghost** [comment]
Great idea, sorry for being slow getting you the link.

[Test link](https://qsurvey.mozilla.com/collab/TxP-User) - for full survey click "I didn't like the experiments".  We don't dig into the individual experiments much, but we ask about: 
- Reason for not being in an experiment
- Satisfaction
- If they are interested in future experiments
- What experiments they tried
- What they didn't like in general about experiments
- General feedback
- Tell them how to uninstall if they're in a group highly likely to not want Test Pilot based on not liking it, not being interested, and not being aware of it.

[Prod link](https://qsurvey.mozilla.com/s3/TxP-User)
