### ISSUE TITLE
Graduate Universal Search

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1771]

**Comment by johngruen** [comment]
Here's a timeline: we will graduate Universal Search at 12:00 EST on November 30th, 2016. Working backward from this, we will need the following:
- [x] Nov 30th: @chuckharmston ships a version of Universal Search That's self-uninstalling. Goodnight.
- [x] Nov 23rd: Test Pilot begins to show per-retirement UI.
- [x] Nov 22nd: @clouserw pushes Test Pilot to Prod with all Universal Search graduation data in place. 
- [x] Nov 19th-22nd: @SoftVision-PaulOiegas leads QA on the graduation UI + Universal Search Add-on.
- [x] Nov 18th: Final copy for the Test Pilot graduation summary due, all final graduation assets in YAML for Sprint-14 tag @javaun
- [x] Nov 18th @chuckharmston and @6a68 provide @SoftVision-PaulOiegas with the final version of the Universal Search add-on
- [x] Nov 14th: @javaun's draft of Test Pilot graduation summary due, YAML updated with draft and completion date ahead of Sprint-14 tag. @jgruen and @chuckharmston will review and our copywriter will give it a few passes.

How does this sound to people, specifically, @javaun, @chuckharmston, @clouserw

**Comment by javaun** [comment]
SGTM. I better start writing.

**Comment by clouserw** [comment]
The current version of https://addons.mozilla.org/en-US/firefox/addon/test-pilot/?src=ss opens a tab and uninstalls itself.  Should just be a matter of replacing the URL and add-on ID.

**Comment by chuckharmston** [comment]
We also need to ensure that prefs we changed are reverted to defaults, including one-off searches. We should probably also make sure the separate search box is restored.

**Comment by ghost** [comment]
Good point.  That add-on also deletes its old prefs so that should be straight-forward too.

**Comment by jaredhirsch** [comment]
> We also need to ensure that prefs we changed are reverted to defaults, including one-off searches. We should probably also make sure the separate search box is restored.

We unset prefs on uninstall already, see [here](https://github.com/mozilla/universal-search/blob/master/bootstrap.js#L28) and [here](https://github.com/mozilla/universal-search/blob/master/lib/universal-search.js#L67). We also restore the search bar [here](https://github.com/mozilla/universal-search/blob/fb3ae049d290f56ea7f3ab7a857273376d9232d8/lib/universal-search.js#L122), if it was originally visible; while some other addons seem to break the API we use, I don't know of a more reliable way to restore that bit of UI.

**Comment by chuckharmston** [comment]
> We unset prefs on uninstall already, see here and here. We also restore the search bar here

Yes we do; my note was to make sure that those bits were carried over to the self-uninstalling update.

**Comment by jaredhirsch** [comment]
> Yes we do; my note was to make sure that those bits were carried over to the self-uninstalling update.

Cool. Just for reference, I think the only thing we'll need to do to make it self-uninstalling is
- get the universal search Addon object from [AddonManager.getAddonById()](https://developer.mozilla.org/en-US/Add-ons/Add-on_Manager/AddonManager#getAddonByID%28%29)
- call [Addon.uninstall()](https://developer.mozilla.org/en-US/Add-ons/Add-on_Manager/Addon#uninstall%28%29)

Edited to add: calling Addon.uninstall will run all the usual bootstrap.js uninstall code, which will clear out prefs and reset the UI.

If we want to show something to the user, we can also open a tab or dialog, but that'd require approved copy and some UX input, which I'm not sure we'll get.

**Comment by jaredhirsch** [comment]
I'm going to write and land the self-uninstalling patch, since I'll be out of office the next two days.

**Comment by jaredhirsch** [comment]
OK, landed the final patch, verified it self-uninstalls cleanly on unbranded release and dev edition.

I've uploaded an unsigned build for QA. It's the top link on [this page](https://people-mozilla.org/~jhirsch/universal-search/). It can also be downloaded directly [here](https://people-mozilla.org/~jhirsch/universal-search/universal-search-1.0.13.xpi).

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be working well. Just checked this using Fx 50 latest unbranded release where I installed production version of Test Pilot and Universal Search. Installing after the provided add-on version from the link, correctly removes Universal Search add-on.

![us auto uninstall](https://cloud.githubusercontent.com/assets/17258026/20384454/952676ae-acbc-11e6-9ffc-b7074c1f3449.gif)

**Comment by chuckharmston** [comment]
@SoftVision-PaulOiegas would you mind additionally verifying a few things?
1. That the separate search box removed by Universal Search on uninstall is restored.
2. That the `browser.urlbar.suggest.searches` pref is cleared on uninstall.
3. That the `browser.urlbar.oneOffSearches` pref is cleared on uninstall.

Thanks!

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston sure thing. When it comes to this, we have some problems. 
1. The separate search bar **is not restored** upon uninstall.
2. The browser.urlbar.suggest.searches **is returned to default** "false" value as expected.
3. There is **no pref with that name** even if you install US from dev/prod/or custom build from the repo. I've added it myself as Boolean and "true" (same as the one from 2), but it **wasn't cleared** with the uninstall.

The pref from 3 should be installed with the build ?

**Comment by ghost** [comment]
@6a68 (and co.) we're scheduled to push the self-uninstaller at 10am on Nov 30

**Comment by jaredhirsch** [comment]
Just following up on the last comment from Paul:

> 1. The separate search bar is not restored upon uninstall.

Unfortunately, I don't think this can be fixed before we end the experiment.

The search bar not getting restored on uninstall has been an open bug for [a while](https://github.com/mozilla/universal-search/issues/311), meaning: we've lost track of whether the user originally had the search bar. The only thing we could do would be to restore the search bar for all users, but I don't know the `CustomizableUI` API very well, and there may be gotchas lurking.

I think it seems too risky to change the addon code now, the night before the (externally imposed) Nov 30 uninstall deadline. Talked this over with @johngruen and @clouserw (Javaun is out), seems ok all around.

> 2. The browser.urlbar.suggest.searches is returned to default "false" value as expected.

\o/

> 3. There is no pref with that name...The pref from 3 should be installed with the build ?

The `oneOffSearch` pref is [only set in Nightly](https://dxr.mozilla.org/mozilla-central/source/browser/app/profile/firefox.js#306). I'm not too worried about this one.

**Comment by johngruen** [comment]
@clouserw think we can close this?

**Comment by chuckharmston** [comment]
Goodnight.
