### ISSUE TITLE
Measurements for "Add flow to entice zero-experiment-users to enable an experiment (TXP-36)"

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1773]
Ref: #1770

I'll take this. #1237 is an example of a past measurement issue, based on [the new features documentation](https://github.com/mozilla/testpilot/blob/master/docs/metrics/new_features.md).

**Comment by chuckharmston** [comment]
@ckprice low-key heads-up: #1800 is blocked on this. Happy to take a stab if you're swamped.

**Comment by ckprice** [comment]
**Formulate the question**
- give us a number of users who installed an experiment that were referred from this notification.
- give us a success rate on displaying this message. users who installed an experiment referred 
  from this notification/users who saw the notification

# Display no experiments notification bar (#1800)

### Capture the event of the notification bar being displayed

This will require an event sent through the add-on GA ([ref](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L353)).

```
ec: 'add-on Interactions',
ea: 'display notification',
el: 'no experiments installed'
```

Documents for tracking add-on events are pending in #1754.

### Capture the event of the notification bar being clicked

This will require an event sent through the add-on GA ([ref](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L353)).

```
ec: 'add-on Interactions',
ea: 'click notification',
el: 'no experiments installed'
```

Documents for tracking add-on events are pending in #1754.

Note: not sure how the measurement protocol compares to ga.js on the website (that requires [an async callback for link clicks](https://github.com/mozilla/testpilot/blob/e173da0883e602e35ebb822b8cc001201c3222fb/frontend/src/app/containers/App.js#L98)).

If this is too big of a pain, we can use the tagged link below to roughly compare displays/clicks.

### Tag links from the notification

Referencing our [ga.md Table of tags documentation](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#table-of-tags):

| Description | utm_source | utm_medium | utm_campaign | utm_content |
| --- | --- | --- | --- | --- |
| Clicks on the no experiments installed notification | testpilot-addon | firefox-browser | testpilot-notification | no-experiments-installed |

This will also tag the session so any experiment installs on the website will be attributed to this referrer. 

Please also update documentation.

### Capture not interested event

Referencing our [ga.md Table of events](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#table-of-events).

| Description | eventCategory | eventAction | eventLabel |
| --- | --- | --- | --- |
| Click on the no thank you survey after coming from no experiments notification | HomePage Interactions | button click | no experiments no thank you |

Please update documentation.

@chuckharmston I _think_ that's everything. Let me know if you have any questions.

**Comment by chuckharmston** [comment]
Thanks Cory! This looks great.
