### ISSUE TITLE
Cannot install Test Pilot extension

### ISSUE THREAD

**Issue by cvan** [mozilla/testpilot#1775]
It just hangs on `Installing…`. No errors in the Console, only logs.

<img width="1155" alt="screen shot 2016-11-07 at 5 01 05 pm" src="https://cloud.githubusercontent.com/assets/203725/20082599/f8af1770-a50b-11e6-8c0f-b8db8c20861e.png">

* Firefox 49.0.2
* Mac OS X 10.11.2

**Comment by chuckharmston** [comment]
@cvan What about the browser console (`cmd+shift+J`)? Any chance you have tracking protection on, are in private browsing mode, or have any security software installed?

**Comment by cvan** [comment]
![](https://cloud.githubusercontent.com/assets/203725/20085114/7732c93e-a51b-11e6-9c39-6d07312c5cec.png)

After I discovered this in `about:addons` and enabled the extension, things seemed to work at https://testpilot.firefox.com/.

My observations and questions:
1. Somehow, during install, the extension got into the disabled state. Ideas on what could have cause this?
2. Is there some way to detect that the extension is installed but disabled on the Test Pilot site (so it's not just saying `Installing…`)?

Thanks, @chuckharmston!

**Comment by mmcclimon** [comment]
I just had the same issue. I might have had an earlier version of Test Pilot installed (I don't remember), but after clicking "Install," it just hung forever. Looking in the add-ons, it was installed but disabled.

**Comment by ckprice** [comment]
> Somehow, during install, the extension got into the disabled state. Ideas on what could have cause this?

This...would be something new. @cvan maybe the add-on was previously disabled?

Better monitoring/messaging is covered in #1335.

**Comment by SoftVision-CosminMuntean** [comment]
Hi @cvan, @mmcclimon

I would like to try to reproduce this issue but I need some more details. Can you guys please go to "about:addons", "Extensions" section and perform a screenshot with your installed add-ons? Maybe you have an add-on which is not compatible with Test Pilot and disabled it. 

There are some add-ons in the wild that are incompatible with some of our experiments. We are currently notify the users about the ones we know, but it would be impossible to know all of them. Maybe the issue you guys had is related in some way.

**Comment by ghost** [comment]
We should be able to detect what add-ons are installed (I forget the API, but we're on the allowlist for it, right?).  If so, we can prompt the user with something useful when we hit this state.

**Comment by mmcclimon** [comment]
In my case at least, I had previously had Test Pilot installed and disabled it myself manually. Having forgotten about this, I tried to install it again by clicking the button on the site, which simply spun forever. Only when I happened on this thread did I think to check if it was already installed and disabled.

**Comment by ghost** [comment]
This looks like it is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1313298 so I'll close this.
