### ISSUE TITLE
Same-origin policy blocking use of pushState in Pontoon

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1777]
`react-router` uses [`history`'s `browserHistory` object](https://github.com/mjackson/history/blob/master/modules/createBrowserHistory.js) for managing history. This uses [`popstate`](https://developer.mozilla.org/en-US/docs/Web/Events/popstate), which is governed by the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) and is causing navigation events to be blocked within Pontoon:

```
error DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: https://testpilot.dev.mozaws.net/static/app/app.14102a7c.js:3]
```

@mathjazz Do you know how existing projects are handling this?

**Comment by mathjazz** [comment]
I'm unable to reproduce this - what navigation events do you have in mind?

If there are multiple localizable pages available on dedicated URLs, we can add them to the Resources menu (the one currently containing only "ftl.app" or "All Resources"), to make it easier for localizers to discover and navigate.

**Comment by chuckharmston** [comment]
You can reproduce this by clicking the "Get Started" button on any of the experiments in the list; it should attempt to navigate, then fail, showing the loading spinner forever. I can screencast it if you can't reproduce.

The navigation events in particular are the ones emitted by the [action creators from `react-router-redux`](https://github.com/reactjs/react-router-redux#pushlocation-replacelocation-gonumber-goback-goforward).

Adding pages to the Resources menu would be great! We do have multiple localizable pages (current list below), but it's unfortunately a slightly dynamic list; we'll launch and retire experiments between 10-20 times per year, and I'd hate to loop you in as a dependency for that.

### Current list of localizable pages
- https://testpilot.dev.mozaws.net/experiments/page-shot
- https://testpilot.dev.mozaws.net/experiments/min-vid
- https://testpilot.dev.mozaws.net/experiments/tracking-protection
- https://testpilot.dev.mozaws.net/experiments/activity-stream
- https://testpilot.dev.mozaws.net/experiments/tab-center
- https://testpilot.dev.mozaws.net/experiments/no-more-404s
- https://testpilot.dev.mozaws.net/experiments/universal-search
- https://testpilot.dev.mozaws.net/legacy
- https://testpilot.dev.mozaws.net/share
- https://testpilot.dev.mozaws.net/error
- https://testpilot.dev.mozaws.net/onboarding
- https://testpilot.dev.mozaws.net/retire

**Comment by mathjazz** [comment]
We just got the same report from @goofy-bz:
https://bugzilla.mozilla.org/show_bug.cgi?id=1316409

But I still can't reproduce it. :/

I'm not exactly sure what's the problem here. Why is the same-origin policy a problem here if we're always on the same domain? But apparenlty it is, given the CSP error @goofy-bz is getting:
https://bug1316409.bmoattachments.org/attachment.cgi?id=8809134

**Comment by ghost** [comment]
> You can reproduce this by clicking the "Get Started" button on any of the experiments in the list; it should attempt to navigate, then fail, showing the loading spinner forever.

I can but confirm I have had same experience as chuckharmston above

**Comment by mathjazz** [comment]
Ah, finally I can reproduce this (see #1999).

**Comment by ghost** [comment]
@mathjazz is this still happening?  What can we do to fix it?

**Comment by mathjazz** [comment]
It is still happenning.

I can't reproduce it with default browser settings, though. Only if I disable 3rd party cookies.

**Comment by ghost** [comment]
We're planning on removing react router which will fix this so closing.  #2260
