### ISSUE TITLE
Experiment content not being picked up by Pontoon

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1778]
We [generate](https://github.com/mozilla/testpilot/blob/master/frontend/tasks/content.js#L58-L63) the en-US [`experiments.ftl`](https://testpilot.dev.mozaws.net/static/locales/en-US/experiments.ftl) from our [content files](https://github.com/mozilla/testpilot/tree/master/content-src/experiments) in our build process, and then appropriate [include it](https://github.com/mozilla/testpilot/blob/master/frontend/src/templates/index.mustache#L13) on the page. Unfortunately, it appears like it's not being picked up by Pontoon.

@mathjazz any chance you know why this is happening? Would the default one need to be included in source control?

**Comment by mathjazz** [comment]
Yup, the file needs to be available here:
https://github.com/mozilla/testpilot/tree/master/locales/en-US

**Comment by chuckharmston** [comment]
#1779 moved a copy of the experiment localization file into the repository as a short-term fix, and it's now being picked up by Pontoon:

https://pontoon.mozilla.org/de/test-pilot-website/experiments.ftl/

Closing this, and I'll follow up with #1781. Thanks for the assist @mathjazz!

**Comment by mathjazz** [comment]
As pointed out by @flodolo, there's a lot of HTML tags in those strings. Can we get rid of them?

**Comment by chuckharmston** [comment]
Yeah, it's not awesome. Normalizing those to remove as much HTML as possible is one of the tasks a task in https://github.com/mozilla/testpilot/issues/1724, which we've slated to do this sprint (ends 11/18). I'll prioritize it.

**Comment by flodolo** [comment]
The problem is that we have already exposed those strings to localization, and people are already working on them. If we clean up en-US string, we should have something to do the same safely in l10n files.
