### ISSUE TITLE
Integration test timing out

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1780]
A few recent integration test builds have timed out.

https://circleci.com/gh/mozilla/testpilot/1507
https://circleci.com/gh/mozilla/testpilot/1508

Possibly related: https://github.com/mozilla/testpilot/pull/1437

cc @6a68

**Comment by jaredhirsch** [comment]
I was just going to file this bug! Pontoon commits should never go red, looks like this one failed, too:

https://circleci.com/gh/mozilla/testpilot/1517

**Comment by chuckharmston** [comment]
Reopening; this seems to still be happening intermittently: https://circleci.com/gh/mozilla/testpilot/1654

**Comment by jaredhirsch** [comment]
It looks like PopupNotifications.jsm or the `addon-install-blocked` nsIObserver events (which trigger the blocked notification being displayed) might be more reliable alternatives to the current approach of sleeping for 5 seconds, then hoping Puppeteer can find the elements.

I think we can use marionette's `execute_async_script` method to call JS code inside the python integration test, but I'm not yet sure if we can return elements from JS to python. If we can pass elements around, then `window.PopupNotifications.panel` gives us the notification panel pointer, assuming it exists, and we can dig into its anonymous elements (like the various buttons) too.

**Comment by jaredhirsch** [comment]
For right now, I'm going to just try making the sleeps longer. It actually might help.

If that doesn't work, I'll look into fancier things, like listening for specific events.
