### ISSUE TITLE
Make German show up on testpilot.dev.mozaws.net

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1784]
I said German, but I really mean all the languages who have committed translations.  Chuck says we need to update the availableLanguages meta tag.

Let's do that part right away and land it, but bonus points for thinking about how to notify us of new languages so we can enable them.

**Comment by chuckharmston** [comment]
> bonus points for thinking about how to notify us of new languages so we can enable them

We should be able to write a mustache helper to trawl the `/locales` directory and return a string to stick here: https://github.com/mozilla/testpilot/blob/master/frontend/src/templates/index.mustache#L10

**Comment by lmorchard** [comment]
Do we want to auto-enable languages before they're initially 100% translated, though? I guess as long as Pontoon tosses the un-translated English in, we won't get l10n IDs displayed

**Comment by pdehaan** [comment]
Yeah, from my vague recollection of FxA days, we'd only enable translations once they hit a certain quality threshold (90%?). Nothing worse than trying to view a page where only 30% of the strings are translated into your language.

It sounds like FxA now uses Pontoon (https://pontoon.mozilla.org/projects/firefox-accounts/) for determining what %% of a locale is translated so they know when they can add/remove supported locales.

**Comment by lmorchard** [comment]
Another idea: We can tweak the build for local & dev vs stage & prod. Maybe we have separate enabled locale lists for dev-like & prod-like - that is, turn on all the things for dev so we can see where they're incomplete and only manually turn on complete locales for prod?
