### ISSUE TITLE
Generate UUID on install and send events

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#179]
<a href="https://github.com/meandavejustice"><img src="https://avatars.githubusercontent.com/u/1844554?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [meandavejustice](https://github.com/meandavejustice)**
_Monday Oct 19, 2015 at 18:46 GMT_
_Originally opened as https://github.com/mozilla/idea-town-addon/issues/34_

---

Need to generate UUID on install and send to server.
This will help us managing conflicts when users have the addon installed in two or more separate browsers.
(should also send an event with the UUID on uninstall)

**Comment by lmorchard** [comment]
https://github.com/mozilla/idea-town/commit/b3b671a0b974c57a60cf5fcc30f9a9ab7838ea0d
