### ISSUE TITLE
Form validation strings aren't localized?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1799]
I noticed that if you don't fill out an email address in the newsletter signup and then try submitting, you get non-localized error messages. (testing on **1784-enable-locales** PR)

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/20199944/f94ec406-a762-11e6-95bb-e7e577775b8c.png)

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/20200054/aa8ef696-a763-11e6-8cd2-0ba189aa9ef2.png)

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/20200076/c11269de-a763-11e6-87ac-d138fae2e46e.png)

**Comment by chuckharmston** [comment]
Those are part of the browser chrome. They _can_ be customized with some work (has to be done through JavaScript, not just an HTML attr), but if they aren't localizing, it's likely either a bug or feature of the browser itself. Can you repro this behavior with a German build?

**Comment by flodolo** [comment]
They're localized in Italian as expected for me (as part of the browser). Given that the target of this website if Firefox users, I wouldn't bother with moving this to JS (as far as I know, it would be necessary for browsers like Safari, that ignore these checks).

**Comment by SoftVision-PaulOiegas** [comment]
Observed this too but only happens if you have en-US browser installed and choose to see the page content in German (DE) from Options>Content. If you have the localized DE browser installed this does not reproduces.

**Comment by chuckharmston** [comment]
Closing per mine and Paul's comments.
