### ISSUE TITLE
Firefox freezes and overflows memory with tab center.

### ISSUE THREAD

**Issue by CableErector** [mozilla/testpilot#1801]
If the key combination: Ctrl+Q is held for a period of time the tabs close and then a lot of new tabs spawn and freeze Firefox, while Firefox is frozen it gradually eats memory out resulting in the need of terminating Firefox. 

Specs:
Target: i686-pc-mingw32
Build: https://hg.mozilla.org/releases/mozilla-release/rev/dc617d65c9f0cdbbe4351cc1e5c288b05f25f8f7

**Comment by johngruen** [comment]
Oh, that's no good...I'm going to move this over to the tab center repo and close it here.

**Comment by johngruen** [comment]
https://github.com/bwinton/TabCenter/issues/793
