### ISSUE TITLE
Error in Universal Search privacy note

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#1802]
https://github.com/mozilla/testpilot/blob/master/locales/en-US/experiments.ftl#L90

> <p>In addition to the <a href="/privacy">data</a> collected by all Test Pilot experiments, here are the key things you should know about what is happening when you use Universal Search:</p><ul> <li>We collect basic usage data regarding how you interact with the Awesome Bar (address bar), such as the number of characters typed, the types of results that you click, and their position in the results list.</li> <li>If you previously configured Firefox to display search suggestions in the Search Bar, installing Universal Search will enable <a href="https://www.mozilla.org/privacy/firefox/#searchsuggestions" target="_blank">search suggestions</a> in the Awesome Bar.</li> <li>When you use the Awesome Bar, we send the terms you type to our recommendation engine. We keep anonymous logs of popular searches to improve the quality of our recommendations.</li> <li>To provide Universal Search, we use a few third-party services. We use <a href="http://www.bing.com/developers/s/APIBasics.html" target="_blank">Bing</a> and <a href="https://developer.yahoo.com/boss/search/" target="_blank">Yahoo</a> to provide recommendations, and <a href="http://docs.embed.ly/docs/" target="_blank">Embedly</a> and <a href="https://clearbit.com/logo" target="_blank">Clearbit</a> to provide additional data (such as images or icons) about those recommendations. To display the recommendations in the Awesome Bar, Universal Search may download those images directly from Embedly and Clearbit, which may allow those services to see your IP address and the image requested.</li></ul>

I'm pretty sure the second list item is wrong: `If you previously configured Firefox to display search suggestions in the Search Bar, installing Universal Search will enable search suggestions in the Awesome Bar.`

previously configured Firefox to *not* display… ? Also kind of poor consistency (Search Bar, Awesome Bar).

**Comment by ghost** [comment]
I think the Search Bar and Awesome Bar are different things here.  /cc @chuckharmston to confirm

**Comment by chuckharmston** [comment]
They are. Traditionally, the bar where you enters URLs is called the Awesome Bar, and the separate search box alongside it is called the Search Bar.

**Comment by flodolo** [comment]
Thanks, I completely forgot that we had two separate checkboxes in preferences. It makes a lot more sense now.
