### ISSUE TITLE
Test Pilot "Legacy" page message is not localized in German

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1806]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- On a new clean Firefox profile, German [de] language was added from Options>Content>Languages section.
- Assure that German language is in the top of the list.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net/legacy" page.
2. Observe all the page strings.

[Expected result]:
- All the page strings are displayed in German.

[Actual result]:
- Only the footer links are displayed in German, the rest of the strings are still displayed in English.

[Notes]:
- Here is a screenshot with the issue:

![legacy no translate](https://cloud.githubusercontent.com/assets/17258026/20269848/8e171a5c-aa8d-11e6-8976-e174d4290e3d.png)

**Comment by ghost** [comment]
This was on purpose because we didn't have L10n at the time, the former project was English-only (I think), and it was a temporary measure.  It's fine to leave this page unlocalized forever.
