### ISSUE TITLE
The redirect to experiments page is not performed after Test Pilot add-on is installed (dev server)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1807]
[Affected versions]:
- Firefox 49.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click the "Install the Test Pilot Add-on" green button and install the add-on.
3. Observe the browser behavior.

[Expected result]:
- Test Pilot add-on is successfully installed and you are redirected to the experiments page.

[Actual result]:
1. On latest Firefox release:
- After the browser is restarted, Test Pilot add-on is successfully installed, but the installation page is still available. 
2. On latest Nightly build:
- Test Pilot add-on is successfully installed, but the button remain in the "Installing" state.

[Notes]:
- The continuous "Installing..." state issue also occurs on experiment details page where you are not redirected to the page from which you can enable the experiment.
- If the page is refreshed, you are correctly redirected to the experiments page. 
- Here are the browser console errors:
1. On the latest Firefox release: https://goo.gl/Ui1JkU.
2. On the latest Nightly build: https://goo.gl/31CVuI
- Here is a screen recording with the issue: https://goo.gl/AQ3Lmz.

**Comment by chuckharmston** [comment]
@SoftVision-CosminMuntean Can you verify that this is still reproducible if `extensions.webapi.testing` is set to `true`?

Any time you're testing the add-on installation in dev or stage, that needs to be set.

**Comment by chuckharmston** [comment]
Now that we're in Firefox 50, any time you see the doorhanger on install (as you would if `extensions.webapi.testing` is either unset of `false`), that's probably the issue.

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston Cosmin is out of office today but I can help here. I've added manually the pref since it's not by default or installed with Test Pilot but this doesn't change the behavior. 
However I can give you some extra bits of information on this. Since after you refresh the page you are correctly redirected after all, uninstalling and reinstalling the add-on after, doesn't display this behavior again.

**Comment by ckprice** [comment]
Cosmin to check the pref and confirm repro still.

**Comment by SoftVision-PaulOiegas** [comment]
Cosmin tested this today also, and confirmed he can still reproduce it too. And the strange part is that the installation doorhanger is displayed even with the set pref, which shouldn't happen. However, this is not reproducing on stage. only on dev server at the moment.

One more thing that we observed, as I've said above, the installation works well the second time you install it, but the doorhanger request to allow installation is not displayed second time.

Here are the browser console logs, maybe you'll find something useful.
[Broken install redirect logs.txt](https://github.com/mozilla/testpilot/files/603268/Broken.install.redirect.logs.txt)

**Comment by ghost** [comment]
Since this only happens on dev and we are moving to using only the new install APIs I don't think this is something we want to dig into.
