### ISSUE TITLE
CSP Sentry report

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1808]
In my ongoing Optimizely saga, I'm encountering the following CSP report on dev

`{"csp-report":{"blocked-uri":"https://sentry.prod.mozaws.net","document-uri":"https://testpilot.dev.mozaws.net/?optimizely_disable=true&optimizely_editor=true&optimizely_log=false&optimizely_include_innie=true&optimizely_cache_buster=1479142480745&optimizely_proxy_rewriter=true","original-policy":"default-src https://testpilot.dev.mozaws.net; connect-src https://testpilot.dev.mozaws.net https://www.google-analytics.com https://ssl.google-analytics.com https://basket.mozilla.org https://analysis-output.telemetry.mozilla.org https://cdn.optimizely.com; font-src https://testpilot.dev.mozaws.net https://code.cdn.mozilla.net; form-action 'none'; frame-ancestors https://testpilot.dev.mozaws.net https://pontoon.mozilla.org https://app.optimizely.com; img-src https://testpilot.dev.mozaws.net https://pontoon.mozilla.org https://ssl.google-analytics.com https://www.google-analytics.com; object-src 'none'; script-src https://testpilot.dev.mozaws.net https://pontoon.mozilla.org https://ssl.google-analytics.com https://cdn.optimizely.com https://app.optimizely.com; style-src https://testpilot.dev.mozaws.net 'unsafe-inline' https://pontoon.mozilla.org https://code.cdn.mozilla.net; report-uri https://testpilot.dev.mozaws.net/__cspreport__","referrer":"https://app.optimizely.com/edit?experiment_id=7822570084","violated-directive":"connect-src https://testpilot.dev.mozaws.net https://www.google-analytics.com https://ssl.google-analytics.com https://basket.mozilla.org https://analysis-output.telemetry.mozilla.org https://cdn.optimizely.com"}}`

Interesting parts
```
"blocked-uri":"https://sentry.prod.mozaws.net"
"violated-directive":"connect-src https://testpilot.dev.mozaws.net https://www.google-analytics.com https://ssl.google-analytics.com https://basket.mozilla.org https://analysis-output.telemetry.mozilla.org https://cdn.optimizely.com"
```

Not sure if this is more Optimizely weirdness (I'm only seeing this on their dashboard), or if we needed to add Sentry to our policy and just never did. /cc @clouserw

**Comment by fzzzy** [comment]
I think we need to add it to our policy. It's odd though, because there are definitely exceptions that are making it into sentry...

**Comment by ghost** [comment]
Could be from browsers that don't support CSP?

Edit: well, I guess if they didn't support it they wouldn't be pinging at all.  Maybe they are buggy?

**Comment by ghost** [comment]
PR @ https://github.com/mozilla/testpilot/pull/1813

**Comment by fzzzy** [comment]
I think you are right that exceptions have only been reported by browsers that don't support csp. Raven still works on those older browsers.

Recent exception browser versions: IE 11, Firefox 17 (!), Firefox 14 (!!). I see no exceptions from reasonable looking browser versions.
