### ISSUE TITLE
Script to convert existing strings to new split up strings

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1811]
The changes in https://github.com/mozilla/testpilot/pull/1786 and https://github.com/mozilla/testpilot/pull/1782 are helpful and appreciated (thanks, Chuck!).  Paragraphs are not a deal breaker for L10n, but multiple paragraphs should be broken up (as in the PRs -- the bulleted lists are a great example).  Any time we can keep HTML out of the localized strings, we should.

So, I'd like to land those PRs, but I don't want to ask the localizers who just spent all that time localizing to essentially do it all again in smaller chunks.  This bug is to look into converting at least the main parts of the .ftl files to use the new strings.  

/cc @mathjazz for any ideas since he already parses these files
/cc @flodolo for L10n interest

**Comment by mathjazz** [comment]
Looking at the `.ftl` files, #1786 only _adds_ one string. If that's correct, there's nothing we need to change in locale files.

#1782 removes `<p>` tags from most of the strings containing them, so those strings need to be modified in locale files, too.

Perhaps @chuckharmston already has something in place, given he already created a zh-CN `.ftl` file. If not, one possible approach is to identify keys with stripped `<p>` tags and then [parse](https://github.com/l20n/python-l20n/blob/master/l20n/format/parser.py), strip and [serialize](https://github.com/l20n/python-l20n/blob/master/l20n/format/serializer.py) locale `.ftl` files.

**Comment by ghost** [comment]
HTML was removed from tour steps in https://github.com/mozilla/testpilot/commit/1c97ab06d4b0fb2496ead7a50d50818d159cee3f
