### ISSUE TITLE
Use l20n sections in FTL files

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1814]
Learned about this neat bit of FTL syntax: http://l20n.org/learn/sections

This is a pretty natural fit for the way we've been namespacing related entities, e.g.

```
restartIntroLead = Preflight checklist
restartIntroOne = Restart your browser
restartIntroTwo = Locate the Test Pilot add-on
restartIntroThree = Select your experiments
```

Especially when pairing with section comments: http://l20n.org/learn/comments

@flodolo Would organizing our entities this way affect existing localizations?

**Comment by flodolo** [comment]
Can you explain the namespacing? Strings in a section are not namespaced, i.e. you couldn't have a IntroLead in different sections.

@mathjazz Can you confirm that we're not breaking anything with the current l20n parser in Pontoon by adding sections, and comment sections?

**Comment by chuckharmston** [comment]
> Can you explain the namespacing? Strings in a section are not namespaced, i.e. you couldn't have a IntroLead in different sections.

Right; we've been namespacing strings (i.e. `restartIntro`) as a practice of grouping related sections. We'd continue to do that with sections, just provide more helpful context to localizers for some of the more esoteric stuff (like `experimentsListNoneInstalled`, which I'm adding the same comment to three times in #1770).

**Comment by mathjazz** [comment]
Sections are supported in Pontoon. Meaning strings are imported properly and section comments are assigned to all strings within the section.

**Comment by chuckharmston** [comment]
@mathjazz Would you mind confirming that adding an entity to a section wouldn't invalidate existing localizations? That's not totally clear from the documentation.

**Comment by mathjazz** [comment]
Yup, I can confirm this!
