### ISSUE TITLE
"This experiment is ending" message lacks padding

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1816]
http://testpilot.dev.mozaws.net/experiments/__version__  (4836bf7947f8d0012d8b00b0ece017abcc64d3a2):

```json
{ "commit": "4836bf7947f8d0012d8b00b0ece017abcc64d3a2",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/1771" }
```

---

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/20330024/b70effba-ab50-11e6-9e03-d934b478fdd9.png)

**Comment by chuckharmston** [comment]
#1741 was the plan for this; CC @johngruen to make sure he sees the issue.
