### ISSUE TITLE
My history disappeared and I now have 9 hi-lite boxes...I want my history stream back...PLEASE!!!!!!

### ISSUE THREAD

**Issue by SherylBratcher** [mozilla/testpilot#1821]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by pdehaan** [comment]
Closing in favor of the https://github.com/mozilla/activity-stream/issues/1802 report since this is related to the Activity Stream add-on.

**Comment by SherylBratcher** [comment]
I didn't open you're email because I didn't know who you were...
I use to have less focus boxes and a recent history link list below them
and I want it back!!!!!
It was very useful to me!
Please do your Tech Magic and tell me how to change it back. If you can
also make it easy for a non-technical website/SEO Sales Person.  :)
Thank you!
Sheryl Bratcher
