### ISSUE TITLE
Create a mechanism to expose pages on dev to localizers, but hide on stage/prod

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1822]
We haven't launched one before, so this bug is to detail what a perfect world looks like, and note any engineering we may need.

- We receive final copy & assets from marketing/product.
- Open an issue to create `new-localized-thing.yaml` and check into dev.
- `new-localized-thing.yaml` is available for localization on Pontoon.
- http://testpilot.dev.mozaws.net/experiments/new-localized-thing can be accessed.
- Before the launch date
  - `/new-localized-thing` can _not_ be accessed on stage and production after deployments.
- On the launch date
  - `/new-localized-thing` is live on stage and production after we do a thing.

In our checkin today it sounded like the `dev:true` could do that for us, but @lmorchard [said this may not be the case in chat](http://logs.glob.uno/?c=testpilot#c31946).

Let's start with @johngruen confirming that the above is actually what should happen.

**Comment by ckprice** [comment]
After speaking with marketing, they would optimally like to keep the product page unpublished on stage/prod until the launch date. 

I'm going to unassign John, and open this up for someone to take. The chat log in the first comment mentions an additional flag we could potentially add.

**Comment by flodolo** [comment]
> After speaking with marketing, they would optimally like to keep the product page unpublished on stage/prod until the launch date.

That's far from ideal for l10n testing, we need to be able to test a page properly and in advance, especially if we lose almost 5 days in a 2 weeks cycle like it currently happens.

**Comment by chuckharmston** [comment]
> we need to be able to test a page properly and in advance

It'd still be testable on the dev site, for what it's worth.

**Comment by flodolo** [comment]
> It'd still be testable on the dev site, for what it's worth.
I'm not sure it's safe to assume that 'stage' doesn't include 'dev', especially coming from marketing perspective.

**Comment by ckprice** [comment]
> I'm not sure it's safe to assume that 'stage' doesn't include 'dev', especially coming from marketing perspective.

We've been clear with marketing that there will be a dev URL public. Their main concern is the live URL being out in the wilds.

Considering the sprint schedule we discussed today, we may not need such a mechanism for this sprint since we'll only be doing one production push at launch. We should expect some pushes to stage though, so let me confirm that it's okay for a dev and stage URL out in the wilds as long as the production URL isn't exposed.

**Comment by ckprice** [comment]
Kicking this out of this sprint.

**Comment by ghost** [comment]
Today we have:
- a dev flag to show/hide experiments
- a launch_date flag to tell the system when to show an experiment

With these flags we've launched a bunch of experiments and survived.  I'm going to close this.
