### ISSUE TITLE
Test Pilot dates not localized into my current locale

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1823]
https://testpilot.dev.mozaws.net/__version__ (8addf5f3dca7e1e6f24af08d7c5efb839bc5b090):

```json
{ "commit": "8addf5f3dca7e1e6f24af08d7c5efb839bc5b090",
  "version":"",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/1792" }
```

---

My current locale is German ("de"), but the date isn't German formatted.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/20365092/7ad73e5e-abfa-11e6-8f99-04d0c2b91f05.png)

I want to blame the [./frontend/src/app/lib/utils.js `formatDate()` method](https://github.com/mozilla/testpilot/blob/e6541b1a74575998e9ef1154a5633d696c667083/frontend/src/app/lib/utils.js#L6-L20). I think it should be passing the desired locale into `.toLocaleDateString()`:

```js
const dat = '2016/11/16';
const dat2 = new Date(dat);

const locales = [undefined, 'en-US', 'fr', 'de', 'in', 'es', 'zh-CH'];

locales.forEach((locale) => {
  console.log(`${locale}: ${dat2.toLocaleDateString(locale)}`);
});

/* OUTPUT:
  "undefined: 11/16/2016"
  "en-US: 11/16/2016"
  "fr: 16/11/2016"
  "de: 16.11.2016"
  "in: 11/16/2016"
  "es: 16/11/2016"
  "zh-CH: 2016/11/16"
*/
```

As you can see in my German translated screenshot above, the date is formatted as "11/16/2016" (mm/dd/yyyy), but the German formatting should be "dd.mm.yyyy".

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

We _may_ be able to do something like:

```js
out = d.toLocaleDateString(navigator.locales);
```

**Comment by SoftVision-PaulOiegas** [comment]
DD.MM.YYYY date format is now correctly displayed for German language on experiment end date notification message, actual experiment end date under logo and last update date sections.
