### ISSUE TITLE
Page titles not localized

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1824]
A quick test shows the `<title>` element not being localized:

<img width="1081" alt="screen shot 2016-11-16 at 5 38 21 pm" src="https://cloud.githubusercontent.com/assets/23885/20371662/80492f04-ac23-11e6-889d-3e0175d5df4e.png">

In fact, it appears that none of our page title strings are even used in the code: [pageTitleDefault](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=pageTitleDefault), [pageTitleLandingPage](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=pageTitleLandingPage&type=Code), [pageTitleExperimentListPage](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=pageTitleExperimentListPage&type=Code), [pageTitleExperiment](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=pageTitleExperiment&type=Code)

Let's either get page titles localized, or decide that it's not necessary and remove the strings.

**Comment by pdehaan** [comment]
Looks like the values are hardcoded in the .mustache templates:

[/frontend/src/templates/index.mustache:17-19](https://github.com/mozilla/testpilot/blob/18aa4b8e591cab05db19625d4fd938965270c021/frontend/src/templates/index.mustache#L17-L19):

``` html
    <title>{{ meta_title }}</title>
    <meta property="og:title" content="{{ meta_title }}" />
    <meta name="twitter:title" content="{{ meta_title }}" />
```

---

[/frontend/tasks/pages.js:61](https://github.com/mozilla/testpilot/blob/18aa4b8e591cab05db19625d4fd938965270c021/frontend/tasks/pages.js#L61):

``` js
    const pageContent = Mustache.render(template, {
      meta_title: 'Firefox Test Pilot',
      meta_description: 'Test new Features. Give us feedback. Help build Firefox.',
```

**Comment by pdehaan** [comment]
Also, for future verification, it looks like only a few of the locales have translations for the `pageTitleDefault`:

``` sh
$ git grep pageTitleDefault *.ftl

locales/ast/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/bn-BD/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/de/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/en-US/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/fa/app.ftl:pageTitleDefault = خلبان آزمایشی فایرفاکس
locales/fr/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/fy-NL/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/ja/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/pt-BR/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/sv-SE/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/tr/app.ftl:pageTitleDefault = Firefox Test Pilotu
locales/uk/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/zh-CN/app.ftl:pageTitleDefault = Firefox Test Pilot
locales/zh-TW/app.ftl:pageTitleDefault = Firefox Test Pilot
```

**Comment by lmorchard** [comment]
> Looks like the values are hardcoded in the .mustache templates

Those templates build our static pages. The hardcoded `<meta>` tags are for social media sharing, and aren't localized yet. 

Not entirely sure *how* to localize them yet, since we do everything client-side with L20N right now and don't have any URL path schemes like `/{en-US,de,fr,ja,zh-CN}/experiments/` etc. I've read that lots of spiders run JS these days, but haven't really seen Twitter & Facebook pick up JS-driven changes to `<meta>` tags yet.

**Comment by lmorchard** [comment]
I *think* we should be able to slap a `data-l10n-id` on the main page `<title>` though, and at least get the in-browser page title localized
