### ISSUE TITLE
Edge Browser Making Extra Boxes around some template strings

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1828]
<img width="356" alt="screen shot 2016-11-17 at 2 39 37 pm" src="https://cloud.githubusercontent.com/assets/3323249/20391487/e31e0734-acd3-11e6-9f85-c0c5808aac61.png">

Just noticed this while debugging edge's SVG behavior.

**Comment by ghost** [comment]
This is suspiciously similar to #875 but I can still reproduce that one (on Firefox) and I can't see this one (on Firefox)

**Comment by johngruen** [comment]
Don't think this is CSS related. Probably l20n placeholders getting rendered

**Comment by meandavejustice** [comment]
Still seeing a little weirdness on edge as of today.

(edge is on the right)
![rendering-issue-edge](https://user-images.githubusercontent.com/1844554/34184871-1f844a06-e51a-11e7-84e1-c1474a03bf4c.png)

Here is some discussion on the issue, https://github.com/l20n/l20n.js/pull/116

We can maybe close this as it is an upstream bug, thoughts?

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas can you confirm this on latest edge?

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen The original boxes were replaced now by some other weirdness as mentioned in Dave's screenshots. These are displayed on every experiment details page after launch date and experiment name.

![extra characters on edge](https://user-images.githubusercontent.com/17258026/35034734-d0414574-fb77-11e7-88bb-de65066743ee.png)

**Comment by johngruen** [comment]
@dannycoates has a fix for this on Send, we should consider implementing the same:

https://github.com/mozilla/send/issues/476

**Comment by fzzzy** [comment]
@johngruen Thank you very much for the link to danny's fix. It looks pretty simple:

`var ctx = new fluent.MessageContext('${locale}', {useIsolating: false});`

See this page for details on these characters: https://en.wikipedia.org/wiki/Bi-directional_text#Unicode_support

FSI is the 'First Strong Isolate' character. PDI is the 'Pop Directional Isolate' character. Presumably, useIsolating: false prevents Fluent from emitting these characters. I assume there is some reason to emit these characters -- leaving them out might cause issues with right-to-left languages? But I guess we can cross that bug when we get to it.

**Comment by fzzzy** [comment]
I submitted an untested pr which might fix it -- can someone with easy access to Edge test it?

**Comment by SoftVision-PaulOiegas** [comment]
The fix on your branch seems to be working. 👍  Verified with Microsoft Edge 40.15063.674.0 on Windows 10 v1703 (OS Build 15063.850).
