### ISSUE TITLE
Figure out localization for graduation reports

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1829]
We don't need to do this for this sprint b/c we're only graduating U.S...

The graduation reports will be long-ish docs and are probably not suitable to be localized by our community localizers. We have budget for paid localization, so we should figure out how to use it for these reports.

**Comment by flodolo** [comment]
Jumping in the discussion as an outsider ;-)

I tend to agree, we shouldn't ask our localizers to work on this: they're long, potentially short-lived.

If you expose these strings to external agencies for localization though, we should figure out a way for localizers to review (and update if needed) those translations. Also, please make sure to talk with @peiying2 about selecting the agency properly.

Some questions:
- Have you thought if these results should be localized at all? I guess it all depends on the target. It would also be interesting to see analytics about the upcoming reports (visitors, time spent on the page).
- Should they live inside the Test Pilot's website at all? They seem like the right content to syndicate on planet and a blog post, comments included.

**Comment by johngruen** [comment]
@flodolo thanks for your response!

> Have you thought if these results should be localized at all? I guess it all depends on the target. It would also be interesting to see analytics about the upcoming reports (visitors, time spent on the page).

So the intent is for these reports to live on after the experiment has concluded in perpetuity after an experiment has ended. To your point about analytics, we will definitely monitor the degree to which people visit the universal search page after it graduates to determine requirements. 

> Should they live inside the Test Pilot's website at all? They seem like the right content to syndicate on planet and a blog post, comments included.

Both, i think... I like the idea of having a central, canonical record of the experiment that doesn't disappear as quickly as a blog post. That having been said, we want to cross link to blog posts etc, and syndicating these reports should be goal.

**Comment by ghost** [comment]
@johngruen is going to look into how many browsers are visiting the summaries and requesting non en-US locales.

**Comment by johngruen** [comment]
Looking at metrics, it seems like the highest level of non en grad report peeping is 145 pairs of DE eyes on the No More 404s report. Closing until this becomes an issue
