### ISSUE TITLE
Convert About page to a localizable format

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#1835]
The about page just landed, and it's a markdown file in the repository. That basically makes it non localizable: it's not available in Pontoon, localizers will need to open PRs to add a translation, and every single time they want to update a typo they need a PR.

That content should be available as an HTML template, and it strings exposed through the standard localization channels.

**Comment by jaredhirsch** [comment]
We're going to have paid localizers handle large blocks of text, like the 'about' page. Closing in favor of #2514, which tracks the paid localization work.
