### ISSUE TITLE
Firefox icon from the "Upgrade Firefox" green buttons, is cropped on German locale

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1836]
[Affected versions]:
- Firefox 44.0.2

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have Firefox 44.0.2 release or a lower version installed.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Observe both the Firefox icons from the "Upgrade Firefox" green buttons.

[Expected result]:
- The icons are correctly displayed on both the "Upgrade Firefox" buttons.

[Actual result]:
- The icons are both displayed as cropped on the "Upgrade Firefox" buttons.

[Notes]:
- Here is a screenshot with the issue:

![update button](https://cloud.githubusercontent.com/assets/19226534/20432037/f3ff31f4-ada5-11e6-8af2-b11780ecb011.png)

**Comment by SoftVision-PaulOiegas** [comment]
Looks ok now in German locale. Marking this as verified.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is reproducible on production.

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean please verify on prod when we tag the next release
