### ISSUE TITLE
Prompt notification to check experiments wrongly shows after browser restart instead of 24h from installation

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1837]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click the "Install the Test Pilot Add-on" green button and install the add-on.
3. Restart the browser and observe its behavior.

[Expected result]:
- Browser is restarted and default homepage is displayed.

[Actual result]:
- Browser is restarted but on the homepage, also a notification that should only appear after 24h from installation is wrongly displayed.

[Notes]:
- Issue is also reproducible on dev server.

![prompt to check experiments](https://cloud.githubusercontent.com/assets/17258026/20432012/e1547cee-ada5-11e6-8888-f81c91f5aad8.gif)

**Comment by ckprice** [comment]
Closed in #1848.

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed, haven't managed to reproduce it with multiple restarts and uninstall + reinstall.. Marking it as verified.
