### ISSUE TITLE
The "What experiments?" button from notification to try experiments after 24h from installation is wrongly colored

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1838]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click the "Install Test Pilot add-on" green button.
3. After installation is completed, restart the browser
4. Observe the color of "What experiments?" button from the displayed notification bar.

[Expected result]:
- The "What experiments" background button has a blue color.

[Actual result]:
- The "What experiments?" background button has a grey color and the text is hardly visible.

[Notes]:
- This issue is not reproducible on Mac OS.
- Here is a screenshot with the issue:
![what experiment background button](https://cloud.githubusercontent.com/assets/19226534/20432368/77420a0e-ada7-11e6-9711-5aebb68c31ff.png)

**Comment by chuckharmston** [comment]
The news here is not great, unfortunately. Cross-platform support for XUL CSS is limited, and the `background` property on `<button>` is one of the ones that is limited. It works okay on OS X, but on Windows any value (tried named colors, hex values, and `rgb()`) is declared invalid and ignored. I don't think there's a good fix for this.

Here's what the system defaults (i.e. no CSS) look like:

![screen shot 2016-11-21 at 9 41 05 am](https://cloud.githubusercontent.com/assets/23885/20491607/29cab1de-afcf-11e6-90fc-0baf3b031e42.png)

![screen shot 2016-11-21 at 9 42 34 am](https://cloud.githubusercontent.com/assets/23885/20491608/29ccb038-afcf-11e6-87c9-89aa3b15aa40.png)

It will vary drastically on Linux with the specifics of the distribution.

I can look into doing platform-specific CSS for OS X-only, but even then, it may look bad depending on the theme the user has installed. My inclination is to trust the platform-specific styles in Firefox to provide a native-feeling prompt.

Thoughts, @sevaan?
