### ISSUE TITLE
Expired dev-only experiment still displays as related add-on

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1840]
https://testpilot.dev.mozaws.net/__version__ (5c97b7918d328741f8684269df80c9d28d0447bd):

```json
{ "commit": "5c97b7918d328741f8684269df80c9d28d0447bd",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/1890" }
```

---

1. Go to https://testpilot.dev.mozaws.net/experiments/min-vid (not logged in)
2. Scroll to bottom.
3. Note that the 'Dev Example' experiment is listed.
4. Click 'Dev Example' tile
5. https://testpilot.dev.mozaws.net/experiments/dev-example

<img width="1440" alt="firefox_test_pilot" src="https://cloud.githubusercontent.com/assets/557895/20439173/45779d32-ad6f-11e6-9334-59a3befa4d86.png">

Note that the Dev only experiment expired 2 days ago on 11/16/2016. 

<img width="558" alt="firefox_test_pilot_-_min_vid" src="https://cloud.githubusercontent.com/assets/557895/20439331/de089df8-ad6f-11e6-9f0c-0af194005646.png">

**Comment by pdehaan** [comment]
Note that the expired add-on does not display on the home page.
<img width="1440" alt="firefox_test_pilot_-_min_vid" src="https://cloud.githubusercontent.com/assets/557895/20439398/265aef48-ad70-11e6-9090-143ee8d287e9.png">

**Comment by ghost** [comment]
I can't reproduce this anymore (listing is not shown at the bottom of the detail page)
