### ISSUE TITLE
Audit existing avatar image sizes

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1845]
Ref: https://github.com/mozilla/testpilot/pull/1843#pullrequestreview-9301574

> @chuckharmston: Can you resize the avatar to 64x64 please?
> https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#contributors

| WxH | SIZE | PATH |
|:---:|-----:|:-----|
| 64x64 | 2.3KB | /frontend/src/images/experiments/activity-stream/avatars/kate-hudson.jpg
| 64x64 | 9.9KB | /frontend/src/images/experiments/activity-stream/avatars/ricky-rosario.jpg
| 400x400 | 34.8KB | /frontend/src/images/experiments/activity-stream/avatars/nan-jiang.jpg
| 500x500 | 128.2KB | /frontend/src/images/experiments/activity-stream/avatars/ursula-sarracini.jpg
| 371x341 | 74.4KB | /frontend/src/images/experiments/activity-stream/avatars/marina-samuel.jpg
| 64x64 | 2.2KB | /frontend/src/images/experiments/activity-stream/avatars/edwin-wong.jpg
| 64x64 | 2.2KB | /frontend/src/images/experiments/activity-stream/avatars/jared-kerim.jpg
| 64x64 | 2.1KB | /frontend/src/images/experiments/activity-stream/avatars/andrei-oprea.jpg
| 64x64 | 1.6KB | /frontend/src/images/experiments/activity-stream/avatars/bernardo-rittmeyer.jpg
| 64x64 | 3.0KB | /frontend/src/images/experiments/activity-stream/avatars/nick-chapman.jpg
| 460x460 | 132.2KB | /frontend/src/images/experiments/activity-stream/avatars/tim-spurway.jpg
| 125x125 | 8.2KB | /frontend/src/images/experiments/activity-stream/avatars/olivier-yiptong.jpg
| 64x64 | 7.1KB | /frontend/src/images/experiments/activity-stream/avatars/bryan-bell.jpg
| 112x112 | 2.9KB | /frontend/src/images/experiments/cliqz/avatars/cliqz-avatar.jpg
| 112x112 | 26.5KB | /frontend/src/images/experiments/avatars/tvyas.png
| 112x112 | 19.4KB | /frontend/src/images/experiments/avatars/amarchesini.png
| 112x112 | 27.6KB | /frontend/src/images/experiments/avatars/lcrouch.png
| 112x112 | 14.2KB | /frontend/src/images/experiments/avatars/kjozwiak.png
| 288x288 | 46.7KB | /frontend/src/images/experiments/avatars/peter.jpg
| 112x112 | 17.1KB | /frontend/src/images/experiments/avatars/michelle.jpg
| 112x112 | 24.5KB | /frontend/src/images/experiments/avatars/jkingston.png
| 112x112 | 27.3KB | /frontend/src/images/experiments/avatars/fshih.png
| 112x112 | 30.7KB | /frontend/src/images/experiments/avatars/mliang.png
| 112x112 | 27.3KB | /frontend/src/images/experiments/avatars/mchen.png
| 112x112 | 10.9KB | /frontend/src/images/experiments/min-vid/avatars/dave-justice.jpg
| 112x112 | 11.8KB | /frontend/src/images/experiments/min-vid/avatars/jared-hirsch.jpg
| 112x112 | 13.4KB | /frontend/src/images/experiments/min-vid/avatars/jen-kagan.jpg
| 112x112 | 10.9KB | /frontend/src/images/experiments/min-vid/avatars/dave-justice.jpg
| 112x112 | 11.8KB | /frontend/src/images/experiments/min-vid/avatars/jared-hirsch.jpg
| 112x112 | 13.4KB | /frontend/src/images/experiments/min-vid/avatars/jen-kagan.jpg
| 62x64 | 10.2KB | /frontend/src/images/experiments/min-vid/avatars/noitidart.jpg
| 96x96 | 1.3KB | /frontend/src/images/experiments/no-more-404s/avatars/the-internet-archive.png
| 400x400 | 17.8KB | /frontend/src/images/experiments/no-more-404s/avatars/richard-caceres.jpg
| 187x187 | 19.4KB | /frontend/src/images/experiments/no-more-404s/avatars/mark-graham.jpg
| 247x247 | 15.9KB | /frontend/src/images/experiments/no-more-404s/avatars/adam-miller.jpg
| 112x112 | 14.9KB | /frontend/src/images/experiments/avatars/udara-w.jpg
| 112x112 | 26.4KB | /frontend/src/images/experiments/avatars/cedric-a.png
| 112x112 | 17.5KB | /frontend/src/images/experiments/avatars/ryan-f.jpg
| 112x112 | 16.4KB | /frontend/src/images/experiments/avatars/remy-h.jpg
| 112x112 | 18.2KB | /frontend/src/images/experiments/avatars/vlad-f.jpg
| 288x288 | 46.7KB | /frontend/src/images/experiments/avatars/peter.jpg
| 288x288 | 39.9KB | /frontend/src/images/experiments/avatars/emil.jpg
| 112x112 | 13.0KB | /frontend/src/images/experiments/page-shot/avatars/ian-bicking.jpg
| 112x112 | 11.5KB | /frontend/src/images/experiments/page-shot/avatars/donovan-preston.jpg
| 112x112 | 14.1KB | /frontend/src/images/experiments/page-shot/avatars/bram-pitoyo.jpg
| 64x64 | 2.3KB | /frontend/src/images/experiments/universal-search/avatars/chuck-harmston.jpg
| 288x288 | 73.9KB | /frontend/src/images/experiments/avatars/sevaan.jpg
| 288x288 | 60.1KB | /frontend/src/images/experiments/avatars/harald.jpg
| 288x288 | 46.7KB | /frontend/src/images/experiments/avatars/peter.jpg
| 128x128 | 23.4KB | /frontend/src/images/experiments/avatars/abhi-a.jpg
| 112x112 | 20.4KB | /frontend/src/images/experiments/avatars/daniela-a.jpg
| 112x112 | 17.9KB | /frontend/src/images/experiments/avatars/danny-c.jpg
| 112x112 | 23.1KB | /frontend/src/images/experiments/avatars/peko-c.jpg
| 112x112 | 30.7KB | /frontend/src/images/experiments/avatars/mliang.png
| 112x112 | 27.3KB | /frontend/src/images/experiments/avatars/mchen.png
| 112x112 | 25.8KB | /frontend/src/images/experiments/avatars/erica-w.png
| 288x288 | 73.9KB | /frontend/src/images/experiments/avatars/sevaan.jpg
| 288x288 | 69.7KB | /frontend/src/images/experiments/avatars/les.jpg
| 288x288 | 73.9KB | /frontend/src/images/experiments/avatars/sevaan.jpg
| 64x64 | 2.3KB | /frontend/src/images/experiments/tab-center/avatars/blake-w.jpg
| 400x400 | 69.1KB | /frontend/src/images/experiments/tab-center/avatars/erica-wright.png
| 288x288 | 61.3KB | /frontend/src/images/experiments/avatars/parag.jpg
| 288x288 | 46.7KB | /frontend/src/images/experiments/avatars/peter.jpg
| 288x288 | 39.9KB | /frontend/src/images/experiments/avatars/emil.jpg
| 288x288 | 40.9KB | /frontend/src/images/experiments/avatars/ciprian.jpg
| 64x64 | 2.3KB | /frontend/src/images/experiments/tab-center/avatars/blake-w.jpg
| 400x400 | 69.1KB | /frontend/src/images/experiments/tab-center/avatars/erica-wright.png
| 64x64 | 2.0KB | /frontend/src/images/experiments/tab-center/avatars/philipp-s.jpg
| 64x64 | 2.2KB | /frontend/src/images/experiments/tab-center/avatars/john-g.jpg
| 112x112 | 12.9KB | /frontend/src/images/experiments/tracking-protection/avatars/luke-crouch.jpg
| 112x112 | 9.6KB | /frontend/src/images/experiments/tracking-protection/avatars/aislinn-grigas.jpg
| 112x112 | 14.6KB | /frontend/src/images/experiments/tracking-protection/avatars/rebecca-billings.jpg
| 64x64 | 3.0KB | /frontend/src/images/experiments/universal-search/avatars/nick-chapman.jpg
| 64x64 | 7.1KB | /frontend/src/images/experiments/universal-search/avatars/bryan-bell.jpg
| 64x64 | 2.5KB | /frontend/src/images/experiments/universal-search/avatars/jared-hirsch.jpg
| 64x64 | 2.3KB | /frontend/src/images/experiments/universal-search/avatars/chuck-harmston.jpg
| 112x112 | 14.5KB | /frontend/src/images/experiments/avatars/andre-n.jpg
| 112x112 | 17.3KB | /frontend/src/images/experiments/avatars/fabrice-d.jpg
| 112x112 | 27.3KB | /frontend/src/images/experiments/avatars/fshih.png
| 112x112 | 30.7KB | /frontend/src/images/experiments/avatars/mliang.png
| 112x112 | 27.3KB | /frontend/src/images/experiments/avatars/mchen.png
| 112x112 | 18.2KB | /frontend/src/images/experiments/avatars/carmen-f.jpg
| 288x288 | 40.9KB | /frontend/src/images/experiments/avatars/ciprian.jpg
| 112x112 | 14.2KB | /frontend/src/images/experiments/avatars/faramarz-r.jpg

```js
const { readdir } = require('fs');
const path = require('path');

const fastimage = require('fastimage'); // `npm i fastimage`
const YAML = require('yamljs');

const EXPERIMENT_DIR = path.join(__dirname, 'content-src', 'experiments');

getExperiments(EXPERIMENT_DIR)
  .then((experiments) => {
    const avatars = experiments.map((experiment) => lintAvatars(experiment.contributors));
    return Promise.all(avatars);
  })
  .then((experiments) => {
    console.log('| WxH | SIZE | PATH |');
    console.log('|:---:|-----:|:-----|');
    experiments.forEach((avatars) => avatars.forEach((avatar) => {
      console.log(`| ${avatar.width}x${avatar.height} | ${(avatar.size/1024).toFixed(1)}KB | ${avatar.realPath}`);
    }));
  })
  .catch((err) => {
    console.error(err.message);
    process.exit(1);
  });

function getExperiments(dir) {
  return new Promise((resolve, reject) => {
    readdir(dir, (err, files) => {
      if (err) {
        return reject(err);
      }
      const yamlFiles = files.filter((file) => (/\.yaml$/).test(file))
        .map((file) => YAML.load(path.join(dir, file)));
      resolve(yamlFiles);
    });
  });
}

function lintAvatars(contributors) {
  const images = contributors.map((contributor) => {
    const avatarPath = contributor.avatar.replace('/static/', './frontend/src/');
    return fastimage.info(avatarPath).then(avatar => {
      avatar.realPath = avatar.realPath.replace(__dirname, '');
      return avatar;
    });
  });
  return Promise.all(images);
}
```

**Comment by ghost** [comment]
Marking this as a good first bug because it's just resizing these images and replacing them.

**Comment by CHBaker** [comment]
I'll take this issue

**Comment by pdehaan** [comment]
Awesome, @CHBaker, thanks! 
Let us know if you have any questions or need help.

~~I'm not sure how accurate the above table is, considering we've added and retired a few experiments since then (but core concept is still the same).~~

Updated the script and output. It now assumes you're running it from the root of the repo and have `fastimage` module installed locally.

**Comment by CHBaker** [comment]
So I'm just updating the fast image configuration? what is the file path to the fast image module

also, on a side note, where should I post about set up issues? Ive got some errors trying to run the quick setup.

**Comment by pdehaan** [comment]
@CHBaker I'd probably just recommend resizing all the avatar images to 64x64. I think it should be mostly straight forward except for the 1 image that is non-square (371x341). For that one you may need to manually crop the image to whatever looks best for 64x64.

Which set up issues? If it's with Test Pilot itself, this repo is the best place. If it's for a specific experiment, I'd file it in that experiment's repo.

**Comment by CHBaker** [comment]
when I was initially running `npm run package` with npm and node up to date, I was getting a series of errors... but I ran through the entire set up, then came back to it and ran `npm run package` again and no errors appeared, so I'm not sure what fixed it.

but I recreated it just by following the quick start. here is the error:
<img width="736" alt="screen shot 2017-08-14 at 4 46 15 pm" src="https://user-images.githubusercontent.com/14304935/29295168-2d3596c8-8110-11e7-91f4-65c9eb0adf68.png">

**Comment by johngruen** [comment]
hey @pdehaan @CHBaker I think we would prefer icons to be at 112x112 which would be 2x their displayed sizes: 
https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/ExperimentPage.js#L399

For those that are already smaller than this 64 x 64, i don't think we need to worry about resizing. They'll still look decent and are on older experiments anyway.

**Comment by CHBaker** [comment]
Alright, i'll change them to 112

**Comment by meandavejustice** [comment]
fixed in https://github.com/mozilla/testpilot/pull/2780
