### ISSUE TITLE
Test Pilot Privacy page in DE locale has no "Show more/less" buttons to expand, hide sections content

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1847]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisite]:
- German language was added on the top of the list from Firefox "Options > Content > Languages" section.

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://testpilot.dev.mozaws.net/" page.
2. Click the "Privacy Policy" text button (Datenschutzhinweis) from under the green install button.
3. Observe the how Privacy page content is rendered on DE locale. 

[Expected result]:
- The page content looks like the one on en-US locale with two "Show more" buttons to expand the available sections.

[Actual result]:
- The page content is rendered directly expanded with no option to hide it 

[Notes]:
- Here is a screenshot of the issue:
![missing buttons to reduce sections](https://cloud.githubusercontent.com/assets/17258026/20482589/1145c9f6-aff6-11e6-9d11-2ac87cfe88a1.png)

- Strangely it seams that we have two pages for en-US "Privacy Policy". One with no slash at the end (default) and the second one with a slash that also displays the same behavior as the DE locale one. See attached recording

![two privacy pages](https://cloud.githubusercontent.com/assets/17258026/20483249/aa693322-aff9-11e6-9887-68e0b618b3fe.gif)

**Comment by ghost** [comment]
This is weird, but it's not affecting the functionality of the privacy policy so I'm going to wontfix it.  Thanks for filing.
