### ISSUE TITLE
[Enhancement] We should display a specific newsletter error message for already signed up emails 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1849]
[Notes]:
- The current behavior is confusing for users that forget that they already signed up for the newsletter.
- Usually the user is not notified at all. This is the most confusing case since the user does not receive anything by email and if he tries for several times it ends up on the default error.
- Default error message only encourages him to try some more which will have the same result.

[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisite]:
- A valid email address was already used to subscribe to the Test Pilot newsletter.

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://testpilot.dev.mozaws.net/" page.
2. Scroll down to the bottom of the page to reach the "Newsletter" section.
3. Click the text box and enter a valid email address that already signed up for it.
4. Check the checkmark box and click on "Sign Up Now" button.
5. Observe the page behavior.

[Expected result]:
- An error is displayed informing the user that the entered email is already signed up for newsletter.

[Actual result]:
- No error or the default error message is displayed "There was an error submitting your email address. Try again ?".

**Comment by chuckharmston** [comment]
Can you check the status code of the API response in this case? I suspect that you're getting a 429 from Basket, which is actually a rate limiting, rather than an email resubmission error. A bug seeking better messaging for that exists at #1669.

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, my bad. I forgot that we logged that one and someone mentioned about this behavior today so I logged it without checking.  Closing as a dupe of #1669.
