### ISSUE TITLE
Hard-coded string: "We will automatically disable the Universal Search experiment and report the results when it ends."

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#1850]
https://testpilot.dev.mozaws.net/experiments/universal-search
https://github.com/mozilla/testpilot/blob/master/content-src/experiments/universal-search.yaml#L95

It's currently displayed in English even for locales completely translated. Not sure if it's because of the missing quotes.

**Comment by fzzzy** [comment]
@flodolo is this still happening?

**Comment by flodolo** [comment]
Not at the moment, but we need an experiment with that warning enabled to verify it.

**Comment by fzzzy** [comment]
Oh, I see. Well, as this experiment has ended, let's just make sure the next "experiment will be ending" message is localized properly when we get closer to ending another experiment, and open another bug if not.

**Comment by flodolo** [comment]
Is there a way to force to show this message locally? I would prefer to check than close and refile if the bug is still there (I assume it is).

**Comment by fzzzy** [comment]
Ok, I'll just reopen this issue then. Probably the easiest way to test this is to change one of the graduation dates locally. I see in docs/content/reference.md that the example eol_warning does have quotes around it.

**Comment by flodolo** [comment]
Tried with SnoozeTabs, and created a snoozetabsEolwarning string. The string seems correctly displayed even if the string has not quotes, so not sure what happened there.

At this point it makes sense to close.

**Comment by fzzzy** [comment]
Thanks!
