### ISSUE TITLE
Consider platform-specific CSS for notification buttons.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#1853]
In #1838 we discovered that some CSS is not applied to notification buttons on some platforms. We should consider finding a centralized way to conditionally override platform-specific styles (e.g. on macOS, `background-color` is supported and we should use it).

**Comment by johngruen** [comment]
@chuckharmston this is a broader issue that may not be platform but site specific. If a site styles buttons directly there's a chance we won't override. We could also consider injecting some kind of reset CSS inline into problem elements (buttons in particular seem to get styled directly)

**Comment by chuckharmston** [comment]
@johngruen we're talking about heartbeat-style notifications here; sites shouldn't be touching them.

**Comment by johngruen** [comment]
Yeah, sorry, i thought we were injecting those bars into content...seems like an easier fix if that's not the case :)

**Comment by johngruen** [comment]
This is probably a wontfix since we'll have to work up a new solution
