### ISSUE TITLE
Test Pilot install counts in Telemetry graphs seem incorrect

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1855]
Check out our raw usage numbers:  https://analysis-output.telemetry.mozilla.org/testpilot/data/installation-counts/latest.json  Those counts are counting the number of 'enabled' pings the Test Pilot add-on is sending to Telemetry.  Some of the numbers are a little suspicious (eg. 360k page shot installs and only 220k test pilot users).  The Page Shot usage stats show more likely 40k active users.

If you look at the graph here:  https://sql.telemetry.mozilla.org/queries/1699/source#3010 you'll see some sharp upward lines.  The current theory is that the Test Pilot add-on is sending a Telemetry ping when an experiment gets an update (when it should only be sending a ping when the experiment is first enabled).

Let's double check and fix it if that's the case.

/cc @fzzzy

**Comment by sunahsuh** [comment]
If we do find this to be the case, sending an "updated" event instead would be my personal preference

**Comment by jaredhirsch** [comment]
@clouserw @sunahsuh I think the SQL used to generate the graph might be the issue.

To track the number of installs, we have to subtract 'disabled' events from 'enabled' events. (The reason is that, if an addon is disabled and then uninstalled, we won't ever get an uninstall ping--Firefox unloads the metrics code when the addon is disabled, so there's nothing listening for the later uninstall event.)

The graph SQL counts 'enabled' pings without also subtracting 'disabled' pings:

```sql
# code from: https://sql.telemetry.mozilla.org/queries/1699/source
with counts as (
  select
    count(*) as count,
    txp_event_object,
    date_parse(submission_date_s3, '%Y%m%d') as submission_date
  from test_pilot_pings
  where txp_event like 'enabled' #  <------------------- right here
  group by 2, 3
  order by 3, 2
)
select
  sum(count) 
    over (partition by txp_event_object order by submission_date)
  as cumulative_sum,
  submission_date,
  txp_event_object
from counts
order by submission_date, txp_event_object
```

I do have some doubts about the addon code, as it seems to [double-fire the 'enabled' ping](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L332) both when an addon is installed, and when it's enabled, but I need to verify that, which I'll do in a separate bug.

I'm going to leave this open to track the dashboarding updates, but if that would be better tracked on bugzilla, we can close this.

**Comment by sunahsuh** [comment]
Hey Jared, apologies, I linked to the incorrect the query in the original bug. The query that's hooked up to the TxP dashboard is this one, which still shows irregularities, particularly for jetpack: https://sql.telemetry.mozilla.org/queries/1724/source#3073

**Comment by jaredhirsch** [comment]
@sunahsuh Do you happen to know where I can find the code that turns Telemetry pings into the `txp_events` table?

I've noticed that the testpilot addon resets its client ID after each upgrade--not the Firefox clientId normally used by Telemetry, but the testpilot user identifier, which is saved in addon storage. I'm wondering if that is the cause of the odd jumps in install counts after each experiment addon is upgraded. The events across time might be something like:

- user installs testpilot
- testpilot sets uid 1
- user enables experiment version 1
- daily ping will include experiment version 1, uid 1
- testpilot updates, changing uid 1 to uid 2
- testpilot fires disable ping with uid 1
- testpilot fires enable ping with uid 2
- daily ping will include experiment version 1 with uid 2
- experiment updates to version 2
- daily ping will include experiment version 2 with uid 2

I guess there's room in here to accidentally double-count an active user, if testpilot disable/enable pings aren't reconciled with the experiment user counts, and if the experiment user counts use the testpilot user id, not the telemetry clientId. Seems like a stretch, but might be worth investigating further.

(Is [this](https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/moz_telemetry/sandboxes/heka/analysis/moz_testpilot_installation.lua) the code that generates the data?)

**Comment by sunahsuh** [comment]
Hey Jared, we don't use the client ID at all in that dashboard -- we just sum up all enables and subtract all disables. Here's the code that we're currently using for the txp_events table https://gist.github.com/sunahsuh/f6e694da157b0e05aedc77ad4cba20ad (The lua filter you found is currently experimental but we'd like to use it in the future.)

**Comment by jaredhirsch** [comment]
@sunahsuh Great, thanks. Is there any chance I could try to run that python code myself on the input data (with PII bits sanitized out, I guess)? Not sure what the permissions are for accessing the data in S3, but I do have access to the cloud services dev and prod AWS accounts.

**Comment by jaredhirsch** [comment]
OK, sunah pointed me at https://analysis.telemetry.mozilla.org/ as a place where I can run that notebook. That site is accessible to Mozilla staff. Also helpful: https://spark.apache.org/docs/2.0.2/api/python/pyspark.html

**Comment by johngruen** [comment]
this may change pending sharon's research report
