### ISSUE TITLE
installations_url for experiments 404s?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1857]
Casually surfing through https://testpilot.firefox.com/api/experiments.json and I see an `installations_url` field for each experiment. If I try and ping that endpoint, I get a 404:

https://testpilot.firefox.com/api/experiments/2.json -- works
https://testpilot.firefox.com/api/experiments/2/installations/ -- no works

Not sure if we're using that `installations_url` for anything, or if we're getting the usage counts via telemetry (see https://github.com/mozilla/testpilot/blob/4ab8fdacc9f1a796115ba3dc54c95d6a9066db6a/frontend/src/app/config.js#L5)?

**Comment by lmorchard** [comment]
Yeah, we should delete this property. Telemetry does i deed handle this now, and the original service went away with Django
