### ISSUE TITLE
Localization missing for specific elements on the Test Pilot website

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1858]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- The "experiments.webapi.testing" boolean pref was manually set to true.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click the "Install Test Pilot add-on" green button in order to install the add-on.
3. Choose an available experiment and enable it.
4. Click the Test Pilot icon from the browser toolbar.
5. Observe the strings displayed in doorhanger.

[Expected result]:
- All the strings are correctly displayed with no format issue in doorhanger.

[Actual result]:
- The "experiment_list_enabled" string is displayed instead of "Enabled" for the enabled experiment.
- The "experiment_list_view_all" string appears instead of "View All Experiments" one at the end of doorhanger. 

[Notes]:
- This issue is also reproducible for Test Pilot massage displayed on the no-experiment notification prompt after 24h from Test Pilot installation.
- This reproduces on all locales including en-US default one.
- This issue could affect other strings too but some of them are unreachable to test at the moment.
- Here are the screenshots with the issue:
![no experiment notification](https://cloud.githubusercontent.com/assets/19226534/20526525/22d51672-b0cd-11e6-95f3-0bf84e6e60d7.png)
![doorhanger strings](https://cloud.githubusercontent.com/assets/19226534/20526530/24bab852-b0cd-11e6-80d2-6f144823e364.png)

**Comment by flodolo** [comment]
That's the behavior of l20n when a string is not available. Since these strings are [exposed](https://github.com/mozilla/testpilot/blob/master/locales/en-US/addon.properties) for localization, I guess something is wrong with the package.

**Comment by chuckharmston** [comment]
> That's the behavior of l20n when a string is not available.

These are all strings in the add-on; which doesn't use l20n, but instead uses the [SDK l10n module](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/l10n) (which may also behave the same way; I'm not sure).

CC @lmorchard

**Comment by flodolo** [comment]
> These are all strings in the add-on; which doesn't use l20n, but instead uses the SDK l10n module (which may also behave the same way; I'm not sure).

D'oh, good point. I've unpacked the .xpi and don't see traces of localization, while the add-on created by `npm run package` has a locale folder in it and it seems correctly localized when installed.

**Comment by lmorchard** [comment]
Hmm, [these strings are present in the `.properties` file](https://github.com/mozilla/testpilot/blob/master/locales/en-US/addon.properties) and they were working when we committed that stuff. Could be a build issue, since we moved the file around to get it picked up by Pontoon. Will take a look at CircleCI and see what's up

**Comment by lmorchard** [comment]
Also, running `npm run package` is no longer sufficient to build the add-on - [you also have to first run `npm run addon:locales`](https://github.com/mozilla/testpilot/tree/master/addon#development) to copy over the `.properties` files from the `locales/` directory in the root of the project. [This *should* be happening in CircleCI builds](https://github.com/mozilla/testpilot/blob/master/bin/circleci/build-addon.sh) but could be worth some troubleshooting

**Comment by lmorchard** [comment]
Ahh, I think I know what it is: Stage & prod don't use the CircleCI scripts. 😞 So, we probably just need to tweak the commands in `package.json` to copy the `.properties` files over
