### ISSUE TITLE
Disabled JavaScript warning is not localized

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#1859]
Just noticed looking at the code, but you can verify it by disabling JavaScript in devtools.
https://testpilot.stage.mozaws.net/ and browser set to Italian.

![schermata 2016-11-22 alle 15 19 16](https://cloud.githubusercontent.com/assets/3644868/20527029/0f5a9ee2-b0c7-11e6-9f3c-ab66ca4513d2.png)

**Comment by pdehaan** [comment]
If JavaScript is disabled, I'm not sure if our l20n scripts will work anyways.

**Comment by flodolo** [comment]
Good point, we might need an alternative strategy to localize it, or at least stop asking to localize these strings.

@stasm 
Out of curiosity, have you guys thought of this scenario for l20n web projects?

**Comment by stasm** [comment]
@flodolo L20n can't do anything without JS (at least right now).   Non-JS scenarios aren't supported at all.   Do you think we should have a story for such cases?

**Comment by flodolo** [comment]
> Do you think we should have a story for such cases?

If we want to promote l20n as a tool to localize websites, and not only software, I think we should at least think about it.

**Comment by johngruen** [comment]
@chuckharmston @sevaan and i were talking about this and basically want to just repeat the hard coded string in a bunch of languages. Thinking about adding a l10n string to the en-us file to get localized and then copy/pasting the results into `index.moustache`

**Comment by johngruen** [comment]
@chenmorpheus lets figure out this UI soon

**Comment by ChenMorpheus** [comment]
@johngruen From UX perspective, to prevent any localization issues, I would suggest displaying an icon or illustration as complement to explain the situation here. It'll be perfect if we can have the hard coded string in several languages like what John mentioned above.

**Comment by johngruen** [comment]
I'm going to reboot this issue by adding a string to localization here so that we can pull out local strings to design a good UX here.

**Comment by johngruen** [comment]
I'll just do "Test Pilot requires JavaScript. Sorry about that" we won't be able to link to a localized resource anyway so i think that will be sufficient.

**Comment by johngruen** [comment]
@ChenMorpheus we're going to get the locale strings coming in, when we have a bunch, i'll extract them for you and put them in here. Keep an eye on this ticket.

**Comment by ChenMorpheus** [comment]
@johngruen Got it. We will check if we could provide an icon or illustration as complement then.

**Comment by lmorchard** [comment]
> I'm going to reboot this issue by adding a string to localization here so that we can pull out local strings to design a good UX here.

FWIW, since all localization is done via client-side JS right now, to actually *use* that string will require a sizable reworking of how we build & serve up the site's static pages. 

Main visible thing would be changing URLs so they contain the locale (i.e. `/{locale}/experiments`, etc) - might also want a language selector in the footer, too. Thought we had an issue for all of that, but I can't find it.

**Comment by johngruen** [comment]
@lmorchard, not looking to pass the string into code. I want go through the locales and get he correct translation of the string for our top 10-15 languages then just put all of them directly into the noscript tag.

**Comment by fzzzy** [comment]
@johngruen Excellent plan.

**Comment by meandavejustice** [comment]
Looks like this was accidentally closed by the wording in #2988, reopening

**Comment by lmorchard** [comment]
> not looking to pass the string into code. I want go through the locales and get he correct translation of the string for our top 10-15 languages then just put all of them directly into the noscript tag.

I missed some conversation about that plan earlier in the issue... rather than manually copy/pasting the strings, we should probably roll it into the code that builds the static page on deploy. It's likely that these strings will be updated & added to over time across locales, and it would be nice to pick them up from the FTL files when we deploy.
