### ISSUE TITLE
End phrase dot placed outside the list element in NoMore404s "Your Privacy" section in German locale

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1861]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on a new clean Firefox profile.
- German language was added on top of the list from "Firefox > Options > Content > Language" section.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on NoMore404s experiment card.
3. After redirected to details page, scroll down to the "Your Privacy" section.
4. Observe how the phrase from the 3rd dot ends.  

[Expected result]:
- The phrase ends with a dot on the same row with the last word.

[Actual result]:
- The phrase ends with a dot placed two rows lower than the last word.

![dot outside list element](https://cloud.githubusercontent.com/assets/17258026/20529240/315c86c0-b0d8-11e6-8d1e-1e44d9dc4327.png)

**Comment by flodolo** [comment]
That's an error in the localization that I've just fixed (dot was between two list items). It will be exported within 10 minutes by Pontoon.

**Comment by flodolo** [comment]
Fix: https://github.com/mozilla/testpilot/commit/77913ebdc90f3a9317c8282ea7d243232efc56aa

**Comment by SoftVision-CosminMuntean** [comment]
This issue is fixed on dev server.  Marking it as verified.
