### ISSUE TITLE
Contributor "Noitidart" is not displayed on Min Vid experiment page (on stage)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1862]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on Min Vid experiment card.
3. Observe the "Brought to you by" section.

[Expected result]:
- Noitidart Engineering Contributor is correctly displayed.

[Actual result]:
- Noitidart Engineering Contributor is not displayed.

**Comment by jaredhirsch** [comment]
refs https://github.com/meandavejustice/min-vid/issues/508

**Comment by pdehaan** [comment]
I think that we merged the Noitidart PR (#1843) after we cut the stage release.

Current stage https://testpilot.stage.mozaws.net/__version__ (26fc59eb0798cf3328700076e9e0a94f46dc6a71):

```json
{ "commit": "26fc59eb0798cf3328700076e9e0a94f46dc6a71",
  "version": "2016-11-17-3",
  "source": "https://github.com/mozilla/testpilot" }
```

But we didn't merge https://github.com/mozilla/testpilot/pull/1843 until the 20th: https://github.com/mozilla/testpilot/compare/26fc59e...52a8b31

**Comment by johngruen** [comment]
This will be fixed on next deployment

**Comment by Noitidart** [comment]
Thanks all!! :)
