### ISSUE TITLE
Universal Search is missing from Test Pilot button doorhanger

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1864]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.firefox.com" page.
2. Choose to install Test Pilot add-on.
3. Observe the available experiments cards on the page.
4. Click on the Test Pilot toolbar button and observe the available experiments.

[Expected result]:
- All the available experiments are displayed on both areas.

[Actual result]:
- Universal Search experiment is missing from the doorhanger.

[Notes]:
- Issue is reproducible on all servers.

![us missing](https://cloud.githubusercontent.com/assets/17258026/20536361/6b2bd914-b0f1-11e6-8320-77c97f257052.png)

**Comment by johngruen** [comment]
We're getting rid of the doorhanger so this may be wontfix, but let's keep it open pending graduation schedule.

**Comment by pmespresso** [comment]
Looks like doorhanger was removed #2002. Should this issue be closed?

**Comment by johngruen** [comment]
Oh yeah!
