### ISSUE TITLE
The "Tour" pop up is not displayed if the experiment first enable attempt fails

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1866]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- The "experiments.webapi.testing" boolean pref was manually set to true.
- Test Pilot add-on was previously installed on the above profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on one of the available experiments cards.
3. Disable / disconnect internet connection.
4. Choose to enable the experiment and wait for the error message to appear.
5. Reconnect to the internet and after choose again to enable the experiment.
6. Observe the error message behavior.

[Expected result]:
- Fail to enable error is replaced by the experiment enable confirmation over a green bar.

[Actual result]:
- Fail to enable error message persists even if experiment is successfully enabled.

[Notes]:
- Here is a recording of the issue:

![error persists](https://cloud.githubusercontent.com/assets/17258026/20568427/34a30fd4-b1a5-11e6-93bf-a0b4743269bf.gif)

**Comment by johngruen** [comment]
we should refresh on `navigator.online` changes

**Comment by Softvision-VladBacia** [comment]
After further testing, we observe that the pop up in which the user is informed about the successful installation of the experiment is not displayed if the "fail to enable error message" persists on the page.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy The issue seems to be partially fixed, now the error message is replaced with the successful one after you re-enable internet. But the confirmation pop up with the Tour is not displayed anymore if first enable action fails.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. After the experiment is enabled, the Tour pop-up is correctly displayed.
