### ISSUE TITLE
Badly rendered survey page displayed when first visiting Universal Search completed experiment from doorhanger

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1871]
[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- The "experiments.webapi.testing" boolean pref was manually set to true.
- Test Pilot add-on was previously installed on the above profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click on "Universal Search" experiment card and choose to enable it.
3. Change the PC system date to 1 December 2016.
4. Return to the browser and click the "Test Pilot" toolbar button.
5. Click on the "Universal Search" experiment from the doorhanger.
6. Observe the page behavior.

[Expected result]:
- You are correctly redirected to the Universal Search retirement page.

[Actual result]:
- You are wrongly redirected to a badly rendered survey page for Universal Search.

[Notes]:
- This only happens on the first attempt to access the page.

<img width="1920" alt="us first open after expiration" src="https://cloud.githubusercontent.com/assets/17258026/20606111/97ee48c4-b277-11e6-9c4c-473f000ae469.png">

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible. Tested on dev, stage and production servers using the following link: https://goo.gl/cuxqqf
