### ISSUE TITLE
Update Tracking Protection copy to differentiate it from the Firefox feature

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1875]
@johngruen to provide copy and placement.

**Comment by ckprice** [comment]
Ref: https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#localization

>If the content of a string changes sufficiently that translations of it should be invalidated:
> 
>1. Make sure that this change needs to be done. We rely on volunteer localizers,
>2. If at all possible, wait to make the change until the beginning of a sprint to give localizers time to translate the new string before the next deployment.
>3. Add a new field to the YAML titled `<fieldname>_l10nsuffix`, set to a short string contextualizing the change.

**Comment by ckprice** [comment]
We [hacked together some copy](https://public.etherpad-mozilla.org/p/6rmZFOXtD7) for this to appear above the 'Contributors' section. John is going to open a patch.

**Comment by SoftVision-PaulOiegas** [comment]
Shouldn't this be placed above the contributors section as Cory said ? I see it under the avatars and names of the people. 
It's fine by me, I'm just curious if it's ok.
