### ISSUE TITLE
Add a link to Chuck's Blog post in Universal Search Graduation Report

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1880]

**Comment by johngruen** [comment]
I believe this is the URL...
https://medium.com/mozilla-tech/universal-search-retrospective-b39e1be5d128

@chuckharmston let us know when the content is final and we can add it to the `graduation_report`

**Comment by chuckharmston** [comment]
Still getting edited, but it's close enough that we can do this.
