### ISSUE TITLE
[release] 2016-11-29-1 on stage

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1881]
We're going to get this up on stage for verification targeting a push tomorrow.

We'll be starting with the last deployed tag, [`2016-11-17-3`](https://github.com/mozilla/testpilot/releases/tag/2016-11-17-3), then cherry-pick 

- https://github.com/mozilla/testpilot/commit/1e394f2426347f63673a26a94e4142e8b6ac785e
- https://github.com/mozilla/testpilot/commit/ad196e1a5dbd7ffd2ec0f531d254f08975b0acfa
- https://github.com/mozilla/testpilot/commit/937ba521e7e0cd2a357b9dc737232841b46ba426
- https://github.com/mozilla/testpilot/commit/c3ed2552f943468f370c3f29818fd172f05a5c18

The first is for the extra contributor field, and the last 3 are updating the graduation report.

/edit + a tweak to graduation report and fixing locale and links for contrib extra and adding Chuck's post

- 490d389220016fc29f4dfeb211aae59c7708bfbe
- fcf5178d716c412443ae139f339b918414824f64
- 9cde9cf346bf628cf1c74e36a7dcbe87dc9f87db

**Comment by ckprice** [comment]
Stage tag and push blocked by #1882.

**Comment by ckprice** [comment]
This is up on stage, please review.

https://github.com/mozilla/testpilot/compare/2016-11-17-3...2016-11-29-1

**Comment by ckprice** [comment]
Ah, SV is on holiday tomorrow. May need @pdehaan to step in a verify this for production.

**Comment by pdehaan** [comment]
[stage](https://testpilot.stage.mozaws.net/__version__) and [production](https://testpilot.firefox.com/__version__) both seem to be rocking version **2016-11-29-1**, so I'm thinking this is complete.

```json
{ "commit": "e42d9cb5ec4e75f45fe6123ade507bce14037fea",
  "version": "2016-11-29-1",
  "source": "https://github.com/mozilla/testpilot" }
```
