### ISSUE TITLE
Add experiment tiles to /onboarding page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1887]
Found in https://testpilot.stage.mozaws.net/__version__ (e42d9cb5ec4e75f45fe6123ade507bce14037fea):

```json
{ "commit": "e42d9cb5ec4e75f45fe6123ade507bce14037fea",
  "version": "2016-11-29-1",
  "source": "https://github.com/mozilla/testpilot" }
```

---

Currently the [/onboarding](https://testpilot.stage.mozaws.net/onboarding) page feels like a bit of a dead end. Not sure if we should add the experiments grid to this page, or something to make it a bit more "actionable". You sort of have to either:

(a) Heed the instructions and use the toolbar icon to find experiments.
(b) Click the "Firefox Test Pilot" in the top-left corner to go to the homepage and browse list of experiments.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/20722944/5f24a4b2-b61d-11e6-8b6e-723d3d64c6b1.png)

**Comment by johngruen** [comment]
This page is no longer used. We should remove it, or a/b test it...
