### ISSUE TITLE
Missing lots of experiment info at smaller resolutions

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1888]
Found in https://testpilot.stage.mozaws.net/__version__ (e42d9cb5ec4e75f45fe6123ade507bce14037fea):

```json
{ "commit": "e42d9cb5ec4e75f45fe6123ade507bce14037fea",
  "version": "2016-11-29-1",
  "source": "https://github.com/mozilla/testpilot" }
```

---

We don't seem to be showing any of the useful Version, Changelog, Date, Forum, Contributors info when viewing at a _mobile_-esque resolution.

![Desktop](https://pageshot.net/images/e49fd577-ace5-457b-9fe6-18986d3222fd.png)
**Figure 1:** [Test Pilot](https://pageshot.net/OQ7Tb2hbnWuo7mS5/testpilot.stage.mozaws.net) in "Desktop" breakpoint.

---

![Mobile](https://pageshot.net/images/a28c1d66-743f-4455-aa33-59cb032ed073.png)
**Figure 2:** [Test Pilot](https://pageshot.net/vIRvJpHu2bJFcaax/testpilot.stage.mozaws.net) in "Mobile" breakpoint.

**Comment by johngruen** [comment]
FEATURE NOT BUG!

**Comment by johngruen** [comment]
TODO: let's file an issue about DRY-ing out ExperimentPage and removing duplicate elements
