### ISSUE TITLE
"TypeError: t is null" when disabling an experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1889]
Found in https://testpilot.stage.mozaws.net/__version__ (e42d9cb5ec4e75f45fe6123ade507bce14037fea):

```json
{ "commit": "e42d9cb5ec4e75f45fe6123ade507bce14037fea",
  "version": "2016-11-29-1",
  "source": "https://github.com/mozilla/testpilot"}

```

---

I was testing uninstalling the Universal Search add-on and as soon as the "Vielen Dank!" dialog popped up, my DevTools console spewed "TypeError: t is null" error, citing some error on line 8 of the minimized vendor.ec3d1ad6.js file. I tried tracking that back to some unminimized source. Not sure if we are generating/linking source maps to make debugging minified source easier.

![firefox_test_pilot_-_universal_search](https://cloud.githubusercontent.com/assets/557895/20724941/19783296-b625-11e6-8e04-7a8397f3fcd6.png)

**Comment by johngruen** [comment]
Will investigate pending #1892 sourcemaps

**Comment by dannycoates** [comment]
This is another conflict between l20n and react, like #1712
