### ISSUE TITLE
Add JavaScript sourcemaps in Stage/Production?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1892]
Ref [./frontend/tasks/scripts.js:49-55](https://github.com/mozilla/testpilot/blob/979875a113bee445170f04f49e3d2ab2c575eddf/frontend/tasks/scripts.js#L49-L55):

```js
gulp.task('scripts-misc', () => {
  return gulp.src(config.SRC_PATH + 'scripts/**/*')
    .pipe(gulpif(config.IS_DEBUG, sourcemaps.init({loadMaps: true})))
    .pipe(gulpif(!config.IS_DEBUG, uglify()))
    .pipe(gulpif(config.IS_DEBUG, sourcemaps.write('./')))
    .pipe(gulp.dest(config.DEST_PATH + 'static/scripts'));
});
```

It looks like we may not enable source maps while not in debug mode (where [`IS_DEBUG`](https://github.com/mozilla/testpilot/blob/03061ad53f1f07b1cc8b7a0bfbbedf02ff8075a8/frontend/config.js#L5) is defined as `IS_DEBUG: (process.env.NODE_ENV === 'development')`.

Oddly, I wasn't seeing sourcemaps working on https://testpilot.dev.mozaws.net/ when I tried browsing the app.7e8065e0.js or vendor.ec3d1ad6.js files and formatting the minified code.

https://blog.sentry.io/2015/10/29/debuggable-javascript-with-source-maps.html

**Comment by ghost** [comment]
We need these to add to sentry also https://docs.sentry.io/clients/javascript/sourcemaps/

**Comment by ghost** [comment]
The mysterious "TypeError: e.data.filter is undefined" report in Sentry has now surpassed 1 million reports.  It would be great to get this landed soon.
