### ISSUE TITLE
Filter out any non-directory results when generating dev locale list?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1893]
Probably not worth much effort since this only affects dev/local envs...

In https://github.com/mozilla/testpilot/pull/1878 we auto generated the list of dev locales [`AVAILABLE_LOCALES`](https://github.com/mozilla/testpilot/blob/992cf978d30ea9bab06df1300883c0745b968cd9/frontend/config.js#L9-L13) using `fs.readdirSync('./locales').join(',')`.

Looking at Chuck's screenshot in https://github.com/mozilla/testpilot/pull/1877#pullrequestreview-10561904, it appears that he had a ./locales/.DS_Store file, which automatically gets added to the `availableLanguages` array.

This is pretty crude, and there's probably a much simpler solution:

```js
const fs = require('fs');
const path = require('path');

const folders = readdir('./locales');
console.log(folders); // de,en-US,fr,...

function readdir(base) {
  return fs.readdirSync(base)
    .filter((dir) => fs.statSync(path.join(base, dir)).isDirectory())
    .join(',');
}
```

**Comment by flodolo** [comment]
Looks like there are option to filter that list directly in fs.readdir
http://stackoverflow.com/questions/18973655/how-to-ingnore-hidden-files-in-fs-readdir-result

**Comment by chuckharmston** [comment]
Since we're trying to slow down development on Test Pilot and this doesn't even break anything, I'm going to close this.
