### ISSUE TITLE
Remove "version" numbers from experiment details page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1894]
I'm not sure that displaying a version number adds any "value", especially considering that 4/7 of the experiment pages show the not-latest version number (2/7 are accurate, 1/7 is Universal Search and I can't see a package.json or manifest.json with a version number in the XPI).

| NAME | TxP VERSION | XPI VERSION | 👍 👎 
|----|----:|----:|:--:|
| Activity Stream | 1.1.3 | 1.1.8 | ❌ 
| Min Vid | 0.3.1 | 0.3.3 | ❌ 
| No More 404s | 1.6.0 | 1.6.0 | ✔️ 
| Page Shot | 0.1.2 | 2.6.201611151453 | ❌
| Tab Center | 1.26 | 1.26.0 | ✔️ 
| Tracking Protection | 1.0.1 | 1.1 | ❌ 
| Universal Search | 1.0.6 | [1] | ❓ 

[1] Unable to find package.json or manifest.json for https://s3-us-west-2.amazonaws.com/universal-search/universal-search.xpi.

**Comment by pdehaan** [comment]
Here's my :poop::fire: code for grabbing the /api/experiments.json file, then fetching each experiments XPI file and attempting to parse out the `name` and `version` properties from the {package,manifest}.json file:

```js
const fetch = require('node-fetch');
const jszip = require('jszip');

getXpiUrls('https://testpilot.firefox.com/api/experiments.json')
  .then((xpi_urls) => Promise.all(xpi_urls.map((xpi_url) => getExperimentXpiVersion(xpi_url))))
  .then((results) => results.map(({name='?', version='?', err=''}) => `${err ? err : name + '@' + version}`))
  .then(console.log)
  .catch(console.error);

/**
 * Fetch the /api/experiments.json file.
 * @param  {String} uri Absolute URI to the /api/experiments.json file.
 * @return {Promise}    [description]
 */
function getXpiUrls(uri) {
  return fetch(uri)
    .then((res) => res.json())
    .then((data) => {
      data.results.forEach(({title, version}) => console.log(title, version));
      return data;
    })
    .then(({results}) => results.map(({xpi_url}) => xpi_url));
}

/**
 * Fetch the experiment's XPI file and try extracting the package.json or manifest.json file.
 * @param  {String} uri Absolute URI to the experiment's XPI file.
 * @return {JSON}       The package.json, manifest.json, or dummy Object if
 *                      unable to find package/manifest in ZIP file.
 */
function getExperimentXpiVersion(uri) {
  return fetch(uri)
    .then((res) => res.buffer())
    .then((buffer) => jszip.loadAsync(buffer))
    .then((zip) => {
      const file = zip.file('package.json') || zip.file('manifest.json');
      if (file) {
        return file.async('string')
          .then((data) => JSON.parse(data));
      } else {
        return {err: `Unable to find package.json or manifest.json for ${uri}`};
      }
    });
}
```

**Comment by ghost** [comment]
Although this has great numbers, some guy already filed this. https://github.com/mozilla/testpilot/issues/1523
