### ISSUE TITLE
Python package marionette_client changing name to marionette_harness

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1903]
According to [a recent post on the dev-platform list](https://groups.google.com/forum/#!topic/mozilla.dev.platform/okCSlu2_ZMI), the python `marionette_client` package, which we use in our integration tests, will soon be renamed to `marionette_harness`.

This work is currently tracked on bugzilla ([bug 1320073](https://bugzilla.mozilla.org/show_bug.cgi?id=1320073)), but nobody's mentioned a date yet.

Opening this tracking bug to remind us to update the package once it's released.

**Comment by lmorchard** [comment]
The good-first-bug label is misleading here, since I think we're in the midst of overhauling the integration tests altogether.

**Comment by fzzzy** [comment]
This was fixed by https://github.com/mozilla/testpilot/pull/2380
