### ISSUE TITLE
Make Discourse more visible on TxP site

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1905]
The discourse instance has migrated from Persona to auth0, and has been moved to a larger AWS instance. It's ready for more traffic.

Let's figure out the best way to integrate Discourse more deeply into the site and improve discoverability.

**Comment by johngruen** [comment]
@6a68 first step we're going to take (which will close this issue) is to change the title for the `Discourse` Link to `Discuss {experiment.name}`. @sevaan is working a larger plan that we will track in Trello. I'll link to that card when it's complete.

**Comment by johngruen** [comment]
@6a68 added this trello item to track progress

https://trello.com/c/eEod37bN/43-txp-43-make-direct-connection-between-test-pilot-builders-and-users-more-accessible
