### ISSUE TITLE
Data collection "Learn more" text link from Privacy section looses the URL underneath and localization at small viewport

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1907]
[Notes]:
- @flodolo It seams that the privacy section issue was not entirely fixed in #1860. The text link about data collection underneath has the same behavior and also looses the URL under it.

[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on a new clean Firefox profile.
- A localization language other than English was added on top of the list (eg German), from "Firefox > Options > Content > Language" section.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on one of the available experiments cards.
3. After redirected, scroll down to the page and observe the "You can learn more about the data collection for <experiment_name> here." text link under "Your Privacy" section.
4. Resize the browser window until mobile portrait view size is reproduced and observe the text link again.
5. Click the text link and observe the page behavior.

[Expected result]:
- Step 3: The text link is correctly displayed in selected language.
- Step 4: The browser window size does not affect the text link.
- Step 5: You are redirected to the data collection details page of each experiment.

[Actual result]:
- Step 3: The text link is correctly displayed in selected language.
- Step 4: After resize the text link looses the localization, displaying the string in English.
- Step 5: The text link has no URL underneath and clicking it will only select the string eventually.

[Additional notes]:
- Here is a screen recording of the issue: https://goo.gl/Ce7PLN .

**Comment by johngruen** [comment]
I think my PR is solid, just needs approval

**Comment by SoftVision-PaulOiegas** [comment]
tested with English, German and Spanish. Bulletproof ! 👍
