### ISSUE TITLE
[Enhancement] Active and past experiments cards should have consistent size in both sections 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1908]
[Notes]:
- I know the cards are dynamically sized depending on largest experiment description. This is ok and much better than having a fixed size and truncate longer descriptions. But couldn't we scale also the past experiments cards depending on the largest card from active ones to have consistency ? Looks a bit odd this way.

[Affected versions]:
- Firefox 50.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on a new clean Firefox profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Observe the available active experiments cards dimensions.
3. Scroll down on the page and click on the "View Past Experiments" button.
4. Observe past experiments cards dimensions.

[Expected result]:
- Cards from both active and past experiments areas have the same dimension (~268 x 406px)

[Actual result]:
- Step 2: Active experiments cards dimensions are ~268 x 406px.
- Step 4: Past experiments cards dimensions are ~268 x 309px

![cards size](https://cloud.githubusercontent.com/assets/17258026/20934478/f7c8706a-bbe3-11e6-8607-1ed167ae8222.png)

**Comment by johngruen** [comment]
Using flexbox here to flow box height to tallest in a given row. WONTFIX-ing this since the design is intentional.
