### ISSUE TITLE
[Enhancement] We should have more consistent date formats and separators for locales that use the same format

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1911]
[Notes]:
- Based on Peter's observation from issue #1823, I think we should have a more consistent way to localize the displayed dates. I've verified 5 European languages locales and on all 5, the date is differently displayed and we use 3 types of separators.  
- There could be other differences too, I've only tested about 8 locales. If we decide to do this, we should apply a general fix for all the locales we have.

[Affected versions]:
- Firefox 50.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on a new clean Firefox profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on one of the available experiments cards and observe the "Last update" date format on the left side of the page.
3. From "Firefox > Options > Content > Language" section, add one of the following languages: German, Spanish, Dutch, Swedish or Hungarian at the top of the list.
4. Return to experiment page, refresh it and observe again the date format.
5. Repeat steps 3 and 4 for the rest of the remaining languages.

[Expected result]:
- Similar date format and separators are displayed for all the above European locales.

[Actual result]:
- German: DD.M or MM.YYYY
- Spanish: DD/M or MM/YYYY
- Dutch: DD-M or MM-YYYY
- Swedish: YYYY-MM-DD
- Hungarian: YYYY.MM.DD.

[Additional notes]:
- Here is a Wikipedia page that contains used formats for most of the countries https://goo.gl/88O5jf.

![date localization](https://cloud.githubusercontent.com/assets/17258026/20975822/4caccb9c-bca9-11e6-8fe2-64defd95cdcb.png)

**Comment by flodolo** [comment]
CLDR is a better source of information
http://www.unicode.org/cldr/charts/30/by_type/date_&_time.gregorian.html#57dac0d1b36c1261

Also, we shouldn't expect all languages to look the same, just to use a consistent format (e.g. dd.mm.yyyy, whatever that turns out to be in the language).

**Comment by johngruen** [comment]
Feature not bug!
