### ISSUE TITLE
Share button for testpilot is not almost unvisible in dark developer theme

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#1913]
While we are in dark developer theme in Firefox, the share button for testpilot is almost invisible. A different color can be easy in eyes and easily noticeable.

This issue was seen in latest Nightly 53

Attachment :     https://drive.google.com/open?id=0B75_JfziYeofWmFmUUV6NTB4Mms

**Comment by flodolo** [comment]
I'm not aware of any share button in Test Pilot. I might be wrong, but I also don't remember any experiment that adds that. Are you sure it's not added by a different add-on?

**Comment by ghost** [comment]
I am sure about this button being a result of tespilot. This button got visible when I enabled Activity Stream⁩ . You can see that screen shot from my previous comment.

**Comment by flodolo** [comment]
Then you should file the issue in Activity Stream ;-)
https://github.com/mozilla/activity-stream/issues/new

I didn't remember that icon when I tried, thanks for confirming it's that experiment adding it.

**Comment by SoftVision-PaulOiegas** [comment]
Closing this as the issue was cloned in AS repo (https://github.com/mozilla/activity-stream/issues/1857).
