### ISSUE TITLE
Two of the prefs added at the installation are kept after uninstall

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1915]
[Notes]:
- Not sure if this is an issue or intended but judging on the fact that we previously said that we want to erase anything related to Test Pilot from users PC's, this could be one.

[Affected versions]:
- Firefox 50.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A new clean Firefox profile was previously created.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to navigate to "about:config page.
2. Accept the risk and after redirected to the preferences page, search for "testpilot" prefs.
3. Open a new tab and navigate to "https://testpilot.firefox.com" page. 
4. Choose to install Test Pilot add-on and after installed, look again on the "about:config" page for related prefs.
5. Return to Test Pilot tab and choose to uninstall the add-on from top right "Settings" button.
6. After uninstalled, return to "about:config" tab and refresh the page.
7. Search again for "testpilot" related prefs.

[Expected result]:
- Step 2: No "testpilot" related prefs are found.
- Step 4: Several "testpilot' related prefs were added after installation.
- Step 7: All the "testpilot" related prefs are removed after uninstall.

[Actual result]:
- Step 2: No "testpilot" related prefs are found.
- Step 4: Several "testpilot' related prefs were added after installation.
- Step 7: Two of the "testpilot" related tabs are still kept after uninstall (browser.uiCustomization.state and testpilot.env).

[Additional notes]:
- Here is a screen recording of the issue: https://goo.gl/Do2H8f

**Comment by johngruen** [comment]
we should keep testpilot.env, @SoftVision-PaulOiegas we believe that browser.uiCustomization.state is set by dev edition, and we think should not be changed if any add-on is uninstalled. Can you confirm?

**Comment by fzzzy** [comment]
testpilot.env is only set manually while developing

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen - I've tested this on latest Firefox release v50.1.0 and not on Dev edition. By default the release has "browser.uiCustomization.state" pref with "user set" status even on a new clean profile and contains the next string:

"{"placements":{"PanelUI-contents":["edit-controls","zoom-controls","new-window-button","privatebrowsing-button","save-page-button","print-button","history-panelmenu","fullscreen-button","find-button","preferences-button","add-ons-button","developer-button","sync-button"],"addon-bar":["addonbar-closebutton","status-bar"],"PersonalToolbar":["personal-bookmarks"],"nav-bar":["urlbar-container","search-container","bookmarks-menu-button","downloads-button","home-button","pocket-button"],"TabsToolbar":["tabbrowser-tabs","new-tab-button","alltabs-button"],"toolbar-menubar":["menubar-items"]},"seen":["pocket-button","developer-button"],"dirtyAreaCache":["PersonalToolbar","nav-bar","TabsToolbar","toolbar-menubar"],"currentVersion":6,"newElementCount":0}"

After Installing Test Pilot, this string is updated and ' "toggle-button--testpilot-addon-testpilot-link"], ' string is added twice in it. One after the "pocket" part and one before "dirtyAreaCache". 
Uninstalling Test Pilot does not removes these string parts.

If this is intended, I'm fine with it. As I've said in the beginning of the issue, this was more as a double check only.

**Comment by ghost** [comment]
Confirmed:  we don't want to touch this.  Please reopen if the actual UI is weird looking.  Thanks!
