### ISSUE TITLE
Min-Vid cannot be enabled on latest Test Pilot version

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#1919]
[Affected versions]:
- Firefox 50.1.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on the profile.
- testpilot.env is set to "stage" in about:config.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on Min-Vid experiment and choose to "Enable" it.
3. Observe the browser behavior.

[Expected result]:
- The experiment is successfully enabled.

[Actual result]:
- The experiment could not be enabled. "Uh oh. Min-Vid could not be enabled ..." error is displayed.

[Notes]:
- Here are the console errors when trying to enable the experiment:
![console output](https://cloud.githubusercontent.com/assets/18304511/21258818/6d56741c-c387-11e6-900b-d39344bee7df.PNG)

**Comment by johngruen** [comment]
@SoftVision-CiprianMuresan this should block release of stage to prod

**Comment by johngruen** [comment]
I'll check this in prod as well

**Comment by johngruen** [comment]
Installs in prod

**Comment by meandavejustice** [comment]
@johngruen digging into this

**Comment by meandavejustice** [comment]
This is what I'm getting in the console.
```
1481917936539	addons.xpi	DEBUG	Download started for https://testpilot.firefox.com/files/@min-vid/latest to file /tmp/tmp-2zh.xpi
1481917936548	addons.xpi	DEBUG	Download of https://testpilot.firefox.com/files/@min-vid/latest completed.
1481917936550	addons.xpi	WARN	Download of https://testpilot.firefox.com/files/@min-vid/latest failed: Downloaded file hash (fa1b9ae302d3fab505731abd497abd0686958a9df2842eaa7b4ba5e0e4da475c) did not match provided hash ()
1481917936551	addons.xpi	DEBUG	downloadFailed: removing temp file for https://testpilot.firefox.com/files/@min-vid/latest
1481917936552	addons.xpi	DEBUG	removeTemporaryFile: https://testpilot.firefox.com/files/@min-vid/latest removing temp file /tmp/tmp-2zh.xpi
```
The file hash did not match message is particularly suspect..

**Comment by chuckharmston** [comment]
@meandavejustice This is likely because the [`X-Target-Digest`](https://github.com/mozilla/testpilot/issues/1537) header is not correctly being set for the new version. Sounds like it's an issue with the uploading script?

**Comment by meandavejustice** [comment]
@chuckharmston thanks chuck, I was digging in amo issues, hadn't come across that yet. Lemme see if I can figure out where @clouserw's upload script is to verify.

**Comment by meandavejustice** [comment]
@chuckharmston could we manually go into s3 and set that and verify just to get this out today?

**Comment by chuckharmston** [comment]
```
$ curl -I https://testpilot.firefox.com/files/@min-vid/latest | grep x-target-digest
x-target-digest: sha256:
```

The header on this redirect should be set to `sha256:fa1b9ae302d3fab505731abd497abd0686958a9df2842eaa7b4ba5e0e4da475c`. It looks like this is due to a bug in the new deployment script.

@relud or @mostlygeek, any chance you could manually fix this for now until we find that bug?

**Comment by relud** [comment]
this was fixed in the build script, but no new builds had been run since the fix. I started a new build and now this lgtm

**Comment by johngruen** [comment]
Thanks @relud!

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the stage server.
