### ISSUE TITLE
[Enhancement] We should display the localized add-on name if available on compatibility notification

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1924]
[Notes]:
- This is a localization improvement suggestion.
- Since some of the add-ons names are automatically localized depending on Firefox build used, and displayed as so in "about:addons/extensions" page after installation, it would be nice to display them as localized in our messages.
- This could help the foreign users to easily find the add-ons that raise compatibility issues.

[Affected versions]:
- Firefox 50.1.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A German (de) localized version of Firefox browser was previously downloaded.
- Add the "testpilot.env" pref and set it to "dev" in about:config.

[Steps to reproduce]:
1. Open the localized browser and navigate to "https://testpilot.stage.mozaws.net" page.
2. Install Test Pilot add-on and after on a new tab, navigate to "about:addons" page 
3. From "Extensions" section, search for "Tabgruppen" (en: Tab Groups) add-on and install it.
4. Return to Test Pilot tab and click on "Tab Center" experiment card.
5. Observe the name of the add-on from the compatibility notification displayed on top of the page.

[Expected result]:
- The add-on name is correctly displayed localized if available on the browser language.

[Actual result]:
- The English version of the add-on name is displayed even if in about:addons page the localized name is displayed.

[Additional Notes]:
![addons not localized](https://cloud.githubusercontent.com/assets/17258026/21355209/cca4eeac-c6d5-11e6-80e1-34d3144944e2.png)

**Comment by ghost** [comment]
We'd rather not have to maintain localizations here, so I'm going to wontfix this.  If there are two very popular localizations we can put them both, worst case scenario.
