### ISSUE TITLE
Please help me get the RSS feed of websites below the focus boxes to come back.

### ISSUE THREAD

**Issue by SherylBratcher** [mozilla/testpilot#1926]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:     https://github.com/mozilla/universal-search/issues/new
- No More 404s:         https://github.com/internetarchive/FirefoxNoMore404s/issues
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Tracking Protection:  https://github.com/mozilla/blok/issues/new

**Comment by johngruen** [comment]
Hey @SherylBratcher not sure exactly what you mean here. could you provide a bit more detail?

**Comment by meandavejustice** [comment]
Sounds like this is a suggestion for a testpilot experiment, is that right @SherylBratcher ?

**Comment by SoftVision-CiprianMuresan** [comment]
Closing this issue in favor of the one opened in the [Activity Stream repo](https://github.com/mozilla/activity-stream/issues/1889).

**Comment by SherylBratcher** [comment]
Yes I've used Activity stream for a while.

When I first installed it I had the most visited focus boxes on top,
underneath them I had a few (3) Hi-lite focus boxes and then under that was
a full history feed.

The history stream has disappeared and I now have 9 Hi-lite boxes...

I want the history stream back and less Hi-lite boxes...PLEASE!!!!!! It's
why I installed the program in the first place and extremely useful and
saves me a lot of time during the day!

Also please include my main email address so I don't miss emails...The only
reason I saw this is because a clients Firewall is blocking my work emails
and I have to use Gmail to get thru!

Thank you

Sheryl Bratcher.
sbratcher@americancreative.com

**Comment by SherylBratcher** [comment]
I am confused...What am I supposed to be doing?

My problem has not been resolved

please help

**Comment by SoftVision-CiprianMuresan** [comment]
@SherylBratcher, all comments should be redirected towards the issue opened in the Activity Stream repo. https://github.com/mozilla/activity-stream/issues/1889
