### ISSUE TITLE
The "Mozilla" name misses the URL underneath it in "About Test Pilot" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1928]
[Notes]:
- This seems to be a regression caused by localization.

[Affected versions]:
- Firefox 50.1.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to https://testpilot.firefox.com/about page.
2. Observe the "Mozilla" name from first phrase.

[Expected result]:
- Mozilla name has an URL underneath it that redirects the user to https://www.mozilla.org page.

[Actual result]:
- Mozilla name has no URL underneath it.

![missing url](https://cloud.githubusercontent.com/assets/17258026/21385028/904a5668-c775-11e6-8170-50c9ee3e4496.png)

**Comment by flodolo** [comment]
> This seems to be a regression caused by localization.

We don't localize that page
https://github.com/mozilla/testpilot/blob/352255e8879df2b0380349d65ecb40dc297becfa/compiled-templates/about/en-US.md

**Comment by SoftVision-PaulOiegas** [comment]
Well, Chuck investigated the issue yesterday and told me this on IRC:
"chuck: looks like it was lost when we added localization to that page. The history on that file is pretty clean: github.com/mozilla/testpilot/commi…/compiled-templates/about/en-US.md".

Haven't checked further, just logged it. But I think the link was there in the beginning. Otherwise I wouldn't be writing a test for it.

**Comment by flodolo** [comment]
> But I think the link was there in the beginning. Otherwise I wouldn't be writing a test for it.

I don't know about that. As you noticed the link was never there on the markdown file, so I guess it was lost in the conversion.

That file was created to enable localization, but we never found a way to localize it (I think there's an issue open about that).

**Comment by SoftVision-PaulOiegas** [comment]
I may have wrongly expressed my thoughts, sorry about that. 😃 I wanted to say that the link was there when the page was first implemented, not when the file was created to enable localization. I think Chuck was saying the same thing. And yes, probably it was lost in the conversion.

**Comment by ghost** [comment]
Thanks for filing but we don't need to link this term.
