### ISSUE TITLE
Test Pilot is not automatically updated, causing enabling loop on all experiments 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1940]
[Notes]:
- Sometimes Test Pilot add-on is not updated even if the user tries to manually update. See this issue: https://goo.gl/dhdILV.
- Another similar issue: [Tab Center 856](https://github.com/bwinton/TabCenter/issues/856)
- Here is my Firefox profile with an old Test Pilot version installed: https://goo.gl/OHwfG3

[Affected versions]:
- Firefox 50.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have an older version of Test Pilot installed on a profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.firefox.com.
2. Click on an available experiment and enable it.
3. Observe the browser behavior.
 
[Expected result]:
- The experiment is successfully enabled. 

[Actual result]:
- The experiment is stuck in the enabling state.

[Additional Notes]:
- Here is a screen recording with the issue: https://goo.gl/sOA3AJ

**Comment by jaredhirsch** [comment]
This seems really bad. I can take a look today.

**Comment by dannycoates** [comment]
I bet this is because the version in package.json hasn't been updated

**Comment by jaredhirsch** [comment]
@dannycoates wow, that's really bad! I guess AMO disallows .xpi files with duplicate version numbers, but since we're self-hosting, nothing prevented this from happening.

we should make a pre-release checklist for the addon to prevent future releases with a stale version number, and make sure this is something QA adds to their test plan, too (cc @SoftVision-CosminMuntean ).

I"ll go ahead and just bump the version number now.

_edited to tag the bug filer, didn't notice it was Cosmin from SV :blush:_

**Comment by lmorchard** [comment]
Hmm, yeah, this probably gets masked as an issue on dev - because on dev we embed a short git commit ID in the version for signing, and so the version technically changes with every merge. But, for prod, just the bare version is used.

**Comment by dannycoates** [comment]
So there's one commit before today to the addon after 0.9.1 that is in the 2016-12-15 tag:

https://github.com/mozilla/testpilot/commit/01c07d24dafc13a692e4445047a17b1526bd1697

Updating the addon version on each release *is* an issue, but I don't yet see how it relates at all to experiments not being able to enable in this case.

/me keeps looking

**Comment by dannycoates** [comment]
Well, the addon from the 2016-11-29-1 tag certainly doesn't work with the current site, while HEAD does, so bumping the version should indeed fix it. If we want to know **why** it'll take some more digging.

**Comment by SoftVision-CosminMuntean** [comment]
I can no longer reproduce this issue. I have 4 different profiles with an old Test Pilot add-on installed and the add-on was automatically updated after a couple minutes to the latest version (0.9.2-dev-78214f8). Marking as verified.
