### ISSUE TITLE
Experiment page shows other experiments at bottom only if addon is not installed

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1946]
Maybe this is intentional and I've just missed something.

Mac OS 10.12.2 / Dev Edition 52.0a2 (2016-12-19) (64-bit)

If the TxP addon is not installed, each experiment page shows a list of the other available experiments between the description and footer.

If the TxP addon is installed, the other experiments module is hidden.

Is this intentional?

**Comment by SoftVision-PaulOiegas** [comment]
Same thing was discussed [here #1596](https://github.com/mozilla/testpilot/issues/1596) but no result. I liked the idea too...

**Comment by johngruen** [comment]
There's no great reason why experiments aren't displayed for installed users, but we might still want to sit on this one while we figure out the UX for getting rid of the doorhanger.

**Comment by johngruen** [comment]
lets show this view at the bottom of all experiment pages!

**Comment by ghost** [comment]
I think this is going away with the new design in txp-36

**Comment by ghost** [comment]
Good idea @wresuolc!  Let's just get rid of this code

**Comment by meandavejustice** [comment]
https://trello.com/c/zkhDk6Yw/36-txp-36%3A-install-experiments-directly-from-the-home-page

**Comment by meandavejustice** [comment]
@wresuolc To clarify, do we want to get rid of the restriction/filtering of experiments not shown when the addon is installed? or stop showing experiments at the bottom of the page all together? (wasn't totally clear in the docs around TxP-36 to me).

**Comment by fzzzy** [comment]
Let's just simplify the experiment page and remove the other experiment list. The home page has the list of experiments. Clicking on the logo at the top of every page takes the user to the home page.

**Comment by fzzzy** [comment]
John wants to keep them, so I am just going to make them show up no matter whether or not the add-on is installed.

**Comment by SoftVision-PaulOiegas** [comment]
Well, for sure they now appear on every experiment page. But @johngruen I wonder, do we want them to be displayed also on past experiments pages ? Right now, they are.
