### ISSUE TITLE
"&nbsp;" text in tooltip for star ratings

### ISSUE THREAD

**Issue by nicholasbishop** [mozilla/testpilot#1947]
On the "give feedback" page there is a required star rating. The tooltip for each star has some accidental HTML; it reads like this: `&nbsp; &nbsp; 2 / 5`

**Comment by meandavejustice** [comment]
![txp-bad-tooltip-survey](https://cloud.githubusercontent.com/assets/1844554/21458810/8d26804a-c907-11e6-8da6-16443f08ab40.png)

**Comment by ghost** [comment]
@rayborn - any ideas here?

**Comment by ghost** [comment]
Good catch, fixed.  (SurveyGizmo doesn't like blank values in the question type that we used, I inserted "<Experiment Name> Rating" instead).

@wresuolc - can you close this?

**Comment by ghost** [comment]
thanks
