### ISSUE TITLE
Unclear instructions for providing feedback on Test Pilot

### ISSUE THREAD

**Issue by nicholasbishop** [mozilla/testpilot#1948]
On https://testpilot.firefox.com, click the Settings button, then "Discuss Test Pilot". In the pop-up dialog the second paragraph says: "If you don't want to create an account, you can always leave feedback through Test Pilot." I don't understand what this means though. The Test Pilot UI seems to allow me to give feedback about an individual pilot, but I didn't see a way to provide general feedback for Test Pilot.

**Comment by johngruen** [comment]
We should just remove the modal and go straight to Discourse
