### ISSUE TITLE
Multi-line textbox on the pilot feedback page should be larger by default

### ISSUE THREAD

**Issue by nicholasbishop** [mozilla/testpilot#1949]
On the feedback pages (e.g. https://qsurvey.mozilla.com/s3/tab-center) there is a multi-line text box. The default box size is quite small for me (Firefox 50.1.0 / Linux / High DPI), roughly 40 characters wide by six lines tall. It is indented a bit on the left and does not scale with the page width. It does have the resize-grippy thing in the bottom right, but if you continue on to page 2 of the survey, then go back to page 1, the size is reset.

**Comment by ghost** [comment]
Can you give a screenshot?  I don't see a textbox there.

**Comment by nicholasbishop** [comment]
Huh, I don't either anymore. The feedback page looks way different now, so I guess an update got deployed? I guess we can close this issue for now, if I see it again I'll be sure to include a screenshot next time.
