### ISSUE TITLE
Allow experiments to load multiple add-ons

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot#1953]
For our [Containers Test Pilot](https://github.com/mozilla/testpilot-containers) experiment, we have built:

* A [WebExtension Experiment](https://webextensions-experiments.readthedocs.io/en/latest/index.html) add-on to provide a `browser.contextualIdentity` API
* A WebExtension add-on that uses `browser.contextualIdentity` to provide a new UI for users to manage their containers

So, we need Test Pilot to load/install both of the add-ons for the experiment to work.

Right now, we've got a directory - `webextension-experiment` - in our repo. I'm zip'ing it up into an `.xpi` and installing it, and then installing the WebExtension. That seems to work. Not sure if/how the Test Pilot add-on could automate that?

**Comment by jaredhirsch** [comment]
We'll soon be changing the Test Pilot install flow to let users install experiments with one click, and install the TxP addon at the same time, if it's not already installed.

This work is [spec'd on Trello](https://trello.com/c/zkhDk6Yw/36-txp-36-install-experiments-directly) and some bugs have been filed as [project TxP-36](https://github.com/mozilla/testpilot/projects/7).

It seems like this issue fits naturally into that work.

**Comment by ghost** [comment]
Why wouldn't this be contained in the experiment as a multi-item packaage (https://developer.mozilla.org/en-US/docs/Multiple_Item_Packaging) or as the add-on installing a second add-on itself (on startup, or something).

Additionally, are you aware that webextension experiments only run in nightly and beta (I think?  definitely not release)

**Comment by groovecoder** [comment]
Ah, multi-item packaging is new to me ... though I've been avoiding as much old-school add-on tech (`install.rdf`) as possible.

And a couple days ago I realized type 256 add-ons won't be in Release until March, so we're moving our experiment code back into the SDK code-base.

**Comment by ghost** [comment]
Sounds good
