### ISSUE TITLE
Allow experiment sections like Measurements to be split in multiple strings

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#1960]
#1811 is about splitting existing strings in FTL files in multiple strings, but I don't think there's an issue on file to allow a section to use multiple strings.

Consider for example the Measurements string in #1957. The change to break that strings while localizing is way too high, given the size and amount of markup present.

Each paragraph's content (without markup) and bullet item (again, without markup) should be in a separate string.

**Comment by clouserw** [comment]
This was fixed in #2048
