### ISSUE TITLE
The DE localization restricted experiments are still available in Test Pilot doorhanger 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1961]
[Notes]:
- The doorhanger will be removed eventually by #1922, but until then maybe we should not display the experiments restricted for some locales.

[Affected versions]:
- Firefox 50.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Install or extract a German Firefox build for this issue.
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open the DE Firefox build with the profile from prerequisites.
2. Navigate to "https://testpilot.dev.mozaws.net" page and observe the available experiments.
3. Click on the Test Pilot icon from browser tooblar.
4. Observe the available experiments.

[Expected result]:
The DE localization restricted experiments are not displayed on the Test Pilot page or in doorhanger.

[Actual result]:
Step 2. The restricted experiments are not displayed on the page.
Step 4. Activity Stream, Tracking Protection and NoMore 404s experiments are still displayed in doorhanger.

[Additional Notes]:
- Vice versa, if other build is used than DE, Cliqz is available in Test Pilot doorhanger.
- The "New" badge is also displayed for Cliqz experiment on other locales than DE.
- Here is a screenrecording using Firefox DE build: https://goo.gl/TuwaO4.
- Here is a screenrecording using Firefox EN build: https://goo.gl/1jg4kX.

**Comment by ckprice** [comment]
Blocks #1968

**Comment by jaredhirsch** [comment]
I'll work on this today

**Comment by johngruen** [comment]
Thanks @6a68!

**Comment by johngruen** [comment]
@6a68 #1966 is a hop skip and jump away from this one if you're feeling interested in poking at that too

**Comment by jaredhirsch** [comment]
@johngruen Cool :+1: I'll slip in a fix for #1966 if it's easy to do

**Comment by jaredhirsch** [comment]
So, while I think it's a little weird to filter on just the locale part of just the user's first preferred language (i.e. the first two letters of `navigator.language`), rather than filter on all the listings in `navigator.languages`, I'm going to stick with that approach, so that the doorhanger results match the results shown by the site. For background, see https://github.com/mozilla/testpilot/pull/1686#discussion_r85161498 as well as #1602.
