### ISSUE TITLE
Make modals on Test Pilot site consistent with tour UI styling

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#1962]
Last year we updated the tour UI for experiments. It looks like this now: 

![tour ui](https://cloud.githubusercontent.com/assets/473531/21649944/6105b4b8-d271-11e6-9b5f-3aa1b7a57a5b.png)

However, we did not update some of the other modals used on the Test Pilot site. They occur when a user…  

- ...installs Test Pilot

<img width="509" alt="screen shot 2017-01-04 at 10 08 54 am" src="https://cloud.githubusercontent.com/assets/473531/21650011/9d33fca6-d271-11e6-8f2c-126e6a390baf.png">

- ...clicks on "Discuss Test Pilot" in the settings menu

<img width="514" alt="discuss test pilot" src="https://cloud.githubusercontent.com/assets/473531/21650070/d70db0f2-d271-11e6-904a-63c2016b69da.png">

- ...disables an experiment

<img width="510" alt="screen shot 2017-01-04 at 10 07 20 am" src="https://cloud.githubusercontent.com/assets/473531/21650110/ef7b6710-d271-11e6-9ee6-da93c50533ee.png">

These should be updated to match the new tour UI.

To be fixed:

- Header row should match height of experiment tour UI
- Header font size should match experiment tour UI
- Close button in header row, instead of Skip/Close test link at bottom of modal
- White border around window and header row
- Text alignment on Discuss Test Pilot and Disabled Experiment modals

So instead of looking like they do now, they should look like this:

- After installing Test Pilot **(center-aligned text)**

![welcome](https://cloud.githubusercontent.com/assets/473531/21650146/0ba82fea-d272-11e6-8c60-2af0d2e6fd9c.png)

- "Discuss Test Pilot" in the settings menu **(left-aligned text)**

![just one second](https://cloud.githubusercontent.com/assets/473531/21650155/107856ee-d272-11e6-9773-c80a00d1c800.png)

Note: I also removed the "(We really read this stuff)" line from above.

- After disabling an experiment **(left-aligned text)**

![thank you](https://cloud.githubusercontent.com/assets/473531/21650158/14b23090-d272-11e6-90bb-be019df3eabd.png)

Here's the spec:

![spec](https://cloud.githubusercontent.com/assets/473531/21652013/e5445bd8-d278-11e6-9deb-c518d80f3023.png)

**Comment by pdehaan** [comment]
@sevaan Why the inconsistent center-vs-left alignment on the "Welcome to Test Pilot" dialog versus the other two left aligned panels?

**Comment by sevaan** [comment]
I hemmed and hawed on this one. Visually it looked off having the larger chunks of text centered; it just didn't parse well, however the one sentence by itself looked better centered to me than left-aligned.

Maybe it's better it's all left-aligned for completely consistency, as you mentioned. I'm okay with that. Let's do it.

![welcome](https://cloud.githubusercontent.com/assets/473531/21656900/0e0f9af4-d28e-11e6-87e2-1b2c6a0f4ced.png)

**Comment by pdehaan** [comment]
Bonus modal:

![firefox_test_pilot_-_cliqz](https://cloud.githubusercontent.com/assets/557895/21658398/53d9b9b0-d27b-11e6-92c5-788a8dce830f.png)

**Comment by pdehaan** [comment]
Other random observations.
The "Uninstall" dialog calls them "active tests" versus all the other dialogs which refers to them as "experiments".

Also, I wonder if removing the "Cancel", "Close", and "Skip" links in favor of the less adjacent "X" button in the upper-right corner will have an increase in conversions (and people uninstalling Test Pilot since it may appear like "Proceed" is the only option). But I don't have any evidence or information on what other services do, if they have Yes/No buttons for everything, or rely on the user explicitly closing a dialog via the "X" to opt-out of a dialog.

**Comment by sevaan** [comment]
And here I thought I clicked on everything.

Same rules as the other modals, except for the red colour.

![uninstall](https://cloud.githubusercontent.com/assets/473531/21658667/79eaa654-d295-11e6-964f-4a07a4dbea6c.png)

I upped the font size of the "To opt out of email updates" text to 13px instead of 12, to eliminate the orphaned word (at least for EN) and overall I think it's a bit better balanced with the text above it.

**Comment by sevaan** [comment]
@pdehaan Good thoughts. For the most part, the increased conversion is good as it elicits more feedback and comments, hopefully. As for the uninstall modal, to see that a user really has to seek it out if they explicitly want to remove TxP anyway, so I don't think at that point seeing the listed options really matters. 

Good catches on the text as well. @johngruen Should we use this an an opportunity to do some strings reviews? Who would look at them? Michelle?

**Comment by johngruen** [comment]
@sevaan i think michelle has seen all of these, but you can throw this stuff her way if you want.
