### ISSUE TITLE
Tour modal incorrectly reports experiment as enabled

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1965]
Found in https://testpilot.dev.mozaws.net/__version__ (94fe4f8334bd81f151e49c2ecfb4f7f4b8150885):

```json
{ "commit": "94fe4f8334bd81f151e49c2ecfb4f7f4b8150885",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/2389" }
```

---

### Steps to reproduce:
1. Install test pilot add-on and select Cliqz from the add-on toolbar icon. (see https://testpilot.dev.mozaws.net/experiments/cliqz)
2. Try enabling the experiment (I'm using en-US, en locales and have Activity Stream installed).
3. Installation fails with a banner of "Uh oh. Cliqz could not be enabled. Try again later."
4. Click the "Launch Tour" link in the left column on the experiment page.

### Actual results:
Even though the experiment didn't successfully install, the tour modal heading says "Cliqz enabled!" even though it didn't and isn't.

### Expected results:
No clue. Technically the user can get into a case where they don't even try enabling the experiment, but wish to display the tour, so the heading can be a bit misleading. But that's an uber-nit.

---

![firefox_test_pilot_-_cliqz](https://cloud.githubusercontent.com/assets/557895/21658283/cbc5c03c-d27a-11e6-86db-67c2b80d027a.png)

**Comment by johngruen** [comment]
@pdehaan i am unable to repro, anything in your console giving hints? also what version of FF are you in?

**Comment by pdehaan** [comment]
@johngruen Which part aren't you repro-ing? The error when trying to enable the add-on, or the tour modal dialog saying "Cliqz enabled!"?

Actually, I was just able to enable the CLIQZ add-on via Test Pilot. Odd. Seems to be [a slightly older] Cliqz Test Pilot 5.10.3 (I think Panos just sent out an unsigned 5.11.1). Current Test Pilot version flags itself as "Cliqz Test Pilot could not be verified for use in Nightly and has been disabled." in about:addons.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/21660136/078bc032-d283-11e6-97e1-0ce94c4ebc8e.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/21660145/11a01028-d283-11e6-9d96-fc51cc2eedbc.png)

**Comment by SoftVision-PaulOiegas** [comment]
Well, I hammered it with all sorts of extreme scenarios and couldn't brake it. It even works with internet down and manual disables. 😄 
I might be a bit rusty after my long PTO but I think it works well enough for now. In case we'll find some cases uncovered, we'll log something new.
