### ISSUE TITLE
`launch_date` doesn't hide experiments in the doorhanger, goes to 404

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1966]
STR:

1. Set `launch_date` in YAML for some time in the future
2. Open door hanger

Expected:

The experiment is not shown.

Actual:

The experiment appears, and if it's new, the "NEW" badge shows on the icon. Clicking on the experiment link will take users to a 404 page.

**Comment by jaredhirsch** [comment]
I can fix this along with 1961 👍

**Comment by SoftVision-PaulOiegas** [comment]
This probably slipped because of #1864 :laughing:. Universal Search was no longer available in doorhanger even before the graduation week. 
Anyway, do we know any graduation dates for the current experiments ?
