### ISSUE TITLE
`locale_blocklist` doesn't hide experiments in the doorhanger

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1967]
STR:

1. Set environment to `dev` with Test Pilot installed
2. Change language to `de`
3. Confirm that Activity Stream is not shown on the homepage
4. Open door hanger

Expected:

Activity Stream is not shown because it has

```
locale_blocklist: 
  - 'de'
```

Actual:

Activity Stream appears in the doorhanger

![screen shot 2017-01-04 at 12 33 01 pm](https://cloud.githubusercontent.com/assets/8632184/21658630/38d7d81c-d27c-11e6-9dce-9b6817a687aa.png)

**Comment by johngruen** [comment]
AAAND this is why we want to get rid of the doorhanger

**Comment by ckprice** [comment]
This will block launch I think.

**Comment by ckprice** [comment]
Dup of #1961

**Comment by jaredhirsch** [comment]
Actually, I think this is importantly different from #1961. Reopening
