### ISSUE TITLE
Use camelcase, not underscores, in the JSON API

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#197]
The front-end code seems to be sprinkled with a growing number of snake_case variables.

The solution suggested in the django rest framework [docs](http://www.django-rest-framework.org/api-guide/parsers/#camelcase-json) is to use this library to convert keys to camel case: https://github.com/vbabiy/djangorestframework-camel-case

**Comment by johngruen** [comment]
@6a68 We're now using snake case to refer to data coming in from the yaml. Do you still feel like this is an issue? I find it useful since it gives a visual indicator of where this stuff comes from.

**Comment by johngruen** [comment]
Closing for now, feel free to reopen.
