### ISSUE TITLE
Can't enable Cliqz on beta or release

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1971]
STR

- Be on Beta or Release
- Be in the 'dev' environment
- Go here https://testpilot.dev.mozaws.net/experiments/cliqz
- Click on Enable

Expected:

Thing installs

Actual:

![screen shot 2017-01-04 at 3 57 31 pm](https://cloud.githubusercontent.com/assets/8632184/21663682/92c33942-d296-11e6-96f1-b630b8530ad9.png)

@pdehaan saw the following error

> 1483574049991	addons.xpi	WARN	Add-on testpilot@cliqz.com is not correctly signed.
> 1483574049992	addons.xpi	WARN	Download of https://testpilot.firefox.com/files/testpilot@cliqz.com/latest failed: signature is required but missing

@past can you confirm this is signed?

This blocks #1968. 

/cc @clouserw

**Comment by clouserw** [comment]
I don't see this signed in the .xpi (no META-INF) and I also see the warning on Nightly

**Comment by SoftVision-PaulOiegas** [comment]
We have seen this but we thought that the xpi was not yet added, just the page, based on the issues and PR's related...

**Comment by past** [comment]
There was a misunderstanding on whether Cliqz or the Test Pilot team were responsible for the signing, but we are resolving it in an email thread.

**Comment by ckprice** [comment]
Latest version uploaded fixes this.
