### ISSUE TITLE
Toolbar button 'new' label should be locale-aware

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#1973]
Some new experiments might not be available in the user's locale, so a 'new' label may be incorrectly shown over the toolbar button.

Given that we're going to remove the doorhanger, the fix is probably to wait till that is done, then just relocate the filtering code into the part of lib/toolbar-button that checks experiment freshness.

So, I guess this is related to #1922.

**Comment by SoftVision-PaulOiegas** [comment]
Indeed this issue is happening and we mentioned it in #1961 on the [Additional Notes] section of the bug.

**Comment by jaredhirsch** [comment]
Looks like we'll also need to filter the 'new' badge based on the launch date.
