### ISSUE TITLE
Test Pilot 404 page returns 200 status code

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1976]
Spent a few minutes debugging a script where I was trying to scrape an XPI hosted on test pilot but my URL was invalid but still returning a HTTP/1.1 200 status code.

```sh
$ http https://testpilot.firefox.com/files/activitystream/lates

HTTP/1.1 200 OK
Age: 456
Cache-Control: max-age=600
Connection: keep-alive
Content-Length: 2763
Content-Type: text/html
Date: Thu, 22 Dec 2016 22:37:13 GMT
ETag: "d745eea7f043b45b9d229bb57e4f3237"
Last-Modified: Thu, 22 Dec 2016 22:31:06 GMT
...
```

**Comment by fzzzy** [comment]
This does still happen. It must be something in the S3 config somewhere that needs work.

**Comment by meandavejustice** [comment]
This stack exchange questions seems relevant here https://serverfault.com/questions/722632/change-nginx-http-status-code-when-using-proxy-pass

**Comment by fzzzy** [comment]
This is fixed on dev but not in prod.

**Comment by johngruen** [comment]
@clouserw will get the ball rolling here

**Comment by relud** [comment]
this should be fixed in stage. let me know when you would like the update deployed to prod

**Comment by fzzzy** [comment]
This was fixed on prod. Thanks @relud!!
