### ISSUE TITLE
Update screenshot description on Cliqz page

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1977]
We received some feedback on the Cliqz page, looks like this was missed during the general copy review.

> Thank you, looks good. Just a minor edit to the text for screenshot 2: It should read
> 
> Sehen Sie in Echtzeit zusammengefasste Informationen, zum Beispiel über das Wetter, direkt unter der Adressleiste.
> 
> ((Removed "und Sendezeiten“ = "and showtimes". We do not offer this feature.))

I think we'll need to modify the YAML as referenced in https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#localization

/cc @flodolo 

Ref #1968.

**Comment by flodolo** [comment]
Argh. Since this string is basically targeting only German, I suggest to fix the string without a new ID, I'll fix the localization in Pontoon in the meantime.

**Comment by flodolo** [comment]
@koehlermichael and @Archaeopteryx
https://pontoon.mozilla.org/de/test-pilot-website/all-resources/?search=zusammengefasste&string=160975

See comment above, the original string is wrong (no showtimes). I was going to change it directly, but it seems quite different.

Current: "Sehen Sie zusammengefasste Informationen – wie Wetter und Sendezeiten – in Echtzeit direkt unter der Adressleiste."

Proposed: "Sehen Sie in Echtzeit zusammengefasste Informationen, zum Beispiel über das Wetter, direkt unter der Adressleiste."

Can you update the translation in Pontoon?

**Comment by koehlermichael** [comment]
@flodolo @Archaeopteryx

I just made the change in Pontoon though the incorrect original string is still visible there. Flod, your translation works fine, nice work as usual.

**Comment by flodolo** [comment]
Thanks Michael, I see it just landed in the repo
https://github.com/mozilla/testpilot/commit/1b03375d8272c09693cb4697190e14ddd813dd90

**Comment by johngruen** [comment]
@koehlermichael thanks! I'll tweak the original string now!

**Comment by ckprice** [comment]
Fixed in #1986 and 1b03375
