### ISSUE TITLE
Enable / Disable <experiment_name> button long format persists when maximazing from mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1980]
[Affected versions]:
- Firefox 50.1.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click on any experiment card.
3. Resize the browser window length until the "Enable <experiment_name>" button enlarges (mobile view).
4. Choose to enable the experiment and dismiss the tour.
5. Maximize the browser window and observe the "Disable <experiment_name> button. 

[Expected result]:
- The button size is automatically reduced when browser is maximized.

[Actual result]:
- The button enlarges even more when browser is maximized. 

[Notes]:
- When this issue occurs the "Give Feedback" button is moved in far left side of the page together with the experiment name. Also experiment names formed from  2 words are displayed on two rows instead of one.
- Same behavior occurs if the browser is resized when disabling the experiment and after window is maximized.
- The button returns to normal size if page is refreshed. 
- Here is a screen recording of the issue https://goo.gl/CJH05d.

**Comment by fzzzy** [comment]
Just tested this, this still happens.

**Comment by johngruen** [comment]
Close this in favor of general photon fixes
