### ISSUE TITLE
Updated `created_date` for Cliqz product page to be 14+ days in the past

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#1981]
~~TL;DR we really want to avoid shipping the `New` to en-us users when we launch cliqz next week. Because some en-us users won't have updated their add-ons they might see the cliqz experiment with a new badge. This is a bad result. The most expedient resolution is to temporarily remove the code triggering the `new` badge from the test pilot app.~~

Correction, the new experiment badge is wholly set within the add-on the remediation here is as follows: 

@ckprice @clouserw when we push the experiment to stage and  the `created` date in the YAML needs to be at least 14 days previous to the current day.

**Comment by ckprice** [comment]
Blocks #1968

**Comment by jaredhirsch** [comment]
I think the better solution here is just to have the 'new' badge be aware of the launch date, related to #1973.

**Comment by jaredhirsch** [comment]
This isn't needed, now that #1984 has landed, fixing #1973. Closing.
