### ISSUE TITLE
Cliqz notification message about data sending cannot be dismissed if browser is not restarted after experiment enable

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1982]
[Affected versions]:
- Firefox 50.1.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- German localized version of Firefox was installed / extracted.
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open DE localized Firefox browser with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click on "Cliqz" experiment card and choose to enable it.
3. Search some well known website from new address bar and navigate to them.
4. Leave the browser idle for a while until the notification message for data sending appears on the bottom of the page.
5. Click on the close button "(x)" to dismiss it.

[Expected result]:
- The notification bar is dismissed.

[Actual result]:
- The notification bar cannot be dismissed.

[Notes]:
- Due to the long amount of idle needed until the bar appears by herself I cannot confirm the behavior entirely but I'll update the bug with new details after I get them. However, we managed to reproduce it on 4 different profiles on two separate PC's.
- The notification message can be forced to appear after restarting the browser but it can be always dismissed by doing so. I'm guessing that this only occurs if it appears on the same browsing session.
- Here is a screen recording of the issue https://goo.gl/KXtmeZ.

**Comment by ghost** [comment]
CC @past  -- sounds like this is a cliqz issue.

Where should issues like this be filed?

**Comment by pdehaan** [comment]
The testpilot dev Cliqz experiment page links to their https://github.com/cliqz-oss/browser-core/issues repo for issues.

**Comment by past** [comment]
Yes, what @pdehaan said.

**Comment by luciancor** [comment]
We unfortunately cannot reproduce this issue. 
@SoftVision-PaulOiegas can you please give us an idea regarding how long you kept the browser idle before this issue appeared ?

**Comment by SoftVision-PaulOiegas** [comment]
@luciancor I'll need to investigate this again a bit since I don't think the notification appeared after a long idle period after all. I just assumed since I had multiple profiles opened to test Cliqz and it was randomly displayed on some of them. 
But I found out after I logged the bug how I can force the display of it. Disabling and re-enabling the experiment from Test Pilot does the job. However, I haven't managed to reproduce the issue after, so I must have done something else too for it to be blocked.
I will report back if I manage to reproduce this somehow in the next days. Currently I am focused on testing the Test Pilot new release.

**Comment by luciancor** [comment]
Thanks for the update @SoftVision-PaulOiegas !

Just to give you a bit more background - the way you described it is exactly how it should work.
We have a way to enable modules from the backend in the form of an AB test. So basically the first time you start our extension the module which shows that message is turned off. It will only be turned on at the next start (either of the browser or enable/disable). Therefore the message should not appear at the very first start but only at the second start in the moment when the mechanism gets active. 

We were still not able to reproduce it at our end, our only guess is that your test pilot version of CLIQZ got automatically updated after the message was shown. Do you, by chance, have any idea regarding the version of CLIQZ you installed and also the version you had when you screen recorded that issues?

**Comment by SoftVision-PaulOiegas** [comment]
Well, actually I got a bright idea 😆 and found the steps to reproduce.  The issue is not reproducible in on current Firefox release but reproduces on all the other channels (Beta, Developer, Nightly). So probably the issue will emerge on the next release.

[Prerequisites]:
- On a new profile add German language from "Options>Content>Languages" to be in the top of the list. 
- Manually add in "about:addons" page a new string type pref with "testpilot.env" name and "dev" value. 
- Test Pilot was already installed on the above profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments/cliqz page.
2. Enable Cliqz from Test Pilot and dismiss the opened page.
3. Dismiss the Test Pilot tour and choose to "Disable" Cliqz.
4. Close the opened page and dismiss the thanks pop up.
5. Enable Cliqz again in order to have the notification bar about data sending displayed on the bottom of the window.
5. Dismiss again the tour and choose to "Disable" again Cliqz.
6. Click the close button for the data sending notification.

[Expected results]:
The notification bar is dismissed.

[Actual results]:
The notification bar cannot be dismissed.

[Notes]:
- As a bonus, if the notification bar is displayed and the Cliqz experiment is disabled, the "Learn more" button redirects the user to a 404 page.

**Comment by SoftVision-PaulOiegas** [comment]
@luciancor If you thought after above steps that this is an edge case, you might wanna reconsider. Found a more easier way to reproduce and might be encountered by users really easy.

[STR]:
1. Install Test Pilot and enable Cliqz.
2. Restart browser in order to have the notification bar displayed.
3. Choose to Disable Cliqz from test Pilot experiment page.
4. Click the close button for the data sending notification.

After this the bar remains stuck on the bottom of the window and can be dismissed only with a browser restart. 
Here's a screen recording of the exact steps to reproduce the issue - https://goo.gl/brHdF8.

**Comment by luciancor** [comment]
Thanks @SoftVision-PaulOiegas ! We will provide a fix for this one.

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc This still reproduces on dev server Cliqz build. Probably a new build wasn't launched yet.
 So either we still leave this open until a new build arrives, either I can clone it in Cliqz repo. It's up to you.

**Comment by luciancor** [comment]
@SoftVision-PaulOiegas @wresuolc this issue is fixed on our side and it will land in our next update

**Comment by ghost** [comment]
Thanks!  I'll close this then.
