### ISSUE TITLE
After the installed Test Pilot add-on auto-updated, the localization restricted experiments were redisplayed in doorhanger

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#1985]
[Affected versions]:
- Firefox 50.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Install or extract a German Firefox build for this issue.
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open the DE Firefox build with the profile from prerequisites.
2. Navigate to "https://testpilot.dev.mozaws.net" page and observe the available experiments.
3. Click on the Test Pilot icon from browser tooblar.
4. Observe the available experiments.
5. Go to about:addons, click on Test Pilot add-on and manually check for updates.
6. If an update is found and installed check again the doorhanger for available experiments. 

[Expected result]:
The DE localization restricted experiments are not displayed on the Test Pilot page or in doorhanger even after update.

[Actual result]:
Step 2. The restricted experiments are not displayed on the page.
Step 4. The restricted experiments are not displayed in doorhanger.
Step 6. The restricted experiments are redisplayed in doorhanger after update.

[Notes]:
- After we managed to reproduce the issue on multiple profiles and on two separate machines, this was no longer happening after a 2-nd update was automatically installed.
- When we reproduced the issue, the installed Test Pilot version was 0.9.2-dev-3fcc802. After updating the add-on the newer version was 0.9.2-dev-78214f8. 
- Vice versa, if other build is used than DE, Cliqz is available in Test Pilot doorhanger.

**Comment by jaredhirsch** [comment]
I'm puzzled by this bug.

When the add-on is [first loaded / installed](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L90) or [checks for new experiments](https://github.com/mozilla/testpilot/blob/master/addon/lib/app.js#L68), it fires the same `'loaded'` event that [triggers UI updates](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L132) (including the list of doorhanger items).

Now that the doorhanger is filtered by the user's preferred locale (`navigator.language`) (#1972), all of these updates should send the same stuff into the doorhanger. I'm not quite sure what the cause might be.

**Comment by ckprice** [comment]
I got this too, thinking this is going to block launch (#1968).

**Comment by jaredhirsch** [comment]
@ckprice I haven't been able to repro this, so I'm slightly nervous about labeling it a blocker.

What steps did you take to repro?

**Comment by jaredhirsch** [comment]
Derp, just noticed your link to #1992

**Comment by jaredhirsch** [comment]
OK, opened PR #1993 to fix #1992, that's a separate issue with a simple fix.

I still can't repro this issue. I've tried setting the [update interval](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L7) to 30 seconds, rather than 12 hours, and I'm consistently seeing the correct set of entries in the doorhanger.

I'd suggest we not block on this issue, unless someone finds consistent STR.

**Comment by ckprice** [comment]
Sounds good! Thanks for looking into Jared.

**Comment by SoftVision-CosminMuntean** [comment]
Hi guys,

Today I was also able to reproduce this issue again on stage. I had an older Firefox profile with Test Pilot v.0.9.1-dev-e42d9cb installed. After I manually updated the add-on, the newer version of Test Pilot was 0.9-dev-78214f8 and the localization restricted experiments were wrongly displayed again in doorhanger.

- Here is a screen recording with the issue: https://goo.gl/oiBu3Z
- Here are the errors displayed in browser console: https://goo.gl/qPrXoQ
- Here is my Firefox profile with an old Test Pilot version installed: https://goo.gl/wx4by7 

I have also managed to reproduce this issue with a new clean profile. I have installed Test Pilot from stage server and the current version was 0.9.2-dev-4c568ed. Manually check for updates and it seems that Test Pilot was updating to a newer version 0.9.2-dev-78214f8 and the localization restricted experiments were again redisplayed in doorhanger.
Also, the "New" badge disappeared after update.

- Here is a screen recording with the issue: https://goo.gl/nfsbrd 
- Here are the errors displayed in browser console: https://goo.gl/QiMVea

For testing this, I have used a Firefox (v50.1.0) DE build.

**Comment by jaredhirsch** [comment]
Doorhanger is gone; closing.
