### ISSUE TITLE
Send correct locale when submitting welcome email 

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1987]
This could be a thing that blocks our launch.

STR:

- Uninstall Test Pilot
- Set language to de
- Browse to dev
- Install Test Pilot
- Submit welcome email modal

Expected Result:

- You are registered in email system as a German speaker, and receive German version of welcome email

Actual Result:

- Receive English version of welcome email

You can test multiple times by adding "+" after your username, e.g. cprice+20160106@mozilla.com.

I think we have to send a locale here: https://github.com/mozilla/testpilot/blob/b3ce96502f5f93113a66b662ac57b2197d10d213/frontend/src/app/actions/newsletter-form.js#L24

**Comment by ckprice** [comment]
We should either fix this, or suppress the dialog for launch.

**Comment by ckprice** [comment]
Including `lang=de` to the basket call fixes this. Ref: http://basket.readthedocs.io/newsletter_api.html#news-subscribe

**Comment by jaredhirsch** [comment]
@ckprice Do we have a German-localized newsletter? That is, is this bug about disabling the newsletter dialog, or adding the `lang` parameter to the basket call?

**Comment by ckprice** [comment]
@6a68 working with wbowden to confirm one is ready. I've confirmed with him that if we send `lang=de`, the record comes into the email platform as DE. So to answer your question, we're looking more like this is going to do the fix (adding `lang` param)

**Comment by jaredhirsch** [comment]
Also, are we just going to have one German newsletter, or will there be one per region (`de-de` vs `de-ch`)?

**Comment by ckprice** [comment]
> Also, are we just going to have one German newsletter, or will there be one per region (de-de vs de-ch)?

Just one (de).
