### ISSUE TITLE
Track progress for installations on experiment detail view.

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#199]
We need to show another state to show the user that the experiment is installing.

**Comment by meandavejustice** [comment]
@johngruen What should we shoot for here for mozlando? Something like [this](http://demo.tutorialzine.com/2013/10/buttons-built-in-progress-meters/)? or just extra "installing/failed" states?

**Comment by meandavejustice** [comment]
add "enabling..." for in between state

**Comment by johngruen** [comment]
@meandavejustice gonna sumbit a test-balloon pr for this one right now
