### ISSUE TITLE
A few HTML errors in localized experiments.ftl files

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#1991]
I was trying to do a quick sanity check on some nested HTML in localized ./locales/*/experiments.ftl files and found a few errors so far.

Not sure if these can be fixed by hand tweaking the *.ftl files, or if we need to go through Pontoon.

1. [/locales/ar/experiments.ftl:6](https://github.com/mozilla/testpilot/blob/6a5012ef8719cd966dd8158d0a3392cfac3f3c76/locales/ar/experiments.ftl#L6) `activitystreamToursteps0Copy` has an invalid closing `</ P>` tag:

    ```html
    <p>والبحث عن أفضل المواقع الخاصة بك، تاريخ التصفح الحديث، والإشارات عند فتح علامة تبويب جديدة.</ P>
    ```

2. [/locales/ar/experiments.ftl:23](https://github.com/mozilla/testpilot/blob/6a5012ef8719cd966dd8158d0a3392cfac3f3c76/locales/ar/experiments.ftl#L23) `minvidIntroduction` has some missing closing `</li></ul>` tags:

    ```html
    <p>هل تحب مشاهدة مقاطع الفيديو؟ هل تود إنجاز عملك بينما وأنت تشاهد مقاطع الفيديو؟ قم بتجربة Min Vid. إنها بمثابة صورة داخل صورة حيث الصورة الأولى هي الفيديو والصورة الثانية هي الموقع نفسه. </p><ul><li><strong> انقر واذهب:</strong> اجعل شاشة Min Vid تنبثق لجعل الفيديو يعمل في الخلفية وأنت تتصفح الويب.
    ```

3. [/locales/ar/experiments.ftl:75](https://github.com/mozilla/testpilot/blob/6a5012ef8719cd966dd8158d0a3392cfac3f3c76/locales/ar/experiments.ftl#L75) `trackingprotectionIntroduction` has an opening uppercase-`<P>` but closing lowercase-`</p>` and I think the case difference is confusing httmlint (despite being valid HTML).

    ```html
    trackingprotectionIntroduction = <p>حتى الآن، كانت حماية التتبع في فيرفكس متوفرة فقط في وضع التصفح الخاص. هذه التجربة تتيح حماية التتبع في كل الأوقات! (وبطبيعة الحال، يمكنك تعطيلها على أساس كل موقع وقتما تشاء.) </p> <P>هذه التجربة تسمح لك بمساعدتنا على فهم حيثية كسر حماية تتبع الويب حتى نتمكن من تحسينها لجميع مستخدمي فيرفكس. بينما أنت تتصفح، انقر على أيقونة الدرع الأرجواني في شريط العنوان في أعلى الصفحة ليقول لنا المواقع التي تعمل بشكل جيد مع الحماية من التعقب والتي لا تفعل ذلك. </p>
    ```

4. [/locales/ru/experiments.ftl:91](https://github.com/mozilla/testpilot/blob/6a5012ef8719cd966dd8158d0a3392cfac3f3c76/locales/ru/experiments.ftl#L91) `universalsearchMeasurements` seems to be missing a closing `</a>` tag.

    ```html
    universalsearchMeasurements = <p>В дополнение к <a href="/privacy">данным</a>, собираемыми всеми экспериментами лётчика-испытателя, существуют несколько важных вещей, которые вы должны знать о том, что происходит, когда вы используете Universal Search:</p><ul> <li>Мы собираем базовые данные о том, как вы взаимодействуете с панелью адреса (адресной строкой), например, количество набранных символов, типы результатов, по которым вы щёлкаете, и их позицию в списке результатов.</li> <li>Если вы ранее настроили Firefox показывать поисковые предложения в панели поиска, установка Universal Search включит <a href="https://www.mozilla.org/privacy/firefox/#searchsuggestions" target="_blank">поисковые предложения</a> в адресной строке.</li> <li>Когда вы используете адресную строку, мы посылаем выражения, которые вы вводите, нашему движку рекомендаций. Мы сохраняем анонимные логи популярных поисковых запросов, чтобы улучшать качество наших рекомендаций.</li> <li>Для работы Universal Search, мы используем несколько сторонних сервисов. Мы используем <a href="http://www.bing.com/developers/s/APIBasics.html" target="_blank">Bing</a> и <a href="https://developer.yahoo.com/boss/search/" target="_blank">Yahoo</a> для функционирования рекомендаций, а также <a href="http://docs.embed.ly/docs/" target="_blank">Embedly</a> и <a href="https://clearbit.com/logo" target="_blank">Clearbit</a>, чтобы предоставлять дополнительные данные (например, изображения или значки) этим рекомендациям. Чтобы отображать рекомендации в адресной строке, Universal Search может загружать эти изображения напрямую через Embedly и Clearbit, которые могут позволить этим сервисам видеть ваш IP адрес и <a href="https://www.mozilla.org/privacy/firefox/#searchsuggestions" target="_blank">запрошенное изображение.</li></ul>
    ``` 

5. [/locales/zh-TW/experiments.ftl:48](https://github.com/mozilla/testpilot/blob/6a5012ef8719cd966dd8158d0a3392cfac3f3c76/locales/zh-TW/experiments.ftl#L48) `nomore404sMeasurements` is missing a closing `</li>`:

    ```html
    nomore404sMeasurements = <p>除了所有 Test Pilot 都會收集的 <a href="/privacy" target="_blank">資料</a> 外，以下是您使用 No More 404s 時應該知道的事情:</p><ul><li>我們會收集您遇到「找不到網頁」（代碼 404）錯誤、該頁面在 Archive.org 上已有存檔、以及您選擇檢視該存檔版本的次數。</li><li>為了提供頁面的快取版本，我們會將找不到的網頁網址傳送到 Archive.org。<a href="https://archive.org/" target="_blank">Archive.org</a> 在 <a href="https://archive.org/about/terms.php" target="_blank">這裡</a> 揭露了他們的隱私權保護政策。<li>我們不會收集您想瀏覽的網頁網址，以及送到 Archive.org 查詢的網址。</li><li>我們可能會將與此實驗相關，您送出給我們的問卷內容、以及加總過的 Telemetry 資料分享給 Internet Archive。</li></ul>
    ```

6. [/locales/zh-TW/experiments.ftl:100](https://github.com/mozilla/testpilot/blob/6a5012ef8719cd966dd8158d0a3392cfac3f3c76/locales/zh-TW/experiments.ftl#L100) `universalsearchMeasurements` is missing a closing `</li>` tag:

    ```html
    universalsearchMeasurements = <p>除了所有 Test Pilot 都會收集的 <a href="/privacy">資料</a> 外，以下是您使用 Universal Search 時應該知道的事情:</p><ul><li>我們會收集您如何與 Awesome Bar 智慧網址列互動，包含打過多少字元、點擊結果的類型、以及這些結果在清單中的位置等基本使用資料。</li><li>若您先前設定過 Firefox，要在搜尋列中顯示搜尋建議，安裝 Universal Search 後也將會開啟 <a href="https://www.mozilla.org/privacy/firefox/#searchsuggestions" target="_blank">搜尋建議</a>。<li>當您使用 Awesome Bar 時，我們會傳送您輸入的字詞到我們推薦的搜尋引擎中，我們會匿名地保留常見的搜尋以改善我們的建議品質。</li><li>我們使用了幾個第三方服務來提供 Universal Search。包含 <a href="http://www.bing.com/developers/s/APIBasics.html" target="_blank">Bing</a> 及 <a href="https://developer.yahoo.com/boss/search/" target="_blank">Yahoo</a> 來提供搜尋建議，以及 <a href="http://docs.embed.ly/docs/" target="_blank">Embedly</a> 和 <a href="https://clearbit.com/logo" target="_blank">Clearbit</a> 來提供這些建議的更多資料（如圖片或圖示）。為了在 Awesome Bar 顯示這些建議，Universal Search 可能會直接從 Embedly 和 Clearbit 直接下載圖片，可能會讓這些服務知道您的 IP 地址，以及您要求了哪些圖片。</li></ul>
    ```

**Comment by flodolo** [comment]
And that's why we should have as less HTML as possible in strings… They're localizers, not web developers, messing things up is way too easy.

Even I had a hard time figuring out what to fix, hopefully I got them all. I had to unapprove #2 for Arabic because the translation is clearly partial.

cc @unghost for Russian (I had some doubts on this, Russian has a link at the end not available in en-US)
https://github.com/mozilla/testpilot/commit/3721caa1246200e0a07d183c887d8897d8b9d8bb

@petercpg for zh-TW
https://github.com/mozilla/testpilot/commit/c36cf0106ef93c6662f039da45b4c3247bd5b4fa
@mohamed7afezz and @aboodmanna for ar
https://github.com/mozilla/testpilot/commit/65ecf2e9bb55eb900d89a15299ef4f66067fcc08

**Comment by flodolo** [comment]
> Not sure if these can be fixed by hand tweaking the *.ftl files, or if we need to go through Pontoon.

To answer your question, you can fix directly the .ftl files and Pontoon will sync them every 20 minutes. That's also the painful part: the risk of merge conflicts is pretty high with this frequency, so for these you might want to create the PR and merge very quickly.

In some cases it's not that easy (see partial translation in Arabic).

**Comment by petercpg** [comment]
Thanks @flodolo for the fix 👍 My couple thoughts for this kind of issue:

There are quality checks in Pontoon but I disabled as it is raising too many false alarms (such as Number of sentences). 
As a webdev I prefer to have one single sentence to localize so I can tweak the sentence order without hassle, but from a localizer's perspective, having multiple long strings would be quite painful so I'm usually just localize one, copy & paste to other similar strings, then tweak the different parts. This is probably why the closing li tag was missed.

**Comment by unghost** [comment]
Thank for the fix. I've removed a link at the end in Pontoon.

**Comment by ghost** [comment]
We're these all fixed in Pontoon or is there more to do here?

**Comment by ghost** [comment]
Closing this.  Please reopen if there is something else to do. Thanks for filing!
