### ISSUE TITLE
All experiments are available in the doorhanger regardless of locale or date settings

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#1992]
STR:

- Set environment to stage
- Set language to `de`
- Go to stage
- Install Test Pilot
- Open doorhanger

Expected Results:

- Only Page Shot, Min Vid and Tab Center should be visible in the doorhanger.

Actual Results:

![screen shot 2017-01-06 at 3 25 32 pm](https://cloud.githubusercontent.com/assets/8632184/21736314/a62d4bdc-d424-11e6-9a07-3717c683e656.png)

Cliqz 404's because it has `launch_date` set.

Could be related to #1972. Blocks #1968.

**Comment by ckprice** [comment]
Closing in favor of #1985.

**Comment by jaredhirsch** [comment]
This seems different from 1985, reopening.

I'm not able to reproduce this. On staging, just now, following the instructions, I got the expected set of things:

<img width="391" alt="screen shot 2017-01-06 at 5 03 37 pm" src="https://cloud.githubusercontent.com/assets/96396/21737880/29867280-d432-11e6-9547-19ad8ad36f69.png">

**Comment by jaredhirsch** [comment]
Oh, Cliqz for sure shouldn't be there. Looking now
