### ISSUE TITLE
There are some not right things on the landing page

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#200]
<img width="1369" alt="screen shot 2015-10-27 at 5 23 00 pm" src="https://cloud.githubusercontent.com/assets/3323249/10764649/764e8190-7ccf-11e5-95f3-ea9d8387b5a1.png">

Tabzilla and legal links need fixin'

**Comment by pdehaan** [comment]
Tabzilla tab misplacement filed as #192

**Comment by meandavejustice** [comment]
Legal links as #123 closing as duplicate.
