### ISSUE TITLE
Loading animations display a white box artifact (Nightly)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2000]
[Notes]:
- This seems to be a browser regression since on latest Firefox release this is not visible. I will investigate more in the next days and log a Firefox issue if needed.

[Affected versions]:
- Firefox 53.0a1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on an experiment card (eg: Tab Center).
3. While observing the "Enable <experiment_name>" button, click it.

[Expected result]:
- The button changes into an "Enabling" barberpole animation displayed with no format issue.

[Actual result]:
- The "Enabling" barberpole animation displays a white box artifact 

[Additional notes]:
- This issue can be seen also on Test Pilot uninstall animation.
- Here are two screen recordings of the issue:
https://goo.gl/a1ntXP
https://goo.gl/JJ8WjW

**Comment by johngruen** [comment]
This is upstream, but we should file an issue on bugzilla.

**Comment by SoftVision-PaulOiegas** [comment]
Haven't seen this anymore on Nightly, so I'll close it for now.
