### ISSUE TITLE
The Testpilot add-on, and the testpilot website appear in the wrong locale.

### ISSUE THREAD

**Issue by AmyAmy** [mozilla/testpilot#2006]
My browser language is set to English (en-GB).
My operating system, (Windows 10) is set to English.
"Choose your preferred language for displaying pages" is set to en-GB.

yet, both the add-on and https://testpilot.firefox.com/ appear in _Dutch_, without any option to change the language.

**Comment by johngruen** [comment]
@Amyamy...Dutch?! that's no good. Could you screenshot the languages panel in the content section of about:preferences for reference? Also, any add-ons you have installed that might be overriding your language preference?

**Comment by AmyAmy** [comment]
![image](https://cloud.githubusercontent.com/assets/630387/21800458/011d0248-d71e-11e6-8a81-0ab824b9e83d.png)

Dutch is in my list, but at the bottom.

I do have the Dutch dictionary installed: https://addons.mozilla.org/en-GB/firefox/addon/woordenboek-nederlands/  
I've quickly tested by disabling it, plug-in and website still appear in dutch.

**Comment by flodolo** [comment]
There's no en-GB, so it falls back to en and then nl, and finally finds a supported language.

You can easily reproduce by setting `intl.accept_languagesintl.accept_languages` to `en-GB, en,nl` in about:config. We should probably do something smarter with 'en', maybe symlink en-US would be enough.

I'm quite surprised that the add-on uses Dutch though, that shouldn't look at accept-languages.

**Comment by SoftVision-PaulOiegas** [comment]
Well, from past experiences, it's always good to have some kind of a safety net for localization. Maybe it would be a good idea to somehow force en-US localization if the set language fails for any reason ?

**Comment by AmyAmy** [comment]
I'm no I27n expert, just here because I filled the bug, but I would expect the following to happen:

If no match can be found for `en-GB` it should look for the base localization, in this case `en`. 
If no match can be found for `en`, fall back to whatever `en-*` can be found.
If there still is no match, repeat for the next item in the `accept-languages` list.

It might also be a good idea, if `en-US` is the only `en` localization, to rename it to `en` (and perhaps the same for `es-ES` ,`fy-NL`, `pt-BR`, `sv-SE`, and one of `zh-CN`, `zh-TW`)

--

There must be other (Mozilla) sites that already have implemented smart algorithms for these kind of things, right?

**Comment by flodolo** [comment]
> Maybe it would be a good idea to somehow force en-US localization if the set language fails for any reason ?

If none of the languages in your accept-languages match, it will already fall back to en-US. In this case, there's a matching 'nl' before that final step, and it gives you Dutch.

Assuming it works, the easiest solution should be to create a `en` folder that is a symlink to `en-US`.

Looking for the language ignoring the region is the not right approach, i.e. you don't want to show zh-CN to users in Taiwan, and there's no such thing as 'zh'. Most of the time you just make a call and decide to redirect 'zh' to one of them, same for es, pt, etc.

**Comment by AmyAmy** [comment]
Doesn't having `en` in my `accept-languages` list mean: "give me english, I don't care which one"?

**Comment by SoftVision-PaulOiegas** [comment]
@flodolo - But why the simple "English [en]" is bypassed ? When we reproduced the issue we had the next order: 1. [en-GB], 2. [en], 3. [nl].

Assuming that en-GB fails, I would expect to jump in default English (second in list) not to Dutch (third in list). I'm not expert either in localization but I think providing the default language option (en-US) if the first selected one fails would be the better approach then offering another language that has less importance in list. 
But then again, maybe I don't understand the logic behind the Firefox current implementation. My point was based on web / mobile apps that I've tested until now which only had a single language selection option.

**Comment by flodolo** [comment]
1) There is no 'en' locale in Test Pilot, that's why it doesn't work.

2) No, bypassing the second language is definitely not a good option. For example I have 'it-IT, it, en-US, en', based on your plan I would get en-US instead of Italian.

**Comment by flodolo** [comment]
(just to be clear, we should definitely serve English if 'en' is in the list, I'm just explaining why it doesn't currently happen)

**Comment by johngruen** [comment]
Yeah i encountered this as well, there need to be an 'en' locale in test pilot. 

### STR

1. go to about:preferences#content
1. in the languages panel set your first language to `en`
1. set your second language to anything else `de` for example

### Result
- Test Pilot displays in DE but with `en` authorized experiments

### Expected
- If `en` is the first choice language in the browser the site should render in en

**Comment by johngruen** [comment]
so this: 
<img width="487" alt="screen shot 2017-01-11 at 9 33 22 pm" src="https://cloud.githubusercontent.com/assets/3323249/21865262/bb5279a4-d845-11e6-8f09-eb051773146e.png">

leads to:
![page-shot-2017-1-11 firefox test pilot](https://cloud.githubusercontent.com/assets/3323249/21865275/ca97a01a-d845-11e6-8485-2d8161158cb2.png)

leads to:
![giphy](https://cloud.githubusercontent.com/assets/3323249/21865378/14314f6e-d846-11e6-905e-83bb99ba93bb.gif)

**Comment by johngruen** [comment]
Thanks for reporting @AmyAmy! This will be fixed on production by Tuesday :)
