### ISSUE TITLE
Button label in feedback bar has wrong color on Windows

### ISSUE THREAD

**Issue by phlsa** [mozilla/testpilot#2007]
The button label for taking a survey is really hard to read on Windows (10). I assume that either the label should have been black or that the button color should have been blue.
![snip_20170110151452](https://cloud.githubusercontent.com/assets/514315/21812009/e4fa3f34-d751-11e6-99db-bcc40a091690.png)

**Comment by ghost** [comment]
We haven't seen this on Windows 10.  Can you give us more information?  Any add-ons?  Any theme colors?  Any lightweight themes in Firefox?

**Comment by phlsa** [comment]
No lightweight themes, but a bunch of add-ons were enabled. Is there a way to manually trigger this bar (through the browser console, or something)? Then I could check whether it's the add-ons. Also, this was happening in Nightly, not release...

**Comment by SoftVision-CosminMuntean** [comment]
I think I was confusing the notification with the one for no experiments installed. 
Managed to reproduce this on Windows 7 and 10 after all. It seems that the "Take a Quick Survey" button from the experiments survey notification is indeed wrongly colored on Windows.

![survay](https://cloud.githubusercontent.com/assets/19226534/21988479/08caa97c-dc10-11e6-8bb5-5cc7b85dad96.png)
