### ISSUE TITLE
[All experiments] The tour pop-up should no longer contain pictures with Test Pilot doorhanger

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2008]
[Affected versions]:
- Firefox 50.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.firefox.com" page.
2. Choose an available experiment and enable it.
3. Navigate through the pop-up tour and observe the slides. 

[Expected result]:
- There are no pictures with Test Pilot doorhager.

[Actual result]:
- The last slide of the tour for each experiment has a picture with Test Pilot doorhanger. 

[Notes]:
- Here is a screenshot with the issue:
![test pilot doorhanger](https://cloud.githubusercontent.com/assets/19226534/21813032/8e015724-d75d-11e6-9361-3231fc717132.png)

**Comment by johngruen** [comment]
@clouserw i have a fix incoming for this
