### ISSUE TITLE
[Enhancement] Tour slides should have the same size independent on the description length

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2012]
[Notes]:
- It's not necessarily an issue but  

[Affected versions]:
- Firefox 50.1.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- German language was added on the top of the list from Firefox "Options > Content > Languages" section or a localized DE build is used.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.firefox.com" page.
2. Click on "Tab Center" experiment card and choose to "Enable" it.
3. Navigate through the pop-up tour and observe the slides size (height). 

[Expected result]:
- All the tour slides have the same size.

[Actual result]:
- Tour slides 3 and 5 have a bigger height than the other 3.

[Notes]:
- This issue occurs due to the slide description. With one row the height is ~471px, whit two rows, the height raises to ~499px.
- This is visible on multiple experiments, here is a list of them
#### German:
- Cliqz - 2nd slide
- Page Shot - 4th slide
- Min Vid - 3rd slide
- Tab Center - 3rd & 5th slide

#### English:
- NoMore404s - 1st slide

![tour slides](https://cloud.githubusercontent.com/assets/17258026/21851496/f99489a6-d817-11e6-9701-c7392deb4342.png)

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas yeah we can probably get a fix going with flex-box

**Comment by pdehaan** [comment]
On the plus side, it looks like every tour_step image is 1280x720px.

# activity-stream.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/activity-stream/experiments_experimenttourstep/b/d/bd3d603ab46949ccb2f98c77f16d9be3_image_1462827230_0789.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/activity-stream/experiments_experimenttourstep/5/7/57b8ba146994300a54ba1528efc30bf5_image_1462827230_0948.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# cliqz.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/cliqz/tour/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/cliqz/tour/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# no-more-404s.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/no-more-404s/experiments_experimenttourstep/d/a/dafca30f93dadf7f13cc48d389e08f84_image_1470245154_0851.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# min-vid.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/min-vid/experiments_experimenttourstep/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/min-vid/experiments_experimenttourstep/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/min-vid/experiments_experimenttourstep/tour3.jpg
tour_steps.image[3] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# page-shot.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour3.jpg
tour_steps.image[3] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour4.jpg
tour_steps.image[4] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# tab-center.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-3.jpg
tour_steps.image[3] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-4.jpg
tour_steps.image[4] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# tracking-protection.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/tracking-protection/experiments_experimenttourstep/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/tracking-protection/experiments_experimenttourstep/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# universal-search.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/universal-search/experiments_experimenttourstep/e/b/eb1a0c8bbb18c79f63d0df45d165eb7a_image_1462826805_0035.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/universal-search/experiments_experimenttourstep/5/2/5218821d5851bef5ad979da5830f68b2_image_1462826805_0031.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/universal-search/experiments_experimenttourstep/1/d/1d414ba2fc88a188b6f74ea79de908e9_image_1462826805_0789.jpg

```js
const path = require('path');

const fastimage = require('fastimage');
const glob = require('glob');
const YAML = require('yamljs');

glob('./content-src/experiments/*.yaml', (err, files) => {
  // Ignore the 'dev-example.yaml' dummy experiment.
  files = files.filter((file) => (path.basename(file) !== 'dev-example.yaml'));

  files.forEach(file => {
    const basefile = path.basename(file);
    const experiment = YAML.load(file);
    const opts = {file: basefile};
    const images = [
      // static(experiment.thumbnail, {label: 'thumbnail', file: basefile}),
      // static(experiment.image_twitter, {label: 'image_twitter', file: basefile}),
      // static(experiment.image_facebook, {label: 'image_facebook', file: basefile}),
      // static(experiment.pre_feedback_image, {label: 'pre_feedback_image', file: basefile})
    ].concat(
      // experiment.contributors.map(({avatar}, idx) => static(avatar, {label: `contributors.avatar[${idx}]`, file: basefile})),
      // experiment.details.map(({image}, idx) => static(image, {label: `details.image[${idx}]`, file: basefile})),
      experiment.tour_steps.map(({image}, idx) => static(image,{label: `tour_steps.image[${idx}]`, file: basefile}))
    );

    return Promise.all(images)
      .then(data => {
        data.forEach((image, idx) => {
          if (idx === 0) {
            console.log(`\n# ${image.file}`)
            console.log('FIELD | DIMENSIONS | PATH\n------|------------|-----');
          }
          if (image.path === undefined) return;
          console.log(`${image.label} | ${image.width}x${image.height} | ${image.path}`);
        })
      })
      .catch(err => console.error(file, err));
  })
});

function static(file, data) {
  if (!file) {
    return Promise.resolve(data);
  }
  const staticfile = file.replace('/static/images/experiments/', './frontend/src/images/experiments/');
  return fastimage.info(staticfile)
    .then((info) => Object.assign(info, data));
}
```

<details>
<summary>All image dimensions...</summary>

# activity-stream.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/activity-stream/experiments_experiment/e/1/e19739ea25188c866b654d3aa2616b27_thumbnail_1461817294_0590.png
image_twitter | 560x300 | ./frontend/src/images/experiments/activity-stream/experiments_experiment/e/1/e19739ea25188c866b654d3aa2616b27_image_1473186642_0579.png
image_facebook | 1200x630 | ./frontend/src/images/experiments/activity-stream/experiments_experiment/e/1/e19739ea25188c866b654d3aa2616b27_image_1473186642_0826.png
contributors.avatar[0] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/kate-hudson.jpg
contributors.avatar[1] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/ricky-rosario.jpg
contributors.avatar[2] | 400x400 | ./frontend/src/images/experiments/activity-stream/avatars/nan-jiang.jpg
contributors.avatar[3] | 500x500 | ./frontend/src/images/experiments/activity-stream/avatars/ursula-sarracini.jpg
contributors.avatar[4] | 371x341 | ./frontend/src/images/experiments/activity-stream/avatars/marina-samuel.jpg
contributors.avatar[5] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/edwin-wong.jpg
contributors.avatar[6] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/jared-kerim.jpg
contributors.avatar[7] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/andrei-oprea.jpg
contributors.avatar[8] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/bernardo-rittmeyer.jpg
contributors.avatar[9] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/nick-chapman.jpg
contributors.avatar[10] | 460x460 | ./frontend/src/images/experiments/activity-stream/avatars/tim-spurway.jpg
contributors.avatar[11] | 125x125 | ./frontend/src/images/experiments/activity-stream/avatars/olivier-yiptong.jpg
contributors.avatar[12] | 64x64 | ./frontend/src/images/experiments/activity-stream/avatars/bryan-bell.jpg
details.image[0] | 1280x1240 | ./frontend/src/images/experiments/activity-stream/experiments_experimentdetail/1/6/16f2bfb82c63c38573005923f4e08457_image_1462827231_0751.png
details.image[1] | 1280x1170 | ./frontend/src/images/experiments/activity-stream/experiments_experimentdetail/6/7/67858740793232e7a71f86b4ef272b67_image_1462827231_0657.png
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/activity-stream/experiments_experimenttourstep/b/d/bd3d603ab46949ccb2f98c77f16d9be3_image_1462827230_0789.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/activity-stream/experiments_experimenttourstep/5/7/57b8ba146994300a54ba1528efc30bf5_image_1462827230_0948.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# cliqz.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/cliqz/icon/thumbnail.png
image_twitter | 560x300 | ./frontend/src/images/experiments/cliqz/social/cliqz-twitter.jpg
image_facebook | 1200x630 | ./frontend/src/images/experiments/cliqz/social/cliqz-facebook.jpg
contributors.avatar[0] | 112x112 | ./frontend/src/images/experiments/cliqz/avatars/cliqz-avatar.jpg
details.image[0] | 1697x1380 | ./frontend/src/images/experiments/cliqz/details/detail1.jpg
details.image[1] | 1697x1380 | ./frontend/src/images/experiments/cliqz/details/detail2.jpg
details.image[2] | 1697x1380 | ./frontend/src/images/experiments/cliqz/details/detail3.jpg
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/cliqz/tour/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/cliqz/tour/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# min-vid.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/min-vid/experiments_experiment/thumbnail.png
image_twitter | 560x300 | ./frontend/src/images/experiments/min-vid/social/mv-twitter.jpg
image_facebook | 1200x630 | ./frontend/src/images/experiments/min-vid/social/mv-facebook.jpg
contributors.avatar[0] | 112x112 | ./frontend/src/images/experiments/min-vid/avatars/dave-justice.jpg
contributors.avatar[1] | 112x112 | ./frontend/src/images/experiments/min-vid/avatars/jared-hirsch.jpg
contributors.avatar[2] | 112x112 | ./frontend/src/images/experiments/min-vid/avatars/jen-kagan.jpg
contributors.avatar[3] | 62x64 | ./frontend/src/images/experiments/min-vid/avatars/noitidart.jpg
details.image[0] | 1280x800 | ./frontend/src/images/experiments/min-vid/experiments_experimentdetail/detail1.jpg
details.image[1] | 1280x800 | ./frontend/src/images/experiments/min-vid/experiments_experimentdetail/detail2.jpg
details.image[2] | 1280x800 | ./frontend/src/images/experiments/min-vid/experiments_experimentdetail/detail3.jpg
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/min-vid/experiments_experimenttourstep/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/min-vid/experiments_experimenttourstep/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/min-vid/experiments_experimenttourstep/tour3.jpg
tour_steps.image[3] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# no-more-404s.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/no-more-404s/experiments_experiment/a/9/a9e6dc66c6a22851721715ae4d0641fb_thumbnail_1470245154_0349.png
image_twitter | 192x192 | ./frontend/src/images/experiments/no-more-404s/experiments_experiment/a/9/a9e6dc66c6a22851721715ae4d0641fb_image_1472573814_0582.png
image_facebook | 192x192 | ./frontend/src/images/experiments/no-more-404s/experiments_experiment/a/9/a9e6dc66c6a22851721715ae4d0641fb_image_1472573814_0278.png
contributors.avatar[0] | 96x96 | ./frontend/src/images/experiments/no-more-404s/avatars/the-internet-archive.png
contributors.avatar[1] | 400x400 | ./frontend/src/images/experiments/no-more-404s/avatars/richard-caceres.jpg
contributors.avatar[2] | 187x187 | ./frontend/src/images/experiments/no-more-404s/avatars/mark-graham.jpg
contributors.avatar[3] | 247x247 | ./frontend/src/images/experiments/no-more-404s/avatars/adam-miller.jpg
details.image[0] | 1280x720 | ./frontend/src/images/experiments/no-more-404s/experiments_experimentdetail/2/4/24ddd4335aca6b96cca9106a6f3411d2_image_1470245154_0440.jpg
details.image[1] | 1280x720 | ./frontend/src/images/experiments/no-more-404s/experiments_experimentdetail/c/d/cdb624363e0e87af81125c39bc69c933_image_1470245154_0280.jpg
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/no-more-404s/experiments_experimenttourstep/d/a/dafca30f93dadf7f13cc48d389e08f84_image_1470245154_0851.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# tab-center.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/tab-center/experiments_experiment/6/9/69333a5f98edf04bbb52085d20e6303e_thumbnail_1461802048_0012.png
image_twitter | 560x300 | ./frontend/src/images/experiments/tab-center/social/tc-twitter.jpg
image_facebook | 1200x630 | ./frontend/src/images/experiments/tab-center/social/tc-facebook.jpg
contributors.avatar[0] | 64x64 | ./frontend/src/images/experiments/tab-center/avatars/blake-w.jpg
contributors.avatar[1] | 400x400 | ./frontend/src/images/experiments/tab-center/avatars/erica-wright.png
contributors.avatar[2] | 64x64 | ./frontend/src/images/experiments/tab-center/avatars/philipp-s.jpg
contributors.avatar[3] | 64x64 | ./frontend/src/images/experiments/tab-center/avatars/john-g.jpg
details.image[0] | 1280x960 | ./frontend/src/images/experiments/tab-center/details/tab-center-1.jpg
details.image[1] | 1280x960 | ./frontend/src/images/experiments/tab-center/details/tab-center-2.jpg
details.image[2] | 1280x960 | ./frontend/src/images/experiments/tab-center/details/tab-center-3.jpg
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-3.jpg
tour_steps.image[3] | 1280x720 | ./frontend/src/images/experiments/tab-center/tour/tc-tour-4.jpg
tour_steps.image[4] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# tracking-protection.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/tracking-protection/experiments_experiment/thumbnail.png
image_twitter | 560x300 | ./frontend/src/images/experiments/tracking-protection/social/tp-twitter.jpg
image_facebook | 1200x630 | ./frontend/src/images/experiments/tracking-protection/social/tp-facebook.jpg
pre_feedback_image | 1280x720 | ./frontend/src/images/experiments/tracking-protection/experiments_experimenttourstep/tour2.jpg
contributors.avatar[0] | 112x112 | ./frontend/src/images/experiments/tracking-protection/avatars/luke-crouch.jpg
contributors.avatar[1] | 112x112 | ./frontend/src/images/experiments/tracking-protection/avatars/aislinn-grigas.jpg
contributors.avatar[2] | 112x112 | ./frontend/src/images/experiments/tracking-protection/avatars/rebecca-billings.jpg
details.image[0] | 1280x720 | ./frontend/src/images/experiments/tracking-protection/experiments_experimentdetail/detail1.jpg
details.image[1] | 1280x720 | ./frontend/src/images/experiments/tracking-protection/experiments_experimentdetail/detail2.jpg
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/tracking-protection/experiments_experimenttourstep/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/tracking-protection/experiments_experimenttourstep/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# page-shot.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/page-shot/experiments_experiment/thumbnail.png
image_twitter | 560x300 | ./frontend/src/images/experiments/page-shot/social/ps-twitter.jpg
image_facebook | 1200x630 | ./frontend/src/images/experiments/page-shot/social/ps-facebook.jpg
contributors.avatar[0] | 112x112 | ./frontend/src/images/experiments/page-shot/avatars/ian-bicking.jpg
contributors.avatar[1] | 112x112 | ./frontend/src/images/experiments/page-shot/avatars/donovan-preston.jpg
contributors.avatar[2] | 112x112 | ./frontend/src/images/experiments/page-shot/avatars/bram-pitoyo.jpg
details.image[0] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimentdetail/detail1.jpg
details.image[1] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimentdetail/detail2.jpg
details.image[2] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimentdetail/detail3.jpg
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour1.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour2.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour3.jpg
tour_steps.image[3] | 1280x720 | ./frontend/src/images/experiments/page-shot/experiments_experimenttourstep/tour4.jpg
tour_steps.image[4] | 1280x720 | ./frontend/src/images/experiments/shared/tour-final.jpg

# universal-search.yaml
FIELD | DIMENSIONS | PATH
------|------------|-----
thumbnail | 192x192 | ./frontend/src/images/experiments/universal-search/experiments_experiment/a/8/a8182b008f6434ba702ab177232625e2_thumbnail_1461818424_0011.png
contributors.avatar[0] | 64x64 | ./frontend/src/images/experiments/universal-search/avatars/nick-chapman.jpg
contributors.avatar[1] | 64x64 | ./frontend/src/images/experiments/universal-search/avatars/bryan-bell.jpg
contributors.avatar[2] | 64x64 | ./frontend/src/images/experiments/universal-search/avatars/jared-hirsch.jpg
contributors.avatar[3] | 64x64 | ./frontend/src/images/experiments/universal-search/avatars/chuck-harmston.jpg
details.image[0] | 870x413 | ./frontend/src/images/experiments/universal-search/experiments_experimentdetail/6/d/6d0ff50eff9223f0d0cc58c5aa5d0c81_image_1462827811_0995.jpg
details.image[1] | 870x413 | ./frontend/src/images/experiments/universal-search/experiments_experimentdetail/8/6/8675c7bf31054abdaf58b47850a1365d_image_1462827811_0451.jpg
tour_steps.image[0] | 1280x720 | ./frontend/src/images/experiments/universal-search/experiments_experimenttourstep/e/b/eb1a0c8bbb18c79f63d0df45d165eb7a_image_1462826805_0035.jpg
tour_steps.image[1] | 1280x720 | ./frontend/src/images/experiments/universal-search/experiments_experimenttourstep/5/2/5218821d5851bef5ad979da5830f68b2_image_1462826805_0031.jpg
tour_steps.image[2] | 1280x720 | ./frontend/src/images/experiments/universal-search/experiments_experimenttourstep/1/d/1d414ba2fc88a188b6f74ea79de908e9_image_1462826805_0789.jpg

</details>

### Observations:
- `thumbnail` images are all consistent at 192x192.
- `image_twitter` image is inconsistent size for no-more-404s.yaml (192x192 vs 560x300).
- `image_facebook` image is similarly inconsistent for no-more-404s.yaml (192x192 vs 1200x630).
- `contributor.avatar[]` image sizes are all over the place (64x64 up to 500x500, and in some cases aren't even square; 371x341). 
- `details.image[]` image sizes are not super consistent. Some are 1280x1240, some are 1691x1380, some are 870x413.

**Comment by ghost** [comment]
We're not sure how to do this, so moving to backlog

**Comment by johngruen** [comment]
WONTFIX
