### ISSUE TITLE
If browser language is set to German/Germany [de-de], Cliqz experiment is available but the Test Pilot pages are displayed in English

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2017]
[Notes]:
- The issue is also reproducible for all the others locales of German language.

[Affected versions]:
- Firefox 50.1.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on the profile.
- Have the German/Germany [de-de] and English [en] languages set in "about:preferences#content".

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.firefox.com" page.
2. Observe the page language and the available experiments.

[Expected result]:
Depending on the desired behavior
- The page is displayed in German and the Cliqz experiment is available since [de-de] is a variation of default German [de] language.
or
- The page is displayed in English [en] (jumps to second in list) and Cliqz is not available since we don't have German [de-de] language localization.

[Actual result]:
- The page is displayed in English and the Cliqz experiment is available.

[Additional Notes]:
- The same behaviour can be observed for most languages that have language variations from default. Probably for all of them.
- Here is a screen recording with the issue: https://goo.gl/ItZTq4.

**Comment by flodolo** [comment]
If you set the browser to "German (de)" does it work as expected?

Default accept-language for German users would be: 'de, en-US, en'.

**Comment by SoftVision-CosminMuntean** [comment]
> If you set the browser to "German (de)" does it work as expected?

Yes, if the browser language is set to German [de] everything works as expected.

**Comment by ckprice** [comment]
Top 3 locales over the last week (% of traffic)

1. de 66.92%
2. en-us 19.85%
3. **de-de 5.27%**

So some traffic, but not the majority of our German users.

**Comment by pdehaan** [comment]
@ckprice @johngruen Should we do a similar en-US=>en copy-pasta for de=>de-de?

**Comment by johngruen** [comment]
@pdehaan maybe, might want to think about being more formal since it's the second time this is happening

**Comment by flodolo** [comment]
I think we need a better solution, there are plenty of other locales in this situation.

Also CC @stasm in case he has any ideas to solve this.

**Comment by flodolo** [comment]
Also filed https://bugzilla.mozilla.org/show_bug.cgi?id=1331721

**Comment by ghost** [comment]
I asked for a priority/timeline in the bug.  If it's a long ways out, let's do a quick fix on our end.

**Comment by jaredhirsch** [comment]
Is it possible that we could just split the locales here and pick up 'de' if 'de-de' is missing? https://github.com/mozilla/testpilot/blob/master/frontend/src/scripts/locale.js#L4-L5

**Comment by ghost** [comment]
The rules for all that are [probably overly] complicated, but it sounds reasonable to me.  I'm in favor.

**Comment by stasm** [comment]
The rules are indeed very complicated :) I just landed the proper fix to [bug 1331721](https://bugzilla.mozilla.org/show_bug.cgi?id=1331721): l20n will use the language negotiation algorithm defined by ECMA 402.  Can you try using the following changeset and seeing if it helps? https://github.com/l20n/l20n.js/commit/c3e35c497b5168270cc629f0ee6996cb34033cb1

**Comment by ghost** [comment]
Let's do the hack for this sprint and upgrade to the new L20n next sprint

**Comment by pdehaan** [comment]
This should be fixed via #2149

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on stage server. Marking as verified.

**Comment by pdehaan** [comment]
The associated PR was merged, but doesn't work in testpilot.dev, but _should_ work in stage/prod. Closing.
