### ISSUE TITLE
Promote experiments at the end of tour

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#2020]
Per discussion with John, in order to increase the install rate of all experiments, we propose to provide users more experiments promotion at the end of tour. You can find the link below for the prototype. Please let us know if any questions or the feasibility issues, thanks.

https://mozilla.invisionapp.com/share/Y79IJHBK5#/214523834_Tour_1-1_Tour

![more experiments](https://cloud.githubusercontent.com/assets/18019946/21924106/864baffa-d9b2-11e6-8956-8603c93f8cac.png)

**Comment by johngruen** [comment]
@chenmorpheus, closing this for now since we're probably gonna change tours anyway
