### ISSUE TITLE
Kabyle locale

### ISSUE THREAD

**Issue by MohammedBelkacem** [mozilla/testpilot#2022]
Hi,
The kab Localization of Test Pilot reached 95%. We will reach 100% today. Please would you like enable it for release?
Thanks

**Comment by johngruen** [comment]
Sure!

**Comment by MohammedBelkacem** [comment]
Thanks johngruen

**Comment by MohammedBelkacem** [comment]
Hi,
I still getting it in French :) . No Test Pilot in Kabyle yet!!

**Comment by chuckharmston** [comment]
@belkacem77 We just tagged and released it to [our staging environment](https://testpilot.stage.mozaws.net) this evening, and are on schedule to deploy it this coming Tuesday.

I just checked our staging environment to ensure that everything is in order, and see that `kab` is included in the appropriate meta tag:

```
<meta name="availableLanguages" content="en-US,en,cs,de,dsb,es-ES,fr,fy-NL,hsb,hu,it,ja,kab,nl,pt-BR,ru,sv-SE,uk,zh-CN,zh-TW">
```

And that the string files are also present:

https://testpilot.stage.mozaws.net/static/locales/kab/app.ftl
https://testpilot.stage.mozaws.net/static/locales/kab/experiments.ftl

It should be ready to go on Tuesday!

**Comment by MohammedBelkacem** [comment]
Wawo!!!! Yes I  got it on staging. I will share it right now. Thaaaaaaaaaanks!!!!

**Comment by flodolo** [comment]
> Wawo!!!! Yes I got it on staging. I will share it right now. Thaaaaaaaaaanks!!!!

Please don't share the link to stage, that's for testing. Wait for the announcement on Tuesday ;-)

**Comment by MohammedBelkacem** [comment]
Ok!
