### ISSUE TITLE
Make Sass more good

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#203]
Basically our Sass is not totally enterprise grade. Adding/changing some things to make it a bit cleaner.
- [ ] #291
- [ ] #290
- [ ] #289
- [ ] #306
- [ ] #307

**Comment by pdehaan** [comment]
I've been poking around with https://www.npmjs.com/package/gulp-pleeease lately. Seems pretty good, and bundles in the autoprefixer, media query combining, and other tricks automatically. May be worth investigating and seeing if it produces smaller/better final CSS.

**Comment by johngruen** [comment]
@pdehaan 👍

**Comment by pdehaan** [comment]
After a wee bit of hacking locally, this may work and reduce a few dependencies:

``` js
const pleeease = require('gulp-pleeease');
...
gulp.task('styles', function () {
  return gulp.src(SRC_PATH + 'styles/**/*.scss', {base: '.'})
    .pipe(sourcemaps.init())
    .pipe(sass({
      includePaths: normalize.includePaths
    }))
    .pipe(pleeease({
      autoprefixer: {browsers: 'last 2 versions'},
      minifier: false,
      mqpacker: true,
      opacity: false,
      out: 'main.min.css',
      sourcemaps: true
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(DEST_PATH + 'styles'));
});
```

And here are a few rough and probably unreliable stats:

```
BEFORE:
main.css (non-minimized):
  832 lines, 23908 characters
main.min.css (minimized -- 18 @media queries):
  1 line, 17109 characters

PLEEEASE:
main.css (non-minimized):
  770 lines, 20295 characters

main.min.css (minimized, mqpacker -- 3 @media queries):
  1 line, 14945 characters
```

Of course, probably all those are useless and we'd only care about gzipped sizes since thats's what we'd be deploying.

**Comment by meandavejustice** [comment]
After a quick look at pleeease(without really knowing anything about it) it looks like it has quite a bit of dependencies. Including stylus, postcss, node-sass, etc... Just pointing out that if the goal is to reduce dev dependencies, this might not be the best way forward.

Otherwise, glad to see it reduce our filesizes.

**Comment by johngruen** [comment]
@pdehaan @meandavejustice this is mostly to make sure we do pass to reduce redundancy/cruft after the Mozlando sprint to make sure things scale and are intelligible to others.

**Comment by pdehaan** [comment]
Ref: #306

**Comment by pdehaan** [comment]
Ref: #307

**Comment by johngruen** [comment]
@pdehaan turning this into a tracking bug for sass polish issues

**Comment by johngruen** [comment]
@pdehaan meh, i'm just gonna close this.
