### ISSUE TITLE
Enabled vs Disabled vs Installed vs Uninstalled

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#204]
In our addon we currently only server two states: Installed(and enabled) and Uninstalled. The experiment detail pages say `enable` and `disable`. Is there ever a time when we want to keep around experiments in the disabled state? If so, we will need to add some ui to allow users to uninstall disabled addons.

**Comment by jaredhirsch** [comment]
Users can manage addons, including idea town experiments, from about:addons; we don't necessarily need to build any new flows for the other states. It might make more sense for the website to say 'install' and 'uninstall', not 'enable' and 'disable'.

**Comment by meandavejustice** [comment]
@6a68 I think that makes the most sense. Will be a quick fix. Does that sound good to @johngruen and @bryanbell ?
