### ISSUE TITLE
Experiments shown as enabled after uninstalling TestPilot

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#2041]
Both the addon and experiment get uninstalled but the app shows the experiment as enabled

![bug](https://cloud.githubusercontent.com/assets/87619/22129700/8104f174-de5c-11e6-8459-305037dfc63b.gif)

**Comment by SoftVision-CosminMuntean** [comment]
We have seen this issue a while ago also, and it's already logged in #1484.

**Comment by dannycoates** [comment]
dupe
