### ISSUE TITLE
Add `example` env to ground control

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2049]
Since @fzzzy added an env for previewing one-click install, we should add a new creature to ground control for more fast env switching goodness. @dannycoates got any more animal emojis over there?

**Comment by lmorchard** [comment]
We should remove the `static-dev` & `static-stage` envs from there while we're at it. The example env has been around about as long as the static-* envs have been gone

**Comment by dannycoates** [comment]
maybe we should just make 'example.com' the new local and stop using 'testpilot.dev' ?

**Comment by fzzzy** [comment]
Yes, using example.com is necessary for one-click install, that's why I switched to it from testpilot.dev which is not whitelisted. I changed the quickstart docs already, but maybe there are more places to change.

**Comment by fzzzy** [comment]
The add-on rewrite switched local to use example.com, and got rid of the example env, so we don't need to do this any more.
