### ISSUE TITLE
Experiments are wrongly displayed as enabled when Test Pilot is uninstalled

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2050]
I think this comes from the one-click install stuff possibly jumbling up application state:

## STR

1. in `example.com` env, enable Page Shot (or other)
2. uninstall test pilot

## Result
The page shot add-on is uninstalled but shows up as installed

## Expected
All Test Pilot experiments should be uninstalled and their state should be reflected as such throughout the UI

**Comment by johngruen** [comment]
@fzzzy here's a screen recording...

Refreshing gets the state back to looking right, so i imagine we just need to dispatch an event somewhere on uninstall to make sure that happens.

https://www.dropbox.com/s/30ld2z9z3ov98yi/Single%20Click%20Intstall%20-%20Bad%20State.mov?dl=0

**Comment by fzzzy** [comment]
This was a bug before the one-click install (can repro on prod right now), but I've managed to fix it regardless.

**Comment by johngruen** [comment]
woot!

**Comment by SoftVision-CosminMuntean** [comment]
This issue was already logged in #1484 a while ago. But since yours was already fixed, I am confirming the fix here and I will close the above one based on this.
