### ISSUE TITLE
Experiment Install sometimes hangs with one-click install method

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2051]
I'm seeing a high rate of add-on install failure with the new one-click method. Noticed this more on Page Shot and Min Vid, though that might be a coincidence. No errors in the web console, but the browser console is showing this: 

<img width="1012" alt="screen shot 2017-01-24 at 11 30 18 am" src="https://cloud.githubusercontent.com/assets/3323249/22256571/2b3e6ce0-e229-11e6-8e3e-51c406c30da4.png">

**Comment by fzzzy** [comment]
Are you testing locally, on dev, or on stage?

**Comment by johngruen** [comment]
locally

**Comment by dannycoates** [comment]
Here's my theory...

The addon takes a certain amount of time to initialize. On startup it makes a request to get the experiments.json from the server. Before that request is finished it knows nothing, so if an `install-experiment` comes in during that time, [this code](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L159) will return false and just ignore it.

**Comment by johngruen** [comment]
@dannycoates did a test where i disabled my internet before clicking the add-on install. I see an actual error in this case, not just an infinite barberpole
<img width="1305" alt="screen shot 2017-01-24 at 2 58 32 pm" src="https://cloud.githubusercontent.com/assets/3323249/22264392/c342347e-e245-11e6-82a7-0dc6abfc704d.png">
