### ISSUE TITLE
The add-on should not set extensions.webapi.testing.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2061]
https://github.com/mozilla/testpilot/blob/f8cf62329d0245de58c2ea6acb7912bd7f244632/addon/index.js#L71

This is a pref that should only be set by users who understand what it is, what it does, and the risks it may carry.

**Comment by ghost** [comment]
The new add-on doesn't do this, so this will be fixed next sprint.

**Comment by dannycoates** [comment]
closed by #2108
