### ISSUE TITLE
'history 4.x' not supported in 'react-router-redux'

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2064]
I started poking at all the greenkeeper pulls and came across these errors after updating packages locally

```
TypeError: createHistory is not a function
TypeError: history.getCurrentLocation is not a function
```

Found the following https://github.com/reactjs/react-router-redux/issues/491

> We don't support history 4.0 in this library.

It's at least used in [`/frontend/app/index.js`](https://github.com/mozilla/testpilot/blob/639eb04f4d9e263450c4dd23e60d437ae3d841d7/frontend/src/app/index.js#L11). Is there something else we can use here?

This probably blocks #2011 and #2004.

**Comment by jaredhirsch** [comment]
Good find @ckprice. I bumped that react-router-redux bug to ask what's up.

**Comment by jaredhirsch** [comment]
Response in that react-router bug indicates we should wait to update `history` until `react-router` hits 4.0:

> React Router doesn't currently support history 4.0. It will in React Router 4.0, but that is not yet released and will require a complete rewrite for this library.

**Comment by ghost** [comment]
@6a68 any update on react-router?

**Comment by pdehaan** [comment]
[**react-router**](https://www.npmjs.com/package/react-router) is still at 3.0.2.

**Comment by ghost** [comment]
4.0.0 is released now, but we're planning on dropping react-router altogether.  That issue is filed. #2260
