### ISSUE TITLE
Setting private  browsing autostart to true in about:config prevents Test Pilot from working

### ISSUE THREAD

**Issue by cbernardi** [mozilla/testpilot#2065]
I had `browser.privatebrowsing.autostart;true` set in `about:config`. This did not prevent the installation from working, it just prevented any features from appearing (ie bar icon and extensions). Setting it back to false and restarting fixed the problem.

**Comment by cbernardi** [comment]
If I change the setting back to `true` and restart, the add-on appears to not be there but shows up in the add-ons list.

**Comment by ckprice** [comment]
Thanks for filing! Test Pilot currently doesn't support private browsing mode.

https://github.com/mozilla/testpilot/blob/master/docs/faq.md#does-test-pilot-work-in-private-browsing-mode
