### ISSUE TITLE
Experiment links and "Your Privacy" sections are hidden in mobile view when Test Pilot is not installed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2068]
[Notes]:
- It's not necessarily an issue but  

[Affected versions]:
- Firefox 50.1.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox with a new profile and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click on one of the available experiments cards.
3. Observe the experiment links and "Your Privacy" sections.
4. Resize the browser to mobile view and observe again both the sections.

[Expected result]:
- Both sections are correctly displayed no matter the window size. 

[Actual result]:
- Both sections are hidden when browser window is resized to mobile view. 

[Notes]:
- Here is a screen recording of the issue - https://goo.gl/Ho3vlj.

![no links and privacy](https://cloud.githubusercontent.com/assets/17258026/22333509/3c758496-e3df-11e6-8e0b-2a3e4274f8a3.png)

**Comment by ghost** [comment]
This is done on purpose
