### ISSUE TITLE
Turn off greenkeeper in favor of making a ticket to run "npm update" every sprint

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2075]
This will help to cut down on pr overload. If we manage to reduce our dependencies a lot, which we should try to do, we can turn greenkeeper back on.

I propose we instead create one ticket per sprint to run "npm outdated". This ticket should be landed as close to possible to the start of the sprint to shake out any issues with updated packages. This ticket should be assigned to someone on the team in a round-robin fashion so it doesn't always fall on one person. There should be considerable peer pressure to close the ticket promptly :)

I also suggest we keep a document which notes the reasons for pinning certain packages to certain versions. It is important to keep this document up to date so that each sprint, the assignee can assess whether those reasons still apply, or the package is safe to be upgraded.

**Comment by jaredhirsch** [comment]
👍 I'm in favor of this proposal.

For the first few sprints, we could just fix one or two related dependencies, since there are so many major updates to deal with.

@lmorchard You've looked through the greenkeeper PRs a bit; any thoughts on a good first cluster of stale packages to update?

**Comment by pdehaan** [comment]
My favorite commands/modules are `npm outdated --depth 0` and [`nsp check`](https://www.npmjs.com/package/nsp) (separate module which checks for known vulnerable modules).

```sh
➜  testpilot git:(master) $ npm outdated --depth 0
Package                 Current  Wanted  Latest  Location
babel-eslint              6.1.2   6.1.2   7.1.1  testpilot
babel-plugin-istanbul     2.0.3   2.0.3   4.0.0  testpilot
browserify               11.2.0  11.2.0  14.0.0  testpilot
del                       2.0.2   2.0.2   2.2.2  testpilot
doctoc                    1.0.0   1.0.0   1.2.0  testpilot
es6-promise               3.3.1   3.3.1   4.0.5  testpilot
eslint-config-airbnb     10.0.1  10.0.1  14.1.0  testpilot
eslint-plugin-import     1.16.0  1.16.0   2.2.0  testpilot
eslint-plugin-jsx-a11y    2.2.3   2.2.3   4.0.0  testpilot
gulp-autoprefixer         2.3.1   2.3.1   3.1.1  testpilot
gulp-cache               0.2.10  0.2.10   0.4.5  testpilot
gulp-connect              2.3.1   2.3.1   5.0.0  testpilot
gulp-cssnano              2.1.0   2.1.0   2.1.2  testpilot
gulp-if                   1.2.5   1.2.5   2.0.2  testpilot
gulp-rev-all             0.8.24  0.8.24   0.9.7  testpilot
gulp-sourcemaps           2.2.3   2.2.3   2.4.1  testpilot
history                   2.1.2   2.1.2   4.5.1  testpilot
js-cookie                 2.1.1   2.1.1   2.1.3  testpilot
node-normalize-scss       1.1.1   1.1.1   1.4.0  testpilot
react-router              2.8.1   2.8.1   3.0.2  testpilot
react-router-redux        4.0.7   4.0.8   4.0.8  testpilot
remarkable                1.6.2   1.6.2   1.7.1  testpilot
sass-lint                 1.5.1   1.5.1  1.10.2  testpilot
through2                  2.0.1   2.0.1   2.0.3  testpilot


➜  testpilot git:(master) $ nsp check
(+) No known vulnerabilities found
```

For FxA, we would break the Travis-CI build if there were known vulnerable modules. And we'd either have to upgrade those modules (if there was a fixed module available), or you could explicitly ignore certain modules from nsp scans in an [.nsprc](https://github.com/mozilla/fxa-content-server/blob/master/.nsprc) file.

**Comment by fzzzy** [comment]
Breaking the build if there are vulnerable modules seems like a really good idea.

**Comment by chuckharmston** [comment]
> Breaking the build if there are vulnerable modules seems like a really good idea.

100% disagree. Builds should be deterministic, and should never be able to break due to external factors (HTTP requests, new versions of dependencies, etc).

**Comment by fzzzy** [comment]
Ok chuck, that makes sense too :)

**Comment by dannycoates** [comment]
I'll troll to say that if we really want deterministic builds we should use npm shrinkwrap or yarn lock :trollface:

**Comment by chuckharmston** [comment]
¯\\\_(ツ)\_/¯ I'd be fine with that.

**Comment by pdehaan** [comment]
Also, apparently greenkeeper supports ignoring certain modules (if we want to ignore updates to **react-router**, for example).
Ref: `https://github.com/greenkeeperio/greenkeeper/issues/132`

Basically in our package.json, we'd just add:

```json
{
  "greenkeeper": {
    "ignore": [
      "eslint-plugin-jsx-a11y",
      "eslint-config-airbnb",
      "react-router"
    ]
  }
}
```

**Comment by ghost** [comment]
Let's turn off greenkeeper!

**Comment by ghost** [comment]
Ok, I think this is off now.  I'll see about deleting all those branches too.

**Comment by pdehaan** [comment]
This also looks interesting: http://npm.im/npm-check-updates

Looks like bumping all the version numbers in package.json ay be as simple as `% ncu -u` (if installed globally, or `% $(npm bin)/ncu -u` if installed locally... or we just add this as a devDep and create a "script" in package.json to bump all version numbers).

**Comment by pdehaan** [comment]
Or... http://npm.im/updtr may help guard against rogue module updates:

> _"Based on `npm outdated`, **updtr** installs the latest version and runs `npm test` for each dependency. If the test succeeds, **updtr** saves the new version number to your `package.json`. If the test fails, however, **updtr** rolls back its changes."_

**Comment by fzzzy** [comment]
@pdehaan I ended up using ncu which I think you mentioned in another bug. Thanks a lot, I think it will work fine for now.
