### ISSUE TITLE
Experiment padding is too narrow on non-Firefox browsers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2080]
Found in https://testpilot.dev.mozaws.net/__version__ (223e0d18236ae11be58b77e89f0240278cbb62c3):

```js
{
  commit: "223e0d18236ae11be58b77e89f0240278cbb62c3",
  version: "",
  source: "https://github.com/mozilla/testpilot",
  build: "https://circleci.com/gh/mozilla/testpilot/2917"
}
```

---

![firefox_test_pilot_-_page_shot](https://cloud.githubusercontent.com/assets/557895/22352934/05ece718-e3d3-11e6-9568-45948dee3a59.png)

![about](https://cloud.githubusercontent.com/assets/557895/22352951/12d02d3c-e3d3-11e6-9ff9-630506b84d6c.png)

### versus

![firefox_test_pilot_-_page_shot](https://cloud.githubusercontent.com/assets/557895/22352964/21da4d6c-e3d3-11e6-842d-2c11ab16801e.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/22352975/2d39ff18-e3d3-11e6-8797-1828a1fd7a7d.png)

**Comment by fzzzy** [comment]
Fixed by https://github.com/mozilla/testpilot/pull/2152
