### ISSUE TITLE
"Install Test Pilot & Enable Universal Search" button is wrongly displayed on Universal Search past experiment page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2085]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox with a new profile and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Click the "View Past Experiments" button under the current available experiments.
3. Click the Universal Search experiment card.
4. Observe the top part of the past experiment page.

[Expected result]:
- Same "Install the Test Pilot Add-on" green button from homepage is displayed on the experiment page.
Or
- The add-on install button is not available on past experiment page.

[Actual result]:
- "Install Test Pilot & Enable Universal Search" button is wrongly displayed on the experiment page.

[Notes]:
- Here is a screen shot with the issue:
![universal serach](https://cloud.githubusercontent.com/assets/19226534/22366182/015a489c-e484-11e6-8ffc-0589f96bfa9a.png)

**Comment by johngruen** [comment]
Let's just use the normal short header, with no install button

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on dev server. Marking as verified.
