### ISSUE TITLE
The "Onboarding" page is not opened after Test Pilot is installed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2086]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Click the "Install Test Pilot" green button.
3. Observe the behavior.

[Expected result]:
- Test Pilot is successfully installed and the "Onboarding" page is opened in a new tab.

[Actual result]:
- Test Pilot is successfully installed but the "Onboarding" page is not opened.

**Comment by johngruen** [comment]
This is the expected behavior for now. We are re-working onboarding in #2066

**Comment by ghost** [comment]
We're adjusting the flow right now so this is expected behavior.  Thanks for filing.
