### ISSUE TITLE
The "moz://a", "GitHub" and "Twitter" logo buttons are wrongly rendered in black color on Edge browser

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2087]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A Windows 10 PC with Edge browser is available. 

[Steps to reproduce]:
1. Open Edge browser and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Scroll to the bottom of the page.
3. Observe the Moz://a, GitHub and Twitter logo buttons from the footer area.

[Expected result]:
- All three logo buttons are correctly rendered in white color on Edge browser. 

[Actual result]:
- All three logo buttons are wrongly rendered in black color on Edge browser.

[Notes]:
- Here is a screenshot of the issue:

![black rendering](https://cloud.githubusercontent.com/assets/17258026/22374787/4f97df2a-e4b0-11e6-97d6-4be0256ab51b.png)

**Comment by johngruen** [comment]
![4593531893_f67a757fa1](https://cloud.githubusercontent.com/assets/3323249/22376975/35bc0860-e47e-11e6-994c-238a6bb0285a.jpg)

**Comment by SoftVision-PaulOiegas** [comment]
Edge is a proud owner of white logos. Marking as verified fixed.
