### ISSUE TITLE
Abstract `#main-footer` into a view

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#209]
Right now the `#main-footer` links are loaded statically in the index template. Since we're using flex box, this causes a gnarly little flash while the ampersand-y parts of the DOM rerender as views are swapped out. Even though the footer persists across all pages, we should load it in dynamically to mitigate this issue.

**Comment by johngruen** [comment]
#209

**Comment by lmorchard** [comment]
Sounds like merging #210 fixed this - reopen if I'm mistaken!
