### ISSUE TITLE
Experiment auto enable hangs if you wait more than ~5 seconds before allowing Test Pilot installation from doorhanger

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2090]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser with a new profile and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Click on one of the active experiments cards.
3. Click on "Install Test Pilot & Enable <experiment_name>" button.
4. Wait for more than 5 seconds before "Allowing" installation.
5. Click "Allow" and "Install".
6. Observe page behavior.

[Expected result]:
- Test Pilot is installed, you are redirected to experiment details page and experiment is auto enabled.

[Actual result]:
-  Test Pilot is installed, you are redirected to experiment details page but the experiment hangs on "Enabling..." state.

[Notes]:
- Would this occur on a bad internet connection even on production ? I'm thinking if the installation would hang for a few seconds due to internet connectivity issues.
- Here is a screen recording of the issue: https://goo.gl/0eqq7s
- It seams that this occurs if the **"Unhandled promise rejection < unavailable >"** occurs.

![error for auto enable](https://cloud.githubusercontent.com/assets/17258026/22379054/6bbbb540-e4c0-11e6-923a-9015f79898b4.png)

**Comment by fzzzy** [comment]
I don't understand why firefox is requesting to allow installation on stage. It should be whitelisted and able to install without any confirmation from the user.

**Comment by chuckharmston** [comment]
Is there any chance that `extensions.webapi.testing` isn't `true`?
