### ISSUE TITLE
A/B Test one click install flow from the Test Pilot home page

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2092]

**Comment by chuckharmston** [comment]
Relevant: https://mail.mozilla.org/pipermail/testpilot-dev/2016-November/000331.html

**Comment by johngruen** [comment]
@fzzzy mockups: 
## large
![new header -- large](https://cloud.githubusercontent.com/assets/3323249/22517376/df512f08-e876-11e6-911f-2ddd7c8b0e75.png)
## medium
![new header -- medium](https://cloud.githubusercontent.com/assets/3323249/22517374/df4c0c4e-e876-11e6-8347-3d15844f5544.png)
## small
![new header -- small](https://cloud.githubusercontent.com/assets/3323249/22517373/df4b081c-e876-11e6-85c4-3770d42245c5.png)

Requirements:
- [ ] it should appear for 10% of users
- [ ] it should pass a custom GA event to differentiate itself from normal install (I can provide the appropriate event details)
- [ ] it should redirect to the experiment onboarding flow and experiment details page

**Comment by johngruen** [comment]
@fzzzy if you can get all the state stuff in place i can probably do the sass on this.

**Comment by fzzzy** [comment]
We're going to hold off on making ui changes to test pilot for a while.

**Comment by chuckharmston** [comment]
This has been shipped.
