### ISSUE TITLE
Verify addon installation doesn't double-fire 'enabled' telemetry ping

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2095]
From https://github.com/mozilla/testpilot/issues/1855#issuecomment-275737599:

I do have some doubts about the addon code, as it seems to [double-fire the 'enabled' ping](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L332) both when an addon is installed, and when it's enabled, but I need to verify that, which I'll do in a separate bug.

Stuff to double-check:
- Make sure upgrades either fire no event, or one 'enabled' and one 'disabled'
- Make sure installation fires exactly one 'enabled' event
- Make sure uninstalling fires exactly one 'disabled' event
- Make sure disabling fires exactly one 'disabled' event
- Make sure enabling fires exactly one 'enabled' event

**Comment by ghost** [comment]
Dupe of #1855
