### ISSUE TITLE
Related experiments list on experiments page shows current experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2096]
Found in http://testpilot.dev.mozaws.net/__version__ (9ccfdec1a5bdd8bce53cebd3ebb19d3c69946702):

```json
{ "commit": "9ccfdec1a5bdd8bce53cebd3ebb19d3c69946702",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/2971" }
```

---

### Steps to reproduce:
1. Go to http://testpilot.dev.mozaws.net/experiments/tracking-protection
2. Scroll down to "Try out these experiments as well".
3. Look at the listed experiments.

### Actual results:
I'm on the "Tracking Protection" experiment page, but it points to the Tracking Protection experiment.
Oddly, the related experiment list does not list the Page Shot experiment.

### Expected results;
The experiment details page should not link to itself in related experiments.

---

![firefox_test_pilot_-_tracking_protection](https://cloud.githubusercontent.com/assets/557895/22388839/83c53158-e497-11e6-8521-2a3e397f18a3.png)

**Comment by dannycoates** [comment]
i can't repro anymore
