### ISSUE TITLE
Newsletter signup is wrongly performed without checking the privacy agreement checkbox on Safari browser

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2102]
[Affected versions]:
- Safari v10.0

[Affected Platforms]:
- All Mac OS

[Steps to reproduce]:
1. Open Safari browser and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Scroll the page until Newsletter section is reached.
3. Enter a valid email address.
4. Leave the checkbox unchecked and click on "Sign Up Now" button.
5. Observe page behavior.

[Expected result]:
- You are prompted to check the agreement checkbox if you want to continue.

[Actual result]:
- The subscribe is wrongly performed and the "Thanks" message is displayed.

[Notes]:
- The subscription email is sent and email is subscribed.
- This reproduces on all servers, including production.
- This does not reproduces on Firefox (Mac OS & Win), Chrome (Mac OS & Win), Edge (Win) or Opera (Win) browsers.

**Comment by ckprice** [comment]
Safari usage over last 30 days is 0.65% of total users. Not a blocker for today, but let's do next sprint.

**Comment by SoftVision-PaulOiegas** [comment]
It seems to be fixed. The user is now prompted with "Please check this box if you want to proceed." error in red characters, when he tries to sign up without checking the box. 👍
