### ISSUE TITLE
CSS + Component Cleanup

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2104]
I've started working on a branch that removes a lot of dead Sass and abstracts a few components into simple functional elements. Not sure if this will go anywhere but my goals are as follows:

- clear out no-longer-used Sass (which is surprisingly plentiful)
- abstract commonly repeated HTML blocks (copter, responsive-content-wrapper) into stateless functional components.
- simplify the relation between React and Sass using BEM syntax for the new component styles.
- provide documentation about how to use the above setup

The big idea is reduce some of the complexity and redundancy currently in our style and JSX code, and to make it easier to create new blocks of content with a greatly simplified set of tools.

**Comment by chuckharmston** [comment]
Perhaps this is the time to think about #1363?

**Comment by johngruen** [comment]
@chuckharmston maybe, but I'm not totally clear the cost-benefit of doing a full migration. Lemmie get my PR in (should be this week) and we can discuss more.
