### ISSUE TITLE
Implement Fancy New Install Toggles on Experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2105]

**Comment by johngruen** [comment]
@fzzzy here's the code from addons, there's lots of state passing through these things:

here's the component
https://github.com/mozilla/addons-frontend/blob/master/src/core/components/InstallSwitch/index.js

and here's where it interacts with mozAddonManager:
https://github.com/mozilla/addons-frontend/blob/master/src/core/addonManager.js

working to run down the CSS

**Comment by johngruen** [comment]
For now...here's the UX spec:

![switch spec](https://cloud.githubusercontent.com/assets/3323249/22444744/457d71f8-e712-11e6-8232-6395520703f2.png)

**Comment by johngruen** [comment]
Here's the css from AMO: https://github.com/mozilla/addons-frontend/tree/master/src/ui/components/Switch

**Comment by johngruen** [comment]
@fzzzy, how would you feel about doing this as a 10% A/B test as well?

**Comment by fzzzy** [comment]
@johngruen Sure, I think this would be a good a/b test.

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen 
1. What if the download or install fails ? How would that state be displayed on the new toggle functionality?
- I assume the knob will move back to the left side and switch background will become red ? Or do you guys have something else in mind ?

2. In what cases the switch button would be in "Inactive state" ?
- Manually disabled addon from "about:addons" page for the green state ? 
- Graduated experiment for gray state ?

**Comment by ghost** [comment]
John is worried about this being on the home page, but the details page is good

**Comment by fzzzy** [comment]
Ok. For some reason I thought this was for on the homepage...

**Comment by fzzzy** [comment]
I think we've decided to abandon this idea.
