### ISSUE TITLE
Make Experiment details content the same if TXP is installed or not

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2109]
[Notes]:
- Now that we have one click install, the user should also see the incompatible add-ons massage before installing Test Pilot together with an experiment that has incompatibilities.

[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Tabs Group add-on was previously installed on a new clean profile.

[Steps to reproduce]:
1. Open the profile from prerequisites and navigate to https://testpilot.stage.mozaws.net.com.
2. Click on Tab Center experiment card.
3. Observe the Tab Center experiment page.

[Expected result]:
- "This experiment may not be compatible with add-ons you have installed" warning message is displayed on the page.

[Actual result]:
- No warning message is displayed on the page.

![incompatible add-ons massage](https://cloud.githubusercontent.com/assets/19226534/22464569/30cd1e4e-e7c0-11e6-8080-1089f0a30d98.png)

**Comment by dannycoates** [comment]
If we do this we should use mozAddonManager to check which ones are installed, not just show the full list.

**Comment by johngruen** [comment]
We should just make the `details-content` the same for users with TXP not installed as it is for users with TXP installed

**Comment by ckprice** [comment]
Could be a dup of #2394 or something else @johngruen to search.

**Comment by SoftVision-PaulOiegas** [comment]
Blasphemy, our issue is older ! Just kidding. 😄 Right now, the incompatible message is only displayed if you have Test Pilot add-on installed. 
@ckprice Not sure if it's a dupe, but I think that what you guys are trying to do on #2394, will probably cover our case too. But maybe we should leave this open as a "depends on" so we won't forget to check this scenario when you guys implement it ?

**Comment by fzzzy** [comment]
From looking at the code, I believe this issue has already been fixed. It is hard to test since I don't think we have any experiments which set the incompatible addons field right now. I think we should close this.
