### ISSUE TITLE
Merge /package.json and /addon/package.json?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2113]
Should we merge [/package.json](https://github.com/mozilla/testpilot/blob/master/package.json) and [/addon/package.json](https://github.com/mozilla/testpilot/blob/master/addon/package.json)?

There are a bunch of packages that overlap between the two package.jsons, but also, it may make linting and building easier since we wouldn't need as many `$ cd addon` and `$ cd ..` in the build scripts.

Plus, it'd let us easily/incrementally add `// @flow` definitions into the rest of the Test Pilot frontend scripts so we can slowly add data types [if we feel like it].
It'd also make it easier to use greenkeeper to manage addon dependencies, etc.

**Comment by dannycoates** [comment]
I think we can definitely improve the build process and maybe do some dep sharing, but we can't get rid of `addon/package.json` completely because `jpm` needs one to build the xpi.

**Comment by pdehaan** [comment]
But couldn't we have **jpm** as a devDependency in the root /package.json and just set the `--addon-dir` option to the /addon/ directory?

```sh
> $(npm bin)/jpm xpi --addon-dir=addon
JPM [info] Starting jpm xpi on Test Pilot
JPM [info] updateRDF created at /Users/pdehaan/dev/github/mozilla/testpilot/addon/@testpilot-addon-1.0.0.update.rdf
JPM [info] Successfully created XPI at /Users/pdehaan/dev/github/mozilla/testpilot/addon/testpilot-addon.xpi (3138ms)
```

**Comment by lmorchard** [comment]
IIRC, `jpm` uses details from the `package.json` in that `--addon-dir` (e.g. `updateURL`, `updateLink`, `icon`, `permissions`) and I'm not sure it would pick them up from the one in the root dir. Might be worth some experimentation though

**Comment by ghost** [comment]
We talked about this in the triage and decided to wontfix this because:
* there are other higher value things we could refactor
* we're a bit nervous about zipping these together because we might have to unzip them
* Our build process is already kinda complicated and, while this would get rid of some cd's, we didn't think this would end up in overall less complexity
