### ISSUE TITLE
UI issues on Test Pilot website using when using Firefox browser version lower than 45.0

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2117]
1. "We're building next-generation features for Firefox. Install Test Pilot to try them!" sentence from experiment page is missing.
![missing text 1](https://cloud.githubusercontent.com/assets/17258026/22517982/9c7545e2-e8b3-11e6-8dbc-bbbe43c7d8cd.png)

2. Number of participants wrongly displayed on experiments cards and not displayed at all on experiment page.
![participants](https://cloud.githubusercontent.com/assets/17258026/22518298/c8c977d4-e8b4-11e6-9f1c-94c5de7b3852.png)

3. "You can learn more about the data collection for <experiment_name> here." message under "Your Privacy" section is missing.
![missign text 2](https://cloud.githubusercontent.com/assets/17258026/22518555/b32c62fa-e8b5-11e6-8963-f14693b56be2.png)

4. The "Install Firefox" and "Update Firefox" buttons have the old design. Should we have the new one on these too ?

**Comment by ghost** [comment]
We officially support >49 currently
