### ISSUE TITLE
Bump min Firefox version to 49?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#2125]
Bumping our min version to 49 would let us fully utilize `mozAddonManager`. We'd get at least one nice feature and could clean up a few hacks. We'd also be able to shrink the addon even more.

* detect when testpilot is installed but disabled (https://github.com/mozilla/testpilot/issues/1335#issuecomment-276720154)
* sever the PageMod comm link between the webpage and addon
* make improving our error handling easier (#1335)

**Comment by johngruen** [comment]
@dannycoates let's do this, also gives us better assurance RE webExtension support

**Comment by johngruen** [comment]
So right now this would effect right at 6.2% of our Firefox population on 45,46,47 and 48. Seems like a reasonable tradeoff, but we should also add some improved messaging about updating for people with older browsers installed
