### ISSUE TITLE
Localization randomly breaks on the Test Pilot website, if opened with an older version

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2126]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have an older version of Test Pilot installed on a profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.firefox.com.
2. Observe the strings from the top of the experiments page.
3. Navigate to "https://testpilot.firefox.com/experiments/cliqz" page and observe the sported language warning.
 
[Expected result]:
- All the strings are correctly displayed with no format issue on Test Pilot pages.

[Actual result]:
2. "experimentsListCondesedHeader" string is displayed instead of "Pick your experiments" message.
3. "localeUnavailableWarningTitle" string is displayed instead of "This experiment is not supported in your language (en).".

[Notes]:
- When I have managed to reproduce the issue I had Test Pilot (version: 0.9.3-dev-e085559) installed.
- Here are some screen shots with the issue: 

![test pilot home page localization](https://cloud.githubusercontent.com/assets/19226534/22586346/ea442aca-ea04-11e6-9e48-8b5c40a6a05b.png)

![cliqz experiment page](https://cloud.githubusercontent.com/assets/19226534/22586424/56b73fc6-ea05-11e6-9f97-1cb576c0abff.png)

**Comment by SoftVision-CosminMuntean** [comment]
End of life warning strings are also affected when using old profiles. Probably is the same cause. 
I can reproduce this issue with all my old Firefox profiles that have Test Pilot 0.9.4-dev-045fca1 version installed. If the page is refreshed the strings are correctly displayed.

Here are some screenshots with the issue:

![txp](https://cloud.githubusercontent.com/assets/19226534/22941532/7ae495aa-f2ee-11e6-9a0b-c9b61790f009.png)
![no more404](https://cloud.githubusercontent.com/assets/19226534/22941534/7cf2387a-f2ee-11e6-9fc4-d5e0772d7358.png)

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the strings from Privacy section are also affected. I have noticed this after yesterday deploy (2017-02-15) to production on older Firefox profiles with Test Pilot (v.0.9.4-dev-045fca1) installed.

I think that any new or changed strings are affected by this issue after deploy on production, if Test Pilot add-on is not up to date.

Here is a screen shot with the issue:

![pricavy section](https://cloud.githubusercontent.com/assets/19226534/23027149/1746f6f8-f46c-11e6-9427-a61193c33274.png)

**Comment by ghost** [comment]
This might be related to stale FTLs when we do a push, but I haven't seen it in a long time.
