### ISSUE TITLE
Popupbar at top of page

### ISSUE THREAD

**Issue by TriMoon** [mozilla/testpilot#2127]
Please see: meandavejustice/min-vid#570 !

**Comment by ghost** [comment]
Hi TriMoon.  Can you give us more information here?  How often are you seeing the popup?  How many times have you seen it?  Is there any pattern?  Do you fill it out or dismiss it?  Do you have any other add-ons installed?  Is your clock correct?

We haven't had any other reports about this so I'm not sure how much we can help here.

**Comment by TriMoon** [comment]
As stated i have seen it **many** times.
I have both dismissed it and filled-out.
My time is in sync with NTP..
As to the frequency i can't tell, but it's too much for my taste..

> We haven't had any other reports about this so I'm not sure how much we can help here.

I surely you ain't of the type to say you dismiss reports just because you had not enough % of your users spend the efforts of actually complaining about it using a issue-tracker...

WHY would you implement such a popup **INSIDE** a foreign webpage the user is viewing, instead of a notification on your button??
I'm sorry but i'm the kind that gets irritated **VERY** fast by such intrusive popups...
I have all kind of anti-popup measures in place and this kind demands an uninstall to get rid of, your choice i would say...

Yes, im aggravated...

**Comment by ckprice** [comment]
(Sorry for taking so long to respond here) These feedback loops are part of the Test Pilot program, and vital for the health of experiments. We understand that it could be intrusive to those not expecting it, but have not been able to reproduce the report of an abnormal amount of feedback prompts appearing. Since there are no plans of removing our feedback prompts, we're going to close this.

**Comment by TriMoon** [comment]
> @ckprice : Since there are no plans of removing our feedback prompts, we're going to close this.

Then RIP Test Pilot program, good riddance...
