### ISSUE TITLE
Rate functionality on survey notification is not working and cannot be dismissed if it shows up on older versions of Test Pilot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2128]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have an older version of Test Pilot installed on a profile.
- Have any experiment enabled for at least 2 days (or edit sistem date). 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.firefox.com.
2. Wait until an experiment survey notification shows up.
3. Rate the experiment or dismiss the survey.
 
[Expected result]:
- The experiment is successfully rated / the notification is successfully dismissed. 

[Actual result]:
- The experiment cannot be rated and the notification cannot be dismissed.

[Notes]:
- This issue does not occur if first you update Test Pilot add-on.
- Here is a screen recording with the issue: https://goo.gl/5Co3ez.
- Here is a screen shot with browser console errors:

![page shot survay](https://cloud.githubusercontent.com/assets/19226534/22598391/0386d4c4-ea3c-11e6-9476-f1f75cf6e7f6.png)

**Comment by ghost** [comment]
Even if we can't record user input because it's not backwards compatible, we should fail gracefully.
