### ISSUE TITLE
Cannot navigate to /404 page on local

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2130]
## STR  

Fire up your local env and go to https://example.com:8000/404  

## Expected  

See the 404 component  

## Actual  

White page with classic `cannot get /404` message.

**Comment by lmorchard** [comment]
Finally fixed this one https://github.com/mozilla/testpilot/pull/2450/commits/01dcd2193994f2d268e2430cafa09f767e78a6ef
