### ISSUE TITLE
Uninstall Tracking Protection experiment

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot#2136]
We are graduating the Tracking Protection experiment out of Test Pilot with plans to do a "Phase 2" tracking protection experiment based on ideas we've learned here.

Since the Tracking Protection add-on is a WebExtension, it cannot use the AddonManager to uninstall itself. (I.e., [`getAddonByID()`](https://developer.mozilla.org/en-US/Add-ons/Add-on_Manager/AddonManager#getAddonByID()) and [`uninstall`](https://developer.mozilla.org/en-US/Add-ons/Add-on_Manager/Addon#uninstall()) like [universal-search](https://github.com/mozilla/universal-search/commit/f1655d6674db79750542c653388a9d79641a1ed6) did.)

So, we need the Test Pilot add-on to uninstall Tracking Protection for us.

**Comment by ghost** [comment]
You're right, this is not implemented in web extensions yet (https://bugzilla.mozilla.org/show_bug.cgi?id=1280236).

I also confirmed that we can't just "upgrade" your webextension to an SDK add-on which uninstalls itself.

So, I think the right thing here is:

1) Plan out a simple list of add-on IDs which Test Pilot uninstalls when it encounters them (*not* on startup, so as to keep our start time down)

2) Make a new version of Tracking Protection which is empty which we'll push when it graduates.  This will make part one less of an emergency as well as catch anyone who isn't upgrading test pilot (or doesn't have it installed) or whatever.

**Comment by dannycoates** [comment]
If uninstalling experiments is something we'll want to do in general, which it probably is, we could add a field to the experiment yml to specify an uninstall date and have the addon remove. It should be pretty easy to implement (few hrs).

**Comment by dannycoates** [comment]
Is this something we'd do silently or do we want ui to inform users what's happening?

**Comment by ghost** [comment]
Hmm, yaml field is interesting.  Good question on how we inform users.  @johngruen ?

**Comment by groovecoder** [comment]
@clouserw so, just to be clear - I should make a new Tracking Protection `.xpi` file that effectively empties out the entire add-on?

**Comment by johngruen** [comment]
@groovecoder that sounds good for now

**Comment by johngruen** [comment]
but yeah @dannycoates is a longer term solution

**Comment by lmorchard** [comment]
FWIW, we have [a BroadcastChannel for Web Extensions to send Telemetry pings via the Test Pilot add-on](https://github.com/mozilla/testpilot/blob/master/addon/src/lib/metrics/webextension-channels.js). We could open another BroadcastChannel to accept a self-uninstall message from a Web Extension that the Test Pilot add-on would execute. That might allow for more of a self-managed uninstall from the Web Extension's UI than a YAML field

**Comment by dannycoates** [comment]
Yeah, I think giving the experiment a way to trigger an uninstall is a good idea. I think we ought to be able to force it from the testpilot end also.

**Comment by dannycoates** [comment]
@johngruen we can do this in the addon now. do we want to set a date?

**Comment by ghost** [comment]
No need to set a date today, we can do it next week (although I think it will be the 15th)

**Comment by ckprice** [comment]
Taking this to set both ending and uninstall dates for the 15th.
