### ISSUE TITLE
Test Pilot doorhanger image is wrongly displayed on "Browser restart request" page for Firefox 49.0

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2138]
[Affected versions]:
- Firefox 49.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Firefox 49.0 was installed / extracted.
- Make sure that e10s is enabled on a new clean profile with "Never check for updates" option selected..

[Steps to reproduce]:
1. Open Firefox 49.0 with the profile from prerequisite and navigate to https://testpilot.firefox.com.
2. Click the "Install the Test Pilot Add-on" green button.
3. Observe the "Browser restart request" page.
 
[Expected result]:
- An onboarding image is correctly displayed on the restart page.

[Actual result]:
- An onboarding image containing the old Test Pilot doorhanger is wrongly displayed on the page.

[Notes]:
- Here is a screen shots with the issue: 

![doorhanger](https://cloud.githubusercontent.com/assets/19226534/22687664/ba3d199c-ed31-11e6-8d01-de57139ca7e7.png)

**Comment by fzzzy** [comment]
The offending jpg is frontend/src/app/images/restart-graphic@2x.jpg

**Comment by ghost** [comment]
Does this still happen?

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Firefox 49.0 and it seems that now the "Browser restart request" page is no longer displayed after clicking the "Install Test Pilot Add-on" button. 
After clicking it the "Installing..." button remains in the installing state until the browser is restarted.

If you navigate to "about:addons" page, you can see "Test Pilot will be installed after you restart Firefox" message.

@wresuolc @fzzzy should I log a different issue for this?
Here is a screen recording with the issue:
![restart](https://cloud.githubusercontent.com/assets/19226534/25753712/499e4282-31c5-11e7-944a-6f063c1150d0.gif)

**Comment by fzzzy** [comment]
Why is the restart required?

**Comment by jaredhirsch** [comment]
I'm not sure why a browser restart would ever be requested. We've deliberately made every addon restartless since the start of test pilot, including the test pilot addon itself.

**Comment by lmorchard** [comment]
I want to say some of the prefs we have to change for telemetry require a restart to take effect, if they were disabled at first. Maybe @chuckharmston knows more? I think he might have been in the thick of those pages

**Comment by chuckharmston** [comment]
I'm fuzzy on the details, but I think what Les is referring to had to do with installing add-ons that were not e10s compatible when e10s was enabled. That seems unlikely here.

**Comment by lmorchard** [comment]
Yeah, I'm having trouble finding any restart-required cases in the repo now. Like, we have this [`RESTART_NEEDED` constant with a `// TODO` comment](https://github.com/mozilla/testpilot/blame/d98a47248b46251cec423a6c2d5a97490a1e72ac/frontend/src/app/lib/moz.js#L7) 🤷‍♂️

**Comment by chuckharmston** [comment]
Maybe @fzzzy stripped out that check when doing one of the refactors?

**Comment by fzzzy** [comment]
I'm pretty sure I left the restart needed logic in. @dannycoates may have removed it in the use-mozAddonManager branch. However, what's weird here is that the add-on manager is reporting that a restart is needed, which I assume we have no control over?

**Comment by chuckharmston** [comment]
> which I assume we have no control over?

We show this view when a restart is required: https://testpilot.firefox.com/restart

**Comment by fzzzy** [comment]
But in the screen recording, "Test Pilot will be enabled after you restart Firefox" is shown in the Add-on manager, and that testpilot.firefox.com/restart ui is not shown.

**Comment by chuckharmston** [comment]
No idea why that's happening; this was the intended flow for restarts, though. Things may have been broken in refactors.

**Comment by SoftVision-PaulOiegas** [comment]
Guys, the restartless install was possible only starting with Fx 50.x. Test Pilot supports Firefox versions starting from 49.x. So for this case we still need the https://testpilot.firefox.com/restart page, and that is not displayed for the moment. 
Maybe we should log something for this separately ? This one is still a valid bug if we fix the page display for 49.x.

**Comment by sevaan** [comment]
Spec:

![restarttp spec](https://cloud.githubusercontent.com/assets/473531/26504444/a2e13590-4212-11e7-8c71-e95382c7acd8.png)


Asset:

![restarttp](https://cloud.githubusercontent.com/assets/473531/26504448/a678040e-4212-11e7-885f-e010c4880af8.png)

**Comment by fzzzy** [comment]
There's another bug here, which is that the restart page is no longer displayed on firefox 49.

**Comment by fzzzy** [comment]
Ah, I see @SoftVision-PaulOiegas already mentioned that the restart page is no longer shown on 49. I think it is ok to use this issue to track that issue too, they are kind of intertwined.

**Comment by fzzzy** [comment]
Our minimum firefox version is currently 49. 50 does not have this restart problem. @clouserw checked and 49 users are 1.04% of requests. I'm just going to fix this by bumping the min firefox version to 50.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy This seems to be ok on Dev, "Upgrade" button appears for 49.0, 49.0.1 and 49.0.2. However, we noticed that the message that informs the user about the min version required was not updated. Cosmin logged a separate issue for it (#2509).
