### ISSUE TITLE
Add next round of Test Pilot experiments to testpilot dev server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2143]
It'd be nice to get the signed XPIs for the following experiments onto the dev server for QA testing sooner rather than later:

- [Containers](https://github.com/mozilla/testpilot-containers)
- [Snooze Tabs](https://github.com/bwinton/SnoozeTabs) &mdash; see https://testpilot.firefox.com/files/snoozetabs@mozilla/latest
- [Pulse](https://github.com/mozilla/pulse)

We've tested these somewhat thoroughly, but independently. It'd be nice to be able to see how/if they work together (as well as with previous experiments). For example, https://github.com/bwinton/SnoozeTabs/issues/151.

Even if we just have a bunch of Lorem Ipsum and dummy content in the YAMLs, giving localizers and QA at least 1-2 weeks to test on testpilot.dev.mozaws.net would be super helpful.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/testpilot-containers/issues/159 &mdash; "getting a signed build that works with release for testing"

**Comment by ghost** [comment]
@johngruen is going to start opening PRs for this tonight/tomorrow

**Comment by lmorchard** [comment]
Also tracking this as an issue on the Snooze Tabs repo: https://github.com/bwinton/SnoozeTabs/issues/56

**Comment by groovecoder** [comment]
@pdehaan @wresuolc are the signed .xpi's going into AMO covering this?

**Comment by lmorchard** [comment]
[Snooze Tabs is using](https://github.com/bwinton/SnoozeTabs/issues/57) the [automated sign & deploy hosting machinery for Test Pilot](https://github.com/mozilla/testpilot/blob/master/docs/development/hosting.md). Not sure if that helps Pulse or Containers at this stage

**Comment by ghost** [comment]
URLs (no xpis yet):

https://testpilot.firefox.com/files/pulse@mozilla.com/latest 
https://testpilot.firefox.com/files/@testpilot-containers/latest

**Comment by ghost** [comment]
Updated the containers URL:  https://testpilot.firefox.com/files/@testpilot-containers/latest and that has the add-on and is all set up now.
