### ISSUE TITLE
The "Back" navigation arrow is wrongly displayed on the first slide from "Take the Tour" pop-up

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2147]
[Notes]:
- Probably this is a regression introduced by #2132.

[Affected versions]:
- Firefox 51.0.1 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net/" page.
2. Click on one of the available experiments and choose to "Enable" it.
3. Observe the navigation arrows from the first slide of the "Take the Tour" displayed pop-up.

[Expected result]:
- Only the "Next" navigation arrow is displayed on the first slide.

[Actual result]:
- The both "Back" and "Next" navigation arrows are displayed on the first slide.

[Additional Notes]:
- The issue is also reproducible if the tour pop-up is opened from the "Launch Tour" button.  
- Here is a screen shot with the issue.

![left arrow](https://cloud.githubusercontent.com/assets/19226534/22736168/a2b55526-ee05-11e6-9d3f-c9a44bf393df.png)

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean what happens if you click the button? Does everything blow up?

**Comment by SoftVision-CosminMuntean** [comment]
Nothing happens and I don't see any errors in browser console.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking this as verified.
