### ISSUE TITLE
CSP error displayed while navigating on Homepage and experiment details pages without having TxP installed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2148]
[Notes]:
- This issue is not reproducible while having Test Pilot add-on installed.
- This issue is not reproducible on stage and production servers.
- This issue is not reproducible while visiting "About Test Pilot", "Privacy", "Terms", "Share" or "404" pages.

[Affected versions]:
- Firefox 51.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and open the Browser console (Windows - Ctrl+Shift+J).
2. While observing the console, navigate to "https://testpilot.dev.mozaws.net/" page.
3. Navigate to one of the available experiments pages and observe the console again.

[Expected result]:
- All the visited pages load without any displayed errors.

[Actual result]:
- CSP errors displayed for Homepage and each experiment page.

[Additional Notes]:
- Here is a screenshot of the error:
![content security policy error 1](https://cloud.githubusercontent.com/assets/17258026/22745154/3f4f8a38-ee28-11e6-84a1-2d24de33b36e.png)

**Comment by ghost** [comment]
Google Analytics is trying to load off of their non-ssl site and CSP is blocking it.

The GA snippet attempts to detect if you are on an ssl site or not and load the corresponding code from Google.

From the logs it looks like you're on non-ssl testpilot dev, but your link in the comment is ssl.  So....there might be some strange redirection happening here or something.
