### ISSUE TITLE
Missing string on newsletter sign up success pop up

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2153]
[Affected versions]:
- Firefox 51.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a valid email address that is not signed up on the Test Pilot Newsletter. 

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Choose to "Install the Test Pilot Add-on".
3. After the "Welcome" pop up is displayed, enter a valid email address in the textbox for Newsletter sign up.
4. Click on the "Sign me up" blue button.
5. Observe the elements displayed on the confirmation pop up.

[Expected result]:
- The confirmation pop up is correctly displayed and contains all the designed elements.

[Actual result]:
- The confirmation pop up is displayed but misses the "When you get a chance, head over to your inbox to verify your email address." string before the "Thank you!" one.

[Notes]:
- It seams that the string was lost in the process. We should make sure the string is also translated before adding it back.
- Here is a screenshot of the current pop up:
![newsletter modal missing](https://cloud.githubusercontent.com/assets/17258026/22789432/92670098-eeeb-11e6-94b0-402efb8df0f4.png)

**Comment by ghost** [comment]
Marking needs:ux.  was this string dropped on purpose or should we add it back?

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc I've talked with @johngruen on IRC about this. Asked him the same question and he told me to log it cause we need to add it back.

**Comment by SoftVision-PaulOiegas** [comment]
Fixed! 👍
