### ISSUE TITLE
Actually record variant test cohorts in google analytics

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2154]
We need to nail down the strategy for storing a user's chosen cohort for a test in ga. I think we can look at Page Shot since it just did the same thing recently.

**Comment by ckprice** [comment]
I'm going to add this to next sprint. A/B testing is kind of useless without it.

These are the custom dimensions we currently have configured

<img width="998" alt="screen shot 2017-02-10 at 9 38 15 am" src="https://cloud.githubusercontent.com/assets/8632184/22837309/cfdbf3fa-ef74-11e6-9ddd-93e02131efe9.png">

It maps well to our [self-maintained documents](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#custom-dimensions) which is great.

I have an email pending to Gareth asking if he has any recommendations on GA implementation. I don't think we should block on his team though. If we just add things into a couple of custom dimensions we should be able to report on results.

**Comment by fzzzy** [comment]
Yes, this is essential, I just ran out of time last sprint.

I'll poke at ga early next week. Thanks a lot for the link to the docs, really helpful.

**Comment by ckprice** [comment]
Added two new custom dimensions today (8 and 9)

Question: do we want to allow for multiple tests at the same time? The current implementation with Custom Dimensions limits this, but I don't think we should yank the code out if it's in (maybe we can improve reporting later). We could update the docs to make sure folks are only doing one at a time.

<img width="996" alt="screen shot 2017-02-14 at 10 21 48 am" src="https://cloud.githubusercontent.com/assets/8632184/22942758/ab688398-f29f-11e6-8530-a38a1b49c947.png">

**Comment by fzzzy** [comment]
I did end up changing the code so that each user is only allowed to be in one test. I think it is the sanest way to do a/b testing -- who knows what weird interactions could arise from users being in multiple tests that don't know about each other.

If we want to allow users to be in more than one test at a time, we can file a feature bug then and discuss the merits of that approach.
