### ISSUE TITLE
github pages docs site?

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2156]
might be nice to make our markdown docs stand out a bit. maybe taipei uxers could pitch in?

**Comment by ghost** [comment]
Are these still built from a gh-pages branch?  I'm afraid this would make people less likely to update docs because it would be another process to go through.  Would reviewing our current docs and making sure breadcrumbs/links work be as effective?

**Comment by lmorchard** [comment]
> Are these still built from a gh-pages branch?

FWIW, we don't have a gh-pages branch, yet.

>  I'm afraid this would make people less likely to update docs because it would be another process to go through. Would reviewing our current docs and making sure breadcrumbs/links work be as effective?

This stuff is pretty easily automated on CircleCI or Read the Docs, doesn't have to be another manual process. But, if we don't have to complicate things, just previewing markdown docs in a dead simple option unless we need more.

**Comment by chuckharmston** [comment]
We don't need to worry about `gh-pages` anymore, you can [publish directly from `/docs` on `master`](https://github.com/blog/2228-simpler-github-pages-publishing).

**Comment by lmorchard** [comment]
I think that works if you don't need a build step - i.e. we're committing HTML rather than markdown. A gh-pages branch works better, IMO, to keep rendered HTML separate from the source.

**Comment by chuckharmston** [comment]
[GitBook](https://www.gitbook.com/) produces very nice documentation and is quite [themable](https://toolchain.gitbook.com/themes/). Might be worth investigating.

**Comment by ghost** [comment]
However we do this, it should be 100% automatic. This is a low priority
