### ISSUE TITLE
The new thick white border that surrounds the install buttons is missing on other locales than en-US

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2159]
[Affected versions]:
- Firefox 51.0.1 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a profile which contains the A/B testing experiment for Test Pilot install button.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net/" page.
2. Observe the "Install Test Pilot Add-on" button.
3. Go to "about:preferences#content" and choose another language (eg: German [de]).
4. Return to Test Pilot homepage and refresh the page.
5. Observe the "Install Test Pilot Add-on" button.

[Expected result]:
- A thick white border surrounds the Test Pilot install button on both locales.

[Actual result]:
Step 2: A thick border surrounds the install Test Pilot button.  
Step 5: The thick white border dispersers after the language is changed.

[Notes]:
- Here is a screen recording with the issue: https://goo.gl/YYsZnj.

**Comment by ghost** [comment]
This is on purpose (is an a/b test @ 50%)
