### ISSUE TITLE
Activity Stream data collection link from your privacy section redirects to a 404 page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2160]
[Notes]:
- The path for the "data_dictionary.md" seems to be wrong. I think the correct path for it should be: htps://github.com/mozilla/activity-stream/blob/master/docs/data_dictionary.md.

[Affected versions]:
- Firefox 51.0.1 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://testpilot.stage.mozaws.net/" page.
2. Click the Activity Stream experiment card and scroll to "Your Privacy" section. 
3. Click the "You can learn more about the data ..." link under the section.
4. Observe the browser behavior.

[Expected result]:
- You are redirected to a specific page where the experiment details about data collection are detailed.

[Actual result]:
- You are redirected to a 404 page.

[Additional Notes]:
- Here is a screen recording with the issue:

![data directionary for as](https://cloud.githubusercontent.com/assets/19226534/22829384/0349698a-efab-11e6-9aa3-ff064567807c.gif)

**Comment by jaredhirsch** [comment]
The working link is https://github.com/mozilla/activity-stream/blob/master/docs/data_dictionary.md

I think we just need to update the yaml
