### ISSUE TITLE
[Stage] Test Pilot spaceship logo is wrongly positioned on Test Pilot "Experiments" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2161]
[Notes]:
- This issue is only reproducible on stage server. 
 
[Affected versions]:
- Firefox 51.0.1 

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net/" page.
2. Observe the Test Pilot spaceship logo from the top right of the page.

[Expected result]:
- Test Pilot spaceship logo is correctly displayed in the center of the semitransparent banner.

[Actual result]:
-  Test Pilot spaceship logo is wrongly positioned a few pixels down on the semitransparent banner.

[Additional Notes]:
- Here is a screen shot with the issue:

![test pilot icon](https://cloud.githubusercontent.com/assets/19226534/22829930/67f57c64-efad-11e6-84cc-a74a7435b765.png)

**Comment by ghost** [comment]
@johngruen is this something you changed on purpose?

**Comment by johngruen** [comment]
@wresuolc @SoftVision-CosminMuntean yeah, this wasn't showing up on 53 when i was testing. Patch inbound.
