### ISSUE TITLE
"Install" button new thick white surrounding border is non persistent on Windows and Linux

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2162]
[Notes]:
- This issue is only reproducible on stage server and only on Windows and Linux OSes.
 
[Affected versions]:
- Firefox 51.0.1 and above

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a profile which contains the A/B testing experiment enabled.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net/" page.
2. Click the "Install the Test Pilot Add-on" button.
3. While observing the button thick white surrounding border, hover away from the button.
4. Click on a free area of the page and observe the button behavior. 

[Expected result]:
- The button surrounding white border remains unchanged no matter what actions are performed on the page.

[Actual result]:
- Step 3: The white surrounding border wrongly disappears when hovering away the button.
- Step 4: The surrounding white border reappears and persists even if button is hovered.

[Additional Notes]:
- While performing the STR we also noticed that the "Installing..." animation color is darker (like hovered state) after choosing to install TxP and becomes brighter after clicking on a free area of the page.
- Here is a screen recording of the issue: https://goo.gl/5HrULz.

**Comment by fzzzy** [comment]
I'm not going to get to this this week and am on vacation next week, so someone else can pick it up if they feel like it.

**Comment by ScottDowne** [comment]
I can take this one.

**Comment by fzzzy** [comment]
@ScottDowne Go for it. The `testpilot-varianttests-id` is stored in localstorage in `frontend/src/app/reducers/varianttests.js`. I can't think of any reason why it would work on mac but not the other platforms.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy @ScottDowne The fix seems to be ok on both Windows and Linux. However, there is a case mentioned in the issue that wasn't treated with this fix.
> While performing the STR we also noticed that the "Installing..." animation color is darker (like hovered state) after choosing to install TxP and becomes brighter after clicking on a free area of the page.

I'm not sure if we should reopen for this, but the animation still changes its color several times while performing the install flow on dev server. Not sure how it will behave on production until it lands on stage at least.

**Comment by ScottDowne** [comment]
I did see that issue, but left it for now. I'm a bit new on this project, and just wanted to iterate on one piece at a time. It's also a slightly different problem than the border and wanted to keep fix as simple as I could.

My guess is we would want to open a new issue for the hover state, but for now I'll keep this issue on my radar and see about fixing the hover state too.

**Comment by fzzzy** [comment]
I agree, open a new issue for that.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy @ScottDowne logged it separately in #2362.
