### ISSUE TITLE
If experiment download fails, the "Enabling..." button remains in the enabling state and no error is displayed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2163]
[Notes]:
- This issue is not reproducible on production server.

[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed on the above profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on one of the available experiments cards.
3. Disable / disconnect internet connection.
4. Choose to enable the experiment and wait for the error message to appear.
5. Observe the browser behavior.

[Expected result]:
- Fail to enable error is displayed after a few seconds.

[Actual result]:
- The "Enabling..." button remains in the enabling state and no error is displayed.

**Comment by dannycoates** [comment]
damn! thanks @SoftVision-CosminMuntean I was *really* hoping you wouldn't find anything with the new version, but I'm glad you caught it, you're awesome!

**Comment by SoftVision-CosminMuntean** [comment]
Thanks @dannycoates :grin:,  
I have retested this issue and is no longer reproducible on stage and dev servers. Marking as verified.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is reproducible if the "extensions.webapi.testing" boolean pref is manually added with "true" value.

The "Enabling..." button remains in the enabling state and no error is displayed, if experiment download fails.

**Comment by fzzzy** [comment]
Yes, I think this was a TODO in the code. I'll fix it today. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible. Marking as verified.

But, the issue describe in [1866](https://github.com/mozilla/testpilot/issues/1866#issuecomment-292979056) is still reproducible. After the experiment is successfully enabled, the Tour pop-up is no longer displayed. 
We left that issue open in order to track this behavior.
