### ISSUE TITLE
The "Changelog" and "Bug Reports" German words are wrongly split on "Experiment details" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2164]
[Affected versions]:
- Firefox 51.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The German [de] language was added on top of the list from Firefox Options>Content section.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click on one of the available experiments cards.
3. Observe how the "Changelog" and "Bug Reports" strings are displayed on page.

[Expected result]:
- Entire words are displayed on the same row.
or
- Entire words that don't fit the designed area are correctly split on two rows depending on language rules. 

[Actual result]:
- Entire words are wrongly split on two rows.

[Notes]:
- Here is a screen shot with the issue:

![german strings](https://cloud.githubusercontent.com/assets/19226534/22835846/cfb0ef0e-efc2-11e6-869b-13b0007b2cef.png)

**Comment by pdehaan** [comment]
What about if we just hyperlinked the words "Changelog", "Contribute", "Bug Reports", and "Discuss ${name}" instead of displaying the URLs:

<img width="321" alt="firefox_test_pilot_-_snooze_tabs" src="https://cloud.githubusercontent.com/assets/557895/23087601/5dcb81a2-f52a-11e6-9084-4d3adc69a929.png">

**Comment by johngruen** [comment]
Peter, you're a genius!

**Comment by pdehaan** [comment]
> Peter, you're a genius!

To be honest, I'm not a huge fan of my proposal. It would remove the experiment URL visibility, so you wouldn't know that an experiment is being offered by Mozilla or Blake or NoMore404s, etc.

For example:

![firefox_test_pilot_-_snooze_tabs](https://cloud.githubusercontent.com/assets/557895/23224862/c3b2ea1a-f8e4-11e6-8d9c-6357ae3df40e.png)

---

Counter proposal would be to convert the `<table>` into a `<dl><dt>...</dt><dd>...</dd></dl>` markup type thing (which _should_ possibly be more l10n-friendly, while still letting us nicely display URLs):

![firefox_test_pilot_-_snooze_tabs](https://cloud.githubusercontent.com/assets/557895/23224932/06ae2e10-f8e5-11e6-8a6b-64aa5f890d27.png)

```html
<dl class="stats">
    <dt data-l10n-id="tour">Tour</dt>
    <dd><a class="showTour" data-l10n-id="tourLink" href="#">Launch Tour</a></dd>
    
    <dt data-l10n-id="changelog">Changelog</dt>
    <dd><a href="https://github.com/bwinton/SnoozeTabs/commits/master">https://github.com/bwinton/SnoozeTabs/commits/master</a></dd>
    
    <dt data-l10n-id="contribute">Contribute</dt>
    <dd><a href="https://github.com/bwinton/SnoozeTabs/">https://github.com/bwinton/SnoozeTabs/</a></dd>
    
    <dt data-l10n-id="bugReports">Bug Reports</dt>
    <dd><a href="https://github.com/bwinton/SnoozeTabs/issues/new">https://github.com/bwinton/SnoozeTabs/issues/new</a></dd>
    
    <dt data-l10n-id="discussExperiment" data-l10n-args="{&quot;title&quot;:&quot;Snooze Tabs&quot;}">Discuss ⁨Snooze Tabs⁩</dt>
    <dd><a href="https://discourse.mozilla-community.org/c/test-pilot/snooze-tabs">https://discourse.mozilla-community.org/c/test-pilot/snooze-tabs</a></dd>
  </dl>
```

**Comment by ChenMorpheus** [comment]
@pdehaan @johngruen 
According to the discussion above, I would recommend the aligned layout below without the "http" to better prevent truncated in certain languages and still provide the URL visibility.

![2017-03-28 2 51 51](https://cloud.githubusercontent.com/assets/18019946/24392622/55dfe3b4-13c7-11e7-9dd0-0816d2934824.png)

**Comment by johngruen** [comment]
@ChenMorpheus solution looks good. Let's do it!

**Comment by SoftVision-PaulOiegas** [comment]
This was implemented, but I see a tiny difference from the design. The "Launch Tour" text button is implemented with normal weight, while in the design it seems to be in bold weight.
@johngruen Do we care about this difference or not?

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas not a priority, but it would be nice to match the spec

**Comment by SoftVision-PaulOiegas** [comment]
Reopening based on @johngruen comment. \
@chuckharmston Maybe it could be a good first bug to fix the font weight for "Launch Tour" button?

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas Yes, I think it would be a good first bug.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy Hmmm, something is strange. I have just looked on dev server and it seems to be already fixed. But nothing was done on this since my previous comment (7 August) and on production is still broken.
We'll recheck this after the stage deploy this week and if it's ok, I'll close it back.

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas Well, one thing that is different between dev and prod is that the loading indicator is no longer used on dev. This means that the content seen in the page is provided by html elements instead of inserted into the page after the fact by javascript. So that may have accidentally fixed it? :)

**Comment by SoftVision-PaulOiegas** [comment]
Retested this on all 3 servers and seems to be fixed after all. 👍

**Comment by fzzzy** [comment]
🏆
