### ISSUE TITLE
Integrate updated ping-centre library

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2171]
The `ping-centre` library is [adding Webpack support](https://github.com/mozilla/ping-centre/pull/48). Try to use it instead of a direct `sendBeacon` call once that PR lands.

**Comment by pdehaan** [comment]
Webpack PR (https://github.com/mozilla/ping-centre/pull/48) has landed. \o/

**Comment by lmorchard** [comment]
FWIW: Had a report today of `sendBeacon` errors breaking Test Pilot, [reminiscent of what happened with `testpilot-metrics` when the `beacon.enabled` pref is `false`](https://github.com/mozilla/testpilot-metrics/issues/25). But, [the only mentions of `sendBeacon` I can find](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=sendBeacon) are related to ping-centre. So maybe this is the fix to that, too.

**Comment by meandavejustice** [comment]
It seems like this issue is a bit outdated, we should probably be using testpilot-metrics here instead of sendToGa, telemetry, and ping centre all directly.

**Comment by jaredhirsch** [comment]
There's been recent discussion about replacing the Test Pilot addon with a webextension API experiment that would expose a Telemetry API. That Telemetry API would be a replacement for the testpilot-metrics library.

The sendToGa, telemetry, and ping centre code would all need to live inside that Telemetry API, routing metrics events to some/all of the three endpoints.

We do want to use the ping-centre library because it provides client-side validation, so experiment authors will be able to catch malformed metrics pings before they submit them--not weeks afterward, when a bunch of bad pings are found in a reject bucket somewhere on S3.

The ping-centre approach is basically:

- for each experiment, file a PR against the ping-centre library to (1) add a client-side Joi schema for custom fields included in that experiment's ping; (2) in that PR, also include a link to the Redshift schema defined in the metrics.md doc - ping-centre uses the same schema for its storage
- once the schema support lands in the ping-centre library, bump the ping-centre version in our test pilot addon (or webextension API experiment) to add support for the new experiment

I've totally neglected metrics work for screenshots, but things seem to be quieting down (🤞), so I can help explain stuff or help with implementation.

**Comment by johngruen** [comment]
Lets reassess in our meeting tomorrow, but probably we wont integrate into test pilot
