### ISSUE TITLE
Define & document Ping Centre setup process for new experiments

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2172]
Our updated [metrics docs](https://github.com/mozilla/testpilot/blob/master/docs/metrics/index.md) explain the setup process for new experiments to send pings to Telemetry. As part of that setup process, a Redshift schema is defined for data storage.

For Ping Centre, we should be able to reuse that same Redshift schema for data storage.

@tspurway or @ncloudioj, what should the process be for new experiments to request Ping Centre support? Should a Redshift support ticket be opened against [infernyx](https://github.com/mozilla/infernyx)? 

Note that experiments won't need to define a new `ping-centre` client schema: the test pilot addon will send all experiment pings using the [`testpilot` schema](https://github.com/mozilla/ping-centre/blob/master/src/schemas/testpilot.js), which includes the addon's ID. That ID can be used to route pings to the appropriate Redshift table.

**Comment by johngruen** [comment]
Probably moot for now
