### ISSUE TITLE
When copying text all you want is...

### ISSUE THREAD

**Issue by Folsome** [mozilla/testpilot#2175]
This relates to page shot - when using this excellent tool what you look for is just the characters. To catch the whole document if you try to shrink and then copy you get (this criticism comes in two partidos) UNO the visible only, even though you fingered whole page
DOS - I can occasionally see the entire text on the screen, i.e. the program (page shot) takes down the entirety of characters, then proceeds to cut of the little piece showing (complete idiocy). Super good plus, like it so far, thank you for a great everything! Firefox rocks!

**Comment by pdehaan** [comment]
Moved to the Page Shot repo: https://github.com/mozilla-services/pageshot/issues/2164

Closing in favor of upstream bug.
