### ISSUE TITLE
Links to Example Tests on Contributing Page No Longer Exist

### ISSUE THREAD

**Issue by chrwang** [mozilla/testpilot#2178]
The Contributing page guide links to two python test files for Server and Client testing. At some point, these moved out of their respective directories, and are now broken.

**Comment by pmespresso** [comment]
Could go ahead and change the link to https://github.com/yjkimjunior/testpilot/blob/master/docs/development/testing.md 

Not sure where the examples were moved to, or whether they were deleted.
