### ISSUE TITLE
Enabled experiment after locale switch isn't displayed as such, and it's not removed at Test Pilot uninstall

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2189]
[Notes]:
- I'm not 100% sure but I think this is a regression.

[Affected versions]:
- Firefox 51.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A new Firefox profile was created with default en-US language set for content.
- Test Pilot was already installed on the profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. In a new tab navigate to "Options > Content" page and add the German [de] language to the top of the list.
3. Return to the Test Pilot tab and refresh the page.
4. Click on "Cliqz" experiment card and choose to "Enable" it.
5. Refresh the experiment page after and verify if the functionality is present.
6. Choose to uninstall Test Pilot and verify if all related add-ons are removed from "about:addons" extensions page. 

[Expected result]:
- Step 5: After a refresh, the experiment is still displayed as enabled and functionality is present.
- Step 6: Uninstalling Test Pilot removes both the add-ons.

[Actual result]:
- Step 5: After a refresh, the experiment is no longer displayed as enabled but functionality is still present.
- Step 6: Uninstalling Test Pilot removes only Test Pilot add-on, leaving the Cliqz one.

[Additional Notes]:
- The user must manually remove the locale dependent experiments if any is installed.
- This also occurs if you manually navigate from en-US locale, for example, to a hidden experiment URL.
- Here is a screen recording of the issue: https://goo.gl/XoZiwA.

**Comment by dannycoates** [comment]
This is a side effect of how the new addon version filters experiments vs the old one. Old one filtered on "display", new one on "load". The fix for this is probably to reload experiments on locale change.

**Comment by SoftVision-PaulOiegas** [comment]
Guys, we have rechecked this on dev server and it seems that it may have been fixed by something. But this still reproduces on production, as expected.

Was this fixed by a recent PR and you guys forgot to close it ? I'm asking because we had another one logged recently that seems to be a dupe to this one #2277.

**Comment by dannycoates** [comment]
#2290

**Comment by SoftVision-PaulOiegas** [comment]
Forgot to close this. Rechecked it and it correctly works, except the uninstall part. But that is caused by another issue (#2366).
