### ISSUE TITLE
A few no-more-404s graduation_report HTML errors via W3's HTML validator

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2195]
Seeing a few HTML validation errors via https://validator.w3.org/nu/#textarea for the no-more-404s.yaml `graduation_report` HTML:

1. **Error:** Bad value 100% for attribute `width` on element `img`: Expected a digit but saw `%` instead.
   From line 21, column 3; to line 21, column 111
   ```html
   figure>↩
   <img src="/static/images/experiments/no-more-404s/graduation/design-update.png" width="100%" height="auto" />↩ 
   <fi
   ```

1. **Error:** Bad value `auto` for attribute `height` on element `img`: Expected a digit but saw `a` instead.
   From line 21, column 3; to line 21, column 111
   ```html
   figure>↩
   <img src="/static/images/experiments/no-more-404s/graduation/design-update.png" width="100%" height="auto" />↩ 
   <fi
   ```

1. **Error:** Bad value `100%` for attribute `width` on element `img`: Expected a digit but saw `%` instead.
    From line 27, column 3; to line 27, column 104
    ```html
    figure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/gr-001.png" width="100%" height="auto" />↩
    <fi
    ```

1. **Error:** Bad value `auto` for attribute `height` on element `img`: Expected a digit but saw `a` instead.
    From line 27, column 3; to line 27, column 104
    ```html
    figure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/gr-001.png" width="100%" height="auto" />↩
    <fi
    ```

1. **Error:** Bad value 100% for attribute width on element img: Expected a digit but saw % instead.
    From line 32, column 5; to line 32, column 103
    ```html
    gure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/car.gif" width="100%" height="auto" />↩
    <
    ```

1. **Error:** Bad value auto for attribute height on element img: Expected a digit but saw a instead.
    From line 32, column 5; to line 32, column 103
    ```html
    gure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/car.gif" width="100%" height="auto" />↩
    <
    ```

1. **Error:** Bad value 100% for attribute width on element img: Expected a digit but saw % instead.
    From line 38, column 5; to line 38, column 106
    ```html
    gure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/gr-002.png" width="100%" height="auto" />↩
    <
    ```

1. **Error:** Bad value auto for attribute height on element img: Expected a digit but saw a instead.
    From line 38, column 5; to line 38, column 106
    ```html
    gure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/gr-002.png" width="100%" height="auto" />↩
    <
    ```

1. **Error:** Bad value 100% for attribute width on element img: Expected a digit but saw % instead.
    From line 43, column 5; to line 43, column 106
    ```html
    gure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/gr-003.png" width="100%" height="auto" />↩
    <
    ```

1. **Error:** Bad value auto for attribute height on element img: Expected a digit but saw a instead.
    From line 43, column 5; to line 43, column 106
    ```html
    gure>↩
    <img src="/static/images/experiments/no-more-404s/graduation/gr-003.png" width="100%" height="auto" />↩
    <
    ```

**Comment by pdehaan** [comment]
Similarly, the **eslint-plugin-jsx-a11y** module noted there was an unclosed `<p>` tag, and subsequently complained about a handful of `<img>` tags that were lacking `alt=""` attributes:

```
> jsx-a11y-test@1.0.0 test /Users/pdehaan/dev/tmp/del/jsx-a11y-test
> eslint .


/Users/pdehaan/dev/tmp/del/jsx-a11y-test/index.js
   8:3  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/img-has-alt
  13:3  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/img-has-alt
  19:3  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/img-has-alt
  24:5  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/img-has-alt
  30:5  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/img-has-alt
  35:5  error  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/img-has-alt

✖ 6 problems (6 errors, 0 warnings)
```

**Comment by pdehaan** [comment]
Unclosed `<p>` tag was at [./content-src/experiments/no-more-404s.yaml:94](https://github.com/mozilla/testpilot/blob/7d2a6b6cc167e8708af8d7c0eadf5597b073d624/content-src/experiments/no-more-404s.yaml#L94).

**Comment by ghost** [comment]
@pdehaan you still on this one?  I'm going to move to in progress
