### ISSUE TITLE
Account inactive page doesn't give me a sign out link

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#220]
Currently I'm logged into idea-town using my personal email account.

I'm given the following message, but no way to sign out or change who I am signed in as:

> **Account Inactive**
> We're not quite ready for you yet!
> Please come back in a few weeks.

<img width="617" alt="idea_town" src="https://cloud.githubusercontent.com/assets/557895/11043553/217e453a-86d2-11e5-95f9-8ebdd5f0fdda.png">

**Comment by lmorchard** [comment]
You're not actually signed in when you see the "account inactive" page. When the site sees that your account is in active, it bounces you there _instead_ of setting a session cookie & etc. Might be worth adding another signin button here or a link back to home to try again

**Comment by johngruen** [comment]
@lmorchard @pdehaan this is closed, yeah? if not, reopen, but i think it's closed.
