### ISSUE TITLE
Tracking Protection and NoMore404s experiments can still be enabled if system date is set to 14th February

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2200]
[Notes]:
- This behavior does not occurs with Universal Search experiment, so I was thinking that maybe we should block this ones too.

[Affected versions]:
- Firefox 51.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A new Firefox profile was created and Test Pilot was already installed on the profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Change the system date of the operating system to 14th of February,
3. Return to Test Pilot page and refresh it.
4. Open both the Tracking Protection and NoMore404s experiments pages in new tabs and choose enable them.

[Expected result]:
- Experiments can no longer be enabled.

[Actual result]:
- Both experiments are enabled and working.

[Additional Notes]:
- Even if I moved the date back to current one, I managed to keep Tracking Protection enabled and working until I've restarted the browser.

**Comment by ghost** [comment]
For these specific experiments:  We're not going to disable NoMore404s, so that's not too big of a deal, and the plan for tracking protection is still to upload an empty add-on so that shouldn't be a big deal either.

Why this doesn't happen with universal search though is a good question.

**Comment by ckprice** [comment]
I think we shipped an empty add-on for Universal Search too?

**Comment by chuckharmston** [comment]
Universal Search self-uninstalls.

**Comment by SoftVision-PaulOiegas** [comment]
Well Tracking Protection already uninstalls if you restart the browser. Hope I'm not mistaking but I've seen this on at least 3-4 profiles. The question is if we want to let them enable if we change the date in the past or not.
Universal Search can no longer be enabled even if you change the date before its graduation. So there's a difference in the behavior of graduated experiments.

**Comment by ckprice** [comment]
Edge case, I think we can close.
