### ISSUE TITLE
No More 404s was removed from Test Pilot before being added to AMO.

### ISSUE THREAD

**Issue by daveloyall** [mozilla/testpilot#2209]
I re-imaged my workstation earlier this week, so I need to reinstall everything, including No More 404s.

But I can't, because today (2017-02-17) it exists in neither the Test Pilot site nor addons.mozilla.org.

**Comment by pdehaan** [comment]
Ref: #2196

@daveloyall Sorry about that. We'll update this bug and the No More 404s page with the AMO link once it gets published (which should be very soon).

**Comment by ghost** [comment]
This is at https://addons.mozilla.org/en-US/firefox/addon/wayback-machine_new/ now.  Sorry for the inconvenience.
