### ISSUE TITLE
Implement Door Hanger and Feedback UI

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#221]
Main page https://invis.io/8Z48QH33W
Net promoter page https://invis.io/WD4V3AJ5H

So the second page here should pop up at random somewhat. I'll figure out what random should mean here and add it to the bug.

**Comment by meandavejustice** [comment]
in progress at branch: [221-door-hanger-feedback-ui](https://github.com/meandavejustice/idea-town/tree/221-door-hanger-feedback-ui)
