### ISSUE TITLE
Finalize product pages for launch

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2210]
We've merged in rough versions of these pages in #2203. This issue is opened to update with final content.

- [ ] Final approval on Containers Privacy Notice
- [x] Final copy/assets for Containers
- [x] Signed final XPI uploaded to https://testpilot.firefox.com/files/snoozetabs@mozilla/latest
- [x] Signed final XPI uploaded to https://testpilot.firefox.com/files/pulse@mozilla.com/latest
- [ ] Signed final XPI uploaded to https://testpilot.firefox.com/files/@testpilot-containers/latest
- [x] Update Containers ID @testpilot-containers, pulse@mozilla.com
- [x] Incompatibility between Snooze Tabs and Containers
- [x] Pre-feedback image for Pulse (see Tracking Protection)
- [x] Remove `dev:` flag in YAML
- [x] Confirm `launch_date` time of ~~2pm PST 2/21 *at risk*~~ 9am PST (after we've had a chance to check-in with SV)
- [ ] Production push

**Comment by ghost** [comment]
Pulse is uploaded
