### ISSUE TITLE
Test Pilot should remember if I had "Past Experiments" toggled on the home page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2216]
Found in https://testpilot.dev.mozaws.net/__version__ (b5ff0ca4df7113ffefe0859f130dffcd03d067c5):

```json
{ "commit": "b5ff0ca4df7113ffefe0859f130dffcd03d067c5",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/3295" }
```

---

### Steps to reproduce:
1. Go to https://testpilot.dev.mozaws.net/
1. Toggle "View Past Experiments".
1. Click on one of the experiments (for example, "Tracking Protection").
1. Click the logo in the top-left corner or the back button to go back to the homepage.

### Actual results:
After returning to the home page, the "Past Experiments" are closed.

### Expected results:
"View Past Experiments" should remember it's previous toggled state.

**Comment by SoftVision-PaulOiegas** [comment]
I've seen this also but from a performance perspective, I haven't considered it a bug. Less items to load, faster page load... But of course, it's up to you guys.

**Comment by ckprice** [comment]
Edgecase-y, closing.
