### ISSUE TITLE
Create a standard engagment metric/event thing for all experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#222]
@nchapman @lmorchard we should have a standard metric to help understand engagement with each experiment. Since every experiment will have different usage rates this metric will only be used to compare internally to an experiment. The Idea Town Council should determine for every experiment which user action should emit the event to be measured.

**Comment by clouserw** [comment]
I think my readme-metrics.md addresses this...

**Comment by meandavejustice** [comment]
yeah pretty sure we settled on net promoter score

**Comment by ckprice** [comment]
@johngruen going to close this per the above comments. Re-open if you think it is still needed.
