### ISSUE TITLE
[release] 2017-02-21 is on Stage (product launch)

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#2222]
We have a planned launch tomorrow morning (`launch_date` is set for 9am PST). This QA verification should focus on any major bugs which appear with these add-ons enabled together (on top of the normal release verification).

Tomorrow morning during our check-in, we will make the decision to move forward with the product launch.

**Note**: stage will not have the experiments listed until the `launch_date` set for tomorrow. So please use dev to install the new experiments.

Please QA stage. Let's use this issue to track deployment status to production. I've assigned this to Paul, but we should all be checking out stage a bit.

* Verification documentation: https://github.com/mozilla/testpilot/blob/master/docs/development/verification.md
* Release notes: https://github.com/mozilla/testpilot/releases

http://testpilot.stage.mozaws.net/

**Comment by pdehaan** [comment]
I currently see https://testpilot.stage.mozaws.net/__version__

```
{ "commit": "9fcc2609e569fee1552a2759c568c4b661d86d22",
  "version": "2017-02-21",
  "source": "https://github.com/mozilla/testpilot" }
```

But https://testpilot.stage.mozaws.net/ has none of the new e'speriments...

**Comment by pdehaan** [comment]
Interestingly, the https://testpilot.stage.mozaws.net/api/experiments.json API endpoint _does_ show the new experiments, so I'm wondering if this is some future `launch_date` issue:

```js
{
  id: 12,
  title: "Containers",
  slug: "containers",
  locales: [
    "en"
  ],
  launch_date: "2017-02-22T17:00:00.00Z",
  ...
}
```

**Comment by ckprice** [comment]
> so I'm wondering if this is some future launch_date issue:

Yeah, stage won't show the experiments since the launch date is set for tomorrow (I've updated the issue opening). In hindsight since we're deploying to production tomorrow morning, we could have just set the launch date for now, but please use dev to install the add-ons.

**Comment by ghost** [comment]
containers is not ready to install.  Amazon rolled out a fancy new UI for AWS in the past hour or so and uploading is broken for me.  Hopefully it's working by morning.  Luke said he emailed a copy of the add-on to Paul, just installing off of our site won't work yet.

**Comment by flodolo** [comment]
Just to understand if I'm reading this right: are we pushing out two new experiments without giving any chance to localize that content, given that string were exposed right before tagging the release?

**Comment by SoftVision-PaulOiegas** [comment]
@ckprice @wresuolc Dev server is down at the moment. 😢 We cannot test stage with dev installed experiments, so I need to do custom repo builds to test this. Not sure if this will replicate the right behavior but still better than nothing. 

L.E. Actually it recovered for the moment. I'll let you know if this happens again.

**Comment by ghost** [comment]
containers is uploaded.  all experiments are on s3 now.
