### ISSUE TITLE
Dev server is showing string IDs instead of text

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2223]
Browser set to Italian, strings are not translated yet

![tp1](https://cloud.githubusercontent.com/assets/3644868/23207880/30b8efe8-f8f3-11e6-96d2-e9227cfba5e2.png)

![Uploading tp2.png…]()

**Comment by johngruen** [comment]
b/c of the en only time crunch we might want to locale whitelist these to en only until they get coverage in other locales. @ckprice thoughts?

**Comment by lmorchard** [comment]
FWIW, L20N doesn't fall back to en-US - if strings are missing from a translation, the IDs are shown
