### ISSUE TITLE
Set up logging/metrics for the server side

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#223]
We should ensure the server side has some useful logging - i.e. for performance, monitoring, etc. This is separate from any metrics about experiments or feedback. Maybe use statsd? datadog? new relic?

**Comment by meandavejustice** [comment]
@lmorchard What is our story for this now?

**Comment by lmorchard** [comment]
No story yet, really. We have some Django logs in dev, but not sure what production will look like. Haven't actually looked into statsd / datadog / new relic.

**Comment by meandavejustice** [comment]
Do we have existing examples to look to within mozilla?

**Comment by meandavejustice** [comment]
cc @6a68

**Comment by jaredhirsch** [comment]
Handling server logs is the main use case for heka and the related data pipeline work, which includes some default dashboard options (kibana, I think?). We should set up a meeting with that team--they'll be able to help us figure out which parts they can handle, and which parts we'll need to think through. cc @kparlante 

Public wiki docs: https://wiki.mozilla.org/CloudServices/DataPipeline

Private wiki getting started doc for teams building new servers: https://mana.mozilla.org/wiki/display/CLOUDSERVICES/Cloud+Services+Metrics+Onboarding

**Comment by meandavejustice** [comment]
Sounds good @6a68, we can get a meeting setup for maybe beginning of 2016.

**Comment by lmorchard** [comment]
One more data point: Saw an email go out just before the new year that we should stop using New Relic for sites per privacy team evaluation of their opt-out options for our users who want to avoid tracking. We're not using it here, but I found it useful on MDN. Guess we'll just steer clear of that :)

**Comment by kparlante** [comment]
Looking forward to talking to you all about idea-town data @6a68, @meandavejustice

**Comment by lmorchard** [comment]
From today's status meeting: Noting that this bug is mainly about main site health & performance, and not metrics on individual experiments (#234). This will probably be solved by whatever happy path is supported by ops, possibly plus Datadog for performance metrics.

**Comment by clouserw** [comment]
Some good notes at https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=40049778 about this.

We'll be sending datadog metrics to $STATD_HOST and $STATD_PORT

**Comment by mostlygeek** [comment]
Since ops will be deploying this app via Docker, we should get this repo up to the new [Dockerflow spec](https://github.com/mozilla-services/dockerflow).

The spec also documents the two available way containers can log / send metrics. See: [https://github.com/mozilla-services/dockerflow#sending-metrics-and-logs](https://github.com/mozilla-services/dockerflow#sending-metrics-and-logs)

**Comment by lmorchard** [comment]
> Since ops will be deploying this app via Docker, we should get this repo up to the new Dockerflow spec.

FWIW, that's #401, #398, #394. No issue open for stats/datadog, but we're not sending any metrics along those lines yet. Might be worth opening another issue about that, at least for coming up with some things to track
