### ISSUE TITLE
Metrics checklist for new experiments

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2239]
Our docs should include a clear todo list for new experiments to get metrics flowing to all the appropriate places. Also need some documentation of contact people from each team, and how to make / where to find dashboards.

**Comment by ghost** [comment]
Let's update the Test Pilot metrics.md

**Comment by johngruen** [comment]
@6a68 here are the seven items from our trello list: https://trello.com/c/Oy7VVaHr/14-metrics

* Metrics.md in the repo in a docs folder explaining the telemetry ping being sent by the experiment
* signoff of metrics.md by someone in measurements (ilana or rebecca)
* Confirm that telemetry pings are digestible
* Bug ___ -- Get data into re:dash
* Bug __ -- Create dashboard
* Survey created for the experiment (rob rayborn) with URL in the testpilot-meta repo
* File an issue in ping-centre's github for a new experiment
