### ISSUE TITLE
url not working in Firefox but works well in Opera browser

### ISSUE THREAD

**Issue by sivalingam41** [mozilla/testpilot#2241]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Containers:           https://github.com/mozilla/testpilot-containers/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Pulse:                https://github.com/mozilla/pulse/issues/new
- Snooze Tabs:          https://github.com/bwinton/SnoozeTabs/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
![screen shot 2017-02-26 at 7 09 52 pm](https://cloud.githubusercontent.com/assets/21272697/23339119/3d52f102-fc56-11e6-8cba-544baadb40a9.png)

**Comment by ckprice** [comment]
Hi! This repository is specific to the Firefox Test Pilot program. This isn't the appropriate place for general Firefox or page loading reports (you could try https://webcompat.com/).
