### ISSUE TITLE
Add Contribute.json

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2243]
didn't know this existed until now: 
https://github.com/mozilla/contribute.json

**Comment by peterbe** [comment]
Official site repo is https://www.contributejson.org/
It's a mozilla originated project but we want to to be as prevalent as robots.txt but specifically for projects that welcome contributions.

**Comment by lmorchard** [comment]
We had a contribute.json. It disappeared with the static publishing switch:

https://github.com/mozilla/testpilot/issues/1582

**Comment by pdehaan** [comment]
At least the file is still there https://github.com/mozilla/testpilot/blob/master/contribute.json, so it looks like we may just need to set up a route to it (and make sure it is served with the correct content type).

**Comment by ghost** [comment]
Closing this as a dupe of #1582
