### ISSUE TITLE
Firefox hangs for ~30s when enabling Containers experiment from Test Pilot on Windows

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2250]
[Affected versions]:
- Firefox 51.0.1 and up
- Containers 1.0.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed from "https://testpilot.dev.mozaws.net" on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net".
2. Click the Containers experiment card and enabled it.
3. Observe the browser behavior.

[Expected result]:
- The Containers experiment is successfully enabled without any problems.

[Actual result]:
- The browser hangs for ~30 seconds when enabling the experiment.

[Notes]:
- The issue is also reproducible on Test Pilot stage server. I have changed my system date in the future (03/02/2017) in order to have Containers experiment available in Test Pilot.
- I have observed in browser console a lots of "DOWNLOAD_PROGRESS" messages after the browser becomes responsive.
- Here is a screen shot with browser console: https://goo.gl/TFGOhk
- Here is a screen recording with the issue: https://goo.gl/yFa8Nv

**Comment by ghost** [comment]
This should be fixed up now

**Comment by ghost** [comment]
PS - we're scheduled to go live tomorrow at noon PST

**Comment by kjozwiak** [comment]
Working for me... 

STR used:

* brand new FX installation with a new profile
* created "testpilot.env;dev" under about:config
* installed test pilot via https://testpilot.dev.mozaws.net/
* clicked on the "Containers" tile and selected "Enable Containers"
* waited about 8-10 seconds for Containers to enable every single time

Platforms Used:

* Win 10 Pro x64 [Personal Desktop] - PASSED
* Win 10 Pro x64 [VM] - PASSED
* Win 8.1 x64 [VM] - PASSED
* Win 7 Pro x64 [VM] - PASSED

**Comment by SoftVision-CosminMuntean** [comment]
I have retest this issue and is no longer reproducible with the latest Containers (1.0.3) version enabled from Test Pilot. Marking this as verified.
