### ISSUE TITLE
Test Pilot add-on not served with X-Target-Digest

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2266]
Ref: #1474, #1537, [this Discourse thread](https://discourse.mozilla-community.org/t/firefox-add-on-test-pilot-wont-install/13822).

We should be serving the Test Pilot add-on with the same redirect/headers as we do the experiments.

**Comment by lmorchard** [comment]
We can set headers for the XPI here, I think: https://github.com/mozilla/testpilot/blob/master/bin/deploy.sh#L90

Edit: Oh, wait, no - [we can't set the header on the XPI, we have to send the header in a 302 redirect to the .xpi](https://github.com/mozilla/testpilot/issues/1537#issuecomment-252095226). That complicates things 😞

**Comment by ghost** [comment]
I think we should just use the system we have for hosting all our other add-ons to host this one too.

**Comment by ghost** [comment]
One thing to consider using the other script is that the add-on could get out of sync from the site for a few minutes while one completes before the other.

Also, the script is expecting the branch to be called 'production' not 'production-static'.  I don't know how easy that is to change in the script per-repository.

**Comment by ghost** [comment]
@relud The /latest/ URL exists now, but it looks like the x-amz-meta- prefixes aren't being stripped.  Are those rules running on this S3 bucket like they are for /files/?

```
$ curl -v 'https://testpilot.dev.mozaws.net/static/addon/latest'
[...]
< x-amz-meta-x-target-digest: sha256:1e0b66604d0ef92108d2632d73815f09383b831466d8df65c653de47a10e63ad
< x-amz-meta-location: /static/addon/addon.xpi
```

**Comment by relud** [comment]
I don't run dev, only stage and prod

**Comment by relud** [comment]
that said, the problem is that you prefixed the metadata tag with x-amz-meta-, but amazon also prefixes the tag with x-amz-meta-, so the double-prefix is properly reduced to a single prefix.

**Comment by ghost** [comment]
Oh, that would be cool.  Fixed in ^, will check after it lands.
