### ISSUE TITLE
CONTROL-TAB not working on main TestPilot page

### ISSUE THREAD

**Issue by aplatypus** [mozilla/testpilot#2267]
Hi

On the TestPilot page 
- https://testpilot.firefox.com/

I used CTRL/LEFT-CLICK  to open the "Pulse" option and once again the "Containers" option in new Browser Tabs.  Instead of opening a new tab Firefox navigated to the page _**within the same tab**_ and I was forced to back-tab (ALT/LEFT-ARROW) to get the TestPilot page 
Control-CLICK  back.

Control-CLICK is a standard browser keystroke.  I tested the Control-CLICK with other web pages in firefox and in Google's chrome.  All opened the link on a NEW tab.  

Thus I think it is the TestPilot page that has the problem, and not Firefox.

As a work-around I was able to use the drop-down menu on these buttons to "Open Link in New Tab" with Firefox and that worked.  This also confirmed for me that the function is present and working.  It is just that the standard key behaviour has been disabled.

- Please restore our CTRL/LEFT-CLICK to  successfully "Open Link in New Tab".

Many thanks

  aplatypus

**Comment by SoftVision-PaulOiegas** [comment]
Hi @aplatypus and thanks for your report ! However, this issue is already tracked under #1795. If you have any suggestions on this, please post them there.

Have a nice day ! :)
