### ISSUE TITLE
[Mac OS] Test Pilot page header text is not rendered in Fira sans font on Safari 9.x

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2268]
[Notes]:
- This only reproduces on OS X 10.11 and lower due to latest Safari browser version supported on it (9.x)

[Affected versions]:
- Safari 9.x

[Affected Platforms]:
- Mac OS 10.11 and lower

[Prerequisites]:
- Have an Apple computer with Mac OS 10.11 in order to have Safari 9.x available. 

[Steps to reproduce]:
1. Open Safari browser and choose to navigate to https://testpilot.dev.mozaws.net page.
2. Open Firefox browser and navigate to the same page.
3. Observe the font used on Test Pilot page headers in both browsers.

[Expected result]:
- The Fira Sans font from sans-serif family is used on both Safari and Firefox. 

[Actual result]:
- On Safari browser a default font from sans-serif family is displayed.

![safari 9 x vs firefox](https://cloud.githubusercontent.com/assets/17258026/23517921/79c4015e-ff7a-11e6-81ab-90287a238248.png)

**Comment by ghost** [comment]
This is a very small % of traffic and not something we are going to work on.  Thanks for filing!
