### ISSUE TITLE
Let users switch language on the website

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2271]
Currently you have to pick what Test Pilot thinks it's right, it would be useful to have a language switcher.

For example, you currently can't see some of the experiments without changing your accept-languages with English first.

**Comment by johngruen** [comment]
Difficulty here is that we have some experiments that are strictly region locked.

**Comment by johngruen** [comment]
We could revisit this when we modify the locale in the path.

**Comment by flodolo** [comment]
> Difficulty here is that we have some experiments that are strictly region locked.

I honestly don't understand how this ties into the ability to switch language. Also, I think we're associating experiments to languages, not regions?
