### ISSUE TITLE
How many users have mozAddonManager?

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2275]
It would be great to assume mozAddonManager is always available. [Looks like](https://wiki.mozilla.org/RapidRelease/Calendar) the FF 45 ESR version will be supported until June, which probably does not have mozAddonManager (but I'm not sure).

Questions:

- which Firefox versions have mozAddonManager support?
- how many users are on versions without mozAddonManager support?

We can probably get the answers from the FF version number in GA.

**Comment by ghost** [comment]
We can find versions from our GA stats, although there are some edge cases which will give us some slop.

**Comment by johngruen** [comment]
Revisting this, we discussed in standup the other day, since we officially don't support pre-49 Firefox. It looks like:
* ~86.7% of all FF visitors are 49+
* ~1.35% of FF visitors are on 45 [ESR]
* ~5.16% of FF visitors are on 46-48

**Comment by johngruen** [comment]
Confirmed with @andymckay that mozAddonManager did not go into 45 ESR.

Also, here's the original issue where we got privileges
https://bugzilla.mozilla.org/show_bug.cgi?id=1288178

**Comment by jaredhirsch** [comment]
@johngruen Awesome! Thanks for looking that up. Followup product question for you: is ~87% of users good enough to require mozAddonManager, and show the remaining ~13% an "upgrade FF" message instead?

**Comment by ghost** [comment]
@johngruen wants to look into options for how we propose upgrading to people

**Comment by fzzzy** [comment]
There's an extensive plan for notifying users to upgrade by doing feature detection on mozAddonManager here:

https://github.com/mozilla/testpilot/issues/2364

I'm going to close this as a dupe of that now.
