### ISSUE TITLE
Can't see latest experiments

### ISSUE THREAD

**Issue by dsestero** [mozilla/testpilot#2278]
Hi I love FF and would like to contribute to the new experiments. Alas I can't see them. I see only page shot, min vid, activity stream, and tab center. This morning I also tried to remove and install again test pilot but no change. With Test pilot add-on remove if I brows page https://testpilot.firefox.com I see only those four.
I am on Ubuntu 16.04.2 64 bit with Firefox 51.0.1
Thanks,
Dario Sestero

**Comment by ghost** [comment]
This is likely because we restrict some experiments to certain locales.  Let's remove the restriction for English-only strings.  We'll need to fix #2249 first.

**Comment by lmorchard** [comment]
Seems #2265 is the same issue as this?

**Comment by dsestero** [comment]
Ah thank you. By changing the preferred languages order in FF preferences I
can now see them all!
Ciao
Dario

2017-03-03 18:07 GMT+01:00 Les Orchard <notifications@github.com>:
