### ISSUE TITLE
Quicker feedback report

### ISSUE THREAD

**Issue by smichel17** [mozilla/testpilot#2281]
I often find myself wanting to give quicker feedback about a test than Test Pilot currently allows. It seems kind of silly to take 5 minutes to fill out the same survey questions over and over again in order to give 1 or 2 sentences of feedback.

For example, I'm piloting the Containers feature. I wanted to give feedback that I'd like to be able to choose what container external links (eg, from my email client) open in. I [ended up on github](https://github.com/mozilla/testpilot-containers/issues/311#issuecomment-284010300), but that's also inefficient because I either spend a long time searching for duplicates or you end up with a lot of duplicates.

(I ended up spending 10 minutes making a mockup anyway, but that's beside the point 😛)

**Comment by ghost** [comment]
I'll mark this as needs product input, but if you have suggestions about what you'd like to see please add a comment.  Thanks.

**Comment by smichel17** [comment]
![feedback-form](https://cloud.githubusercontent.com/assets/6563664/23572267/dbc74cdc-003b-11e7-87d6-83e32db9e60e.png)

It's one of taiga.io's feedback boxes (really, just the cleanest text box I could quickly find) inside the type of drop-down that Snooze Tabs uses, with the test pilot icon. There should probably also be a link to the test pilot site, a way to select which experiment I'm giving feedback about, and maybe one question on sentiment), but I think it's good enough as a reference. The point is, I can click the icon, then maybe 3-4 more times, type a sentence, and submit feedback.

An example use case for this feature would be: someone is trying out an experiment, gets frustrated about something for a couple seconds, and wants to be helpful by letting you know about it. The quicker and easier that process is, the more people will do it.

**Comment by johngruen** [comment]
I don't think we're doing anything in the XPI, but we're going to start rolling feedback into experiments themselves. Design team is working on a spec, will close this bug and file a new one with the specs.
