### ISSUE TITLE
Side Tab does not close and remains as a blank space 

### ISSUE THREAD

**Issue by ayazmaqbool** [mozilla/testpilot#2285]
Issue for Side Tab 

Issue : After clicking X on side tab for a window , The tab still remains with Blank space. Attached screen shot for your reference .
![sidetab](https://cloud.githubusercontent.com/assets/22630878/23597608/55fb2c60-025a-11e7-86f2-605305ba9778.png)

**Comment by SoftVision-CiprianMuresan** [comment]
I have cloned this issue to the [Tab Center repo](https://github.com/bwinton/TabCenter/issues/991).
If you have additional add-ons, besides the Test Pilot ones, could you also add them to the report? 

Closing this issue in favor of the one opened in Tab Center.
