### ISSUE TITLE
Define General Strategy for Animations

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#229]
PR #224 hints at some scaling issues with adding and removing various classes. 

Straw proposal: lets stick with using CSS class toggles, but optimize for scale. A few thoughts: 
- Use http://ampersandjs.com/docs#ampersand-view-cacheelements to streamline DOM selection
- Use http://amp.ampersandjs.com/# DOM methods to toggle classes
- Possibly use something like: https://www.npmjs.com/package/gulp-json-sass to cross-register duration variables between sass and ampersand view modules.

**Comment by meandavejustice** [comment]
dom bindings docs => https://github.com/ampersandjs/ampersand-dom-bindings#readme
