### ISSUE TITLE
The "Settings" doorhanger can no longer be dismissed by clicking outside of it

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2294]
[Affected versions]:
- Firefox 52.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- Test Pilot add-on was previously installed from "https://testpilot.dev.mozaws.net" on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net".
2. Click the "Settings" button from the top right corner of the page.
3. Click outside the "Settings" doorhanger and observe the behavior.

[Expected result]:
- The "Settings" doorhanger is automatically dismissed.

[Actual result]:
- The "Settings" doorhanger is not dismissed.

[Notes:]
- The only way to dismissed the "Settings" doorhanger is to click again the button.
- Here is a screen recording with the issue:
![settings doorhanger](https://cloud.githubusercontent.com/assets/19226534/23713771/9f646d22-042f-11e7-91ec-fdb0a4bc2ce9.gif)

**Comment by johngruen** [comment]
How does this keep happening :)

**Comment by jaredhirsch** [comment]
guessing this was regressed by #2256, which landed yesterday

**Comment by pmespresso** [comment]
Oops, I'll get right working on it.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking as verified.
