### ISSUE TITLE
Add some buttons to "How do you like [experiment X]" ...

### ISSUE THREAD

**Issue by groovecoder** [mozilla/testpilot#2299]
When Test Pilot asks a user how they like an experiment, and they rate it with 4+ stars, show additional call-to-action buttons, so we can learn if the experiment encourages Firefox retention & growth:

* Make Firefox your default browser
* Share this Firefox experiment (twitter, etc.)

These are even stronger signals than a 4- or 5-star rating. By measuring the clicks to these buttons, we should learn which experiments cause users to switch (back) to Firefox, and promote Firefox to others.

**Comment by groovecoder** [comment]
Note: the "Make Firefox your default browser" option doesn't need to be functional - it could simply be a link to https://support.mozilla.org/t5/Customize-controls-options-and/Make-Firefox-your-default-browser/ta-p/2627

**Comment by johngruen** [comment]
#2562

**Comment by chuckharmston** [comment]
Closing since heartbeat ratings are gone.
