### ISSUE TITLE
Snooze Tabs page wrongly displays placeholders for [es-es] locale and does not fallback to [es] or [en] locales

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2301]
[Affected versions]:
- Firefox 52.0 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A new Firefox profile was created and content language was set to [es-ES] from "Options>Content>Language" section.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Click on the "Snooze Tabs" experiment card. 
3. Observe the experiment description and the "Privacy Policy" area on middle left of the page.  

[Expected result]:
- The default Spanish translation is displayed in both areas for the experiment.
or
- If there is no translation for the selected content option, the en-us translation is displayed as fallback on both areas.

[Actual result]:
- The en-us description is shortly displayed before it is replaced by placeholders in both areas.

[Notes]:
- Refreshing the page does not fix the issue.
- This issue is only present on Snooze Tabs experiment page.
- The issue is not reproducible on default [es] localization.
- Here is a screen recording of the issue: https://goo.gl/NsSkrV.

**Comment by ghost** [comment]
maybe related to #2249

**Comment by flodolo** [comment]
There's no Snooze Tabs experiment on the home page for Spanish, it was enabled only for en-US. Once you reach the page, it was expected to display IDs instead of strings, now it should fall back to en-US strings instead.

**Comment by SoftVision-PaulOiegas** [comment]
The placeholders from Snooze Tabs experiment page, correctly fallback to English now when there is no translation.
