### ISSUE TITLE
Support custom Ping Centre ping for snoozetabs

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2312]
Once the ping-centre library is integrated, and the snoozetabs ping-centre schema is defined, add metrics code to the test pilot addon that uses a different ping-centre schema for snooze tabs.

**Comment by lmorchard** [comment]
Is this something that *must* live in the Test Pilot add-on? If so, this sounds like every new experiment is going to need additions to the Test Pilot add-on. That means we'll have to bind together releases of the two - at least for metrics changes. Might be better if there were some way to let this live in the experiment - e.g. passed along in usage of the testpilot-metrics module
