### ISSUE TITLE
Localization is not working in other language than English

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2318]
[Affected versions]:
- Firefox 52.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have any language set other than English in "about:preferences#content" on a new Firefox profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Observe the Test Pilot page language.

[Expected result]:
- The Test Pilot page is correctly displayed in the chosen language.

[Actual result]:
- The Test Pilot page is wrongly displayed in English.

[Notes]:
- This issue is also reproducible on localized Firefox builds.
- This issue is only reproducible on stage server.
- Here is a screen recording with the issue:
![test pilot localization](https://cloud.githubusercontent.com/assets/19226534/23900108/954f7792-08c0-11e7-88a1-58c594754203.gif)

**Comment by flodolo** [comment]
Localization seems to work as expected after #2320

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using multiples locales and is no longer reproducible on stage. Closing as verified.
