### ISSUE TITLE
Missing space between "in" string and "this Privacy Notice" link from the Newsletter section

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2319]
[Affected versions]:
- Firefox 52.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Scroll down to the bottom of the page until the "Newsletter" section is reached.
3. Enter at least one character in the text box.
4. Observe the text under the email text box.

[Expected result]:
- The text is correctly displayed without any typos.

[Actual result]:
- There is no space between "in" string and "this Privacy Notice" link.

[Notes]:
- This issue is only reproducible on stage server.
- Here is a screen shot with the issue:
![missing space](https://cloud.githubusercontent.com/assets/19226534/23904159/8f7fe78e-08cf-11e7-8726-34292643016f.png)

**Comment by flodolo** [comment]
Looks good on stage right now

![schermata 2017-03-14 alle 17 52 45](https://cloud.githubusercontent.com/assets/3644868/23912117/133a9060-08df-11e7-9f0a-a26063b93b28.png)

**Comment by SoftVision-CosminMuntean** [comment]
Yes, I have retested this issue on stage and looks to be fixed. Closing as verified.
