### ISSUE TITLE
The Containers incompatibility warning message is visible when the page is refreshing

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2323]
[Affected versions]:
- Firefox 52.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on a new profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Click the Containers experiment card.
3. Observe the experiment details page when is refreshing.

[Expected result]:
- The Containers incompatibility warning message is not displayed.

[Actual result]:
- The Containers incompatibility warning message is displayed when the page is refreshing.

[Notes]:
- Here is a screen recording with the issue:
![containers warning message](https://cloud.githubusercontent.com/assets/19226534/23957042/1171e04e-09a7-11e7-9c25-b416ff3e043e.gif)

**Comment by fzzzy** [comment]
I have noticed this recently too. I think the message should be display: none by default and made visible if the message needs to be shown.

**Comment by SoftVision-PaulOiegas** [comment]
I think this is a "leftover" from the day we decided to postpone the Containers launch by 1 week. I'm not sure this should be displayed at all. The devs on Containers already addressed the compatibility issues that the message was preparing the users for.
Please correct me if I'm wrong.

**Comment by fzzzy** [comment]
If someone can confirm that we don't need the message at all any more, then I can just remove it.

**Comment by fzzzy** [comment]
I think this was fixed by the new loading indicator behavior. Please re-open if this can still be reproduced.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible. Marking as verified.
