### ISSUE TITLE
Stop displaying a "New" badge on the toolbar icon

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2325]
Just realized that Test Pilot is trying to show a "New" badge on the icon. Too bad that basically no language will fit in a 4-characters space (the full word is "Novità", "Novi" is a non-sense in Italian, or a very good brand of chocolate…)

![schermata 2017-03-16 alle 08 37 29](https://cloud.githubusercontent.com/assets/3644868/23986350/f5a9cca0-0a23-11e7-873b-88d0dd5c361c.png)

**Comment by SoftVision-PaulOiegas** [comment]
Yep, got it also today on my daily work profile out of the "blue" 😄.

**Comment by johngruen** [comment]
@flodolo we have no other way to indicate new stuff outside of popping a tab and the SDK api is pretty restrictive. We also know that the badged icon converts well for driving people to experiments. We won't remove it but i wonder if it needs to be localized at all?

**Comment by johngruen** [comment]
@fangshih, could we do something similar to what we're doing with Screenshots here? A custom version of the icon w/ a star or similar. We'd need both dark and light themed versions in this case.

**Comment by Pekochen** [comment]
[News alerts Badge.zip](https://github.com/mozilla/testpilot/files/1007130/News.alerts.Badge.zip)
Here is the measurement for new badge.
I am not sure which format should I provide, not quite sure how to find the exist toolbar icon file. 
Can you help to give me exist file? Just want to make sure the correct size and position of icon.
Thanks!

**Comment by johngruen** [comment]
@johngruen, let's discuss this in UX meeting next tuesday

**Comment by johngruen** [comment]
Let's think *more insane* here 💯

**Comment by johngruen** [comment]
@chenmorpheus We learned from Sharon's research that the star is not the way to go with badges. I'd like to do something a little more out there and eye catching here if possible. For reference, here's what the screenshots badge wound up looking like, for reference:

https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/icons/icon-starred-32.svg

**Comment by ChenMorpheus** [comment]
@johngruen Sorry that I might misunderstand something here. I thought the one for screenshots would also apply to Test Pilot, and even the badging system for Design System. However, if that's not the case, we'll try to come up a new badge specifically for Test Pilot.
