### ISSUE TITLE
Snooze Tabs listing page showing "your locale (zh) is unsupported" while zh-TW is supported

### ISSUE THREAD

**Issue by petercpg** [mozilla/testpilot#2328]
STR:
1. Add and move zh-TW to the top of Accept-language list of Firefox.
2. Go to https://testpilot.firefox.com/experiments/snooze-tabs and observe the contents. If the page is opened before switching language fallback list, reload the page.

Expected: 
"This experiment is not supported in your language ( zh )." block is not displayed to  zh-TW users. I can find the experiment localized to zh-TW after enabling.

Actual:
"This experiment is not supported in your language ( zh )." block is displayed. 

Thanks!

**Comment by lmorchard** [comment]
While it's true we *did* just release Snooze Tabs with a lot of new translations, we're not quite yet ready to officially tag it as supported in those new locales. There are some areas ([like the calendar widget](https://github.com/bwinton/SnoozeTabs/issues/261)) that still need some attention.

Some details here: https://discourse.mozilla-community.org/t/snooze-tabs-v1-0-15-released/14460
