### ISSUE TITLE
installing test pilot addon when it is already installed but disabled is poorly handled

### ISSUE THREAD

**Issue by globau** [mozilla/testpilot#2331]
when the test pilot addon is installed but disabled, clicking on the "install" button changes it to "installing.." but then nothing else happens.

the addon is not re-enabled, nor is the user informed that the addon is installed and could be manually enabled.

**Comment by fzzzy** [comment]
Thanks for the report. There has been some work in this area recently that may help, but I'll want to keep this bug open to confirm that this particular case is handled properly.

**Comment by fzzzy** [comment]
This particular bug is still happening on master. I'll want to take a look at fixing this soon.

**Comment by chuckharmston** [comment]
This no longer reproduces. Closing!
