### ISSUE TITLE
Characters are automatically deleted when typed in the text box from "Newsletter" section (dev server)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2334]
[Notes]:
- Also the "Sign Up Now" button seems to be inactive (on desktop and mobile). Here is the error displayed in browser console after clicking the button: https://goo.gl/gnSUop.

[Affected versions]:
- Firefox 52.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Scroll down to the bottom of the page until the "Newsletter" section is reached.
3. Enter at least one character in the text box and observe the page behavior.

[Expected result]:
- The entered character is displayed and hint text is removed from the text box.

[Actual result]:
- The entered character is automatically deleted and also the "Checkbox" is not displayed.

[Additional Notes]:
- Here is a screenshot with browser console errors:
![typing in email tex boc](https://cloud.githubusercontent.com/assets/19226534/24095800/64de4704-0d67-11e7-8400-9f57f24e4a72.png)

- Here is a screen recording with the issue:
![typing in email text box](https://cloud.githubusercontent.com/assets/19226534/24095806/70bb3956-0d67-11e7-8a5c-684faceb55df.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and the "Newsletter" functionality is working as expected. 

But, the "Sing Up Now" button seems to be inactive (on desktop and mobile). After I successfully sign up with an valid email, some errors are displayed in browser console:
![sign up](https://cloud.githubusercontent.com/assets/19226534/24142213/9504f6ae-0e2e-11e7-99ae-b4b60afdb54a.png)

Here is a screenshot with the issue:
![sign up button](https://cloud.githubusercontent.com/assets/19226534/24142205/91bc45c4-0e2e-11e7-84f7-13b3d7834fe5.png)

@fzzzy , @dannycoates Should I log a different issue for this?

**Comment by fzzzy** [comment]
@SoftVision-CosminMuntean Yes, I think log a different bug for this.
