### ISSUE TITLE
"Just launched!" message is wrongly displayed for each experiment on details page (dev server)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2337]
**[Notes]:**
- Also, **the number of participants** is no longer displayed on the experiments cards. Here is a screenshot: https://goo.gl/JnoJt4.

[Affected versions]:
- Firefox 52.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click on an available experiment card.
3. Observe the message under the experiment logo.

[Expected result]:
- "There are x people trying <experiment_name> right now!" message is displayed.

[Actual result]:
- "Just launched!" message is wrongly displayed under the experiment logo.

[Additional Notes]:
- "Just launched" message is only displayed on the experiments details page.
- Before this issue, when the experiment page was refreshed the "Just launched" message was displayed instead of the number of participants. This behaviour can be observed on stage and production server. Here is a screen recording: https://goo.gl/e7B1dG
- Here is a screen shot with the issue:
![just launched](https://cloud.githubusercontent.com/assets/19226534/24142460/4bcffa3c-0e2f-11e7-8710-75ee841679c9.png)

**Comment by fzzzy** [comment]
This was broken by updating the isomorphic-fetch library. It changed the response.json() method from synchronously returning the result to returning a Promise. 👎

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking this as verified.
