### ISSUE TITLE
Test Pilot Metrics Dashboard

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#234]
What should this thing look like?

**Comment by johngruen** [comment]
Here's a link to the working doc: https://docs.google.com/a/mozilla.com/document/d/1FxzBoA1ykMQNMpcgi8ZRR68sCs7lajAFnrwi9fGjKGs/edit?usp=sharing

Here's a mockup: 
https://invis.io/HB5BU02AP

**Comment by johngruen** [comment]
https://wiki.mozilla.org/Test_Pilot/Metrics

**Comment by clouserw** [comment]
RFC for draft plan @ https://docs.google.com/document/d/1D0QvPngp3Va7Q1AIR8Bp_4GYltszsYbUytvXw_gV8Ok/edit

**Comment by clouserw** [comment]
Plan now lives at https://github.com/mozilla/testpilot/blob/master/docs/README-METRICS.md

Bugs filed for telemetry hookups: https://bugzilla.mozilla.org/show_bug.cgi?id=1255184 and https://bugzilla.mozilla.org/show_bug.cgi?id=1255182

Next steps:  Document how tests will use our metrics pipeline.  File Issues for ensuring test pilot is hooked up to log in the formats detailed in the plan.  Ensure data is flowing into the pipeline and showing up in Redshift.  Build some visualizations from the data in Redshift (probably using Periscope).

**Comment by chuckharmston** [comment]
> Next steps: Document how tests will use our metrics pipeline. File Issues for ensuring test pilot is hooked up to log in the formats detailed in the plan. Ensure data is flowing into the pipeline and showing up in Redshift. Build some visualizations from the data in Redshift (probably using Periscope).

Related: https://github.com/mozilla/universal-search/pull/79

**Comment by chuckharmston** [comment]
> Next steps: Document how tests will use our metrics pipeline. File Issues for ensuring test pilot is hooked up to log in the formats detailed in the plan. Ensure data is flowing into the pipeline and showing up in Redshift. Build some visualizations from the data in Redshift (probably using Periscope).

We should also make sure that there is a client identifier that is passed on to Telemetry to allow calculations of retention rate and user type analysis. It should be a UUID derived from neither the test pilot user ID nor the FxA ID. Activity Stream is [doing something similar](https://github.com/mozilla/activity-streams/blob/master/data_dictionary.md) with their `client_id` property.

**Comment by clouserw** [comment]
Telemetry has a unique ID

**Comment by clouserw** [comment]
I filed https://github.com/mozilla/testpilot/issues/479 for the actual implementation of the metrics wrapper and the documentation.  That means all that is left for this issue is:
- Get data flowing (the bugs referenced in above comments)
- Build a visualization (going to use a 3rd party tool for this)

So, this issue is probably no longer "too large" although it does involve 3rd parties so still some unknowns...

**Comment by lmorchard** [comment]
After thinking a bunch about #401 and #479 and #481 and #430, I'm still really fuzzy on exactly how and which metrics data should be captured and where it flows. So, [I started drawing a picture in Google Draw](https://docs.google.com/a/mozilla.com/drawings/d/1McTKdbMog0OQ9Mg29DCPRoGL43NODOs2ZqS1bAkvhQ0/edit?usp=sharing). 

Some of this is measurement of Test Pilot itself and some of it is measuring experiments. But, things cross boundaries messily (e.g. like feedback responses on the site vs within the add-on door hanger).

Hopefully this makes some sense, especially where I'm fuzzy and need some help understanding:

[![metrics flows](https://dl.dropboxusercontent.com/u/2798055/Test%20Pilot%20metrics%20flows%201.png)](https://docs.google.com/a/mozilla.com/drawings/d/1McTKdbMog0OQ9Mg29DCPRoGL43NODOs2ZqS1bAkvhQ0/edit?usp=sharing)

**Comment by ckprice** [comment]
@rjweiss created [Test Pilot KPI Validity Check.ipynb](https://gist.github.com/rjweiss/fb067a7261b3c15bd7d4132d2780ff6e) for us with the following note

> we are successfully pulling down test pilot pings and i can compute DAU and MAU using the standards library for computing DAU and MAU courtesy of our measurements team

She's taken the action item of getting this into a pretty re:dash view (thanks!).

I'm going to move this on to the next milestone.

Relevant bugs
- [Bug 1264049](https://bugzilla.mozilla.org/show_bug.cgi?id=1264049) - Make Test Pilot data available in Re:dash
- [Bug 1255184](https://bugzilla.mozilla.org/show_bug.cgi?id=1255184) - Start consuming Test Pilot logs

**Comment by clouserw** [comment]
Soooo, I think this is completed. :ear_of_rice: 

We have a dashboard at https://sql.telemetry.mozilla.org/dashboard/txp-engagement-ratio which we'll expand as we learn how to use our tools and refine what we actually want to see.

https://github.com/mozilla/testpilot/blob/master/docs/README-METRICS.md remains the document of record for all things stats related for Test Pilot.  Each experiment in the program has a similar metrics document, and we'll continue that requirement in the future.

Big thanks to everyone who came along for this ride -- we learned a lot! :)
