### ISSUE TITLE
[Enhancement] The button that informs the user that experiment was manually disabled should redirect to about:addons page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2344]
[Notes]:
- Since the current implementation uses a button shaped message that does nothing, I was thinking that we could use it to ease the user access to re-enable the experiment.

[Affected versions]:
- Firefox 52.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Test Pilot installed and at least one active experiment enabled.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click on the enabled experiment card.
3. In a new tab, navigate to "about:addons" page and select the "Extensions" tab.
4. Look after the enabled experiment and choose to disable it.
5. Return to the experiment details page.
6. Hover and click on the "<experiment_name> disabled in Add-ons Manager" button.

[Expected result]:
- The button changes color when hovered and clicking it redirects you to "about:addons" extensions page.

[Actual result]:
- The button changes color when hovered, but nothing happens when clicked.

[Notes]:
- Here is a screen recording of the scenario: https://goo.gl/kDjVXm.

**Comment by fzzzy** [comment]
There is no more button in master. Instead, an experiment that was disabled in the add-on manager just shows up as disabled, with the normal ui to enable it, which correctly enables it.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy Are you sure ? I'm still seeing this on dev server. Or you are referring to other master ? If that's the case, it means that the mozAddonManager is also not on dev server yet ? 

That would be really bad since it would mean that Cosmin ran yesterday the Full Functional suite to verify its behavior totally in vain...  

![disabled from add-ons manager](https://cloud.githubusercontent.com/assets/17258026/24695008/ce162584-19ec-11e7-843e-41bca211312c.png)
