### ISSUE TITLE
Test Pilot page for installed add-on constantly switches between installed and not installed states, if it's moved to a new window

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2350]
**[Affected versions]:**
- Firefox 52.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.  
- Test Pilot add-on was previously installed on the profile. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Open a second tab (can be empty).
3. Right click on the Test Pilot tab and choose to move it to a new window.
4. Observe the page behavior on the new window.

**[Expected result]:**
The Test Pilot page loads without issues in the new window. 

**[Actual result]:**
The Test Pilot page continuously switches between the one with add-on installed and the one without.

**[Notes]:**
- The same behavior occurs even if you navigate between experiments details pages.
- The page returns to normal state if you refresh the page.
- Here is a screen recording of the issue: https://goo.gl/t3aoH2.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas I was able to repro this on 52.01 (release)

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy @wresuolc If it's possible, I think we should fix this before Tuesday launch. This is quite easy to encounter by real users and since Containers experiment is so well received, this is even easier. The "Move tabs to a new window" option from the experiment is causing the same effect.

**Comment by SoftVision-PaulOiegas** [comment]
The issue no longer occurs when Test Pilot tab is moved to a new window. 
However, it seems that after this fix, something similar with #2352 occurs even without e10s-multi enabled. I've provided more details in the release Tag issue (#2348).
