### ISSUE TITLE
TxP add-ons appear as not installed when moving the Test Pilot web page tab to a new window, while having e10s-multi enabled

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2352]
**[Affected versions]:**
- Firefox release v52.0.1
- Firefox Beta v53.0b5
- Dev edition - 54.0a2
- Nightly 55.0a1

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string pref was manually added with "stage" value on a new clean profile in "about:config" page.  
- The "dom.ipc.processCount" pref was updated in "about:config" page to "4" (only if using Release, Beta or Dev edition).
- Test Pilot add-on was previously installed on the profile. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Navigate to an experiment and choose to enable it.
3. Open a second tab (can be empty).
3. Right click on the Test Pilot tab and choose to move it to a new window.
4. Observe the experiment state.
5. Refresh the page and observe again the experiment state.

**[Expected result]:**
The experiment remains enabled in the new window no matter what actions are performed.

**[Actual result]:**
4. The experiment is displayed as enabled in the new window.
5. The experiment is wrongly displayed as disabled after page refresh.

**[Notes]:**
- Also, if you try to uninstall Test Pilot this won't work. After the uninstall is performed and you click on "Home" button, you are redirected to the Test Pilot page for users with installed add-on.
- It seems that the entire tab from the new window is broken. Tried to navigate to another URL, outside of the Test Pilot website and then navigate again to TxP website and it was still broken.
- The issue is bypassed only if you open a new tab in the window.
- Here is a screen recording of the issue: https://goo.gl/iQdsZa.

**Comment by fzzzy** [comment]
This seems fixed on master. Tested against https://testpilot.dev.mozaws.net/ and all steps to reproduce show the correct experiment state, with dom.ipc.processCount set to 4.
