### ISSUE TITLE
The "Installing..." animation briefly changes its color after each action performed on the installation flow

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2362]
[Affected versions]:
- Firefox 52.0.2 and above

[Affected Platforms]:
- All Windows
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://testpilot.dev.mozaws.net" page.
2. Click the "Install the Test Pilot Add-on" button.
3. While observing the "Installing..." animation color, go trough the install process.

[Expected result]:
- The "Installing" animation color remains unchanged (darker green) throughout the entire installation process. 

Actual result]:
- The "Installing..." animation briefly changes its color to a brighter green after each action performed on the installation flow. 

[Notes]:
- The same behavior can be observed if you click outside of the animation somewhere on the page. But after this, the color persists to the brighter green for the entire process.
- This issue does not occurs on Mac OS. There the animation is in the brighter green color and darkens if you hover it.
- Here is a screen recording of the issue: https://goo.gl/io7qc0.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy This was fixed on supported Firefox versions, but sadly, I have encountered it on outdated Firefox versions for the "Upgrade" button. And also on Chrome browser for the Download button. 
But to be honest, I'm not sure if we should reopen or log a separate issue for it. It's quite unnoticeable for the "untrained eye". 😄

**Comment by fzzzy** [comment]
@SoftVision-CosminMuntean Since it is on a different button, I think it is worth opening a new issue. Although it is minor, it is also easy to fix, so we might as well fix it.
