### ISSUE TITLE
The enabled experiments are not removed at Test Pilot uninstall

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2366]
[Affected versions]:
- Firefox 52.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- The "extensions.webapi.testing" boolean pref was manually added with "true" value on the crated profile.
- Test Pilot add-on was previously installed on the profile and at least one of the active experiments was enabled.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Settings" button and choose to uninstall Test Pilot.
3. Observe the enabled experiments cards from Test Pilot home page.

[Expected result]:
- The experiments are uninstalled together with Test Pilot and are no longer displayed as enabled on Homepage.

[Actual result]:
- The experiments are not uninstalled and are displayed as "Enabled" on Test Pilot homepage and experiments page.

[Notes]:
- The experiments are not uninstalled and are still available in "about:addons" page.
- The experiments are not removed even after the browser is restarted.
- The issue is also reproducible if Test Pilot add-on is removed from "about:addons".
- Here is a screen shot with browser console errors: https://goo.gl/Rwfu2j
- Here is a screen recording of the issue: https://goo.gl/PhAc9g

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy Noticed while performing manual remove tests from "about:addons" page that this issue only occurs on first attempt. If you "Undo" the Test Pilot add-on removal, and you choose to remove it the second time, all the installed experiments are also removed.

Same behavior occurs even if you reinstall and uninstall from the website.

**Comment by fzzzy** [comment]
This one is very strange. The code looks correct.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy Found out another piece of info that might help you. It seems that any experiment you install after Test Pilot add-on is installed, won't be uninstalled.

I've Installed Test Pilot together with an experiment from its page and at uninstall, I remained with the experiment. Until here, same as last night. 
But when I've installed again Test Pilot together with a second experiment (TxP + exp 1 + exp 2 in about:addons), and chose to uninstall Test Pilot the second time. I was left with only the second enabled experiment, while the first one and Test Pilot were removed.

I assume this is happening since the first experiment was already installed when I've reinstalled Test Pilot.

Hope it helps...

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas Useful info! Thanks!

**Comment by fzzzy** [comment]
Time to raise the priority on this one.

**Comment by johngruen** [comment]
@fzzzy think this is something you could pick up next week. seems good to have before we launch the next experiments

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy just tested on Production and it still occurs on production. If I remember well, this was working better last time. So the severity increased again for it.

**Comment by lmorchard** [comment]
FWIW, I seem to remember we made a decision in a status meeting to stop doing this in the Test Pilot add-on. So... the new SDK-less 2.0+ add-on does *not* remove experiments when it's uninstalled.

If that's a mistake, and we *do* want it to do that, we'll need to re-implement that stuff from the old add-on.

**Comment by fzzzy** [comment]
We've waffled on this a lot. I think we just need to close this now. If it causes big problems, we can decide to reimplement this feature in the future.
