### ISSUE TITLE
Wrong button is displayed on the experiment details page, if the add-on is manually removed from "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2367]
[Affected versions]:
- Firefox 52.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- The "extensions.webapi.testing" boolean pref was manually added with "true" value in "about:config" page.
- Test Pilot add-on was previously installed on the profile and one of the active experiments was enabled.
- Have at least one experiment enabled.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "about:addons".
2. Choose to remove an enabled experiment from Test Pilot.
3. Click the Test Pilot icon from browser toolbar.
4. Click the removed experiment card.
5. Observe the experiment details page.

[Expected result]:
- The "Enable [experiment_name]" button is correctly displayed.

[Actual result]:
- The "[experiment_name disabled in Add-ons Manager]" button is wrongly displayed.

[Notes]:
- If the "about:addons" and Test Pilot pages are both refreshed the "Enable [experiment_name]" button is correctly displayed on the experiment details page. Also, the issue disappears if the browser is restarted.
- Here is a screen recording of the issue:
![removed experiment](https://cloud.githubusercontent.com/assets/19226534/24757976/8cc74b96-1ae9-11e7-9b1a-15a8f8ec2d24.gif)

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy When we tackle this, we should also auto update the experiments details page status when we manually remove an experiment from "about:addons" page. Same thing when we choose to "Undo" the remove option from the same page.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and it seems that is still reproducible on stage and dev server.

**Comment by fzzzy** [comment]
I think the issue here is that as long as the "undo" ui is still visible in the add-on manager, the add-on won't actually appear to be uninstalled. Once you close the add-on manager, it appears to be fully uninstalled.

**Comment by ghost** [comment]
We don't think this is a bug we're going to work on.  Thanks.
