### ISSUE TITLE
Footer URLs don't appear to be clickable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#237]
Tried in FF and Chrome.
### Steps to reproduce
1. Go to http://idea-town-dev.elasticbeanstalk.com/
2. Try and click on the footer links (Mozilla, Legal, Privacy, Cookies, Contribute)
### Actual results:

Not clickable.
### Expected results:

Clickable. The code looks like links. Not sure why they're foiling me yet though.

**Comment by pdehaan** [comment]
Actually... Looking through the Developer Tools at the div#main-footer element, it looks like a basic `z-index: -1;` situation.
If I disable that rule (or set it to `1`) then things seem to work as expected.

Looks like it was added to [./idea_town/frontend/static-src/styles/modules/_footer.scss:7](https://github.com/mozilla/idea-town/blob/b1a7dce51e21b8a92bd6b44ad8fca9b952a37709/idea_town/frontend/static-src/styles/modules/_footer.scss#L7) in https://github.com/mozilla/idea-town/commit/e4b35911c6976fb8a9a06a3a3bc71fc726b6cca3#diff-d3348d1d6cda42b893cf6996569cfcfaR7

**Comment by lmorchard** [comment]
https://github.com/mozilla/idea-town/commit/62e1a8e37ffbb152be7320fc164ed14fd28c2517
