### ISSUE TITLE
Newsletter current email wrongly contains a graduated experiment (Tracking Protection)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2370]
[Affected versions]:
- Firefox 52.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to "http://testpilot.dev.mozaws.net" page.
2. Scroll down until the Newsletter sign up section is reached.
3. Click inside the text box and enter a valid email address (not already used).
4. Check the privacy text box and click the "Sign Up Now" button.
5. Open the email client and observe the content of the received email for the Newsletter sign up.

[Expected result]:
- The Newsletter email contains 3 of the latest / 3 of the active experiments along with other information related to Test Pilot. 

[Actual result]:
- The current Newsletter email contains 2 active experiments and one that was already graduated (Tracking Protection).

![newsletter current](https://cloud.githubusercontent.com/assets/17258026/24767039/475fda4c-1b06-11e7-83c8-ec42ae07c921.png)

**Comment by ghost** [comment]
jess o is looking into this

**Comment by ghost** [comment]
This is fixed.  New newsletter @ https://litmus.com/pub/139ee65

**Comment by SoftVision-PaulOiegas** [comment]
Heh, I thought for a second that #2386 is a dupe of this, but then I've seen that this one it's closed as fixed. I was thinking that you are gonna use this one for Newsletter updates also.
Anyway, the graduated experiment was correctly removed.
