### ISSUE TITLE
[release] 2017-04-07 is on Stage

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2374]
Hi guys,

Here is the testing report for the Stage server:
### **New Issues** (not yet logged)
1. #2377 - Test Pilot dev add-on installation prevented by Nightly builds starting from 7th of April (Major severity but not for release) 
   -Test Pilot dev add-on cannot be installed on latest Nightly 55.0a1.

2. #2378 - Experiment details page displays the complete install button (Test Pilot + experiment) if you have only Test Pilot disabled from add-ons manager (Normal severity)
   -If Test Pilot and an experiment are enabled, when you manually disable Test Pilot, the experiment page will reflect that experiment is enabled. But you have the "Install test Pilot & Enable <experiment_name>" button.

3. Never mind, this is a Firefox issue related to the enable of e10s-multi. The issue is already logged in [#1350324](https://bugzilla.mozilla.org/show_bug.cgi?id=1350324)
   -Moving a tab with Test Pilot web page (add-on not installed) in a new window, will display infinite loading animation on the tab favicon. (Minor severity)

4. #2379 - The add-ons conflict notification is displayed only after page refresh even with the use of mozAddonManager (Normal severity)
-"mozAddonManager" does not recognizes conflicting add-ons after install, unless you refresh the experiment page. 

### **Reopened issues**
1. #2367 - Wrong button is displayed on the experiment details page, if the add-on is manually removed from "about:addons" page
-still reproducible even with "extensions.webapi.testing" boolean pref set to "true"

### **Known issues**
1. #2366 - The enabled experiments are not removed at Test Pilot uninstall

### **Enhancements**
1. #2382 - [Enhancement] Graduated experiments should no longer have localization restrictions, so anyone could see the reports
- [Proposal] Should we display all past experiments after graduation indifferent of content language ?

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy I couldn't have stayed more yesterday so I have logged today 3 of the 4 found issues and updated the report above. 
Any news on #2366 ? Other than that, I think we are good to GO, unless you guys consider some of the logged / reopened issues as blockers.

**Comment by fzzzy** [comment]
Thanks very much! No news on #2366, but I will be looking into that and #2378 first thing in the upcoming sprint.

**Comment by SoftVision-PaulOiegas** [comment]
The production deployment was performed yesterday. Testing results were good, 95% pass rate on the Acceptance suite and with no new issues found.
