### ISSUE TITLE
Test Pilot dev add-on installation prevented by Nightly builds starting from 7th of April

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2377]
**[Notes]:**
- After digging trough older builds, this seems to be a Firefox regression. Using mozzregression tool, I found out that Bugzilla bug [#1353975](https://bugzilla.mozilla.org/show_bug.cgi?id=1353975) caused this. 
- I'm not able to see the issue because I'm not authorized, but from the pushlog (https://goo.gl/sbgsCG) it seems to be related to "Fix nullPrincipal edge case".
- This issue only occurs on Nightly for now and it started with the build from 7th of April.
- The strange part is that if you first install the Stage version, then you uninstall it and try again on the Dev server, it correctly installs.

**[Affected versions]:**
- Nightly 55.0a1 (2017-04-07 and above)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "extensions.webapi.testing" boolean type pref was manually added on a new profile with "true" value set.
- The "testpilot.env" string type pref was manually added on the same profile with "dev" value set.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to "http://testpilot.dev.mozaws.net" page.
3. Click on "Install the Test Pilot Add-on" green button.
4. Observe the browser behavior. 

**[Expected result]:**
- You are prompted to "Allow" or "Deny" the Test Pilot add-on installation.

**[Actual result]:**
- You are prompted that "Nightly prevented this site from asking you to install software on your computer." and you only have an "OK!" button.

**[Additional notes]:**
- Here is the console output for the issue: https://goo.gl/Rfv32s.
- Here is the console output if you install the stage version first and after the dev one: https://goo.gl/IuaeWj.
- Here is the screen recording of the issue: https://goo.gl/QhxspZ.

![nightly dev install fail prompt](https://cloud.githubusercontent.com/assets/17258026/24908169/bd847b96-1ec7-11e7-85a5-3b05fd82fd02.png)

**Comment by jaredhirsch** [comment]
@wresuolc Mossop CC'd you on the bugzilla bug, he said he fixed this yesterday. So we could have SV try to repro again on latest Nightly next time they are in office.

**Comment by SoftVision-PaulOiegas** [comment]
@6a68 @wresuolc Well, indeed this was fixed on Nightly, but now I encounter the same issue on Dev Edition. 
Based on this behavior I'm afraid that this issue could also appear on Beta and Release if Mossop's fix won't be uplifted sooner than the normal trains. 

I don't think we want to have a full Firefox 54.x version where you cannot install Test Pilot. That would be a "Blocker".😄

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas There is another public bug that will be tracking the uplift of the fix. I am not an expert at reading bugzilla, but I think it will be uplifted.

https://bugzilla.mozilla.org/show_bug.cgi?id=1356292#c28

**Comment by SoftVision-PaulOiegas** [comment]
I think it may already be uplifted, but I still want to keep an eye on this in the future. I'll close this when I'm sure.

**Comment by fzzzy** [comment]
I think this is fixed now?
