### ISSUE TITLE
Experiment details page displays the complete install button (Test Pilot + experiment) if you have only Test Pilot disabled from add-ons manager

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2378]
**[Notes]:**
- I would personally go with the first expected behavior in this case if we want in the future to re-enable Test Pilot in add-ons manager when the "Install the Test Pilot Add-on" button is clicked. This to solve the problem reported by the users that cannot install Test Pilot because they manually disabled it from add-ons manager.

**[Affected versions]:**
- Firefox v52.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "extensions.webapi.testing" boolean type pref was manually added on a new profile with "true" value set.
- The "testpilot.env" string type pref was manually added on the same profile with "stage" value set.
- Test Pilot add-on from Stage server was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to http://testpilot.stage.mozaws.net" page.
2. Click on one of the active experiments cards and choose to "Enable" it.
3. Open a new tab and navigate to "about:addons" page.
4. Select "Extensions" tab and choose to "Disable" the Test Pilot add-on.
5. Select the Test Pilot page tab and observe the content behavior.

**[Expected result]:**
- Since experiment is already installed and displayed as enabled, the page displays only the "Install the Test Pilot Add-on" green button.

 Or

- The experiment is no longer displayed as enabled, so the page displays the "Install test Pilot & Enable <experiment_name>" complete button.

**[Actual result]:**
- Experiment is displayed as enabled but the "Install test Pilot & Enable <experiment_name>" complete button is also displayed.

![experiments disabled txp](https://cloud.githubusercontent.com/assets/17258026/24909215/aa87e0ba-1ecb-11e7-8d7a-1e43301d7093.png)

**Comment by fzzzy** [comment]
Yes, there are some bad behaviors when the test pilot add-on is disabled in the add-on manager right now. I'll make this a priority for next sprint.

**Comment by chuckharmston** [comment]
The current behavior: if the Test Pilot extension is installed and disabled, it behaves as if it was installed and enabled. Let's look into this more.

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates this was partially fixed by the fix you did on #3374. Now the page correctly shows the right button when Test Pilot add-on is uninstalled. But the "disabled" case still reproduces and hits the scenario from bug #2866.
