### ISSUE TITLE
The add-ons conflict notification is displayed only after page refresh even with the use of mozAddonManager

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2379]
**[Notes]:**
- Since mozAddonManager is detecting manual disable / enable actions and auto updates the Test Pilot pages. Maybe this can be done too for conflicting add-ons ?

**[Affected versions]:**
- Firefox v52.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "extensions.webapi.testing" boolean type pref was manually added on a new profile with "true" value set.
- The "testpilot.env" string type pref was manually added on the same profile with "stage" value set.
- Test Pilot add-on from Stage server was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to http://testpilot.stage.mozaws.net" page.
2. Click on Tab Center experiment card and observe the top part of the experiment area.
3. Open a new tab and navigate to "about:addons" page at "Extensions" section.
4. In the top right search field enter "Tab Groups" string and hit "Enter" key.
5. Choose to "Install" it and after switch back to the Tab Center tab.
6. Observe again the top part of the experiment area. 

**[Expected result]:**
- Step 2: The Tab Center description is displayed in top part.
- Step 6: Page is automatically updated displaying an incompatibility notification between "Tab Groups" and Tab Center experiment.

**[Actual result]:**
- Step 2: The Tab Center description is displayed in top part.
- Step 6: The same Tab Center description is displayed even after Tab Groups add-on was installed.

**[Additional notes]:**
- The notification is only displayed after the experiment page is refreshed.
- Here is a screen recording of the issue: https://goo.gl/cOjJvZ.

**Comment by chuckharmston** [comment]
This is pretty edge-casey and probably can't be a priority. Going to close it.
