### ISSUE TITLE
Tabzilla logo isn't clickable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#238]
Similar to #237

Currently, it looks like the actual "Mozilla" logo in the Tabzilla header isn't clickable. The highlighted area _below_ the text is clickable, as well as the tab area on the left and right of the logo is clickable, just not the big text hit area itself.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11107424/889fbfd4-8892-11e5-84ac-1791e621487c.png)

Also similar to #237's workaround, this seems like a `z-index` issue.
Specifically, [./idea_town/frontend/static-src/styles/_base.scss:47-50](https://github.com/mozilla/idea-town/blob/b1a7dce51e21b8a92bd6b44ad8fca9b952a37709/idea_town/frontend/static-src/styles/_base.scss#L47-L50), which says:

``` css
// override the 
#tabzilla a {
  z-index: inherit;
}
```

Turning off that rule via dev tools seems to make the text logo clickable as well.

Looks like this was added/changed in https://github.com/mozilla/idea-town/commit/e4b35911c6976fb8a9a06a3a3bc71fc726b6cca3#diff-73af7ba0cddb1021940ebfbb07344e77R49

**Comment by lmorchard** [comment]
https://github.com/mozilla/idea-town/commit/62e1a8e37ffbb152be7320fc164ed14fd28c2517
