### ISSUE TITLE
URL on site - testpilot.firefox.com/experiments - pinwheels forever

### ISSUE THREAD

**Issue by mhoye** [mozilla/testpilot#2383]
https://testpilot.firefox.com/experiments  

... is one of the first links Google offers up on a search for "firefox testpilot". On my machine it pinwheels forever with an animated loading thing, and never takes me to a usable page.

I'm using release Firefox on Windows 10.

**Comment by SoftVision-PaulOiegas** [comment]
That's not good... We are no longer using that page, now the redirect after install is made on the same https://testpilot.firefox.com page. 
Friday we have a triage meeting and will see what the team thinks on this matter. Thanks for reporting it @mhoye !

**Comment by fzzzy** [comment]
I have a fix for this now. Coming soon.
