### ISSUE TITLE
Enabled experiment "Give Feedback" button wrongly opens the form in the same tab

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2385]
**[Notes]:**
- There are 3 feedback forms in the website, if I remember well, from which 2 are opened in a new tab (after TxP uninstall and after experiment disable). Considering this, I think we should also do the same for the enabled experiment feedback.

**[Affected versions]:**
- Firefox v52.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- On a new Firefox profile, the "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Click on one of the active experiments cards and choose to "Enable <experiment_name>".
3. Dismiss the tour pop up.
4. Click on the "Give Feedback" button from top part of the page that appeared after enable.
5. Observe the page behavior. 

**[Expected result]:**
- The feedback form is loaded in a separate new tab.

**[Actual result]:**
- The feedback form is loaded in the same tab.

**Comment by fzzzy** [comment]
This didn't actually turn out to be a good first bug since I had to figure out that sendToGA was setting window.location, causing both the original page and the page opened in a new tab to show the survey, but I figured it out.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on dev server and is no longer reproducible. Marking as verified.
