### ISSUE TITLE
Update / Download Firefox button worngly remains in hovered state

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2387]
**[Notes]:**
- Logged based on @fzzzy 's comment https://github.com/mozilla/testpilot/issues/2362#issuecomment-293592894

**[Affected versions]:**
- Firefox v52.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Chrome browser or Firefox 48.0.2 or lower is installed on the testing machine.

**[Steps to reproduce]:**
1. Launch the Firefox old version or latest Chrome browser.
2. Navigate to https://testpilot.firefox.com page.
3. Click and hold the Update / Download button.
4. While holding the click, move out of the button and release it.
5. Observe the button color and after click outside of it. 

**[Expected result]:**
- Nothing happens, button hover state is lost when mouse is moved outside of it.

**[Actual result]:**
- The button wrongly remains in hovered state when mouse is moved out of it and it regains the normal color after clicking outside.

**[Additional Notes]:**
- This also occurs on Firefox if you click the "Upgrade" button and you return to the Test Pilot page afterwards.
- Here is a screen recording of the issue https://goo.gl/n5Jnfm.

**Comment by fzzzy** [comment]
@ScottDowne Is this similar to the other bugs you fixed? Think it is easy?

**Comment by ScottDowne** [comment]
Probably yeah.

**Comment by ScottDowne** [comment]
I don't mind taking a look.

**Comment by ScottDowne** [comment]
It's the button's active state, which blocks the button's hover state. Def similar to the other bugs.

**Comment by ScottDowne** [comment]
Correction, it's the button's focus state, not active like I initially though.

Because both hover and focus use the same styling, while it's focused, you'll never see the visible difference while hovering..

https://github.com/mozilla/testpilot/blob/master/frontend/src/styles/modules/_buttons.scss#L56-L57

We just need to make the hover and focus styles different.

**Comment by ScottDowne** [comment]
Fixed in https://github.com/mozilla/testpilot/pull/2390

My solution is to apply a slightly darker green on hover if it's also focused.

**Comment by SoftVision-PaulOiegas** [comment]
Now we have 3 color states instead of two. Light and dark green for the previous states and a slight darker green for hover state (in between the other 2). This kind of fixes our issue, but I'm not sure if we haven't complicated the situation.

@ScottDowne @fzzzy  I personally don't think that we should invest more time in this since it's a very minor issue. So I am considering the fix to be OK. The only problem is that this only applies to Chrome. On an older Firefox build (48.0.2) the issue is still present on the "Update" button...

**Comment by fzzzy** [comment]
Maybe John will want to come in and do a redesign of all of these mechanics at some point.

**Comment by ScottDowne** [comment]
I also don't think investing more time is worth while at this point. Initially I was going to consider removing the "focus" state styling completely, but it's helpful for accessibility.

I think there always was 3 colour states. Regular, hover/focus and active. Now if you focus and hover, it just reuses the active colour.

The other option was a focus state that wasn't colour based for accessibility. Probably would be ideal, but didn't feel worth it.

The fix I ended up with felt like a nice middle between works, didn't change things too much, and wasn't a lot of work.
