### ISSUE TITLE
Add a __version__ route

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#239]
Ref: https://github.com/mozilla/fxa-content-server/issues/2864

There was recently a document circulating about a new version route proposal standard:
https://docs.google.com/document/d/1rGVyiLYvZyKE2oHcSVx-vBmQRKhs1kLLgn7xeCs6qKs/edit

**TL;DR:** Basically we'll need to:
1. Add a `source`  attribute which is the URL for the source repository.
2. Rename the route from `/ver.json` to `/__version__` (or add clever aliases).

---
#### Required Objects

``` json
{
    "source": "URL for the source repository",
    "version": "human readable version string",
    "commit": "commit hash"
}
```
#### Optional Objects

Any additional fields as required by the application in JSON format.
#### Definition

| FIELD | DESCRIPTION | REQUIRED | TYPE |
| --- | --- | :-: | --- |
| `source` | Source repository for the code base. | yes | String |
| `version` | The human readable version of the code base that has been deployed. | yes | String |
| `commit` | The commit hash pointing to deployed code in source control. | yes | String |
#### Rationale
- To keep this generic enough to work for all projects and still allow flexibility for what individual devs/project want, we think the 3 required fields are sufficient for the original purpose of this (a consistent location to determine what version of a project is deployed)
- Additional fields can be provided as needed, see some examples in the discussion below 
- Configuration (e.g. puppet) information was purposely excluded because the `__version__` route will be stored with the application source.

---

You can see an example of this at https://accounts.firefox.com/__version__ (which includes a couple optional fields for `l10n` and `tosPp` which are the Git SHAs for external, related repos:

``` js
{
  "commit": "e982d202fe3021a28f78a3b2b58f6db68048e2e7",
  "version": "0.49.3",
  "l10n": "1828d37f34",
  "tosPp": "b86f95ea39",
  "source": "https://github.com/mozilla/fxa-content-server.git"
}
```

But adding this route would be useful for QA because we can easily tell exactly what code is deployed to a server at any given time, plus OPs uses it for monitoring or something OPs-ey.

**Comment by meandavejustice** [comment]
fixed in #427
