### ISSUE TITLE
mozAddonManagerInstall can be simplified a lot

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2391]
return mam.createInstall({ url }).then(install => install.install()) should be sufficient.

**Comment by lmorchard** [comment]
Might do with some more details in this issue - is `install.install()` sufficient because it returns a promise that resolves on install ended and rejects on download / install failed?

**Comment by fzzzy** [comment]
Yes. There was a long discussion about it on irc around the time I filed the bug... I could dig out the logs if needed.

**Comment by lmorchard** [comment]
> There was a long discussion about it on irc around the time I filed the bug... I could dig out the logs if needed.

Yeah, that, or I guess self-assign it because no one else has the context behind this issue :)

**Comment by fzzzy** [comment]
@lmorchard Your previous comment was exactly correct -- it returns a promise that does the right thing.

**Comment by fzzzy** [comment]
This was fixed by https://github.com/mozilla/testpilot/pull/2984
