### ISSUE TITLE
Don't show TxP tour for experiments with built-in tours

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#2393]
TabCenter has a built-in tour for when a user first installs it. Test Pilot also shows a tour saying pretty much the same thing. Both tours are on screen at the same time.

Let's not show the TxP site tour for experiments that have built-in tours. We can leave the link to the tour in the sidebar for users who are curious before installing.

I'm not sure what other experiments currently have tours in them. @johngruen?

**Comment by johngruen** [comment]
@sevaan containers does, but it complements the test pilot tour, and I'd rather keep both. 

For this issue, we should just add a YAML flag to optionally disable experiment tours, and set it to `true` for Tab Center.

**Comment by lmorchard** [comment]
One catch I'd throw in here is that we have a link to show the tour, and folks who haven't installed the experiment can use that to preview more about what the experiment does.

That said, I don't know if this link is all that well used or promoted.

**Comment by SoftVision-PaulOiegas** [comment]
@lmorchard This was the requested by Sevan in #1483. And just as a reminder, with this decision we got also a tiny bug #1965.

**Comment by chuckharmston** [comment]
Tab Center is no longer in Test Pilot. We can reconsider if a new experiment requires it. Closing!
