### ISSUE TITLE
Update our design to improve experience without the add-on

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#2394]
When we first launched, we wanted to get people to install Test Pilot so we added some big targets on the page.  In our current world, we install the Test Pilot add-on automatically when people click the install button for any add-on so it's not something we really need to worry about.

The substantial differences between the installed/not-installed designs cause noticeable delay or element shifting when loading the page because we can start rendering the page before we know if the browser has the test pilot add-on installed.

We'd like to revisit the designs and make them either the same, or with minor differences we can fill in without a jarring experience after the page loads.

/cc @johngruen

**Comment by SoftVision-PaulOiegas** [comment]
Please let us know if possible, when you guys have something on this. If there will be changes, we will need to update our tests too, preferably before we implement and merge anything.

Thanks!

**Comment by fzzzy** [comment]
Need the UX for this, plz!

**Comment by fzzzy** [comment]
I took a quick stab at this.

Without addon:

<img width="1397" alt="no-addon" src="https://cloud.githubusercontent.com/assets/46048/25672170/81b265c0-3000-11e7-9d22-05b23ef1337a.png">

With addon:

<img width="1396" alt="yes-addon" src="https://cloud.githubusercontent.com/assets/46048/25672192/8d2fa61a-3000-11e7-813f-71e7d90f0a88.png">

**Comment by johngruen** [comment]
Since we broke this page out into distinct routes, it's worth revisiting this issue.
