### ISSUE TITLE
Document Design and use cases feedback buttons directly in experiment UI

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2396]

**Comment by johngruen** [comment]
Adding the following for discussion only; final spec still WIP
![feedback_buttons_measurement](https://cloud.githubusercontent.com/assets/3323249/26318831/c7ace3ea-3f1c-11e7-8667-ad116c64b9dd.png)

**Comment by ChenMorpheus** [comment]
Updated for regular version of feedback button and move the measurement of experiment cards to #2462. Please find the attached [final measurement](https://www.dropbox.com/s/njd010300ge0cqv/Feedback%20buttons%20measurement.png?dl=0), thanks.

![feedback buttons measurement](https://cloud.githubusercontent.com/assets/18019946/26351153/e9b18ad2-3fe8-11e7-9856-6ece97797a2c.png)

**Comment by ChenMorpheus** [comment]
Please find the link below for the feedback icon.
https://www.dropbox.com/sh/un2ojq9s3lc9n85/AAAR-hrkRC7tSGg6ZmiL_oWsa?dl=0
