### ISSUE TITLE
Specific experiment options from about:addons are not displayed, after re-enabling some of the active Test Pilot experiments

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/testpilot#2400]
[Affected versions]:
- Firefox 53.0 and above

[Affected Platforms]:
- All Windows
- All Linux
- All MAC OS

[Prerequisites]:
- Test Pilot add-on was previously installed on the profile.
- Have one of the following experiments enabled: Activity Stream, Min Vid or Tab Center.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "about:addons" page.
2. Click on "Extensions" tab from the left side of the page.
4. Double click (or click "More") on one of the enabled Test Pilot experiments.
5. Click on "Disable" button.
6. Click on "Enable" button and observe the experiment's specific options in the Description. 

[Expected result]:
- Experiment specific options are re-displayed along with the previously set preferences by the user.

[Actual result]:
- Specific options are not re-displayed at all.

[Notes]:
- The options are displayed again after reloading the webpage.
- This is reproducible with both Test Pilot and dev versions of experiments.
- Please see the screencast attached:

![options](https://cloud.githubusercontent.com/assets/26000308/25491883/fca274ae-2b79-11e7-882f-033e3be6aecf.gif)

**Comment by ghost** [comment]
This is weird.  Do we know why this happens?  If we know why and it doesn't break anything else, I'm comfortable closing it.

**Comment by lmorchard** [comment]
Does it happen for other add-ons besides Test Pilot experiments? I'd guess it's an artifact of the add-on manager not having a way to refresh the options available until the page is reloaded. I don't think there's much we can do about it on our end

**Comment by SoftVision-CarmenFat** [comment]
Hi @lmorchard,

I tested the same scenario using add-ons that are not part of the Test Pilot experiments.
After re-enabling the add-ons, the specific options were displayed again without having to reload the webpage.

The tested add-ons are the following:
- Adblock Plus 2.8.2
- Classic Toolbar Buttons 1.5.6
- cliget 1.2.3.1-signed.1-signed
- GlassMyFox 1.4.0
- VimFx 0.20.10

![adblock](https://cloud.githubusercontent.com/assets/26000308/25658855/a0e5b584-300d-11e7-96e0-2db3a7f26b8f.gif)

**Comment by chuckharmston** [comment]
I still don't think there's much we can do about it on our end. Closing.
