### ISSUE TITLE
Came back to my Mac and #testpilot #pageshot GONE!!!

### ISSUE THREAD

**Issue by PiratDOM** [mozilla/testpilot#2401]
Wow, I was pretty much completely dependant my past 48 hrs on PageShots, bookmarking all I use for research for work.... It is all gone... What has happened?

I wasn't signed off. I use quite few browsers for different purposes, but all my research was actually doing here in firefox.... OMG.... So much time... Well shoot... At least I would like to know what caused it... 
All other addons seem fine, but those 2 plus video downloaders are gone... And Social Fixer for FB has been acting funny so I got rid of it now...

Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Containers:           https://github.com/mozilla/testpilot-containers/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Pulse:                https://github.com/mozilla/pulse/issues/new
- Snooze Tabs:          https://github.com/bwinton/SnoozeTabs/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new

**Comment by PiratDOM** [comment]
Before I left my computer cpl hrs ago, I was uploading video on youtube and had to switch my google account to my second one, so I suppose it has something to do with that...

**Comment by PiratDOM** [comment]
![screen shot 2017-04-27 at 17 32 48](https://cloud.githubusercontent.com/assets/28035413/25493901/b2b1dc90-2b6f-11e7-8385-99e29a5ae605.png)


Not It guy so I am not trying to fix this... Could You please let me know how to pull the data back? Seems like it will be there...

**Comment by ianb** [comment]
Do you have a URL of a shot you previously made, and a new shot that you've made?  You should have old shot URLs in your browser history.

**Comment by ckprice** [comment]
Have you made any changes to your about:config settings lately?

Also, are you on Firefox Nightly, Aurora, Beta, or Release (if you don't know then you are probably on Release). And is this Mac, Windows or Linux?

**Comment by PiratDOM** [comment]
Firstly appreciate the speed of Your response to my SOS :D 

But I am an absolute Laic in coding, so I do not even know Ian where to look for it... I didnt really want to touch anything... I was making changes in Youtube of my google account name, so yeah that might be the problem... Well since I was naive to use the beta tool I wasnt making snapshot backups... My fault.

**Comment by PiratDOM** [comment]
Mac... 
![screen shot 2017-04-27 at 19 08 54](https://cloud.githubusercontent.com/assets/28035413/25497597/1131aa90-2b7d-11e7-9f72-0d2daeb6cc8d.png)
Yeah changed my name in youtube so i suppose thats what messed it up

**Comment by PiratDOM** [comment]
![screen shot 2017-04-27 at 19 10 44](https://cloud.githubusercontent.com/assets/28035413/25497670/4659633e-2b7d-11e7-8ae8-4b9f35ebc39f.png)

**Comment by DomBugi** [comment]
https://pageshot.net/bgfzCymS5Kn9dGiq/medium.com

**Comment by PiratDOM** [comment]
![screen shot 2017-04-27 at 19 13 12](https://cloud.githubusercontent.com/assets/28035413/25497857/c9230162-2b7d-11e7-97dc-0ddfeeefd750.png)

**Comment by PiratDOM** [comment]
![screen shot 2017-04-27 at 19 17 57](https://cloud.githubusercontent.com/assets/28035413/25498005/42efd812-2b7e-11e7-8250-b4755ac77990.png)

**Comment by ianb** [comment]
My question might be premature.  I'd recommend looking at **Tools > Add-ons** to see if the extensions are present but not activated.  You can also look in about:config, and there is a preference `extensions.jid1-NeEaf3sAHdKHPA@jetpack.deviceIdInfo` that contains your authentication information for Page Shot.  You may wish to save the value of that setting as a kind of backup.  After that you might want to try reinstalling Page Shot.

**Comment by PiratDOM** [comment]
They are active since I had to reinstall them ... The icons were gone when I came to the computer... Installed the test pilot from scraycj again...

**Comment by PiratDOM** [comment]
ARE You making any changes in my browser remotely? Cuz I deleted the facebook fixer addon and now I see its back on again...

**Comment by PiratDOM** [comment]
How do I actually debug in console... I think it jumped back to the old profile again but I cant open page shot it needs debug
![screen shot 2017-04-27 at 20 52 54](https://cloud.githubusercontent.com/assets/28035413/25501793/dbf2df84-2b8b-11e7-95ed-74fd62417be5.png)

And since I have You on, what is the shortcut for page shot pls ... when i wanna keyboard shortcut it

**Comment by PiratDOM** [comment]
![screen shot 2017-04-27 at 21 05 55](https://cloud.githubusercontent.com/assets/28035413/25502169/7caa8692-2b8d-11e7-9143-8ea42ebd464e.png)
![screen shot 2017-04-27 at 21 05 55](https://cloud.githubusercontent.com/assets/28035413/25502186/92e3880a-2b8d-11e7-9ed2-89fcb5dc5282.png)


I think It got back to old now and needs some debuggin... do I have to do it one by one

**Comment by PiratDOM** [comment]
![screen shot 2017-04-27 at 21 16 26](https://cloud.githubusercontent.com/assets/28035413/25502549/ef4a8eb2-2b8e-11e7-86ab-303833bace3b.png)

**Comment by PiratDOM** [comment]
it seems like it is much easier to just kill it and install all again right

**Comment by ckprice** [comment]
> it seems like it is much easier to just kill it and install all again right

Great! I'm going to close this issue then.

If you are facing a specific problem with Test Pilot or Page Shot please feel free to file a new issue (or reopen this if you still can't find your Shots). If you have general questions regarding specific add-ons, you can file an issue with the add-on developers (contact information can typically be found in https://addons.mozilla.org).

Thank you!
