### ISSUE TITLE
Add News Summary to /experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2418]
## How it works

-  The layout on `/experiments` is expanded to accommodate short summaries of recent news items
- 2-3 items are shown
- hovering on each item changes UI slightly (see hover state, below)
- clicking on news item takes user to expanded article in news feed

## Spec
Main UI: https://mozilla.invisionapp.com/share/U7BLDRERA
Hover State: https://mozilla.invisionapp.com/share/GYBLHAOKZ

**Comment by lmorchard** [comment]
Are these per-experiment summaries meant to be taken from the latest post? Or is each one a manually-authored piece of content separate from posts?

**Comment by youwenliang** [comment]
We can pull 2~3 latest post from the news feed page as the summary here.

### Updated Spec Link:
(including default state & hover state)
https://mozilla.invisionapp.com/share/9XBO0DC7F

All the news feed related measurements can be found here:
https://www.dropbox.com/sh/ludnt78ky7ttrwq/AACh3mXB8FsxMxbRpGs34Repa?dl=0

**Comment by meandavejustice** [comment]
I think there should additionally be a "view all updates" link either beside the "Latest Updates" header or beneath the 2 experiments

**Comment by meandavejustice** [comment]
We will be having updates with a link to a blog and without links to a blog, we should have some way to differentiate whether it is a blog link or not

**Comment by meandavejustice** [comment]
I see that there are additional labels on the experiment detail cards that read `update` with a mustard yellow background. Are we showing anything else on the experiment detail pages regarding the update?

**Comment by meandavejustice** [comment]
@youwenliang How do you recommend to checkout these measurements? I downloaded the folders and they do not open in a browser for me. What am I missing? I've eyeballed the measurements for now and pulled out colors with my image editing tool (gimp)

I will also need the chevron/arrow icon for the hover effect

**Comment by meandavejustice** [comment]
_Deleted the past comments and consolidating them into one for readability here:_

@youwenliang @johngruen 

1. We will be having updates with a link to a blog and without links to a blog, we should have some way to differentiate whether it is a blog link or not
2. I see that there are additional labels on the experiment detail cards that read update with a mustard yellow background. Are we showing anything else on the experiment detail pages regarding the update?
3. How do you recommend to checkout these measurements? I downloaded the folders and they do not open in a browser for me. What am I missing? I've eyeballed the measurements for now and pulled out colors with my image editing tool (gimp)
4. I will also need the chevron/arrow icon for the hover effect
5. ~~For the pretty formatted, written out dates, how will we handle localization?~~

**Comment by lmorchard** [comment]
> For the pretty formatted, written out dates, how will we handle localization?

We could probably [use Moment's i18n for this](https://momentjs.com/docs/#/i18n/) - I can't remember if we're using it elsewhere as an example.

There's also [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) that might be handy

**Comment by meandavejustice** [comment]
Thanks @lmorchard this looks like it could work well for us. Though I'm wondering if it makes sense to add such a big dependency (especially when loading all of these languages) for one date string. Would it make more sense in this case to use a more universal date format? cc/ @johngruen

**Comment by lmorchard** [comment]
> Though I'm wondering if it makes sense to add such a big dependency

You mean Moment? [It's already a dependency](https://github.com/mozilla/testpilot/blob/master/package.json#L27) - we're using it for date comparisons & such in the Redux store, but not sure we're using it for display yet

**Comment by meandavejustice** [comment]
@lmorchard Oh I somehow overlooked that in the package.json, thanks :)

**Comment by meandavejustice** [comment]
[In progress branch diff](https://github.com/mozilla/testpilot/compare/master...meandavejustice:2418-news-feed-summary-frontend) in case anyone wants to take a look (or start an early review).

Here is a screenshot, you will notice the text "chevron" in place of the chevron/arrow icon, but beyond that the styles should match up.

![2017-05-30--09-19-41-1920x1080_scrot](https://cloud.githubusercontent.com/assets/1844554/26608908/10c4e4b0-456c-11e7-97ed-558aa32f7a20.png)

**Comment by lmorchard** [comment]
Hmm, one thing that looks missing: We need UX input on how to display a news update that's not associated with an experiment. We had discussion about wanting that as a feature in the last meeting, but I don't think it's reflected in the mocks here. 

(Or, if we don't want that, and only want pre-experiment news items, I can remove the bits I'm implementing for that on the backend)

/cc @johngruen
