### ISSUE TITLE
Add News alerts for major experiment changes

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2419]
## How it works
- when we launch a *major* change or update to a feature (such as queues in Min Vid, or graduating page shot), the toolbar icon is badged (note, this feature goes beyond the `/experiments` news summary and is reserved for major updates.
- when the user clicks on the badge they are taken `/experiments` and a news modal is popped.
- if there are multiple new major features, the modal is a carousel
- if the updates have to do with specific experiments that the user is (a) not in and (b) eligible for (no conflicts installed), the option to enable said experiment is presented on the modal.

## Spec
Icon Badge: https://mozilla.invisionapp.com/share/GPBLHHLA6
Modal: https://mozilla.invisionapp.com/share/9YBLHHZKD

## Events
coming soon...

**Comment by lmorchard** [comment]
So, we show a "new" badge on the add-on icon right now when there are new experiments.

Does this co-exist with / replace / override with that existing badge somehow?

**Comment by lmorchard** [comment]
More questions:

* How do we identify what's a "new major feature" - e.g. are all posts shown in #2420 major features to be paginated in a carousel? Or, is "major feature" a news feed post type / tag? (on reading #2420 through again, it sounds like the latter - a post type or tag.)

* Is "newness" a per-user thing - e.g. we try to stash a last-visited date in the user's localStorage? 

* Is there a limit to "newness" - e.g. new user (ignore all existing, wait til the next post?), user hasn't visited in awhile but there have been 20 features (render 'em all in the carousel?)

**Comment by youwenliang** [comment]
### Updated Spec Link: 
(including enabled/not-enabled experiment situations)
https://mozilla.invisionapp.com/share/8SBO0GLA9

All the news feed related measurements can be found here:
https://www.dropbox.com/sh/ludnt78ky7ttrwq/AACh3mXB8FsxMxbRpGs34Repa?dl=0

**Comment by SoftVision-CosminMuntean** [comment]
Hi @johngruen,  
We started to create test cases for the news functionality and we encountered some areas that were not covered in the descriptions. Here are a few questions:

1. The "New Updates" pop-up modal is only displayed when you have Test Pilot installed, right? Also, is it only displayed when you have a "notification" on the toolbar button and you navigate to Test Pilot homepage by clicking it ?
2. After the "New Updates" pop-up modal is dismissed, is there any way to be brought back? I am asking this for testing purpose. Otherwise it would be really hard to test.
3. What happens after you click the "Enable [experiment_name]" button from the button of the pop-up? What would be the pop up behavior.
4. If you click the "LEARN MORE >>" blue text link what happens? The details section is expanding or you are redirected to the experiment details page?

**Comment by meandavejustice** [comment]
@SoftVision-CosminMuntean 

>1. The "New Updates" pop-up modal is only displayed when you have Test Pilot installed, right? Also, is it only displayed when you have a "notification" on the toolbar button and you navigate to Test Pilot homepage by clicking it ?

My reading of the original description above was that updates should only be shown to users with testpilot installed and enabled. But that the popup modal will be shown to both users navigating to testpilot or being directed there from the toolbar button notification.

>2. After the "New Updates" pop-up modal is dismissed, is there any way to be brought back? I am asking this for testing purpose. Otherwise it would be really hard to test.

Based on other parts of these discussions, it looks like we will probably set a cookie to determine whether or not to show the modal, in that case all you should have to do to test would be to delete the cookie. If that doesn't work, we can always add a switch onto the `window` object for testing.

>3. What happens after you click the "Enable [experiment_name]" button from the button of the pop-up? What would be the pop up behavior.

My opinion would be to close the modal and redirect to the experiment's detail page. Not sure if @johngruen  or @youwenliang have something else in mind. Good catch for this edge case.

>4. If you click the "LEARN MORE >>" blue text link what happens? The details section is expanding or you are redirected to the experiment details page?

I think we should close the modal and navigate to experiment detail.

**Comment by johngruen** [comment]
After our discussion about moving the newsfeed out to a blog and focusing on short in product notifications, i think we can probably refocus this bug a bit.

* @lorchard WRT question of badging, we might lose that feature with migration away from the SDK, in Screenshots we faked badging by actually creating a different version of the logo. We might want to file a separate ticket to track badge state issues; IIRC @flodolo asked us ditch the SDK badge anyway since the string inside it isn't localized.
*WRT identifying major features; maybe this is just a beefier version of the schema for the little notifications that lives in the same yaml file. I guess with this one we'd have to flag that a user had previously dismissed it and not show it again, but that's my thought.
* Newness should be global; if a user doesn't open for N-time (2 weeks), we kill the notification
* Also we would only ever show one of these; if there are two notifications w/in a given timeframe, we just show the new one

@SoftVision-CosminMuntean @meandavejustice 

> 
> 1. The "New Updates" pop-up modal is only displayed when you have Test Pilot installed, right? Also, is it only displayed when you have a "notification" on the toolbar button and you navigate to Test Pilot homepage by clicking it ?

Only on /experiments

> 2. After the "New Updates" pop-up modal is dismissed, is there any way to be brought back? I am asking this for testing purpose. Otherwise it would be really hard to test.\

no, but we could probably find a way to reset from the console

> 3. What happens after you click the "Enable [experiment_name]" button from the button of the pop-up? What would be the pop up behavior.

not sure...i might de-scope this for the moment

> 4. If you click the "LEARN MORE >>" blue text link what happens? The details section is expanding or you are redirected to the experiment details page?

redirects to the experiment page (or a blog post if more appropriate)

**Comment by flodolo** [comment]
> IIRC @flodolo asked us ditch the SDK badge anyway since the string inside it isn't localized.

Correction: it's localized, and badly broken, which might be worse
https://github.com/mozilla/testpilot/issues/2325

**Comment by lmorchard** [comment]
It occurs to me just now that this feature might be kinked a bit by the need to rewrite the main Test Pilot add-on to get away from the SDK. That is, we can't use the SDK badge for this. (I mean, we *could* for the sake of closing this issue and then throw it away and rewrite it 😁 )

**Comment by jaredhirsch** [comment]
The approach Screenshots has taken here is to have an alternate version of the icon with a little brightly-colored star in one corner, to show users that it's new.

I think having a special icon would be far easier to implement in a bootstrapped addon, compared with creating and positioning some bit of XUL. Using a special starred icon also removes the issue of the localized label string being longer than the toolbar button itself.

**Comment by meandavejustice** [comment]
Getting back into this...

Looks like the UI described back on may 11th is still relevant minus the icon badges. (https://mozilla.invisionapp.com/share/8SBO0GLA9#/screens/232957979)

My understanding is that instead of icon badges we are going to be using [notifications](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications) now that the Testpilot addon is a webextension.

We have a couple different options for the layout of content inside a notification, https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/notifications/TemplateType. It probably makes the most sense to stick with the "basic" type and just link to the update with either the experiment or testpilot icon, with some simple messaging like "{Experiment Name} has had some updates, <a href="link-to-experiment-page-with-modal">take a look</a>"

**Comment by meandavejustice** [comment]
@johngruen @youwenliang

Been working on the implementation of this, needed little bit of clarification on something:

What is the behavior when `Enable {Experiment}` is clicked within the modal? The quickest solution would be to navigate to the Experiment's detail page and let the user enable the experiment themselves on this page. Another way to do this would be to carry over the behavior of the install button from the detail page, where we show progress etc.. all within the modal. Then we could direct to the experiment page and launch the tour dialog. This will introduce a lot more edge cases and push the time to implement this out a bit with testing, but be a nice flow for the user.

working branch: https://github.com/meandavejustice/testpilot/tree/2419-news-alerts

**Comment by johngruen** [comment]
@meandavejustice i think actually installing the experiment is an optimization we should make later on. We need to show users the privacy info and these cards don't display that info. Can we change that button to say "View Experiment Page"

**Comment by meandavejustice** [comment]
Looks like all that I am missing from this now is the assets for the icon. I will need an icon with the green background star badge and the pink icon star badge

cc/ @youwenliang @johngruen

**Comment by meandavejustice** [comment]
*bump* @johngruen

**Comment by johngruen** [comment]
@meandavejustice sorry, dropped this before vacation. Circling back now
