### ISSUE TITLE
No way to close the "We're still building Idea Town" modal

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#242]
### Steps to reproduce:
1. Go to http://idea-town-dev.elasticbeanstalk.com/
2. Click the "Get started with your Firefox Account" button.
3. Change your mind and try and read the "Terms of Service" or "Privacy Notice" links.
### Actual results:

You cannot close the helicopter modal without refreshing the page. Possibly not important if we don't expect the modal to be required for very long.
### Expected results:

Add a little "X" in the corner?
### Workaround:

Refresh the page.

**Comment by pdehaan** [comment]
<img width="1181" alt="idea_town_and_inbox__1_141__-_pdehaan_mozilla_com_-_mozilla_mail" src="https://cloud.githubusercontent.com/assets/557895/11108191/a5bca184-8899-11e5-9aef-0d05e10e5366.png">

~~Another oddity is if you have a smaller page and then scroll, down, the modal doesn't cover the entire page, only the original [unscrolled] viewport. New bug available upon request.~~

**Comment by johngruen** [comment]
@pdehaan yeah, probably a good idea. I kind of went back and forth on this one...Already fixed the modal/scrolling issue.

**Comment by meandavejustice** [comment]
no longer relevant since switching to new ui in #472
