### ISSUE TITLE
Stop using the add-on SDK

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#2423]
This is going to be a tracker for moving us away from the SDK.  If you make PRs, use the "connected to" keywords please.

Most of the content here comes from [our API spreadsheet](https://docs.google.com/spreadsheets/d/1r0EekWPF_v427dt0P_gs5MAEWHZDC78d7k1KWZNNfrs/edit#gid=0) and [the documentation comparing the SDK with webextensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Comparison_with_the_Add-on_SDK)

We don't actually know if these will easily convert to their webextension counterparts easily so if we run into any issues just bring them up and we'll figure them out.

Please note that this isn't a "make test pilot a web extension" issue -- we're just getting rid of the SDK for now.  One step at a time.

Replace these APIs:
- [ ] self
- [ ] page-mod
- [ ] ui/action/button
- [ ] timers
- [ ] L10n
- [ ] request
- [ ] tabs
- [ ] querystring
- [ ] simple-storage
- [x] notifications  (checking this one off, because deleting this code is already in #2417)
- [ ] util/uuid

**Comment by lmorchard** [comment]
Think I'll officially put myself down for taking a swing at this

**Comment by lmorchard** [comment]
Hmm, running into one wall so far: 

We've been using the SDK's `page-mod` module to inject `window.navigator` properties to inform [the web frontend](https://github.com/mozilla/testpilot/blob/master/addon/data/message-bridge.js) and [a couple of Mozilla sites & `about:home`](https://github.com/mozilla/testpilot/blob/master/addon/data/set-installed-flag.js) about Test Pilot installation state, version, and client UUID.

WebExtension content scripts looked like the easiest port-over approach. But, [WebExtension scripts are disallowed](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082) on [Mozilla hosts that can use `mozAddonManager`. ](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManagerWebAPI.cpp#39)

So, I need to figure out how to do the equivalent from bootstrapped add-on code. 😞  Could use some pointers, if anyone knows how to easily do that and save me some research.

**Comment by chuckharmston** [comment]
We could copy/paste [the `page-mod` source](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/content/page-mod.js) as a starting point?

**Comment by chuckharmston** [comment]
Also CC @aswan, who may have ideas.

**Comment by aswan** [comment]
Can you point me to a list of the pages where you want to inject test pilot information?

**Comment by lmorchard** [comment]
> Can you point me to a list of the pages where you want to inject test pilot information?

Basically, these patterns:

* https://testpilot.firefox.com/*
* https://testpilot.dev.mozaws.net/*
* https://testpilot.stage.mozaws.net/*
* https://example.com:8000/*
* https://www.mozilla.org/*
* about:home

For all the `testpilot.*` pages and `example.com`, we inject these properties (example data):
```javascript
window.navigator.testpilotAddon = true;
window.navigator.testpilotAddonVersion = '1.0.2';
window.navigator.testpilotClientUUID = '8673509blahblah';
```
For mozilla.org and about:home, we omit `testpilotClientUUID`.

We also set up a messaging channel with page content on testpilot pages, but I think that can go away now that those pages have access to mozAddonManager. 

FWIW, the [pagemod creation is here](https://github.com/mozilla/testpilot/blob/a6280f64f626fd2dd91abf7f6949f22c70d83ac6/addon/src/lib/WebApp.js#L43) and there are two page scripts - [set-installed-flag.js](https://github.com/mozilla/testpilot/blob/a6280f64f626fd2dd91abf7f6949f22c70d83ac6/addon/data/set-installed-flag.js) and [message-bridge.js](https://github.com/mozilla/testpilot/blob/a6280f64f626fd2dd91abf7f6949f22c70d83ac6/addon/data/message-bridge.js)

**Comment by lmorchard** [comment]
> We could copy/paste the page-mod source as a starting point?

I think that's probably overkill. We really just want to inject some properties into the content, can probably do without the communication ports now since mozAddonManager is available in content

**Comment by lmorchard** [comment]
FWIW, we can use mozAddonManager from the testpilot pages to take care of detecting the add-on and its version. Not sure how to pass along the testpilotClientUUID for metrics pings - but if there's an easier mechanism, we can switch over to that in the web frontend.

Maintaining compatibility [with about:home snippets filtering](https://github.com/mozmar/snippets-service/blob/0081d7417346b0811fcfc1727942b3b12703f036/snippets/base/templates/base/includes/snippet.js#L238) and mozilla.org as "third-party" users of this stuff is a concern. Not sure they're whitelisted to use mozAddonManager, and would like to avoid propagating changes into their bug pools unless absolutely necessary. Also not sure how prevalent their usage of these properties are

**Comment by lmorchard** [comment]
Hmm, I think I might be figuring out how to do it with [frame scripts](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Message_Manager/Frame_script_environment) - which I haven't used before, because I skipped learning about e10s and leaned on the SDK

**Comment by aswan** [comment]
Frame scripts would work if you want to have a single solution for all these different (types of) pages, which would be understandable...
Pages that have mozAddonManager cannot use WebExtensions content scripts, but since those pages have mozAddonManager, they can look up the test pilot extension to see which version (if any) is installed.  That won't get you the client id but why does the original page need that?
As for about:home, I have to admit I don't know much about how it is implemented but WebExtensions can't run content scripts on any about: pages since many of them run with chrome privileges.  From a quick glance at the snippest filtering code you linked, it looks like about:home does have some special privileges that allow it to read configuration data that isn't otherwise available to content (using UITour??)  Perhaps we could do something like that for test pilot?
For any other pages (eg mozilla.org from your original list), you should be able to use a content script to inject properties onto `window`.
For now, it sounds like the path you're currently on (using a frame script from the privileged portion of the test pilot extension) is probably a wise choice since the alternative is a patchwork of different techniques.

**Comment by lmorchard** [comment]
> Pages that have mozAddonManager cannot use WebExtensions content scripts, but since those pages have mozAddonManager, they can look up the test pilot extension to see which version (if any) is installed.

Yeah, that's part of where I hope to avoid propagating a demand for changes out to other projects and maintain the status quo of what we're doing in terms of external interface.

> That won't get you the client id but why does the original page need that?

We generate a UUID in the Test Pilot add-on for our own metrics - separate from Telemetry's UUID. It gets re-generated on uninstall & reinstall.

> For any other pages (eg mozilla.org from your original list), you should be able to use a content script to inject properties onto window.

Yeah, [I think I have that working now in my in-progress branch](https://github.com/lmorchard/testpilot/commit/a17ff14af1904debebf351e6a11618dd566a8270#diff-2d226cb81cbdfc1c0a6e6b9681da7917R17). I haven't checked yet whether it's working on about:home, but it seems like it should

**Comment by fzzzy** [comment]
This is merged!
