### ISSUE TITLE
No or wrong strings are displayed before the Test Pilot pages are fully loaded

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2431]
[Affected versions]:
- Firefox 53.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- The "extensions.webapi.testing" boolean pref was manually added with "true" value in "about:config" page.
- Have Test Pilot and at least one experiment enabled on the created profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net/".
2. Observe the Test Pilot homepage.
3. Click one of the enabled experiment card.
4. Observe the experiment details page.

[Expected result]:
- All the strings are correctly displayed while Test Pilot pages are loaded.  

[Actual result]:
Step 2: 
- "Installed" button is displayed instead of the "Choose your features" button.
- The "Enable" string is not displayed in the top left corner of the cards if experiments are enabled.
- The number of participants is not displayed.
- "Get Started" background is displayed over the "Manage" button.

Step 4:
- "[experiment_name] is enabled." string is not displayed on the top active green bar.
- "Your privacy" button is displayed instead of "Give Feedback" button and the "Disable [experiment_name]" is not displayed.
- "Just lunched" string is displayed instead of "There are x people trying [experiment_name] right now!" string.
- The text from "Your Privacy" area is not displayed.

[Notes]:
- The issue is also reproducible if Test Pilot add-on is not installed.
- Here is a screen recording (0.8x speed) of the issue: https://goo.gl/y9WEUU.

**Comment by fzzzy** [comment]
Thanks for the detailed analysis. We are going back to a loading indicator in https://github.com/mozilla/testpilot/issues/2434 so I will close this as a dup of that.
