### ISSUE TITLE
Users with Test Pilot installed should be automatically redirected to /experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2433]
Users with Test Pilot installed should never see `testpilot.firefox.com`.

They should always be redirected to `/experiements`

**Comment by SoftVision-CosminMuntean** [comment]
@johngruen I have question regarding to a similar behavior.

If you navigate directly to "https://testpilot.dev.mozaws.net/experiments" and you don't have Test Pilot installed, you should not be automatically redirected to "https://testpilot.dev.mozaws.net"?

**Comment by pdehaan** [comment]
I'm not sure about redirecting people who do **not** have the Test Pilot add-on installed.
That seems like we'd potentially be preventing Chrome users and search engines from seeing the experiments details pages.
