### ISSUE TITLE
Remember that users have been in experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2435]
So we already know when users are _currently_ in experiments, but @clouserw suggested we keep a bit more of a record about users past activities. The benefits of doing this would be:

- If a user leaves an experiment, we could later reconnect with them to try to entice them back, or follow up on their reasons for leaving.
- If an experiment leaves test pilot and eventually makes it into Firefox or AMO etc, we could directly message all participants of that experiment in order to thank them and let them know how to engage with the follow on version.

I don't think this has to be super complicated, we could probably just use local storage and keep a record of each:

1. experiment ID
2. if the user is currently in
3. if the user was in and the date they left
4. if the user was in when the experiment graduated

Seems like being able to poll this information for down-the-line messaging would help round out the experiment experience.

**Comment by ghost** [comment]
Original idea credit to ckarlof, but I am a supporter.  We should get this in before we graduate any more experiments.

**Comment by meandavejustice** [comment]
Thinking the object to store will look like this:

``` json
{
  "experimentHistory": {
    "@min-vid": {
       "installed": false,
       "uninstallDate": "2017-05-15T22:48:30.565Z"
     }
  }
}
```

From this we can infer if the experiment was graduated based on the `uninstallDate`

**Comment by ghost** [comment]
Let's get an installDate also.  People that just try out every experiment but remove them after 30minutes probably don't want a reminder later.  Or we could just delete the entry completely if it's less than a certain amount I guess.

I saw in your commit that you're using the sdk -- we gotta figure out another option.  Also, how persistent is that storage?

**Comment by meandavejustice** [comment]
@wresuolc I'm using sdk for now since that is what the rest of the addon is using. We can switch it to use webextension storage when we convert the rest of the addon.

I'll add the installDate as well, good thinking.

**Comment by lmorchard** [comment]
FWIW, this might all be better to do from the web site rather than the add-on, since that's where we do installs / uninstalls for the most part these days. (via mozAddonManager)

**Comment by dannycoates** [comment]
> since that's where we do installs / uninstalls for the most part these days

Clearly installs, but we don't have data on how many folks uninstall via about:addons vs the site. If we don't care about about:addons, fine, but i'd hesitate to exclude it with no idea of the ratio.

**Comment by dannycoates** [comment]
Well, reading the intended use case (after the fact 😂) since it's not a stats thing maybe we just let the about:addons folks slip through the cracks
