### ISSUE TITLE
Current add-on install page is minimal and 404s on XPI

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#244]
### Steps to reproduce:
1. Go to http://idea-town-dev.elasticbeanstalk.com/ [1]
2. Sign in with a @mozilla.com account
3. Click the [Install the Add-on] button [2]
### Actual results:

Add-on link 404s currently.
The "install the add-on" page is pretty light on details. I'm not entirely sure what the add-on does, why I want it. Or if I am interested in Idea Town yet and trust this add-on/site. Now I'm scared and full of doubt, but due to URL writing, I can't really go back in history to the original page.
### Expected results:

Not sure if it's possible to delay the Idea Town Add-on install until I try and install my first experiment so I can freely look around the site before fully committing.

---

![idea_town](https://cloud.githubusercontent.com/assets/557895/11131688/bd9a2f72-8940-11e5-9d9d-389f730dedd2.png)

![idea_town](https://cloud.githubusercontent.com/assets/557895/11131709/dde5a036-8940-11e5-8af8-d67d37a63318.png)

**Comment by lmorchard** [comment]
> Add-on link 404s currently.

Related to #92 / addon signing, I think.

> Not sure if it's possible to delay the Idea Town Add-on install until I try and install my first experiment so I can freely look around the site before fully committing.

FWIW, I think this has been discussed a few times in status meetings. If I recall, we made a deliberate decision to require addon installation before allowing experiment browsing. Might be worth bringing up again in a status meeting, since I can't remember what the reasoning was.

**Comment by meandavejustice** [comment]
fixed in #470
