### ISSUE TITLE
The loading indicator and the background are changing their position when page content is loaded (Windows)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2441]
[Notes]:
- Probably this happens because of the Firefox scrollbar when is redisplayed and pushes the page content a few pixels in the left part.

[Affected versions]:
- Firefox 53.0.2 and above

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to "https://testpilot.dev.mozaws.net/".
2. Click one of the available experiment cards.
3. Observe the loading indicator and the background.

[Expected result]:
- The loading indicator and the background does not change its position.

[Actual result]:
- The loading indicator and the background are changing their position.

[Additional Notes]:
- Also I have noticed that the background light darkens a little when the pages are loading. Probably because of the behavior described in "Notes" from issue #2440. When the page is loading, the page content is displayed under the loading indicator. 
- Here is the browser console errors: https://goo.gl/wMtfnW
- Here is a screen recording of the issue: https://goo.gl/7qoSfs

**Comment by jaredhirsch** [comment]
hmm, I'm not convinced this is actually worth fixing. @johngruen thoughts?

**Comment by SoftVision-CosminMuntean** [comment]
Closing this issue due to the fact that is no longer reproducible. I think this also was fixed by #2465 :relieved:.

**Comment by fzzzy** [comment]
🎉

**Comment by SoftVision-CosminMuntean** [comment]
I have observed that this issue is again reproducible. I think that this behavior is caused by the issue described in #2454.

**Comment by fzzzy** [comment]
Yes, this was broken again. I figured it out, pr incoming.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on dev and stage servers and is no longer reproducible. Marking as verified.
