### ISSUE TITLE
The 404 page is no longer displayed for wrong URLs

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/testpilot#2446]
[Affected versions]:
- Firefox 53.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to "https://testpilot.dev.mozaws.net/fourohfourohno".
3. Observe the displayed webpage.

[Expected result]:
- The Test Pilot page that treats 404 cases is correctly displayed.

[Actual result]:
- The TestPilot homepage is displayed.

[Notes]
- Attached a screenshot of the issue:
![issue_404](https://cloud.githubusercontent.com/assets/20083658/26163382/36f04830-3b32-11e7-9ca4-b352f712ce42.png)

**Comment by lmorchard** [comment]
We stopped doing routing by inspecting `window.location`, but we serve up `index.html` as the Error Document in S3. 

So, instead, I think we need to generate an `error.html` that dispatches to the proper 404 container with `data-page-name="error"` and reconfigure S3 to serve that up instead. (This will unfortunately require some ops help to complete for stage & prod.)

(notice that `index.html` is used twice below, in the static website hosting properties for testpilot.dev.mozaws.net - with my PR #2450, the error document will need to be `notfound/index.html`) 
<img width="550" alt="screenshot 2017-05-17 14 59 42" src="https://cloud.githubusercontent.com/assets/21687/26171024/7edfb872-3b11-11e7-821e-6c2992e4786c.png">

**Comment by ghost** [comment]
@relud would you change the Error document field to /notfound/index.html for the test pilot bucket?  thanks

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking as verified.

**Comment by relud** [comment]
this is fixed in stage, @clouserw we need to schedule a time to deploy this change to prod

**Comment by ghost** [comment]
@relud cool.  Our next push is June 6 at ~8ish in the morning.  Want to do it then?

**Comment by relud** [comment]
@wresuolc that wfm

**Comment by Softvision-VladBacia** [comment]
This issue is reproducible on stage env but on dev it is fixed. Tested on 06/02/2017

**Comment by relud** [comment]
@Softvision-VladBacia Thanks! looks like I need to set the cloudfront error url to that as well. stage should be fixed now.

**Comment by Softvision-VladBacia** [comment]
I have retested this issue and is no longer reproducible on stage. Marking as **Verified**.
