### ISSUE TITLE
Tweak CSS for more verbose locales

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#245]
Using [Google Translate](https://translate.google.com/#auto/de/Install%20the%20Idea%20Town%20Add-on%0Aand%20you%27re%20good%20to%20go!) I tried to convert the install add-on page to German to see how the UI would look with longer locales.

Things generally look pretty good, although I noticed that the buttons look a bit tight when you have longer strings.

---

![idea_town](https://cloud.githubusercontent.com/assets/557895/11132242/a5fac392-8943-11e5-82f3-046eeeadd95c.png)

**Comment by johngruen** [comment]
@pdehaan we're not localizing any time soon...
