### ISSUE TITLE
'npm start' semi-broken on Git for Windows (MINGW64)

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2453]
I've installed nodejs natively (that is, via an msi) on a win 10 system, and have also installed git for windows (which gives you git inside a MINGW 64-bit environment). I've also installed gulp globally in the git for windows environment, in the usual way (`npm install gulp -g`).

Interestingly, in my windows clone of the testpilot repo, `npm start` fails:

```sh
$ npm start

> testpilot@1.0.0 start C:\codez\github\mozilla-testpilot
> NODE_ENV=development ENABLE_DEV_LOCALES=1 ENABLE_DEV_CONTENT=1 gulp

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

However, if I type those commands manually into the prompt, the local server starts just fine:

```sh
$ NODE_ENV=development ENABLE_DEV_LOCALES=1 ENABLE_DEV_CONTENT=1 gulp
[15:46:21] Requiring external module babel-register
[15:46:32] Using gulpfile C:\codez\github\mozilla-testpilot\gulpfile.babel.js
[15:46:32] Starting 'default'...
[15:46:32] Starting 'self-lint'...
[15:46:37] Finished 'self-lint' after 4.67 s
[15:46:37] Starting 'clean'...
[15:46:37] Finished 'clean' after 27 ms
[15:46:37] Starting 'build'...
(continues, starts normally)
```

**Comment by pdehaan** [comment]
Wonder if we need something like [**cross-env**](https://www.npmjs.com/package/cross-env).

**Comment by lmorchard** [comment]
FWIW, I have a Windows laptop coming soon, so I may end up caring about this and may take a swing at it.

**Comment by lmorchard** [comment]
Yeah, it turns out that `npm` runs `cmd.exe` on Windows, no matter what shell you started from. Doesn't matter whether it's MINGW bash or Bash on Ubuntu on Windows. Looks like cross-env does the trick, though.
