### ISSUE TITLE
The pages content is wrongly displayed under the loading indicator, while the pages are loading

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2454]
[Affected versions]:
- Firefox 53.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open Firefox browser and navigate to "https://testpilot.dev.mozaws.net/".
2. Scroll the page until the "Install the Test Pilot Add-on" button reach the top part of the page.
3. Refresh the page and observe the browser behavior.

[Expected result]:
- The page content is not visible while the loading indicator is displayed.

[Actual result]:
- The page content is displayed under the loading indicator.

[Notes]:
- This issue is reproducible on most of Test Pilot pages with the add-on installed/uninstalled. Here is a screen recording with the issue with Test Pilot installed: https://goo.gl/bIsiVo
- Here is a screen recording with the issue when Test Pilot is not installed : 

![content page](https://cloud.githubusercontent.com/assets/19226534/26193920/5df03688-3bbf-11e7-9942-07d5f722390d.gif)

**Comment by fzzzy** [comment]
This is intentional.

**Comment by fzzzy** [comment]
Let me explain a little bit: by putting the actual html content in the page, that content should score higher in google and other search engines. We could hide those html nodes using css, but google is likely to penalize that severely. If the user does scroll down and try to use the html nodes before the js runs (or even with javascript turned off), they'll still be able to click links properly.

**Comment by SoftVision-CosminMuntean** [comment]
This behavior is no longer reproducible on dev server. I think this was fixed by #2465. :+1:

**Comment by SoftVision-CosminMuntean** [comment]
It seems that this issue is again reproducible. @fzzzy there is a chance that the fix for #2468 reintroduced the behavior?

**Comment by fzzzy** [comment]
Yes, it is likely that the fix for #2468 reintroduced this, although it wasn't intentional. I'll take a look.
