### ISSUE TITLE
German privacy and terms pages are no longer localized on dev server

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/testpilot#2455]
[Affected versions]:
- Firefox 53.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open a German localized build or change content language to "de".
2. Navigate to "https://testpilot.dev.mozaws.net/".
3. Click on any Terms or Privacy links under the green "Install" button.
4. Observe the page content language.

[Expected result]:
- Content of both pages is in German.

[Actual result]:
- Content of both pages is in English.

[Notes]
- On stage and production server the content for the privacy and terms pages is in German.

**Comment by lmorchard** [comment]
Hmm, [looks like the localized page exists](https://testpilot.dev.mozaws.net/terms/de), but we don't redirect to it anymore.

**Comment by SoftVision-EmilPasca** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking as verified.
