### ISSUE TITLE
The tour pop-up is out of date for Activity Stream

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/testpilot#2458]
[Notes]
- An image with the Activity Stream toolbar button is also displayed on the experiment page.
- This issue is also reproducible on stage and production servers.

[Affected versions]:
- Firefox 53.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- On a new Firefox profile, the "testpilot.env" string set to  "dev" in "about:config".
- TestPilot was already installed on a new profile.

[Steps to reproduce]:
1. Open browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/ page.
2. Click on the Activity Stream experiment card and choose to "Enable Activity Stream".
3. Observe the first two slides in the pop-up tour.

[Expected result]:
- The information displayed in the slides cover the current functionality of the feature.

[Actual result]:
- The slides show information about an out-of-date feature version.

[Notes]
- Attached a screenshot of the issue:
![as_issue_pop-uptour](https://cloud.githubusercontent.com/assets/20083658/26251756/05344c48-3cb7-11e7-9255-60202feb9a86.jpg)

**Comment by johngruen** [comment]
this is somewhat low priority ATM since we're likely to graduate this experiment soon

**Comment by pdehaan** [comment]
Related: https://github.com/mozilla/activity-stream/issues/1544
We can probably close both issues at the same time if we decide this isn't worth fixing.

**Comment by johngruen** [comment]
Wontfixing this due to graduation
