### ISSUE TITLE
Test Pilot in-add-on survey has broken L10n

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#2461]
On IRC, jkt gave us this screenshot:

https://irccloud.mozilla.com/file/v6cUFGfC/Selection_635.png

We've seen broken L10n on the site, but I just assumed weird caching.  I wouldn't expect to see it in the add-on.  Either way, we should probably fix it in both places, because I see screenshots of broken L10n pretty often.

jkt is on  1.1.2-dev-f3fe9bf

**Comment by lmorchard** [comment]
The add-on no longer has surveys, so... fixed I guess!
