### ISSUE TITLE
New Loading behavior breaks about/legal pages

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2468]
Oops!

**Comment by fzzzy** [comment]
Oh, that's because of the display: none on the static node I guess? That node gets removed automatically when the js loads, so I guess the css to hide it is just extra.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue an is no longer reproducible. The about/legal pages are successfully loaded. Marking as verified.
