### ISSUE TITLE
User is redirected to "/experiments" page instead of homepage when Test Pilot is uninstalled in another tab or window

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2472]
[Notes]
- This is not necessarily an issue, but before adding back the "/experiments" page, the redirect was correctly made on https://testpilot.firefox.com page.

[Affected versions]:
- Firefox 53.0.3 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- On a new Firefox profile, the "testpilot.env" string was added to "dev" in "about:config" page.
- The "extensions.webapi.testing" boolean pref was also added on the same profile with "true" value.
- TestPilot was already installed on the same new profile.

[Steps to reproduce]:
1. Open browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Open one of the available experiments in a new window.
3. Put both the windows on half screen display.
4. Focus the experiment window and click the "Settings" button on top right of the page.
5. Click the "Uninstall Test Pilot" option.
6. While observing the "/experiments" initial window, click the "Proceed" button.

[Expected result]:
- A redirect is performed from "/experiments" page to the Test Pilot Homepage on the initial window.

[Actual result]:
- A refresh is performed and you are left on the same "/experiments" page, but without Test Pilot installed

[Additional Notes]
- Here is a screen recording of the issue: https://goo.gl/9GFxmo

**Comment by ghost** [comment]
I don't think this is something we want to spend time on right now.  There is another issue which tweaks the way the /experiments redirect works which might affect this also.
