### ISSUE TITLE
Test Pilot share options should have some suggested text

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#2476]
Visit https://testpilot.firefox.com/share and click on the Facebook, Twitter or Email icons. They pop sharing mechanisms with just a long URL (with a bunch of modifiers for tracking it seems). As a user I can't just press share and I have to think of my own text/explanation for what the URL is.

I propose that by having some suggested copy included as part of the tweet, sharing numbers will go up.

**Comment by chuckharmston** [comment]
This page isn't used anymore. Closing!
