### ISSUE TITLE
If there is a lint error, the integration tests never complete.

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2477]
To reproduce, introduce a lint error on a branch (for example, use a javascript string with double quotes " instead of apostrophe ') and then push it to github. You can verify that a lint error occurs locally by using `npm run test:all`.

When circle tries to run the tests, the lint fails, and then the script which waits for the integration tests to complete runs forever.

**Comment by b4handjr** [comment]
Do you have example I could look at?

**Comment by b4handjr** [comment]
Fixed in #2484
