### ISSUE TITLE
Update dependencies again

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2480]
Whoops, it's been too long since we explicitly updated our dependencies. I'm going to do this first thing in our next sprint.

**Comment by jvhoven** [comment]
This might be worth looking into:

[Greenkeeper.io](https://greenkeeper.io/)
> Greenkeeper sits between npm and GitHub, observing all of the modules you depend on. When they get updated, your project gets a new branch with that update. Your CI tests kick in, and we watch them to see whether they pass.

**Comment by fzzzy** [comment]
@jvhoven Yes, we used to have greenkeeper enabled, but it was just far too noisy and we turned it off. We have since reduced the number of dependencies, so we may turn it on again soon.

**Comment by fzzzy** [comment]
Updating the dependencies causes things to break because of the propTypes deprecation. I tried to override the rule in .eslintrc but was not successful. We should therefore do #2482 before trying to update the deps again.
