### ISSUE TITLE
A "-" symbol is wrongly displayed on all experiments details pages if Test Pilot is not installed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2497]
[Affected versions]:
- Firefox 53.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to "https://testpilot.stage.mozaws.net/".
2. Click one of the available experiments.
3. Observe the experiment details page.

[Expected result]:
- No extra row is displayed on the page.

[Actual results]:
- A "-" symbol is displayed between the experiment logo and the description.

[Notes]:
- This issue is reproducible on dev and stage servers.
- Here is a screen shot with the issue:
![line](https://cloud.githubusercontent.com/assets/19226534/26826834/2c9c2f52-4ac3-11e7-95ac-0de3f72a2ecd.png)

**Comment by fzzzy** [comment]
John fixed this.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking as verified.
