### ISSUE TITLE
Sometimes Test Pilot pages takes more than 40 seconds to load

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2499]
[Affected versions]:
- Firefox 53.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on a new profile.

[Steps to reproduce]:
1. Open the browser and navigate to "https://testpilot.firefox.com/experiments".
2. Click one of the available experiments.
3. Click the "Firefox Test Pilot" text from the top of the page.
4. Repeat Step 2 and Step 3 a few times and observe the browser behavior.

[Expected result]:
- Each time, Test Pilot pages are quickly loaded.

[Actual results]:
- Sometimes Test Pilot pages takes more than 40 seconds to load.

[Notes]:
- Sometimes the page remains in the loading state until the tab is closed.
- While the page is loading a "Read ssl.google-analitycs.com" tooltip is displayed in the left bottom corner of the page.
- Here is a screenshot with browser console errors displayed while navigate through Test Pilot pages: https://goo.gl/ZD56Xy.
- Here is a screen recording with the issue: https://goo.gl/PMxiWI

**Comment by SoftVision-CosminMuntean** [comment]
It seems that this issue is much harder to reproduce. I was able to reproduce it only 4-5 times this morning and I am not sure what are the exactly steps. It happens randomly when I am navigating through the Test Pilot pages. 
Please let me know if you need more information. 

Here is a screenshot with Network Monitor after the page is successfully loaded: 
![loading network console](https://user-images.githubusercontent.com/19226534/26876665-f3c1d858-4b8f-11e7-8624-912d9655e9c6.png)

**Comment by ghost** [comment]
We've done some solid changes since then (avoiding loading the bundle again on /experiments loading).  Is this still seen?  Closing for review
