### ISSUE TITLE
FxA integration

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#25]
I think FxA now supports the implicit grant flow (no server needed) as well as the auth code flow (server-server secrets exchange). Auth code flow has been used longer, is probably fine as a starting point.

**Comment by lmorchard** [comment]
[django-allauth claims to support FxA](http://django-allauth.readthedocs.org/en/latest/providers.html#firefox-accounts), so I'm going to give that a try!

**Comment by lmorchard** [comment]
Going to say the groundwork for this was merged with PR #45 - let's create more specific issues for further iteration
