### ISSUE TITLE
Privacy & Terms pages localization differences, between Dev server and Stage & Production servers

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2502]
[Affected versions]:
- Firefox 53.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- A German localized build was installed / extracted or browser primary content language was set to "German [de]" on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.firefox.com/privacy/de page.
2. Open a new tab and navigate to http://testpilot.dev.mozaws.net/privacy/de page.
3. Switch between the tabs and observe the localized content for differences between servers.

[Expected result]:
- There is no difference in content localization between the servers.

[Actual results]:
- There are lots of differences in content localization between the servers.

[Notes]:
- Differences can be seen also on the Terms page translation between the servers.
- Looks like something might be broken on Dev server localization, because on "Terms" page also the numbering is broken, starting with "0" instead of "1".
- Dev server localization is different from Stage and Production one.
- Here is a screen recording with the issue: https://goo.gl/mzRNwD.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy It seems that the numbering issue mentioned above from "Terms" page is present also on "en-US" localization on Dev server.

**Comment by chuckharmston** [comment]
These pages are identical now. Closing!
