### ISSUE TITLE
Cover LayoutWrapper and View with FlowTypes

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2504]
In https://github.com/mozilla/testpilot/issues/2482 I ported our usage of propTypes to FlowTypes, but I punted on LayoutWrapper, View, and ExperimentPage because they were not straightforward. I put TODOs in the code. We should figure out how to use FlowTypes in these cases as soon as we can.

**Comment by meandavejustice** [comment]
This has become a much more accessible issue since @lmorchard took care of adding types to the experiment page, marking as `good-first-bug`.

There are comments showing a guideline in both `View` and `LayoutWrapper`.

https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/View/index.js#L119
https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/LayoutWrapper/index.js#L20

**Comment by kovsk1** [comment]
Hi, can I try to help out with this issue?

**Comment by meandavejustice** [comment]
@naperkovskiy That'd be great.

You can run the flow check with `npm run flow` and see flow coverage with `npm run flow-coverage`. Ping me if you have any questions :)

**Comment by kovsk1** [comment]
Hi @meandavejustice 

I think I have implemented FlowTypes to the View component but when I do "npm run flow" command I keep getting these errors. 

frontend/src/app/components/View/index.js:5
  5: import ReactDOMFactories from 'react-dom-factories';
                                   ^^^^^^^^^^^^^^^^^^^^^ react-dom-factories. Required module not found

frontend/src/app/components/View/index.js:6
  6: import Symbol from 'es-symbol';
                        ^^^^^^^^^^^ es-symbol. Required module not found

frontend/src/app/components/View/index.js:87
 87:       return <NewsletterFooter {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `NewsletterFooter`
 21:   props: NewsletterFooterProps
              ^^^^^^^^^^^^^^^^^^^^^ property `getWindowLocation`. Property not found in. See: frontend/src/app/components/NewsletterFooter/index.js:21
 87:       return <NewsletterFooter {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `NewsletterFooter`

frontend/src/app/components/View/index.js:87
 87:       return <NewsletterFooter {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `NewsletterFooter`
 21:   props: NewsletterFooterProps
              ^^^^^^^^^^^^^^^^^^^^^ property `newsletterForm`. Property not found in. See: frontend/src/app/components/NewsletterFooter/index.js:21
 87:       return <NewsletterFooter {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `NewsletterFooter`

frontend/src/app/components/View/index.js:87
 87:       return <NewsletterFooter {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `NewsletterFooter`
 21:   props: NewsletterFooterProps
              ^^^^^^^^^^^^^^^^^^^^^ property `sendToGA`. Property not found in. See: frontend/src/app/components/NewsletterFooter/index.js:21
 87:       return <NewsletterFooter {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `NewsletterFooter`

frontend/src/app/components/View/index.js:94
 94:       return <Footer {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Footer`
 14:   props: FooterProps
              ^^^^^^^^^^^ property `sendToGA`. Property not found in. See: frontend/src/app/components/Footer/index.js:14
 94:       return <Footer {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Footer`

frontend/src/app/components/View/index.js:101
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Header`
 27:   props: HeaderProps
              ^^^^^^^^^^^ property `forceHideSettings`. Property not found in. See: frontend/src/app/components/Header/index.js:27
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Header`

frontend/src/app/components/View/index.js:101
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Header`
 27:   props: HeaderProps
              ^^^^^^^^^^^ property `hasAddon`. Property not found in. See: frontend/src/app/components/Header/index.js:27
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Header`

frontend/src/app/components/View/index.js:101
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Header`
 27:   props: HeaderProps
              ^^^^^^^^^^^ property `openWindow`. Property not found in. See: frontend/src/app/components/Header/index.js:27
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Header`

frontend/src/app/components/View/index.js:101
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Header`
 27:   props: HeaderProps
              ^^^^^^^^^^^ property `sendToGA`. Property not found in. See: frontend/src/app/components/Header/index.js:27
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Header`

frontend/src/app/components/View/index.js:101
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `Header`
 27:   props: HeaderProps
              ^^^^^^^^^^^ property `uninstallAddon`. Property not found in. See: frontend/src/app/components/Header/index.js:27
101:       return <Header {...this.props} />;
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Header`

I think that ReactDOMFactories has been deprecated and it may be a part of another issue but the rest seem to work fine, but the command throws these error.

**Comment by ghost** [comment]
We're going to close this.  There is more info at #3497
