### ISSUE TITLE
The minimum browser version requirement message wrongly displays "49" as supported

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2509]
[Affected versions]:
- Firefox 49.0.2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have Firefox 49.0.2 version installed on the computer.  

[Steps to reproduce]:
1. Launch the Firefox 49.0.2 version. 
2. Navigate to "https://testpilot.dev.mozaws.net/" page.
3. Observe the message displayed above the green "Upgrade Firefox" button.

[Expected result]:
- "Test Pilot requires Firefox 50 or higher." message is displayed.

[Actual results]:
- "Test Pilot requires Firefox 49 or higher." message is wrongly displayed, even if now the minimum version is Firefox 50.

[Notes]:
- Here is a screen shot with the issue:
![firefox 49](https://user-images.githubusercontent.com/19226534/26970199-2930ec54-4d11-11e7-857d-1cdcc1d5ac38.png)

**Comment by SoftVision-PaulOiegas** [comment]
Correct version is now displayed on versions under Firefox 50. Marking this as verified.
