### ISSUE TITLE
Include star images with Test Pilot add-on.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2512]
Pulse [has discovered](https://github.com/mozilla/pulse/issues/179) that the star images that Test Pilot's Heartbeat prompts are likely to rely on [are being removed](https://hg.mozilla.org/mozilla-central/rev/48a6570b38cb#l5.137) from Nightly with Photon work.

The Test Pilot add-on should ship with our own images, and make sure that it looks good on each operating system.

**Comment by ghost** [comment]
Depending on what we do with the notification bar we might get this fixed for free.  Les's new add-on is removing this functionality
