### ISSUE TITLE
Use paid localizers to translate large blocks of text

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2514]
We've discussed using a paid localization service to avoid burdening Mozilla's volunteer localizers with translating large amounts of text, like experiment descriptions, or our 'about' page.

This is a bug to track the definition of some process around that work.

**Comment by flodolo** [comment]
Can you make sure to talk with Peiying Mo (@peiying2) about vendors?

**Comment by peiying2** [comment]
@6a68 please send me an email on your request and we go from there.

**Comment by flodolo** [comment]
To clarify: I think you (Test Pilot folks) and Peiying should talk about this, since she has experience and vetted vendors, and in the meantime you might be trying to figure the process on your own.

**Comment by johngruen** [comment]
I think the blog will mitigate this, but adding needs product for now

**Comment by ghost** [comment]
We're putting graduation reports on https://medium.com/firefox-test-pilot now.  I don't think we need this anymore.  Re-open if you disagree please.
