### ISSUE TITLE
Experiment Ratings Bar (SDK) Seems Borked in Nightly

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2522]
One more reason to get of the SDK, our "heartbeat" ratings are no longer working correctly in 56. Instead, they display a dark bar and no longer show stars. Whatever styles we're inheriting don't seem to be there any more.

**Comment by lmorchard** [comment]
> One more reason to get of the SDK

FWIW, the APIs to make the ratings bar don't exist at all for WebExtensions - and IIRC that API isn't from the SDK [but from directly dealing with XUL](https://github.com/mozilla/testpilot/blob/master/addon/src/lib/feedbackUI.js#L28). We can do that in a bootstrapped extension or embedded webextension, but it'll likely still carry over this issue. So, getting rid of SDK won't help here. We might want to think about redesigning that feedback mechanism UI-wise

**Comment by chuckharmston** [comment]
#2512
