### ISSUE TITLE
[addon] Protocol vs Protocall

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#253]
Spotted this while trying to install the add-on via _about:addons_:

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/11195530/34a8a6d8-8c67-11e5-8057-7c91f4b617bb.png)

Wasn't sure if this was just a typo, or had some deeper meaning that my ignorant self is unaware of.
Looks like this is coming from [./addon/package.json:33-34](https://github.com/mozilla/idea-town/blob/8e98c7963b58349cd4a1638df9b96f3672dd7a2f/addon/package.json#L33-L34):

``` js
  "preferences": [
    {
      "name": "BASE_URL",
      "title": "Ideatown protocall",
      "description": "protocall",
      "type": "string",
      "value": "http://ideatown.dev:8000"
    },
```

**Comment by pdehaan** [comment]
Plus, if we're tweaking that config page, I'd also vote to change the 5x instances of "Ideatown" in the configs to "Idea Town" to be in sync with the add-on name and brand stuffs.

**Comment by pdehaan** [comment]
Also, as a note to my future self who struggles with simple tasks...

Dear future self,
Remember that you'll [possibly] need to set the `xpinstall.signatures.required` and `xpinstall.whitelist.required` flags to **false** in [about:config](about:config) to get the add-on installed and running (due to add-on signing).

Best,
me

**Comment by meandavejustice** [comment]
@pdehaan Thanks for pointing all of this out. I've been overlooking these.
