### ISSUE TITLE
Test Pilot - Error: install failed

### ISSUE THREAD

**Issue by ipmanlk** [mozilla/testpilot#2530]
I have been trying to install Test Pilot addon since the day it was released. But still, I can't do that. I tried every possible solution I could find in firefox forums, test pilot discussion boards and other places. But still no luck. When  I click on Install Test Pilot button, nothing happens. It's just showing installing and that's it. (Check console output below). I tried disabling my Antivirus (ESET SS8) & also I'm on Windows 10 Pro. 

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://testpilot.firefox.com https://ssl.google-analytics.com”). Source: onsubmit attribute on DIV element. testpilot.firefox.com
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://testpilot.firefox.com https://ssl.google-analytics.com”). Source: onchange attribute on DIV element. testpilot.firefox.com
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://testpilot.firefox.com https://ssl.google-analytics.com”). Source: onfocusin attribute on DIV element. testpilot.firefox.com
Content Security Policy: The page’s settings blocked the loading of a resource at https://ff-input.mxpnl.net/data?_channel_id=&_partner_id=39571&_sub_id=0000&_app_version=1.0.23&_app=cs-dca (“connect-src https://testpilot.firefox.com https://sentry.prod.mozaws.net https://www.google-analytics.com https://ssl.google-analytics.com https://basket.mozilla.org https://analysis-output.telemetry.mozilla.org”).  (unknown)
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More]  app.ftl
Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.[Learn More]  experiments.ftl
uncaught exception: undefined  (unknown)
Error: install failed
```

Now, is it possible to install this addon from anywhere else? or manually using the .xpi file?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @ipman98 and thanks for your report. Since you mentioned about ESET antivirus client, is there any add-on related to it installed in "about:addons" page at "Extensions" tab ? If yes, try disabling that one before retrying the installation.

If this is not the case, are you in some kind of a network that has a 3rd party firewall ? In the past we had some users that were trying to install our add-ons from private environments like school or company networks and encountered the same issue.

**Comment by ipmanlk** [comment]
Hi @SoftVision-PaulOiegas & thanks for your reply. Answer for your first question is no, I don't have any kind of addon installed related to my antivirus. But I do have a 3rd party firewall from my antivirus. But I don't believe it's causing this. 

Also, I tried to install Test Pilot from my Linux laptop & it worked just fine.

**Comment by lmorchard** [comment]
> But I do have a 3rd party firewall from my antivirus. But I don't believe it's causing this.

Firewalls from antivirus packages *can* often cause issues. If I recall, it's because they intercept SSL requests, decrypt, scan, and then re-encrypt them with a certificate that Firefox does not recognize as being from a site permitted to install add-ons.

**Comment by chuckharmston** [comment]
What @lmorchard cites is what is happening here, indicated by this line in the console output:

> Public-Key-Pins: The certificate used by the site was not issued by a certificate in the default root certificate store. To prevent accidental breakage, the specified header was ignored.

**Comment by SoftVision-PaulOiegas** [comment]
Yep, that line was the reason why I was asking for antivirus add-on in the first place. 
@ipman98 can you look into the Antivirus Firewall settings and look for options related to HTTPS filtering or related to certificates? One particular user had the same problem and after unchecking it (http://imgur.com/W26U8e2), he fixed the install problem.
 
You mentioned about ESET AV client, maybe these links will help.
http://support.eset.com/kb5833/?viewlocale=en_US
http://support.eset.com/kb939/?viewlocale=en_US

**Comment by ipmanlk** [comment]
@SoftVision-PaulOiegas Thanks for your help. I was able to fix the issue by disabling eset's HTTPs filtering & realtime protection.
