### ISSUE TITLE
The "Take a quick survey" button text from "/retire" page dialog is not visible 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2534]
[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Test Pilot add-on was already installed on the same profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click the top right "Settings" button and choose the "Uninstall Test Pilot" option.
3. Click the "Proceed" button on the displayed pop up.
4. After the uninstall is complete, observe the buttons on the displayed dialog.

[Expected result]:
- The dialog displays a blue button with "Take a quick survey" white text and a "Home" blue text button.

[Actual results]:
- Both the buttons are displayed but the "Take a quick survey" white text is not visible on the blue one.

[Notes]:
- The text becomes hardly visible if you hover the button.
- Also, the line spacing for the displayed dialog text is bigger on dev server than on production server.

![no text](https://user-images.githubusercontent.com/17258026/27337438-18052fa8-55db-11e7-89d8-956c42e103ab.png)

**Comment by SoftVision-PaulOiegas** [comment]
Same thing occurs for the 404 page "Home" button. I think we should fix this before we release on Public server.

![404 button](https://user-images.githubusercontent.com/17258026/27859037-237867f0-6180-11e7-94f4-656629ae56ac.png)

**Comment by johngruen** [comment]
This has been fixed for awhile
