### ISSUE TITLE
The user must manually enter "https://" protocol in order to navigate to "testpilot.dev.mozaws.net" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2535]
[Notes]:
- I don't think there is any popular website that requires the user to manually enter the "https" protocol if he tries to navigate to it without entering the protocol. I think this kind of message should only be displayed if the user specifically tries to navigate to Test Pilot website using just the "http" protocol.

[Affected versions]:
- Firefox 54.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Enter "testpilot.dev.mozaws.net" address in the awesomebar and hit the "Enter" key.
3. Observe the browser behavior and displayed page.

[Expected result]:
- Since the "https" protocol is available for Test Pilot pages, you are automatically redirected to "https://testpilot.dev.mozaws.net" page.

[Actual results]:
- You are not redirected to the "https" page, instead an intermediate page is displayed informing you that "Test Pilot must be accessed over HTTPS. Please see our documentation for details.".

**Comment by ghost** [comment]
@SoftVision-PaulOiegas can you still reproduce this?

**Comment by SoftVision-PaulOiegas** [comment]
No, it was fixed long ago. I thought I closed this, but it was a separate issue regarding other browsers redirect.
Closing now 👍
