### ISSUE TITLE
Skip tests in Circle CI for commits from Pontoon on master branch?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2542]
Hacky idea in advance of moving l10n to a branch in #2430: 

What if we looked for `/^Pontoon: Update/` in the commit message on CircleCI and use that as a signal to just skip tests altogether? Chances are low that any particular Pontoon commit will break the site, and such commits are very frequent because our localizer community is prolific. So, we get a lot of mostly useless test runs.

**Comment by lmorchard** [comment]
<strike>Alternatively, if Pontoon supported it, we could add `[skip ci]` to commit titles or descriptions - [because CircleCI supports this as a conventional signal to skip test runs](https://circleci.com/docs/1.0/skip-a-build/).</strike> Pontoon does not support this, and it sounds like it would take significant work to support custom commit templates per-project.

**Comment by ghost** [comment]
Let's focus on the L10n branch
