### ISSUE TITLE
TXP-48: Test Pilot Web Experiments

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#2546]
@johngruen 
In order to accommodate web experiments on Test Pilot, I created the proposal and took some future possibilities into consideration as well to ensure the flexibility, such as mobile experiments. However, for the current implementation, please feel free to implement only what we need for now. Besides, for web experiments, perhaps we can display how many users visit the web experiment instead of removing the user counts section. What do you think? 

![web experiments](https://user-images.githubusercontent.com/18019946/27419581-525ad138-5754-11e7-8c1c-92710308dbd0.png)

Please find assets here.
web experiment: https://github.com/mozilla/testpilot-assets/blob/master/Test_Pilot_Website/00_Assets/webexperiment.svg
add-on: http://design.firefox.com/icons/icons/addons/extensions.svg
mobile: http://design.firefox.com/icons/icons/new/device-mobile-16.svg

**Comment by lmorchard** [comment]
Think I can start taking a look at this, might be a good thing to set up along with a React Storybook demo

**Comment by lmorchard** [comment]
(meant to post this on #2462 but can come back to this one too)

**Comment by ghost** [comment]
Les accidently clicked the take button!

**Comment by lmorchard** [comment]
Hmm, well I have a PR for #2462, so maybe I *will* start on this. Sorry for the confusion

**Comment by lmorchard** [comment]
One gotcha: Getting a visit count for a web experiment will be a small project itself. We have a JSON resource we load from Telemetry for add-on install counts. We'd need something similar for experiment sites - e.g. from Google Analytics or similar.

Otherwise, I should be able to build the rest of this on our side

**Comment by lmorchard** [comment]
Also, it looks like platform isn't a single type - i.e. it's any combination of web, mobile, and add-on? Some questions / thinking out loud:

- Is it really any combination? If so, we'll need 6 strings for localization to cover the permutations: web; add-on; mobile; web + mobile; mobile + add-on; web + mobile + add-on.
- If there will be a web + add-on experiment, what do we do with the "Enable" / "Go to" button on the experiment detail page? Show both enable add-on and go-to site? Similar concern for displaying install count vs visit count

**Comment by lmorchard** [comment]
Oh yeah, this also occurred to me just now: I see the concept of "enabled" for mobile & web experiments. That could be really tricky to track & implement. We only know if an add-on has been installed, not whether the user has visited a site or installed a mobile app

**Comment by SoftVision-PaulOiegas** [comment]
The indicators were added just for the web experiments or for all experiments types?
I'm asking because I'm not seeing any indicators on dev, and I can't access either the storybook links from the PR. 🤔
