### ISSUE TITLE
Remove addon code that removes experiments when txp addon is removed

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#2557]
Related to #1011

**Comment by ghost** [comment]
great idea!

**Comment by lmorchard** [comment]
FWIW, the addon i'm working on for #2423 doesn't include any add-on install / uninstall code. So we could consider that a fix for this

**Comment by johngruen** [comment]
@clouserw any idea why this is needs:product?

**Comment by lmorchard** [comment]
I think we were trying to decide whether this is still something we wanted the add-on to do on uninstall. It doesn't do it now - so if that's okay product-wise, we can just close this.
