### ISSUE TITLE
The new page content loading animation has pixelated edges on the left transition

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2565]
**[Affected versions]:**
- Firefox 54.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Tools" browser button from top bar and hover the "Web Developer" option
3. Select the "Responsive Design Mode" option and enlarge the view port to see the whole page.
4. Select a low throttling option from the responsive mode bar (GPRS or Regular 2G).
5. Refresh the page a few times and observe how the new loading animation paints.

**[Expected result]:**
- The animation is smoothly working and has no "sharp edges".

**[Actual results]:**
- The animation edges are pixelated on the left transition.

**[Notes]:**
- Here is a screenshot of the issue (no damn good screen recorders on Mac OS 😄): 

![new animation](https://user-images.githubusercontent.com/17258026/27664752-33f72178-5c1e-11e7-8543-71b1f4349e76.png)

**Comment by fzzzy** [comment]
We went back to the old loader for now 🎉
