### ISSUE TITLE
The Test Pilot Homepage remains in infinite loading loop

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2570]
**[Affected versions]:**
- Firefox 54.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the page behavior.

**[Expected result]:**
- A loading animation is displayed and after the Test Pilot homepage content is loaded.

**[Actual results]:**
- The loading animation is displayed but the homepage never loads.

**[Notes]:**
- If you enter any other link related to Test Pilot (eg: /experiments), the page correctly loads.

**Comment by lmorchard** [comment]
I think our CloudFront distribution is a bit jumbled from a series of recent auto-deployments close together - the index.html points to JS & CSS URLs that are no longer in S3, so the page never manages to load things up. Going to restart the most recent CircleCI run and see if the deployment sorts things out.

**Comment by lmorchard** [comment]
[Just finished a rebuild & deploy](https://circleci.com/gh/mozilla/testpilot/4670), which I *think* fixed this issue.

**Comment by SoftVision-PaulOiegas** [comment]
Seems so 👍
