### ISSUE TITLE
Invalid 'self' link in feed.atom

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2575]
https://testpilot.dev.mozaws.net/__version__ (d609c15b8dfc62fc8c0a76d5e5298336a7816dc7):

```js
{
  commit: "d609c15b8dfc62fc8c0a76d5e5298336a7816dc7",
  version: "",
  source: "https://github.com/mozilla/testpilot",
  build: "https://circleci.com/gh/mozilla/testpilot/4698"
}
```

---

https://testpilot.dev.mozaws.net/feed.atom has the following output:

```xml
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
    <id>https://blog.mozilla.org/testpilot</id>
    <title>Test Pilot News Updates</title>
    <updated>2017-06-30T16:36:54Z</updated>
    <generator>Feed for Node.js</generator>
    <author>
        <name>Mozilla</name>
        <uri>https://testpilot.firefox.com</uri>
    </author>
    <link rel="alternate" href="https://blog.mozilla.org/testpilot"/>
    <link rel="self" href="[object Object],[object Object]"/>
    <subtitle>News Updates for Test Pilot experiments</subtitle>
    <icon>https://testpilot.firefox.com/static/images/favicon.ico</icon>
</feed>
```

Note the odd `<link rel="self" href="[object Object],[object Object]"/>` bit:

```xml
<link rel="self" href="[object Object],[object Object]"/>
```

**Comment by pdehaan** [comment]
Similarly in the https://testpilot.dev.mozaws.net/feed.rss file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>Test Pilot News Updates</title>
        <link>https://blog.mozilla.org/testpilot</link>
        <description>News Updates for Test Pilot experiments</description>
        <lastBuildDate>Fri, 30 Jun 2017 16:36:54 GMT</lastBuildDate>
        <docs>http://blogs.law.harvard.edu/tech/rss</docs>
        <generator>Feed for Node.js</generator>
        <atom:link href="[object Object],[object Object]" rel="self" type="application/rss+xml"/>
    </channel>
</rss>
```

Specifically:
```xml
<atom:link href="[object Object],[object Object]" rel="self" type="application/rss+xml"/>
```

**Comment by lmorchard** [comment]
I think this will be addressed by https://github.com/mozilla/testpilot/pull/2573 - items are missing *and* the self link is weird

**Comment by pdehaan** [comment]
Looks like the self links are also failing the validator:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftestpilot.dev.mozaws.net%2Ffeed.atom
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftestpilot.dev.mozaws.net%2Ffeed.rss

I can't seem to find a json.feed validator yet.

But I can recheck all these once #2573 lands.

**Comment by pdehaan** [comment]
OK, built locally and now the validator is saying the feed is valid, with one minor nit:

http://0.0.0.0:8000/feed.atom:

> ### Recommendations
> This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
>
> line 12, column 69: Self reference doesn't match document location [help]
> ```xml
>    <link rel="self" href="https://testpilot.firefox.com/feed.atom"/>
> ```

---

http://0.0.0.0:8000/feed.rss:

> ### Recommendations
> This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
>
> line 10, column 105: Self reference doesn't match document location [help]
> ```
> ...  rel="self" type="application/rss+xml"/>
>                                             ^
> ```
>
> line 16, column 12: Ensure description precedes content:encoded (2 occurrences) [help]
> ```
>            <content:encoded><![CDATA[We added this news feed to Test Pilot  ...
>            ^
> ```

For the first issue, not sure if we want to use the current domain versus hardcoding production. 🤷‍♀️ 
Not sure what to do about the second issue of `<description>` being before `<content:encoded>`. I don't even see a `<description>` element in the `<item>` node.

```xml
        <item>
            <title><![CDATA[Changes on the way]]></title>
            <link>https://testpilot.firefox.com/experiments/#general-update-2</link>
            <guid>https://testpilot.firefox.com/experiments/#general-update-2</guid>
            <pubDate>Thu, 29 Jun 2017 12:00:01 GMT</pubDate>
            <content:encoded><![CDATA[Page Shot, Activity Stream, Tab Center, and Pulse will graduate from Test Pilot next week as we get ready for the next round of experiments. We'll follow up very soon to tell you where these experiments are going and how you can keep using them.
]]></content:encoded>
        </item>
```

**Comment by pdehaan** [comment]
Per the `<description>` warning in the above comment, it seems like we can just add a `description` property to the feed item:

```js
  newsUpdates.forEach(({experimentSlug, title, slug, link, published, content}) => {
    const item = { title, date: published };
    item.description = content.trim();
    item.content = converter.makeHtml(item.description);
```

We can probably ignore that `item.content = converter.makeHtml(item.description)` bit. I was just experimenting with converting the plain text to HTML using [**showdown**](https://github.com/showdownjs/showdown):

```js
const showdown  = require('showdown');
const converter = new showdown.Converter({
  simpleLineBreaks: true,
  simplifiedAutoLink: true
});
```

### Output:

```xml
        // ...
        <item>
            <title><![CDATA[My Update title dos]]></title>
            <link>https://blog.mozilla.org/testpilot/example2</link>
            <guid>https://blog.mozilla.org/testpilot/example2</guid>
            <pubDate>Sat, 03 Jun 2017 12:00:00 GMT</pubDate>
            <description><![CDATA[Example content goes here, homeskillet.]]></description>
            <content:encoded><![CDATA[<p>Example content goes here, homeskillet.</p>]]></content:encoded>
        </item>
    </channel>
</rss>
```

**Comment by fzzzy** [comment]
This is fixed now
