### ISSUE TITLE
Save voice sample and submitted text with a method respecting a user's privacy

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#2576]
When saving the voice sample:

 -  Ensure the voice data is not associated with any person-identifiers, including Firefox or Test Pilot identifiers
- Don't send the voice sample to two places
- No requirement to delete within a time frame

/cc @eleemoz @johngruen 

Andre:  Can you sketch a diagram of how this works?  Kaldi can probably save a sample, but we need to do a separate ping for what was submitted?  let's talk!

**Comment by lmorchard** [comment]
Was this meant to be filed in another repo?

**Comment by ghost** [comment]
yeah
