### ISSUE TITLE
Feed id/link point to a 404 page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2578]
Ref: [/frontend/tasks/content.js:40-41](https://github.com/mozilla/testpilot/blob/6e4cc60ee54f99f71a52cf9f3db7992a27829690/frontend/tasks/content.js#L40-L41),

```js
id: 'https://blog.mozilla.org/testpilot',
link: 'https://blog.mozilla.org/testpilot',
```

But if you go to https://blog.mozilla.org/testpilot, you get a glorious 404 page.

**Comment by chuckharmston** [comment]
![](http://textfiles.com/underconstruction/BaBajaCanyon9450construct4.gif)

http://textfiles.com/underconstruction/
