### ISSUE TITLE
changelog link looks mis-aligned on experiment details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#258]
### Steps to reproduce:
1. Sign in and go to http://idea-town-dev.elasticbeanstalk.com/experiments/test
2. Look at the "Details" -> "Version" section.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11224307/2e463928-8d29-11e5-8efc-28fe395d3b0f.png)
### Actual results:

The "changelog" link doesn't align with the last updated text.
Looking through the source, I'm guessing it's because the [`<span data-hook="version"></span>`](https://github.com/mozilla/idea-town/blob/6526f8f58b52596c871df8aa644c02e326350508/idea_town/frontend/static-src/app/templates/experiment-page.js#L38-L39) isn't getting set (or has no value in the database). That, combined with the `&nbsp;<a data-hook="changelog-url">changelog</a>` causes the extra space and alignment issue.

I guess this is a non-issue as long as the version number for an add-on is always set.

**Comment by lmorchard** [comment]
Hmm, though we should probably hide the elements if they're optional and not filled in (like Contribute, also)

**Comment by pdehaan** [comment]
Should "Version" and "Last Update" be optional?

**Comment by pdehaan** [comment]
> we should probably hide the elements if they're optional and not filled in

Filed as https://github.com/mozilla/idea-town/issues/281

**Comment by lmorchard** [comment]
https://github.com/meandavejustice/idea-town/commit/26e3e207f2cac4351a446b2bdab78b4724800c96
