### ISSUE TITLE
Dates in newsfeed are not localized

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2583]
I'm looking at Test Pilot in Italian and I see `June 29th, 2017` instead of a properly localized date.

![schermata 2017-07-04 alle 12 42 04](https://user-images.githubusercontent.com/3644868/27827152-31cc76f4-60b6-11e7-9e54-3f4bce011bc3.png)

**Comment by flodolo** [comment]
Now it looks like this, with localized names and a completely broken format for Italian. Full English would be better.

<img width="1015" alt="schermata 2017-10-18 alle 19 41 42" src="https://user-images.githubusercontent.com/3644868/31733607-724d2b68-b43c-11e7-9714-40d4a3f889ff.png">

**Comment by lmorchard** [comment]
Two spots where we format news update timestamps that need reworking:

* https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/UpdateList/index.js#L12
* https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/NewsUpdatesDialog/index.js#L37

Might be better to use the [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) API? Seemed like [we had good luck with it on Snooze Tabs](https://github.com/bwinton/SnoozeTabs/blob/master/src/lib/time-formats.js) and it seems to have good browser support.

**Comment by flodolo** [comment]
> Might be better to use the Intl.DateTimeFormat API? Seemed like we had good luck with it on Snooze Tabs and it seems to have good browser support.

Yes, I think that would be a better approach

**Comment by ghost** [comment]
closing in favor of #3512
