### ISSUE TITLE
Weird scaling issue when dragging test pilot out of the toolbar into the customize area on nightly

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2585]
This only happens on Nightly, not release.

STR:

Install test pilot.
Click hamburger menu. Click customize.
Drag test pilot into the customize area, out of the toolbar.

Expected:
Test pilot icon in the customize area looks correct.

Actual:
Test pilot icon in the customize area has a weird scale ratio.

This doesn't happen for the other icons in the toolbar. Are we not setting a scale factor on our svg that other icons are?

![screen shot 2017-07-05 at 5 19 52 pm](https://user-images.githubusercontent.com/46048/27885484-3243342e-61a6-11e7-93ae-3e793d1b1791.png)

**Comment by jonathanKingston** [comment]
I think the fill might be wrong too, I noticed the library icon suffered from this in Photon to but I think they fixed that. When in the customise area the icon should match the same colour.

**Comment by fzzzy** [comment]
https://github.com/mozilla/testpilot/issues/2602 is probably a dupe of this, and is already in our next sprint. So I am going to close this bug in favor of that one.
