### ISSUE TITLE
Experiment details page doesn't seem to mention Idea Town at all

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#259]
I just noticed that there doesn't seem to have any references to Idea Town on the [experiment details](http://idea-town-dev.elasticbeanstalk.com/experiments/example-experiment) page.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11224764/7c7e151e-8d2b-11e5-9bc2-bfa1909a925e.png)
**Figure 1:** Default "details" page.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11224778/95158ac6-8d2b-11e5-8415-8880586d3669.png)
**Figure 2:** Scrolled "details" page.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11224815/c08308f0-8d2b-11e5-8c90-61a191e65b59.png)
**Figure 3:** Scrolled "details" page (with footer).

**Comment by lmorchard** [comment]
Definitely a bug... I wonder if it's related to https://github.com/mozilla/idea-town/issues/243

**Comment by lmorchard** [comment]
https://github.com/mozilla/idea-town/commit/c2e0f05bfcbf80af94b7b39fa60dfa0305481c17
