### ISSUE TITLE
Blank tab is displayed after sharing on Facebook from TxP Share page

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot#2593]
**[Affected versions]:**
- Firefox Latest Release 54.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- User is logged on Facebook.

**[Steps to reproduce]:**
1. Open Firefox and go to https://testpilot.stage.mozaws.net/share .
2. Click on the "Facebook Share" button.
3. Click on "Post to Facebook" button from the bottom right corner of the browser window.
4. Observe the behavior of the page.

**[Expected result]:**
- Facebook page should be closed or the user should be redirected to Facebook Home page.

**[Actual result]:**
- The Facebook tab remains opened but blank. In the Browser Console the following error is displayed: `Scripts may not close windows that were not opened by script.`

**[Notes]:**
- This issue is also reproducible on Nightly.
- Below is a screen recording of the issue.

![facebook share tab is not closed](https://user-images.githubusercontent.com/9248513/27918771-98c293f2-6278-11e7-8644-96ebbab7ca42.gif)

**Comment by fzzzy** [comment]
This must be because of the rel=noopener which was added recently. I'm going to say this shouldn't block the release.

**Comment by ghost** [comment]
Can we drop rel=noopener?  @jvehent -- is there a security risk to dropping that?

**Comment by g-k** [comment]
ulfr asked me to comment. 

The risk with dropping rel=noopener is FB could redirect the testpilot page to a phishing site or something similar (kind of like a popunder) https://mathiasbynens.github.io/rel-noopener/

Depending on which FB API we're using, we could set the redirect_uri to return to the Facebook Home page after posting https://developers.facebook.com/docs/sharing/reference/share-dialog or to a testpilot page that closes itself.

**Comment by chuckharmston** [comment]
We'll be removing the share page. Closing.
