### ISSUE TITLE
Update the Test Pilot Newsletter email before graduating Page Shot

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2594]
Currently the Newsletter sign up email contains Page Shot and Min Vid as promoted experiments. Since we are graduating Page Shot next week, we should either remove it from the email, which leaves just Min Vid, or promote other experiments instead.

**Comment by fzzzy** [comment]
This can be fixed without changing the code in the repo, so doesn't block the deploy. It can still be fixed before Page Shot graduates.

**Comment by ghost** [comment]
Jess & Kirby have this change targeted for the 25th

**Comment by ghost** [comment]
This is still on their radar

**Comment by ghost** [comment]
We have a new email that doesn't talk about any specific tests so we shouldn't run into this again
