### ISSUE TITLE
Experiment image and details are not displayed when posting the experiment link on Facebook

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot#2595]
**[Affected versions]:**
- Firefox Latest Release 54.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- User is logged on Facebook.

**[Steps to reproduce]:**
1. Open Firefox and go to TxP Experiments page.
2. Click on an experiment card.
3. Copy the experiment URL ( e.g.: https://testpilot.stage.mozaws.net/experiments/activity-stream . )
4. Go to Facebook and paste the URL into "What's on your mind?" field from the top of the wall page.

**[Expected result]:**
-  Experiment image, experiment title and a short experiment description are displayed inside the post field.

**[Actual result]:**
- Firefox Test Pilot card and image are displayed.

**[Notes]:**
- On Twitter the information from the tweet matches the link of the shared experiment.
- Below is a screen recording of the issue.

![post facebook](https://user-images.githubusercontent.com/9248513/27919840-6f866718-627b-11e7-91c0-4d70820d163b.gif)

**Comment by SoftVision-PaulOiegas** [comment]
Sry Vlad but this was already logged in #2473. My bad... Closing as dupe.
