### ISSUE TITLE
Version detection doesn't work in Nightly

### ISSUE THREAD

**Issue by fmarier** [mozilla/testpilot#2597]
When trying to install an experiment (for example, [containers](https://testpilot.firefox.com/experiments/containers)), I get the following message:

![testpilot-version-detection](https://user-images.githubusercontent.com/167821/27933913-ccf23c4e-6292-11e7-910a-efb498221c9e.png)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @fmarier and thanks for your report! I've tried to reproduce this using latest Nightly build available (2017-07-06) and could not reproduce this. Are you sure you are on a version above Firefox 51? This should only show up if the browser version is indeed lower than required. 
Test Pilot itself needs at least Firefox 50 and current release is at 54.0.1 so this is quite strange. 

If the version is not the problem, could you please try with a new Firefox profile? Maybe it's something related to your browser settings.

![containers](https://user-images.githubusercontent.com/17258026/27947914-76ed398e-6300-11e7-880b-baa6a88457e6.png)

**Comment by fmarier** [comment]
You're right, it works in a new profile.

I have tried to re-add add-ons and other customizations but haven't been able to isolate why it's not working for me in today's Nightly.

It is 100% reproducible in my profile though, preventing me from installing any new test pilot experiments.

**Comment by SoftVision-PaulOiegas** [comment]
Maybe we can debug it. Can you please navigate to "about:support" page, scroll down to "Important Modified Preferences" section and throw here a screenshot of that section? Maybe one of the preferences from your profile is doing that.
Or you can compare that section yourself with the one of a new profile.

**Comment by fmarier** [comment]
It turns out it's because of the `privacy.resistFingerprinting` pref, which lies about my user agent and pretends it is `Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0`.

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, that one surely does the trick. I think I've worked with that pref and it even lies about timezone and local time. If you use also the Snooze Tabs experiment, that pref will affect the return of the snoozed tabs.

**Comment by fmarier** [comment]
For the record, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1393283 for this.
