### ISSUE TITLE
Simplify database config handling in idea_town/settings.py

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#260]
For connecting to the database, our `settings.py` accepts either a `DATABASE_URL` environment variable or a set of AWS `RDS_*` variables. 

[This is a bit convoluted.](https://github.com/mozilla/idea-town/blob/master/idea_town/settings.py#L147) For consistency, it would be simpler to just use the `RDS_*` variables directly. The variables used in `docker-compose` would need a tweak, too.

**Comment by lmorchard** [comment]
At this point, prod & stage environments do not use Elastic Beanstalk. So, it might not be as great an idea to settle on `RDS_*` variables.

@mostlygeek - can you tell me the names of env vars used in prod & stage to configure the database? Don't want to make changes for this issue that end up breaking deployments

**Comment by mostlygeek** [comment]
The env names are whatever the application requires. If you don't like `RDS_*` you can always use `DB_`. The `RDS_*` are just automatic from ElasticBeanstalk and are much more are convenient. 

I suppose if you want ideatown to be easily deployable via ElasticBeanstalk you can keep the `RDS_*` env vars. If you want it to be more generic then switch them to something else. It might be more code, but you can also support both. :)

**Comment by lmorchard** [comment]
Eh, I'll just leave it as-is since everything's working
