### ISSUE TITLE
Different font size used for the buttons on the "Newsletter" sign up dialogs after Test Pilot install

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2600]
**[Affected versions]:**
- Firefox 54.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.stage.mozaws.net page.
2. Click on "Install the Test Pilot Add-on" green button.
3. On the "Welcome to Test Pilot!" dialog, observe the "Sign Up Now" button font size.
4. Enter a valid email in the text box and check the privacy ok checkbox.
5. Click the "Sign Up Now" button.
6. After the "Thanks!" dialog is displayed, observe the "On to the experiments..." button font size.

**[Expected result]:**
- Both the buttons in the dialogs have the same font size.

**[Actual results]:**
- The "On to the experiments..." button font is smaller with 2px than the "Sign Up Now" one.

**[Notes]:**
- Here is a screenshot of the issue:

![newsletter buttons font](https://user-images.githubusercontent.com/17258026/27957196-ffce0966-6325-11e7-84be-8e880791bc2c.png)

**Comment by chuckharmston** [comment]
We've done a redesign since this bug was filed. Closing.
