### ISSUE TITLE
No "HTTPS" protocol required for loading Test Pilot pages in other browsers than Firefox

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2601]
**[Affected versions]:**
- Chrome, Edge, Safari, Opera

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open Chrome/Edge/Safari/Opera browser and navigate to "http://testpilot.dev.mozaws.net" or "http://testpilot.stage.mozaws.net pages.
2. Observe the address bar URL and loaded page content.

**[Expected result]:**
- You are prompted that "Test Pilot must be accessed over HTTPS." and Test Pilot "Homepage" is not loaded.

**[Actual results]:**
- The Test Pilot "Homepage" is loaded without a warning on other browsers than Firefox.  

**[Notes]:**
- Here is a screenshot of the issue:

![no https required](https://user-images.githubusercontent.com/17258026/27958199-8f9e322e-632a-11e7-9547-0afb2398ecbd.png)

**Comment by ghost** [comment]
@SoftVision-PaulOiegas can you still reproduce this?  I tried it with safari and was redirected to https on dev

**Comment by SoftVision-PaulOiegas** [comment]
Nope, all good on Windows 10 and Mac OS 10.11 using several browsers. 👍
