### ISSUE TITLE
Icon in extended tabbar looks ugly

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/testpilot#2602]
The Test-Pilot-Icon in the extended tabbar (the arrow for the expanded list) looks ugly.
![2017-07-07 19_03_38-add-ons manager - nightly build 20170707030206](https://user-images.githubusercontent.com/11881073/27970364-d8904070-634e-11e7-9632-a68f03aef870.png)

**Comment by johngruen** [comment]
ewww

**Comment by SoftVision-PaulOiegas** [comment]
Maybe a dupe of #2585? I know it's on another menu but most likely it has the same root cause.

**Comment by Tobias-B-Besemer** [comment]
Yes, seems to be the same bug! Just a other view of it...

**Comment by nchevobbe** [comment]
Not sure if this is the same issue since I have different result, but still looking not that good :
 
<img width="342" alt="screen shot 2017-08-11 at 15 18 42" src="https://user-images.githubusercontent.com/578107/29214696-a19ea76c-7ea8-11e7-93f4-1ba1928ee615.png">

**Comment by Tobias-B-Besemer** [comment]
And this one...
![2017-08-11 20_11_42-icon in extended tabbar looks ugly issue 2602 mozilla_testpilot - nightly](https://user-images.githubusercontent.com/11881073/29226210-73924dbe-7ed1-11e7-89ff-d6777206ee47.png)

**Comment by Tobias-B-Besemer** [comment]
And 'Testpilot' should IMHO be written with a big 'T'.

**Comment by Tobias-B-Besemer** [comment]
'Test Pilot' is now written in Add-ons with two words, but as tooltip in one word.
![2017-08-12 17_44_19-add-ons manager - nightly](https://user-images.githubusercontent.com/11881073/29242065-45058690-7f86-11e7-8e1e-d00016e87268.png)

**Comment by lmorchard** [comment]
https://github.com/mozilla/testpilot/commit/619fb50bed94e9d1fe156384423d0ca92967a408

**Comment by Tobias-B-Besemer** [comment]
What's about the wrong tooltip ???

**Comment by lmorchard** [comment]
Got a fix for that too, I think https://github.com/mozilla/testpilot/pull/2794

**Comment by SoftVision-PaulOiegas** [comment]
The ugly button icon has been fixed for the "Customize" menu, but I don't think it's ok in the "Overflow" menu. The icon is black'ish while in toolbar and "Customize" menu and changes to white with a drop of shadow in the "Overflow" menu. 

Reopening this to clarify.
![overflow menu](https://user-images.githubusercontent.com/17258026/29677847-1d10e390-8905-11e7-951f-cd2471b5b301.png)

**Comment by uniquePWD** [comment]
Just came to report this.
