### ISSUE TITLE
Experiment graduation message is not removed from experiments details page when changing system date to a past date

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2606]
**[Notes]:**
- This is an edge case that probably won't happen, but I chose to log it because when we previously graduated experiments, this was working fine.

**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- At least one experiment is set to graduate soon.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. From the system settings, move the system date to be at least 8 days before the graduation time.
3. Refresh the Test Pilot Homepage and observe the graduation message behavior.
4. Click on one of the graduating experiments cards observe the graduation message behavior.

**[Expected result]:**
- Graduation messages are no longer displayed on the experiment card and experiment details page.

**[Actual results]:**
- Step 3: The Graduation message is correctly removed from the experiment card.
- Step 4: The graduation message is still displayed on the experiment details page. 

**[Additional Notes]:**
- Even if I moved the date with more than 1 month before, the message was still displayed on the page.
- Here is a screenshot of the issue:

![screen shot 2017-06-25 at 15 59 28](https://user-images.githubusercontent.com/17258026/28076734-4170b3ce-6668-11e7-983b-041b0e647c40.png)

**Comment by pdehaan** [comment]
My **guess** is that this is due to #2581; _"Ensure page content even without grad report"_, and we're only showing this UI since we don't have graduation reports for the newly graduating experiments yet.

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, could be. We'll double check after we have the grad reports implemented.

**Comment by ghost** [comment]
Thanks, but we've decided not to focus on this.
