### ISSUE TITLE
[Enhancement] Optimize experiments details page elements to reduce the unneeded empty space

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2607]
**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on Snooze Tabs or Containers experiment cards.
3. Scroll down the page while observing how page elements are arranged.

**[Expected result]:**
- Page elements are arranged in such a way that every available space is covered by details about the experiment.

**[Actual results]:**
- Both experiments have large chunks of empty space under the experiment description images.

**[Notes]:**
- This is usually caused by the left side page elements that take more space than the images and experiment descriptions. 
- This occurs for multiple experiments, but I only mentioned about the will still be active after graduation.
- Here is a screen recording of the issue: https://goo.gl/dCUJJQ.

![empty space](https://user-images.githubusercontent.com/17258026/28077899-c277f0d8-666b-11e7-8174-34612fd1d4cd.png)

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas I think we are going to switch back to a world where the page looks the same regardless of installl state

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Well that will help, it looks a bit better when Test Pilot is installed. But you still got a blank space and that could enlarge if any new details are added on the left side of the page (eg: like contributors, or a longer privacy section).

**Comment by ghost** [comment]
John says he fixed the view to be a bit more balanced.

**Comment by SoftVision-PaulOiegas** [comment]
Seems so for the current active experiments. But when you look at Send and Notes that we'll be launching soon... Notes is even worse due to long contributors list and only one feature screenshot on the right side.

![send notes](https://user-images.githubusercontent.com/17258026/28776202-46cd0ade-75fe-11e7-8558-f5f228d94254.png)
