### ISSUE TITLE
Containers wrongly installs together with Test Pilot and works on Fx 52.0.2 when minimum version was set to Fx 53

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2610]
**[Notes]:**
- The Containers add-on is not displayed as unsupported on Firefox 52.0.2, but it is displayed as so and disabled in Fx 50.0 for example.
- The "New Tab" button hover menu is still working and opening container tabs, but the containers toolbar doorhanger is not visible.
- Version limitation was set in #2603.

**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Old Firefox 52.0.2 or lower was installed / extracted on the system. 

**[Steps to reproduce]:**
1. Open the old browser version with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on the "Containers" experiment card.
3. Click on "Install Test Pilot & Enable Containers" button.
4. Observe the page behavior.

**[Expected result]:**
- Test Pilot add-on is successfully installed (requires Fx50) but the Containers experiment is not since it requires at least Firefox 53. 

**[Actual results]:**
- Both Test Pilot and Containers add-ons are installed and working (Containers partially).

**[Additional Notes]:**
- Here is a screen recording of the issue: https://goo.gl/1dSZwR
- Here is a console screenshot:

![containers install console](https://user-images.githubusercontent.com/17258026/28165976-cd875382-67de-11e7-88eb-8c6e5bdf6d14.png)

**Comment by ghost** [comment]
This is a containers bug.  I filed https://github.com/mozilla/testpilot-containers/issues/692
