### ISSUE TITLE
Localize the <title> with fluent-react

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2612]
The fluent-react branch is about to land, but I forgot to localize the title properly. Since that other pr is so big, I'd like to do this as another issue, in this same sprint.

**Comment by fzzzy** [comment]
This actually looks like it will be quite difficult with things set up the way they are currently. However, it will be quite easy once we move the locale string into the beginning of the url and statically render different language pages at build time. So, let's wait until after we do that to do this.

**Comment by fzzzy** [comment]
Jared pointed me at this which can be used to fix this bug with the way the architecture is now:

https://github.com/projectfluent/fluent.js/wiki/withLocalization

However I think it would be best to just wait until the locale is in the url.

**Comment by chuckharmston** [comment]
This is still hard to do, but may be easier using something like [`react-helmet`](https://github.com/nfl/react-helmet). Let's investigate that.

**Comment by meandavejustice** [comment]
fixed in https://github.com/mozilla/testpilot/commit/3c05f7e5bb1d6da487dcd87dd45e7d97950cbd7a#diff-54e5bb01a3b713a3a8ba8b1d70328870

**Comment by dannycoates** [comment]
Unfortunately fluent-react doesn't play nice with react-helmet. I suggest WONTFIX
