### ISSUE TITLE
Tab Center is gone?!?

### ISSUE THREAD

**Issue by nosefouratyou** [mozilla/testpilot#2614]
I'm using Tab Center right now and I love it. Is there a way for this to still be available? I can't imagine why this was discontinued. If it's gone for good, could someone point me at the source code? Thanks!

**Comment by lmorchard** [comment]
Tab Center is a Test Pilot experiment - and like all Test Pilot experiments, it runs for a limited time. That is, Test Pilot experiments are not intended to be or developed as permanently available features. It might show up again as a real feature in Firefox, but for now the Tab Center experiment has ended. You can follow up for more info at these places:

* Source code - https://github.com/bwinton/TabCenter
* Discussions - https://discourse.mozilla-community.org/c/test-pilot/tab-center
* Retired experiment page (report coming soon) - https://testpilot.firefox.com/experiments/tab-center

**Comment by lmorchard** [comment]
To be more specific, though, I see there's some explanation of why Tab Center in particular is coming to a close right now [in the discussion forum](https://discourse.mozilla-community.org/t/whats-all-this-about-sunsetting-tab-center/15999/7).

**Comment by SoftVision-PaulOiegas** [comment]
@nosefouratyou Until a future decision is taken with Tab Center, you can try to use a webextension based on Tab Center. It's not as good, but it could be if you give it some time.
https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/?src=search
