### ISSUE TITLE
Experiment cards all share same "show-detail" id

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2616]
[/frontend/src/app/components/ExperimentRowCard.js:43](https://github.com/mozilla/testpilot/blob/ecc0f788c1ade754c85913a971d26ff842a90ab3/frontend/src/app/components/ExperimentRowCard.js#L43) says:

```js
return (
--
  | <a id="show-detail" href={`/experiments/${slug}`} onClick={() => this.openDetailPage()}
  | className={classnames('experiment-summary', {
  | enabled,
  | 'just-launched': this.justLaunched(),
  | 'just-updated': this.justUpdated(),
  | 'has-addon': hasAddon
  | })}
  | >
```

Unfortunately, that means when you do a view-source or inspect element on the home page, all the experiment cards share the same `show-detail` id:

<img width="817" alt="firefox_test_pilot" src="https://user-images.githubusercontent.com/557895/28225866-ec8d169a-6888-11e7-8290-b7801e766d28.png">

... And the past experiments id's too:

<img width="777" alt="firefox_test_pilot" src="https://user-images.githubusercontent.com/557895/28226022-6e39a794-6889-11e7-883f-4121744f3104.png">

**Comment by johngruen** [comment]
@pdehaan yeah i noticed this too recently
