### ISSUE TITLE
ISSUE :: On mouse over at add new tab

### ISSUE THREAD

**Issue by sujeet-kumar-buzyears** [mozilla/testpilot#2618]
Please go through the image.
As per your diagram 1
![firefox test pilot _containers_](https://user-images.githubusercontent.com/29161189/28238355-92a58418-696f-11e7-97dd-9e754c7cbcbe.png)

My computer snapshot:
![screenshot from 2017 07 15 15 12 43](https://user-images.githubusercontent.com/29161189/28238429-c6345a88-6970-11e7-97e3-6ee222070eac.png)

Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Containers:           https://github.com/mozilla/testpilot-containers/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Pulse:                https://github.com/mozilla/pulse/issues/new
- Snooze Tabs:          https://github.com/bwinton/SnoozeTabs/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new

**Comment by SoftVision-PaulOiegas** [comment]
@sujeet-kumar-buzyears I think the functionality was changed by the Containers development team. Right now you need to long click the new tab "+" button in order to have that menu displayed.

Details can be found in the next issue:
https://github.com/mozilla/testpilot-containers/issues/674
