### ISSUE TITLE
Truncate long experiment names and descriptions

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#262]
It's currently a bit too easy to break the layout if you specify an offensively long experiment **title** (or **description**):

http://idea-town-dev.elasticbeanstalk.com/experiments/experiment-third-which-has-longer-title

![idea_town](https://cloud.githubusercontent.com/assets/557895/11226522/5c12dcf6-8d35-11e5-9766-5cc2a36fe4e5.png)
**Figure 1:** long **title** in the details page. This is super edge case for sure, but you can see how easy it is to overflow that "Enable {{experiment.name}}" button label, which is a lot more likely.

---

![idea_town](https://cloud.githubusercontent.com/assets/557895/11226593/d1b785ec-8d35-11e5-8f6d-5979e18fca34.png)
**Figure 2:** The home page with the absurdly long description. We should probably trim to the first _X_ characters on this page (and make sure we strip out any potential HTML tags).

**Comment by pdehaan** [comment]
Feel free to yell at me for being lazy and combining similar issues in the same bug. I can break this into 2 separate bugs if you want (one for long titles, another for long descriptions).

**Comment by johngruen** [comment]
@lmorchard @pdehaan I'd actually prefer we enforced a cap on string length on the django side of things. We're not localizing any time soon so I don't view this as beng totally pressing.

**Comment by lmorchard** [comment]
Let's keep this open but kick it out of the Mozlando milestone, for now

**Comment by meandavejustice** [comment]
Do we want this in the `internal-release` tag?

**Comment by lmorchard** [comment]
Maybe implement validation rules, but at least try to keep the names reasonably short as human content editors / gatekeepers of the site. This isn't user-generated content per se, so the Idea Town Authorities have some say over the content (Maybe needs more thinking about this)

**Comment by lmorchard** [comment]
Would #301 + manual editorial control possibly resolve or mitigate this issue?
