### ISSUE TITLE
Get Test Pilot add-on signed as a Mozilla Extension

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#2627]
All the extensions are going through our new signing pipeline (and being hosted on testpilot.f.c/files/) which means they are good to go for when non-webextension restrictions hit Firefox.

However, Test Pilot still does its own thing (signing on AMO?  I thought that was disabled.  Maybe that's only for new add-ons).  We should have Test Pilot run through the same pipeline as everything else.

These days it's a matter of supporting `npm run package` (docs being updated in #2615)

**Comment by lmorchard** [comment]
And now after saying `npm run package` was fine in #2615, I just remembered what the gotcha was here: 

We have two separate `package.json` files - one in the repo root for the website, and one under `addon/` for the add-on. Separate sets of NPM scripts and dependencies. (This is what Issue #2113 was about, but we punted on it.) So, just running `npm install && npm run package` in the root directory won't work - because that hits the website `package.json`. 

Maybe we can stick something like `"package": "cd addon && npm install && npm run package"` in the website `package.json`? That will still mean Jenkins installs all the website dependencies and *then* installs the separate set of add-on dependencies. 

Or, maybe we can make a special case where Jenkins does a `cd addon` first if it detects that an `addon` directory exists?

If we supported `bin/build-addon.sh` in Jenkins, this might be simpler to abstract away

**Comment by lmorchard** [comment]
Another thought: If we change the URL for the main Test Pilot add-on along with Mozilla Extension signing - and I'm assuming we will - [we'll have to change the URL in the frontend code for installation](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/lib/addon.js#L18).

**Comment by lmorchard** [comment]
Not sure I want to call it a complete "fix" for this issue, but we just merged PR #2652 - which implements `npm run package` in the root directory of the Test Pilot repo. That does this:
```
cd addon && npm install && npm run package && cp addon.xpi ..
```
Would be nice to see if jenkins could do that itself if an `addon` directory is found. But, in the meantime, this *should* at least work and result in a built addon.

**Comment by ghost** [comment]
thanks @lmorchard 

@relud - please set test pilot up on /files/ so we can start QAing versions that go there

**Comment by relud** [comment]
another thing: the addon version is extracted from the package.json in the root of the repository. will that be acceptable here, or do we need to implement getting version and addon name from `addon.xpi` first?

**Comment by relud** [comment]
another other thing: right now mozillaextension addons are only built for prod. If we continue that pattern here, this means that deploying stage would not update the addon

**Comment by ghost** [comment]
Good point on package.json.  I think we should write that patch to extract from addon.xpi.  (update: talked on IRC, we're going to do that)

As for building for prod...  Since we wouldn't be deploying in the same bundle as the code anymore, I don't think we need to build for stage.  @SoftVision-PaulOiegas might have an opinion though?

**Comment by lmorchard** [comment]
> another thing: the addon version is extracted from the package.json in the root of the repository. will that be acceptable here, or do we need to implement getting version and addon name from addon.xpi first?

Yeah, needs to be taken from the `.xpi` - just like the Test Pilot addon lives in `addon/` with its own `package.json`, it has a totally separate versioning series from the `package.json` in the repo root

**Comment by SoftVision-PaulOiegas** [comment]
> As for building for prod... Since we wouldn't be deploying in the same bundle as the code anymore, I don't think we need to build for stage. @SoftVision-PaulOiegas might have an opinion though?

@wresuolc Let me see if I get this right. You are saying that this change won't affect the code so it's no point in testing this on stage, it would be enough to test dev and then uplift to production?
If this is it, then yes, I agree. If not, please give me more details to fully understand this.

**Comment by ghost** [comment]
I mean we won't have add-on versions built for stage, and that's fine.  I think we're agreeing.

**Comment by relud** [comment]
version and id will be taken from the xpi for all future builds

**Comment by SoftVision-PaulOiegas** [comment]
> I mean we won't have add-on versions built for stage, and that's fine. I think we're agreeing.

@wresuolc we won't have an add-on for stage like always, or just for this stage?
I'm asking because if we won't be able to install the add-on on Stage after 57, this will end bad eventually. We are running our Full testing suite on stage deploys, and if we can't install Test Pilot add-on, we won't be able to test anything except the homepage and other pages that are accessible without Test Pilot add-on installed.

However, this will only happen when 57 will hit the Release version. We'll still be able to test stage for two more cycles until that happens because we are using latest Firefox release for stage and production testing.

**Comment by lmorchard** [comment]
FWIW, I've got a few comments on add-on testing [over in this issue on turning off signing in CircleCI](https://github.com/mozilla/testpilot/issues/2651) which I think relates to add-on builds for stage (and dev). It'll be a problem we need to work out

**Comment by relud** [comment]
Pushing to the production-static branch will now trigger building the addon with mozilla extension signing. I can also manually trigger builds of other branches while we're getting the kinks worked out.

**Comment by ghost** [comment]
Thanks!  I think these are the remaining steps:

- [x] QA the newly signed Test Pilot add-on @  https://testpilot.firefox.com/files/@testpilot-addon/latest
- [x] Update updateURL and updateLink with the new URLs (https://github.com/mozilla/testpilot/blob/master/addon/package.json#L9)
- [ ] Manually modify https://testpilot.firefox.com/static/addon/update.rdf to point to the new add-on location
- [ ] Change https://testpilot.firefox.com/static/addon/latest to point to the new /latest/ location
- [x] Increment add-on version before release

Step 2 will fix install for any new users.  Step 3 will upgrade existing users.  I'm not sure if Step 4 matters.

**Comment by relud** [comment]
the new `latest` location is https://testpilot.firefox.com/files/@testpilot-addon/latest

**Comment by relud** [comment]
and the new addon url is https://testpilot.firefox.com/files/@testpilot-addon/signed-addon.xpi

**Comment by ghost** [comment]
and https://testpilot.firefox.com/files/@testpilot-addon/updates.json is the new updates location

**Comment by fzzzy** [comment]
Ok, I verified that both https://testpilot.firefox.com/files/@testpilot-addon/latest and https://testpilot.firefox.com/files/@testpilot-addon/signed-addon.xpi work properly with extensions.legacy.enabled set to false. Who is going to do the remaining steps? I think they are safe to do at any time since the new addon is identical to the old one except for the signing key.

**Comment by relud** [comment]
looks like manually changing /static/addon/latest to point to the new latest location will require that https://github.com/mozilla/testpilot/blob/master/bin/deploy.sh#L171-L177 be removed before the next push to production-static, or it won't persist

**Comment by relud** [comment]
probably also need to remove these so we don't generate an old addon on the next build:

- [x] https://github.com/mozilla/testpilot/blob/master/bin/deploy.sh#L94-L114
- [x] https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/testpilot/pipeline-prod.groovy#L76-L79
- [x] https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/testpilot/pipeline-stage.groovy#L79-L82

**Comment by relud** [comment]
how long are we going to preserve https://testpilot.firefox.com/static/addon/latest because if it's for more than one addon release then I'll need to modify the testpilot-prod job to wait for the addon to deploy at the end and then copy the `latest` file from the new location to the old

**Comment by lmorchard** [comment]
Maybe not *quite* as urgent as removing the add-on deployment lines from `bin/deploy.sh`, but we should also very quickly follow up with removing the wasted work of auto-signing via AMO in CircleCI (#2651)

**Comment by ghost** [comment]
Thanks for looking at this @lmorchard .  These are the new URLs for addon/package.json:
```
-  "updateURL": "https://testpilot.firefox.com/static/addon/update.rdf",
-  "updateLink": "https://testpilot.firefox.com/static/addon/latest",
+  "updateURL": "https://testpilot.firefox.com/files/@testpilot-addon/updates.json",
+  "updateLink": "https://testpilot.firefox.com/files/@testpilot-addon/latest",
```

**Comment by fzzzy** [comment]
I checked all the checkboxes I could in this bug, can someone make sure the checkboxes that aren't checked get checked?

**Comment by relud** [comment]
> Change https://testpilot.firefox.com/static/addon/latest to point to the new /latest/ location

I can do this manually if we are ready, or it will be updated in the next prod deployment

> Manually modify https://testpilot.firefox.com/static/addon/update.rdf to point to the new add-on location

I believe that needs to be updated manually, when clouserw has a manually edited rdf for me to upload. I see what appears to be an addon version number in that url, so presumably this url will stop working next time the addon version is bumped?

**Comment by ghost** [comment]
I made a new RDF, but also got a new idea.  Let's just 301  https://testpilot.firefox.com/static/addon/update.rdf to https://testpilot.firefox.com/files/@testpilot-addon/updates.json 

I think that will keep updates working as expected.  @relud great idea or what?

**Comment by lmorchard** [comment]
> I think that will keep updates working as expected

Hmm, the RDF to JSON content-type switch seems troublesome... not sure when Firefox switched over to that, version-wise. Will that cause an issue?

**Comment by relud** [comment]
if that works, sounds great

**Comment by ghost** [comment]
@lmorchard pretty sure it's way before any version we still support.  I think it'll work.  If GA doesn't show a rapid drop in old test pilot add-on versions, we're go back to the manually updated RDF plan.

@relud - can you add a redirect on the server?

**Comment by relud** [comment]
redirect added

**Comment by lmorchard** [comment]
We deployed this and I think it's all working
