### ISSUE TITLE
Navigation changes too much when scrolling details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#263]
### Before scroll:

![idea_town](https://cloud.githubusercontent.com/assets/557895/11226843/65c477e4-8d37-11e5-85c1-12c60cd7bd17.png)

Note that we have the "[...]" button in the blue bar nav (which includes **Tour Idea Town**, **Idea Town Wiki**, **File an Issue**, and **Logout** subnav), and then we have a green **[Give Feedback]** button and gray **[Disable _{{experiment.name}}_]** button.

---
### After scroll:

![idea_town](https://cloud.githubusercontent.com/assets/557895/11226858/7f4512b4-8d37-11e5-9137-2f295c5d0259.png)

After scrolling, the "[...]" navigation disappears, as well as the **[Give Feedback]** button. The **[Disable _{{experiment.name}}_]** button also switches from gray to green.

**Comment by johngruen** [comment]
@pdehaan, I will fix. Just you wait.

**Comment by johngruen** [comment]
@meandavejustice hey i just pushed a branch demonstrating the intended behavior that's written in a way that's totally unmergable.

**Comment by meandavejustice** [comment]
@johngruen we don't want the sticky header anymore?(going by your demo)

**Comment by johngruen** [comment]
@meandavejustice so i'm just making the experiment header sticky on scroll, pull it down and check out the interaction, you might have to change the value on that global setTimeout

**Comment by meandavejustice** [comment]
@johngruen Ahh, the scroll isn't work for me, there is an error `TypeError: detailsWrapper.offset(...) is undefined`
