### ISSUE TITLE
Collisions in parallel dev deployments sometimes break the site (loader never stops spinning)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2634]
**[Notes]:**
- Might be again something that will resolve by itself, but better safe than sorry. 

**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the Firefox with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the page behavior.

**[Expected result]:**
- Test Pilot dev server Homepage is correctly loaded.

**[Actual results]:**
- The page blue background and loading animation appear but the page remains in infinite loading.
 
**[Additional Notes]:**
- Here is a console screenshot:

![dev errors for not loading](https://user-images.githubusercontent.com/17258026/28462840-c9e8e068-6e25-11e7-9169-116c93cc6230.png)

**Comment by johngruen** [comment]
Local is failing too. Oddly i checked out the current stage branch and it also fails locally.

**Comment by fzzzy** [comment]
MIME type mismatch? I have never seen that...

**Comment by fzzzy** [comment]
Do we have any idea what happened here?

**Comment by SoftVision-PaulOiegas** [comment]
Tried to test today something on dev and this is still reproducing on both Nightly and Release with the same errors. Why it has been closed?

**Comment by fzzzy** [comment]
I think John thought it was fixed... but apparently not...

**Comment by lmorchard** [comment]
Poked at this a bit & reproduced. The "MIME type mismatch" error is technically correct, but misleading. 

Looking at the actual URL of the JS bundle referenced by the `<script>` tag - the response is a 403 status with the text/html 404 page. Looking at the S3 bucket in the AWS console, there's an `app.{hash}.js` bundle in there - but it's a different hash than what `index.html` points to.

A guess off the top of my head is that we have competing deployment happening and some (many?) of them are clobbering each other. Every test run on master branch results in a deployment. That includes Pontoon commits - of which we have many sometimes in close succession. One deployment might result in an `index.html` pointing to the JS bundle it was built alongside - meanwhile another simultaneous deployment deletes that JS bundle and uploads a different one.

Could skip deployment on pontoon commits, but then we wouldn't see the results of l10n work.

**Comment by fzzzy** [comment]
So that would explain why this is sometimes fixed and sometimes not. If a commit causes a deploy without another commit interfering with it, then it is fixed. If two commits cause two deploys and they interfere, then the problem appears.

**Comment by lmorchard** [comment]
Tweaked the title to reflect what I think we've figured out as the underlying issue

**Comment by lmorchard** [comment]
Just so I don't forget - this looks like an interesting way to make a CircleCI deployment wait until there are no other deployment runs going for a given branch:

https://discuss.circleci.com/t/serializing-deployments/153
https://github.com/bellkev/circle-lock-test
