### ISSUE TITLE
The whole privacy section from newsletter sign up pop up / form is considered action radius for its checkbox

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2640]
**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the Firefox with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on the "Install Test Pilot Add-on" button in order to install the add-on.
3. After the installation is performed click on the welcome pop up text box.
4. Enter at least one character to have the privacy checkbox to appear.
5. Click a few times on the area right to the text box and over the privacy message.

**[Expected result]:**
- Nothing happens.

**[Actual results]:**
- The privacy checkbox is wrongly checked when clicking the privacy section area.

**[Notes]:**
- This also occurs on the bottom page Newsletter sign up form.
- Here is a screen recording of the issue: https://goo.gl/rY67RD.

**Comment by johngruen** [comment]
This is acutally on purpose. we're using a `for=` attr in the label to bind clicks to the check box.

**Comment by SoftVision-PaulOiegas** [comment]
👍 the issue was more to make sure that this was intended.
