### ISSUE TITLE
Flip all our add-ons over to Mozilla Extensions

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#2643]
We've got add-ons getting signed with the new Mozilla Extension certs and being uploaded to s3 in parallel to our other signing pipeline.  They can be accessed by adding mozillaextension to the URL.  For example:

> https://testpilot.firefox.com/files/@notes/latest

becomes

> https://testpilot.firefox.com/files/mozillaextension/@notes/latest

That'll currently work for @min-vid, @notes, @speak-to-me, and @testpilot-containers.  We'll need to push a new version of snooze tabs to get it to use the new signing pipeline.

The actual work of this is (I assume) pretty easy, relud just changes the path in the pipeline to put the new files where the existing files are going.  However, before we do this we want to make sure everything works as expected.  So...

@SoftVision-CosminMuntean @SoftVision-PaulOiegas -- I know you did some good testing on this already.  Are you comfortable swapping out these .xpi files or do you want to test more?  **Testing the newly launching experiments and any compatibility testing between the new experiments is a higher priority than this for now.**

@relud -- heads up on the plan here ^.  Once we're ready I'll bug you more.  If I'm wrong about just changing the path please let me know.

@lmorchard -- not critical to do yet, but if you get a chance could you bump the version of snoozetabs and push so we get a new signed version?

The deadline for all of this is **August 8th** when 57 goes to Nightly and it stops running anything except Mozilla and Web Extensions.  Cheers!

**Comment by relud** [comment]
lgtm. Changing the path will cause new extensions to go to the right place, but there's a little more work. After that we'll need to either release updates to all the add-ons, or I will need to copy everything and modify the location tag on the 'latest' files. The latter is fine, and probably less effort overall. Also when I change the path I will need to simultaneously disable the old signing, so they don't collide. Alternately I could change the path the old signing, but I'm not sure if that would be helpful/desirable.

**Comment by lmorchard** [comment]
I think we've got Snooze Tabs ready for the switch over

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc Sorry for the delayed response, this issue somehow got skipped. 

I think the testing done was enough for now. We'll probably need to test again after Nightly 57 will be released, to be sure that nothing has changed from the testing we performed on Nightly 56. But I think we can do the switch.  
This will also help us when we'll retest on 57, since we'll do the testing straight from test Pilot instead of changing URL's.

Thanks!

**Comment by SoftVision-PaulOiegas** [comment]
One thing though. Will all the experiments versions be bumped? We should assure that the users are receiving the ones with nu signatures as updates.

**Comment by ghost** [comment]
Yeah, we can bump the experiment versions.  @relud mentioned just copying files, but I think it's safer to do a new version.  So....:

1) [@relud] No-op the old signing path
2) [@relud] Change the path for the new signing to be in the correct location
3) [@clouserw] Deploy new versions for each add-on.  This can be done one-at-a-time if QA would prefer.
4) [@clouserw] Remove the old build-addon.sh scripts from the repositories

Aside from @relud's steps, these don't need to be done right after the other, and I can do the new versions any day.  So, @relud -- this is over to you.  Let me know when you're ready for new versions.

**Comment by relud** [comment]
1 and 2 are complete

**Comment by ghost** [comment]
- [x] snoozetabs -- done Jul 26
- [x] containers -- https://github.com/mozilla/testpilot-containers/issues/693 -- done Jul 31
- [x] min vid -- done Jul 31
- [x] notes -- done Jul 28
- [x] voice fill -- done jul 28

**Comment by ghost** [comment]
Thanks all

**Comment by SoftVision-PaulOiegas** [comment]
I can confirm that all the above experiments add-ons from stage server remain enabled after flipping the "extensions.legacy.enabled" pref to "false" (restriction active). Good job guys! 👍 

![legacy ok](https://user-images.githubusercontent.com/17258026/28824828-8cadc434-76cc-11e7-9739-275414f5d995.png)
