### ISSUE TITLE
ideatown.firefox vs ideatown.mozilla

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#265]
My eyes randomly tripped over this, but I wanted to file before I pushed it out of my mind...

| LOCATION | URL |
| --- | --- |
| [/addon/package.json:36](https://github.com/mozilla/idea-town/blob/4b60baf1f25c9f6e6fb0b462faa977f77248bdaa/addon/package.json#L36) | `"https://ideatown.firefox.com"` |
| [/addon/package.json:50](https://github.com/mozilla/idea-town/blob/4b60baf1f25c9f6e6fb0b462faa977f77248bdaa/addon/package.json#L50) | `"https://ideatown.firefox.com"` |
| [/addon/dev-prefs.json:3](https://github.com/mozilla/idea-town/blob/4b60baf1f25c9f6e6fb0b462faa977f77248bdaa/addon/dev-prefs.json#L3) | `https://ideatown.firefox.com/*` |
| [/addon-api/package.json:37-38](https://github.com/mozilla/idea-town/blob/b5ebd03f1da4d667be80691195ff147b0c124772/addon-api/package.json#L37-L38) | `"https://ideatown.firefox.com"` |
| [/.ebextensions/00-environment.config-dist:22](https://github.com/mozilla/idea-town/blob/de207eb207d8a3a1d4ddf04d7978602c4010b194/.ebextensions/00-environment.config-dist#L22) | `ideatown.mozilla.com` |

Not sure if that last one matters (ideatown.mozilla.com) or is just a placeholder. But it seemed to be inconsistent with the other references to the final Idea Town url.

**Comment by lmorchard** [comment]
Yeah, just a placeholder. The `-dist` file should be copied to a non-`-dist` file and all the settings changed to final production values by ops. Still probably worth making even this placeholder consistent with intended prod values where possible.
