### ISSUE TITLE
Failure in build-{addon,frontend}.sh silently ignored in CircleCI

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2650]
Just saw [build 4952](https://circleci.com/gh/mozilla/testpilot/4952?utm_campaign=chatroom-integration&amp;utm_medium=referral&amp;utm_source=irc) fail - but only in the deployment step because `addon.xpi` was missing. The real failure was that `build-addon.sh` failed in its call out to AMO for signing.

CircleCI should have failed the build back in *that* earlier step.

**Comment by lmorchard** [comment]
Also worth noting that we've had `build-frontend.sh` fail and get ignored. So, this could be a common issue that needs going over in all the circleci scripts

**Comment by ghost** [comment]
We can get rid of build-addon.sh completely once we are on the new signing pipeline

**Comment by lmorchard** [comment]
We can get rid of build-addon.sh, but I would like to see the failures ignored in other build scripts checked out too (like frontend)

**Comment by chuckharmston** [comment]
This isn't relevant anymore, closing.
