### ISSUE TITLE
Experiment installation is wrongly performed when the "Enable <experiment_name>" button is scroll clicked

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2656]
**[Notes]:**
- This also occurs for the "Disable <experiment_name>", "Your privacy", "Settings" and "View Past Experiments / Hide Past Experiments" buttons. Hope I checked all of them.

**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the Firefox with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on "Install Test Pilot Add-on".
3. After the install was performed, click on one of the active experiments cards.
4. Hover over the top right "Enable <experiment_name>" button and scroll click from mouse.
5. Observe the page behavior.

**[Expected result]:**
- Page auto scroll is started.

**[Actual results]:**
- The experiment installation is wrongly performed performed.

**Comment by chuckharmston** [comment]
Since we [can't detect middle clicks](https://github.com/mozilla/testpilot/issues/3309#issuecomment-363119326), this bug isn't fixable. Closing.
