### ISSUE TITLE
[l10n] Remove content from old experiments

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2657]
A contributor starting to localizing the website correctly noted that there's a ton of obsolete content in experiments.ftl

Example: AS, cliqz, nomore404, paheshot, etc.

Why can't we get rid of this content?

CC @rprys

**Comment by fzzzy** [comment]
We still show all the old experiment content, under "view past experiments". It seems fine if new languages don't want to do the work to localize old experiments though.

**Comment by flodolo** [comment]
Good point, I completely missed that we still have that content. Is the plan to keep them on the website for the time being?

**Comment by flodolo** [comment]
Correction: we still have the experiments, but there's a lot of content not available anymore (tour, privacy notes).
https://testpilot.firefox.com/experiments/activity-stream

So, there's a lot of content that could be removed when an experiment retires.

**Comment by fzzzy** [comment]
Good call on removing content that actually isn't used any more. Let's do this.

**Comment by flodolo** [comment]
Any chance of getting resources on this? I keep getting this question from locales that want to localize Test Pilot.

**Comment by fzzzy** [comment]
I'll do this now.
