### ISSUE TITLE
Add platforms to past TestPilot experiments

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2659]
With the latest batch of experiments, we got this business:

```yaml
platforms: ['addon']
```

We may want to backport those changes to the previous experiments as well, for visual consistency.

<img width="1440" alt="firefox_test_pilot" src="https://user-images.githubusercontent.com/557895/28598851-4500a226-715b-11e7-8e21-b78e1238e7c4.png">

**Comment by johngruen** [comment]
Yeah, this is probably a good idea

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Was just asking about this on IRC. Shouldn't we add those before the prod release planned on Monday?
