### ISSUE TITLE
Add new experiments to the "New Bug" issue template

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2660]
[/.github/ISSUE_TEMPLATE.md](https://github.com/mozilla/testpilot/blob/master/.github/ISSUE_TEMPLATE.md) currently says:

```
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues. If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:      https://github.com/mozilla/activity-stream/issues/new
- Containers:           https://github.com/mozilla/testpilot-containers/issues/new
- Min Vid:              https://github.com/meandavejustice/min-vid/issues/new
- Page Shot:            https://github.com/mozilla-services/pageshot/issues/new
- Pulse:                https://github.com/mozilla/pulse/issues/new
- Snooze Tabs:          https://github.com/bwinton/SnoozeTabs/issues/new
- Tab Center:           https://github.com/bwinton/VerticalTabs/issues/new
```

I'd argue that we add the 3 new ones and remove the retired ones.

**Comment by chuckharmston** [comment]
I'd argue that we should remove it entirely in favor of this banner:

<img width="1006" alt="screen shot 2017-07-25 at 19 00 11" src="https://user-images.githubusercontent.com/23885/28599916-a2c37676-716b-11e7-93bc-762ac8cfc707.png">

Because half our community-filed bugs end up being just the text of that template.

**Comment by b4handjr** [comment]
I'm with Chuck.

**Comment by pdehaan** [comment]
I'm with Benny.

**Comment by chuckharmston** [comment]
I'm with Peter.

**Comment by lmorchard** [comment]
I'm with Benny, Peter, and Chuck

**Comment by pdehaan** [comment]
Read it and weep: #2671 😭
