### ISSUE TITLE
YouTube video being blocked by CSP on dev

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2661]
I think there is some ghost YouTube iframe or something that is occupying a bunch of space and making things look frightfully unbalanced:

<img width="1016" alt="firefox_test_pilot_-_voice_fill" src="https://user-images.githubusercontent.com/557895/28599820-78b4267c-7162-11e7-87b5-0e5e062b46cc.png">

**Comment by chuckharmston** [comment]
Yeah, that's a placeholder for a YouTube video that John is working on. This is definitely safe to close.

**Comment by pdehaan** [comment]
<img width="1439" alt="item-0_and_airportextra_and_item-0" src="https://user-images.githubusercontent.com/557895/28599950-982c5f3c-7163-11e7-8ab4-dca912d1419e.png">

**Comment by pdehaan** [comment]
Also giving me a CSP error:

> "Content Security Policy: The page’s settings blocked the loading of a resource at https://www.youtube.com/embed/wjvM18UWMmM (“default-src https://testpilot.dev.mozaws.net”)."

<img width="1430" alt="firefox_test_pilot_-_voice_fill" src="https://user-images.githubusercontent.com/557895/28599982-c33c2d56-7163-11e7-86ec-709489f25f0a.png">

**Comment by fzzzy** [comment]
This is only on dev, because dev uses a non-standard deployment configuration.
