### ISSUE TITLE
Dev server is not loading

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2662]
https://testpilot.dev.mozaws.net/ is stuck on a waiting loop.

**Comment by pdehaan** [comment]
Same for me. I seem to be collecting some 403s for a few *.js files:

<img width="1439" alt="firefox_test_pilot" src="https://user-images.githubusercontent.com/557895/28608297-b6097c3e-7194-11e7-8d07-c7081e0716c5.png">

**Comment by johngruen** [comment]
@flodolo this seems to be an intermittent problem due to pontoon-triggered rebuilds.

**Comment by johngruen** [comment]
Might have to do with this? #2631

**Comment by SoftVision-PaulOiegas** [comment]
And dupe of #2634. I think @fzzzy and @lmorchard alerady found a trail on it. However, if you don't care about the Homepage, all the other pages are working. You can go straight to https://testpilot.dev.mozaws.net/experiments for example.

**Comment by fzzzy** [comment]
Closing as dupe of #2634.
