### ISSUE TITLE
A couple console CSP errors on dev

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2663]
Not sure if these are new or not, but spotted running through my console:

> **Content Security Policy:** The page’s settings blocked the loading of a resource at self (“style-src https://testpilot.dev.mozaws.net https://pontoon.mozilla.org https://code.cdn.mozilla.net”). Source: height:0px;.

> **Content Security Policy:** The page’s settings blocked the loading of a resource at self (“style-src https://testpilot.dev.mozaws.net https://pontoon.mozilla.org https://code.cdn.mozilla.net”).

Only thing I found with a 0px on that page was:

```html
<div class="sticky-header-sibling" style="height:0px;" data-reactid="14"></div>
```

---

Also noticed a ton of these:

> **Public-Key-Pins:** The site specified a header that did not include a matching pin.

**Comment by SoftVision-PaulOiegas** [comment]
Seen those too, but I am under the impression that are the same old ones that we already discussed about. Still, devs would know better.

**Comment by fzzzy** [comment]
Dupe of https://github.com/mozilla/testpilot/issues/2560
