### ISSUE TITLE
Snooze Tabs add-on name displayed like a single word and with lowercase in "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2666]
**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Test Pilot and all the active experiments were installed.

**[Steps to reproduce]:**
1. Open the Firefox with the profile from prerequisite and navigate to "about:addons" page.
2. Click on "Extensions" tab from left side.
3. Observe the names of all the Test Pilot related add-ons.

**[Expected result]:**
- All the experiments have the name displayed with uppercase letters at the beginning of each word

**[Actual results]:**
- Snooze Tabs add-on has the name displayed as "snoozetabs".

**[Notes]:**
- Here is a screenshot of the issue:
![snoozetab name](https://user-images.githubusercontent.com/17258026/28621691-724b46f4-721a-11e7-9afd-9fb54fdbc049.png)

**Comment by SoftVision-PaulOiegas** [comment]
@lmorchard maybe I should have logged this on Snooze Tabs repo instead ? Now that I'm thinking, it looks like to be related to the xpi itself, rather than Test Pilot.

**Comment by lmorchard** [comment]
Yeah, if it's in about:addons, it comes from the .xpi from the Snooze Tabs repo

**Comment by SoftVision-PaulOiegas** [comment]
I'll move this to the Snooze Tabs repo then. Ty!
