### ISSUE TITLE
Firefox Send privacy statement's "websites privacy notice" link doesn't work

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2667]
Pretty sure this sounds vaguely familiar, but I couldn't find an open issue for it...

Browsing https://testpilot.dev.mozaws.net/experiments/send and noticed that the "websites privacy notice" text (in the "Your privacy" block) looks like a link, but doesn't have an `href=""` so clicking the text does nothing, which is unfortunate since it looks like a legal privacy link.

<img width="1439" alt="firefox_test_pilot_-_send" src="https://user-images.githubusercontent.com/557895/28630297-cc559b72-71de-11e7-8059-81603fce4af4.png">

**Comment by SoftVision-PaulOiegas** [comment]
I think you were referring to this one #2103 ? It is closed but before graduating AS, it was still not working...

**Comment by pdehaan** [comment]
@SoftVision-PaulOiegas That's the one I was trying to find, thanks...
Looks like we need a better fix since it seems like it's been closed and reopened and killed a few times.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev and stage servers. Marking as verified.
