### ISSUE TITLE
If one of the "Voice Fill" or "Notes" experiment page is visited, the "Just launched" tag dispersers from both cards

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2669]
[Affected versions]:
- Firefox 54.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox clean profile.
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

[Steps to reproduce]:
1. Open the Firefox with the profile from prerequisite and navigate to "https://testpilot.dev.mozaws.net/experiments" page.
2. Click one of the "Voice Fill" or "Notes" experiment.
3. Return to the experiments page and observe the cards.

[Expected result]:
- The "Just Launched" tag disappears only for the visited experiment card.

[Actual results]:
- The "Just launched" tag disappears from both cards even if only one was visited.

[Notes]:
- Here is a screen recording with the issue:
![tag 2](https://user-images.githubusercontent.com/19226534/28633277-f1f5fa36-723b-11e7-815c-e7085d3825de.gif)

**Comment by johngruen** [comment]
huh

**Comment by johngruen** [comment]
I used the same id # in both experiments.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server. Marking as verified.

**Comment by gaby2300** [comment]
I tested with today's normal build, I could not reproduce the issue. I
suppose it's fixed?

Gabriela
QA Mozilla Hispano Team Responsible

http://www.mozilla-hispano.org
