### ISSUE TITLE
Photon sidebars are working poorly on the Test Pilot website

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/testpilot#2673]
[Notes]:
- This issue became much more apparent when using the Notes experiment, but it is also reproducible with all sidebars
- This issue will be very easily encountered after enabling Notes from TxP.

[Affected versions]:
- Firefox 54 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string pref was manually added with "dev" value on a new clean profile in "about:config" page.
- The "extensions.webapi.testing" boolean pref was manually added with "true" value on the crated profile.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Open the Bookmarks sidebar (CTRL+B).
3. Resize the sidebar and observe the behavior.

[Expected result]:
- Resizing is smooth.

[Actual result]:
- Resizing is very janky.

[Additional notes]:
- This issue is much more apparent on Windows.
- Here is a screen recording of the issue: [Link](https://drive.google.com/open?id=0B8ICzPJynbchTHVrNnBLX3NueTA).

**Comment by ghost** [comment]
We tried some other sites and saw they were also pretty jumpy.  We think this should be addressed by photon

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc That's odd, can you please name those websites? We also did that before logging this issue and we haven't seen the same behavior.

**Comment by ghost** [comment]
@johngruen tried it on CNN first, I think
