### ISSUE TITLE
Both Prod & Stage server add-ons are wrongly installed and disabled in "about:addons" while "extensions.legacy.enabled" pref is active (false value)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2680]
**[Affected versions]:**
- Firefox 56.0a1 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" or "production" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Change the "extensions.legacy.enabled" pref to "false" value.

**[Steps to reproduce]:**
1. Open the Firefox with the profile from prerequisite and navigate to https://testpilot.stage.mozaws.net / https://testpilot.firefox.com page.
2. Click on "Install Test Pilot Add-on" button.
3. Observe the page behavior.

**[Expected result]:**
- Test Pilot stage / production add-on cannot be installed since it's not signed with the new signature. 

**[Actual results]:**
- The Test Pilot stage / production add-on is wrongly installed but shows up as "Disabled" in "about:add-ons" page.

**[Notes]:**
- When this occurs, you are also redirected to /experiments page.
- Here is a screen recording of the issue: https://goo.gl/nV5Nwp.

**Comment by johngruen** [comment]
IDK if anything that involves manual `about:config` fiddling rises to the level of Major

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen I assume you know that when Nightly 57 lands (August 2nd), this pref that I'm talking about will be ON by default, right? Which means that nobody on Nightly could install Test Pilot or any other experiments due to this.

**Comment by fzzzy** [comment]
@clouserw said on irc that "a n d y m says they'll hold off landing the new webextensions-only patch until the 8th for nightly"

**Comment by ghost** [comment]
Duplicate of #2627
