### ISSUE TITLE
[Enhancement] The "Feedback" button should also be displayed on the "Send" experiment card, when Test Pilot is installed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2681]
[Notes]:
- Considering the fact that the "Feedback" button is displayed on the experiments card only when the experiments are enabled, I think we should figure out a way to also add it on Web experiments.

[Affected versions]:
- Firefox 54.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox clean profile.
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Have Test Pilot add-on installed on the created profile. 

[Steps to reproduce]:
1. Open the Firefox with the profile from prerequisite and navigate to "https://testpilot.dev.mozaws.net/experiments" page.
2. Observe the Send experiment card.

[Expected result]:
- The "Feedback" blue button should be displayed on the card.

[Actual results]:
- There is no way to provide feedback from Test Pilot website, you have to navigate to Send own site to do that.

[Additional Notes]:
- Here is a screenshot with the all experiments enabled:
![feedback](https://user-images.githubusercontent.com/19226534/28720526-19808244-73b6-11e7-986d-4f7949ff8848.png)

**Comment by johngruen** [comment]
Feedback for this experiment will go through the website itself
