### ISSUE TITLE
[Enhancement] Move the experiment type string under the experiment name while in mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2682]
**[Notes]:**
- I would suggest to move the experiment type string centrally positioned under the experiment title, while in mobile view. 

**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

**[Steps to reproduce]:**
1. Open the Firefox with the profile from prerequisite and navigate to https://testpilot.stage.mozaws.net page.
2. Click on "Install Test Pilot Add-on" button.
3. After redirected on /experiments page, click on any of the new experiments (Notes, Send or Voice Fill).
4. Observe where the experiment type string is displayed.
5. Resize the browser window until the page contents are displayed in mobile view.
6.  Observe again where the experiment type string is located.

**[Expected result]:**
- The experiment type string is displayed under the experiment name in both cases.

**[Actual results]:**
- Step 4: Experiment type string is displayed under the experiment name.
- Step 6: Experiment type string is wrongly displayed under the "Enable <experiment_name> button.

**[Additional Notes]:**
- This probably happens because the experiment title and buttons are in the same div, while the string div is placed next.
- This is an inconsistency since we have it displayed under the Experiment name while Test Pilot is not installed. And also since on experiment cards it's displayed the same.
- This also occurs after the experiment is enabled, when the string is lowered under both the buttons.

![experiment type](https://user-images.githubusercontent.com/17258026/28726082-6fb3db54-73c8-11e7-90d8-8b5f1c8dd0b8.png)

**Comment by ghost** [comment]
This is a little jarring, but we're going to wontfix it as there are other priorities to do. Thanks.
