### ISSUE TITLE
The new experiments image is not displayed on Twitter posts

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2684]
[Affected versions]:
- Firefox 54.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.

[Steps to reproduce]:
1. Open the Firefox with the profile from prerequisite and navigate to "https://testpilot.stage.mozaws.net/experiments" page.
2. Click one of the new experiments card.
3. Copy the experiment details page link and share it to Twitter.
4. Observe the tweet.

[Expected result]:
- The experiment image is correctly displayed.

[Actual results]:
- The experiment image is not displayed.

[Notes]:
- Here is a screenshot with the issue:
![twitter](https://user-images.githubusercontent.com/19226534/28726608-8ad76e76-73ca-11e7-8c25-071b56a10634.png)

**Comment by pdehaan** [comment]
I _think_ that is almost expected. I visited https://testpilot.dev.mozaws.net/experiments/notes and did a view-source and noticed that we're hard-coding the **PROD** URLs into the OpenGraph/Twitter `<meta>` tags, so we'd only be able to test that when we deploy those assets to production.

```html
<meta property="og:image" content="https://testpilot.firefox.com/static/images/experiments/notes/social/notes-fb.jpg"/>
<meta name="twitter:image" content="https://testpilot.firefox.com/static/images/experiments/notes/social/notes-twitter.jpg"/>
```

**Comment by johngruen** [comment]
@pdehaan yeah, i think you're right

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, seems legit. We'll recheck this when we deploy to production this week, and close this if everything is ok.

**Comment by pdehaan** [comment]
But I totally agree with the core issue. Having to wait until we've released to production to test something (and possibly require a production redeploy) is far from ideal. We should modify this bug (or file a separate one) for making those `<meta>` tags environment aware (so we can test on dev/stage as well).

**UPDATE:** Filed #2691

**Comment by SoftVision-PaulOiegas** [comment]
Works! However, the Send one is not very readable when it comes to the text under the logo.
![image](https://user-images.githubusercontent.com/17258026/28833278-8a42415a-76e7-11e7-898f-7ce9e16e83e0.png)
