### ISSUE TITLE
After turning off containers, "Open Link in New Container Tab" persists

### ISSUE THREAD

**Issue by lilyball** [mozilla/testpilot#2686]
I turned on containers for a few minutes the other day, then turned them off. Just now I noticed that if I right click on a link, I'm still given the option "Open Link in New Container Tab", which looks like a submenu except it doesn't actually have any submenu items (hovering over it does nothing).

**Comment by pdehaan** [comment]
@kballard, Thanks for the report! This repo is for the Test Pilot site/add-on, but I've migrated your bug over to the [**Test Pilot Containers** experiment's repo](https://github.com/mozilla/testpilot-containers/) at https://github.com/mozilla/testpilot-containers/issues/697.

Closing this in favor of the upstream bug.
