### ISSUE TITLE
Asset & measurement for Good First Bug Website

### ISSUE THREAD

**Issue by Pekochen** [mozilla/testpilot#2687]
Please see these links as below.
measurement:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Contribute/01_Measurements/
assets:
https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Contribute/00_Assets
Thanks~

**Comment by johngruen** [comment]
@chuckharmston ^

**Comment by pdehaan** [comment]
@johngruen @chuckharmston I'm mildly confused. Is the "good-first-bug" portal going to remain a separate site, or are we planning on adding the UI to the main testpilot.firefox.com site?

**Comment by chuckharmston** [comment]
I did it as a side project for a presentation, but I believe that John eventually wants to bring it in to the main site. For this, it was being used as a playground for trying out a Photonized aesthetic.

**Comment by pdehaan** [comment]
Awesome. I think it sounds way better as part of the core Test Pilot site. :+1:

**Comment by chuckharmston** [comment]
This is shipped: https://contribute.testpilot.firefox.com

CC @ChenMorpheus and @Pekochen for some visual QA.

**Comment by pdehaan** [comment]
@chuckharmston Where could a certain up-and-coming Jr QA file bugs against said code? I tried the big, shiny GitHub icon in the footer, but that seems to be a circular link.

**UPDATE:** Nevermind, I was trolling your commits and found https://github.com/chuckharmston/testpilot-contribute

**Comment by chuckharmston** [comment]
> @chuckharmston Where could a certain up-and-coming Jr QA file bugs against said code? I tried the big, shiny GitHub icon in the footer, but that seems to be a circular link.

https://github.com/chuckharmston/testpilot-contribute/issues/new

**Comment by chuckharmston** [comment]
I've completely updated the storybook for the new design, and it is now deployed, so you can check it out here: https://chuckharmston.github.io/testpilot-contribute/

CC @youwenliang, who may want to pitch in with some programming. It'd be a great test of out new proposed workflow.

**Comment by ChenMorpheus** [comment]
@chuckharmston Thanks for the storybook, but we've collected several UI issues here: #2767, just let us know if any questions, thanks.
