### ISSUE TITLE
TxP is not recognized as installed on latest Nightly build on Linux 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/testpilot#2689]
**[Affected versions]:**
- Firefox 56.0a1

**[Affected Platforms]:**
- All Linux

**[Steps to reproduce]:**
1. Open the Firefox Nightly and go www.testpilot.firefox.com
2. Install Test Pilot from the accessed page.
3. Click on any experiment.

**[Expected result]:**
- The user is prompted to install only the experiment.

**[Actual results]:**
- TxP install is not recognized. The user is instructed to install TxP and the experiment.

**[Notes]:**
- This is happening only on the latest Nightly build. On latest Firefox release TxP can be installed without issues.
- This error is displayed in the Browser Console:
`NS_ERROR_FILE_ACCESS_DENIED: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIZipReaderCache.getZip] 1 loader.js:249`

**Comment by SoftVision-PaulOiegas** [comment]
@Softvision-VladBacia please do a regression window with mozregression tomorrow on this. So we can point out where the breakage occurred.

**Comment by jaredhirsch** [comment]
The error message points to [a zip reader cache call](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/toolkit/loader.js#249) in the SDK loader.

I wonder if this bug is related? Last comment mentions the same error message for a related case (SDK addon loading an html page, hitting NS_ERROR_FILE_ACCESS_DENIED): https://bugzilla.mozilla.org/show_bug.cgi?id=1383215

**Comment by fzzzy** [comment]
This could be related:

https://bugzilla.mozilla.org/show_bug.cgi?id=1385891

**Comment by callahad** [comment]
I'm also seeing a warning before each error:

```
Use of nsIFile in content process is deprecated.  loader.js:247:15
NS_ERROR_FILE_ACCESS_DENIED: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIZipReaderCache.getZip]
```

__WORKAROUND:__ Everything works when opened in a non-e10s window.

**Comment by marco-c** [comment]
> I'm also seeing a warning before each error:

Maybe a sandbox error?

**Comment by callahad** [comment]
That would explain why it only shows up under e10s.

**Comment by pascalchevrel** [comment]
I have this bug, if I create a profile in /tmp it works, but it doesn't work  if the profile is in my home.

Works:
```
mkdir /tmp/foobar
firefox -Profile /tmp/foobar
```
Doesn't work:
`firefox -Profile $HOME/path/to/foobar
`

**Comment by bclary** [comment]
I believe this is due to the sandboxing that was recently enabled on Nightly. I have seen this on Linux 64bit with Nightly. If you set security.sandbox.content.level to 0 and restart, it will work.

**Comment by Softvision-VladBacia** [comment]
I did a regression range with mozregression and ended up with the following result:

https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=69e573abaccb3eba8446c669328f133b7c503a48&tochange=7a7db98b3785ace1e19637b6595a79864251bc7d
DEBUG : Using url: https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=b5fa08551d6e74d8300fa94f3161afdffd867764&full=1
DEBUG : Found commit message:

Bug 1308400 - Report failures in file processes too. r=jld

**Comment by rpellerin** [comment]
I am affected as well on Xubuntu 16.04 with the latest build of Nightly (57). It was not working either with 56.0a1

**Comment by eliedrian** [comment]
I turned off sandboxing by suggestion of bclary, everything works. Installing experiments and turning sandboxing back on again works as well.

**Comment by linux-modder** [comment]
Appears fully functional again on 57.0.a1 nightly as well.

**Comment by cmoud94** [comment]
@linux-modder Nope, I'm using 57.0a1 and the problem is still here. At least for me.

**Comment by SoftVision-PaulOiegas** [comment]
Just posting a couple of workarounds for people that land here from other experiments. It seems that we have a lot of Linux users on them. Try these steps until the issue gets fixed.
1. Turned off sandboxing, everything works. Installing experiments and turning sandboxing back on again works as well.
2. Install Test Pilot and desired experiments on the Firefox release version and after switch back to Nightly on the same profile. This will bypass the Nightly issue.

**Comment by eliedrian** [comment]
I have just found that some experiments don't work in NIghtly after turning
sandboxing back on, such as Min Vid. "Notes", however, still work after turning
sandboxing back on.

**Comment by ghost** [comment]
Is there a bug to fix this in Bugzilla that we can use to know whether this is fixed or not?  Or should I file one?

**Comment by MikkCZ** [comment]
There are two bugs mentioned in https://github.com/mozilla/testpilot/issues/2689#issuecomment-319229665 and below, but I do not see anyone confirming any of it. I guess filing a new bug with https://github.com/mozilla/testpilot/issues/2689#issuecomment-319653376 is the way?

**Comment by bclary** [comment]
I would test with a build containing https://bugzilla.mozilla.org/show_bug.cgi?id=1385891 to see if that fixed it.

**Comment by bjherbison** [comment]
I don't know if bug 1385891 was the issue but the problem seems to be gone.

**Comment by eliedrian** [comment]
Agreed! Min Vid works now in the last few nightlies.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas can you verify this is fixed

**Comment by MikkCZ** [comment]
Works for me for some time already.

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen I can confirm too that it works well on latest Nightly build (2017-08-21). I will close this as verified fixed.
