### ISSUE TITLE
"Disable <experiment_name>" red button for graduated experiments is not vertically aligned in the middle of the designed area

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2695]
**[Affected versions]:**
- Firefox 54.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Test Pilot production add-on was already installed on a Firefox profile.
- Change the system date to be July 11th 2017.

**[Steps to reproduce]:**
1. Open the Firefox with the profile from prerequisite and navigate to https://testpilot.firefox.com page.
2. Click on Page Shot experiment card and click on the "Enable Page Shot" button.
3. After enabled, return system date to current date.
4. Refresh the Page Shot experiment details page and observe the "Disable Page Shot" button position.
5. Scroll down on the page until the button detaches and observe its position.  

**[Expected result]:**
- in both cases the button is vertically aligned in the middle of the designed area.

**[Actual results]:**
- In both cases the button is positioned higher than it should in the designed area.

**[Notes]:**
- Here is a screenshot of the issue:

![disable button graduation](https://user-images.githubusercontent.com/17258026/28825604-974287f6-76cf-11e7-9ccd-5fd341134b67.png)

**Comment by vikramnr** [comment]
@wresuolc Can I take up this issue? If so height of the `Disable Page Shot` should be lowered?

**Comment by meandavejustice** [comment]
@vikramnr go for it :)

**Comment by marvinsanchez1** [comment]
Hi @wresuolc , is this bug not assigned to someone, can I work on it for my assignment?
Thank you!

**Comment by himanish-star** [comment]
I would like to fix this issue. May I ?

**Comment by vikramnr** [comment]
@himanish-star  I'm not working on this. :+1:

**Comment by chuckharmston** [comment]
No longer valid, closing.
