### ISSUE TITLE
AWS integration work for staging/prod server

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#27]
- RDS or EC2 for postgres in AWS?
- Do we want to continue trying to use Elastic Beanstalk?

**Comment by lmorchard** [comment]
I had a small staging-ish success earlier that may or may not be handy in the future. Just so I don't forget it, here's the gist:

``` bash
    export AWS_ACCESS_KEY_ID=YOURKEYIDHERE
    export AWS_SECRET_ACCESS_KEY=YOURKEYSECRETHERE
    export AWS_VPC_ID=vpc-c02b81a5

    cp docker-compose.yml docker-compose-stage.yml

    # Edit docker-compose-stage.yml, remove the the lines that say "volumes: .:/app"
    # Volumes are just for dev, mounting the project directory rather than copying

    docker-machine -D create --driver amazonec2 amazon
    eval $(docker-machine env amazon)
    docker-compose -f docker-compose-stage.yml up 
```

**Comment by lmorchard** [comment]
Maybe a duplicate or tracker for Issues #131 and/or #132

**Comment by lmorchard** [comment]
#143 is progress toward this!

**Comment by lmorchard** [comment]
Between #143 and 543656b04c4b8dec0c650da58229a43441f1b975, I think we know where we're going with this stuff. Going to call this done
