### ISSUE TITLE
When logged in, logged out state state flashes on refresh

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#270]
This gif sort of captures it (ignore the part where i accidently click on the mozVR link)

![flashy-flashy](https://cloud.githubusercontent.com/assets/3323249/11249756/18e57eda-8e29-11e5-9feb-9e4c5425a330.gif)

**Comment by meandavejustice** [comment]
I'm unable to reproduce this on the issue-191-provisional branch

**Comment by lmorchard** [comment]
Can't reproduce this either... Going to guess that this might have been fixed along the way because `main.js` now waits for the `/api/me` resource to load (which has auth details) before initializing the Router (which fires off page display)
