### ISSUE TITLE
prod vs production

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#2700]
We've had a couple of reports of testpilot.env being "production" and the site not recognizing the add-on.  IRC thinks this should be "prod".  When did it change?  Why?  What's the fallout?

**Comment by SoftVision-PaulOiegas** [comment]
The environment was always "production" if I remember well. I don't recall setting it as "prod".
However, if you refer to the Linux issue where the add-on is not recognized as installed, this is a known issue that was logged yesterday #2689. The issue was mentioned in the deploy bug and on IRC.

**Comment by ghost** [comment]
Les says it defaults to production if it doesn't recognize the string, so that would explain prod vs production.  for the record, it is "production".  Paul is right. as usual. :champagne:
