### ISSUE TITLE
Cannot install any experiment after Noted, Voice Fill and Send have been published

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/testpilot#2701]
Seems the Test Pilot add-on is not recognized well. After the new experiment got enabled, I only see the green button to say me to install Test Pilot and enable the add-on. After clicking it, I see a doorhanger informing me the Test Pilot add-on has been installed, but nothing happens than. After page reload, I am again asked to install the Test Pilot despite I see it in the add-ons manager (version 1.1.4-dev-22b26fa).

Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0 ID:20170801100311 CSet: 51ffb9283f0c7c00e08eb8c39b33fbee218c370d

**Comment by SoftVision-PaulOiegas** [comment]
Hi @MikkCZ and thanks for the report. However this is a known issue that is reproducible only on Linux, see #2689. I will close this in favor of that.
