### ISSUE TITLE
No test install telemetry ping is being sent

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/testpilot#2703]
The realtime installation counter used on the site relies on incoming `testpilot`-type experiment install pings sent to our own telemetry servers. We're not seeing any installations from the new tests coming into the realtime filter as far as I can tell, and when I just tried installing one of the new tests on my personal browser it never sent the install ping (I see the icon-clicked ping though) so it seems likely the issue is on the txp addon/metrics library side.

**Comment by ghost** [comment]
The pings are being shown in about:telemetry for us.  Is that where you are looking?  Can you give us more steps to reproduce. thanks

**Comment by lmorchard** [comment]
Do we have any updates on this?

Or should we drop this issue into the backlog? Or maybe even close it WONTFIX since we [removed the display of install counts](https://github.com/mozilla/testpilot/issues/2736)?

**Comment by sunahsuh** [comment]
Bleh, sorry, this issue fell into email-filter hell. If it's not being used for the website and TxP real-time installations are being tracked elsewhere then it's probably fine to close -- I just need to do some cleanup in removing the filter on our pipeline

**Comment by ghost** [comment]
We're not using telemetry anymore.  We can close this.
