### ISSUE TITLE
Build a better sense of connection between testers and developers.

### ISSUE THREAD

**Issue by klondikemarlen** [mozilla/testpilot#2709]
When I submit feedback on a Firefox Test Pilot experiment ... I don't feel a sense of connection with the project. Could you make the feedback more two way? Such as seen here http://community.wrio-keyboard.com/?

I can't tell if my suggestions are being heard or if other people have the same problem.

i.e. I submitted feedback on the Min Vid experiment that I wanted the mini player to be resizable as I found it too small to watch the content of the videos. Did other people have the same problem? Did the developers start a feature request? Or are there so many reviewers that my feedback was lost in the multitude?

I feel that this also would help build a community among testers and help produce better feedback.

I am excited by the experiments and will keep trying and reviewing them even if you don't implement this.
    Marlen

**Comment by SoftVision-PaulOiegas** [comment]
Hi @klondikemarlen and thanks for your report. In the future, I would suggest that you should log ideas like this straight to the specific experiment repository. All the logged issues are triaged and would be definitely seen. For example https://github.com/meandavejustice/min-vid/issues is for Min Vid. You can find the repository link on each Test Pilot experiment page, on the left column.

However, I think your idea was "heard" and it is already implemented in the latest version found on Test Pilot. If you go to "about:addons" page in the extensions tab, double click "Min Vid" extension, you'll see that it offers "Window height / width" options.

**Comment by klondikemarlen** [comment]
Hi! Thanks for your reply. I will check out the Min Vid issues page.
I didn't know it had a preferences page. I didn't know any of the "experiments" had preferences pages.

After checking it out ... the Min Vid window still doesn't do what I want. I was looking for a "drag to resize" option. In the about:addons page .. you can only make it smaller. I want the size to be bigger. Say 640 x 480. Or like 1/5 of my screen. Instead of 1/8.

Should I post this request to the Min Vid issues page then? I am quite new this kind of thing.

**Comment by SoftVision-PaulOiegas** [comment]
Well, I think something broke, because in the past you could increase the size of the player. Or at least I remember so. Please file an issue on the link I gave you above regarding this.

**Comment by klondikemarlen** [comment]
I guess it is a work in progress https://github.com/meandavejustice/min-vid/issues/69. Thanks again for your patience.

**Comment by fzzzy** [comment]
@klondikemarlen We do have our discourse forum. You could take a look there. It might be more interactive.

https://discourse.mozilla.org/c/test-pilot

**Comment by ghost** [comment]
related to #2867

**Comment by chuckharmston** [comment]
As noted above, Discourse is the place where this happens. Closing.
