### ISSUE TITLE
Would like to be in the test pilot

### ISSUE THREAD

**Issue by nenay8** [mozilla/testpilot#2716]
I tried to use Firefox browser and get onto the test pilot program.  Says it's got a bug.
I am going to try another browser.
Thank you,
Renee'

**Comment by chuckharmston** [comment]
Thanks for the report, @nenay8! I suspect that you are using Firefox Nightly on Linux? If so, this is a known issue that we're tracking at #2689.

As a temporary workaround, you should be able to install Test Pilot experiments in release Firefox, then starting up Nightly with the same profile.

**Comment by nenay8** [comment]
No I am currently using an Apple 6s plus.  Any word on that having issues?
		

		Renee' Watts
	





On Wed, Aug 2, 2017 at 6:04 PM -0400, "Chuck Harmston" <notifications@github.com> wrote:












Thanks for the report, @nenay8! I suspect that you are using Firefox Nightly on Linux? If so, this is a known issue that we're tracking at #2689.


As a temporary workaround, you should be able to install Test Pilot experiments in release Firefox, then starting up Nightly with the same profile.

**Comment by chuckharmston** [comment]
Ah ha, that's a different issue, #2642. Unfortunately, that one is quite low priority as Test Pilot experiments only work on desktop Firefox.

Closing this as a duplicate for tracking purposes. Thank you for letting us know!
