### ISSUE TITLE
 Firefox Test Pilot website does not recognize installed extension [bug 1386442]

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/testpilot#2717]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
Build ID: 20170801100311

**Steps to reproduce:**
1. Open Firefox Nightly browser using Deepin Linux dock;
2. Write https://testpilot.firefox.com on the URL bar and Enter on keyboard;
3. Clicked on Install Test Pilot extension, and has been installed;
4. On https://testpilot.firefox.com/experiments, I clicked on "Notes" experiment;
5. On https://testpilot.firefox.com/experiments/notes  only option I have is "Install Test Pilot and enable Notes", when clicking the Test Pilot extension is installed again and the button shows "Installing ..." infinitely.

**Actual results:**

On https://testpilot.firefox.com/experiments/notes  only option I have is "Install Test Pilot and enable Notes", when clicking the Test Pilot extension is installed again and the button shows "Installing ..." infinitely.
![deepin-screen-recorder_navigator_20170801183640](https://user-images.githubusercontent.com/14970832/28896538-346e9612-77b3-11e7-9d73-7742bb269fe9.gif)

**Expected results:**
1. OK
2. OK
3. OK
4. OK
5. On https://testpilot.firefox.com/experiments/notes, I should have the option to enable Notes, and that's it.

Also: https://bugzilla.mozilla.org/show_bug.cgi?id=1386442

**Comment by barrosgeraldo** [comment]
![deepinscreenshot_select-area_20170802185810](https://user-images.githubusercontent.com/14970832/28896882-95f4cc84-77b4-11e7-9278-b3872ada709d.png)

**Comment by chuckharmston** [comment]
Thanks for the report! This is a known issue on Nightly in Linux, and we're tracking it at #2689. I'm going to close this as a duplicate.

As a temporary workaround, you should be able to install Test Pilot experiments in release Firefox, then starting up Nightly with the same profile.
