### ISSUE TITLE
Testpilot addon not detected and can't install new experiment

### ISSUE THREAD

**Issue by leplatrem** [mozilla/testpilot#2718]
Version: Nightly 57 (2017-08-07)
Testpilot install: 1.1.4-dev-22b26fa

Steps to reproduce:
* I go to https://testpilot.firefox.com/experiments/notes
* I see «install test pilot and enable notes" (whereas I already have testpilot)
![screenshot from 2017-08-03 11-23-59](https://user-images.githubusercontent.com/546692/28915092-4f64e558-783e-11e7-9d93-9d1027a3c343.png)
* I click install, the popup "Test pilot has been added to nightly"  shows up
* The button is stuck on "Installing..." and the Send experiment is never installed
* Refresh goes to step 1 :)

Console log:
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://testpilot.firefox.com https://code.cdn.mozilla.net”). Source: height:0px;. notes
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://testpilot.firefox.com https://code.cdn.mozilla.net”). notes
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://testpilot.firefox.com https://code.cdn.mozilla.net”). Source: height:0px;. notes
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://testpilot.firefox.com https://code.cdn.mozilla.net”). notes
Loading failed for the <script> with source “https://ssl.google-analytics.com/analytics.js”. notes:1
Loading failed for the <script> with source “https://static.doubleclick.net/instream/ad_status.js”. vaFvr_70yxw:1 
```

**Comment by SoftVision-CosminMuntean** [comment]
@leplatrem thanks for reporting this! 
Did you encountered this issue on Linux? I'm asking this because there is an issue on Nightly in Linux, and we're tracking it at #2689.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @leplatrem and thanks for your report. I assume you are on Linux based OS? If that's true, this is a known Nightly issue on Linux that is currently debugged in #2689. So please bear with us until a fix lands for this.

Other people mentioned some workarounds for this:
1. I turned off sandboxing, everything works. Installing experiments and turning sandboxing back on again works as well.
2. Install Test Pilot and desired experiments on the Firefox release version and after switch back to Nightly on the same profile. This will bypass the Nightly issue.

I'm gonna close this one in favor of #2689, so please follow the discussions there. If you are not on Linux, please reopen this and provide more info about your environment.
