### ISSUE TITLE
Learn more Error

### ISSUE THREAD

**Issue by lilianfornea** [mozilla/testpilot#2719]
Clicked to see more details in https://send.firefox.com 
![image](https://user-images.githubusercontent.com/17119455/28919303-9ad20e64-7855-11e7-80bc-368b2dd5c65f.png)
about feature and get a something wrong page

**Comment by fzzzy** [comment]
Thank you for the report. This looks like a tablet version of firefox? Can you give details about the firefox version used?

**Comment by SoftVision-PaulOiegas** [comment]
Indeed, I think this is on iOS tablet. We have this issue already tracked under #2642. Unfortunately, this is quite low priority issue, as Test Pilot experiments only work on desktop Firefox. 
Even if this will be fixed, you would still not be able to use most of the experiments on mobile devices.

I will close this in favor of #2642, please follow the discussions there.
