### ISSUE TITLE
Test Pilot icon is missing from "about:addons" page (dev)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2720]
- Firefox 54.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was manually added in "about:config" page with "dev" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Test Pilot is already installed on the created provile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Navigate to "about:addons" page and click the "Extensions" section.
3. Observe the Test Pilot add-on.

[Expected result]:
- The Test Pilot logo is displayed on the left side of the page.

[Actual results]:
- The Test Pilot logo is missing.

[Notes]:
- The issue is reproducible only if Test Pilot is installed from the dev server,
- Here is a screen shot with the issue:
![test pilot icon](https://user-images.githubusercontent.com/19226534/28927443-39c7986e-7873-11e7-8714-310a4f45435e.png)

**Comment by SoftVision-CosminMuntean** [comment]
I thought that this issue will also reproduce after deploy on stage, but it seems that is only reproducible on dev server for now.

**Comment by SoftVision-PaulOiegas** [comment]
@lmorchard @fzzzy Hmm, not sure that this fixed the issue. I still can't see an icon for the dev server add-on.

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas You're right, I don't see the icon on dev but I do see it on stage, even though they have the same code deployed in both places right now.

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy Cosmin mentioned that this only reproduces on dev, before the fix was made. So I'm not sure what this fixed. 😄

**Comment by lmorchard** [comment]
Is this still an issue? Should be fixed, and I can see the icon

**Comment by johngruen** [comment]
I'm seeing it as well, @SoftVision-CosminMuntean can you confirm and close

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and the Test Pilot icon is correctly displayed.

**Comment by SoftVision-PaulOiegas** [comment]
This is like a boomerang, forever returning to us. 😆 Again, the dev server has no icon for TxP add-on in "about:add-ons" page.

**Comment by SoftVision-PaulOiegas** [comment]
And now it's ok again... Closing until it comes back. 😄
