### ISSUE TITLE
Add scss-linting to gulp

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#273]
~~@pdehaan this seems like a job for you. Not sure how to handle the ruby dependency~~

@pdehaan, actually, I can take care of the gulp part of this, but IDK how scss-lint might work with travis.

**Comment by pdehaan** [comment]
@johngruen We could try using https://github.com/sasstools/gulp-sass-lint which I think doesn't have any Ruby dependencies.

**Comment by johngruen** [comment]
@pdehaan oh cool, i got that working...we have a lot of tidying to do :)
