### ISSUE TITLE
Localization is not working in other language than English

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2732]
[Affected versions]:
- Firefox 54.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Have any language set other than English in "about:preferences#content" on a new Firefox profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to "https://testpilot.stage.mozaws.net" page.
2. Observe the Test Pilot page language.

[Expected result]:
- The Test Pilot page is correctly displayed in the chosen language.

[Actual results]:
- The Test Pilot page is wrongly displayed in English.

[Notes]:
- The issue is also reproducible on localized Firefox builds. 
- The issue is reproducible on dev and stage servers.
- Here is a screen recording with the issue:
![localiation](https://user-images.githubusercontent.com/19226534/29019763-4a52ed26-7b68-11e7-8182-4baff7e00a7d.gif)

**Comment by fzzzy** [comment]
config.AVAILABLE_LOCALES is returning undefined.

**Comment by fzzzy** [comment]
I have figured out what this is. Apparently there are two files named config, and the one that is accessible in the browser does not specify AVAILABLE_LOCALES. I switched to getting the available languages from `document.querySelector('meta[name=availableLanguages]')`, which is always available.
