### ISSUE TITLE
Experiment download counts not consistent on experiments page vs details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2734]
Found in https://testpilot.dev.mozaws.net/__version__ (d38c9fb1a61097501aa3e087589f8e4bd497d9d6):

```json
{
  "commit": "d38c9fb1a61097501aa3e087589f8e4bd497d9d6",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/5290"
}
```

---

### Steps to reproduce:
1. Go to https://testpilot.dev.mozaws.net/experiments/ and check the participants counts for min-vid.
1. Go to https://testpilot.dev.mozaws.net/experiments/min-vid and check the participants count.

### Actual results:
The /experiments page uses comma separator, the details page doesn't.

<img width="325" alt="firefox_test_pilot" src="https://user-images.githubusercontent.com/557895/29035505-b39d2016-7b50-11e7-8a14-b5ec9c9fec93.png">

<img width="322" alt="firefox_test_pilot_-_min_vid" src="https://user-images.githubusercontent.com/557895/29035540-d151ebb4-7b50-11e7-9416-02aaad45d2eb.png">

**Comment by ghost** [comment]
We're planning on removing these counts completely.  @fzzzy removed them this morning
