### ISSUE TITLE
Snooze Tabs page looks bad in Chrome (on dev/stage)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2735]
Looks bad in dev/stage, but fine in prod.
I kind of _want_ to blame the new sidebar UI that recently landed, but that's just a guess with the new UI and potentially long, unwrapping URLs. In my quick testing, it looks like Snooze Tabs may have been the only experiment with the issue, but I'll try digging deeper.

### Steps to reproduce:
1. Open https://testpilot.dev.mozaws.net/experiments/snooze-tabs in Chrome and Firefox.

### Actual results:
UI gets squishy in Chrome, but looks 👌 in Firefox.

<img width="1440" alt="firefox_test_pilot_-_snooze_tabs" src="https://user-images.githubusercontent.com/557895/29035814-d8ed9a2a-7b51-11e7-8cfa-7342078f20fd.png">

**Figure 1:** Dev server (Chrome Release channel)

---

<img width="1440" alt="firefox_test_pilot_-_snooze_tabs" src="https://user-images.githubusercontent.com/557895/29035867-fcff15a6-7b51-11e7-9721-a3cab5fe37a9.png">

**Figure 2:** Prod server (Chrome Release channel)

---

<img width="1440" alt="firefox_test_pilot_-_snooze_tabs" src="https://user-images.githubusercontent.com/557895/29035895-15e6c94c-7b52-11e7-804f-20149a63f4fc.png">

**Figure 3:** Dev server (Firefox Beta channel)

**Comment by SoftVision-PaulOiegas** [comment]
Voice Fill page looks the same, and yeah, the long URL's are at fault here. I have just modified the text of the URL's for Voice Fill "Changelog" and "Bug Reports" and the UI jumped back correctly.

![chrome ui](https://user-images.githubusercontent.com/17258026/29123311-fae30976-7d1d-11e7-9ab7-0145b84fb692.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev server on Chrome. Marking as verified.
