### ISSUE TITLE
Icon size is wrong when moved to overflow menu

### ISSUE THREAD

**Issue by rhysforyou** [mozilla/testpilot#2739]
When I move the Test Pilot extension's action button into the overflow menu, it looks like its icon's getting cropped for some reason:

![screen shot 2017-08-08 at 11 56 57 am](https://user-images.githubusercontent.com/320910/29053015-cf7f6d3a-7c30-11e7-8366-a9d2265e46d4.png)

**Comment by fzzzy** [comment]
Thank you for the report. There's already a bug open for this: #2602

Closing this as a duplicate.
