### ISSUE TITLE
Rename branches from stage-static and production-static to stage and production

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2741]
We used the names stage-static and production-static during the switchover from the dynamic site to the static site. We might as well switch back to the names stage and production to be more consistent with the rest of the experiments now.

**Comment by fzzzy** [comment]
We'll have to update the documentation, update jenkins, and update the ops scripts for this.

**Comment by ghost** [comment]
@relud This is easy on our end.  How much work is this on your end?

**Comment by relud** [comment]
v easy

**Comment by relud** [comment]
merging mozilla-services/cloudops-deployment#1359 combined with deploying the new branch once will do it

**Comment by ghost** [comment]
Thanks.  I'll pull this out of stretch so we can do it in the next sprint

**Comment by fzzzy** [comment]
@relud I'm ready for you to merge the ops side of this whenever you are. Let me know when a good time for you is.
