### ISSUE TITLE
Testpilot website doesn't work in Tor Browser

### ISSUE THREAD

**Issue by mrphs** [mozilla/testpilot#2745]
As shown in the screenshot below, I can't seem to be able to load any of the testpilot pages inside Tor Browser.

<img width="500" alt="screen shot 2017-08-08 at 3 42 37 pm" src="https://user-images.githubusercontent.com/453701/29091289-ff5bb90a-7c71-11e7-90a8-39d0fb818684.png">

**Comment by SoftVision-PaulOiegas** [comment]
Hi @mrphs and thanks for your report. Tor is not on our usual browsers list for compatibility verification, but indeed you are right. The Test Pilot homepage tries to load but throws up this error. We have a similar issue (#2642) on iOS devices where the same page is displayed. Maybe it's something related.
The dev team will probably look into this and report back with any findings.

Here is a screenshot with the browser console logs while the browser attempts to load the page
![image](https://user-images.githubusercontent.com/17258026/29111758-34172d78-7cf4-11e7-826b-04b46d4ae200.png)

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen this still happens on Tor Browser. Double checked on Firefox 52.3.0 ESR and it's working perfectly on both x32 and x64 builds. So it might be related to the iOS issue #2642.

![tor browser 08 22 2017](https://user-images.githubusercontent.com/17258026/29555310-e9f963a0-872a-11e7-9a5a-9a31eb3be70b.png)

**Comment by chuckharmston** [comment]
<img width="1112" alt="screen shot 2018-03-05 at 09 24 16" src="https://user-images.githubusercontent.com/23885/36986431-01a46462-2057-11e8-8130-fa1c5bcf4c52.png">

Since Tor is on a pre-57 channel, it now serves an appropriate error message. Closing.
