### ISSUE TITLE
Localization issue reported on Twitter

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2753]
@fzzzy

User reports: `Accept-Language: en,ru;q=0.7,ja;q=0.3`

Looks like they're seeing a mix of accepted languages :(

<img width="1195" alt="screen shot 2017-08-09 at 6 37 25 pm" src="https://user-images.githubusercontent.com/3323249/29132881-f09bd646-7d31-11e7-93cc-c211222e9d98.png">

**Comment by johngruen** [comment]
Note, user said that until last week the whole site was working in English, which was their first choice.

**Comment by 13xforever** [comment]
I use English version of Firefox on Linux with English language & Russian regional Formats.
Selected languages for content are: English [en], Russian [ru], Japanese [jp].

Page renders in a deterministic way (i.e. no random language swaps on refresh).

![Fullscreen screenshot](https://user-images.githubusercontent.com/36445/29133556-4c0e1e42-7d4d-11e7-8b59-c4d5a8544b23.png)

**Comment by johngruen** [comment]
Looks like we need to add `en` here https://github.com/mozilla/testpilot/blob/master/frontend/config.js#L13

**Comment by lmorchard** [comment]
A little more needs doing: We either need to copy the `en-US` locale to `en` along with adding `en` to the production locale list - [or, better yet, we find a way to alias `en` to `en-US` in the language negotiation stage](https://github.com/projectfluent/fluent.js/tree/master/fluent-langneg#likely-subtags)

**Comment by fzzzy** [comment]
It looks like we can use the likelySubtags feature in fluent-langneg to help with this:

https://github.com/projectfluent/fluent.js/tree/master/fluent-langneg

Since we manually maintain the list of 100% languages, we will still need to keep that string up to date, though.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on dev and stage servers and is no longer reproducible. Marking as verified.
