### ISSUE TITLE
Voice Fill, Notes, Send do not load using macOS High Sierra 10.13 Beta (17A330h)

### ISSUE THREAD

**Issue by ggenaw** [mozilla/testpilot#2755]
Just updated to Firefox 55 this morning and Signed on to Test Pilot. Some of the new add on experiments looked interesting, but won't load

**Comment by lmorchard** [comment]
Maybe a duplicate of #2746 ?

**Comment by SoftVision-PaulOiegas** [comment]
That seems right Les. 
Hi @ggenaw, I have to close this issue as a dupe of the one mentioned above. Please follow the thread there and provide any extra details you can, to help us debug this issue. Thanks!
