### ISSUE TITLE
UI issues on contributor site

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#2767]
@chuckharmston The implementation looks nice! We've collected several UI issues and one related to UX improvement. Please check the list below for details and let us know if any questions, thanks.

1. Card size, color (should be flat and photon color), icon size are incorrect
![image](https://user-images.githubusercontent.com/18019946/29205391-1ee6a520-7eaf-11e7-9972-74819f31ba11.png)

2. In normal status, text should be align center, and no overlay. Icon size and card size need fine tune as well.
![image](https://user-images.githubusercontent.com/18019946/29205395-284c3314-7eaf-11e7-9348-f0ae89307e81.png)

3. Background image and color changes when setting different filters
![image](https://user-images.githubusercontent.com/18019946/29205403-334b502e-7eaf-11e7-83fc-bbb7adfac96c.png)

4. Color of hover state for primary button is incorrect
![image](https://user-images.githubusercontent.com/18019946/29205406-3969a104-7eaf-11e7-9b3e-ca73b4268f20.png)

5. Hover state for framed button is incorrect
![image](https://user-images.githubusercontent.com/18019946/29205412-40f24296-7eaf-11e7-9dbc-54705b32be87.png)

6. [UX] While scrolling down, the toolbar should stick to the bottom of the chrome
![image](https://user-images.githubusercontent.com/18019946/29205418-49e776a0-7eaf-11e7-8137-3662739d3805.png)

7. Footer size is small
![image](https://user-images.githubusercontent.com/18019946/29205424-50701248-7eaf-11e7-9c68-71ebadc008f2.png)

**Comment by johngruen** [comment]
@ChenMorpheus WRT Issue 1: I'd greatly prefer that the card colors match those on the site for the the time being in order to maintain continuity. 

In the case of Screenshots, we have a new icon that matches neither the one found in the design spec nor the one used on Page Shot: 
https://github.com/mozilla-services/screenshots/blob/master/static/img/landing-icon-screenshots.svg

**Comment by ChenMorpheus** [comment]
@johngruen For issue 1, that makes perfect sense. We were just worried that the style doesn't match the rest of Photon design. 
As for screenshots icon, sorry that we grabbed the old icon. The one you mentioned is the correct icon. Nice catch!

**Comment by chuckharmston** [comment]
I've moved all these issues to the appropriate repo:

- https://github.com/chuckharmston/testpilot-contribute/issues/32
- https://github.com/chuckharmston/testpilot-contribute/issues/33
- https://github.com/chuckharmston/testpilot-contribute/issues/34
- https://github.com/chuckharmston/testpilot-contribute/issues/35
- https://github.com/chuckharmston/testpilot-contribute/issues/36
- https://github.com/chuckharmston/testpilot-contribute/issues/37
- https://github.com/chuckharmston/testpilot-contribute/issues/38

Please file future issues here: https://github.com/chuckharmston/testpilot-contribute/issues/new
