### ISSUE TITLE
Experiments keep loading forever

### ISSUE THREAD

**Issue by erik8752** [mozilla/testpilot#2768]
I have installed testpilot 1 hour ago. Plugin is installed and enabled. After clicking the icon I get to the
[start page](https://testpilot.firefox.com/experiments?utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content=not+badged)
I can't load any of the experiments because they just keep loading for several minutes until I close the tab. CPU, RAM and network usage is low during the experiment loading so I doubt it is my computer slowing it down. Other web pages work fine. Currently test pilot is the only extension in my browser.

I tried IRC #testpilot but there was noone to chat with (or maybe IDK how to use IRC because it was my first time too).

I am using firefox 54.0.1 on Windows 10.
![start page](https://user-images.githubusercontent.com/30925346/29209721-413c3bcc-7e90-11e7-8457-4f0d3bdca0ae.PNG)
![min vid loading forever](https://user-images.githubusercontent.com/30925346/29209727-4995d01c-7e90-11e7-97e9-f230c7b4a483.PNG)

**Comment by romme** [comment]
![image](https://user-images.githubusercontent.com/775083/29213419-e8ae8a2a-7eab-11e7-9377-b79aecfef054.png)

Made it a picture to preserve line number in the transpiled file.

**Comment by davehunt** [comment]
Likely a duplicate of https://github.com/mozilla/testpilot/issues/2746

**Comment by erik8752** [comment]
Yes it is a duplicate of #2746 I was probably mislead by it's title.
