### ISSUE TITLE
Improve handling of "new" badge on add-on toolbar button

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2769]
Every [4 hours](https://github.com/mozilla/testpilot/blob/master/addon/src/webextension/lib/environments.js#L42), the add-on [checks for updates](https://github.com/mozilla/testpilot/blob/master/addon/src/webextension/lib/environments.js#L76) from the site. [If there are new or changed experiments](https://github.com/mozilla/testpilot/blob/master/addon/src/webextension/lib/browserAction.js#L35) since the last time the toolbar button was clicked, a "NEW" badge is shown.

This logic could be improved:

* "New" should clear immediately on click. Currently, [the timestamp is set on click](https://github.com/mozilla/testpilot/blob/master/addon/src/webextension/lib/browserAction.js#L39), but the badge isn't updated until the next data fetch from the site. That could be up to 4 hours away.

* "New" appears even if you've visited the site, seen the content, and installed all the new experiments (see also #2747). Maybe the "New" should be cleared on any visit to Test Pilot, regardless whether it was via clicking the toolbar button

**Comment by SoftVision-PaulOiegas** [comment]
I think we should add another one to the list to cover this even better (if it can be done):
- If the user does not visit the TxP website, new experiments or doesn't clicks the toolbar button, dismiss "New" badge when the launched experiments are no longer considered "Just launched".

I have just visited a very old profile that still had the "New" badge displayed, and when I clicked the toolbar button, I was redirected on the TxP page where no experiment had "Just launched" badge. So I think we can also relate to the removal of experiments badge to dismiss also the "New" one.
