### ISSUE TITLE
Blank strings when using en-CA locale

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2770]
Looks like we're falling back to in-DOM strings on the en-CA locale (maybe others too). Related to #2753 maybe?

As an example, the "Just Launched" string ends up blank - because that DOM node is blank. The platform indicator string, however, falls back to [DOM text](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/ExperimentPlatforms.js#L29) - which differs from [the final en-US strings that we shipped](https://github.com/mozilla/testpilot/blob/master/locales/en-US/app.ftl#L156) with the feature.

If I have en-US in my list of languages in browser preferences, I see this:
![capture](https://user-images.githubusercontent.com/21687/29224943-695ca43e-7e9a-11e7-8d86-4d135d46298b.PNG)

If I remove en-US and add en-CA, I see this:
![capture](https://user-images.githubusercontent.com/21687/29224907-400d5006-7e9a-11e7-9627-2e814f5bffed.PNG)

**Comment by lmorchard** [comment]
Doing some sleuthing... with a locale of `en-CA` it looks like we:

1. [negotiate languages and end up with `["en-US"]`](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/App.js#L119)
1. [load `en-US`](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/App.js#L125)
1. [attempt to generate messages](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/App.js#L151) for `en-CA` [from `navigator.languages`](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/App.js#L165), but we never loaded anything for `en-CA` so we have no strings

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on dev and stage servers. Marking as verified.
