### ISSUE TITLE
Annotate dispatch() calls with action flow types

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2772]
While banging my head against flow-type annotations to polish #2771, I noticed something:

Our reducers ([like this one](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/reducers/addon.js#L191)) assert a type for the action parameter that's [composed of actions usually associated with that reducer](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/reducers/addon.js#L76). 

But, actions don't belong to reducers. In fact, all [slice reducers in the `combineReducers` call](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/store.js#L15) see every action passing through `dispatch()`. It's like a broadcast event - ["Multiple slice reducers can respond to the same action"](http://redux.js.org/docs/recipes/reducers/UsingCombineReducers.html).

So, ideally, slice reducers should instead be annotated to expect any one of the complete set of actions in the app - because that's what actually happens. It's up to the switch statement in each reducer to decide whether to process an action.

We're also [not asserting a type on what goes into `dispatch()`](http://frantic.im/using-redux-with-flow#dispatch) - i.e. [the disjoint union of all known action types used throughout the app as input to reducers](https://flow.org/en/docs/frameworks/redux/#toc-typing-redux-actions).

Kind of nitpicky stuff, but I think it means we're not actually guarding against incorrect action type passing through the system.

**Comment by lmorchard** [comment]
Thought some more about this. [Seems like using specific action types in reducers is fine](https://flow.org/en/docs/frameworks/redux/#toc-typing-redux-actions), practically speaking: Even though, technically speaking, *all* actions will flow through every reducer - specific slice reducer code will only deal with certain actions. (dynamic dispatch is hard to wrangle with static types)

What I think this issue should be about is wrapping up `dispatch()` calls with type annotations, because that feels like the missing piece here.

**Comment by ghost** [comment]
closing in favor of #3497
