### ISSUE TITLE
Two strings are hardcoded in the newsletter form

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/testpilot#2775]
“Your email here” placeholder is hardcoded:
<img width="461" alt="capture d ecran 2017-08-13 a 17 27 05" src="https://user-images.githubusercontent.com/1294206/29251444-c30d7810-804c-11e7-9d62-1aee7d88461d.png">

“this privacy notice” is hardcoded as well:
<img width="464" alt="capture d ecran 2017-08-13 a 17 26 56" src="https://user-images.githubusercontent.com/1294206/29251445-c33f2996-804c-11e7-936e-0f33ddc8a31a.png">

Verified on production using French.

cc @flodolo

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed now in both page newsletter and pop up newsletter that appears after installation. 👍 
Verified on French, German, Italian, Spanish and Russian.
