### ISSUE TITLE
Upgrade warning dialog improvements

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2778]
Dug around to find the warning dialog we show for #2364 and thought of some improvements:

1. The component makes direct access to browser APIs that we generally reserve for the App container. The dialog should just render all from props, because that makes tests & storybook stories easier.
1. The dialog lives in `frontend/src/app/components/View.js` - which felt like a weird spot for it, since this component is meant to just be a small layout utility wrapper. Might be better if:
    1. The dialog itself is extracted into a separate small component
    1. The App component renders the dialog
1. Once extracted and driven by props, we can wrap the dialog in a storybook story

Might just come up with a PR for this myself, but wanted to write up an issue to capture it first.

**Comment by meandavejustice** [comment]
@lmorchard Would you mind if I took this issue? I haven't touched our storybook stuff at all, think this would be a good one to get familiar with it

**Comment by lmorchard** [comment]
Sure, go for it!

**Comment by meandavejustice** [comment]
fixed in https://github.com/mozilla/testpilot/pull/2918
