### ISSUE TITLE
 Test Pilot website doesn't load on Firefox on Android

### ISSUE THREAD

**Issue by tiwoc** [mozilla/testpilot#2788]
Steps to reproduce:
1) Open Firefox on Android (tested with v55.0 on Sony Xperia X compact, 4.7").
2) Go to https://testpilot.firefox.com/
3) Wait

Actual results:
The content doesn't load. The loading animation never finishes.

Expected results:
The website content should be displayed, just like on the regular Firefox.

![screenshot_20170816-205039](https://user-images.githubusercontent.com/1260821/29380874-9a38810a-82c7-11e7-80b5-c911b0fdc91a.png)

**Comment by tiwoc** [comment]
I should add that this is neither a problem with an addon (tried it without addons) nor with my internet connection, as all other websites load normally, a laptop using the same wifi can load it just fine, and switching to cellular data doesn't help.

**Comment by lmorchard** [comment]
We just deployed fixes to localization code to production today - I suspect they may also fix this issue. But I'll leave this open until someone other than me can verify

**Comment by tiwoc** [comment]
Just tried it again on Firefox 55.0.2 on Android: Nothing has changed :-/

**Comment by grahamperrin** [comment]
Reproducible with 55.0.2 and Beta 55.0 on Android 6.0.1.

**Comment by grahamperrin** [comment]
**Not** reproducible with Firefox 56.0 on Android 6.0.1.

**Comment by tiwoc** [comment]
Yes, works for me with 56.0.
