### ISSUE TITLE
META: Measurement and Assets for Photonized Test Pilot website

### ISSUE THREAD

**Issue by Pekochen** [mozilla/testpilot#2789]
Here is the link for the measurement 
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Testpilot_Homepage/
assets:
https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Website/00_Assets/Photonized_homepage
Thanks

**Comment by ChenMorpheus** [comment]
This is the overview for homepage redesign. We'll provide the rest of pages, including detail page, other elements and different cases based on this [document](https://docs.google.com/spreadsheets/d/1ZtT_MTjoC3VxVTdVWOgmCDUqJJXF_HFR_oy7xjv2NWM/edit#gid=0). 
@johngruen @clouserw Could we have a meeting to go through the design and check if we miss something here? Thanks.

**Comment by johngruen** [comment]
@ChenMorpheus @Pekochen sounds good to me. I'm going to speak to @fzzzy about getting the ball rolling here today.

**Comment by johngruen** [comment]
@ChenMorpheus I think it would be useful to provide an overview of the various changes you're requesting in this bug so @fzzzy has a clear list.

@fzzzy Let's open up a new dev branch so we can start to preview this work as it comes in.

**Comment by Pekochen** [comment]
Component: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/

Homepage:https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/

Detail page:https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Detailpage_20170927/
@johngruen , @fzzzy Please check these links for the rest of pages.
Thanks~

**Comment by ChenMorpheus** [comment]
Let me give some context here. 
For each link, you can click "all artboards" on the top-left corner to switch to different measurements, including full-page mockups, various elements, and responsive design. For instance:

Homepage_20170927 (Full-page mockups)
- Introduction
- Latest updates
- Experiment cards
- Newsletter footer
- Responsive

Note that "number of participants" seems to be removed on the current website, so just ignore the information in these measurements (see the attached screen as an example). 

![group 7](https://user-images.githubusercontent.com/18019946/30904771-81608a84-a3a5-11e7-8ca0-106566adf2bb.png)

We've tried our best to collect as many screens as possible, but I believe there must be crucial screens left out. Please let us know if we need to provide some missed screens, thanks.

**Comment by SoftVision-PaulOiegas** [comment]
@ChenMorpheus Maybe pages like:
https://testpilot.firefox.com/share
https://testpilot.firefox.com/retire
https://testpilot.firefox.com/fourohfour
https://testpilot.firefox.com/legacy

Not sure if we still need the "legacy" page, but the "share" page should definitely need a new look too. 😄

**Comment by fzzzy** [comment]
Thanks. I'm going to be OOO next week because I am getting married, but maybe someone else can take a look at this. Otherwise I'll start on it when I get back.

**Comment by ChenMorpheus** [comment]
@SoftVision-PaulOiegas @fzzzy We've updated the measurement to include the pages below: 

> @ChenMorpheus Maybe pages like:
https://testpilot.firefox.com/share
https://testpilot.firefox.com/retire
https://testpilot.firefox.com/fourohfour
https://testpilot.firefox.com/legacy

Please find the link below for the measurement, thanks.

Component: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/

![component_20171003-modal](https://user-images.githubusercontent.com/18019946/31121074-6a313470-a7fc-11e7-8908-a237ff5defff.png)

**Comment by fzzzy** [comment]
Let's move this to the next sprint.
