### ISSUE TITLE
Implement "Tour Idea Town" flow

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#279]
Currently it doesn't look like the ["Tour Idea Town"](https://github.com/mozilla/idea-town/blob/8e98c7963b58349cd4a1638df9b96f3672dd7a2f/idea_town/frontend/static-src/app/views/settings-menu-view.js#L16) link in the settings drop down menu on http://idea-town-dev.elasticbeanstalk.com/home does anything.

Not sure if we want to add that before Mozlando, or maybe just hide the option.

**Comment by meandavejustice** [comment]
@johngruen Assuming this is complete with the new UI changes?
