### ISSUE TITLE
Hardcode image dimensions in HTML templates or move to CSS?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#280]
via https://github.com/mozilla/idea-town/issues/257#issuecomment-157503352

---

Should we be hardcoding image dimensions in the HTML templates, or leave that in the CSS?
1. [`<img data-hook="thumbnail" src="" width="260">`](https://github.com/mozilla/idea-town/blob/6526f8f58b52596c871df8aa644c02e326350508/idea_town/frontend/static-src/app/templates/experiment-page.js#L22)
2. [`<img class="avatar" data-hook="avatar" width="56" height="56">`](https://github.com/mozilla/idea-town/blob/1072c7dd4110bead7fa8fc33905d965f45f28c6f/idea_town/frontend/static-src/app/views/contributor-view.js#L5)
3. [`<img data-hook="detail-image" width="680">`](https://github.com/mozilla/idea-town/blob/1072c7dd4110bead7fa8fc33905d965f45f28c6f/idea_town/frontend/static-src/app/views/detail-view.js#L7)

**Comment by pdehaan** [comment]
Looks like these are the only 3 references to `height=` and `width=` in the HTML templates:

``` sh
$ egrep -irn ' (width|height)=' .

./app/templates/experiment-page.js:22:  <img data-hook="thumbnail" src="" width="260">
./app/views/contributor-view.js:5:  <img class="avatar" data-hook="avatar" width="56" height="56">
./app/views/detail-view.js:7:  <img data-hook="detail-image" width="680">
```

**Comment by clouserw** [comment]
John is doing this in his responsive design
