### ISSUE TITLE
Add general feedback survey to Footer

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2806]
Per @sbautista's research, let's add a link to the site footer in Test Pilot to a general feedback survey. 

Here's the URL to link to: 
https://qsurvey.mozilla.com/s3/test-pilot-general-feedback

<img width="588" alt="screen shot 2017-08-21 at 11 55 50 am" src="https://user-images.githubusercontent.com/3323249/29527720-be0b80a2-8667-11e7-95e2-8f69801e3199.png">

**Comment by SoftVision-PaulOiegas** [comment]
The "Give Feedback" text button appears on all pages (/experiments, /share, /legacy), except on "About Test Pilot", "Privacy" and "Terms" pages. 
Tried to verify also the 404 page, but it does not load because of the Homepage loading issue. Reopening issue.

**Comment by SoftVision-PaulOiegas** [comment]
The "Give Feedback" text button was added on missing pages and correctly works.
