### ISSUE TITLE
Hide empty elements on experiment details pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#281]
via https://github.com/mozilla/idea-town/issues/258#issuecomment-157508739

---

> @lmorchard: _"Hmm, though we should probably hide the elements if they're optional and not filled in (like Contribute, also)"_

**Comment by lmorchard** [comment]
https://github.com/meandavejustice/idea-town/commit/26e3e207f2cac4351a446b2bdab78b4724800c96
