### ISSUE TITLE
Stars in feedback surveys are very blurry

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#2813]
The stars and cancel 'X' in our feedback surveys are very blurry. Need higher-res assets.

<img width="273" alt="screen shot 2017-08-23 at 1 16 29 pm" src="https://user-images.githubusercontent.com/473531/29629056-7bf59d52-8805-11e7-920a-c38862389237.png">

Icons available here: http://design.firefox.com/icons/viewer/

**Comment by johngruen** [comment]
Those don't come from us, they come from SG...I'm not sure we'd be able to change those assets :(

**Comment by sevaan** [comment]
We could file a support ticket, but I don't have access to the SurveyGizmo account to do that. https://help.surveygizmo.com/help/surveygizmo-support-hours#how-do-i-get-help-contact-support-

**Comment by sevaan** [comment]
Support ticket filed (Case # 00066968).

**Comment by sevaan** [comment]
From the Customer Support Specialist:

> Hi there!
> 
> Thanks for that screenshot. I can see that they can appear a bit blurry, especially when enlarged. 
> 
> I would be happy to put a request in with our development team to see if they are able to assist with this. Unfortunately, I can't say right away if this is a request that we could act on right away so I'm not able to provide a timeline on a fix like this but this is definitely a good start! 
> 
> I'll send that request over to our team and will keep you posted if we're able to make that change. 
> 
> Thanks!
