### ISSUE TITLE
Min Vid

### ISSUE THREAD

**Issue by moonundermood** [mozilla/testpilot#2816]
I can't choose my decision and  I can't send my screenshot

**Comment by SoftVision-PaulOiegas** [comment]
Hi @moonundermood! Sorry but we cannot understand your issue. From the title it looks like it's something related to MIn Vid. Can you please give us more details about it?

**Comment by moonundermood** [comment]
Yes, sorry. I can't move this window. It happens with all videos on YouTube. What should I do?

**Comment by SoftVision-PaulOiegas** [comment]
The Min Vid player window can be moved by dragging it from the area between the top buttons.
Here is a recording of of how to do it https://goo.gl/bd2SG5. 

If you still cannot move it, please let us know what operating system are you using, and what version of Firefox, so we can try to reproduce your issue.

**Comment by johngruen** [comment]
I am closing this issue, @moonundermood if you are still having difficulties, please add this issue here: 
https://github.com/meandavejustice/min-vid
