### ISSUE TITLE
Odd experiment layout with 5 items

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#282]
Currently http://idea-town-dev.elasticbeanstalk.com/home looks a bit ridiculous (mainly because I'm an idiot and added a bunch of edge case data).
But I noticed that the experiments lay out a bit funky when there are 5 items. Not sure if the 5 items is significant, or if it's a weird layout issue because of my silly data-set, but I can still reproduce the issue if I edit the "Experiment the third which has a longer title" description in devtools to only be 2 lines.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11258338/038c1092-8e0d-11e5-816d-ab206e53c7cd.png)
**Figure 1:** What the what? Why isn't my "Experiment number five" (aka: "Jake") experiment under the "Peter is a fraud" experiment?

---

![idea_town](https://cloud.githubusercontent.com/assets/557895/11258357/3855e460-8e0d-11e5-94a1-28f697f9bd62.png)
**Figure 2:** Even with the modified description for experiment number 3, the items still wrap oddly. Not sure if this is some Flex-box justification thing.

**Comment by pdehaan** [comment]
I forgot to add that the layout gets even weirder at <1024px wide, where the bottom row of 2 experiments shift a bit more to the center of the page:

![idea_town_and_odd_experiment_layout_with_5_items_ _issue__282_ _mozilla_idea-town_and_force_square_ish__thumbnails_and_fix_invalid_html_markup_by_pdehaan_ _pull_request__277_ _mozilla_idea-town_and_1__pdehaan_pdehaan____dev_github_idea-town](https://cloud.githubusercontent.com/assets/557895/11259137/f6b2ac80-8e13-11e5-8b29-a7ae565df201.png)

**Comment by pdehaan** [comment]
At 788px wide, the experiments shrink to a single column:
![idea_town](https://cloud.githubusercontent.com/assets/557895/11259253/fe50cf7a-8e14-11e5-857f-a3206ec331e5.png)

**Comment by meandavejustice** [comment]
closing since new ui has much simpler layout.
