### ISSUE TITLE
Automate Storybook S3 bucket clean up

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2820]
Currently, there is nothing cleaning up old Storybook deployments in the S3 bucket for http://testpilot-storybook.dev.mozaws.net. I think they're about 20MB each - so, not an urgent disaster looming, but it would be polite to clean up after ourselves.

Maybe we can build something in AWS Lambda that deletes old Storybook deployments by some criteria. Maybe age, maybe closed branch / merged PR. Could trigger a handler every time there's a new deployment.

**Comment by fzzzy** [comment]
Age seems simplest and probably good enough.

**Comment by ghost** [comment]
S3 buckets can have lifecycle policies.  Let's just have it delete objects over 100 days old?

**Comment by lmorchard** [comment]
Added a lifecycle rule for this, though I haven't seen it take effect yet:

![capture](https://user-images.githubusercontent.com/21687/38958824-5e278a32-432c-11e8-846e-6e504a05a966.PNG)

**Comment by lmorchard** [comment]
Going to close this - I see that these rules happen once a day, so I'll check back tomorrow and reopen if it hasn't happened.

**Comment by lmorchard** [comment]
Circled back to check today and things look good. The oldest objects are from late January, and the list of per-commit build directories are down by about half.
