### ISSUE TITLE
containers

### ISSUE THREAD

**Issue by jeanettel6740** [mozilla/testpilot#2825]
Hi 
Containers has stopped working and I dont kwo why. I have uninstalled and re-installed firefox and it has not helped.
I have diabled and re-enabled them too.
Please help me get containers up and running again.

**Comment by SoftVision-EmilPasca** [comment]
@jeanettel6740 Thank you for submitting this issue.
Can you please give us more details about your system, such as what Firefox version you have installed, operating system and other addons you may have installed?

**Comment by johngruen** [comment]
Hi @jeanettel6740 Containers has now graduated from Test Piulot and can be installed from the Add-on Marketplace!

https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/
