### ISSUE TITLE
Min Vid Player Problem

### ISSUE THREAD

**Issue by SpeedyGC** [mozilla/testpilot#2835]
In the latest update of Min Vid Player, it won't float above other open firefox windows. It can appear, but when I click on other tabs, it goes into the background.

**Comment by pdehaan** [comment]
@SpeedyGC Thanks for the bug report! I've filed this in the **min-vid** repo at https://github.com/meandavejustice/min-vid/issues/1023.

Closing in favor of upstream bug.
