### ISSUE TITLE
Test Pilot site misbehaves with SeaMonkey

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot#2837]
SeaMonkey 2.48 on FreeBSD-CURRENT. 

## `testpilot.firefox.com`

<https://testpilot.firefox.com/>: 

![2017-09-05 18 57 45 firefox test pilot](https://user-images.githubusercontent.com/192271/30075253-42818c5e-926c-11e7-8a89-03259bd7b5f1.png)

## `testpilot.dev.mozaws.net`

https://github.com/mozilla/testpilot/issues/2298#issuecomment-285429044 (2017-03-09) mentioned a telemetry-related patch and <https://testpilot.dev.mozaws.net/>, here's a current shot of that URL: 

![2017-09-05 18 58 08 firefox test pilot](https://user-images.githubusercontent.com/192271/30075279-60e855d8-926c-11e7-9f0c-d561e504ba05.png)

If I change `general.useragent.compatMode.firefox` from `true` (the default) to `false`, then I can progress to pages such as <https://testpilot.dev.mozaws.net/experiments/send>: 

![2017-09-05 19 07 05 firefox test pilot - send](https://user-images.githubusercontent.com/192271/30075477-74789b2a-926d-11e7-9b6f-0126c9802da5.png)

## Related

[Define browser support matrix · Issue #2563 · mozilla/testpilot](https://github.com/mozilla/testpilot/issues/2563)

**Comment by ghost** [comment]
The production site will be updated to what you saw on the dev site tomorrow.  Since that renders without error we're calling this fixed.  Thanks

**Comment by grahamperrin** [comment]
Hmm, no go here with SeaMonkey 2.49.1. Just me? Should the issue be reopened? 

![2017-10-10 21 55 24](https://user-images.githubusercontent.com/192271/31410109-dcc10092-ae05-11e7-8255-7003741a0c67.png)

PS I forgot, `general.useragent.compatMode.firefox` was `false`. Now reverted to `true` (the default) and still, no go with the Test Pilot site content.

**Comment by fzzzy** [comment]
@grahamperrin Are you still seeing the loader screen? There must be an issue with stale cache if so.

**Comment by grahamperrin** [comment]
Control-F5 reloaded after that change of boolean so I doubt it, but I'll restart the browser etc. and tell what happens.

**Comment by grahamperrin** [comment]
Restarted SeaMonkey, removed cookies for `firefox.com`, <kbd>Control</kbd>-<kbd>F5</kbd>, still no go. 

The symptom now differs from the shot in [the opening post](https://github.com/mozilla/testpilot/issues/2837#issue-255362744). Now there's just the starry sky, no loader. Should I create a separate issue?

PS no go in safe mode, either. <https://testpilot.firefox.com/experiments> just a starry sky.

**Comment by fzzzy** [comment]
Might as well just reuse this issue.

**Comment by johngruen** [comment]
@grahamperrin we've decided to kill support for ESR 52 unfortunately. This means SeaMonkey won't be supported going forward. There's simply too much delta btwn Quantum and current ESR for our team to support both. I am not familiar with the SeaMonkey roadmap WRT future ESR releases, but we have every intention of supporting ESR 59. Closing this for now! :(
