### ISSUE TITLE
The element `button` must not appear as a descendant of the `a` element.

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#284]
Ref: https://github.com/mozilla/idea-town/issues/267#issuecomment-157606828

---

> Also seeing a couple warnings in [/idea_town/frontend/static-src/app/templates/landing-page.js](https://github.com/mozilla/idea-town/blob/4b60baf1f25c9f6e6fb0b462faa977f77248bdaa/idea_town/frontend/static-src/app/templates/landing-page.js) [against https://html5.validator.nu/]
> 
> > **Error:** The element `button` must not appear as a descendant of the `a` element.
> > From line 27, column 55; to line 27, column 85
> > 
> > ``` html
> > xt=/home"><button class="button primary">Sign m
> > ```

This dirty little grep seems to say there are 3 places we're doing an apparently frowned upon `<a><button/></a>` type nesting:

``` sh
$ grep -irn "</button></a>" .

./app/templates/account-inactive-page.js:9:  <a href="/"><button class="button primary">Home</button></a>
./app/templates/landing-page.js:21:  <a href="/accounts/login/?next=/home"><button class="button primary">Sign me up!</button></a>
./app/templates/landing-page.js:33:  <a href="{{ downloadUrl }}"><button class="button large primary">Install the Add-on</button></a>
```

**Comment by meandavejustice** [comment]
Looks like this has been fixed
