### ISSUE TITLE
Mention extensions.legacy.enabled in the quickstart

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#2843]
For local development of the addon, which is not signed with the mozilla key, we now need the extensions.legacy.enabled true pref. This is mentioned in the addon README, but we should also mention it in the quickstart.

**Comment by CHBaker** [comment]
I'll take this issue

**Comment by himanish-star** [comment]
@CHBaker you still working on this ? Or can I fix this

**Comment by CHBaker** [comment]
Oh, I thought I already pushed it but I guess I forgot... sorry about that. yeah **you can take it** @himanish-star

**Comment by divyabaid16** [comment]
@himanish-star are you still working on this issue ? Or can I fix it ?

**Comment by himanish-star** [comment]
@divyabaid16 , I'm still waiting for a confirmation. I will file a PR for this as soon as I get a confirmation

**Comment by fzzzy** [comment]
@himanish-star @CHBaker said you could take it. Go for it.

**Comment by himanish-star** [comment]
@fzzzy , on it.
