### ISSUE TITLE
Duplicate `id` in experiment-page template

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#285]
Ref: https://github.com/mozilla/idea-town/issues/267

I addressed the unclosed tags in #277 PR, but the duplicate `id` field error still remains when trying to lint the template against https://html5.validator.nu/

> **Error:** Duplicate ID details.
> [From line 12, column 7; to line 12, column 24](https://github.com/mozilla/idea-town/blob/11da23fb24504fcef28397c564aa745673840b28/idea_town/frontend/static-src/app/templates/experiment-page.js#L5)
> 
> ``` html
> er>      <div id="details">
> ```
> 
> **Warning:** The first occurrence of ID details was here.
> [From line 10, column 5; to line 10, column 54](https://github.com/mozilla/idea-town/blob/11da23fb24504fcef28397c564aa745673840b28/idea_town/frontend/static-src/app/templates/experiment-page.js#L3)
> 
> ``` html
> age">    <section id="details" data-hook="experiment-page">
> ```

**Comment by lmorchard** [comment]
https://github.com/mozilla/idea-town/commit/86fd0edaf31f7e2f855ecb46f6dd976be85a10ae
