### ISSUE TITLE
Visisting https://screenshots.firefox.com/shots says 500 Internal Server Error

### ISSUE THREAD

**Issue by niyali** [mozilla/testpilot#2855]
Not sure where you host the server and who is responsible for backend. 
But there's 500 error when visiting https://screenshots.firefox.com/shots as attached screenshot for your information. 
Thought you might want to take a look at it. 

Thank you. 

<img width="367" alt="screen shot 2017-09-11 at 2 27 56 pm" src="https://user-images.githubusercontent.com/1436482/30261080-78e7de34-96fd-11e7-8406-c8a29ef1d990.png">

**Comment by SoftVision-CosminMuntean** [comment]
@niyali thanks for reporting this!

This is a known issue and it's already logged in Screenshots repository: [#2520](https://github.com/mozilla-services/screenshots/issues/2520).
If you have more information please add a comment in the issue.

Also, if you find other issues related to Screenshots, please log them [here](https://github.com/mozilla-services/screenshots/issues).
