### ISSUE TITLE
Icon is hard to see in light theme

### ISSUE THREAD

**Issue by davehunt** [mozilla/testpilot#2858]
As mentioned in the similar issue for the dark theme (#2832), the light theme icon is also hard to see due to the lack of contrast:

<img width="177" alt="screenshot 2017-09-12 16 50 54" src="https://user-images.githubusercontent.com/122800/30347723-00636f4e-97db-11e7-8b76-5d082b0c7390.png">

**Comment by fzzzy** [comment]
This is now fixed in addon version 2.0.4, which has been deployed to production.
