### ISSUE TITLE
Multi-Account Containers addon - Add option to color whole tab to indicate container type

### ISSUE THREAD

**Issue by Vardoger** [mozilla/testpilot#2862]
The current, and only, option for a Multi-Account Container tab is to underline the tab with a specific color. 

With multiple addons installed, and the bloom of color from websites broadly, page text, page pictures, and addon icons, the tab underline feels like it fades into the background and is not as easily identifiable when juggling multipe accounts.

While the underline option should stay for those who perhaps prefer that more minimalist feel,  there could be a checkbox option added in the Multi-Account Container toolbar dropdown menu to enable coloring the whole tab the color of applicable container type.  

This may aid more easily seeing the segmentation of different container types across multiple tabs.

**Comment by johngruen** [comment]
@Vardoger thanks for the suggestion, i am going to close this here and add it directly to the containers repo

**Comment by johngruen** [comment]
@Vardoger filed here: https://github.com/mozilla/testpilot-containers/issues/828
