### ISSUE TITLE
[Stage server] Test Pilot button is no longer added in browser toolbar on latest Nightly

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2864]
[Notes]:
- The issue is not reproducible on Test Pilot dev server.
- Also, is not reproducible on Firefox 55.0.3 release and Beta 56.0b12 where the "extensions.legacy.enabled" boolean pref is set to "true" by default.

[Affected versions]:
- Nightly 57.0a1, Build ID: 20170917220255

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "testpilot.env" string type pref was manually added in "about:config" page with "stage" value on a new clean profile.
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value. 
- The "extensions.legacy.enabled" boolean  pref is set to "true".

[Steps to reproduce]:
1. Start the latest Nightly browser with the profile from prerequisites.
2. Navigate to "https://testpilot.stage.mozaws.net/" page.
3. Click the "Install the Test Pilot Add-on" button.
4. After the installation is completed, observe the browser toolbar.

[Expected result]:
- Test Pilot button is added in browser toolbar.

[Actual results]:
- The Test Pilot icon is no longer added in browser toolbar.

[Additional Notes]:
- If the "extensions.legacy.enabled" boolean pref is set to false, the add-on is automatically disabled.
- Here is a screenshot with browser console errors:
![no test pilot icon](https://user-images.githubusercontent.com/19226534/30545584-bb61302c-9c92-11e7-8ff7-a6ab2411327c.png)
- Here is a screen recording with the issue:
![no test pilot icon](https://user-images.githubusercontent.com/19226534/30545593-c145a540-9c92-11e7-9822-1245b3f14a27.gif)

**Comment by johngruen** [comment]
@SoftVision-CosminMuntean is it in the customize menu?

**Comment by SoftVision-CosminMuntean** [comment]
@johngruen it's not there. It seems it does not appear in any place.

**Comment by lmorchard** [comment]
I *think* we fixed this after getting stage up-to-date with the current add-on version

**Comment by SoftVision-PaulOiegas** [comment]
You are right. Just verified on all 3 servers and the button correctly appears on all 3 servers.
