### ISSUE TITLE
[Enhancement] The "Blog" button should be displayed even if the Test Pilot add-on is not installed 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2877]
**[Notes]:**
- For the cases when a user of Firefox or other browser wants find more details about Test Pilot before installing it.

**[Affected versions]:**
- Firefox 55.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Look for "Blog" button on top of the "Test Pilot" homepage.
3. Navigate to https://testpilot.firefox.com/experiments page and look for the "Blog" button.
4. Install Test Pilot add-on and look again for the "Blog" button on both pages.

**[Expected result]:**
- The "Blog" button is displayed on both pages with or without the Test Pilot add-on installed. 

**[Actual result]:**
- The "Blog" button is not displayed on Test Pilot "Homepage" or "Experiments" page without Test Pilot add-on installed.

**Comment by ChenMorpheus** [comment]
To be honest, I don't know who added the "Blog" button there. However, that's a good design, and I think it's an excellent approach to display it even if users don't install the add-on. It could provide an entry point to promote our channel and experiment.

**Comment by marvinsanchez1** [comment]
Hi @ChenMorpheus , I am a student at Seneca College. I'm currently taking a open source course, looking for my first bug. If this bug is not assigned to someone, can I work on it for my assignment?
+ I already made so that "Blog" appears on the home page and even if you haven't install the Test Pilot Add-on

Thank you!

**Comment by ChenMorpheus** [comment]
I would suggest asking Wil for this question. @clouserw What do you think?

**Comment by fzzzy** [comment]
@msanchez5 I was about to do it but didn't start yet. Go ahead!

**Comment by SoftVision-CosminMuntean** [comment]
I have tested this on Test Pilot dev server and the "Blog" button is also correctly displayed even if the Test Pilot add-on is not installed. Closing this as verified fixed.
