### ISSUE TITLE
Test Pilot toolbar button is just an empty placeholder on Firefox 52 to 54 including ESR 52.0 to 52.4.0

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2878]
**[Affected versions]:**
- Firefox ESR 52.0 to 52.3.0 (releases)
- Firefox ESR 52.4.0 (candidate)
- Firefox 52.0

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser with a new profile and navigate to https://testpilot.firefox.com page.
2. Choose to install Test Pilot add-on.
3. Observe the Test Pilot toolbar button.

**[Expected result]:**
- Test Pilot toolbar button is correctly added and looks like the platform logo (spaceship).

**[Actual result]:**
- Test Pilot toolbar icon is just an empty placeholder.

![txp esr icon](https://user-images.githubusercontent.com/17258026/30816326-5d622828-a21e-11e7-8fe8-e1f650be9be4.png)

**Comment by SoftVision-PaulOiegas** [comment]
After testing on Nightly using Mozregression tool, I found out that this is more spread than I thought. It affects our button starting with Firefox 52 and ending with Firefox 55 (2017-03-14 Nightly build).

Managed to find a regression window and it seems that something from Bugzilla bug [1058040](https://bugzilla.mozilla.org/show_bug.cgi?id=1058040) has fixed it. 
Here is the pushlog link: https://goo.gl/eqDhjd.

Since this was working before I assume that we also changed something that affected this on our end.

**Comment by SoftVision-PaulOiegas** [comment]
Sadly, this issue still reproduces on Fx 54. 👎 
I've verified this on Fx 54 release unbranded build since the dev add-on cannot be installed on 54 release even with all the 5 prefs set. And I also double checked on a Nightly 54 build (2017-02-12) and the result was the same.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas UGH

**Comment by johngruen** [comment]
Relevant: https://bugzilla.mozilla.org/show_bug.cgi?id=1396462

**Comment by johngruen** [comment]
This is not in our OFFICIAL support matrix™
