### ISSUE TITLE
Test Pilot is no longer supported in Firefox 50.0 which is specified as minimal supported version

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2879]
**[Affected versions]:**
- Firefox 50.0

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox 50.0 browser with a new profile and navigate to https://testpilot.firefox.com page.
2. Choose to install Test Pilot add-on.
3. Open a new tab and navigate to "about:addons" page.
4. Click on "Extensions" section and observe the Test Pilot add-on state.

**[Expected result]:**
- Test Pilot add-on is displayed as enabled.

**[Actual result]:**
- Test Pilot add-on is displayed as incompatible with Firefox 50.0

**[Notes]:**
- Even if it's disabled by default, the website works and experiments can be enabled.
- Test Pilot toolbar button is also not displayed since the add-on is disabled ad installation. 

![firefox 50 not supported anymore](https://user-images.githubusercontent.com/17258026/30816844-c216b5ee-a21f-11e7-9627-142c27d519a9.png)

**Comment by ghost** [comment]
Most of our users are on 54/55/56/57.  ESR is 52 and is ~4% of our visitors.

Let's make this a rolling release-1.  We already have a minimum of 50, lets just update that.

**Comment by lmorchard** [comment]
I *think* this is where the site-wide minimum version is configured:

https://github.com/mozilla/testpilot/blob/master/frontend/src/app/config.js#L3

**Comment by SoftVision-PaulOiegas** [comment]
Don't forget that we have a string for this, which is displayed on older versions than supported. That needs to be updated too. Last time we forgot to.

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas Actually last time when we forgot to update the string, I changed the implementation so that it does not hard code the version number in the string, but instead pulls it from config.minFirefoxVersion :-)

**Comment by SoftVision-PaulOiegas** [comment]
Sneaky 😄

**Comment by SoftVision-PaulOiegas** [comment]
Verified this on dev server using Fx 50, Fx 52.4.0 ESR, Fx 53 and Fx 54 and it behaved as expected on each of the versions.
Also, the string is indeed updated.
