### ISSUE TITLE
<esc> to exit modals

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#2888]
I want to be able to hit <esc> and exit our modals

**Comment by kgeorgiou** [comment]
Hello @meandavejustice - is someone working on this or shall I pick it up?

Also, how about:
- `ArrowLeft` and `ArrowRight` keys for going through the steps of tour dialogs?
- `Enter` key for done/continue/submit actions in modals?

**Comment by SoftVision-PaulOiegas** [comment]
Hi @kgeorgiou, I don't think someone is working on this and don't see anyone assigned to it either. I think it's ok if you pick it up.
Regarding to your proposal of extended keyboard actions support, let's see what @johngruen  has to say about this,

**Comment by johngruen** [comment]
@kgeorgiou love it!
