### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2894]
[React 16 was released](https://reactjs.org/blog/2017/09/26/react-v16.0.html?utm_source=reactnl&utm_medium=email), and it looks like a lot of good stuff. [I started a branch to try upgrading](https://github.com/lmorchard/testpilot/tree/react-16). 

But, I ran into at least one dependency issue - [`html-react-parser` seems to need an upstream fix](https://github.com/remarkablemark/html-react-parser/issues/43).

So, I'm filing this issue and deferring further work on an upgrade for now. There might be more dependencies that need upgrades.

**Comment by remarkablemark** [comment]
@lmorchard [`html-react-parser@0.4.0`](https://github.com/remarkablemark/html-react-parser/tree/v0.4.0) has been released:
```sh
# npm
npm install html-react-parser@0.4.0 --save

# yarn
yarn upgrade html-react-parser@0.4.0
```

You can find details regarding the fix in the [original issue](https://github.com/remarkablemark/html-react-parser/issues/43). Let me know if you encounter any more issues when upgrading.

**Comment by lmorchard** [comment]
@remarkablemark Thanks so much for the follow-up comment over here!

**Comment by lmorchard** [comment]
Hacked at this a little more. Looks like the site builds successfully without errors, and seems functional on a brief bit of clicking through. But, we now have 16 or so frontend test failures to figure out

**Comment by chuckharmston** [comment]
https://blog.discordapp.com/lessons-from-migrating-a-large-codebase-to-react-16-e60e49102aa6
