### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by mikelmasek** [mozilla/testpilot#2895]
I really liked the vertical tabs. I am using version 57.0b, and for some reason they don't work anymore. I think they were part of test pilot or were an add-on.

Please tell me how I can get them back. Thanks!

**Comment by chuckharmston** [comment]
The Tab Center experiment has unfortunately been retired. But you do have a few options for Vertical Tabs in 57!

- [Tree Style Tab](https://addons.mozilla.org/firefox/addon/tree-style-tab/) is a favorite of power users, while;
- [Tab Center Redux](https://addons.mozilla.org/firefox/addon/tab-center-redux/) is closer in experience to the Tab Center experiment on Test Pilot.

**Comment by mikelmasek** [comment]
Thanks, Chuck – I used the Redux option, and it’s fine, except for it not being removed from the normal location of the tabs (which it looks like is being addressed already)

 

Mike
