### ISSUE TITLE
[Dev] Graduated experiments details page wrongly contain the enable option and most of them can be enabled together with Test Pilot

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2899]
**[Notes]:**
- It seems that this is a regression caused by #2875 PR.
- The experiments that had a final report no longer have it (Universal Search, NoMore404s and Tracking Protection).
- With the install functionality returned to the graduated experiments, you can enable all graduated experiments except Universal Search.

**[Affected versions]:**
- Nightly 58.0

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down on the Homepage and click the "View Past Experiments" button under the last active experiment.
3. After past experiments cards are displayed, open them all in new tabs.
4. Select each tab and observe the graduated experiments details page.

**[Expected result]:**
- The graduated experiment old details page is displayed without the install part that is displayed for active experiments.

**[Actual result]:**
- Graduated experiments details pages are wrongly containing the install part along with Test Pilot add-on.

![grad experiment detaisl page](https://user-images.githubusercontent.com/17258026/31134002-a8d078b8-a869-11e7-9789-4f505183a030.png)
![enabled graduated](https://user-images.githubusercontent.com/17258026/31134062-d61cf684-a869-11e7-9bc3-36d12d45fe30.png)

**Comment by lmorchard** [comment]
Taking a look at this today

**Comment by SoftVision-PaulOiegas** [comment]
The top part was correctly removed on dev server so I'm marking this as verified fixed. 👍 
However, I've found another problem with unneeded info on graduated experiments pages, see #2927.
