### ISSUE TITLE
Release 2017-10-03 on stage

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2900]
Hi guys,

We have finalized testing the stage server and we a 95% pass rate on our tests (https://goo.gl/6LrAxJ).

Here are the testing results:

**New Issues**
#2897 - Uninstalling Test Pilot add-on randomly leaves you on the same page instead of "Retire" (NORMAL)
-This issue is also reproducible on production

**Reopened Issues**
#2473 - Experiments images are not displayed on Facebook and Activity Stream one is not displayed on Twitter (MINOR)
-Reproducible on stage and production servers

**Known Issues**
#2866 - Test Pilot website still looks as if it's add-on is installed, after manually disabling it from (NORMAL)
#2848 - Voice Fill and Notes are wrongly enabled on unsupported Fx version when installed together with Test Pilot add-on (MINOR)
#2829 - Test Pilot webextensions installation occurrences are not removed at tab close from "about:addons" page (MINOR)
 
Since issue #2897 is also reproducible on production and we haven't found other new issues, from the QA point of view we are good for deploying to production. 

Regards,
Cosmin

**Comment by ghost** [comment]
@lmorchard going to push today

**Comment by SoftVision-CosminMuntean** [comment]
This is already in production.
