### ISSUE TITLE
The "Install" word is wrongly localized as "Inslatar" on "Experiment details" page for Spanish [es] and [es-es] locales

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2906]
**[Affected versions]:**
- Nightly 56.0 and above

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux 

**[Prerequisites]:**
- On a new profile, add Spanish [es-es] language for page content from "Options > General > Language and Appearance > Language".

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the "Install the Test Pilot Add-on" green button Spanish localization.
3. Scroll down and click on one of the active experiments cards.
4. Observe the "Install Test Pilot & Enable <experiment_name>" green button Spanish localization.

**[Expected result]:**
- On both pages, the localization is correct.

**[Actual result]:**
- On the "Experiment details" page, the Install word is wrongly localized as "Inslatar" instead of 'Instalar". 

![inslatar](https://user-images.githubusercontent.com/17258026/31178983-568e7ac2-a923-11e7-85ba-63e6ad7bb66c.png)

**Comment by johngruen** [comment]
FIxed by #2908

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed now, verified on all servers. Nobody is "insaltar-ing" anymore. 👍
