### ISSUE TITLE
Text under download button has "Terms of Use" and "Privacy" in English

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#2911]
https://testpilot-l10n.dev.mozaws.net/experiments/containers

The Italian text displayed is "Procedendo accetti i Terms of Use e l’Privacy Notice di Test Pilot."

No clue why the original translations (`landingLegalNotice = Procedendo accetti i <a>termini d’uso</a> e l’<a>informativa sulla privacy</a> di Test Pilot.`) is changed like this.
https://github.com/mozilla/testpilot/blob/master/locales/it/app.ftl#L42

It happens for all languages, also on production.

CC @stasm

**Comment by lmorchard** [comment]
Sounds like the issue @johngruen noticed over here https://github.com/mozilla/testpilot/pull/2905#discussion_r142644755

I'm not entirely up on how links work in react-fluent, but maybe merging that PR will be a fix?

**Comment by lmorchard** [comment]
Merged #2905 to master. Will be doing a merge from master to l10n to pick up new strings in a few minutes. Maybe that will address this for now?

**Comment by johngruen** [comment]
@lmorchard @flodolo yeah i think i fixed that on master.

**Comment by SoftVision-PaulOiegas** [comment]
I can confirm too that this is fixed on dev server. 👍
