### ISSUE TITLE
Handle WebExtension Installation Cancel and Send Event to GA

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2913]
Currently we do not handle the following case: 

### STR

1. Go to the Voice Fill Experiment Page
2. Click `Enable Voice Fill`
3. On the webExtension Install dialog, click `Cancel`
![screen shot 2017-10-06 at 1 30 54 pm](https://user-images.githubusercontent.com/3323249/31277823-ae5f2918-aa9a-11e7-8989-4ea0bb9e95f2.png)

### Expected

The `Enable Voice Fill` Button should revert to its pre-installed state and an event should be emitted indicating that the user opted out of experiment installation.

```
ec: ExperimentDetailsPage Interactions
ea: Cancel From Permission
el: {experiment title}
```

Additionally in order to understand how cancels compare to installations, we should also record each time a user accepts installation from the permission dialog.

```
ec: ExperimentDetailsPage Interactions
ea: Accept From Permission
el: {experiment title}
```

### Actual

The `Enable Voice Fill` button barberpolls until page reset and the test pilot icon sheds a tear.

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen I think I've seen this before. Isn't this related to #2697?

**Comment by johngruen** [comment]
OMG
