### ISSUE TITLE
The "Launch Tour" and "Changelog" strings are wrongly displayed in lowercase characters on Spanish [es-es]

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2914]
**[Notes]:**
- I'm not sure if there are also other languages with this problem. it will need a couple hours of testing to check all of them.
- Now each language has its rules, but shouldn't we have all the words in the strings strings starting with capital letters like on English US? On languages like Spanish MX or German strings like "Launch Tour" and "Bug Reports" have only the first word starting with capital letter. 

**[Affected versions]:**
- Firefox 56.0 and above

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Add Spanish [es] as top language for web content from "Options > General > Language" section.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down on the Homepage and click on one of the active experiments cards.
3. Observe the "Launch Tour" (Visita Virtual) and "Changelog" (Registro de Cambios) strings localization under the experiment logo.

**[Expected result]:**
- Both strings have the first word (at least) starting with capital letter. 

**[Actual result]:**
- Both strings wrongly start with lowercase letters.

**[Additional Notes]:**
- Attaching a screenshot with both the behaviors observed:

![lower case](https://user-images.githubusercontent.com/17258026/31286366-98ce74a6-aac6-11e7-875c-5e23208de008.png)

**Comment by lmorchard** [comment]
Doesn't look like this is a problem in Test Pilot component code - [I think this is just how the contributor chose to translate the string](https://github.com/mozilla/testpilot/blame/master/locales/es-ES/app.ftl#L177). Also looks like it's been that way for awhile (11 months).

@flodolo We can change this with a quick commit to the l10n branch, but is there a way to maybe flag issues with localizations in Pontoon? Small change, but generally speaking I'm hesitant to meddle in languages I don't understand.

> I'm not sure if there are also other languages with this problem. it will need a couple hours of testing to check all of them.

Also wondering how we can or should review / QA localizations without having SoftVision folks include all locales in their testing?

It's rare that issues like this come up. But, since we don't QA locales before release or review Pontoon commits before they land, it's also rare that we catch these issues (i.e. the 11 months that this string has been as-is).

**Comment by pdehaan** [comment]
> it will need a couple hours of testing to check all of them.

@SoftVision-PaulOiegas You could also `git grep` to get a list of all those translation strings for each locale (ignoring the fact that some may not be "live" in production). But would be quicker than doing a bunch of locale switching and visual confirmation.

```sh
$ git grep "tourLink = " locales

locales/ar/app.ftl:tourLink = جولة
locales/ast/app.ftl:tourLink = Llanzar percorríu
locales/bn-BD/app.ftl:tourLink = ভ্রমণ শুরু করুন
locales/cak/app.ftl:tourLink = Kemil Tz'etoj
locales/cs/app.ftl:tourLink = prohlídka
locales/cy/app.ftl:tourLink = Cychwyn y Cyflwyniad
locales/de/app.ftl:tourLink = Rundgang starten
locales/dsb/app.ftl:tourLink = tura
locales/el/app.ftl:tourLink = Εκκίνηση ξενάγησης
locales/en-US/app.ftl:tourLink = Launch Tour
locales/es-AR/app.ftl:tourLink = Comenzar la visita
locales/es-CL/app.ftl:tourLink = Tur de lanzamiento
locales/es-ES/app.ftl:tourLink = visita virtual
locales/es-MX/app.ftl:tourLink = Visita virtual
locales/fa/app.ftl:tourLink = تور
locales/fr/app.ftl:tourLink = visite guidée
locales/fy-NL/app.ftl:tourLink = toer
locales/he/app.ftl:tourLink = הפעלת הסיור
locales/hsb/app.ftl:tourLink = tura
locales/hu/app.ftl:tourLink = kalauz
locales/id/app.ftl:tourLink = Jalankan Tur
locales/it/app.ftl:tourLink = Panoramica
locales/ja/app.ftl:tourLink = ツアーを始める
locales/kab/app.ftl:tourLink = Senker tirza fessusen
locales/ms/app.ftl:tourLink = Lancarkan Lawatan
locales/nb-NO/app.ftl:tourLink = Start gjennomgang
locales/nl/app.ftl:tourLink = Rondleiding starten
locales/nn-NO/app.ftl:tourLink = Start omvisingstur
locales/pt-BR/app.ftl:tourLink = Começar o tour
locales/pt-PT/app.ftl:tourLink = Iniciar visita guiada
locales/ro/app.ftl:tourLink = Lansează turul
locales/ru/app.ftl:tourLink = тур
locales/sk/app.ftl:tourLink = prehliadka
locales/sl/app.ftl:tourLink = Začnite predstavitev
locales/sq/app.ftl:tourLink = Niseni Turin
locales/sr/app.ftl:tourLink = Крените у обилазак
locales/sv-SE/app.ftl:tourLink = Starta guidad visning
locales/tr/app.ftl:tourLink = tur
locales/uk/app.ftl:tourLink = тур
locales/zh-CN/app.ftl:tourLink = 导览
locales/zh-TW/app.ftl:tourLink = 導覽
```

I haven't played w/ [PhantomJS](http://phantomjs.org/) or [SlimerJS](https://slimerjs.org/) (or even [trifleJS](http://triflejs.org/)) lately, but it may be possible to write a few scrapers that would _maybe_ take screenshots of various pages from different engines. Depends on how easy it'd be to pass different locales through those tools to the site.

**Comment by flodolo** [comment]
* Please do not make changes to localization files. If necessary, you can look at the history of a specific language, and cc the person (people) who worked on the folder (that's what I do when you ping me).
* Don't make assumptions on other languages. Title case is something that basically exist only in English, e.g. using it in Italian it's just poor knowledge of the language.

The only potential issue in that screenshot is the lowercase for es-ES (cc @avelper), for consistency, but I also expect localizers to test their translations on stage once in a while.

**Comment by SoftVision-PaulOiegas** [comment]
That was the whole point of the bug, the lowercase for "Launch Tour" string and maybe also the "Changelog" string too (some languages have that in lowercase also). It seems that Peter uncovered all the "Launch Tour" ones.

What I wrote on the "Notes" section, was just a question because exactly this I want to avoid, any assumptions on other languages that I don't know. I'm sorry if that wasn't clear enough.

@pdehaan thanks, that's a really helpful command.

**Comment by flodolo** [comment]
> What I wrote on the "Notes" section, was just a question because exactly this I want to avoid, any assumptions on other languages that I don't know. I'm sorry if that wasn't clear enough.

Thanks for confirming. To answer your question: no, we should not seek consistency between en-US and other language, but each language should be internally consistent and follow their own grammar rules.

**Comment by avelper** [comment]
Hi!

Yes, we could have it changed, but I would need someone to tell me where to modify it or just if someone can do it for me. It's just a matter of changing the first letter of the first word in each case (Visita and Registro)

**Comment by flodolo** [comment]
> Yes, we could have it changed, but I would need someone to tell me where to modify it or just if someone can do it for me. It's just a matter of changing the first letter of the first word in each case (Visita and Registro)

Hi Angela, they're in this project, looks like they were translated a while ago by Imma
https://pontoon.mozilla.org/es-ES/test-pilot-website/all-resources/?status=translated&string=159550

Also make sure that someone in the community goes through the website and search for errors.

**Comment by avelper** [comment]
Great, thanks!

It's changed and I will personally take a look to see if I find something else.

Ángela.

**Comment by ghost** [comment]
The developers talked in our meeting today and we'll add L10n comments where we can in the code.  

Thanks for the help Flod and @avelper

**Comment by ghost** [comment]
Looks like this specific case is addressed, so closing this. thanks

**Comment by SoftVision-PaulOiegas** [comment]
This was indeed fixed for Spanish [es-es], especially fort the "Launch Tour" string, but there are still languages that may show this behavior. At least for the "Changelog" string I've found the next ones:

```sh
locales/ast/app.ftl:changelog = rexistru de cambeos
locales/cs/app.ftl:changelog = seznam změn
locales/dsb/app.ftl:changelog = protokol změnow
locales/fy-NL/app.ftl:changelog = lochboek
locales/hsb/app.ftl:changelog = protokol změnow
locales/hu/app.ftl:changelog = változások listája

```
@flodolo Can we double check those to if they need to be changed too?

**Comment by flodolo** [comment]
I'll try, but chasing down all locales for this kind of problems doesn't really scale (locales x projects, not all of them are responsive).

ast: @enolp
cs: @MikkCZ
dsb/hsb: @milupo 
hu: @meskobalazs

**Comment by meskobalazs** [comment]
Fixed it in hu, thanks!

**Comment by milupo** [comment]
Changed on Pontoon for both hsb and dsb.

**Comment by SoftVision-PaulOiegas** [comment]
I understand, probably there are others lurking around, but I insisted on this one since it's quite user facing and since we were already aware of it... 
Thanks @flodolo! 👍

**Comment by enolp** [comment]
Fixed for Asturian, thanks for notifying us.
