### ISSUE TITLE
Update docs with respect to experiment graduation content

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2916]
[The docs still mention `graduation_report`](https://github.com/mozilla/testpilot/blob/master/docs/content/reference.md#graduation_report). But, as of #2694, we no longer use that and instead just have `graduation_url` to link to a report on Medium.

We should update the docs to reflect that. (Just got confused by that since my memory is swiss cheese apparently.)

**Comment by fzzzy** [comment]
Whoops -- I'll take this.
