### ISSUE TITLE
"data" link no longer localized

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/testpilot#2917]
#2728 no update to https://github.com/mozilla/testpilot/blob/0d7f5653a479a46f0987cbabb658bacaa6ea9159/locales/en-US/app.ftl#L137 and other locales.

**Comment by fzzzy** [comment]
@yfdyh000 Thanks for the report. These links have long been problematic; we should probably add some automated tests that check that they are working.

**Comment by johngruen** [comment]
@fzzzy i fixed this for some other instances. I can grab this.

**Comment by fzzzy** [comment]
@johngruen I saw your fix. I feel like it should work with the default content in the template. It would be good to investigate why it doesn't. Also, when #2728 landed, it was working, so what changed?

**Comment by meandavejustice** [comment]
@johngruen If you can link to the fix yall are talking about here I don't mind taking this over.

**Comment by johngruen** [comment]
@meandavejustice sure...https://github.com/mozilla/testpilot/pull/2905 fixed this in a few places. basically you'll need to delete the inline strings.
