### ISSUE TITLE
Settings popup is too sticky

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#292]
Not a huge problem on the [home page](http://idea-town-dev.elasticbeanstalk.com/home)[1] where we have a header, but the settings popup is a mildly annoying on the [details page](http://idea-town-dev.elasticbeanstalk.com/experiments/test-title) where it obscures the Enable[2] and Disable[3] buttons.

Not sure if we can close the popup when the user does a `mouseout` or something similar.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11280680/e52c4898-8eab-11e5-8ba7-5105ab1a9e41.png)
[1] Home page w/ header.

---

![idea_town](https://cloud.githubusercontent.com/assets/557895/11280635/c17d1350-8eab-11e5-840f-b07e9f996955.png)
[2] Enable experiment

---

![idea_town](https://cloud.githubusercontent.com/assets/557895/11280628/b70abcf6-8eab-11e5-9e0c-72a52822b343.png)
[3] Disable experiment

**Comment by johngruen** [comment]
@meandavejustice @pdehaan we should probably close it with a click outside of the button or the box
