### ISSUE TITLE
Audit the environment variables we have in CircleCI.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2921]

**Comment by lmorchard** [comment]
Any concerns in particular?

**Comment by lmorchard** [comment]
Deleted vars related to AMO & Docker that we don't use any more. Remaining vars are for publishing the dev site & storybook to S3 and querying the read-only CircleCI API. FWIW, nothing production-wise is done in CircleCI - that's all taken care of on in-house Mozilla infra

Is that the kind of thing you're looking for?

**Comment by lmorchard** [comment]
Also just created [a new github account for Storybook comments](https://github.com/MozillaTestPilotStorybook) so that they no longer post from my account. ([And it worked](https://github.com/mozilla/testpilot/pull/2922#issuecomment-335554108), yay!)
