### ISSUE TITLE
Useless Incompatible add-on error displayed for Tab Center when only Test Pilot add-on is installed on Beta or Nightly

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2928]
**[Notes]:**
- The error last sentence "Get the current version of Firefox." seems useless on Firefox 57 and 58 since the link redirects you to a lower version. 
- Also, I would suggest that only the first sentence from the message should be displayed, and only when the graduated add-on is still installed, even if disabled in about:addons due to version.

**[Affected versions]:**
- Nightly 58.0a1
- Beta 57.0b7

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox Beta 57 or Nightly 58.0a1 browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down on the Homepage and click the "View Past Experiments" button under the last active experiment.
3. After past experiments cards are displayed, click on the Tab Center one.
4. Look for any error messages displayed on page.

**[Expected result]:**
- There are no error messages on the page, just some alerts regarding the graduation report and supported Firefox versions.

**[Actual result]:**
- There is an error message displayed on red background on the top right side saying "Tab Center is not supported in this version of Firefox. Get the current version of Firefox." even if Tab Center is not installed and cannot be.

![useless error](https://user-images.githubusercontent.com/17258026/31446233-94150e4e-aea8-11e7-94d4-d38ee842e237.png)

**Comment by ghost** [comment]
Let's hide the error if the experiement has ended.  This is a good first bug because it is just adding the check in the template.

**Comment by SoftVision-CosminMuntean** [comment]
I have tested this on Test Pilot dev server and the error message is no longer displayed on the page. Marking as verified.
