### ISSUE TITLE
Open Settings links in new tabs?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#293]
![idea_town](https://cloud.githubusercontent.com/assets/557895/11280738/20f02e9e-8eac-11e5-9df9-6cdb93c46e0b.png)

Currently if you select the ["Idea Town Wiki"](https://wiki.mozilla.org/Idea-Town) or ["File an Issue"](https://github.com/mozilla/idea-town/issues/new) links, it replaces the current tab. We may want to see if we can add `target="_blank"` or some Ampersand magic to get those two links to open in a new tab since it's likely that we'll want to keep the user on the site while they file a bug or whatever.

**Comment by johngruen** [comment]
@pdehaan def
