### ISSUE TITLE
Containers should follow the same 7 days pre-graduation flow as previous experiments since it's graduation date is 10/17/2017

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2934]
**[Notes]:**
- There is a default graduation process in place that shows notifications on Test Pilot experiment ticket and experiment details page. First notification is showed starting with 7 days before graduation and says "Ending soon". The second is showed 1 day before graduation saying "Ending tomorrow".
- If possible, the graduation date should be updated for production server too this week, in order to make aware the Test Pilot and Containers users about this, since this will happen next Tuesday.

**[Affected versions]:**
- Firefox 56.0 and above

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down on the page and look for Containers experiment card.

**[Expected result]:**
- The Containers experiment card is still displayed and a notification is displayed informing that it's "Ending soon" (10/17/2017). 

**[Actual result]:**
- The Containers experiment card is no longer displayed as active experiment. Instead you can already find it in "Past Experiments" section (10/12/2017).

**Comment by SoftVision-PaulOiegas** [comment]
cc @groovecoder 
I've suggested this yesterday in the Test Pilot call and @johngruen agreed that we should follow the same process.

**Comment by fzzzy** [comment]
It looks like this is because the completed date is:

completed: '2017-09-05T19:38:00.42Z'

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy yes, noticed that. However, will the change of grad date apply also to production without a deploy? I'm asking since October 17 is Tuesday, and we are only deploying production on Tuesday. If the change will enter only then, this change is pretty useless. Containers should already display the graduation notification since there are only 5-6 days left.

Also, maybe we must consider how we are informing the users about the fate of Containers since this is only mentioned in the graduation report added on Medium, which is not displayed until the experiment graduates.

**Comment by fzzzy** [comment]
@SoftVision-PaulOiegas You're correct. We may want to consider pushing a special release with just that change.

**Comment by ghost** [comment]
We messed up the timing a bit here w/ l10n and such so we're going to just let it be expired.
