### ISSUE TITLE
[Enhancement] Transform the Test Pilot logo into website favicon for better display in Activity Stream 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2936]
**[Notes]:**
- While testing on Nightly, observed that in a new tab Activity Stream picks the visited Test Pilot website and adds it to "Top Sites", but it displays a screenshot of the homepage and the Firefox favicon. So I was thinking that maybe we can transform the Test Pilot logo into website favicon, that will be displayed more nicely in top sites if we have a high res favicon for them to show. 
Are there any limitations for Test Pilot website that request to have the Firefox logo as favicon?  

**[Affected versions]:**
- Firefox 57.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS X
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.firefox.com page.
2. Restart the browser.
3. Open a new tab and wait for the Test Pilot Top Sites entry to populate its image.

**[Expected result]:**
- The Test Pilot logo is correctly displayed as image for the Top Sites entry.

**[Actual result]:**
- A screenshot of the homepage and Firefox favicon are displayed instead.

![txp favicon](https://user-images.githubusercontent.com/17258026/31505876-90ccea0a-af7e-11e7-8005-4f69eeb5ff52.png)

**Comment by johngruen** [comment]
I did this, but updated to a scaled up FF logo instead per Mozilla Site conventions.

**Comment by SoftVision-PaulOiegas** [comment]
Well, the TxP logo would have been nicer, but yeah, it's better than before. Thanks! 👍
