### ISSUE TITLE
Rename "good first bug" to "good first issue"?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#2939]
A bit absurd, and may require some tweaking to [**chuckharmston/testpilot-contribute**](https://github.com/chuckharmston/testpilot-contribute), but I noticed this banner on GitHub today and if you click the inviting **good first issue** tag, it returns zero results since we use **good first _bug_** (which currently has [**10** open issues](https://github.com/mozilla/testpilot/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22)):

<img width="1001" alt="issues_ _mozilla_testpilot" src="https://user-images.githubusercontent.com/557895/31556837-73275670-affb-11e7-8766-e1478fbac82e.png">

Not sure if any of this really _matters_ (like, if GitHub surfaces "good first issues" elsewhere in the UI or not), but getting zero results is a bit unfortunate.

**Comment by chuckharmston** [comment]
Yeah, this will require about 10 minutes of work on my repo. Hope to get to it next week.

**Comment by fzzzy** [comment]
👍

**Comment by chuckharmston** [comment]
This has been done and deployed: https://contribute.testpilot.firefox.com/
