### ISSUE TITLE
Add social links in footer?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#294]
As a nerd, I often like it if I can easily find a project's GitHub and Twitter links somewhere on the page.
I'm thinking adding a GitHub/Twitter links or icons in the site footer is probably easy enough.

**Comment by meandavejustice** [comment]
Do we need an ideatown twitter account? main ideatown name is taken https://twitter.com/IdeaTown

**Comment by pdehaan** [comment]
Not sure why I mentioned Twitter. We probably need to confirm final naming before we go decide on if social media accounts even make sense. But we could do GitHub and point it at the current repo at any time.

**Comment by meandavejustice** [comment]
Assigning to @nchapman so we can get an update on the name once that is confirmed.

**Comment by jaredhirsch** [comment]
We've got an Outreachy contributor interested in this one.

I think linking to the main Mozilla twitter account, and this Github repo, would be enough for this bug.

**Comment by pdehaan** [comment]
Per https://github.com/mozilla/testpilot/issues/910#issuecomment-221684509,

> we have a twitter account https://twitter.com/FxTestPilot

**Comment by chuckharmston** [comment]
@johngruen We need UX for this.

**Comment by johngruen** [comment]
@chuckharmston did you one better
