### ISSUE TITLE
"Upgrade Firefox to continue!" error message is wrongly displayed if Test Pilot page is loaded in other browsers

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#2942]
[Notes]:
- This issue is reproducible on dev and stage websites. On production Test Pilot website is correctly displayed.
- On Microsoft Edge and Internet Explorer the page is not loading, but this issue is also reproducible on production. I will log another issue related to this.

[Affected versions]:
- Chrome
- Safari
- Opera

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

Steps to reproduce]:
1. Open the Chrome or Safari browser and navigate to "https://testpilot.stage.mozaws.net/" page.
2. Observe the Test Pilot page.

[Expected result]:
- Test Pilot page is correctly loaded.

[Actual results]:
- "Upgrade Firefox to continue!" message is displayed even if you are on other browser.

[Additional Notes]:
- Here is a screenshots with the issue:
![chrome](https://user-images.githubusercontent.com/19226534/31604355-b3761f3c-b26b-11e7-8044-b62f8bb40aed.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Chrome and Safari and is no longer reproducible on dev server. The Test Pilot website is correctly loaded.

**Comment by fzzzy** [comment]
Unfortunately this patch doesn't apply cleanly on top of the code that is currently on stage, so we're going to have to figure out how to get this deployed.
