### ISSUE TITLE
Feedback textarea font size is pretty small

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#295]
![idea_town](https://cloud.githubusercontent.com/assets/557895/11281339/14c0fc18-8eaf-11e5-8645-93c349e56910.png)

via [idea_town/frontend/static-src/styles/modules/_modals.scss:140](https://github.com/mozilla/idea-town/blob/5759803b2252fdb367d69aef36c9cf647d4e951f/idea_town/frontend/static-src/styles/modules/_modals.scss#L140)

Seems like the `1.1rem` calculates to ~11px. If I remove the `font-size` on the `<textarea>` in dev tools, it is about 16px.
It also looks like the `ul > li > label` input strings are 1.8rem, or 18px.

For reference, here's the `<textarea>` with the default 16px font size:
![idea_town](https://cloud.githubusercontent.com/assets/557895/11281511/c5f53512-8eaf-11e5-8a50-3bba9604f1c4.png)

**Comment by pdehaan** [comment]
Actually, it looks like we have 4 different font sizes currently in that feedback popup:

![idea_town](https://cloud.githubusercontent.com/assets/557895/11281625/3a3e5ad4-8eb0-11e5-96f1-98b98874d22e.png)

**Comment by johngruen** [comment]
This has been resolved
