### ISSUE TITLE
Email received by German users for newsletter sign up wrongly promotes graduated experiment (Page Shot)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2952]
**[Affected versions]:**
- Firefox 56.0 and above

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- From browser "Options > General > Language" add as top choice a different language than English (eg: German).

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down to reach the "Newsletter" section at the bottom of the page.
3. Click the text box and enter a valid email address (preferably, one already used that was unsubscribed).
4. Click the "Sign Up Now" button and open the email client. 
5. Observe the email content.

**[Expected result]:**
- Received email contains general info about Test Pilot and some of the active experiments are also promoted.

**[Actual result]:**
- Received email wrongly contains a promoted experiment that graduated (Page Shot).

![german newsletter page shot](https://user-images.githubusercontent.com/17258026/31667133-2d809d84-b357-11e7-9231-b946558bda44.png)

**Comment by ghost** [comment]
the interface is all changed now.  kirby is going to help me with this on monday

**Comment by ghost** [comment]
@kirbzilla did all the hard work here.

The confirmation email remains in German (it has no content that will expire).  The welcome email is now in English.
