### ISSUE TITLE
"Learn More" button is wrongly displayed on active experiments cards on supported Firefox versions

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#2953]
**[Notes]:**
- The "Learn More" button should only be displayed for unsupported Firefox versions and other browsers than Firefox.
- This does not reproduce on stage server so it might be a recent regression (maybe due to #2942).

**[Affected versions]:**
- Firefox 56.0 and above

**[Affected Platforms]:**
- All Windows
- All mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down on the page and observe the active experiments cards elements.

**[Expected result]:**
- All the cards contain the experiment logo, title, exp type, short description and "Get Started" blue button with white text.

**[Actual result]:**
- "Learn More" gray button with black text is wrongly displayed instead "Get Started" button for Firefox users on each active experiment.

![learn more](https://user-images.githubusercontent.com/17258026/31668399-c7136320-b35a-11e7-8c93-9c85e40454d5.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is no longer reproducible on Test Pilot dev and stage servers. Marking as verified.
