### ISSUE TITLE
Apply Photon Styles to Modals

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2956]
Pease see this spec for details: 

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/#artboard0

@ChenMorpheus can you provide the appropriate emoji assets outlined in this spec?

**Comment by Pekochen** [comment]
Hi @johngruen 
Here is the asset for modal
https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Website/00_Assets/Modal
Related to email icon, please use "mail 16"
you can get this from http://design.firefox.com/icons/viewer/
Thanks.

**Comment by meandavejustice** [comment]
Is there an example image for the news updates dialog? This is the most recent example I have https://mozilla.invisionapp.com/share/9YBLHHZKD#/screens/229830551 wanna include those in this update

**Comment by johngruen** [comment]
@meandavejustice i don't think so, @ChenMorpheus can you turn around an example for this ASAP?

**Comment by ChenMorpheus** [comment]
@Pekochen @youwenliang Could you dig out the proposal and provide screens and measurements accordingly?

@johngruen Since the design we have is not Photonized, it might still take a while to provide the screens, but we will try it ASAP.

**Comment by johngruen** [comment]
Okay, @ChenMorpheus I will work with @meandavejustice to best-guess the correct style based on all other other specs you've provided. @meandavejustice let's just ping-pong commits until we get something that feels close. We can do follow up changes as needed.

**Comment by meandavejustice** [comment]
@johngruen Sounds good to me, should have something together tomorrow morning for you to look at

**Comment by youwenliang** [comment]
I think Peko has an updated version here: https://mozilla.invisionapp.com/share/Z8E7QF476#/screens
It's an early version so we will sync with the current photonization design Peko did and provide the updated measurement soon!

**Comment by meandavejustice** [comment]
@youwenliang This looks like the current version, are you sure you linked to the _updated_ version?

**Comment by youwenliang** [comment]
@meandavejustice Peko is working on a revised version, will share it here soon!

**Comment by Pekochen** [comment]
Hi, I am sorry for reply late.
We had a long discussion and wanted it to make it perfect
So it took some time to revise the design. 
Here is the measurement for the modal.
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Modal_Photon_Styles/
Thanks!

**Comment by Pekochen** [comment]
Hi,I am sorry for reply late.
We had a long discussion and want it to make it perfect
So it took some time to revise design. 
Here is the measurement for the modal.
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Modal_Photon_Styles/
Thanks!

**Comment by meandavejustice** [comment]
Quick question, should we show the "Done" button when we are only showing one update in the modal?

![2017-11-08--44-16-14-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/32576176-2452ab40-c4a4-11e7-8e76-2eb8adac021d.png)

**Comment by meandavejustice** [comment]
Just realized I'm missing some assets, I thought they were exportable from the testpilot-assets site linked above.

@Pekochen @youwenliang @johngruen 

![2017-11-09--55-12-53-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/32621312-6dc034b0-c54d-11e7-8046-55342d7b8c34.png)
![2017-11-09--55-12-13-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/32621315-6e418c68-c54d-11e7-95e1-e0dd9d6666c6.png)
![2017-11-09--55-12-02-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/32621316-6e508ede-c54d-11e7-8068-7ba092a66194.png)
![2017-11-09--54-12-57-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/32621317-6e66b830-c54d-11e7-9822-87f329df6c94.png)

**Comment by meandavejustice** [comment]
I think it would be reasonable to ship a first run with the other style updates without them and follow up

**Comment by meandavejustice** [comment]
Also need the slimmer close icon

**Comment by ChenMorpheus** [comment]
> Quick question, should we show the "Done" button when we are only showing one update in the modal?

@meandavejustice Quick answer, we don't need to show the "Done" button for any cases since it's not like onboarding providing a sequence of instructions. We only provide next/last arrow buttons for users to find all updates. 

As for assets, I found all these assets in the [link](https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Website/00_Assets/Modal) @Pekochen provided. Could you be more specific? Thanks.

**Comment by meandavejustice** [comment]
fixed in #3103
