### ISSUE TITLE
Apply Photon Styles to Experiment Cards

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2957]
Please see this spec for complete set of states:

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard5

The following show responsive views:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard7
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard8
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard9

@ChenMorpheus can you make sure we have icon assets here (the star and checkbox)

**Comment by Pekochen** [comment]
Please get these two icons from
http://design.firefox.com/icons/viewer/
1.Star: bookmark 16 filled
2.Check: check 16

**Comment by fzzzy** [comment]
@Pekochen Is there an svg for the new feedback icon?

**Comment by fzzzy** [comment]
I found it, it looks like Notification 16
