### ISSUE TITLE
Apply Photon Styles To Email Footer

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2958]
Please see the following Spec:

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard6

@ChenMorpheus can you make sure we have the appropriate email icon asset.

**Comment by Pekochen** [comment]
Hi @johngruen 
You can find checkbox status for email footer here
https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Website/00_Assets/Email%20footer
and for email icon, please use "mail 16"
you can get this from http://design.firefox.com/icons/viewer/
Thanks.
