### ISSUE TITLE
As a user I want a page to tell me which experiments I currently have installed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#296]
We currently have 5 dummy experiments on the [dev server](http://idea-town-dev.elasticbeanstalk.com/home). Without clicking each one separately, I have no easy way to tell which experiments I'm currently enrolled in.

~~Not sure if we want to add a "My Experiments" link in the Settings popup which lists all the currently active experiments I'm participating in (maybe with a [Disable] button next to them to easily leave an experiment in less than 3 clicks).~~

**Comment by meandavejustice** [comment]
I'm :+1: on this

**Comment by johngruen** [comment]
@meandavejustice @pdehaan ...we have UX for this...just add an `.active` class to each `.idea-card`. The CSS is already in the app! active experiments will look like this:

<img width="1507" alt="screen shot 2015-11-20 at 11 04 15 am" src="https://cloud.githubusercontent.com/assets/3323249/11297125/9ff340ee-8f76-11e5-8085-2c075cf47463.png">

Don't add anything to settings.

**Comment by johngruen** [comment]
DONE-ZO
