### ISSUE TITLE
Update extension api use

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/testpilot#2968]
This is blocking https://bugzilla.mozilla.org/show_bug.cgi?id=1291399

https://github.com/mozilla/testpilot/blob/a732512053cc3cb64d408918dcff85d8cb96a083/addon/src/lib/channels.js#L15

You need to replace the uuid getter to do something like:

const {WebExtensionPolicy} = Cu.getGlobalForObject(Cu.import("resource://gre/modules/Extension.jsm", {}));
let {mozExtensionHostname} = WebExtensionPolicy.getByID(gAddon.id);
baseurl = `moz-extension://${mozExtensionHostname}/`,

**Comment by lmorchard** [comment]
Moved this into the current sprint, since it seems urgent

**Comment by mixedpuppy** [comment]
No rush, but when this does get resolved, can you ni? me on the bugzilla bug?  Thanks!

**Comment by mixedpuppy** [comment]
Literally no rush, I just read the above comments, this is not an urgent issue.  I'm just doing some cleanup here and there this quarter.

**Comment by mixedpuppy** [comment]
Is it safe to land the patch in bug 1291399 for 58?

**Comment by lmorchard** [comment]
We haven't deployed this code yet and add-on updates haven't rolled out. We're working through issues with a deployment right now, so it might be okay by the time 58 hits nightly?

FWIW, this is our issue tracking the current deployment https://github.com/mozilla/testpilot/issues/2996

**Comment by fzzzy** [comment]
@mixedpuppy We hope to have the code deployed by tomorrow.

**Comment by mixedpuppy** [comment]
Ok, I'll plan to land bug 1291399 next week.

**Comment by mixedpuppy** [comment]
Just thought I'd triple check before I land...did the update get deployed?

**Comment by fzzzy** [comment]
@mixedpuppy Yes. Land away!
