### ISSUE TITLE
please bring back page shot

### ISSUE THREAD

**Issue by tumaru** [mozilla/testpilot#2969]
i used it a bunch and then you took it away to analyze that how it was working. until you do whatever your going to do can you please put it back onto test pilot?

**Comment by chuckharmston** [comment]
Good news! With Firefox 56, Page Shot has shipped with Firefox itself as [Screenshots](https://medium.com/firefox-test-pilot/screenshots-is-shipping-in-firefox-56-25ecbe0d5b91). We're so glad you like it!

**Comment by tumaru** [comment]
thanks man. that's great news.
