### ISSUE TITLE
Remove BroadcastChannels support for Telemetry pings from WebExtension experiments?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2978]
In [`addon/src/lib/channels.js`](https://github.com/mozilla/testpilot/blob/master/addon/src/lib/channels.js), we have support for a BroadcastChannel hack that lets WebExtension based experiments ping Telemetry by way of sending an event through the main Test Pilot add-on. 

It's already needed one tweak to keep up with Firefox APIs (#2968), and it will probably need more. Would be nice to finally remove the code altogether.

Containers was using this channel, but it's graduated. Snooze Tabs is still using the channel [via testpilot-metrics](https://github.com/mozilla/testpilot-metrics/blob/master/testpilot-metrics.js#L319). Do we know if any other experiments are still using this metrics channel?

**Comment by chuckharmston** [comment]
Dupe #3183
