### ISSUE TITLE
Document or update add-on build scripts to fix frame scripts in temporary installation

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#2995]
[Recent Firefox changes have broken frame scripts for legacy add-ons in temporary installation](https://bugzilla.mozilla.org/show_bug.cgi?id=1393805) - unless the add-on XPI is loaded from a special directory that varies between platforms and user profile location. 

We use frame scripts in the add-on to inject `navigator.testpilotAddon` into the Test Pilot web frontend, about:home, and mozilla.org. We don't really need it on our site any more, but I think the other two may still use these properties to detect Test Pilot participation. 

But, since this only breaks `navigator.testpilotAddon` for temporary installation of the add-on, this is probably an edge case we shouldn't care too much about.

Still, we might want to eventually document how to install a locally built copy of the add-on to enable frame scripts - i.e. if we have to do any work on the in the future. For bonus points, we could have an npm script that copies the XPI over to the correct directory

**Comment by chuckharmston** [comment]
We do not use frame scripts anymore.
