### ISSUE TITLE
New component for dismissable modal window

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#2998]
With the new featured experiment experience being specced in #2976, we'll be introducing a modal document display sort of thing to display an experiment's privacy notice:

![oct-30-2017 10-39-21](https://user-images.githubusercontent.com/23885/32183367-baa5d056-bd5e-11e7-88a1-f2a3eb899672.gif)

This is pending UX, and is blocked by #2976.

**Comment by chuckharmston** [comment]
No longer blocked on #2976; the work from it just needs to be updated to match the Photon styles, tracked in #3019.

**Comment by meandavejustice** [comment]
This should probably wait until after #2956 is completed, as there is a lot of restructuring of modals, also the ability to dismiss modals easily is included in the changes
