### ISSUE TITLE
Create a standalone news feed page.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3000]
We will be replacing the news feed in the homepage with a section highlighting a featured experiment, and will be moving the news feed out to a standalone page:

<img width="1131" alt="screen shot 2017-10-30 at 10 45 20" src="https://user-images.githubusercontent.com/23885/32183794-dd914144-bd5f-11e7-9d6d-6c2a4cd689f2.png">

This is blocked pending UX in #2976.

**Comment by Pekochen** [comment]
Hi Chuck,
Please check here for the measurement.
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/
For convenience, I put all the pages into one file.
and for news feed, you can check
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/#artboard6
I also update the hover and the press status,
for news feed small windows please check
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/#artboard9

link to English article icon: http://design.firefox.com/icons/viewer/ and use "open in new 16"
small window menu icon: http://design.firefox.com/icons/viewer/ and use"menu 16"
Thanks!

**Comment by Pekochen** [comment]
For menu design in the small window version, we are waiting for sync AMO design. Can you please keep this part and we will keep update after aligning with AMO.
Thanks.

**Comment by chuckharmston** [comment]
No longer blocked on #2976; the work from it just needs to be updated to match the Photon styles, tracked in #3019.
