### ISSUE TITLE
Fix position of the "Try our other experiments" header

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3001]
To make sure that the new featured experiment UI doesn't cannibalize installations from other experiments, we'd like to make the "Or try our other experiments" header sticky to the bottom of the page if it would be off the page.

![](https://user-images.githubusercontent.com/18019946/31928140-96400df6-b8c9-11e7-9f46-9d4a2bb4ffa4.png)

![](https://user-images.githubusercontent.com/18019946/31928179-b2a71ec6-b8c9-11e7-966e-da4f586efa9d.png)

This is blocked pending UX in #2976.

**Comment by Pekochen** [comment]
Hi Chuck,
Please see the link as below for the measurement.
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/#artboard4

please use"arrowhead down 16" for arrow icon. you can download it from
http://design.firefox.com/icons/viewer/

**Comment by chuckharmston** [comment]
No longer blocked on #2976; the work from it just needs to be updated to match the Photon styles, tracked in #3019.

**Comment by lmorchard** [comment]
Totally missed that I got assigned to this - will try to get to this today or monday

**Comment by lmorchard** [comment]
> No longer blocked on #2976; the work from it just needs to be updated to match the Photon styles, tracked in #3019.

@chuckharmston I see #3019 is closed, but I don't see an update for this issue in there. I can probably wing it, but a spec update would be good. The plain header is there in a few of the artboards, but the fixed position state seems missing.

**Comment by lmorchard** [comment]
Also, could we avoid adding a new string here by reusing "Try out these experiments as well" from the bottom of the experiment detail pages?
![capture](https://user-images.githubusercontent.com/21687/33580458-4d2c770e-d91b-11e7-8c34-47c659f0fbed.PNG)

Might not be a great idea, the more I think about it 😞

**Comment by lmorchard** [comment]
Submitted PR #3143 for this. Still looking for input on styles, transitions, l10n

**Comment by marniepw** [comment]
@johngruen talk about at Design meeting.

**Comment by johngruen** [comment]
@ChenMorpheus this design causes overlapping issues with the CTA button, we need to revise.

**Comment by ChenMorpheus** [comment]
@johngruen We'll come up with a proposal which doesn't have a bar.

**Comment by johngruen** [comment]
@ChenMorpheus any progress here?

**Comment by Pekochen** [comment]
@johngruen Here is our revised version. We remove the background indtead of small button.So that we can avoid overlapping issue.please have a look.Thanks
![photon-style-revides_featured-experiment_txp-sticky-banner](https://user-images.githubusercontent.com/8252151/35034776-3fdafa92-fbaa-11e7-9a32-f493e0b2cd5d.png)
Measurement and assets:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment_sticky_banner/

**Comment by chuckharmston** [comment]
Moving to milestone 39.

**Comment by lmorchard** [comment]
Is there a copy somewhere of that icon with the circle & chevrons? Doesn't look like that's in the testpilot-assets link

**Comment by Pekochen** [comment]
Please check here~
measurement:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment_sticky_banner/
assets:
https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Website/01_Measurements/Featured_experiment_sticky_banner/assets
![featured experiment_txp sticky banner_animationspec](https://user-images.githubusercontent.com/8252151/35313653-8211fa6c-00fc-11e8-99d6-1584391b84ea.png)
; Besides we still hope we can do animation for the arrow. this is timeline setting for your reference.
Thank for your help.

**Comment by lmorchard** [comment]
Looks like the measurement spec has this oval (without arrows) for export: 
![](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment_sticky_banner/assets/Oval%202.svg)
The assets directory has separate arrows and an oval.

I can try to put these together in Gimp or Inkscape, but it'll probably be a poor result

**Comment by youwenliang** [comment]
@lmorchard Peko separated the arrows and the oval because we were thinking animating the arrows, probably with CSS keyframes. Would that work for you?

I mockup the animation here: https://codepen.io/youwenliang/pen/qpzOqo
