### ISSUE TITLE
Code related to RESTART_NEEDED is no longer required

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#3006]
In https://github.com/mozilla/testpilot/blob/master/frontend/src/app/lib/InstallManager.js we still have code related to `RESTART_NEEDED` which hasn't ever worked since we stopped using the non-mozAddonManager codepath. All code related to this can be removed now.

**Comment by svitlana-galianova** [comment]
Hi, I would like to try to help out here

**Comment by fzzzy** [comment]
@svitlana-galianova Go ahead -- you can ask questions here or on the irc channel #testpilot on the mozilla servers if you need help. Thanks!

**Comment by rsenwar** [comment]
[# **RESTART_NEEDED Unnecessary Code Removed ** ](url)https://github.com/mozilla/testpilot/pull/3277

**Comment by dannycoates** [comment]
fixed as of #3458
