### ISSUE TITLE
Move the locale into the URL

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#3008]
Right now, every locale accesses the site at the same urls, `/`, `/experiments`, `/experiment/foo` and translation is done in the browser using fluent-react. If we moved the locale to the beginning of the url, like `/en-US/`, `/en-US/experiments`, '/en-US/experiment/foo`, then the locale will be known at build time, meaning:

  - Search engines will see all language content
  - We can localize the html content sent in the html body
  - We can localize the <title> element easily
  - We can implement language switching ui easily

**Comment by fzzzy** [comment]
There's an existing issue for localizing the <title>:

https://github.com/mozilla/testpilot/issues/2612

**Comment by chuckharmston** [comment]
This is a big project, and I don't think we should worry about accomplishing it before setting down Test Pilot for a while, so I'm going to close it. I [made a suggestion](https://github.com/mozilla/testpilot/issues/2612#issuecomment-370470127) for a way we can accomplish #2612 without this bug.

**Comment by lmorchard** [comment]
FWIW, this includes more than just the page title - e.g. our header tags for social media sharing are all en-US only (#2001). But, noticed that issue's closed too, so I guess this is just a comment for posterity :)
