### ISSUE TITLE
Each experiment should have a short description and a long description

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#301]
Sort descriptions should appear on the home page and be quite short (capped at 60 characters).

Long descriptions can be longer. These should appear on the experiment details page:

![screen-shot-2015-11-19-at-7 43 33-pm](https://cloud.githubusercontent.com/assets/3323249/11297045/0c051308-8f76-11e5-8ccc-32ea81d5a5f0.png)

**Comment by pdehaan** [comment]
@johngruen Unrelated to this issue, but I notice that you have a green "&#9673; Now Active" blurb above the experiment name in the screenshot above. I'm not seeing that on the site. Should I file a bug?

**Comment by lmorchard** [comment]
> I notice that you have a green "◉ Now Active" blurb above the experiment name in the screenshot above. I'm not seeing that on the site. Should I file a bug?

Created issue #385
