### ISSUE TITLE
Handle experiment title extraction from addon installation URL when the Test Pilot addon is installed

### ISSUE THREAD

**Issue by kgeorgiou** [mozilla/testpilot#3010]
When an experiment is enabled, the following code extracts the experiment title from the URL and uses it in GA events:
https://github.com/mozilla/testpilot/blob/48982797d849f7651642e4b8278b20176d0c2a85/frontend/src/app/lib/InstallManager.js#L18-L21
This works for Experiment addons:
`https://testpilot.firefox.com/files/notes@mozilla.com/latest` -> **notes**  

But the above code is also called when the Test Pilot addon installed: 
`https://example.com:8000/static/addon/addon.xpi` -> **https**

A straightforward (and hacky) solution would be to set `experimentTitle` to something like "testpilot" when `url.indexOf('files/') === -1`.

**Comment by chuckharmston** [comment]
<img width="191" alt="screen shot 2018-03-05 at 11 20 52" src="https://user-images.githubusercontent.com/23885/36992150-4b041228-2067-11e8-929a-da81d0d034ee.png">

This is no longer an issue. Closing!
