### ISSUE TITLE
Remove /legacy page and redirect to home page from URL

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#3013]
We sometimes get errors from really old versions of firefox visiting /legacy. There is nothing dynamic on that page; we could simply make it a static page and not include any js.

**Comment by ghost** [comment]
Let's just get rid of this page.  (redirect to home page off this URL).

**Comment by ppatel221** [comment]
Hey, Im a student who is taking an Open source development class at Seneca College and I'm currently looking to contribute to a project. Can I get started on this bug?

**Comment by meandavejustice** [comment]
@ppatel221 Go for it :) I've updated the title to indicate what needs to be done now, feel free to ping us if you have any questions.

(sorry for the delayed response)
