### ISSUE TITLE
Update testing.md document

### ISSUE THREAD

**Issue by kgeorgiou** [mozilla/testpilot#3017]
[Testing.md](testpilot/docs/development/testing.md) looks like it needs some extra information/instructions to make testing easier for people new to Test Pilot.

## All tests

> To quickly run all tests, including addon tests, frontend tests, eslint checks, and flow types coverage reports, use npm run test:all.  

- Undocumented dependency on [tox](https://tox.readthedocs.io/en/latest/)  
- `flow-coverage` fails for the minimum coverage threshold:
```
> cd frontend && flow-coverage-report --threshold 60 -i 'src/**/*.js' -t html -o coverage/flow
View generated HTML Report at file:///testpilot/frontend/coverage/flow/index.html
Flow Coverage 57% is below the required threshold 60%
```

## Integration tests

> Integration tests are currently disabled and being re-evaluated. See Issue #1975 for details.

That issue seems to be resolved now.

**Comment by fzzzy** [comment]
Yes, the flow coverage percentage is not enforced anywhere right now. test:all should probably change so that it is closer to what runs on circleci.

Thanks for filing this issue!

**Comment by ghost** [comment]
The Tox dependency is documented now.  It looks like the flow coverage threshold has been set to 50% in the `flow-coverage` command and it no longer warns about being too low:

> cd frontend && flow-coverage-report --threshold 50 -i 'src/**/*.js' -t html -o coverage/flow
> View generated HTML Report at file:///testpilot/frontend/coverage/flow/index.html

So, I think this is fine to close as well.  If there is anything missing please open a new issue.  Thanks!
