### ISSUE TITLE
Updated featured experiment UX for Photonization

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3019]
We have the UX ready for the featured experiments project in #2976. We'll be moving the site over to Photon styles before shipping this feature, so we'll need to update this excellent UX work to match.

CC @pekochen

**Comment by Pekochen** [comment]
Hi~
Please check here for photon version.
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment_photonized/
Another thing I would like to mention, gear menu is still an uncertain part.
we will update this when we have a conclusion.
If you need anything please let me know.
Thanks!

**Comment by chuckharmston** [comment]
This looks awesome, thanks @Pekochen! 👏
