### ISSUE TITLE
Upgrade uniformly to node LTS v8.9.0

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#3024]
We [specify an old Node version (v4.4.0) in our `package.json`](https://github.com/mozilla/testpilot/blob/master/package.json#L13). 

We use [v6.9.1 in `circle.yml`](https://github.com/mozilla/testpilot/blob/master/circle.yml#L14) for build & test on our dev server.

We use [v6.2.0 in cloudops scripts](https://github.com/mozilla-services/cloudops-deployment/blob/5b80e655a43869dec2a0c9b8cb3bd2e54758939d/projects/testpilot/pipeline-prod.groovy#L52) for prod & stage (this link will 404 for anyone not invited to that repo).

Current LTS [is v8.9.0](https://github.com/nodejs/Release#release-schedule) - maybe we should get on that train? This will involve updating `package.json` and `circle.yml` and coordination with ops to upgrade.

Not sure if this will break any of our build scripts, but fixing such breakage should be done too.

**Comment by fzzzy** [comment]
I'd really like to require 8.9. I think we can get rid of the babel part of gulpfile.babel.js if we do that, which should speed most operations up.

**Comment by lmorchard** [comment]
Oh hey, this is done!
