### ISSUE TITLE
TXP-49: Tag experiments with relevant workflows

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#3027]
From Q2 2017 Test Pilot field research finding: "Participants expected experiments to support common workflows." - Sharon, [SF All Hands 2017 Test Pilot User Research](https://docs.google.com/presentation/d/1lcxcnCjDZFE8Ry9mXgTE-kSHxfthvCKTXP_t_BVRuI4/edit#slide=id.g23a6014ffc_0_75)

## Proposal

The proposal tries to introduce the possible daily workflows for each experiment by tags. Given that the current information might be too overwhelming, I propose to restructure the layout and offer an approach to include informative video and the ability to share experiment while users hover on it. Besides, the proposal could strengthen the connection between the icon, color, and the name.

## Key screens
![default](https://user-images.githubusercontent.com/18019946/32435265-67d057b2-c31b-11e7-94a1-c488c2a74e19.png)

![default](https://user-images.githubusercontent.com/18019946/32435174-3109e824-c31b-11e7-99e2-92765c7826e2.png)

## Prototype
https://mozilla.invisionapp.com/share/QCCPNI3YZ#/251804815_1-1_Homepage_Carousell

## Proposed features(Draft)
- [ ] Relayout the vital information on experiment cards and detail pages
- [ ] Displaying preset tags to reveal the possible workflows on experiment cards and detail pages
- [ ] Users can hover to access the informative video
- [ ] Users can hover to access the feedback button if enabled 
- [ ] Users can hover to access the share button to share experiment on specified social medias

(@johngruen Feel free to revise or prioritize them) 

**Source**
[Redesign plan - Theme 1: Support daily workflow](https://docs.google.com/document/d/13bKCjf7oNvDNYVu7syFVe9sKZT29eG9mWKyJHReGyao/edit#heading=h.sx1pjy53f255)
[Workshop for common workflows](https://docs.google.com/presentation/d/1IyhGxloPAq_BexP69mduM41e90jiRApnuO5eLUyzEX4/edit#slide=id.p)

**Comment by chuckharmston** [comment]
We won't be doing this in the near- or mid- term, so I'm closing.
