### ISSUE TITLE
TXP-58: Deprioritize in hierarchy of experiment detail pages links to technical resources (Github, Discourse, etc.)

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#3028]
From Q2 2017 Test Pilot field research finding: "Participants’ mental models of giving experiment feedback were influenced by retail customer service models." - Sharon, [SF All Hands 2017 Test Pilot User Research](https://docs.google.com/presentation/d/1lcxcnCjDZFE8Ry9mXgTE-kSHxfthvCKTXP_t_BVRuI4/edit#slide=id.g23a6014ffc_0_75)

## Proposal

Instead of deprioritizing, the proposal tries to offer a comprehensive and contextual approach to accommodate these technical resources. The tabs divide different information into three categories which provide structured data and relevant resource links.  

## Key screens
![default](https://user-images.githubusercontent.com/18019946/32489462-09633322-c3eb-11e7-8ee5-c21427f4d589.png)

## Prototype
https://mozilla.invisionapp.com/share/QCCPNI3YZ#/254060427_Detail_Page_1

## Proposed features(Draft)
- [ ] FAQ tab (Frequently asked questions) displays critical questions users might ask
- [ ] FAQ tab provides a "more discussion" button to direct users to discourse for more discussion
- [ ] Contributors tab shows the photo, name, and position of each contributor
- [ ] Contributors tab offers a button which leads users to find bugs to contribute in Good first bug site 
- [ ] Github links tab briefly explains what Github is and shows the links to changelog and issues
- [ ] Github links tab provides "file a bug" button for users directly file a bug

(@johngruen Feel free to revise or prioritize them) 

**Source**
[Redesign plan - Theme 2: Emphasize How-to content](https://docs.google.com/document/d/13bKCjf7oNvDNYVu7syFVe9sKZT29eG9mWKyJHReGyao/edit#heading=h.sx1pjy53f255)
[Workshop for emphasizing how-to content](https://docs.google.com/presentation/d/11PlMfSp0YkfoTWChdQmcBylYs3hwWDYMjQn40wwuicY/edit#slide=id.p)

**Comment by chuckharmston** [comment]
We won't be doing this in the near- or mid- term, so I'm closing.
