### ISSUE TITLE
TXP-56: Surface selected feedback on experiment detail page

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#3032]
From Q2 2017 Test Pilot field research finding: "Participants’ mental models of giving experiment feedback were influenced by retail customer service models." - Sharon, [SF All Hands 2017 Test Pilot User Research](https://docs.google.com/presentation/d/1lcxcnCjDZFE8Ry9mXgTE-kSHxfthvCKTXP_t_BVRuI4/edit#slide=id.g23a6014ffc_0_75)

## Proposal

This proposal seeks to give a solution to "surface selected feedback on experiment detail page" before and after experiment launched. Before the experiment starts, we could ask several Firefox influencers to leave a comment or collect testing participant's words to advertise the experiment. After experiment releases for a while, we could collect some users' positive feedback and surface as testimony.  

## Key screens

![default](https://user-images.githubusercontent.com/18019946/32476447-62ef8546-c3b2-11e7-8f9e-a0197ac13764.png)

## Prototype
https://mozilla.invisionapp.com/share/QCCPNI3YZ#/254060427_Detail_Page_1

## Proposed features(Draft)
- [ ] A section to display testimonial's photo, name, position and comment/quote 
- [ ] Allow users to find more than three comment/testimony

(@johngruen Feel free to revise or prioritize them) 

**Source**
[Redesign plan - Theme 2: Emphasize How-to content](https://docs.google.com/document/d/13bKCjf7oNvDNYVu7syFVe9sKZT29eG9mWKyJHReGyao/edit#heading=h.sx1pjy53f255)
[Workshop for emphasizing how-to content](https://docs.google.com/presentation/d/11PlMfSp0YkfoTWChdQmcBylYs3hwWDYMjQn40wwuicY/edit#slide=id.p)

**Comment by chuckharmston** [comment]
We won't be doing this in the near- or mid- term, so I'm closing.
