### ISSUE TITLE
TXP-52: Ensure that experiment detail pages prioritize step-by-step, bulleted instructions for using experiments

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla/testpilot#3033]
From Q2 2017 Test Pilot field research finding: "Participants sought how-to content for the experiments they chose." - Sharon, [SF All Hands 2017 Test Pilot User Research](https://docs.google.com/presentation/d/1lcxcnCjDZFE8Ry9mXgTE-kSHxfthvCKTXP_t_BVRuI4/edit#slide=id.g23a6014ffc_0_75)

## Proposal

The proposal tries to collect all informative materials in a step-by-step sequence. It provides an instructive video as an overview of the experiment first; then users can turn to other bulleted numbers underneath to find the series of text instructions with screenshots.

## Key screens
![default](https://user-images.githubusercontent.com/18019946/32484043-77f5ed3c-c3d9-11e7-8d95-ed6c702baf71.png)
![default](https://user-images.githubusercontent.com/18019946/32484054-805f454a-c3d9-11e7-87e3-61012f6103c8.png)

## Prototype
https://mozilla.invisionapp.com/share/QCCPNI3YZ#/254060427_Detail_Page_1

## Proposed features(Draft)
- [ ] Accommodating informative video and series of instructions in the carousel 
- [ ] The indicator of pages show bulleted numbers as steps

(@johngruen Feel free to revise or prioritize them) 

**Source**
[Redesign plan - Theme 2: Emphasize How-to content](https://docs.google.com/document/d/13bKCjf7oNvDNYVu7syFVe9sKZT29eG9mWKyJHReGyao/edit#heading=h.sx1pjy53f255)
[Workshop for emphasizing how-to content](https://docs.google.com/presentation/d/11PlMfSp0YkfoTWChdQmcBylYs3hwWDYMjQn40wwuicY/edit#slide=id.p)

**Comment by chuckharmston** [comment]
We won't be doing this in the near- or mid- term, so I'm closing.
