### ISSUE TITLE
Wrong color and no hover or click effect displayed for "Proceed" button from uninstall TxP flow

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3034]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click the top right "Settings" button and choose to "Uninstall Test Pilot".
3. Observe the header and "Proceed" button colors.
4. Hover over the "Proceed" button and observe the color.
5. Click the "Proceed" button and observe again its color.

**[Expected result]:**
- Step 3: Header and button color is #D70022.
- Step 4: Button gains a hover effect where the color darkens a bit to #A4000F.
- Step 5: While clicking the button, the color darkens even more to #5A0002.

**[Actual result]:**
- Step 3: Header and button color is #ff0039 instead.
- Step 4: The button has no hover effect.
- Step 5: The button has no click effect.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas marking as closed. Spec is not 100% matched but we're using all the photon colors now

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Sadly not for modal header too. The button now has #D70022, but the header remained on #FF0039. Unless you think it should be changed to match, I won't reopen it.

Forgot to mention in the title about the header too, but I've mentioned in the expected and actual results section.

![modal colors](https://user-images.githubusercontent.com/17258026/32668830-58ef90d0-c647-11e7-83cd-e7952b22f18a.png)
