### ISSUE TITLE
The "Settings" button does not entirely follow it's Photonization design 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3036]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Observe the color of the "Settings" buttons.
3. Hover the "Settings" button and observe its behavior.
4. Click the "Settings" button and observe its behavior.

**[Expected result]:**
- Step 2: Both button text and cogwheel are 100% white colored (#FFFFFF)
- Step 3: Button text and cogwheel both gain a hover effect where their color changes to light blue (#0A84FF).
- Step 4: While clicking the button, its text and cogwheel color change to darker blue (#0060DF).

**[Actual result]:**
- Step 2: Header and button color is 100% white (#FFFFFF)
- Step 3: Button and cogwheel colors remain unchanged when hovered. 
- Step 4: Button and cogwheel colors remain unchanged when clicked.

**[Notes]:**
- Also, I don't see any borders around the text in the design. Should those be removed or not? 
- Here is a screenshot from the design https://screenshots.firefox.com/CR3Ra2sNneBUrspY/mozilla.github.io.
- Here is a screen recording of the behavior https://goo.gl/sFWfQP.

**Comment by lmorchard** [comment]
FWIW, we're still mid-sprint with photon style work and not done with everything yet

**Comment by SoftVision-PaulOiegas** [comment]
I know, that's why I logged today issues only related to button colors. Since John closed #2955 I assumed that at least those should have been ok by now. Otherwise the issue should not have been closed yet.

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Are you sure this is right? In the specs "Settings" should be white in normal state, light blue when hovered and dark blue when clicked.
