### ISSUE TITLE
Animation for scroll hint(Sticky banner)

### ISSUE THREAD

**Issue by Pekochen** [mozilla/testpilot#3039]
Hi @chuckharmston 
I made an animation sample for scroll hint.
Please check here for the animation!
https://www.dropbox.com/sh/jv3fk7kg3ehxo99/AADJiUSQPvToyocey6l40jpaa?dl=0
I also write down some information you may need.
![animation preference](https://user-images.githubusercontent.com/8252151/32541282-2e94f350-c4aa-11e7-9481-725266157624.png)
Arrow keeps looping. When you roll over, the arrow will stop and then when the user scrolls down the page; the sticky bar is going to move down and fade out.
When you press the arrow, it will change color to #0094FB. The rest of page(or try other experiments that part) is going up, and the sticky bar is going to move down and fade out at the same time.
I am not sure if the explanation is clear enough, if you have any question, please let me know.
Thanks!

**Comment by chuckharmston** [comment]
Fully blocked on #3001, unassigning until that lands.

**Comment by johngruen** [comment]
I am gonna go ahead an close this, and let's use #3001 to track everything
