### ISSUE TITLE
Dialog Newsletter sign up is wrongly validated when "Enter" key is pressed without checking the privacy checkbox

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3041]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Install the Test Pilot Add-on" big green button.
3. After TxP "Newsletter sign up" dialog is displayed, click the text field in order to focus it.
4. Leave text box empty or enter a valid email address.
5. Leave the privacy checkbox unchecked and hit the keyboard "Enter" key.
5. Observe the dialog behavior. 

**[Expected result]:**
- The sign up process is not performed and you are notified to check the privacy notice checkbox.

**[Actual result]:**
- You are wrongly advanced to the sign up confirmation dialog if the entered email is valid or to the newsletter sign up error dialog if an invalid address was used.

**[Notes]:**
- If a valid email address is used, you even get the sign up newsletter email.
- This behavior does not occur when clicking the dialog "Sign Up Now" button.
- This behavior does not occur on the footer Newsletter form.
- Here is a screen recording of the behavior https://goo.gl/p7NFBa.

**Comment by kgeorgiou** [comment]
This is related to #2983, I'll take a look.

**Comment by SoftVision-PaulOiegas** [comment]
This seems to be fixed. 👍 But now, I have found another scenario where "Enter" key fails, that couldn't be caught before this fix (#3059). 
Maybe you can take a look @kgeorgiou?
