### ISSUE TITLE
Footer Newsletter Photonization - Design vs implementation observed differences

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3044]
Here are the differences observed:
- [x] Implemented background color is darker than designed.
- [x] ~~Background color should also cover footer links based on design.~~
A different design was made for this area #3225 
- [x] First message displayed on 2 rows (implementation) vs 3 rows (design).
- [x] ~~Hint message from text box has first letter in uppercase (implementation) vs all letters in uppercase (design). As on old implementation.~~
- [x] There is already space between text box and sign up button for privacy message (implementation) vs no space (design). Like on old implementation
- [x] The "Sign Up Now" button font size is 20px (implementation) vs 15px (design).
- [x] The "We will only send you Test Pilot-related information." message font size is 14px (implementation) vs 13px (design).
- [ ] The "We will only send you Test Pilot-related information." message is aligned to center (implementation) vs to left (design).
- [x] The privacy notice message font size is 12px (implementation) vs 13px (design). ~~Also, in the designs, the text exceeds the text box and button, while on current implementation it wraps if modified.~~
- [x] ~~Error message is displayed on the center of the Newsletter section (implementation) vs centered above the text box and pointing at it (design). Also, the design of it is different than the one in designs.~~
Tracked separately in #3042
- [x] I haven't seen the "Sign Up Now" button barberpole animation + "Submitting..." text even with the internet connection down. Also, when clicked, the button remains in "clicked" state after an error occurs.
- [x] Submitted message is displayed on 3 rows (implementation) vs 2 rows (design).

Let me know if you want me to file separate bugs for any of them.

**Comment by johngruen** [comment]
>     Implemented background color is darker than designed.
Fixed
>     Background color should also cover footer links based on design.
Obviated by #3225
>     First message displayed on 2 rows (implementation) vs 3 rows (design).
Fixed, grudgingly.
>     Hint message from text box has first letter in uppercase (implementation) vs all letters in uppercase (design). As on old implementation.
>     There is already space between text box and sign up button for privacy message (implementation) vs no space (design). Like on old implementation
Wontfix...all caps is bad for l10n
>     The "Sign Up Now" button font size is 20px (implementation) vs 15px (design).
appears to be resolved now
>     The "We will only send you Test Pilot-related information." message font size is 14px (implementation) vs 13px (design).
appears to be resolved now
>     The "We will only send you Test Pilot-related information." message is aligned to center (implementation) vs to left (design).
>     The privacy notice message font size is 12px (implementation) vs 13px (design). Also, in the designs, the text exceeds the text box and button, while on current implementation it wraps if modified.
I object to the text overflow, also this is tracked through #3221
>     Error message is displayed on the center of the Newsletter section (implementation) vs centered above the text box and pointing at it (design). Also, the design of it is different than the one in designs.
Tracked through: #3042
>     I haven't seen the "Sign Up Now" button barberpole animation + "Submitting..." text even with the internet connection down. Also, when clicked, the button remains in "clicked" state after an error occurs.
I can see the barberpole here, apparently this is resolved
>     Submitted message is displayed on 3 rows (implementation) vs 2 rows (design).
fixed

**Comment by SoftVision-PaulOiegas** [comment]
There is only 1 difference that is still visible:
- The "We will only send you Test Pilot-related information." message is aligned to center (implementation) vs to left (design).
Should start together with the "Sign Up Now" button

The rest are fixed or have a different approach now. 👍

**Comment by SoftVision-PaulOiegas** [comment]
And of course, the Twitter and GitHub buttons from footer must be changed to round ones instead of squares. But I think those are tracked elsewhere if I'm not mistaking.
