### ISSUE TITLE
[Newsletter forms] The privacy notice message checkbox shortly disappears after hover, check and hover away actions

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3048]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down to the page until you reach the "Newsletter" section.
3. Click on the section text box and enter at leas one character.
4. After the privacy notice checkbox appear, slowly hover it and observe its behavior.
5. Click the checkbox and observe its behavior.
6. Hover away the checkbox and observe it's behavior.

**[Expected result]:**
- Step 4: The checkbox border becomes blue without any display issues.
- Step 5: The checkbox is correctly checked without any display issues.
- Step 6: The checkbox border looses the blue border without any display issues.

**[Actual result]:**
- Step 4: The checkbox shortly disappears before the hover effect occurs.
- Step 5: The checkbox shortly disappears again before the check mark is displayed.  
- Step 6: Again, the checkbox shortly disappears when hovered away. 

**[Notes]:**
- These 3 behaviors only occur the first time the above actions are performed. But sadly they reappear in a new tab or after browser restart. 
- This behavior also occurs on the Newsletter dialog flow after you install Test Pilot add-on.
- Here is a recording of the issue: https://goo.gl/pg7dDP.

**Comment by fzzzy** [comment]
I guess this is because we are now using an external svg file for the checkbox and it is not cached. I think we may be able to preload all the checkbox images on the main page load somehow.

**Comment by chuckharmston** [comment]
@fzzzy I've successfully used this to inline an SVG from a Webpack build: https://www.npmjs.com/package/svg-url-loader

**Comment by lmorchard** [comment]
I can try taking a swing at this

**Comment by lmorchard** [comment]
Spent some time on this and never actually found a solution. Not actively working on it now, so un-assigning myself so someone else might be able to take a crack at it

**Comment by SoftVision-PaulOiegas** [comment]
Uuuu, finally fixed. 👍
