### ISSUE TITLE
The "Enter" key wrongly advances you to error dialog after you checked the privacy notice and deleted the entered string

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3059]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Install the Test Pilot Add-on" big green button.
3. After TxP "Newsletter sign up" dialog is displayed, click the text field in order to focus it.
4. Enter at least 1 character and check the displayed "privacy notice" message checkbox.
5. Delete the entered character / string and click outside the text box.
6. Hit the keyboard "Enter" key and observe the dialog behavior.

**[Expected result]:**
- The sign up process is not performed and you are notified to fill out the text field. 

**[Actual result]:**
- You are wrongly advanced to the error dialog for Newsletter sign up. 

**[Notes]:**
- This behavior does not occur when clicking the dialog "Sign Up Now" button.
- This behavior does not occur on the footer Newsletter form, but still, you are aren't notified about the need to fill the text field.
- Here is a screen recording of the behavior https://goo.gl/ojieeU.

**Comment by kgeorgiou** [comment]
When the input field is not focused, the "Enter" key doesn't trigger the HTML5 form validation. (However the backend correctly rejects the invalid input, hence the error dialog.)

Below are 3 possible solutions, sorted in descending order of simplicity.

When the "Enter" key is pressed on the Email Dialog and the input field is not focused:
- Do nothing (behaviour before #2983)
- Validate input against an email regex and advance only on valid input (but still no tooltip warnings will be shown on the input field)
- Grab a reference on the contained form and trigger its `.submit()` method

I'd be happy to listen to ideas on what would be the best way to approach this and put together a patch for it.

**Comment by fzzzy** [comment]
@kgeorgiou I think #3 is the right thing to do. Thanks!

**Comment by SoftVision-PaulOiegas** [comment]
Hammered it a bit, but seems to be fixed. 👍
