### ISSUE TITLE
Firefox Free Download button lacks download animation when hovered

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/testpilot#3061]
[Affected versions]:
- Firefox 56.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

[Steps to reproduce]:
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/page.
2. Hover over the "Install the Test Pilot Add-on" button and observe the color.

[Expected result]:
- Button gains a hover effect where the color darkens a bit.

[Actual result]:
- The button has no hover effect.

[Notes]:
- This is also reproducible with "Install Test Pilot & Enable (experiment)" button on the experiment's page.
- The hover effect appears only when the "Installing..." process takes place.
- This is also reproducible with the "Free Download" button on Chrome (in this case, the arrow animation when hovering the button is also missing).
- Please see the following screencast with the issue:

![hover button tp](https://user-images.githubusercontent.com/26000308/32726227-e1b85f56-c880-11e7-8db2-ab6ad8a85bb8.gif)

**Comment by ghost** [comment]
This matches the spec

**Comment by Pekochen** [comment]
![2017-11-20 3 18 21](https://user-images.githubusercontent.com/8252151/33006650-22d3228e-ce06-11e7-8ff4-8a70dba7ef57.png)
Please follow the visual spec we've provided, you can check component page and you can find different status for buttons.Thanks!

**Comment by youwenliang** [comment]
Here's a link to the hover states: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Component_20171003/#artboard1

**Comment by Pekochen** [comment]
I want to further explain the button status:
Please keep the animation, when hovering the button, download icon keeps moving up and down.

**Comment by johngruen** [comment]
@Pekochen but no color change on hover?

**Comment by Pekochen** [comment]
So sorry about that :( 
Please check here 
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard0

**Comment by SoftVision-PaulOiegas** [comment]
Verification blocked because of #3136. Not sure what caused this, maybe even this fix since yesterday it was working fine?

**Comment by SoftVision-PaulOiegas** [comment]
Stage was re-deployed and included this fix too. However, I must reopen this because the download animation mentioned by @Pekochen [here](https://github.com/mozilla/testpilot/issues/3061#issuecomment-347085917) was left behind...

**Comment by SoftVision-PaulOiegas** [comment]
> Please keep the animation, when hovering the button, download icon keeps moving up and down.

Reopening this since the download icon animation requested by Peko Chen is still missing and @johngruen confirmed via Slack that it should be added back.

**Comment by chuckharmston** [comment]
I'll leave this as a good first issue, but I don't expect we'll be getting to it any time soon.

**Comment by ShivangiKakkar** [comment]
Hey! @SoftVision-CarmenFat, @chuckharmston @SoftVision-PaulOiegas 
I would like to work on this issue if anyone is not working on it currently.

**Comment by fzzzy** [comment]
@ShivangiKakkar Go ahead.

**Comment by SoftVision-PaulOiegas** [comment]
The animation was added, but when testing this I've noticed that we don't have a pressed state for the button.
@johngruen @youwenliang , do we care about this or we can live without it?
