### ISSUE TITLE
The navigation bubbles from the bottom of the experiment Tour are no longer visible

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3062]
**[Notes]:**
- I think this issue is a regression since is not reproducible on Test Pilot production server.
- Also the hover effect is hardly visible on the navigation arrows.

**[Affected versions]:**
- Firefox 56.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open the browser from prerequisites and navigate to "https://testpilot.stage.mozaws.net/experiments/" website.
2. Click on one of the available experiments.
3. Click the "Tour" link button.
4. Observe the navigation bubbles from the bottom of the Tour.

**[Expected result]:**
- The navigation bubbles are visible.

**[Actual result]:**
- The navigation bubbles are not visible.

**[Additional Notes]:**
- Here is a screen shot with the issue:
![tour](https://user-images.githubusercontent.com/19226534/32731490-a4ffefc2-c892-11e7-9780-6e916debb1bc.png)

**Comment by meandavejustice** [comment]
fixed in #3103

**Comment by SoftVision-PaulOiegas** [comment]
Fixed! 👍
