### ISSUE TITLE
Release 2017-11-09 on stage

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3063]
Hi guys,

We have finalized testing the stage server and we have a 77% pass rate on our tests.
Here are the testing results:

**New Issues**
#3054 - "Text Select" pointer is wrongly displayed when hovering the "Settings" button - **minor**
-the issue already has a PR
#3056 - The "Blog" and "Settings" buttons are not aligned with their icons - **minor**
-the issue already has a PR
#3059 - The "Enter" key wrongly advances you to error dialog after you checked the privacy notice and deleted the entered string - **normal**
#3061 - Test Pilot install and Firefox Free Download buttons don't have any hover effect **normal**
#3062 - The navigation bubbles from the bottom of the experiment Tour are no longer visible - **minor**

**Known Issues**
#3046 - Enabled experiment bar is no longer displayed on experiments details page - **normal**
-The issue is also reproducible if experiment download fails. The "Uh oh..." red error bar is no longer displayed.
#3042 - [Newsletter] Notification that informs about the need to check the privacy notice checkbox is no longer displayed - **normal**
#3048 - [Newsletter forms] The privacy notice message checkbox shortly disappears after hover, check and hover away actions - **normal**
#3047 - Old Firefox logo is still displayed on the Test Pilot and experiments feedback survey - **minor**
#2866 - Test Pilot website still looks as if it's add-on is installed, after manually disabling it from - **normal**
#2848 - Voice Fill and Notes are wrongly enabled on unsupported Fx version when installed together with Test Pilot add-on  - **minor**

All the above mentioned issues are user facing issues and should be fixed, but since most of them are minor we suggest to fix at least #3046 and #3042 before deploying to production.

Regards,
Cosmin

**Comment by SoftVision-PaulOiegas** [comment]
Adding two more to the **New Issues** list:
#3064 - Old background displayed for Test Pilot social media sharing message
#3065 - Footer links are wrongly displayed on the Share page background

**Comment by SoftVision-PaulOiegas** [comment]
This is already on production. Closing.
