### ISSUE TITLE
Old background displayed for Test Pilot social media sharing message

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3064]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- You are already logged on a Facebook / Twitter account

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/share page.
2. Click the Facebook or Twitter button and share/tweet the Test Pilot website.
3. Navigate to the Facebook / Twitter profile page amd observe the shared message. 

**[Expected result]:**
- The message correctly contains all the designed details and the TxP logo over the new Photon background.

**[Actual result]:**
- The message correctly contains all the designed details but the old website background is displayed instead.

**[Notes]:**
- Here's a screenshot of the message: 

![screenshot-2017-11-13 share background](https://user-images.githubusercontent.com/17258026/32738155-c4e2854a-c8a4-11e7-8092-d4602923a8d6.png)

**Comment by SoftVision-CarmenFat** [comment]
Same issue is reproducible when receiving the "Welcome to Test Pilot"  subscription email.

![email](https://user-images.githubusercontent.com/26000308/32781381-7bd7a520-c94d-11e7-9a5f-d4b574eebe1e.png)

**Comment by chuckharmston** [comment]
We should update these images.

**Comment by meandavejustice** [comment]
We no longer have a share page, closing

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice @johngruen Now, I'm not sure if we care so much about this. But if we do, the bug is still valid even without the share page. Copying the Test Pilot website URL and pasting it in a Facebook  post/comment, transforms it in the same image that is outdated.

![screenshot-2018-5-11 34 facebook](https://user-images.githubusercontent.com/17258026/39931860-4e10a6f6-5547-11e8-8882-c42b3637279e.png)
