### ISSUE TITLE
"Something has gone wrong with Test Pilot. Please file a bug and mention this error message".

### ISSUE THREAD

**Issue by Homme-Nuage** [mozilla/testpilot#3068]
So what went wrong? I use Windows 7 64 bits. I had the same error when I was on Nightly.

**Comment by fzzzy** [comment]
@Homme-Nuage Do you see any error messages in the Web Console?

Does it still happen if you make a fresh Firefox profile?

Thank you for the report.

**Comment by Homme-Nuage** [comment]
Thank you for your answer. I looked into my about:config tweaks and I found that the issue was caused by privacy.resistFingerprinting.block_mozAddonManager which was set on true.

**Comment by fzzzy** [comment]
@Homme-Nuage Great! Yes, blocking mozAddonManager would cause this message in this case.
