### ISSUE TITLE
Shield Study handling

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3073]
Min Vid is going to become a shield study soon, there will likely be overlap between the time the study is running and min vid is still in testpilot.

Need to figure out how we want to handle the case where a user has the shield study active and they visit test pilot.

Thinking we could detect the shield study addon id, disable the install button, and have some sort of note on our end.

Thoughts?

cc/ @johngruen

**Comment by fzzzy** [comment]
If the shield study add-on has a different id, set it as an incompatible_addon in the test pilot min vid yaml.

**Comment by johngruen** [comment]
Closing this since it seems like a profound edge case with lots of complexity.
