### ISSUE TITLE
Enable / Disable <experiment_name> button long format persists when maximazing from mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3074]
**[Affected versions]:**
- Firefox 57.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Scroll down to the page and click one of the active experiments cards (except Send).
3. Resize the browser window until the page enters in mobile view mode and the buttons enlarge.
4. Hit the "Enable <experiment_name>" button and follow the process.
5. Maximize the browser while observing the section where the title, "Give Feedback" and "Disable <experiment_name>" elements are located.

**[Expected result]:**
- The button size is automatically reduced when browser is maximized.

**[Actual result]:**
- The button enlarges even more when browser is maximized, breaking the section UI. 

**[Notes]:**
- Same behavior occurs if the browser is resized when disabling the experiment and after window is maximized.
- The buttons return to normal size if page is refreshed.
- Screen recording of the issue: https://goo.gl/uXKB3z.

**Comment by SoftVision-PaulOiegas** [comment]
Just an addition to the initial behavior. This also reproduces when having the browser on half the screen (22 inch monitor), after enabling and disabling Notes experiment.
![image](https://user-images.githubusercontent.com/17258026/33716290-490ddfce-db5e-11e7-88b3-504d2b2a9e06.png)

Also, if the browser window size is a bit more narrow, the next thing occurs:

![image](https://user-images.githubusercontent.com/17258026/33716391-aca2a862-db5e-11e7-99eb-b31c0f632444.png)

**Comment by meandavejustice** [comment]
There isn't any real world scenario where a device is going to be switching resolutions while a user is viewing the site I can think of

**Comment by SoftVision-PaulOiegas** [comment]
Well, as I've said above, it's enough just to have the browser on half screen. Windows allows you to do this this very easy, you just need to press "Windows" key + "Left arrow" or "Righ arrow" depending on the side where you want it. If you do this while having the sidebar opened (bookmarks, Notes, Vertical Tabs, etc) and you are on the experiment details page, this issue occurs.

Here is a screen recording of it: https://goo.gl/X8zbyq. I'm using a 22 inch monitor FHD, so it's not a small screen and this still occurs. Probably even worse on smaller screens.

**Comment by chuckharmston** [comment]
<img width="952" alt="screen shot 2018-03-05 at 11 32 49" src="https://user-images.githubusercontent.com/23885/36992868-789eb61e-2069-11e8-9aeb-448ea4d73d38.png">
This bug no longer reproduces.

**Comment by SoftVision-PaulOiegas** [comment]
For now it doesn't, because a new issue was introduced in #3274. Will double check when that gets fixed.
