### ISSUE TITLE
Better filtering for Sentry logs

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#3075]
Seems like we have a lot of errors in Sentry caused by things outside our control that we won't ever be able to fix. Would be nice to squelch those messages to see things that we can address.

**Comment by fzzzy** [comment]
Many of the errors have paths that look like:

`/nwp/v0_0_1187/release/Shared/App/SharedApp.js`

I think we can safely filter anything that contains `/nwp/` as these machines are infected with malware and there is nothing we will be able to do to fix them. The example I just looked at was running Firefox 16.

Another class of errors is something we should actually fix, which I just filed a bug for:

https://github.com/mozilla/testpilot/issues/3072

After those two things are not showing up in sentry, we should probably take a look at each of the exceptions that comes in to see if there is anything else we can squelch or if they are actual bugs we can fix.

**Comment by chuckharmston** [comment]
Realistically, we are not likely to find time to do this.

**Comment by fzzzy** [comment]
Besides, in the last few months the sentry has been extremely quiet. I look at a lot of them, and they are almost always really ancient browser versions that are malware infested. We can't do anything about those.

But, this means we fixed the bugs that were causing the sentry to be noisy! \o/
