### ISSUE TITLE
Missing (container) Tab Centre

### ISSUE THREAD

**Issue by Ernstt** [mozilla/testpilot#3080]
Well i've been paitiently waiting on 57, hoping to get the Sidebar Tabs back...

The Tab Redux plugin does not work as nice as Tab Centre did, and in my opninion with screens beying oblong and sites beying landscape and resolution growing into 5k the waisted spece at the sides really should be USED to make space for the sites without loosing real estate at the top.

Not to forget the most usefull expansion of the sitepage names, which are trunckated with only 16 sites on the top tab bar, while with 30 ore more at the side, every page name can be read to distinguish the pages on the same site one works on...

How often do you click fruitlessly on several tabs to find teh info contact or whatever subpage you are working on?

Please reconsider the rebirth of Tabcentre !?!?!

**Comment by fzzzy** [comment]
@Ernstt Can you try Tree Style Tab, and check Tools -> Addons -> Extensions -> Tree Style Tab -> Preferences to see if it works for you?

https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

Or, alternatively, if you think there is a bug in Tab Redux or a missing feature that Tab Centre had, you could file a bug or a feature request for them:

https://github.com/eoger/tabcenter-redux/issues/new

57 allows addons in addons.mozilla.org to implement features for doing sidebar tabs. So, try a few out and see if any of them work for you.

Thanks for your feedback!

**Comment by Ernstt** [comment]
I've tried both, Redux looks a lot like the Test Pilot sidebar tabs Opera style, but it doesn't remove the tob tabs, but i will look if i can shut up the top tabs.

It works okay, but just thinking about the wider screen growth i would like to have all "controls" in the sidebar though i know this isn't the place for wishlists, thanks for the help.

This is just some feedback to show i've read your suggestions :-)

**Comment by SoftVision-PaulOiegas** [comment]
@Ernstt The top tabs can't be removed yet due to some missing API's in the new browser implementation. But as far as I know, the developers are already working on a way to allow this. 
Just so you know that it's not because of the extension. The original Tab Center would have had the same issue in Firefox 57.
Please bear with us a bit more until this is implemented.
