### ISSUE TITLE
Better handle missing mozAddonManager.

### ISSUE THREAD

**Issue by Keith94** [mozilla/testpilot#3083]
I get this page every time I load https://testpilot.firefox.com/ on Nightly.

![image](https://user-images.githubusercontent.com/5490615/32988446-cae80c58-ccb9-11e7-9c06-d85567d8415e.png)

**Comment by fzzzy** [comment]
@Keith94 Does it happen if you use a fresh profile?

**Comment by Keith94** [comment]
Nope, only happens in my main profile.

**Comment by chuckharmston** [comment]
@Keith94 Do you happen to have `privacy.resistFingerprinting` enabled?

**Comment by Keith94** [comment]
Oh, I do have `privacy.resistFingerprinting.block_mozAddonManager` disabled. That causes the issue...

**Comment by chuckharmston** [comment]
That is exactly the problem; Test Pilot uses `mozAddonManager` to manage and install our experiments. We should handle this error more gracefully, though; I'm going to repurpose this bug to do so.

Thanks for the report!

**Comment by Keith94** [comment]
Thanks for the help.

**Comment by lmorchard** [comment]
Peeking at this - what does "more gracefully" mean? i.e. Do we message the user? Or act more like a visit from a non-Firefox browser and just disable the installation buttons? (I guess we should *not* show a call to action to install Firefox though)
