### ISSUE TITLE
Update visual for delete screenshot confirm window 

### ISSUE THREAD

**Issue by fangshih** [mozilla/testpilot#3085]
Delete shot confirm window are still using the old UI, I'll update the visual screens and spec soon.

**Comment by ghost** [comment]
@fangshih can you give us more details about what this bug is for?  This is for the Test Pilot tour of the Page Shot past experiment?  Or is this a screenshot bug?

**Comment by johngruen** [comment]
@fangshih, i think this is for the Screenshots repo

**Comment by youwenliang** [comment]
@johngruen yes I think she posted to the wrong repo...

**Comment by fangshih** [comment]
Sorry guys :P
