### ISSUE TITLE
Prevent the page background from scrolling

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#309]
... at least on the experiments details page. I haven't manually tested with the rest of the pages yet.
### Current behavior (before scroll)

![idea_town](https://cloud.githubusercontent.com/assets/557895/11315767/c9590852-8fac-11e5-844f-05de4c9d8873.png)
### Current behavior (after scroll)

![idea_town](https://cloud.githubusercontent.com/assets/557895/11315774/ea3a8adc-8fac-11e5-8b21-63972d4b3c7c.png)
### Current behavior (fixed header)

![idea_town](https://cloud.githubusercontent.com/assets/557895/11315781/1a9040f0-8fad-11e5-8a44-382bc49f43d7.png)

---
### Proposed solution:

Add `background-attachment: fixed` to the `body#idea-view` type selector. That way the gradient is always there and looks good with and without the blue header.

![idea_town](https://cloud.githubusercontent.com/assets/557895/11315795/4e60f5aa-8fad-11e5-8d04-5c7e4c41b00d.png)
![idea_town](https://cloud.githubusercontent.com/assets/557895/11315800/59dd4b68-8fad-11e5-9eab-8b8be19b19aa.png)
![idea_town](https://cloud.githubusercontent.com/assets/557895/11315803/62043306-8fad-11e5-90b1-87cbf8556657.png)

**Comment by pdehaan** [comment]
OK, maybe only on the experiments details page. It looks a bit unpleasant after scrolling if I try and hack the fixed background pos onto the homepage where the gradient is less subtle:

![idea_town](https://cloud.githubusercontent.com/assets/557895/11315826/cf96c9ce-8fad-11e5-9ff9-6700756ee177.png)

**Comment by johngruen** [comment]
First of all @pdehaan, you are not a fraud. Second of all, this was fixed by #304
