### ISSUE TITLE
Non-firefox users landing page message position

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3092]
The additional message should be placed below the header title instead of center aligned above the button.

Current Implementation:
![image](https://user-images.githubusercontent.com/8919308/33166222-71f5a0ba-d074-11e7-9018-cc1915b7b758.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/33166229-7bddb7de-d074-11e7-9d7a-58ba97d7de8f.png)

**Comment by johngruen** [comment]
@youwenliang this one is actually pretty complicated to solve...

**Comment by johngruen** [comment]
I'm moving this into stretch.

**Comment by youwenliang** [comment]
@johngruen Yes that's why I didn't try to fix this... the span is connected to the install button with different states.

**Comment by johngruen** [comment]
@youwenliang can we close it?

**Comment by meandavejustice** [comment]
Current Implementation LGTM
