### ISSUE TITLE
Enabled label layout padding

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3093]
The label has wrong padding size.

Current Implementation:
![image](https://user-images.githubusercontent.com/8919308/33166406-1178740a-d075-11e7-8664-f2fdc2f97647.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/33166412-18479e3c-d075-11e7-94dc-f78edd96d6d9.png)

checkout more details here:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Homepage_20170927/#artboard1

**Comment by SoftVision-PaulOiegas** [comment]
To be honest, I kind of like it more how it is right now. It looks sharper and modern. I thought Photon was all about sharp edges and no more round corners. 😆

**Comment by youwenliang** [comment]
@SoftVision-PaulOiegas The border-radius here is actually correct, same 3px. The issue here is the spacing around the text.

**Comment by SoftVision-PaulOiegas** [comment]
They look about the right size now. I would say it's fixed. 👍
