### ISSUE TITLE
Wrong font weight for experiment detail page subtitle

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3094]
1. Font-weight and line-height for subtitle
2. Indentation for the whole title section
3. Word wrapping for the privacy notice

Current Implementation:
![image](https://user-images.githubusercontent.com/8919308/33166636-e6b4b728-d075-11e7-8452-4320a446bba0.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/33166606-cd069ec2-d075-11e7-9351-8f8f593b4d0f.png)

(please ignore the wrong firefox logo in the screenshots)

**Comment by SoftVision-PaulOiegas** [comment]
1. Font weight was changed but I see an extra row between the subtitle and install button which is not in the design.
2. Indentation applied and looks like in the designs.
3. There is some word wrapping for the privacy, but not as narrow as in the design
 
@youwenliang @johngruen  Are you ok with current implementation or you want to remove the extra row and narrow down some more the word wrapping?

**Comment by youwenliang** [comment]
Thanks for the notice, I'll take a look!
