### ISSUE TITLE
Experiments page UI breaks when you return to it after enabling an experiment together with Test Pilot add-on

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3096]
**[Affected versions]:**
- Firefox 57.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down and click on any active experiments cards except Send.
3. Click the "Install Test Pilot & Enable <experiment_name>" button.
4. Click the "Add" button on the doorhanger displayed for experiment enable.
5. Dismiss the experiment tour and click the "Firefox" logo on top left.
6. Observe the page behavior. 

**[Expected result]:**
- You are redirected to the Test Pilot experiments page where all the page elements are correctly displayed and the welcome + newsletter sign up pop up is displayed over a page overlay.

**[Actual result]:**
- You are redirected to the Test Pilot experiments page, but almost all the page elements are wrongly displayed and the welcome + newsletter pop up is wrongly displayed in page. 

**[Notes]:**
- This also reproduces if the Test Pilot toolbar button is clicked instead of the Firefox logo.
- This issue does not reproduces on Production server so it's probably a recent regression.
- The issue does not reproduce if you use "Back" button for navigation.
- Screen recording of the issue: https://goo.gl/SLesYU.
- Screenshot: 

![test pilot ui break](https://user-images.githubusercontent.com/17258026/33172380-86a9c4e4-d058-11e7-98e3-12144eaa0d41.png)

**Comment by b4handjr** [comment]
I'd like to add an integration test for this.

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed, at least on the above scenarios. Tried other several approaches but I haven't managed to make the newsletter modal appear. Marking this as verified fixed. 👍
