### ISSUE TITLE
Notes experiment page does not reflect the latest UI changes and new engine features

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/testpilot#3097]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Navigate to https://testpilot.firefox.com/experiments/notes
2. Click on the video and observe the Notes features presented in the video.
3. Observe Notes UI in the screenshot below the video.
4. Click on the "Launch Tour" and observe the Notes UI presented in the tour.

**[Expected result]:**
2. In the video the new engine features and the latest UI changes are presented.
3. The heading letter "h3" is displayed instead of "16" font size value.
4. The images in the "Launch Tour" displays "P" instead of "14" font size value.

**[Actual result]:**
2. The video presents the older engine functionality.
3. The screenshot displays the "Text Size" button with "16" font size value.
4. The images in the "Launch Tour" displays  the "Text Size" button with "14" font size value. 

**[Notes]:**
- Attached a screen recording of the issue:
![notes_changes](https://user-images.githubusercontent.com/20083658/33268029-47682288-d384-11e7-9591-a8f31b0880f1.gif)

**Comment by johngruen** [comment]
Note that ckeditor is stil in alpha and so app icons etc will likely change over time.

**Comment by chuckharmston** [comment]
@ryanfeeley could we get some updated screenshots for this?

**Comment by ryanfeeley** [comment]
@chuckharmston This is the current mockup devs are working from BUT not built yet nor released. https://mozilla.invisionapp.com/share/6VBUYHMRB#/281041484_Firefox_Notes

**Comment by johngruen** [comment]
Let's do this with the multinote release

**Comment by johngruen** [comment]
this is fixed

**Comment by SoftVision-PaulOiegas** [comment]
True, true.
