### ISSUE TITLE
Revise Photonized website details

### ISSUE THREAD

**Issue by Pekochen** [mozilla/testpilot#3102]
Hi~We see AMO and Test pilot as our two significant websites under Firefox product line. To keep the same style and make sure follow the same design in some parts. After discussed with AMO team and DS team we've revised some details. Please make sure to turn on the note mode when you see the measurement. I made some notes there.
Thanks for your great help to fine tune these changes.
Please check the link as below for the latest measurement.
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/

**Comment by marniepw** [comment]
@youwenliang is this something you can own?

**Comment by youwenliang** [comment]
@marniepw sure I'll take a look. I might break this up into several github issues.

**Comment by johngruen** [comment]
assigning this one @youwenliang will break it down!

**Comment by youwenliang** [comment]
@johngruen I broke this issue into 6 different parts, should be a better way to start.
#3221  
#3222 
#3223
#3224
#3225
#3226

**Comment by johngruen** [comment]
Thank @youwenliang i'm going to go ahead and close this.
