### ISSUE TITLE
Not a single modal is working on Test Pilot dev server

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3105]
**[Notes]:**
- This issue reproduces for every single modal on the website (newsletter, uninstall, retirement, share, 404, tour, disable experiment)

**[Affected versions]:**
- Firefox 57.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click on "Install the Test Pilot Add-on" green button.
3. Observe the page behavior.

**[Expected result]:**
- After the TxP add-on is installed, you are redirected to the "/experiments" page where a modal is displayed with a welcome message over a darker overlay and containing a newsletter sign up form.

**[Actual result]:**
- After the TxP add-on is installed, you are redirected to the "/experiments" page, the darker overlay is displayed, but the modal is fully transparent.

**[Additional Notes]:**
- Here is a screen recording of the issue: https://goo.gl/Fs9gid.

**Comment by fzzzy** [comment]
:(

**Comment by fzzzy** [comment]
Ok, this fix seems to have worked.

**Comment by SoftVision-PaulOiegas** [comment]
The modals are correctly showing up now. 👍

**Comment by SoftVision-PaulOiegas** [comment]
`opacity: 0` seems to be again set for all modals. It seems that some of the yesterday merges probably overlapped your change Donovan.
We are not blocked on QA side since we can manually change that in dev tools, but should be fixed as soon as possible.

**Comment by meandavejustice** [comment]
Sounds like the two issues we had in the past couple of weeks where css animations haven't been being applied correctly on the dev server.

**Comment by fzzzy** [comment]
@meandavejustice Yes, it is the same issue, and @johngruen said he would fix it. We finally figured out the root cause, which is that the animation is not getting included in the generated css file. It needs to be converted into a mixin (I think)

**Comment by johngruen** [comment]
Yeah, root cause was cssNano changing keyframe names for the gulp part of our styles, and not getting picked up by webpack.

#3146 fixes this

**Comment by SoftVision-PaulOiegas** [comment]
Just checked and it seems fixed again. 👍
