### ISSUE TITLE
The "Install the Test Pilot add-on" button "Installing..." state is smaller than the default state 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3106]
**[Affected versions]:**
- Firefox 57.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the size of the "Install the Test Pilot Add-on" green button.
3. Click it and observe the size of the button when the "Installing..." state is displayed.

**[Expected result]:**
- Both the states of the button have the same size as per designs.

**[Actual result]:**
- The "Installing..." state of the button is smaller than the normal state.

**[Notes]:**
- Same issue is visible for the button from the experiments details page, but only for specific experiments (eg: Snooze Tabs).
- Here are the implementation vs design screenshots:

![install states](https://user-images.githubusercontent.com/17258026/33378866-f26f48c8-d51e-11e7-8a9c-ac9ba00b5d09.png)
![install design](https://user-images.githubusercontent.com/17258026/33378871-f7475232-d51e-11e7-8434-58b83cc18ae7.png)

**Comment by ghost** [comment]
Let's just add min-width for whatever this is in en-US
