### ISSUE TITLE
The "Shutting down..." uninstall animation no longer corelates with the text size 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3108]
**[Affected versions]:**
- Firefox 57.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click the top right "Settings" button and chose to "Uninstall Test Pilot" option.
3. Click the "Proceed" button on the displayed modal.
4. Observe the size of the "Shutting down..." loading animation.

**[Expected result]:**
- The animation it's surrounded by a white thin border and its size correlates with the string and only slightly exceeds it. 

**[Actual result]:**
- The animation no longer depends of the text size and greatly exceeds its size. Also, the white border is no longer displayed. 

**[Notes]:**
- Here is a screenshot of the issue:

![shutting down animation](https://user-images.githubusercontent.com/17258026/33385464-5deb0e72-d531-11e7-9977-2358c56f3d96.png)

**Comment by meandavejustice** [comment]
fixed in #3130

**Comment by SoftVision-PaulOiegas** [comment]
Nicely fixed. 👍 

![shutting down animation fix](https://user-images.githubusercontent.com/17258026/33656587-27b81996-da7f-11e7-8b76-77fb2f377eea.png)
