### ISSUE TITLE
addon-api should work without SDK

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#311]
The addon-lib looks great, but the search addon doesn't use the SDK, so we'll need to make a few changes. (More detail to come)

**Comment by meandavejustice** [comment]
Assigning to @6a68 To see what is needed for universal search.

**Comment by lmorchard** [comment]
Relevant to this issue is [this comment](https://github.com/mozilla/idea-town/issues/355#issuecomment-169358284) I just left on #355:

> Also thinking that the addon-api module could be pulled into the Idea Town addon proper (rather than maintained as a shared module) if the addon takes responsibility for all metrics pings and the interface for experiments is just nsIObserver events.
