### ISSUE TITLE
Try to get off airbnb lint config

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#3119]
Last sprint I updated all the dependencies except 5 of them. Let's try to get them all fully updated now.

**Comment by pdehaan** [comment]
Not sure if something like [**eslint-plugin-only-warn**](https://www.npmjs.com/package/eslint-plugin-only-warn) would be useful here.

> _"Downgrade errors to warnings"_

At least it may stop any build-busting ESLint errors as we swap out base ESLint config rules.

**Comment by fzzzy** [comment]
Thanks @pdehaan. I just squelched the error result in our code.

**Comment by fzzzy** [comment]
Getting off the airbnb config was a big enough change as it is; I'll open a new bug to update the dependencies.
