### ISSUE TITLE
The 404 modal does not follow the design

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3121]
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/404 page.
2. Observe the 404 page modal.

**[Expected result]:**
- The "404" page modal is looking and working as designed.

**[Actual result]:**
- The "404" modal has lots of differences from the design (see attached screenshot).

**[Notes]:**
- See attached screenshot:
![404 differences](https://user-images.githubusercontent.com/17258026/33564724-deddca10-d923-11e7-930f-fb961e0eaf94.png)

**Comment by ghost** [comment]
Let's not change the "Home" string
