### ISSUE TITLE
Test Pilot Homepage lacks the CSS formatting

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3136]
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Observe how the page elements are rendered.

**[Expected result]:**
- The Test Pilot Homepage is correctly rendered.

**[Actual result]:**
- The Test Pilot Homepage entirely lacks the CSS formatting.

**[Notes]:**
- The /experiments and other pages are correctly working.
- Strangely, Voice Fill experiment is not displayed on the Homepage when this occurs.
- When this occurs, the environment setup notes page is bypassed.
- See attached screenshot:
![txp no css](https://user-images.githubusercontent.com/17258026/33655879-06b228ce-da7d-11e7-8184-44c70707ad93.png)

**Comment by pdehaan** [comment]
Here's what I see in my Firefox Nightly DevTools (and Browser Console):

<img width="1439" alt="firefox_test_pilot_-_dev" src="https://user-images.githubusercontent.com/557895/33675116-5f15b95c-da66-11e7-8c35-1d0ef61c05ba.png">

<img width="1007" alt="browser_console_-2" src="https://user-images.githubusercontent.com/557895/33675424-5752f5a8-da67-11e7-83f2-96c0a82ef2f7.png">

---

And here's what I see in Google Chrome's DevTools:

<img width="1439" alt="firefox_test_pilot_-_dev2" src="https://user-images.githubusercontent.com/557895/33675337-15f58080-da67-11e7-8401-4c148c1598d6.png">

**Comment by lmorchard** [comment]
Yeah, this sounds like the usual unresolved issue we've been having with dev deployments colliding - the HTML gets references to one set of JS & CSS with hashes in the URLs, meanwhile a different set actually deploys and so there are 404s

**Comment by lmorchard** [comment]
And it looks like a recent dev deploy fixed this. Expecting this will keep occurring, since we haven't been able to figure out what the cause is. We've put checks in place to wait for cache invalidation, serialize deployments, etc and nothing has solved it

**Comment by SoftVision-PaulOiegas** [comment]
Would be helpful for us if you guys could double check at the end of your day that dev is loading properly after merges are performed on it. Otherwise we end up with 8 hours of work where we cannot test the Homepage. And that's a hell of a lost time... Especially when we are close to a new release.
