### ISSUE TITLE
Experiment tour header wrongly says that experiment is enable even if Test Pilot and the experiment are not

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3137]
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click on any of the active experiments cards (except Send one).
3. Click the "Launch Tour" button from under the experiment logo on left column.
4. Observe the modal title displayed on the header.

**[Expected result]:**
- Experiment name is displayed on header.

**[Actual result]:**
- "<experiment_name> enabled!" message is wrongly displayed.

**[Notes]:**
- This seems to be a regression. If I remember correctly, we had the same issue in the past and it was fixed.
- The issue occurs also on stage server.

![image](https://user-images.githubusercontent.com/17258026/33663873-3f70a696-da9a-11e7-82bd-1a90778dc655.png)

**Comment by SoftVision-PaulOiegas** [comment]
Nope! it seems the issue was only fixed for other browsers than Firefox. I can still reproduce it on latest Nightly.

![image](https://user-images.githubusercontent.com/17258026/33774231-49b8f626-dc43-11e7-961b-f6ad054cd9e3.png)

**Comment by fzzzy** [comment]
I noticed that too, and added a comment on the pr after it was merged with the fix:

https://github.com/mozilla/testpilot/pull/3141/files#diff-3ad85f3d55f77ea89a30b4fcf0fa0868R53

**Comment by SoftVision-PaulOiegas** [comment]
Fixed along the way. Closing as it's correctly working. 👍
