### ISSUE TITLE
Experiment gets enabled and tour modal is displayed only when the install confirmation doorhanger is dismissed

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3142]
**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile. 

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click on any of the active experiments cards that are not enabled (except Send one).
3. Click on the "Enable <experiment_name> button.
4.  Click the "Add" option when prompted in the doorhanger.
5. Observe the page behavior.
6. Click on the "OK" button from the doorhanger or anywhere outside of it. 

**[Expected result]:**
- Step 5: The experiment is installed, the experiment tour modal is displayed and the doorhanger informs that the add-on was added to Firefox.
- Step 6: The doorhanger is dismissed without affecting the page functionality.

**[Actual result]:**
- Step 5: The experiment wrongly remains in "Enabling..." loop no matter how log you wait.
- Step 6: The doorhanger is dismissed and only now the experiment tour modal is displayed and confirms that it was enabled.

**[Notes]:**
- This issue reproduces on all servers and seems to be a regression.
- here is a screen recording of it: https://goo.gl/rCjg4Z.

**Comment by fzzzy** [comment]
I'm pretty sure this is the way things have to be going forward. Personally, I like it better.

**Comment by SoftVision-PaulOiegas** [comment]
I know for sure this wasn't happening before our latest deploy and this is not how AMO website works for example. 
You already confirm in the doorhanger that you want to add the add-on to the browser. The doorhanger that you need to dismiss on Test Pilot, acts just for page change to display that add-on was enabled and tour display. While the add-on is already installed and working in the back.

It's a minor issue for sure, but I personally find it annoying. However, as always, it's up to you guys to decide.

**Comment by ghost** [comment]
@andymckay -- is this working as intended?  (We're basing this on the promise from mozaddonmanager).  If so, we'll wontfix, just want to make sure since the behavior is different from AMO.

**Comment by andymckay** [comment]
It might be good to check what promise or events TestPilot is listening to. I think it would be better not to depend upon the dialog being clicked because I can imagine users can navigate away without clicking OK and triggering the end state. Probably to ask @aswan from the Firefox side or @tofumatt from the AMO side as to how it works there.

I checked in about:addons and it doesn't exhibit this behaviour, which is what @SoftVision-PaulOiegas said as well.

**Comment by tofumatt** [comment]
This is exactly how `mozAddonManager` works on AMO; the events we listened to in the past that would allow a "silent" install (or at least one with zero user interaction after `mozAddonManager.install()` was called) now forces the user to confirm installation with the list of permissions.

I'm not a huge fan of the UX either but it is a change Firefox has made for installs using `mozAddonManager` so users can see permissions I think.

Interesting point that Disco Pane doesn't exhibit this behaviour. I wonder if pages running un `about:` URLs (even in iFrames) are different? Or maybe just the disco pane URL is different?

**Comment by andymckay** [comment]
@tofumatt if you watch the video though, I think its about the second door hanger, the one that confirms the install happened where a user clicks OK. The "enable" button doesn't change state till they click OK.

**Comment by aswan** [comment]
You should be able to listen to the onInstalled event.  That event should fire at the same time the post-install notification is displayed so you can update the button at that time (note that onInstalled is a global event so its a little gross but you'll need to make sure its actually an event for the extension you care about and not some other extension).
I'm pretty sure we deliberately made the install promise not resolve until that notification is dismissed to keep the onboarding flow for the main test pilot extension smooth :)

**Comment by dannycoates** [comment]
wontfix? I mean technically we can do it but it makes the code more complicated for questionable gain. @johngruen?

**Comment by johngruen** [comment]
WFM
