### ISSUE TITLE
Update /frontend/tasks/styles.js to lint sass files in component directories

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3144]
and fix lint errors

https://github.com/mozilla/testpilot/blob/master/frontend/tasks/styles.js#L16

`config.SRC_PATH + '/styles/**/*.scss',` becomes `config.SRC_PATH + '/**/*.scss',`

**Comment by ppatel221** [comment]
Hey im a student whos taking an Open-Source Development class at Seneca College. Im currently looking for a bug to fix. Is it okay if i work on this?

**Comment by meandavejustice** [comment]
@ppatel221 You sure can, let me know if you have any issues, I'm in the #testpilot irc channel as JSON_voorhees

**Comment by ghost** [comment]
@ppatel221 are you working on this?  Do you have any questions?

**Comment by marvinsanchez1** [comment]
@meandavejustice I'm interested in this bug if the person above doesn't fix the issue :)

**Comment by meandavejustice** [comment]
Thanks for the interest @msanchez5, this was just fixed in #3155.
