### ISSUE TITLE
[UI] All website modals have pixelated corners instead of perfectly round

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3148]
**[Notes]:**
- This issue occurs on every modal from the website.

**[Affected versions]:**
- Firefox 57.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile. 

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click the top right "Setting" button and choose the "Uninstall Test Pilot" option.
3. Zoom in to 200% and observe the uninstall modal corners.

**[Expected result]:**
- The modal corners are perfectly rounded.

**[Actual result]:**
- The modal corners are pixelated.

![pixelated corners](https://user-images.githubusercontent.com/17258026/33843571-704e4448-dea6-11e7-8a58-32bcbaafec99.png)

**Comment by ghost** [comment]
"I'm very sorry."  --@johngruen

**Comment by chuckharmston** [comment]
We're just using `border-radius` here, I don't think this is something we can control. @SoftVision-PaulOiegas this might be a good candidate for a m-c bug though.
