### ISSUE TITLE
Entering in Full Screen mode with "F11" key is not working over the experiment "Tour" modal

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3151]
**[Notes]:**
- This issue occurs both with or without Test Pilot add-on installed.
- The issue occurs also when the modal is displayed after enabling the experiment.
- The "Full Screen" button from browser menu works perfectly over the problematic modal.
- The "F11" key Full Screen functionality correctly works over all the other modals.
- Here is a screen recording of the issue https://goo.gl/GBGjLt.

**[Affected versions]:**
- Firefox 57.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Click on one of the available experiments cards (except Send).
3. Click the "Launch Tour" button from left column.
4. Press the keyboard "F11" key and observe the browser behavior. 

**[Expected result]:**
- Browser correctly enters in full screen mode expanding and re-positioning page elements.

**[Actual result]:**
- Browser remains stuck in the current window size while the "Tour" modal is displayed.

**Comment by johngruen** [comment]
I think the modals consume basically all keypresses.

**Comment by SoftVision-PaulOiegas** [comment]
Working ok now on Windows and MacOS. 👍
