### ISSUE TITLE
Settings button looses the increased opacity if hovered away while its menu is opened

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3156]
**[Affected versions]:**
- Firefox 57.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile. 

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Hover the tp right "Settings" button and click it.
3. After the doorhanger menu appears, hover away from the "Settings" button.
4. Observe its behavior.

**[Expected result]:**
- The button remains at ".8" white opacity to signal that it's active. 

**[Actual result]:**
- The button wrongly returns to its ".6" opacity value. 

![opacity](https://user-images.githubusercontent.com/17258026/34265989-5b4404e8-e680-11e7-8626-488a6d5be06b.png)

**Comment by shikhar-scs** [comment]
@SoftVision-PaulOiegas I would have loved to work on this issue however I fail to see a settings button I dont why
![settings](https://user-images.githubusercontent.com/25258877/34297482-68f31e08-e73e-11e7-8315-846b6c786d03.png)

**Comment by SoftVision-PaulOiegas** [comment]
@shikhar-scs And you won't find it ever if you visit https://testpilot.dev.mozaws.net trough Google Chrome browser. 😄  The Test Pilot platform is only for Firefox browser users.

Also, if you will visit it from Firefox, first you'll need to set several prefs for the dev server, in the browser "about:config" page:
`extensions.legacy.enabled = true`
`xpinstall.signatures.required = false`
`testpilot.env = dev`
`extensions.webapi.testing = true`
`extensions.install.requireBuiltInCerts = false`

After this, please visit https://testpilot.dev.mozaws.net page first, and install the Test Pilot add-on first as mentioned in "Prerequisites". Only after you'll be able to see the button.

**Comment by shikhar-scs** [comment]
> @shikhar-scs And you won't find it ever if you visit https://testpilot.dev.mozaws.net trough Google Chrome browser. The Test Pilot platform is only for Firefox browser users.

I'm really sorry @SoftVision-PaulOiegas I didn't notice that.
I'll configure my firefox accordingly and revert back as soon as possible.

**Comment by SoftVision-PaulOiegas** [comment]
No problem, and thanks for your involvement. let me know if I can help you with any other details. I'm one of the QA's for the platform.

**Comment by shikhar-scs** [comment]
@SoftVision-PaulOiegas
Just now I've downloaded `the firefox developer edition` and configured it accordingly as was required by the above configs.
Next, I set up testpilot as was given [https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md). Also after setting up I ran all the necessary commands listed for linux.

After following all the precautions and everything, whenever I open up `example.com:8000/` Nothing loads up, even though my console shows this
 `[21:24:45] webpack is watching for changes
`

**Comment by shikhar-scs** [comment]
@SoftVision-PaulOiegas mind helping a bit?

**Comment by fzzzy** [comment]
@shikhar-scs Mozilla is closed until the new year, so we probably won't be fast to respond until then.

If you type `ping example.com` does it resolve to 127.0.0.1? Make sure your /etc/hosts file has a line mapping example.com to 127.0.0.1 and it is being used so that when you type example.com in the browser, it resolves to 127.0.0.1.

Also, you can try viewing `https://127.0.0.1:8000/` to make sure the server is listening on port 8000. You will get an ssl error and then a page saying `Unapproved hostname!` but at least you will know the server is listening.

**Comment by shikhar-scs** [comment]
@fzzzy Ohk I'll try all of that and see what can be done. And any queries now, I'll post them after the new year then.

**Comment by shikhar-scs** [comment]
> If you type ping example.com does it resolve to 127.0.0.1?

Typing it in the console of the directory -> yes it does happen
> https://127.0.0.1:8000/

Error loading page always, which i guess, means that the server is not listening :( 
Lets discuss this after the new year.

**Comment by shikhar-scs** [comment]
@SoftVision-PaulOiegas If you are back, can we continue here please

**Comment by SoftVision-PaulOiegas** [comment]
Let's see. I just did the setup for local environment on my Windows and works. Here are he steps that I performed:
1. Clone the repo with `git clone https://github.com/mozilla/testpilot.git`.
2. Change directory to testpilot folder `cd testpilot`.
3. Change directory to addon folder `cd addon`.
4. Run `npm install` and `npm run package` commands.
5. Return to testpilot folder `cd ..`
6. Run `npm install` command also on the testpilot folder.
7. Open a new cmd window as administrator (right click on cmd and select run as administrator from context menu)
8. Run `echo 127.0.0.1 example.com >> %WINDIR%\System32\Drivers\Etc\Hosts` command to set the hostname in the network.
9. Install Firefox Dev edition and create a new profile (set in browser icon proprieties `-p -no-remote` attributes)
10. Navigate to `about:config` page in the browser.
11. Search for `xpinstall.signatures.required` and set it to `false`.
12. Search for `extensions.legacy.enabled` and set ti to `true`.
13. Add a new "String" type pref (right click in the list) with `testpilot.env` = `local`.
14. Add a new "Boolean" type pref with `extensions.webapi.testing` = `true`.
15. Add a new "Boolean" type pref with `extensions.install.requireBuiltInCerts` = `false`.
16. With the browser opened, return to the first cmd window and run `npm start` command.
17. Navigate to [https://example.com:8000/](https://example.com:8000/)
18. First time you will need to add an exception for the page, but after that it correctly works.

In order to install the Test Pilot add-on, you will have to change the `testpilot.env` pref to `dev' and install it from `testpilot.dev.mozaws.net` page. After change back the `testpilot.env` pref to `local` and you are good to go.

Probably for Linux some steps might be slightly different, but let me know if you encounter any issues and we'll see what we can do. I have a Ubuntu machine but I haven't tried to setup it there yet.

**Comment by shikhar-scs** [comment]
@SoftVision-PaulOiegas I followed almost all these steps as it is (making minor changes as I work on ubuntu ) however still I am getting the following 
![screenshot from 2018-01-04 18-16-15](https://user-images.githubusercontent.com/25258877/34564086-6422105e-f17b-11e7-98b5-db354a5dd830.png)



I've tried `https://127.0.0.1:8000` `localhost:8000` `https://example.com:8000/` and even `https://0.0.0.0:8000` however none of them seem to work 



>  create a new profile (set in browser icon proprieties -p -no-remote attributes)

I wasn't able to get this so can this be the reason maybe ?

**Comment by SoftVision-PaulOiegas** [comment]
I'll retry the setup on Ubuntu myself and let you know.

**Comment by shikhar-scs** [comment]
Yeah sure 

Also lookup if this might be a cause

> create a new profile (set in browser icon proprieties -p -no-remote attributes)

**Comment by SoftVision-PaulOiegas** [comment]
Those attributes have the following roles:
`-p` = starts browser with profile window
`-no-remote` = allows multiple instances of the browser to be opened with different profiles. You can work without those, but we are using them since we usualy create multiple profiles daily,

**Comment by SoftVision-PaulOiegas** [comment]
Works ok on my Ubuntu 16.04 LTS. The steps are a bit different, so here we go:

1. Open a new terminal window and clone the repo with `git clone https://github.com/mozilla/testpilot.git`.
2. Change directory to testpilot folder `cd testpilot`.
3. Change directory to addon folder `cd addon`.
4. Run `npm install` and `npm run package` commands.
5. Return to testpilot folder `cd ..`
6. Run `npm install` command also on the testpilot folder.
7. Open a new terminal window, write `sudo su` and enter your password when prompted.
8. Run `echo '127.0.0.1 example.com' | sudo tee -a /etc/hosts` command.
9. Download and extract the Firefox Developer edition archive.
10. Open a new terminal window, drag the "firefox" file in it from the extracted folder
11. Write the `-p` and `-no-remote` options and hit "Enter" key. 
12. Create a new profile and after opened, navigate to `about:config` page in the browser.
13. Search for `xpinstall.signatures.required` and set it to `false`.
14. Search for `extensions.legacy.enabled` and set ti to `true`.
15. Add a new "String" type pref (right click in the list) with `testpilot.env` = `local`.
16. Add a new "Boolean" type pref with `extensions.webapi.testing` = `true`.
17. Add a new "Boolean" type pref with `extensions.install.requireBuiltInCerts` = `false`.
18. With the browser opened, return to the first terminal window and run `npm start` command.
19. Navigate to [https://example.com:8000/](https://example.com:8000/)
20. First time you will need to add an exception for the page, but after that it correctly works.
 
![image](https://user-images.githubusercontent.com/17258026/34569210-bdc81da2-f170-11e7-8e64-78d69c4c4c48.png)

**Comment by SoftVision-PaulOiegas** [comment]
One more thing, be sure you have latest `git` and `npm` installed before you try to clone the repo.
You can get them with `sudo apt-get install git` and `sudo apt-get install npm`. Otherwise you'll probably get some errors that might affect the setup.

**Comment by shikhar-scs** [comment]
Yeah all of that has been there since the beginning.

**Comment by SoftVision-PaulOiegas** [comment]
Good, then you please delete the previous clone of testpilot repo and redo it from scratch with the last provided steps and let me know if it's ok.

**Comment by shikhar-scs** [comment]
Ok Ill do that tomorrow,currently I am a bit occupied ... Thanx for all the help anyways ☺️

**Comment by SoftVision-PaulOiegas** [comment]
@shikhar-scs Have you managed to setup the dev environment?

**Comment by shikhar-scs** [comment]
This went off my mind completely, sorry for that. I'll do this ASAP and report here.

**Comment by shikhar-scs** [comment]
@SoftVision-PaulOiegas tried twice, sadly the same window shows up , the screenshot in the comment above. I'll move on to some other issue rather :+1:

**Comment by chuckharmston** [comment]
This was a great catch, but the fix for this would involve blocking off the ability to click on `Blog` and part of `News Feed` while the settings menu is open. Given that choice, I'd prefer this behavior.
