### ISSUE TITLE
Legal modal dialog isn't always launched from featured experiment section

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3158]

**Comment by chuckharmston** [comment]
I have no idea what this is referring to, but I couldn't reproduce. I'll close for now, but would appreciate it if you could take a poke at it @SoftVision-PaulOiegas.

**Comment by SoftVision-PaulOiegas** [comment]
I think it was related to the "Notes privacy policy" button that opens the Notes privacy message in a modal. I think we had another issue for this that was fixed a while ago. 
Tried to reproduce it too, but I don't think it's still happening.
