### ISSUE TITLE
Other experiments render funny locally if you have a featured experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3159]
### With no `is_featured: true` experiments:

<img width="1440" alt="firefox_test_pilot1" src="https://user-images.githubusercontent.com/557895/34276304-aa3400e2-e655-11e7-8dee-f142ed5b96f8.png">

---

### With one `is_featured: true` experiment:

<img width="1440" alt="firefox_test_pilot2" src="https://user-images.githubusercontent.com/557895/34276284-8c20a5f6-e655-11e7-875a-7695c451fdfa.png">

**Comment by pdehaan** [comment]
This is tricky... Not sure if we should make the dev-only **Dev Example** experiment featured, so we can verify UI on testpilot.dev.mozaws...

---

Conversely, let's just set **Notes** or **Send** to be featured for the next deploy and test out this fancy new UX w/ real users.

**Comment by johngruen** [comment]
uh, this no longer happens
