### ISSUE TITLE
"Welcome to Test Pilot" on homepage takes up too much vertical space

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3161]
Found in 17c86e7b049c78b8cbebdfef1fa46801d99183f4

```json
{ "commit":"17c86e7b049c78b8cbebdfef1fa46801d99183f4",
  "version":"", 
  "source":"https://github.com/mozilla/testpilot",
  "build":"https://circleci.com/gh/mozilla/testpilot/6427" }
```

---

### Steps to reproduce:

1. Go to https://testpilot.dev.mozaws.net/ (without add-on installed)
1. Go to https://testpilot.dev.mozaws.net/ (WITH add-on installed)

### Actual results:

Using 378px of vertical space to say "Welcome to Test Pilot" seems a bit excessive.

<img width="1439" alt="firefox_test_pilot_1" src="https://user-images.githubusercontent.com/557895/34312034-04fb97a4-e716-11e7-8d7d-395c1b0af7d2.png">

**Figure 1:** Without add-on installed (940 x 450).

---

<img width="1437" alt="firefox_test_pilot" src="https://user-images.githubusercontent.com/557895/34311995-c7719d48-e715-11e7-86b3-98451f1fa49c.png">

**Figure 2:** _With_ add-on installed (940 x 378).

If we move "Welcome to Test Pilot" beside the copter image, it'd be about 280px high, saving us ~100px of precious vertical space.

<img width="1439" alt="firefox_test_pilot_3" src="https://user-images.githubusercontent.com/557895/34312142-cd14321e-e716-11e7-8a10-494b8689d015.png">

**Comment by egefeyzioglu** [comment]
Will look into the issue

**Comment by chuckharmston** [comment]
This is very reasonable, but needs UX work, and we don't really have UX resources right now.

**Comment by johngruen** [comment]
I fixed this awhile ago
