### ISSUE TITLE
Funky rendering of featured experiments if undefined video_url

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3162]
Per https://github.com/mozilla/testpilot/pull/3114#issuecomment-353461457

> When I try setting Min-Vid to the featured experiment, it seems to have a big gap where I'd expect a video/image to be:
>
> ![](https://user-images.githubusercontent.com/557895/34275458-44c5c310-e652-11e7-95fe-30a8b8954f43.png)

I checked the 5 active experiments (and the dummy "Dev Example" experiment), and the only two experiments that didn't render correctly are:
- [Snooze Tabs](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/snooze-tabs.yaml)
- [Min Vid](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/min-vid.yaml)

As far as I can tell, those are the only two experiments that don't specify a `video_url`:

https://github.com/mozilla/testpilot/blob/17c86e7b049c78b8cbebdfef1fa46801d99183f4/frontend/src/app/components/FeaturedExperiment/index.js#L64

https://github.com/mozilla/testpilot/blob/17c86e7b049c78b8cbebdfef1fa46801d99183f4/frontend/src/app/components/FeaturedExperiment/index.js#L97-L105

Not sure if we need to create some YouTube videos for **Snooze Tabs** and **Min Vid**, or if we need to fall back to some Tour carousel if no `video_url` exists.

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, those 2 don't have video presentations and I bet there won't be any for old experiments. Probably showing some image with the functionality would be nice.

**Comment by johngruen** [comment]
I agree, using an image would be a good fallback here.

**Comment by ChenMorpheus** [comment]
@johngruen @SoftVision-PaulOiegas We can quickly grab what we have to create two images for these. Let me check with Fang for help.

**Comment by fangshih** [comment]
Hey guys, here are the images. Let me know if it works, or you need any other pages for it.  

**Mid Vid**
![image_midvid](https://user-images.githubusercontent.com/4862573/34603574-65253976-f23f-11e7-9eb1-f6048c7f3f44.png)

**Snooze Tabs**
![image_snooze](https://user-images.githubusercontent.com/4862573/34603576-6555cdde-f23f-11e7-81a8-d32bab41470f.png)

**Image assets:**
https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Website/%233162_experiments_video_image

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen is the one to decide here. Just one opinion from me. Maybe having Min Vid over a lighter background would be better. It looks a bit clogged with all the writing behind.

**Comment by meandavejustice** [comment]
I agree with the having an image as a fallback.

We shouldn't need to add images for Min Vid or Snooze Tabs unless we plan to make them featured experiments (which seems unlikely at this point)

**Comment by fangshih** [comment]
Hey @SoftVision-PaulOiegas  I do have a lighter version of it. I'll upload to [here](https://github.com/mozilla/testpilot-assets/blob/master/Test_Pilot_Website/%233162_experiments_video_image/image-midvid-light.png) 
 as an option.

**Comment by dannycoates** [comment]
how about no featured experiments without videos?

**Comment by johngruen** [comment]
deal
