### ISSUE TITLE
Visiting site in iOS Firefox shows errror message

### ISSUE THREAD

**Issue by mgaudet** [mozilla/testpilot#3169]
... instead of saying “can’t install test pilot extensions on iOS”

**Comment by johngruen** [comment]
I'm seeing this too. Per our support matrix we should be supporting FXiOS

**Comment by fzzzy** [comment]
Yes, this has been a bug for a long time. What happens is that we see that the browser is Firefox, but then mozAddonManager is not available, so we get confused about that.

**Comment by SoftVision-PaulOiegas** [comment]
Dupe of #2642

**Comment by johngruen** [comment]
Hey @mgaudet we are gonna fix this one this week, but we'll track it in #2642.
