### ISSUE TITLE
Do something with our Frame Scripts

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3176]
As part of our departure from bootstrap, we need to do something with this:

> Frame Scripts to set window.navigator properties - our legacy way of informing about:home & mozilla.com pages about Test Pilot participation

Maybe we can just drop this?  Why do those pages need to know about Test Pilot?

**Comment by lmorchard** [comment]
> Maybe we can just drop this? Why do those pages need to know about Test Pilot?

Folks (I forget who) wanted snippets on about:home to be tailored / filtered on whether or not the user was participating in Test Pilot. That way, we could promote joining Test Pilot to users without, or promote the latest experiment for users with. 

There's code currently in snippets JS logic that looks for this navigator property, though I seem to have lost the link in my browser history. Whether this is actually being used currently, I don't know.

**Comment by lmorchard** [comment]
Here we go, this repo search on mozmeao/snippets-service seems to point to the implementation for about:home - maybe we could send a PR to remove it if nothing is using it:

https://github.com/mozmeao/snippets-service/search?utf8=%E2%9C%93&q=test+pilot&type=

As for mozilla.org sites, I don't know if it's in use or has ever been used

**Comment by lmorchard** [comment]
Another thing that just occurred to me: Sounds like snippets still uses this as a data source. Could we pitch in with a PR on their repo to expedite switching to a different solution? I haven't looked at the code surrounding the check for window.navigator.testpilotAddon. But if their client-side filters can support something async, we might be able to substitute a ping to the addon and add their origins to our content script config.
