### ISSUE TITLE
Figure out if we need install/uninstall tracking for test pilot add-ons

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3177]
This is still using bootstrap:

> Addon Manager - overall tracking install/uninstall of Test Pilot experiments for metrics

Do we still need this?

**Comment by lmorchard** [comment]
[We send a count of enabled experiments in the daily Telemetry ping](https://github.com/mozilla/testpilot/blob/master/addon/src/webextension/lib/metrics.js#L116). If we stop needing that, we can stop tracking installs / uninstalls. Or, if there's a way to count installed experiments from a WebExtension, we could do that instead - though I don't know how to do this off the top of my head.

**Comment by meandavejustice** [comment]
@lmorchard It looks like we can get our list of install experiments with the [management api](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management)

**Comment by lmorchard** [comment]
Yeah, I think at the point when we were coming up with these issues, that API only reported on themes - [and then only by using getAll, because oninstall / onuninstall weren't supported](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/management#Browser_compatibility). Probably want to verify it returns all the data we want

**Comment by fzzzy** [comment]
Can't we just use mozAddonManager for this? We know it works, it's not bootstrap, and we're whitelisted for it.

**Comment by fzzzy** [comment]
Actually, aren't we already using mozAddonManager for it? If so, it's not bootstrap, so maybe this can be closed as invalid.

**Comment by meandavejustice** [comment]
@fzzzy We still need an answer for how we should get the list of enabled experiments for the daily telemetry ping. We may be able to use the webextension management api for that, but we haven't verified that yet (I'll check that this afternoon). So we can't close the issue until that is resolved. But it looks like that may be the only question left to answer before install/uninstall handling is removed.

**Comment by lmorchard** [comment]
> Actually, aren't we already using mozAddonManager for it? If so, it's not bootstrap, so maybe this can be closed as invalid.

Yeah, no - this happens in the add-on, independent of website visits. It's for the daily telemetry ping that measures what experiments are active

**Comment by johngruen** [comment]
I will reach out to Ilana and Sunah about this, I don't know if this ping is behind our redash dashboards or if that's just a filter on the installed add-ons field in telemetry. I think it's the latter, but I will confirm.

**Comment by fzzzy** [comment]
@lmorchard the addon could load a hidden page which uses mozAddonManager to fetch the data, then sends it up to the addon.

Although if the other api does work, then it probably does make more sense to switch to that for the addon, then.

**Comment by meandavejustice** [comment]
I just remembered that we will also lose `disable` and `enable` events when removing the AddonManager tracking.
