### ISSUE TITLE
Drop startup deferral code

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3181]
In bootstrap:

> sessionstore-windows-restored event - defer init until after browser startup

With all the web extension improvements, hopefully this isn't a thing that we need to do manually anymore?

**Comment by meandavejustice** [comment]
This looks like it should be the one of if not _the_ last issue we address to close out the `bootstrap` issues. I vote that we bump it to `Sprint 41` milestone.

What do yall think @chuckharmston @clouserw

**Comment by ghost** [comment]
I don't know enough to talk about what order things should be done in.  Doing this last is fine with me.  I don't think we should kick it out of the sprint unless we have to though

**Comment by meandavejustice** [comment]
fixed in https://github.com/meandavejustice/testpilot/commit/9c11090c64b0205d3d2965f025703221883b9777
