### ISSUE TITLE
Drop nsIObserver

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3182]
From bootstrap:

> nsIObserver - hacky way to receive messages from legacy extension based experiments, used as proxy to telemetry and to manage a/b testing (may be unused now, though I think)

**Comment by lmorchard** [comment]
Not sure if anything is using this any more - the last experiment I remember using it was (I think) containers. I seem to remember Min Vid was using it, but stopped at some point?

**Comment by meandavejustice** [comment]
~~This is also used in [lib/appStartup.js](https://github.com/mozilla/testpilot/blob/0eed4b5eaa10becf3fa05bdf396529e9f0e302ec/addon/src/lib/appStartup.js) which affects how we lead all of our modules in bootstrap.js. Going to loop back around to this one after I've taken care of more of the other bootstrap issues.~~ This is actually #3181

**Comment by lmorchard** [comment]
FWIW, that `sessionstore-windows-restored` event observer is just a startup performance hack for a legacy add-on embedded webextension. Once we move to a pure webextension, we won't need it and can just rely on the default behavior of webextension loading.
