### ISSUE TITLE
Broken link on Development Quickstart

### ISSUE THREAD

**Issue by marvinsanchez1** [mozilla/testpilot#3194]
Broken link on [Reference to L9 on Quickstart](https://github.com/mozilla/testpilot/edit/master/docs/development/quickstart.md#L9).
Also, I tried to follow the instructions and I think the instructions needs to be updated for [For Windows hosts](https://github.com/mozilla/testpilot/edit/master/docs/development/quickstart.md#L93-L120)?
similarly on [2. Install the DevPrefs](https://github.com/mozilla/testpilot/edit/master/docs/development/quickstart.md#L51). Using FireFox Developer Edition V58.0b6 you can't install that plug in.

**Comment by SoftVision-PaulOiegas** [comment]
Yes, they need to be updated. I have just configured yesterday the environment on Windows 10 and Ubuntu 16.04LTS and mentioned the proper steps in a different bug (#3156). I'll see with the dev team how they want the file to be updated.

**Comment by ghost** [comment]
The link on line 9 works now, and the instructions that Paul wrote in #3156 were already added to the quickstart doc.  Closing this.
