### ISSUE TITLE
There is no relationship between the test pilot or any add-on being installed and the test pilot UI

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3196]
## STR

1. Install Test Pilot
2. Go to an experiment page

## Expected
The ui should reflect that test pilot is installed

## Actual 
it does not

This bug appears to affect Test Pilot quite globally and has significant bad effects on Test Pilot UX

here's a video demonstrating the bad state on both the test pilot home page and experiment pages.

https://www.dropbox.com/s/0zmlafmlk7uezld/bad-state-everywhere.mov?dl=0

**Comment by johngruen** [comment]
TLDR:

If test pilot is installed i should never see a prompt to install it.

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Check `about:addons` page and look for TxP add-on. I have a feeling it appears as disabled. Which means you forgot yo set `extensions.legacy.enabled` to `true`.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas No effect there, though i can install from stage/dev now :)

**Comment by johngruen** [comment]
You can see in the video that the add-on is active.

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, my bad, thought you were testing on dev / stage. The stage server seams unaffected, same for dev. So it's something related to the production server only. 

The stranger part is that if I install the stage xpi, change the `testpilot.env` pref back to production, the production website correctly works. So it might be something with the production xpi.

**Comment by johngruen** [comment]
@fzzzy @lmorchard the issue here appears to be as follows:

@fzzzy ~~landed some new add-on~~ removed polling code recently that checks the `testpilot.env` pref. This pref is not explicitly set by the add-on in production, but the new code expects it to be there. We didn't observe this in dev/stage b/c in those contexts the pref must be set explicitly.

I can fix this bug by explicitly adding `testpilot.env` and setting the value as `production` in a clean profile.

**Comment by lmorchard** [comment]
> landed some new add-on polling code recently that checks the testpilot.env pref. 

That explanation isn't quite right, still investigating... thing is, [we *removed* polling code](https://github.com/mozilla/testpilot/commit/95c0462e8773112c5edfd8026ffbce66f76c1cdb) and the web front end doesn't have access to check prefs at all.

The presence or absence of the pref does seem to trigger the bug, but still looking into the mechanism.

**Comment by lmorchard** [comment]
To fix production for now, we've rolled back to [release 2017-12-6](https://github.com/mozilla/testpilot/releases/tag/2017-12-6). Also committed [a revert for the polling code cleanup](https://github.com/mozilla/testpilot/pull/3197), which seems to address the issue but we're not sure what the underlying cause is yet
