### ISSUE TITLE
Icon is hard to see with dark theme

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#320]
The default theme for Firefox Developer Edition is Dark, the idea town icon is hard to see against this theme.

![icon-demo](https://cloud.githubusercontent.com/assets/1844554/11377728/495d9670-929c-11e5-9a79-06b461a7d0ca.png)

**Comment by meandavejustice** [comment]
cc/ @johngruen

**Comment by johngruen** [comment]
@bryanbell @meandavejustice should this thing just be an SVG?

**Comment by bryanbell** [comment]
[Ideatown icons.zip](https://github.com/mozilla/idea-town/files/52478/Ideatown.icons.zip)
I included an inverted set.

**Comment by meandavejustice** [comment]
Thanks @bryanbell
