### ISSUE TITLE
Experiment page button style & CTA bar color

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3222]
There are some new updates on the buttons style on the top right corner, and CTA bar color (Voice Fill is enabled)

Current:
![image](https://user-images.githubusercontent.com/8919308/34758645-8b5607c0-f612-11e7-9847-b682b45e9117.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/34758620-697cb75c-f612-11e7-8414-3c83b1f2ce67.png)

Full spec: https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard20

**Comment by SoftVision-PaulOiegas** [comment]
The bar was green before Photonization. Why did we changed it in the first place? 😕

**Comment by ChenMorpheus** [comment]
@SoftVision-PaulOiegas So sorry about changing it again. We changed the color to the defined green in the Design system and followed the CTA button color to make it consistent. Besides, the original teal color would confuse users with the color of Voice Fill. Please find the link for more details, thanks.
https://design.firefox.com/photon/visuals/color.html

**Comment by SoftVision-PaulOiegas** [comment]
I see. Thanks for clarification. 

_Goes back to TestRail to update the testcase color._ 😄

**Comment by SoftVision-PaulOiegas** [comment]
Both bar and buttons were changed to match the designs. However, the vertical size of the green bar seems to be off by 4px (32 vs 36).

@youwenliang is this ok with you or it should be 36px?

**Comment by johngruen** [comment]
I'm going to assume that since mark both filed the issue and made the PR that this is cool
