### ISSUE TITLE
Update new get-started illustrations for non-testpilot user

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3223]
There are three new illustrations for the get started section

Current:
![image](https://user-images.githubusercontent.com/8919308/34758721-036b9630-f613-11e7-8be8-8639855cf4d7.png)

Spec:
![image](https://user-images.githubusercontent.com/8919308/34758724-09526880-f613-11e7-9a53-60c5a5aba75b.png)

Assets:
https://github.com/mozilla/testpilot-assets/blob/master/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/assets/illustration_01.svg
https://github.com/mozilla/testpilot-assets/blob/master/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/assets/illustration_02.svg
https://github.com/mozilla/testpilot-assets/blob/master/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/assets/illustration_03.svg
  
Full Spec:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard3

**Comment by SoftVision-PaulOiegas** [comment]
@youwenliang One suggestion here. If we are targeting especially the non-firefox users, why not moving the Firefox download button above the illustrations.  You cannot "Get Test Pilot add-on" until you have Firefox installed in the first place.

**Comment by youwenliang** [comment]
Actually, the "get-started" message is also showing for non-testpilot users, not just non-firefox users. I agree with you but I don't think that's a big problem, the button here is just another reminder to download firefox since there's already a download button on the top of the page.

(This is the main download button)
![image](https://user-images.githubusercontent.com/8919308/34811918-64560b6c-f6de-11e7-80ac-e12d96d39438.png)

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, it has been there for 2 years now. 😃 Anyway, it was just a UX suggestion that would apply only for non-firefox users since we will be working on that section soon.

**Comment by SoftVision-PaulOiegas** [comment]
The illustrations were correctly changed. 👍
