### ISSUE TITLE
New Photonized Footer design based on AMO

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3225]
Should update the footer design.

Spec:
![image](https://user-images.githubusercontent.com/8919308/34758955-4b660ad2-f614-11e7-8bdc-73e67a88a456.png)

Link:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard2

**Comment by dannycoates** [comment]
with strings this isn't going to make this sprint

**Comment by meandavejustice** [comment]
@youwenliang Can i get icons for github, twitter, and youtube. I am both going off of the above design but modifiying a bit to match footers across other mozilla properties(ie: https://www.mozilla.org/en-US/firefox/mobile/)

**Comment by youwenliang** [comment]
@meandavejustice  Here are the icons: https://github.com/mozilla/testpilot-assets/tree/master/Test_Pilot_Website/00_Assets/Icons

**Comment by meandavejustice** [comment]
@youwenliang can I get these in white, since they are used as background images
