### ISSUE TITLE
New Menu style for mobile view

### ISSUE THREAD

**Issue by youwenliang** [mozilla/testpilot#3226]
Currently, all the header links will disappear in mobile view, here a new proposal in the design spec for mobile menu (turn into hamburger menu):

![image](https://user-images.githubusercontent.com/8919308/34759048-b06bbd64-f614-11e7-8f83-5fddc5670127.png)

Full Spec here:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard11
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Photonized_Txp_Website_Final/#artboard12

**Comment by ghost** [comment]
closing in favor of other mobile issues
