### ISSUE TITLE
Update style for error message in newletter footer to match mockups

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3229]
context https://github.com/mozilla/testpilot/issues/3042#issuecomment-356557146

Error message in newsletter footer still looks like: 

![](https://user-images.githubusercontent.com/1844554/34687213-f6d74892-f4a5-11e7-9577-fceeeeca383f.png)

when it should look like:

![](https://user-images.githubusercontent.com/18019946/34703994-03627538-f531-11e7-8203-53419f12b8da.png)

**Comment by chuckharmston** [comment]
We're using browser UI for this rather than Test Pilot UI. Closing.
