### ISSUE TITLE
Navigation events are not being logged

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3232]
When we moved away from a single page app, we did not account for this change in the way we log navigation events. They aren't being sent to Google, since the browser navigation is preventing the request from firing off.

**Comment by johngruen** [comment]
I don't think this always true...i am seeing events while clicking on experiment cards

**Comment by chuckharmston** [comment]
We might be able to use `outboundURL` to fix this with a low level of effort, with some twiddling with event propagation:

https://github.com/mozilla/testpilot/blob/67531d1c0cefea3ce842b178b7330c1e0efb6937/frontend/src/app/containers/App/index.js#L199-L216
