### ISSUE TITLE
Test Pilot thinks it's installed when it isn't

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3233]
# STR
Uninstall test pilot from about:addons and go to testpilot.dev.mozaws.net. The site thinks test pilot is installed.

**Comment by fzzzy** [comment]
Close about:addons and then testpilot thinks it is uninstalled. This has been a longstanding issue that the addons manager keeps reporting that the addon is installed while the "undo" ui is visible.

**Comment by johngruen** [comment]
ah, got it.
