### ISSUE TITLE
Featured experiments UI lacks event reporting

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3234]

**Comment by chuckharmston** [comment]
In doing this, we should make sure that the featured block versions of [`Open Detail Page`](https://github.com/mozilla/testpilot/blob/e21e15c386aba1b6909e6dee022dae3debaf79f4/frontend/src/app/components/FeaturedExperiment/FeaturedButton.js#L84) and [`Give Feedback`](https://github.com/mozilla/testpilot/blob/e21e15c386aba1b6909e6dee022dae3debaf79f4/frontend/src/app/components/FeaturedExperiment/FeaturedButton.js#L93) each differentiate themselves from the regular versions.

**Comment by chuckharmston** [comment]
@teonbrooks, can we get a spec for this?

**Comment by johngruen** [comment]
@chuckharmston i think teon is at onboarding this week

**Comment by teonbrooks** [comment]
Here's a first pass on a spec for the featured experiment section of the TxP website:

### Event Category: `Featured Experiment`

| Description | eventAction | eventLabel |
| ------------ | ------------| ----------- |
| Click Featured Experiment Video | video click | Play Featured video
| Click View Details | link click | View Featured details
| Enable Featured Experiment | button click | Enable Featured
| Click General Terms link | link click | Open general terms
| Click General Privacy link | link click | Open general privacy
| Click Featured Experiment specific Privacy link | link click | Popup Featured privacy


Can we get any information about the video such as how many seconds/what percentage of video was watched? It might be interesting to see if watching the video is related to more enables.

**Comment by johngruen** [comment]
@teonbrooks yeah, we can get video data from our youtube metrics

**Comment by johngruen** [comment]
Also, @teonbrooks I think you'll need to think a bit more carefully about what buttons are shown when test pilot is installed vs. not installed...Additionally, can you specify whether [custom dimensions](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#custom-dimensions) will be applied to these metrics.

**Comment by chuckharmston** [comment]
A reference to what we can gather from the YouTube player: https://developers.google.com/youtube/iframe_api_reference

**Comment by teonbrooks** [comment]
just noticed that when I uninstall test pilot, all the experiments are still installed. is this the correct behavior?

there's a mismatch in what the button says and the noted state above the experiment.
<img width="450" alt="txp" src="https://user-images.githubusercontent.com/1578674/36288427-649e20f8-126f-11e8-9689-5a21561dad46.png">


few other comments/questions
-------------------------------
you can't screenshot on the test pilot page (likely known).
in the onboarding for screenshots, it reads that it is in beta, is that still true?

**Comment by johngruen** [comment]
@teonbrooks WRT the state mismatch that's a known issue.

The other two are by design: 
Test Pilot has a bunch of special permissions that mean you cannot run scripts on the page and Screenshots will be in beta for at least a few more release (gmail was in a public beta for like 10 years 😎)

**Comment by SoftVision-PaulOiegas** [comment]
@teonbrooks As @johngruen mentioned, the first issue you mentioned is already logged in #2378. However, this was only reproducible on experiments details page at the moment of logging. Now it also reproduces on the Homepage due to implementation of the "Featured Experiment" section that has the same broken functionality.

@johngruen Maybe we should raise the priority of #2378 because of this?

**Comment by chuckharmston** [comment]
@teonbrooks How's this going? Anything we can help with?

**Comment by chuckharmston** [comment]
Assigning to Dave for implementation.

**Comment by meandavejustice** [comment]
Everything here is completed (in #3435) except the featured video metric, I had some security concerns about adding the youtube_iframe api. The issue tracking that is https://github.com/mozilla/testpilot/issues/3436

**Comment by johngruen** [comment]
Okay, let's go ahead and verify/close this

**Comment by dannycoates** [comment]
video clicks won't be tracked by the page.

https://github.com/mozilla/testpilot/pull/3534#issuecomment-387153586
