### ISSUE TITLE
Confirm all events and make sure they're documented

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3237]

**Comment by johngruen** [comment]
- cancel from permissions is a thing, and needs to be documented
- accept from permissions is a thing, needs to be documented

**Comment by chuckharmston** [comment]
I've audited each event in the [Table of Events](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#table-of-events) in our documentation, and have found the following errors:

- ~`Click on experiment from landing page` is not implemented.~
- ~`Click on Install from experiment details page` is implemented, but seems to be in a dead code path.~
- ~`Click on the "Try out these experiments as well" section` is not implemented.~
- `Click Take Tour on tour dialogue` is not implemented.
- `Click on Install from landing page` is implemented, but seems to be in a dead code path. Additionally, there are no landing page install buttons except for the featured experiment section. That install button does not fire this event.
- `Click on experiment from landing page` has a race condition, and should use `outboundUrl` to make sure the event is logged.
- `Prompted to restart the browser` is implemented, but we no longer require restarts.

I'll be combing through the code next to find the events that are not documented in that table.

Update: I ~struck through~ a few events that were actually mis-documented.

**Comment by chuckharmston** [comment]
I've audited each event sent by code and have found the following errors:

- [`Sign Me Up`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/EmailDialog/index.js#L152) is not documented.
- [`email submitted to basket`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/EmailDialog/index.js#L160) is not documented.
- [`Skip email`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/EmailDialog/index.js#L187) is not documented. 
- [`On to the experiments`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/EmailDialog/index.js#L201) is not documented. 
- The various [`open`](https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/src/app/components/ExperimentRowCard/tests.js#L193) [`detail`](https://github.com/mozilla/testpilot/blob/e21e15c386aba1b6909e6dee022dae3debaf79f4/frontend/src/app/components/FeaturedExperiment/FeaturedButton.js#L84) page events are documented as `Open details page`.
- The [`dot to step`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/ExperimentTourDialog/index.js#L42) [events](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/NewsUpdatesDialog/index.js#L44) are not documented. 
- The featured experiment [`Open detail page`](https://github.com/mozilla/testpilot/blob/e21e15c386aba1b6909e6dee022dae3debaf79f4/frontend/src/app/components/FeaturedExperiment/FeaturedButton.js#L84) event does not differentiate itself from other `open detail page` events.
- The featured experiment [`Give feedback`](https://github.com/mozilla/testpilot/blob/e21e15c386aba1b6909e6dee022dae3debaf79f4/frontend/src/app/components/FeaturedExperiment/FeaturedButton.js#L93) event is not documented and does not differentiate itself from other `Give feedback` events. 
- The [`open blog`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/Header/index.js#L101) event is not documented. 
- The [`email failed to submit to basket`](https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/src/app/components/NewsletterFooter/index.js#L28) and [`email submitted to basket`](https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/src/app/components/NewsletterFooter/index.js#L28) events are not documented.
- The `NewsUpdatesDialog Interactions` events are not documented: [`forward to step`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/NewsUpdatesDialog/index.js#L28),  [`back to step`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/NewsUpdatesDialog/index.js#L36),  [`dot to step`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/NewsUpdatesDialog/index.js#L44),  [`cancel updates`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/NewsUpdatesDialog/index.js#L105),  [`complete updates`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/NewsUpdatesDialog/index.js#L117). 
- The [`retire`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/RetireConfirmationDialog/index.js#L65) event is not documented. 
- The [`news-item-`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/components/UpdateList/index.js#L103) event is not documented. 
- The [`cancel feedback`](https://github.com/mozilla/testpilot/blob/7fbfe8a7a67a0ee7d4a02d7bf0195fec7663743c/frontend/src/app/containers/ExperimentPage/ExperimentPreFeedbackDialog.js#L76) event is not documented. 
- The [`upgrade notice shown`](https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/src/app/containers/UpgradeWarningPage/tests.js#L24) event is not documented.
- The [`Accept From Permission`](https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/src/app/lib/InstallManager.js#L26) and [`Cancel From Permission`](https://github.com/mozilla/testpilot/blob/93c9ea7aa6104fbbdc21508e44d486d7ca7c77aa/frontend/src/app/lib/InstallManager.js#L32) events are not documented.

**Comment by chuckharmston** [comment]
Spun off #3301, but this will be otherwise be closed with #3300, so I'm closing this bug.
