### ISSUE TITLE
Documented add-on events are not firing

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3238]

**Comment by johngruen** [comment]
@chuckharmston it occurs to me that we should be getting a good proxy for these events through the utm params in the links generated by the toolbar button

**Comment by chuckharmston** [comment]
Implementation blocked on #3238

**Comment by chuckharmston** [comment]
Moving this to sprint 41 to stay out of @meandavejustice's way as he heavily works on the add-on this sprint.

**Comment by meandavejustice** [comment]
@johngruen can we review this, should have been fixed in the recent addon to webextension commit
