### ISSUE TITLE
inconsistent Enabled icon and color

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3243]
@ChenMorpheus can we get a bit more consistency here...

featured experiment:
<img width="188" alt="screen shot 2018-01-12 at 3 55 58 pm" src="https://user-images.githubusercontent.com/3323249/34880581-2eb44a04-f7b1-11e7-981b-40260b7dabb5.png">

experiment card:
<img width="190" alt="screen shot 2018-01-12 at 3 56 02 pm" src="https://user-images.githubusercontent.com/3323249/34880584-3284befc-f7b1-11e7-9732-e5259d510f57.png">

For what it's worth, the 'enabled' graphic on the featured experiment card really doesn't show up well on the blue background. I think using the green checkbox consistently would make more sense.

**Comment by Pekochen** [comment]
Hi @johngruen 
Our final featured experiment page design would be green label design which is the same style as experiment card. you can see the screenshot here
![2018-01-16 10 48 38](https://user-images.githubusercontent.com/8252151/34969836-c52095cc-faab-11e7-96ce-99bf100dd255.png)

**Comment by meandavejustice** [comment]
![homepage-featured](https://user-images.githubusercontent.com/1844554/35446283-1f59c664-02ac-11e8-95e9-ab1a9e278e1d.png)
I'm going to merge #3294, but I wanted to mention, the left side of the featured Experiment looks a little heavy now with the statuses moved to that side.
