### ISSUE TITLE
Do not include featured experiment in homepage card lists

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3244]
This should apply to Test Pilot both with and without add-ons installed.

**Comment by johngruen** [comment]
the featured experiment card should still appear on experiment detail page card lists.

**Comment by SoftVision-PaulOiegas** [comment]
Notes is no longer displayed on the Homepage or /experiments page. Also, the locales filter correctly works now. 👍 
Verified on Widows 10 and MacOS 10.13.
