### ISSUE TITLE
The "Featured Experiment section" for non-Firefox user misses the availability parenthesis

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3255]
**[Affected versions]:**
- Chrome
- Opera
- Safari
- Edge

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open a browser other than Firefox and navigate to https://testpilot.dev.mozaws.net page.
2. Observe both the Firefox download buttons and the elements that accompany them from top and bottom of the page.

**[Expected result]:**
- Both the buttons have above them a parenthesis that states "(Test Pilot is available for Firefox on Windows, OS X and Linux)"

**[Actual result]:**
- The top button from "Featured Experiment" section no longer displays the parenthesis. 

![missing parenthesis](https://user-images.githubusercontent.com/17258026/35054555-80a15b6a-fbb5-11e7-800b-c7d2ead3da1a.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Test Pilot dev server with Chrome, Safari and Edge and the availability message is correctly displayed in featured experiment section.
