### ISSUE TITLE
Hardcode gravatar to use HTTPS?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#326]
It looks like gravatar currently is hardcoded to use a protocol-less format:
[`return '//www.gravatar.com/avatar/%s?s=%s' % (email_hash, size)`](https://github.com/mozilla/idea-town/blob/6526f8f58b52596c871df8aa644c02e326350508/idea_town/utils.py#L78-L80)

This makes the developer tools output look a bit unpleasant and scary with a big lock with a red line through it. Not sure if it's worth just forcing the URL to always use HTTPS regardless of the protocol. Although I guess this is only a minor issue when testing on the dev server and the production server will only respond on HTTPS and not HTTP.

<img width="841" alt="idea_town_and_idea-town_package_json_at_master_ _mozilla_idea-town_ _github" src="https://cloud.githubusercontent.com/assets/557895/11697105/0772e724-9e86-11e5-88c6-8035e2365a56.png">

**Comment by lmorchard** [comment]
This would also end up being a problem for local dev, where it's always HTTP. We could possibly vary that on the `DEBUG` setting, though that would also break elastic beanstalk dev if/when we turn on `DEBUG` to diagnose issues

**Comment by pdehaan** [comment]
True, although it looks like the [fonts are hardcoded to HTTPS](https://github.com/mozilla/idea-town/blob/c30f62e04bc521a3b7c1dcd0f4d85ecdc88ab488/idea_town/frontend/templates/idea_town/frontend/index.html#L5): 
https://fonts.googleapis.com/css?family=Open+Sans:400,700,300

Feel free to close this out if it isn't worth it (which it doesn't sound like it is since it'd only be an issue in development environments).

**Comment by lmorchard** [comment]
Just going to close this for now... started poking at it a little, but things got tangly fast
