### ISSUE TITLE
/__version__ on testpilot.dev.mozaws.net has blank properties

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#3262]
We use this script to produce `/__version__` on the CircleCI build that goes to dev:

https://github.com/mozilla/testpilot/blob/master/bin/circleci/build-version-json.sh

However, as of the last build to dev, the properties in that file came out blank (look under "Build addon and frontend" and search for `cat version.json`):

https://circleci.com/gh/mozilla/testpilot/7061

My guess is that the switch to CircleCI 2.0 broke this script. Probably changes to environment variables, [though they look the same in docs to me](https://circleci.com/docs/2.0/env-vars/). Will probably call for some time tinkering in a build with SSH enabled to see what's happening with the script in the new environment.

**Comment by lmorchard** [comment]
(This shouldn't break on staging or production - those deployments use totally different infra and a [different script](https://github.com/mozilla/testpilot/blob/master/bin/build-version-json.sh))

**Comment by pdehaan** [comment]
**Current status:**

- https://testpilot.dev.mozaws.net/__version__

    ```js
    {
      commit: "",
      version: "",
      source: "https://github.com//",
      build: ""
    }
    ```

- https://testpilot.stage.mozaws.net/__version__

    ```js
    {
      commit: "c8d6171bbc1a56ac5cb5ee070ca6b6f806ea693f",
      version: "2018-01-19",
      source: "https://github.com/mozilla/testpilot"
    }
    ```

- https://testpilot.firefox.com/__version__

    ```js
    {
      commit: "d95706613444e96ab75ce12d723e19482d6d28df",
      version: "2017-12-6",
      source: "https://github.com/mozilla/testpilot"
    }
    ```
