### ISSUE TITLE
Sort out the polling code troubles

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3264]
I'm on the outside here so I'm trying to follow what happened, but I think:

- Some patches were written in #3007 that were cool but unrelated to the issue #2997 that the PR was for
- #3014 was filed to rebase and land those patches, and that was done in #3123 .  This patch landed and was pushed live.
- #3196 was filed that things were broken in production and #3197 was written and pushed live to revert #3123 

So, all the issues and PRs are closed, but we're back to the first bullet point up there.  I think we need a new issue (it can be this one) to remove the polling code again, only this time make sure it doesn't break anything. :)

**Comment by fzzzy** [comment]
We landed the fix for the problem that caused the rollback here:

https://github.com/mozilla/testpilot/pull/3198/files

We wanted to wait a release or two so that the add-on update is widely deployed, and then we are safe to re-apply the original polling code removal:

https://github.com/mozilla/testpilot/pull/3123/files

**Comment by divyabaid16** [comment]
May I work on this issue ? 
If yes, can you please guide me ?

**Comment by chuckharmston** [comment]
@divyabaid16 thanks for the interest! This is likely not a good bug for you to work on, we have some internal timing to work through. Instead, I'd suggest you look at our [Contribute](https://contribute.testpilot.firefox.com/) site, which lists good first bugs from across our projects.

**Comment by chuckharmston** [comment]
@fzzzy want to ship this during this sprint?
