### ISSUE TITLE
Notes Tour is wrongly displayed for a short period of time when Installing Test Pilot add-on

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3265]
**[Affected versions]:**
- Firefox v57.0.4 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Install test Pilot & Enable Notes" green button and also click the "OK" for the installation confirmation doorhanger.
3. Observe the Test Pilot page behavior.

**[Expected result]:**
- The welcome modal is correctly displayed for the user.

**[Actual result]:**
- The Notes "Tour" modal is wrongly displayed for a short period of time before it is replaced by the welcome pop up.

**[Notes]**
- This issue occurs also on Stage server.
- Here is a screen recording of the issue: https://goo.gl/urrNTi.

**Comment by meandavejustice** [comment]
It seems that in this case we would want the tour modal instead of the welcome modal, since the user is choosing to install both testpilot and the featured experiment.

Thoughts? @chuckharmston @johngruen

**Comment by chuckharmston** [comment]
I'm torn on this. The ideal user experience is probably the Notes tour with an additional final slide with the content from the welcome information, but that's a lot of work for a small bug.

I'll defer to John or @pekochen.

**Comment by SoftVision-PaulOiegas** [comment]
Well, from the start I said that this flow is a bit misleading because the first buttons say "Install Test Pilot & Enable Notes" as the one from the experiment details page, but doesn't behave like that one. You need to manually enable Notes after TxP is installed.

The only way I see it is to make the homepage button work as on the experiment details page and display the welcome pop up only when user will next navigate to the "/experiments" page. 
Or we need to change the entire flow to have consistency on these two. But, as you said, that might be to much for a small bug like this. 

I think this issue might be somehow related with an older issue that we have and we said we can live with it. Right now, if you click the same button on the experiment details page, you get both TxP and Notes installed and then you get the tour modal. If you navigate afterwards to the "/experiments" page, only then you get the welcome pop up with the newsletter form.

**Comment by johngruen** [comment]
So, the install experience for TXP and Notes should be one click only...
Flow should be as follows:
1. TXP installs
2. Notes installs
3. Notes onboarding happens
4. Email solicitation happens (stretch if possible: we should defer this to the next time the user goes to /experiments)

**Comment by meandavejustice** [comment]
@johngruen and @SoftVision-PaulOiegas Thanks for the replies, that definitely sounds right to me. It doesn't look like I'll be getting this in before the end of this milestone(tomorrow) but we should definitely do it next sprint.

**Comment by SoftVision-PaulOiegas** [comment]
Reopening because this issue still occurs and because the [desired flow](https://github.com/mozilla/testpilot/issues/3265#issuecomment-361646910) mentioned by @johngruen was not implemented. 
The newsletter modal is still the main displayed and the tour pop up is first displayed for ~1 second if the TxP add-on install confirmation doorhanger is dismissed.

**Comment by ghost** [comment]
Clearing the milestone for re-triage.  If we didn't implement that flow, what did we implement?

**Comment by SoftVision-PaulOiegas** [comment]
This was fixed in the following days from my message. However, yesterday we have found a new issue related (#3387). We'll close this one since the remaining issue is tracked under that. 
Thanks for bringing this up!
