### ISSUE TITLE
Notes Privacy modal is wrongly opened under the Tour modal after enabling Notes from "Featured Experiment" section

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3266]
**[Affected versions]:**
- Firefox v57.0.4 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click the "Notes" button from under the "Enable Notes" green button.
3. Observe the Test Pilot page behavior.
4. Click the "Enable Notes" green button and follow the process.
5. Dismiss the Notes experiment tour and observe the page behavior.

**[Expected result]:**
- Step 3: Nothing happens because Notes is not enabled (bug #3231).
- Step 5: The Test Pilot "Experiments" page is correctly displayed and Notes appears as enabled on the "Featured Experiment" section.

**[Actual result]:**
- Step 3: Nothing happens because Notes is not enabled (bug #3231).
- Step 5: The Notes Privacy modal is wrongly displayed.

**[Notes]**
- The Privacy modal is opened underneath the Tour modal because you can see that the overlay accompanies the Tour modal is darker when the above steps are performed since it's doubled by the one for the Privacy. 
- This issue occurs also on Stage server.
- Here is a screen recording of the issue: https://goo.gl/XuXBZr.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on Test Pilot dev server.
