### ISSUE TITLE
"Your privacy" and "Enable [experiment_name]" buttons are shortly displayed for a moment when you navigate to an enabled experiment page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3269]
**[Notes]**:
- I wasn't able to reproduce this issue on Windows 10 x64 and Windows 8.1 x32, but I have managed to reproduce it on Windows 7 x64.
- The issue is most noticeable on Mac OS and less noticeable on Windows 7.

**[Affected versions]:**
- Firefox 57.0.4 and above

**[Affected Platforms]:**
- Windows 7 
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on is already installed.
- At least one of the available experiments is enabled.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.stage.mozaws.net/experiments page.
2. Click on one of the enabled experiments card.
3. Observe the experiment page while is loading.

**[Expected result]:**
- The page is correctly loaded. 

**[Actual result]:**
- The "Your privacy" and "Enable [expriment_name]" buttons are quickly displayed for a fraction of a second before the "Give Feedback" and "Disable [experiment_name]" buttons appears.

**[Additional Notes]:**
- This behavior can also be observed if you refresh the page.
- This issue is not reproducible on production.
- Here is a screen recording with the issue: https://goo.gl/F71MQP

**Comment by chuckharmston** [comment]
We should defer rendering anything in these components until we know whether the user's state.

**Comment by chuckharmston** [comment]
This will be addressed in #3405.
