### ISSUE TITLE
[Featured Experiment] While it's already enabled, the "Enable Notes" button is shortly displayed each time the experiments page is loaded

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3270]
**[Notes]**:
- I wasn't able to reproduce this issue on Windows 10 x64 and Windows 8.1 x32, but I have managed to reproduce it on Windows 7 x64.
- The issue is most noticeable on Mac OS and less noticeable on Windows 7.

**[Affected versions]:**
- Firefox 57.0.4 and above

**[Affected Platforms]:**
- Windows 7
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on and Notes experiment are already installed.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.stage.mozaws.net/experiments page.
2. While the page is loading observe the "Featured Experiment" section.

**[Expected result]:**
- The correct state of the "Notes" experiment is displayed. 

**[Actual result]:**
- The "Enable Notes" button is shortly displayed for a moment even if the experiment is already enabled.

**[Additional Notes]:**
- Here is a screen recording with the issue:
![enable notes button](https://user-images.githubusercontent.com/19226534/35231947-d9d4594e-ffa2-11e7-82bb-3e29972f6541.gif)

**Comment by chuckharmston** [comment]
Duping this against the slightly more general #3269.
