### ISSUE TITLE
[Featured Experiment] Agreement string is the only one not localized in the supported languages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3273]
**[Affected versions]:**
- Firefox v57.0.4 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- A supported language different than English US [en-us] was added as top option for page content from Options>Language and Appearance section (eg. German [de]).

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Observe how the "Featured Experiment" section is localized in the selected language.

**[Expected result]:**
- The "Featured Experiment" section is fully localized in the selected language. 

**[Actual result]:**
- The "By proceeding, you agree to the terms and privacy of Test Pilot and Notes." string is not localized and it falls back to [en-us].

**[Notes]**
- Since we already have a translation for the string without "and Notes" termination on the bottom of the page, I think we can reuse that translation to have the top one localized too.
- Not entirely sure that this the same on all supported languages, but at least on the most important ones it is.
- This issue occurs also on Stage server.
- Here is a screenshot of the issue:

![agrreement not translated](https://user-images.githubusercontent.com/17258026/35279770-b6ba9784-0056-11e8-8165-6594d1a3658d.png)

**Comment by fzzzy** [comment]
This is the real problem. This string has simply not been translated, so we can't release this feature until it has been translated.

I would like to reuse the old string that doesn't include "and Notes", but I'm unsure how I can reuse this string and still properly localize the "and Notes" part.

**Comment by SoftVision-PaulOiegas** [comment]
The string is not entirely localized. See the "terms", "privacy" and "Notes privacy policy" words.

![string not entirely localized](https://user-images.githubusercontent.com/17258026/36799353-a88b6db6-1cb5-11e8-8415-e54da6a3f682.png)

**Comment by meandavejustice** [comment]
It sounds like this is still blocked by not having the string translated

**Comment by dannycoates** [comment]
fixed in #3517
