### ISSUE TITLE
Experiment details page buttons remain small shaped when browser window is resized to mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3274]
**[Affected versions]:**
- Firefox v57.0.4 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click on one of the available experiments that was not already enabled.
3. Resize the browser until experiment details page enters in mobile view.
4. Observe how the "Enable <experiment_name> button is displayed.
5. Click the "Enable <experiment_name> button and follow the flow to enable it.
6. Observe again how the "Feedback" and "Disable <experiment_name> buttons are displayed in mobile view.

**[Expected result]:**
- In both cases the buttons are displayed enlarged to follow the page style in mobile view.

**[Actual result]:**
- In both cases the buttons remain displayed small shaped as on maximized page.

**[Notes]**
- This issue occurs also on Stage server.
- Here is a screenshot of the issue:

![small buttons on mobile view](https://user-images.githubusercontent.com/17258026/35283132-048f67e2-0060-11e8-9095-ddde143d06eb.png)

**Comment by ghost** [comment]
closing in favor of #3504
