### ISSUE TITLE
Resizing the browser causes the fonts to try and reload a bunch of times

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#328]
After loading the Idea Town site, I foolishly tried to resize my browser (more specifically my dev tools panel) and this seems to cause the fonts to try and reload a metric ton of times:

<img width="851" alt="idea_town_and_idea_town" src="https://cloud.githubusercontent.com/assets/557895/11698508/eef47026-9e8c-11e5-8b19-293e8d03188d.png">

The good news is that the fonts are seemingly cached and don't re-download, but it seems a bit weird.

**Comment by meandavejustice** [comment]
I have a hunch this is because some of our font sizes are declared in percentages. https://github.com/mozilla/idea-town/blob/master/idea_town/frontend/static-src/styles/_base.scss#L3

You know anything about this @johngruen ?

**Comment by meandavejustice** [comment]
Assigning to @johngruen so he can verify this is still an issue

**Comment by johngruen** [comment]
@pdehaan i'm not seeing anything in release or nightly. You still see this? If not, go ahead and close this one.

**Comment by ckprice** [comment]
> @pdehaan i'm not seeing anything in release or nightly. You still see this? If not, go ahead and close this one.

Closing this one - I'm also not seeing this. @pdehaan let us know if it should stay open.

**Comment by pdehaan** [comment]
Unable to repro on http://testpilot.dev.mozaws.net/experiments/activity-stream :tada:
