### ISSUE TITLE
Unable to sign in to idea-town site after logging out

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#329]
I foolishly clicked the "logout" button in the `...` menu, and now it doesn't seem like I can log back in.
After completing the FxA login flow, I end up on a page which simply says:
### Server Error (500)

http://idea-town-dev.elasticbeanstalk.com/accounts/login/callback/?state={{state}}&code={{code}}&action=signin

**Comment by meandavejustice** [comment]
Are you on latest master?

**Comment by pdehaan** [comment]
@meandavejustice I'm just using the hosted site on EBS, not anything locally.

<img width="1440" alt="mozilla_firefox" src="https://cloud.githubusercontent.com/assets/557895/11701143/d819df9e-9e9b-11e5-96d9-5ef7185593e4.png">

**Comment by pdehaan** [comment]
Oddly, I installed the 0.2.1 XPI from https://github.com/mozilla/idea-town/blob/master/addon/dist/idea-town-addon-0.2.1.xpi, but when I install it, it reports as v0.2.0 in the about:addons page.

**Comment by meandavejustice** [comment]
sweet thanks @pdehaan

**Comment by lmorchard** [comment]
FWIW, your addon settings are a bit off... Idea Town Hostname should be `idea-town-dev.elasticbeanstalk.com` to match the protocol setting. This is what mine looks like, and I'm not seeing an error on EB dev ![screenshot](https://www.dropbox.com/s/fzq2rbqtkw6rs39/Screenshot%202015-12-10%2010.43.30.png?dl=1)

**Comment by lmorchard** [comment]
That said, keeping this issue open because addon settings _really shouldn't_ result in a server 500 error.

Oh wait, huh, now I _am_ seeing a 500 error. Grr.

**Comment by pdehaan** [comment]
It seems to be back, thanks.

**Comment by lmorchard** [comment]
Looks like there may have also been an FxA issue, which turned into a 500 because templates were missing

https://github.com/mozilla/idea-town/pull/330
