### ISSUE TITLE
Hangy thing in newsletter icon in footer

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3308]
<img width="106" alt="screen shot 2018-01-31 at 14 38 32" src="https://user-images.githubusercontent.com/23885/35648935-a2f9edb4-0694-11e8-88c3-fe4d7e3f66b9.png">

**Comment by SoftVision-PaulOiegas** [comment]
Ahaaa, nice catch. 👍 Made a little bit of testing because I wondered why we haven't caught this and found out that It only occurs on MacOS...

**Comment by chuckharmston** [comment]
"Hangy thing" is the technical term, of course.

**Comment by SoftVision-PaulOiegas** [comment]
Couldn't think otherwise. 🤣

**Comment by SoftVision-PaulOiegas** [comment]
Seems that also Chrome, Opera but not Edge are showing the same issue on Windows. But comparing the browsers, it seems that the icon is displayed squished on Chrome and Opera. Maybe it's the same on Mac OS?
![squished](https://user-images.githubusercontent.com/17258026/35744970-6d2197c0-084a-11e8-89b1-4e087807167d.png)

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed. 👍 Tested on Chrome and Opera on Windows and Firefox, Chrome and Safari on Mac OS.
