### ISSUE TITLE
Investigate what we're storing in the background page

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3313]
Reported by rnewman on slack.  It sounds like we're loading the yaml contents of experiment files.  Let's see if we need to be loading those, and if we can skip graduated experiments altogether.  Report below:

![image](https://user-images.githubusercontent.com/16946141/35701038-9de9be2a-0749-11e8-81ed-797ee7339284.png)

**Comment by meandavejustice** [comment]
This may be fixed with the work removing bootstrap from the addon. I'll self assign and make sure to loop back around to this one
