### ISSUE TITLE
[Featured Experiment] No error message displayed when the attempt to enable Notes fails

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3317]
**[Notes]**
- If a message is added for possible enable error cases, this could be used also for the case from #2564 when attempting to install TxP add-on without internet.
- There could be other cases when the enable process could not take place, and this error message should cover all of them.

**[Affected versions]:**
- Firefox v58.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Disable the computer internet connection.
3. Click the "Enable Notes" green button from "Featured Experiment" area.
3. Observe the green button and "Featured Experiment" section behavior.

**[Expected result]:**
- The button passes from "Enabling..." animation state back into "Enable Notes" and an error is displayed to inform the user about the inability to enable the experiment.

**[Actual result]:**
- No error message is displayed, the button only passes from "Enabling..." animation state back into "Enable Notes" state.

**[Additional Notes]**
- The issue also occurs on stage server.
- Here is a screen recording of the issue: https://goo.gl/gsFF2H.

**Comment by johngruen** [comment]
You can see the featured experiment implementation here:
https://testpilot.stage.mozaws.net/

**Comment by youwenliang** [comment]
Can we do something like this?
![default](https://user-images.githubusercontent.com/8919308/35853852-ad29d27a-0b69-11e8-8602-131aa87224e7.png)
(It'll be a new status bar component for feature experiment section.)

Using the full-width status bar seems a bit off:
![default](https://user-images.githubusercontent.com/8919308/35853969-f7c2fc62-0b69-11e8-8c6f-ce83f5890753.png)

What do you think? @johngruen

**Comment by meandavejustice** [comment]
@youwenliang First one looks good to me

**Comment by SoftVision-PaulOiegas** [comment]
@youwenliang First looks ok to me too, but are we sure about the color? We have the same error in red on the experiment details page. Shouldn't we have consistency on both pages? 
I honestly like yellow better than red. 😃

**Comment by youwenliang** [comment]
@SoftVision-PaulOiegas  Yes good point, we were thinking to make both yellow, so will need to also change the detail page's error status bar. (following the color here: https://design.firefox.com/photon/patterns/warnings.html)

**Comment by johngruen** [comment]
Yeah i like the first one as well

**Comment by johngruen** [comment]
@youwenliang can you just provide some basic measurements?

**Comment by youwenliang** [comment]
![default](https://user-images.githubusercontent.com/8919308/35953034-b195ad48-0cbd-11e8-843c-1092f3b64054.png)

Things I changed based on .status-bar
width: 440px;
height: 32px;
border-radius: 0 0 4px 4px;
margin-bottom: 30px;
background-color: #ffe900 (yellow-50)
border-bottom: 1px solid #d7b600 (yellow-60)
color: #000

**Comment by SoftVision-PaulOiegas** [comment]
The error appears on featured experiment enable fail, but there are 2 things that don't meet the request:
1. The error bar should be narrower based on the design specs provided by @youwenliang (440px vs 500px.
2. The bar wrongly appears aligned to the left same as the left part content of the area, while in the designs is centrally positioned. 

![error message for featured](https://user-images.githubusercontent.com/17258026/38032697-f42933a0-32a6-11e8-9946-4d4839e22cec.png)

**Comment by SoftVision-PaulOiegas** [comment]
Well this is awkward... after testing a bit more, the bar magically moved to the center. Can't explain why, after I reproduced this on 3 profiles on Mac OS and Windows as on the above printscreen.

The only thing remaining is the bar width, but I don't think this is something that needs necessarily rework. There's not such a big difference.
