### ISSUE TITLE
Experiment details page background flickers when "moz://a" logo or the GitHub and Twitter social buttons are hovered (Chrome and Opera)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3320]
**[Affected versions]:**
- Chrome 64.0
- Opera 50.0

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Chrome browser and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Scroll down on the page and click on any experiments (even past experiments).
3. Scroll to the bottom of the experiment details page.
4. While observing page background, hover the "moz://a" logo or the GitHub and Twitter social buttons. 

**[Expected result]:**
- No change occurs to the background, only the buttons gain a hover state where the the white color gets more opaque.

**[Actual result]:**
- The whole page background flickers when hovering the mentioned buttons.

**[Notes]:**
- The issue does not occurs on other tested browsers.
- Here is a recording of the issue: https://goo.gl/Jdxv3n.

**Comment by chuckharmston** [comment]
I can't reproduce this in release Chrome. Is it still an issue?

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston Yep, still reproduces on latest Chrome version. Just a reminder, this only reproduces on [experiment details page](https://testpilot.dev.mozaws.net/experiments/notes). No other page is affected.

**Comment by chuckharmston** [comment]
![2018-03-06 08_02_02](https://user-images.githubusercontent.com/23885/37039432-b35ebb36-2114-11e8-9575-f70d7a566fc1.gif)
Am I missing something? Is it maybe Windows-only?

**Comment by SoftVision-PaulOiegas** [comment]
No, but it seems that retina displays do not show this issue. Just checked Mac OS 10.13 with my old iMac (1080p) and it looks even worse than on Windows. But the issue does not reproduces on the MBP with retina display.

Screen recording: https://goo.gl/Z9LdWL.

**Comment by ghost** [comment]
We've decided not to invest time in fixing this
