### ISSUE TITLE
[Android][Mobile view] The "View Past Experiments" button breaks the UI on French locale

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3321]
**[Affected versions]:**
- Firefox 58.0.1 (mobile)

**[Affected Platforms]:**
- Android 7.0 (Samsung Galaxy S6 with 2K display)

**[Prerequisites]:**
- Latest Firefox browser version was installed on the mobile device.
- French language was selected from "Settings>General>Language" menu.

**[Steps to reproduce]:**
1. Start the Firefox Android app and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down until the "View Past Experiments" button is reached.
3. Observe how the button is rendered in French locale.

**[Expected result]:**
- The button is correctly rendered in French locale and fits the designed area.

**[Actual result]:**
- The button is correctly translated but it exceeds its designed area breaking the UI. 

**[Notes]:**
- This also reproduces on stage server.
- Here is a screenshot of the issue: 
![screenshot_20180205-162957](https://user-images.githubusercontent.com/17258026/35811771-fbef47e6-0a97-11e8-81f4-a8668f5080a4.png)

**Comment by johngruen** [comment]
let's bump the l/r padding down by a few pixels on each side

**Comment by divyabaid16** [comment]
@johngruen PR #3363 have failed two circleci builds. Can you please guide me for this?

**Comment by meandavejustice** [comment]
Hey @divyabaid16 the failures aren't your fault. Some code was merged into master on friday that caused the failures. It should be fixed up today and then your tests should pass. Sorry for the confusion

**Comment by chuckharmston** [comment]
Reviewing now!

**Comment by SoftVision-PaulOiegas** [comment]
Looks ok on my Galaxy S6 using French locale. Marking as verified. 👍 
Thanks for the contribution @divyabaid16!
