### ISSUE TITLE
Bump minimum supported firefox version to 58

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3328]
We support current -1...would be nice if we could do this programmatically, and not have to do a manual bump every time

**Comment by johngruen** [comment]
https://product-details.mozilla.org/1.0/firefox_versions.json

**Comment by chuckharmston** [comment]
We can get it programmatically from https://product-details.mozilla.org/1.0/firefox_versions.json

**Comment by lmorchard** [comment]
FWIW, sometime soon, we'll need to bump our supported min version to reflect WebExtension Experiment usage in new experiments & the main Test Pilot add-on. That stuff is 59+ only - maybe 60+ to be safe considering [bug 1434076](https://bugzilla.mozilla.org/show_bug.cgi?id=1434076). 

Maybe this will be a moot point considering timing of when this stuff will ship, but worth noting that we might not be able to just do this programmatically

**Comment by johngruen** [comment]
No harm in leaving it manual for the time being

**Comment by chuckharmston** [comment]
Nee, 58.
