### ISSUE TITLE
Firefox Voice Fill does not recognise a disabled microphone

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3329]
If I have the microphone disabled / shut off (in software using PulseAudio volume controls / mute button or using a hardware switch), Firefox Voice Fill does not recognise this. Instead of telling me to check my microphone because it did not receive any audio data at all, it tells me "no results found", which is not helpful at all.

**Comment by b4handjr** [comment]
See my comment here: https://github.com/mozilla/testpilot/issues/3331
