### ISSUE TITLE
I want to customize the order of experiments in the list view

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#333]
Right not, the most recently updated experiment goes to the end. Let's not do this.

**Comment by meandavejustice** [comment]
We can do this by sorting our collection on the client by three different properties.
``` json
{
  "id": 1,
  "created": "2015-12-04T01:56:19.275747Z",
  "modified": "2015-12-04T01:56:19.275772Z"
}
```
so either, date added(id acts as this as well) or date modified?

cc/ @lmorchard
