### ISSUE TITLE
Firefox Voice Fill takes me to Google without a way to configure this

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3330]
When I click the Voice Fill button in the icon bar, Firefox will take me to Google Search. However, the default search (in the URL bar) for my browser is set to DuckDuckGo -- I would expect Voice Fill to respect this. Further, [the Voice Fill experiment page](https://testpilot.firefox.com/experiments/voice-fill) allows me to disable the addon and offers "settings", but no way to configure the search engine to go to when clicking the icon.

**Comment by b4handjr** [comment]
See my comment here: https://github.com/mozilla/testpilot/issues/3331
