### ISSUE TITLE
[News Feed] No semitransparent background displayed when news are hovered or clicked

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3337]
**[Affected versions]:**
- Firefox 58.0.1 and above

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on the top right "News Feed" button.
3. After redirected, hover any news and observe its behavior.
4. Click and hold the article while observing its behavior.

**[Expected result]:**
- Step 3: The hovered article gains a white semitransparent background and a thin white border.
- Step 4: The clicked article white semitransparent background and border gain a bit more more opacity.

**[Actual result]:**
- Step 3: The hovered article gains a thin white border but no semitransparent white background.
- Step 4: The clicked article white border gains a bit more more opacity but still no white semitransparent background.

**[Notes]:**
- This issue reproduces on all servers and it is a deviation from [design](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment_photonized/#artboard8).

![no white semitransparent background on hover](https://user-images.githubusercontent.com/17258026/36024540-b3f60e4e-0d98-11e8-9f90-20fe7e88ea58.png)

**Comment by SoftVision-PaulOiegas** [comment]
Played a bit with the Web Console Inspector rules since I needed some screenshots for our test cases. Probably it will look like this:
### Hovered ###
![news feed article hovered](https://user-images.githubusercontent.com/17258026/36212273-2c32ea96-11ac-11e8-8bc7-a144dff1cce8.png)

With 5% white background opacity and 20% white border opacity

### Pressed ###
![news feed article clicked](https://user-images.githubusercontent.com/17258026/36212316-49ee8162-11ac-11e8-9017-f5a4a3f7c5f9.png)

With 8% white background opacity and 40% white border opacity.

Not really like in designs since we haven't implemented it in the same way exactly.

**Comment by divyabaid16** [comment]
Please review the PR.

**Comment by SoftVision-PaulOiegas** [comment]
Good fix and thanks for your contribution! 👍 
Verified on Windows 10, Mac OS 10.13 and Ubuntu 14.04.
