### ISSUE TITLE
[News Feed] The news date is wrongly displayed separately when article title is displayed on two rows

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3338]
**[Affected versions]:**
- Firefox 58.0.1 and above

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on the top right "News Feed" button.
3. Search for a long news name and reduce the size of the browser while observing the date of it.

**[Expected result]:**
- The news date is always displayed at the end of the news title no matter how long it is or how small is the browser window.

**[Actual result]:**
- The news date is wrongly separated from long titles when the browser window is reduced and the title ends displayed on two rows.

**[Notes]:**
- This issue will occur even on maximized browser window if a future news title will be long enough to be displayed on two rows.

![date separated when title is too long 2](https://user-images.githubusercontent.com/17258026/36029519-2f85e198-0dac-11e8-832b-be05f1d92c88.png)
 
- This issue reproduces on all servers.
- This issue can be easily encountered if the Notes sidebar is opened and browser is placed on half the screen.

![date separated when title is too long](https://user-images.githubusercontent.com/17258026/36029526-34732364-0dac-11e8-87c4-d09088aa98fe.png)

**Comment by ghost** [comment]
closing in favor of #3512
