### ISSUE TITLE
[News Feed] The blue line uniting the news dots disappears in mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3339]
**[Affected versions]:**
- Firefox 58.0.1 and above

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on the top right "News Feed" button.
3. Reduce the size of the browser while observing the line that connects the news dots on left side. 

**[Expected result]:**
- The line that unites the news dots is always displayed no matter how small is the browser window size.

**[Actual result]:**
- The line that unites the news dots disappears even when the browser window has a decent size and elements can be easily read. 

**[Notes]:**
- The issue also occurs on mobile devices even on landscape mode. 
- This issue reproduces on all servers.
![missing dots line in mobile view](https://user-images.githubusercontent.com/17258026/36030039-54125526-0dae-11e8-9e48-3bd8cc3e8a5f.png)

**Comment by meandavejustice** [comment]
Marking this as `good-first-issue` as it's probably just simple css tweak in [/frontend/src/app/containers/NewsFeedPage/index.scss](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/NewsFeedPage/index.scss?utf8=%E2%9C%93)

[Responsive design mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) will be helpful in finding the fix here.

**Comment by divyabaid16** [comment]
I would like to work on this issue.

**Comment by meandavejustice** [comment]
Go for it @divyabaid16 , ping me if you have any issues

**Comment by divyabaid16** [comment]
The blue line was not present in the mobile view or when the screen size was small. So I added them. Kindly review the PR.

**Comment by SoftVision-PaulOiegas** [comment]
Uuu, nice fix @divyabaid16. Good Job and thanks for your contribution! 👍 
Verified on Windows 10 and Mac OS 10.13 and it's correctly working.
