### ISSUE TITLE
Footer links are wrongly overlapping on languages with long words, when resizing the browser window

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3340]
**[Affected versions]:**
- Firefox 58.0.1 and above

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- A supported browser content language with longer words (ex: German or French) was added as main option. 

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down to the footer links in the bottom of the page.
3. Reduce the horizontal size of the browser window while observing the footer behavior.

**[Expected result]:**
- When the window is to narrow to display the footer links on a single row, all the links are moved vertically one under the other.

**[Actual result]:**
- There is a large portion between the display of one line links and vertical links where they are wrongly overlapping on languages with long words.

**[Notes]:**
- This issue reproduces on all website pages and on all servers.
![news feed footer broken](https://user-images.githubusercontent.com/17258026/36031158-7321e478-0db2-11e8-8e14-348b125dbbe6.png)

**Comment by Paarmita** [comment]
@chuckharmston This issue is no longer there. Is it still open?
![screenshot from 2018-03-06 15-10-39](https://user-images.githubusercontent.com/26546816/37025053-aea51734-2150-11e8-85e9-a9c04c46c0a5.png)
![screenshot from 2018-03-06 15-10-13](https://user-images.githubusercontent.com/26546816/37025054-aed93906-2150-11e8-8027-043671ec6a34.png)

**Comment by chuckharmston** [comment]
@Paarmita yes, if you change your browser's language settings to German, it does still reproduce.

**Comment by ghost** [comment]
closing in favor of #3225
