### ISSUE TITLE
[News Feed] Footer links are wrongly displayed on center instead of left in mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3341]
**[Affected versions]:**
- Firefox 58.0.1 and above

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click on the top right "News Feed" button.
3. Reduce the size of the browser window until mobile view is reached.
4. Scroll down to the footer links and observe their position.

**[Expected result]:**
- When the window is to narrow to display the footer links on a single row, all the links are moved vertically one under the other.

**[Actual result]:**
- The footer links are wrongly displayed on the center of the page.

**[Notes]:**
- This issue reproduces on all servers.

![news feed footer](https://user-images.githubusercontent.com/17258026/36031318-fd3ad372-0db2-11e8-8e9b-ee2361b8be73.png)

**Comment by meandavejustice** [comment]
These may actually look better and be easier to click when in the center.

They aren't shown in the mockups [here](https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Featured_experiment/#artboard9). maybe we can do some digging to see what was in the designs for experiments page

**Comment by johngruen** [comment]
Let's do everything on the left

**Comment by SoftVision-PaulOiegas** [comment]
Fixed 👍 Tested on Windows and Mac OS with multiple browsers and also on Firefox for Android (latest release).
Thanks for the contribution @divyabaid16!
