### ISSUE TITLE
News feed is hard-coded in template

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#3345]
https://github.com/mozilla/testpilot/blob/8bbf2fc1b0253ead275fb01a76afca802fcb4c2e/frontend/src/app/components/Header/index.js#L145

**Comment by lmorchard** [comment]
Looks like this string is wrapped in `<Localized id="headerLinkNews">` on the line before. But, `headerLinkNews` doesn't appear in [`locales/en-US/app.ftl`](https://github.com/mozilla/testpilot/blob/master/locales/en-US/app.ftl)

**Comment by flodolo** [comment]
> Looks like this string is wrapped in <Localized id="headerLinkNews"> on the line before. But, headerLinkNews doesn't appear in locales/en-US/app.ftl

Uhm, right. How come tests didn't fail?

**Comment by lmorchard** [comment]
> Uhm, right. How come tests didn't fail?

There's no way currently to test strings in app.ftl, because they're manually extracted. The place where we have tests is for experiments.ftl, because we can auto-extract strings and detect when some are missing.

**Comment by flodolo** [comment]
> The place where we have tests is for experiments.ftl, because we can auto-extract strings and detect when some are missing.

Ah, I completely missed that it was only for one part.
