### ISSUE TITLE
[News Feed] A dotted line selector is wrongly displayed around clicked news article on Linux

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3365]
**[Affected versions]:**
- Firefox 58.0.2 and above

**[Affected Platforms]:**
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser on a Linux machine with the profile from prerequisite.
2. Navigate to https://testpilot.dev.mozaws.net page and click the "News Feed" button from top right side of the page.
3. Right click one of the displayed news articles and observe the page behavior.

**[Expected result]:**
- The news article gains a hovered overlay and the browser context menu opens.

**[Actual result]:**
- The news article gains a hovered overlay and the browser context menu opens, but the entire post is also surrounded by a dotted line.

**[Notes]:**
- This issue does not reproduce son Windows or MacOS.
- Here is a screenshot of the issue:

![news feed selector](https://user-images.githubusercontent.com/17258026/36378653-497a5c16-1584-11e8-9baf-f7a30451e07e.png)

**Comment by Paarmita** [comment]
@marniepw 
![screenshot from 2018-03-05 20-06-28](https://user-images.githubusercontent.com/26546816/36980766-48d861c6-20b1-11e8-86ca-05573c4e01ce.png)
On linux Firefox 58.0.2 version the link doesn't show the site

**Comment by chuckharmston** [comment]
@Paarmita that's expected. You'll need to follow the `our documentation` link on that page to finish setting up the development environment.

**Comment by Paarmita** [comment]
@chuckharmston Okay, so can i take up this issue?

**Comment by Paarmita** [comment]
@chuckharmston okay, I will setup it locally.

**Comment by Paarmita** [comment]
@chuckharmston this issue is no longer there now.

**Comment by chuckharmston** [comment]
@SoftVision-PaulOiegas would you mind checking that?

**Comment by SoftVision-PaulOiegas** [comment]
Still reproducible on my Ubuntu 16.04 using latest Nightly and Latest Beta (59).
Here is a recording: https://goo.gl/Ayiwdt.

**Comment by SoftVision-PaulOiegas** [comment]
The News Feed page was entirely removed.
