### ISSUE TITLE
"More experiments" button position at small screen sizes

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3367]
<img width="383" alt="screen shot 2018-02-20 at 09 58 49" src="https://user-images.githubusercontent.com/23885/36437666-d87ae9a8-1624-11e8-8aa4-d1fda66d201d.png">

<img width="806" alt="screen shot 2018-02-20 at 10 00 21" src="https://user-images.githubusercontent.com/23885/36437689-ec8b872c-1624-11e8-977b-310fcae6aa89.png">

The position and opacity here are pretty awkward. Is this as UX intended? CC @ChenMorpheus

**Comment by lmorchard** [comment]
I think this [was by design](https://github.com/mozilla/testpilot/pull/3359#issuecomment-366437650), yeah /cc @johngruen

**Comment by johngruen** [comment]
Yeah, it was intended as an improvement over just having it in the middle where the two buttons sat on top of each other. I think it could stand a polish pass.

**Comment by ghost** [comment]
closing in favor of #3397
