### ISSUE TITLE
Dev is failing

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3368]
Dev is just showing a bluescreen right now with the following:

![screen shot 2018-02-20 at 2 21 54 pm](https://user-images.githubusercontent.com/3323249/36447428-04a63a3a-164a-11e8-9be8-d200dbbaa6be.png)

**Comment by lmorchard** [comment]
This looks like our usual intermittent issue with failed deployments on dev.

Usually fixed with [a rebuild on circleci](https://circleci.com/gh/mozilla/workflows/testpilot/tree/master). Just started one, let's see if that fixes it
