### ISSUE TITLE
[Featured Experiments] Loading indicator and onboarding not displayed

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3371]
### STR

1. Make sure test pilot is uninstalled
2. click the `install test pilot and enable notes` button

### Results
Test Pilot and notes install but there is no barberpoll on the installing notes button and the experiment onboarding tour does not appear.

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen Maybe when we fix this, we should also treat the case when the featured experiment is already enabled but Test Pilot is not installed/disabled? The button should display only "Install the Test Pilot Add-on" string in that case.
The fix would also apply for the #2378 issue on "Experiment details" page. 

However, I've noticed and logged another issue (#3374), where the "Enabled" label is no longer displayed now when the TxP uninstall flow works as it should. And it is displayed when it fails to redirect you to "/retire" page.
