### ISSUE TITLE
"More Experiments" string is not localized in the supported languages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3373]
**[Affected versions]:**
- Firefox 58.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- A supported language different than English US [en-us] was added as top option for page content from Options>Language and Appearance section (eg. German [de]).

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Vertically resize the browser until the "Try all of our experiments" section is not visible.
3. Observe the "More Experiments" button.

**[Expected result]:**
- The "More Experiments" string is localized in the selected language. 

**[Actual result]:**
- The "More Experiments" string is not localized in the selected language. 

**[Notes]**
- Here is a screen recording of the issue:
![more experiments](https://user-images.githubusercontent.com/19226534/36479741-6a5ec6a8-1712-11e8-995c-7ff6c9ab3efc.gif)

**Comment by meandavejustice** [comment]
Somehow this just didn't get localized, we have it in app.ftl and it looks correct in the views.

```
meandave@LAPTOP-NA0Q0G86:/mnt/c/Users/Dave Justice/Code/testpilot$ git grep -i "landingMoreExperimentsButton"
frontend/src/app/containers/HomePage/HomePageNoAddon.js:              <Localized id="landingMoreExperimentsButton">
frontend/src/app/containers/HomePage/HomePageWithAddon.js:            <Localized id="landingMoreExperimentsButton">
locales/en-US/app.ftl:landingMoreExperimentsButton = More Experiments
```

@flodolo what would the best way forward for this be? Should I just update the id in app.ftl?

**Comment by flodolo** [comment]
Can someone explain how am I supposed to see that text? I'm trying stage in English, and I don't see anything like that.

The en-US file has that string, but it was never exposed in Pontoon.

@mathjazz 
Any clue what happened. Can you force a re-sync for en-US?

**Comment by mathjazz** [comment]
I see multiple strings aren't imported into Pontoon.

Investigating...

**Comment by flodolo** [comment]
@meandavejustice 
Localization was moved to the l10n branch, it looks like it hasn't been updated in a long time?
https://github.com/mozilla/testpilot/tree/l10n/locales/en-US

**Comment by mathjazz** [comment]
@flodolo @meandavejustice Pontoon is configured to use the [l10n](https://github.com/mozilla/testpilot/blob/l10n/locales/en-US/app.ftl) branch for Test Pilot.

**Comment by lmorchard** [comment]
Yeah, if we have strings to get localized, our process has roughly been:

1. finalize the strings on master, consider them "frozen"
1. merge master into l10n (FWIW, this is what the bi-weekly "TXP String Merge" event in the Test Pilot calendar is meant to remind us to do)
1. wait a week at least (if not two) for Pontoon commits to roll into l10n
1. merge l10n back into master (usually coinciding with end-of-sprint deployment)

If l10n branch hasn't been updated, then we don't get localizations.

**Comment by SoftVision-PaulOiegas** [comment]
> Can someone explain how am I supposed to see that text? I'm trying stage in English, and I don't see anything like that.

@flodolo to answer your question. Just resize the browser window until you cannot see the "Pick your experiments!" section on the Homepage.

![image](https://user-images.githubusercontent.com/17258026/38555904-882d73b2-3cd0-11e8-8c7e-0caf97a3b7dd.png)

When the issue was logged, we had the "Featured Experiment" area displayed. But there isn't any featured experiment right now. You can make that section appear if you change locally the `is_featured` attribute to `true` in `notes.yaml` file for example.

**Comment by meandavejustice** [comment]
![mas-exp](https://user-images.githubusercontent.com/1844554/39836059-b571c3c0-53c1-11e8-8bec-99de0e3c8662.png)
string has been translated

**Comment by SoftVision-PaulOiegas** [comment]
@flodolo Am I the only one who thinks the French translation is wrong for this button? Could be other languages too.
"Davantage d'expériences" 

I'm not a native French speaker, did some years in school only. But I think there is a clear difference between experiment and experience even in French. 🤔

**Comment by flodolo** [comment]
Can you provide a screenshot of French? I don't see one in the discussion (also cc @TheoChevalier)

**Comment by SoftVision-PaulOiegas** [comment]
Sure, here it is. This one is from my Android device, but you can simulate it in the browser by reducing the vertical size of the window while on Test Pilot website, until it appears.

![screenshot_20180511-181659](https://user-images.githubusercontent.com/17258026/39932081-d8ef2e5a-5547-11e8-8b21-30430372b9ec.png)

**Comment by TheoChevalier** [comment]
Expérience can have several meanings, but this example may help to understand how it’s used here https://www.linguee.com/french-english/translation/mener+une+exp%C3%A9rience+scientifique.html (conduct a science experiment)

**Comment by SoftVision-PaulOiegas** [comment]
Hi @TheoChevalier I was aware that, "expérience" word can be used also in "experiment" case. I just felt that in this case was not so fit.
Anyway, you are the expert. I don't think there's a point in arguing about this, since it's such a small thing. Thanks for clarifying! 😃
