### ISSUE TITLE
Newsletter privacy checkbox wrongly gains a red border when unchecked

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3376]
**[Affected versions]:**
- Firefox Nightly 60.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Steps to reproduce]:**
1. Start Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down to the "Newsletter" section and click the textbox.
3. Enter at least 1 character in the text box.
4. Observe the displayed Privacy checkbox color.
5. Check and uncheck the checkbox and after click outside of it.
6. Observe again the checkbox color.

**[Expected result]:**
- The unchecked checkbox returns to the initial white + gray border look.

**[Actual result]:**
- The unchecked checkbox returns to a white + red border like there is an error.

**[Notes]:**
- This only happens if you click outside of the box after unchecking it.
- This issue also happens on the Newsletter modal displayed after installing TxP add-on.
- Here is a screen recording of the issue: https://goo.gl/Pq3EpW.

**Comment by chuckharmston** [comment]
We need to set [`:invalid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) rules for this.

**Comment by Paarmita** [comment]
@chuckharmston Can I work on this issue?

**Comment by SoftVision-PaulOiegas** [comment]
@Paarmita if you think you got the needed skills required, go for it! 👍

**Comment by ghost** [comment]
Hi @chuckharmston @SoftVision-PaulOiegas from dev tools, I couldn't find out which property is causing the white + red border. Disabling that would help here maybe?

Also, I set `outline` property in a `:invalid` rule. But I couldn't land on expected result with that. Could you please tell me which property has to be set in `:invalid` rule for expected result?

**Comment by piyushmittal25** [comment]
Can i take care of this issue?:)

**Comment by ghost** [comment]
@piyushmittal25 please go ahead.

**Comment by meandavejustice** [comment]
After reading over this one again, I vote we close as `wontfix`

**Comment by SoftVision-PaulOiegas** [comment]
Fixed! 👍 Tested on Windows 10, Mac OS 10.13.4, Android 7.0 and iOS 11.0.1.
