### ISSUE TITLE
"Your email here" hint message is no longer displayed in the newsletter sign up textbox

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3377]
**[Affected versions]:**
- Firefox Nightly 60.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Steps to reproduce]:**
1. Start Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down to the "Newsletter" section.
3. Observe the textbox displayed in the section.

**[Expected result]:**
- The textbox is correctly displayed and has white color with round corners and "Your email here" hint message in gray characters inside it.

**[Actual result]:**
- The textbox is white with round corners but the hint message is no longer displayed inside it.

**[Notes]:**
- This issue also happens on the Newsletter modal displayed after installing TxP add-on.
- Here is a screenshot of the issue:

![no hint in newsletter](https://user-images.githubusercontent.com/17258026/36484007-897d1414-1720-11e8-9270-72dab4f456fa.png)

**Comment by chuckharmston** [comment]
Let's make sure the placeholder text is there.

**Comment by ghost** [comment]
Hello @chuckharmston I would like to work on this issue

**Comment by chuckharmston** [comment]
Excellent, @csd713! It should have the HTML `placeholder` attribute with the localized string `newsletterFormEmailPlaceholder`. Let me know if you have any troubles.

**Comment by ghost** [comment]
Hi @chuckharmston thank you. I figured out the place to make changes for this issue.
However, I have a question regarding localization of string.
https://github.com/mozilla/testpilot/blob/ffd98fecb54fd2f562128966fe04f95da909fe7b/locales/en-US/app.ftl#L195
Is `newsletterFormEmailPlaceholder` variable combined with `.placeholder` or do we have a wrong variable `.placeholder` on next line in that file?
Please let me know if I'm missing something.

**Comment by chuckharmston** [comment]
That's how `fluent-react` localizes HTML attributes.

More about the FTL syntax here: http://projectfluent.org/fluent/guide/attributes.html

And you can see an example just like this one here: https://github.com/projectfluent/fluent.js/wiki/Localized

**Comment by ghost** [comment]
@chuckharmston This is what I wanted. Thank you.

**Comment by SoftVision-PaulOiegas** [comment]
This seems to be fixed on the dev server. However, the fix introduced another issue, but that's tracked separately in #3428.
Closing this, as the hint message was re-added.
