### ISSUE TITLE
[Android] [Newsletter] The "Privacy" checkbox wrongly gains the text selection pointers each time it is tapped

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3379]
**[Affected versions]:**
- Firefox 58.0.2 or above

**[Affected Platforms]:**
- Android 7.0

**[Steps to reproduce]:**
1. Start Firefox mobile browser and navigate to https://testpilot.dev.mozaws.net page.
2. Swipe down until the Newsletter section is reached.
3. Tap on the email text box and enter at least 1 character.
4. Tap outside on empty area to close the keyboard and lose the field focus.
5. Tap on the "Privacy" checkbox.
6. Tap outside on the empty space and tap the checkbox again to uncheck.

**[Expected result]:**
- The "Privacy" checkbox is correctly checked and unchecked each time it is tapped. 

**[Actual result]:**
- The "Privacy" checkbox wrongly gains the text selection pointers each time it is tapped.

**[Notes]:**
- Here is a screenshot of the issue:

![android checkbox sellected](https://user-images.githubusercontent.com/17258026/36489724-6013ada4-172f-11e8-9faa-5af96a3db7cb.png)

**Comment by divyabaid16** [comment]
I was searching through the files but I couldn't locate the exact place where the code should be modified. Can you please tell me that where is the file located, which is required to be modified?

**Comment by SoftVision-PaulOiegas** [comment]
@fzzzy @meandavejustice some help for our contributor? 😃 
As QA I could only guess that might be somewhere around `frontend/src/app/components/Newsletter`.

**Comment by divyabaid16** [comment]
@SoftVision-PaulOiegas , please review.

**Comment by SoftVision-PaulOiegas** [comment]
As I've said, I'm only doing QA on Test Pilot. But probably one of the developers involved will help you with a review, as soon as they wake up and start working.
Thanks for the contribution!

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be working just fine. 👍 Great work, thanks again for the contribution @divyabaid16 !
