### ISSUE TITLE
Buttons should be able to expand and wrap.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3380]
Our current buttons break poorly when the text overflows its size. In #3321 we fixed one instance of this, but there are more:

<img width="1100" alt="screen shot 2018-02-21 at 08 47 22" src="https://user-images.githubusercontent.com/23885/36497538-d2debd4c-16f8-11e8-948d-c00e1e30ab82.png">

Rather than hunt out those instances and fix each individually, we should allow buttons to expand in size and wrap in the places where they can't.

**Comment by meandavejustice** [comment]
![button-expand](https://user-images.githubusercontent.com/1844554/40023920-1a5201b2-57bc-11e8-88a3-5aee8b4752c2.png)
buttons are looking better since @dannycoates made the mobile changes

**Comment by meandavejustice** [comment]
Still looks bad on front page with much longer text 
![bad-wrap](https://user-images.githubusercontent.com/1844554/40023985-56cbaf62-57bc-11e8-9a8d-417b151d1800.png)
