### ISSUE TITLE
scripts and stylesheets are 404-ing on dev

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3381]
![screen shot 2018-02-21 at 1 03 23 pm](https://user-images.githubusercontent.com/3323249/36499689-afb46e3e-1707-11e8-9023-084465e506e3.png)

**Comment by lmorchard** [comment]
[Tried a rebuild on circleci](https://circleci.com/gh/mozilla/workflows/testpilot/tree/master)? Looks like the deployment failure issue again. Basically whenever there's 404/403 errors, that's the most likely culprit

**Comment by lmorchard** [comment]
Looks like a rebuild fixed it
