### ISSUE TITLE
The "Done" button from the experiment tour is not localized in the supported languages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3385]
**[Affected versions]:**
- Firefox 58.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- A supported language different than English US [en-us] was added as top option for page content from Options>Language and Appearance section (eg. German [de]).

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Navigate to any of the available experiments cards.
3. Click the "Launch Tour" button from the experiment details page.
4. Click the right arrow until reaching the last slide.
5. Observe the "Done" button.

**[Expected result]:**
- The "Done" string is localized in the selected language. 

**[Actual result]:**
- The "Done" string is not localized in the selected language. 

**[Notes]**
- This issue is also reproducible on stage and production servers.
- Here is a screen recording of the issue:
![done button](https://user-images.githubusercontent.com/19226534/36600034-d5a270f6-18b9-11e8-98da-806eba3b40d8.gif)

**Comment by johngruen** [comment]
We should just use the same check we use in screenshots here. No way the string will fit across all locales

**Comment by chuckharmston** [comment]
@johngruen what check are you talking about?

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston If I got it right form the meeting where this was discussed, he was referring to something like a checkmark "✔️" that is also implemented on Screenshots tour.

This one to be more specific:

![img_06032018_175859_0](https://user-images.githubusercontent.com/17258026/37042966-2f9c1600-2168-11e8-80b5-ebb3f72418fa.png)

**Comment by chuckharmston** [comment]
Aha! I thought he meant "check" as in "an attempt to look for something".

**Comment by ghost** [comment]
Hi I would like to work on this.
what is the recommended material icon for this?

I came across this one. https://material.io/icons/#ic_done

**Comment by chuckharmston** [comment]
Hi @csd713,

This is the icon referenced above: https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/icons/done.svg

You'll want to change the fill to use a color that better fits Test Pilot. I would suspect #30e60b to be the correct value here, but perhaps @johngruen or @sevaan could confirm that.

**Comment by sevaan** [comment]
Yep! #30e60b is the correct colour to use.

**Comment by ghost** [comment]
Hello @chuckharmston @SoftVision-CosminMuntean @SoftVision-PaulOiegas 

I found that there is one 'done' icon(white color) present already.

https://github.com/mozilla/testpilot/blob/master/frontend/src/images/done.svg

Can someone confirm that I can edit color of this  image for this fix?

**Comment by ghost** [comment]
I used the icon suggested by @chuckharmston and changed the fill to #30e60b.
Created a PR for this. Please review it.

**Comment by dannycoates** [comment]
done in #3446

**Comment by SoftVision-PaulOiegas** [comment]
Other than the fact that the check mark looks a bit too big in comparison with the navigation arrows, this looks ok.

@johngruen Do we care about this? It's more sleek on Screenshots to be honest.

![check tour](https://user-images.githubusercontent.com/17258026/38027441-577c0d74-3298-11e8-8597-3c390d9d8beb.png)

**Comment by sevaan** [comment]
We should make it the same size as the back arrow. I believe the width is 40px.

@dannycoates @csd713

**Comment by johngruen** [comment]
It looks like the width of the element is 40px but the svg is actually only 20 px

**Comment by dannycoates** [comment]
<img width="751" alt="screen shot 2018-03-28 at 11 15 35 am" src="https://user-images.githubusercontent.com/87619/38048126-6a67a6c4-3279-11e8-808a-79fbba713711.png">

db8a4b475221fd6e17e2cfa8fb0bf0ca18185b5a

**Comment by SoftVision-PaulOiegas** [comment]
Now we're talking. 👍 Looks great!
