### ISSUE TITLE
Consider a staging deployment to the production environment

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3393]
By deploying to, for example, `testpilot.firefox.com/staging`, we could do some last-minute testing on the production hostname before performing a full production deployment.

Lots of potential issues here, but logging the idea for discussion anyway.

**Comment by lmorchard** [comment]
I think one of the main issues, unfortunately, would be that the site has a pretty well-ingrained assumption on everything living at the root path of the domain. That could be changed with some elbow grease, though

**Comment by chuckharmston** [comment]
@fzzzy @lmorchard @meandavejustice @dannycoates Any other thoughts here?

**Comment by dannycoates** [comment]
What does the prod domain offer / enable that stage doesn't? I'd prefer to bring stage up to parity with prod (if we can) before going this route.

-- forgive me, I haven't been in this code for a while

**Comment by chuckharmston** [comment]
It's specifically the browser's restrictions around `mozAddonManager` that are problematic; [all of this](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md#for-linux--os-x-hosts) is required, which brings stage and prod out of parity in terms of simple testing. This caused a deployment issue a few sprints ago.
