### ISSUE TITLE
Welcome + Newsletter sign up modal is not displayed after installing TxP from bottom page button (normal flow)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3395]
**[Affected versions]:**
- Firefox Nightly 60.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down the page until the "Install the Test Pilot Add-on" button is reached.
3. Click the button and after install is performed, dismiss the displayed doorhanger.
4. Observe the page behavior.

**[Expected result]:**
- You are redirected to the "Experiments" page where the page is covered by a black semitransparent overlay and the Welcome + Newsletter sign up dialog is displayed.

**[Actual result]:**
- You are redirected to the "Experiments" page, but no modal is displayed.

**[Notes]:**
- The Welcome + Newsletter modal is only displayed if you refresh the page or when you reach /experiments page next time.
- here is a screen recording of the issue: https://goo.gl/j1Y3A8.

**Comment by dannycoates** [comment]
#3458 fixes this

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed. 👍 Can't confirm if something is wrong when there is a featured experiment since I cannot test locally. The building issues are stopping me.
