### ISSUE TITLE
Multiple "Sending message that cannot be cloned..." warnings are displayed in browser console while any of the Test Pilot pages is opened

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3396]
**[Notes]:**
- This issue is only reproducible if Test Pilot add-on is installed.

**[Affected versions]:**
- Firefox 58.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have the Test Pilot add-on installed on a new Firefox profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to "https://testpilot.firefox.com" page.
2. Open the browser console (Ctrl+Shift+J/Cmd+Shift+J).
3. Observe the browser console errors

**[Expected result]:**
- No warnings or errors are displayed in browser console.

**[Actual result]:**
- Multiple "Sending message that cannot be cloned. Are you trying to send an XPCOM object?" warning are displayed in browser console.

**[Additional Notes]**
- This issue is also reproducible on Test Pilot dev and stage servers.
- Here is a screen recording of the issue:
![multiple warnings](https://user-images.githubusercontent.com/19226534/36904396-46250ef4-1e39-11e8-9661-7171e43cecac.gif)

**Comment by chuckharmston** [comment]
@aswan any thoughts here? This strikes me as likely being an issue on the Gecko side, but it doesn't appear to be causing any bugs here.

**Comment by aswan** [comment]
This is a Firefox issue.  @SoftVision-CosminMuntean you list 58.0.2 and above as affected, does that mean this didn't occur in earlier versions?  Or is that just what's been tested?  (no need to test older versions if you haven't done so, I'm just trying to figure out if this was a recent regression or not)

**Comment by SoftVision-CosminMuntean** [comment]
I haven't test this issue on Firefox versions lower than 58 when I have logged it due to time constrains. I've found a bit of time today to test with older Firefox versions too. It seems that the issue is also reproducible on older versions, but I was forced to stop at Firefox 49.0 since Test Pilot website is not available for versions lower than it.

Also, in the current implementations of Test Pilot, the minimum supported version is Firefox 54 (planned to be raised to 57). In order to test the issue on versions older then 54, I had to open the browser with a profile where Test Pilot was already installed. Unfortunately this method doesn't work for versions older than 49.
We even tried to alter the limitations locally to to bypass them, but we were unsuccessful.

However, I don't remember seeing these errors in browser console in the past. So this is either a Test Pilot issue that occurs due to a more recent change or it's a combination between a Test Pilot change and a browser change. Cannot tell due to limitations. 
@aswan, let me know if you need more information.

**Comment by aswan** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1445130, I think this issue can probably be closed.

**Comment by fzzzy** [comment]
Thanks @aswan. We'll track it there.
