### ISSUE TITLE
The scroll hint postion is too close to the bottom

### ISSUE THREAD

**Issue by Pekochen** [mozilla/testpilot#3397]
<img width="1305" alt="screen shot 2018-03-05 at 10 20 17" src="https://user-images.githubusercontent.com/8252151/36954886-de9ea956-205f-11e8-8e3a-a16532b8952a.png">
More experiment is too close to the buttom.Please have a look.
Thanks

**Comment by dannycoates** [comment]
@johngruen What if we always have it to the side? Then it doesn't overlap anything.

<img width="814" alt="screen shot 2018-04-18 at 11 57 18 am" src="https://user-images.githubusercontent.com/87619/38952284-e97b7f8a-42ff-11e8-8411-52378196dfe4.png">
