### ISSUE TITLE
Move back to react-router.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3405]
We removed `react-router` due to problems in our localization process that have since been resolved. At this point in time, I think it makes sense to restore it for a few reasons:

1. Being a single-page app will be a much better and smoother UX.
1. It's a de facto library, and will make it easier for contributors familiar with React to help us.
1. We store a bunch of state that we asynchronously retrieve from the browser on page load. When that state is used to vary UI, it feels janky. On react-router we only have to do that once for the initial  load.

For bonus points: whenever collected, store the pieces of state referenced in point 3 in localstorage, then attempt to rehydrate that on page load. That will help us render without jank even faster, and we can update asynchronously if things change.

@fzzzy has a partial branch to do this. Could you post that, Donovan?

**Comment by fzzzy** [comment]
https://github.com/mozilla/testpilot/compare/master...fzzzy:use-react-router-4?expand=1

The pages render now, but routing doesn't seem to be happening properly. Investigating.

**Comment by chuckharmston** [comment]
Note that we can go back to asynchronously tracking navigation events, which we stopped doing in #3232.

**Comment by dannycoates** [comment]
done in #3416
