### ISSUE TITLE
It is a snapshot of the page as it appeared on 7 Mar 2018 09:32:30 GMT. 

### ISSUE THREAD

**Issue by welljahinge** [mozilla/testpilot#3413]

**Comment by welljahinge** [comment]
It is a snapshot of the page as it appeared on 7 Mar 2018 09:32:30 GMT.

**Comment by SoftVision-PaulOiegas** [comment]
Hello @welljahinge and thanks for your report. However, I cannot understand what your issue is about. Can you please give us more details regarding your issue? 
Also, I'm not able to see any snapshot image in your report.

**Comment by SoftVision-PaulOiegas** [comment]
Closing this since nothing is actionable here. Please reopen if you provide more details.
