### ISSUE TITLE
[Graduation] Cliqz experiment wrongly appears to be graduated on March 6th on both dev and stage servers

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3421]
**[Affected versions]:**
- Firefox Beta 60.x and above 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the Voice Fill, Snooze Tabs and Min Vid graduation dates on their details page.
3. Replace the current experiment name from address bar with "cliqz" and hit "Enter" key.
4. Observe Cliqz graduation date. 

**[Expected result]:**
- Cliqz planned graduation date is 03/27/2018, the same as the other 3 experiments.

**[Actual result]:**
- Cliqz experiment is wrongly displayed as graduated since 03/06/2018.

**[Notes]:**
- This issue occurs on both dev and stage servers.
- Screen recording: https://goo.gl/5WeyFp.

**Comment by marniepw** [comment]
@johngruen

**Comment by ghost** [comment]
#3423 fixed this.  I made a new tag and put on stage.  The bot says it's building.  Presumably it will be deployed by the time you read this. :)  Thanks for catching this!
