### ISSUE TITLE
[Enhancement] Modify the Featured Experiment section to display a random experiment / a carousel of new launched experiments

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3422]
This is a proposal that I had in mind for some time now. I've suspected that Notes won't remain forever as featured experiment and it will probably be replaced by newly launched ones. 
I was thinking at taking the Featured Experiment section to next level and either display randomly one of the new experiments launched, either display them as a carousel, so the user could navigate between them.

What do you guys think?

**Comment by chuckharmston** [comment]
Great idea, but we're actively avoiding adding new features to Test Pilot.

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston @johngruen I'm aware of that, but right now the "Featured Experiment" area is unused since Notes is no longer featured. So probably the new ones will be featured next, otherwise it was a waste of time to implement it. 
However, right now you can only feature one of them, which in my opinion will unbalance the chances of success for the other new experiments (it will probably be a batch). That's why I was proposing a method to make them all visible for the end user.

Maybe doing something like random feature won't take to much to implement? You know, like having more featured experiments, one of them displayed at each page navigation and changing it at each page refresh? Simple "automation" instead of manually doing this each time you want another featured. 

Anyway, it's your call guys, just trying to help make this platform even more awesome that it is. 😃
