### ISSUE TITLE
Page scrolls up when a key is pressed in newsletter form input

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3428]
![ezgif-3-d9af309c10](https://user-images.githubusercontent.com/22018999/37549072-2fbfb770-2953-11e8-88a0-eb09f900a12c.gif)

**Comment by SoftVision-PaulOiegas** [comment]
I thought first this is an enhancement. Forgot my coffee at home today. 😆 
This seems to have been started occurring after you landed the fix for #3377 in the #3427 PR, since I cannot reproduce it on stage server.
