### ISSUE TITLE
Test Pilot extension: unexpected updates with a 56.x browser

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/testpilot#3432]
Yesterday (2018-03-20) with my 'everyday' Waterfox profiles: 

![2018-03-20 18 14 25](https://user-images.githubusercontent.com/192271/37704515-f489bed4-2cf0-11e8-891c-013b6bbd6402.png)

![2018-03-20 18 15 13](https://user-images.githubusercontent.com/192271/37704531-0209ac22-2cf1-11e8-8286-78410be4a8c0.png)

tl;dr as far as I could tell, the update that was offered: 

- did download
- did not install. 

----

Today, with a different Waterfox profile: 

![2018-03-21 07 58 32](https://user-images.githubusercontent.com/192271/37704664-5af415fc-2cf1-11e8-856b-1afb6c81770d.png)

![2018-03-21 08 00 57](https://user-images.githubusercontent.com/192271/37704667-5dec176e-2cf1-11e8-89c2-fc0b5745d12e.png)

UA string: 

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4`

Already installed: 

- 2.0.7-dev-b9268d2

I refrained from attempting to download or install the update. 

----

According to <https://testpilot.firefox.com/>, 

> Test Pilot requires Firefox 58 or higher.

– so for a 56.x browser (Waterfox 56.0 was based on Firefox 56.0.2), I doubt that an update to the extension is applicable.

**Comment by marniepw** [comment]
Closing as we no longer support v.56.
