### ISSUE TITLE
Scroll clicking the "Blog" button wrongly redirects you to the page in same tab, instead of a new one

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3434]
**[Notes]:**
- The react-router implementation from #3405 fixed all the `open in a new tab `issues with scroll click (middle click) we had, except this one. Maybe it's something related to the button itself? 

**[Affected versions]:**
- Firefox Nightly 61.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll click (middle click) on the "Blog" text button on top right side of the page.
3. Observe the page behavior.

**[Expected result]:**
- A new tab is opened where the Test Pilot Medium blog page is loaded.

**[Actual result]:**
- The Test Pilot Medium blog page is wrongly loaded in the same tab.

**[Additional Notes]:**
- This issue also occurs on /experiments page after Test Pilot add-on is installed.
- Here is a screen recording of the issue: https://goo.gl/wAFBXV.

**Comment by ghost** [comment]
@SoftVision-PaulOiegas Something is wrong with the link?

<img width="1155" alt="Image broken link" src="https://user-images.githubusercontent.com/22018999/37858405-ab7045ce-2eda-11e8-934a-140e50d97b36.png">

**Comment by SoftVision-PaulOiegas** [comment]
@csd713 Seems that Google had some issues with the shortener last week. Is it working for you now? I managed to view it on 3 different browsers.

Still, even without the screen recording, the issue is pretty straight forward to reproduce.

**Comment by SoftVision-PaulOiegas** [comment]
Scroll clicking on the button now correctly loads the Blog page into a new tab. 👍
