### ISSUE TITLE
Add metric for featured experiment video

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3436]
This is a follow up issue for https://github.com/mozilla/testpilot/pull/3435.

The [Click Featured Experiment Video](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#featured-experiment) metric calls for dimension12, which asks "How much did the video did the user watch?". In order to attain this information we'll need to add youtube's Iframe api.

We'll probably need to get a sign off from security to add this exception to our CSP ruleset.

**Comment by johngruen** [comment]
We do get metrics from the youtube side, though i don't know how/whether we can filter on embed context. I can look into this.

**Comment by meandavejustice** [comment]
@johngruen did you find anything out about this?

**Comment by meandavejustice** [comment]
Okay so after looking into this a bit more, here is where we are with this metric.

| Description                      | `eventAction`         | `eventLabel`                  | Custom Dimensions          |
| -------------------------------- | --------------------- | ----------------------------- | -------------------------- |
| Click Featured Experiment Video  | video click           | Play Featured video           | [1, 2, 3, 12, 10, 11, 13]  |

We are only able to log one, initial click onto the iframe without adding the [YouTube Iframe Api](https://developers.google.com/youtube/iframe_api_reference). This is because of limitations of iframes built in for security concerns. This logging/handling of the initial click is a hack.

Adding the YouTube iframe api has some additional concerns. We would have to add an exception to CSP which would need to get security review.

#### The 12th dimension
| Page                                          | Description                                             | dimension | values |
|-----------------------------------------------|---------------------------------------------------------|-----------|--------|
| Home Page                                     | How much did the video did the user watch?              | 12        | {'None (<10)','Some (10-90)','All (>90)'}|

The only way to get the video's progress is by adding the YouTube Iframe api. And will only send the event when the video has been manually stopped. We could also add a video ended metric event.

> We do get metrics from the youtube side, though i don't know how/whether we can filter on embed context.

Here are available youtube metrics:
![image 1](https://user-images.githubusercontent.com/1844554/38640632-5702165e-3dc4-11e8-839c-5fe788bca594.png)
![image](https://user-images.githubusercontent.com/1844554/38640633-572ab50a-3dc4-11e8-8563-cb2440bc5353.png)

It sounds like it would be rather difficult if possible, to corelate our youtube metrics and ga featured video click event.

I think this metric may simply be not worth the amount of effort to adding the yt api, security review, and event listener hack that would be required to complete it.

Thoughts? @johngruen @teonbrooks

**Comment by fzzzy** [comment]
Using the yt api that allows getting the time played requires loosening the CSP to allow youtube.com to run inline-scripts. This would allow scripts running from youtube.com to access mozAddonManager. This would probably not pass security review.

**Comment by meandavejustice** [comment]
I'd like to get this issue closed so that we can close #3234, it's the only bug left in the current milestone. We should be able to close this by just removing the reference to the featured video metric in `ga.js`.

**Comment by johngruen** [comment]
@meandavejustice  could do something where we could start a counter (probably incremented per session) on our end when a user starts a video and then dump that into the CD? We could manually add a field to yaml with the total video time if we wanted to report % in the CD

**Comment by teonbrooks** [comment]
@meandavejustice, if we can't get the duration, I think having the action of starting the video would be useful to know. you mentioned that this doesn't require instrumenting any of the yt api, correct?

**Comment by johngruen** [comment]
@teonbrooks yeah we could at least record click events on the video

**Comment by dannycoates** [comment]
video clicks won't be tracked by the page.

https://github.com/mozilla/testpilot/pull/3534#issuecomment-387153586
