### ISSUE TITLE
Maybe we should just show past experiments on landing pages for awhile.

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3437]
Since we're about to only have two active experiments for a bit, maybe we should simplify our UI and show past experiments by default...something like this:

<img width="1466" alt="screen shot 2018-03-22 at 9 27 16 am" src="https://user-images.githubusercontent.com/3323249/37773172-3de4886c-2db3-11e8-89a0-62d1493bf3a5.png">

@dannycoates @sevaan @chuckharmston what do you guys think?

**Comment by sevaan** [comment]
That's a good idea. Maybe the cards for past experiments could be reduced a bit, or formatted into rows or something just to separate it more from what's active.

**Comment by johngruen** [comment]
KK, i'll give this needs UX then for now and assign you.

**Comment by meandavejustice** [comment]
@sevaan  any progress on this here?

**Comment by sevaan** [comment]
I made a little progress but have held off as this may be a piece of work our new intern will work on as an easy thing to start on.
