### ISSUE TITLE
Testing local server on Window is not possible due to page loading issues

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3443]
**[Affected versions]:**
- Firefox Nightly 60.0a1 

**[Affected Platforms]:**
- Windows

**[Prerequisites]:**
- Latest Firefox Developer Edition browser was installed / extracted.
- The setup for local environment testing was performed as described in the [quickstart](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md) document. 
- Test Pilot GitHub repo was cloned and installed as in the above document (if not already done above)  

**[Steps to reproduce]:**
1. Open a cmd/terminal window and change the directory to the "testpilot" folder (`cd testpilot`).
2. Enter the `npm start` command and after wait for the server start to be finalized.
3. Open the Firefox Developer Edition with the profile from prerequisites and navigate to `https://example.com:8000/` page.
4. Observe the page behavior.  

**[Expected result]:**
- The Test Pilot Homepage is correctly loaded.

**[Actual result]:**
- A glimpse of the Homepage is shortly displayed, but after the page is cleared and you are left only with the gradient background.

**[Notes]:**
- The same steps applied on Mac OS are correctly working.
- Here is the console output for trying to load the Homepage: https://pastebin.mozilla.org/9080928.

**Comment by dannycoates** [comment]
This seems to be because the email `<input>` is wrapped in `Localized` and it's somehow not going through [here](https://github.com/projectfluent/fluent.js/blob/8e4f284e04b9333393da8c66dca46d82f3e60b57/fluent-react/src/localized.js#L115-L121) properly. 😕

I don't know why it happens on windows but not osx. Are the versions of fluent and react the same?

**Comment by meandavejustice** [comment]
I'm not able to reproduce this on Window 10. Firefox Developer Edition 60.0b7 

![dev-editon-no-addon](https://user-images.githubusercontent.com/1844554/38045793-6292bf04-32ad-11e8-87b8-01efd8017b81.png)

![dev-editon-with-addon](https://user-images.githubusercontent.com/1844554/38045795-65d1016c-32ad-11e8-9cfe-f16f6cfc1de4.png)

**Comment by SoftVision-PaulOiegas** [comment]
This is strange. I'm testing on the same version of Dev Edition now and I'm still getting just the page background after each page refresh.
What is your windows version Dave? I have Windows 10 Pro x64, Version 10.0.15063 Build 15063. 

Do we still need all the prefs to run locally?
1. `user_pref("extensions.webapi.testing", true);`
2. `user_pref("extensions.legacy.enabled", true);`
3. `user_pref("testpilot.env", "local");`
4. `user_pref("extensions.install.requireBuiltInCerts", false);`
5. `user_pref("xpinstall.signatures.required", false);`

Could node or npm affect in some way?

**Comment by SoftVision-PaulOiegas** [comment]
Adding also a recording of the issue https://goo.gl/19P7eg.
You can see that only if I stop the page loading I can see the content of it. Otherwise, I always end up just with the background.

**Comment by dannycoates** [comment]
@SoftVision-PaulOiegas it looks like you were nearly there, a couple hundred more refreshes and I bet it'd work ;) 

It seems like a npm dependency issue. Have you tried a `npm install` recently?

**Comment by SoftVision-PaulOiegas** [comment]
I had npm 5.6.0 and updated to 5.8.0 and Node was 8.8.5 or something and updated to 8.11.1. Still, the same issue occurs even after creating a new dev edition profile with all the prefs set.

C:\Users\paul.oiegas>npm -v
5.8.0
C:\Users\paul.oiegas>node -v
v8.11.1

Double checked with some of my team members PC's that are also on Win 10 and they encountered the same behavior...

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates @meandavejustice this became worst now. As I've mentioned Thursday on Slack, now I cannot even build the add-on to test locally.

![image](https://user-images.githubusercontent.com/17258026/38558257-3368b62c-3cd8-11e8-95a6-406387303138.png)

Tried the next things:
1. Install the missing stuff locally
 - Installed ESLint locally `npm install eslint --save-dev eslint` + ESLint-plugin-flowtype using `npm i eslint-plugin-flowtype@latest --save-dev eslint`
-doing this threw the next error `ESLint couldn't find the plugin "eslint-plugin-react".`
- installed plugin-react with `npm i eslint-plugin-react@latest --save-dev eslint`
-doing this threw the next error `ESLint couldn't find the plugin "eslint-plugin-mozilla".`
- installed plugin-mozilla with `npm i eslint-plugin-mozilla@latest --save-dev eslint`
-doing this threw the next error `ESLint couldn't find the plugin "eslint-plugin-no-unsanitized".`
- installed plugin-no-unsanitized with `npm i eslint-plugin-no-unsanitized@latest --save-dev eslint`
-this threw `Cannot find module 'babel-eslint'`. At this point I gave up and uninstalled all the local installs made including ESLint.

I haven't configured anything else because I'm not familiar with this.

2.  Install ESLint glogally + flowtype
- used `npm install -g eslint` and `npm install -g eslint-plugin-flowtype`
- this threw again `ESLint couldn't find the plugin "eslint-plugin-flowtype".`

3. Reinstall everything + retry
- uninstalled all the local plugins previously installed
- uninstalled Node.js
- restarted PC and reinstalled Node JS 8.11.1 with npm 5.8.0.
- used `git clone https://github.com/mozilla/testpilot && cd testpilot && cd addon && npm install && npm run package` and the result was again as above in the console screenshot.

I have never encountered this issues before with the old implementation, so probably additional configurations are required in order to setup the local server for testing that are not mentioned in quickstart doc.

**Comment by dannycoates** [comment]
@SoftVision-PaulOiegas I want to help you with this. It'd probably be easiest over Vidyo. Ping me tomorrow morning if you have time. I'm available starting at 8am PDT

**Comment by lmorchard** [comment]
> used git clone https://github.com/mozilla/testpilot && cd testpilot && cd addon && npm install && npm run package and the result was again as above in the console screenshot.

If this is *exactly* what you did, then there's an `npm install` missing after `git clone https://github.com/mozilla/testpilot && cd testpilot` and before `cd addon`. That would explain a lot of missing modules, if `npm install` was never run in the project root directory.

So to start a dev server:
```
git clone https://github.com/mozilla/testpilot
cd testpilot
npm install
npm start
```
And *then* you can try building the add-on - which, actually, I haven't tried on Windows in awhile:
```
cd addon
npm install
npm run package
```
There *might* be a unix-specific command or two in the add-on package comment, but I'm not sure.

**Comment by lmorchard** [comment]
> The setup for local environment testing was performed as described in the [quickstart](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md) document.

Also, I just noticed in quickstart that [we mention](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md#for-windows-hosts) running `npm install` in the addon directory *before* `npm install` in the root project directory. That might be backward and need a tweak.

Additionally, the `package-win` command is no longer available and should probably be changed to just `package` in those instructions. 

Edit: Actually, I think we might need a `package-win` again - or use a cross-platform mv equivalent ([shx maybe?](https://github.com/shelljs/shx)) - because windows has no `mv` command as used in `npm run package`
```
'mv' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testpilot-addon@3.0.0 package: `cross-env web-ext build --overwrite-dest && mv web-ext-artifacts/test_pilot-$npm_package_version.zip ./addon.xpi`
npm ERR! Exit status 1
npm ERR!
```

**Comment by lmorchard** [comment]
Also also, I think that with the bootstrap-based add-on, we tried to keep node_modules and package.json completely separate for the site and the add-on. 

Now, I think the addon directory depends on the parent directory packages - especially when considering eslint and associated modules. So, we have to run `npm install` in the project directory before doing so in `addon` - the reverse of what quickstart advises.

FWIW, I don't think this is a Windows specific issue - if someone tried a fresh, from scratch clone and build, they'd probably see similar issues on OS X or Linux

**Comment by lmorchard** [comment]
And for good measure, I just tried a fresh checkout on Windows. Main issue is that a) the addon package task failed on the mv command and b) webpack build on the web frontend failed on trying to copy the addon.xpi from npm package.

But, the dev server did start up for me and things worked. Here's an edited copy of from my PowerShell window:
```
C:\Users\lmorchard\devel> git clone https://github.com/mozilla/testpilot testpilot-3443
Cloning into 'testpilot-3443'...
remote: Counting objects: 37058, done.
remote: Compressing objects: 100% (278/278), done.
remote: Total 37058 (delta 169), reused 171 (delta 78), pack-reused 36702
Receiving objects: 100% (37058/37058), 47.95 MiB | 556.00 KiB/s, done.
Resolving deltas: 100% (26570/26570), done.
C:\Users\lmorchard\devel> cd testpilot-3443
C:\Users\lmorchard\devel\testpilot-3443 [master ≡]> npm install
(... snip npm install output ...)
C:\Users\lmorchard\devel\testpilot-3443 [master ≡]> cd .\addon\
C:\Users\lmorchard\devel\testpilot-3443\addon [master ≡]> npm install
(... snip npm install output ...)
C:\Users\lmorchard\devel\testpilot-3443\addon [master ≡ +0 ~1 -0 !]> npm run package
(... this works until there's an error with mv  ...)
C:\Users\lmorchard\devel\testpilot-3443\addon [master ≡ +1 ~1 -0 !]> cd ..
C:\Users\lmorchard\devel\testpilot-3443 [master ≡ +1 ~1 -0 !]> npm start

> testpilot@1.0.0 start C:\Users\lmorchard\devel\testpilot-3443
> cross-env NODE_ENV=development ENABLE_DEV_LOCALES=1 ENABLE_DEV_CONTENT=1 npm-run-all build:gulp watch
(... snip output from build ...)
```

**Comment by SoftVision-PaulOiegas** [comment]
@lmorchard I see. In the past the order was not a problem, Donovan confirmed this. But as you've said, this only worked for the bootstraped version.

I've performed the steps in the correct order and the server did started, but now I hit the initial problem, where only the website background is loaded.

@dannycoates Thanks, but I will have to leave the remaining issue for Thursday. I have a medical issue and I won't be available today. I'll ping you tomorrow.

**Comment by lmorchard** [comment]
> I've performed the steps in the correct order and the server did started, but now I hit the initial problem, where only the website background is loaded.

@SoftVision-PaulOiegas Are you seeing any errors in the JS console by chance? (Things are working okay for me on Win10)

**Comment by meandavejustice** [comment]
I just pulled down another fresh copy when reviewing #3483, and everything worked smoothly.

**Comment by ghost** [comment]
@SoftVision-PaulOiegas we can't reproduce this, so closing.  reopen if there is more to do here. thanks

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc sadly it still reproduces for me both at work and at my home on different machines.

@dannycoates offered to help but due to timezone differences it was hard to find a proper time to debug this further. I'll try to find a moment to discuss with him on this matter and we'll reopen this only if there is an issue on Test Pilot side that is causing this behavior on my end...
