### ISSUE TITLE
Update Test Pilot pages in SUMO

### ISSUE THREAD

**Issue by marniepw** [mozilla/testpilot#3447]
See:
https://support.mozilla.org/en-US/kb/new-test-pilot-experiments
https://support.mozilla.org/en-US/kb/test-pilot-firefoxs-experimental-features (wrong image under Leave Test Pilot section, etc.)

_(this is something I can do, but wanted to park it here so it doesn't get lost...)_

**Comment by SoftVision-PaulOiegas** [comment]
@marniepw If you need any help with the flows that changed since the old description, let me know. 😃

**Comment by marniepw** [comment]
Thanks @SoftVision-PaulOiegas!

**Comment by SoftVision-PaulOiegas** [comment]
@marniepw Hmm... [this one](https://support.mozilla.org/en-US/kb/test-pilot-firefoxs-experimental-features) is still not updated and contains very old designs and flows.

**Comment by marniepw** [comment]
Yep, I submitted changes for that Wednesday afternoon. They're waiting to be approved!

**Comment by SoftVision-PaulOiegas** [comment]
Oh, ok. Didn't knew that. Will double check when it updates.
