### ISSUE TITLE
Whitelist about:newtab

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/testpilot#3451]
Hi testpilot team,

The snippets-service does some targeting based on the existence of testpilot addon. For that we use `navigator.testpilotaddon` which you make available for us by whitelisting `about:home`.

This works fine for `about:home` and we want to do the same for `about:newtab`. I know that these will go away in the future and we have already made the needed changes to handle this situation in Fx60. But we'll like to be able to query `navigator.testpilotaddon` before Fx60. 

Is it possible to whitelist and push this update to users in the near future?

**Comment by glogiotatidis** [comment]
Hey @dannycoates could you please provide some feedback here?

**Comment by marniepw** [comment]
FYI @johngruen and @clouserw

**Comment by ghost** [comment]
Hi.  We actually have a pull request under review (#3456) which removes all bootstrap code from Test Pilot which we are (hopefully) landing today.  This will mean it's not possible to do this.

An alternative @chuckharmston suggested was that the about: pages should get access to the MozAddonManager API so it can look at what is installed.
