### ISSUE TITLE
Don't render application until we have the correct application state (fix loading jank)

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3453]
Test Pilot is looking pretty zippy these days, but experiments details pages still flash incorrect content for a quick second while rendering.

To view this, go to: 
1. https://testpilot.firefox.com/experiments/notes with test pilot installed
2. Note the flash of content at the top of the page before the site detects the add-on

Either we should avoid rendering the page content until state is resolved or we should bring back the loader. Loaders are better ui than janky loading.

IIRC this is an issue on the featured experiment UI as well, though we're not displaying a featured experiment at the moment.

**Comment by dannycoates** [comment]
How's dev for you? (It should be better)

**Comment by marniepw** [comment]
Add a loading spinner. Spinner in repo.
