### ISSUE TITLE
failing unit tests pass circleci

### ISSUE THREAD

**Issue by dannycoates** [mozilla/testpilot#3455]

**Comment by b4handjr** [comment]
Is there an example of this?

**Comment by dannycoates** [comment]
https://circleci.com/gh/mozilla/testpilot/8868?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

which is commit b0705c994a956694cb505a27a6d18ca7d00b12f9

The exit code of `npm run test:ci` is 18, as in 18 failures, which are easier to see if you run `npm test`

**Comment by b4handjr** [comment]
So should we run npm test instead? What does ```test:ci``` do vs ```test```?
