### ISSUE TITLE
Browser tab name is no longer updated when navigating to Test Pilot experiments pages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3461]
[Affected versions]:
- Firefoxx 59.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

[Steps to reproduce]:
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.stage.mozaws.net page.
2. Observe the browser tab name and after click on one of the available experiments.
3. Observe again the browser tab name.

[Expected result]:
- Step 2: "Firefox Test Pilot" is displayed as tab name.
- Step 3: The tab name updates with the name of the visited experiment page "Firefox Test Pilot - experiment_name".

[Actual result]:
- Step 2: "Firefox Test Pilot" is displayed as tab name.
- Step 3: The tab name remains as "Firefox Test Pilot" no matter what experiment you visit. 

[Notes]:
- The tab name only updates if the page is refreshed.
- This is a regression since the issue is not reproducible on Test Pilot production server.
- I recall having a similar issue (#1518) in the past and it was fixed by #1676
- Here is a screen recording with the issue:
![tab name](https://user-images.githubusercontent.com/19226534/38249899-e5df83cc-3755-11e8-8ae4-55745c2b0b8d.gif)

**Comment by chuckharmston** [comment]
https://github.com/nfl/react-helmet

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be working well now. 👍
