### ISSUE TITLE
News articles do not return to their default state when they are dragged and released in a different area

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/testpilot#3463]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
Following 5 prefs have been set or added on a new profile: 
- 	"extensions.legacy.enabled = true" 
- 	"xpinstall.signatures.required = false" 
- 	"testpilot.env = stage" 
- 	"extensions.webapi.testing = true" 
- 	"extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.stage.mozaws.net/news page.
2. Click on a news article and hold the click.
3. Drag and release the click.

**[Expected result]:**
- The article returns to its default state without any overlay and border.

**[Actual result]:**
- The news article has a white semitransparent overlay with a white semitransparent border around it.

**[Notes]:**
- Attached a screen recording of the issue:
![hover over copy button2](https://user-images.githubusercontent.com/37875464/38256452-f97e3638-3766-11e8-831e-81f7b110c4d0.gif)

**Comment by dannycoates** [comment]
Y’all crack me up 😂

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, we had this in pipe for like a month now. But me and Cosmin were keep saying that this is something so insignificant that we shouldn't care of. But since we have a new team member who has a hawkeye... well you get the story. 😂

**Comment by SoftVision-PaulOiegas** [comment]
No longer applies since the News Feed page will be removed soon also on Production.
