### ISSUE TITLE
"Test Pilot Accessibility Design Course" article redirects to a wrong page

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/testpilot#3464]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Start Firefox browser and navigate to "https://testpilot.firefox.com/news" page.
2. Click on "Test Pilot Accessibility Design Course" article.
3. Observe the opened article.

**[Expected result]:**
- The "[Students Pitch New Accessibility Features for Firefox](https://medium.com/firefox-test-pilot/students-pitch-new-accessibility-features-for-firefox-3c21781ed725)" article is opened: 

**[Actual result]:**
- "[Storybook + Test Pilot = ❤](https://medium.com/firefox-test-pilot/storybook-test-pilot-26d21fdb6c64)" article is opened.

**[Notes]:**
- attached a screen recording of the issue:
![wrong article page](https://user-images.githubusercontent.com/37875464/38259372-812c5564-376d-11e8-862b-2c83f0cf9109.gif)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on Test Pilot (3.0.0) dev version. Now you are correctly redirected to the "Students Pitch New Accessibility Features for Firefox" article. 
Tested on Windows 7 x64, Mac 10.12 and Arch Linux.
