### ISSUE TITLE
Experiments cards have lost their URL's which makes them impossible to be opened in separate tabs

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3467]
**[Affected versions]:**
- Firefox Nightly 61.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Hover over the available experiments cards and right click one of them.
3. Choose the "Open Link in New Tab" option from context menu.

**[Expected result]:**
- The experiment details page is opened in a new tab.

**[Actual result]:**
- There are no link options in the displayed context menu.

![context menu](https://user-images.githubusercontent.com/17258026/38309598-22c35566-3823-11e8-8430-cd1d34d7962a.png)

**Comment by dannycoates** [comment]
This is from #3454

**Comment by SoftVision-PaulOiegas** [comment]
Works ok now. 👍
