### ISSUE TITLE
Test Pilot production is wrongly opened when clicking the toolbar button after you instaleld from dev server

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3468]
**[Affected versions]:**
- Firefox Nightly 61.0a1 

**[Affected Platforms]:**
- Windows
- Mac OS
- Linux

**[Prerequisites]:**
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net page.
2. Click the "Install the Test Pilot Add-on" button.
3. After the add-on is installed, click on the Test Pilot toolbar button.
4. Observe the URL of the page opened in the new tab. 

**[Expected result]:**
- You are redirected to https://testpilot.dev.mozaws.net.experiments page in the newly opened tab.

**[Actual result]:**
- You are wrongly redirected to https://testpilot.firefox.com/experiments production page.

**[Notes]:**
- Here is a screen recording of the issue: https://goo.gl/J8BDco.

**Comment by dannycoates** [comment]
This is the new behavior going forward. The environment is configured on the addon's options page.

We can't read about:config so unless we create a separate build for each environment to set the default, we're stuck with one initial state. It seems like it'd lead to more confusion if we had different builds.

**Comment by fzzzy** [comment]
We had previously discussed having a build for each environment -- would it be less confusing if each one had a different name, like Test Pilot Dev, Test Pilot Stage, etc?

**Comment by dannycoates** [comment]
My care level is super low on this. It's a dev feature and complicating the build for it is worse imo.
