### ISSUE TITLE
"Back" button does not redirect to the previous experiment page if the page was accessed from another experiment's page

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/testpilot#3469]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: 
	"extensions.legacy.enabled = true" 
	"xpinstall.signatures.required = false" 
	"testpilot.env = stage" 
	"extensions.webapi.testing = true" 
	"extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate to
https://testpilot.stage.mozaws.net/ page.
2. Click on an experiment card.
3. Scroll to the bottom of the page and click an available experiment card.
4. Click the "Back" button and observe the behavior.

**[Expected result]:**
 The previous page is opened.

**[Actual result]:**
 The page doesn't change.
 URL doesn't change.
 Only video changes accordingly to the previous page.

**[Notes]:**
- This issue is not reproducible on Test Pilot production server.
- This issue is also reproducible on Google Chrome, Safari, Microsoft Edge and Opera Browsers.
- attached a screen recording of the issue:
![go back button does not work properly](https://user-images.githubusercontent.com/37875464/38312054-64e8dd70-3829-11e8-99b7-9f898ccff3fc.gif)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible on Test Pilot (3.0.0)  dev version. Tested on Windows 7 x64, Mac 10.12 and Arch Linux.
