### ISSUE TITLE
A "SG" favicon is wrongly displayed on the Test Pilot and experiments feedback survey

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/testpilot#3474]
[Affected versions]:
- Firefox 59.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to https://testpilot.firefox.com/.
2. Scroll to the bottom of the page and click the "Give Feedback" text link.
3. Observe the tab's favicon.

[Expected result]:
- Firefox logo favicon is displayed.

[Actual result]:
- A "SG" favicon is displayed.

[Notes]:
- Here is a screenshot with this issue:
![test pilot - feedback](https://user-images.githubusercontent.com/31244235/38374738-1a51d314-38fd-11e8-8cff-6c5603eec25c.png)

**Comment by lmorchard** [comment]
I think that's for SurveyGizmo, who hosts our surveys. Is that something we normally customize? /cc @johngruen @clouserw

**Comment by johngruen** [comment]
I can poke at it, but idk

**Comment by johngruen** [comment]
It's hard to convey how much of a pain in the ass this was to fix :)
