### ISSUE TITLE
Add master->l10n merging to the docs

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3477]
I'd be happy to help with this step, but I'm not sure how we do this.  Let's add it to the docs! :)

**Comment by lmorchard** [comment]
Got a bunch of pings on this in Slack from Friday, but I don't have a magic formula beyond basic merges between master and l10n. Suggestions welcome on a better process.

FWIW, we do also already have docs on the l10n-to-master side of this in the deployment docs:

https://github.com/mozilla/testpilot/blob/master/docs/development/deployment.md#merge-l10n

Here's a brain dump to expand from:

### Getting started from scratch
```
git clone git@github.com:mozilla/testpilot.git
cd testpilot
# Add an explicit mozilla remote, since origin *could* be your own fork
git remote add mozilla git@github.com:mozilla/testpilot.git
git fetch mozilla
git co -b l10n mozilla/l10n
```
Some of these steps can be skipped if you're already working on Test Pilot. Detailing them just for the sake of completeness and clarity.

### Merge master to l10n
This is how we request translations from the community using Pontoon. Ensure changes to strings have stabilized. This should ideally be done every 2 weeks, off cycle from production deployments so we have a week or two for contributions to roll in.
```
git checkout master
git pull mozilla
git checkout l10n
git merge master
git push mozilla
```
### Merge l10n to master
This is how we accept contributed translations from Pontoon. This should ideally be done just before tagging a release for deployment.
```
git checkout l10n
git pull mozilla
git checkout master
git merge l10n
git push mozilla
```
### Caveats / Notes
* We defer localization to the l10n branch to a) cut down on noise on master and b) try to make fewer, more stable requests for translations
* The l10n branch has a dev server auto deployment so localizers can preview work - https://testpilot-l10n.dev.mozaws.net/
* Simple merge yields merge commits - in lieu of pull requests from Pontoon, these can help us see when a batch of translations were accepted.
* Never use `git rebase` or `git push -f` on either master or l10n branches. This has the potential to lose work - and is discouraged on shared public branches in general. (i.e. both master and l10n are shared public branches)
