### ISSUE TITLE
Check issue with Accept headers in ampersand-sync

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#349]
Probably just need to update our dependencies.

_from `app/collections/experiments`_

``` js
// Ampersand.sync doesn't seem to pass correct Accept headers by default.
// This supposedly is fixed by https://github.com/AmpersandJS/ampersand-sync/pull/24
// but still seems busted. Maybe the deps of the dependents haven't been
// updated yet? TODO: investigate
```

**Comment by lmorchard** [comment]
Doh! Turns out the fix in #512 broke things, but I didn't see it in review :(
Reverted in 16898cd8ccfd69bd94fed614f1122ab40a8f763a

**Comment by meandavejustice** [comment]
Opened a pr upstream https://github.com/AmpersandJS/ampersand-model/pull/72

**Comment by clouserw** [comment]
Looks like that was merged.  Can we upgrade and close this?

**Comment by meandavejustice** [comment]
@clouserw The upstream patch still does not fix our specific issue, I need to dig a bit deeper and fix upstream. Not blocking anything, just a minor cleanup issue for future dave

**Comment by johngruen** [comment]
@lmorchard I bet we can close this now :)
