### ISSUE TITLE
Default state prerendering concerns

### ISSUE THREAD

**Issue by marniepw** [mozilla/testpilot#3496]
The default state we prerender is the no-addon state whose header is much larger than the with-addon state which causes a worse UX for with-addon users on first page render. (Comments also in doc: https://docs.google.com/document/d/1dNptk8RArXlxWpfcHXrdIDVFDzbiNyk9Pljh5Y5-KXg/edit# )
 - Can we render a “null state” that has a smooth transition to either state?
 - Can get to where we can use React.hydrate?

**Comment by marniepw** [comment]
Null state (first bullet, above) comments:
 - @johngruen : yeah, difficulty here is that l10n makes it hard to tell how tall the elements would be in advance. Again, page loaders are a totally reasonable (and widely used) solution to this problem. We already have a component just gathering dust :)
 - @lmorchard : Didn't we get a lot of vocal complaints when we had a load spinner, though? Didn't help when it was on every click between pages, so maybe it'll be better now that we have react-router back
 - @johngruen : I think we got them internally?
 - @clouserw : page loading slowness was a common complaint we heard from people all over (including karlof and mayo). Let's record how long it takes browsers to detect the add-ons existence so we can decide how long we'd wait for a spinner to time out.

**Comment by marniepw** [comment]
React.hydrate (second bullet, above) comments:
- @lmorchard : Probably not entirely. One thing that will always catch us is when a timer ticks over on the client-side for graduating an experiment or hiding news items. When that content differs from the server static rendering, bad things happen
 - @ianb : Actually bad things? Or just a console warning?
 - @lmorchard : Bad things in applying virtual DOM changes. Like incorrect img src attributes and broken DOM structures because the algo tried to reuse the wrong nodes. It can be semi-mitigated by ensuring that the **initial render** matches the server and then e.g. only applying client-side driven changes after component mount.
@ianb : Huh, the only time I recall seeing actual problems is when I used a bad key attribute.
@fzzzy : The behavior changed in react 16.

**Comment by ghost** [comment]
closing in favor of #3507
