### ISSUE TITLE
Some incomplete, missing, or unuseful flow type annotations

### ISSUE THREAD

**Issue by marniepw** [mozilla/testpilot#3497]
Some incomplete, missing, or unuseful flow type annotations (details needed: @dannycoates )

**Comment by meandavejustice** [comment]
output from `flow-coverage-report --threshold 50 -i 'src/**/*.js'`

┌──────────────────────────────────────────────────────────────────┬────────────┬─────────┬───────┬─────────┬───────────┐
│ filename                                                         │ annotation │ percent │ total │ covered │ uncovered │
│ src/app/actions/addon.js                                         │       flow │   100 % │    39 │      39 │ 0         │
│ src/app/actions/experiments.js                                   │       flow │   100 % │     8 │       8 │ 0         │
│ src/app/actions/localizations.js                                 │       flow │   100 % │    13 │      13 │ 0         │
│ src/app/actions/newsletter-form.js                               │    no flow │    46 % │    62 │      29 │ 33        │
│ src/app/actions/varianttests.js                                  │       flow │   100 % │     3 │       3 │ 0         │
│ src/app/components/Banner/index.js                               │       flow │   100 % │    21 │      21 │ 0         │
│ src/app/components/Banner/stories.js                             │    no flow │    60 % │    25 │      15 │ 10        │
│ src/app/components/Banner/tests.js                               │    no flow │    50 % │    67 │      34 │ 33        │
│ src/app/components/Copter/index.js                               │       flow │   100 % │    20 │      20 │ 0         │
│ src/app/components/Copter/stories.js                             │    no flow │    57 % │    26 │      15 │ 11        │
│ src/app/components/Copter/tests.js                               │    no flow │    50 % │    63 │      32 │ 31        │
│ src/app/components/EmailDialog/index.js                          │       flow │    79 % │   239 │     189 │ 50        │
│ src/app/components/EmailDialog/tests.js                          │    no flow │    38 % │   325 │     125 │ 200       │
│ src/app/components/ExperimentCardList/index.js                   │    no flow │    39 % │    43 │      17 │ 26        │
│ src/app/components/ExperimentCardList/stories.js                 │    no flow │    73 % │    60 │      44 │ 16        │
│ src/app/components/ExperimentCardList/tests.js                   │    no flow │    49 % │    87 │      43 │ 44        │
│ src/app/components/ExperimentPlatforms/index.js                  │    no flow │    70 % │    60 │      42 │ 18        │
│ src/app/components/ExperimentPlatforms/tests.js                  │    no flow │    61 % │   112 │      69 │ 43        │
│ src/app/components/ExperimentRowCard/index.js                    │       flow │    79 % │   212 │     169 │ 43        │
│ src/app/components/ExperimentRowCard/stories.js                  │    no flow │    81 % │   153 │     124 │ 29        │
│ src/app/components/ExperimentRowCard/tests.js                    │    no flow │    40 % │   703 │     286 │ 417       │
│ src/app/components/ExperimentTourDialog/index.js                 │       flow │    91 % │   214 │     195 │ 19        │
│ src/app/components/ExperimentTourDialog/stories.js               │    no flow │    94 % │    75 │      71 │ 4         │
│ src/app/components/ExperimentTourDialog/tests.js                 │    no flow │    38 % │   297 │     113 │ 184       │
│ src/app/components/FeaturedExperiment/FeaturedButton.js          │       flow │    81 % │   191 │     156 │ 35        │
│ src/app/components/FeaturedExperiment/FeaturedStatus.js          │       flow │   100 % │    33 │      33 │ 0         │
│ src/app/components/FeaturedExperiment/index.js                   │       flow │    67 % │    88 │      59 │ 29        │
│ src/app/components/FeaturedExperiment/stories.js                 │    no flow │    76 % │   209 │     160 │ 49        │
│ src/app/components/FeaturedExperiment/tests.js                   │    no flow │    54 % │   646 │     350 │ 296       │
│ src/app/components/Footer/index.js                               │       flow │    66 % │    33 │      22 │ 11        │
│ src/app/components/Footer/tests.js                               │    no flow │    41 % │   112 │      46 │ 66        │
│ src/app/components/GraduatedNotice/index.js                      │    no flow │    80 % │    25 │      20 │ 5         │
│ src/app/components/GraduatedNotice/stories.js                    │    no flow │    52 % │    21 │      11 │ 10        │
│ src/app/components/GraduatedNotice/tests.js                      │    no flow │    53 % │    43 │      23 │ 20        │
│ src/app/components/Header/index.js                               │       flow │    90 % │   163 │     148 │ 15        │
│ src/app/components/Header/stories.js                             │    no flow │    56 % │    23 │      13 │ 10        │
│ src/app/components/Header/tests.js                               │    no flow │    49 % │   366 │     181 │ 185       │
│ src/app/components/LayoutWrapper/index.js                        │    no flow │    83 % │    18 │      15 │ 3         │
│ src/app/components/LayoutWrapper/stories.js                      │    no flow │    87 % │   148 │     129 │ 19        │
│ src/app/components/LayoutWrapper/tests.js                        │    no flow │    54 % │    46 │      25 │ 21        │
│ src/app/components/Loading/index.js                              │    no flow │    75 % │     4 │       3 │ 1         │
│ src/app/components/Loading/tests.js                              │    no flow │    52 % │    34 │      18 │ 16        │
│ src/app/components/LocalizedHtml.js                              │    no flow │    46 % │   131 │      61 │ 70        │
│ src/app/components/MainInstallButton/index.js                    │       flow │    57 % │   226 │     130 │ 96        │
│ src/app/components/MainInstallButton/stories.js                  │    no flow │    75 % │    60 │      45 │ 15        │
│ src/app/components/MainInstallButton/tests.js                    │    no flow │    52 % │   241 │     126 │ 115       │
│ src/app/components/Measurements/index.js                         │       flow │    61 % │    59 │      36 │ 23        │
│ src/app/components/Modal/index.js                                │       flow │    79 % │    72 │      57 │ 15        │
│ src/app/components/NewsUpdatesDialog/index.js                    │       flow │    90 % │   181 │     163 │ 18        │
│ src/app/components/NewsUpdatesDialog/stories.js                  │    no flow │    65 % │   134 │      88 │ 46        │
│ src/app/components/NewsUpdatesDialog/tests.js                    │    no flow │    57 % │   226 │     131 │ 95        │
│ src/app/components/NewsletterFooter/index.js                     │       flow │    96 % │    50 │      48 │ 2         │
│ src/app/components/NewsletterFooter/stories.js                   │    no flow │    78 % │    57 │      45 │ 12        │
│ src/app/components/NewsletterFooter/tests.js                     │    no flow │    53 % │   226 │     121 │ 105       │
│ src/app/components/NewsletterForm/index.js                       │       flow │    95 % │   107 │     102 │ 5         │
│ src/app/components/NewsletterForm/stories.js                     │    no flow │    75 % │    65 │      49 │ 16        │
│ src/app/components/NewsletterForm/tests.js                       │    no flow │    46 % │   232 │     107 │ 125       │
│ src/app/components/PastExperiments/index.js                      │       flow │   100 % │    52 │      52 │ 0         │
│ src/app/components/PastExperiments/stories.js                    │    no flow │    73 % │    60 │      44 │ 16        │
│ src/app/components/PastExperiments/tests.js                      │    no flow │    40 % │    76 │      31 │ 45        │
│ src/app/components/RetireConfirmationDialog/index.js             │       flow │    75 % │    69 │      52 │ 17        │
│ src/app/components/RetireConfirmationDialog/tests.js             │    no flow │    33 % │   203 │      68 │ 135       │
│ src/app/components/Settings/index.js                             │       flow │    83 % │   130 │     109 │ 21        │
│ src/app/components/StepModal/index.js                            │       flow │    92 % │   234 │     217 │ 17        │
│ src/app/components/StepModal/tests.js                            │    no flow │    39 % │   105 │      41 │ 64        │
│ src/app/components/UpdateList/index.js                           │       flow │    84 % │   267 │     225 │ 42        │
│ src/app/components/UpdateList/stories.js                         │    no flow │    74 % │   175 │     130 │ 45        │
│ src/app/components/UpdateList/tests.js                           │    no flow │    50 % │   547 │     275 │ 272       │
│ src/app/components/VariantTests/index.js                         │       flow │    71 % │    42 │      30 │ 12        │
│ src/app/components/View/index.js                                 │    no flow │    55 % │   102 │      57 │ 45        │
│ src/app/components/View/tests.js                                 │    no flow │    48 % │   225 │     110 │ 115       │
│ src/app/components/Visibility/index.js                           │       flow │    89 % │   141 │     126 │ 15        │
│ src/app/components/Visibility/tests.js                           │    no flow │    45 % │   181 │      82 │ 99        │
│ src/app/components/Warning/index.js                              │       flow │    92 % │    82 │      76 │ 6         │
│ src/app/components/Warning/tests.js                              │    no flow │    40 % │   132 │      54 │ 78        │
│ src/app/components/types.js                                      │    no flow │   100 % │     2 │       2 │ 0         │
│ src/app/config.js                                                │    no flow │    80 % │    41 │      33 │ 8         │
│ src/app/containers/App/index.js                                  │    no flow │    41 % │   714 │     299 │ 415       │
│ src/app/containers/App/tests.js                                  │    no flow │    47 % │   134 │      64 │ 70        │
│ src/app/containers/ErrorPage.js                                  │       flow │   100 % │     9 │       9 │ 0         │
│ src/app/containers/ExperimentPage/DetailsDescription.js          │       flow │    41 % │   162 │      67 │ 95        │
│ src/app/containers/ExperimentPage/DetailsHeader.js               │       flow │    54 % │   576 │     315 │ 261       │
│ src/app/containers/ExperimentPage/DetailsOverview.js             │       flow │    34 % │   145 │      50 │ 95        │
│ src/app/containers/ExperimentPage/ExperimentDisableDialog.js     │       flow │    64 % │   109 │      70 │ 39        │
│ src/app/containers/ExperimentPage/ExperimentEolDialog.js         │       flow │    75 % │    60 │      45 │ 15        │
│ src/app/containers/ExperimentPage/ExperimentPreFeedbackDialog.js │       flow │    70 % │   117 │      83 │ 34        │
│ src/app/containers/ExperimentPage/IncompatibleAddons.js          │       flow │    85 % │    47 │      40 │ 7         │
│ src/app/containers/ExperimentPage/TestpilotPromo.js              │       flow │    34 % │    23 │       8 │ 15        │
│ src/app/containers/ExperimentPage/index.js                       │       flow │    58 % │   478 │     279 │ 199       │
│ src/app/containers/ExperimentPage/stories.js                     │    no flow │    77 % │   403 │     312 │ 91        │
│ src/app/containers/ExperimentPage/tests.js                       │    no flow │    40 % │  2555 │    1043 │ 1512      │
│ src/app/containers/ExperimentPage/types.js                       │    no flow │   100 % │    19 │      19 │ 0         │
│ src/app/containers/HomePage/HomePageNoAddon.js                   │       flow │    96 % │    79 │      76 │ 3         │
│ src/app/containers/HomePage/HomePageWithAddon.js                 │       flow │    88 % │   246 │     217 │ 29        │
│ src/app/containers/HomePage/index.js                             │    no flow │    66 % │     9 │       6 │ 3         │
│ src/app/containers/HomePage/stories.js                           │    no flow │    78 % │    76 │      60 │ 16        │
│ src/app/containers/HomePage/tests.js                             │    no flow │    56 % │   607 │     345 │ 262       │
│ src/app/containers/NewsFeedPage/index.js                         │       flow │   100 % │    19 │      19 │ 0         │
│ src/app/containers/NewsFeedPage/stories.js                       │    no flow │    53 % │    30 │      16 │ 14        │
│ src/app/containers/NewsFeedPage/tests.js                         │    no flow │    67 % │    81 │      55 │ 26        │
│ src/app/containers/NotFoundPage.js                               │    no flow │    90 % │    10 │       9 │ 1         │
│ src/app/containers/OnboardingPage/index.js                       │    no flow │    87 % │     8 │       7 │ 1         │
│ src/app/containers/RestartPage.js                                │       flow │    94 % │    17 │      16 │ 1         │
│ src/app/containers/RetirePage/index.js                           │       flow │    94 % │    71 │      67 │ 4         │
│ src/app/containers/UpgradeWarningPage/index.js                   │       flow │    98 % │    67 │      66 │ 1         │
│ src/app/containers/UpgradeWarningPage/stories.js                 │    no flow │    67 % │    55 │      37 │ 18        │
│ src/app/containers/UpgradeWarningPage/tests.js                   │    no flow │    49 % │   131 │      65 │ 66        │
│ src/app/containers/types.js                                      │    no flow │   100 % │     3 │       3 │ 0         │
│ src/app/index.js                                                 │    no flow │    50 % │    87 │      44 │ 43        │
│ src/app/lib/InstallManager.js                                    │    no flow │    38 % │   473 │     184 │ 289       │
│ src/app/lib/experiment.js                                        │       flow │    95 % │    63 │      60 │ 3         │
│ src/app/lib/ga-snippet.js                                        │    no flow │    39 % │    81 │      32 │ 49        │
│ src/app/lib/install-history.js                                   │    no flow │    42 % │    57 │      24 │ 33        │
│ src/app/lib/tests.js                                             │    no flow │    46 % │   101 │      47 │ 54        │
│ src/app/lib/utils.js                                             │    no flow │    65 % │   138 │      91 │ 47        │
│ src/app/reducers/addon.js                                        │       flow │    94 % │   214 │     203 │ 11        │
│ src/app/reducers/browser.js                                      │    no flow │    58 % │    74 │      43 │ 31        │
│ src/app/reducers/experiments.js                                  │       flow │   100 % │    96 │      96 │ 0         │
│ src/app/reducers/localizations.js                                │       flow │   100 % │    40 │      40 │ 0         │
│ src/app/reducers/news.js                                         │       flow │   100 % │    18 │      18 │ 0         │
│ src/app/reducers/newsletter-form.js                              │       flow │    98 % │    76 │      75 │ 1         │
│ src/app/reducers/varianttests.js                                 │       flow │    87 % │   124 │     108 │ 16        │
│ src/app/selectors/addon.js                                       │    no flow │    14 % │     7 │       1 │ 6         │
│ src/app/selectors/experiment.js                                  │    no flow │    36 % │   163 │      60 │ 103       │
│ src/app/selectors/localizations.js                               │    no flow │    16 % │    12 │       2 │ 10        │
│ src/app/selectors/news.js                                        │    no flow │    41 % │   206 │      86 │ 120       │
│ src/app/store.js                                                 │    no flow │    67 % │    58 │      39 │ 19        │
│ src/pages/index.js                                               │    no flow │    59 % │    44 │      26 │ 18        │
│ src/scripts/legal.js                                             │    no flow │    56 % │   266 │     149 │ 117       │
│ src/scripts/locale.js                                            │    no flow │    55 % │   124 │      69 │ 55        │
└──────────────────────────────────────────────────────────────────┴────────────┴─────────┴───────┴─────────┴───────────┘
┌─────────────────────────┬─────────────────────────────────────────┐
│ included glob patterns: │ src/**/*.js                             │
│ excluded glob patterns: │ node_modules/**                         │
│              threshold: │ 50                                      │
│       concurrent files: │ 1                                       │
│           generated at: │ Mon Apr 16 2018 13:09:14 GMT-0400 (DST) │
│           flow version: │ 0.47.0                                  │
│      flow check passed: │ yes (0 errors)                          │
└─────────────────────────┴─────────────────────────────────────────┘
┌──────────┬─────────┬───────┬─────────┬───────────┐
│ project  │ percent │ total │ covered │ uncovered │
│ frontend │    58 % │ 19645 │   11515 │      8130 │
└──────────┴─────────┴───────┴─────────┴───────────┘

**Comment by ghost** [comment]
This is a good first issue.  If you're interested in working on this, just make a PR for a few files and we can commit it in steps, no need to make one giant PR.  Thanks

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. @meandavejustice can you guide me a little bit?

**Comment by meandavejustice** [comment]
@KhushilMistry Sure thing, You'll want to run the command `npm run flow-coverage` to get the most up to date output. Then you can pick a file or two and try to update the flow errors. [docs are here](https://flow.org/en/docs/).

Best way to approach this would be to chip away in small chunks. Just try and fix 1-3 files for each pull request. In your first time through just try and get the low hanging fruit type fixes. If a certain error looks confusing or looks like your going to have to modify a whole bunch of files or refactor a bunch of code just to silence the error, just skip it and document it in this issue so we can approach it down the road.
