### ISSUE TITLE
The page loads translations async, so non-english users see a flash of english

### ISSUE THREAD

**Issue by marniepw** [mozilla/testpilot#3498]
- Can we make it sync?
 - Can we prerender and serve in other languages?
 - Can we just put the loader back again?

Comments also in doc: https://docs.google.com/document/d/1dNptk8RArXlxWpfcHXrdIDVFDzbiNyk9Pljh5Y5-KXg/edit#

**Comment by marniepw** [comment]
Sync comment (first bullet, above):
 - @lmorchard Not really, no. We can render all languages as static (the next point) but otherwise the best we ever managed was to obscure everything with a loader until after first JS render

**Comment by marniepw** [comment]
Prerender comment (second bullet, above):
 - @lmorchard : Sure, but need to restructure the site to include language in the URL (e.g. /en-US/) and render the site once for each supported locale https://github.com/mozilla/testpilot/issues/3008
 - @fzzzy : I've been arguing for this for a long time. I still think it is important.

**Comment by marniepw** [comment]
Loader comment (third bullet, above):
 - @johngruen I'm a broken record

**Comment by dannycoates** [comment]
fixed by #3484
