### ISSUE TITLE
Tour is no longer displayed when re-enabling a manually disabled experiment

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3502]
[Affected versions]:
- Firefox 59.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Have Test Pilot add-on installed and the Notes experiment disabled in "about:addons" page.

[Steps to reproduce]:
1. Start Firefox browser with the profile from prerequisite and navigate to https://testpilot.firefox.com/experiments/notes page.
2. Click the "Enable Notes" blue button.
3. Observe the behavior.

[Expected result]:
- The experiment is correctly enabled and the Notes tour is displayed.

[Actual result]:
- The experiment is correctly enabled, but the Notes tour is not displayed.

[Notes]:
- This issue is not reproducible on Test Pilot production.
- Here is a screen shot with the issue:
![tour is no longer displayed](https://user-images.githubusercontent.com/19226534/38811566-880ae8d0-4192-11e8-816d-f6ea558c2d82.gif)

**Comment by dannycoates** [comment]
I did this on purpose

**Comment by ghost** [comment]
this is by design
