### ISSUE TITLE
Experiment Control UI

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3504]
It looks like we will have four experiment platforms soon, and we'll need to make sure that all combinations are accounted for when displaying Experiment Controls on different platforms. For example, if Send has a mobile app, there will need to be buttons to go to the site, get the app, and for a privacy link. If Notes as a mobile app, there will need to be buttons to go to install the add-on, get the app, and get the privacy link. If i'm viewing either of these experiments on a mobile device, i just need to see thew app store icon and privacy link.

So here's the precedence for experiment control buttons:

## Desktop
1. One Click Install (install test pilot and add-on) (`primary`)
1. Legal string (if showing one click install)
1. Enable Experiment (add-on control if test pilot is installed) (`default` button colors if )
1. Visit Experiment (web-control) (`default` if no add-on, otherwise `secondary`)
1. Get Mobile App (mobile modal trigger) (`secondary`, unless no add-on or website, then `default`)
1. Your Privacy

## Mobile (if applicable)
1. App store badge (link to app store)
1. Visit Experiment Website (optional, this should be a boolean field in YAML like `list_site_for_mobile`)
1. Your Privacy

**Comment by johngruen** [comment]
One edge case, for experiments that are graduated but still installed, the Uninstall button should go in the same location as above

<img width="1085" alt="screen shot 2018-04-16 at 11 25 22 am" src="https://user-images.githubusercontent.com/3323249/38819272-f057a0ec-4168-11e8-801e-d4394508e0d6.png">

#3503

**Comment by dannycoates** [comment]
<img width="794" alt="screen shot 2018-04-25 at 3 53 10 pm" src="https://user-images.githubusercontent.com/87619/39277127-211e650a-48a1-11e8-8bef-c8f13c83f484.png">

**Comment by johngruen** [comment]
wfm

**Comment by dannycoates** [comment]
I need assets for the app store buttons. @sevaan pointed me to the ios ones.  Do we need to worry about l10n of the buttons?
