### ISSUE TITLE
Experiment DetailsMobile and Responsive UI Updates

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3506]
Responsive Desktop View:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard4

iOS & Android:
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard9
https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard1

**Comment by meandavejustice** [comment]
getting 404s for all these links

**Comment by johngruen** [comment]
@meandavejustice should be fixed

**Comment by dannycoates** [comment]
What are we going to do about the modals? They're too wide.

**Comment by johngruen** [comment]
Will bring this up in today's design mtg

**Comment by dannycoates** [comment]
Can we do something different with the platform list? Multiple icons is fine, but constructing sentences for all the possible combinations (and localizations) makes by brain hurt.

Maybe just "Available on: 🌐 🍎 🤖"?

<img width="237" alt="screen shot 2018-05-04 at 3 36 01 pm" src="https://user-images.githubusercontent.com/87619/39655878-139d0a3c-4fb1-11e8-8347-6c1a31899730.png">

**Comment by johngruen** [comment]
Yeah, seems reasonable to me...stay tuned.

**Comment by dannycoates** [comment]
so we have l10n for mobile/web/addon already, but not ios and android specifically. If we don't need icons for them specifically I think we're already good.
