### ISSUE TITLE
Warning Bar for Non-Supported Mobile

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3508]
If We make an iOS experiment adn the user visits on Android (or vice versa) we should show them a warning.

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard6

**Comment by dannycoates** [comment]
It'll be easier to put the warning under the experiment icon like enabled in #3517. @johngruen ok?

**Comment by johngruen** [comment]
WFM

**Comment by johngruen** [comment]
bumping @sevaan just so he's aware

**Comment by sevaan** [comment]
Thanks. Below the icon is great.

**Comment by sevaan** [comment]
![image](https://user-images.githubusercontent.com/473531/39526526-0139eba0-4ded-11e8-8904-aae0057dcd2a.png)

**Comment by dannycoates** [comment]
stupid question: do we really need a warning label when the download buttons are branded & platform specific?

**Comment by SoftVision-PaulOiegas** [comment]
You will be amazed of the logic of some people that are reviewing apps. 😆

**Comment by johngruen** [comment]
I mean, this is like what, 30 minutes of work?

**Comment by sevaan** [comment]
I do like the explicitness of the bar.

**Comment by SoftVision-PaulOiegas** [comment]
Verified this on Android since we only have the Dev experiment marked as iOS app and the error was correctly shown. However, I can't check this on iOS since we don't have an experiment with Android app. unless, there is an easy way to setup something.
