### ISSUE TITLE
Implement Mobile Modals for Desktop Site

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3509]
If an experiment has a mobile component, we will surface that through a button that takes the user to a Modal giving them options to access the mobile experiment on their device or just go to the relevant app store. 

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_experiment_integration/#artboard0

Note:
This spec shows both email and SMS options. Firefox Marketing uses both through an approved API.  I need to have some more conversation with our marketing team to figure out which (SMS/Email) they recommend.

**Comment by johngruen** [comment]
@sevaan what happens in these modals if there's an iOS and an Android app?

**Comment by dannycoates** [comment]
do we have evidence that these modals work? (I assume so, I'm just curious what the success rate is)

**Comment by meandavejustice** [comment]
@sevaan @johngruen Can I get an update for this issue? Is there an answer to @dannycoates question above? Also are the marketing apis documented and available to us?

**Comment by meandavejustice** [comment]
@sevaan the endpoint we have for sms from basket provides us with an "optin to future sms updates from mozilla" option. Would you like me to add a checkbox for this with sms examples?

```- optin: 'Y' if the user wishes to receive other SMS from us in future (default: N)```

**Comment by sevaan** [comment]
Thanks Dave, I spoke to John and we're going to leave the checkbox out for now. Thanks.

**Comment by meandavejustice** [comment]
@sevaan I've noticed we don't handle an error state from basket. Do we want to account for this?

**Comment by sevaan** [comment]
No, no need at this moment. Let's keep track of how many numbers/emails are not going anywhere after passing our validation rules, and then we can decide if we want to address this. I still suspect not.

**Comment by meandavejustice** [comment]
@sevaan Do we have a url for the `learn more` link in the notice at the bottom of the modal?

**Comment by sevaan** [comment]
@johngruen Does our Privacy Policy suffice here?

**Comment by meandavejustice** [comment]
@sevaan Do you have the links for the learn more notice we discussed last week? I can't remember where it was

**Comment by sevaan** [comment]
Here: https://www.mozilla.org/en-US/privacy/websites/#campaigns
