### ISSUE TITLE
Creating a new FxA account Logs into a Social Network Failure Page

### ISSUE THREAD

**Issue by cuff-links** [mozilla/testpilot#351]
# Steps to Reproduce
1. Go to ideatown (https://ideatown.stage.mozaws.net)
2. Click to sign up for new account
3. Create new FxA Account and verify the email
## Expected Result

After verifying email address, you should be taken to a page that says "Thank you for signing up! We will email you when IdeaTown is ready" (or something like that)
## Actual Result

You are taken to a page that says Social Network Failure. If you wait about ten seconds, it takes you to the expected page.

**This only happens with new accounts. Existing accounts go to the correct page.**

**Comment by lmorchard** [comment]
I think this is a duplicate of #341. Also, I don't think ideatown.stage.mozaws.net is not yet a fully set-up instance of Idea Town. I'm curious how folks are finding it and trying things there, I don't think we've linked to it or have publicized it

**Comment by cuff-links** [comment]
@lmorchard  Hello, Les. This link wasn't stumbled upon. Stuart had me working on IdeaTown automation and gave me the link. I checked out #341 and will use the Elastic Beanstalk instance to run the tests instead.
