### ISSUE TITLE
Switching to a website tab while enabling an experiment, breaks the enabling process

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/testpilot#3510]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: 
	- "extensions.legacy.enabled = true" 
	- "xpinstall.signatures.required = false" 	
	- "testpilot.env = stage" 
	- "extensions.webapi.testing = true" 
	- "extensions.install.requireBuiltInCerts = false".
- Have Test Pilot installed. 

**[Steps to reproduce]:**
1. Start Firefox browser with the profile from prerequisite and navigate on any website in a tab.
2. Open a new tab and and navigate to https://testpilot.stage.mozaws.net/ page.
3. Click on one of the available experiments and click on "Enable <experiment>" button for it.
4. Wait for the "Add" doorhanger to appear and switch to previus page tab. 
5. Return to the Test Pilot tab and click on "Add" button from displayed doorhanger.
6. Observe the page's behaviour.

**[Expected result]:**
- The doorhanger is dismissed and the experiment is correctly enabled. 
    
**[Actual result]:**
- The doorhanger is dismissed but the experiment is not installed.

**[Notes]:**
- This issue is not reproducible on Test Pilot production.
- Attached a screen recording of the issue:
![broken enable](https://user-images.githubusercontent.com/37875464/38860624-4b82e780-4239-11e8-9fac-dab33be7e4ee.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
After performing further investigations, this seems to be a upstream issue due to a change occured in Nightly. After searching for regression window, I have found that this is caused by  [Bug 1446686](https://bugzilla.mozilla.org/show_bug.cgi?id=1446686).

**Comment by ghost** [comment]
Thanks for finding that upstream bug.  We're going to close this as we don't see it as a big deal.

**Comment by SoftVision-PaulOiegas** [comment]
Andreea filed an upstream issue [#1455269](https://bugzilla.mozilla.org/show_bug.cgi?id=1455269) for this behavior since it was reproducing also with AMO add-ons.  
Was triaged and marked as P2 by the add-ons devs. We'll recheck once it's fixed.
