### ISSUE TITLE
Remove News Feed

### ISSUE THREAD

**Issue by marniepw** [mozilla/testpilot#3512]
Do eeet. 

John, fill out details.

**Comment by SoftVision-PaulOiegas** [comment]
Wait what? Why?

![806c79e65040440fff1843be392945fa014a250bc09d168b2525289cbbb84d16](https://user-images.githubusercontent.com/17258026/38999367-4f47bd9c-43fa-11e8-85e9-81311be38799.jpg)

**Comment by SoftVision-PaulOiegas** [comment]
![i-didnt-delete-9xbegk](https://user-images.githubusercontent.com/17258026/39633260-1df47cb8-4fc0-11e8-85de-4437063dbbb5.jpg)
