### ISSUE TITLE
Add tests for addon / discussion

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#352]
Would be interested to see some prior art here.
- [ ] Unit tests
- [ ] integration tests
  cc/ @6a68 @lmorchard

**Comment by clouserw** [comment]
@meandavejustice  -- This doesn't really have a description so we're not sure what it is.  We're assuming not a blocker...

**Comment by lmorchard** [comment]
I _think_ this is about unit testing for the site addon? Could be about integration testing involving the add-on and Test Pilot site. We need both, at some point.

**Comment by meandavejustice** [comment]
updated description, not blocking

**Comment by ghost** [comment]
What we really need here are integration tests because the add-on pretty much just talks to other services (and other add-ons).  @pdehaan and @silne30 -- what are your recommendations for automating some integration tests?
