### ISSUE TITLE
The dev TxP add-on version wrongly updates to the production version

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3521]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile: `xpinstall.signatures.required` = `false`, testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Click on the big green "Install the Test Pilot Add-on" button and confirm the choice in the displayed dorhanger.
3. Navigate to "about:addons" in a new tab and switch to "Extensions" section.
4. Double click on the Test Pilot entry and observe the add-on version.
5. Click the "Settings" cog wheel button and chose "Check for Updates" option.
6. After check is performed, refresh the page and observe the TxP add-on version again.

**[Expected result]:**
- The TxP add-on version remains the same as the one installed from Dev server since it's the latest version.

**[Actual result]:**
- The TxP add-on wrongly updates to 3.0.0 version that seems to be the Production version since it lacks the details re-added in #3501. 

**[Notes]:**
- This issue occurs even without manually checking for updates since the browser does this automatically after a period of time. 
- Here is a screen recording of the issue: https://goo.gl/VCXLvM.

**Comment by marniepw** [comment]
@clouserw any concerns here before today's deploy to stage?

**Comment by ghost** [comment]
No, I think we should still deploy to stage, because that's cheap.  If the add-on changed (in an important way) in the last two weeks, we should get this fixed before it goes live though.

**Comment by ghost** [comment]
Looking at the commit history, I don't think anything important has changed in this sprint

**Comment by marniepw** [comment]
Sounds like it's not a huge issue, per @meandavejustice. In slack he said "we'll just need to update the addon version before pushing"

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue on Test Pilot dev server and the issue is no longer reproducible.
