### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by calvinarchil** [mozilla/testpilot#3526]
I can't view any of the site. it just says "Something went wrong" and no matter where I go on testpilot.firefox.com it shows the same error message and says to report it on GitHub.

**Comment by pdehaan** [comment]
@calvinarchil What browser/OS are you using?
I was unable to reproduce the error in Firefox Nightly, Firefox Beta, or Google Chrome (release channel) on macOS.

**Comment by johngruen** [comment]
@calvinarchil do you have resist fingerprinting enabled?

https://github.com/mozilla/testpilot/blob/master/docs/faq.md#why-is-test-pilot-telling-me-that-something-went-wrong
