### ISSUE TITLE
The "Install the Tes Pilot Add-on" green button is no longer displayed on experiment details page for a previously enabled experiment

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3530]
**[Affected versions]:**
- Firefox 59.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile: `xpinstall.signatures.required` = `false`, testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`
- Test Pilot and Notes add-ons were already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to "testpilot.dev.mozaws.net/experiments page".
2. Click the "Settings" button from top right and chose to "Uninstall Test Pilot" from the displayed menu. 3. Click the "Proceed" button displayed on the uninstall modal.
4. After redirected to "Homepage" click the "Notes" experiment card.
5. Observe the displayed buttons on the experiment details page left side. 

**[Expected result]:**
- The "Install the Test Pilot Add-on" green button is displayed under the experiment logo.

**[Actual result]:**
- There is no button for Test Pilot add-on installation on the page. The "Disable Notes", "Give Feedback" and "Your privacy" buttons are displayed.

**[Notes]**
- This seems to be an issue caused after the move of the page buttons on the left column from #3503 and the removal of the Promo section.
- Here is a screen recording of the issue: https://goo.gl/987BXb.

**Comment by dannycoates** [comment]
it's a feature ;)

**Comment by johngruen** [comment]
I think we could add the install TxP button back to the sidebar?

**Comment by dannycoates** [comment]
<img width="931" alt="screen shot 2018-05-09 at 9 51 15 am" src="https://user-images.githubusercontent.com/87619/39828115-cbefaaac-536e-11e8-81a5-307e0040bc51.png">

part of #3535

**Comment by SoftVision-PaulOiegas** [comment]
Uuu, looks sexy. But sadly, we have a couple of issues with it (#3541 and #3542) that I have logged separately so I can mark this as done.
