### ISSUE TITLE
Dev website uses wrong font across all its pages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3536]
**[Affected versions]:**
- Firefox 59.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile: `xpinstall.signatures.required` = `false`, testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to "https://testpilot.dev.mozaws.net" page.
2. Observe the font used all across the website.
3. Open a new tab and navigate to "https://testpilot.firefox.com page.
4. Compare the font used on both pages by switching between tabs. 

**[Expected result]:**
- Both the Dev and Production websites use the same font.

**[Actual result]:**
- The Dev website uses a different font than it should. 

**[Notes]**
- This issue reproduces on all the website pages and even if TxP add-on is installed or not.
- The Stage server is not affected which means the issue appeared after recent changes.
- Here is a screenshot of the issue:

![wrong font dev](https://user-images.githubusercontent.com/17258026/39757647-2f42e8a6-52d6-11e8-80ae-e88ab864d455.png)

**Comment by lmorchard** [comment]
Not sure why, but it looks like CSP is blocking loading of all the fonts

![capture](https://user-images.githubusercontent.com/21687/39770649-9b6d7cda-52bd-11e8-8642-53a88e1107cb.PNG)

**Comment by SoftVision-PaulOiegas** [comment]
Seems to be fixed on dev, verified both Windows and Mac OS. 👍

**Comment by SoftVision-PaulOiegas** [comment]
Issue is reproducing now on production. Reopening...

**Comment by ghost** [comment]
This might not have been an "https" problem at all.  Looks like we were missing semi-colons.  Danny added some in https://github.com/mozilla/testpilot/commit/b4aa6ec03d39423bf3950e1ebe64ab6456284eed but missed one.  I'll make a PR
