### ISSUE TITLE
[Experiment details] TxP install button ends into a wrong state and page shows a wrong error if you cancel add-on install while experiment is already enabled

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3541]
**[Affected versions]:**
- Firefox 59.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile: `xpinstall.signatures.required` = `false`, testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`
- Test Pilot and Notes add-ons were already installed on the same profile.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to "testpilot.dev.mozaws.net/experiments page".
2. Click the "Settings" button from top right and chose to "Uninstall Test Pilot" from the displayed menu.
3. Click the "Proceed" button displayed on the uninstall modal.
4. After redirected to "Homepage" click the "Notes" experiment card.
5. Click on "Install the Test Pilot Add-on" green button.
6. Click the "Cancel" button on the install doorhanger and observe the page behavior.

**[Expected result]:**
- An error message is displayed informing the user that Test Pilot could not be installed.
- The button returns from "installing..." state back to "Install the Test Pilot Add-on state.

**[Actual result]:**
- An error message is displayed but it wrongly states that Notes could not be enabled.
- The button wrongly returns to "Install test Pilot & Enable Notes" state like when Notes is not enabled.

**[Notes]**
- Here is a screen recording of the issue: https://goo.gl/9DXga8.

**Comment by dannycoates** [comment]
We don't have an error message for just the main addon failing so I went with the status quo of no error message and returning to the previous button state.

**Comment by SoftVision-PaulOiegas** [comment]
That was the right choice removing the error message for when the experiment is already enabled. And now the flow when only TxP needs install, correctly works. 👍 

However, I think we should have kept the error message for the complete flow when user makes the combo install. It seems right to display that Notes could not be enabled if one of the 2 installs fails or is canceled. I'll log something separate for this case since it was removed on this PR.

**Comment by SoftVision-PaulOiegas** [comment]
Here it is #3544.
