### ISSUE TITLE
[Experiment details] Add back the experiment enable error when installing both TxP add-on and experiment

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3544]
**[Notes]:**
- The error message was wrongly removed for both cases when installing TxP add-on alone and in combination with an experiment. We should keep the error for the case when in combination with an experiment.

**[Affected versions]:**
- Firefox 59.0.3 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile: `xpinstall.signatures.required` = `false`, testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to "testpilot.dev.mozaws.net" page.
2. Click on "Notes" experiment card and chose to "Install Test Pilot & Enable Notes".
3. Click the "Cancel" button on the TxP add-on install doorhanger.
4. Observe the page behavior. 

**[Expected result]:**
- The "Uh oh. Notes could not be enabled. Try again later." error message in black characters over yellow background is displayed.
- The button returns from "installing..." state back to "Install Test Pilot & Enable Notes" state.

**[Actual result]:**
- The button correctly returns to "Install test Pilot & Enable Notes" state but there's no error message for Notes not being enabled.

**[Additional Notes]**
- This initial removal of the message causes now to no longer show the error also when there is no internet connection.

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. Will make a PR in a day.

**Comment by SoftVision-PaulOiegas** [comment]
The issue si no longer reproducible. Verified on Windows 10 and Mac OS 10.13 using the latest Nightly Build (20180926) and checked on [en-US], and [de] locales.
