### ISSUE TITLE
"Install Test Pilot & Enable [experiment_name]" button is wrongly displayed on past experiment pages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3545]
[Affected versions]:
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisite and navigate to "https://testpilot.stage.mozaws.net.com" page.
2. Click the "View Past Experiments" button under the current available experiments.
3. Click one of the graduated experiment cards.
4. Observe the top part of the past experiment page.

[Expected result]:
- No Test Pilot install button is displayed.

[Actual result]:
- "Install Test Pilot & Enable [experiment_name]" button is displayed.

[Notes]:
- The issue is also reproducible if Test Pilot add-on is installed. The "Enable [experiment_name]" button is displayed on the past experiments page (beside Tab Center) and it seems that Voice Fill, Pulse, Snooze Tabs, Containers and Min Vid  experiments can successfully be installed.
- Here is a screen shot with the issue:
![past experiments](https://user-images.githubusercontent.com/19226534/39925821-d81e1552-5535-11e8-88c9-7396f4c5da14.gif)

**Comment by SoftVision-PaulOiegas** [comment]
Yep, the mobile version seems "OK" also. 😄 Managed to install TxP and Voice Fill. Sadly they were not working, Voice Fill just redirected me to Google.

![screenshot_20180511-171546](https://user-images.githubusercontent.com/17258026/39930266-ed17dc88-5542-11e8-9bcf-fb51271d20ee.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this and the issue is no longer reproducible on latest version of Test Pilot from dev and stage servers.
