### ISSUE TITLE
The "information" link in the "Telemetry and Browser Data" section from "Privacy" page wrongly redirects to a 404 page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3546]
[Affected versions]:
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisite and navigate to "https://testpilot.stage.mozaws.net.com/privacy" page.
2. Click the first "Learn More" button.
3. Click the "information" link.
4. Observe the behavior.

[Expected result]:
- You are redirected to the Telemetry docs from Github.

[Actual result]:
- You are redirected to a 404 page.

[Notes]:
- Here is a screen shot with the issue:
![information link](https://user-images.githubusercontent.com/19226534/39928773-e96af9a2-553e-11e8-8669-b3a00dd53430.gif)

**Comment by ghost** [comment]
PR to change the wording in the legal docs: https://github.com/mozilla/legal-docs/pull/1066/files

**Comment by ghost** [comment]
PR landed.  This is fixed in production.  -dev still has the old version.  I assume there is some kind of caching of packages there.  @lmorchard do you know?  This is included at https://github.com/mozilla/testpilot/blob/master/package.json#L29 with no pinning so I assume it just grabs the latest and greatest

**Comment by ghost** [comment]
This is fixed on -dev now too.  I'm closing this, although how it works is still a mystery.
