### ISSUE TITLE
[Android] "TxP & experiment enable" buttons wrongly displayed for Firefox experiments

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3547]
**[Affected versions]:**
- Firefox 60.0 and above

**[Affected Platforms]:**
- Android 7.0

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile: `xpinstall.signatures.required` = `false`, testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to "testpilot.dev.mozaws.net page.
2. Scroll down on the mobile page and observe the button displayed on the experiments cards. 
3. Click on on "Notes" experiment card in order to navigate to experiments details page.
4. Observe the available buttons on the top part of the page. 

**[Expected result]:**
- Step 2: "Learn More" button is correctly displayed on all experiments cards that are not supporting Android OS.
- Step 4: There is no button available for Android devices unless there is an Android experiment available.

**[Actual result]:**
- Step 2: "Get Started" button is wrongly displayed on all experiments cards on Android devices.
- Step 4: The "Install Test Pilot & Enable Notes" green button is wrongly displayed on Android devices.

**[Notes]**
- This issue is not reproducible on iOS devices.

![screenshot_20180514-155205](https://user-images.githubusercontent.com/17258026/39998671-7e1b6e68-578f-11e8-97ae-702c0169506e.png)

**Comment by dannycoates** [comment]
Are you sure this is a regression? There hasn't been any changes to the card button in months. What does production do?

**Comment by SoftVision-PaulOiegas** [comment]
@dannycoates Indeed, it seems to be something that we have for some times now. The production server looks the same when it comes to the card button. 
However, I'm sure that the button should look differently because it was one of my proposed enhancements to show "Learn More" button instead for unsupported platforms.

Still, when we fix this, we might want to take into consideration that we'll have cases when the "Get Started" button will need to show up instead. I'm referring to mobile applications. So we'll need to check for OS and display the right button depending on it.

**Comment by dannycoates** [comment]
To answer my own questions, Dave showed me prod on mobile ff android, the install button part is a regression that I'll fix asap, while 'Get Started' (still a bug, just not new) can be fixed later.

**Comment by SoftVision-PaulOiegas** [comment]
The "Install Test Pilot & Enable <experiment_name>" is no longer available on Android devices. tested with Samsung Galaxy S6 (Android 7.0).

@dannycoates we leave this open for the other problem or you want me to log something separately?

**Comment by dannycoates** [comment]
Added #3557 for the rest
