### ISSUE TITLE
Make it possible to show both Mobile OS icons for apps that support both

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3549]
**[Affected versions]:**
- Firefox 60.0 and above

**[Affected Platforms]:**
- Android 7.0

**[Prerequisites]:**
- Following 4 prefs have been set or added on a new profile (on each device): `xpinstall.signatures.required` = `false`, `testpilot.env` = `dev`, `extensions.webapi.testing` = `true` and `extensions.install.requireBuiltInCerts` = `false`

**[Steps to reproduce]:**
1. Open Firefox browser on Windows / MacOS and navigate to "testpilot.dev.mozaws.net page.
2. Scroll down on the page and click on on "Dev Example" experiment card.
3. Observe the buttons displayed  on the left side of the page.
4. On an Android device, open the Firefox browser and navigate to the same experiment details page.
5. Observe the displayed buttons on the page.

**[Expected result]:**
- Step 3: Two buttons displayed, one for Firefox experiment install and one for the iOS mobile experiment download.
- Step 5: No buttons displayed since the Android device is not compatible with any of them.

**[Actual result]:**
- Step 3: Two buttons displayed, one for Firefox experiment install and one for the iOS mobile experiment download.
- Step 5: iOS App Store download button wrongly displayed on Android.

**[Notes]**
- The iOS download button should not be displayed on Android and vice versa.

![screenshot_20180514-170516](https://user-images.githubusercontent.com/17258026/40003575-5c64ea08-579c-11e8-8b80-98e257d966c8.png)

**Comment by johngruen** [comment]
We actually don't have the ability to display both icons right now.

**Comment by clouserw** [comment]
Let's only show the matching platform, not both

**Comment by clouserw** [comment]
We talked about this -- it might be confusing to see the iOS button on an android device, but it also communicates that the app is available on iOS (this is assuming it's only iOS and not Android).  Otherwise we don't really communicate what platform it works on.

So...it's a little awkward, but they all seem like a compromise.  We're going to close this, but open to recommendations from designers. :)
