### ISSUE TITLE
Alternative client-side metrics implementation

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#355]
The current approach to exposing the idea town metrics endpoint doesn't work for non-SDK (non-jpm) addons, like universal search. Loading code in non-SDK code is [really weird](), and it's hard to see how providing a library could solve the problem for all possible experiments.

Possible approaches:
- xhr to an endpoint (secured via CORS allow-origin headers, rather than user cookies)
- postmessage from experiments to the idea town addon, where the idea town addon manages sending to the server
- expose a metrics function via a `window.navigator` API on the chrome window; @6a68 can help with implementation (seems like iterating chrome windows & assigning something on navigator should do it).

**Comment by meandavejustice** [comment]
:+1: from me.
ping @lmorchard for input.

**Comment by jaredhirsch** [comment]
@lmorchard How do you want to proceed? I kinda think the navigator API seems nicest for experiments, but I'm fine with whatever.

I can implement whatever's needed on the idea town side, as I'm already working on metrics for search.

**Comment by lmorchard** [comment]
Not sure, haven't really had a chance to think much about it yet... We've used `navigator` as a means to pass data from the Idea Town addon to the Idea Town website client code. 

But, does that work addon-to-addon? What `navigator` reference is shared between addons? Is there a `postMessage` mechanism between addons?

**Comment by lmorchard** [comment]
To clarify, what I think we _were_ stumbling toward is something like this:
1. An interesting interaction happens in the **Universal Search iframe**
2. **Universal Search iframe** sends a message up to the **Universal Search addon**
3. **Universal Search addon** uses [an **Idea Town code library**](https://github.com/lmorchard/idea-town/tree/master/addon-api) that:
   1. finds an Idea Town login cookie and
   2. sends an auth'd POST to the **Idea Town server**
4. **Idea Town server** stores some data to measure the happening.

What I'm thinking needs to happen is something like this flow:
1. An interesting interaction happens in the **Universal Search iframe**
2. **Universal Search iframe** sends a message up to the **Universal Search addon**
3. **Universal Search addon** sends a message over to the **Idea Town addon**
4. **Idea Town addon** sends a POST request to the **Idea Town server**
5. **Idea Town server** stores some data to measure the happening.

While postMessage or navigator sound like channels usable for iframe -> addon, I don't think that works addon -> addon. We leave the land of web content APIs when it's addon-to-addon.

Maybe [`nsIObserverService`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIObserverService) and the [`sdk/system/events` wrapper](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/system_events) are interesting avenues for addon-to-addon messaging? Not sure if that helps in the WebExtension case, though, unless we can get an extension to the extension API that supports intra-firefox messaging.

**Comment by jaredhirsch** [comment]
Yup, the new flow sounds good to me.

At some point, I think someone in IRC told me that you can't register new nsIObserver topics restartlessly. But I can't find any docs around that now, and I seem to be able to fire and receive from arbitrary made-up topics in a browser toolbox debugger window. So yeah, that should work, and it's much nicer than polluting global namespace. :+1:

I don't know if WebExtension addons will be powerful enough to wind up in idea town, so we can probably not worry about that for now.

**Comment by lmorchard** [comment]
> Yup, the new flow sounds good to me.

Cool!

> I can implement whatever's needed on the idea town side, as I'm already working on metrics for search.

@6a68 Are you still good with implementing both sides, using nsIObserver messaging as the go-between and having the Idea Town addon send the metrics requests? Don't want to drop the ball if you'd like me to work on it :)

**Comment by lmorchard** [comment]
Also thinking that the [`addon-api` module](https://github.com/mozilla/idea-town/tree/master/addon-api) could be pulled into the Idea Town addon proper (rather than maintained as a shared module) if the addon takes responsibility for all metrics pings and the interface for experiments is just nsIObserver events.
