### ISSUE TITLE
[iOS][Accesibility] Night Mode doesn't work on Test Pilot website

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3554]
**[Affected versions]:**
- Firefox 60.0 and above

**[Affected Platforms]:**
- iOS 11.x

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to "testpilot.dev.mozaws.net page.
2. Open the browser "Hamburger" menu and chose to "Enable Night Mode".
3. Navigate trough the pages and observe how the Night Mode changes the website.

**[Expected result]:**
- All the website pages have the colors inverted on Night Mode.

**[Actual result]:**
- Nothing changes on TxP website when Night Mode is activated, except the experiment logo from the "Experiment details" page. 

![image-1](https://user-images.githubusercontent.com/17258026/40059010-98010794-585b-11e8-823a-623e2cab621e.jpg)

**Comment by ghost** [comment]
This is already a dark site, so it already works at night :)  (also, this isn't a priority for us)

**Comment by SoftVision-PaulOiegas** [comment]
Good one 🤣
