### ISSUE TITLE
[release] 2018-05-10 on stage

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3555]
Hi guys,

We have finalized running our Full Functional test suite on the Staging server and here are the testing results:

### **Legend** ###
&#x26D4;   - blocker issue
&#x1F4D5; - major issue
&#x1F4D9; - normal issue
&#x1F4D2; - minor issue
&#x1F4D7; - enhancement

## New Issues ##
1. #3544 - &#x1F4D9; [Experiment details] Add back the experiment enable error when installing both TxP add-on and experiment
2. ~~#3545 - &#x26D4; "Install Test Pilot & Enable [experiment_name]" button is wrongly displayed on past experiment pages~~
3. #3546 - &#x1F4D9; The "information" link in the "Telemetry and Browser Data" section from "Privacy" page wrongly redirects to a 404 page
4. #3547 - &#x26D4; [Android] "Get Started" and "TxP & experiment enable" buttons wrongly displayed for Firefox experiments (**partially Fixed**)
5. ~~#3548 - &#x1F4D9; [Mobile] The new experiment bar logo from experiment details page breaks the UI on mobile devices~~
6. #3549 - &#x1F4D7; [Enhancement][Mobile] The Android Market / Apple App Store button should be displayed based on OS
7. #3554 - &#x1F4D9; [iOS][Accesibility] Night Mode doesn't works on Test Pilot website

## Known Issues ##
1. #3520 - &#x1F4D2; [about:addons] Environment selector wrongly jumps back to "Local" no matter what environment si selected and saved

## Based on testing results we would suggest the next course of actions: ##
- Considering that both the blockers were addressed, but only the fix for one of them was re-deployed on stage server, we suggest to merge the fix for the #3547 on stage too before deploying to production.
- Since #3546 is a legal issue and already has a PR opened, we suggest to merge it if it's OK, before deploying to production.

**Comment by SoftVision-PaulOiegas** [comment]
@marniepw @clouserw The remaining blocker (#3547) issue was merged also on stage server and it's no longer reproducible there anymore.

However, the #3546 PR for legal document change was not even merged on dev server yet. So, the decision is on you guys, depending on how important you consider this issue.

**Comment by marniepw** [comment]
@clouserw @SoftVision-PaulOiegas I think it's ok to release w/out the legal fix, although not ideal; I wouldn't call it a blocker. Thoughts?

**Comment by ghost** [comment]
Not a blocker.

**Comment by ghost** [comment]
@SoftVision-PaulOiegas since Danny is out, I'll plan on pushing what is on stage to production with you tomorrow morning.  if @meandavejustice is up early, y'all can do it earlier if you want.

**Comment by SoftVision-PaulOiegas** [comment]
@wresuolc Sounds like a good plan if @meandavejustice can do it! 👍 I'll Ping him on slack.

**Comment by ghost** [comment]
This is live
