### ISSUE TITLE
Complete new experiments content

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3562]
Need to:
- [ ] Verify IDs and update URLS
- [x] Add correct YouTube links
- [ ] Add correct social media images
- [ ] Verify discourse URLs
- [x] Verify survey URLs
- [x] Make Color a featured experiment

All should be done after #3561 is in master

**Comment by johngruen** [comment]
Can't verify discourse urls yet, will take a best guess

**Comment by pdehaan** [comment]
I think YouTube urls were fixed in #3600
