### ISSUE TITLE
[Featured Experiment] Experiment enable error is wrongly displayed on two rows on languages with longer words

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3564]
**[Affected versions]:**
- Firefox 61.0b6 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Test Pilot repo was cloned locally and server started.
- A Developer Edition browser profile was setup for Local testing as in the "Quickstart" document.
- Browser language was set to German [de] from Options > General > Language.
- Notes experiment was set as featured from "notes.yaml" file found in the repo clone.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to 'https://example.com:8000/" page.
2. Click on the "Install Test Pilot & Enable Notes" button.
3. Click the "Cancel" button on the Test Pilot add-on install doorhanger.
4. Observe the error message displayed over the yellow banner.

**[Expected result]:**
- The error message is correctly displayed on a single row and fits the designed space.

**[Actual result]:**
- The error message is wrongly displayed on two rows and is not entirely visible.

**[Notes]:**
- This behavior occurs on languages that exceed the designed space for the error, meaning that German could be not the only one affected.

![screen shot 2018-05-21 at 12 05 12](https://user-images.githubusercontent.com/17258026/40314528-66f39a34-5d21-11e8-98df-5c0c9c46689f.png)

**Comment by ShivangiKakkar** [comment]
@SoftVision-PaulOiegas @meandavejustice Hey! I would like to work on this issue. 
What are the possible ways to resolve this issue? (One possible is putting an check on `max-width`)

**Comment by ShivangiKakkar** [comment]
@SoftVision-PaulOiegas May I ?

**Comment by SoftVision-PaulOiegas** [comment]
@ShivangiKakkar Of course, be my guest. 😉

**Comment by ShivangiKakkar** [comment]
> @SoftVision-PaulOiegas @meandavejustice Hey! I would like to work on this issue.
> What are the possible ways to resolve this issue? (One possible is putting a check on `max-width`)

@meandavejustice adjustment of `font-size` percentage in the overall HTML class or should I fix with max-width? Would you please guide me a bit through this? Thanks :)

**Comment by SoftVision-PaulOiegas** [comment]
The issue no longer reproduces. Verified on Mac OS 10.13.6 using a local copy in order to move a Firefox experiment in featured area since we have Lockbox (mobile) by default.
