### ISSUE TITLE
[Featured Experiment] Experiment enable error is wrongly displayed on left when attempting to install it together with TxP 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3565]
**[Affected versions]:**
- Firefox 61.0b6 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Test Pilot repo was cloned locally and server started.
- A Developer Edition browser profile was setup for Local testing as in the "Quickstart" document.
- Notes experiment was set as featured from "notes.yaml" file found in the repo clone.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to 'https://example.com:8000/" page.
2. Click on the "Install Test Pilot & Enable Notes" button and Click "Cancel" button on the Test Pilot add-on install doorhanger.
3. Observe the yellow banner with the error message position..
4. Chose again to install TxP add-on and confirm adding it this time.
5. Click the "Cancel" button for Notes install doorhanger.
6. Observe again the error message position

**[Expected result]:**
- In both cases the yellow banner with the error message is displayed on the top middle part of the section. 

**[Actual result]:**
- Step 3: The yellow banner with the error message is wrongly displayed on the top left part of the section.
- Step 4: The yellow banner with the error message is correctly displayed on the top middle part of the section.

![screen shot 2018-05-21 at 17 58 11](https://user-images.githubusercontent.com/17258026/40315045-fa2f1110-5d22-11e8-8a0d-81b0078a9ef5.png)

**Comment by knrt10** [comment]
Hi!! I would like to work on this issue. Would you please direct me to the file to be changed.

**Comment by ShivangiKakkar** [comment]
@SoftVision-PaulOiegas 
Hey, I am new to contributions in Mozilla. Can I work on this issue if someone is not working on it currently?

**Comment by SoftVision-PaulOiegas** [comment]
Oh man, I missed the first comment somehow. Sorry for that!
@ShivangiKakkar or @knrt10  sure, any of you can take it and work on it if you consider having the necessary skills.

**Comment by knrt10** [comment]
@ShivangiKakkar if you want you can do it.

**Comment by ShivangiKakkar** [comment]
@knrt10 Yeah! if you don't mind :)

**Comment by ShivangiKakkar** [comment]
Hey, @SoftVision-PaulOiegas 
I am facing some issues regarding this:
1.) In `Prerequisites` I have set `notes.yaml` -> `is_featured` -> `true`. Then notes experiment was shown on my home screen.
2.) Then when I click on the `Install Test Pilot & Enable Notes`, nothing happens and I get `304` in the terminal log.
3.)I didn't get this part: 'Click "Cancel" button on the Test Pilot add-on install doorhanger.'
Can you please help me out? 
Is there anything I am missing?

**Comment by SoftVision-PaulOiegas** [comment]
I'm just a QA for the project, but I can try to help if none of the devs jumps in.

How did you cloned the repo locally? 
I use the next commands `git clone https://github.com/mozilla/testpilot && cd testpilot && npm install && cd addon && npm install && npm run package && cd .. && npm start"

**Comment by SoftVision-PaulOiegas** [comment]
hey @ShivangiKakkar I can try to help if none of the devs jumps in, I'm the QA for the project.

In order to clone, build and run it locally I make the next steps:
1. I use the next line of commands in a new terminal (MacOS): `git clone https://github.com/mozilla/testpilot && cd testpilot && npm install && cd addon && npm install && npm run package && cd .."
- This way you have also the Test Pilot add-on built, because you need to install Test Pilot add-on first in order to try to enable the featured experiment. 
- If the add-on build fails with above commands, I don't think I can help you to figure out why, but maybe one of the devs can. It works perfectly on Mac OS, but I have encountered issues while trying to build it on Windows or Linux.
2. I create a new profile on Firefox Developer edition that has the next prefs added/set in `about:config` page:
- Boolean `extensions.webapi.testing` with `true` value
- Boolean `extensions.install.requireBuiltInCerts` with `false` value
- Boolean `xpinstall.signatures.required` with `false` value.
3. Run in a new terminal with sudo `echo '127.0.0.1 example.com' | sudo tee -a /etc/hosts`
4. Return to the main terminal and run `npm start`.
5. Also, please edit `lockbox.yaml` file and edit `is_featured` to `false` and after edit `side-view.yaml` and edit `is_featured` to `true`. 
- You need to remove Lockbox from featured (currently) and move "Side View" experiment to featured. Notes received an update and it no longer behaves like in the initial bug.
6. Follow the initial bug steps for Side View experiment featured.

Let us know if this helps you and thanks for involvement on the issue. :)

**Comment by ShivangiKakkar** [comment]
Hey, @SoftVision-PaulOiegas  
It did help :) Thanks a lot for the detailed explanation!

**Comment by SoftVision-PaulOiegas** [comment]
Glad it helped. I can apply now for junior developer role. 😆 Kddin'

**Comment by SoftVision-PaulOiegas** [comment]
Works like a charm! Thanks @ShivangiKakkar for your contribution! 🥇 👍

**Comment by ShivangiKakkar** [comment]
@SoftVision-PaulOiegas Thank you so much!!  :')
