### ISSUE TITLE
[Featured Experiment] Fix improper string concatenation in renderOneClickInstallButton function of MainInstallButton component

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3566]
Edit: We are [concatenating two different localized strings in MainInstallButton](https://github.com/mozilla/testpilot/blob/ff322ca8bd5182a3d043a0977ea5cc9a7975c712/frontend/src/app/components/MainInstallButton/index.js#L104) that are part of the same sentence by placing two elements with localized content next to each other and we shouldn't be doing that.

**[Affected versions]:**
- Firefox 61.0b6 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Test Pilot repo was cloned locally and server started.
- A Developer Edition browser profile was setup for Local testing as in the "Quickstart" document.
- Notes experiment was set as featured from "notes.yaml" file found in the repo clone.
- Browser language was set to French [fr] from Options > General > Language.
- Test Pilot add-on was already installed. 

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to 'https://example.com:8000/" page.
2. Observe the green "Activer Notes" button string.
3. Navigate to Experiment details" page and observe the blue "Activer Notes" button.

**[Expected result]:**
- Both buttons are displaying "activer" word with capital "A". 

**[Actual result]:**
- The "Featured Experiment" section wrongly displays "activer" word with lower case "a".

![screen shot 2018-05-21 at 12 07 05](https://user-images.githubusercontent.com/17258026/40315768-f8ae9a16-5d24-11e8-8ee2-67303241b7c0.png)

**Comment by lmorchard** [comment]
Oof, this looks like it's from [a year-old update to the fr locale from Pontoon](https://github.com/mozilla/testpilot/commit/e1994159186d609a6beceef2b89d7defc41f0979). Not sure we ever really came up with a way to review those

**Comment by flodolo** [comment]
cc @TheoChevalier and @goofy-bz

**Comment by TheoChevalier** [comment]
From my understanding of those two strings, they can sometimes be concatenated: https://pontoon.mozilla.org/fr/test-pilot-website/app.ftl/?search=oneClickInstall&string=162055

And become “Install Test Pilot & Enable {$title}”

If this is **not** the case, I will capitalize oneClickInstallMajorCta. However if it’s the case, we need a different string for the button in the screenshot above.

**Comment by flodolo** [comment]
He has a point. As it stands, this is not really localizable
https://github.com/mozilla/testpilot/blob/ff322ca8bd5182a3d043a0977ea5cc9a7975c712/frontend/src/app/components/MainInstallButton/index.js#L104

**Comment by lmorchard** [comment]
Yeah, now that I look at it, that is a bad arrangement. We can't just concatenate strings like that in the component - the `oneClickInstallMinorCta` and  `oneClickInstallMajorCta` strings in that button should be combined into the same single string for l10n to allow for reordering words & whatever else differs between locales. We might also have to drop / rethink the major / minor styling there to accommodate that

**Comment by lmorchard** [comment]
Tweaked the issue title to highlight the change in what needs doing here

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. Will make a PR in a day or two.

**Comment by SoftVision-PaulOiegas** [comment]
This seems to have been fixed on French language. Performed testing on local using Mac OS 10.13.
