### ISSUE TITLE
The "Go to Color" button from Color experiment page is not working

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3569]
**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed. 

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisite.
2. Navigate to "https://testpilot.dev.mozaws.net/experiments/color" page.
3. Click the first "Go to Color" button.
4. Observe the behavior.

**[Expected result]:**
- You are redirected to the Color website.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- The issue is also reproducible even if Test Pilot add-on or Color experiment is installed.
- Here is a screen recording of the issue:
![go to color](https://user-images.githubusercontent.com/19226534/40487485-fa529ca6-5f6c-11e8-95b4-0b2e1211e96c.gif)

**Comment by lmorchard** [comment]
Looks like [color.yaml](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/color.yaml) has no `web_url` - guessing it should be https://color.firefox.com unless there's some GA crud we need to add

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and is no longer reproducible on Test Pilot dev version. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
