### ISSUE TITLE
The "Give Feedback" button from the Side View experiment page does not redirect to the correct survey

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3570]
**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = stage" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".
- Test Pilot add-on was already installed. 
- Have Side View enabled.

**[Steps to reproduce]:**
1. Open Firefox with the profile from prerequisite.
2. Navigate to "https://testpilot.dev.mozaws.net/experiments/side-view" page.
3. Click the "Give Feedback" blue button.
4. Observe the behavior.

**[Expected result]:**
- You are redirected to the Side View survey.

**[Actual result]:**
- You are redirected to survey Not Found page.

**[Notes]:**
- The issue is also reproducible if you click the "Feedback" button from the Side View experiment card.
- The issue is also reproducible if you click the "Take a quick survey" button after you disable the experiment.
- Here is a screen recording of the issue:
![side view survey](https://user-images.githubusercontent.com/19226534/40487630-72744ab8-5f6d-11e8-8a47-e50637a5ad06.gif)

**Comment by johngruen** [comment]
Fixed

**Comment by johngruen** [comment]
Had to file this bug here: https://github.com/mozilla/side-view/pull/263

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue on Test Pilot dev server and is no longer reproducible. You are redirected to the Side View survey, but it seems that it is completed. However, this issue is already tracked in Side View repository at:
https://github.com/mozilla/side-view/issues/255
