### ISSUE TITLE
Remove traces of restartRequired

### ISSUE THREAD

**Issue by fzzzy** [mozilla/testpilot#3571]
restartRequired hasn't been used in a very long time. It can be removed.

**Comment by Vimal-Raghubir** [comment]
I am interested in working on this issue. Just to be clear the `restart.isRequired` portion is still required but the `restartRequired` isn't correct?

**Comment by fzzzy** [comment]
@Vimal-Raghubir I'm pretty sure everything having to do with restarting is no longer needed.
