### ISSUE TITLE
Idea-town dev site looks single column in latest FF Nightly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#358]
### Steps to reproduce:

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/12151528/72d80a6e-b464-11e5-81f4-a49eb3148f05.png)
1. Log into http://idea-town-dev.elasticbeanstalk.com/home
2. Navigate to an experiment details page, a lahttp://idea-town-dev.elasticbeanstalk.com/experiments/universal-search
### Actual results:

![idea_town](https://cloud.githubusercontent.com/assets/557895/12151581/caa94abe-b464-11e5-9942-bd62328937fa.png)
**Figure 1:** Home page.

---

![idea_town](https://cloud.githubusercontent.com/assets/557895/12151600/db5702e8-b464-11e5-8dbf-e11256c12bc7.png)
**Figure 2:** Details page.

---

**NOTE:** and because **6a68 asked this in IRC, here's my browser dimensions (1/2 screen width on a 24" Dell via my rMBP):

``` js
console.log(document.documentElement.clientWidth) // 1279px
console.log(document.documentElement.clientHeight) // 866px
```

**Comment by pdehaan** [comment]
This may be Nightly specific (but appear later in other channels).
I got this installed/working today in FF Beta 44.0b9.

**Comment by meandavejustice** [comment]
I'm now seeing this is Firefox Dev edition

**Comment by pdehaan** [comment]
I too can reproduce in today's FF DevEdition 46.0a2. It _was_ working a few minutes ago in FF DevEdition 43.x (before I upgraded).

Looks like something probably changed w/ FlexBox or something between FF43 and FF46 that is breaking our layout.

---

**UPDATE:** Definitely looks like something that changed in FF46. Didn't see anything interesting in https://www.mozilla.org/en-US/firefox/46.0a2/auroranotes/, but I haven't trolled through ["the complete list of changes in this release"](https://bugzilla.mozilla.org/buglist.cgi?j_top=OR&f1=target_milestone&o3=equals&v3=Firefox%2046&o1=equals&resolution=FIXED&o2=anyexact&query_format=advanced&f3=target_milestone&f2=cf_status_firefox46&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&v1=mozilla46&v2=fixed%2Cverified&limit=0) via Bugzilla yet. I'm guessing whatever it is, it's riding the trains and will hit the other channels soon enough.

![test_pilot_-_experiments_and_spike_in_push_intermittent_failures_-_pdehaan_mozilla_com_-_mozilla_mail](https://cloud.githubusercontent.com/assets/557895/12737233/9adaf5a6-c90b-11e5-878a-7e434f81b410.png)

![test_pilot_-_experiments_and_spike_in_push_intermittent_failures_-_pdehaan_mozilla_com_-_mozilla_mail](https://cloud.githubusercontent.com/assets/557895/12737239/adbfc3cc-c90b-11e5-903d-74f00897a40a.png)

![test_pilot_-_experiments_and_spike_in_push_intermittent_failures_-_pdehaan_mozilla_com_-_mozilla_mail](https://cloud.githubusercontent.com/assets/557895/12737254/d12f189e-c90b-11e5-92e4-2f5488bd96fd.png)

**Comment by johngruen** [comment]
I haven't had time to investigate this, but i'm using the same flex mixin in another project and it looks fine in nightly...maybe we;re not closing a div somewhere? that can lead to this sort of chaos

**Comment by pdehaan** [comment]
Hhmm, I tested the full generated HTML in https://html5.validator.nu/ and it only came up with 4 errors and 2 warnings.
Only potentially legit error was this:

>  Error: The element `header` must not appear as a descendant of the `header` element.
> From line 19, column 11; to line 19, column 18
>          `<header>`↩     

But even when I changed that nested `<header>` to a `<div>` via devtools, it still renders as a odd vertical column.

**Comment by johngruen** [comment]
@pdehaan @meandavejustice basically i used 'default' when i should have used 'initial' or 'row' as the flex-direction value. PR incoming

**Comment by meandavejustice** [comment]
Than
