### ISSUE TITLE
Implement SMS integration

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3582]
The rough plan:

- Load the page normally, as it is today
- If the user clicks the button to get the app:
  - Show a spinner while doing a background ping to https://www.mozilla.org/country-code.json  (special note: may need to modify our CSP to allow this)
  - If the user is in the US, show the input box offering phone number or email.  Otherwise, only show email.
  - submit directly to basket
  - submission button should have a GA event as well

Designs are at https://github.com/mozilla/testpilot/issues/3509

**Comment by pmac** [comment]
There's also the [Mozilla Location Service](https://location.services.mozilla.com/api). It might be the better and more "ready to go" solution for GeoIP.

**Comment by meandavejustice** [comment]
basket is used for email via `subscribeToBasket` see it's uses [here](https://github.com/mozilla/testpilot/search?q=subscribeToBasket&unscoped_q=subscribeToBasket)

as far as SMS goes, the url at https://www.mozilla.org/country-code.json will need some permission changes as I'm unable to request via `fetch`.

https://location.services.mozilla.com/api suggests using the HTML5 geolocation api for webapps/sites which seems to be overkill for what we need here.

For actual sms signup, I'm not seeing docs on it [here](http://basket.readthedocs.io/newsletter_api.html#news-subscribe), but found [bugzilla #1173780](https://bugzilla.mozilla.org/show_bug.cgi?id=1173780) which indicates that the functionality exists. @pmac Would you be able to shine some light on that?

**Comment by pmac** [comment]
> as far as SMS goes, the url at https://www.mozilla.org/country-code.json will need some permission changes as I'm unable to request via fetch.

Yes. I'll have to add CORS support to the endpoint. We'll have to discuss if this is the best course since it would add an external dependency to what was previously a purely internal interface. I'm happy to do this but I think Mozilla Location Services mentioned below would be the best and most supported option for you.

> https://location.services.mozilla.com/api suggests using the HTML5 geolocation api for webapps/sites which seems to be overkill for what we need here.

It suggests that, but does have a full [Geo API](https://mozilla.github.io/ichnaea/api/region.html). You'll just need to request an API key from them. But this works fine for me even without one:

```bash
$ curl -X POST https://location.services.mozilla.com/v1/country
{"country_name": "United States", "country_code": "US"}
```

> For actual sms signup, I'm not seeing docs on it here, but found bugzilla #1173780 which indicates that the functionality exists. @pmac Would you be able to shine some light on that?

My apologies. I have it on my list to flesh-out that documentation this week. Here is the summary which I hope will suffice until then:

```
URL: https://basket.mozilla.org/news/subscribe_sms/
POST requests only
Request content-type: application/x-www-form-urlencoded
Response content-type: application/json
Required Parameters:
 - mobile_number: the phone number
Optional Parameters:
 - country: 2 character country code (default: us)
 - lang: 2 - 5 character language code (default: en-US)
 - msg_name: ID of the message to send (default: SMS_Android)
 - optin: 'Y' if the user wishes to receive other SMS from us in future (default: N)
```
