### ISSUE TITLE
Something fishy with the deploys (-dev is down)

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#3586]
Trying to load https://testpilot.dev.mozaws.net/ shows a white page and 404s on two resources:

https://testpilot.dev.mozaws.net/static/app/vendor.26bf1b94.js
https://testpilot.dev.mozaws.net/static/app/app.4ddd1acf.js

**Comment by lmorchard** [comment]
Rebuilt the last master run on CircleCI and it looks like the dev site is okay now.
