### ISSUE TITLE
Switch away from gulp-in-docker as the default recommended local dev process

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#359]
It seems like we are no longer using docker for the front-end code, but the README isn't quite up to date. There's also a hacky docker script I landed in /bin that probably isn't useful to keep around any longer.

**Comment by lmorchard** [comment]
FWIW, I'm still using Docker for the front-end code. It's always worked great for me, but it seems like I'm the only one. Not sure why.

Maybe this issue should expand from a deceptively simple README update to giving up on gulp-in-docker for local dev altogether? (Needs some things rearranged in docker-compose.yml to make that case the default, etc)

**Comment by jaredhirsch** [comment]
I actually think it might make sense to figure out the gulp-docker weirdness. This will probably come up in a future experiment, since gulp is pretty popular and docker-compose is the way ops likes to do things. I'll try to get gulp-docker working, and file a bug if I run into one. I can also fire up an old windows laptop and try the install process there / file bugs.

**Comment by meandavejustice** [comment]
@6a68 Another thing to remember is that sourcemaps for `node_modules` do not work when running from withing the container

**Comment by meandavejustice** [comment]
I'll also add that I think it would be easier to support our client code running outside of the containers.

**Comment by meandavejustice** [comment]
_bump_

**Comment by ghost** [comment]
Les & Dave are going to dig into this later this week.  It will definitely consist of improving documentation and will probably revolve around some fancy npm commands. /cc @lmorchard @meandavejustice

**Comment by johngruen** [comment]
@lmorchard i bet we can close this too

**Comment by lmorchard** [comment]
Yup! Closing.
