### ISSUE TITLE
The footer links are wrongly displayed on the Test Pilot page when the "Developing Test Pilot?" warning is displayed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3597]
[Notes]:
- The issue is reproducible on Test Pilot stage and dev website if no prefs are stet.

**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox with a new clean profile.
2. Navigate to "https://testpilot.dev.mozaws.net/.
3. Observe the footer links.

**[Expected result]:**
- The footer links are correctly displayed.

**[Actual result]:**
- The footer links are wrongly displayed at the middle of the page.

**[Additional Notes]:**
- Here is a screen shot of the issue:
![footer links](https://user-images.githubusercontent.com/19226534/40786296-66e97002-64f3-11e8-8b75-1c1b4cf9af30.png)

**Comment by SoftVision-PaulOiegas** [comment]
Footer is now correctly displayed on narrow pages. 👍 Verified on MBP with Mac OS 10.12.
