### ISSUE TITLE
Ensure clever UI flourishes do not distract from Idea Town.

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#360]
Specifically at issue here is the helicopter blocking users from accessing FxA sign-up. We're going through a branding evaluation so all of this stuff is in flux anyway, but let's make sure Idea Town isn't too cute for its own good.

**Comment by jaredhirsch** [comment]
:+1: Related: http://xenon.stanford.edu/~lswartz/paperclip/

**Comment by johngruen** [comment]
@6a68 chill, coppy

**Comment by pdehaan** [comment]
Not sure if this discussion is "sign up" specific, or if we're also planning on removing dear old Choppy from the 404 page: http://idea-town-dev.elasticbeanstalk.com/404

![idea_town](https://cloud.githubusercontent.com/assets/557895/12159510/aedd9320-b497-11e5-9887-4586a7bfa746.png)

**Comment by johngruen** [comment]
This seems a bit silly...closing in favor of refactoring UI for TxP
