### ISSUE TITLE
Badge icon wrongly displayed before experiments launch

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3608]
**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have and old Firefox profile with an old Test Pilot add-on version installed.  

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and observe the Test Pilot toolbar button.
2. Navigate to `https://testpilot.firefox.com` page and observe the available experiments.
3. Navigate to `about:addons#extensions` page and click the settings button (cog wheel) from top right.
4. Click on "Check for Updates" option and wait for the TxP add-on to update.
5. Observe again the toolbar button.
6. Click the toolbar button and observe the available experiments.

**[Expected result]:**
- Nothing changes on the toolbar button or website after add-on is updated.

**[Actual result]:**
- Step 1: The default Test Pilot spaceship button is displayed with no notification. 
- Step 2: Notes and Send experiments are the only one available.
- Step 5: The toolbar button wrongly displays a notification on the Test Pilot toolbar button. 
- Step 6: No new experiment is displayed, just the old Notes and Send ones.

**[Notes]**
- The badge is also displayed on the toolbar button for each first install of TxP add-on.
- Here is a screen recording of the issue: https://goo.gl/iTrURS.

![badge](https://user-images.githubusercontent.com/17258026/40976424-d17c1a96-68d6-11e8-97ce-598a072c2e55.png)

**Comment by johngruen** [comment]
I believe the offending section is here on line 144: 

```
  const newExperiments = (experiments || []).filter(experiment => {
    const dt = new Date(experiment.modified || experiment.created).getTime();
    return dt >= clicked;
  });
```

There needs to be a check if `dt <= Date.now()` which should return `false`

**Comment by johngruen** [comment]
@meandavejustice we need to fix this before lockbox content gets merged in
