### ISSUE TITLE
The Mozilla Facebook social network button is missing from the new footer

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3610]
**[Affected versions]:**
**- There are differences also on the displayed links, but for that I'm not sure if it was intended or not.**

**[Affected versions]:**
- Firefox 60.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to `https://testpilot.firefox.com page.
2. Scroll down to the new footer section.
3. Observe the social network buttons for `Firefox` designed area from the footer.

**[Expected result]:**
- Twitter, Facebook and YouTube social network buttons are displayed under the other links. 

**[Actual result]:**
- The Facebook social network button is missing.

![34758955-4b660ad2-f614-11e7-8bdc-73e67a88a456](https://user-images.githubusercontent.com/17258026/40989778-90dd772a-68f7-11e8-8443-2f01f38a4cd9.png)

**Comment by meandavejustice** [comment]
Do we want to link to facebook? We've publicly been taking a break from facebook over data leaks and the many other reasons to not engage on facebook.

From the Firefox facebook page:
```
Dear 18 million people we’ve had the opportunity to interact with over the past several years here:

We’re taking a break from Facebook.

At Mozilla we champion platforms and technologies that are good for the web and good for the people that use it.
We stand up for transparency and user control because they make the web healthier for us all.

That’s why we are pressing pause on any Facebook activity. Mark Zuckerberg has just promised to improve Facebook’s settings and make them more protective, which is a start! Please do that! But we can’t help but think we’ve heard it before, so we’re still going to wait and see what materializes before we resume spending our ad dollars or time here.

IN THE MEANTIME:
If you need support for Firefox, you can find us here: https://support.mozilla.org/en-US/

If you’re someone who tweets, you’ll find us here: https://twitter.com/firefox
```

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice I've logged this because it wasn't matching the designs, but mostly because every Mozilla website was displaying it too in the footer. However, looking today on some of the official pages, I've seen it disappeared from there too.
I'm totally fine to leave it undisplayed if the team agrees.

<img width="1280" alt="screen shot 2018-06-13 at 22 53 02" src="https://user-images.githubusercontent.com/17258026/41393887-af667190-6f5c-11e8-8a2e-140c127b8853.png">
