### ISSUE TITLE
Firefox Color

### ISSUE THREAD

**Issue by swingwolf** [mozilla/testpilot#3615]
Don't run. Rune when firefox (60.0.2) start up and immediately all FF color's settings disappear.

**Comment by bittin** [comment]
Works fine in Firefox 61 Beta, used this at work now since it was released
:)

**Comment by SoftVision-PaulOiegas** [comment]
Works for me on 60.0.2 even after updating from 60.0.1. However, this repository is the one for Test Pilot website and not for Color experiment. 
Can you please log your issue offering more details in the [Color repository](https://github.com/mozilla/FirefoxColor/issues)?

**Comment by SoftVision-PaulOiegas** [comment]
Thanks @swingwolf!
Closing this as the user cloned the issue in the Color repo.
