### ISSUE TITLE
Wrong footer displayed for "Privacy", "Terms" and "About" pages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3616]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to `https://testpilot.firefox.com page.
2. Scroll down to the new footer section.
3. Click on the `Privacy` or `Terms` links from bottom left or `About us` link from "About" section.
4. Scroll down to the page footer if needed and observe it.

**[Expected result]:**
- The same footer as on Homepage is correctly displayed on all 3 mentioned pages

**[Actual result]:**
- A footer that resembles to the old one is wrongly displayed.

![terms wrong footer](https://user-images.githubusercontent.com/17258026/41114994-bfa6fad4-6a8e-11e8-9037-4481f3eaf094.png)

**Comment by johngruen** [comment]
let's see if we can just render the normal footer here.

**Comment by lmorchard** [comment]
https://github.com/mozilla/testpilot/commit/a2d85d74aa114310ba2d20c8de703c78b15e8a56

**Comment by SoftVision-PaulOiegas** [comment]
The right footer is now displayed on all pages. 👍
