### ISSUE TITLE
Test Pilot "Privacy" page footer is wrongly displayed in the middle of the page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3626]
**[Notes]:**
- While this was OK when we had no footer background, now it looks pretty awkward to have a black stripe splitting the page.

**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to `https://testpilot.firefox.com page.
2. Scroll down to the new footer section.
3. Click on the `Privacy` text button from bottom left side of the page.
4. Observe how page footer is displayed on the Test Pilot "Privacy" page.

**[Expected result]:**
- The footer is displayed on the bottom of the page and it's not constrained by the amount of page content.

**[Actual result]:**
- The footer is wrongly constrained by page content and it's displayed in the middle of "Privacy" page.

![image](https://user-images.githubusercontent.com/17258026/41528848-f4cefeb0-72f3-11e8-9129-c6023676315d.png)

**Comment by lmorchard** [comment]
https://github.com/mozilla/testpilot/commit/a2d85d74aa114310ba2d20c8de703c78b15e8a56

**Comment by SoftVision-PaulOiegas** [comment]
This is still broken on Local & Dev. We need to display that footer always at the page bottom and not at the end of the text.
![image](https://user-images.githubusercontent.com/17258026/42825815-88d99e90-89eb-11e8-9a3d-dcdfa3908f05.png)

**Comment by meandavejustice** [comment]
cc/ @johngruen as I know he has a clever way to get this to work.

We've made a couple commits trying to fix this, and spent a lot of time digging around on stack exchange etc.. to no avail :sob:

**Comment by SoftVision-PaulOiegas** [comment]
OMG, a miracle has occurred!!! Finally a fix for it. 😆
