### ISSUE TITLE
Removed bolding in fine print links in Featured Experiment area

### ISSUE THREAD

**Issue by sevaan** [mozilla/testpilot#3637]
The links in the fine print in the featured experiment area are bolded, and should not be.

![image](https://user-images.githubusercontent.com/473531/41864043-982b252a-7876-11e8-9569-1bcd0379870a.png)

**Comment by SoftVision-PaulOiegas** [comment]
@sevaan This seems fixed on both Dev and Stage for the featured experiment section. Verified on Local too for every experiment that we currently have and seems ok.  I'll close this as fixed.

One thing though, I've seen one issue that does not affects us for now. the Send experiment has an incomplete legal string when featured. Same issue happened with Lockbox and seems related to how the privacy notice is implemented (#3667).
However, this could affect us only if the Send app will be released and featured.

![screen shot 2018-07-03 at 14 53 38](https://user-images.githubusercontent.com/17258026/42218580-c879a57e-7ed1-11e8-8b19-de152c1495f7.png)
