### ISSUE TITLE
Access control for experiment addons

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#364]
It's possible for users who are not opted into an experiment to download the addon XPI and install it. For security, scaling, and privacy reasons we should look into some access controls such that the addons work only for authenticated users who are accepted into an experiment - i.e. currently everyone, but in the future participation may be limited by factors like # of users, etc.

Initially this issue was about blocking access to XPI downloads, but a better approach might be to have experiments check in with the main addon and refuse to initialize if the user is not authenticated and given access to the experiment.

**Comment by lmorchard** [comment]
A concern that occurred to me: We install addons via the AddonManager, and it does the download. How do we pass along site auth? Maybe a pre-signed URL in S3? Temporary token in the XPI URL we hand off to AddonManager?

**Comment by meandavejustice** [comment]
I have quite a few questions around this myself. @lmorchard Let's discuss this sometime in the next couple of weeks

**Comment by clouserw** [comment]
Why the strict concern for access restriction?  Are we super concerned about unauthorized users?  If we have 10000 users through the regular channel and 100 find the add-on on their own, is that a problem?

**Comment by chuckharmston** [comment]
> Why the strict concern for access restriction? Are we super concerned about unauthorized users? If we have 10000 users through the regular channel and 100 find the add-on on their own, is that a problem?

Yes, because we require that they sign an additional TOS that gives us more power for metrics collection.

**Comment by lmorchard** [comment]
Off the top of my head, some stuff that came up chatting with @nchapman and other status meetings:
- Users opted into Test Pilot will have agreed to certain terms that general users haven't - e.g. around privacy, etc - and we would like to try to restrict access to the XPIs to that audience
- Some experiments may only support a certain scale at first - e.g. because the prototype is backed by services running on a cheap PaaS - and we want to restrict to invited participants for that particular experiment. (This also implies a participation limit on experiments, which I thought we had an issue open for but...)
- The experiment addons will be semi-integrated with the main Test Pilot addon, at least at first. They'll communicate with the Test Pilot site for metrics & feature flipping. So, installing an experiment XPI separately from Test Pilot may end up with them working in an unexpected or broken way.

**Comment by clouserw** [comment]
Privacy/TOS can be added to the normal fields on AMO for the small percentage of users who discover it that way.  I don't think this is any different than any other add-on on AMO that does things with user data.

Scale is legit, but if we're not advertising the add-ons it seems like it would be a very small percentage of people who would stumble across them on AMO.

Just feels like this is added complexity which we might not need.

**Comment by lmorchard** [comment]
Could be we don't need it, but it's being asked for - so we should be at least note why we don't have it for when it gets asked for again :)

**Comment by chuckharmston** [comment]
> Privacy/TOS can be added to the normal fields on AMO for the small percentage of users who discover it that way. I don't think this is any different than any other add-on on AMO that does things with user data.

Except that users aren't discovering or installing through AMO; they're doing that through the Test Pilot website.

**Comment by lmorchard** [comment]
> The experiment addons will be semi-integrated with the main Test Pilot addon, at least at first. They'll communicate with the Test Pilot site for metrics & feature flipping. So, installing an experiment XPI separately from Test Pilot may end up with them working in an unexpected or broken way.

Though, having said this, experiments should ideally be built in a way that lets them function when Test Pilot integration is unavailable - i.e. how they'll function if eventually released for real.

**Comment by clouserw** [comment]
> > Privacy/TOS can be added to the normal fields on AMO for the small percentage of users who
> > discover it that way. I don't think this is any different than any other add-on on AMO that does
> > things with user data.
> 
> Except that users aren't discovering or installing through AMO; they're doing that through the 
> Test Pilot website.

That seems pretty straight forward to add a link to a privacy policy.  I'm just saying they either do it through the normal, "I'm logged in, and going down the normal happy path to discover tests" or they found another way around.  It just seems like putting the right messaging somewhere is easier than trying to enforce authentication.

If we have an experiment that really needs auth we could make it part of the bootstrap of the test add-on to check-in with the test pilot add-on. (random idea)

**Comment by lmorchard** [comment]
> If we have an experiment that really needs auth we could make it part of the bootstrap of the test add-on to check-in with the test pilot add-on. (random idea)

Yeah, I wonder if that's fine enough for this issue. Don't care about XPI downloads, just don't complete initialization if the experiment doesn't get a thumbs up from the Test Pilot addon - and that can be based on whatever we want. Kind of smells like DRM, but less for copy protection and more for keeping us out of trouble.

**Comment by clouserw** [comment]
I'd expect the enforcement of it to be pretty rare - maybe only in a particularly sensitive data area or where scale would be a concern.  For, say, testing tabs on the side of your browser?  Eh, any skewing of random installs would be within the margin of error.  (he assumes without actually knowing...)

**Comment by lmorchard** [comment]
Tweaked the issue description a bit, hopefully makes it a bit more general rather than literally about stopping downloads

**Comment by jaredhirsch** [comment]
To add some context not mentioned so far: when the search addon was first happening, there was a lot of interest in tightly controlling downloads, because we didn't want to make search partners nervous.

I believe this fed into the idea of controlling both who could access addons (for instance, moco/mofo only), as well as how many people could access addons (to make it clear there wouldn't be any revenue impact whatsoever).

**Comment by ghost** [comment]
Not on our roadmap anymore. Thanks!
