### ISSUE TITLE
Add mobile button to featured experiment page

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3642]
Here's the spec for mobile featured experiments.

https://mozilla.github.io/testpilot-assets/Test_Pilot_Website/01_Measurements/Mobile_Featured_Experiments/

Please DO NOT include the black ios button, just do the green "Send me the App" button. Also, Make the string  use the `mobileDialogLaunchButton` string.

Clicking this button should trigger the SMS/email modal.

**Comment by devinreams** [comment]
To elaborate, I think in other words this means: don't show the standard "Install Test Pilot and Enable X" button but instead the mobile-specific CTA.

![firefox_test_pilot](https://user-images.githubusercontent.com/49511/41921943-4609b09e-7921-11e8-930b-2bfb3809535f.png)

(was about to file an issue but found this one, please correct me if wrong)
