### ISSUE TITLE
[SMS] Inconsistent validation of the telephone numbers in the send experiment link modal

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3645]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Scroll down to the available experiments and click the "Dev Example" card.
3. Click on the "Send App Link to Device" blue button from top left of the page.
4. Enter a number with `+` sign for country code (eg `+40744111222` where `+` represents `00` and `0040` is the code for Romania).
5. Click the "Send me the Download Link" button and observe the modal behavior.
6. Replace the `+` sign with `00` and click again the button.
7. Replace again the `00` with `+` sign and observe the modal behavior.
8. Click again the button and observe the modal behavior.

**[Expected result]:**
- An error is displayed, informing the user to "Enter a valid phone number or email:" for each of the numbers entered above.

**[Actual result]:**
- Step 5: Nothing happens and there is no error message displayed on the modal.
- Step 6: The error message is correctly displayed.
- Step 7: The error message is removed like the entered number is accepted.
- Step 8: The error message is no correctly displayed also for numbers with `+` sign.

**[Notes]:**
- Here is a screen recording of the issue: https://goo.gl/t1itUY

**Comment by KhushilMistry** [comment]
I think UI of this page has been changed. So this issue is no more producible. @SoftVision-PaulOiegas Can you check this ?

![screenshot 2018-10-16 at 10 06 23 pm](https://user-images.githubusercontent.com/17615573/47032331-c0349480-d18f-11e8-85cb-92101e841f13.png)

**Comment by SoftVision-PaulOiegas** [comment]
Yes, the UI has changed a bit, but the issue is still present for Lockbox experiment for example. But you will need a VPN client (try [Windscribe](https://addons.mozilla.org/en-US/firefox/addon/windscribe/) from Mozilla add-ons) to fake location to US since the phone number modal part only shows up if you have IP location in US.

Here are the steps:
1. After you have your VPN active, open Firefox browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Click on "Get the App" Lockbox green button from Featured Experiment section.
3. In the displayed modal, enter a number with `+` sign for country code (eg `+40744111222` where `+` represents `00` and `0040` is the code for Romania).
4. Click the "Send me the Download Link" button and observe the modal behavior.
5. Replace the `+` sign with `00` and click again the button.
6. Replace again the `00` with `+` sign and observe the modal behavior.
8. Click again the button and observe the modal behavior.

Here is also a screen recording of the issue: https://goo.gl/Vsp2ea.

**Comment by KhushilMistry** [comment]
Cool Thanks. Will make a PR in a day or so.
