### ISSUE TITLE
Change prod endpoint to ideatown.services?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#365]
From IRC this morning, it looks like we're using the following stage/prod URLs. Not sure what in our code/addon may need to be changed, but filing this just so I can remember the final/proposed URLs in the future when I undoubtedly forget these URLs:
- https://ideatown.stage.mozaws.net/
- https://ideatown.services.mozilla.com/

Here are some rough results from searching this GitHub repo for [:mag: "ideatown.firefox.com"](https://github.com/mozilla/idea-town/search?utf8=%E2%9C%93&q=ideatown.firefox.com):
1. [./addon/dev-prefs.json:4](https://github.com/mozilla/idea-town/blob/4d6da17280f528b9369b55ff33be9e314641cce6/addon/dev-prefs.json#L4) -- need to add stage URL and replace the ideatown.firefox.com?
2. [./addon-api/package.json:37-38](https://github.com/mozilla/idea-town/blob/4d6da17280f528b9369b55ff33be9e314641cce6/addon-api/package.json#L37-L38)
3. [./addon/package.json:41](https://github.com/mozilla/idea-town/blob/f4d129f3782b89044a0f0ebfd562919f35bf759c/addon/package.json#L41) -- update "production" with "ideatown.services.mozilla.com"?
4. [./addon/index.js:31](https://github.com/mozilla/idea-town/blob/f4d129f3782b89044a0f0ebfd562919f35bf759c/addon/index.js#L31) -- update to "ideatown.services.mozilla.com"?
5. [./.ebextensions/00-environment.config-dist:34](https://github.com/mozilla/idea-town/blob/2cfe24c9d18b2a5382005caebef695cd8e5e313a/.ebextensions/00-environment.config-dist#L34)

**Comment by meandavejustice** [comment]
Should probably be rolled in to (or at least referenced) the renaming work coming soon.
