### ISSUE TITLE
[Featured experiment] The Android store button and message is wrongly displayed in "Send App Link to Device" button modal when setting "ios" as experiment platform

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3650]
**[Notes]:**
- This issue was observed while testing the changes from #3647 PR.

**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Local clone the branch for "Send app link to device" button in the featured experiment section for mobile experiments.
- Perform the setup in order to run the build locally and start the server.
- Edit the "color.yaml" file by change the  `platforms` attribute from `web` to `ios` and save the file

**[Steps to reproduce]:**
1. Open Firefox Developer edition browser and navigate to `https://example.com:8000/ page.
2. Click the green "Send App Link to Device" button displayed in the featured experiment section.
3. Observe the elements on the top part of the displayed modal.

**[Expected result]:**
- Since the platform was set to `ios`, the modal correctly mentions on "Download Color from the iOS App Store." message and displays the "Download on the App Store" button on the top part.

**[Actual result]:**
- The modal wrongly mentions "Download Color from the Google Play Store." message and displays the "Get it on Google Play" button on top.

**[Additional notes]:**
- Here is a screenshot of the issue:

![screen shot 2018-06-27 at 15 57 15](https://user-images.githubusercontent.com/17258026/41980947-70646748-7a30-11e8-8281-0c9660021b06.png)

**Comment by johngruen** [comment]
@meandavejustice ^

**Comment by meandavejustice** [comment]
This is essentially the same as #3652, if `ios_url` is set the modal behaves correctly. I recommend closing as we don't code in the frontend against yaml files being mis filled out. The way to handle this would be to have some yaml validation. ie: 
``` js
if (yamlExperimentDataAsJSON.platforms.includes('ios') && !yamlExperimentDataAsJSON.ios_ur) {
  throw new Error('')
}

**Comment by SoftVision-PaulOiegas** [comment]
Totally agree! Also, I've been verifying with the ios_url/android_url and it perfectly works. 👍
