### ISSUE TITLE
[Experiment details page] The iOS message and App Store button are wrongly displayed on the send link modal when "android" platform is set

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3652]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Local clone the branch for "Send app link to device" button in the featured experiment section for mobile experiments.
- Perform the setup in order to run the build locally and start the server.
- Edit the "dev-example.yaml" file by change the  `platforms` attribute from `ios` to `android` and save the file

**[Steps to reproduce]:**
1. Open Firefox Developer edition browser and navigate to `https://example.com:8000/ page.
2. Scroll down to the available experiments and click on the "Dev Example" card.
3. Observe the store button displayed on the experiment controls section of the page.
4. Click the "Send App Link to Device" blue button from experiment controls section.
5. Observe the message and store button displayed on the modal.

**[Expected result]:**
- Step 3: Android Google Play button is correctly displayed on the experiment controls section.
- Step 5: Android Google Play button and message are correctly displayed on the send link modal.

**[Actual result]:**
- Step 3: Android Google Play button is correctly displayed on the experiment controls section.
- Step 5: iOS button and message are wrongly displayed on the send link modal.

**[Additional notes]:**
- Here is a screenshot of the issue:

![screen shot 2018-06-27 at 18 26 56](https://user-images.githubusercontent.com/17258026/41983902-f73b6fe4-7a37-11e8-9039-679432a37823.png)

**Comment by SoftVision-PaulOiegas** [comment]
Also, if you set both platforms in the yaml file, you get both of them on the experiment controls area, but still get only iOS on the modal. 
Maybe this should be taken into consideration for future experiments that will have both the mobile platforms.

**Comment by meandavejustice** [comment]
This issue is caused by not setting the `android_url` while having the `ios_url` set. We don't usually add code in the app to defend against the yaml files being mis-filled out.

>Also, if you set both platforms in the yaml file, you get both of them on the experiment controls area, but still get only iOS on the modal.
Maybe this should be taken into consideration for future experiments that will have both the mobile platforms.

This is a separate issue, we should plan to address this scenario in the future. cc/ @johngruen

**Comment by lmorchard** [comment]
FWIW: https://github.com/mozilla/testpilot/issues/1308 for linting YAML in CI

**Comment by SoftVision-PaulOiegas** [comment]
Totally agree! Also, I've been verifying with the ios_url/android_url and it perfectly works. 👍
