### ISSUE TITLE
test pilot prgrofram

### ISSUE THREAD

**Issue by nycookie** [mozilla/testpilot#3657]
i can't get out of ur "experiment" which left me unable to log into my fvoret site.  get error meesages. server issues frm diff sites

**Comment by nycookie** [comment]
my email is:  nycookie1@outlook.com

**Comment by SoftVision-PaulOiegas** [comment]
Hi @nycookie and thanks for your report. That's unfortunate and we would like to hear more about your issue with Color experiment. If you have some time, can you please file an issue explaining the encountered problems in [Color GitHub repository](https://github.com/mozilla/FirefoxColor/issues)?

Regarding exiting the experiments, you can follow the next steps:
1. Navigate to https://testpilot.firefox.com page.
2. Scroll down on the page until you reach the available experiments cards.
3. Left click the one that you want to remove.
4. After redirected, click the grey "Disable <experiment_name>" button on the left side of the experiment page.

Also, if you want to quit the Test Pilot program:

5. Click the "Settings" button on top right side of the page.
6. Select "Uninstall Test Pilot" option and click "Proceed" on the displayed pop up.

Hope this helps.
