### ISSUE TITLE
integration test breakage caused by now building the addon for dev

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3660]
We may need to build 2 addons, one "local" for integration tests and one "dev" for pushing to the dev site

**Comment by ghost** [comment]
Les had an idea to just change the hosts file.  Let's try it!

**Comment by meandavejustice** [comment]
We've tried changing the hosts file to point to the dev url (`https://testpilot.dev.mozaws.net/`). This also gives us the advantage of testing the actual dev addon instead of the local build.

It appears that the reason it's not passing now is because of the port number. I'm going to try and see if I can set the port number to 80 for this build in circleci to solve it.

**Comment by clouserw** [comment]
This is still being investigated.  Let's call this `size:L` and if it takes longer than that, let's stop and regroup.

**Comment by meandavejustice** [comment]
Just got some feedback from @jrbenny35 on the pull request. I'm going to leave the size at `large` for now since it will probably be a bit time consuming to get these tests passing. Hoping to have them passing by the end of the week.

**Comment by meandavejustice** [comment]
https://github.com/mozilla/testpilot/pull/3828#issuecomment-419461778

**Comment by clouserw** [comment]
This is blocked on having a macbook delivered to @meandavejustice .  Expect delivery this week.
