### ISSUE TITLE
If featured platform is mobile, mobile store button should be displayed if viewed on mobile device

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3670]
Similar to what happens on the experiment details page. We should not now the `Get the App` Modal. Instead, we should show the appropriate mobile store icon

**Comment by SoftVision-PaulOiegas** [comment]
Button was added, but I've found 2 issues with it, that I've logged separately. In my opinion it should not be displayed on Android (#3716). And also, the button wrongly overlaps the "More Experiments" overlay button (#3717).
