### ISSUE TITLE
"Get the app" modal only displays one mobile platform even when experiment has two available

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3672]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Local clone the master Test Pilot branch. 
- Perform the setup in order to run the build locally and start the server as in [quickstart ](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md)doc.
- Edit the "lockbox.yaml" file by adding the `android` one to the existing `ios` one and save the file.
- Edit the "lockbox.yaml" file by adding the `android_url:` with a link to a Google Play store app and save the file. 

**[Steps to reproduce]:**
1. Open Firefox Developer edition browser and navigate to `https://example.com:8000/ page.
2. Click the "Get the App" green button for Lockbox featured experiment.
3. Observe the displayed modal message and buttons.
 
**[Expected result]:**
- The message of the modal is oriented for both the platforms and both the iOS and Google Play market buttons are available.

**[Actual result]:**
- Only one market button displayed and message oriented for only one platform in the displayed modal.

**[Notes]:**
- Here is a screenshot of the issue: 

![screen shot 2018-07-02 at 16 52 10](https://user-images.githubusercontent.com/17258026/42168714-6a7155b0-7e1a-11e8-9ef3-6332c9d6cf97.png)

**Comment by kgeorgiou** [comment]
Would something like the image below be acceptable? 

![3672-preview](https://user-images.githubusercontent.com/4765455/42432215-796249b0-8317-11e8-92ce-f17b77dfc7c4.png)

I'd like some feedback on:
- The wording. (e.g. Is it ok for the platforms to be joined with " or the "?)
- Should the platforms appear in any particular order? 
- Spacing, alignment, etc

Thanks.

**Comment by johngruen** [comment]
@kgeorgiou i think we will need two separate buttons on the main page. @youwenliang per our discussion eariler this week, we can track UX for multi-device experiments here.

**Comment by youwenliang** [comment]
Here's what Ryan had for the design:
https://mozilla.invisionapp.com/share/68OIGU9F42T#/screens
https://mozilla.invisionapp.com/share/3QOIGUL2S4R#/screens

I think it's good for now. One thing I would change is to make the two buttons in different colors.
@johngruen what do you think?

like this:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/8919308/46934220-80838500-d089-11e8-8933-9f31c4dd9dcc.png">

**Comment by SoftVision-PaulOiegas** [comment]
The functionality was implemented and works as requested. verified on local using Mac OS 10.13 machine.
However it seems that we have an issue on the buttons color that I've filled separately in #3925 so I won't need to reopen this.
