### ISSUE TITLE
Side view same on both monitors

### ISSUE THREAD

**Issue by carliskj** [mozilla/testpilot#3673]
When using side view I would like it if i could have two separate side views on both monitors for ultimate multitasking because now if I open a side view it comes up on the other screen too and If i close it on one screen it closes on both.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @carliskj and thanks for your report. However, this is the Test Pilot repository and not the Side View one. In order to have a developer respond to your request, can you please file this on the [Side View repository](https://github.com/mozilla/side-view/issues) instead? Thanks!
