### ISSUE TITLE
experiment.modified = undefined

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3678]
just noticed this, and it turns out we no longer track experiment.modified anywhere even though we're still trying to represent experiments as modified on the ExperimentRowCard components. We should bring this back.

**Comment by johngruen** [comment]
Crazily, if you add a modified field directly to yaml, it actually works...i guess we could resolve this issue by documenting this!

**Comment by lmorchard** [comment]
Yeah, I think it drives the "Just Updated" display on experiments. Used to be auto-updated by the Django CMS. Not sure why it isn't documented, but I don't think we ever took out the code to use it

**Comment by johngruen** [comment]
no, i want to tho...i'll take care of this looks like there's a bit of missing CSS too

<img width="203" alt="screen shot 2018-07-02 at 9 11 32 pm" src="https://user-images.githubusercontent.com/3323249/42182002-25816a30-7e3d-11e8-97eb-03dd5626b615.png">

**Comment by johngruen** [comment]
<img width="229" alt="screen shot 2018-07-02 at 9 22 17 pm" src="https://user-images.githubusercontent.com/3323249/42182301-0d98703e-7e3e-11e8-90a6-8431948f7e1a.png">

**Comment by johngruen** [comment]
found the culprit
