### ISSUE TITLE
[Experiment details] Web experiments button SVGs are forbidden (403) on Dev server

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3683]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false", "extensions.webapi.testing = true", "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Scroll down to the available experiments and click on "Color" or "Send" experiment card.
3. Observe the "Go to Color" / "Go to Send" button elements from experiment controls section.
 
**[Expected result]:**
- Both experiment buttons contain the "Go to <experiment_name>" string preceded by a globe image (white or black).

**[Actual result]:**
- Both experiment buttons correctly contain the string, but the globe image is just a placeholder.

**[Notes]:**
- Inspecting the Network console, it seems that both images are forbidden (403).
- Here is a screenshot of the issue: 

![403 button image](https://user-images.githubusercontent.com/17258026/42217598-78c5bf48-7ece-11e8-9f29-876f09010fa0.png)

**Comment by lmorchard** [comment]
FWIW, a 403 on S3 is basically a 404 with how we have things configured right now on dev. So I think this means that the .svg is missing. I suspect this will be an issue with hashed / non-hashed image filenames after assets got moved around in recent commits

**Comment by lmorchard** [comment]
I can try taking a look at this

**Comment by SoftVision-PaulOiegas** [comment]
Web experiment SVGs are now correctly displayed on the buttons of both experiments. Verified on Windows, MacOS, Android and iOS. 👍
