### ISSUE TITLE
[Mobile] Newsletter sign up success message is not focused after signing up with valid email

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3685]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- Android 7.0 - 8.0
- iOS 11.0.1

**[Prerequisites]:**
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false", "extensions.webapi.testing = true", "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox mobile browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Scroll down to the Newsletter section at the bottom and tap the text field.
3. Enter a valid email address and check the legal checkbox.
4. Tap the "Sign Up Now" button and observe the page behavior.
 
**[Expected result]:**
- The form is replaced by a success message and the view is automatically scrolled for the message to be fully visible.

**[Actual result]:**
- The success message is displayed but it is not focused.

**[Notes]:**
- The user needs to scroll up to find out that the sign up was successful.
- Here is a screen recording of the issue: https://goo.gl/AHvyNe.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using Test Pilot dev website and the issue is no longer reproducible. The view is automatically scrolled for the message to be fully visible. Tested on Android 7.0 and iOS 11.4.1.
