### ISSUE TITLE
Bookmarks Manager

### ISSUE THREAD

**Issue by rob-drigues** [mozilla/testpilot#3686]
Favor Manager (bookmarks) is having problems. The Favorites Bar is completely unstructured just below the URL Search Box

**Comment by SoftVision-PaulOiegas** [comment]
Hey @rob-drigues and thanks for your report. However, the terms you specify are not ringing any bells in relation with Test Pilot platform. Can you be more specific about your issue? 

Or if it's not related to Test Pilot or any of its experiments, but it does with the Firefox browser, maybe you should file a new issue in the browser [Bugzilla page](https://bugzilla.mozilla.org/enter_bug.cgi).

**Comment by rob-drigues** [comment]
Thanks for your attention PaulOiegas.
