### ISSUE TITLE
Test Pilot Dev is Blank

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3699]
Some errors appear in the console

```
Public-Key-Pins: The site specified a header that did not include a matching pin.[Learn More] testpilot.dev.mozaws.net
Public-Key-Pins: The site specified a header that did not include a matching pin.[Learn More] experiments.164365d5.css
Public-Key-Pins: The site specified a header that did not include a matching pin.[Learn More] app.574765b1.css
Loading failed for the <script> with source “https://testpilot.dev.mozaws.net/static/app/vendor.21390d24.js”. testpilot.dev.mozaws.net:6
Loading failed for the <script> with source “https://testpilot.dev.mozaws.net/static/app/app.28dce94e.js”. testpilot.dev.mozaws.net:8
Public-Key-Pins: The site specified a header that did not include a matching pin.[Learn More] stars@2x-ff27d84ea5509355e481a86232e6744c.png
Public-Key-Pins: The site specified a header that did not include a matching pin.[Learn More] favicon.ico 
```

**Comment by devinreams** [comment]
@johngruen I _do_ see the `Public-Key-Pins` errors but _only_ one `Loading failed for <script>` (ad_status.js) error. The rest of the vendor and app JS loads and works for me:

<img width="1552" alt="screen shot 2018-07-05 at 9 58 10 am" src="https://user-images.githubusercontent.com/49511/42334206-f2c7844a-8039-11e8-88ea-05801574b762.png">

**Comment by lmorchard** [comment]
> Loading failed for the <script> 

When you see this, it's nearly always our usual dev deployment issue. Hit rebuild on CircleCI to fix.

Edit: To elaborate, you can [go here to the workflows page](https://circleci.com/gh/mozilla/workflows/testpilot/tree/master) and hit "Rerun from Beginning" on the latest commit and hopefully that fixes it. I just did that, so we'll see if it's the usual

**Comment by lmorchard** [comment]
FWIW, the public-key-pins error has been there for a very long time, and I think that's because our SSL cert on dev is not included in the list of hashes in the headers we deploy

Edit: [Filed this issue to capture the problem](https://github.com/mozilla/testpilot/issues/3703) - to be clear, this warning is *not* breaking the dev site and fixing it will not improve that situation
