### ISSUE TITLE
Allow jpegs to be imported via webpack

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3709]

**Comment by lmorchard** [comment]
FWIW, I don't think this is a general issue - jpegs work fine on my machine and in CircleCI. It's an error that came up on @johngruen's machine, so I think it's an issue specific to macOS or @johngruen's machine.
```
Error: Module build failed: Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
 Referenced from: /Users/jgruen/Repos/testpilot/node_modules/mozjpeg/vendor/cjpeg
 Reason: image not found
   at Promise.all.then.arr (/Users/jgruen/Repos/testpilot/node_modules/execa/index.js:231:11)
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)
```
Seems like a weird error, since the image was actually there

**Comment by devinreams** [comment]
I think it's a "dyld and macOS" thing:

- https://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-loaded
- https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s

I haven't looked into it much further..

**Comment by devinreams** [comment]
I had the same problem. After running `brew reinstall libpng` the `start` command worked for me.

**Comment by johngruen** [comment]
Same fix WFM. Closing.
