### ISSUE TITLE
Link text is in English in localized page for Lockbox

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#3715]
This is how it currently looks for Italian (bad…)
https://testpilot-l10n.dev.mozaws.net/experiments/firefox-lockbox

![schermata 2018-07-06 alle 12 34 02](https://user-images.githubusercontent.com/3644868/42374673-2b63fb14-8119-11e8-9a3e-8453725f55dc.png)

cc @devinreams

**Comment by flodolo** [comment]
Worth noting that all other experiments don't have links, I wonder if that's a known issue.

**Comment by devinreams** [comment]
Thanks @flodolo. Given the constrains of the experiments YAML and front-end display, what do you think is a good approach to making this better?

One idea, not perfect, would be for us to remove the link from “here” on both instances so it can be translated, and then add the actual URL (as a hyperlink) after. For example:

>...puoi creane uno utilizzando aqui:
>[https://lockbox.firefox.com/faq.html#how-do-i-get-my-firefox-saved-logins-into-firefox-lockbox](https://lockbox.firefox.com/faq.html#how-do-i-get-my-firefox-saved-logins-into-firefox-lockbox)

**Comment by flodolo** [comment]
> Thanks @flodolo. Given the constrains of the experiments YAML and front-end display, what do you think is a good approach to making this better?

IMO this looks like a bug, and we should try to figure out what's causing it (disclaimer: I'm going to PTO in a few hours, and back on the 16th, so I won't be able to help).

For example, it works for [sideviewLegalnotice](https://github.com/mozilla/testpilot/blob/master/locales/en-US/experiments.ftl#L175)

Maybe it's the presence of the `href` causing it?

It would be enough to test changing

```
If you do not have an account set up, get started <a href="https://lockbox.firefox.com/faq.html#how-do-i-get-my-firefox-saved-logins-into-firefox-lockbox">here</a>
```

to 

```
If you do not have an account set up, get started <a>here</a>.?
```

**Comment by flodolo** [comment]
> For example, it works for sideviewLegalnotice

And this is likely a bad example, seems it seems to be used in JS :-\ I'm not sure if we have links coming from YAML files. 

Is the Lockbox experiment going to be visible only for en-US users? Otherwise, those sections look really awful in localized pages.

**Comment by flodolo** [comment]
Not sure if @stasm has ideas on what could be causing only the links to show up in English.

**Comment by stasm** [comment]
> Given the constrains of the experiments YAML and front-end display, what do you think is a good approach to making this better?

How is YAML used for this content? I don't remember exactly how Test Pilot displays the descriptions of experiments.

The need to include link anchors in the translations predates the solution built into more recent versions of `fluent-react`, called [React overlays](https://github.com/projectfluent/fluent.js/wiki/React-Overlays). There's a custom-written components called [`LocalizedHtml`](https://github.com/mozilla/testpilot/blob/master/frontend/src/app/components/LocalizedHtml.js). Is this component involved here?

**Comment by flodolo** [comment]
Any update?

**Comment by devinreams** [comment]
The workaround plan from here is:

1. re-write the Firefox Account paragraph so the "saved logins" and "here" are not hyperlinked and just have one URL at the end of the paragraph linking to the Lockbox website (not in an anchor tag with English)
2. re-write the Android paragraph similarly so it ends with just a URL (not an anchor tag with English)
2. remove the last paragraph (that this is limited to English and certain countries)
3. bump the l10n prefix so it can be re-reviewed and translated better

Does anyone have any concerns or alternative approaches to work around this before we submit those changes as a PR?

**Comment by clouserw** [comment]
That sounds like the right thing to do.  Thanks @devinreams
