### ISSUE TITLE
[Android] Download on the App Store button is wrongly displayed on Firefox for Android

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3716]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- Android 7.0 - 8.0

**[Prerequisites]:**
- [Android] The "extensions.webapi.testing = true" Boolean pref was added on a new profile.

**[Steps to reproduce]:**
1. Open Android Firefox mobile browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Observe if there is a mobile platform download button displayed for Lockbox featured experiment.

**[Expected result]:**
- There is no platform download button displayed on Android since Lockbox is only available for iOS platform.

**[Actual result]:**
- The iOS App Store download button is wrongly displayed on Android for Lockbox experiment.

**[Additional Notes]:**
- Here is a screenshot of the issue:

![screenshot_20180706-150436](https://user-images.githubusercontent.com/17258026/42378216-2cbf4cdc-812f-11e8-93bb-653f018c0ac3.png)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. 
To solve this issue, I need to check whether device is Android or IOS and display buttons according i.e. for any Android only experiment, show Download button only on Android device and don't show anything on IOS device and vice verca for IOS only device. Right ?
Is this also applicable for Experiment detail page ?

![screen shot 2018-08-16 at 02 42 45](https://user-images.githubusercontent.com/17615573/44173591-09b82300-a0fe-11e8-8145-f25281ae41e3.png)

**Comment by meandavejustice** [comment]
I think it makes sense to still show the App Store button here. It quickly signifies to users that it's available on ios and not android.

**Comment by meandavejustice** [comment]
cc/ @johngruen for his opinion. I think this issue should be closed

**Comment by KhushilMistry** [comment]
Should I close the PR #3826 ?

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice @johngruen let's clarify this, we have created a bit of confusion here.

1. Do you guys want to keep showing the iOS App Store button everywhere while viewing the website on Android? 
2. Do you guys want to keep showing the iOS App Store button only on experiment details page while viewing the website on Android?

From Dave's comment, I understood the second one at first. But now that he closed the issue, I'm not that sure anymore and we're confusng @KhushilMistry also. 😄 
Obviously the same thing should happen for Android based experiments on iOS platform.

**Comment by KhushilMistry** [comment]
I have made a PR if you guys want to reconsider it #3826. I can also make changes on your suggestions.
