### ISSUE TITLE
[Mobile] The "More experiments" button is partially overlapped by the "App Store" Lockbox button

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3717]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- Android 7.0 - 8.0
- iOS 11.0.1

**[Prerequisites]:**
- [Android] The "extensions.webapi.testing = true" Boolean pref was added on a new profile.

**[Steps to reproduce]:**
1. Open Android or iOS Firefox mobile browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Scroll down and observe the position of the "Download on the App Store" Lockbox button when it meets the "More experiments" button.

**[Expected result]:**
- The App Store button is overlapped by the 'More Experiments" one until the "Try all of our experiments" section is reached and the overlapping button disappears.

**[Actual result]:**
- The App store button is partially overlapping the "More Experiments" one. 

**[Additional Notes]:**
- Partially overlapping since it seems that the "More Experiments" button is composed from 2 layers and only one is overlapped.
- Here is a screenshot of the issue:

![image-1](https://user-images.githubusercontent.com/17258026/42379254-d00ce658-8132-11e8-956c-9bb34fe21010.jpg)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. Will send a PR in a while.

**Comment by SoftVision-PaulOiegas** [comment]
Works like a charm, at least for the iOS App Store button on both Android (7.0 Galaxy S6) and iOS (iPhone 5 SE). Thanks for the fix @KhushilMistry! 👍
