### ISSUE TITLE
[Experiment details] Localization warning message has several display issues

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3718]
**[Affected versions]:**
- Firefox 61.0 and above

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Prerequisites]:**
- The `extensions.webapi.testing` boolean pref wass added with `true` value on a new profile.
- The German [de] browser content language was added in first position from "Menu>Options>General>Language" menu, on the created profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to `https://testpilot.dev.mozaws.net page.
2. Click on the "Firefox Lockbox" experiment logo or title.
3.  Observe the localization warning message displayed above the experiment video presentation.

**[Expected result]:**
- The localization warning is correctly displayed and according to design. 

**[Actual result]:**
The localization warning message has the next issues:
- The box is too small to have equal space on each side of the message. 
- Message and warning image are not displayed in the middle of the box.
- The entire box is displayed too close to the video, the entire content udner the box should move down a few pixels.

**[Notes]:**
- Here is a screenshot of the issue:

![screenshot-2018-7-6 firefox test pilot - firefox lockbox 1](https://user-images.githubusercontent.com/17258026/42383163-166375c0-813f-11e8-98d8-cf9fc547b058.png)

**Comment by SoftVision-PaulOiegas** [comment]
- Seems that the error message misses some margins
margin: 20px 0 0; vs 20px 20px 20px;

- The video also misses a margin-top: 20px;

Should look like this
![screenshot_2018-07-30 firefox test pilot - firefox lockbox 3](https://user-images.githubusercontent.com/17258026/43410194-c660f4b4-942e-11e8-93a5-6f2421da3ecd.png)

**Comment by SoftVision-PaulOiegas** [comment]
Umm... looks good but now we have another problem. The warning icon went black from orange/yelow'ish.

![screenshot_2018-08-06 firefox test pilot - firefox lockbox](https://user-images.githubusercontent.com/17258026/43707408-acd46b2e-9970-11e8-9fab-75ad134d91c8.png)

**Comment by meandavejustice** [comment]
Hmm, that doesn't seem to make sense with the changes. Digging into this

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas Checked against master, and we're having the same issue there.

![icon-color](https://user-images.githubusercontent.com/1844554/43727152-b75eb458-9990-11e8-9a6b-9be60a831ba5.png)

This is peculiar. There haven't been any changes to this component in the past 3 months, yet prod looks good while master is rendering black.

![warning-history](https://user-images.githubusercontent.com/1844554/43727276-03f826be-9991-11e8-9274-f78566a45ef2.png)

I say we create a new issue for the color, so that we can get the margin issue fixed.

**Comment by meandavejustice** [comment]
created https://github.com/mozilla/testpilot/issues/3782 for icon color issue

**Comment by SoftVision-PaulOiegas** [comment]
Looks fixed on dev and stage servers. 

![screenshot_2018-08-08 firefox test pilot - firefox lockbox 1](https://user-images.githubusercontent.com/17258026/43828144-54c539f0-9b04-11e8-9910-c5ecba1077a6.png)
