### ISSUE TITLE
Experiment detail headers are misaligned

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3720]
### DEVELOPMENT:

![side-view-dev](https://user-images.githubusercontent.com/557895/42395202-e38c1602-8111-11e8-9cca-b2b06d463231.png)

**Figure 1:** https://testpilot.dev.mozaws.net/experiments/side-view

![lockbox-er](https://user-images.githubusercontent.com/557895/42395960-9baff6c0-8114-11e8-85b6-ec2877a08fe9.png)

---

### PRODUCTION:

![side-view-prod](https://user-images.githubusercontent.com/557895/42395146-a086d45a-8111-11e8-896f-a591fa9c1a56.png)

**Figure 2:** https://testpilot.firefox.com/experiments/side-view

**Comment by SoftVision-PaulOiegas** [comment]
Yep, something broke there. Don't remember this to be something intended. 😄
