### ISSUE TITLE
Not getting emails for mobile apps on dev/stage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3721]
I tried downloading the Notes Android app via https://testpilot.stage.mozaws.net/experiments/notes and the Lockbox iOS app via https://testpilot.dev.mozaws.net/experiments/firefox-lockbox and I entered by email address, but after 30+ minutes I still haven't received any messages to my 2 email accounts (so I should have 4 emails total).

<img width="645" alt="locken-boxen" src="https://user-images.githubusercontent.com/557895/42405117-96ec6b0a-8146-11e8-9a57-18bee2609971.png">

**Comment by devinreams** [comment]
I'm not getting emails from production, either. Just SMS...

**Comment by SoftVision-PaulOiegas** [comment]
Just tried with my gmail account on production and got an email for Lockbox.
https://screenshots.firefox.com/g69wdSFiulL8PPSZ/mail.google.com

LE: Same for my personal yahoo account when it comes to Notes.

**Comment by devinreams** [comment]
Same here, re-tested with a gmail account and received the email! 💌 

@pdehaan I believe this can be closed? 🤞

**Comment by SoftVision-PaulOiegas** [comment]
I'll close it for Peter. If it's not fixed I'll give him a 🍺  next time we meet so he won't be mad.
