### ISSUE TITLE
Add Anthony Lam to the Notes Experiment Page

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3726]
Title = Designer

![pic php](https://user-images.githubusercontent.com/3323249/42525472-85c27df8-8473-11e8-8e65-1387f12aa0e5.jpeg)

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen If we are doing this, can we also change the Lockbox QA "Catalin Sasca = Mobile QA Engineer" with "Catalin Suciu = Mobile QA Engineer"? I think the team confused them since their names are alike. Suciu is the Mobile QA, while Sasca is a Desktop QA.

**Comment by devinreams** [comment]
I'll take care of both of these right now...

https://github.com/mozilla/testpilot/pull/3727
