### ISSUE TITLE
Right click or long click

### ISSUE THREAD

**Issue by pt4r** [mozilla/testpilot#3732]
When opening Google Drive i tried to long press or right click a folder but there was no options shown like as they are on a Mobile.

**Comment by SoftVision-PaulOiegas** [comment]
Hey @Pt4r and thanks for your report. However, I don't see how this is related to the Test Pilot platform. Can you be more explicit on which experiment is this happening?

Or is this a Firefox issue that you encounter? In which case, you should log an issue in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi) instead. The Test Pilot platform doesn't deal with browser issues.

**Comment by pt4r** [comment]
Hello and thank you for your reply. Thank you for reminding me that I completely forgot to mention that this issue is for the Side View feature.

**Comment by johngruen** [comment]
Hey @pt4r, i moved this over to the Side View repo. Closing here

https://github.com/mozilla/side-view/issues/306
