### ISSUE TITLE
Add dimensions to mozAddonManagerEvent, SMS Events, Featured Experiment Events and Experiment Buttons

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#3735]
Needs to include: 
`dimension1`
`dimension2`
`dimension3`

**Comment by meandavejustice** [comment]
I think we should add these in the root `sendToGa` definition in https://github.com/mozilla/testpilot/blob/master/frontend/src/app/containers/App/index.js#L315. Any reason we shouldn't do that?

**Comment by lmorchard** [comment]
> Any reason we shouldn't do that?

Looks like from [the metrics doc for GA](https://github.com/mozilla/testpilot/blob/master/docs/metrics/ga.md#custom-dimensions), those dimensions aren't meant to be included on every page. But then, neither are 8 or 9 and they are included in every ping. So, I guess I don't know / am confused?

**Comment by ghost** [comment]
Adding them to `sendToGa` makes sense to me.  Those dimensions are interesting broadly so sending them on every page is fine.  As Les pointed out, let's keep the docs up to date with any changes that are made.  Thanks!
