### ISSUE TITLE
[release] 2018-07-26 on stage

### ISSUE THREAD

**Issue by devinreams** [mozilla/testpilot#3746]
minor: JSX in pages.js is replaced with React components, lots more translations

https://github.com/mozilla/testpilot/compare/2018-07-17...master

**Comment by clouserw** [comment]
This is live:

0822 cloudops-ansibl+│ testpilot static prod #76 building
0824 cloudops-ansibl+│ testpilot-mozillaextension testpilot #495 signing
0824 cloudops-ansibl+│ testpilot-mozillaextension testpilot #495 deployed
0826 cloudops-ansibl+│ testpilot static prod #76 deploy succeeded
