### ISSUE TITLE
[Experiment details] The "Your privacy" button is missing from experiment controls area on 3rd party browsers

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3751]
**[Affected versions]:**
- All 3rd party browsers

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Steps to reproduce]:**
1. Open a 3rd party browser and navigate to https://testpilot.dev, mozaws.net page.
2. Scroll down on the page and click on any experiment card available except "Side View".
3. Look for "Your privacy" blue text button under the experiment logo or experiment control buttons.
4. Return to Homepage and click on "Side View" experiment card.
5. Look for the same "Your privacy" blue text button.

**[Expected result]:**
- All experiments, including "Side View" have the "Your privacy"  blue text button displayed under the experiment logo or experiment control buttons.

**[Actual result]:**
- Side View experiment does not have the "Your privacy" button displayed.

**[Notes]:**
- This issue occurs probably because the privacy button is bundled with the experiment control buttons and Side View has none displayed due to experiment type.
- Here is a screen recording of the issue: https://goo.gl/iDvL9o

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue.
