### ISSUE TITLE
[Experiment details] Experiment square logo wrongly displayed on Windows 10 Edge browser

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3752]
**[Affected versions]:**
- Edge browser v40.15

**[Affected Platforms]:**
- Windows 10 x64

**[Steps to reproduce]:**
1. Open a Edge browser on a Windows 10 machine and navigate to https://testpilot.dev, mozaws.net page.
2. Scroll down on the page and click on any experiment card available except.
3. Observe the experiment logo shape on top left part of the page.

**[Expected result]:**
- The experiment logo is round. 

**[Actual result]:**
- The experiment logo is rectangular. 

**[Notes]:**
- This issue does not reproduce for Lockbox logo from Featured experiment section.
- Here is a screenshot of the issue:

![square logos](https://user-images.githubusercontent.com/17258026/43406109-321e42f2-9424-11e8-8058-48b93c00116f.png)

**Comment by meandavejustice** [comment]
fixed in #3869

**Comment by SoftVision-PaulOiegas** [comment]
No longer reproducible on Windows 10 with Edge v40.15063.674.0. Thanks for the fix @sakshi97 👍
