### ISSUE TITLE
Experiment subtitle style improvement

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#3759]
<img width="352" alt="screen shot 2018-07-31 at 2 10 59 pm" src="https://user-images.githubusercontent.com/23885/43481439-922d2fb2-94cb-11e8-8f03-3ffa4a8074a0.png">

I'll get this.

**Comment by chuckharmston** [comment]
<img width="292" alt="screen shot 2018-07-31 at 2 12 46 pm" src="https://user-images.githubusercontent.com/23885/43481596-0083a810-94cc-11e8-9741-52f9069c37a2.png">

I'd also like to subtitle-ize the type a bit here.

**Comment by SoftVision-PaulOiegas** [comment]
Had to rerun this job in order to see it on dev since it failed last night. The subtitle was correctly aligned, but this change also caused other changes regarding the experiment type string. Filed this separately in #3763.
