### ISSUE TITLE
pontoon.js returns a 301 redirect

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#376]
I was looking at the developer console and noticed that it looks like pontoon.js is getting loaded twice.

Turns out, the first request is a 301 MOVED PERMANENTLY.

[./idea_town/frontend/templates/idea_town/frontend/index.html:18](https://github.com/mozilla/idea-town/blob/8b6034b33a373d8b0e2d4d21f09a62621a755b0c/idea_town/frontend/templates/idea_town/frontend/index.html#L18)

``` html
<script src="https://pontoon.mozilla.org/pontoon.js"></script>
```

That URL returns a 301 and redirects to https://pontoon.mozilla.org/static/js/pontoon.js. Probably best to just use the final URL and save a request/redirect.

Related: #373

**Comment by lmorchard** [comment]
[This is the documented URL given by the Pontoon folks](https://developer.mozilla.org/en-US/docs/Implementing_Pontoon_Mozilla). Even if it results in a redirect, I don't want to second guess their official deployment. Like I said in #373, this isn't a library we're using, it's a service integration.

**Comment by meandavejustice** [comment]
I'm with @lmorchard on this. I think the existing url is the safe bet. Thanks for finding this @pdehaan. May be worth filing [upstream](https://github.com/mozilla/pontoon)
