### ISSUE TITLE
The experiment type string formatting was wrongly changed on experiment card and experiment details page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3763]
**[Notes]:**
- This change appeared after #3761 was implemented and I'm not sure it was intended. At least the one on the experiment details page desen't seems to be based on the screenshots added by @chuckharmston.

**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Prerequisites]:**
- The `webextensions.webapi.testing` Boolean pref was added as `true` on a new profile. 

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.dev.mozaws.net page.
2. Open a new tab and navigate to https://testpilot.firefox.com page.
3. Scroll down on both opened pages and observe the experiment type string displayed on the cards.
4. Open an experiment from both pages and observe again the experiment type string displayed on top right side of the page.  

**[Expected result]:**
- The experiment type string format looks the same on both servers and on both experiment card and experiment details page.

**[Actual result]:**
- The experiment type string seems to be in bold on experiments cards and bold + increased size on experiment details page on Dev server.

**[Additional Notes]:**
- Here is a screenshot of the issue:

![screenshot_2018-08-01 firefox test pilot](https://user-images.githubusercontent.com/17258026/43513462-79af103e-9586-11e8-9009-a17971ddc319.png)

**Comment by ghost** [comment]
@sevaan @chuckharmston -- was this on purpose or is this bug valid?  Thanks

**Comment by chuckharmston** [comment]
It's valid. I'll try to get to it today.

**Comment by clouserw** [comment]
@chuckharmston any updates here?

**Comment by SoftVision-PaulOiegas** [comment]
Testing the fix blocked by #3798. I'll check it when we figure out what's causing the issue.

**Comment by SoftVision-PaulOiegas** [comment]
@chuckharmston your fix seems to have treated the issue on the experiment details page, but the strings on the experiments cards are still in bold.
@johngruen do we care about this? See the initial screenshot.

**Comment by SoftVision-PaulOiegas** [comment]
Reopening this to clarify the last question. Seems stranger each day. 😄

**Comment by SoftVision-PaulOiegas** [comment]
Verified on both Windows and MacOS and on experiments page and experiment details page. Looks better, thanks for the fix! 👍
