### ISSUE TITLE
Side View

### ISSUE THREAD

**Issue by bmarden12** [mozilla/testpilot#3766]
I have noticed that while using side view in two open windows of mozilla both would change simultaneously to the same website. I believe it would be more helpful if sideview could work separately if desired for more than one open mozilla firefox window.

**Comment by fzzzy** [comment]
Thanks for the suggestion. We already have a bug about this open in the Side View repository, so I am going to close this one as a dupe.

https://github.com/mozilla/side-view/issues/304
