### ISSUE TITLE
Remove Fira Sans?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3781]
It _may_ be worth revisiting the design somewhat and using system fonts.

![testpilot-fonts](https://user-images.githubusercontent.com/557895/43789030-ca9571d6-9a23-11e8-8133-09319926c7fe.png)

It looks like we're loading 7 .woff fonts and downloading roughly 590 KB of fonts in Chrome, but only 3 fonts (FiraSans-{Light,Regular,Medium}.woff) in Firefox Beta, for a total of 246.66 KB.

| FONT | SIZE | Chrome | Firefox
|------|-----:|:------:|:-------:
| FiraSans-Bold.woff | 86.5 KB | ✅ | 
| FiraSans-Regular.woff | 81.8 KB | ✅ | ✅ 
| FiraSans-LightItalic.woff | 86.7 KB | ✅ | 
| FiraSans-UltraLight.woff | 82.0 KB | ✅ |
| FiraSans-SemiBold.woff | 86.4 KB | ✅ | 
| FiraSans-Light.woff | 82.1 KB | ✅ | ✅ 
| FiraSans-Book.woff | 82.6 KB | ✅ | 
| FiraSans-Medium.woff | 82.75 KB |  | ✅ 
| **TOTAL** | &nbsp; | ~588.1 KB | ~246.66 KB |

**Comment by lmorchard** [comment]
FWIW, I think this basically ends up being an upstream issue for [the Photon Design System](https://design.firefox.com/photon/visuals/typography.html). But maybe we're not actually using every one of those fonts? I suspect we are, though

**Comment by johngruen** [comment]
Agree with @lmorchard here that whole brand design stuff is going to change our font scene anyway. We can close this for now.
