### ISSUE TITLE
Localization Warning box icon is now black?

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3782]
first noticed here https://github.com/mozilla/testpilot/issues/3718#issuecomment-410639489

**Comment by meandavejustice** [comment]
copied from https://github.com/mozilla/testpilot/issues/3718#issuecomment-410757157


@SoftVision-PaulOiegas Checked against master, and we're having the same issue there.

![icon-color](https://user-images.githubusercontent.com/1844554/43727152-b75eb458-9990-11e8-9a6b-9be60a831ba5.png)

This is peculiar. There haven't been any changes to this component in the past 3 months, yet prod looks good while master is rendering black.

![warning-history](https://user-images.githubusercontent.com/1844554/43727276-03f826be-9991-11e8-9274-f78566a45ef2.png)

I say we create a new issue for the color, so that we can get the margin issue fixed.

**Comment by meandavejustice** [comment]
In yesterdays meeting about the current milestone, it was mentioned that @chuckharmston might know something about this

**Comment by SoftVision-PaulOiegas** [comment]
LOL, looks ok on dev and stage without a fix. Maybe the issue was only present on local env?

![screenshot_2018-08-08 firefox test pilot - firefox lockbox](https://user-images.githubusercontent.com/17258026/43828042-16be9c14-9b04-11e8-90b1-464960ed86aa.png)

**Comment by SoftVision-PaulOiegas** [comment]
Ah wait, Donovan merged a fix for it. I assume we can close this too @meandavejustice ?

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas If it works on dev then I guess it should be fine, it's still weird to me that this is happening on local
