### ISSUE TITLE
Experiment card "Feedback" button is wrongly displayed lower than default when there is a subtitle

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3786]
**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Prerequisites]:**
- Test Pilot add-on was already installed on a new profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com/experiments page.
2. Enable first 3 experiments available (Notes, Advance and Color).
3. Return to the https://testpilot.firefox.com/experiments page.
4. Observe the "Feedback" buttons on all 3 experiments cards.

**[Expected result]:**
- The "Feedback" button is displayed on the same position on all the cards.

**[Actual result]:**
- The "Feedback" button on the "Advance" experiment card is displayed lower than on the others due to the extra subtitle.

**[Additional Notes]:**
- Here is a screenshot of the issue:

![screenshot_2018-08-08 firefox test pilot 2](https://user-images.githubusercontent.com/17258026/43845034-b915f762-9b33-11e8-891e-cf40a8301424.png)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. I have made the change. I will make a PR in a while.

**Comment by SoftVision-PaulOiegas** [comment]
The fix seems about right. Thanks for the PR @KhushilMistry! 👍 

![feedback aligned](https://user-images.githubusercontent.com/17258026/44215935-66f2b980-a17c-11e8-9112-0ec1c554d33b.png)
