### ISSUE TITLE
Update to a newer version of Fluent

### ISSUE THREAD

**Issue by stasm** [mozilla/testpilot#3789]
The Test Pilot website uses two Fluent dependencies: the core `fluent` package as well as `fluent-react`, the bindings for React. In #3631 I mentioned that I'm working on a fix to `fluent-react`.

Independently of `fluent-react`, I'd like Test Pilot to update to a newer version of the core `fluent` package. You're currently o n 0.4.3 and the latest is [0.7.0](https://github.com/projectfluent/fluent.js/blob/master/fluent/CHANGELOG.md#fluent-070-july-24-2018).

I tried updating it in my local setup, and unfortunately I ran into a build error. One of the changes 0.7.0 shipped with is an updated compatibility matrix for the `fluent/compat` builds. And while this new matrix is aligned with your browser support documented in the [FAQ](https://github.com/mozilla/testpilot/blob/master/docs/faq.md#what-browsers-are-supported-by-test-pilot), it turns out it's not compatible with old versions of Webpack. More specifically, UglifyJS breaks on non-ES5 syntax 🤦‍♂️  (e.g. `class` or `async`).

I'm filing this issue to let you know of my intent to update `fluent` somehow and to track my progress on dealing with the build error. And also to ask if you have any plans to upgrade to a newer version of Webpack and Uglify? :)

**Comment by clouserw** [comment]
Marking this small assuming an ES5 build will be provided
