### ISSUE TITLE
Experiment title and experiment type strings are wrongly aligned on mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3791]
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All platforms

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.firefox.com page.
2. Scroll / swipe down to the available experiments section.
3. Click / tap on the "Advance" experiment card and if on desktop, resize the browser to get in mobile view.
4. Observe the title, subtitle and experiment type strings position versus the experiment logo.

**[Expected result]:**
- All 3 strings are centrally aligned with the experiment logo.

**[Actual result]:**
- The title and experiment type strings are wrongly aligned more to the left side instead of middle.

**[Additional Notes]:**
- The experiment title and type strings are wrongly positioned on all the experiments in mobile view.
- Here is a screenshot of the issue:

![screenshot_20180813-185229](https://user-images.githubusercontent.com/17258026/44094595-42a95a28-9fdf-11e8-89ab-f5752fce98c9.png)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue.

**Comment by SoftVision-PaulOiegas** [comment]
Testing the fix blocked by #3798. I'll check it when we figure out what's causing the issue.

**Comment by SoftVision-PaulOiegas** [comment]
Hey @KhushilMistry, managed to test this, but sadly it's only partially fixed. The experiment names are properly aligned now, but the experiment type strings are still a bit out of place (horizontally).

![experiment type not aligned](https://user-images.githubusercontent.com/17258026/44276278-a6d6a100-a24f-11e8-9deb-737abc4a56e7.png)

**Comment by KhushilMistry** [comment]
No issue. I will make a change and send a PR in a while.

**Comment by SoftVision-PaulOiegas** [comment]
Looks perfect now! Thank you for your contribution @KhushilMistry! 👍
