### ISSUE TITLE
[Featured experiment] Web experiments wrongly display "Download Firefox" button instead of "Go to <experiment_name>" button on 3rd party browsers

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3792]
**[Notes]:**
- If Send experiment will get featured after the new UI for the website and the Android app will be released, this issue could surface. We should think at a way to manage this.
- If you run the local page on Firefox browser, the button becomes "Enable Send" so both the cases are something we haven't thought at since we never had a web experiment featured.

**[Affected versions]:**
- All 3rd party browsers

**[Affected Platforms]:**
- All platforms

**[Prerequisites]:**
- Test Pilot Master branch was locally cloned and setup was performed to run it locally. 
- Lockbox experiment was marked as not featured (false) in the `lockbox.yaml` file and Send experiment was marked as featured (true) in the `send.yaml` file.

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.firefox.com page.
2. Observe the big green button content displayed on the featured experiment section.

**[Expected result]:**
- The button shows the "Go to Send" string and allows you to navigate to its website.

**[Actual result]:**
- The button wrongly shows "Download Firefox" for a web experiment that can be used on all browsers and platforms.

**[Aditional Notes]:**
- Here is a screenshot of the issue: 

![screen shot 2018-08-14 at 16 41 52](https://user-images.githubusercontent.com/17258026/44095993-d6be6994-9fe2-11e8-9129-88ed58633bf8.png)

**Comment by meandavejustice** [comment]
Also noticed that we are showing the incorrect action in firefox as well

![untitled](https://user-images.githubusercontent.com/1844554/44364250-059d5400-a4b6-11e8-8e59-51c6e67a0b54.png)

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice Yeah, I have noticed that too while logging this issue. But I assumed this is because we never featured a web experiment, so the default option is shown. Mentioned this also in initial comment at "Notes" section.

**Comment by SoftVision-PaulOiegas** [comment]
Seems fixed while testing on local. 👍 The only remaining issue related is tracked separately in #3833.
