### ISSUE TITLE
[l10n] "View Details" and "Get Started" text not translated

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#380]
These are a bit subtle/tricky, since they only appear in the Sass.
1. "Get Started": [./idea_town/frontend/static-src/styles/modules/_list-view.scss:113](https://github.com/mozilla/idea-town/blob/60666a715d24e431aebe4011862d205c68e6ac2f/idea_town/frontend/static-src/styles/modules/_list-view.scss#L113)
2. "View Details": [./idea_town/frontend/static-src/styles/modules/_list-view.scss:130](https://github.com/mozilla/idea-town/blob/c7f3cd950167cdb1d05b2ab6d9e8b3dee1163070/idea_town/frontend/static-src/styles/modules/_list-view.scss#L130)

**Comment by lmorchard** [comment]
Worth referring to #130 for continuing work on l10n, mentioning here to get this linked over there too
