### ISSUE TITLE
Dev server is down and all attempts of jobs reruns fail

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3809]
**[Notes]:**
- Tried to rerun several recent jobs that passed, every one of the attempts failed.

**[Affected versions]:**
- All browsers

**[Affected Platforms]:**
- All platforms

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the loaded page.

**[Expected result]:**
- The Test Pilot dev serer page is correctly loaded.

**[Actual result]:**
- A blank page is wrongly displayed.

**[Aditional Notes]:**
- We cannot verify any changes / fixes performed because of this.
- Here is a screenshot with console output:

![image](https://user-images.githubusercontent.com/17258026/44462239-adcd2d00-a61c-11e8-83d1-d88d3d64ea74.png)

- Here is a screenshot from Circle CI integration fail

![screenshot_2018-08-22 circleci - circleci](https://user-images.githubusercontent.com/17258026/44462708-2ed8f400-a61e-11e8-895d-be013878ab13.png)

**Comment by fzzzy** [comment]
Dave and I managed to fix this yesterday. 🎉
