### ISSUE TITLE
[l10n] Add second locale to test l20n?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#381]
I created a German (de) translation locally (which is just the English strings, but ALL-CAPS).
It lets me play with string lengths and see what wraps weird and some intermittent flashing of English before the translations pop in.

Not sure if we want to try creating a real (or fake) translation and push it into ebs so we can check out switching locales and seeing this in action.

So far I've only found a pair of untranslated strings hiding in the Sass: #380 

Other things that aren't translated include:
- experiment names and details on http://ideatown.dev:8000/experiments
- measurement details on http://ideatown.dev:8000/experiments/universal-search
- screenshot descriptions on http://ideatown.dev:8000/experiments/universal-search

Not sure how to address the latter three, since those are "user" submitted experiments and not site strings (unless we do something like /locales/{locale}/{experiment_slug}.l20n).

**Comment by meandavejustice** [comment]
I believe that all of these will be taken care of once database localization is added cc/ @lmorchard

**Comment by lmorchard** [comment]
FWIW, [localization work is not done yet](https://github.com/mozilla/idea-town/issues/130#issuecomment-173072814).

**Comment by ghost** [comment]
Adding a second locale is secondary (eh? eh?) to adding localization in general which is https://github.com/mozilla/testpilot/issues/551 .  Once we add localization we'll definitely add a second locale, so I'm going to close this.  Thanks!
