### ISSUE TITLE
The waffle board link needs to be updated

### ISSUE THREAD

**Issue by ShivangiKakkar** [mozilla/testpilot#3821]
### Steps to reproduce the issue:
- Go to `README.md`. Then click on the `process`.
-  A link is opened which is [this](https://waffle.io/project/create/chosen-repository?repo=mozilla%2Ftestpilot) 
- It reads as shown in screenshot, that `mozilla/testpilot` is not a waffle project yet.
<img width="1203" alt="screen shot 2018-08-23 at 9 21 20 pm" src="https://user-images.githubusercontent.com/35342019/44536667-9aa08700-a71a-11e8-9d50-0020e36b83f3.png">

**Comment by meandavejustice** [comment]
Thanks for filing @ShivangiKakkar , we no longer use waffle, I've removed that section from the process doc

**Comment by ShivangiKakkar** [comment]
Pleasure :) @meandavejustice
