### ISSUE TITLE
[Featured experiment] "Go to <experiment_name>" button icon displayed in the wrong color

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3833]
**[Affected versions]:**
- All browsers

**[Affected Platforms]:**
- All platforms

**[Prerequisites]:**
- Test Pilot Master branch was locally cloned and setup was performed to run it locally see ([quickstart](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md)). 
- Lockbox experiment was marked as not featured `false` in the `lockbox.yaml` file and for Send experiment `is_featured: true` was added in the `send.yaml` file.

**[Steps to reproduce]:**
1. Open Firefox or a 3-rd party browser and navigate to https://testpilot.dev.mozaws.net page.
2. Observe the featured experiment area button displayed for Send experiment. 

**[Expected result]:**
- "Go to Send" blue button with white string and white globe icon displayed.

**[Actual result]:**
- The button globe icon is black instead of white.

**[Additional Notes]:**
- If the button is desired to be green instead of blue, then the string and icon should be both black.
- Related with #3806.
- Here is a screenshot of the issue: 

![screen shot 2018-08-27 at 13 16 21](https://user-images.githubusercontent.com/17258026/44658030-c87e1800-aa07-11e8-9bc3-a6e2dde5e78e.png)

**Comment by ShivangiKakkar** [comment]
@SoftVision-PaulOiegas , @clouserw 
May I work on this issue?

**Comment by clouserw** [comment]
@ShivangiKakkar that would be great, please do.  We talked about it in our triage and think it's just a forgotten CSS rule.

**Comment by ShivangiKakkar** [comment]
@clouserw Okay! Thank you :)

**Comment by ShivangiKakkar** [comment]
Also the error message (in yellow banner) doesn't go away untill we refresh the page. Is that a desired behaviour?
Or it's a bug? @clouserw @SoftVision-PaulOiegas

**Comment by ShivangiKakkar** [comment]
Hey! @clouserw,
I am not able to reproduce it. What am I missing? Would you please guide me through that?

<img width="1275" alt="screen shot 2018-08-27 at 11 53 09 pm" src="https://user-images.githubusercontent.com/35342019/44677783-70213780-aa54-11e8-85eb-50b0bb445d25.png">

<img width="1237" alt="screen shot 2018-08-28 at 12 31 19 am" src="https://user-images.githubusercontent.com/35342019/44679895-d2c90200-aa59-11e8-8e3d-5da4c3ee7ab5.png">

**Comment by meandavejustice** [comment]
Hey @ShivangiKakkar you will need to go into `content-src/experiments/send.yml` and set the attribute `is_featured` to true. You'll also need to set that attribute to false in `content-src/experiments/lockbox.yml` for testing.

Don't forget to set them back after getting a screenshot and opening the pr.

**Comment by ShivangiKakkar** [comment]
@meandavejustice 
I did that and after setting both, I got these as shown in the screenshots :(

**Comment by SoftVision-PaulOiegas** [comment]
@ShivangiKakkar 
>Also the error message (in yellow banner) doesn't go away untill we refresh the page. Is that a desired behaviour?
Or it's a bug? @clouserw @SoftVision-PaulOiegas

I know about this behavior, but I think it's due to how the website is implemented like a single page and only the content updates. That's why we haven't logged anything on it. 

@dannycoates - is this a limitation due to the implementation, or the error can be dismissed when navigating through the website?

**Comment by ShivangiKakkar** [comment]
@meandavejustice Hey! I just realised that we both pushed the same fix, you can merge any one of them. 😅

**Comment by ShivangiKakkar** [comment]
@meandavejustice Thanks a lot :)

**Comment by SoftVision-PaulOiegas** [comment]
The fix seems to be the right one. 👍 Thanks @ShivangiKakkar for another good fix. 😃 

![screenshot_2018-09-05 firefox test pilot](https://user-images.githubusercontent.com/17258026/45078682-4a053280-b0f9-11e8-9bf9-231a83ed9def.png)
