### ISSUE TITLE
Css fails to load if not in DEBUG mode

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#384]
if NODE_ENV is not set to 'development' we minify our css and name it `main.min.css`. Our html only links to `main.css`.

**Comment by lmorchard** [comment]
Should be fixed by https://github.com/mozilla/idea-town/commit/b968504a40bd1fad9bbe6c7ce2118646ad0f2962

**Comment by meandavejustice** [comment]
Whoops you're right @lmorchard no :coffee: yet today!
