### ISSUE TITLE
Bookmarks toolbar appears briefly on open and then disappears.

### ISSUE THREAD

**Issue by Professor-Teplow** [mozilla/testpilot#3842]
I'm running 63.0b2 (64-bit) on a Mac Pro, Early 2009, 2.66 GHz Quad-Core Intel Xeon, 20 GB of 1066 MHz DDR3, OS X 10.11.6. All of a sudden, when I open Firefox, my toolbar bookmarks toolbar opens for about 1/10 sec and then disappears. I've:

1. Reinstalled the app.
2. Reset under Customize.
3. Looked for the "Bookmarks Toolbar Items" icon in customize. It's not there!
4. Toggled Views/Toolbars/Bookmarks Toolbar multiple times.
5. Renamed the json file and restarted Firefox.

Nothing helped.

Help!

**Comment by lmorchard** [comment]
This sounds like a general Firefox issue. Is there a particular Test Pilot experiment that you think is causing this issue? If not, this probably isn't the right place for this issue.

**Comment by Professor-Teplow** [comment]
Thanks Imorchard. It's not a Test Pilot experiment. I'll post to the general forum.
