### ISSUE TITLE
[release] 2018-09-10-1 on stage

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3854]
https://github.com/mozilla/testpilot/releases/tag/2018-09-10
https://github.com/mozilla/testpilot/releases/tag/2018-09-10-1

**Comment by SoftVision-PaulOiegas** [comment]
Hi guys,

We have finalized running our [Full Functional test suite](https://testrail.stage.mozaws.net/index.php?/runs/view/12185&group_by=cases:section_id&group_order=asc) on the Staging server and here are the testing results:

### **Legend** ###
&#x26D4;   - blocker issue
&#x1F4D5; - major issue
&#x1F4D9; - normal issue
&#x1F4D2; - minor issue
&#x1F4D7; - enhancement

## New Issues ##
1. #3863 - &#x1F4D2; Featured experiment section "Terms" and "Privacy" links are different than the ones from under the bottom "Install" button
2. #3865 - &#x1F4D2; The "Shutting down..." animation words seem to overlap on Italian localization

## Known Issues ##
1. #3544 - &#x1F4D9; [Experiment details] Add back the experiment enable error when installing both TxP add-on and experiment
2. #3061 - &#x1F4D9; Firefox Free Download button lacks download animation when hovered
3. #3687 - &#x1F4D9; [Mobile][Android] "Please enter an email address" error message is wrongly displayed without submitting the sign up form
4. #3696 - &#x1F4D2; [Mobile] Experiment launch / expiration date no longer displayed on mobile view
5. #3564 - &#x1F4D9;  [Featured Experiment] Experiment enable error is wrongly displayed on two rows on languages with longer words 

## Based on testing results we would suggest the next course of actions: ##
- Considering the fact that the new issues are quite minor ones that don't affect the website functionality, we are good for deploying this version to production.
However, we strongly recommend fixing the mentioned known issues in the next releases if possible.

**Comment by meandavejustice** [comment]
The plan is to push to prod monday morning (9am Eastern Time)
