### ISSUE TITLE
Update babel-loader

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#3856]
There were some changes to how babel loads plugins, more info here https://github.com/babel/babel-loader/issues/540

**Comment by lmorchard** [comment]
Not sure if it helps, but I played with it over the weekend and managed to upgrade babel-loader over on Firefox Color https://github.com/mozilla/FirefoxColor/pull/424/commits/f02963304ef30f048b24cf6f37977b7185331a93
