### ISSUE TITLE
Featured experiment section  "Terms" and "Privacy" links are different than the ones from under the bottom "Install" button

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3863]
**[Notes]:**
- it seems that we have 2 pages for Terms and Privacy pages.

**[Affected versions]:**
- Firefox 62.0 and above

**[Affected Platforms]:**
- All platforms

**[Prerequisites]:**
- The `extensions.webapi.testing` Boolean pref was added as `true` on a new profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.stage.mozaws,net page.
2. Open in new tabs the links for "Terms" and Privacy" pages found under the top green button for featured experiment.
3. Observe both the pages URLs.
4. Return to the Test Pilot tab and scroll down to the bottom "Install the Test Pilot Add-on" button.
5. Open the same two pages from the links under the bottom.
6. Observe again the URLs of the opened pages.

**[Expected result]:**
- Both the top and bottom links are opening the same pages.

**[Actual result]:**
- Step 3: The pages opened from top links have the URLs **without** "/" at the end.
- Step 6: The pages opened from bottom links have the URLs **with** "/" at the end and a difference can be seen between the "Privacy" page that has all sections expanded and there is no button to "Show less".

**[Notes]:**
- This also reproduces on 3rd party browsers.
- Doe snot reproduces on Production server, but if you add the "/" at the end of the URL, the same thing occurs on production too.
- Here is a screen recording of the issue: https://goo.gl/2Xkr7M.

**Comment by clouserw** [comment]
This is two separate resources in AWS.  I kind of think we did that on purpose to make trailing slashes work, and I remember talking about us being confused about it later.  Maybe AWS didn't support redirects?

We'll leave this open to investigate, but it should be easy to see the double copy in the script.

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. 
What should be the URLs ? With '/' or without ?

**Comment by fzzzy** [comment]
@KhushilMistry Both with '/' and without should work, and they should both be the same page. Right now they both work but the pages are slightly different for unknown reasons.

**Comment by SoftVision-PaulOiegas** [comment]
The user is now redirected to the pages without "/" no matter from where he accesses Privacy and Terms pages. Also, the pages with "/" can still be manually accessed.
