### ISSUE TITLE
The "Shutting down..." animation words seem to overlap on Italian localization

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3865]
**[Notes]:**
- This could be happening on other locales too, checked also German, French, Russian but haven't seen any issues.

**[Affected versions]:**
- Firefox 62.0 and above

**[Affected Platforms]:**
- All platforms

**[Prerequisites]:**
- The `extensions.webapi.testing` Boolean pref was added as `true` on a new profile.
- The Test Pilot add-on was already installed on the same profile.
- Italian language for page content was added as top selection from browser Options > General > Language section.  

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.stage.mozaws,net page.
2. Click on top right "Settings" button and chose the "Uninstall test Pilot" option.
3. On the displayed modal, click the "Proceed" button.
4. Observe the "Shutting down..." animation display in Italian language.

**[Expected result]:**
- The animation is correctly displayed and the text is perfectly readable.

**[Actual result]:**
- The two words are displayed on separate rows and they seem to overlap a bit.

**[Notes]:**
- Here is a screenshot of the issue: 

![shutting down in italian](https://user-images.githubusercontent.com/17258026/45501491-06aa6400-b78a-11e8-997b-19daf45276cd.png)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. Will make a PR in a day.

**Comment by SoftVision-PaulOiegas** [comment]
Checked Italian along with other several languages and it seems to be working fine on the checked ones.
