### ISSUE TITLE
Rename the project to Test Pilot

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#387]
Sounds like we're pretty firm on the name change, so let's look into what all needs changing to reflect the new name "Test Pilot"

**Comment by clouserw** [comment]
This is what I'm imagining:
- [x] Rename repository
- [x] Adjust webhooks
- [x] Adjust IRC settings in webhook
- [x] Adjust travis ci settings in webhook
- [x] Adjust coveralls settings in webhook
- [x] Land s/Idea Town/Test Pilot/ PR (this will cover the .travis.yml files and such) This is #393
- [x] Email mailing list with a note to change URLs.  Something like:

> We've renamed our repository!  See the new repository at ___________
> If you already have the code checked out run try these commands:
> `git remote -v` to get a list of all your remotes
> `git remote set-url origin git@github.com:mozilla/testpilot.git` (adjust URL to https if that's what you see in the first command)

.....do we have to do anything with docker?  Any other repositories?  Other stuff I'm missing?
- [ ] confirm name changes in legal docs

/cc @lmorchard @meandavejustice

**Comment by pdehaan** [comment]
I'll also need to rename "eslint-config-idea-town" to "eslint-config-testpilot" and update package.json.
Then I can deprecate or just delete the old idea-town ESLint config package.

I can do that anytime, I was just waiting to see if this repo was going to be "testpilot" or "test-pilot" so I could be consistent.

**Comment by clouserw** [comment]
I've been encouraging no dash.  just testpilot.

**Comment by pdehaan** [comment]
Renamed and published [**eslint-config-testpilot**](https://www.npmjs.com/package/eslint-config-testpilot) to npm.

And since I thought it'd be weird to publish a new module with a version of 1.2.0 to npm, I reset the version number to 1.0.0.

---

Unrelated, but if we bump the **eslint-config-airbnb** dependency to the latest version (currently 4.0.0), we're going to start getting a bunch more ESLint errors/warnings (see [CHANGELOG.md](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md))

**Comment by lmorchard** [comment]
A few more things off the top of my head, since we have a continual deployment thing happening that feeds into cloudops deployments:
- [ ] Move hub.docker.com/r/lmorchard/idea-town somewhere more official (eg. mozilla/testpilot)
- [ ] Build & deploy a new dev environment (currently idea-town-dev.elasticbeanstalk.com)
- [x] Adjust travis to push container to new Docker Hub location, and deploy to new elasticbeanstalk env

**Comment by lmorchard** [comment]
Internal renaming landed. We still need to rename the repo itself, announce the change, and make sure all of us devs change local refs to repos. 

And then there's the Docker-to-dev stuff I mentioned above. If we're not finding it useful, we can nuke it. Otherwise, it will be broken on repo rename and need some work to fix. Not sure what dependencies deployment on ops has on the repo name yet...

**Comment by lmorchard** [comment]
Oh yeah, and:
- [x] Change repos for Waffle & any other project management tools we're using

**Comment by clouserw** [comment]
New waffle @ https://waffle.io/mozilla/testpilot .  travis and coveralls are hooked up.  I'll follow up on the legal docs.  I think we're done here?
