### ISSUE TITLE
[Experiment details] Experiment logo is wrongly displayed over an oval shape instead of a circle in mobile view

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3876]
**[Affected versions]:**
- Firefox 62.x and above

**[Affected Platforms]:**
- All Desktop
- All Mobile

**[Prerequisites]:**
- The "extensions.webapi.testing = true" Boolean pref was added on a new profile.

**[Steps to reproduce]:**
1. Open Firefox Desktop or mobile browser and navigate to `https://testpilot.dev.mozaws.net page.
2. Scroll down to the available experiments and tap one of the cards.
3. [Desktop] Reduce browser window size horizontally until reaching mobile view mode.
4. Observe the experiment logo on top of the page.
 
**[Expected result]:**
- The experiment logo is correctly displayed over a round gradient colored circle shape (experiment card color).

**[Actual result]:**
- The logo is wrongly displayed on a oval gradient colored shape.

**[Additional Notes]:**
- This occurs for any experiment tested.
- Here is a screenshot of the issue:

![screenshot_2018-09-20 firefox test pilot - firefox lockbox](https://user-images.githubusercontent.com/17258026/45833652-dd4f8200-bd0d-11e8-9fc3-5197330c34f2.png)

**Comment by SoftVision-PaulOiegas** [comment]
This issue might be caused by the fix made in #3869 for #3752.

**Comment by meandavejustice** [comment]
fixed in #3879

**Comment by SoftVision-PaulOiegas** [comment]
The issue is no longer reproducible. tested on Windows 10x64, MacOS 10 13.6 and Android 7.0.
