### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by nchapman** [mozilla/testpilot#388]
Use Google Analytics to track page visits and related metrics. We should also identify key funnel steps and button presses to make sure those are appropriately tagged.

**Comment by ghost** [comment]
@meandavejustice do you have the GA code for this or do you need us to find one?

**Comment by meandavejustice** [comment]
@wresuolc I need the GA code

**Comment by ckprice** [comment]
@meandavejustice @wresuolc filed [bug1253728 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1253728) to get this.

**Comment by ckprice** [comment]
The GA snippet was supplied in [bug1253728comment3](https://bugzilla.mozilla.org/show_bug.cgi?id=1253728#c3). This ID can be used on both stage and prod.

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49796218-34', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by meandavejustice** [comment]
thanks @ckprice
