### ISSUE TITLE
No description is displayed on the "ending" warning from the Advance experiment page 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3904]
[Notes]:
- Usually, a description is displayed on the "ending warning" that describe what happens next with the experiment and also if it will remain or will be automatically uninstalled after it expires.

[Affected versions]:
- Nightly Firefox 62.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false", "extensions.webapi.testing = true", "extensions.install.requireBuiltInCerts = false".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to "testpilot.stage.mzoaws.net".
2. Click the Advance experiment card.
3. Observe the "expiring warning".

[Expected result]:
- A description that informs the user what will happen next with the experiment is displayed.

[Actual results]:
- No description is displayed.

[Additional Notes]:
- Here is a screen
![no description 2](https://user-images.githubusercontent.com/19226534/47005097-bed97c80-d13b-11e8-82fb-949bac2401cb.png)
shot of the issue:

**Comment by meandavejustice** [comment]
Issue now irrelevant since `2018-10-15` was deployed
