### ISSUE TITLE
The "Learn more" link displayed in the "ending" warning from the Advance page is misaligned  

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#3905]
[Affected versions]:
- Nightly Firefox 62.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Following 3 prefs have been set or added on a new profile: "xpinstall.signatures.required = false", "extensions.webapi.testing = true", "extensions.install.requireBuiltInCerts = false".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to "testpilot.stage.mzoaws.net".
2. Click the Advance experiment card.
3. Observe the "Learn more" link displayed in the "expiring warning".

[Expected result]:
- The "Learn more" link is aligned with the "Advance is ending on October 17, 2018" title.

[Actual results]:
- The "Learn more" link is misaligned.

[Notes]:
- Here is a screenshot of the issue:
![learn more link](https://user-images.githubusercontent.com/19226534/47005292-1d9ef600-d13c-11e8-91c0-7ac9623737f4.png)

**Comment by meandavejustice** [comment]
no longer relevant since `2018-10-15` was deployed
