### ISSUE TITLE
Allow other domains besides @mozilla.com for dev/stage

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#391]
It will make our QA automated testing a lot easier if we can allow specific domains or accounts so QA doesn't have to try and manage LDAP passwords for @mozilla.com email addresses.

For other services we just create a bunch of @restmail.net accounts which are easy to create and check.

**Comment by silne30** [comment]
+1

**Comment by lmorchard** [comment]
Some details: Right now mozilla.com is a hardcoded check. I think the easiest thing to do here is support a list of domains in Django settings, next hardest would be a list of regexes. The list should be configurable via environment variable like most of the important settings.
