### ISSUE TITLE
[Featured experiment] Mobile platform download buttons wrongly have the same color

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3925]
**[Affected versions]:**
- Firefox 63.0 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Local clone the master Test Pilot branch. 
- Perform the setup in order to run the build locally and start the server as in [quickstart ](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md) doc.
- Edit the "lockbox.yaml" file by adding the `android` one to the existing `ios` one and save the file.
- Edit the "lockbox.yaml" file by adding the `android_url:` with a link to a Google Play store app and save the file. 

**[Steps to reproduce]:**
1. Open Firefox Developer edition browser and navigate to `https://example.com:8000/ page.
2. Observe the buttons displayed for both mobile platforms.
 
**[Expected result]:**
- Both mobile platform buttons are correctly displayed and working.

**[Actual result]:**
- Both buttons have the same green color, while in the designs added on [#3672](https://github.com/mozilla/testpilot/issues/3672#issuecomment-428806072) they have different colors.

**[Notes]:**
- Here is a screenshot of the issue: 

![screenshot_2018-10-30 firefox test pilot](https://user-images.githubusercontent.com/17258026/47739254-aad66480-dc7d-11e8-87cd-b4d864951e3f.png)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue. Will make a PR in a day.

**Comment by SoftVision-PaulOiegas** [comment]
Buttons color has been fixed. iOS has blue and Android has green now. This reflects on both Featured experiment section and Experiment details page.
https://screenshots.firefox.com/79atmlYyD8scBCwy/example.com
https://screenshots.firefox.com/ifd6a4nXEceHqNl5/example.com
