### ISSUE TITLE
[Featured experiment] Get the App Modal wrongly shows Google Play Store Button on Lock Box(iOS Experiement)

### ISSUE THREAD

**Issue by KhushilMistry** [mozilla/testpilot#3933]
![screenshot 2018-11-02 at 2 01 24 am](https://user-images.githubusercontent.com/17615573/47878235-cbe8b200-de43-11e8-8709-ca29a9c0a2fb.png)

@SoftVision-PaulOiegas is it right behaviour ?

**Comment by SoftVision-PaulOiegas** [comment]
@KhushilMistry Is there a chance that this issue is the same as #3650 and #3652?

**Comment by KhushilMistry** [comment]
Yes, it is same as #3650. I guess this is due to new introduction of iOS and Andriod buttons in Featured Experiement. 
Should I make a PR for this ?

**Comment by johngruen** [comment]
Just a heads up...since we're de-featurizing Lockbox, this does not need to block a release with new experiments.
