### ISSUE TITLE
Add operations endpoints

### ISSUE THREAD

**Issue by clouserw** [mozilla/testpilot#394]
The operations infrastructure is expecting some endpoints for each project to reply in a standardized fashion.  This will be expected for all Test Pilot experiments as well as Test Pilot itself.  They are handy for debugging too!
1. Respond to `/__version__` with a [JSON version object](https://docs.google.com/document/d/1rGVyiLYvZyKE2oHcSVx-vBmQRKhs1kLLgn7xeCs6qKs/edit)
2. Respond to `/__heartbeat__` with a HTTP 200 or 5xx on error
   
   this endpoint is used by external monitoring to check the health of the service
   it is recommended to check the app's dependencies (database, caches, etc) here
3. Respond to `/__lbheartbeat__` with an HTTP 200
   
   used by the load balancer to check if the server and application is OK
   do not include dependency checks as this check may trigger automatic node termination and replacement

**Comment by lmorchard** [comment]
My question with the `__version__` thing is how & when do we increment version? Should we just have a 1.0.0 that gets incremented (eg. 2.0.0, 3.0.0) every time we deploy ala Firefox? 

Up to now, we were kind of aiming toward a continual deployment thing, if possible. So, git commit hashes would have been basically the version. We don't have a numbering scheme otherwise.

Another option - if this isn't required to be semver - is I guess we could toss the sprint end date in there?

**Comment by chuckharmston** [comment]
With `master` checked out, `git rev-list --count HEAD` will give you a the number of commits. Could be used as a point version to make sure everything is unique?

**Comment by lmorchard** [comment]
Also, generating the `commit` value should probably happen in the Docker container build. Kind of redundant / weird to commit a change to project source to note the commit hash of the previous commit

**Comment by lmorchard** [comment]
> With master checked out, git rev-list --count HEAD will give you a the number of commits. Could be used as a point version to make sure everything is unique?

Sure, as long as we never ever ever rebase / force-push master. (which we shouldn't ever, but it's possible)

**Comment by clouserw** [comment]
Saying we're not going to force push master seems like a reasonable thing to do.

**Comment by lmorchard** [comment]
> Saying we're not going to force push master seems like a reasonable thing to do.

Yeah, fair enough. Bad things happen on master with a force push, so we can just chalk this up as one more bad thing that could happen.

**Comment by clouserw** [comment]
For the record, I also set the master branch to protected in github so we shouldn't be able to accidentally force push it either.

**Comment by lmorchard** [comment]
We had that protected at one point, but disabled it. Turns out it makes pull requests very hard to merge without constantly rebasing against master, even if there aren't conflicts
