### ISSUE TITLE
The "Firefox experiment" tag is misplaced if the"unsupported browser version" warning is displayed

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/testpilot#3947]
[Affected versions]:
- Firefox 62.0.3 and older

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Old Firefox 62.0.3 or lower was installed/extracted on the system.

[Steps to reproduce]:
1. Open the old browser version with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click on "Install Test Pilot & Enable Price Wise" button.
3. Click on the "Manage" button.
4. Observe the "Firefox experiment" tag from the experiment's page.

[Expected result]:
- The "Firefox experiment" tag is displayed above the "unsupported browser version" warning, aligned to the right.

[Actual results]:
- The "Firefox experiment" tag is misplaced on the left side of the "unsupported browser version" warning, aligned to the left.

[Additional Notes]:
- Here is a screenshot of the issue:

![error](https://user-images.githubusercontent.com/26000308/48256925-b2ce9b00-e419-11e8-8e83-68fec45d1d43.png)

**Comment by SoftVision-PaulOiegas** [comment]
This is no longer reproducible on both Windows 10 and Mac OS 10.13 systems tested.

![image](https://user-images.githubusercontent.com/17258026/48365328-48388c00-e6b3-11e8-85f2-683566d1335d.png)
