### ISSUE TITLE
Price Wise is wrongly installed on unsupported Firefox version 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/testpilot#3948]
[Notes]:
- The "Price Wise requires Firefox 63 or later." error is displayed only if the Test Pilot add-on is installed. Even though, this error doesn't stand out since it's just a string blending with other ones near it (issue tracked [here](https://github.com/mozilla/testpilot/issues/3947)). 

[Affected versions]:
- Firefox 62.0.3 and older

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "extensions.webapi.testing" boolean type pref was manually added in "about:config" page with "true" value.
- Old Firefox 62.0.3 or lower was installed/extracted on the system.

[Steps to reproduce]:
1. Open the old browser version with the profile from prerequisite and navigate to https://testpilot.dev.mozaws.net/experiments page.
2. Click on "Install Test Pilot & Enable Price Wise" button.
3. Observe the page behavior.

[Expected result]:
- Test Pilot add-on is successfully installed, but Price Wise experiment is not since it requires at least Firefox 63.0 to properly work.

[Actual results]:
- Test Pilot add-on is successfully installed but also Price Wise experiment is installed together with it.

[Additional Notes]:
- The Price Wise experiment can also be enabled from the experiment page if the Test Pilot add-on is already installed. 
- However, If the Test Pilot add-on is not installed, the "Install Test Pilot & Enable Price Wise" button is not displayed on the Price Wise experiment page.
- Here is a screen recording of the issue: 

![old browser](https://user-images.githubusercontent.com/26000308/48257340-ec53d600-e41a-11e8-8a47-ddc73b5166db.gif)

**Comment by meandavejustice** [comment]
Our `isMinFirefox` test checks against the version we set for testpilot.
https://github.com/mozilla/testpilot/blob/master/frontend/src/app/config.js#L3

We can either update the min testpilot version to `63` or add some functionality to also check the min version of the experiment in the main install button also.

**Comment by johngruen** [comment]
@meandavejustice you could honestly just hardcode it at this point :)

**Comment by SoftVision-PaulOiegas** [comment]
No longer reproduces on Fx 62.0.3, verified on Windows 10 and Mac OS 10.13. You an no longer install TxP on older versions of Firefox than 63.x. Even if TxP was already installed before, the featured experiment cannot be installed from homepage or experiment details page.
