### ISSUE TITLE
Price Wise is missing a few links on details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3952]
Just noticed the [Price Wise experiment (dev)](https://testpilot.dev.mozaws.net/experiments/price-wise) doesn't have the following links in the sidebar:

- Launch tour
- Changelog
- Contribute

Maybe not a big deal, but thought I'd mention it in case we are missing something in the YAML or need to do some light tweaking.

| Price Wise | vs | Email Tabs |
|------------|----|------------|
| ![firefox_test_pilot_-_price_wise](https://user-images.githubusercontent.com/557895/48290299-380c7c80-e427-11e8-91d5-f290a9d6a04e.png) | &nbsp; | ![firefox_test_pilot_-_email_tabs](https://user-images.githubusercontent.com/557895/48290283-262ad980-e427-11e8-9886-b6d6e09e967a.png) |

/cc @chuckharmston

**Comment by chuckharmston** [comment]
These are all known. Thanks for flagging, though!
