### ISSUE TITLE
email-tabs doesn't have video_url

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#3953]
Ref: [/content-src/experiments/email-tabs.yaml](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/email-tabs.yaml)

Not sure if we need/want it for launch, but I noticed we had one for Price Wise and a handful of the other e'speriments.

/cc @johngruen

**Comment by johngruen** [comment]
closing due to extreme meh
