### ISSUE TITLE
Rework server Docker container to run under non-root user

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#398]
[The Dockerflow deployment pipeline from ops](https://github.com/mozilla-services/Dockerflow#dockerfile-guidelines) says this:

> - Set a non-root user and group app in the container and run everything as this user
>   - make the uid for the user 10001
>   - make the guid for the group 10001

But, our Docker container runs everything as root. This should be reworked.

**Comment by mostlygeek** [comment]
When installing packages / dependencies at container creation time it is ok to run as root. When we run the container it should run as the non-privileged user. I will create an issue to help clarify that.
