### ISSUE TITLE
[Experiment details] Email Tabs page wrongly mentions "Firefox Color" in the legal string under the green install button

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3984]
Issue found by @flodolo and mentioned on Slack. Logging it on his behalf.

**[Affected versions]:**
- Firefox 63.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
- Test Pilot is not installed on the used profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com page.
2. Scroll down to the available experiments cards and click on the "Email Tabs" one.
3. Observe the privacy and legal notice strings under the "Install Test Pilot & Enable Email Tabs" green button on the left.
 
**[Expected result]:**
- The "By proceeding, you agree to the terms and privacy policies of Test Pilot and the Email Tabs privacy policy." string is displayed.

**[Actual result]:**
- The string wrongly mentions the "Firefox Color" instead of Email Tabs privacy policy.

**[Notes]:**
- it seems that just the string has this issue since the link underneath correctly scrolls down to the Email Tabs Privacy notice. 
- Here is a screenshot of the issue: 

![d4c833d3-7c9a-43ad-baee-09d36289c9bb](https://user-images.githubusercontent.com/17258026/48419309-4547a500-e760-11e8-97e8-464e4b70c7c1.png)

**Comment by marniepw** [comment]
@meandavejustice is this something you can look into? thanks!

**Comment by devinreams** [comment]
Quick patch at https://github.com/mozilla/testpilot/pull/3985

I triple checked and didn't see anywhere else we had a mistaken reference..
