### ISSUE TITLE
Change logging output to conform to Dockerflow

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#401]
The [Dockerflow repo](https://github.com/mozilla-services/Dockerflow) says this about logging:

> Applications logs should be written to stdout and stderr in the [mozlog format](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=42895640). These will be sent to an Elastic Search cluster and accessible via Kibana. This feature is enabled on request. 

So, we need to change the logging setup in the Docker container to:
- [ ] Output to stdout & stderr
- [ ] Use the [mozlog format](https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=42895640)

**Comment by meandavejustice** [comment]
here is the python package for mozlog https://pypi.python.org/pypi/mozlog/3.1

**Comment by lmorchard** [comment]
Hmm, confusingly, I don't think [that mozlog package](http://mozbase.readthedocs.org/en/latest/mozlog.html) produces the same thing as this [this mozlog schema](http://mozbase.readthedocs.org/en/latest/mozlog.html). That package looks like it's specifically for formatting automated testing output, not server activity

**Comment by lmorchard** [comment]
@mostlygeek do we have any other apps (ideally using Django) that produce this mozlog format that I could look at as an example?

**Comment by meandavejustice** [comment]
hmm, weird. Might be worth opening an issue if there is a conflict in the
naming

**Comment by mostlygeek** [comment]
I rewrote part of the spec to provide some links. The [python library](https://github.com/mozilla-services/mozservices/blob/master/mozsvc/util.py#L106) is rather undocumented. Tokenserver uses it and we're able to parse the logs in Heka without any extra work.

**Comment by mostlygeek** [comment]
I dug a little deeper and standardized logging isn't a great story for python. 

However, the official documentation is available here https://mana.mozilla.org/wiki/display/CLOUDSERVICES/Logging+Standard. In a nutshell, output JSON blobs with the right keys and magic will happen. 

The schema is available here https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=42895640.

Maybe @whd can give some recommendations on what we should be done for logging since he runs that component.

**Comment by whd** [comment]
Unfortunately I don't think we have a standalone modern python library for mozlog. The python library @mostlygeek pointed to is for an old legacy format that is also supported by our decoder, but which should not be used. The only newer python app I can think of that uses the new format is autopush, which uses some custom logging: https://github.com/mozilla-services/autopush/blob/master/autopush/logging.py. So you probably have to roll your own logging that conforms to the spec or write a standalone logging library.
