### ISSUE TITLE
"Price Wise" link redirects to a placeholder page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/testpilot#4023]
**[Affected versions]:**
- Firefox Release 64.0.2 and above

**[Affected Platforms]:**	 	
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net/.
2. Click the "blog post" link from the last paragraph.
3. Observe the behavior. 

**[Expected result]:**
- You are redirected to the "blog post" page.

**[Actual result]:**
- You are redirected to https://example.com/blog-post.

**[Notes]:**
- The issue is also reproducible on Test Pilot stage server.
- The same behavior can be observed for the "Firefox Notes", "Price Wise" and "Email Tabs" links.
- Here is a screen recording with the issue:
![test pilot links](https://user-images.githubusercontent.com/19226534/51485428-b631bb80-1da6-11e9-9f54-23eb90b07e8e.gif)

**Comment by clouserw** [comment]
Notes can be seen at https://addons.mozilla.org/en-US/firefox/addon/notes-by-firefox/

**Comment by pdehaan** [comment]
Looks like Email Tabs and the blog post links are updated in [/src/index.html](https://github.com/mozilla/testpilot/blob/eol/src/index.html).
That only leaves the [placeholder link](https://github.com/mozilla/testpilot/wiki/Coming-Soon) for Price Wise:

```html
<a data-l10n-name="priceWiseLink" href="https://github.com/mozilla/testpilot/wiki/Coming-Soon">Price Wise</a>
```

**Comment by lmorchard** [comment]
Yeah, we might not have that Price Wise link for a while. The Coming Soon page was a compromise to not delay deploying the EoL site.

**Comment by marniepw** [comment]
Here's the Price Wise URL: https://addons.mozilla.org/en-US/firefox/addon/price-wise/

**Comment by SoftVision-PaulOiegas** [comment]
The link now properly redirects to the AMO page for Price Wise.
