### ISSUE TITLE
Please update production with new locales

### ISSUE THREAD

**Issue by flodolo** [mozilla/testpilot#4038]
There are currently 16 locales enabled in production (+en-US).

There are several locales that were completed but are currently not in production (nl and it were both done around Jan 21, almost two weeks ago).

Locales at 100% and missing from production: dsb, el, fy-NL, it, nl, ru.

cs, es-MX, tr are enabled in production even if not at 100%, I guess they had those strings translated.

**Comment by flodolo** [comment]
I've double checked locally, removing experiments.ftl and only keeping the [EOL strings](https://github.com/mozilla/testpilot/blob/eol/locales/en-US/app.ftl#L272-L312) in app.ftl

This is the full list of locales at 100% in these conditions: cs, cy, de, dsb, el, en-CA, en-US, es-AR, es-ES, fr, fy-NL, hsb, hu, it, nl, pt-PT, ru, sk, sl, sv-SE, tr, zh-CN, zh-TW.

I have no clue why `es-MX` is enabled in production.

**Comment by TonnesM** [comment]
cc @lmorchard Would it be possible to do a new pull/push? We have a broken and ugly Lockbox link for our locale (nl). Some more recent activity for other locales on Pontoon can be seen, so perhaps others will benefit too.
