### ISSUE TITLE
Handle hosting & signing of experiment addon XPIs

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#406]
Capturing this from the status meeting back on 2/1:

> decision: Use jpm sign for automatic signing.  Test Pilot will host the add-ons for now.  We can revisit later.

I'm interpreting this as needing these things done:
- [ ] Accept upload of experiment XPIs via Django admin, hosted from our S3 bucket
- [ ] Apply `jpm sign` with credentials dedicated to the Test Pilot site
  - can we do that automatically as a part of the Django admin? or do the XPIs need to be signed manually before upload?
- [ ] Link to those self-hosted experiment addons
- [ ] Support `updateURL` for each experiment addon from Django? 

My memory might be faulty, so let's hash this one out.

**Comment by lmorchard** [comment]
FWIW, we've also talked about just hosting these as unlisted addons on AMO. But, if I recall, the argument against was that we couldn't link to the XPI without authentication. Seems like there was also concern about the review process. Might help to jot down those reasons here if anyone else remembers better :)

**Comment by lmorchard** [comment]
This is also related to #92, which pertains to the main site addon. I think whatever we come up with for that XPI should be useful in how we handle experiment XPIs.

**Comment by lmorchard** [comment]
It looks like Activity Streams is doing their own thing in S3. IMO, we shouldn't interfere with this & should continue supporting this as long as it's how that team wants to work.

The main thing Test Pilot should do is make this easier, but not try to force a top-down One True Way unless we need to - i.e. for legal & privacy concerns. So, if we can offer a quick & convenient path to getting an addon signed & hosted via Test Pilot - that's great. But, if experimenters already have that covered, that should be great too.

**Comment by pdehaan** [comment]
@oyiptong Were we using S3 for ActivityStream as a temporary thing until we could host the add-on on TestPilot, or were we thinking of using S3 long term?

**Comment by lmorchard** [comment]
Well, we're using S3, one way or another. I think the choice is whether Test Pilot does it on behalf of experimenters, or whether experimenters manage that themselves.

**Comment by lmorchard** [comment]
One case where we might have to insist Test Pilot manages the hosting, is if we ever want to restrict access to download XPIs for access control (#364) - because Test Pilot would need to be able to issue pre-signed S3 URLs. 

But, even there, we're not sure pre-signed S3 URLs would work with the Firefox add-on update process. I think the consensus is that we should control access via config sent to experiments from the main Test Pilot addon, in turn fetched from the server. Could even be treated as a feature flag.

**Comment by oyiptong** [comment]
@pdehaan As this issue describes, we weren't sure what the final hosting situation would be.

We currently sign, host ourselves and handle the update URL, so in theory, we should be good to go if TestPilot only requires a URL from us.

What we're missing is a managed AMO API key. I think it's OK for now, but it would be something to consider long term for TestPilot.

**Comment by lmorchard** [comment]
> We currently sign, host ourselves and handle the update URL, so in theory, we should be good to go if TestPilot only requires a URL from us.

Right now, a URL is all we need. In fact, until / unless this issue is resolved, a URL is all we support :)

**Comment by oyiptong** [comment]
Heh, ok. WFM. I'll watch this issue and will be able to adapt in case things change

**Comment by clouserw** [comment]
I think we've updated our plan to ask each experiment to host their own add-on.  If they don't have a place, they can use AMO.  So...closing this.  Let me know if I'm misunderstanding the issue though.

**Comment by lmorchard** [comment]
Less work for us, if experiments can manage their own signing & hosting. We support any arbitrary URL for the `.xpi` right now. 

This was intended to be a convenience for experimenters, but would also be a hassle if they _have_ to go through us. We could always revisit later if it's handy.

**Comment by jaredhirsch** [comment]
Reopening: I think it actually makes sense for Test Pilot to abstract out the build, sign, and deploy process.

The current proposal requires experiment authors to do a lot of work that's unrelated to creating a product experiment:
- authors must have AMO accounts,
- have S3 access,
- install AWS CLI tools and jpm (might require a package.json just for the `jpm` dependency),
- get cozy with the S3 and `jpm sign` APIs,
- coordinate signing duties for vacations/sick days

None of this is a huge deal, but it is work, duplicated by each experiment, that takes away from prototyping time. Seems like a great opportunity for us to remove some friction.

What if Test Pilot exposed an API that could build, sign, and deploy an add-on? Suppose you gave it the repo name, commit SHA, and maybe a version ID (although that should be in the add-on metadata files,  either package.json or install.rdf), like this:

`$ testpilot release https://github.com/mozilla/universal-search eeaaa815`

To make it even more friendly, we could provide a web page interface to the API, basically a form restricted to FxA logins for current experiment authors. That would enable non-technical experiment owners to push new releases.

Discussed this a bit with @lmorchard and @chuckharmston in channel today, reopening to take the discussion async :-)

**Comment by meandavejustice** [comment]
Maybe the solution would be to let current addons host themselves and have this addon api feature be a backlog item. Seems more like a (very) nice-to-have

**Comment by ghost** [comment]
I don't think authors having AMO accounts (that is, using the Firefox Account we already require them to have to log in to AMO) is a big deal.  

They don't need S3 or AWS, since AMO can host the add-on.  There is already extensive documentation about how to sign add-ons using the AMO system.

I feel like the right answer is to address the concerns with using AMO rather than automating around them.  Fixing them on AMO would help the largest percent of people.

The main concern about using AMO I've heard is review time wait.  I just logged in and looked at the reviewer's dashboard for pending updates and there are 3 add-ons waiting more than a day (still less than a week), and every other add-on is measured in hours.  That is not a long time, and the AMO administrators have already suggested they are open to building other pipelines or flags for test pilot experiments.  We haven't given them any real proposals or requirements.

Are there other concerns with using AMO?

Rather than spend time working around a system that already hosts  & signs let's discuss what we'd like to see and make a proposal to the AMO team.

**Comment by lmorchard** [comment]
> They don't need S3 or AWS, since AMO can host the add-on. 

Authors can host the add-on there, but only if it's publicly listed. Otherwise, the downloads aren't public and require developer auth, which doesn't work for Test Pilot. 

But, we don't really want Test Pilot experiments reviewed by or listed on AMO. We want them mainly available from the Test Pilot site only, and managed through our opt-in agreements & metrics & feedback & etc.

> I feel like the right answer is to address the concerns with using AMO rather than automating around them. Fixing them on AMO would help the largest percent of people.

We've discussed before that patching AMO to work differently is kind of a hack when all we need is a URL, and that's what S3 is great for. 

Also, as things progress, AMO is likely to focus on WebExtensions while we may drift toward supporting temporary System Add-ons for feature experiments.

AMO isn't really the right home for Test Pilot experiment add-ons. Kind of a square peg in a round hole, IMO.

**Comment by lmorchard** [comment]
Well, we need signing from AMO, too. But, that's also something we might want to consider changing someday - i.e. if parts of Test Pilot get rolled into Firefox itself, maybe Test Pilot should be able to sign its own experiments.

**Comment by ghost** [comment]
We've decided not to do any hosting of .xpi files.

The only thing left to do in this issue is write some documentation about our recommended practice (write a script to sign and upload to S3) and/or use AMO.

**Comment by chuckharmston** [comment]
Example Makefile that builds an add-on, signs it at AMO, tags it, and uploads the build version to S3: https://github.com/mozilla/universal-search/blob/master/Makefile

**Comment by ghost** [comment]
oh @wresuolc from a couple months ago, how times change.  Now we're hosting all new add-ons (so that we can install without a warning prompt).

I have a production S3 bucket I've been putting them in manually.  We might want to do some auto-upload at some point, but I'd suggest that's a different bug instead of this giant thread.

I'm going to tentatively close this since we're also dropping django.... someone holler if there was more to do here though.  Thanks!
