### ISSUE TITLE
Gulp does not watch gulpfile.js and restart with changes

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#41]
This is an issue already when running Gulp straight on OS X host. But, when it's in a Docker container things are worse: you have to restart the container. So, it might be handy to wrap `gulp` in nodemon or something and make it restart itself when `gulpfile.js` changes

**Comment by meandavejustice** [comment]
@lmorchard Creating a label (`client-concern`)for these issue which should be moved over to (or at least kept in mind)`idea-town-app`

**Comment by meandavejustice** [comment]
cc/ @6a68

**Comment by lmorchard** [comment]
I'm just going to straight copypasta this issue over to -app
