### ISSUE TITLE
Get rid of scroll bars in addon popup UI

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#428]
There is a css issue forcing scroll.

**Comment by ktbee** [comment]
I can work on this one! Is there a screenshot I can take a look at to see the extra scroll bar?

**Comment by meandavejustice** [comment]
Awesome @ktbee! here is a screenshot.
![2016-03-11_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1844554/13715863/4fc0065c-e78c-11e5-84a5-6f4261e6543d.png)

**Comment by ktbee** [comment]
Thank you for the screenshot @meandavejustice! I haven't been able to reproduce this scrollbar however, which you can see in this screenshot:

![unable to repro scroll issue](https://cloud.githubusercontent.com/assets/7991694/13759269/21cd1226-e9f3-11e5-9be5-b7b7c109f113.png)

I'm running version 47.0a2 of the Firefox Developer Edition. Do you have any suggestions on how I can reproduce this?

**Comment by chuckharmston** [comment]
@ktbee that could be an artifact of OS X's tendency to hide the scrollbar. What's your value of this setting (in System Prefs > General)?

<img width="541" alt="screen shot 2016-03-14 at 2 45 44 pm" src="https://cloud.githubusercontent.com/assets/23885/13759369/7fe1325c-e9f3-11e5-95be-a986d7dc0502.png">

Alternately, it could be a Linux-only thing.

**Comment by ktbee** [comment]
@chuckharmston thanks for taking a look at this. I checked my OS X scroll bar preferences, and they're set to "Automatically based on mouse or trackpad." Even when I change the setting to "Always," I'm not able to repro this scroll bar. I'm traveling at the moment, but I'll check this issue on a linux machine as well once I get home later this week.

**Comment by jaredhirsch** [comment]
@ktbee I've added you as a collaborator to this repo, so I can assign this bug to you. If you still aren't able to repro the issue locally on your linux machine, it might be best just to hop on another issue, so you can get it done in plenty of time for next week's deadline.

**Comment by jaredhirsch** [comment]
@ktbee Correcting my earlier comment: the application needs to be in next week, but you have a few weeks past that to work on the contribution part (fixing a good first bug).

**Comment by meandavejustice** [comment]
Sounds like this is only visible to me. I run weird a tiling window manager and all sorts of weird junk on linux, so I'm gunna close this for now as it sounds like it's good for 99% of our audience
