### ISSUE TITLE
Create retina versions for all images in the addon

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#429]
cc/ @johngruen might want to tweak the existing icons as a part of this.

**Comment by johngruen** [comment]
@meandavejustice everything should be in the prototype, but here's what you should need (note the check images are hiding cause they're just white): 
![dh-arrow 2x](https://cloud.githubusercontent.com/assets/3323249/14185036/216cb6e6-f746-11e5-9953-880409ea181a.png)
![dh-arrow](https://cloud.githubusercontent.com/assets/3323249/14185037/217b99fe-f746-11e5-9cbd-9e1c65cf5205.png)
![small-check](https://cloud.githubusercontent.com/assets/3323249/14185052/2e6e2dca-f746-11e5-8105-09c2c076c2a0.png)
![small-check 2x](https://cloud.githubusercontent.com/assets/3323249/14185051/2e6bfb0e-f746-11e5-92aa-a9af0f75a717.png)
![copter](https://cloud.githubusercontent.com/assets/3323249/14185059/34139134-f746-11e5-9b9a-2e10a05d4b4f.png)
![copter 2x](https://cloud.githubusercontent.com/assets/3323249/14185058/341254ea-f746-11e5-8a2d-d33e3224b1f4.png)

**Comment by meandavejustice** [comment]
Thanks @johngruen
