### ISSUE TITLE
Need a way to connect WebExtension tests to the Test Pilot add-on.

### ISSUE THREAD

**Issue by bwinton** [mozilla/testpilot#433]
The current solution for communicating with the main add-on from experiments (`nsIObserverService`) won't work for WebExtensions.  There is [an API](https://developer.chrome.com/extensions/runtime#method-connect) we could use instead, but it's [not implemented yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1213473), and worse, isn't going to block the first release of WebExtensions.
![😢](http://replygif.net/i/127.gif)

But, if we can convince the WebExtensions team that we really, _really_ need this, they will probably bump it up the priority queue.  Also, maybe there are other solutions we can use in the meantime, like hitting the Test Pilot server manually…

**Comment by bwinton** [comment]
It looks like from the WebExtension side, we can use [`chrome.runtime.sendMessage`](https://developer.chrome.com/extensions/runtime#method-sendMessage).  I’m not sure what that’ll translate to on the Test Pilot add-on side, though…

**Comment by ckprice** [comment]
A quick note that product would like to include Tab Center with the go to market release of Test Pilot in April.

/edit thanks @bwinton :blush: Not required for Tab Center, but still important as noted.

**Comment by bwinton** [comment]
Fortunately, Tab Center isn't a WebExtension, however the No-More-404s extension is… (And future extensions will be, if at all possible. :wink:)

**Comment by lmorchard** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1252215

**Comment by ckprice** [comment]
I'm moving this into the current milestone to make sure we're tracking this. Wayback Machine is blocked by this bug.

**Comment by ckprice** [comment]
> See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1252215

Confirmed in #amo that this is something that will have to ride the trains. Once it gets resolved, I'll request an uplift.

**Comment by ckprice** [comment]
~~Ref 904, may want to make sure Optimizely is okay.~~

/edit WRONG BUG, thanks Les.

**Comment by lmorchard** [comment]
> Ref #904, may want to make sure Optimizely is okay.

FWIW, I think this might be more relevant to #715 & possible add-on install whitelisting

**Comment by lmorchard** [comment]
Starting to try catching myself up on the concerns surrounding this issue. 

Wondering if another approach is that we have the webextension throw metrics pings at the Test Pilot HTTP API? From there, we somehow get them into the telemetry pipeline via an alternate pathway. Maybe the Test Pilot server relays those pings on to the Telemetry servers?

Edit: Oh, but those webextension pings would probably be missing all the extra environmental context we send along with Telemetry pings from the other add-on based experiments

**Comment by ghost** [comment]
The above bugs about WebExtension <-> SDK messaging are planned to land in Firefox 50, so, we have a few months to cover.

Pinging testpilot.firefox.com sounds like a great idea.  Our logs are already set up there to get into redshift and we already have a `service` field for if we got pinged from a specific experiment.  Setting up a lightweight end-point for simple data collection is my favorite idea here. :)

Missing environment data is too bad, but we'd still collect the data we'd need to answer our questions, we just wouldn't get as much context.  Better than nothing!

**Comment by lmorchard** [comment]
Just so happens I had some code lying around from a previous PR which adds an `/api/metrics/testpilottest` resource. Seems slightly spammable, since I disabled the auth requirement. 

But, [with that PR](https://github.com/mozilla/testpilot/issues/952), a webextension should be able to POST JSON at `https://testpilot.firefox.com/api/metrics/testpilottest` and have it show up in server logs / redshift

**Comment by lmorchard** [comment]
Thinking about this some more, I've got an idea to try:
- WebExtensions can load background pages & scripts
- Background pages can include `<iframe>`s
- An `<iframe>` can be loaded from the Test Pilot site
- The main Test Pilot add-on injects a content script into pages from the Test Pilot site
- So... I think a bridge can work something like:

```
webextension -> postMessage to <iframe> in background page -> content script -> test pilot -> telemetry
```

Edit: This seems to be a dead end. The main add-on content script never gets attached in the `<iframe>` content, regardless of [the `attachTo` option value](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/page-mod).

**Comment by lmorchard** [comment]
Spent most of the day trying to figure out a way to hack together a communication bridge between a WebExtension and the main Test Pilot add-on, but just ran into dead ends. [Bug 1252215](https://bugzilla.mozilla.org/show_bug.cgi?id=1252215) will probably end up being the thing that actually works.

Until then, PR #952 and having WebExtensions send metrics pings to the server are probably the best option we have right now. 

That doesn't really help us for feature flags (#477), but maybe we can push off supporting that for WebExtensions for a bit.
