### ISSUE TITLE
Implement onboarding for individual tests

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#438]
![idea-onboarding](https://cloud.githubusercontent.com/assets/3323249/13469735/a243ca84-e076-11e5-9171-8aa46e1479b5.gif)

**Comment by lmorchard** [comment]
Hmm, off the top of my head, seems like this needs another Model alongside ExperimentDetails (e.g. ExperimentTourSteps) to contain the image/copy content

**Comment by ckprice** [comment]
Moving this to the 2016-04-22 milestone. @johngruen is this UX final?

**Comment by meandavejustice** [comment]
@johngruen did a pass at this https://people.mozilla.org/~jgruen/test-pilot/activity-stream.html
