### ISSUE TITLE
update add-on install flow

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#440]
Demo: https://people.mozilla.org/~jgruen/test-pilot/get-add-on.html

![add-install](https://cloud.githubusercontent.com/assets/3323249/13470333/b04ad14c-e079-11e5-876b-490601ea2f39.gif)

**Comment by lmorchard** [comment]
Hmm, I'm not sure the initial addon installation is something we can customize like that. It will have to go through the usual Firefox addon management process. After installation, I think we can do the doorhanger thing, though.

**Comment by meandavejustice** [comment]
We may be able to do it using `self.loadReason`
https://github.com/mozilla/testpilot/blob/master/addon/index.js#L120

**Comment by meandavejustice** [comment]
@johngruen Could i get access to your demo code?

**Comment by johngruen** [comment]
@meandavejustice 
https://github.com/johngruen/test-pilot-prototype

**Comment by meandavejustice** [comment]
thanks @johngruen
