### ISSUE TITLE
Improve static asset caching for upstream proxies

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/testpilot#443]
For example: 

```
> curl -I https://testpilot.stage.mozaws.net/static/images/firefox-logo.png
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=0
...
```

The `max-age=0` basically tells the nginx proxy to never cache the assets so we're serving out of the container/python for every request. Changing this value to something > 0 will offload the static asset serving to nginx or CDNs.

Also adding an `Etag` header and/or creating unique asset names with a long `max-age` setting would improve performance.

**Comment by lmorchard** [comment]
Going to look at this later today. But, if I don't get to it, this looks like a good starting point for enabling gzip & caching support with whitenoise in the app:

http://whitenoise.evans.io/en/latest/django.html#add-gzip-and-caching-support

Also notes further on in that page for tweaking the `WHITENOISE_MAX_AGE`. We'd need to add the appropriate env var lookups in `settings.py` on the dev side for whatever needs configured on the ops side.

**Comment by lmorchard** [comment]
FWIW, is `DEBUG` set to `True`? Those docs claim `WHITENOISE_MAX_AGE` default is `60 if not settings.DEBUG else 0` - i.e. it should be `60` if `DEBUG=False`

**Comment by mostlygeek** [comment]
For gzip, we actually let nginx do that too. I think Debug=False in stage.

**Comment by pdehaan** [comment]
I think `DEBUG` is `True` on stage (currently logging in via FxA vomits a bunch of Python/Django debug info to the screen):

![keyerror_at__accounts_login_callback_](https://cloud.githubusercontent.com/assets/557895/13512388/2b76f80c-e14f-11e5-9242-96a21fa73d60.png)

Also, that value for `ALLOWED_HOSTS` looks a bit suspect, `"testpilot.dev.mozaws.net"` for the testpilot.stage server.

**Comment by chuckharmston** [comment]
Closing due to the move to S3-based deployment.
