### ISSUE TITLE
strategy for upgrading legacy testpilot users

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#448]

**Comment by ghost** [comment]
John is working on this with Ryan starting next week.

**Comment by ckprice** [comment]
In the Test Pilot Mission Control meeting today, it was noted that this does not block our launch. Removing milestone.

**Comment by javaun** [comment]
This does not block launch. The agreed upon next step was that we'd meet w/ UAG (Gregg Lind) to understand which, if any, users are offered the upgrade.

**Comment by johngruen** [comment]
Here is the strategy: 
1. We ship an update to Old Test Pilot that uninstalls it silently. (at or around launch of new)
2. When we do an initial blog post about new Test Pilot we discuss the update.

**Comment by ghost** [comment]
Perfect.  I marked this `public launch` because it will save us confusion, I'm sure.  In fact, the further ahead of public launch, the better, probably.

/apologies for the scope creep!

**Comment by ghost** [comment]
Alright.  I have an add-on written which uninstalls the old test pilot silently.  One thing to note, is that the old add-on is not restartless, so, people will get the upgrade, have to restart, and then it'll be uninstalled (without another restart).

This isn't something that can be reversed so let's be sure we have it right.  The add-on is at http://micropipes.com/temp/d/tp.xpi if you'd like to give it a try.

Requesting sign-off:
- [ ] @javaun 
- [ ] @pdehaan 
- [ ] @johngruen

**Comment by pdehaan** [comment]
So, to clarify, is the test plan to install the old Test Pilot add-on from https://addons.mozilla.org/en-US/firefox/addon/test-pilot/?src=search, and then install evil, bizarro @wresuolc add-on from https://github.com/mozilla/testpilot/issues/448#issuecomment-205930019 and verify that both add-ons get uninstalled (after a restart)?

**Comment by ghost** [comment]
That sounds right

**Comment by meandavejustice** [comment]
Do we want to get some metrics pings on uninstalls? We may get this automatically from amo.

**Comment by ghost** [comment]
Should be automatic: https://addons.mozilla.org/en-us/firefox/addon/test-pilot/statistics/?last=30

**Comment by meandavejustice** [comment]
awesome @wresuolc

**Comment by ckprice** [comment]
We met today with @gregglind, Ilana, @clouserw 

**Decisions**
- We're not going to just silently uninstall the old add-on (amending [the original plan](https://github.com/mozilla/testpilot/issues/448#issuecomment-204559595)).
- We'll want to message some segment of existing old TP users (at least Release users, maybe other channels).
- This does not block launch.
- When we do execute, we'll want to remember to filter old add-on users who have installed the new add-on.

**todo**
- Disable new downloads for old add-on on AMO.
- Create UI/tech spec for new plan (again, doesn't block launch).

**Comment by javaun** [comment]
Some color commentary from our chat. 
- Pre-release users were auto-enrolled in the old add-on, but release was opt-in
- Of the 800k DAUs of the old add-on, approx 50% are release users and 77% EN-US [Source: AMO analytics](https://addons.mozilla.org/en-US/firefox/addon/test-pilot/statistics/?last=7)
- The eager opted-in folks of the old add-on are actually the kind of people we probably want (Fx choosers, high usage, early adopters). If we started from scratch, we'd likely end up with a similar audience.
- We shouldn't include Beta users. Studies are still forthcoming but that skews very very different.
  Ilana also made a recommendation that the DevEd audience is also probably perfect for us.

**Comment by johngruen** [comment]
@clouserw what do we want to do with this issue? close it?

**Comment by ghost** [comment]
we got strategy!
