### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#455]
Currently requesting the https://testpilot.stage.mozaws.net/favicon.ico file returns a status code of 200, but is actually the "Four Oh Four!" page.

![test_pilot](https://cloud.githubusercontent.com/assets/557895/13587168/17c53d80-e47b-11e5-95d0-6d594af7a926.png)

---

(And here's the same page in Chrome's Network tool:)

![test_pilot_-_help_build_firefox](https://cloud.githubusercontent.com/assets/557895/13587239/b512fc3a-e47b-11e5-9042-51f25e13d5f2.png)

**Comment by johngruen** [comment]
@mostlygeek do we get the favicon for free when we host in *.firefox.com?

**Comment by mostlygeek** [comment]
> @mostlygeek do we get the favicon for free when we host in *.firefox.com?

Nope. At least, nothing I know of.

**Comment by pdehaan** [comment]
If we just want the regular old Firefox logo, we can totally steal it (and anything else, like robots.txt) from [**mozilla/fxa-content-server**](https://github.com/mozilla/fxa-content-server/tree/master/app).

**Comment by johngruen** [comment]
@pdehaan 👍

**Comment by johngruen** [comment]
@lmorchard @meandavejustice [here are the icons we need](https://www.dropbox.com/sh/090rwmkg8dg0v71/AADPwGn9LIe9S25zcUbFDPloa?dl=0), not sure where they should live on the server? maybe just `testpilot/frontend`?

**Comment by pdehaan** [comment]
Missing favicons are more obvious once a user enables Activity Stream experiment and browses the Test Pilot site:

![new_tab](https://cloud.githubusercontent.com/assets/557895/14093318/d9e7d260-f501-11e5-85f6-59ef3934135a.png)
