### ISSUE TITLE
Assign every test a color-scheme

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#461]
In the new UX, every test should be assigned two hex values and an angle.

<img width="334" alt="screen shot 2016-03-08 at 12 52 15 pm" src="https://cloud.githubusercontent.com/assets/3323249/13610637/a52b3506-e52c-11e5-868b-b2446020522f.png">

**Comment by pdehaan** [comment]
Instead of a linear gradient, you could go nuts with tiles: https://github.com/qrohlf/trianglify http://qrohlf.com/trianglify-generator/

**Comment by johngruen** [comment]
@meandavejustice gonna need some help updating the django app on this one.
