### ISSUE TITLE
Bring back the auto-deploying dev server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#462]
I miss the old dev server that got bumped on each commit. (Which was killed in aptly named #404 PR):

> _"Going to retire idea-town-dev, because we're moving to a deployment model supported by ops."_

We have a stage server, https://testpilot.stage.mozaws.net/, but it currently has an old (yesterday's) build and won't let me download the signed addon (it points to a 404 page on GitHub -- see https://github.com/mozilla/testpilot/issues/244). Currently I'm not 100% certain how I can build the addon myself so I can log into stage TestPilot and check the UI.

It'd be nice if we had a:
1. An auto-deployed dev server which is updated on each commit and is always fresh, so QA can kick the tires and test stuff out.
2. A stage environment which is safe and can be promoted up to prod.
3. A prod environment to share our gift with the world.

I think we have a solid plan for 2) and 3), so I guess I'm just lobbying to get the self aware, auto-deploying dev server back so I don't need to throw up an entire Docker stack just to look at the UI.

---

@mostlygeek made the following, excellent statements earlier in IRC:

> 9:53 AM **mostlygeek:** pdehaan: did you want me to deploy the latest master to stage? 
> 9:53 AM **mostlygeek:** will that eventually make it to prod? 
> 9:53 AM **mostlygeek:** or is this just a thing to play around with? 
> 9:53 AM **pdehaan**: i just want to play around.
> 9:54 AM **pdehaan**: and yes please (re: deploy). it looks like the last 2 PRs are red, so we won't wait around for them.
> 9:54 AM **mostlygeek**: pdehaan: the stage deployment isn't really the right thing to push something to play around with
> 9:54 AM **mostlygeek**: we need a dev account for that
> 9:54 AM **mostlygeek**: or a dev thing.. 
> 9:55 AM **mostlygeek**: probably something where master is auto-pushed to it 
> 9:55 AM **pdehaan**: we used to have a dev server, but it got killed.
> 9:55 AM **pdehaan**: ok, maybe leave it for now, and we can figure out a plan on how QA can test this.

**Comment by lmorchard** [comment]
I can look into rebuilding a continuously deployed dev instance on Elastic Beanstalk again, but the point of staging is to have something stable (i.e. not changing with every master commit during active development) for QA that's staged prior to deployment to prod.

Master branch should be okay to deploy to staging whenever. It's not playing around. If we want a deployment for QA, that's the point of staging IMO. If something goes wrong there, it means we screwed up - which is what QA is meant to tell us.

**Comment by pdehaan** [comment]
Is there a way to automate the master->dev so it uses the same ops stack as stage/prod?

But yeah, even if we just push master->stage today so I can grab the bundled+signed addon and log in, that'd be super (then we can leave the auto-deploy chore for another day).

**Comment by lmorchard** [comment]
> Is there a way to automate the master->dev so it uses the same ops stack as stage/prod?

My impression is that automating those deployments has a lot of moving parts. Folks in ops haven't had the bandwidth to implement all that stuff.

So, current prod & stage process is to ping @mostlygeek for a deployment. If there's stuff you want to QA from master, we should do that as needed. (We can probably ping other folks too, but I don't have a list of alternates.)

The dev server was on Amazon Elastic Beanstalk and that was completely self-service for devs. But, for prod & staging, ops-managed hosting & deployment is a different system aimed at all the things they need to do to keep the lights on.

**Comment by lmorchard** [comment]
All that said, let's not close this issue. A dev server on a different stack can still be handy, and hopefully my first run through the setup process comes back to me :)

**Comment by lmorchard** [comment]
Adding to this - I just had [a change](https://github.com/mozilla/testpilot/commit/033999d7d0a021c50884f0b8f3a7b275eb77dc7d) work on my local machine, but fail on stage & prod. Not sure if it would fail in the same way on an elastic beanstalk dev, but probably worth a try.

**Comment by lmorchard** [comment]
Bumping this to 4/8, because I'm definitely not getting this working by Friday.

**Comment by lmorchard** [comment]
Moving this back to the 3/25 milestone, because I actually did get it working after it seemed to suddenly rise in importance.
