### ISSUE TITLE
Create mechanism to allow for content detection

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#463]
There is a request to give owned channels (about:home, moz.org) the ability to detect whether or not a user is a participant in Test Pilot. I don't know if such a thing exists (or is possible), but this issue is opened to discuss, and implement if appropriate.

**Comment by lmorchard** [comment]
Hmm, thinking out loud ahead:

We do [set `window.navigator.testpilotAddon = true;` in our `message-bridge.js` PageMod](https://github.com/mozilla/testpilot/blob/master/addon/data/message-bridge.js#L11) to indicate presence of the add-on to [the Test Pilot site](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L29). 

That only happens for pages in [an `ALLOWED_ORIGINS` whitelist](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L83), which currently [only includes the environment configured](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L76) in addon prefs (i.e. testpilot.dev or testpilot.stage.mozaws.net or testpilot.firefox.com)

So, maybe we can add a few domains to that `ALLOWED_ORIGINS` list, so they can also see the `navigator.testpilotAddon` flag? 

The danger in doing something that straightforward, though, is all those domains would also be able to send command messages to the addon - i.e. to install/uninstall experiments, etc. 

If we _just_ wanted other domains to see the flag, but not send messages, we'd have to split `message-bridge.js` into a PageMod that accepts messages for the Test Pilot site and another that just sets the `navigator.testpilotAddon` flag for other domains.
