### ISSUE TITLE
Unable to install TestPilot add-on and enter site (stage)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#467]
``` json
{"source": "https://github.com/mozilla/testpilot",
  "commit": "dfe112fd2d6151ca15f1e607652b5b6b83975ade",
  "version": "2016-03-09"}
```

&mdash; via https://testpilot.stage.mozaws.net/__version__ 

---
### Steps to reproduce:
1. Go to https://testpilot.stage.mozaws.net/ and sign in with your Mozilla email address.
2. On the "Install the Test Pilot Add-on" page, click the nice, green **[Install the Add-on]** button.
3. Click the **[Allow]** button in the doorhanger-esque popup (see **Figure 1** below).
4. Click the **[Install]** button. (see **Figure 2** below).
5. Go to about:addons > Extensions (The "Test Pilot Addon v0.4.9" should be enabled -- see **Figure 3** below).

![test_pilot_-_help_build_firefox_and_debugger_-_test_pilot_addon_and_sign_in_to_continue_to_test_pilot](https://cloud.githubusercontent.com/assets/557895/13682224/ba2c10a8-e6b5-11e5-9443-1b077fafce1f.png)
**Figure 1:** Click "Allow". I'm told this is only an issue on stage env. Currently prod server still has older build, so I test there yet.

---

![test_pilot_-_help_build_firefox_and_irccloud](https://cloud.githubusercontent.com/assets/557895/13682483/d372623c-e6b6-11e5-9789-f2538a024f9d.png)
**Figure 2:** Click **Install**.

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/13682839/7db4ecf0-e6b8-11e5-85c9-17bddf8bd16d.png)
**Figure 3:** The addon is enabled.
### Actual results

The addon seems to be enabled, but I'm stuck on the "Install the Add-on" page. Even if I go back to about:addons and set the environment to "Staging" (see **Figure 4** below), it seems stuck on the install page.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/13682859/91ed5568-e6b8-11e5-8927-2d6778b93aed.png)
**Figure 4:** The Environment is even set to Staging (oddly rendering the dropdown twice).

---

**NOTE:** I'm seeing the following in my dev tools console, which may be relevant:

```
ReferenceError: reference to undefined property window.navigator.testpilotAddon (app.js:7:7039)
```

The source is minified, and it doesn't look like we have source maps, so it's a bit tricky to dig into the minified code.

---

**NOTE:** If you go to about:addons and click the "Debug" button for Test Pilot Addon it opens a debugger that looks like thus:

![console_-_test_pilot_addon](https://cloud.githubusercontent.com/assets/557895/13682600/4ff0cdd0-e6b7-11e5-8e4d-726f35cd5e31.png)

All errors seem to look the same, apart from the first 4 having a `__proto__` of "DeadObject", and the last 2 having a `__proto__` of "TypeError". All errors seem to report as `fileName` [resource://testpilot-addon/index.js:39](https://github.com/mozilla/testpilot/blob/5477c953338a15a07eb2695019bde9952eb06236/addon/index.js#L39) and a message of:

> "can't convert undefined to object"

And thanks to the Debugger tab, here's the line in question:
![debugger_-_test_pilot_addon](https://cloud.githubusercontent.com/assets/557895/13682736/fe4bccd6-e6b7-11e5-9b06-59a850fd8932.png)

Looks like possibly `store.availableExperiments` may be `undefined` in [/addon/index.js:39](https://github.com/mozilla/testpilot/blob/5477c953338a15a07eb2695019bde9952eb06236/addon/index.js#L39). ¯\_(ツ)_/¯

**Comment by lmorchard** [comment]
Hmm, I can't reproduce... Did you happen to reload the site after installing the add-on and switching environments in prefs? I think that's something we don't handle gracefully right now

**Comment by pdehaan** [comment]
@lmorchard I've refreshed a few times, yeah. I'll try in a new profile maybe. I've been seeing some very odd jank when trying to screenshot the bug and not clicking the buttons in the doorhangers and then trying to get the addon installed. At one point I had to go into about:addons and try and kick the addon from within there.

**Comment by pdehaan** [comment]
Oddly worked in Nightly once (saw one experiment called "jk"), but it won't let me in again, even with a restart and different profile.

**Comment by cuff-links** [comment]
I too am stuck at the install addons page. 

Env. Mac OSX 10.11.1
FF 48.0a1 

I switched the env to staging (came installed with production as the default) and still cannot get into the Test Pilot application. 

I can also reinstall the add-on, over and over again.

**Comment by clouserw** [comment]
I'm also stuck on the install add-ons page but I'm trying in production.  Using Firefox Nightly on linux.  I didn't see any messages in my console.

**Comment by lmorchard** [comment]
What versions of Firefox is everyone using? We have to use Firefox Dev Edition to do addon development, so I can't say I've tried it in Nightly or Release... probably ever. I wonder if it's related to that?

**Comment by lmorchard** [comment]
Ah, never mind: I can reproduce on a fresh release Firefox profile and I just noticed the tail end of @pdehaan 's notes. I also see the undefined object error in Browser Console, and yep I think that's the problem. 

It's undefined because I haven't yet gotten into the site to get a list of available experiments, but I can't get into the site until the addon works. So, bleargh. Guess we need to look into some automated integration tests, because this doesn't show up on a well-used development setup >_<

**Comment by lmorchard** [comment]
Additionally, this makes #462 look even more important, because we're going to have a broken addon in stage & prod preventing any testing until we get another deployment. And deployments are heavy events right now, so we can't do that every time we have a master commit that fixes something.

**Comment by pdehaan** [comment]
> Guess we need to look into some automated integration tests, because this doesn't show up on a well-used development setup >_<

Activity Stream actually has a solid little setup where I can type [`npm run once`](https://github.com/mozilla/activity-streams/blob/a1bf706ec86dc57a4f009b2ca4813a19e34d2f9a/package.json#L88) and it creates the bundle/add-on and then uses [JPM to launch a new instance of FF Beta](https://github.com/mozilla/activity-streams/blob/a1bf706ec86dc57a4f009b2ca4813a19e34d2f9a/package.json#L105) with a clean profile. Once I Ctrl+C the Terminal window, my browser automatically closes.

**Comment by lmorchard** [comment]
I'll steal this from @meandavejustice, because I think he's in the thick of reworking UI stuff for the new Test Pilot design

**Comment by lmorchard** [comment]
> Activity Stream actually has a solid little setup where I can type npm run once and it creates the bundle/add-on and then uses JPM to launch a new instance of FF Beta with a clean profile

Hmm, actually we have `npm start` for that in package.json, but looks like it's hardcoded for a Linux copy of Firefox. Will tweak some things as part of this PR.

**Comment by lmorchard** [comment]
FWIW, our addon build is simpler than Activity Stream, but I made some Activity-Stream-inspired tweaks to npm scripts over in PR #470 (along with a fix to this issue)

**Comment by ghost** [comment]
Thanks!
