### ISSUE TITLE
Test Pilot title should link to the home page

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#476]
Right now the test pilot title is just an h1, we should make it a link to the most appropriate page (home if you're logged in, sign up, or get the add on)

**Comment by jaredhirsch** [comment]
@johngruen Stealing for a new contributor :-)

**Comment by johngruen** [comment]
@ktbee hey, WRT styles, no need to underline or change color or anything...just make sure `cursor:pointer`

**Comment by pdehaan** [comment]
I think this was fixed via #510. Closing.
