### ISSUE TITLE
Include ephemeral request time data in feature flag calculations

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#478]
Thinking about #468, we don't collect locale as an attribute of a user's profile or in any particular experiment installation. But, we might need locale - and potentially other things - as data to feed into conditionals for feature flipping.

Do we want to collect more things like that associated a user's profile and/or experiment installation? What sorts of things would be useful in determining segments for feature flipping?

Alternatively, is this something that more properly belongs in Firefox? That is, we never store the data, it stays in the browser - and instead we ship conditionals to the Test Pilot addon, and it calculates feature flags based on local data?

**Comment by lmorchard** [comment]
A middle way to do it that just occurred to me: Have the client send various parameters along with the request to fetch feature flags. That could include locale, RTL, etc, etc. Then, server-side conditionals can use that request-time data to decide, and not have to store it at all.

**Comment by mconnormoz** [comment]
Worth noting is that Firefox already has, and can send, both the UI locale and the geo (ISO 3166, essentially).  It's just a value in nsURLFormatter, so you don't need to duplicate any code, just make your API calls include those params (search uses this for defaults/visible engines).

**Comment by lmorchard** [comment]
Tweaked title to reflect that we shouldn't be _collecting_ & _storing_ additional information, but we can use it on the spot if / when it's available at request time to the feature flipping API

**Comment by ghost** [comment]
Chuck is working on this in issue #477 and we can evolve that spec as needed once we start using it.  :love_hotel:
