### ISSUE TITLE
What data to collect from / questions to ask of users?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#48]
[See comments in PR45](https://github.com/mozilla/idea-town-server/pull/45#discussion_r38021132). TL;DR: What data should be we collecting from users per experiment? What questions should we be asking & recording answers for?

This will determine fields added to the data model, at least. A numerical rating is in there now. Do we want to add a text field for a single comment? If we want to run surveys, that implies new chunks of server functionality to add. Anything else?

**Comment by johngruen** [comment]
@lmorchard, part of this is answered by the feedback mockups. #156 #154

**Comment by johngruen** [comment]
Also, here's a bug to to track the doorhanger/ net promoter stuff:  #221

**Comment by nchapman** [comment]
@johngruen and I discussed this and decided that specifically tracking installs and uninstalls should allow us to generate reports on most things we care about (retention, churn, active users, etc):
- Number of installs
- Number of uninstalls
- Track installs and uninstalls in a way that we can show trends
- Amount of time between install and uninstall

**Comment by johngruen** [comment]
Here's a bug for a standard engagement metric (not for mozlando) #222

**Comment by johngruen** [comment]
Hey @lmorchard, between nick's answer the issues i've listed/created here, it seems like this is probably closable? I'll let you chose what to do here.

**Comment by lmorchard** [comment]
Cool by me... we can always reopen / file a new issue if we need more work here
