### ISSUE TITLE
Wire GA events

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#481]
In [bug 1253728](https://bugzilla.mozilla.org/show_bug.cgi?id=1253728) we received our GA ID and it was added to the main template in #456.

To get the most out of GA reporting & funnel creation, we should add an [event](https://developers.google.com/analytics/devguides/collection/analyticsjs/events#overview) on every (or at least every meaningful) user interaction on the site.

/edit [Event requirements](https://docs.google.com/document/d/1SIOaZLHsMGNBNmAxphon4cxF_F07Q1ctBkU6gkP2SD0/edit?ts=56fc371c)
- [ ] create helper function to facilitate sending events
- [ ] call function for interactions

**Comment by ckprice** [comment]
Something interesting to note. We could feasibly capture feedback submissions with GA events, and aggregate/display dashboards however we want.

**Comment by lmorchard** [comment]
> We could feasibly capture feedback submissions with GA events, and aggregate/display dashboards however we want.

Does that include flowing feedback data into the same stream as our Telemetry & Heka data? Or vice versa? (See #430 asking for a consistent way to handle client & server side feedback submissions)

I'm still fuzzy on how our dashboards (#234) are going to work and where the data's going to come from. Also kind of afraid we're growing a metrics hydra here, with no single head to ask questions of - but maybe that's okay?

**Comment by ckprice** [comment]
I'm going to dig into this one (haven't worked with AmpersandJS before, so please bear with me). Just going to throw some stuff on paper here...
1. From what I can see, the files in [`/testpilot/frontend/static-src/app/views`](https://github.com/mozilla/testpilot/tree/master/testpilot/frontend/static-src/app/views) inject properties and other things into the templating in [`/testpilot/frontend/static-src/app/templates`](https://github.com/mozilla/testpilot/tree/master/testpilot/frontend/static-src/app/templates).
2. It also appears that you [can attach events through view files](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/experiment-page.js#L24), which is pretty cool.
3. Although it looks like we don't use the `data-hook` event binding everywhere (for instance [on the landing page `Get started with a Firefox Account` button](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/templates/landing-page.js#L62)). Probably only where we need something extra, which makes sense I think.
4. It looks like all views import [`/testpilot/frontend/static-src/app/views/base-view.js`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/base-view.js).
5. In [the commit to just add the GA snippet to the app](https://github.com/mozilla/testpilot/pull/456/commits/ccf3d2f6a4c26650e2603a596473ac3a0f73892e). The snippet was added up a couple levels in [`/testpilot/frontend/index.html` ](https://github.com/mozilla/testpilot/tree/master/testpilot/frontend/templates/testpilot/frontend).

So, I think this work probably wants to be contained in [`/testpilot/frontend/static-src/app`](https://github.com/mozilla/testpilot/tree/master/testpilot/frontend/static-src/app). Which means I may propose a change to the work done in `#5` above.

**create helper function to facilitate sending events**

So, I see something that resembles [a helper function in `main.js`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/main.js#L55).

Now that I'm adding another one, I could take this opportunity to refactor a bit and create a specific helper file for the AmpersandJS app (unless I'm missing an obvious place where it should go). 

Or just create an `/app/lib/all-things-ga.js` file and keep stuff there, and import it from [`/app/main.js`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/main.js), or  [`/app/views/base-view.js`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/base-view.js).

I'd bring up moving the GA ID to some kind of ENV thing, but dragons.

**call function for interactions**

I'll want to call this helper for pretty much all the things listed in the issue opening (working with Gareth to finish defining this).

I'll probably just go through each button/thing and add events (or add on to existing events) per `#2` above.

So that's my cursory look over this thing. @lmorchard @meandavejustice, please tell me if I've vastly misunderstood the site.

**Comment by pdehaan** [comment]
Not sure how common it is, but FWIW I get the following message in my DevTools console whenever I look at Test Pilot site:

> _"The resource at "https://www.google-analytics.com/analytics.js" was blocked because tracking protection is enabled. [[Learn More](https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection)]"_

Looking at my address bar's shield, it looks like I have Tracking Protection enabled.

![menubar_and_firefox_test_pilot_and_wire_ga_events_ _issue__481_ _mozilla_testpilot_and_rundetails_js_ _loads-web-react_and_1__npm_start__node_](https://cloud.githubusercontent.com/assets/557895/14055754/b7e0314c-f2a1-11e5-941e-57f7ebc9a462.png)

Your mileage may vary.

**Comment by ghost** [comment]
@ckprice I just realized :facepunch: is a facepunch and not a fistbump but :fist: looks weird.  anyway, thanks for digging into this.  Once @lmorchard or @meandavejustice sign off, let's get rid of the needs discussion label.

@pdehaan shouldn't stop us from closing out this bug.  That's an issue we (Mozilla & the internet) will need to solve on a grander scale :)

**Comment by meandavejustice** [comment]
@ckprice Your assumptions about the helper method in `main.js` is correct, that is the proper place to add the ga helper. We can leave it in that file as we only have two helpers at the moment. Then you will access it off of app like...

``` javascript
const app = require('ampersand-app');

app.sendToGa('my-event', {some: 'data'})
```

> I'd bring up moving the GA ID to some kind of ENV thing, but dragons.

We can open up a separate issue for this. We will probably just use something like this browserify transform in our build => https://github.com/hughsk/envify

**Comment by lmorchard** [comment]
> We can open up a separate issue for this. We will probably just use something like this browserify transform in our build 

Hmm, I don't think we can switch things for local / dev / stage / prod at build time - because all of those environments use the same Docker container.

Better to control that at runtime with server env vars - e.g. make a Django setting that gets included in the <head> of the HTML and picked up from there by the Ampersand app.

**Comment by ckprice** [comment]
FWIW just checked, and it looks like we use a single ID, and have GA filter things into different buckets by domain matching. 

![Image of GA](https://s3.amazonaws.com/f.cl.ly/items/450t193z0r1S2N1Q0e3s/Image%202016-03-29%20at%209.00.40%20AM.png?v=02179d21)
(need to ask Gareth to update the dev entry)

So, not sure how much the env thing is needed.

**Comment by ckprice** [comment]
Met with @garethcull today, and he provided a[ GA Requirements document](https://docs.google.com/document/d/1SIOaZLHsMGNBNmAxphon4cxF_F07Q1ctBkU6gkP2SD0/edit?ts=56fc371c) for us to reference when building these events.
