### ISSUE TITLE
Link to TOS/Policy from 'Install Add-On' prompt

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#482]
We need a link to our TOS/privacy policy on the add-on install page; somewhere near the 'Install Add-On' prompt.

Needs:
- words (or an already-existing link)
- implementation: if it's not a link, how to show? Probably just a modal is fine.

This will block our April launch.

/cc @javaun

**Comment by clouserw** [comment]
We'll cross this bridge if we have to.  Until then -> wontfix
