### ISSUE TITLE
Add-on builds result in stale code when version is not updated

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#484]
Currently, add-on signing happens [on every Circle CI run](https://github.com/mozilla/testpilot/blob/master/circle.yml#L48) - this includes PR review test runs. This is problematic, because AMO only supports signing any given version once.

That means if a PR is submitted, the code gets built & signed on initial submission with the version string in `package.json`. If add-on code changes are made in response to a review - but the version isn't changed - the old code from the initial submission is what sticks around. Our build automation [just downloads the previously signed version](https://github.com/mozilla/testpilot/commit/e4659e9351ebf45b5f227d03f42c28fd7af8b48a#diff-8894e422ed2d6af58eed4df3575eb027R1), because attempting to re-sign an already used version results in an AMO API error.

But, manually bumping the add-on version number with every edit to a PR seems problematic - both in terms of remembering to do it and in terms of arbitrary version number inflation for unreleased changes.

We could investigate a way to run `npm run sign` only when we **mean** it. That is, only when building a Docker container from master branch intended for deployment. I suspect that will really complicate our `circle.yml` file, though.

Alternatively, we could find a way to automatically vary the version string based on the code - e.g. include the git commit in the version string. That would directly tie the add-on version to code changes. Are there any drawbacks to that? Could un-reviewed / un-approved yet signed versions of the XPI get accidentally released?

**Comment by chuckharmston** [comment]
> we should find a way to run npm run sign only when we mean it. That is, only when building a Docker container from master branch intended for deployment. I suspect that will really complicate our circle.yml file, though.

I believe circle exposes an environment variable with the current branch name. Could you do this through a `release` branch?

**Comment by oyiptong** [comment]
Just curious: are you using separate signing credentials for a "production release" of test pilot?

We aren't putting the AMO API keys on third-party CI at the moment, because that would allow anyone that gets access to Travis to sign addons under our name.

**Comment by lmorchard** [comment]
> I believe circle exposes an environment variable with the current branch name. Could you do this through a release branch?

Yes, but what I mean by complication is that we need two paths for Docker container build:
1. Build without signing the addon
2. Build with signing the addon
And then, either path needs to result in Django tests being run. Maybe not huge complication, but we'd need to figure that out.

**Comment by lmorchard** [comment]
> We aren't putting the AMO API keys on third-party CI at the moment, because that would allow anyone that gets access to Travis to sign addons under our name.

We do have AMO API keys on Circle CI. So yeah, if someone did gain access to our Circle CI account, they would be able to sign add-ons under our name. They'd also be able to push server builds to Docker Hub, so we'd have lots of problems in that case.

**Comment by chuckharmston** [comment]
> Yes, but what I mean by complication is that we need two paths for Docker container build:
> 1. Build without signing the addon
> 2. Build with signing the addon
> And then, either path needs to result in Django tests being run. Maybe not huge complication, but we'd need to figure that out.

Sure. You only run `jpm sign` when the build is caused by a push to the release branch. That should be achievable with a conditional around the value of `$CIRCLE_BRANCH`. Then you only push the release branch when you **mean** it.

**Comment by lmorchard** [comment]
So, I'm kind of thinking that doing both the things can save us from some trouble: 
1. Include git commit hash in all versions, so we _never_ reuse a version even accidentally and 
2. only sign the addon when building a deploy-ready container (i.e. master branch, tagged releases)

Since devs can still run `npm run sign` on a local machine, unless we do #1 we can still end up with this problem if someone signed a local version

**Comment by chuckharmston** [comment]
Works for me!

For reference: https://circleci.com/docs/environment-variables
