### ISSUE TITLE
Logs and tracebacks when getting errors on stage/prod

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#489]
This seems less than ideal, but maybe not...

Currently I'm stuck on the homepage where I can sign in with my @mozilla email address, but it won't let me fully install the add-on and get into the site. I can't sign out, or otherwise use the site or get back to the original homepage, so I'm stuck in a dead end.

As a last ditch effort, I figured I'd try and force a signout so I could hopefully get back to the homepage, but when I go to https://testpilot.stage.mozaws.net/accounts/logout/ (stage or prod), I get a gross stack trace and what looks like a Django/Python error page with full tracebacks and stacks. I haven't fully scraped through it yet to see if we're leaking any potentially sensitive data, but it seems like something we wouldn't want to expose to users.

---

![noreversematch_at__accounts_logout__and_new_issue_ _mozilla_testpilot](https://cloud.githubusercontent.com/assets/557895/13794268/4d92e2a8-eab8-11e5-9898-b0bbb7f41a57.png)

**Comment by ckprice** [comment]
@pdehaan does this still happen? I'm unable to reproduce. Think it may have been fixed with a previous add-on update.

**Comment by ckprice** [comment]
I'm closing this. If you're still able to repro, you can re-open.

**Comment by pdehaan** [comment]
I'm still seeing this on stage: https://testpilot.stage.mozaws.net/accounts/logout/

**Comment by pdehaan** [comment]
Actually, I can't reproduce this on production (it just redirects me to the home page). Closing because "whatever".
