### ISSUE TITLE
Disable Activity Stream button sometimes leaks text

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#494]
Found in https://testpilot.firefox.com/__version__ (b2f03ce74366e7c4eae1b53c4d24a5a9c0ac083b)

``` json
{
  "commit": "b2f03ce74366e7c4eae1b53c4d24a5a9c0ac083b",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-03-16"
}
```

---

Was randomly toggling the add-on and noticed this weird state:

![firefox_test_pilot_-_activity_stream_and_activity_stream_test_plan_-_google_docs_and_firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/13826287/e5e3e654-eb73-11e5-8591-9c8f926d66da.png)

**Comment by johngruen** [comment]
@pdehaan could you do some patented @pdehaan fuzzing on master and close this guy. should be fixed now.

**Comment by pdehaan** [comment]
So far all attempts to break the label are failing, so I'm confident we've fixed it. :tada:
... But currently the link to the XPI seems to be broken, so I'll try logging into the admin site and fixing the XPI link so I can get the ActivityStream experiment installed on testpilot.dev.mozaws.net.

@johngruen We may want to work on https://github.com/mozilla/testpilot/issues/555 so we can have some clean data for the UX research on the dev server (in case of server reboot or data reset in the future). I vaguely recall you loathing my dancing banana avatar and tweaking a bunch of the data on the dev server recently.

**Comment by pdehaan** [comment]
Actually, I can enable the Universal Search add-on and verify with that longer button text and was unable to get the text to wrap, so I'm confident that this has been expertly fixed and adequately fuzzed.

![menubar_and_firefox_test_pilot_-_universal_search_and_index_js_ _src_ _loads-web-react](https://cloud.githubusercontent.com/assets/557895/14186851/37f26642-f735-11e5-8c81-f62ae3846468.png)

**Comment by pdehaan** [comment]
Fixed via #563

**Comment by johngruen** [comment]
@pdehaan, yeah that will get fixed by the broader responsive PR

**Comment by pdehaan** [comment]
@johngruen,

![](http://filmjunk.com/images/weblog/iloveyoumantrailer.jpg)

Sincerely,
@pdehaan
