### ISSUE TITLE
Implement 'Retire' flow to allow users to uninstall Test Pilot

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#499]
@johngruen provided the following mockup:

/edit 4-Apr with updated UI
![Test Pilot Retire Flow](https://cloud.githubusercontent.com/assets/3323249/14213073/05e639ce-f804-11e5-9c29-6ecbaa5aa190.gif)

Open question here is if we should capture exiting feedback (@johngruen, @javaun).

Clicking `Proceed` should:
- Disable all active experiments.
- Disable the Test Pilot add-on.
- Anonymize any identifiable user information in the system.
- Remove the user from any email lists we create.

**Comment by lmorchard** [comment]
FWIW, not sure if "retire" is applicable in this case, but: Sounds like for testing, we'll want to generate a bunch of random accounts and delete them when tests are done. Otherwise, we'll just have a pile of garbage accounts sitting around. 

@pdehaan - this might be a question for you: Do you know exactly how *@restmail.net accounts will be used and what we might need to do for cleanup?

**Comment by johngruen** [comment]
@lmorchard "retire" may not be the right language, but hopefully the concept is more or less intelligible. I'm talking to our various language gurus later, so we might have to update strings at some point.

**Comment by lmorchard** [comment]
I guess I'm wondering if we need "retire" for humans, and straight-up "delete" for testing robots (#133)?

**Comment by johngruen** [comment]
@lmorchard my understanding is that giving humans the option to retire may block on launch. Not sure about robots. I don't trust robots.

**Comment by meandavejustice** [comment]
@johngruen would you like to get the ui changes into a branch and we can collab from there?

**Comment by johngruen** [comment]
@meandavejustice sounds good

**Comment by pdehaan** [comment]
> Do you know exactly how *@restmail.net accounts will be used and what we might need to do for cleanup?
> &mdash; via https://github.com/mozilla/testpilot/issues/499#issuecomment-198454320

/summon @silne30

**Comment by ckprice** [comment]
Question: "Anonymize" what's it mean?

**Comment by ghost** [comment]
@ckprice Couple of options, depending on what @lmorchard or @meandavejustice want to do.  Usually means replacing the identifying into in the users table with anonymous@anonymous or something.

One thing to be aware of is that it _doesn't_ attempt to strip any personal info out of comments.  If a user uploads a comment with their family tree in it and then retires from test pilot, their comment would still remain (attributed to "anonymous").

**Comment by meandavejustice** [comment]
@wresuolc the "replacing with anonymous@anon" sounds like a good solution to me. Will defer to @lmorchard 's wisdom though.

I assume that our privacy policy link should cover the "uploading your family tree" issue, but opens up the question, Should we add another link to privacy policy on the feedback submission form? Might be overkill.

**Comment by ghost** [comment]
If legal hasn't asked, let's not.  No need to guess at what we might need when we've got experts right here. :)

**Comment by ckprice** [comment]
> @wresuolc the "replacing with anonymous@anon" sounds like a good solution to me. Will defer to @lmorchard 's wisdom though.

This sounds good! Just a note that this touches #505 slightly as we have to be able to remove this user from the list once they have "Retired?" from the program.

I'm going to move this one into the 2016-04-22 Milestone, as it doesn't look like it's in progress, and has some other dependencies.

**Comment by johngruen** [comment]
Retire flow has been slightly updated so the gif up top has been deprecated...here's what's up given #430 
![retire](https://cloud.githubusercontent.com/assets/3323249/14213073/05e639ce-f804-11e5-9c29-6ecbaa5aa190.gif)

You can trigger this flow by going to: http://people.mozilla.org/~jgruen/test-pilot/home.html

And see the entire state diagram here: https://www.lucidchart.com/documents/view/bc257f5b-d2f9-4e23-8c60-fdb91b274bc6
