### ISSUE TITLE
Add signed in menu to the 'Install the Add-on' Page

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#500]
Since the user is logged in, all of the [signed in menu options](http://cl.ly/1b0m030b0z2Y) should be available on this page:

![Install Add-on Page](https://s3.amazonaws.com/f.cl.ly/items/2U2h3N2C1r1L3a0H2N1G/Image%202016-03-17%20at%202.48.15%20PM.png?v=1259a24c)

Will need a bit of tweaking on the white background.

**Comment by johngruen** [comment]
This page no longer exists.
