### ISSUE TITLE
Display experiment-level Privacy and Legal Notices

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#501]
Need 1

**Where to display link?**

We're currently displaying it in the left column along with measurement data. This may turn into an arbitrary bucket for information, but the approach is the same.

![TOS](https://s3.amazonaws.com/f.cl.ly/items/272r3C073m3W0u3g0x1C/Image%202016-03-17%20at%202.53.28%20PM.png?v=b1a38be4)

Do we think there's a reason to change this approach?

**How to store and serve the information?**
1. We can create another field in admin, and hold the terms there. Then we can serve them in a simple modal (or a new, not-so-simple legal template/page).
2. We can ask each experiment to provide their own hosting for the information, and just link to it.
3. ?

**Comment by lmorchard** [comment]
Is this related to #504?

**Comment by ckprice** [comment]
> Is this related to #504?

#504 could be tangential to the first part of the request, `Where to display link?`. But is unrelated to the `How to store and serve the information?` piece. I asked John for more details on #504.

**Comment by clouserw** [comment]
This is a two part issue.  For the first part (where to display) that's in John's court and he's handling it.

For the second part, we should be storing a single URL which we link to on the page.  There isn't a strict policy on where the URL points, but for Mozilla created experiments I'd expect it to point to a privacy policy markdown document in the experiments repository.  /cc @javaun -- did you have another idea?

**Comment by lmorchard** [comment]
> For the second part, we should be storing a single URL which we link to on the page.

The Experiment model has [a "Privacy notice URL" field](https://github.com/mozilla/testpilot/blob/master/testpilot/experiments/models.py#L48) and it gets (optionally) displayed [in the left sidebar](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/templates/experiment-page.js#L31). Is there something other than this that we need?

**Comment by ghost** [comment]
thanks les! that's perfect.  We discussed this in the meeting today and that URL will be fine.  John is handling any moving that would need to happen elsewhere, which means this bug can be closed.  Thanks.
