### ISSUE TITLE
Present 'Thank You' message on all feedback submission points.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#502]
(This may want to be broken down more)

Presently when a user submits feedback, the window closes rather abruptly:

![Feedback feedback](https://s3.amazonaws.com/f.cl.ly/items/0V182O0p3k1c3J1J270G/feedbackmessage.gif?v=db37926f)

Currently the places where feedback is submitted is on the experiment detail page via the `Give Feedback` button, or after disabling the experiment.

Needs some UX love from @johngruen.

**Comment by lmorchard** [comment]
I think this might get rendered moot by [the new feedback gathering plan in 430](https://github.com/mozilla/testpilot/issues/430#issuecomment-200982042).

**Comment by ckprice** [comment]
Moot'd.
