### ISSUE TITLE
Define proper `Survey` UI behavior from toolbar doorhanger

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#503]
The toolbar doorhanger is a bit broken now:

![first step](https://s3.amazonaws.com/f.cl.ly/items/0o2g0U3C2q1b083e452H/Image%202016-03-17%20at%203.26.26%20PM.png?v=96db4947)
![second step](https://s3.amazonaws.com/f.cl.ly/items/1E0u190R442r3B2F3u34/Image%202016-03-17%20at%203.26.53%20PM.png?v=0b9b25f6)
#430 goes into handling the technical side of submissions here. This will focus on what we want the UI to look like.

/cc @johngruen @javaun

**Comment by lmorchard** [comment]
I think this might get rendered moot / totally changed by [the new feedback gathering plan in 430](https://github.com/mozilla/testpilot/issues/430#issuecomment-200982042).

**Comment by johngruen** [comment]
@meandavejustice @lmorchard here's the new survey behavior: https://people.mozilla.org/~jgruen/test-pilot/ratings-scale.html

should run as follows: 
Feedback requests appear for a random subset of users with a given experiment enabled 5 minutes into a session.

**Comment by johngruen** [comment]
@meandavejustice @lmorchard Since this is now defined, I'm gonna close this bug and open and implementation issue
