### ISSUE TITLE
Adding a `Coming Soon` blocking modal unless special query parameter is specified until launch

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#508]
With a public URL (and all our work in public) there's a chance that users will find the site. The site currently ~~allows registration from @mozilla.com email addresses~~ 404's on non @mozilla.com registrations. It may make sense to add some kind of banner to the site to warn users that things may not work quite right.

/cc @johngruen @clouserw @javaun @6a68 @lmorchard

**Comment by pdehaan** [comment]
Is there a "Not worth the effort" tag in GitHub?
I think just fixing #487 (to not 404, and instead display the "hey, we're working on it and will let you know when we ship" message is probably kosher enough).

**Comment by lmorchard** [comment]
For what it's worth, registration is _not_ limited to @mozilla.com addresses. 

Anyone can register, but only accounts registered with @mozilla.com addresses are activated automatically. Inactive users are registered, but waiting for an invitation. This was the solution we came up with, [last fall](https://github.com/mozilla/testpilot/issues/128#issuecomment-148826004), in lieu of launching a standalone splash site announcing the project.

The plan (pending implementation of #216) was to be able to later drop the curtain entirely for a public launch, activate all those inactive accounts, and send notification emails out to their owners. We could also have the option of inviting individual or small groups of users, if we wanted a more gradual roll out.

**Comment by lmorchard** [comment]
And, yeah, #487 is an unintended bug. The page at [/accounts/inactive/](https://testpilot.firefox.com/accounts/inactive/) is supposed to be our "splash / coming soon" announcement that inactive users get until the site opens up for them.

**Comment by lmorchard** [comment]
Also FWIW, we _did_ at one point have [copy on the front page that was more "coming soon" in tone](https://github.com/mozilla/testpilot/blob/dfe112fd2d6151ca15f1e607652b5b6b83975ade/testpilot/frontend/static-src/app/templates/landing-page.js#L19) - i.e. "We're still building Test Pilot! Sign up now and we'll let you know when it's ready to go!" 

But, I think we moved away from that with the Idea Town -> Test Pilot transition. "Try these features today with Test Pilot" is decidedly less in-progress-y :)

**Comment by pdehaan** [comment]
FWIW (and it ain't worth much), I vote that that the splash/coming soon page (at [/accounts/inactive/](https://testpilot.firefox.com/accounts/inactive/)) adequately solves @ckprice and @javaun concerns:

> _"It may make sense to add some kind of banner to the site to warn users that things may not work quite right."_

**Comment by ckprice** [comment]
Thanks all for the history. If I understand things correctly, once #487 is fixed, these users will be forwarded to the coming soon announcement/page. Is there a screenshot we can see of this page?

**Comment by johngruen** [comment]
@ckprice @lmorchard @javaun: so the ask from marketing was to take prod down all together.

**Comment by johngruen** [comment]
Is that too nuclear? Is it really necessary to have it up right now?

**Comment by ckprice** [comment]
> so the ask from marketing was to take prod down all together.

K, that conflicts slightly with what @javaun noted in channel. Let's regroup.

**Comment by javaun** [comment]
I don't think we need to pull it down. I haven't had a full chat w/ PMM
yet, but the concern is that signing in and getting a 404 wall is a dead
end / bad UX for users. There are probably ample mitigations to solve this,
and whatever is less work / dovetails with where we're already headed (487)
is acceptable. I'll try to get Winston early next week.

**Comment by ckprice** [comment]
@javaun any update on this? Can we close this and run with #487?

**Comment by javaun** [comment]
I'm meeting w/ Winston tomorrow morning ET. I was going to poke the edges and try to find the minimum need. Want to join @johngruen ?

**Comment by ckprice** [comment]
We talked in the triage today about putting up a gating modal for the standard URL, and use a super sneaky param to get access to the "Get Started with a Firefox Account" button. 

E.g. New user visits the site at...
- `https://testpilot.firefox.com`: user sees a coming soon modal, and is unable to continue.
- `https://testpilot.firefox.com/?butimspecial`: no modal present, user can continue.

Realized we didn't run this by @lmorchard, so would like to make sure there's no technical flags here. It also addresses concerns posted in #487.

**Comment by lmorchard** [comment]
To be clear & pedantic, even adding the `?butimspecial` param still results in 404-on-signin (#487) unless we change the email domain restriction logic. Obscures the path to reach it, but the bug is still there and will trigger for anyone not on the domain whitelist. 

(Which also means if we, for whatever reason, share the `?butimspecial` param with someone signing in with a non-mozilla email - they will hit the bug.)

**Comment by johngruen** [comment]
#537 Assigning this to @lmorchard for review

**Comment by ckprice** [comment]
Fixed in #537
