### ISSUE TITLE
Document what to do after installing locally

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#513]
Our README doesn't explain what to do after you've gotten Docker working. Might be good to provide a walkthrough with a couple of screenshots, covering stuff like:
- you need to install the add-on
- it's useful to load the dummy data
- ~~set `ACCOUNT_INVITE_ONLY_MODE` to `False` to disable the email address whitelist check~~ fixed in #514 
- clicking the log in button redirects to the fxa dev endpoint (and you need to create an account)

**Comment by ktbee** [comment]
In terms of some ways to clarify the OS X setup instructions, I thought these would be some helpful details to add:
- For the README-DOCKER instructions on how to load dummy data, it would be good to clarify that you need to exit the shell before executing the `docker exec testpilot_server_1 ./manage.py loaddata fixtures/demo_data.json` command
- For testing changes, it would be helpful to specify which test to run and what to expect if some of them fail for reasons not related to your code changes. Using the tests [at this link](https://github.com/mozilla/testpilot/blob/master/TESTING.md), I repeatedly got a headless browser error when I tried to run `npm test` despite installing slimer.js on my Mac. Running `npm run test:browser` allowed me to see test results for my code changes, but I didn't realize I needed to open a browser and go to the IP address given by the terminal until @6a68 pointed it out.

**Comment by chuckharmston** [comment]
Closing since we're getting rid of Docker.
