### ISSUE TITLE
Font error on stage when installing the Test Pilot add-on

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#515]
Found in https://testpilot.stage.mozaws.net/__version__ (b2f03ce74366e7c4eae1b53c4d24a5a9c0ac083b)

``` json
{
    "commit": "b2f03ce74366e7c4eae1b53c4d24a5a9c0ac083b",
    "source": "https://github.com/mozilla/testpilot",
    "version": "2016-03-16"
}
```

---
### Steps to reproduce:
1. Go to https://testpilot.stage.mozaws.net/
2. Sign in to Test Pilot using your LDAP email address.
3. On the "Install the Test Pilot Add-on and you're good to go!" page, open the DevTools console.
### Actual results:

> _"downloadable font: maxp: bad max_zones: 0 (font-family: "Fira Sans" style:normal weight:300 stretch:normal src index:2) source: https://fonts.gstatic.com/s/firasans/v5/VTBnrK42EiOBncVyQXZ7jxampu5_7CjHW5spxoeN3Vs.woff2"_

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/13935122/e047b95c-ef72-11e5-85f3-1611c9b7e3a7.png)
### Expected results:

Not that.

**Comment by johngruen** [comment]
https://github.com/mozilla/Fira

**Comment by ghost** [comment]
@johngruen is going to put a version of the font here that we can host ourselves and/or link to a mozilla CDN

**Comment by meandavejustice** [comment]
Thanks @johngruen and @wresuolc I'll take care of installing the font
