### ISSUE TITLE
Broken images in doorhanger when using TestPilot dev server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#527]
Found in http://testpilot-dev.us-east-1.elasticbeanstalk.com/__version__ (9bf2838358cfb7001ed54122406e9c9b9968e0c9)

``` json
{"version": "", 
  "source": "https://github.com/mozilla/testpilot", 
  "commit": "9bf2838358cfb7001ed54122406e9c9b9968e0c9"}
```

---
### Steps to reproduce:
1. Go to http://testpilot-dev.us-east-1.elasticbeanstalk.com/ and sign sign up/in.
2. Go to about:addons and make sure your Test Pilot add-on is configured to point to Dev (testpilot-dev.us-east-1.elasticbeanstalk.com)"
3. Once the addon is installed, click the choppy icon in the tool bar area.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14026316/8b1ddab2-f1af-11e5-96dd-30b7e6fc726d.png)
### Actual results:

![mozilla_firefox_and_revive_the_elastic_beanstalk_dev_server_by_lmorchard_ _pull_request__524_ _mozilla_testpilot_and_revive_the_elastic_beanstalk_dev_server_by_lmorchard_ _pull_request__524_ _mozilla_testpilot](https://cloud.githubusercontent.com/assets/557895/14026281/5664522e-f1af-11e5-92b9-b2478591cb86.png)

**Figure 1:** Broken images.
### Expected results:

Non-broken images.

**Comment by lmorchard** [comment]
I think I _just_ fixed this one in parallel with you filing it :) Though, it's possible it may need a browser restart to refresh the URLs in the addon - I'm not sure off the top of my head how often the addon requests that API data

**Comment by pdehaan** [comment]
You're the best, @lmorchard!

![add-ons_manager_and____github_com___2_223__-_peterdehaan_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/557895/14026438/1b06c8dc-f1b0-11e5-9cd9-8307428d222e.png)
