### ISSUE TITLE
Active experiments don't display description in door hanger

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#529]
Found in http://testpilot-dev.us-east-1.elasticbeanstalk.com/__version__ (9bf2838358cfb7001ed54122406e9c9b9968e0c9)

``` json
{"version": "", 
  "source": "https://github.com/mozilla/testpilot", 
  "commit": "9bf2838358cfb7001ed54122406e9c9b9968e0c9"}
```

---
### Steps to reproduce:
1. Go to http://testpilot-dev.us-east-1.elasticbeanstalk.com/ and sign up/in.
2. Activate the Universal Search add-on.
3. Open the Test Pilot door hanger via the toolbar.
### Actual results:

The Universal Search experiment doesn't have a 1-line description, and instead just says "active".

![firefox_test_pilot_-_universal_search_and_1__pdehaan_pdehaan_____zsh__and_automatically_add_vendor_prefixes_based_on_caniuse_by_openjck_ _pull_request__138_ _mozilla-services_push-dev-dashboard](https://cloud.githubusercontent.com/assets/557895/14026911/5e71f2f2-f1b2-11e5-967c-5d7dbdf10046.png)
### Expected results:

Retain the 1 line description, and say "Active" somewhere else (or just stick with a green outline around the thumbnail or something).

**Comment by ckprice** [comment]
Related: #503

**Comment by johngruen** [comment]
Closing for #565
