### ISSUE TITLE
Unable to enable the Activity Stream add-on on Dev server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#534]
Found in http://testpilot-dev.us-east-1.elasticbeanstalk.com/__version__ (9bf2838358cfb7001ed54122406e9c9b9968e0c9)

``` json
{"version": "", 
  "source": "https://github.com/mozilla/testpilot", 
  "commit": "9bf2838358cfb7001ed54122406e9c9b9968e0c9"}
```

---
### Steps to reproduce:
1. Go to http://testpilot-dev.us-east-1.elasticbeanstalk.com/ and sign up/in.
2. Go to the [Activity Stream](http://testpilot-dev.us-east-1.elasticbeanstalk.com/experiments/activity-stream) experiment page.
3. Click the [Enable] button.
4. Wait.
### Actual results:

The spinner button says "Enabling..." but add-on never enables. I just ate lunch and came back 30m later and it's still not enabled yet.
I don't see anything in my DevTools Console or Network tabs indicating it failed, or had any issues.

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/14029208/17cb3d8e-f1be-11e5-9c64-73fa6c4865c7.png)
### Expected results:

This seems Activity Stream (and Tab Cinema) specific. The Universal Search add-on enabled within seconds.

**Comment by lmorchard** [comment]
FWIW, the experiments on the dev server right now are all fake data, and there are no actual add-ons behind the entries.

**Comment by lmorchard** [comment]
Oh, yeah, except for the Universal Search one which I think points to an ancient version on someone's people.m.o account.

**Comment by johngruen** [comment]
@lmorchard just discovered this is the case after adding a link to the real activity stream add-on. The add-on installs , but doesn't register with the test pilot.

This blocks user testing on the dev box.

![screen_shot_2016-03-28_at_5_16_33_pm](https://cloud.githubusercontent.com/assets/3323249/14090687/c6549c08-f509-11e5-923f-aad8336f14cf.png)

**Comment by pdehaan** [comment]
Seeing same behavior here. It looks like Activity Stream is getting installed (verified in about:addons), but for some reason the "Enabling" state never completes.

**Comment by lmorchard** [comment]
>  The add-on installs , but doesn't register with the test pilot.

This is because the "Addon Id" in admin did not match the `<em:id>` in the add-on's `install.rdf`. It's different for every add-on and has to match exactly, because that's how the system identifies experiments. Took a look in the addon & updated the value, seems like things work now

**Comment by johngruen** [comment]
@lmorchard ah...all looks well on my end. I think this means we can close this issue.

**Comment by lmorchard** [comment]
I also just filed #547, because looking up those `<em:id>` values is a pain and I always forget I have to do it :)

**Comment by pdehaan** [comment]
FWIW, I'm still seeing this issue for the Tab Center addon (on testpilot.dev.mozaws.net).

**Comment by lmorchard** [comment]
> FWIW, I'm still seeing this issue for the Tab Center addon (on testpilot.dev.mozaws.net).

That's because the URL to the Tab Center .xpi is fake data - http://example.com

**Comment by pdehaan** [comment]
Yeah, I'm thinking we're missing some defensive TestPilot code around this. I'm seeing this again today on ActivityStream add-on (probably due to the data refresh and the XPI URL has reset to "example.com"), and my install button is stuck in the "Enabling..." state, but I'm seeing this in my iTerm window:

> 1459448624340 addons.xpi  WARN    Download of http://example.com/ failed: [Exception... "Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [nsIZipReader.open]"  nsresult: "0x8052000b (NS_ERROR_FILE_CORRUPTED)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: AddonInstall.prototype.loadManifest< :: line 5468"  data: no] Stack trace: AddonInstall.prototype.loadManifest<()@resource://gre/modules/addons/XPIProvider.jsm:5468 < TaskImpl_run()@resource://gre/modules/Task.jsm:315 < TaskImpl()@resource://gre/modules/Task.jsm:276 < createAsyncFunction/asyncFunction()@resource://gre/modules/Task.jsm:250 < AddonInstall.prototype.onStopRequest()@resource://gre/modules/addons/XPIProvider.jsm:5790

I'm not certain which bowels of the code that is getting thrown from, or if is even something we can wrap something in a `try..catch` block, or otherwise detect if the XPI is unreachable for whatever [possibly valid] reason (S3 being down, etc).

So yes, this current data/URI is bad, but we should probably "Fail Better(tm)".

**Comment by pdehaan** [comment]
@lmorchard Not sure if there is anything actionable left on this. Can we close it out?

**Comment by lmorchard** [comment]
Not much we can do about bad data, no. There's not a way for the addon to know whether a particular URL is or isn't a good XPI
