### ISSUE TITLE
Implement quit experiment/thank you flow

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#536]
Since we're redirecting to surveys, we need to thank people first then ask them to take a survey on uninstall.

**Comment by ckprice** [comment]
This might be informed by the new feedback gathering plan in #430.

**Comment by johngruen** [comment]
here's the flow in gif form: 
![disable thanks](https://cloud.githubusercontent.com/assets/3323249/14210268/39815466-f7f6-11e5-8dd0-819e8913934d.gif)

also you can see the state diagram here: https://www.lucidchart.com/documents/view/bc257f5b-d2f9-4e23-8c60-fdb91b274bc6

and go through the install/uninstall flow here: https://people.mozilla.org/~jgruen/test-pilot/activity-stream.html

**Comment by ckprice** [comment]
Moving this to the next milestone.

**Comment by pdehaan** [comment]
@johngruen Is this complete? Here's what it currently looks like when I uninstall Universal Search experiment on testpilot.dev.mozaws:

![firefox_test_pilot_-_universal_search](https://cloud.githubusercontent.com/assets/557895/14801529/ac1b552e-0afe-11e6-969d-de90de2931de.png)

**Comment by lmorchard** [comment]
Yeah, actually I think this is done. (if not, let's re-open and describe what should be different from what we have now)
