### ISSUE TITLE
Add ability to see version info on all test pilot deployments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#544]
This is something FxA has in place. I found it quite helpful to instantly check what is deployed where, especially as we spun up new instances. 

example: https://accounts.firefox.com/ver.json

**Comment by chuckharmston** [comment]
https://testpilot.dev.mozaws.net/__version__
https://testpilot.stage.mozaws.net/__version__
https://testpilot.firefox.com/__version__

**Comment by johngruen** [comment]
whelp, there you go
