### ISSUE TITLE
There is no redirect to /experiments when test pilot add-on installed

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#545]
On http://testpilot.dev.mozaws.net/ I download the add-on and on install there is no redirect to http://testpilot.dev.mozaws.net/experiments

This blocks user testing.

**Comment by johngruen** [comment]
![screen_shot_2016-03-28_at_5_22_27_pm](https://cloud.githubusercontent.com/assets/3323249/14090738/1c1a1294-f50a-11e5-9e85-684b003d8a9d.png)

**Comment by pdehaan** [comment]
@johngruen What if you hit "Reload" in the browser?

**Comment by johngruen** [comment]
@pdehaan yep, that works.

**Comment by johngruen** [comment]
Actually seeing this behavior on Prod as well, i guess i never noticed because i'm always fiddling with where my add-on is pointing. Hopefully @meandavejustice in flight PR will mitigate this, but maybe we should keep this open until that gets resolved. I think Sharon can include a 'reload' in the pilot user testing script.

**Comment by lmorchard** [comment]
Yeah, this is not a thing we've implemented yet. I keep forgetting about it, but I think it's going to be a part of #440 & #540. Took a peek in the PR and it looks like there's code in there that should do the trick

**Comment by meandavejustice** [comment]
Yes, #540 takes care of this.

**Comment by meandavejustice** [comment]
fixed in #540
