### ISSUE TITLE
Now Active label doesn't animate very smoothly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#546]
This is weird because it looks "Not Great (tm)" on my laptop, and when I create an .MOV via QuickTime (but when I convert to GIF, it looks slightly better -- so it's a bit difficult to capture in the wild).

![2016-03-28 14_52_16](https://cloud.githubusercontent.com/assets/557895/14091371/bb624044-f4f4-11e5-92a4-ea861e7e470b.gif)

**Comment by johngruen** [comment]
@pdehaan, i noticed that too but then had a snack and took a nap...let's file this under 'i'll tweak thing and see what i can do'
