### ISSUE TITLE
Auto-extract experiment details from add-on package and/or update.rdf

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#547]
The "addon id" field of an Experiment has to match the contents of `<em:id>` in the `install.rdf` in an `.xpi`. It would be nice if the admin could peek in the `.xpi` and auto-extract that value, because it can be a pain to dig up manually sometimes.

**Comment by pdehaan** [comment]
Not sure if there is anything else we can auto-extract from the XPI, like `version` or `description`.

I imagine it could get a bit annoying if (as an experiment maintainer) I need to remember to log into Test Pilot to bump the version number each time we deploy a new XPI to S3.
Although I guess it could be equally annoying to write some cronjob on Test Pilot to query all the XPIs and check for version number changes.

:8ball:

**Comment by meandavejustice** [comment]
This is defined in our `package.json` in the key `name` https://github.com/mozilla/testpilot/blob/master/addon/package.json#L3

**Comment by chuckharmston** [comment]
The current version is also in update.rdf, which is web-hosted and wouldn't require extraction from an XPI.

**Comment by chuckharmston** [comment]
I don't think this is relevant anymore, given the move to flatfiles. Closing.
