### ISSUE TITLE
Enable HTTPS on testpilot.dev.mozaws.net

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#548]
Now that we've moved testpilot.dev.mozaws.net (per #542), we should probably consider forcing HTTPS (and reject plain HTTP traffic).

Currently if I go to https://testpilot.dev.mozaws.net/ I get a sad page saying:

> ## The connection has timed out
> 
> The server at https://testpilot.dev.mozaws.net is taking too long to respond.
> - The site could be temporarily unavailable or too busy. Try again in a few moments.
> - If you are unable to load any pages, check your computer's network connection.
> - If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by lmorchard** [comment]
Thanks for filing this! I meant to create this issue as a followup but then got distracted by something shiny. I think this is something we need, though I don't know how yet off the top of my head. 

(And having a DNS alias in front of the actual Elastic Beanstalk server _should_ make it easier to point it instead at whatever SSL front end we can use from AWS or elsewhere.)

**Comment by lmorchard** [comment]
FWIW, @mostlygeek shouldn't have anything to actually do here, except maybe point me in the direction of what we do for SSL on *.dev.mozaws.net servers in AWS. Assuming there's a wildcard cert there already, I can do the actual config & such once I've figured out where the bits & bobs are

**Comment by lmorchard** [comment]
I think I've found [where to start in the EB doco](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https.html). But, I also think starting the process may disrupt availability for the UX research we want to do on the dev server. So, we should hold off on this issue until it's okay to have some extended downtime there and possibly wipe data (at worst).

**Comment by pdehaan** [comment]
Ah, on that note, why are we doing UX research on the always-changing testpilot.dev.mozaws.net server?

Shouldn't we create a new "ux-research" branch and auto-deploy a new server to elastic-beanstalk or EC2 from there? I'd imagine it would be less risky to have a dedicated testpilot.ux.mozaws.net server running which we infrequently update from a special branch so the UX research is always stable and unchanging.

**Comment by lmorchard** [comment]
Yes, that's #525, but I haven't had time to get to it, yet. So, dev's better than trying to do it on stage or prod.

**Comment by lmorchard** [comment]
This is going to be done when we start using testpilot-static.dev.mozaws.net as dev proper
