### ISSUE TITLE
Experiment icons are difficult to see in doorhanger

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#549]
Found in http://testpilot.dev.mozaws.net/__version__ (cbc87ed04e7ca7982f41428422f54e0a4b3f2cc6):

``` json
{ "commit": "cbc87ed04e7ca7982f41428422f54e0a4b3f2cc6",
  "source": "https://github.com/mozilla/testpilot",
  "version": ""}
```

---
### Steps to reproduce:
1. Log into http://testpilot.dev.mozaws.net/experiments and make sure you have the Test Pilot add-on installed and configured for testpilot.dev.mozaws.net.
2. Click on the Choppy icon in the toolbar.
### Actual results:

![menubar_and_firefox_test_pilot_and_firefox_test_pilot_and_install_rdf_and_activity-streams-latest__1__xpi](https://cloud.githubusercontent.com/assets/557895/14092580/caeae3ba-f4fc-11e5-99c1-ad605606e681.png)
**Figure 1:** White on almost-white.
### Expected results:

A bit more contrast.

**Comment by meandavejustice** [comment]
@johngruen Should we just add our gradient behind these?(feel free to assign back to me once you reply)

**Comment by pdehaan** [comment]
Or see if we can dynamically set the SVG fill color using CSS (https://css-tricks.com/cascading-svg-fill-color/). That way we could set inactive icons to black and active icons to green, or something.

**Comment by johngruen** [comment]
@meandavejustice https://people.mozilla.org/~jgruen/test-pilot/main-doorhanger.html how's that?

**Comment by meandavejustice** [comment]
@johngruen Looks great, I'll take it from here
