### ISSUE TITLE
Inconsistent height for experiment contributors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#550]
Found in http://testpilot.dev.mozaws.net/__version__ (cbc87ed04e7ca7982f41428422f54e0a4b3f2cc6):

``` json
{ "commit": "cbc87ed04e7ca7982f41428422f54e0a4b3f2cc6",
  "source": "https://github.com/mozilla/testpilot",
  "version": "" }
```

---
### Steps to reproduce:
1. Sign in and go to http://testpilot.dev.mozaws.net/experiments/activity-stream
2. Look at the list of contributors.
### Actual results:

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/14093118/60a391ba-f500-11e5-8404-715ae19b4071.png)

I'm noticing that if a contributor has a tagline ("Designer", or "{web,mad,computer} scientist") then it almost takes up almost 2x vertical space as users without taglines.

You can see from the above screenshot that Mr Gruen takes up 102px height.
But if we inspect Mr Chapman, it only takes 67px (which makes his name look vertically centered):

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/14093166/c116b612-f500-11e5-8890-f04cfa966f8c.png)
### Expected results:

We should either compress the space between the contributor's name and tagline, or maybe just force a min-height of 102px.

**Comment by johngruen** [comment]
This got resolved somewhere
