### ISSUE TITLE
Follow up on Pontoon integration with Test Pilot for localization

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#551]
Now that we have a prod server, I think it should be easier to close the localization loop with Pontoon & L20n. Let's do that! I think the loose ends include:
- [ ] Contact Pontoon team again to get Test Pilot added to their system
- [ ] Ensure we properly accept localizations from Pontoon
- [ ] Add some additional locales
- [ ] Ensure the end-to-end flow is acceptable to localizers and we're on their radar

Not sure whether this blocks initial public launch, or whether we want to get this in the immediate future thereafter.

**Comment by lmorchard** [comment]
Filed a bug with the Pontoon project to push this along:
https://bugzilla.mozilla.org/show_bug.cgi?id=1280410

**Comment by chuckharmston** [comment]
Added this to TXP-15.

**Comment by chuckharmston** [comment]
#1688 is related.

**Comment by chuckharmston** [comment]
I believe that all the remaining work in this is contained in https://bugzilla.mozilla.org/show_bug.cgi?id=1280410

I'll keep this open until we're finished.

**Comment by chuckharmston** [comment]
Everything is set up and working in Pontoon; just waiting on @peiying2 to flip the switch.
