### ISSUE TITLE
Unstyled "Sign up" view appears if a User was manually created in Django admin instead of via signing up from FxA

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#553]
This is probably an edge case no one will really see, but it's worth fixing at some point:
- Create a new User from the Django admin with a real email address
- Try signing in via FxA with that email address
- You'll get an un-styled "Sign up" view with no good way to continue into the site

Normally, the first sign-in from an unknown FxA ID results in 1) the auto-creation of a User record with the email address from FxA and 2) the auto-creation of a "Social Account" record linking the User record to the FxA ID. So, on next sign-in, the FxA ID will automatically login with the User record.

But, if that User was manually created - it didn't get a corresponding "Social Account" associating it with an FxA ID. So, the system thinks the FxA ID is trying to sign up for a new account, but with an email address that appears in an existing User record. And email addresses are unique per User record. 

But, the "Sign up" view that appears in this case is ugly and fairly useless.

So... we should probably either 1) disable that sign up view & display an error message, or 2) quietly associate the FxA ID with the existing User that matches the email address FxA sends.

**Comment by johngruen** [comment]
We can close this when we drop django

**Comment by chuckharmston** [comment]
Closing since we're getting rid of Django.
