### ISSUE TITLE
Refresh demo_data.json with up to date info

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#555]
So we can stop losing things when instances are rebuilt. And generally probably good to poke at this thing every couple of months.

Ref: [/fixtures/demo_data.json](https://github.com/mozilla/testpilot/blob/master/fixtures/demo_data.json)

**Comment by pdehaan** [comment]
:+1: to marking this "faux-critical" so we can have consistent data on dev/stage/prod for testing.

**Comment by pdehaan** [comment]
Ref: #493

**Comment by ckprice** [comment]
https://testpilot.dev.mozaws.net has been updated with the new freshness. Will use that as base.

**Comment by lmorchard** [comment]
Copying over a comment from #493 since it seems to make sense here too:

I'm not sure `demo_data.json` should actually match any particular environment. Data will differ between prod, stage, and dev depending on what kind of tests / research we want to run there. 

`demo_data.json` is mainly there to offer some sample data to exercise features during local dev, not to replicate what might be in production. I don't think we should spend effort to try to ensure it stays in synch reflecting prod, just that it has enough data to trigger all the site features and/or special cases

**Comment by meandavejustice** [comment]
I think we should make a practice of updating demo_data.json when adding a new field or changing data shape. Just as we have to change the shape of data in our tests to get them to pass when we make changes to a model. This is probably a given, but that is my only opinion

**Comment by lmorchard** [comment]
> I think we should make a practice of updating demo_data.json when adding a new field or changing data shape.

Yes, this. Update it to exercise features, not to match any deployed environment.

**Comment by ckprice** [comment]
This is still on me, but won't be this week.

For new fields it seems pretty straight forward from the testing I've done. For example, `gradient_start` isn't currently in `demo_data.json`, but just adding it to the file automagically saves it to the DB (tested with `docker exec testpilot_server_1 ./manage.py loaddata fixtures/demo_data.json`).

As far as getting the fieldname, I guess just troll through [`testpilot/experiments/migrations/`](https://github.com/mozilla/testpilot/tree/master/testpilot/experiments/migrations) unless there's a more elegant method.

**Comment by lmorchard** [comment]
For what it's worth, there's also `./manage.py dumpdata` which does the opposite of `loaddata`. The problem with that, though, is it's the firehose of _all_ data in the database. You can pare it down and prettify it with options (`dumpdata --help`), but it's best to open the fixture and a data dump side-by-side and selectively copy things over to the fixture from the raw dump.

**Comment by johngruen** [comment]
hey @ckprice this seems to have become a little more important with the recent addition of our friends at softvision. Could you take a look at this some time soon.

**Comment by lmorchard** [comment]
[Just commented over on the PR](https://github.com/mozilla/testpilot/pull/1111#issuecomment-234326663), but tl;dr for this issue: I think `demo_data.json` is the wrong mechanism for QA content purposes. It's meant to exercise features in local development along with unit testing, and shouldn't necessarily aim to exactly reflect current experiment content on prod. Sometimes, it should even have stuff in it that we're not using yet in prod and might not use for awhile.
