### ISSUE TITLE
Localize the Test Pilot add-on

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#557]
THere's HTML content in the add-on, now. We should start using l20n to localize it, if possible.

**Comment by meandavejustice** [comment]
https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/l10n

**Comment by lmorchard** [comment]
That tutorial doesn't use l20n, though. It uses `sdk/l10n`. If we're l20n on the front end, we should figure out how to use it in the add-on too. That way, we're not splitting localizations between `*.l20n` and `*.properties` formats

**Comment by meandavejustice** [comment]
Here is an example from activity-streams https://github.com/mozilla/activity-streams/pull/429/files

**Comment by ckprice** [comment]
Strings in the add-on will have to be localized ("View all experiments", "New experiment", etc) for our German launch in Q4. We recently landed a big localization PR (#1708), not sure if any of that touched the add-on, but pinging this issue in case it didn't. /cc @chuckharmston

**Comment by johngruen** [comment]
@chuckharmston @ckprice I will file a follow up when i hear final confirmation from Winston. We will probably hand localize the add-on via the SDK API for the near term and then figure out a better solution going forward.

**Comment by chuckharmston** [comment]
@ckprice it wasn't, and this bug won't land in this sprint.

Without a lot of engineering work, we won't be able to use Pontoon for this; strings will have to get added manually. So the sooner we can get the German translations necessary, the sooner we can start testing this. I'm not sure who to talk to about that.

**Comment by johngruen** [comment]
@chuck I can coordinate any german strings we need with the German team

**Comment by ghost** [comment]
We chatted about this briefly on IRC.  We can just support .properties files in the add-on and pontoon will work fine.  This should be straight forward.  You can see Min Vid doing this at https://github.com/meandavejustice/min-vid/commit/4341c32e7e2212c1ca5f008bd0859c7defc6f489 (although note that the .properties files need to be in /locale/%LOCALE%/whatever.properties instead of what min vid is doing.

**Comment by lmorchard** [comment]
Just tweaked the title to get us less snagged on the literal l20n issue (or maybe just me, because I was scratching my head since March)

**Comment by chuck** [comment]
Hi folks, just a note that I'm @chuck, not the Chuck that works on this project. :)

**Comment by chuckharmston** [comment]
Sorry about that, Chuck! Great name though. Solid. Sounds dependable.

**Comment by johngruen** [comment]
My bad, I guess i just need more Chucks in my life!

**Comment by april** [comment]
@chuckharmston Sure, but does this @chuck _also_ answer to Chuckles?

**Comment by pdehaan** [comment]
We've reached peak Chuck.

**Comment by bittin** [comment]
haha ey Chuck can you tell me when i can start translate this on Pontoon ?
:D

**Comment by chuckharmston** [comment]
@bittin soon, possibly as soon as today! We're tracking that [on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1280410).

**Comment by lmorchard** [comment]
> although note that the .properties files need to be in /locale/%LOCALE%/whatever.properties instead of what min vid is doing.

How come? Looks like min-vid is using the standard `sdk/l10n` path pattern of `locale/%LOCALE%.properties`, [which appears to be hardcoded in the lookup code](https://github.com/mozilla/gecko-dev/blob/master/addon-sdk/source/lib/sdk/l10n/properties/core.js#L29). Do we have an example of an add-on where this path can be changed?

Alternatively, we _could_ try doing a build step before jpm that copies files around, but that seems ooky.

**Comment by lmorchard** [comment]
Another wrinkle: The add-on loads content about experiments from `api/experiments.json` - which is generated only in its original `en-US` locale straight from YAML. 

The translations for this content will be in `.ftl` format. Seems like we'll need L20N either in the add-on to read these localizations - or in the content build chain to generate JSON resourced with pre-localized content.

On the other hand, most (all?) of what we display are experiment titles. And I don't think we want those localized. So, maybe this is okay?

**Comment by lmorchard** [comment]
Started looking into / hacking on this a bit out of curiosity, might as well take it for now

**Comment by ghost** [comment]
> How come? Looks like min-vid is using the standard sdk/l10n path pattern of locale/%LOCALE%.properties, which appears to be hardcoded in the lookup code. Do we have an example of an add-on where this path can be changed?

https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website shows the format pontoon wants.  @mathjazz will have answers to questions if something is hardcoded

**Comment by ghost** [comment]
https://github.com/mozilla/outofdate-notifications-system-addon/tree/master/addon/outofdate-notifications%40mozilla.org is in pontoon.  It looks like they are overriding the locale defaults in chrome.manifest.  Is that something we can do?  We can ask Pontoon to support the SDK recommended format, but it's not something they will get to for a while.

/cc @meandavejustice because he is hitting this in min vid also.

**Comment by lmorchard** [comment]
> It looks like they are overriding the locale defaults in chrome.manifest. Is that something we can do?

Both the Test Pilot add-on and min vid are using the add-on SDK and `sdk/l10n`. The path patterns are hardcoded in the loader in the SDK module, as far as I can tell. No overrides in chrome.manifest.

Looks like the outofdate system addon is not SDK-based. It's [bootstrapped](https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions) and [uses a different l10n mechanism altogether](https://github.com/mozilla/outofdate-notifications-system-addon/blob/master/addon/outofdate-notifications%40mozilla.org/bootstrap.js#L75) - i.e. [nsIStringBundleService](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIStringBundleService). Looks like there are [docs for using this in boostrapped add-ons](https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions#Localization_%28L10n%29).

So, we _could_ probably skip using the SDK's l10n stuff & rewrite all this to use nsIStringBundleService. That seems like a bit of run around to change some paths, though. And it affects l10n in _all_ SDK add-ons - would be nice if we had a way to handle l10n using the usual module.

**Comment by lmorchard** [comment]
Easier hack to try for now: Let's put the .properties files in a Pontoon friendly location in the repo for now, and require a build task to move them into the SDK add-on friendly location before add-on build.

**Comment by ghost** [comment]
Thanks @lmorchard .  Bug filed for Pontoon to support the SDK format @ https://bugzilla.mozilla.org/show_bug.cgi?id=1315820
