### ISSUE TITLE
Implement random survey behavior

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#566]
Here's the prototype: https://people.mozilla.org/~jgruen/test-pilot/ratings-scale.html
Here's the state diagram: https://www.lucidchart.com/documents/view/bc257f5b-d2f9-4e23-8c60-fdb91b274bc6

**Comment by meandavejustice** [comment]
Researching how we are going to handle this today. Investigating if we can use some of the existing UI from heartbeat https://dxr.mozilla.org/mozilla-central/source/browser/components/uitour/UITour.jsm#1096

**Comment by lmorchard** [comment]
<strike>Oh, so wait: This particular star rating feedback point is _not_ done through SurveyMonkey? I thought the new plan was that _all_ feedback was going to be collected that way, by launching a new tab with a survey URL.</strike>

<strike>Where do we send this rating for collection, and how are we displaying / analyzing it? Maybe via Telemetry? If so, I think we'll need to update the [README-METRICS doc](https://github.com/mozilla/testpilot/blob/master/docs/README-METRICS.md) to cover it and work with the data pipeline folks</strike>

**Comment by lmorchard** [comment]
I think this ends up being a question for @rayborn / @MattGrimes:

Hmm, looking at the state diagram and [430](https://github.com/mozilla/testpilot/issues/430#issuecomment-204534763), I think this _does_ open a new tab with a SurveyMonkey URL - and the star rating is passed as a parameter in that URL.

Assuming this is the case, we'll need some kind of template for that survey URL. A query parameter name, at least.

**Comment by lmorchard** [comment]
@meandavejustice As for the UI... It's been awhile since I hacked on XUL stuff like that. But, once upon a time, I used a notification box from an SDK addon that looked a little like the prototype. 

Not sure if this is a red herring, [but here's the code I used to make it appear](https://github.com/lmorchard/fireriver/blob/master/lib/main.js#L369). And, here's [the notificationbox doco on MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/notificationbox), though it looks more ancient than my add-on. Not sure if it's easily customizable without descending into the XUL dungeon.

(Edit: Oh, hmm. "However it is possible to use only buttons and a label there." So, that might be a dead-end)

**Comment by meandavejustice** [comment]
Thanks @lmorchard this is great feedback, I'll take a look at these and see if they will work for us

**Comment by meandavejustice** [comment]
I've got the notifications working thanks to @lmorchard 's snippet. Polishing and hooking up to SurveyMonkey before opening up a pr. Progress can be viewed here https://github.com/mozilla/testpilot/compare/master...meandavejustice:566-random-survey

**Comment by meandavejustice** [comment]
Just about finished up with this. Two last questions before I open a PR:
1) what are the time intervals we want to show these on? I currently have 2 days, then 1 week, then 3 weeks, then 1 month and a half.
2) How should we choose which experiment is surveyed. Do we actually want it to be random? it currently is.
3) Should each experiment have a separate survey per time interval?

Only other thing holding this up is getting an account with SurveyGizmo setup, which I should have by tomorrow.
cc/ @johngruen @ckprice

**Comment by ckprice** [comment]
Thanks Dave - I'll get you answers on these.

**Comment by meandavejustice** [comment]
After talking with Matt_G:

It sounds like we should have something on the server which will select a subset of our users to participate. From the addon we will hit our api, probably `/api/me`, to see if the current user has been selected. It was also mentioned that each experiment should have its own separate survey per interval (see 3 about). Here is the log from irc. http://logs.glob.uno/?c=testpilot#c3979

```
14:01   Matt_G  how are you currently doing sampling? You pick a random percentage of users at each of those specified time intervals?
14:15   JSON_voorhees   Trying to get an answer back on that now
14:16   JSON_voorhees   The current implementation (just as a sample) will grab a random experiment to survey at each of the time intervals, 2 days, 1 week, 3 weeks, 1month and a half
14:16   JSON_voorhees   Yes today/tomorrow works :) thank you Matt_G
14:18   Matt_G  JSON_voorhees: I think I need to better understand the sample rate. So the TP addon running locally picks a random experiment at each of those intervals and then asks the user to provide feedback?
14:18   Matt_G  that assumes you install more than one experiment on the same date?
14:19   Matt_G  We might want to do it by experiment. So regardless of how many concurrent experiments you are running, if you installed experiment X you are eligible for the HB sample at each of those intervals
14:19   Matt_G  and then select randomly from that population (depending on population size)
14:22   JSON_voorhees   I'm +1 to getting a survey for each experiment at all of those intervals
14:22   Matt_G  and if you are only eligible at each interval (but not necessarily selected) it will cut down on fatigue
14:23   JSON_voorhees   right
14:23   JSON_voorhees   How do we do the selection?
14:23   JSON_voorhees   is that just a random selection on the server?
14:23   Matt_G  yeah
14:23   Matt_G  random by users currently online that fit the selection criteria
14:24   Matt_G  which in this case would be "have experiment x and have used it for exactly Y days"
14:24   JSON_voorhees   right
14:24   Matt_G  if population size is really small we might want to prompt everyone at those intervals
14:24   JSON_voorhees   We don't currently have 'online status' but it should be fine without that
14:25   Matt_G  yeah, that's fine
14:25   JSON_voorhees   We should come up with a number or percentage of users to shoot for
14:25   Matt_G  but assuming we can get 500-1000 responses at each interval we should be good
14:25   Matt_G  yeah that all depends on overall population size
14:25   JSON_voorhees   right
14:25   Matt_G  so we'll need to tweak it likely
14:26   Matt_G  for desktop release it's like .00001% daily sample
14:26   Matt_G  with like 10% response rate (which is actually pretty high for surveys)
14:27   JSON_voorhees   Thank you
14:27   JSON_voorhees   That is helpful
```
