### ISSUE TITLE
Make it more obvious what the number of active users means on the experiment page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#570]
Currently it isn't super obvious what the "2" means next to the profile image. Not sure if we want a tooltip or something explaining that it's the current active number of users.

<img width="361" alt="firefox_test_pilot_-_universal_search" src="https://cloud.githubusercontent.com/assets/557895/14295283/de5cb760-fb29-11e5-9838-fc3ad9cf3d11.png">

**Comment by meandavejustice** [comment]
:+1: to adding at least a title attribute

**Comment by johngruen** [comment]
I think I have something for this...stay tuned.
