### ISSUE TITLE
Update the version of UniversalSearch XPI that's currently on dev

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#571]
Apparently the version being served by testpilot.dev.mozaws.net is a couple months old, so we should check the XPI path to make sure it's pointing to the latest version.

**Comment by pdehaan** [comment]
@chuckharmston says that the version on stage should be recent, so it may be a simple copy/pasta.

**Comment by chuckharmston** [comment]
Thanks for filing this!

**Comment by lmorchard** [comment]
It should just be a quick copy & paste in the Django admin. Most of us should have access to that admin.

But, dev is currently being used for UX user testing, so I'm really hesitant to touch it for any reason until that's complete. Can someone paste the current XPI URL in this issue's description and maybe @johngruen can update it?

**Comment by lmorchard** [comment]
Also, FWIW, to save too many future issues filed against dev server data - dev should not be expected to have real up-to-date data. It matters for prod and less so for stage, but dev should be expected to have complete garbage at any particular moment unless we've set it up for some particular testing (like the UX testing right now).

**Comment by ckprice** [comment]
> Also, FWIW, to save too many future issues filed against dev server data - dev should not be expected to have real up-to-date data. It matters for prod and less so for stage, but dev should be expected to have complete garbage at any particular moment unless we've set it up for some particular testing.

Agreed. But we used it today in a demo, so this was a special case. I've updated the dev django admin anyway.

**Comment by lmorchard** [comment]
> Agreed. But we used it today in a demo, so this was a special case. I've updated the dev django admin anyway.

Was it a demo unrelated to UX testing? Probably okay, as long as everyone involved knows what's happening (I didn't). 

Until / unless we have multiple dev servers, we should be really careful about what's being used for what & when so we don't possibly monkey wrench parallel efforts. Might have been a problem if we were doing some destructive tests or troubleshooting when it was expected to be working for a demo or research
