### ISSUE TITLE
Replace Firefox logo with TestPilot specific logo in TestPilot header

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#573]
Do we want to replace the generic Firefox logo with a Test Pilot specific Choppy or hovercraft logo?

<img width="930" alt="firefox_test_pilot_-_universal_search" src="https://cloud.githubusercontent.com/assets/557895/14296016/0189da94-fb2d-11e5-87dc-77813468fa6d.png">

**Comment by johngruen** [comment]
No
