### ISSUE TITLE
Add-on should be automatically set to the appropriate env on install

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#580]
This is sort of a nit, but it makes user testing and debugging the add-on install flow quite difficult.

**Comment by lmorchard** [comment]
Need to think about this one. As far as I know, the add-on doesn't have any way to know what the appropriate env is or from where it was downloaded. 

And, until it's set to an environment, the site content has no way to tell it anything. We could bake the environment into the build, but env-specific builds defeats the purpose of the dev/staging/prod flow (i.e. testing a build that should eventually end up on prod).

Best we could probably do is have it listen for page loads on all known envs and auto-switch to the last env visited. But, that doesn't help before the add-on is installed, and means you'd need to refresh the install page

**Comment by lmorchard** [comment]
One other idea: Maybe we can peek at browser history on install, and look for the last visit to a known environment? That _should_ be the install page the add-on just came from

**Comment by chuckharmston** [comment]
Is there any way the build script can look for an environment variable that circle sets when building the package, and overwrites the appropriate value in `dev-prefs.json`?

**Comment by lmorchard** [comment]
`dev-prefs.json` only applies with you're launching a new browser profile with `npm run once`, not during build or when you're clicking through the site to install in user testing
