### ISSUE TITLE
version info not set on dev server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#584]
Possibly not relevant, but thought I'd post for giggles.

Currently if you go to http://testpilot.dev.mozaws.net/__version__ you see something like the following:

``` json
{ "version": "",
  "commit": "a41e42424096277f7fa0504baf5bca046b9ae346",
  "source": "https://github.com/mozilla/testpilot" }
```

As you can see, the `version` is empty. We can still figure it out by looking up the commit SHA, but this is a bit inconsistent with the way stage and prod handle the /__version__ endpoint.

**Stage:** https://testpilot.stage.mozaws.net/__version__

``` json
{ "version": "2016-03-30-1",
  "commit": "a4eb4b37a92e3d9779881e058dc32964785640d7",
  "source": "https://github.com/mozilla/testpilot" }
```

**Production:** https://testpilot.firefox.com/__version__

``` json
{ "version": "2016-03-30-1",
  "commit": "a4eb4b37a92e3d9779881e058dc32964785640d7",
  "source": "https://github.com/mozilla/testpilot" }
```

**Comment by lmorchard** [comment]
We don't have versioning for dev, just commits as they happen & get auto deployed

**Comment by lmorchard** [comment]
(it's also possible prod & staging will be missing a version someday, if/when we get to continual deployment there too)
