### ISSUE TITLE
Design email template for new experiment notifications

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#589]
Ref: #505

Design is by us, coding the template is by marketing.

This does not necessarily block launch, but I am adding it to our milestone immediately after launch.

/cc @bniolet1

**Comment by ckprice** [comment]
Closing this, as the assets have been handed off.

**Comment by jaredhirsch** [comment]
@ckprice Is there a bugzilla bug to track the work marketing is doing?
