### ISSUE TITLE
Implement a non-flexbox based splash page for browsers that don't support flexbox

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#593]
We're using the shit out of flex box, but maybe occasionally somebody's browser won't support it. Might be nice to use modernizr or similar to route people to a non-flexy splash page that tells them that Test Pilot is only supported in the latest Firefox. 

BTW support looks like: 
![screen shot 2016-04-12 at 8 18 49 am](https://cloud.githubusercontent.com/assets/3323249/14459688/5b21181a-0087-11e6-9498-a35a7b407fcf.png)

**Comment by ghost** [comment]
"meh" -- @johngruen
