### ISSUE TITLE
Addon download button broken

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#597]
addon installation was broken when we switch to `<button>` from `<a>` in this commit https://github.com/mozilla/testpilot/commit/00a8d90be21758ce6672d1ffc0e0949a87c6df91

**Comment by meandavejustice** [comment]
Sign in button is also broken. Basically all of the links from that pr are busted.

**Comment by ckprice** [comment]
! I can't reproduce.

**Comment by ckprice** [comment]
Uhg, yeah it's not clicking through with private browsing.
