### ISSUE TITLE
Make sure redirects work to individual experiments if you're not signed in

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#602]
I can't get this to work currently, but it may be related to the [temporary] query string gate on the index page.

I want to link directly to an experiment (ie: http://testpilot.dev.mozaws.net/experiments/tabcenter) but I'm not logged in. It'd be nice if Test Pilot redirected me through the proper FxA flows and then dumped me back on the Tab Center experiment page instead of on the homepage.

This would also be pretty useful for the ![](https://img.shields.io/badge/available_on-Test_Pilot-0996F8.svg) badge so we can point to specific experiments instead of the generic homepage.

**Comment by lmorchard** [comment]
This is kind of an interaction with how the site intentionally works right now: Anonymous users are not allowed to navigate into experiment detail pages right now. So, they end up redirected to the home page. Then, they can sign in. We can probably fix this one along with that, if/when we decide to change that product decision

**Comment by ckprice** [comment]
Closing this in favor of #419.
