### ISSUE TITLE
Change GA code to be run as a side effect.

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#604]
Remove `window.location = url` snippet in our handling of GA and implement as a side effect.

a quick solution was added in #603

**Comment by lmorchard** [comment]
Adding this to public launch blockers, because a fix for #642 seems to depend on it.

**Comment by lmorchard** [comment]
Removed from launch blockers because it turns out not to be a dependency

**Comment by meandavejustice** [comment]
Do we still want to change the way `app.sendToGa` works? It seems to be working alright for us. Are we still worried about `ampersand.history`?
