### ISSUE TITLE
Launch Test Pilot: remove query string gate & INVITE ONLY code

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#605]
Our launch date is May 10th (Tuesday).
- [ ] Remove query string gate.
- [ ] Remove INVITE ONLY code for @mozilla.com emails on production.
- [ ] Create final production tag and deployment bug [Ops].

(anything I'm missing?)

~~@mostlygeek~~ @relud considering we have some Ops dependencies, can we get this into the Ops pipeline, and have everything land on **Monday May 9th**, with someone from Ops on-hand for emergency pushes throughout the day? How best to accomplish/request this?

/edit Ops contact will be Daniel Thorn for May 9/10.

**Comment by ckprice** [comment]
Regrouped with Benson/Travis. Benson will be unavailable May 9th/10th, but Travis will assign a TBD secondary contact. I'll update this bug with that contact when it's available.

**Comment by ckprice** [comment]
Updated bug to note that @relud will be our Ops contact for May 9/10.

**Comment by lmorchard** [comment]
FWIW, this can/should probably be split into separate issues:
- Removing the query string gate is a code change that needs doing before the next deploy
- _Disabling_ the invite-mode code is an env var switch we should ask ops to perform as part of deployment - i.e. [ACCOUNT_INVITE_ONLY_MODE=False](https://github.com/mozilla/testpilot/blob/master/testpilot/settings.py#L158)
- _Removing_ the invite-mode code is a more involved clean up task that we could punt until post-launch
- Final production tag & deployment bug seems redundant as a separate issue, I guess (i.e. file the issue to file the bug to deploy the site)

**Comment by ckprice** [comment]
> FWIW, this can/should probably be split into separate issues:

Done. Closing.
