### ISSUE TITLE
Experiment with updated content on landing page based on user research

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#606]
Meeting with John/Javaun/Sharon on Monday to discuss.
- [ ] Updated copy/UI saved to a branch.
- [ ] Option 1: have the experimental content merged and available on [`http://testpilot.dev.mozaws.net/`](http://testpilot.dev.mozaws.net/).
- [ ] Option 2: use the tech in #525 to spin up a disposable dev instance (@lmorchard to comment on availability of this).

**Comment by ckprice** [comment]
After discussing with Javaun/Sharon, @johngruen is going to work on this today/tomorrow to get some changes in for another round of UR.

**Comment by johngruen** [comment]
Closed via #625
