### ISSUE TITLE
TestPilot icon in Developer Edition is difficult to see in dropdown menu

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#607]
Ref: #320

Edgiest of edges. Icon looks great in dark theme, but gets a bit obscured if the icon overflows into the dropdown menu.

![activity_stream_and_firefox_test_pilot_-_tab_center_and_can_t_see_the_find_menu_with_tab_center_ _issue__34_ _bwinton_verticaltabs_and_building_pull_requests_-_travis_ci](https://cloud.githubusercontent.com/assets/557895/14577933/7198779a-0330-11e6-86f5-d250a2d29b4c.png)

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/14577940/9fb1451c-0330-11e6-9a9c-2cd0578d532f.png)

**Comment by chuckharmston** [comment]
> Edgiest of edge cases

Your new job title in Phonebook.

**Comment by pdehaan** [comment]
The second screenshot is funny in that there are _**three**_ hamburglar style icons in the toolbar.
1. "Show your bookmarks"
2. "Activity Stream"
3. "Open menu"

**Comment by ghost** [comment]
Closing this in favor of #719
