### ISSUE TITLE
Do we want to report engagement events for random experiment surveys?

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#608]
Our heartbeat surveys report a couple different engagement events to telemetry [example](https://dxr.mozilla.org/mozilla-central/source/browser/components/uitour/UITour.jsm#1166). Do we want to do something similar in our random surveys? refs #566

**Comment by lmorchard** [comment]
No, I don't think so - at least, not right now. We don't have plans to set up a Telemetry pipeline like Heartbeat, not sure if we want to send our data to their pipeline.

**Comment by lmorchard** [comment]
FWIW, [this is all the Telemetry stuff we have in the works](https://github.com/mozilla/testpilot/blob/master/docs/README-METRICS.md#data-collection-details) so far. Accepting more/different data via Telemetry is a process that involves [bugzilla bugs like this](https://bugzilla.mozilla.org/show_bug.cgi?id=1255182) to get the pipeline set up.

**Comment by meandavejustice** [comment]
Thanks @lmorchard Should I leave this open as a question for down the road?

**Comment by meandavejustice** [comment]
After meeting today with matt grimes. It looks like we will want to do this. Mostly for the "dismiss" action.

**Comment by johngruen** [comment]
@meandavejustice I actually don't know what you mean by 'random surveys' here. Closable?
