### ISSUE TITLE
Simplify addon/index.js

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#610]
At the time of creating this issue `addon/index.js` is 527 lines long. There are some things that could easily be pulled out into separate modules in `lib/`. Comments should also be audited as a part of this effort.

**Comment by lmorchard** [comment]
Been thinking about this a little bit, too, but haven't had time to chase things down. 

One big thing I'd like to see happen is to move most of the initialization stuff scattered across random spots throughout `index.js` and move it to `init()` functions in modules - basically like what I did with [`Metrics.init()`](https://github.com/mozilla/testpilot/blob/master/addon/lib/metrics.js#L29) that gets [called in `exports.main`](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L505). Then, `exports.main` can be a clearer table-of-contents of what happens on startup.

**Comment by meandavejustice** [comment]
I like what you did in `Metrics.init` and `exports.main`. My dream would be to have the entire file just pull things into `exports.main` and kicked off from there. But that dream may be unattainable.

**Comment by johngruen** [comment]
@dannycoates @meandavejustice can we close this given recent changes?

**Comment by dannycoates** [comment]
I think this is an ongoing effort. I don't know if it makes sense to keep this bug open or not though. I'll defer to @meandavejustice since he opened it :)

**Comment by meandavejustice** [comment]
Let's keep it open, We've gotten it a lot nicer, but `addon/index.js` is still pretty big.

**Comment by lmorchard** [comment]
Yeah, no, this is not done. A few things off the top of my head yet to do:
- [ ] Move AddonManager & add-on management stuff into a submodule.
- [ ] Move environment management stuff into a submodule.
- [ ] Unit tests for everything for bonus points

Really, IMO, index.js should boil down to a screen or so of initializing everything at startup and tearing everything down on shutdown.

We could file separate issues for these things, but maybe keep this one open to track the overall effort. There might be more things we can clarify / split out as we go

**Comment by chuckharmston** [comment]
Proposal for an end state: a very, very thin version of Django's `apps` functionality:

```
const modules = [
        Metrics,
        WebExtensionChannels,
        SharePrompt,
        ToolbarButton,
        ExperimentNotifications,
        SharePrompt
];

exports.main = options => {
        modules.forEach(module => {
                module.setup(options.reason, settings);
        });
};

exports.onUnload = reason => {
        modules.reverse().forEach(module => {
                module.teardown(reason, settings);
        });
}
```

If we refactor settings into its own module, we can even drop that from the `setup`/`teardown` signatures and let each import it independently as necessary without having to worry about circular requires.
