### ISSUE TITLE
Make sure all the things are GA'd

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#615]
We gave GA an initial pass in #577.

This issue is opened to make sure all of the functionality landed since then are also wired correctly.
- [x] #614 retire flow
- [x] #438 onboarding
- [ ] #609 subscribe/unsubscribe to emails
- [x] #611 surveygizmo

**Comment by lmorchard** [comment]
We should think about adding this as a concern to every new feature. I'm not sure what our GA strategy is, what we want to measure, etc. This stuff should also probably be documented in [docs/README-METRICS.md](https://github.com/mozilla/testpilot/blob/master/docs/README-METRICS.md) in terms of what we specifically measure and why, both for transparency and so we're all on the same page about the GA strategy

**Comment by ckprice** [comment]
We're keeping track of some of these things in the [GA Reqs document](https://docs.google.com/document/d/1SIOaZLHsMGNBNmAxphon4cxF_F07Q1ctBkU6gkP2SD0/edit?ts=56fc371c). Once this is cleaned up we'll be sure to add to the readme.

**Comment by meandavejustice** [comment]
@ckprice I'm going to try and get this finished up today. #438 #609 and #611 are done, but none of them included a ping to GA. To finish this up. I'm going to go through the GA reqs doc linked above and make sure we have the calls in proper places and update readme-metrics.

**Comment by ckprice** [comment]
Closed via #690.
