### ISSUE TITLE
TypeError: document.querySelector(...) is null

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#616]
Randomly spotted this in the Browser Console while looking at #\613.

The line in question is [./testpilot/frontend/static-src/app/views/landing-page.js:60](https://github.com/mozilla/testpilot/blob/e31466bc9c47778e7943f87bd60c082996ce1c30/testpilot/frontend/static-src/app/views/landing-page.js#L60):

``` js
document.querySelector('.button.default').classList.remove('state-change');
```

---

![browser_console_and_http___testpilot_dev_8000_static_app_app_js_and_1__docker-compose_up__docker-compose_](https://cloud.githubusercontent.com/assets/557895/14657968/9e623c44-0645-11e6-9145-4ba3e5f91bf7.png)

**Comment by johngruen** [comment]
I changed the button to primary with the most recent style changes...fix incoming

**Comment by Trupti-R** [comment]
I am getting this error (TypeError: document.querySelector(...) is null) again on firefox 58.0.2 . I have two json addons jsonlite and jsonvich . Not sure if it is a firefox issue or one of the add ons causing this . Could you please help ?
