### ISSUE TITLE
Create privacy notice and terms of service pages

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#619]
URLs
- `/privacy-notice/`
- `/terms-of-service/`

Mock up

![Privacy policy/TOS page](https://s3.amazonaws.com/f.cl.ly/items/0W3I383E1B1g2j0b2Y0a/Image%202016-04-20%20at%201.12.06%20PM.png?v=27e5c321)

Links
- On the landing page (underneath the `Get Started with a Firefox Account` button)
- Footer

**Comment by johngruen** [comment]
@ckprice @lmorchard easy enough to template these out, but where are we storing the ToS/PN

**Comment by edwindotcom** [comment]
activity stream has it's own PN specific language - how do we want to support that?

**Comment by lmorchard** [comment]
Peeking at this issue and a little confused now... what do we need to do?
1. Create one privacy notice & one terms of service page for Test Pilot in general? (i.e. hardcoded page templates for the site, no content in database admin)
2. Create a privacy notice & terms of service page for each experiment, with associated content fields in admin? (i.e. we'd host the copy for those pages)
3. Use the existing per-experiment privacy notice URL we have right now and add a terms of service URL? (i.e. experimenters would host their own pages with that copy)

Or, some combination of the above?

**Comment by johngruen** [comment]
@lmorchard basically we need need number one for now. At some point we'll need an l10n story, but that can wait. 

@edmoz each experiment has a PN URL field that should link back to it's respective repo. You can fill these in in the django admin

**Comment by johngruen** [comment]
@ckprice do we have content for these bad boys?

**Comment by ckprice** [comment]
Per email from Javaun, we're good to keep the Test Pilot PN/TOS in the repository somewhere so we have a history. Also, this is blocked by final signoff of the PN/TOS (hopefully next week).

**Comment by meandavejustice** [comment]
If no one gets to this by tomorrow morning, I will be setting up the templates, l20n, etc so we will be ready once we get legal docs.

**Comment by johngruen** [comment]
@meandavejustice hold of for today, we are having a meeting with the lawyers to hash this one out tonight.

**Comment by johngruen** [comment]
I will post the results here after.

**Comment by johngruen** [comment]
@meandavejustice so Legal uses their own l20n process b/c they need lawyers to do lawyer-ly translating. Ultimately we'll move all legal copy into their big repo where this l20n happens, but for now, we might do something like this.
1. Make markdown files in testpilot/docs for the TOS and PN
2. add a gulp task to convert markdown to HTML pages with a dest of ./testpilot/frontend/templates/testpilot/frontend
3. when the client gets built these will be served from firefox.testpilot.com/terms-of-service.html and firefox.testpilot.com/privacy-notice.html

**Comment by meandavejustice** [comment]
@johngruen Sounds good, I'll get a pr open today

**Comment by ckprice** [comment]
Final documents ready
- [Privacy notice](https://docs.google.com/document/d/14HB8hPnuH5YlO3HtZeIATmFCMIhiHIPBNEgWN66XkDQ/edit)
- [Terms of service](https://docs.google.com/document/d/1KoE8wYDI-fyXpnqlQQSJAXcDwlxtkHkA69wCdnmn6EY/edit)

Note: in the PN, you'll see some _Learn more_ strings. These are meant to initiate a drop down that reveals the sections underneath it [(Ref)](https://www.mozilla.org/en-US/privacy/firefox/). If this is too tricky, it's not required.

**Comment by ckprice** [comment]
@meandavejustice are you still okay with taking this one?

**Comment by pdehaan** [comment]
I converted it to Markdown in https://gist.github.com/pdehaan/b855855af732ac0632ad6eddee8b0c6a
which may save you a whole 3 minutes.

Not sure what a good gulp markdown library is these days. I was hoping to avoid [**marked**](https://nodesecurity.io/advisories/101).

Actually, [**remarkable**](https://www.npmjs.com/package/remarkable) is pretty good, looks active, and has a solid looking gulp task, [**gulp-remarkable**](https://www.npmjs.com/package/gulp-remarkable):

``` js
const md = require('gulp-remarkable');

...

gulp.task('legal', function legalTask() {
  return gulp.src('legal/*.md')
    .pipe(md({
      remarkableOptions: {
        html: true,
        xhtmlOut: true,
        breaks: true,
        linkify: true,
        typographer: true
      }
    }))
    .pipe(gulp.dest('legal_html'));
});
```

**Comment by meandavejustice** [comment]
@ckprice yeah, won't be a problem.

**Comment by johngruen** [comment]
@meandavejustice make sure you update these links as well
![screen_shot_2016-05-04_at_11_27_45](https://cloud.githubusercontent.com/assets/3323249/15019300/7ed49898-11eb-11e6-8f3f-355a4054f04d.png)
