### ISSUE TITLE
logged-in landing page with idea town install check

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#62]
- if idea town not installed, show an install button
- if it is installed, show a placeholder list of experiments (we've already got this)

**Comment by meandavejustice** [comment]
[You will need to trigger the loaded event](https://github.com/mozilla/idea-town-addon/blob/master/stub-content/index.js#L39)
[and listen for this event](https://github.com/mozilla/idea-town-addon/blob/master/index.js#L82)

**Comment by jaredhirsch** [comment]
Fixed by #73
