### ISSUE TITLE
Odd v-scrolling on "Test Pilot installed!" page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#620]
Found in http://testpilot.dev.mozaws.net/__version__ (6b009172185f98271ce8163e24b65e266379da63):

``` json
{ "version": "",
  "commit": "6b009172185f98271ce8163e24b65e266379da63",
  "source": "https://github.com/mozilla/testpilot" }
```

---

By complete accident I noticed that when you sign up for Test Pilot, you end up on the "Test Pilot installed!" page, and you can scroll vertically and a Firefox logo appears beneath the fold.

![firefox_test_pilot_and_canceled_event___tab_center__launch_status_checkin___wed_apr_20__2016_12_30pm_-_12_45pm__pdehaan_mozilla_com__-_pdehaan_mozilla_com_-_mozilla_mail_and_irccloud_and_1__docker-compose_up__docker-compose_](https://cloud.githubusercontent.com/assets/557895/14691282/3ebb50ee-0705-11e6-829b-84bff6b4965d.png)

**Comment by johngruen** [comment]
Sneaky sneaky
