### ISSUE TITLE
Inconsistency in the `Let's go` doorhanger

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#622]
This thing doesn't always drop for me. Below is what should happen after you `Install add-on`.

![Let's go doorhanger](https://s3.amazonaws.com/f.cl.ly/items/1r0e2l130Z2G3I101e3u/Image%202016-04-20%20at%207.55.38%20PM.png?v=4919b9d3)

But there are times when it doesn't happen for me.

I actually noticed this a bit ago, but haven't been able to reproduce reliably. Still can't reproduce, but filing this anyway, in the hopes others who have notice this will bravely step forth.

**Comment by pdehaan** [comment]
I too have occasionally noticed that as well sometimes.
Haven't found reliable repro steps (like it disappears because I was interacting with the other doorhanger, etc), but next time I notice it I'll check my devtools console and browser console.

**Comment by johngruen** [comment]
Yeah i see this too, i think it's down to all of us fussing with where the add-on is pointing all the time. Nevertheless, it's probably a good idea to make the logic here less clever and just always show the install doorhanger once if the add-on is installed.

**Comment by ckprice** [comment]
Going to move this over to #654. Moving over assignment and label.
