### ISSUE TITLE
Visiting the page on a non-Firefox browser should prompt you to download Firefox

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#624]
And not present the Install Add-on button.

![non fx](https://s3.amazonaws.com/f.cl.ly/items/0q3r1M3x3O2f230r0g3g/Image%202016-04-21%20at%2010.11.45%20AM.png?v=5929622c)

**Comment by johngruen** [comment]
@ckprice how did you get to that page? You shouldn't be able to get to the firefox account sign in from the front page.

**Comment by ckprice** [comment]
STR:
1. Be on Chrome.
2. Visit http://testpilot.dev.mozaws.net/?butimspecial.

**Comment by johngruen** [comment]
@ckprice cannot reproduce

**Comment by johngruen** [comment]
@ckprice do you have your user agent string in chrome modified?

**Comment by ckprice** [comment]
Hmm, don't think so. moz.org seems to detect me okay.

![moz.org non Fx](https://s3.amazonaws.com/f.cl.ly/items/2W323V312d0h1b080Y2B/Image%202016-04-21%20at%201.43.05%20PM.png?v=7b6c9c76)

**Comment by johngruen** [comment]
@ckprice can you console log ur user agent for me?

**Comment by johngruen** [comment]
`navigator.userAgent`

**Comment by ckprice** [comment]
> navigator.userAgent
> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36"

**Comment by ckprice** [comment]
If it's working okay for you, I'm not too worried about it tbh.

**Comment by ckprice** [comment]
Checked this on another machine and it works. Going to close this and write off as an issue with my work laptop.

**Comment by ckprice** [comment]
App uses [`me.user.id`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/landing-page.js#L22) to determine if a user is logged in. This logged in state supersedes the `isFirefox` check in the template.

My current /api/me: https://irccloud.mozilla.com/pastebin/HSo7iccb

This should be an edgecase just for admins.
