### ISSUE TITLE
add /user endpoint to pass session info to front-end app

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#63]
- if user's logged in, provide email address, whether the user has the main addon, and a list of any installed experiments
- if user's not logged in, return empty object / null / TBD

**Comment by lmorchard** [comment]
Was thinking of taking some pokes at this, if it doesn't trample on anything @meandavejustice already has in progress. (I'm an issue thief, feel free to smack me)

**Comment by meandavejustice** [comment]
no smacks necessary, happy you picked this up!

**Comment by jaredhirsch** [comment]
This was fixed by #82
