### ISSUE TITLE
Upgrade gulp-sass and gulp-sass-lint

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#636]
In #633, I discovered that unexpected upgrades to gulp-sass and gulp-sass-lint dependencies broke our frontend build.

In #635, I fixed the frontend build by pinning the dependencies those two packages need to the last known working versions.

At some point, though, we need to bite the bullet and try upgrading these packages to their latest versions and figure out 1) if the upstream breakage has been fixed and 2) whether our sass code has actual issues.

**Comment by ghost** [comment]
Closing in favor of #1597
