### ISSUE TITLE
Tweak pluralization on userCountContainer in l20n

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#639]
Re: https://github.com/mozilla/testpilot/pull/637#discussion_r60988105

> Also, because it's probably my job to make stupid comments, but do we care about the singular case?
> 
> :+1: "There are 0 people using {{title}} right now!"
> :-1: "There are 1 people using {{title}} right now!" [are => is, people => person]
> :+1: "There are 2 people using {{title}} right now!"
> 
> I'd almost lean towards "meh, f-it", because it's a pretty small and blunt edge and not worth the added complexity, and words are hard.
> ... But what do I know, I'm just one people.

**Comment by johngruen** [comment]
We aren't showing this until we have < 100 users
