### ISSUE TITLE
Offboarding surveys are mandatory and unskipable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#640]
Found in http://testpilot.dev.mozaws.net/__version__ (70d7a7582fbd8b181bef7f8d3a1d1658171e97c9):

``` json
{ "source": "https://github.com/mozilla/testpilot",
  "commit": "70d7a7582fbd8b181bef7f8d3a1d1658171e97c9",
  "version": ""}
```

---
### Steps to reproduce:
1. Sign in to testpilot.dev.mozaws and enroll in an experiment.
2. Disable experiment.
3. Witness glorious popup saying "Thank you!" plus a [Take a quick survey] button and Close link.
4. Click the Close link, because I don't want to participate in a survey (which sounds optional).
### Actual results:

Clicking "Close" link closes the modal, but doesn't disable the experiment.
![firefox_test_pilot_-_universal_search](https://cloud.githubusercontent.com/assets/557895/14801607/6eeb8786-0aff-11e6-8ad5-3b86ba8410d2.png)
### Expected results:

"Close" should close modal and let me skip the [not-very-optional] survey.
Possibly rename "Close" to "No thanks" or "Skip".
### Survey.gif

![](http://tclhost.com/JBRyizs.gif)

**Comment by pdehaan** [comment]
Since the exit survey opens in a new browser window/tab, the easiest workaround is to click the survey button, and then immediately close the survey tab which will leave the experiment in a disabled state.

**Comment by lmorchard** [comment]
Oh, yeah, that's a bug and 100% not intentional. I think it's because I reused some of the old feedback dialog code that didn't disable when the dialog was closed

**Comment by ckprice** [comment]
Should we stop deployment for this one?

/edit I say no. It's a bug, but nothing too crazy. I have tagged as blocking launch.

**Comment by pdehaan** [comment]
@ckprice I'd vote "yes", but only because it's annoying and @lmorchard already has a PR for it. Let's see if we can get @meandavejustice or @johngruen to :+1: that PR, then deploy that latest SHA instead.
