### ISSUE TITLE
Let's not log heartbeat hits

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#646]
I think we should have a list somewhere of URLs which we don't log.  We had 41k hits yesterday, of which 80 were to URLs that weren't:

```
/favicon.ico
/__heartbeat__
/__lbheartbeat__
/nginx_status
/robots.txt
```

Let's not bother sending logs for those  URLs

**Comment by lmorchard** [comment]
I guess the good news, then, is that our server logging is working? Is there a dashboard where we can see what's happening with the messages? Implementing a blacklist of URL paths for request logging should be pretty easy, but it would be nice to verify the results.

**Comment by ghost** [comment]
I'm hoping to give a more solid intro as I learn how to do things, but yeah:

1) go to https://sql.telemetry.mozilla.org/queries/new
2) Change the Data Source drop down to Testpilot
3) Paste this in:  
`SELECT * FROM testpilot_server_20160424 WHERE path NOT IN ('/favicon.ico', '/__heartbeat__', '/__lbheartbeat__','/nginx_status')`

4) click Execute
