### ISSUE TITLE
Test Pilot add-on does not seem to install in Private Browsing Mode

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#647]
Really hoping this is a case of 'I hack on the thing too often with too much weird stuff' case, but I'm able to reproduce on dev and stage.

STR:
1. Be in Private Browsing Mode on Firefox (tested on Beta and DevEdition).
2. Browse to https://testpilot.stage.mozaws.net/?butimspecial.
3. Click `Get Started with a Firefox Account`.
4. Sign up/in.
5. Click on `Install add-on`
6. See the below screen. No toolbar icon, doorhanger has nothing to anchor to, so it appears in the middle of the page. ![wut](https://s3.amazonaws.com/f.cl.ly/items/3Q2r42083N3C0j2C1618/Image%202016-04-26%20at%205.38.37%20PM.png?v=37fd23da)
7. Clicking `Let's go` takes you back to the front page with an `Install add-on` prompt.
8. Repeat step 5.

**Comment by jaredhirsch** [comment]
I'm not sure I understand the use case. When would a user want to log into a website and install an add-on while in private browsing mode?

**Comment by johngruen** [comment]
@6a68 late night piloting

**Comment by pdehaan** [comment]
If test pilot isn't supported in private browsing mode, we should do a better job messaging that. Currently we disable Activity Stream in private browsing, iirc. Not sure if we could do the same w/ test pilot where we can detect that via addon or before installation.

**Comment by lmorchard** [comment]
Maybe we could use [some hacks](https://gist.github.com/cou929/7973956) to detect private browsing mode? Before the add-on gets installed, our options to look into what's going on with the browser are as limited as any other web content.

Might be handy to toss another hidden step into the onboarding flow that looks for PBM and displays a message to disable PBM before proceeding. And also, once installed, the add-on should probably suspend its normal activities in PBM windows (assuming that's feasible)

**Comment by jaredhirsch** [comment]
> Maybe we could use some hacks to detect private browsing mode? 

We need cookies enabled for the user to access the site, right? Maybe we can try to set/get a cookie, and show an error screen explaining that cookies need to be enabled. This should cover private browsing mode, too.

**Comment by meandavejustice** [comment]
Isn't there a way we could check from the addon itself in a more sure way? Since we have access to firefox itself?

**Comment by jaredhirsch** [comment]
> Isn't there a way we could check from the addon itself in a more sure way? Since we have access to firefox itself?

You can detect PBM via `PrivateBrowsingUtils.isWindowPrivate(window)`. 

If the add-on isn't installed yet, I think we'd want to detect PBM from the website, so that users can avoid having to open a new window and run through the sign in flow a second time.

**Comment by meandavejustice** [comment]
> I think we'd want to detect PBM from the website, so that users can avoid having to open a new window and run through the sign in flow a second time.

Oh of course, 8 hours of driving has left me :confused:

**Comment by jaredhirsch** [comment]
Ha! No worries

**Comment by pdehaan** [comment]
+1 to cookie check if it also catches private browsing

**Comment by ckprice** [comment]
I'm going to bump this one, and see if it's something we want to fix (or at least update messaging) for launch. Currently user ends up in a loop to 'Install Add-on'.

/cc @johngruen @javaun @clouserw

**Comment by ghost** [comment]
I don't think it's very important, fwiw
