### ISSUE TITLE
Add basket API key to site configuration

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#648]
This is required for #609.

For us to send unsubscribe pings, we need an API key from basket.

See documentation for [`/news/unsubscribe/`](http://basket.readthedocs.org/newsletter_api.html#news-unsubscribe) and [`/news/lookup-user`](http://basket.readthedocs.org/newsletter_api.html#news-lookup-user).

We have an API key for production. ~~TBD if we'll need a separate for dev/stage.~~ ~~We can use this one key for stage and production.~~ Looks like we do want a separate key for stage and production.

**Comment by lmorchard** [comment]
These kind of things generally belong in ops-managed env vars, and not as values accessible from admin. For example, [this is how we access the credentials for Firefox Accounts](https://github.com/mozilla/testpilot/blob/master/testpilot/settings.py#L148). We don't even have those credentials on hand as devs. If we do, we have to somehow pass them to ops as part of the deployment process

FWIW, if we _do_ want to add things to the admin, that then depends on #506 to add something like constance and/or django-waffle to the project

**Comment by ckprice** [comment]
> These kind of things generally belong in ops-managed env vars. For example, this is how we access the credentials for Firefox Accounts. We don't even have those credentials on hand as devs.

@relud, @mostlygeek would you be able to add this for us?

**Comment by lmorchard** [comment]
> TBD if we'll need a separate for dev/stage.

FWIW, I'd say that we _do_, unless we want tests & QA on dev & stage to affect production data

**Comment by ckprice** [comment]
> FWIW, I'd say that we do, unless we want tests & QA on dev & stage to affect production data

Spoke to @pmclanahan this morning. We're good with using the one key and basket production environment for testing and production (shouldn't be creating too much noise).

**Comment by lmorchard** [comment]
I'm also not super-comfortable with having production credentials on our stage & dev servers for security & privacy concerns. They're reasonably secure, but less-so than prod for the sake of dev flexibility (among other things). 

As a rule, we should avoid having real personal info on (or accessible to) anything other than prod, and never ever import prod data to stage or dev. But, if that's how basket is used on other projects, I guess we go with it.

**Comment by pmclanahan** [comment]
I can give you a separate API key for use on your stage instance. I'd prefer that actually. There's no reason for you to use our basket staging instance, but it would be great if we could have separate keys for invalidation in case of a breach.

**Comment by pmclanahan** [comment]
And just to clarify, basket itself stores no data and only sends it to Salesforce Marketing Cloud (SFMC, formerly Exact Target). Both basket stage and prod use the same SFMC account. We do have a separate SFMC sandbox account for basket-dev, but it doesn't have all of the newsletters and is a bit too unreliable for use in a CI situation.

**Comment by mostlygeek** [comment]
> These kind of things generally belong in ops-managed env vars. For example, this is how we access the credentials for Firefox Accounts. We don't even have those credentials on hand as devs.

@lmorchard is right. The keys should be pulled from environment variables we pass in.

**Comment by ckprice** [comment]
> I can give you a separate API key for use on your stage instance. I'd prefer that actually.

@pmclanahan okay, could you please create the stage API key and send to me? Once it's received, we'll send both stage and prod keys to Ops to create the environment variables.

**Comment by pmclanahan** [comment]
@ckprice or we can skip the middlemen and I can encrypt and send directly to Ops. That'd be the most secure thing to do. Just let me know who should get 'em.

**Comment by ckprice** [comment]
Yes sure. If that works for @mostlygeek?

**Comment by lmorchard** [comment]
(tweaked the title to reflect discussion)

**Comment by lmorchard** [comment]
One more thing: We're talking about separate credentials for stage and sending those to ops, but what about dev on elastic beanstalk? Ops doesn't manage our dev server - that's on me / us. So, we'll need non-prod credentials to update env vars there, too. If that's the same as staging credentials, I / we will need those on the dev team side too.

**Comment by ckprice** [comment]
@pmclanahan given ^ can we just send them to one person (me), and I'll give to @lmorchard and whoever ends up doing the Ops work for us?

**Comment by ckprice** [comment]
@mostlygeek I have both stage and production keys - do you want me to encrypt and toss them over to you? `BASKET_API_KEY` should be fine for the name.

@lmorchard I will send you the stage key to be used on dev.

**Comment by mostlygeek** [comment]
@ckprice yes. Please GPG and send it to my mozilla email. Thanks.

**Comment by ckprice** [comment]
Stage key sent to @lmorchard (for dev).

Stage and prod keys sent to @mostlygeek (for stage and prod).

Let's use `BASKET_API_KEY` as the env variable name.

**Comment by mostlygeek** [comment]
keys are in our secrets repo. Ready for the next deployment.
