### ISSUE TITLE
Line break in Universal Search header text when browser window is too narrow

### ISSUE THREAD

**Issue by kaganjd** [mozilla/testpilot#650]
This doesn't happen with Activity Stream or Tab Center, though.

https://testpilot.stage.mozaws.net/experiments/universal-search
<img width="845" alt="screen shot 2016-04-27 at 2 01 30 pm" src="https://cloud.githubusercontent.com/assets/9204835/14863142/8b02fb96-0c82-11e6-9cb7-0f001860eecb.png">
<img width="626" alt="screen shot 2016-04-27 at 2 03 11 pm" src="https://cloud.githubusercontent.com/assets/9204835/14863143/8c985aaa-0c82-11e6-821c-a456a3dda6d3.png">

**Comment by johngruen** [comment]
@kaganjd tracking UI papercuts in #653...going to close this one out to keep everything consolidated. Good catch!
