### ISSUE TITLE
TestPilot not reporting user install numbers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#652]
Found in https://testpilot.stage.mozaws.net/__version__ (e181c39f76a363870c46d34fc9cc0810b70f2f72):

``` json
{ "version": "2016-04-26",
  "commit": "e181c39f76a363870c46d34fc9cc0810b70f2f72",
  "source": "https://github.com/mozilla/testpilot" }
```

---
### Steps to reproduce:
1. Go to https://testpilot.stage.mozaws.net/experiments/tab-center
2. Verify installed user count.
3. Enable experiment.
4. Verify installed user count.
### Actual results:

<img width="856" alt="firefox_test_pilot_-_tab_center" src="https://cloud.githubusercontent.com/assets/557895/14865761/136b2a3e-0c75-11e6-87fe-52a0b715bb76.png">
### Expected results:

There should be at least ONE people trying it actively, because I have it enabled.

**Comment by pdehaan** [comment]
Ref: #583

**Comment by lmorchard** [comment]
Huh, this is weird: On staging, the # of [user installations](https://testpilot.stage.mozaws.net/admin/experiments/userinstallation/) in the DB is 0. When I enable or disable an experiment, the HTTP API requests to PUT or DELETE an installation record get 403 FORBIDDEN responses in the browser console.

**Comment by lmorchard** [comment]
The PUT / DELETE requests work properly on dev. However, they fail on prod. Hmm, I wonder if this ends up being an issue for ops... needs some investigation.

A couple of relevant lines from my browser console:

```
PUT XHR https://testpilot.firefox.com/api/experiments/2/installations/f7403225-d00c-fa48-900c-ce25090355b5 [HTTP/1.1 403 FORBIDDEN 126ms]
...
DELETE XHR https://testpilot.firefox.com/api/experiments/2/installations/f7403225-d00c-fa48-900c-ce25090355b5 [HTTP/1.1 403 FORBIDDEN 374ms]
```

**Comment by lmorchard** [comment]
@mostlygeek: Do you happen to know if our prod & stage deployments are configured to deny requests with HTTP PUT & DELETE methods?

**Comment by mostlygeek** [comment]
PUT and DELETE are not blocked. They will propagate through nginx to the app.

**Comment by mostlygeek** [comment]
I confirmed on the stage boxes that PUT and DELETE methods make it through

**Comment by lmorchard** [comment]
Hmm, if these requests are getting through to the app, I wonder if this has something to do with SSL and/or cookies in authenticating the request. Lacking SSL is the only other thing I can think of that distinguishes my local machine & dev from stage & prod.

**Comment by lmorchard** [comment]
Adding this to public launch blockers, because an API issue like this seems pretty serious.

**Comment by lmorchard** [comment]
Got some debugging output from the 403 Forbidden responses, and it looks like lacking the referer header might be the issue: "CSRF Failed: Referer checking failed - no Referer."

Next, figuring out why this doesn't happen on local & dev, hopefully finding a way to reproduce it & fix it locally. Ah, yup - [looks like referer checking is only enforced for CSRF token when the request is secure](https://github.com/django/django/blob/master/django/middleware/csrf.py#L136)

**Comment by lmorchard** [comment]
Got a PR that seems to fix the issue. As follow up, we should pursue #662 and #548 to enable HTTPS and reduce the differences between local and dev environments that let this slip through to stage & prod.
