### ISSUE TITLE
UI papercuts

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#653]
- [x] Noise doesn't look great
- [x] Ship doesn't look great on non-retina
- [x] Bring back horizontal rule on experiements list page
- [x] Universal Search name breaks on smaller breakpoint #650 
- [x] tour images aren't quite full bleed
- [x] tour captions could be improved
- [x] Disable {experiment}" button needs a hover state 
- [x] Animations on Now Active dot and three dot menu look blurry/glitchy on non-retina displays
  ~~\- [ ] Ability to cancel onboarding tour without needing to go through all slides~~

**Comment by jaredhirsch** [comment]
Edited description to make it a bit more friendly. Please abide by our code of conduct when contributing to this project, thanks!

https://github.com/mozilla/testpilot/blob/master/CODE_OF_CONDUCT.md

:heart:

**Comment by johngruen** [comment]
@6a68 noted <3

**Comment by shorlander** [comment]
- [x] Animations on Now Active dot and three dot menu look blurry/glitchy on non-retina displays

**Comment by Verdi** [comment]
~~Screenshots should be platform specific or at least default to Windows.~~

**Comment by johngruen** [comment]
Moving Verdi's issue out of this bug, since it's related to content

**Comment by johngruen** [comment]
Moving the cancel tour issue out of this bug

**Comment by pdehaan** [comment]
FWIW, I'm still seeing linebreaks in "Universal Search" with Tab Center installed. I don't think the Tab Center is relevant, just that if you pin it open, it takes up another few hundred px, making this a lot more likely on desktop:

![firefox_test_pilot_-_universal_search](https://cloud.githubusercontent.com/assets/557895/15159510/e0c6173a-16a9-11e6-92e1-8fe1931355c3.png)

---

https://testpilot.firefox.com/__version__ (f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/360",
  "version": "2016-05-10",
  "source": "https://github.com/mozilla/testpilot",
  "commit": "f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd" }
```
