### ISSUE TITLE
Installing the Test Pilot add-on dead ends

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#654]
I tried it this morning and thought it might just be nightly, but someone else just tried it and it also happened so I'm filing this.

STR:

1) Go to stage and sign in
2) Click the button to install the Test Pilot add-on
3) See a page that says the add-on has been installed....and that's it:

<img width="1440" alt="screen shot 2016-04-27 at 6 01 45 pm" src="https://cloud.githubusercontent.com/assets/16946141/14869792/c42e3784-0c8a-11e6-9e32-211646d2cac6.png">

It never does anything after this point.  Refreshing the page fills in the content as expected.  This was reproduced on Fx46 and Nightly, although it sounds like it may be sporadic for others.

/cc @ckprice @johngruen @meandavejustice

**Comment by ckprice** [comment]
Fixed in #656 with a follow up in #659.
