### ISSUE TITLE
"Disable {experiment}" button needs a hover state

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#658]
Found in http://testpilot.dev.mozaws.net/__version__ (e181c39f76a363870c46d34fc9cc0810b70f2f72):

``` json
{ "source": "https://github.com/mozilla/testpilot",
  "version": "",
  "commit": "e181c39f76a363870c46d34fc9cc0810b70f2f72" }
```

---
### Steps to reproduce:
1. Go to http://testpilot.dev.mozaws.net/experiments/activity-stream
2. Hover over the [Disable Activity Stream] button (or tab to it until it has focus).
### Actual results:

There is no :hover or :focus state for the button.
### Expected results:

It's good for accessibility and stuff.

**Comment by johngruen** [comment]
@pdehaan closing in favor of #653
