### ISSUE TITLE
Update pip & remove peep

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#66]
Seeing oodles (37, to be exact) of messages being spewed out in Travis logs (https://travis-ci.org/mozilla/idea-town/jobs/79713081):

> **You are using pip version 6.1.1, however version 7.1.2 is available.**
> **You should consider upgrading via the `pip install --upgrade pip` command.**

---

![job__45_3_-_mozilla_idea-town_-_travis_ci](https://cloud.githubusercontent.com/assets/557895/9801984/a3ba4c96-57cb-11e5-9566-c2566ace1b33.png)

**Comment by lmorchard** [comment]
We're locked to this version of pip by the use of [peep](https://github.com/erikrose/peep). Peep wraps pip and enforces crypto hashes on the packages in requirements.txt. Looks like [support for pip 7 is still in progress on the peep project](https://github.com/erikrose/peep/pull/97).

**Comment by lmorchard** [comment]
Going to close this for now, since it's waiting on peep

**Comment by jaredhirsch** [comment]
Reopening, as peep is now [deprecated in favor of pip 8](https://github.com/erikrose/peep/wiki/UpgradeToPip8).

**Comment by ghost** [comment]
Cautiously marking this as a good first bug :)
