### ISSUE TITLE
Enable HTTPS on testpilot.dev local server

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#662]
Issue #548 is for enabling HTTPS on the elastic beanstalk dev server. But, it should be enabled on the local Docker environment, too. There's been at least one case (#652) where HTTP vs HTTPS made a difference in exposing a bug.

**Comment by chuckharmston** [comment]
Closing because d3fe158cf37565ba99876bc831e3ce5ef76f4d2d merged.
