### ISSUE TITLE
Should be able to reorder contributors

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#664]
right now I can't reorder contributors in a test. They always go in the order tehy were added. We should make it possible to reorder them to make sure people who do the most work are at the top.

**Comment by lmorchard** [comment]
The solution for #1250 should offer solution for this

**Comment by lmorchard** [comment]
In the new static YAML world, we can put contributors in any manual order

4096b56ac135e471166b8cbcd3197688f6d78e94
