### ISSUE TITLE
Generate separate vendor & app JS bundles

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#665]
Noticing that the scripts task in gulp takes awhile, these days - between 7 and 18 seconds sometimes.

It might be handy to generate separate JS bundles for vendor and app code. The vendor bundle would contain stuff from `package.json` while the app bundle would contain our own code. Just rebuilding the app bundle with project code changes would probably speed up file watcher cycles.

For an example, [I did something like this on a side project](https://github.com/lmorchard/arboretum/blob/master/gulpfile.babel.js#L15). Might be handy to find a way to auto-generate the external vendor modules list from `package.json` rather than hand-coding it like I did though

**Comment by pdehaan** [comment]
We do something like that for [activity-streams](https://github.com/mozilla/activity-streams/blob/10e3925341aee7772ad6d2f2b4044b288eeec809/webpack.config.js#L43-L48), but we use webpack, so your mileage may vary.

**Comment by meandavejustice** [comment]
That looks great @lmorchard 

getting the list from `package.json` should be as simple as:

``` js
var venderDeps = Object.keys(require('./package.json').dependencies)
```

While looking at this I noticed we have some unused npm deps, so I created an issue for that here #669

**Comment by johngruen** [comment]
+1 I get antsy waiting for scripts to rebuild.
