### ISSUE TITLE
Cookies link 404s

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#67]
Super lame bug, but I'll forget if I don't file it.

Build the app locally and then run `docker-compose up`. Once the app launches, click on the "Cookies" link (see https://github.com/mozilla/idea-town/pull/59/files#diff-2cabeffb936e476d6305a174ddfbbfd5R27). You're redirected from http://mozilla.org/cookies to https://www.mozilla.org/en-US/cookies, which is a fancy 404 page.

I think this should link to "//mozilla.org/privacy/websites/#cookies", per [**mozilla/idea-town-splash** /routes/data.json#L43-L46](https://github.com/mozilla/idea-town-splash/blob/6bb0ca832896249240c76fb745ef143c1d446387/routes/data.json#L43-L46)

**Comment by jaredhirsch** [comment]
Good call! We might want to exclude the `en-US` slug from the URL; mozilla.org has some locale-detection magic that will insert the locale slug for any viewer.

**Comment by pdehaan** [comment]
@6a68 Good catch, updated URL above.

**Comment by lmorchard** [comment]
This looks fixed now
