### ISSUE TITLE
Test Pilot thinks disabled add-ons are active

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#670]
This is a little edge-casey but was showed to me by someone who had old versions of tab center and activity stream installed but disabled, and then installed Test Pilot who saw the add-ons were installed and said "Now Active" for them.

So, basically we shouldn't be looking at if an add-on is installed, but if it is installed _and active._

**Comment by meandavejustice** [comment]
This is in progress [here](https://github.com/mozilla/testpilot/compare/master...meandavejustice:670-active-means-active-not-installed)

**Comment by meandavejustice** [comment]
Opened #680 to discuss clientside web handling of this issue
