### ISSUE TITLE
Handle little Firefoxes

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#672]
Fennec and FXiOS have easy to spot UAs. We should include a message letting users visitng Test Pilot from these browsers that the service is only available from Firefox Desktop.

**Comment by meandavejustice** [comment]
``` js
const UAString = navigator.userAgent.toLowerCase();
const isMobile = (UAString.includes('gecko') && UAString.includes('mobile') || UAString.includes('fennec'));
```

_edit_ updated UAString check

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/testpilot/issues/671#issuecomment-215759522

My totally not scientific results from my iPad Air 2 and Samsung Galaxy S6:

| OS | `userAgent` |
| --- | --- |
| iPad Air 2<br/>**iOS 9** | "Mozilla/5.0 (iPad; CPU OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) FxiOS/3.0 Mobile/13E238 Safari/601.1.46" |
| Samsung Galaxy S6<br/>**Android 5** | "Mozilla/5.0 (Android 5.1.1; Mobile; rv:46.0) Gecko/46.0 Firefox/46.0" |

Regular reminder that user agent strings are a huge :-1:.

**Comment by meandavejustice** [comment]
Thanks @pdehaan I actually looked at your feedback in #671 when making this. I made it check for 'gecko' and 'mobile' so that we could catch both in one go. It looks like we will have to add a separate line for `fennec` though according to this list http://www.useragentstring.com/pages/Fennec/

**Comment by sevaan** [comment]
Proposed UX: https://mozilla.invisionapp.com/share/G28SJV79Q

**Comment by sevaan** [comment]
Slight update to spec: Removed the download button as well.

**Comment by johngruen** [comment]
This UX should apply to both Firefox for iOS and Firefox for Android
