### ISSUE TITLE
Alert users to new experiments (post v1)

### ISSUE THREAD

**Issue by javaun** [mozilla/testpilot#675]
We're going to email users when we launch new experiments, but they might delete it when they're on the go and forget. We're not always going to reach them at the right time, when they're ready to install.

As a user, I want Test Pilot to remind me when new experiments are available so that I can go play w/ more cool stuff.

Suggested DOD: The toolbar icon is badged to alert/subtly nag users. The icon doorhanger also features new experiments marked "NEW" . Clicking New experiments either enrolls users or takes them to that experiment page where they can enroll.

**Comment by johngruen** [comment]
This is vague. Going to open up more specific issues.

**Comment by javaun** [comment]
Intentionally so. If we need a place to put higher level users stories, LMK. I can always assign you Aha cards ;-)
(That's a bluff. I don't want to do that either.)

**Comment by pdehaan** [comment]
FWIW, I _DON'T_ want TestPilot to notify me of new experiments, so it'd be nice if it were opt-in (or opt-out -- just as long as I have an "opt").
