### ISSUE TITLE
Add copy for when experiments have been manually disabled

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#680]
#679 handles active status for experiments that are enabled/disable manually by the user. It adds some events we can listen for (`addon-manage:enabled` and `addon-manage:disabled`) to be able to tell the user if their addon is disabled.

This should be a quick thing, maybe a little [attention icon](https://images.duckduckgo.com/iur/?f=1&image_host=http%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fd%2Fdc%2FIcon_attention.svg%2F300px-Icon_attention.svg.png&u=https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Icon_attention.svg/300px-Icon_attention.svg.png) and some small red text with a title attr that explains the addon has been manually disabled.

**Comment by johngruen** [comment]
cool

**Comment by meandavejustice** [comment]
This is what I have in progress for the details page.
![disabled-ui-details-page](https://cloud.githubusercontent.com/assets/1844554/15479127/acde067e-20ec-11e6-82e6-af8790b090ec.png)

@johngruen Would you mind giving me an asset(! icon or something) for the experiment list page?

gh is having some issues right now so I cannot link to the in progress branch, but the branch name is [`680-manually-disabled-experiments-endcase`](https://github.com/mozilla/testpilot/compare/master...meandavejustice:680-manually-disabled-experiments-endcase).

**Comment by pdehaan** [comment]
@meandavejustice Looks good! Not sure if we want to:
- hyphenate "Add-on".
- Change "Add-on" to `{{title}} has been manually disabled in `about:addons`` (although we already have the title in like 9 places on this page).
- Link `about:addons` to the actual about:addons page for easy toggling back on.
- Not sure if we can provide a link or easy way to re-enable the add-on from this page without making the user return to about:addons to enroll in experiment again.

**Comment by meandavejustice** [comment]
@pdehaan I can't seem to find a way to link `about:addons` I've tried `chrome` and `//` prefixes. 

# ¯\_(ツ)_/¯

Good point with the reenabled option... I'd like to get @6a68 and @lmorchard 's opinion on that. I feel like we are wrapping a lot of the `about:addons` functionality as is..

**Comment by pdehaan** [comment]
Funny, I even tried `window.location = 'about:addons'` in the developer tools console and got this gem:

> Error: Access to 'about:addons' from script denied

Maybe Firefox makes it difficult on purpose for personal safety reasons. OK, forget it. Dumb idea.

**Comment by meandavejustice** [comment]
>Because SlimerJS uses the version of firefox passed in the SLIMERJSLAUNCHER environment variable, edge builds of firefox can be used.

https://github.com/graingert/slimerjs/blob/master/README.md

**Comment by johngruen** [comment]
@meandavejustice 

![disabled from add-on main 2x](https://cloud.githubusercontent.com/assets/3323249/15517568/71b77122-21c6-11e6-8b01-996d8893c478.png)

Here are the exclamation marks: 
![notice](https://cloud.githubusercontent.com/assets/3323249/15517582/82eac07a-21c6-11e6-9140-351b15733115.png)
![notice 2x](https://cloud.githubusercontent.com/assets/3323249/15517583/82eb0bc0-21c6-11e6-9e32-ad3efe04e587.png)

**Comment by johngruen** [comment]
@dannycoates colors adjusted to match #660
![disabled from add-on main 2x](https://cloud.githubusercontent.com/assets/3323249/17447550/08f7d1aa-5b1d-11e6-8de2-81c891378e08.png)

**Comment by johngruen** [comment]
@johngruen add reenable state.

**Comment by sevaan** [comment]
Updated UX: https://mozilla.invisionapp.com/share/Q77S1H6ZC#/214781378_Disabled_From_Add-On_Main

**Comment by meandavejustice** [comment]
@sevaan a couple months ago we discovered that linking to the addons manager (about:addons) page is not allowed in webpages. However, we may be able to send a signal to the addon and open up a new tab with the `about:addons` page.

**Comment by sevaan** [comment]
If it's easy, let's do that.

We could probably live without it though, because in order to see the message in the first place you would have to have gone into the Add-ons Manager to disable the add-on from there, so it's not like the user doesn't know what the Add-ons Manager is or how to get there.

**Comment by SoftVision-PaulOiegas** [comment]
We've looked over the implementation and it seems to be working properly for most of the locales.
On some of the locales the message is not translated so it falls back to English translation.

However, the functionality is affected by #2338. So we'll recheck this after the fix is performed.
