### ISSUE TITLE
Integrate Sentry for error reporting

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/testpilot#684]
~~Do we want to integrate something like https://getsentry.com?~~
- [ ] django error reporting https://docs.getsentry.com/hosted/clients/python/integrations/django/
- [ ] client side reporting https://docs.getsentry.com/hosted/clients/javascript/

**Comment by lmorchard** [comment]
We definitely do want to use Sentry! See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1269512

**Comment by pdehaan** [comment]
+1 to trying to do this in the current sprint. We're having a few reports of users unable to install experiments or spinners spinning. /cc @ckprice @clouserw 

---
- #812 &mdash; i cant able to test "Tab Center"
- #802 &mdash; Stuck on 'Enabling' for over 10 minutes
- #800 &mdash; Lots of JS errors on front page
- #798 &mdash; "TypeError: e is undefined" if I click the [...] button lots
- #794 &mdash; "TypeError: workers.get(...) is undefined" error on uninstall
- #792 &mdash; Opening a test project from the extention often does not work
- #772 &mdash; Installation fails

**Comment by ghost** [comment]
If we can integrate Django (which I think is mostly adding to INSTALLED_APPS?) it would be good to land that asap and worry about the client side later.  (I saw the size:large tag and assume that's about the client side).

**Comment by meandavejustice** [comment]
updated to `size:medium`

**Comment by pdehaan** [comment]
@ckprice @clouserw Any chance we can get this added to the current/next milestone?

**Comment by meandavejustice** [comment]
Would recommend moving to the next milestone.

**Comment by jotes** [comment]
@pdehaan @lmorchard I can look into this if you don't mind.

**Comment by lmorchard** [comment]
> I can look into this if you don't mind.

@jotes that would be amazing! Pretty much all of the core dev team are about to wander off to an all-hands in London over the next few days, so none of us are likely to dig into this very soon.

**Comment by jotes** [comment]
Hi Everyone,
I'm really sorry, but I overestimated my time-bending capabilities and I won't be able to finish this integration in a reasonable amount of time.
As I don't want to stop you -> please free to takeover this issue.

I apologize if I caused any troubles.

**Comment by meandavejustice** [comment]
@jotes no problem, thanks for the update

**Comment by ghost** [comment]
I'm going to close this, in favor of https://github.com/mozilla/testpilot/milestone/20

**Comment by pdehaan** [comment]
Ref: #1609
