### ISSUE TITLE
Update ACCOUNT_INVITE_ONLY_MODE=False for stage & production

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#686]
Ref: #605

@javaun can we ship this with our next deployment? Should go out Wednesday/Thursday. This is the thing that will allow non mozilla.com email addresses to join.

**Comment by javaun** [comment]
We need final policy/Terms posted before we can do this. It's worth shooting for but right now seems very unlikely we'll have this by Wed/Thursday

**Comment by ckprice** [comment]
Blocked by #619.

**Comment by lmorchard** [comment]
FWIW, resolving this issue should require no code changes - we just need to remember to ask ops to change the env var as part of the deployment bug when we're ready to go.
