### ISSUE TITLE
Remove ?butimspecial query string gate

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#688]
Ref: #605 

@javaun can we bring this down ahead of our Monday deployment? Our next is scheduled ~Wednesday/Thursday.

**Comment by javaun** [comment]
This one seems blocked on #686, no? Non-moz email folks are going to get a weird 404 error if they try signing in, and the purpose of "coming soon" wall is so they try to enroll and hit a bad experience.

**Comment by ckprice** [comment]
> This one seems blocked on #686, no? Non-moz email folks are going to get a weird 404 error if they try signing in, and the purpose of "coming soon" wall is so they try to enroll and hit a bad experience.

Yeah. Both of these would be closed with the same deployment. Outside of that, is there anything else blocking us removing the query string? (e.g. GTM plans)

**Comment by lmorchard** [comment]
Also FWIW, the invite flag is already `False` on dev, so getting this change merged in won't have a net effect there. If we're also switching off the invite flag as part of deploying this code to stage / prod (#686), the 404 issue (#487) will be moot then as well.
