### ISSUE TITLE
Final pass on strings before launch

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#693]
@ckprice and I will review strings.

**Comment by ckprice** [comment]
Here is the [copy document for reference](https://docs.google.com/document/d/1Uw-NkI7wrqFHc0D8p1Nsj31BWlR5Uq4IXoH_n1lRI_I/edit).

One of the bigger changes is that we are changing `Retire` to `Leave Test Pilot`. We don't have to worry about the API calls/function names for launch.

**Comment by meandavejustice** [comment]
Do we want this to be a group effort?

**Comment by johngruen** [comment]
@meandavejustice we got updates from marketing to change strings throughout the site. I'm doing it right now. expect a PR In a minute. @ckprice will review, but @meandavejustice this one could use some eyes since spelling is dificult.

**Comment by ckprice** [comment]
Closed via #701
