### ISSUE TITLE
Add spec docs for GA

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#696]
Ref: #481

**Comment by lmorchard** [comment]
Seems like this should include info from this Google Doc? https://docs.google.com/document/d/1SIOaZLHsMGNBNmAxphon4cxF_F07Q1ctBkU6gkP2SD0/edit?ts=56fc371c

**Comment by ckprice** [comment]
Yep. That doc is also linked to in the bug opening of the referenced bug in the first comment, but probably good to have it here too.
