### ISSUE TITLE
Add 'Requirements for Experiments' docs

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#698]
This would be a checklist of technical things and documentation we require for experiments to be launched through Test Pilot.

e.g.
- Metrics
- [Test Pilot attribution](https://github.com/mozilla/universal-search/issues/174)
- Name review

**Comment by ghost** [comment]
We talked about requiring "Part of the Test Pilot syndicate." or something in the add-on descriptions.  I think only universal search has something right now.

**Comment by ghost** [comment]
I can take a crack at this

**Comment by pdehaan** [comment]
> _"We talked about requiring "Part of the Test Pilot syndicate." or something in the add-on descriptions. I think only universal search has something right now."_

All three of the current experiments currently have the `[ available on | Test Pilot ]` badge in the root README.md file.
- [Activity Stream](https://github.com/mozilla/activity-stream/blob/master/README.md#activity-stream-add-on)
- [Tab Center](https://github.com/bwinton/VerticalTabs/blob/master/README.md#tabcenter-)
- [Universal Search](https://github.com/mozilla/universal-search/blob/master/README.md#universal-search)

**Comment by ghost** [comment]
Every time I try to do this it comes out duplicating that giant spreadsheet tracking all the projects.  I feel like we need some public documentation, but maintaining it in two places feels wrong.  Kind of at a loss. 😿

**Comment by ghost** [comment]
https://trello.com/b/0kxTOKPU/test-pilot-experiment-status is what we're using for now.
