### ISSUE TITLE
Periodic `i.default.me.installed is undefined` error

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#703]
This seems to happen while I'm testing with my @gmail.com account.

STR (sorry it's not great):
- Visit http://testpilot.dev.mozaws.net/?butimspecial.
- Log in with @gmail.com (or other non mozilla.com maybe) email.
- Browse around some (sorry this isn't more detailed).
- Error in image happens.
- Restarting browser sometimes works.

![error](https://s3.amazonaws.com/f.cl.ly/items/1j3l303o0j3U300C0o0L/Image%202016-05-04%20at%2011.36.52%20AM.png?v=bc80b726)
- Complete console: https://gist.github.com/ckprice/223d115c453dc831fbb122a7fdc45704
- This error happens locally too, and there's nothing weird happening in the shell.

**Comment by lmorchard** [comment]
Was there anything happening in your shell at the time? e.g. was the frontend rebuilding or the back end server restarting, etc? 

What version of the add-on do you have installed?

**Comment by ckprice** [comment]
> Was there anything happening in your shell at the time? e.g. was the frontend rebuilding or the back end server restarting, etc?

This is on dev, so I don't know. This error happens locally too, and there's nothing weird happening in the shell.

> What version of the add-on do you have installed?

None.

**Comment by lmorchard** [comment]
FWIW, the only places I can find reference to `app.me.installed` in the code are in these spots related to GA events:

```
➜  testpilot git:(master) find ./testpilot/frontend/static-src -type f -exec grep -Hni 'me.installed' {} \;
./testpilot/frontend/static-src/app/views/landing-page.js:41:      'dimension2': this.loggedIn ? Boolean(app.me.installed.length) : null,
./testpilot/frontend/static-src/app/views/landing-page.js:42:      'dimension3': this.loggedIn ? app.me.installed.length : null
```

Could be related to the recently added GA calls? We might need to add some checks to ensure `app.me.installed` is defined before attempting to access `app.me.installed.length`

**Comment by lmorchard** [comment]
Hmm, actually, yeah there might be more issues with this particular bit: [`app.me.installed` should be an Object by default](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L16), not an Array, so there will be no `length` property. 

Probably want something like `Object.keys(app.me.installed || {}).length` here. But, I'm curious how `app.me.installed` ends up _undefined_ when it should at least be an empty Object by default

**Comment by lmorchard** [comment]
I've been working on this for a bit already, will probably have a PR with tests around the issue soon

**Comment by pdehaan** [comment]
I've gotten this 4/4 times on testpilot.dev.mozaws.net (using beta and nightly).
Seems to be happening right after I log in to FxA (with my @mozilla.com email), but before the add-on gets installed.

**Comment by lmorchard** [comment]
Yeah, that sounds consistent with what PR #705 should fix. The installation count only happens after login, and the installation object seems to be undefined before the add-on is around and populates it.
