### ISSUE TITLE
Privacy Notice legal page has unprocessed "<a>Learn More.</a>" blocks

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#710]
Found in http://testpilot.dev.mozaws.net/__version__ (ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5):

``` json
{ "commit": "ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/324" }
```

---

http://testpilot.dev.mozaws.net/privacy

![test_pilot](https://cloud.githubusercontent.com/assets/557895/15031711/97c20ae2-120f-11e6-9dad-0ce47cd736f0.png)

We either need to add some jQuery or other sauce to get toggling working, or take the cheap way out, and just do a simple search/replace of "<a>Learn More.</a>" in the legal templates before/after converting to HTML.

**Comment by johngruen** [comment]
@pdehaan can't we just use markdown links? they seem to be working in other places

**Comment by johngruen** [comment]
Oh, these are expandos...guh

**Comment by johngruen** [comment]
@ckprice @pdehaan i went through this with legal on FXA, we just removed the text. It was NBD.

Straw plan: we do the same here.

**Comment by pdehaan** [comment]
Yeah, since we currently "own" the legal docs end to end, we can probably remove the "Learn More" placeholders and not worry about this until the privacy+terms pages get hosted on the **legal-docs** repo.

**Comment by johngruen** [comment]
I agree with @pdehaan Esq.'s legal rational, and since my sister and brother-in-law are both lawyers I know what I'm talking about.
