### ISSUE TITLE
Survey popup blocked w/ Nightly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#711]
Found in https://testpilot.stage.mozaws.net/__version__ (ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/325",
  "commit": "ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-04"}
```

---
### Steps to reproduce:
1. Go to https://testpilot.stage.mozaws.net/ and sign in using Nightly (possibly relevant).
2. Enable and disable an experiment.
3. After disabling the add-on/experiment, click the [Take a quick survey] button.
### Actual results:

> Nightly prevented this site from opening a pop-up window.

![firefox_test_pilot_-_tab_center](https://cloud.githubusercontent.com/assets/557895/15032179/2c275aae-1213-11e6-910a-a46003027aae.png)

I also noticed that my Developer Tools console said;

> TypeError: `window.open(...)` is `null`

(presumably because of the blocked pop-up.
### Expected results:

I should be able to see the survey.
Currently I'm in a state where the add-on/experiment is now disabled and I'm unable to provide feedback.
I am now faced with two equally unpleasant options:
1. Click [Enable Tab Center] button, then click [Give Feedback] button to give feedback. (This didn't work and now Firefox says "Nightly prevented this site from opening 2 pop-ip windows.")
2. Click [Enable Tab Center] button, then click [Disable Activity Stream] add-on. (This didn't work because it's the same steps as the original steps to reproduce.)
3. Disable pop-up blocker and try option 1 or 2 above.

The mostly likely solution is that I'm impossibly lazy, and won't run through the 2-3 steps to try and give feedback now that the popup was disabled.

**Comment by ckprice** [comment]
This is happening because we are [opening links in new tabs from `sendToGA` with `window.open`](https://github.com/mozilla/testpilot/blob/f9b13478d3b978ddd221e4adde974c48029933b6/testpilot/frontend/static-src/app/main.js#L68). I actually don't know if we can do anything about this.

Some other interesting observations/things:
1. Should we be opening exit surveys in new tabs? They've decided to remove themselves from the program/experiment, why open a new tab.
2. When opening links in new tabs, we don't have to use the `outboundURL` async callback because the frame it's being called in stays in tact.

To fix this specific issue, I would recommend opening exit surveys in the same tab (see 1).

**Comment by pdehaan** [comment]
I'm also seeing this with the "Test Pilot Wiki" and "File an Issue" links in the pop-up menu:

![firefox_test_pilot_-_tab_center_and_browser_console](https://cloud.githubusercontent.com/assets/557895/15061062/c3d591e0-12e5-11e6-9f81-3cf19a91c059.png)

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/testpilot/issues/642

I'd think if a user "retires" from Test Pilot, we should probably put the open the exit survey in the **same** tab (since they're done w/ Test Pilot).

If a user leaves an _experiment_ (but wants to stay enrolled in Test Pilot), it probably makes to open the exit survey/feedback in a **new** tab so they're still somewhat on the Test Pilot site so they can easily enroll in other experiments if they wish [without needing to manually type in testpilot.firefox.com or clicking the Test Pilot icon in the toolbar to return to the site].

---

**UPDATE:** Interesting. I remember seeing this a few days ago in my Twitter feed and may be worth a quick glance:
- ["Target='_blank'  &mdash;  the most underestimated vulnerability ever"](https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c#.7crk56iuq)
- ["About `rel=noopener`"](https://mathiasbynens.github.io/rel-noopener/)

**Comment by nchapman** [comment]
I experienced this in release as well (46.0.1).
