### ISSUE TITLE
Firefox sometimes warns me before installing Test Pilot

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#715]
This is because we are self-hosting and not on AMO. @andymckay has offered a couple suggestions

`<andym>` you can host the test pilot on amo as an addon
`<andym>` or make a static page on AMO that hosts the add-on
`<andym>` eg https://github.com/mozilla/addons-server/blob/master/static/html/snippets/lastpass.html

![addon warning](https://irccloud.mozilla.com/file/JGe97CRC/Screen+Shot+2016-05-05+at+12.37.05+PM.png)

**Comment by gregglind** [comment]
20:08 < gregglind> (chuck, @_6a68, a static page on amo only solves it IFF the link for the addon is _also_ on amo)
20:09 < gregglind> https://addons.mozilla.org/en-US/firefox/shield-study-2/
20:09 < gregglind> (static page on amo, linked to an AMO hosting url)
20:10 < gregglind> I could be wrong, but at least a month ago, having an amo url for the addon wasn't enough.
20:10 < gregglind> But test it out :)

Our bug for this:  https://github.com/mozilla/addons/issues/2644

**Comment by ckprice** [comment]
Any other recommendations here?

@clouserw @lmorchard what are some of the drawbacks to hosting on AMO?

**Comment by kumar303** [comment]
> This is because we are self-hosting and not on AMO

But the add-on is signed, right? You shouldn't see this error with a signed, self-hosted add-on so I'm confused.

**Comment by lmorchard** [comment]
As far as I can tell, we're signing it with every version change and deployment tag. 

[The add-on .xpi is here](https://testpilot.firefox.com/static/addon/addon.xpi) - is there an easy way to verify the signature from the command line, if only to double check we're doing the right thing?

**Comment by lmorchard** [comment]
Just to double check, I downloaded our deployed [self-hosted add-on](https://testpilot.firefox.com/static/addon/addon.xpi) and [what should be the equivalent private version on AMO](https://addons.mozilla.org/firefox/downloads/file/436538/test_pilot_addon-0.5.7-tag-2016-05-10-fx+an.xpi?src=devhub). Ran `shasum` on the two XPIs and got the same hash:

```
➜  tmp git:(810-gunicorn-exec) ✗ shasum ~/Downloads/test_pilot_addon-0.5.7-tag-2016-05-10-fx+an.xpi
0bb059e027cfaf9484b8d92478cd5f1b8b55898c  /Users/lmorchard/Downloads/test_pilot_addon-0.5.7-tag-2016-05-10-fx+an.xpi
➜  tmp git:(810-gunicorn-exec) ✗ shasum addon.xpi
0bb059e027cfaf9484b8d92478cd5f1b8b55898c  addon.xpi
```

**Comment by andymckay** [comment]
It's not an error, its a warning that occurs to prevent drive by installations of malicious add-ons. The signing failure is quite a different warning.

**Comment by ghost** [comment]
To answer the "why not AMO" question:    You have to wait through a review queue (which, last time I looked, was down to a few hours), however, it breaks our easy/automatic deploy of add-on + site all at once.  This makes it harder to adjust APIs and stuff quickly, however, since test pilot is a stable project (that is, not an experiment) we should be pretty careful with API adjustments anyway.

I think Les might have had another reason too the last time we talked about it.

**Comment by kumar303** [comment]
> is there an easy way to verify the signature from the command line

This doesn't verify the signature but it's a quick sanity check that the add-on has a signature:

```
$ unzip -l addon.xpi | grep META-INF/mozilla.sf
      121  05-10-16 17:50   META-INF/mozilla.sf
```

**Comment by kumar303** [comment]
Just for the record, I was completely wrong about this statement:

> You shouldn't see this error with a signed, self-hosted add-on

Sorry, my bad

**Comment by ckprice** [comment]
No worries, thanks for checking it out!

**Comment by lmorchard** [comment]
> <andym> eg https://github.com/mozilla/addons-server/blob/master/static/html/snippets/lastpass.html

Hmm, this URL is a 404, and I can't see an `html` directory under [`static`](https://github.com/mozilla/addons-server/tree/master/static). Did that go away?

**Comment by andymckay** [comment]
Yup, after looking at it for this issue I realised it wasn't need and removed it. Here's one added for shield recently:

https://github.com/mozilla/addons-server/blob/f3a457b68f5e43bc5b76ae4dc961013bbf2eaf94/src/olympia/pages/templates/pages/shield_study_2.html

**Comment by meandavejustice** [comment]
@ckprice This is definitely not going to make it into the 05-20 milestone. Do we want to bump it to the next one?

**Comment by ckprice** [comment]
> @ckprice This is definitely not going to make it into the 05-20 milestone. Do we want to bump it to the next one?

Yeah. Going through the comments, I think our best solution may be just put in the request to whitelist testpilot.firefox.com, and have it ride the trains (maybe we can get it uplifted).

@andymckay @clouserw thoughts?

**Comment by ckprice** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1274332. Feel free to close/comment that bug if there is a better solution. I'll keep this GH issue open for now for tracking purposes.

**Comment by andymckay** [comment]
Works for me.

**Comment by andymckay** [comment]
You might also want to consider beefing up security on testpilot.firefox.com a bit, just so you don't become an attack vector. @clouserw knows these things as well but things we watch out for on AMO are: outgoing links that people add that have an xpi in them (since you don't have user generated content this might not be a problem), CSP (currently not enabled) and SRI (also not enabled).

**Comment by lmorchard** [comment]
> You might also want to consider beefing up security on testpilot.firefox.com a bit, just so you don't become an attack vector.

Now that you mention it, those could end up being reasonable demands from the Fx team before we get whitelisted. 

With respect to user-generated content, I'd assert right now that we should just never do that from the testpilot.firefox.com domain. That's where using our off-site community Discourse instance makes sense for hosting discussions, for example.

But, [CSP](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) and [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) are definitely worth pursuing ASAP.

Filed new issues:
- SRI - https://github.com/mozilla/testpilot/issues/881
- CSP - https://github.com/mozilla/testpilot/issues/882

**Comment by ckprice** [comment]
Quick update

In [bug 1274332](https://bugzilla.mozilla.org/show_bug.cgi?id=1272395#c2) we received a go-ahead to add us to the whitelist once the following issues are closed.
- [x] Implement Content Security Policy mozilla/addons#1599 
- [ ] Move Test Pilot /admin/ to something hosted behind a secure Mozilla VPN mozilla/addons-server#890 (ops bug)

**Comment by lmorchard** [comment]
Quick security point: As we're tightening things up for possible add-on install whitelisting in Firefox, is adding Optimizely to the site okay? (issue mozilla/addons-server#904)

**Comment by kumar303** [comment]
It would be great if you could enable [CSP](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) on https://testpilot.firefox.com/ (I only checked the prod site, maybe it's forthcoming?)

**Comment by ckprice** [comment]
> It would be great if you could enable CSP on https://testpilot.firefox.com/ (I only checked the prod site, maybe it's forthcoming?)

Ref mozilla/addons-server#930.

**Comment by ckprice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1274332 landed!
