### ISSUE TITLE
Tabs pulled from main browser instance

### ISSUE THREAD

**Issue by hondurasjones** [mozilla/testpilot#718]
When I have multiple tabs open and I want to pull one tab out of the main cluster of tabs to view individually in separate display, the pulled tab opens in a very small size that I can't actually use unless I pull corners to expand. Expected functionality is that the pulled tab would be the same size as the previous instance or auto-fit itself to the display. 

DeveloperEdition 48.0a2
MacBook Pro (Retina, 13-inch, Late 2013)
2.8 GHz Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris 1536 MB
<img width="1221" alt="screen shot 2016-05-05 at 10 49 09 am" src="https://cloud.githubusercontent.com/assets/9257516/15051756/184cdc2e-12af-11e6-9509-c89af33c6131.png">

**Comment by chuckharmston** [comment]
Thanks for the report! Moving to the correct repo: https://github.com/bwinton/VerticalTabs/issues/109
