### ISSUE TITLE
Test pilot icon appears white

### ISSUE THREAD

**Issue by past** [mozilla/testpilot#719]
Just installed test pilot add-on on latest nightly, OS X, default theme:

<img width="210" alt="white-button" src="https://cloud.githubusercontent.com/assets/49118/15052123/ac904740-1304-11e6-8b12-1156ad850022.png">

I already had activity-stream and universal-search installed, nothing peculiar in the browser console.

**Comment by meandavejustice** [comment]
@past Thanks for reporting this, I'm also seeing this with the light theme.

**Comment by meandavejustice** [comment]
@past would you mind going into `about:config` and looking for the `devtools.theme` key? I've seen a weird state with firefox stable where `devtools.theme` is set to dark, but the address bar/toolbar area still has a light background. Lemme know if this is what you are seeing.

**Comment by callahad** [comment]
On my end, toggling the DevTools theme from light to dark changes the Test Pilot icon to the inverse.

Which would be appropriate if I was using the DevEdition Firefox theme, but I'm not.

**Comment by past** [comment]
@meandavejustice I see the same thing as @callahad: when I switch to the light devtools theme, I get the right test pilot icon. So this looks like what's going on: the icon is toggled depending on the selected devtools theme, regardless of the actual theme that is applied in the browser chrome.

**Comment by ckprice** [comment]
Removing this as a launch blocker.

**Comment by meandavejustice** [comment]
Talking to bwinton about this today. We were originally checking against the `devtools.theme` pref. It seems we need to be checking something more like this: https://dxr.mozilla.org/mozilla-central/source/browser/themes/linux/browser.css#1565

**Comment by leplatrem** [comment]
I have a similar problem with GTK and the dark theme:
![capture d ecran de 2016-05-10 12-49-08](https://cloud.githubusercontent.com/assets/546692/15144111/9dade5c8-16ad-11e6-921f-ef9fc522e2a5.png)

![capture du 2016-05-10 12-50-02](https://cloud.githubusercontent.com/assets/546692/15144133/d61cf71e-16ad-11e6-9f42-13eb7fdb834e.png)

**Comment by rtanglao** [comment]
i have this problem in developer edition and so do users:

https://twitter.com/uimanishere/status/731162989735350273

**Comment by warpr** [comment]
Looks correct for me in Developer Edition on Fedora 23, when it is near the address bar.  But it stays white when dragged into hamburger menu using customize:

![test-pilot-icon](https://cloud.githubusercontent.com/assets/85700/15695982/e92032d4-2771-11e6-9e18-e5ed3b7d71d1.png)
