### ISSUE TITLE
Universal Search page content is very imbalanced

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#720]
![screen shot 2016-05-05 at 12 05 00 pm](https://cloud.githubusercontent.com/assets/23885/15052191/a53adb4a-12b9-11e6-96fc-0d1cff33ff16.png)

Perhaps it would make sense to move the privacy section into the main content area?

**Comment by meandavejustice** [comment]
@chuckharmston I think in most cases we will have more details and screenshots specific to the actual experiment. Are we sure there isn't anything missing in our universal-search data?

**Comment by johngruen** [comment]
Getting a second image from @bryanbell

**Comment by johngruen** [comment]
@chuckharmston i will play with moving details to the top.

**Comment by chuckharmston** [comment]
@johngruen Note https://github.com/mozilla/universal-search/issues/189

**Comment by johngruen** [comment]
noted
