### ISSUE TITLE
Add bug report link to experiment "details" section

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#721]
Seems like a pretty cheap way to direct bug reports, e.g.

![screen shot 2016-05-05 at 12 13 38 pm](https://cloud.githubusercontent.com/assets/23885/15052418/d78cba36-12ba-11e6-8937-93421cfef61b.png)

**Comment by gregglind** [comment]
(Fast work!)

I wonder if putting a link to this in the survey (as a 'question 0', conditional on coming in through the feedback page query arg) is also worthwhile.  

I filed on the specific project issues page.  Felt not awesome.

**Comment by chuckharmston** [comment]
@gregglind that's definitely also in the works, cc @johngruen

**Comment by meandavejustice** [comment]
@lmorchard what do you think of this? It sounds good to me.

**Comment by johngruen** [comment]
@meandavejustice i like chuck's proposal a lot

**Comment by johngruen** [comment]
(the original one)...let's discuss adding to the survey in the meeting. my guess is that most people using test pilot won't have GH accounts.

**Comment by chuckharmston** [comment]
My suggestion would be a lot more effective if we also had that block higher up the page, e.g. https://github.com/mozilla/testpilot/issues/720

**Comment by johngruen** [comment]
Getting a second image from @bryanbell

**Comment by chuckharmston** [comment]
Improved suggestion:

![screen shot 2016-05-09 at 1 13 15 pm](https://cloud.githubusercontent.com/assets/23885/15125006/ef70f254-15e7-11e6-9dd1-50d6351e58d3.png)

**Comment by johngruen** [comment]
Love it, ship it

**Comment by pdehaan** [comment]
Do we need to update the Django models to add an "Issues" link to the experiments?
I see that we could _almost_ use the **contribute** URL links:

| Experiment | Contribute URL |
| :-- | :-- |
| **Activity Stream** | https://github.com/mozilla/activity-streams |
| **Tab Center** | https://github.com/bwinton/VerticalTabs#readme |
| **Universal Search** | https://github.com/mozilla/universal-search |

So if we make the **Tab Center** contribute link to the more generic /VerticalTabs (without the `#readme` at the end) we could just append `/issues` to the "Source code" link.

**Comment by meandavejustice** [comment]
In most cases appending `/issues` should be fine. I would like people creating experiments to not be tied to github. It's not very hard to update the django model, I vote we just add a field.

**Comment by pdehaan** [comment]
+1 to a new field in Django, as appending "/issues" is probably too GitHub specific and adds unnecessary complexity.
