### ISSUE TITLE
"Please rate undefined" in heartbeat-like prompt.

### ISSUE THREAD

**Issue by mythmon** [mozilla/testpilot#722]
This was originally reported against Normandy in [bug 1270581](https://bugzilla.mozilla.org/show_bug.cgi?id=1270581).

<img src="https://bugzilla.mozilla.org/attachment.cgi?id=8749309"/>

We got a couple reports of users getting a heartbeat-like prompt with the message "Please rate undefined". One of those users confirmed this was after installing the new Testpilot addon. This was seen in (at least) Nightly.

**Comment by meandavejustice** [comment]
Thanks @mythmon this is definitely on our end.

**Comment by leibovic** [comment]
Let me know if I can help debug. I am running test pilot, so this makes sense.

**Comment by meandavejustice** [comment]
Hey @leibovic thank you! I think we have a fix over at #727 turns out that `keys` is a reserved word in `addon-sdk` land. I was trying to set a variable to that name :/
