### ISSUE TITLE
Update doorhanger `Active` state on enablement without a refresh.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#723]
STR:
- Install Experiment.
- Click on Test Pilot icon while staying in the same tab (don't refresh).

Expected:
- Doorhanger should indicate that the newly enabled experiment is "Active".

Actual Result:
- Experiment is not indicated as "Active".
- Refreshing web page fixes the issue.

![not active](https://s3.amazonaws.com/f.cl.ly/items/2Z3r1T0j1t312h243q0y/Image%202016-05-05%20at%2011.24.52%20AM.png?v=7d0cffe7)

**Comment by javaun** [comment]
I saw this too. When I refresh the page (CTRL + R) it came in.

**Comment by ckprice** [comment]
Looks like Mayo commented on this again. I'm going to move this to planned and add it to TXP-0.

**Comment by johngruen** [comment]
![screen shot 2016-07-29 at 3 15 24 pm](https://cloud.githubusercontent.com/assets/3323249/17260622/747289ee-559f-11e6-87d6-0f839f43f7ab.png)
