### ISSUE TITLE
Get our oauth endpoints from our endpoints

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#724]
#717 talked about needing to configure our endpoints for dev/stage/prod.  We can do that off of well-known URLs:  https://accounts.firefox.com/.well-known/openid-configuration

**Comment by lmorchard** [comment]
I think this might be more of an upstream django-allauth bug if/when we drop our custom code for configuring the endpoints in favor of what comes out of the box now

**Comment by lmorchard** [comment]
Closing, because we dropped FxA entirely
