### ISSUE TITLE
Enable manually editing top sites

### ISSUE THREAD

**Issue by mystor** [mozilla/testpilot#725]
Currently, in the new new-tab page, there doesn't seem to be a way for me to remove a website from my top sites, or pin one, unlike the tiles on the old new tab page. I would like to be able to do that, because having a stable list of top sites helps me navigate from the new tab page to websites I want to visit faster.

**Comment by pdehaan** [comment]
@mystor Thanks for the feedback!
Moved to https://github.com/mozilla/activity-streams/issues/652
