### ISSUE TITLE
preference and addon page are gone

### ISSUE THREAD

**Issue by shinglyu** [mozilla/testpilot#730]
I installed testpilot, activated tab center and activity stream. But now I can't open preference and add-ons from the menu. I have to type `about:preference` and `about:addons` in the URL bar to get it. 

Also, if I click the customize button, all the available buttons from add-ons are all gone. 

Not sure which feature breaks my profile.

**Comment by chuckharmston** [comment]
Thanks for the report!

I believe this is an issue with Tab Center, which we have logged here: https://github.com/bwinton/VerticalTabs/issues/50
