### ISSUE TITLE
Feedback issue

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#734]
Copied over from https://bugzilla.mozilla.org/show_bug.cgi?id=1270896, filed by @theres-waldo:

---

I went to "Give Feedback" on one of the Test Pilot experiments, and the feedback page is not functioning properly:
- The title of the tab keeps changing between "Tab Center" and
  "Connecting..." as if the page was being automatically reloaded
  over and over again.
- The form says "There was an error on your page. Please correct
  any required fields and submit again." even though I haven't
  submitted the form yet.
- The "Next" button on the form page is not responsive.

**Comment by johngruen** [comment]
Matt Grimes is working on a mitigation for this. There was some fancy JS on this page. should be resolved soon.

**Comment by johngruen** [comment]
Assigning myself to keep an eye on this one since it's technically not in the TxP codebase.

**Comment by jaredhirsch** [comment]
Seems fixed to me. @theres-waldo feel free to reopen if you can still reproduce.
