### ISSUE TITLE
Activity Stream supports Firefox 45 or later

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/testpilot#736]
AS hasn't tested earlier versions of Fx before Fx45, it would be ideal to do version detection and ask the user to update version.

**Comment by johngruen** [comment]
@edmoz all of test pilot is basically current -2

**Comment by ckprice** [comment]
We can update #698 to indicate that Test Pilot supports `current-2`. If this is a Test Pilot feature request to allow experiments to configure their version requirements, I think that would deserve it's own bug and need some discussion. Please open a new bug if this is the case.

I recommend saying somewhere in your add-on about the version requirements. Closing this bug for now (please re-open if you'd like to discuss more).
