### ISSUE TITLE
Move legal documents to /mozilla/legal-docs

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#738]
Our legal documents are currently in https://github.com/mozilla/testpilot/tree/master/legal-copy.

We should move them over to https://github.com/mozilla/legal-docs someday, since that's where the rest are (and will help l10n at some point).

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/legal-docs/pull/509
I made a pull request against **mozilla/legal-docs** to add a package.json, which will let us do something like this and add the legal-docs repo :

``` bash
$ npm install mozilla/legal-docs -D
```

Then I think we'll just need to move over our legal *.md files and blah, blah, blah.

---

In **fxa-content-server** we used the [bower.json](https://github.com/mozilla/fxa-content-server/blob/4450796bed0224a617b5cbd201895a22647c9d77/bower.json#L37) file to specify the **mozilla/legal-docs** as a dependency, but I'd rather not add Bower to this stack just for that one repo.

**Comment by pdehaan** [comment]
Upstream **legal-docs** package.json fix was merged (thanks @clouserw!), in case anybody wants to jump on this before I get around to it.

**Comment by ckprice** [comment]
~~Received the following request from Brian Smith in legal (also updated bug title, and opening):~~

> I noticed that the Test Pilot privacy notice webpage does not have the sections collapsed like our other [privacy notices](https://www.mozilla.org/en-US/privacy/firefox/). Can we please revise to make the two sections of the notice collapse/expand? Denelle does not like our notices to just be a wall of text, so this is a priority for us.
> 
> Casey (cc'd) can help the relevant person on your team with the css/html formatting as needed.

/cc @mozcmcgill

/edit addressing in #877.

**Comment by meandavejustice** [comment]
@ckprice This sounds like a separate issue, maybe to be made as a follow up to this one.

**Comment by pdehaan** [comment]
> _This sounds like a separate issue, maybe to be made as a follow up to this one._

Filed as #877

**Comment by pdehaan** [comment]
Another legal hiccup, but in the [**mozilla/legal-docs** firefox_cloud_services_PrivacyNotice](https://github.com/mozilla/legal-docs/tree/master/firefox_cloud_services_PrivacyNotice) we have localized versions of the legal docs. So we'll need something like dis:

```
mozilla/legal-docs/
  - testpilot_privacy-notice/
    - de.md
    - en-US.md
    - es-ES.md
    - fr.md
    - it.md
    - ...

  - testpilot_terms-of-use/
    - de.md
    - en-US.md
    - es-ES.md
    - fr.md
    - it.md
    - ...
```

So when we move our legal docs over to **mozilla/legal-docs**, we'll also need to add another depth so the Privacy Notice and Terms of Use legal docs can be translated.

**Comment by clouserw** [comment]
We talked about this in a meeting with the legal team, but I forget the outcome.  As I recall, they seemed ho-hum about it like it wasn't a big deal.  English is fine, localizing is a bonus.  @ckprice - is that your recollection?  If so I won't feel as bad about not doing this yet.

**Comment by johngruen** [comment]
@clouserw i think we should revisit this in the next sprint, right now i don't think these files are getting localized. I imagine that's a hard requirement for the German launch.

**Comment by ckprice** [comment]
> I imagine that's a hard requirement for the German launch.

I don't know for sure about this -- @eleemoz?

Also, as IIRC putting these docs in the repo doesn't automagically get them localized. This was more of an organizational thing for the legal team. /cc @caseymcgill

**Comment by johngruen** [comment]
@ckprice yeah, i didn't mean to conflate the issues here. Right now we aren't localizing these things, but we'll need to.

**Comment by ghost** [comment]
We'll follow up on this next Monday in our legal meeting

**Comment by pdehaan** [comment]
Both these folders in the **mozilla/legal-docs** repo currently have translations for _en-US.md_ and _de-DE.md_:

https://github.com/mozilla/legal-docs/tree/master/firefox_testpilot_PrivacyNotice
https://github.com/mozilla/legal-docs/tree/master/firefox_testpilot_Terms
