### ISSUE TITLE
`docker-compose build` errors

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#74]
I've found that `docker-compose build` sometimes fails by hanging forever.

I've seen this happen during the `client_build` build process, when it's attempting to install npm deps.

This problem is intermittent, but when it occurs, it's impossible to get any work done.

One thing that, oddly, fixed the problem for me today was doing an `npm install` in the host OS, then repeating `docker-compose build`. Maybe npm problems? Maybe the local npm cache is visible to docker-compose, but it fails to fetch the deps from the npm site?

Weird. Leaving this open to collect other symptoms and possible solutions.

**Comment by jaredhirsch** [comment]
Being a bit more explicit, here's what I did to unclog the pipes:
1. `docker rmi $(docker images -f dangling=true -q)`
2. `docker rm $(docker ps -qa)`
3. `npm install`
4. `docker-compose build`

Weirdly, the `npm install` seems to be a critical part of the process. I tried the other three steps repeatedly, without luck.

**Comment by lmorchard** [comment]
Seems like gulp in docker and file watching ends up being the source of many woes. Maybe we should just run Django in Docker and accept running Gulp on the host like normal people https://github.com/mozilla/idea-town/pull/136

**Comment by meandavejustice** [comment]
closing since we now have a [README-DOCKER.md](https://github.com/mozilla/idea-town/blob/master/README-DOCKER.md) file
