### ISSUE TITLE
Optimize all the django images

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#740]
I can grab this one, but we should do it before we launch.

**Comment by lmorchard** [comment]
Just to clarify:

```
<lorchard> are the “django” images in #740 just image uploads in the admin pages?
<lorchard> If so, that’s cool because we don’t have to necessarily hustle for the next deployment & etc
<jgruen> lorchard: yeah
```

So, they're not the images served up from the django server but from S3, so we don't have to tie this to a pull request & a deployment

**Comment by johngruen** [comment]
I did it!
