### ISSUE TITLE
Add query params to links in the doorhanger

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#745]
![doorhanger](https://s3.amazonaws.com/f.cl.ly/items/1v1u0V0e393j101y1R29/Image%202016-05-09%20at%2012.23.33%20PM.png?v=75025b6f)

Adding query parameters to these links will give us a quick and easy way to see usage of these links.

It would mean appending this to each of the links: 

~~`utm_source=firefox-browser&utm_medium=doorhanger`~~

/edit:

> utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content={{doorhanger link name}}
> 
> where {{doorhanger link name}} is the name of the app (ie. Universal Search) OR "View All Experiments

@garethcull will these work for all the links?

**Comment by garethcull** [comment]
@ckprice can we use the following:
utm_source=testpilot-addon&utm_medium=firefox-browser&utm_campaign=testpilot-doorhanger&utm_content={{doorhanger link name}}

where {{doorhanger link name}} is the name of the app (ie. Universal Search) OR "View All Experiments"

Thanks!

**Comment by ckprice** [comment]
This should work, thanks!

**Comment by johngruen** [comment]
This seems important and easy. moving into this sprint.
