### ISSUE TITLE
Fix `Give Feedback` buttons on experiments page.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#748]
#726 introduced a few small errors:

~~https://testpilot.stage.mozaws.net/experiments/activity-stream~~ (enabled view)

/edit stage has been rolled back. You can verify on [dev](http://testpilot.dev.mozaws.net/experiments/activity-stream).
- Doesn't open in a new tab.
- Survey URL is malformed (https://qsurvey.mozilla.com/s3/activity-stream?ref=givefeedback&experiment=Activity%20Stream?ref=givefeedback&experiment=Activity%20Stream&installed=%40activity-streams&installed=universal-search%40mozilla.com).
- ~~"Give Feedback" doesn't have hover pointer.~~

**Comment by pdehaan** [comment]
Tried adding a shotgun approach to fixing button cursors in #749
