### ISSUE TITLE
User can't see who she is logged in as (i.e., which FxA)

### ISSUE THREAD

**Issue by ckarlof** [mozilla/testpilot#750]
<img width="342" alt="screenshot 2016-05-09 16 45 30" src="https://cloud.githubusercontent.com/assets/2365255/15131533/a97e6916-1605-11e6-8034-517051274ce6.png">

**Comment by johngruen** [comment]
yeah, this is a good thing to fix. @lmorchard can we pass the fxa username (email) into the view? Do we even have this?

**Comment by meandavejustice** [comment]
@johngruen yes, we have it in the `me` model

**Comment by johngruen** [comment]
cool, i will grab this
