### ISSUE TITLE
A few console logs and warnings from qsurvey.mozilla.com

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#751]
Found in https://testpilot.stage.mozaws.net/__version__ (60035a999b17135beff6debb3c083c7aa2608203):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/346",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-06",
  "commit": "60035a999b17135beff6debb3c083c7aa2608203" }
```

---
### Steps to reproduce:
1. Go go https://testpilot.stage.mozaws.net/experiments/activity-stream and enable the experiment.
2. Click the [Give Feedback] button.
3. Open the Developer Tools and look at the Console tab output (a).
4. Go to https://testpilot.stage.mozaws.net/experiments/tab-center and enable the experiment.
5. Click the [Give Feedback] button.
6. Open the Developer Tools and look at the Console tab output (b).
### Actual results:

(a) Developer Tools console says:

> "here"
> &mdash; see [activity-stream:301:3](https://qsurvey.mozilla.com/s3/activity-stream?ref=givefeedback&experiment=Activity%20Stream):

``` html
<script id="sgE-2730399-4-72-box" type="text/javascript">// Script
$(document).ready(function(){
  document.getElementsByClassName('sg-progress-bar')[0].style.display = 'none';
  console.log('here'); // <------- this line right here.
});
</script>
```

---

(b) Developer Tools console says:

> "SyntaxError: missing ) after argument list"
> &mdash; see [tab-center:151:40](https://qsurvey.mozilla.com/s3/tab-center?ref=givefeedback&experiment=Tab%20Center)

``` html
<script id="sgE-2730414-4-58-box" type="text/javascript">// Script
document.body.style.display = 'none';

function containsParamVal(key,val) {
  return location.search(key + '=' + val;) > -1; // <------- this line right here.
}

// ...
</script>
```

**Comment by pdehaan** [comment]
Can't exactly repro on prod, because currently I'm seeing:

> TypeError: `window.open(...)` is `null`

https://testpilot.firefox.com/__version__

``` json
{ "commit": "ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-04",
  "build": "https://circleci.com/gh/mozilla/testpilot/325" }
```

**Comment by ghost** [comment]
Can we check if this still happens? thanks

**Comment by pdehaan** [comment]
I can still repro the "here" issue on https://qsurvey.mozilla.com/s3/activity-stream?ref=givefeedback&experiment=Activity%20Stream&installed=%40activity-streams:
![activity_stream](https://cloud.githubusercontent.com/assets/557895/19324604/50203452-9077-11e6-8793-6755a8661529.png)

Plus if I look at my Browser Console, I'm seeing a suspicious error (which as a reference to [resource://testpilot-addon/data/set-installed-flag.js:15:3](https://github.com/mozilla/testpilot/blob/5641deddb006f95b8969b2fbac45ae2dd1fdc061/addon/data/set-installed-flag.js#L15)):
![browser_console](https://cloud.githubusercontent.com/assets/557895/19324626/6f61086e-9077-11e6-8934-a107adfd7f66.png)

> "Error: Permission denied to access property "wrappedJSObject"

**Comment by pdehaan** [comment]
I'm unable to repro that SyntaxError on the Tab Center survey page though.
Although, I am possibly seeing some CSP error in the Browser Console:

![browser_console](https://cloud.githubusercontent.com/assets/557895/19324864/77d2fa60-9078-11e6-901c-ac81ed2c6ad5.png)

Oddly, I can't seem to reproduce that CSP error consistently, so not sure if I need to create a new profile or if something in my JPM launched Firefox 50 is partially to blame.

**Comment by ghost** [comment]
I can reproduce the "here" issue at that URL for activity stream.  I don't see any syntax or CSP issues though.  I think @rayborn owns the 'here' thing.

**Comment by ghost** [comment]
I don't see the "here" anymore.  Is this still an issue?

**Comment by ghost** [comment]
Calling this fixed.  Thanks!
