### ISSUE TITLE
Edge case: Resolving privacy choice conflicts.

### ISSUE THREAD

**Issue by javaun** [mozilla/testpilot#752]
When a user installs Test Pilot, we store their prior Telemetry state so that we can restore it when they leave test pilot. Policy highlighted an edge case.

For example, a user has telemetry on, installed Test Pilot (full Telemetry is one), but then turns Telemetry off. Then, a user uninstalls Test Pilot. In this case, we'd restore to their state prior to joining Test Pilot (Telemetry on) but would revert their latest choice to disable Telemetry. 

We'd discussed code that errs on the side of privacy -- when uninstalling Test Pilot, do not revert a more private setting to a less private one.

However, I think the correct way to handle this is just to require full telemetry as a condition of using Test Pilot. I don't know how we can enforce this. We'll talk at an ENG standup

**Comment by meandavejustice** [comment]
@javaun We can listen for manual updates to the telemetry pref in the addon, and set that as our "pre-testpilot" preference.
