### ISSUE TITLE
Render errors in doorhanger when switching to and from retina and non-retina displays

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#754]
When i switch from non-retina to retina: 
<img width="378" alt="screen shot 2016-05-10 at 11 00 56 am" src="https://cloud.githubusercontent.com/assets/3323249/15151555/93c08e02-169f-11e6-856d-b1261c8c70d3.png">

When I switch from retina to non-retina:

![screen shot 2016-05-10 at 11 01 05 am](https://cloud.githubusercontent.com/assets/3323249/15151556/95239aa0-169f-11e6-83fc-ee5350a67c00.png)

Issue is fixed in both cases by closing and reopening doorhanger

**Comment by ghost** [comment]
John suspects this is an upstream bug which we might not be able to affect.

**Comment by ghost** [comment]
If we can reproduce in other add-ons, let's just close this
