### ISSUE TITLE
undefined error after browser relaunch (White Screen of Death)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#755]
Found in https://testpilot.firefox.com/__version__ (ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5):

``` json
{ "version": "2016-05-04",
  "commit": "ca8af43986ea2e0f8f8ecb08625b26f1aae7a6e5",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/325" }
```

---
### Steps to reproduce:
1. Launch a fresh browser and go to https://testpilot.firefox.com
2. Sign up with a brand new account (on a fresh profile)
### Actual results:

After signing in to FxA, I see a blank page with a simple `undefined` in my Dev Tools console:

![test_pilot](https://cloud.githubusercontent.com/assets/557895/15153757/5943bbba-168f-11e6-91bb-cbb2096d8ad0.png)

Refreshing the page seems to resolve the issue.

Digging into the minified source is a mess, but seems to point to this general line:

``` js
["catch"](function(e){console&&console.error(e)})}
```

Unminifying and searching for that line seems to give me this general block:

``` js
document.l10n.ready]).then(function () {
  s['default'].me.updateEnabledExperiments(s['default'].experiments),
  s['default'].pageManager = new y['default']({
    pageContainer: document.querySelector('[data-hook=page-container]')
  }),
  s['default'].router.history.started() || (s['default'].router.history.start(), addEventListener('pageshow', s['default'].router.history.checkUrl, !1))
}) ['catch'](function (e) {
  console && console.error(e)
})
```

Unwinding further, it seems to be coming from somewhere in this block:
[./testpilot/frontend/static-src/app/main.js:29-50](https://github.com/mozilla/testpilot/blob/312e91baf5a3b21cb92ac478ed69e62fe9644ccd/testpilot/frontend/static-src/app/main.js#L29-L50):

``` js

    Promise.all([
      app.me.fetch(),
      app.experiments.fetch(),
      document.l10n.ready
    ]).then(() => {
      app.me.updateEnabledExperiments(app.experiments);

      app.pageManager = new PageManager({
        pageContainer: document.querySelector('[data-hook=page-container]')
      });

      if (!app.router.history.started()) {
        app.router.history.start();
        // HACK for Issue #124 - sometimes popstate doesn't fire on navigation,
        // but pageshow does. But, we just want to know if the URL changed.
        addEventListener('pageshow', app.router.history.checkUrl, false);
      }
    }).catch((err) => {
      // for now, log the error in the console & do nothing in the UI
      console && console.error(err); // eslint-disable-line no-console
    });
},
```

**Comment by pdehaan** [comment]
Closing.
I can't repro this currently on stage anymore. I think I was trying to use older prod add-on pointed to a stage server which is why I could see this in both envs earlier...
Switching envs sucks.

**Comment by pdehaan** [comment]
Actually, i was just able to reproduce this in prod (f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd) using Beta channel and I installed an update. The browser restarted and everything went white. Reloading the tab renders as expected.

https://testpilot.firefox.com/__version__

``` json
{ "commit": "f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd",
  "build": "https://circleci.com/gh/mozilla/testpilot/360",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-10" }
```

![test_pilot](https://cloud.githubusercontent.com/assets/557895/15163659/9b05bf38-16be-11e6-9273-7fdc2d573c6a.png)

**Comment by pdehaan** [comment]
Actually, I can occasionally reproduce this by just hitting refresh on the /experiments page.
About 1 in 20 refreshes gives me a blank page with the `undefined` error.

**Comment by johngruen** [comment]
oof

**Comment by ckprice** [comment]
Have another report of this. Adding it to this sprint.

**Comment by pdehaan** [comment]
Also reported by another user in #792. Apparently refreshing the page worked for them, but still pretty bad user experience.

**Comment by pdehaan** [comment]
Also reported by @ckarlof and @johngruen in #827

**Comment by pdehaan** [comment]
``` json
{ "version": "2016-05-18",
  "commit": "a729b09008914caeeb9357b29f52f40ebf55f60f",
  "build": "https://circleci.com/gh/mozilla/testpilot/425",
  "source": "https://github.com/mozilla/testpilot" }
```

I'm still seeing this somewhat frequently on Test Pilot. In fact, I just got it about 3 out of my last 6 page refreshes.

![test_pilot](https://cloud.githubusercontent.com/assets/557895/15374882/4ec4ddcc-1d01-11e6-84f6-08999e50313d.png)

**Comment by lmorchard** [comment]
Having trouble reproducing this one to track down a cause. We also had a deployment yesterday, right around the time of that last screenshot. The deployment process has been known to temporarily break the site, though I think that's being improved.

**Comment by lmorchard** [comment]
More info that might be handy for if/when this happens again: If you have everything enabled in the "Net" dropdown in your web console - or at least "XHR" - we might be able to see if things broke because some resource or another was a 403 / 404 / 400 / 500 / etc.

**Comment by johngruen** [comment]
@lmorchard fwiw, still seeing this today. Here it is in the wild...got it on the 3rd attempt: https://www.dropbox.com/s/zr9bijwpt5xuuaf/failure.mov?dl=0

**Comment by johngruen** [comment]
@lmorchard @pdehaan 
Possibly related: setting up some screenshotting automation with phantom/slimer to audit our UI occasionally. I can't get either to work b/c errors that seem like they might be related to this problem. 

To repro, install phantomjs or slimer js....here's the script I'm running: 

```
var page = require('webpage').create();
var url = 'https://testpilot.firefox.com/';

page.open(url, function (status) {
  if(status === 'success') {
    page.render('test.png');
  }
  console.log(status);
  phantom.exit();
});
```

you can run this with `phantomjs test.js` or `slimerjs test.js`, but errors get thrown in both cases:

Phantom (webkit) throws: 

```
ReferenceError: Can't find variable: WeakSet

  https://testpilot.firefox.com/static/app/app.9a2988e445a5.js:10
  https://testpilot.firefox.com/static/app/app.9a2988e445a5.js:11
  https://testpilot.firefox.com/static/app/app.9a2988e445a5.js:1 in a
  https://testpilot.firefox.com/static/app/app.9a2988e445a5.js:1
  https://testpilot.firefox.com/static/app/app.9a2988e445a5.js:9
  https://testpilot.firefox.com/static/app/app.9a2988e445a5.js:1 in a
  https://testpilot.firefox.com/static/app/app.9a2988e445a5.js:1 in e
success // this comes from the console.log statement
```

Slimer (Gecko) throws: 

```
Script Error: [JavaScript Error: "ReferenceError: WeakSet is not defined" {file: "https://testpilot.firefox.com/static/app/app.9a2988e445a5.js" line: 10}]
       Stack:
         -> https://testpilot.firefox.com/static/app/app.9a2988e445a5.js: 10

success // this comes from the console.log statement
```

This script works just fine on other sites (tested on google and nytimes).

**Comment by lmorchard** [comment]
FWIW, I think the phantomjs / slimerjs errors are unrelated to this issue

**Comment by lmorchard** [comment]
So, a hunch - this might be related to #742 and a race condition:
- This error happens at [`initialize()` in `app/main.js`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/main.js#L24)
- `initialize()` calls [`updateEnabledExperiments()` in `app/models/me.js`](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L53)
- `updateEnableExperiments()` expects `this.installed` to be an Object (`{}`), but [it's initialized as an empty Array ('[]') by default](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L16).
- If `sync-installed` from the addon doesn't initialize that `this.installed` with an Object, we could be [trying to assign to a non-numeric index on an array by mistake](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/models/me.js#L56)

I haven't quite tracked this down, but I wonder if changing that `[]` to a `{}` and changing the server to send an object instead of an array would fix this?

**Comment by meandavejustice** [comment]
@lmorchard I have a branch for #742 I was having issues getting tests to pass, maybe we can get together tomorrow morning and get them passing to get the fix in.

branch => https://github.com/meandavejustice/testpilot/tree/742-audit-me-model-installed

**Comment by pdehaan** [comment]
Dear @johngruen,

I'm not sure what version of WebKit Phantom/Slimer are using, but it isn't too surprising that it may be choking on something ES6-fancy like that (see WeakSet browser compatibility:  https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#Browser_compatibility).

From a quick GitHub search, it looks like the only instance of [WeakSet](https://github.com/mozilla/testpilot/search?utf8=%E2%9C%93&q=weakset) in "our" comes from the l20n library: [./testpilot/frontend/static-src/vendor/l20n.js:169](https://github.com/mozilla/testpilot/blob/9f323963554d2267de4dc0e84b84ce58a9b75e7b/testpilot/frontend/static-src/vendor/l20n.js#L169).

So our browser support plans may be semi-blocked on what l20n supports (Ref https://github.com/l20n/l20n.js/pull/64 &mdash; which mentions WeakSet and IE11)

Not sure what our long term support plans are for other browsers. Currently we only support Firefox, but I thought the plan was to try and remove the sign-in as the first step so users and spiders could view the site/experiments without first creating an FxA account (but I can't find a GitHub issue stating that, so maybe I made it up).

---

**EDIT:** A few other random observations in this now off-topic sub-thread:

I tested in both PhantomJS (2.1.1) and SlimerJS (0.9.6) &mdash; both of which seemed to be the latest from npm.

``` js
var page = require('webpage').create();
var url = 'http://testpilot.dev.mozaws.net/';

page.open(url, function (status) {
  if(status === 'success') {
    page.render('test.png');
  }

  console.log(page.settings.userAgent);
  // phantomjs: Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1
  // slimerjs:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:33.0) Gecko/20100101 SlimerJS/0.9.6

  console.log(status); // success
  phantom.exit();
});
```

If I'm reading that mess of a UserAgent correctly, SlimerJS may be using **Firefox 33**? Looking at the [release notes for 0.9.6](http://docs.slimerjs.org/current/release-notes-0.9.html) (again, the version I _just_ pulled from npm), it looks like "SlimerJS 0.9.6 has been released on June 8th, 2015", which is ~11 months old, which is why it might not have WeakMap support (which wasn't added until **Firefox 34**, per the [compatibility link](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#Browser_compatibility) above).

Looks like SlimerJS 0.10 may have been released on May 2, 2016 (per http://docs.slimerjs.org/current/release-notes-0.10.html), so I'll see if I can get that installed locally and get your test to not cry at WeakMap sightings.

**Comment by meandavejustice** [comment]
> Because SlimerJS uses the version of firefox passed in the SLIMERJSLAUNCHER environment variable, edge builds of firefox can be used.

https://github.com/graingert/slimerjs/blob/master/README.md

**Comment by zackp30** [comment]
Sorry to be "that guy", but is this fixed now?

**Comment by lmorchard** [comment]
> Sorry to be "that guy", but is this fixed now?

Issue's still open, we're still poking at it.

**Comment by johngruen** [comment]
@lmorchard is this still a thing?

**Comment by johngruen** [comment]
@lmorchard @pdehaan I am closing this.
