### ISSUE TITLE
Add pointer cursors to forward/back navigation arrows in experiment tours

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#757]
Hat tip to @6a68 who reported in IRC.

Found in https://testpilot.firefox.com/__version__ (f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/360",
  "version": "2016-05-10",
  "source": "https://github.com/mozilla/testpilot",
  "commit": "f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd" }
```

---
### Steps to reproduce:
1. Sign in to https://testpilot.firefox.com/
2. Enable an experiment
3. Take the UI tour
4. Hover over the forward/back arrow graphics
### Actual results:

No pointer cursor

![firefox_test_pilot_-_activity_stream](https://cloud.githubusercontent.com/assets/557895/15159752/0ff6706c-16ab-11e6-9922-72a3c188670d.png)
### Expected results:

Pointer cursor to visually point out that the nav images are clickable.

**Comment by ckprice** [comment]
Adding to sprint.
