### ISSUE TITLE
Tab Center's disabled "New" text is hard to read (white-on-white) when using a Lightweight Theme (like "Furfox Tail Twister")

### ISSUE THREAD

**Issue by dholbert** [mozilla/testpilot#758]
STR:
1. Activate the "Tab Center" extension.
2. Hover the sidebar, and look at the "New..." text at the top.
3. NOW: Visit https://addons.mozilla.org/en-US/firefox/addon/furfox-tail-twister/ and install & apply that lightweight theme.
4. Repeat step 2 -- hover the sidebar, look at the "New..." text.

ACTUAL RESULTS:
The "New..." text is black in Step 2, but it's white-with-a-shadow in step 4 (on a whiteish background).  In other words: it looks broken & is really hard to read if you have a lightweight theme applied.

EXPECTED RESULTS:
Step 2 and Step 4 should give the same results.

I'm using latest Firefox Nightly, version 49.0a1 (2016-05-10).

**Comment by dholbert** [comment]
Screenshot with no theme:
![no-theme](https://cloud.githubusercontent.com/assets/426803/15160368/24a7b13a-16ae-11e6-979e-dddc1960b725.png)

Screenshot with lightweight theme (note the broken-looking white-on-white "New..." text at upper-left):
![theme](https://cloud.githubusercontent.com/assets/426803/15160391/345521c6-16ae-11e6-8a05-5aa718e17b69.png)

**Comment by dholbert** [comment]
It looks like this text-color-change is intended for stuff that's drawn on top of the lightweight theme background (like the "File | Edit | ..." menus shown at the right side of my screenshots).

However: this sidebar does _not_ have the lightweight theme background. So, it should not be using styling for text that's intended to be drawn on top of that background.

**Comment by pdehaan** [comment]
Closing. Filed in upstream **Tab Center** repo as https://github.com/bwinton/VerticalTabs/issues/149
