### ISSUE TITLE
Using tab center + bookmarks toolbar messes up IRCcloud?

### ISSUE THREAD

**Issue by ddurst** [mozilla/testpilot#762]
Using tab center, when I have the bookmarks toolbar shown, it would appear that the content frame's height is eaten into by the toolbar (note the difference between the two screenshots) -- and I can barely see the boundary of the message input control on irccloud; the window doesn't scroll, so I have to disable either tab center or bookmarks toolbar to use it again.

<img width="1546" alt="screen shot 2016-05-10 at 4 16 28 pm" src="https://cloud.githubusercontent.com/assets/395920/15161145/09174706-16cb-11e6-83f6-7361d61605cd.png">
<img width="1546" alt="screen shot 2016-05-10 at 4 16 39 pm" src="https://cloud.githubusercontent.com/assets/395920/15161150/0cb1b608-16cb-11e6-95b3-8b020cd678a8.png">

**Comment by pdehaan** [comment]
Closing. Filed in upstream **Tab Center** repo as https://github.com/bwinton/VerticalTabs/issues/148
