### ISSUE TITLE
Tab Center bookmark position indicator bug

### ISSUE THREAD

**Issue by karashata** [mozilla/testpilot#763]
I encountered a bug where the indicator for where a bookmark will be placed when moving bookmarks around in the toolbar is displayed significantly below the toolbar in the web page space when using Tab Center.
![tab center bookmark indicator bug](https://cloud.githubusercontent.com/assets/4993762/15161491/60a706f4-16cc-11e6-881f-cb3ba9e4743a.png)

**Comment by pdehaan** [comment]
Closing. Filed upstream in **Tab Center** repo as https://github.com/bwinton/VerticalTabs/issues/147
