### ISSUE TITLE
Test Pilot add-on post-install doorhanger has jaggedy edges on logo image

### ISSUE THREAD

**Issue by dholbert** [mozilla/testpilot#765]
STR:
1. Install Test Pilot add-on.
2. Watch for the "You're always just a click away from the latest experiments" doorhanger (pointing to the new button).

ACTUAL RESULTS:
 The image on this doorhanger has extremely jaggedy edges on the curves of the spaceship.

EXPECTED RESULTS:
 The image should not have jaggedy edges.

**Comment by dholbert** [comment]
Here's a screenshot of this logo image, in the Firefox UI:

![test-pilot-postinstall-image](https://cloud.githubusercontent.com/assets/426803/15163142/9af7cb38-16bb-11e6-9730-be3b7ef3526a.png)

**Comment by dholbert** [comment]
Here is the actual PNG from the extracted add-on package. The edges are jaggedy in this actual PNG file (viewed at its native resolution), as you can see here (e.g. on the fox's tail, and on the upper left edge of the spaceship):
![copter](https://cloud.githubusercontent.com/assets/426803/15163164/b421ff3e-16bb-11e6-8f5a-b9663c8a90e3.png)

**Comment by dholbert** [comment]
The logo image from the _actual website_ is here:
  https://testpilot.firefox.com/static/images/copter.png
Its edges are buttery-smooth.

Compare that against the [image attached above from the extension XPI](https://cloud.githubusercontent.com/assets/426803/15163164/b421ff3e-16bb-11e6-8f5a-b9663c8a90e3.png).  Edges are way smoother in the larger image from the actual website.

(I'm guessing the extension's jaggedy image was generated by doing a downscale in some image editor, and the image editor produced jaggedy edge artifacts.)

**Comment by johngruen** [comment]
@dholbert good catch. i think i downsampled that thing wrong!

**Comment by johngruen** [comment]
Fixed By #780

**Comment by dholbert** [comment]
Thanks! The image files in that commit (viewed on GitHub at least) look much nicer.

**Comment by johngruen** [comment]
gimme a minute to bump the version
