### ISSUE TITLE
checkboxes (and radio buttons) don't work in latest firefox version

### ISSUE THREAD

**Issue by Theophrastvs** [mozilla/testpilot#766]
I suppose it's gtk to blame, but only in the latest firefox versions are checkboxes and radio-buttons invisible.  I can't even properly send mozilla feedback because checkboxes widgets are involved.  thank you!

**Comment by chuckharmston** [comment]
Thanks for the report! I've moved it over to the official bug tracker for Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1271815
