### ISSUE TITLE
Recommended sites have black titles as opposed to being grey like the rest

### ISSUE THREAD

**Issue by HammyHavoc** [mozilla/testpilot#771]
#757 I searched "Berlin" as per the video demo of Universal Search, and the rest of the results are fine, but under FT DeepDark the recommended sites have black titles so they aren't readable, obviously this could be fixed within the theme itself, but I don't think it makes all that much sense to have this black by default anyway.

<img width="960" alt="berlin firefox 2" src="https://cloud.githubusercontent.com/assets/503951/15170162/516820fa-173b-11e6-9531-eaee8d543172.PNG">

**Comment by ckprice** [comment]
Moving this over to https://github.com/mozilla/universal-search/issues/206, thank you for the report!
