### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by InfiniteMonkeys** [mozilla/testpilot#772]
Just signed up for Test Pilot.  Tried installing Universal Search and the 'Enabling' status just hangs forever.  Exited, retried, same result.  Tried Activity Stream installation.  Same thing.

**Comment by johngruen** [comment]
@InfiniteMonkeys a few to help you debug this thing:
-  What OS are you on?
- What Version of Firefox?
- Can you go to tour Firefox add-on manager, select Test Pilot preferences and check the following: 
  - what is the exact add-on title?
  - is the add-on enabled?
  - what does the Environment selector say?

Let's see if we can debug your issue!

**Comment by InfiniteMonkeys** [comment]
OS: Windows 10 64-bit
Firefox: 46.0.1
Test Pilot Add-On
- AddOn Name: Test Pilot-0.5.7-tag-2016-05-10
- Enabled: Yes
- Environment: Production (testpilot.firefox.com)

**Comment by ghost** [comment]
https://github.com/mozilla/testpilot/issues/660 will fix this

**Comment by InfiniteMonkeys** [comment]
I hoped you were correct and some fix you had implemented would fix the
problem.

I uninstalled TestPilot, rejoined and reinstalled it.  Whenever I try to
enable "Activity Stream" or "Universal Search", the button just shows
"ENABLING" and never completes.  I have uninstalled it again and will wait
for someone else to reply with a fix that actually works.

Thanks
