### ISSUE TITLE
Browser doesn't POST immediately after disabling Universal Search

### ISSUE THREAD

**Issue by 13xforever** [mozilla/testpilot#773]
I had some issues with POSTing forms (post-uninstall survey, and filing an issue here on github) immediately after opting-out of Universal Search experiment.

There were no errors in console, and everything worked again after the browser restart.

I was testing on Firefox 48.0a2 (2016-05-10), Windows x64 build.

**Comment by johngruen** [comment]
@13xforever thanks for filing...just to be clear, are you referring to POSTs fired by the surveygizmo survey?

**Comment by 13xforever** [comment]
Yes, I'm referring to POSTs that should've been fired by either web forms, but I haven't seen a single one in the Network tab of dev console.

It might have to do with the hooking of uninstalling the experiments (so the browser is borked until restart).

**Comment by 13xforever** [comment]
This is most likely a duplicate of https://github.com/mozilla/universal-search/issues/213

**Comment by ghost** [comment]
ok, closing. thanks for filing
