### ISSUE TITLE
Get rid of scroll bar in testpilot tab center

### ISSUE THREAD

**Issue by g7r** [mozilla/testpilot#776]
Scroll bar appears on the tab center when I hover mouse cursor over it (all my tabs fit well in the Firefox window).
Platform: Windows8.
The scroll bar doesn't appear on Ubuntu.

**Comment by g7r** [comment]
![firefox-tabcenter-scroll](https://cloud.githubusercontent.com/assets/457958/15177865/02c2af20-177b-11e6-9b26-3c4502725979.png)

**Comment by johngruen** [comment]
Hey @g7r, thanks for filing the issue. I'm going to move this over to the vertical tabs repo: https://github.com/bwinton/VerticalTabs/issues/169
