### ISSUE TITLE
The main menu disappears with Tab Center enabled

### ISSUE THREAD

**Issue by romanblanco** [mozilla/testpilot#778]
I have no option to align items in the main menu with Tab Center feature enabled:
See the screenshots:  _(sorry for the resolution)_

Disabled:
![b](https://cloud.githubusercontent.com/assets/1187051/15182306/1537ed3a-178c-11e6-9243-1bb33d62cb4f.png)
Enabled:
![c](https://cloud.githubusercontent.com/assets/1187051/15182322/205590b4-178c-11e6-976a-bc4c522b481e.png)

**Comment by johngruen** [comment]
Hey @romanblanco thanks for the screenshots. I'm going to close this bug out and add the screenshots and text to an existing bug in the vertical tabs repo (where tab center lives)

**Comment by johngruen** [comment]
@romanblanco https://github.com/bwinton/VerticalTabs/issues/168

**Comment by romanblanco** [comment]
@johngruen thanks! :+1:
