### ISSUE TITLE
Shifted navigation menu with fullscreen and Tab Center enabled

### ISSUE THREAD

**Issue by romanblanco** [mozilla/testpilot#779]
With fullscreen window and Center Tab feature enabled, the navigation menu seems to be wrongly shifted and does not respond to mose hover.

Screenshot:
![d](https://cloud.githubusercontent.com/assets/1187051/15182436/b47d79a0-178c-11e6-99b2-dab221a48f4b.png)

**Comment by johngruen** [comment]
Thanks @romanblanco same thing as the other issue you filed here, moving this over to the verticalTabs repo. https://github.com/bwinton/VerticalTabs/issues/156

**Comment by johngruen** [comment]
High five
