### ISSUE TITLE
Tab Center masks bookmarks sidebar

### ISSUE THREAD

**Issue by doctorow** [mozilla/testpilot#781]
Tried Tab Center on Ffox for Ubuntu 15.10, but found that it obscured the bookmarks sidebar:

![056c026d-1c66-4d42-9fae-a8e96df290c5-1020x1060](https://cloud.githubusercontent.com/assets/19307926/15184496/482e9410-174a-11e6-8be4-a657977665b1.jpg)

I use the bookmarks sidebar to launch folders full of tabs -- daily visits, or all the URLs relevant to a project/context -- by selecting the folder and middle-clicking it.

I uninstalled Tab Center as a result.

**Comment by johngruen** [comment]
Hey @doctorow, thanks for reporting...this is a known bug: https://github.com/bwinton/VerticalTabs/issues/62
