### ISSUE TITLE
asked to survey activity stream twice in two days

### ISSUE THREAD

**Issue by willkg** [mozilla/testpilot#782]
I installed test pilot yesterday. Within 10 minutes, it asked me to fill out a (very long) survey for activity stream.

It just asked me to fill out another survey for activity stream today.

Why is it asking me to fill out a survey for the same experiment two days in a row? That seems overly zealous.

Using Firefox dev edition 2016-05-11 on Ubuntu 16.04. I updated dev edition today--I don't remember what version I was using yesterday.

**Comment by meandavejustice** [comment]
@willkg This is a bug, it is not our intention to ask that suddenly. Thanks for bringing this to our attention.

**Comment by meandavejustice** [comment]
I'm having trouble reproducing this locally. If @6a68 @pdehaan @lmorchard have time, would you mind taking a look at this as well? Here is the entry point => https://github.com/mozilla/testpilot/blob/master/addon/lib/survey.js#L34

We are supposed to return early [here](https://github.com/mozilla/testpilot/blob/master/addon/lib/survey.js#L86) if our interval doesn't pass `checkInstallDate`

**Comment by ghost** [comment]
I'm seeing this for Tab Center at least once a day as well.

**Comment by meandavejustice** [comment]
Moving into current milestone because this bug is A N N O Y I N G

**Comment by ckprice** [comment]
I'm going to add an additional piece of feedback from @mattgrimes:

> we only have 30ish responses for each experiment at the 7 day interval
> so even if I include partial responses (anyone that gave a HB score but didn’t actually take the survey) we only have 24 total for Tab Center day 7
> which means either super high attrition prior to that date or something else is happening

This is high priority to investigate to confirm it's not something on the Test Pilot side.

@meandavejustice this is still planned for this sprint (ending tomorrow). Should we update this bug to something like "Investigate survey intervals" or are you good to leave as is.
