### ISSUE TITLE
click on "x" of survey bar scrolls page to top

### ISSUE THREAD

**Issue by willkg** [mozilla/testpilot#783]
I got asked to fill out a survey for activity stream today. Given that I filled it out yesterday, I didn't want to do it again today. So I clicked on the "x".

When I clicked on the "x", the page I was reading scrolled all the way to the top. It was a long page, so I lost my place.

Clicking on the "x" of the survey request bar shouldn't change the page it's over at all.

**Comment by willkg** [comment]
I'm using Firefox dev edition 2016-05-11 on Ubuntu 16.04.

**Comment by johngruen** [comment]
@meandavejustice

**Comment by johngruen** [comment]
Thanks for reporting @willkg!

**Comment by MattGrimes** [comment]
@willkg this is on the star rating prompt, not the actual survey? Is that correct?

**Comment by willkg** [comment]
That's correct. I was looking at a web page and this bar appeared at the top of the view port asking me to rate activity stream. Clicking on the "x" of that bar caused the page i was reading to scroll to the top.

**Comment by meandavejustice** [comment]
~~Hello @willkg I'm having trouble reproducing this one. Do you remember what page you were on so I can try it there?~~ nm I was just able to get it to happen on wikipedia

**Comment by meandavejustice** [comment]
@willkg Thanks for bringing this to our attention.
I've filed a bug upstream, https://bugzilla.mozilla.org/show_bug.cgi?id=1273607. 

@6a68 Tested on OS X and did not see the issue. Going to close since this is an issue with XUL on Linux.
