### ISSUE TITLE
Test Pilot website sometimes uses a lot of CPU

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#786]
We had [a report](http://logs.glob.uno/?c=testpilot#c9688) come in on IRC of the Test Pilot website using excessive amounts of CPU.

CC @johngruen

**Comment by chuckharmston** [comment]
One idea: the floating fox animation is likely quite processor-intensive if not hardware-accelerated. Unfortunately, that [is not detectable](https://github.com/Modernizr/Modernizr/wiki/Undetectables#general-undetectables).

**Comment by pdehaan** [comment]
Workaround is maybe just do the animation 5-10 times and then stop.
I think we really only have the bouncy animation on the following pages:
1. https://testpilot.firefox.com/ &mdash; if you're not logged in.
2. https://testpilot.firefox.com/experiments/ &mdash; if you're logged in and staring at list of experiments.
3. https://testpilot.firefox.com/experiments/tab-center &mdash; in the modals if you are prompted to take a tour or give feedback after disabling the experiment.
