### ISSUE TITLE
Discourse integration

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#788]
We now have [Discourse categories](https://discourse.mozilla-community.org/c/test-pilot) for Test Pilot and all the active experiments.

Let's figure out the right places to integrate Discourse into the TxP UI.

**Comment by johngruen** [comment]
@6a68 let's do this for now...see how we do and iterate:
<img width="1440" alt="screen shot 2016-05-12 at 8 11 00 pm" src="https://cloud.githubusercontent.com/assets/3323249/15234611/742a211e-1881-11e6-9e91-deb19367a25c.png">

<img width="1440" alt="screen shot 2016-05-12 at 8 25 21 pm" src="https://cloud.githubusercontent.com/assets/3323249/15234609/6d90df78-1881-11e6-9d48-37379ddab715.png">

**Comment by pdehaan** [comment]
In the spirit of copy-pasta, here's the screenshot text:

> # Just one second...
> 
> In the spirit of experimentation, we're using a forum service that requires an account different from the one you created for Test Pilot. We are working hard to change this and make the forum experience smoother.
> 
> If you don't feel like creating another account, you can always leave feedback through Test Pilot.
> (We really do read this stuff)
> 
> [Take me to the forum]
> Cancel

~~I'm not sure if "leave feedback through Test Pilot" should be linked or not. Wasn't sure if that directs people to the GitHub issues for Test Pilot, or if we leave it unlinked and it's implied that it's the experiment specific "Give feedback" buttons.~~

**Comment by johngruen** [comment]
@pdehaan i think for now, let's leave that copy unlinked. It's available on the landing page as well as the experiment pages, so it'd be hard to determine intent.

**Comment by meandavejustice** [comment]
@6a68 IRC is messing up for me rn. But yes I can take care of this, this week.

**Comment by jaredhirsch** [comment]
Awesome, thanks @meandavejustice :-)
