### ISSUE TITLE
Unable to scroll fully to the bottom - Tab Center

### ISSUE THREAD

**Issue by TDA** [mozilla/testpilot#789]
After installing Tab Center, I noticed that I am unable to fully scroll to the bottom of the tabs list, and certain websites, like GitHub for example.
### Before Tab Center

<img width="1440" alt="screenshot 2016-05-11 11 00 26" src="https://cloud.githubusercontent.com/assets/432707/15191024/a1212f34-1767-11e6-9e90-9a22aac537c1.png">
### With Tab Center

<img width="1440" alt="screenshot 2016-05-11 10 59 40" src="https://cloud.githubusercontent.com/assets/432707/15191034/a603b45e-1767-11e6-996e-6a5c03389ebf.png">

**Comment by meandavejustice** [comment]
Thanks for filing.
moved to https://github.com/bwinton/VerticalTabs/issues/179
