### ISSUE TITLE
Port features to Android

### ISSUE THREAD

**Issue by LifeIsStrange** [mozilla/testpilot#791]
All is in the title and thanks for making open source software, you make the World better :)

**Comment by LifeIsStrange** [comment]
Oh sorry there is already Android support, but could you port the features to Android ?

**Comment by johngruen** [comment]
We're exploring this!

**Comment by LifeIsStrange** [comment]
Thank you :) I would be happy to test it !

**Comment by ghost** [comment]
Thanks for filing. We'll track this in https://github.com/mozilla/testpilot/issues/672
