### ISSUE TITLE
Opening a test project from the extention often does not work

### ISSUE THREAD

**Issue by mrleblanc101** [mozilla/testpilot#792]
Firefox open a new tab called "Test pilot" but the experiment never load and Firefox does not show any sign of loading. If you try again, then the page will load but it's annoying and should be fixed quickly

**Comment by pdehaan** [comment]
@mrleblanc101 Thanks for the bug report! It sounds like you're likely hitting this issue: #755

We're investigating and hope to have a fix shortly.
Closing this issue in favor of #755.
