### ISSUE TITLE
Scrollbar functionality impaired with Tab Center

### ISSUE THREAD

**Issue by martindholmes** [mozilla/testpilot#793]
Using the Tab Center add-on in FF 46.0 (Ubuntu 16.04 64-bit), certain pages do not scroll properly, whether the bar is minimized or pinned open. This page, for instance:

https://ant.apache.org/manual/Tasks/fail.html

will not scroll past `</resourcecount>`.

**Comment by pdehaan** [comment]
Closing. I believe this is a dupe of the upstream **Tab Center** repo's https://github.com/bwinton/VerticalTabs/issues/105.
