### ISSUE TITLE
Test Pilot reports Tab Center as enabled when it is actually disabled

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#795]
Originally reported by @bobsilverberg 

Fx 46.0.1, OS X 10.11.4, a bunch of add ons installed, including Tab Mix Plus. See screenshots below:

![screenshot 2016-05-10 08 10 50](https://cloud.githubusercontent.com/assets/142755/15146072/45a25e66-1687-11e6-82aa-3e568ed46d15.png)

![screenshot 2016-05-10 08 12 08](https://cloud.githubusercontent.com/assets/142755/15146078/4bb5dd14-1687-11e6-8c25-2493043b800f.png)

**Comment by meandavejustice** [comment]
related to #680

**Comment by meandavejustice** [comment]
closing in favor of #680
