### ISSUE TITLE
Unable to install Test Pilot add-on if I have HttpFox installed/active

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#796]
Found in https://testpilot.firefox.com/__version__ (f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd):

``` json
{ "commit": "f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd",
  "build": "https://circleci.com/gh/mozilla/testpilot/360",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-10" }
```

---

@jrgm showed me this this morning and I was able to reproduce locally (as long as HttpFox is toggled/active).
### Steps to reproduce:
1. Install https://addons.mozilla.org/en-US/firefox/addon/httpfox/ and open the network monitor (Tools > Web Developer > HttpFox > Toggle HttpFox)
2. Go to https://testpilot.firefox.com/ and sign up.
3. Install the Test Pilot add-on
### Actual results.

The spinner button just says "Installing Test Pilot..." but I never see a doorhanger or the add-on get installed. Seems specific to HttpFox. Not sure how common add-on collisions are.

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/15196770/e06b828c-1782-11e6-9a13-f51d4a752f83.png)
**Figure 1:** Stuck on "Installing Test Pilot..."

---

![browser_console](https://cloud.githubusercontent.com/assets/557895/15196789/f10d93d2-1782-11e6-9bba-7676b12e0e25.png)
**Figure 2:** Browser Console output. Nothing fascinating, but seeing an HTTP/400 trying to XHR POST to Basket API.

---

![httpfox](https://cloud.githubusercontent.com/assets/557895/15196914/85724068-1783-11e6-9a38-f48f50568011.png)
**Figure 3:** HttpFox output. Similar error for HTTP/400 to Basket API and odd red line for the /static/addon/addon.xpi
### Expected results:

Not sure why having HttpFox open/active would prevent me from seeing an XPI install doorhanger or proceeding.

**Comment by pdehaan** [comment]
Clicking "Stop" in HttpFox and then clicking [Installing Test Pilot...] button again seems to make it work, so it definitely looks like its an add-on issue. Not sure how actionable this is.

**Comment by johngruen** [comment]
closing in favor of #944
