### ISSUE TITLE
"TypeError: e is undefined" if I click the [...] button lots

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#798]
Found in https://testpilot.firefox.com/__version__ (f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd):

``` json
{ "commit": "f5b1b19dfdcbaafba4e5fc335fdc8b90cdfc79bd",
  "build": "https://circleci.com/gh/mozilla/testpilot/360",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-10" }
```

---
### Steps to reproduce:
1. Go to https://testpilot.firefox.com/ and sign in.
2. Install the add-on.
3. Click the [...] in the top-right corner.
4. After the drop-down menu is open, keep clicking the [...] button.
### Actual results

The first time you click the [...] button, life is great and you're your best you!
The second time you click the [...] button (if the menu is already open) you get a TypeError in your Developer Tools console or Browser Console.

![firefox_test_pilot_-_experiments](https://cloud.githubusercontent.com/assets/557895/15198142/6aff3fb8-178a-11e6-9553-d76c5f2874b9.png)

Closest I can figure from the minified source (do we have sourcemaps enabled?), the error is coming from roughly [./testpilot/frontend/static-src/app/views/settings-menu-view.js:37-38](https://github.com/mozilla/testpilot/blob/312e91baf5a3b21cb92ac478ed69e62fe9644ccd/testpilot/frontend/static-src/app/views/settings-menu-view.js#L37-L38):

``` js
  close(ev) {
    if (!ev.target.parentElement.classList.contains('settings-menu')) {
      this.query('.settings-menu').classList.add('no-display');
      this.query('.settings-button').classList.remove('active');
    }
  },
```

My _guess_ is that for some reason, `ev` is undefined if the pop-up is already visible, and we just need another `null` check.

**Comment by pdehaan** [comment]
I can still reproduce this on https://testpilot.stage.mozaws.net/experiments (but testpilot.dev.mozaws is broken right now so I can't verify in leading edge build)

**Comment by dannycoates** [comment]
This looks like it was fixed here: https://github.com/mozilla/testpilot/commit/9ff10c3d9fd999fa33a9235fb66c544cd7a43f26#diff-9122a431ad71d321669d254c7c602d82L70

**Comment by SoftVision-PaulOiegas** [comment]
Verified this on dev server and haven't seen the issue anymore. 
Tested on both Windows 10 (x64) and Mac OS 10.11.
