### ISSUE TITLE
The doorhanger is following me…

### ISSUE THREAD

**Issue by cvan** [mozilla/testpilot#799]
<img width="1440" alt="screen shot 2016-05-11 at 3 40 05 pm" src="https://cloud.githubusercontent.com/assets/203725/15198841/e461a540-178e-11e6-9188-bfe97e6da806.png">

Mac OS X 10.11.2 (15C50)
Firefox Nightly 49.0a1 (2016-05-11)
1. Install the extension.
2. Quickly change windows.
3. Notice the cute doorhanger persists, appearing atop other applications.
4. Open Firefox to notice the doorhanger is now gone.

**Comment by meandavejustice** [comment]
I've just pushed a partial fix for this. It's at https://github.com/mozilla/testpilot/pull/859. In the process I've come across an upstream bug in the [addon-sdk](http://github.com/mozilla/addon-sdk).

details => https://bugzilla.mozilla.org/show_bug.cgi?id=1230816#c1

**Comment by jaredhirsch** [comment]
The relevant SDK source code seems to be here: https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/tabs/observer.js#37-95

Based on the comments in that chunk of code, it looks like the SDK fires the 'deactivate' event in the cases where the user switches tabs or switches between Firefox windows, but not in the case where the user switches away from the Firefox application.

Here's a workaround:
- when the doorhanger is shown, add a 'deactivate' listener on the window itself
  - try this in the browser toolbox to convince yourself it works: `window.addEventListener('deactivate', () => { console.log('window deactivated') })`
- when the application loses focus, the 'deactivate' listener will fire
- have the listener detach itself, then hide the doorhanger

You could optionally get fancy and check if the [`nsIFocusManager`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIFocusManager)'s `activeWindow` is null, which definitively tells you if Firefox has lost the focus, but I don't think we need to be terribly specific here. Just closing the doorhanger on deactivate should work.

**Comment by meandavejustice** [comment]
Thanks @6a68 this looks like a great solution. Updating the pr now.

**Comment by johngruen** [comment]
This should be closed by #1043
