### ISSUE TITLE
Lots of JS errors on front page

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#800]
I'm seeing a ton of JS errors on the site right now. This doesn't seem normal:

<img width="1255" alt="screen shot 2016-05-11 at 4 00 16 pm" src="https://cloud.githubusercontent.com/assets/96396/15199264/965d9bee-1791-11e6-82e3-9174b055853a.png">

**Comment by pdehaan** [comment]
@6a68 Are you still seeing this, or was it HTTP/50x related?
I'm not seeing it currently on https://testpilot.firefox.com/experiments w/ Release.
