### ISSUE TITLE
Fullscreen video display not rendering correctly.

### ISSUE THREAD

**Issue by Recon419A** [mozilla/testpilot#801]
![2016-05-11 1](https://cloud.githubusercontent.com/assets/16583234/15204258/f8ee7c62-17d0-11e6-99bf-e67242f539bc.png)
![2016-05-11](https://cloud.githubusercontent.com/assets/16583234/15204259/f8efa664-17d0-11e6-8d09-0544366bd923.png)

The fullscreen button on Netflix and YouTube causes bars to remain on the sides of the screen when clicked.

**Comment by meandavejustice** [comment]
@Recon419A Is this a bug report for testpilot or firefox?

**Comment by Recon419A** [comment]
It only applies to the new tab center.

**Comment by pdehaan** [comment]
@Recon419A Thanks for the bug report. I've moved the bug to the **Tab Center** repo: https://github.com/bwinton/VerticalTabs/issues/196

Closing this issue in favor of the upstream Tab Center one.
