### ISSUE TITLE
Stuck on 'Enabling' for over 10 minutes

### ISSUE THREAD

**Issue by Finnikin** [mozilla/testpilot#802]
After installing Tab Center successfully, I attempted to enable both Activity Stream and Universal Search. Both of which I have tried to enable separately with no success except for the 'Enabling button acting as though it is loading for over ten minutes each. Any help is appreciated.

Screen Grab:
![Enabling_Loop](https://cloud.githubusercontent.com/assets/1754642/15205946/c8cdc34c-185e-11e6-8d2a-d8884ca178e0.PNG)

**Comment by northernned** [comment]
I had a similar experience. I found if you disable tab center and go back to enable either activity stream or universal search, they seem to enable.

I had to hit enable give it a few seconds then go back to the test pilot homepage and then they appear as enabled

**Comment by Finnikin** [comment]
> northernned commented 28 minutes ago
> 
> I had a similar experience. I found if you disable tab center and go back to enable either activity stream or universal search, they seem to enable.
> 
> I had to hit enable give it a few seconds then go back to the test pilot homepage and then they appear as enabled

Thanks for your suggestion, I just tried that and it did not work for me. However, I was able to re-enable the Tab-Center after attempting it.

**Comment by meandavejustice** [comment]
Thanks for reporting @Finnikin. It sounds like we need better error handling and messaging here.

**Comment by ghost** [comment]
https://github.com/mozilla/testpilot/issues/660 will handle this
