### ISSUE TITLE
Feedback form preventing feedback?

### ISSUE THREAD

**Issue by eklem** [mozilla/testpilot#804]
Hi,
I'm testing `Activity stream`, `Tab center` and `Universal search`, and I get new ideas for feedback all the time, but it's cumbersome to reply to all the generic questions all the time. Maybe skip it or keep the old answers the second time around?

**Comment by meandavejustice** [comment]
@eklem This is a good point. ccing/ @ckprice for discussion.

**Comment by johngruen** [comment]
Hey @eklem, I agree :) we want to make the whole feeback circuit a lot shorter...feel free to file issues on github.

**Comment by eklem** [comment]
Didn't I just do that, @johngruen ? =P Or do you want it in another form or more specific?

**Comment by johngruen** [comment]
hey @eklem we've made all survey questions optional
