### ISSUE TITLE
All Conflict

### ISSUE THREAD

**Issue by ddepatie** [mozilla/testpilot#805]
Hi; I am so excited to finally have a little input!!! I am on windows 10 enterprise, 64bit, i7 with 16GB. I have engaged all three; Active stream, Tab Center & Universal search. I [CRTL] + [TAB] all day between windows. There is an issue with the full screen mode. You can not see the information at the bottom of the window. But, if you use [F11] to full screen then the bottom of the window is view-able. This a problem as I then loose the task bar. I hope you find this feed back useful. As tech support at the University of Florida, I STRONGLY suggest that all the student use Firefox, as it gives us the least problems and issue with our LMS Canvas.
Dave
: -)
ddepatie@ufl.edu

**Comment by pdehaan** [comment]
@ddepatie Thanks for trying Test Pilot and giving feedback!
It sounds like you're hitting this **Tab Center** issue: https://github.com/bwinton/VerticalTabs/issues/105.

Closing this bug in favor of the upstream Tab Center bug.
