### ISSUE TITLE
Triage of recent outage and changes to make to improve scaling

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/testpilot#810]
While triaging the recent outage we discovered that: 
- when `DEBUG=false` 
  - the app returns a 500 error code for all requests. This includes `/` and `/__lbheartbeat__` which means it can never join the load balancer.
  - whitenoise defaults to `Cache-Control: public, max-age=0` for static assets which disables nginx proxy caching. 
- ~~~the app appears to be single threaded, able to handle only a single request at a time. When the python process is overloaded the `__lbheartbeat__` endpoint becomes unresponsive and the server is removed from the load balancer and terminated.~~~

Changes to make: 
- [x] Determine and fix the app to work in when `DEBUG=false`
- [x] Provide a better default for static assets, even 60s would improve the performance of the site substantially 
- [x] ~~Fix why we basically get single threaded concurrency. Is it not an evented engine in the docker container? Can we configure how many child processes to start up?~~
- [x] ~~On [this line](https://github.com/mozilla/testpilot/blob/master/bin/run-prod.sh#L4) it should be `exec gunicorn...` so bash replaces itself and process signals can be sent to gunicorn instead of being lost~~ (ref #816)

cc @lmorchard @relud

**Comment by mostlygeek** [comment]
I figuree out the concurrency issue and will fix on the deployment side. Basically set `WEB_CONCURRENCY` to 4\* number of CPUs in the environment.

**Comment by chuckharmston** [comment]
The default value for `WHITENOISE_MAX_AGE` is `60 if not settings.DEBUG else 0`, so it seems likely that being able to turn `DEBUG` to `False` will solve the problems.

http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_MAX_AGE

That said, there's no reason we couldn't set it to `60 * 60 * 24` or something moderately aggressive, since the upstream cache is flushed with each deploy.

**Comment by mostlygeek** [comment]
> That said, there's no reason we couldn't set it to 60 \* 60 \* 24 or something moderately aggressive, since the upstream cache is flushed with each deploy.

The `Cache-Control` value is sent to the user as well, so we have to consider the browser's cache too. I think 60s will already make a huge performance improvement on the server side.

**Comment by lmorchard** [comment]
This Django app is not evented and I don't think multi-threading support is great in Django & Python - though my understanding might be outdated.

Looks like [gunicorn has a config option to run multiple worker processes](http://docs.gunicorn.org/en/latest/run.html#commonly-used-arguments), which I think is the thing to do here. The docs suggest "This number should generally be between 2-4 workers per core in the server."

So maybe I can just pass `-w $WEB_CONCURRENCY` into `gunicorn`?

**Comment by relud** [comment]
When I was load testing [normandy](https://github.com/mozilla/normandy) we found that the right number of workers varied greatly by which worker type being used (between sync, eventlet, and gevent). eventlet got the best performance with 1 worker per core, and sync should not be used in production. I don't remember how gevent performed, other than being slower than eventlet.

**Comment by mostlygeek** [comment]
I think @lmorchard has the right approach. Going multi-process means less simpler and we don't have to worry about django+middleware being async safe.

**Comment by lmorchard** [comment]
So, I think the 500 errors when DEBUG=False on prod boil down to one issue in the frontend HTML template, which #834 should fix on next deploy. And once DEBUG=False, the default 60 second Max-Age header in whitenoise should kick in.

**Comment by mostlygeek** [comment]
Great! let's get this deployed asap! When you're ready please roll a release and we'll get it into stage to kick the tires a bit.

**Comment by lmorchard** [comment]
@ckprice Friday deployments stink, but maybe we should get something started to staging at least? That, or something early Monday. Would be nice to see if recent work resolves things and we can turn off DEBUG on stage & prod

**Comment by lmorchard** [comment]
Going to say this is resolved after our prod push today.
