### ISSUE TITLE
Site not loaded

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#811]
After enabling, https://en8.forgeofempires.com/game/index?ref= (uses Flash player) stops working. It does not load. (White screen.)

**Comment by meandavejustice** [comment]
Thank you @slitkx, This sounds like a bug for the firefox bugtracker, https://bugzilla.mozilla.org/. Here are some tips for reporting bugs https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

**Comment by ghost** [comment]
Why would that be a bug for Firefox Bugtracker, as page is not loaded AFTER enabling this experimental feature?

**Comment by pdehaan** [comment]
@slitkx Which add-ons/experiments did you enable on the Test Pilot site?
I have the Test Pilot and Activity Stream add-ons enabled in my Firefox 46/OS X and am able to see  https://en8.forgeofempires.com/game/index?ref= (and the Flash video on that page).

Does disabling the Test Pilot add-on make the forgeofempires site start working again?

**Comment by ghost** [comment]
First site is loaded, but a white screen appears after clickin on 'world's' button (to actually enter game's playground). I'll try and reply.

**Comment by ghost** [comment]
It stops working after enabling Tab Center - more specific, after clicking on 'Houndsmoor' button (Houndsmoor is one of the worlds.) After disabling Tab Center, site is automatically and successfully reloaded.

![free to play strategy game online - forge of empires](https://cloud.githubusercontent.com/assets/10394206/15223445/c3860460-1874-11e6-805d-492b80557c86.png)

**Comment by ghost** [comment]
It works now.
