### ISSUE TITLE
i cant able to test "Tab Center"

### ISSUE THREAD

**Issue by mutharasum23** [mozilla/testpilot#812]
I am using ubuntu  14.04  with firefox. i cant able to access the tab center option

**Comment by pdehaan** [comment]
@mutharasum23 What do you mean by "i cant able to access the tab center option"?

Is the https://testpilot.firefox.com/experiments/tab-center page not loading for you, or is the add-on not enabling as expected?

**Comment by ghost** [comment]
It's been 2 weeks. closing...
