### ISSUE TITLE
Test Pilot add-ons don't sync

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/testpilot#813]
Was testing out Sync performance and noticed that while AMO add-ons and themes are syncing, Test Pilot was not.

Original device:
<img width="1286" alt="unknown" src="https://cloud.githubusercontent.com/assets/68213/15221096/00e4545c-1838-11e6-9b86-e86710cd862a.png">

Second device:
![57349dba3c2a7](https://cloud.githubusercontent.com/assets/68213/15221095/00e120f2-1838-11e6-8e2a-1a2a0bbfd3cf.jpg)

**Comment by johngruen** [comment]
@ryanfeeley This is probably a good thing, since idk if the signed-in account state would persist across devices. Tempted to wontfix

**Comment by ckarlof** [comment]
I'm not seeing Test Pilot itself sync. There's way to Sync custom stuff for addons and I'd consider exploring that before closing wontfix.

**Comment by lmorchard** [comment]
I'm not sure we actually want Test Pilot add-ons to sync. We've been working from an assumption that users should be able to run different sets of experiments using different profiles & Firefox installations. The Test Pilot add-on generates an ID for each browser & profile in which it's installed, so we can keep track of possibly multiple browsers per user.

Not that that precludes syncing the installations between profiles, but I don't think that's something we've really given any thought or testing.

**Comment by ckarlof** [comment]
However the team decides it should be behave, the behavior should be intentional, not accidental, and there should be test plan to ensure it doesn't regress from the intended behavior. 

/cc @clouserw @pdehaan

**Comment by ghost** [comment]
We discussed this in our triage this morning.  Someone (Jared?) looked into syncing and it sounds like only add-ons installed from AMO sync, so, the system is working as expected.

We also talked about whether we wanted this or not, and the feeling was that it would complicate our instrumentation and wasn't something we wanted to deal with right now.

So, it's good to have an explanation of what's going on, but this is a wontfix.  Thanks for filing.
