### ISSUE TITLE
Bottom of Webpages are not shown 

### ISSUE THREAD

**Issue by Masteroftruth** [mozilla/testpilot#814]
Hi - Im testing things and I already see a problem - the bottom of some of my datingsites - like plantromeo and gayroyal 
Is there anything to do about that

**Comment by pdehaan** [comment]
@Masteroftruth Thanks for the bug report!
It looks like you're probably hitting the following **Tab Center** issue: https://github.com/bwinton/VerticalTabs/issues/105

Closing in favor of upstream bug.
