### ISSUE TITLE
Telemetry pings are underreported

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#815]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1272395 .  I don't know if it's in the code or in the pipeline.  I think we're just doing a simple call to submitExternalPing() but this issue is to double check that code and make sure we're not doing anything obviously wrong.  We'll come at it from the other side too.

**Comment by ghost** [comment]
It looks like we only ping if it's been longer than 24 hours:  https://github.com/mozilla/testpilot/blob/master/addon/lib/metrics.js#L72

**Comment by karlht** [comment]
Stuart and I have both observed that the 'testpilot' ping does not show up in about:telemetry ten minutes after we install test Pilot on a fresh profile.  We're both on Nightly (49.0a) -- he's on OS X and I'm on Linux.

Is this expected behaviour?  How soon should we expect the first 'testpilot' ping to appear after installation?

**Comment by stuartphilp** [comment]
Maybe it ought to send sooner for the first ping and then get on the 24 hour timer?

**Comment by ghost** [comment]
If I'm reading the metrics.js script correctly, the first ping goes out at 24 hours and 10 minutes.  That shouldn't happen -- @lmorchard can you confirm?

@lmorchard on line 37 there is a reference to store.telemetryPing.  Can you tell us where that is being set?

**Comment by lmorchard** [comment]
> If I'm reading the metrics.js script correctly, the first ping goes out at 24 hours and 10 minutes. That shouldn't happen -- @lmorchard can you confirm?

Yeah, that's probably what the code does now.

> on line 37 there is a reference to store.telemetryPing. Can you tell us where that is being set?

Looks like it doesn't - I think that was meant to be `telemetryPingPayload` or something got renamed along the way.

Can get a PR together to fix these two things

**Comment by lmorchard** [comment]
Do we have a way to see where these pings end up / when they happen? We've been kind of developing this stuff against a black box without a way to verify the results.

**Comment by lmorchard** [comment]
[Got what I _think_ are some fixes in PR #938](https://github.com/mozilla/testpilot/pull/938), but I'm not seeing _any_ pings newer than 5/8 in my about:telemetry "Archived ping data" section that would verify that it's working.
