### ISSUE TITLE
Problem on youtube full screen - tab center

### ISSUE THREAD

**Issue by smol-ninja** [mozilla/testpilot#819]
![selection_002](https://cloud.githubusercontent.com/assets/6676622/15223379/c51b5e02-1891-11e6-9656-e6f9a6d20506.jpg)

When I make the YouTube video full screen, this is how it looks like. You see that white area on the right and bottom side of the page. This problem arises when I enabled tab center .

**Comment by shubhamy** [comment]
The white area on the right side and bottom side.

**Comment by pdehaan** [comment]
@shubhamy: Which **Test Pilot** experiments do you currently have enabled?
This may be the same issue as #801, but more details would help debug this.

**Comment by smol-ninja** [comment]
I have updated my comment. And yes, it is the same issue as #801. Frankly I am loving the tab center feature. But this is the only issue which forced me to disable it. But I had to enable it again because of the flexibility of switching tabs that it gives when the number of tabs increases.

I have also observed that if I keep sidebar open by pinning it, the width of the white area increases.

**Comment by pdehaan** [comment]
@shubhamy Thanks for the bug report. I've moved the bug to the **Tab Center** repo: https://github.com/bwinton/VerticalTabs/issues/196

Closing this issue in favor of the upstream Tab Center one.
