### ISSUE TITLE
Add ISSUE_TEMPLATE.md to help adventurous issue reporters find the correct repos

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#821]
The exceptionally handsome @chuckharmston reminded me of the new [Issue and Pull Requests templates](https://github.com/blog/2111-issue-and-pull-request-templates) support in GitHub and they'd probably be a good fit in this repo.

I figure a simple .github/ISSUE_TEMPLATE.md which possibly points people to the correct experiment repos before they file an issue in Test Pilot.

Can't hurt to try... Or _can_ it?

Discuss, or fear my PR wrath when I eventually get around to an initial stab at some horrible word-smithing.

/cc @ckprice @clouserw

**Comment by meandavejustice** [comment]
YAAASSS

**Comment by ckprice** [comment]
👍

**Comment by pdehaan** [comment]
You sure you don't want to add any more Labels to this? I'm sure we have a few extra stored in the back room if you need me to find them.
