### ISSUE TITLE
Switch to sign-addon for `npm run sign`

### ISSUE THREAD

**Issue by kumar303** [mozilla/testpilot#822]
The [npm run sign](https://github.com/mozilla/testpilot/blob/master/addon/bin/sign) script requires the [jpm](http://github.com/mozilla-jetpack/jpm/) package to perform signing. After https://github.com/mozilla-jetpack/jpm/issues/519 lands, jpm will be using the [sign-addon](https://github.com/mozilla/sign-addon/) module directly for signing so testpilot should use `sign-addon` directly as well.

I don't think testpilot will break when jpm moves to `sign-addon` but you'll get a few benefits from moving to it:
- sign-addon is a smaller package to depend on
- new features and bug fixes will be added to sign-addon first
- the interface in sign-addon will be better supported for programmatic use

**Comment by ckprice** [comment]
@kumar303 I don't suppose this would also fix #715?

**Comment by meandavejustice** [comment]
@ckprice Nope, this is basically a code quality upgrade. Thanks @kumar303

**Comment by ghost** [comment]
We're getting away from using the SDK but not ready to jump to a web extension yet.  We'll be continuing as a bootstrap add-on.  Is this the right module to continue to use?  @kumar303 @andymckay

**Comment by lmorchard** [comment]
Hmm, yeah [there's mention of webextensions in the readme](https://github.com/mozilla/sign-addon/#dealing-with-extension-ids), so sounds like this is the module we'll want to use going forward regardless of add-on type.

**Comment by kumar303** [comment]
Yes, `sign-addon` would be a better package to use instead of `jpm`.

**Comment by johngruen** [comment]
We'll leave this open pending signing solution for webExt

**Comment by ghost** [comment]
This might change again now that we have special signing for Mozilla Extensions

**Comment by lmorchard** [comment]
No longer need this, since signing is done with a Mozilla Extension key.
