### ISSUE TITLE
Footer not visible - tab center

### ISSUE THREAD

**Issue by smol-ninja** [mozilla/testpilot#823]
![selection_001](https://cloud.githubusercontent.com/assets/6676622/15224210/b618a276-1895-11e6-9baf-b7a8171ef2c3.jpg)
![selection_002](https://cloud.githubusercontent.com/assets/6676622/15224211/b61ec99e-1895-11e6-949f-e193d997c17b.jpg)

When I enable tab center, footer is not completely visible.

**Comment by pdehaan** [comment]
@shubhamy Thanks for the bug report!
I believe this is a dupe of this **Tab Center** issue: https://github.com/bwinton/VerticalTabs/issues/105

Closing this in favor of the upstream **Tab Center** issue.
