### ISSUE TITLE
Fullscreen issue - Tab Center

### ISSUE THREAD

**Issue by CiRiX-** [mozilla/testpilot#826]
Hello. I really like the idea for the Tab Center plugin. I have one problem with it. When entering fullscreen mode in videos, it doesn't use the whole screen. It looks like Tab Center takes up the space on the sides of the video.

It looks like this when going into fullscreen mode in a video on youtube: https://i.imgur.com/Nkha3VC.png

**Comment by pdehaan** [comment]
@CiRiX- Thanks for the bug report. I've moved the bug to the **Tab Center** repo: https://github.com/bwinton/VerticalTabs/issues/196

Closing this issue in favor of the upstream Tab Center one.
