### ISSUE TITLE
Pass UT Client ID to Survey Gizmo

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/testpilot#829]
Was just talking to Rebecca about this. When we recruit users through Heartbeat to fill out a survey for each experiment, it would be really powerful to be able to match that to the UT data. That means we'll be able to correlate what users are actually doing with attitudinal measures. @ckprice I think this is covered under the consent page already.

**Comment by MattGrimes** [comment]
@nchapman @rjweiss @javaun this is the issue we discussed in Vancouver. This would be extremely helpful for us to have.

**Comment by ckprice** [comment]
Closed in favor of #949.
