### ISSUE TITLE
Switch from xhr to fetch-polyfill in frontend app?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#83]
Poked at the frontend client code, saw we're using [xhr](https://www.npmjs.com/package/xhr). 

Since I like promises and future things, it occurred to me we might like to use [a fetch() polyfill](https://www.npmjs.com/package/fetch-polyfill).

Main benefits of fetch:
- Built into Firefox 39+
- Promises, so we can easily fire many API GETs in parallel & carry on when they're all done
- Easier JSON handling? (but I probably just haven't figured out xhr)

**Comment by jaredhirsch** [comment]
Closed by #84
