### ISSUE TITLE
404 when signing in

### ISSUE THREAD

**Issue by erikrose** [mozilla/testpilot#830]
I wanted to try out test pilot (yay!), so I…
1. Went to https://testpilot.firefox.com/
2. Clicked "Get started with a Firefox Account"
3. Clicked "Sign In" on the page that popped up showing my email address

I was rewarded with a redirect to https://testpilot.firefox.com/accounts/inactive/, which says, literally "Four Oh Four!". (Note that my Firefox Account is probably weird in some way; I believe I had some trouble activating it back when I was testing Firefox OS. I don't use it day-to-day.)

**Comment by ghost** [comment]
Having the same issue.

**Comment by lmorchard** [comment]
This may be a reappearance of #487, because I think our invite-mode flag got accidentally flipped back on in prod and #687 hasn't been deployed yet to remove the invite-mode code.

**Comment by pdehaan** [comment]
@erikrose Were you using an @mozilla.com email, or something else?

**Comment by onekopaka** [comment]
I was having this issue about when this was first filed, but I was able to log in now. For what it's worth, I was using a gmail.com email.

**Comment by pdehaan** [comment]
@lmorchard Was this resolved on the prod server, and we can close this now?

**Comment by erikrose** [comment]
@pdehaan I was using a non-mozilla.com email address.

**Comment by pdehaan** [comment]
Looks like OPs and @lmorchard fixed this on prod yesterday with some magic. Closing.
Let us know if anybody is still having login issues and we'll investigate.
