### ISSUE TITLE
can't edit properties in bookmark links

### ISSUE THREAD

**Issue by whroll** [mozilla/testpilot#831]

**Comment by whroll** [comment]
I installed testpilot and tab center. Had terrible problem logging in with my Firefox account credentials, kept being taken to the download screen. So I quit tab center and uninstalled testpilot. Now I am back to the regular tabs. The negative result is that now I can no longer edit properties in the bookmark items.

**Comment by johngruen** [comment]
Hi @whroll let's try to fix your problem. The first thing to do is to try to quit Firefox and restart it. If that doesn't work, can you go to your add-on manager in firefox and tell me if test pilot or tab center remain installed? The add-on manager can be accessed with these instructions: https://support.mozilla.org/en-US/kb/find-and-install-add-ons-add-features-to-firefox#w_how-do-i-find-and-install-add-ons

**Comment by whroll** [comment]
I restarted Firefox, and the problem was fixed. Thanks.

Sincerely,

William Henry Roll

whroll@gmail.com
The _New_ Roll Family Windmill:
http://rollwindmill.org
The Genealogy of the Roll and Allied Families:
http://wc.rootsweb.ancestry.com/cgi-bin/igm.cgi?db=wroll

**Comment by johngruen** [comment]
Glad to hear it! Thank you for your feedback and thanks for trying out Test Pilot.
