### ISSUE TITLE
What's with the new "bookmarks bar"?

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#837]
I can't move the bookmarks bar to under the address bar, where it usually sits.

**Comment by pdehaan** [comment]
@jasoncheng1024 Which TestPilot add-ons do you currently have installed?

**Comment by ghost** [comment]
All of them.

**Comment by ghost** [comment]
I can't reproduce this.  See screenshot:  
![bookmarks](https://cloud.githubusercontent.com/assets/16946141/15558054/0379d8fa-228c-11e6-9130-a8975696fe8e.png)

@jasoncheng1024 -- can you attach a screenshot and describe more about the results you're seeing?  Can you try disabling the add-ons and enabling one at a time to see if that affects anything?  Thanks.
