### ISSUE TITLE
GA refinements

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#839]
Met with @garethcull and team today, and we have a couple of requests.
1. Send an identifier on the `Install add-on` page that the user has successfully signed into FxA.
2. Add the experiment title to the Enable/Disable/Feedback events on the experiment details page.

Updating these to (@garethcull ok?)

```
eventCategory: 'ExperimentDetailsPage Interactions',
eventAction: this.model.title,
eventLabel: {'Give Feedback','Enable Experiment','Disable Experiment'}
```

**Comment by ckprice** [comment]
Adding a reference to a relatively new article '[Single Page Application Tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#tracking_virtual_pageviews)'.

The approach is to call `ga('set', 'page', '/new-page.html');` anytime the URL changes on the client. This would automatically fix the existing `pageview` commands and could make the two items in the bug opening unneeded. Removing the Ready column and assigning further research to myself.

**Comment by ghost** [comment]
@ckprice - any updates?  Does this still need discussion?

**Comment by ckprice** [comment]
I removed the label. I think this still wants to be done, but may be better to wait until after TXP-32.

**Comment by lmorchard** [comment]
Is this still needing to be done or discussed? Or did we do it somewhere else?

**Comment by ckprice** [comment]
I'm going to add this to this sprint, and take it.
