### ISSUE TITLE
Plugins dysfuctioning after disabling experiment add-ons

### ISSUE THREAD

**Issue by xbouroseu** [mozilla/testpilot#840]
It seems when i disable one of the experiment add-ons then some plugins did not work (ex. Lastpass, Pocket) and also the "Customize" option from the toolbar brought an empty page (with not tools or whatsoever).

OS: Mac OS X El Capitan
Latest Firefox 46.0.1 Release channel

**Comment by johngruen** [comment]
@xbouroseu does restarting firefox resolve this issue?

**Comment by xbouroseu** [comment]
Yes it does.  Also, i tried to reproduce it and the only plugin responsible for this is the "Universal Search Bar".

**Comment by pdehaan** [comment]
@xbouroseu Thanks for the bug report. I've moved this over to the **Universal Search** repository for better tracking: https://github.com/mozilla/universal-search/issues/221

Closing in favor of the upstream issue.

---

**UPDATE:** We believe the Customize issue is likely related to https://github.com/bwinton/VerticalTabs/issues/50.
