### ISSUE TITLE
Test Center doesn't seem compatible with Diigo sidebar

### ISSUE THREAD

**Issue by WorldsEndless** [mozilla/testpilot#841]
Linux (OpenSUSE) 42.1. Maybe the side-tabs makes sense on a wide-screen real-estate idea, so I was willnig to give it a chance--but not when it conflicts with other sidebar addons, most notably my bookmarks in diigo. The sidebar couldn't open until center tabs was gone.

**Comment by johngruen** [comment]
Hey @WorldsEndless, we are aware of this iproblem and are working to fix it. I'm going to close out this issue for now. You can track our progress on sidebars here: https://github.com/bwinton/VerticalTabs/issues/62

Thanks for your input!
