### ISSUE TITLE
Tab Center glitch with using bookmarks sidebar

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#844]
When pressing Ctrl-B (to open the bookmarks area) it causes an visual glitch.

**Comment by pdehaan** [comment]
@Qhue Thanks for the bug report.

I believe this is related to the following **Tab Center** issue: https://github.com/bwinton/VerticalTabs/issues/62
I'll update the upstream **Tab Center** bug with your keyboard combination shortcut and some screenshots. **Update:** https://github.com/bwinton/VerticalTabs/issues/62#issuecomment-219127583
