### ISSUE TITLE
new tab button and bookmark bar missing after disabling Test pilot

### ISSUE THREAD

**Issue by kaus02** [mozilla/testpilot#845]
- Windows 8
- Firefox edition 46.0.1

After disabling the Test pilot:
1. new tab button is missing
2. bookmark bar is missing.

**Comment by meandavejustice** [comment]
Seems like this has to do with Tab Center.  cc/ @bwinton 

Leaving this open here until it is confirmed as an issue of tab center.

**Comment by ghost** [comment]
This is specifically talking about Test Pilot, not Tab Center, so I'm not re-filing there yet.  @kaus02 - can you confirm what experiments you had active?  Is this reproducible?  Thanks

**Comment by kaus02** [comment]
all the three experiments included in test pilot were active - namely tab center, activity stream and universal search.

**Comment by johngruen** [comment]
Hey @kaus02 I think this is a dupe of resolved bug in Tab Center. Can you reproduce in the latest version?

**Comment by kaus02** [comment]
Hey @johngruen 
No it's not resolved, checked it again still new tab button missing(v 46.0.1). I am attaching the screenshot in which tab center is activated.
![screenshot 22](https://cloud.githubusercontent.com/assets/14627369/15626680/bed39b78-24e8-11e6-998b-ed5fbeeabefe.png)
And also the one in which tab center is deactivated.
![screenshot 23](https://cloud.githubusercontent.com/assets/14627369/15626692/30d7949a-24e9-11e6-80f9-834bba3ba829.png)

**Comment by bwinton** [comment]
@kaus02 can you replicate this by enabling and disable only Tab Center (and not all of Test Pilot)?  Also, can you tell me which version of Tab Center you're using, and if you have any other add-ons installed?  Thanks!

(We've made a bunch of fixes to Tab Center in the past month that should solve this case, so I'm interested in seeing whether it still happens…)
