### ISSUE TITLE
Tab Centre stopped working after using Dev tools

### ISSUE THREAD

**Issue by Hazz223** [mozilla/testpilot#847]
Hi,

Found when using the dev tools on Facebook (turns out they have a nice little console output to stop people getting hacked, who knew?) that when i closed them suddenly the tab centre stopped working.

I activated and deactivated, which didn't work. But closing and re-opening Firefox did the trick. 

Using the standard build for Firefox (46.0.1), on Mac. 

Like the test pilot program though. Nice friendly way to try out new features!!!

Cheers,
Harry

**Comment by meandavejustice** [comment]
@Hazz223 thanks for the report, I've moved it over to https://github.com/bwinton/VerticalTabs/issues/229
