### ISSUE TITLE
Experiments won't install

### ISSUE THREAD

**Issue by jamiebally** [mozilla/testpilot#848]
The Activity Stream & Universal Search apps will not install in my copy of Firefox. I have deleted almost all of my add-ons and disabled my adblocker on firefox.com, but the app page sits at "Enabling..." for hours (if I let it) without the app loading. Oddly, Tab Center loaded without any problem.

I am running: 
- Windows 10 build 10586.218
- Firefox 46.0.1

**Comment by meandavejustice** [comment]
Closing in favor of #843
