### ISSUE TITLE
Tabs are not on side.

### ISSUE THREAD

**Issue by 7837440** [mozilla/testpilot#849]
I'm experiencing a bug in Test Pilot. No side tabs now.
- [ ] Windows 10 64bit
- [ ] Firefox build: Beta  (I think)

---
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by ariefbayu** [comment]
I get the same issue this morning.

OSX 10.11.4
Firefox 46.0.1

**Comment by meandavejustice** [comment]
This looks like a duplicate, closing in favor of https://github.com/bwinton/VerticalTabs/issues/223
