### ISSUE TITLE
Constant prompts to rate Activity Stream

### ISSUE THREAD

**Issue by bradmont** [mozilla/testpilot#851]
- [ ] Operating system
  Debian testing.
- [ ] Firefox build (Nightly, Developer Edition, Beta, Release)
  Firefox ESR 45.0.2
  ---

Every few hours firefox prompts me to rate Activity Stream. I have already done this; the prompts should end (or at least be stopped for at least a week) once I've done it. I whould also like to be able to disable these prompts.

**Comment by meandavejustice** [comment]
closing in favor of #782
