### ISSUE TITLE
Changing user count strips out commas. 

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#852]
This is a good problem to have since you don't see it until user counts get above 999. Here's the bug in action: 

![comma-strip](https://cloud.githubusercontent.com/assets/3323249/15275986/eb0604dc-1ada-11e6-918c-0fbf66326b5a.gif)

STR: 
- go to details page of any experiment
- uninstall or install
- count increments or decrements, but loses the comma that's added to the string when the view first renders

**Comment by pdehaan** [comment]
**Protip:** `(300000).toLocaleString(); # "300,000"` (as a string)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

Seems reasonably well supported.
Not sure why/where the original number is getting its comma from (if Python is pre-formatting that string), but it'd be nice if we used the same formatting code pre-and-post experiment install, for consistency.
