### ISSUE TITLE
Test Pilot icon won't stay where it is put

### ISSUE THREAD

**Issue by swaldman3** [mozilla/testpilot#853]
Windows 7 / x64. Firefox release, currently on 46.0.1.

When I installed Test Pilot, the button for it appeared on screen near to the address bar. Since I won't use it a lot, I moved it into the hamburger menu.
Every time I restart Firefox, it is back where it originally wanted to be, rather than respecting my preference.

**Comment by meandavejustice** [comment]
I'm having trouble reproducing this. What other test pilot addons do you have installed?

**Comment by swaldman3** [comment]
Huh, it's stopped doing it. Sorry to waste your time, I'll close the issue unless/until it happens again...
