### ISSUE TITLE
Tab center stopped working

### ISSUE THREAD

**Issue by lovemytux** [mozilla/testpilot#854]
I am using the last days the tab center (pilot mode). I found that today (without even close firefox), the addon stopped working. I can see the addon as "Now Active" when I check the test pilot (restarted it also a couple of times), but tabs are shown as they used to be without this addon.
- OS: Windows 7
- Firefox Release

When I am home I will inform you If I have the same issue on my Linux machine.

Thank you for the great work!

Br,
Pavlos

**Comment by lovemytux** [comment]
After one more Firefox restart issue has been resolved.

**Comment by meandavejustice** [comment]
This looks like a duplicate, closing in favor of https://github.com/bwinton/VerticalTabs/issues/223
