### ISSUE TITLE
Side Bar navigation is not coming though tab center is active

### ISSUE THREAD

**Issue by eranshul20** [mozilla/testpilot#855]
Side Bar navigation is not coming though tab center is active
![tab center view active but side bar disappears firefox test pilot prog 16 may 16](https://cloud.githubusercontent.com/assets/12758815/15289574/c05e6ef2-1b90-11e6-9197-b0c5da0a8328.png)
- Windows 10 , 64 bit , Operating system
## \- [ 46.0.1 ] Firefox build 

I
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new

**Comment by meandavejustice** [comment]
This looks like a duplicate, closing in favor of https://github.com/bwinton/VerticalTabs/issues/223
