### ISSUE TITLE
Difficulty submitting Universal Search feedback

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/testpilot#856]
[Originally posted](https://github.com/mozilla/universal-search/issues/224) by @shilow19 on the search repo: https://github.com/mozilla/universal-search/issues/224

---

i am using windows 10 os and  Firefox 46.0.1
![2016-05-14](https://cloud.githubusercontent.com/assets/19353672/15270966/adc44f78-1a00-11e6-991c-88a7ebc76f87.png)
![2016-05-14 1](https://cloud.githubusercontent.com/assets/19353672/15270968/b4904dfc-1a00-11e6-8fd5-a0095a2bf1ad.png)

   when i find a page i want to be on it will load fine after a few min the page will do 1 of 2 thing reload or universal search web page will open any were from 1 to 3 web search pages at a time.it will also if playing a game stop the game like its set to pause.then when i went to submit the report on what i though about the add-on i could not send the submission also i use a dell i have a 1 button push to take screenshots when using this i had to use the ctrl and screenshot at the same time i did not know at the time i had to use both keys to do the screenshots i tried to do a screenshot of the web pages reloading and or opening new search pages but had to figure out how to get my screenshots working plus test pilot icon will not stay on in the menu bar but here are the screenshots of not being able to send in report and universal was still in use from what i was showen it did not look like it added on

**Comment by meandavejustice** [comment]
@ckprice

**Comment by johngruen** [comment]
@MattGrimes

A user reported this in IRC this morning as well

**Comment by ali1234** [comment]
I also can't fill in the Universal Search feedback. Using Ubuntu 16.04 and Firefox 46. Click "Next" at the end of the first page and nothing happens.

The Activity Stream survey works fine so this seems to be an issue with that one specific survey.

**Comment by ghost** [comment]
@johngruen, etc - A quick look suggests that there is no overriding of logic that we performed when creating this survey that would cause form errors (i.e. we aren't overriding the "Next" button like we've had to do with some other surveys).  I'll keep looking into it, but this was surprising to me.

**Comment by johngruen** [comment]
@rayborn @chuckharmston I wonder if there's a correlation btwn this issue and tracking protection

**Comment by ghost** [comment]
@johngruen @chuckharmston  - I could not reproduce with Tracking Protection enabled.

If anyone repeats this, please copy any console errors here (SG has same origin policy image warning that we're aware of, this would be something different).

For the record, for the 2-day heartbeat users we have 29 partials + 495 completes, so that puts our **upper bound** for this issue at ~6%.

**Comment by rayborn** [comment]
If anyone repeats this, please copy any console errors here (SG has same origin policy image warning that we're aware of, this would be something different).

**Comment by johngruen** [comment]
@rayborn we had another report of this on (specifically for universal search) from a moz employee (irc: jpetto)

**Comment by ali1234** [comment]
Today I tried a few things to repro this:

First I removed Universal Search, rebooted the computer, and tried to submit the survey from an old bookmark to it, while having the error console open the whole time. This worked correctly.

Then I immediately tried again but with different options on the form. This also worked.

Then I enabled Universal Search, restarted Firefox, disabled Universal Search, and tried to submit the form after landing on it from the Test Pilot link - not my bookmark. This did not work.

Then I tried to submit from my bookmark which worked previously. This did not work.

I only saw one error on the console in the whole time, and it was displayed every time whether the form worked or not:

Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. (https://www.surveygizmo.com/2016.05.16.00/runtimejs/dist/survey/js/survey.js :10:8022)

**Comment by jaredhirsch** [comment]
Another report of this same issue came in via IRC yesterday:

```
3:31 PM <jpetto> the next button on the survey provided after disabling
 universal search is inert for me. no errors, no page refresh, no console messages,
 nothing.
3:32 PM <•clouserw> any errors in your console?
3:32 PM <jpetto> nope
3:32 PM <jpetto> using fx beta
3:33 PM <jpetto> 47.0b5
3:33 PM <jpetto> even refreshed the page with console open to make sure i didn’t 
miss anything
...
3:41 PM <•_6a68> jpetto: do you have any other addons enabled? do you have tracking 
protection enabled?
7:40 AM <jpetto> _6a68: (from the survey issue yesterday) i have JSON-formatter and 
User Agent Switcher add-ons installed. i do have tracking protection enabled, but disabled 
it after the first time the survey button did nothing.
```

**Comment by ali1234** [comment]
I have just noticed that when the survey button doesn't work, the submit button on amazon.co.uk also does not work. As I said above, this happens after enabling and disabling universal search and persists until Firefox is restarted. As such it seems like a bug in Universal Search or the add-on subsystem and not a problem with the survey form.

**Comment by shilow19** [comment]
i was not on amazon i was on the home page of firefox i am also still having problem with loading and other pages opening on top of each other 

----- Original Message -----

**Comment by pdehaan** [comment]
Another user report in #871 

> This probably just a client side problem, but clicking on next on the feedback page does nothing. I've tried reloading, quitting Firefox and restarting and even resetting Firefox but nothing happens.

**Comment by gregglind** [comment]
(I looked over the survey js and such too.  Nothing weirder than normal, afaict.)

**Comment by ghost** [comment]
To add to @gregglind: 
@ali1234 makes it sound like a general compatibility bug since this happening elsewhere.

Alternatively, I could ping the SurveyGizmo support email to see if there are any know compat bugs; there is nothing to suggest that there's something wrong with only this survey (it's quite simple).

P.S. The getPreventDefault is a minor warning due to SurveyGizmo using an outdated version of JQuery (1.8.2).

**Comment by shilow19** [comment]
did not mean to cause a mess. tracking protection was on also tried hitting the enter button that did not work 

----- Original Message -----

**Comment by ghost** [comment]
@shilow19 - any bug reports are very helpful.  If you are tired this showing up in your email you can click the Unsubscribe button on the right hand side of the GitHub page at this url: https://github.com/mozilla/testpilot/issues/856
Alternatively you're email client may have a "mute" function that you could use to ignore follow ups.

@ rest - sorry for the off-topic reply, wish Github still had private messages :)

**Comment by shilow19** [comment]
no im not tired of the e-mails thank you 

----- Original Message -----

**Comment by rtanglao** [comment]
reported on twitter as well:

https://twitter.com/firefox/status/733332139790467072

**Comment by ghost** [comment]
The Twitter report was fixed in a new profile (seems unresolved into what the issue was with their existing profile).

Sounds like SurveyGizmo is not aware of any known compat/rendering bugs on their end.

I'm keeping an eye on this issue hoping that there is a resolution that will be applicable here: https://github.com/mozilla/universal-search/issues/213

Let me know if you need any further testing/follow up here, but for now I'm mostly watching threads.

**Comment by ghost** [comment]
@pdehaan can you reproduce this?

**Comment by pdehaan** [comment]
I wasn't able to reproduce on OS X w/ Firefox 46.0.1 after disabling Tab Center. I was able to complete the survey (even after resizing browser lots, switching tabs, switching browsers, viewing some YouTube videos in a different browser, then returning ~20m later to hit Next a couple times. Both times the Next version clicked (the first time was me not fully entering the required fields and it correctly prompted me to complete the form). The second time I hit Next it submitted the form and took me to the Thank You! page.

**Comment by ghost** [comment]
Sounds like this is fixed on the latest versions
