### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#857]
By going into incognito mode on Firefox, the incognito mode icon is glitched in the tab center. 

Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

If you're experiencing a bug in Test Pilot, please include the following information:
- [ ] Operating system
- [ ] Firefox build (Nightly, Developer Edition, Beta, Release)

---

If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by meandavejustice** [comment]
Thanks for filing @Qhue I've moved this issue to https://github.com/bwinton/VerticalTabs/issues/230
