### ISSUE TITLE
Research switching from Ampersand to React

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#865]
So, they always tell you to never rewrite things, and they're usually right. Nonetheless, I have a strong urge to rewrite our frontend with React. 

Last summer, I thought Ampersand was pretty great. But now, after we've put some miles on it and ended up with [this tangled mess of explicit DOM bindings on our experiment details page](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/views/experiment-page.js#L32), the simplicity of a React component is compelling. React moves the complexity of that sort of thing out of view code and into the virtual DOM, so all we have to write is straightforward template code and let React sort out the changes.

Filing this issue to start a discussion. Also, in terms of action items, we could 

a) let me hide in a cave for a few days and try a full rewrite, or

b) try introducing React on one view at a time, each initially behind a feature flag. 

c) forget I ever said this and we never speak of this again.

The option b looks tedious, but is likely way less risk than option a. Option c leaves me with the worry that our Ampersand code will get increasingly complex without much payoff.

All the above said, what do folks think about this?

**Comment by lmorchard** [comment]
Oh, and when I say "rewrite the frontend" I mean replace Ampersand views & models with something like React & Redux. Leave all the CSS and backend API alone, produce the same DOM structures.

**Comment by pdehaan** [comment]
💯 We're already using React in a lot of other Mozilla sites/tools, so it also has the benefit of potentially being easier for new contributors to get involved.

**Comment by lmorchard** [comment]
> We're already using React in a lot of other Mozilla sites/tools, so it also has the benefit of potentially being easier for new contributors to get involved.

Yeah, that also gives me flashbacks to when I was still on projects using PHP while the rest of Mozilla Webdev moved on to Django & Python :)

**Comment by pdehaan** [comment]
@lmorchard Let me know if you want me to file a bug for "Research switching from Django & Python to PHP".

**Comment by meandavejustice** [comment]
I'm generally not in favor of `option a`-like solutions(or long running parallel branches) ... But I feel that our site is simple enough and @lmorchard is more than competent enough to make it happen.  If we were to go that route, I would like to also have: 
1. more thorough testing
2. better debugging tools
3. lighter weight bundles with webpack.
4. maybe [server-side rendering](https://github.com/mic159/react-render) of react components.

Since react is so popular in the industry right now, we mine as well get all of the nice tooling that is being built around it as well if we are doing the switch.

In order to make a educated decision for this. We should think about how react could benefit us down the road on test pilot. How much more will really be changing on the test pilot site? Will these changes be easier to implement with react in our stack?

**Comment by lmorchard** [comment]
So, in between games of Overwatch over the weekend, [I started converting some views to React to see what it would look like](https://github.com/lmorchard/testpilot/commit/4251139c729aba876a79076805181a3add8d8ba9). Comments & critique welcome, hoping to have some more of this done to talk about in London.

**Comment by lmorchard** [comment]
Some TL;DRs from my experience converting some core views so far:
- React isn't all-or-nothing - we can incrementally replace Ampersand views (and change tests).
- Redux replacing all Ampersand models would be an end goal after views are done.
- The React idiom for styling is CSS-in-JS for inline styles. But, personally I'm not a fan and we have all this good CSS already - so we never need to adopt inline styles.
- [My React version of Experiment detail page](https://github.com/lmorchard/testpilot/commit/4251139c729aba876a79076805181a3add8d8ba9#diff-f7d8c66e87502032c48bc240bbbea490R1) looks much simpler to me than the Ampersand version. No data bindings because React just re-renders on data change, "subviews" for dialogs are just conditionally rendered elements based on state switches.
- Converting views was mostly copy & paste, with some tweaks to change data bindings to simple value inclusions. But, `class` -> `className` in JSX, which is annoying.
- eslint probably needs an upgrade to be okay with React components in variables appearing as unused when they are actually used in JSX

**Comment by meandavejustice** [comment]
This is looking good. The react version of experiment details _does_ look simpler. It sure is long tho. We could probably break it into smaller components though.

I recently started working on a side project that is using the whole redux, react, react-router etc.. stuff so i'm learning as well. Getting more and more comfortable with redux. The css story for this project has been [postcss](https://github.com/postcss/postcss) and [css-modules](https://github.com/css-modules/css-modules) with the [css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook). It's been not terrible so far. I'm usually a simple fella when it comes to these types of things. Avoiding transpiling and preprocessors. I've made an exception for this project and it's actually been working well.

**Comment by lmorchard** [comment]
> The react version of experiment details does look simpler. It sure is long tho. We could probably break it into smaller components though.

Yeah, that was pretty much just copypasta of the original mustache template and then tweaks to reactify it. Could totally get broken up.

And my CSS stance on this project is pretty much if @johngruen is happy, I don't wanna mess with it :)

**Comment by lmorchard** [comment]
Also speaking of breaking up that experiment view... Ironically, it was [this tweet from Henrik Joreteg](https://twitter.com/henrikjoreteg/status/652157136605020160) (the instigator of Ampersand) that kind of turned me around on React. Stateless functional components are pretty keen. You can just do something like:

```
const UserCount = experiment => (
  <section className="user-count">
    <span data-l10n-id="userCountContainer">There are 
    <span data-l10n-id="userCount" className="bold" data-hook="install-count">{experiment.installation_count.toLocaleString()}</span>
    people trying <span>{experiment.title}</span> right now!</span>
  </section>
);
```

**Comment by lmorchard** [comment]
Going to close this "research" issue in favor of an "action" issue in #1307

**Comment by facugon** [comment]
Hello everybody , and thank you @lmorchard for your research. This is very useful. I have some projects running with Ampersand, and I love the way it works, but it is hard to learn and complicated to maintain. We were thinking on moving to React, too. And your research helps a lot. Thanks.
