### ISSUE TITLE
Implement additional server logging events

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#866]
From [README-METRICS](https://github.com/mozilla/testpilot/blob/master/docs/README-METRICS.md#data-collection-details):

> The server will use server logs to store metric data which will be picked up by the measurement team (some docs), parsed and transformed if necessary, and pushed into ElasticSearch (as scale permits), S3, and Redshift. Events recorded in the logs will include:
> 
> request.summary (a generic event fired for each visit)
> testpilot.newuser
> testpilot.newfeedback
> testpilot.main-install
> testpilot.test-install

We log `request.summary` but none of the others. Let's start producing those log messages.

**Comment by ghost** [comment]
Thanks.  Dashboards are all set up at https://kibana.shared.us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/PROD%20-%20Test%20Pilot%20App%20Logs and will start showing this data when it rolls in.

**Comment by lmorchard** [comment]
Hmm, looks like I'm not authorized to see that dashboard

**Comment by ghost** [comment]
Dupe https://bugzilla.mozilla.org/show_bug.cgi?id=1249320 for yourself

**Comment by lmorchard** [comment]
Looking at the Google Analytics dashboard, it seems like we're recording these missing events (and more) there too. Do we need some way of comparing them, or are they redundant?

**Comment by ghost** [comment]
In theory they are redundant.  In reality they record slightly different things (JS button click vs server side processing).  If they ever get far apart though, something is fishy.

**Comment by lmorchard** [comment]
For these two, I'll have to add server-side API resources to receive pings for the events on top of the GA ping: 
- Feedback (`newfeedback`) is an external survey link, with a GA ping side effect on the link click.
- Main add-on install (`main-install`) happens all client-side, with a GA ping side effect on the button click.

Only `test-install` and `newuser` can be tied to things we're already doing server-side.

**Comment by ghost** [comment]
I think we can skip them if they aren't instrumenting existing code.  imo :)  Let's close when you land what you got

**Comment by lmorchard** [comment]
Okay, just started implementing the ping API, but I'll back that out and submit a PR for `test-install` and `newuser`
