### ISSUE TITLE
Test Pilot is confused about which experiments are active.

### ISSUE THREAD

**Issue by ali1234** [mozilla/testpilot#869]
The Test Pilot menu is currently showing Universal Search as active, but it is not. It is not even shown in the add-ons page, and the URL bar is clearly split into two.

Ubuntu 16.04 / Firefox 46 / Test Pilot 0.5.9-tag-2015-05-16

![screenshot from 2016-05-18 16-27-07](https://cloud.githubusercontent.com/assets/651970/15364791/bd8a391e-1d15-11e6-918f-2fff03d05a84.png)

**Comment by meandavejustice** [comment]
@ali1234 Can we have a little more info on how to reproduce? Did you have universal-search installed and remove it from the `about:addons` page or from the `disable` option on `testpilot.firefox.com/experiments/universal-search`?

**Comment by ali1234** [comment]
To reproduce:
1. Install Ubuntu 16.04.
2. Run Firefox.
3. Install uBlock Origin.
4. Install Test Pilot.
5. On the Test Pilot web page, enable Universal Search.
6. On the Test Pilot web page, disable Universal Search.
7. Attempt to do the feedback survey. Notice that it doesn't work as you cannot submit the form. (bug #856)
8. Attempt to search for something on amazon.co.uk. Notice that the form submission button doesn't work there either.
9. Restart Firefox and notice that the feedback survey and amazon website now both work correctly.
10. Open the Test Pilot menu as shown in the screen shot and notice that it says Universal Search is enabled, even though it quite clearly isn't.

**Comment by hafta** [comment]
I have hit a similar issue where tab center doesn't display as active in the test pilot drop down list, but it is installed and clicking on tab center then changes the list item to appear as installed. See screenshot where tab center is installed, but not displayed as installed in the drop down list. I've only seen this problem with tab center.

I hit this problem on Firefox release too.

![tab-center-not-checked](https://cloud.githubusercontent.com/assets/10162738/15722798/4540aef4-27f4-11e6-9d10-9a775bdb1bc6.png)

**Comment by meandavejustice** [comment]
I think this may be fixed in https://github.com/mozilla/testpilot/issues/913. Let's see once it gets deployed
