### ISSUE TITLE
Configure Travis to build+lint the front end

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#87]
At a minimum we should probably run `gulp build` and `gulp lint` to make sure the code builds and looks kosher.
Currently Travis reports green on PRs, even though the front end doesn't lint cleanly due to string termination, blah blah blah.

**Comment by lmorchard** [comment]
FWIW, poking at this a little, [found this lead on using node.js & Python in the same project](http://www.arunmozhi.in/travis-ci-config-for-python-nodejs/). Seeing if it's just as easy as adding another Tox environment to the travis matrix

**Comment by lmorchard** [comment]
[Seems like this is working now](https://travis-ci.org/mozilla/idea-town/builds/82217824), though I suppose the real test will be to see it fail a PR with JS that runs afoul of linting

**Comment by lmorchard** [comment]
We've had a few instances of linting gripes caught by travis, so I think this is done
