### ISSUE TITLE
Firefox Tab center Issue

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#870]
When tab center is active, and you click on a bookmark in your bookmarks bar, this causes some glitchy graphics. (Windows 7, fairly old computer, newest version of Firefox, I think)

[UPDATE]: New discovery about this issue, this only happens when I go to inbox.google.com (Google Inbox) via the bookmarks bar. This could be on the google side of this, but I can't tell.

![bookmarks_bar_glitch](https://cloud.githubusercontent.com/assets/12704804/15367065/2bde031c-1cdc-11e6-8e4b-ef0591fbe596.PNG)

Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

If you're experiencing a bug in Test Pilot, please include the following information:
- [ ] Operating system
- [ ] Firefox build (Nightly, Developer Edition, Beta, Release)

---

If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by Qhue** [comment]
New discovery about this issue, this only happens when I go to inbox.google.com (Google Inbox) via the bookmarks bar.

**Comment by ghost** [comment]
refiled for tab center @ https://github.com/bwinton/VerticalTabs/issues/271
