### ISSUE TITLE
"Please rate _______" is very plain

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#873]
I saw this feedback from somewhere, but I don't know if it's filed yet, so I'm filing...

I was just prompted for "Please rate Tab Center \* \* \* \* *" .  I like the idea, but unless you're really involved in this process you're not going to know what Tab Center (or any of the experiments are).  A couple ideas:
- add the test pilot logo to the bar
- Expand the wording to something like "Thanks for trying Test Pilot.  You've been using Tab Center for a few days.  How would you rate it?"

**Comment by meandavejustice** [comment]
I vote to both add the logo, and expand copy.

**Comment by ghost** [comment]
Add logo for sure.  

Open to other language.  "Please rate ____" was just to be consistent with desktop where we tested 4 different prompt languages that were all pretty plain for CTR.

**Comment by MattGrimes** [comment]
I'm fine with it. If we change CTR by doing this, we'll need to account for that. If we are changing things I'd like to do it sooner rather than later.

**Comment by johngruen** [comment]
Adding in the logo is going to be a bit complicated b/c it'll likely confuse people. here's a change i have ready to go which
- changes the string
- adds a filter on the experiment image to make it visible
- slightly moves the stars to make them more aligned with copy

<img width="1177" alt="screen shot 2016-05-25 at 12 16 54 pm" src="https://cloud.githubusercontent.com/assets/3323249/15547686/db8f7b88-2272-11e6-99ad-3be39e85f8a0.png">

**Comment by ckprice** [comment]
I thought we'd be adding in the Test Pilot logo (and/or the Firefox logo). Will people recognize the individual experiment logos?

Also, someone noted to me yesterday that it may be nice to have a link back to the experiment page for further context.

**Comment by ghost** [comment]
In desktop Heartbeat we have a "Learn More" link floating left of the "X"
button that looks pretty good.  If we were to link to the experiment we
could have a "View Add-on", "Go to experiment", or "Learn More" link
there.
