### ISSUE TITLE
Legal Docs Privacy Notice sections should be collapsable

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#877]
Ref: https://github.com/mozilla/testpilot/issues/738#issuecomment-220063420

---

@ckprice received the following request from Brian Smith in legal (also updated bug title, and opening):

> I noticed that the [Test Pilot privacy notice](https://testpilot.firefox.com/privacy) webpage does not have the sections collapsed like our other [privacy notices](https://www.mozilla.org/en-US/privacy/firefox/). Can we please revise to make the two sections of the notice collapse/expand? Denelle does not like our notices to just be a wall of text, so this is a priority for us.
> 
> Casey (cc'd) can help the relevant person on your team with the css/html formatting as needed.

/cc @mozcmcgill

---

/edit adding some specifications

Ref: https://docs.google.com/document/d/14HB8hPnuH5YlO3HtZeIATmFCMIhiHIPBNEgWN66XkDQ/edit?usp=sharing

The two _Learn More_ links should expand out the bullet points underneath them. The bullets start collapsed.

**Comment by ckprice** [comment]
Moving this ~~and #738~~ to this sprint because Legal noted it was a priority.

**Comment by ckprice** [comment]
Mika from legal dropped by and told me that this issue was blocking a blog post legal wants to publish. It's basically a "Look how simple our privacy pages are!" post that wants to use Test Pilot as a use case.

They would like to publish this post next week, so we're looking at an _out-of-band deployment_ if we want to fulfill this request. Step 1 though is getting this bug closed. I've updated the bug opening with some specifications.

**Comment by mozcmcgill** [comment]
Looping in Kohei who has been a huge help with us updating the legal docs
pages. Hey Kohei, we have a Privacy Notice for Test Pilot [1]  and are to
get the "Learn More" expanding tabs like the Firefox Privacy Notice has.
Could you help us get the formatting right?

[1]
https://github.com/mozilla/testpilot/blob/master/legal-copy/privacy-notice.md

/edit actually looping in @kyoshino

**Comment by kyoshino** [comment]
Looking into this now.

**Comment by mozcmcgill** [comment]
Thanks Kohei!

**Comment by kyoshino** [comment]
#923 will fix it!
