### ISSUE TITLE
Add GitHub URLs to prod

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#879]
I don't have Django admin access to prod, so this is probably a @ckprice or @nchapman or @johngruen to-do.

<img width="404" alt="firefox_test_pilot_-_activity_stream" src="https://cloud.githubusercontent.com/assets/557895/15403482/05b266ec-1dae-11e6-9152-5e85e12b9584.png">

**Comment by johngruen** [comment]
on it :)

**Comment by ckprice** [comment]
Done.
