### ISSUE TITLE
Implement Subresource Integrity for our JS & CSS assets

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#881]
[Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) allows us to require that linked assets match a crypto hash in markup, thus mitigating risks that the assets may have been tampered with. We should implement SRI for all our assets.

**Comment by lmorchard** [comment]
See also: #889

**Comment by lmorchard** [comment]
Whoops. Looks like things are broken on dev. Investigating.

**Comment by lmorchard** [comment]
Ugh, I see what it is:

```
/app # cat static/styles/main.885355dc102e.css |  openssl dgst -sha384 -binary | openssl base64 -A; echo
vnDt+fGbk3oCVKyHvGrF3RYzC7h4WdAENt74SgaNvFkdfZxqkwt3lzgJ6gSPe/sP
/app # cat static/styles/main.css |  openssl dgst -sha384 -binary | openssl base64 -A; echo
kk6qdLuqMxc4A9OWaAAHDMMkVGDWmr/R86FviagCNqT4l1ZvwhFW3vHq8HfQm0Gh
```

The hash for `main.css` is what gets used in the integrity hash, but `main.885355dc102e.css` is what's linked. Looks like Django tries to minify our CSS that's already been minified by gulp, so the hashes don't match. Going to poke at that some more.

**Comment by pdehaan** [comment]
Ref: #945

**Comment by pdehaan** [comment]
> Looks like Django tries to minify our CSS that's already been minified by gulp, so the hashes don't match.

That sounds kind of bad. Or at least potentially worrysome if it does that for JavaScript too, as it could break sourcemaps (if we currently use them, or are planning on adding them in the future).

**Comment by lmorchard** [comment]
We have sourcemaps, but only in development. They mainly work for the es6-processed but non-minified source. They've never worked for prod

**Comment by lmorchard** [comment]
Should be fixed with https://github.com/mozilla/testpilot/pull/945
