### ISSUE TITLE
Make post-retire modal header match other 404-style modal headers

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#884]
Right:
![screen shot 2016-05-20 at 10 19 52](https://cloud.githubusercontent.com/assets/3323249/15421820/aa47e0c0-1e75-11e6-84c4-b41d67420d25.png)

Wrong:
![screen shot 2016-05-20 at 10 19 06](https://cloud.githubusercontent.com/assets/3323249/15421838/b86c5c1c-1e75-11e6-9ff8-a988ced06f63.png)

**Comment by bmcculley** [comment]
I would like to try this one out as my first contribution to the project.

**Comment by johngruen** [comment]
@bmcculley go for it!

**Comment by pdehaan** [comment]
Fixed via #886.

Thanks @bmcculley!
