### ISSUE TITLE
Survey after disabeling TabCenter shows only a gradient, no content (when using AdBlock Plus)

### ISSUE THREAD

**Issue by designakt** [mozilla/testpilot#887]
I just installed TabCenter and removed it after testing it for about 5min. After removing it I have been asked to take a survey. The window opening after clicking the button only shows a page with a gradient background, but no actual survey.
this is the URL I have been refereed to: https://qsurvey.mozilla.com/s3/tab-center?ref=disable&experiment=Tab%20Center&installed=tabcentertest1%40mozilla.com
and this is what I see:
![screen shot 2016-05-20 at 18 13 21](https://cloud.githubusercontent.com/assets/8145891/15434370/cfd0226c-1eb6-11e6-935e-e9b4952be0c5.png)

experienced on Windows 10, Firefox Nightly 49.0a1 (2016-05-19)
I noticed it is due to AdBlock Plus blocking the content of the survey.

**Comment by ghost** [comment]
@johngruen - can we just put a message on this page saying what is happening?  @6a68 also has some ideas

**Comment by johngruen** [comment]
Closing in favor if #887
