### ISSUE TITLE
Doorhanger positioned too low on Windows 10

### ISSUE THREAD

**Issue by designakt** [mozilla/testpilot#888]
The Testpilot doorhanger is positioned much lower than other doorhangers on Windows.
![testpilot-doorhanger-position-too-low](https://cloud.githubusercontent.com/assets/8145891/15434756/d63def6a-1eb8-11e6-9c8c-bb5f7fd826fe.gif)
Should be same vertical starting position than other doorhangers.

experienced on Windows 10, Firefox Nightly 49.0a1 (2016-05-19)

**Comment by meandavejustice** [comment]
Thanks for reporting @designakt 

This is peculiar. We [currently](https://github.com/mozilla/testpilot/blob/master/addon/index.js#L296) position the panel by attaching to buttons as suggested by this [mdn page](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/panel#Panel_positioning). Looks like this may be another `addon-sdk` bug. searching `position panel` on `addon-sdk` in bugzilla gives me "Zarro Boogs found."

**Comment by designakt** [comment]
I think there was a bug with positioning when building the panels for WebExtensions. I couldn't find a bug for it though. @bwinton might know more about that.

**Comment by ghost** [comment]
This is coming from the SDK add-on (which may or may not get much continued support).  It's not something we can fix here, so closing this. Thanks.
