### ISSUE TITLE
Test Pilot needs some security improvements

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#889]
Test Pilot doesn't seem to have gotten a full, formal security review. Let's make that happen.

**Comment by ckprice** [comment]
> Test Pilot doesn't seem to have gotten a full, formal security review. Let's make that happen.

We did pass this by the sec team early on for approval for launch in [bug 1255231](https://bugzilla.mozilla.org/show_bug.cgi?id=1255231) (moz confidential). #890 was mentioned in their list of recommendations. It may deserve a follow-up with that team, but would defer to @clouserw on next steps.

**Comment by lmorchard** [comment]
Cool, I'm not cc'ed on that bug & never saw it until now, so I was afraid we'd dropped the ball here. Good to hear that's not the case!

**Comment by lmorchard** [comment]
Actually, I'll just close this issue since the review process was actually started
