### ISSUE TITLE
Sign in / sign up should be different links

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#89]

**Comment by lmorchard** [comment]
Actually, I think there's an issue with the entire sign in / sign up concept from the front page. It's all just sign-in-with-FxA, which might involve a sign up on the FxA side. There's not actually a sign up on our side so far - we just pull in the FxA details and automatically create an account.

**Comment by meandavejustice** [comment]
This is no longer relevant with the new landing page.
