### ISSUE TITLE
Move Test Pilot /admin/ to something hosted behind a secure Mozilla VPN

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#890]
Currently, if you are a user with `is_superuser` set, you can access https://testpilot.firefox.com/admin/

Security-wise, this would be much improved by hosting the `/admin/` pages behind a firewall that requires Mozilla VPN access.

**Comment by lmorchard** [comment]
See also: #889

**Comment by lmorchard** [comment]
This is also a dupe / cross-post of https://bugzilla.mozilla.org/show_bug.cgi?id=1258766

**Comment by ckprice** [comment]
Assigning to benson and moving to in progress.

**Comment by chuckharmston** [comment]
TXP-30 negates the need for this bug.
