### ISSUE TITLE
Cursor appears in unexpected location after enabling Tab Center

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#892]
This seems to have started when I enabled tab center, but this gives me access to place a weird movable flashing cursor-bar (the one that appears when you type,) in weird places in webpages. I can't provide a screenshot, but I can provide an example picture. 
![capture](https://cloud.githubusercontent.com/assets/12704804/15443776/d796be6e-1e9f-11e6-8e8e-a60201a4f3da.PNG)

**Comment by ghost** [comment]
This is on any website, anywhere. It's reacting as if it's an editable text document. I've tried resetting Firefox and that does not work.

**Comment by pdehaan** [comment]
@Qhuea I don't seem to be able to reproduce this on Firefox 46.0.1 (OS X 10.11.5) and testing text input fields on a handful of sites -- and Activity Stream and Tab Center experiments enabled.

What OS and Firefox version/channel are you using?
What other Test Pilot experiments do you have enabled (besides Tab Center)?
Do you have any other Firefox add-ons installed?

---

**UPDATE:** I was testing text input fields on the following sites:
1. https://google.com
2. https://yahoo.com
3. http://www.cnn.com
4. https://npmjs.com
5. https://github.com/mozilla/testpilot
6. http://www.sfgate.com

**Comment by ghost** [comment]
@pdehaan I'm using Windows 7, and no other Test Pilot add-ons. I use adblock plus, that's all. The weird cursor thing works on all websites for me, BTW.

**Comment by pdehaan** [comment]
Thanks @Qhuea. I'll see if I can reproduce this on my Windows 10 laptop (or within a Windows 7 VM).
In the meantime, I've moved this into the **Tab Center** repo at https://github.com/bwinton/VerticalTabs/issues/269 for better tracking.

Closing this bug in favor of the upstream Tab Center issue.
