### ISSUE TITLE
I am trying to enable the test pilot features.

### ISSUE THREAD

**Issue by deva1992** [mozilla/testpilot#893]
None of the features are getting enabled.
They get stuck at enabling.

Firefox 46.01. and Windows 10

**Comment by deva1992** [comment]
None of the features are getting enabled.
They get stuck at enabling.

**Comment by deva1992** [comment]
Firefox 46.01. and Windows 10

**Comment by karloffover** [comment]
Cannot start Pilot, keep on asking to install extension.
OSX 10.11.4
Firefox 46.0.1

**Comment by pdehaan** [comment]
I believe this is a dupe of #843.

@magullo's comment above seems slightly different, so I can move that into a new GitHub issue so we can track it separately.

**UPDATE:** Filed as #895
