### ISSUE TITLE
Not Happy

### ISSUE THREAD

**Issue by joan81** [mozilla/testpilot#894]
I am running Win7 Ultimate on a Lenovo T400 laptop. How do I revert to the old Tabs please? I don't like losing temporarily the Menu and Tool bars at the top. But more than that, I have totally lost my bottom row where the Start button is situated. Please help me get that back.

**Comment by pdehaan** [comment]
@joan81 The easiest way to disable the vertical tabs would be to go to https://testpilot.firefox.com/experiments/tab-center and click the [Disable Tab Center] button in the top-right corner. That should uninstall the experiment and put your tabs back at the top.

**Comment by joan81** [comment]
Thank you, that's much better having my old Firefox back again.

Joan81
