### ISSUE TITLE
Cannot start Test Pilot add-on, keep on asking to install extension

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#895]
Reported by @magullo in https://github.com/mozilla/testpilot/issues/893#issuecomment-220824443

> Cannot start Pilot, keep on asking to install extension.
> OSX 10.11.4
> Firefox 46.0.1

**Comment by ghost** [comment]
We'll need lots more info to debug this.  Other extensions installed?  Errors in the console?  Reproducible in a new profile?

**Comment by thibautsergent** [comment]
I have the same issue. 
Firefox 47.0.1 on windows 7 x64
Extensions : wot, adblock plus (disabled for testpilot.firefox.com), video downloader
Console output :1234: 

```
NS_ERROR_ABORT: Certificate issuer is not built-in. CertUtils.jsm:171:0
1468351266391   addons.xpi  WARN    Download of https://moz-activity-streams.s3.amazonaws.com/dist/activity-streams-latest.xpi failed: 307 Temporary Redirect
in update_random_feed
```

No idea on how to do a new profile :-1:
