### ISSUE TITLE
Prompted to rate Activity Stream multiple times

### ISSUE THREAD

**Issue by ckarlof** [mozilla/testpilot#899]
I'm seeing the prompt to rate Activity Stream multiple times after I've already rated it. I'll try to capture more info the next time I see it, but I typically see it in the morning after I use Firefox for the first time. Mac OS X, Nightly 49.0a1 (2016-05-23).

Hah, just got it now! Nothing suspicious in the logs except that I see [this error](https://github.com/mozilla/activity-stream/issues/735) in Activity Stream. Another detail is that my machine just crashed, so Firefox probably restored from an unclean shutdown.

<img width="1437" alt="screenshot 2016-05-23 13 40 21" src="https://cloud.githubusercontent.com/assets/2365255/15483859/ede9ba92-20eb-11e6-8f6e-5e43027894b5.png">

**Comment by pdehaan** [comment]
Possible dupe of **"asked to survey activity stream twice in two days"** #782

**Comment by ghost** [comment]
dupe of #782
