### ISSUE TITLE
Add Optimizely to Test Pilot.

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#904]
This issue is created to just add Optimizely to the website.

Optimizely has some [developer notes on single page applications](https://help.optimizely.com/Build_Experiments/AngularJS,_Backbone.js,_React,_and_Single_Page_Applications). It looks like there's a bit of special things we have to do on both the app and in the Optimizely console.

@johngruen as a first step, could you provide the Optimizely snippet?

**Comment by ckprice** [comment]
Just a note that once this lands, @garethcull has some cool dashboarding we can use to track results and learnings.

**Comment by ckprice** [comment]
I've done a bit more digging into the [Optimizely SPA documentation](https://help.optimizely.com/Build_Experiments/AngularJS,_Backbone.js,_React,_and_Single_Page_Applications). There are a couple major ways that our implementation will have to change from a standard implementation (only one of which will require code changes to the app).

**Custom events**

In single page apps, we have to [add a custom event](https://help.optimizely.com/Track_Conversion_Goals/Custom_event_goals#Format_to_add_a_Custom_Event_for_Web_experiments) to everything we want to measure (button clicks mostly). Then in the Optimizely dashboard, we configure our goals to look for `Event=button_click`.

A possible low overhead solution here is to overload the existing [`sendToGA` function](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/app/main.js#L65) with an additional ping to the Optimizely event API. Specifications for the two should be pretty well aligned.

**Conditional activation**

On the Optimizely side instead of just targeting URLs (e.g. /experiments/, /), we'll have to use [conditional activation in the Optimizely dashboard](http://developers.optimizely.com/javascript/code-samples/index.html#conditional) to identify our desired testing grounds.

This can be done a few ways, but the way that would require _no changes_ to the Test Pilot app is [polling for DOM elements](http://developers.optimizely.com/javascript/code-samples/index.html#conditional-activation-dom-element) in the Optimizely experiment configuration.

Example: `$('button.green').length > 0` means we're on the `/example/` page.

**Comment by ghost** [comment]
Can we get security/legal signoff on this?

**Comment by ckprice** [comment]
Checking in with legal/security.

**Comment by ckprice** [comment]
Got signoff on this from both Marshall and Julien. Julien did add:

> No particular concerns from me either. It would be nice if you can pin
> the version of the javascript from optimizely we serve to users, and SRI
> it, but if not possible we can probably accept the risk.
