### ISSUE TITLE
Allow experiments to specify max/min Firefox versions

### ISSUE THREAD

**Issue by edwindotcom** [mozilla/testpilot#906]
Activity Stream only supports Fx45 or greater.  We'd like Test Pilot to have a feature where it would ask the user to upgrade their version of Fx if they want to install this experiment.
1. Activity Stream defines min fx version in django UI or in repo
2. Fx44 user browses to Activity Stream experiment and clicks 'enable activity stream'

actual: it installs as normal

expected: user should get a prompt or dialog that says: you need Fx45 or greater to install this add-on.

**Comment by edwindotcom** [comment]
this is a follow up to #736

**Comment by johngruen** [comment]
@edmoz Does activity stream actually break in 44? GA is telling me that 44 has only shown up in ~700 sessions so far and older versions are less than that. IDK if this is a major problem. For UI, i'd suggest the following:
- Use the same UI as #660 
- Make The String " {{ Title }} requires Firefox {{ version }} or newer. [Download the latest version of Firefox here](https://www.mozilla.org/firefox/). "

**Comment by pdehaan** [comment]
> Does activity stream actually break in 44?

Yes, Activity Stream requires Firefox 45+ (per https://github.com/mozilla/activity-stream#requirements).

**Comment by chuckharmston** [comment]
Updated bug title to include a max-version case, since it's very little work and there have been times where upstream changes have broken our add-ons (i.e. Universal Search + one-off buttons).

Still needs UX.

**Comment by johngruen** [comment]
Closing, since the initial issue has been resolved. will replace with a nightly specific bug
