### ISSUE TITLE
Reenable gulp-imagemin

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#908]
... maybe.

In #903 we removed **gulp-imagemin** due to https://github.com/sindresorhus/gulp-imagemin/issues/183.

Not sure if we _need_ gulp-imagemin (or if we can get away with just checking in pre-optimized images), but we should probably discuss.

**Comment by ghost** [comment]
Optimizing images before they go in makes sense to me and there's less stuff to break.  This is apparently how people describe two cents in emoji: ✌💰

**Comment by johngruen** [comment]
WONTFIX, We can optimize images manually
