### ISSUE TITLE
Resize images for Facebook + Twitter cards

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#909]
Re: https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Ftestpilot.dev.mozaws.net%2F

<img width="674" alt="sharing_debugger_-_facebook_for_developers" src="https://cloud.githubusercontent.com/assets/557895/15518051/cde3d04c-21af-11e6-8c12-f6c626b190bc.png">

We should probably resize Choppy 2.0 to something a bit smaller so it fits nicely without getting cropped.

**Comment by johngruen** [comment]
@pdehaan @lmorchard could i make a custom image for these things? That'd be the optimal/easiest option.

**Comment by pdehaan** [comment]
Dear @johngruen, 

I believe @lmorchard is at a conference, but I'll go out on a limb and say that since the files are named [.../thumbnail-twitter.png](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/images/thumbnail-twitter.png) and [.../thumbnail-facebook.png](https://github.com/mozilla/testpilot/blob/master/testpilot/frontend/static-src/images/thumbnail-facebook.png), you're probably OK to optimize them for each of those sites. You can read @lmorchard's original Facebook comments from his PR at https://github.com/mozilla/testpilot/pull/872#issuecomment-220092480 (as well as the original issue at #761).

Also, since these images are seemingly hardcoded in the templates, they are site-wide, so IIRC we don't have specific share assets or Open Graph support for the individual experiments [yet].

Sincerely,
@pdehaan

**Comment by pdehaan** [comment]
This was fixed via #922.
Will close this out once dev gets deployed and I can give it a proper eyes-on against Facebook+Twitter validation tools.

**Comment by pdehaan** [comment]
Closing. This looks great [on dev] for Twitter and Facebook!

<img width="1007" alt="card_validator___twitter_developers" src="https://cloud.githubusercontent.com/assets/557895/15556711/32daa7ee-2284-11e6-87e1-0bfe32799262.png">

<img width="757" alt="sharing_debugger_-_facebook_for_developers" src="https://cloud.githubusercontent.com/assets/557895/15556722/40e98350-2284-11e6-9c53-077b3c5e3002.png">
