### ISSUE TITLE
Tabzilla tab invisible on 'install addon' landing page

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#91]
White-on-white. What's needed to make the tab shape blue?

**Comment by pdehaan** [comment]
It looks like we'd probably have to convert the Tabzilla image assets to our custom colors: https://github.com/mozilla/tabzilla/tree/master/media/img (and probably host them ourselves -- or convert to SVG or whatever).

I think @johngruen was actually looking into this.

**Comment by lmorchard** [comment]
https://github.com/mozilla/idea-town/commit/5c2f837ee8a47680f32bef493c5e77ba2b1eacd6
