### ISSUE TITLE
Unable to get Twitter preview for testpilot.dev.mozaws.net

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#910]
https://cards-dev.twitter.com/validator

When testing https://testpilot.firefox.com (and http://testpilot.dev.mozaws.net), I got the following output:

> INFO:  Page fetched successfully
> INFO:  15 metatags were found
> WARN:  Not whitelisted

Not sure how we enable Twitter card support for [at the very least] the production URL, but we should make sure that works as expected.

**Comment by pdehaan** [comment]
Here's our current [meta tags](https://github.com/mozilla/testpilot/blob/ba036f1a09145fdf0dafd21a515656c7e8180f85/testpilot/frontend/templates/testpilot/frontend/index.html#L19-L33) (sorted alphabetically so you can see open graph vs twitter easier):

``` html
<link rel="canonical" href="{{ meta_url }}">
<meta name="description" content="{{ meta_description }}" />

<meta property="og:description" content="{{ meta_description }}" />
<meta property="og:image" content="{{ request.build_absolute_uri(static('images/thumbnail-facebook.png')) }}" />
<meta property="og:locale" content="en_US" />
<meta property="og:title" content="{{ meta_title }}" />
<meta property="og:type" content="website" />
<meta property="og:url" content="{{ meta_url }}" />

<meta property="twitter:description" content="{{ meta_description }}" />
<meta property="twitter:image" content="{{ request.build_absolute_uri(static('images/thumbnail-twitter.png')) }}" />
<meta property="twitter:title" content="{{ meta_title }}" />
<meta property="twitter:url" content="{{ meta_url }}" />
```

Plus, here's the link to the [Summary Card](https://dev.twitter.com/cards/types/summary) documentation and a sample HTML:

``` html
<meta name="twitter:card" content="summary" />
<meta name="twitter:description" content="..." />
<meta name="twitter:image" content="..." />
<meta name="twitter:site" content="@flickr" />
<meta name="twitter:title" content="..." />
```

| Card Property | Required | Notes |
| --- | --- | --- |
| `twitter:card` | Yes | Must be "summary". |
| `twitter:site` | Yes | The Twitter @username the card should be attributed to. Required for Twitter Card analytics. |
| `twitter:title` | Yes |  |
| `twitter:description` | Yes |  |
| `twitter:image` | No | The image must be a minimum size of 120px by 120px and must be less than 1MB in file size. |
| `twitter:image:alt` | No |  |

More info on debugging [here](https://dev.twitter.com/cards/troubleshooting#display):

> ### My tweet is missing the image/video/summary text.
> 
> There are a number of possible reasons for this. Here are some suggestions and ways to troubleshoot:
> - Your Player Card has yet to be whitelisted. Please run your example URL through the Card Validator, and click the Request Approval button to begin the whitelist process.
> - Your website has a robots.txt that is blocking us from getting your Card metadata. To learn how to diagnose this case, click here.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/testpilot/issues/294

From the looks of my _gorgeous_ table above, we may need a Twitter account if we want Twitter card support.

**Comment by johngruen** [comment]
@pdehaan we have a twitter account https://twitter.com/FxTestPilot

**Comment by pdehaan** [comment]
> "Grab your parachute and get access to experimental Firefox features."

Do parachutes work in space?
/ducks

**Comment by pdehaan** [comment]
Closing. This currently looks great and works awesome (in dev).

<img width="1007" alt="card_validator___twitter_developers" src="https://cloud.githubusercontent.com/assets/557895/15556688/129e8770-2284-11e6-8737-7d90b3f0794f.png">
