### ISSUE TITLE
A few warnings when trying to validate Open Graph card support

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#911]
Re: https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Ftestpilot.dev.mozaws.net%2F

I'm getting a few warnings:

> ### Warnings That Should Be Fixed
> 
> | TYPE | MESSAGE |
> | --- | --- |
> | Extraneous Property | Objects of this type do not allow properties named 'twitter:title'. |
> | Extraneous Property | Objects of this type do not allow properties named 'twitter:description'. |
> | Extraneous Property | Objects of this type do not allow properties named 'twitter:url'. |
> | Extraneous Property | Objects of this type do not allow properties named 'twitter:image'. |
> | Share App ID Missing | The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog. |
> | Parser Mismatched Metadata | The parser's result for this metadata did not match the input metadata. Likely, this was caused by the data being ordered in an unexpected way, multiple values being given for a property only expecting a single value, or property values for a given property being mismatched. Here are the input properties that were not seen in the parsed result: 'twitter:title, twitter:description, twitter:url, twitter:image' |

**Comment by pdehaan** [comment]
More Open Graph docs: http://ogp.me/ (since I don't know nothing about Open Graph and this is _almost_ interesting).

Plus https://developers.facebook.com/docs/platforminsights/domains has some good info on setting up `fb:app_id`.

**Comment by pdehaan** [comment]
Leaving this one open. I'm still seeing the "Share App ID Missing" warning after our latest tweaks:

<img width="1038" alt="sharing_debugger_-_facebook_for_developers" src="https://cloud.githubusercontent.com/assets/557895/15556757/74bdbb92-2284-11e6-90b4-ca369bc0e2f9.png">

**Comment by ghost** [comment]
Maybe we could tie this to the Firefox facebook page?  Or just $RANDOM a new one every day? 🎋

**Comment by johngruen** [comment]
@pdehaan per [this](http://stackoverflow.com/questions/35066102/facebook-debugger-why-complaining-about-app-id-missing) we aren't an app and therefore don't need an app id.

PR-ing an og:url in #2375
