### ISSUE TITLE
Four Oh Four! header doesn't have a lot of contrast

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#916]
Found in https://testpilot.stage.mozaws.net/__version__ (3eef36e8365dce6693f5de2f8f9b903cf1a3b69b):

``` json
{ "build": "https://circleci.com/gh/mozilla/testpilot/450",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-05-24",
  "commit": "3eef36e8365dce6693f5de2f8f9b903cf1a3b69b" }
```

---
### Steps to reproduce:
1. Go to https://testpilot.stage.mozaws.net/robots.txt
2. Read it.
3. Weep.
### Actual results:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/15550398/23f8127a-2266-11e6-9b2b-d12d6b5c55e4.png)
**Figure 1:** https://testpilot.stage.mozaws.net/robots.txt (per 3eef36e8365dce6693f5de2f8f9b903cf1a3b69b)
### Expected results:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/15550493/7844fcda-2266-11e6-99f0-0997584ba7a0.png)
**Figure 2:** https://testpilot.firefox.com/robots.txt (per a729b09008914caeeb9357b29f52f40ebf55f60f)

**Comment by johngruen** [comment]
Fixed By #921
