### ISSUE TITLE
handle build and serving of addon

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/testpilot#92]
The addon should be auto-signed without problems by the AMO tools, so we should easily be able to replace the raw.github.com URL (which isn't served with the right mime-type) with an AMO link.

Assigning to @meandavejustice because he uploaded the addon originally and should have a pointer to the link.

**Comment by jaredhirsch** [comment]
This depends on https://github.com/mozilla/idea-town-addon/pull/22

**Comment by meandavejustice** [comment]
Still having trouble with this for some reason... after signing and trying to install I still get this error
![](http://i.imgur.com/CWRU6yv.png)

**Comment by meandavejustice** [comment]
Unfortunately we cannot link to AMO since our addon is unlisted. I tried testing to see if it would still work as hidden. But cannot switch visibility https://bugzilla.mozilla.org/show_bug.cgi?id=1122107

**Comment by jaredhirsch** [comment]
Yup, you're exactly right.

There's a bug open to find a way to promote idea town addons from the AMO 'unlisted' state to the 'hidden' state: https://bugzilla.mozilla.org/show_bug.cgi?id=1225536

**Comment by meandavejustice** [comment]
So my plan for this atm is to have a simple signing/packaging `npm script` in the addon called `deploy`. From our `gulpfile` we can build and move it into our `static` dir.

I'll need to do some investigation on hosting our own addon, via updates, access control etc...
@lmorchard how does this sound? Am I leaving anything out here?

**Comment by lmorchard** [comment]
Hmm, so I haven't had a change to play with `jpm sign` myself yet... Does that come back immediately with a signed add-on? Or do you have to wait for an email notification or something?

If it's an immediate thing, it would be cool to roll add-on build & signing into the scripts that build our Docker container for deployment. We're already running gulp in there to build the frontend JS.

If it waits on a notification, we'll probably have to keep manually building the add-on, keep it in a dist directory & copy it over during container build. Either that, or add a file upload field in the admin pages so we can update the add-on separately from site deployment (though that sounds like a bad idea)

**Comment by jaredhirsch** [comment]
@meandavejustice Helpful links for hosting add-ons:

The mime type for the xpi is `application/x-xpinstall`, from the [extension packaging page on mdn](https://developer.mozilla.org/en-US/Add-ons/Extension_Packaging#Making_an_extension_XPI). The mime type for update.rdf is documented on the [manifests page on mdn](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#updateURL), and can be any of `text/rdf`, `text/xml`, or `application/rdf+xml`. That manifests MDN page covers most of the stuff you'll need to know to get the rdf files together.

[MDN says](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign) that `jpm sign` does the signing, so, yay jpm. It also [looks like](https://github.com/mozilla-jetpack/jpm/pull/301) a PR landed last year to enable jpm to generate update.rdf files. Maybe give that a shot, and compare with the rdf files used by the [old search addon](https://github.com/mozilla/universal-search-addon/tree/master/templates).

Let me know if you have other questions or get stuck.
