### ISSUE TITLE
Don't ask to rate an addon that isn't activated

### ISSUE THREAD

**Issue by marco-c** [mozilla/testpilot#924]
I have `Tab Center` installed, but I'm not using it (it is disabled).
Test Pilot asked me to rate it.

**Comment by johngruen** [comment]
@marco-c we've made some pretty major changes to the add-on since this issue was filed. Have you seen it crop up recently? I'm inclined to close it.

**Comment by marco-c** [comment]
No, I haven't seen it in a while.
