### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#928]
Diff-ing between releases isn't difficult or impossible (see [2016-05-18...2016-05-24](https://github.com/mozilla/testpilot/compare/2016-05-18...2016-05-24)), but it may be better to have an auto generated CHANGELOG using something like [**conventional-changelog-cli**](https://github.com/conventional-changelog/conventional-changelog-cli); so we can quickly diff releases.

**Comment by lmorchard** [comment]
Personally, I'd rather work toward using a tool like [whatsdeployed](https://github.com/peterbe/whatsdeployed). We have a 2-week cadence now, but eventually I'd like to see us get to continual deployment. Changelogs don't make a lot of sense when you might be deploying a few times a day

**Comment by ghost** [comment]
We could be more verbose in https://github.com/mozilla/testpilot/releases and use that.
