### ISSUE TITLE
Define behavior for browsers other than desktop Firefox

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#93]
Edited: What should the landing page look like in browsers not eligible for Idea Town?

We might want to distinguish between old versions of Firefox, mobile Firefox, and every other browser.

---

I just noticed that I can log in using Chrome and it prompts me to install the add-on, which probably won't get me very far (not to mention a console error in Chrome):

> ### "Uncaught Error: Error connecting to extension null"

![idea_town](https://cloud.githubusercontent.com/assets/557895/10111514/69fb2826-6389-11e5-8f76-07d995738852.png)

**Comment by johngruen** [comment]
Well we should have a button, presumably one of these buttons

https://www.mozilla.org/en-US/styleguide/websites/sandstone/buttons/

Problem is, these are all painfully non-retina. Will cook up a replacement. Also need to figure out what query strings to pass in to the download link

**Comment by johngruen** [comment]
Also unfortunate, that site has zero code snippets :(

**Comment by johngruen** [comment]
This'll get fixed by #203, closing

**Comment by meandavejustice** [comment]
_bump_

**Comment by meandavejustice** [comment]
Just tested, this is still an issue. marking post-mozlando

**Comment by johngruen** [comment]
Here's the UX for this...
Click the button in the lower right to see the behavior
https://people.mozilla.org/~jgruen/test-pilot/
![screen shot 2016-02-29 at 12 18 46 pm](https://cloud.githubusercontent.com/assets/3323249/13402518/a9ecde22-dede-11e5-8d70-84262d74982a.png)

**Comment by johngruen** [comment]
@meandavejustice hey, maybe we could figure out the best way to do client detection here...I'm not sure what the prefered method is. I can implement the UI if you can get the detection part implemented.

**Comment by johngruen** [comment]
@meandavejustice alternately, find me a good tutorial and i can take a crack at it

**Comment by meandavejustice** [comment]
I think the simplest way to do this would just be to check the useragent

``` javascript
if (navigator.userAgent.toLowerCase().indexOf('firefox') > -1) {
  console.log('the user is using firefox')
} else console.log('the user is NOT using firefox')
```

we could also use something like [browser-detect](https://www.npmjs.com/package/detect-browser), but the above snippet would be faster.

**Comment by pdehaan** [comment]
FWIW, here was my experience today from trying to install a Chrome addon from Firefox today:

![postman_-_chrome_web_store_and_postman___supercharge_your_api_workflow_and_define_behavior_for_browsers_other_than_desktop_firefox_ _issue__93_ _mozilla_testpilot_and_embedly-proxy_dev_mozaws_net___version__](https://cloud.githubusercontent.com/assets/557895/13506702/35e25568-e134-11e5-988e-af61b7f3e44e.png)
