### ISSUE TITLE
Glitch in opening of tabs

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#931]
When I try and open a new tab, if I hover my mouse over the '+' and wait for the tab center to fully open, it will put the new tab on top of the old tab, but if I press the '+' while the tab center opening  animation is still playing, the new tab appears on the bottom. 
![ontop](https://cloud.githubusercontent.com/assets/12704804/15635179/672d504a-258c-11e6-817f-dd3088ac6d8e.PNG)
![onbottom](https://cloud.githubusercontent.com/assets/12704804/15635180/672f3f36-258c-11e6-991a-064725ff74f4.PNG)

**Comment by meandavejustice** [comment]
I've reopened on the [tab center bug list](https://github.com/bwinton/VerticalTabs/issues/313)
