### ISSUE TITLE
Please rate undefined

### ISSUE THREAD

**Issue by bnjbvr** [mozilla/testpilot#932]
Please see [screenshot](https://benj.me/pub/1464593506.png).

I'm using Ubuntu 15.10, Firefox Nightly 2016-05-25.

Only Activity stream is activated at the moment. I've enabled Universal Search at some point but disabled it later.

Please let me know if you need further information.

**Comment by ghost** [comment]
Just saw this today on Firefox Nightly 50.0a1 20160718081125 with Test Pilot 0.7.2-tag-2016-07-05 on Mac OS 10.11.6 Beta 15G26a. In case it matters, my Test Pilot environment is currently set to "Production" aka testpilot.firefox.com with Activity Stream and Universal Search activated, Tab Center deactivated.

**Comment by ghost** [comment]
Dupe of #1142
