### ISSUE TITLE
TypeError: can't define property "pingTimer": Object is not extensible

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#936]
Randomly spotted in Test Pilot Browser Console:

> TypeError: can't define property "pingTimer": Object is not extensible [[/addon/lib/metrics.js:85:22](https://github.com/mozilla/testpilot/blob/3eef36e8365dce6693f5de2f8f9b903cf1a3b69b/addon/lib/metrics.js#L85-L88)]

``` js
    this.pingTimer = setTimeout(
      () => this.maybePingTelemetry(),
      PING_CHECK_INTERVAL
    );
```

**Comment by pdehaan** [comment]
~~I also saw this, but not sure if it's related:~~ **UPDATE:** It's not, per https://github.com/mozilla/testpilot/issues/936#issuecomment-223344061

> TelemetryStopwatch: requesting elapsed time for nonexisting stopwatch. Histogram: "FX_PAGE_LOAD_MS", key: "null" [TelemetryStopwatch.jsm:297:0]

| WHAT | WHERE |
| --- | --: |
| `this.TelemetryStopwatchImpl.timeElapsed()` | TelemetryStopwatch.jsm:297 |
| `this.TelemetryStopwatchImpl.finish()` | TelemetryStopwatch.jsm:315 |
| `this.TelemetryStopwatch.finish()` | TelemetryStopwatch.jsm:192 |
| `TabsProgressListener.onStateChange()` | browser.js:4631 |
| `callListeners()` | tabbrowser.xml:494 |
| `_callProgressListeners()` | tabbrowser.xml:515 |
| `mTabProgressListener/<._callProgressListeners()` | tabbrowser.xml:564 |
| `mTabProgressListener/<.onStateChange()` | tabbrowser.xml:722 |
| `loadSourceFromURL()` | viewSource-content.js:349 |
| `loadSource()` | viewSource-content.js:313 |
| `viewSource()` | viewSource-content.js:244 |
| `receiveMessage()` | viewSource-content.js:131 |

![browser_console](https://cloud.githubusercontent.com/assets/557895/15729128/4b5811d4-2816-11e6-88e1-5d87696d885a.png)

**Comment by georgf** [comment]
The `TelemetryStopwatch` issue is a known separate issue and unrelated.
