### ISSUE TITLE
Cannot close tab

### ISSUE THREAD

**Issue by rpichot** [mozilla/testpilot#937]
For an unindentified reason one of my tab lost icon/label/close button

![capture](https://cloud.githubusercontent.com/assets/7021290/15742740/ad77509e-28b8-11e6-9e9f-cecd93c3b1b6.PNG)

When I reload it, or close it and reopen it, nothing change (keyboard shortcuts or by right clicking on the tab)

When I move it to a new window, the icon/label/close button reappear in the new firefox window. I can then move back this new tab into the original firefox window (yeah, workaround found :) )

**Comment by pdehaan** [comment]
@rpichot Thanks for the bug report!

This looks like a Tab Center specific issue, so I migrated it over to https://github.com/bwinton/VerticalTabs/issues/328 for better tracking.

Closing this issue in favor of the upstream Tab Center one.
