### ISSUE TITLE
Add robots.txt?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#943]
Not sure if we want to add a robots.txt in case we want to optimize spider behavior (or access to admin, although that's probably better tracked by #890).

Currently going to https://testpilot.firefox.com/robots.txt takes you to the 404 page.

**Comment by ghost** [comment]
Could start with /admin/ and build from there.  the heartbeat pages?  Either way, let's make sure we add it to the logging whitelist so it doesn't show up in our stats.

**Comment by ghost** [comment]
I don't think we need this anymore
