### ISSUE TITLE
Create place in experiment details to call out incompatable add-ons

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#944]
Some experiments collide with other add-ons. We should call these out on experiment details pages.

**Comment by pdehaan** [comment]
HttpFox seems to be incompatible (Ref: #796)

**Comment by ghost** [comment]
Let's do:

1) A standard place in the repositories for a list of incompatible add-ons
2) Something on the details page ( --> needs ux)

**Comment by johngruen** [comment]
@sevaan is on it

**Comment by sevaan** [comment]
Please find the UX attached. This warning box would appear only if:
- the experiment is active
- the user has conflicting Add-ons installed and **enabled**

This box would stack above other boxes (e.g. experiment is ending soon).

Clicking the link would open up the Add-ons manager in a new active tab.

![incompatible add-ons](https://cloud.githubusercontent.com/assets/473531/17982882/68ca49de-6acf-11e6-913b-27002c6cb467.png)
[Assets.zip](https://github.com/mozilla/testpilot/files/437887/Assets.zip)

**Comment by johngruen** [comment]
@chuckharmston wanna pick this up?

**Comment by ghost** [comment]
I was dragging my feet on any frontend bugs, waiting on the flat files patch to land, fwiw.

**Comment by johngruen** [comment]
cool

**Comment by johngruen** [comment]
We may need to make this apply to about config prefs as well, please see: 
https://github.com/mozilla/blok/issues/12

**Comment by chuckharmston** [comment]
I'm not in love with this. The big red box looks like an error message, and it won't apply whatsoever to large proportions of our users. The Test Pilot add-on can:
- Get a list of installed add-ons
- Read prefs
- Change prefs

We should just change prefs for the user (maybe with a callout if we do so), only display the incompatibility message if we know that the user has an incompatible add-on installed, and prevent installation in that event.

**Comment by johngruen** [comment]
@chuckharmston that's the point i think, we don't wanna show this to everybody

**Comment by johngruen** [comment]
@sevaan wants this iff

> the user has conflicting Add-ons installed and enabled

I agree, the red is a little brutal. let's start by getting it in there, and see if we can't soften it.

**Comment by chuckharmston** [comment]
Huh, sorry, I was reading the thread in email and everything but the mock in Sevaan's message got truncated as if it was quoted text.

**Comment by johngruen** [comment]
@chuckharmston, lets user $eol-light-orange as the background and $eol-orange as the border

**Comment by johngruen** [comment]
@chuckharmston can we close this guy?

**Comment by chuckharmston** [comment]
Closing with #1402
