### ISSUE TITLE
'Download' Icon Glitched

### ISSUE THREAD

**Issue by ghost** [mozilla/testpilot#947]
Whenever I download a file, it appears like this:
![frozen](https://cloud.githubusercontent.com/assets/12704804/15803337/6900eef8-2a8d-11e6-8ba9-9a00dc205915.PNG)
If I close and reopen Firefox it disappears, but re-downloading something will cause the glitch again.

**Comment by pdehaan** [comment]
@Qhuea Which Test Pilot add-ons do you currently have installed?

**Comment by ghost** [comment]
@pdehaan Tab Center

**Comment by ghost** [comment]
It happenned by me too without Test Pilot a few Nightlies ago, I don't have it anymore with the latest Nightly...

**Comment by ghost** [comment]
Judging by the last comment this is something that was in nightly and fixed now, so going to close this.  Thanks.
