### ISSUE TITLE
Dupai's establishment now a pretty interesting with Delta Airlines in for assistance

### ISSUE THREAD

**Issue by tommyunitedstates2** [mozilla/testpilot#948]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

If you're experiencing a bug in Test Pilot, please include the following information:

- [x] Operating system
- [x] Firefox build (Nightly, Developer Edition, Beta, Release)

---

If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:

- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by lmorchard** [comment]
wat? Seems like spam.
