### ISSUE TITLE
Share Survey Gizmo response ID with Telemetry

### ISSUE THREAD

**Issue by MattGrimes** [mozilla/testpilot#949]
We closed issue #829 in favor of this route. Each survey has a unique response ID that is generated at the time of creation. We should record this in Telemetry so that we can look at how attitudinal measures compare to actual usage.

If it looks like this is a challenge we could generate a random uuid in TxP that we pass into the survey as a url param.

**Comment by ckprice** [comment]
This was a moonshot added mid-sprint; moving to next cycle.

**Comment by ckprice** [comment]
Closing in favor of #1461.
