### ISSUE TITLE
None of the "sha384" hashes in the integrity attribute match the content of the subresource

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#950]
Ref: https://github.com/mozilla/testpilot/pull/945#issuecomment-223713540

Found in http://testpilot.dev.mozaws.net/__version__ (3b2838cf9a3b468e5dc13d4454ef936c584bdb75):

``` json
{
  "commit": "3b2838cf9a3b468e5dc13d4454ef936c584bdb75",
  "version": "",
  "source": "https://github.com/mozilla/testpilot",
  "build": "https://circleci.com/gh/mozilla/testpilot/490"
}
```

---

Looks like this was deployed to Pontoon prod! Now the only error I'm seeing in my console is:

> _None of the "sha384" hashes in the integrity attribute match the content of the subresource_

&mdash; via http://testpilot.dev.mozaws.net/experiments

It doesn't seem to tell me what the subresource in question is, but in in the very rare chance that this is useful, here's a full list of resources which specify an `integrity` attribute:

``` html
<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css"
    crossorigin="anonymous"
    integrity="sha384-APhs/OUouhH+ZbBANL3+7a5J1sVSYyfUhGxTWiDMkTuEIO5fXWZonzNEj+CagDB7">
<link rel="stylesheet" href="/static/styles/main.885355dc102e.css"
    integrity="sha384-vnDt+fGbk3oCVKyHvGrF3RYzC7h4WdAENt74SgaNvFkdfZxqkwt3lzgJ6gSPe/sP">

<script src="/wafflejs"
    integrity="sha384-5d9kZFKvlS6GZLFL9+S09Csf9ARSzUGjYKAEQtluyFoAQ0LfdjTfg1Em/BB0pxKU"></script>
<script src="/static/app/app.6191ebb52259.js"
    integrity="sha384-KBzwckljV1slIx2Ftb77wV/08khQLr5//2aRta9r9ZB+okaCNuBqDN431XzjkIce"></script>
<script src="https://pontoon.mozilla.org/pontoon.js"
    crossorigin="anonymous"
    integrity="sha384-OLBgp1GsljhM2TJ+sbHjaiH9txEUvgdDTAzHv2P24donTt6/529l+9Ua0vFImLlb"></script>
```

**Comment by pdehaan** [comment]
Google Chrome's DevTools Console says:

> [testpilot.dev.mozaws.net/:1] Failed to find a valid digest in the 'integrity' attribute for resource 'https://pontoon.mozilla.org/pontoon.js' with computed SHA-256 integrity 'MxSx4iT+DcJA/8qH80qqi5xAstRsUTvzINuALz/A0jw='. The resource has been blocked.

**Comment by lmorchard** [comment]
Looks like the external resource changed since I last hashed it:

``` bash
➜  testpilot git:(master) ✗ curl -s https://pontoon.mozilla.org/pontoon.js | openssl dgst -sha384 -binary | openssl base64 -A; echo
Wrfqhq3/nkU9KwCpKD8b55Aq0xMbUGEd7tETkuiRGhApLJ0QvusEhLBwta1OYdwi
```

That will happen in between our deployment windows, so I added [an admin override](http://testpilot.dev.mozaws.net/admin/constance/config/) for hashes. I just updated that on dev, and it looks like the error went away for me.

**Comment by lmorchard** [comment]
Also just updated [on stage](https://testpilot.stage.mozaws.net/admin/constance/config/), and will need to follow up on prod once the SRI feature makes it there.
