### ISSUE TITLE
testpilot.dev update.rdf points to production updateLink?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#955]
Not sure if any of this matters or not, but it looks potentially suspicious and crossing streams.

http://testpilot.dev.mozaws.net/static/addon/update.rdf returns some XML that looks [roughly] like this:

``` xml
...
<Description>
  <em:version>0.6.5-dev-4ce1eec</em:version>

  <em:targetApplication>
    <Description>
      <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
      <em:minVersion>38.0a1</em:minVersion>
      <em:maxVersion>43.0</em:maxVersion>
      <em:updateLink>https://testpilot.firefox.com/static/addon/addon.xpi</em:updateLink>
    </Description>
  </em:targetApplication>

  <em:targetApplication>
    <Description>
      <em:id>{aa3c5121-dab2-40e2-81ca-7ea25febc110}</em:id>
      <em:minVersion>38.0a1</em:minVersion>
      <em:maxVersion>43.0</em:maxVersion>
      <em:updateLink>https://testpilot.firefox.com/static/addon/addon.xpi</em:updateLink>
    </Description>
  </em:targetApplication>
</Description>
...
```

The 4ce1eec SHA checks out, since that was the latest commit, the `maxVersion` looks weird to me (if anything enforces that), plus the `em:updateLink` points to the **PRODUCTION** addon.xpi, even though I'm currently on http://testpilot.dev.mozaws.net.

Also, why are there TWO `em:targetApplication`s specified?

**Comment by chuckharmston** [comment]
> Also, why are there TWO `em:targetApplications` specified?

`ec8030f7-c20a-464f-9b0e-13a3a9e97384` is the application ID for Firefox, `aa3c5121-dab2-40e2-81ca-7ea25febc110` is for Firefox for Android.

**Comment by ghost** [comment]
We don't want to have updates coming off of multiple places.
