### ISSUE TITLE
Nothing seemed to start.

### ISSUE THREAD

**Issue by YoDaMa** [mozilla/testpilot#956]
- [ ] Operating system
- [x] Firefox build (Nightly, Developer Edition, Beta, Release)

The Test Pilot does not seem to really work at all. I've downloaded the addon, however nothing works when clicking and I can't activate any of the test. Each one I click on just takes me to a page that doesn't load.

**Comment by ckprice** [comment]
@YoDaMa thanks for the report! As we try to reproduce this, could you please add a bit more information?
- Does this just happen in the Release channel, or all builds?
- What OS are you using?
- Are you in private browsing, or do you have tracking protection on?
- What other add-ons do you have installed?

Thanks!

**Comment by YoDaMa** [comment]
Hrm strange now it works after restarting Firefox. I have onetab, adblockplus, Pocket, and ePub-Catalog as add-ons. I don't have private browsing on, and I am using Windows 10. However, the problem seems to be resolved. I am not sure why or what changed.

**Comment by ckprice** [comment]
Thanks! Let us know if anything else comes up.
