### ISSUE TITLE
CSP errors when using Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#962]
Found in http://testpilot.dev.mozaws.net/__version__ (107d86faf8177fefd564692ee20bf67420cd5aa9):

``` js
{
  version: "",
  commit: "107d86faf8177fefd564692ee20bf67420cd5aa9",
  build: "https://circleci.com/gh/mozilla/testpilot/503",
  source: "https://github.com/mozilla/testpilot"
}
```

---
### Steps to reproduce:
1. Open Google Chrome.
2. Open Developer Tools and select the Console tab.
3. Go to http://testpilot.dev.mozaws.net/privacy
### Actual results:

> [privacy:1] Refused to load the script `data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZl…07Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=` because it violates the following Content Security Policy directive: "script-src 'self' `http://*.mozilla.org https://*.mozilla.org http://*.mozilla.net https://*.mozilla.net http://*.google-analytics.com https://*.google-analytics.com https://apis.google.com`".

**Comment by pdehaan** [comment]
I can't reproduce the error message in Firefox, so maybe they just report differently.
I also can't reproduce on stage, but am not sure yet if that's because the changes haven't been uplifted, or if there's potentially some issue w/ dev being on HTTP and stage being on HTTPS.

**Comment by lmorchard** [comment]
Hmm, that's actually a super-suspicious data URL that CSP is designed to block. We don't use any on the site. Do you have any extensions running in Chrome? Those tend to have occasional issues in both Chrome & Firefox.

**Comment by pdehaan** [comment]
Ah, yeah, it may have been my uBlock or "Mark non-secure links". I can't reproduce the error if I switch to Chrome Private Browsing mode w/ no plugins active.
Sorry for the noise.

**Comment by lmorchard** [comment]
Naw, good to report & keep in mind for the inevitable future reports of this scenario
