### ISSUE TITLE
Cleanup npm run package and npm run sign commands

### ISSUE THREAD

**Issue by pdehaan** [mozilla/testpilot#967]
**DISCLAIMER:** I'm not very smart.

I'm trying to add **addons-linter** to the Circle-CI scripts (ref: #966), but I don't know where to add a hook yet.
Not sure if it should be an npm "postsign" or "postpackage" hook in [/addon/package.json](https://github.com/mozilla/testpilot/blob/master/addon/package.json), but it almost looks like the `npm run package` script does a lot of the same boilerplate as [/addon/bin/sign](https://github.com/mozilla/testpilot/blob/master/addon/bin/sign).

Something feels like we should move the shell scripting stuff from addon/package.json's "package" script to something in /addon/bin/package, and then modify the "sign" script in /addon/package.json scripts to do something like this:

``` js
"package": "./bin/package",
"sign": "./bin/update-version && ./bin/package && ./bin/sign"
   # or "./bin/update-version && npm run package && ./bin/sign"

```

That'd probably consolidate all the XPI generation+renaming+moving and update.rdf shuffling in a single place (/addon/bin/package) instead of having two [very different] code paths doing the same thing in two separate places.

Or not, what do I know. ¯\_(ツ)_/¯

**Comment by meandavejustice** [comment]
@pdehaan you should just add `addons-linter` to postsign for now. We should def take time to clean these commands up though, thanks for pointing this out.

**Comment by pdehaan** [comment]
@meandavejustice I have a PR submitted at #975, but happy to revise and set to `postsign` if it looks better.

**Comment by ghost** [comment]
@pdehaan anything else to do here?

**Comment by pdehaan** [comment]
> @pdehaan anything else to do here?

I don't think so. Let's close it.
