### ISSUE TITLE
Make 'Active' / Experiment started indicator more clear.

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#968]
User testing shows that users want to know when experiments start collecting data. We should do a better job indicating when an experiment has started as well as the correlation btwn experiment activity and metrics collection

**Comment by johngruen** [comment]
Two Changes:

Details Page:
 https://invis.io/Q77S1H6ZC#/169802286_Details_Page_-_Experiment_Active

Home Page:
https://invis.io/Q77S1H6ZC#/169825427_Home_Page_-_Brand_New_Experiment

**Comment by kaganjd** [comment]
Details Page is done, hopefully I'll get Home Page done today or tomorrow: https://github.com/kaganjd/testpilot/commit/b0deae955c21407f2f4e22d0a7e13a5476e8e8e9

**Comment by johngruen** [comment]
Hey @kaganjd can you assign your finished PR to me for review when you're ready? Thanks for helping out here!

**Comment by kaganjd** [comment]
will do @johngruen! tomorrow, for real. sorry it's taking longer than i expected.

**Comment by johngruen** [comment]
@kaganjd no sweat. Next Train doesn't get cut until next week anyway. If you have Sass questions, let me know!
