### ISSUE TITLE
Update install counts to be client-side only

### ISSUE THREAD

**Issue by ckprice** [mozilla/testpilot#970]
In the June usability study, users expressed some confusion over two things:
1. Count format lost its comma when clicked on.
2. Count increased more than 1 when they 'enabled'.

(1) was fixed in #852. (2) could happen if other users install/disable while on the experiment page. When the user clicks "Enable", the server will return a number that may look odd.

This bug is opened to update that interaction to only happen on the client, so this number only ever goes up or down only by 1. This goes slight against [some of the work done in past bugs](https://github.com/mozilla/testpilot/issues/583#issuecomment-215143250), so maybe we should discuss.

**Comment by lmorchard** [comment]
Then, ironically, we really will be lying about the number, which seems to be what the confusion implied. But it's all smoke & mirrors sometimes, so ¯\_(ツ)_/¯
