### ISSUE TITLE
TooManyTabs disappeared my tabs

### ISSUE THREAD

**Issue by wryker** [mozilla/testpilot#976]
Thank you for contributing to Test Pilot!

Please use this form to report Test Pilot specific issues.

All of my tabs have disappeared. I had multiple layers of tabs stored using TooManyTabs. TooManyTabs is still present but all of my stored/saved tabs are gone!

If you're experiencing a bug in Test Pilot, please include the following information:
- [ ] Operating system
- [ ] Firefox build (Nightly, Developer Edition, Beta, Release)

---

If you think you've found an issue with one of the experiment add-ons, please file an issue in the appropriate repo below:
- Activity Stream:   https://github.com/mozilla/activity-stream/issues/new
- Tab Center:        https://github.com/bwinton/VerticalTabs/issues/new
- Universal Search:  https://github.com/mozilla/universal-search/issues/new

**Comment by ghost** [comment]
This was reported at https://github.com/bwinton/VerticalTabs/issues/234

Thanks!
