### ISSUE TITLE
Stabilize user count so it only updates on install/uninstall and page refresh

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#980]
Async changes to user count are confusing. We should back out asynchronous updates to the ui and simply increment or decrement based on user installs and unininstalls. Might be nice to add a pop animation to the number when we change it as well.

**Comment by johngruen** [comment]
@meandavejustice

**Comment by pdehaan** [comment]
Ref: #970

**Comment by johngruen** [comment]
@pdehaan yeah looks like this is a dupe.
