### ISSUE TITLE
Change "Leave Test Pilot" to "Uninstall Test Pilot"

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#986]
(in the settings menu)

**Comment by johngruen** [comment]
also in that modal

**Comment by pdehaan** [comment]
Also in [/legal-copy/terms-of-use.md#termination](https://github.com/mozilla/testpilot/blob/8d481518f501d3a9197cfe02ba6af3403b40db24/legal-copy/terms-of-use.md#termination):

> _"If at any time, you decide you no longer wish to participate in Test Pilot, you may deactivate your Test Pilot account by visiting https://testpilot.firefox.com, signing in using your Firefox Account, clicking the "Settings" button, and clicking **"Leave Test Pilot"**."_
