### ISSUE TITLE
"File an Issue" is hard to find

### ISSUE THREAD

**Issue by mcomella** [mozilla/testpilot#987]
"File an issue" takes many clicks to find:
1. click the Test pilot add-on icon in the toolbar
2. click an experiment
3. hit the "..." menu
4. click "File an Issue".

3 is particularly unintuitive. fwiw, a few weeks ago, I found a bug in universal search and gave up trying to file an issue for it.

I'd recommend either:
- Including "File an issue" in the menu from the Test Pilot add-on icon in the toolbar
- Making "File an issue" an obvious item on each experiment page

**Comment by pdehaan** [comment]
I agree. I'd vote for adding the "File an Issue" in the footer, so it's available everywhere. I currently noticed this on Chrome where you get prompted to download Firefox to install the add-on, so nowhere on that page is there any link to our GitHub repo.

But, for what it's worth, we did add a "Bug Reports" link to each experiment details page which has a link to each experiment's GitHub repo's "File an Issue" page:

<img width="337" alt="firefox_test_pilot_-_tab_center" src="https://cloud.githubusercontent.com/assets/557895/16110495/ee72a650-33a5-11e6-9f2b-efb33c3f14cd.png">

**Comment by johngruen** [comment]
@mcomella hey! we're changing around the way settings work in the next couple of trains. Also, @pdehaan how were you able to log in on chrome?

**Comment by pdehaan** [comment]
@johngruen I can't log in on Chrome, but Chrome prompts me to download the Firefox browser, and nowhere on that page do we show the "..." navigation, with the link to GitHub.

**Comment by johngruen** [comment]
@pdehaan: wontfix your problem

**Comment by johngruen** [comment]
@mcomella, gonna close this in favor of #984. we don't necessarily want to drive people to github, b/c we're not targeting techincal users, but changing the '...' to 'settings' will make the pref a bit more accessible.
