### ISSUE TITLE
Can't submit feedback for Universal Search

### ISSUE THREAD

**Issue by arthur-e** [mozilla/testpilot#989]
- Operating system: Ubuntu GNU/Linux 14.04
- Firefox build: Firefox 47.0 (Stable/Release?)

---

I assume the issue is with the Test Pilot website, not with Universal Search.

After filling out [the feedback form](https://qsurvey.mozilla.com/s3/universal-search?ref=givefeedback&experiment=Universal%20Search&), regardless of which of the two bottom radio selections I make, I click "Next" and nothing happens.

**Comment by johngruen** [comment]
hey @aurthur-e are you using any ad blockers? if so which ones, and if you know, which block lists are they using?

**Comment by arthur-e** [comment]
I do have Ghostery installed but no external scripts are detected on the feedback page (as I'm looking at it now). I just tried to submit feedback on Firefox 47.0 and Ubuntu 16.04 (different OS, different machine) and it worked just fine without disabling Ghostery.

**Comment by ghost** [comment]
Thanks.  I just tried this with uMatrix on and it also worked on ubuntu.
