### ISSUE TITLE
Switch to built-in Firefox APIs for managing experiment add-ons?

### ISSUE THREAD

**Issue by lmorchard** [mozilla/testpilot#990]
So, it sounds like there are going to be WebIDLs for AMO to manage add-ons. Most of the reason our bootstrap add-on exists is to expose a few AddonManager APIs to web content on testpilot.firefox.com. Maybe we can get whitelisted for these new APIs for AMO and delete most of our bootstrap add-on code?

This needs follow up & details filled in.

**Comment by lmorchard** [comment]
#1223 solves / supersedes this issue

**Comment by ghost** [comment]
good call
