### ISSUE TITLE
Add install counts to the homepage

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#995]
Sharon's UR strongly suggests that social proof is a big factor for user trust. Let's add install count to the landing page view to help entice users.

**Comment by johngruen** [comment]
<img width="1211" alt="screen shot 2016-06-20 at 6 57 52 pm" src="https://cloud.githubusercontent.com/assets/3323249/16203357/256bbea4-371a-11e6-9c81-6dd7ea9fdb03.png">

A few notes:

The user count should be something like

```
font-size: 14px;
color: #a2a2a2;
margin: 0;
```

The `experiment-information` div should be flexed using something like: 

```
@include flex-container(column, stretch, flex-start);
```

~~Make sure the `experiment-actions` div is removed (so as not to add extra padding or height). Note that this div still needs to exist on the logged in versions of these boxes.~~

Control buttons are now stripped out...see new ux spec:

**Comment by lmorchard** [comment]
This looks done via PR #1069

**Comment by pdehaan** [comment]
Verified on stage:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/16923818/19f4f7c6-4cd1-11e6-9d36-6a0931238784.png)

``` js
{
  version: "2016-07-15",
  build: "https://circleci.com/gh/mozilla/testpilot/612",
  commit: "e66c1d60d2705b87a98f663312b779d975bc99af",
  source: "https://github.com/mozilla/testpilot"
}
```
