### ISSUE TITLE
Ensure that all surveys have user-facing titles; avoid marketing jargon like “sentiment”

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#999]

**Comment by johngruen** [comment]
@sharonbautista

**Comment by sharonbautista** [comment]
Turns out I don't have access to the TxP surveys. I reached out to Rob Rayborn last week and just followed up again. As soon as I get admin access, I can make the changes.

**Comment by johngruen** [comment]
@rayborn could you give @sharonbautista access to our SG account. She wanted to make small adjustments to grammar and language in the surveys.

also #1000

**Comment by ghost** [comment]
Until we decided on a cohesive naming strategy, I've simply removed the page titles.  The UX is still understandable, and the user still has the test pilot logo / status bar to provide a nice framing / status.

We can revert this if/when we want some new page names.  @sharonbautista - the option is in Style > Text > Show page titles.
